### ISSUE TITLE
可以直接引导硬盘上的iso吗？

### ISSUE THREAD

**Issue by sonichy** [ventoy/Ventoy#10]
U盘引导成功，但是把ISO从硬盘复制到U盘太慢了，硬盘上有，复制到U盘启动是多余的步骤。

**Comment by ventoy** [comment]
在Ventoy 2.X 版本有规划这种形式， U盘里只放1个启动器，ISO文件可以放在U盘或者其他地方。 当前1.X版本还不支持。

**Comment by sout233** [comment]
我觉得移动硬盘和u盘有着相同之处，希望下一个版本可以支持移动硬盘安装

**Comment by ventoy** [comment]
@sonichy @sout233  
Ventoy 1.0.66 版本开始支持启动本地硬盘中的 ISO/WIM/VHD(x)/IMG/EFI 文件
https://www.ventoy.net/en/doc_news.html

**Comment by sonichy** [comment]
我觉得设置搜索路径更好，一个个创建很麻烦，数量很多的话更麻烦，自动化的刚需。

**Comment by sonichy** [comment]
下一步设计不分区常驻硬盘启动。
