### ISSUE TITLE
[issue]: ventoy usb detect but not working this msg will show me "selected boot image did not authenticate" I have 2-3 desktop and its working properly....

### ISSUE THREAD

**Issue by Soumya8989** [ventoy/Ventoy#1008]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1..0.46

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI

### Partition Style

MBR

### Disk Capacity

32GB

### Image file checksum (if applicable)

Yes.

### What happened?

A bug happened !.
### selected boot image did not authenticate 
![IMG_20210718_141412](https://user-images.githubusercontent.com/57490665/126061456-cb6c7a77-dfc8-47f7-a4ca-8df054c22be1.jpg)
![IMG_20210718_141420](https://user-images.githubusercontent.com/57490665/126061461-a54d3852-85a1-45d0-9ea1-ed5c88a31536.jpg)

**Solution:-** ??? 

_I'm big fan of ventoy owner and developers.._
I Am Also A Devloper In Node JS.

**Comment by ventoy** [comment]
It's something about the secure boot. You have 2 choice:
1. Disable the secure boot option in your BIOS and retry.
2. When you install Ventoy, enable the `secure boot support` option and follow: https://www.ventoy.net/en/doc_secure.html

**Comment by Soumya8989** [comment]
> It's something about the secure boot. You have 2 choice:
> 
> 1. Disable the secure boot option in your BIOS and retry.
> 2. When you install Ventoy, enable the `secure boot support` option and follow: https://www.ventoy.net/en/doc_secure.html

I was already trying to disable the secure boot option and rry again but still happening

**Comment by Soumya8989** [comment]
> > It's something about the secure boot. You have 2 choice:
> > 
> > 1. Disable the secure boot option in your BIOS and retry.
> > 2. When you install Ventoy, enable the `secure boot support` option and follow: https://www.ventoy.net/en/doc_secure.html
> 
> I was already trying to disable the secure boot option and try again but still happening

Thanks Problem Solved...

**SOLUTION:-** First do disable secure boot than enable legacy mode in your system configuration in your laptop then try its work for me
