### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [ventoy/Ventoy#101]
[An extra null pointer check is not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [vtoydm_get_img_map_data](https://github.com/ventoy/Ventoy/blob/05a1b863a66bf72b26e5d87570c4e0e61b9736cd/VtoyTool/vtoydm.c#L120 "vtoydm_get_img_map_data function")
- [vtoydump_main](https://github.com/ventoy/Ventoy/blob/ad9a031092f1d953d10bcf6ec77cb2fa1fc2c103/VtoyTool/vtoydump.c#L553 "vtoydump_main function")

**Comment by ventoy** [comment]
The check in vtoydm_get_img_map_data maybe needed when malloc return NULL.
