### ISSUE TITLE
[Issue]: Can't boot anything on AMD laptop

### ISSUE THREAD

**Issue by Willy-JL** [ventoy/Ventoy#1010]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.47

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### What happened?

Can't manage to boot anything on my machine.
I used 2 laptops and I'll refer to them like this:
 - Huawei:
   - Huawei Matebook D14 2020 IIRC
   - AMD Ryzen 5 3500U
   - No discrete GPU
   - Seemingly only UEFI support, couldn't find any Legacy switch in BIOS
   - Secure boot always disabled
 - Alienware:
   - Alienware 13 R2, can't remember the year
   - Intel Core i7 6500U
   - NVidia GeForce GTX 960M
   - Always boot in Legacy since the Windows install is on MBR but can also boot UEFI
   - Secure boot always disabled

<br>

<br>

Ok, so I tried with 2 ISOs:
 - Latest Deepin live installer (downloaded with torrent link from official website):
   - Huawei:
     - Ventoy was just freshly installed with above version, I hadn't touched the table settings so I'm guessing it set it up as MBR
     - Ventoy boots fine, I select the only ISO on it (Deepin)
     - Things look like they're loading, I then get a glowing Deepin logo as if it was still loading but that never goes anywhere
     - Shrugged it off and burnt the ISO directly onto another USB and it worked flawlessly
     - Didn't end up testing on Alienware
 - Latest GParted live environments (from official website):
   - Huawei:
     - Boot up Ventoy
     - Selecting ISO goes fine
     - I get to GParted's GRUB and I can navigate it, I select first default option (also tried a few other settings though, same results as the first try)
     - Stuff looks like it's loading
     - I see [this](https://media.discordapp.net/attachments/745422936743084032/867186914967683102/image0.jpg) on screen, nothing happens for next 5 minutes
     - Start to notice a pattern
     - Both amd64 and i686 GParted versions give same results
     - Try formatting Ventoy drive and reinstalling with GPT table setting
     - Same results on all versions
   - Alienware:
     - All goes fine
     - GParted loads up fine as it should

<br>

<br>

My pitch is it's something to do with the AMD processor, but what do i know... please help me figure this out, I really could use this fantastic piece of software!

**Comment by STPKITT** [comment]
In the meantime something must've have changed for the worse on Ventoy or Lenovo since I had this issue today with a brand new ThinkPad L16 with Ryzen CPU. I bought it without any pre-installed OS. I always only got the non-blinking white cursor, nothing else. Secure Boot was disabled on the machine btw.
