### ISSUE TITLE
Cannot change resolution in text mode

### ISSUE THREAD

**Issue by Silexium** [ventoy/Ventoy#1013]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.47

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64GB [Kingston DT100G3]

### What happened?

The resolution in text mode cannot be changed. GRUB's resolution will always remain as 1024x768 even if "gfxmode" is set to a custom resolution (e.g. 1920x1080). Also, switching to graphics mode or changing resolutions when "display_mode" is set to "CLI" gives off a "not a regular file" error. Changing the resolution using the F5 Tools menu makes the font weird & gives the "not a regular file" error when any option is selected. The same is true if the resolution is set using the command-line via "set gfxmode='resolution'". Here's my "ventoy.json" file:

{
    "control": [
        { "VTOY_DEFAULT_MENU_MODE": "1" },
        { "VTOY_TREE_VIEW_MENU_STYLE": "1" }
    ],
    "theme": {
        "file": "/ventoy/themes/Ventoy/theme.txt",
        "gfxmode": "1920x1080",
        "display_mode": "CLI",
        "ventoy_left": "5%",
        "ventoy_top": "95%",
        "ventoy_color": "#4fb9fe",
        "fonts": [
            "/ventoy/themes/Ventoy/terminus-12.pf2",
            "/ventoy/themes/Ventoy/terminus-14.pf2",
            "/ventoy/themes/Ventoy/terminus-16.pf2",
            "/ventoy/themes/Ventoy/terminus-18.pf2",
            "/ventoy/themes/Ventoy/ubuntu_regular_17.pf2",
            "/ventoy/themes/Ventoy/ubuntu_regular_20.pf2"
        ]
    },
    "menu_alias": [
        {
            "image": "/Windows/en_windows_10_consumer_editions_version_21h1_x64_dvd_540c0dd4.iso",
            "alias": "Windows 10 21H1 x64"
        },
        {
            "image": "/Windows/en_windows_10_enterprise_ltsc_2019_x64_dvd_5795bb03.iso",
            "alias": "Windows 10 LTSC 2019 x64"
        },
        {
            "image": "/Windows/en_windows_8.1_with_update_x64_dvd_6051480.iso",
            "alias": "Windows 8.1 x64"
        },
        {
            "image": "/Windows/Win7_AIO_SP1_English_x64.iso",
            "alias": "Windows 7 All-in-One SP1 x64"
        },
        {
            "image": "/Windows/HBCD_PE_x64.iso",
            "alias": "Hiren's BootCD PE 1.0.2 x64"
        },
        {
            "image": "/Linux/elementaryos-5.1-stable.20200814.iso",
            "alias": "elementaryOS 5.1.7 Hera x64"
        },
        {
            "image": "/Linux/ubuntu-21.04-desktop-amd64.iso",
            "alias": "Ubuntu 21.04 Hirsute Hippo x64"
        },
        {
            "image": "/Linux/kubuntu-21.04-desktop-amd64.iso",
            "alias": "Kubuntu 21.04 Hirsute Hippo x64"
        },
        {
            "image": "/Linux/xubuntu-21.04-desktop-amd64.iso",
            "alias": "Xubuntu 21.04 Hirsute Hippo x64"
        },
        {
            "image": "/Linux/linuxmint-20.2-cinnamon-64bit.iso",
            "alias": "Linux Mint 20.2 Uma (Cinnamon) x64"
        },
        {
            "image": "/Linux/pop-os_21.04_amd64_nvidia_6.iso",
            "alias": "Pop!_OS 21.04 x64"
        },
        {
            "image": "/Linux/systemrescue-8.03-amd64.iso",
            "alias": "System Rescue CD 8.03 x64"
        },
        {
            "image": "/Linux/fossapup64-9.5.iso",
            "alias": "Puppy Linux 9.5 x64"
        },
        {
            "image": "/Linux/finnix-122.iso",
            "alias": "Finnix 122 x64"
        },
        {
            "image": "/memtest86-pro-usb.img",
            "alias": "MemTest86 Pro 9.0"
        }
    ],
    "image_list": [
        "/Windows/en_windows_10_consumer_editions_version_21h1_x64_dvd_540c0dd4.iso",
        "/Windows/en_windows_10_enterprise_ltsc_2019_x64_dvd_5795bb03.iso",
        "/Windows/en_windows_8.1_with_update_x64_dvd_6051480.iso",
        "/Windows/Win7_AIO_SP1_English_x64.iso",
        "/Windows/HBCD_PE_x64.iso",
        "/Linux/elementaryos-5.1-stable.20200814.iso",
        "/Linux/ubuntu-21.04-desktop-amd64.iso",
        "/Linux/kubuntu-21.04-desktop-amd64.iso",
        "/Linux/xubuntu-21.04-desktop-amd64.iso",
        "/Linux/linuxmint-20.2-cinnamon-64bit.iso",
        "/Linux/pop-os_21.04_amd64_nvidia_6.iso",
        "/Linux/systemrescue-8.03-amd64.iso",
        "/Linux/fossapup64-9.5.iso",
        "/Linux/finnix-122.iso",
        "/memtest86-pro-usb.img"
    ],
    "menu_class": [
        {
            "key": "Win",
            "class": "windows"
        },
        {
            "key": "windows",
            "class": "windows"
        },
        {
            "key": "HBCD",
            "class": "recovery"
        },
        {
            "key": "kubuntu",
            "class": "kubuntu"
        },
        {
            "key": "lubuntu",
            "class": "lubuntu"
        },
        {
            "key": "xubuntu",
            "class": "xubuntu"
        },
        {
            "key": "ubuntu-mate",
            "class": "linux"
        },
        {
            "key": "ubuntu-budgie",
            "class": "linux"
        },
        {
            "key": "ubuntu",
            "class": "ubuntu"
        },
        {
            "key": "pop-os",
            "class": "pop-os"
        },
        {
            "key": "manjaro",
            "class": "manjaro"
        },
        {
            "key": "debian",
            "class": "debian"
        },
        {
            "key": "arch",
            "class": "arch"
        },
        {
            "key": "linuxmint",
            "class": "linuxmint"
        },
        {
            "key": "elementary",
            "class": "elementary"
        },
        {
            "key": "Fedora",
            "class": "fedora"
        },
        {
            "key": "openSUSE",
            "class": "opensuse"
        },
        {
            "key": "Solus",
            "class": "solus"
        },
        {
            "key": "KNOPPIX",
            "class": "recovery"
        },
        {
            "key": "pup",
            "class": "recovery"
        },
        {
            "key": "systemrescue",
            "class": "recovery"
        },
        {
            "key": "finnix",
            "class": "recovery"
        },
        {
            "key": "memtest",
            "class": "memtest"
        }
    ]
}

**Comment by elvary** [comment]
do you still have this issue? does it look low display resolution like this?
![PXL_20220826_194320609.MP.jpg](https://user-images.githubusercontent.com/69122770/187018711-08177246-fa3c-4a4e-9b9f-cd9ed250cbed.jpg)
![PXL_20220826_193455511.MP.jpg](https://user-images.githubusercontent.com/69122770/187018733-a40fa109-e6b1-46ac-a621-7df56e13c735.jpg)
