### ISSUE TITLE
[issue]: 安全启动支持相关问题

### ISSUE THREAD

**Issue by 18030600277** [ventoy/Ventoy#1017]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.47

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

64GB

### Image file checksum (if applicable)

Yes.

### What happened?

请教一个问题，，我经常批量安装机器，全部是安全启动，导致我每台机器 都要 注册秘钥 才能进我的U盘，，有没有什么办法 可以 自动注册秘钥，，不用手动注册，。
![secure_cn](https://user-images.githubusercontent.com/60255199/126956484-8497b49f-91ed-49d6-822d-5dfe8f98a583.png)

**Comment by ventoy** [comment]
这个没办法。

**Comment by 18030600277** [comment]
> 这个没办法。

哦，知道了 谢谢，。。
