### ISSUE TITLE
[issue]: Iso windows 7 and drivers when i try to install

### ISSUE THREAD

**Issue by rakantoh** [ventoy/Ventoy#1019]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

latest versions of ventoy

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

32gb

### Image file checksum (if applicable)

No.

### What happened?

I have a windows 7 sp1 iso with updates (only official updates) made by me, if i install win7 directly from the usb (creating the correct format of usb and putting the files, not the iso in the usb) i can install win 7 from the usb 3.0 port, the installer says me that a driver is missing, but i have the driver in the hdd and i search for it and then i selected it, and the driver is installed and i can continue with the installation of win7 without problem, when i started to use ventoy, i can been do this, but in latest versions of ventoy, i try to do this same steps but the driver is not installed, and i cant continue with the installation of win 7. I already try to format the usb in mbr and gpt, and with secure boot enabled and disabled, with different recent versions of ventoy, with the same result, but with a old version of ventoy (1.0.06) this steps works perfect.
Please fix this issue, for me ventoy is the best and most simple tool to boot multiple SO from iso file, im not want change of tool. Thanks.

**Comment by rakantoh** [comment]
UPDATE: The issue when i try to install win7 is present with usb 2.0 too. Please fix this soon.

**Comment by steve6375** [comment]
Please try ventoy 1.0.6 with same pc and same drive today?

**Comment by rakantoh** [comment]
> Please try ventoy 1.0.6 with same pc and same usb drive today?

v1.0.6 or **1.0.06**?

**Comment by rakantoh** [comment]
UPDATE: The issue is present from version 1.0.29 to the latest version, from version that add support for special characters in the name of the iso. I mantain the name of the iso without any special char (no spaces, no "-", only letters and numbers) but the issue persist. I dont know if the problem appears with other iso or SO, at least for me with iso of win7 the issue appears.

**Comment by steve6375** [comment]
With 1.0.47, what exactly happens? Please describe exactly what you see.
1. It boots to ISO and runs Setup.exe
2. You get to next screen
3. You choose Install option
4. You see an error message about a 'missing device driver for CD/DVD' ?  EXACT ERROR MESSAGE or screenshot?
5. You press SHIFT+F10 to get to command console
6. You use DIR command and can see the contents of the Ventoy USB drive listed
7. You attempt to load a driver (what exact driver? How do you load it? Where is the driver located?)
8. etc.
i.e. give exact steps with exact details

**Comment by rakantoh** [comment]
i already explained in first post what happened, and again, when i install win 7 from dvd or usb 2.0 (in a usb correctly prepared), i can install it normally, if i use usb 3.0, i must search and install the drivers for the usb 3.0, i have this drivers, and i made this steps multiple times, without and with ventoy, after the installer install and recognize usb 3.0, i can continue with the installation of win7 normally, this changed from ventoy version 1.0.29 where usb 2.0 is not recognized and usb 3.0 is not installed following the steps. In the latest version is the same issue, not recognize usb 2.0 and usb 3.0 is not installed, when the procedure to install 3.0 is verified by me multiple times and is always success.

**Comment by steve6375** [comment]
You have merely repeated the same words as before.
Windows 7 only has old usb 2 chipset drivers.
Win7 does not have usb chipset drivers for modern usb 2 or usb 3 chipsets.
So it depends on what mainboard chipset you have.
When you boot to windows 7 setup it only uses drivers in winpe. It has nothing to do with ventoy or any boot manager that is used.
You also need to be specific when you say 'not recognise usb 2' - do you mean usb 2 port or usb 2 drive, or usb 2 drive in a usb 3 port or usb 3 drive in a usb 2 port.
You still have not described the error message, what driver you install, where is the driver located (can't be on the usb drive as that is not accessible, can't be on internal HDD as that may be blank or formatted???).
So, to repeat, are you testing the same pc with the same iso and the same usb drive and the same usb port each time you test ventoy versions? A different pc has a different usb chipset and so win7 may or may not see the usb 2 ports and usb 2 drives, depending on how different the chipset registers are.

**Comment by rakantoh** [comment]
Again, i have been doing this proccess multiple times before. Before, i formatted my usb (Kingston DT Elite 3.0 32GB) and mark the partition as active, and put the files of installer of win7 in the usb, and from usb 2.0 PORT i can install win7 without any problem, and from usb 3.0 PORT, the installer shows me a message that say that a driver is missing, i click in the browse button, and search and select the usb 3.0 PORT driver and the installer install and recognize the usb 3.0 PORT, then i can continue with the installation of win7 from usb 3.0 PORT without any problem. Now, when i started to use ventoy, i can follow this EXACT steps with the same results and with the same ISO (same files used earlier), but this changed from the version 1.0.29 of ventoy, where none of this steps, when previously worked perfect, as i described, now won´t works, this from ventoy v1.0.29 to the latest (1.0.47), Adittional, yesterday, i installed win7 with ventoy 1.0.28 from my Kingston DT Elite 3.0 32GB in my usb 3.0 PORT without problems, and i try with ventoy v1.0.29 and ventoy 1.0.47 and appears the issue reported and described. 
Is now clear? or is neccessary more clear/specific?

**Comment by steve6375** [comment]
Are you talking about the same PC in each case? i.e. you are always testing with the same PC?
What exact model of PC are you installing to?
You say you browse to the USB 3 port driver - but where is this driver? What drive and folder is this driver in? What is this driver?
When you use Ventoy 1.0.47 and select this driver - what do you see (any error message?).

When you boot to Windows 7 Setup - before you install any drive, if you press **SHIFT+F10** you will see the command console.
If Windows 7 has the correct USB 2 drivers, you should be able to see a USB drive in a USB 2 port (e.g. by using DIR command you can find and list files on the Ventoy USB drive).
If you boot with 1.0.28 can you see the USB drive in USB 2 port (with no driver needed)?
If you boot on same PC using same ISO with 1.0.47 and use SHIFT+F10, can you see the USB drive in a USB 2 port?

**Comment by rakantoh** [comment]
This is the last time that i answer you, i already has been very clear to the issue/error.
YES, the test was made in the same pc's. In the two pc's i obtain the same results. 
The only answer that i respond is this: When i use ventoy 1.0.29 or newer version of ventoy, i browse the usb 3.0 drivers and i follow the steps described before, but the port is not installed/recognized, with the usb 2.0, the usb 2.0 ports drivers is present by default in the win7 iso, at least the drivers of the test pc's, but is not recognized. With ventoy 1.0.28 or old versions, the usb 2.0 is recognized normally and i can install win7 without any special steps or additional installation, and in the usb 3.0 ports i browse the drivers of the usb 3.0 ports and the installer install it and i can continue install win 7 without any special or additional steps, only the steps described before.
I am very clear with the steps, if you are a contributor or creator/cocreator of ventoy, is not my problem if you cant or not want to solve the problem or if you not trust in my report. I already reported the issue, is in the hands of the creator/cocreator/contributers discover more about the issue and solve it, not in my hands. 
Thanks, and fix the issue soon. At least for now, i will continue use ventoy v1.0.28 or another software that doing the same work.

**Comment by steve6375** [comment]
It is difficult to discover more about the problem if you refuse to answer my questions. Without more details I cannot reproduce the issue and I cannot think of any reason why using a different version of Ventoy would affect Windows not being able to detect the USB 2 port+USB 2 drive, since it would be using the same Windows 7 drivers which should not be affected by anything to do with Ventoy. Maybe someone else can help you...

**Comment by rakantoh** [comment]
i already explain clearly what steps i follow, i dont know what is the difficult to understand the steps that i described, and yes, exist a reason, described in the first post, where the issue appears, from ventoy version 1.0.29, the iso images can have any name with spaces and special chars, versioin 1.0.28 and older the iso can´t have special chars and spaces in the names. Maybe this help to the issue appears, maybe not, in any case, is in the hands of the developers/contributers detect and fix the issue, not in the hands of the users, if you as contributer/developer cant detect and fix the issue, then this program have a very poor developers.

**Comment by 18iteration** [comment]
How pompous and arrogant does a human have to be to reach this level of ungratefulness is beyond my comprehension.
First you refuse to listen to steved, then you proceed to thumb down and arrogantly (passively) insult him.... The only person willing to help you. I think ventoy is not your biggest issue buddy.

**Comment by rakantoh** [comment]
> How pompous and arrogant does a human have to be to reach this level of ungratefulness is beyond my comprehension.
> First you refuse to listen to steved, then you proceed to thumb down and arrogantly (passively) insult him.... The only person willing to help you. I think ventoy is not your biggest issue buddy.

I expect that you read ALL post and replies, first, i explained multiple times the issue, clearly, and the only responses that i received was more questions and no some vestige of an solution, second, i suppose that you are an user too, you as user of ventoy, ¿is in your hands fix/repair the issue/problem of the software? i think that is not your responsability, again, is in the hands of the developers fix the problems, not in hands of the user, the function of report an issue is to announce to the developers the existence of an some problem; third, in any moment (read ALL post and replies again), i insulted steve, i was very clear with the steps that i done, multiple times; fourth, if a developer of a program dont care the problem of its own program, then the program have very poor support; and fifth, i use ventoy for the versatility and easily use, i like ventoy, and i appreciate the program, but again, a good program with bad support convert the program in a bad program.

I expect that you think more in ALL implications described and more analysis in both point views of the users, instead of judge without any valid argument. Good day Buddy.

**Comment by rakantoh** [comment]
Since version 1.0.49, the issue that i reported was resolved. i proceed to close the issue.
