### ISSUE TITLE
[issue]: arch based iso cant boot

### ISSUE THREAD

**Issue by u0a266** [ventoy/Ventoy#1021]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.47

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

16GB

### Image file checksum (if applicable)

Yes.

### What happened?

An arch-based distribution fails to boot
bootmode: uefi
If I boot with bios bootmode, it boots fine
```bash
Mounting '/dev/disk/by-label/ARCH_202107'
Waiting 30 seconds for device /dev/disk/by-label/ARCH_202107 ...
ERROR: '/dev/disk/by-label/ARCH_202107' device did not show up after 30 seconds...
   Falling back to interactive prompt
   You can try to fix the problem manually, log out when you are finished
sh: can't access tty; job control turned off
```

Edit: im sorry 
im using custom archiso

**Comment by ventoy** [comment]
The ISO download link?

**Comment by u0a266** [comment]
https://github.com/u0a266/myarch/releases/tag/2021.07.25

**Comment by ventoy** [comment]
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/1070914417

**Comment by u0a266** [comment]
i updated ventoy and failed to boot
```bash
ln: /dev/disk/by-label/ARCH_202107: No such file or directory
:: Mounting '/dev/disk/by-label/ARCH_202107' mounted successfuly.
:: Mounting /run/archiso/cowspace (tmpfs) filesystem, size=256M...
losetup: cannot find an unused loop device
:: Mounting '' to '/run/archiso/airootfs'
Waiting 30 seconds for device...
ln: No such file or directory
mount: /run/archiso/airootfs: wrong fs type, bad superblock on  , missing codepage or helper program, other error.
ERROR: Failed to mount ''
   Falling back to interactive prompt
   You can try to fix the problem manually, log out when you are finished 
sh: cannot access tty: job control turned off
```

 Kernel command line with `img_label=Ventoy img_loop=/path/to/iso`.
to the kernel command line and it booted!

**Comment by ventoy** [comment]
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/1071498619

**Comment by u0a266** [comment]
oh its amazing
successfully boot
thank you very much!
