### ISSUE TITLE
Problem with boot Artix after 28 of June [issue]: 

### ISSUE THREAD

**Issue by GM2405** [ventoy/Ventoy#1028]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.46 1.0.47

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

64Gb

### Image file checksum (if applicable)

No.

### What happened?

I can't boot Artix Linux after 2021-06-28

![2021-07-27_220149](https://user-images.githubusercontent.com/66706857/127732967-f584ea5b-090b-442d-961c-60f11d1bd082.png)

If I write ISO file (for example artix-xfce-openrc-20210726-x86_64.iso) with dd all works fine.
Weekly images you can download from here https://iso.artixlinux.org/weekly-isos.php

**Comment by Ohio2** [comment]
Yes, same problem!

**Comment by ventoy** [comment]
Please test with the latest 1.0.48 release

**Comment by GM2405** [comment]
Thanks!
All works fine
![2021-08-01_182323](https://user-images.githubusercontent.com/66706857/127774671-eb6f2391-589a-4389-8086-519b24e1d72b.png)
![2021-08-01_182944](https://user-images.githubusercontent.com/66706857/127774674-8682866b-185d-45dc-b323-397860475aa7.png)
