### ISSUE TITLE
WinPE 10-8 Sergei Strelec does not load all programs

### ISSUE THREAD

**Issue by masterjoe007** [ventoy/Ventoy#1032]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.47

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

128 GB

### What happened?

WinPE 10-8 Sergei Strelec does not load all programs
There are no problems with Ventoy 1.0.46

**Comment by ventoy** [comment]
The ISO download link?

**Comment by ventoy** [comment]
Did you see that the iso was mounted as  a logic driver?  
Does `X:\windows\system32\ventoy.log` exist? Its content?

**Comment by masterjoe007** [comment]
Problem solved!
The USB stick was the problem.
