### ISSUE TITLE
Prevent mounting of USB boot partition on Windows systems

### ISSUE THREAD

**Issue by makeworld-the-better-one** [ventoy/Ventoy#1035]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.47

### What about latest release

No. I didn't try the latest release.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32 GB

### What happened?

On my Linux system, XFCE doesn't provide an option to mount the EFI/boot partition of my Ventoy USB, only the main partition. This is what I want. On Windows 10, the boot partition is automatically mounted along with the main one. If there's a way to prevent the boot partition from being mounted that would be great, so that anyone using that USB doesn't get confused at where to put files into, and doesn't accidentally delete important files in that partition.

If there isn't a way to prevent Windows from mounting it, maybe there's a way to make it read-only?

**Comment by ventoy** [comment]
Latest Windows will show all the partitions for USB stick with MBR partition style.
So there is no universal way to automatically hide this partition. Also there is no way to make it read-only.

Maybe you can try GPT partition style.

**Comment by makeworld-the-better-one** [comment]
Ok thanks, that's too bad. But thanks a lot for creating Ventoy! It's very useful.

**Comment by steve6375** [comment]
You can set hidden and read-only attributes on all files?
