### ISSUE TITLE
Failed to compile GRUB2

### ISSUE THREAD

**Issue by a1ive** [ventoy/Ventoy#104]
报错信息:

>  ...
> mv -f grub-core/fs/.deps-util/libgrubmods_a-cpio_be.Tpo grub-core/fs/.deps-util/libgrubmods_a-cpio_be.Po
> mv -f grub-core/fs/.deps-util/libgrubmods_a-newc.Tpo grub-core/fs/.deps-util/libgrubmods_a-newc.Po
> In file included from grub-core/fs/exfat.c:2:
> grub-core/fs/fat.c: 在函数‘grub_fat_dir’中:
> grub-core/fs/fat.c:970:14: 错误：‘struct grub_dirhook_info’没有名为‘size’的成员
>   970 |          info.size = ctxt.dir.file_size;
>       |              ^
> make[2]: *** [Makefile:7322：grub-core/fs/libgrubmods_a-exfat.o] 错误 1
> make[2]: *** 正在等待未完成的任务....
>  ...

是不是 include/grub/fs.h 没有上传？

**Comment by a1ive** [comment]
另外是不是不需要 grub-core/commands/blocklists.c 这个文件，看起来没有实质性改动。

**Comment by ventoy** [comment]
fs.h是漏了，已上传。
blocklist.c是没有修改，可能当初beyondcompare比的时候没注意。
