### ISSUE TITLE
Could give a folder named EFI？

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#1043]
Users prefer a custom ESP, so could you package the folder named EFI to be a zip file？

Usually, ESP need to be FAT32 even exFAT, and the size of partition depends on the case, and many cases are different.

If you just give all files from ESP of ventoy, everything will be easier.

In another word, users would like to copy the files when upgrading.

**Comment by ventoy** [comment]
Ventoy's EFI partition is fixed at size 32MB and can NOT be changed.
If you copy Ventoy's files to another bigger ESP partition, it will NOT boot.
It was designed as this from the beginning.

**Comment by 1457384613gh** [comment]
> Ventoy's EFI partition is fixed at size 32MB and can NOT be changed.
> If you copy Ventoy's files to another bigger ESP partition, it will NOT boot.
> It was designed as this from the beginning.

But you could give all files into ESP: /EFI/  
And we can copy them into our ESP: /EFI/ by ourselves.

**Comment by steve6375** [comment]
Use 7zip to open the image file inside.
\ventoy-1.0.47-windows.zip\ventoy-1.0.47\ventoy\ventoy.disk.img.xz\ventoy.disk.img\EFI\

**Comment by 1457384613gh** [comment]
> Use 7zip to open the image file inside.
> \ventoy-1.0.47-windows.zip\ventoy-1.0.47\ventoy\ventoy.disk.img.xz\ventoy.disk.img\EFI\

Thanks for your reply and how earnest you are !

**Comment by ventoy** [comment]
Why you want to copy files by yourself? Why you don't use Ventoy to update itself?
The files under /EFI/ can be dynamically changed depend on whether the user select `support secure boot` option or not.
Some files will be removed if user don't select the  `support secure boot` option, and if the user select  `support secure boot` option to update Ventoy will add these files to EFI folder.
So it's not a good way to copy files manually.

**Comment by 1457384613gh** [comment]
> Why you want to copy files by yourself? Why you don't use Ventoy to update itself?
> The files under /EFI/ can be dynamically changed depend on whether the user select `support secure boot` option or not.
> Some files will be removed if user don't select the `support secure boot` option, and if the user select `support secure boot` option to update Ventoy will add these files to EFI folder.
> So it's not a good way to copy files manually.

Because I want to use ventoy to boot OpenCore, and then boot dmg of Mac PE into exFAT partition.
However, a larger ESP is not a bad thing.
By the way, if you want to make ventoy super, you could add OpenCore but users add configuration by themselves to load dmg to install Hackintosh.

**Comment by ventoy** [comment]
But if you copy Ventoy EFI files to a bigger ESP, they will NOT work.  How to boot OpenCore?

**Comment by 1457384613gh** [comment]
> Why you want to copy files by yourself? Why you don't use Ventoy to update itself?
> The files under /EFI/ can be dynamically changed depend on whether the user select `support secure boot` option or not.
> Some files will be removed and some files will be renamed if user don't select the `support secure boot` option, and if the user select `support secure boot` option to update, then Ventoy will add some files to EFI folder and also do some rename operation.
> So it's not a good idea to copy files manually.



> But if you copy Ventoy EFI files to a bigger ESP, they will NOT work. How to boot OpenCore?

😱😱😱😱😱My god! Bless me, please!
If not, could you a conventional way to upgrade ventoy? Which is copy files just like upgrade EFI files of Hackintosh.

**Comment by ventoy** [comment]
I suggest you reserve some space at the end of the USB stick when install Ventoy.
After install Ventoy you can create another ESP partition with these reserved space and install OpenCore to this bigger ESP.
https://www.ventoy.net/en/doc_disk_layout.html#reserve_space

**Comment by 1457384613gh** [comment]
> I suggest you reserve some space at the end of the USB stick when install Ventoy.
> After install Ventoy you can create another ESP partition with these reserved space and install OpenCore to this bigger ESP.
> https://www.ventoy.net/en/doc_disk_layout.html#reserve_space

Sounds easy and good!

**Comment by AnomSanjaya** [comment]
> GPT disk with ESP is no problem without MSR？

MSR only works in Windows, since Ventoy use GRUB Linux, the MSR is useless and Windows without MSR still working as usual
