### ISSUE TITLE
[issue]: Ventoy2Disk is blocked by Windows Defender

### ISSUE THREAD

**Issue by ferino75** [ventoy/Ventoy#1045]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.49

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GB

### What happened?

Hi,
cannot start Ventoy2Disk.exe
probably is blocked by Windows Defender
Windows 10 Pro 21H1 19043.1110

**Comment by ventoy** [comment]
I can't do anything about it.

**Comment by ferino75** [comment]
OK. This can be resolved so that for a moment I disable Defender.

**Comment by ventoy** [comment]
ok
