### ISSUE TITLE
[issue]: 

### ISSUE THREAD

**Issue by ps1-hagrid** [ventoy/Ventoy#1048]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.49; 1.0.48; 1.0.47

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### Image file checksum (if applicable)

Yes.

### What happened?

When I installed the latest and some previous version until 1.0.46, Windows doesn't recognize what File System VTOYEFI uses. I can't assign a letter. I want to access the VTOYEFI partition for plugins and themes. I've done a hour of troubleshooting too. And in 1.0.49 Windows can't even read the label as "VTOYEFI" anymore it is just blank.
![1 0 46](https://user-images.githubusercontent.com/81025171/128595380-40d4d3f8-d230-4db3-a973-de6cd85bc90f.png)
![1 0 49](https://user-images.githubusercontent.com/81025171/128595381-d0556328-2264-43eb-8242-36f9aeac608b.png)
![10 47](https://user-images.githubusercontent.com/81025171/128595495-2f7ab8d9-54c9-46ae-afd9-842067526c36.png)
![1 0 48](https://user-images.githubusercontent.com/81025171/128595572-9be874fa-e03b-42c1-99cb-abd150777fbe.png)

**Comment by ventoy** [comment]
It's the limitation of the Windows system.
In Win7/8/8.1 and earlier Win10 versions, for the removable USB stick, Windows will only display the first partition. 
For the 2/3/4 partitions (VTOYEFI is the 2nd partition) you can NOT see them. You can NOT assign a drive letter for them.

Besides, I think you have some misunderstandings.
The plugins and theme must put in the 1st partition (Ventoy partition) not the VTOYEFI partition.
So you don't need and should not access the 32MB VTOYEFI partition.

**Comment by ps1-hagrid** [comment]
well I rename my theme as ventoy and replace it VTOYEFI. and since it works on 1.0.46 I'll keep using it

**Comment by ventoy** [comment]
Well this indeed can work, but you need to update everytime when you update Ventoy. 1.0.47/48/49/50/51....
If you use the theme plugin following the official instruction then you don't need to do the work all the time.

**Comment by ventoy** [comment]
From 1.0.47 a hidden attribute for VTOYEFI part in GPT partition style was added.
https://github.com/ventoy/Ventoy/commit/da746c608fc7acbb4c9763d08c97fcd9584b809b

So this will prevent some Windows version to access the VTOYEFI partition.
This is for the protection of the VTOYEFI partition. 
So you need to follow the official instruction to use the theme plugin.
https://www.ventoy.net/en/plugin_theme.html
