### ISSUE TITLE
[Feature]: Can Ventoy be made to respect Folder Structure on its GRUB screen ?

### ISSUE THREAD

**Issue by aiamuzz** [ventoy/Ventoy#1051]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.49 (Latest downloaded from your website)

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

160 GB

### What happened?

Its not a bug ... but rather a question on a possible feature !

Firstly thanks for this great project and solution ... saves a lot of time on creating live CD's especially for testing purposes(various flavors of Linux).

I had segregated the ISO's i drop on to the VENTOY partition into 3 basic folders ...

**linuxISO's**
**windowsISO's**
**macISO's**(would be a good idea, though i haven't created it on my partition, provided ventoy supports MAC OS ISO's, does it ?)
**utilityISO's**(for gparted, clonezilla, HBCD, etc ... would like to add more, but know of only these 3 utilities, love to know more)

I am hoping this feature request isn't difficult, given that the grub does have a folder structure(with the older kernels segregated into a separte folder like entry)

Hope to see this feature implemented if this IDEA appeals to you.

Great work, Once Again !!!

**Comment by steve6375** [comment]
F3 is TreeView.
Is that what you want?

**Comment by aiamuzz** [comment]
> F3 is TreeView.
> Is that what you want?

Wow ... that's fantastic ... its already there ... 

Any way i can make the F3 as my default view ... would be nice !

If its a difficult implementation let me know, and i'll close this request thread, if its implementable than i can leave it open ...

**Comment by steve6375** [comment]
yes, just use a ventoy.json file
Read the Documentation on the website!

**Comment by aiamuzz** [comment]
> yes, just use a ventoy.json file

this is my folder structure ...
![image](https://user-images.githubusercontent.com/3283676/128682612-542a6cfe-8b7c-492c-a116-d0b5938a6c5d.png)


the following is the contents of the json file placed at the path `/media/muz/Ventoy/ventoy/ventoy.json` ... when i booted into ventoy disk i am getting no ISO's found ... is the   `{ "VTOY_DEFAULT_SEARCH_ROOT": "/ISO" },` for i have no ISO folder ... can i just "/" ? couldn't find any documentation on the possibility of putting only the '/' for root ...

```
{
    "control": [
        { "VTOY_DEFAULT_MENU_MODE": "1" },
        { "VTOY_TREE_VIEW_MENU_STYLE": "0" },
        { "VTOY_FILT_DOT_UNDERSCORE_FILE": "1" },
        { "VTOY_SORT_CASE_SENSITIVE": "1" },
        { "VTOY_MAX_SEARCH_LEVEL": "max" },
        { "VTOY_DEFAULT_SEARCH_ROOT": "/ISO" },
        { "VTOY_MENU_TIMEOUT": "10000" },
        { "VTOY_DEFAULT_IMAGE": "/ISO/debian_netinstall.iso" },
        { "VTOY_FILE_FLT_EFI": "1" },
        { "VTOY_DEFAULT_KBD_LAYOUT": "QWERTY_USA" }
    ]
}
```

**Comment by steve6375** [comment]
Of course!
        { "VTOY_DEFAULT_SEARCH_ROOT": "/" },

**Comment by aiamuzz** [comment]
@steve6375 ... thanks for your quick response ... turned out "/" worked ... closing this thread as feature already exists.

A GREAT DESIGN is one that already taps into as many potential possibilities in it ... turns out my feature request has already been tapped into !!!

BTW ... Who is the creator(founder) of this Ventoy Project !!!

Complements due to him and the community which has supported it so far !!!

Great job guys !!!
