### ISSUE TITLE
[Feature]: Option to create separate partitions on the Ventoy disk, to test drive it beyond the live USB(by installing it to the additional partition)

### ISSUE THREAD

**Issue by aiamuzz** [ventoy/Ventoy#1052]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.49 (Latest downloaded from your website)

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

160 GB

### What happened?

Not a Bug, rather a possibility of a potential feature !!!

I viewed my 160GB ventoy disk under a gparted live CD hoping to create additional partitions in my big harddisk so i could attempt an install of one of the distros i intend to test ... to see if Ventoy is equipped to handle these installations and the many ISO's already on this disk within its grub.

Unfortunately i discovered that by design the disk cannot be re-partitioned. 

**Would've been cool to have the option of installing flavors one intends to test drive beyond the LiveUSB/CD !!!**

Could this be a viable feature to develop ?

PS : I saw one plugin by the name **"Linux vDisk Boot Plugin"**, by any chance is this plugin created to accomplish the exact same feature i have shared here ? I haven't been able to find time to test those yet.

thanks.

**Comment by ventoy** [comment]
Once you have finished the installation of Ventoy. The disk partition layout can not be changed.
But you can reserve some space at the end of the disk when you install Ventoy.
Then after install, you can create your own partition with the reserved space as you want.
https://www.ventoy.net/en/doc_disk_layout.html#reserve_space

**Comment by aiamuzz** [comment]
@ventoy ... 
Complements to this very handy piece of solution ... I am over whelmed at the well though'out'ed'ness ... there is already an option to something i thought would make sense ... Great Work @ventoy 

> Once you have finished the installation of Ventoy. The disk partition layout can not be changed.
> But you can reserve some space at the end of the disk when you install Ventoy.
> Then after install, you can create your own partition with the reserved space as you want.
> https://www.ventoy.net/en/doc_disk_layout.html#reserve_space

thanks, I'll try it out and post my experiences / hiccups if any ...

**Comment by aiamuzz** [comment]
> The disk partition layout can not be changed.
> But you can reserve some space at the end of the disk when you install Ventoy.

@ventoy ...

I was able to successfully create 2 partitions at the end ...

1. With these 2 partitions of 15GB each that i've created, Will i be able to install(test drive) any one of the live-USB distro's to these partition ?
2. If I did do something like this, will the ventoy grub factor in and populate this installed partition/s ? Normally the GRUB of the installed OS takes control, isn't it ?
3. If that happens will 'Ventoy' work(as in the many ISO's that i have in the ventoy partition be bootable) as its supposed to work ?
4.  Please let me know if there is a way to install the booted in Live-ISO from ventoy to these partitions and yet ensure that the ventoy grub continues to be in command.
5. Is there a limit to the no of partitions that one can create towards the end of the harddisk ? Your documentation mentions only 2 partitions, is it so or one is free to create 'n' number of partitions out of the unallocated reserved space towards the end of the harddisk ?

**Comment by SuJiKiNen** [comment]
you can refer to this #852

**Comment by tute123456** [comment]
thx!!!
