### ISSUE TITLE
Will Haiku get a support?

### ISSUE THREAD

**Issue by GHNewbiee** [ventoy/Ventoy#1053]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.49

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Image file checksum (if applicable)

No.

### Image file download link (if applicable)

https://cdn.haiku-os.org/haiku-release/r1beta3/haiku-r1beta3-x86_64-anyboot.iso

### What happened?

Haiku **fails** to boot since it is **not supported** yet (as per list).

Are there any **plans** for haiku to get support in the **near** future? *Tia*

**Comment by ventoy** [comment]
No plan in the near future.

**Comment by mmuman** [comment]
Well it boils down to #194 and working out a consensus on the protocol, because alternative OSes don't have time to support 10 times the same thing for every thing out there.

**Comment by thetick1234567890** [comment]
Any chance to add support for Haiku / Be OS anyboot images ?
http://cgit.haiku-os.org/haiku/tag/?id=hrev56184
