### ISSUE TITLE
[issue]: Untangle ISO won't detect "CDROM"

### ISSUE THREAD

**Issue by asheroto** [ventoy/Ventoy#1054]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.48

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

32GB

### Image file checksum (if applicable)

a811426e5d50868b343497377e5995c4b92ba67b541352d5e6a18dcaf816cb26

### Image file download link (if applicable)

https://mega.nz/file/zPoywIaI#R5G4wrC288beW4NN-1B1v7-y1N-QKh4HPJJ6L8hLrc8

### What happened?

I tried installing Untangle by putting the ISO on my flash drive.  Ventoy detects it and runs it, but the Untangle software fails and says "The CD-ROM drive contains a CD which cannot be used for installation.".  It tries to detect files on `/cdrom`.  If I use Rufus and create a flash drive with the same ISO, the install works and detects `/cdrom`.

I also tried pressing `F1` and loading from memory.  Same error.

You can download the ISO at the `Image file download link`.

Picture of error:
![pic](https://i.imgur.com/imUevCl.jpeg)

**Comment by ventoy** [comment]
Please try this CI release: https://github.com/ventoy/Ventoy/actions/runs/1114937374

**Comment by asheroto** [comment]
Thank you.  It works in UEFI Mode but not in Legacy Mode.

**Comment by ventoy** [comment]
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/1118408418

**Comment by asheroto** [comment]
@ventoy just FYI, my UEFI entries now have two entries for `UEFI: Samsung Flash Drive` and one for `USB: Samsung Flash Drive`.  Wondering if the test Ventoy build I ran caused it?  I used to just have 1x UEFI and 1x USB (legacy).
