### ISSUE TITLE
[issue]: Dont boot with windows 10 ...

### ISSUE THREAD

**Issue by penny1mx** [ventoy/Ventoy#1057]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.49

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

32Gb

### Image file download link (if applicable)

https://www.microsoft.com/en-us/software-download/windows10

### What happened?

Hi guys !!!

I have a problem, I create an ISO with the Media Creation Tool from Microsoft downloaded from ( https://www.microsoft.com/en-us/software-download/windows10 ), but don't boot, I try with different options says in the FAQ, and don't work.

Anyone has an idea why ???

Thanks so much !!!

Kind regards.

**Comment by ventoy** [comment]
A photo about the problem?
Does other linux iso file boot ok in the same way? (e.g.  Ubunut/Archlinux ...)

**Comment by penny1mx** [comment]
My mistake I'm so sorry for that.

The problem is the format is not in the standard 2048.

Thanks so much !!!
