### ISSUE TITLE
[issue]: Installing Linux alongside Ventory (GRUB)

### ISSUE THREAD

**Issue by TolyanDimov** [ventoy/Ventoy#1058]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.49

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

GPT

### Disk Capacity

900 GB

### Image file checksum (if applicable)

No.

### What happened?

I registered on the forum https://forums.ventoy.net/.
However, for some reason I am unable to write messages.

I installed ventoy and also installed linux on the same usb-hdd.

- Partition-1 (exFAT) = 100GB - standard ventoy-partition on which iso-images are located.
- Partition-2 (FAT16) = 32MB - system ventoy-partition on which the fan-loader is located.
- Partition-3 (swap) = 2GB - swap.
- Partition-4 (ex4) = 100GB - root.

The problem is that after installing Linux, when the computer starts up, the Linux bootloader is displayed.
I want the ventoy bootloader to boot.

I was advised to make a copy of the MBR-Venta bootloader and install Linux.
Next, we restore the disk sectors through the BootIce program.

I am wondering how much space the ventoy bootloader takes up?

PS
Sorry for my bad english.

**Comment by ventoy** [comment]
You can try to do a update operation to the Ventoy USB after you install the linux.

**Comment by TolyanDimov** [comment]
I expected after ventoy update on next system reboot my local bootloader will appear in F4> grub4dos lists. That did not happen.

I don’t know which direction should I go next?
I just want venttoy to be my default bootloader for installed systems.

I would be grateful for any help.

**Comment by ventoy** [comment]
Ventoy can't be so intelligent.
You need to write a custom grub.cfg to load your system and this custom grub.cfg can be load from Ventoy from F6.
https://www.ventoy.net/en/plugin_grubmenu.html
