### ISSUE TITLE
Windows 11 iso not booting in UEFI mode, Legacy is ok

### ISSUE THREAD

**Issue by enigma131** [ventoy/Ventoy#1061]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.49

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

16 Go

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://www.swisstransfer.com/d/185a40cc-edb6-4fb4-98a1-0750977acba3

### What happened?

message : no file found \efi\microsoft\boot\bootx64.efi   (bootx64.efi stands at \efi\boot\bootx64.efi)

**Comment by ventoy** [comment]
1. Did you test with the latest 1.0.50 release?
2. What is your computer's manufacturer? HP/Dell ...
3. All Windows ISO boot fail in UEFI mode? Or only this one?
4. Can some linux iso boot ok in UEFI mode? (e.g. Ubunut/CentOS/Archlinux ...)
5. Please try wimboot mode https://www.ventoy.net/en/doc_wimboot.html

**Comment by enigma131** [comment]
Upgraded to 1.0.50 and same problem,  have forgot to mention error message 0xc000014c.
Computer is Laptop Acer E571. 
Other Windows ISOs are booting, perhaps a W11 special case ?
All Linux are booting.

**Comment by steve6375** [comment]
I tried this same ISO on Ventoy 1.0.47 and got the same 0xc000014c error.
It boots OK if I first type Ctrl+W (but ISO is not loaded as virtual disk so cannot install)
Other Win11 ISOs work OK.

**Comment by ventoy** [comment]
Can you share the ISO with [https://mega.nz](https://mega.nz)

**Comment by enigma131** [comment]
Iso is still available on first post link ;)

**Comment by ventoy** [comment]
OK, I have download it.
I connect the ISO file directly to a VM(tested with VMWare and VirtualBox) and boot in UEFI mode, it also report the 0xc000014c error.
So I think the ISO file has some problem itself.

**Comment by ventoy** [comment]
> Using VBox 5 + VBUM:
> I tried this same ISO on Ventoy 1.0.47 and got the same 0xc000014c error.
> It boots OK if I first type Ctrl+W (but ISO is not loaded as virtual disk so cannot install)
> Ctrl+R did nothing.
> Other Win11 ISOs work OK.
> I can boot it using grubfm OK (wimboot)

I test the ISO with my laptop.
Both 1.0.47 and 1.0.50 can boot OK in wimboot mode (press `ctrl+w` first) and the iso is auto loaded as virtual disk, so it can install OK.

**Comment by enigma131** [comment]
Ok thanks, there not official ISO for W11 just now, must care for next releases and next beta.

**Comment by ventoy** [comment]
OK. I think this should be the ISO file problem.
For next release you can test with VM(e.g. VMWare/VirtualBox) if you get problem again.
I close this issue now.

**Comment by Jogai** [comment]
It works without a hitch on 1.0.53 (GPT) and Windows 11 (english international) from here: https://tb.rg-adguard.net/dump.php?seach=win11&str=50&lang=en-GB
