### ISSUE TITLE
Escaped quotes (\") cause a syntax error

### ISSUE THREAD

**Issue by Silexium** [ventoy/Ventoy#1062]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.50

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64GB

### What happened?

Escaping quotes (\") in "ventoy.json" causes a syntax error when trying to boot Ventoy. I want to get double quotes in my image alias configuration. That is, I want codenames like "Odin", "Hirsute Hippo", etc. to be enclosed in double quotes. I tried using the above method, but I got a syntax error when booting to Ventoy. VS Code did not complain about the escaped quotes & there were no syntax errors in the ".json" file. Are there other ways to include double quotes in JSON strings?

**Comment by ventoy** [comment]
You can try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/1137579608
https://www.ventoy.net/en/doc_github_ci.html

**Comment by Silexium** [comment]
Everything works fine now. Thanks!
![20210817_180235](https://user-images.githubusercontent.com/87285693/129761799-3dba87d3-7276-42b1-9d93-8c8f9da128b7.jpg)
