### ISSUE TITLE
[issue]: This is NOT a standard Ventoy device and is not supported (0x7)

### ISSUE THREAD

**Issue by Nate700** [ventoy/Ventoy#1066]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.50

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

256 GB

### What happened?

![20210822_001539](https://user-images.githubusercontent.com/74857129/130343403-209c0eb8-e589-48bf-b88f-c6f8c6025faa.jpg)

**Comment by Nate700** [comment]
https://www.amazon.com/Samsung-BAR-Plus-256GB-MUF-256BE3/dp/B07BPKL2D2?th=1&psc=1
This the usb I used

**Comment by steve6375** [comment]
The error means that Ventoy files are either:
1. not on the 2nd partition
2. not on a partition of exact size = 32MB
3. partition does not immediately follow the previous partition
The official Ventoy tool will make the correct partitions.
Did you use the official Ventoy tool or linux script?
Did you change the partitions after installing Ventoy?

**Comment by Nate700** [comment]
1st partition I changed to ex4

**Comment by steve6375** [comment]
How?

**Comment by Nate700** [comment]
I used KDE partition manager
![20210822_003645](https://user-images.githubusercontent.com/74857129/130343754-8e0da1d2-01cc-4213-83d0-8af85f494059.jpg)

**Comment by Nate700** [comment]
2 Partition files are untouch

**Comment by steve6375** [comment]
Did you re-partition it or just re-format partition 1?
try fdisk -l  to see if partition 2 starts immediately after partition 1

Remake the drive and reformat the first partition - do not delete the partition or remake it or change its size.

**Comment by Nate700** [comment]
I think I see the mistake I made

**Comment by Nate700** [comment]
![16296116303671624105689298000448](https://user-images.githubusercontent.com/74857129/130344141-aa981d82-d2ec-4d24-b813-d8fc05e91565.jpg)
I deleted it

**Comment by steve6375** [comment]
Instructions should be given on website on how to reformat the first partition and a warning given not to delete any partition or change any partition  size once the drive has been made.

**Comment by Nate700** [comment]
I guess I missed read something
