### ISSUE TITLE
exFAT分区如何设置簇大小，对齐到4096扇区整数倍？

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#1069]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.49

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

github

### What happened?

exFAT分区前面保留了几百KB。手动编辑exFAT分区，哪怕是调整分区大小，ventoy都会显示未安装，需要重装。有没有办法，让exFAT分区前保留0kb，并且设置自定义簇大小，设置对齐到4096扇区的整数倍。

**Comment by ventoy** [comment]
exFAT分区是从 1MB的位置开始的，而且必须从1MB的位置开始，这个是固定的，不能改。
exFAT分区的大小也是计算好的，一旦安装完Ventoy之后，exFAT分区的大小也是不能改动的。

在安装Ventoy的时候，根据U盘大小，小于32GB的U盘，默认簇大小为32KB，大于32GB的U盘，默认簇大小为128KB。
安装完之后，对于exFAT分区，你也可以重新手动右键格式化，格式化时自己选择簇大小。

你使用默认安装的Ventoy遇到了什么问题吗？请详细描述下。

**Comment by ventoy** [comment]
Ventoy安装后的U盘布局：
https://www.ventoy.net/cn/doc_disk_layout.html

**Comment by 1457384613gh** [comment]
> Ventoy安装后的U盘布局：
> https://www.ventoy.net/cn/doc_disk_layout.html

![Screenshot_2021-08-25-06-56-23-1015880207_EDIT_1629845813536](https://user-images.githubusercontent.com/69227436/130701758-41970ab9-5e52-4c86-a60a-21b1633c20e8.png)
簇大小只能2048，为什么啊？

**Comment by 1457384613gh** [comment]
> Ventoy安装后的U盘布局：
> https://www.ventoy.net/cn/doc_disk_layout.html

可以自定义exFAT分区的卷标吗？

**Comment by ventoy** [comment]
exFAT卷标默认是Ventoy，可以随便改。

**Comment by 1457384613gh** [comment]
> exFAT卷标默认是Ventoy，可以随便改。



> Ventoy安装后的U盘布局：
> https://www.ventoy.net/cn/doc_disk_layout.html

diskgenius显示，排除GPT前的64扇区，还有好几百KB的闲置空间。你的意思是，GPT磁盘前面预留64扇区是不够的？那些被分区软件识别成了闲置空间怎么办？可以划分到前端去吗？

**Comment by ventoy** [comment]
是的，那部分虽然看着是空闲空间，但是Ventoy有些启动相关的文件会写到里面，Ventoy启动时会用到。所以不能动。

**Comment by ventoy** [comment]
exFAT分区从1MB位置开始应该可以满足各种对齐要求的。

**Comment by 1457384613gh** [comment]
> exFAT分区从1MB位置开始应该可以满足各种对齐要求的。

那，分区末端要不要预留1MB？毕竟，GPT硬盘末端是 前端的备份诶。

**Comment by ventoy** [comment]
不需要。末端的GPT备份分区表并不需要对齐，而且它只有33个扇区长，也对不齐。
所谓对齐只是针对分区本身的要求，对于分区表是没有要求的，因为分区表只在启动的时候读取一次就够了。
GPT的主分区表是从扇区1开始的，它也不是对齐的。

**Comment by 1457384613gh** [comment]
> 不需要。末端的GPT备份分区表并不需要对齐，而且它只有33个扇区长，也对不齐。
> 所谓对齐只是针对分区本身的要求，对于分区表是没有要求的，因为分区表只在启动的时候读取一次就够了。
> GPT的主分区表是从扇区1开始的，它也不是对齐的。

能不能更新一下Ventoy，使得在设置预留空间时，单位可以选择KB和B

**Comment by ventoy** [comment]
你需要分区以多少对齐？

**Comment by ventoy** [comment]
另外，你可以这样试试（我没试过，不保证管用）。
1、安装完Ventoy之后，比如exFAT分区大小是 1GB+4KB，使用分区软件，修改exFAT分区的大小，改成 1GB。
2、重新格式化exFAT分区，此时这个exFAT文件系统就只会使用 1GB 空间。
3、再使用分区软件，把exFAT分区大小改回成 1GB+4KB

这样，不会影响Ventoy软件。相当于exFAT分区浪费了4KB空间。

**Comment by 1457384613gh** [comment]
> 你需要分区以多少对齐？你的U盘是多大？ 是4KB对齐的吗？

4kib对齐。假设我想在末端预留175.5MiB，0.5MiB是小数，好像无法输入，只好输入512KiB，但也无法输入……
由于物理硬盘的容量设计是1000进制的，以1024进制计算，给人缩水的感觉……Mac OS还有不少Linux的都支持1000进制显示容量，增强体验。所有我分区一般以B为单位分区。例如分区8GB，我要手抖输入8000,000,000B。所以，我想设置预留分区可以以B为单位，预留多少多少B。毕竟，U盘要给 Mac 读取，建立ESP2，设置OpenCore引导Mac PE 和 Mac 安装程序。以B为设置分区的单位，以1000进制显示容量，可以增强体验，给人不缩水的感觉。

**Comment by ventoy** [comment]
Ventoy安装时默认会让exFAT分区以4Kib对齐。

**Comment by 1457384613gh** [comment]
> Ventoy安装时默认会让exFAT分区以4Kib对齐。

那么，预更新的Ventoy可以在设置预留空间那里，选择以KB或B为单位吗？

**Comment by ventoy** [comment]
暂时不会，Ventoy还有一个4K对齐的选项和这个是有关联的。 
以MB为单位是不需要考虑用户输入的保留空间不对齐的问题的，如果以KB和B为单位就需要考虑了，改起来就比较麻烦了。
如果对功能没有影响，仅仅是显示的话，暂不考虑修改。

**Comment by 1457384613gh** [comment]
> 暂时不会，Ventoy还有一个4K对齐的选项和这个是有关联的。
> 以MB为单位是不需要考虑用户输入的保留空间不对齐的问题的，如果以KB和B为单位就需要考虑了，改起来就比较麻烦了。
> 如果对功能没有影响，仅仅是显示的话，暂不考虑修改。

顺便问下，如果预留空间新建了分区，而且里面有ISO文件，ventoy会扫描吗？

**Comment by ventoy** [comment]
不会，预留空间创建的分区Ventoy不管。完全是用户自由使用。
