### ISSUE TITLE
[issue]: nomadbsd 启动失败

### ISSUE THREAD

**Issue by aeeq** [ventoy/Ventoy#1070]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.49

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64G

### Image file download link (if applicable)

https://nomadbsd.org/download.html

### What happened?

可以进入nomadbsd的引导菜单,进入系统之后有报错,大概意思是mount 不到盘

**Comment by ventoy** [comment]
目前还不支持 nomadbsd
https://www.ventoy.net/cn/distrowatch.html
