### ISSUE TITLE
Cannot boot the image; you should boot kernel first.[issue]: 

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#1074]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.50

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128

### Image file checksum (if applicable)

Yes.

### What happened?

A bug happened!
屏幕黑屏，白字显示：
Cannot boot the image; you should boot kernel first.
尝试过许多linux的ISO镜像包，无法UEFI启动，只能传统BIOS启动。不知道是不是跟Ventoy先启动了微内核有关。

**Comment by 1457384613gh** [comment]
> 具体是哪些ISO不能启动？请列出一两个。
> 是否开启了安全启动？

说来，好像也与“安全启动的设置”有关。
这是很久很久以前的笔记本。虽然支持UEFI，但其实是旧版的。BIOS设置里压根就没有“安全启动”的选项。但TPM什么的，是关的。U盘没有设置安全启动。

**Comment by 1457384613gh** [comment]
> Does it work on other systems?
> Did you try different USB drive?
> Did you try booting the USB drive using VM like VirtualBox or VMWare or QEMUBootTester set to UEFI64 mode?
> Since Ventoy works for millions of other people, you should suspect your equipment, ISO files or method.

linux内核的无法启动，其他的，还未尝试。

**Comment by 1457384613gh** [comment]
> Does it work on other systems?
> Did you try different USB drive?
> Did you try booting the USB drive using VM like VirtualBox or VMWare or QEMUBootTester set to UEFI64 mode?
> Since Ventoy works for millions of other people, you should suspect your equipment, ISO files or method.

deepin OS
fedora OS
cannot be boot

**Comment by ventoy** [comment]
> > 具体是哪些ISO不能启动？请列出一两个。
> > 是否开启了安全启动？
> 
> 说来，好像也与“安全启动的设置”有关。
> 这是很久很久以前的笔记本。虽然支持UEFI，但其实是旧版的。BIOS设置里压根就没有“安全启动”的选项。但TPM什么的，是关的。U盘没有设置安全启动。尝试过运行开源的，需要关闭安全启动的“xx.efi”，可以启动。
> 总之，UEFI启动ventoy，可以进入grub主题界面，有列表ISO，可以选择，但所有带linux内核的ISO启动失败。提示，必须先启动内核文件。同一台机子，使用传统启动，可以通过Ventoy启动ISO。

可能和主板的UEFI固件有关，Ventoy虚拟CDROM设备是需要UEFI固件的支持的，如果是很早期的UEFI固件，有可能不是非常符合UEFI标准，或者有些地方的实现和主流的不一样。

你可以先按 `ctr+r` 进入 grub2 模式，然后再选择ISO文件启动。

**Comment by 1457384613gh** [comment]
![Screenshot_2021-08-30-17-41-24-799_com miui video](https://user-images.githubusercontent.com/69227436/131320270-a64e90a8-0b5e-4c64-99c5-dc000e3da4e9.jpg)
![Screenshot_2021-08-30-17-41-35-820_com miui video](https://user-images.githubusercontent.com/69227436/131320300-e33c3492-a31a-4aa8-bd43-923127af1d46.jpg)

**Comment by ventoy** [comment]
这个看着像是Ventoy启动文件被破坏了。升级的时候有没有出现问题？ 重新打开Ventoy程序还能否检测出版本号。 重新升级一次再试有没有用。

**Comment by ventoy** [comment]
另外，U盘是什么牌子的。

**Comment by 1457384613gh** [comment]
> 这个看着像是Ventoy启动文件被破坏了。升级的时候有没有出现问题？ 重新打开Ventoy程序还能否检测出版本号。 重新升级一次再试有没有用。

都检查了，是正常的，传统启动成功了，进入了图形界面的grub2，加载了主题。UEFI启动失败。

**Comment by ventoy** [comment]
你能不能把你当前这个有问题的U盘里的32MB的VTOYEFI分区内的文件导出来发我看看。或者整个32MB分区数据dump出来也行。

**Comment by diogocardoso28** [comment]
Is secure boot off?
