### ISSUE TITLE
[issue]: Can't Update my USB drive from ventoy-1.0.50 To ventoy-1.0.51 

### ISSUE THREAD

**Issue by PhoenixCODE2322** [ventoy/Ventoy#1079]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.50

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64GB

### What happened?

Happened in ventoy-1.0.49 To ventoy-1.0.50 To ventoy-1.0.51, while updating ventoy in device. Never Used Ventoy before that.

The Log - 
the error Occured at this point -
`[2021/08/29 19:59:01.716] NOTE: Could not identify the process(es) or service(s) accessing \Device\Harddisk1\DR9`
[Here's the full Log](https://pastebin.com/Q6Hb9ZNc)

**What i did to troubleshoot -** 

- tried the faq (installing Ventoy2disk.exe failed) but it reformatted the drive completely.
- I tried My Two USB Drives both are having Same Error.
- Changed Ventoy Files Location.
- Had Medicat files in the drive, but then i experimented and cleared the ventoy and installed  ventoy-1.0.50 ( Note: did not removed the drived) went straight to updating to ventoy-1.0.51. But it failed with the same log.
- Tried disabling Windows Defender(only AV i use) , also exluded the USB drive partition. ( i did not restart my device).

edit- My USB Drive info-
1.  Sandisk 64GB SDCZ73-064G-I35
2. Sandisk 8GB Cruzer Blade

**Comment by ventoy** [comment]
If you have an old version of Ventoy and just want to update it.
Just put the Ventoy LiveCD iso file to the USB and reboot your computer and select the iso to boot.
And follow the menu to update Ventoy.

**Comment by PhoenixCODE2322** [comment]
Thank you it worked. My bad for Not seeing the Method 2 of Ventoy2Disk.exe
