### ISSUE TITLE
Can you change translation error  on Turkish language

### ISSUE THREAD

**Issue by crasadure** [ventoy/Ventoy#108]
hi ventoy;
I had made a translation error on **STR_UPDATE_TIP** parameter :

I updated Ventoy v1.0.09 and I think, "update message" will be good like that at STR_UPDATE_TIP parameter :

**STR_UPDATE_TIP='Ventoyun versiyon bilgisi güncellenecek, ISO dosyalarınız bundan etkilenmiyecek.#@Devam edilsinmi?'**

sorry..this is my fault..Can you change this line in language.ini file for turkish translation?

**Comment by ventoy** [comment]
I have committed it, thank you.

**Comment by crasadure** [comment]
thanks :)
