### ISSUE TITLE
[issue]: lubuntu-20.10-desktop-amd64.iso not working

### ISSUE THREAD

**Issue by MatiasMovie** [ventoy/Ventoy#1080]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1,0,51

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

8GB

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

http://cdimage.ubuntu.com/lubuntu/releases/20.10/release/

### What happened?

Failed to set MokListRT
I checked iso in hashcalc and it's good

**Comment by ventoy** [comment]
In current release, Ventoy use `Super UEFIinSecureBoot Disk` to supprot secure boot. 
You can make an issue in https://github.com/ValdikSS/Super-UEFIinSecureBoot-Disk
