### ISSUE TITLE
升级的过程中，exFAT分区容易丢失小文件。

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#1081]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.50

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128

### What happened?

A bug happened!
每次使用后，启动任意镜像后，diskgenius提示分区表错误，需要修复；检测到的ventoy的版本号变成问号，需要点击升级。而且exFAT分区容易丢失小文件，丢失以后，空的文件夹删不掉，显示文件系统错误，需要输入错误的代码才能删除。

**Comment by ventoy** [comment]
Ventoy版本号变成问号应该是因为最后面那个32MB的FAT分区被破坏了。Ventoy的版本号不是保存在exFAT分区，是保存在U盘最后的32MB VTOYEFI分区中。
exFAT/FAT分区都是无日志型的，所以日常使用时需要安全拔插，谨慎操作。 另外U盘的质量也很关键。
实在问题多你可以重新格式化成NTFS分区使用。
从大多数使用者的反馈情况看，这种情况并不多见。

**Comment by 1457384613gh** [comment]
> Ventoy版本号变成问号应该是因为最后面那个32MB的FAT分区被破坏了。Ventoy的版本号不是保存在exFAT分区，是保存在U盘最后的32MB VTOYEFI分区中。
> exFAT/FAT分区都是无日志型的，所以日常使用时需要安全拔插，谨慎操作。 另外U盘的质量也很关键，很多山寨U盘就很容易出这种问题。如果确实经常出问题，你可以重新格式化成NTFS分区使用。但从大多数使用者的反馈情况看，这种情况并不多见。
> 而且你是Ventoy版本号变成问号，这个就和exFAT分区无关了。

只是一次性反应两个问题而已。我当然知道两个分区相对独立。

**Comment by ventoy** [comment]
FAT分区被破坏的情况很少见，暂时不知道你这边具体是什么问题导致的。你可以换个U盘或者换个电脑对比试试，如果每次都是启动之后就变成问号了，那你可以把ISO文件、具体的操作反馈给我，我在我的环境上试试能不能出现。

**Comment by ventoy** [comment]
另外，你能不能换个U盘对比试试。

**Comment by 1457384613gh** [comment]
> FAT分区被破坏的情况很少见，暂时不知道你这边具体是什么问题导致的。你可以换个U盘或者换个电脑对比试试，如果每次都是启动之后就变成问号了，那你可以把ISO文件、具体的操作反馈给我，我在我的环境上试试能不能出现。

我在预留的空间里新建了一个FAT32分区。ESP分区夹在中间。USB启动进入系统，要加载分区挂载器，有的，就类似于搜索分区，把ESP分区读成了Basic data partition，并且提示分区表错误，分区损坏，还顺便改写了分区表……ESP分区夹在中间，会有很多程序读错并且改写分区表。

**Comment by ventoy** [comment]
不预留空间的话，同样的测试条件下就不出问题吗？
Ventoy的EFI分区确实是Basic Data partition, 不是真正的ESP分区，这个是为了规避Window的一个问题，Windows不允许系统内有多个ESP分区，所以设置成ESP分区Windows安装会失败。不过提示分区表错误倒是不应该。
你换个U盘测试也是这样吗？ 你能不能把你的配置、启动的ISO文件，启动之后的情况下截图或者录个视频看下。我在自己环境上测试一下。

**Comment by ventoy** [comment]
从你 https://github.com/ventoy/Ventoy/issues/1107 的反馈看你这个128GB的U盘可能硬件上有问题。
