### ISSUE TITLE
[issue]: U盘插手机使用，部分手机无法识别，提示需要格式化，目前出现该问题的手机有小米10ultra手机。

### ISSUE THREAD

**Issue by jimsonbuilder** [ventoy/Ventoy#1082]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.51

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32GB

### What happened?

使用安装了ventory软件的U盘，手机提示需要格式化U盘。
When using the U disk with this software installed, the phone prompts that the U disk needs to be formatted.

**Comment by ventoy** [comment]
可能是手机不识别exFAT分区的原因。有的手机只能识别FAT分区格式。
而Ventoy的主分区默认是格式化成exFAT分区的。你可以把存放ISO文件的分区在电脑上手动右键重新格式化成FAT分区再试试。
不过由于FAT分区固有的限制，无法存放超过4GB的问题，格式化成FAT分区之后，就不能存放超4G大小的ISO文件了。

**Comment by ventoy** [comment]
要是你手机能识别NTFS分区的话，也可以格式化成NTFS分区，NTFS分区没有4GB的限制。

**Comment by jimsonbuilder** [comment]
意思是说，使用ventoy制作U盘启动盘的时候选择NTFs格式是吧？
目前只是部分手机无法识别，电脑和其他手机可以识别到U盘，也可以查看和使用U盘里面的文件。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月30日(周一) 下午5:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ventoy/Ventoy] [issue]:U盘插手机使用，部分手机无法识别，提示需要格式化，目前出现该问题的手机有小米10ultra手机。 (#1082)




 
要是你手机能识别NTFS分区的话，也可以格式化成NTFS分区，NTFS分区没有4GB的限制。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jimsonbuilder** [comment]
好的，了解，感谢答复！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月30日(周一) 下午5:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ventoy/Ventoy] [issue]: U盘插手机使用，部分手机无法识别，提示需要格式化，目前出现该问题的手机有小米10ultra手机。 (#1082)




 
可能是手机不识别exFAT分区的原因。有的手机只能识别FAT分区格式。
 而Ventoy的主分区默认是格式化成exFAT分区的。你可以把存放ISO文件的分区在电脑上手动右键重新格式化成FAT分区再试试。
 不过由于FAT分区固有的限制，无法存放超过4GB的问题，格式化成FAT分区之后，就不能存放超4G大小的ISO文件了。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ventoy** [comment]
> 意思是说，使用ventoy制作U盘启动盘的时候选择NTFs格式是吧？ 目前只是部分手机无法识别，电脑和其他手机可以识别到U盘，也可以查看和使用U盘里面的文件。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年8月30日(周一) 下午5:26 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [ventoy/Ventoy] [issue]:U盘插手机使用，部分手机无法识别，提示需要格式化，目前出现该问题的手机有小米10ultra手机。 (#1082) 要是你手机能识别NTFS分区的话，也可以格式化成NTFS分区，NTFS分区没有4GB的限制。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Ventoy制作U盘时默认是exFAT分区，这个是不能选的，但是制作完成之后，你可以再次手动格式化成NTFS。
