### ISSUE TITLE
建议：加载.dmg镜像文件

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#1083]
Ventoy能够加载ChromeOS，是Ventoy发展的一次跨越。
大概的原理，想必是读取.img映像中的ESP分区，加载.efi文件，启动镜虚拟盘中的ChromeOS。
.dmg镜像文件与.img镜像文件很像，而且可以互相转换。如果能够读取.dmg映像文件中的ESP分区，加载Clover或者OpenCore进而启动黑苹果的安装程序，或者 黑苹果预安装环境，便是又一大跨越。

希望，Ventoy可以读取.dmg映像文件，并且加载虚拟盘中的ESP分区。
以下链接中的.dmg映像文件可供测试。
对应机型的EFI文件可以在第二个链接中的表格上寻找。
https://blog.daliansky.net/macOS-BigSur-11.4-20F71-Release-version-with-OC-0.6.9-and-Clover-5134-and-PE-original-image.html#more

https://github.com/daliansky/Hackintosh

**Comment by ventoy** [comment]
这个难度很大。
Ventoy能够加载ChromeOS是因为ChromeOS也是基于Linux的，也是开源的。我能知道它内部的运行机制。
Ventoy去读img文件中的ESP分区加载efi文件启动，这只是万里长征第一步， efi启动之后，把内核启动起来以后，
系统就会按照常规的方法去寻找安装介质，所谓常规的方法就是扫描硬盘、分区、光驱、USB等实际的物理介质。但是常规的方法
是肯定找不到安装介质的，因为实际的安装介质实际上是位于某个硬盘分区下、某个目录下的、某个 img文件。但是这个信息系统是不知道的。所以它一定找不到，就会报错，走不下去了。

Ventoy能启动liunx/chromeOS是因为Ventoy在启动时做了一些“手脚”，往系统里面插入了一些hook的脚本，这个脚本会在系统启动扫描安装介质的时候生效，让系统能够顺利找到“安装介质”。

而对于 MacOS来说，它不是开源的，而且对于它的启动过程我也完全不懂，想做“手脚”也做不了，加载dmg文件中的ESP分区启动这一步是简单的，但是后续的启动肯定还是会失败。

**Comment by xiagw** [comment]
可否启动 OpenCore

https://dortania.github.io/OpenCore-Install-Guide/prerequisites.html

https://github.com/acidanthera/OpenCorePkg
