### ISSUE TITLE
[issue]: 1440x900 resolution fix please

### ISSUE THREAD

**Issue by catalingrigoriev50** [ventoy/Ventoy#1084]
### Official FAQ

- [ ] I have checked the official FAQ.

### Ventoy Version

1.0.51

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

16

### Image file checksum (if applicable)

Yes.

### What happened?

On my 1440x900 screen, ventoy software is not full screen, is like middle of menu and black. Thanks

**Comment by ventoy** [comment]
A photo about it ?

**Comment by rakantoh** [comment]
i suggest to the developers that add to ventoy more support to more resolution screens, and support to 21:9 resolutions.
