### ISSUE TITLE
Cannot mount VTOYEFI partition under Windows

### ISSUE THREAD

**Issue by Silexium** [ventoy/Ventoy#1085]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.51

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64GB

### What happened?

The VTOYEFI partition cannot be mounted under Windows. Strangely, it can be mounted under WinRE & Linux without any issues.

![Screenshot 2021-08-30 174759](https://user-images.githubusercontent.com/87285693/131367509-72578a7a-310f-4e71-807b-fd5dd3b97d4c.png)

![Screenshot_2021-08-30_17-59-58](https://user-images.githubusercontent.com/87285693/131369334-ef17e436-3e61-4c5b-91fe-f0e13e380d0f.png)

The Event Viewer does not show any logs.

**Comment by steve6375** [comment]
The 2nd partition should have a label of VTOYEFI.
Diskpart does not show that label.
Maybe you have a fake USB Flash drive which does not have the full capacity of flash memory?

**Comment by Silexium** [comment]
> 
> 
> The 2nd partition should have a label of VTOYEFI.
> Diskpart does not show that label.
> Maybe you have a fake USB Flash drive which does not have the full capacity of flash memory?

I actually did a test with h2testw on this drive a while ago & there were no errors, so that can't be the case.

**Comment by steve6375** [comment]
How did you make the ventoy drive?
It should have a label and show as FAT in diskpart? The fact that it doesn't implies it is corrupt. Maybe you should retest it and then remake it or try ventoy update which will remake ptn 2.

**Comment by steve6375** [comment]
Ps. Are you using windows 10? Other versions don't see more than one partition on a flash drive!

**Comment by Silexium** [comment]
I just installed Ventoy 1.0.51 on a 16GB stick after running `clean` in diskpart & the VTOYEFI partition cannot be mounted on that drive as well. As for the 64GB drive, the data partition is formatted as NTFS. The 64GB drive works flawlessly, actually. It boots into Ventoy just fine, it's just that the VTOYEFI partition cannot be mounted under Windows for whatever reason. I'm running Windows 10 21H1 build 19043.1165.

**Comment by steve6375** [comment]
Can you try using a different windows 10 system?

**Comment by Silexium** [comment]
> 
> 
> Can you try using a different windows 10 system?

No, unfortunately. Can a VM work?

**Comment by steve6375** [comment]
You can try using VM and win10 diskpart

**Comment by Silexium** [comment]
OK, this is weird. If the disk is formatted as MBR, the VTOYEFI partition shows up & it can be mounted. However, when the details of the partition are viewed through `diskpart`, the partition type is reported as `EF` & there's nothing under the volumes view.

![Screenshot 2021-08-30 193701](https://user-images.githubusercontent.com/87285693/131382141-8761655d-3789-4819-84fc-994c454d6057.png)

![Screenshot 2021-08-30 193814](https://user-images.githubusercontent.com/87285693/131382162-a60d88d8-090d-4a96-97a5-9bfbf0d1b9e2.png)

**Comment by Silexium** [comment]
OK, this is weird. If the disk is formatted as MBR, the VTOYEFI partition shows up & it can be mounted. However, when the details of the partition are viewed through `diskpart`, the partition type is reported as `EF` & there's nothing under the volumes view.

![Screenshot 2021-08-30 193701](https://user-images.githubusercontent.com/87285693/131382141-8761655d-3789-4819-84fc-994c454d6057.png)

![Screenshot 2021-08-30 193814](https://user-images.githubusercontent.com/87285693/131382162-a60d88d8-090d-4a96-97a5-9bfbf0d1b9e2.png)

**Comment by Silexium** [comment]
The VTOYEFI partition cannot be mounted even in a VM.

**Comment by steve6375** [comment]
Maybe it's because it's gpt and is of type EF?

**Comment by Silexium** [comment]
> 
> 
> Maybe it's because it's gpt and is of type EF?

`EF` only appears if the disk is formatted as MBR. The ID of the VTOYEFI partition (GPT) is `ebd0a0a2-b9e5-4433-87c0-68b6b72699c7`

**Comment by ventoy** [comment]
A hidden attribute is set to the EFI partition table of the VTOYEFI partition.
So this will prevent some Windows version to access the VTOYEFI partition.
This is for the protection of the VTOYEFI partition.
VTOYEFI partition was designed for Ventoy internal use only and you'd better don't change it.

You can reserve some space at the end of the disk and create new ESP partition with the reserverd space as you want.

**Comment by niiiksh** [comment]
> A hidden attribute is set to the EFI partition table of the VTOYEFI partition. So this will prevent some Windows version to access the VTOYEFI partition. This is for the protection of the VTOYEFI partition. VTOYEFI partition was designed for Ventoy internal use only and you'd better don't change it.
> 
> You can reserve some space at the end of the disk and create new ESP partition with the reserverd space as you want.

@ventoy need access to VTOYEFI in GPT mode on windows https://github.com/ventoy/Ventoy/issues/2814
workaround is the only access VTOYEFI partition that it is already not internal use only, and MBR won't boot in UEFI.
