### ISSUE TITLE
[issue]: USB with Ventoy installed boots into GNU grub

### ISSUE THREAD

**Issue by umtcnyd** [ventoy/Ventoy#1086]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.51

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Image file checksum (if applicable)

No.

### What happened?

When I boot from my USB, instead of Ventoy ISO list I get the GNU grub command line. Can't go to the Ventoy menu using the cli either. Tried multiple times but to no avail.

**Comment by ventoy** [comment]
If this problem only appears in Legacy BIOS mode and can boot OK in UEFI mode, please refer:
https://www.ventoy.net/en/doc_legacy_limit.html

**Comment by umtcnyd** [comment]
Well, my motherboard doesn't support UEFI and can only boot in Legacy so I can't test that.

**Comment by ventoy** [comment]
So it must be a old computer and maybe have this problem.
https://www.ventoy.net/en/doc_legacy_limit.html

**Comment by ventoy** [comment]
You can reinstall Ventoy and reserve some space (e.g. 28GB) at the end of the USB and then test it to see whether it can boot to Ventoy's main menu.

**Comment by umtcnyd** [comment]
> So it must be a old computer and maybe have this problem.
> https://www.ventoy.net/en/doc_legacy_limit.html

In the link you sent, it says that the typical behaviour on a small capacity USB, like mine, doesn't have this problem. I have a 32GB capacity USB drive, as I mentioned in the issue. I'll try to reserve space about 4GB to see if it works.

**Comment by ventoy** [comment]
The big/small is relative.
From the Ventoy's user's feedback, there is some computer can not boot ok even if the USB stick is bigger than 8GB.
So you can reserve more space(e.g 30GB) just  to check that whether it can boot to Ventoy's main menu if Ventoy only use the first 1GB/2GB space.

**Comment by shawn8888** [comment]
This solution works for me!
My USB is only 16GB, but my computer is ASUS.EeeTop PC ET1602, which is 10+ yrs old and only support x86.
I just copy the ventoy folder with file ventoy.disk.img.xz to the USB drive and it can boot into ventoy perfectly now!

**Comment by ventoy** [comment]
Goo news.
