### ISSUE TITLE
建议增加修改EFI分区大小的选项

### ISSUE THREAD

**Issue by gujiangjiang** [ventoy/Ventoy#109]
默认的EFI分区太小了，有些时候EFI分区里面可能有Clover，Linux，OpenCore，Windows等很多引导项目，200M的EFI大小差不多，macOS和windows目前默认的EFI分区大小貌似都是200M，或者我建议增加一个选项能够自定义EFI分区容量的大小，不然后期还要手动的无损修改分区比较麻烦，其他的完美！

**Comment by ventoy** [comment]
这个在下一个 2.X 大版本中有规划。
