### ISSUE TITLE
./VentoyWeb.sh: line 104: ./tool/x86_64/V2DServer: No such file or directory[issue]: 

### ISSUE THREAD

**Issue by confbeltbuck** [ventoy/Ventoy#1092]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.51

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

256GB

### What happened?

./VentoyWeb.sh: line 104: ./tool/x86_64/V2DServer: No such file or directory

i just downloaded the latest one from github and i get this error, ive tried chmod +x on the file and changing the VentoyWeb.sh file to the specific location of the file which didnt work. thanks for any help.  disregard the bios and partition style stuff

**Comment by ventoy** [comment]
@confbeltbuck  
Any update?
