### ISSUE TITLE
[issue]: Ventoy won't boot to Windows 10 21H1 iso

### ISSUE THREAD

**Issue by Playertrip777** [ventoy/Ventoy#1094]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.51

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

15GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://www.microsoft.com/en-au/software-download/windows10ISO

### What happened?

When booting to Windows 10 iso, It will say for a split second "Boot to cd or dvd" before going to a black screen or restarting the laptop.
I also tried Winboot mode and it didnt work.

**Comment by steve6375** [comment]
Check file on usb drive is not corrupt. Check crc32 of file.
Try opening iso file on usb drive using 7zip and check contents.

**Comment by Playertrip777** [comment]
I checked the sha265sum and the contents of the iso
Everything seems okay i believe

**Comment by steve6375** [comment]
So this is Windows 10  64-bit ISO testing on a PC with a UEFI-64 BIOS?
Language?
Edition?
Architecture?  32 or 64 or both?

**Comment by Playertrip777** [comment]
Windows 10 English International 64-bit

**Comment by steve6375** [comment]
I would think many thousands of people have used Ventoy with that ISO. So I would suspect that there is a problem with your PC or your USB drive since it works for many other people. So try different systems to see if it UEFI64 boots to Windows Setup. If they all show the same problem, try a different USB drive.

**Comment by Playertrip777** [comment]
I think you are right. I tested in a virtual machine and the iso boot well. So i suspect it's something to do with my pc's hardware..

**Comment by lonelysoul** [comment]
来自与windows官网的windows 10 的ISO文件是不包含boot的程序的，所以用ventry才会报错。
