### ISSUE TITLE
[issue]: My Modify ventoy.json causing get "Syntax Error Detected in ventoy.json, Please Check!"

### ISSUE THREAD

**Issue by AnomSanjaya** [ventoy/Ventoy#1096]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.51

### What about latest release

No. I didn't try the latest release.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

64 GB

### Disk Manufacturer

SanDisk

### What happened?

Once day, im going to modify ventoy.json with following the Theme plugin guide first, the modification sucsessful!

But, while im modify again with adding strings following the autoinstall plugin and injection plugin, always get "Syntax Error Detected in ventoy.json, Please Check!" message while booting.

Maybe, u can check my modify json for where my fault in these json.

![image](https://user-images.githubusercontent.com/31486344/133016945-d7c280e4-073f-4ab7-8264-58a150153f15.png)

[Ventoy.zip](https://github.com/ventoy/Ventoy/files/7151063/Ventoy.zip)

**Comment by ventoy** [comment]
There are too many syntax errors in the json file. 
I suggest you to spend some time to learn the basic json syntax, it's very easy.
This is the right format:
```
{
    "theme_legacy":{
        "file":"/ventoy/themes/Ventoy-Dark/theme.txt",
        "gfxmode":"1024x768"
    },
    "theme_uefi":{
        "file":"/ventoy/themes/Ventoy-Dark/theme.txt",
        "gfxmode":"1366x768"
    },
    "theme_ia32":{
        "file":"/ventoy/themes/Ventoy-Dark/theme.txt",
        "gfxmode":"1366x768"
    },
    "theme_aa64":{
        "file":"/ventoy/themes/Ventoy-Dark/theme.txt",
        "gfxmode":"1366x768"
    },
    "theme_mips":{
        "file":"/ventoy/themes/Ventoy-Dark/theme.txt",
        "gfxmode":"1366x768"
    },
    "injection":[
        {
            "image":"04._Windows_XP_Professional_SP3_32bit.iso",
            "archive":"ventoy/drivers/DPMS_XP/DPMS.7z"
        },
        {
            "image":"07._Windows_8.1_Update_1_32bit.iso",
            "archive":"ventoy/drivers/EI/ei.zip"
        },
        {
            "image":"08._Windows_8.1_Update_1_64bit.iso",
            "archive":"ventoy/drivers/EI/ei.zip"
        }
    ],
    "auto_install":[
        {
            "image":"08._Windows_8.1_Update_1_64bit.iso",
            "template":"/ventoy/unattended/unattended_w81_64bit.xml"
        },
        {
            "image":"08._Windows_8.1_Update_1_32bit.iso",
            "template":"/ventoy/unattended/unattended_w81_32bit.xml"
        }
    ]
}
```
