### ISSUE TITLE
建议：增加镜像文件的备注说明功能

### ISSUE THREAD

**Issue by liyxxx** [ventoy/Ventoy#1097]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.51

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

128G

### What happened?

我现在把Ventoy当做日常维护工具使用，经常各种装机，所以里面拷贝了十几个iso文件。有些iso功能很接近，只能靠文件名来区分。一是不方便，二是能表达的内容有限。因此，我希望能针对每个iso文件做出详细的说明，选择iso的时候在旁边窗口可以显示说明内容。最后，感谢大大们开发出如此神器，谢谢！

**Comment by steve6375** [comment]
Why not rename the iso files?

**Comment by liyxxx** [comment]
靠文件名说明的信息量很少，而且文件名太长也不便阅读啊。比如我有几个win10的镜像，分别包含了不同的驱动及软件，要备注的信息较多时，通过文件名并不方便啊。

**Comment by steve6375** [comment]
Maybe ventoy could also detect .txt files which have same name as iso and if user presses ctrl+h they see contents of txt file?  Would that help?

**Comment by liyxxx** [comment]
差不多就是这个意思，其实不需要ctrl+h，弄个同名的txt文件，下边开个窗口直接显示就行了，就象Ghost那样。

**Comment by ventoy** [comment]
大概可以类似这种：
![image](https://user-images.githubusercontent.com/59477474/133618907-4066b95e-f81d-4808-9c85-a477df7325b5.png)

**Comment by ventoy** [comment]
@liyxxx 
可以测试下1.0.53版本的 `菜单提示` 插件功能 https://www.ventoy.net/cn/plugin_menutip.html
