### ISSUE TITLE
Need clarification about changing theme

### ISSUE THREAD

**Issue by prog-amateur2** [ventoy/Ventoy#110]
Hello, I have read the [website](https://www.ventoy.net/en/plugin_theme.html) plugin section and the [issue here](https://github.com/ventoy/Ventoy/issues/77). 

But I still don't understand where to put files. Let's imagine that I have downloaded a new theme from Gnome-look, I have a folder and many files (not only `theme.txt`). 

1. Where/when should I put those files (Ventoy release folder, USB stick, before, after install script) ? 
2. Where can I edit the theme object ? 

Thank you very much for your kind help.

**Comment by ventoy** [comment]
After install ventoy to you USB drive.
You create a ventoy directory in the first partition (exfat)  and put a ventoy.json under the ventoy directory. Set the configuration about the theme path in the json file.
And the theme directory you download should also put under the ventoy directory.

**Comment by prog-amateur2** [comment]
Thank you very much, I appreciate your quick and clear support !
I have followed your instructions and now I can enjoy ventoy with customized grub interface. I close this issue as it is solved. 
Thank you again.
