### ISSUE TITLE
Booting Windows Based Images From Ventoy Works But Not Linux Images From UEFI On Intel NUC

### ISSUE THREAD

**Issue by TuckerEck** [ventoy/Ventoy#1101]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.52

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://ubuntu.com/download/desktop/thank-you?version=20.04.3&architecture=amd64
https://ubuntu.com/download/desktop/thank-you?version=21.04&architecture=amd64
https://cdimage.ubuntu.com/kubuntu/releases/20.04.3/release/kubuntu-20.04.3-desktop-amd64.iso
https://cdimage.ubuntu.com/kubuntu/releases/21.04/release/kubuntu-21.04-desktop-amd64.iso

### What happened?

Device Is A Intel NUC10i3FNK With 1TB Crucial P2 NVME SSD and 16GB Dual Rank 2x8 DDR4 2666MHZ

My USB 32GB SanDisk Drive Setup is Using Secure Boot with GPT and NTFS Since Ubuntu Does Not Support EXFAT Drives. Secure Boot Key Was Imported Using the Guide On Ventoy's Website. When Booting Ubuntu Images In UEFI in Secure Boot Mode It Gives Me A Black Screen and Booting Ventoy in UEFI Changes My Resolution to A Very Low Quality When My Theme Is Running 3840x2160 For My 4K Monitor.
Booting In Legacy Works Fine And The Resolution Is Normal Which Is At 4K. Booting Windows ISO Works Fine While Booting In UEFI Secure Boot & Legacy Boot. But The Image Quality Still Looks Crap While Booting Windows ISOs In UEFI.

-Thanks, Tucker Eck

**Comment by ventoy** [comment]
For Linux please try: 
press `ctrl+r` to enter grub2 mode and then select the ISO file to boot.

**Comment by TuckerEck** [comment]
Crtl-R Solved The Issue. Thanks For Your Help
