### ISSUE TITLE
分区预留空间磁盘损坏

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#1107]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.52

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128GB

### Disk Manufacturer

SAMSUNG

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

官网

### What happened?

A bug happened!
![1](https://user-images.githubusercontent.com/69227436/133919763-b640485f-be16-488e-bb2c-2864f61eb064.png)

![2](https://user-images.githubusercontent.com/69227436/133919768-cea206d2-02fb-4f5c-940f-0097cfa48133.png)

![3](https://user-images.githubusercontent.com/69227436/133919773-4cbf5e23-cc69-4df0-91fb-00ac1b5b29e4.png)

**Comment by ventoy** [comment]
正常情况下U盘应该会显示出厂商名称，比如：
![image](https://user-images.githubusercontent.com/59477474/133933573-3480d3ed-fc5d-4c2d-8309-ee32503ab4dc.png)

从Ventoy收到的很多反馈情况来看，显示这种 VendorCoProductCode 的大部分都是山寨U盘。不说100%也基本上有95%以上。
所以建议你网上找一些工具对U盘做一个全面的检测。
