### ISSUE TITLE
[issue]: ventoy installed usb stick not supported in Android otg drive

### ISSUE THREAD

**Issue by ProgrammingPlanet** [ventoy/Ventoy#1108]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.51

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GB

### Image file checksum (if applicable)

No.

### What happened?

usb storage with ventoy installed on it supported on both windows 10/7 and linux based os. but what about android os? kindly add support for android os when i plug it into android device as OTG drive.

**Comment by ventoy** [comment]
It depend on whether the android OS support the file system.
Ventoy only divide the USB into 2 partitions and format the main partition in exfat filesystem by default.
You can also reformat the main partition to FAT32 or NTFS filesystem as long as the android OS supports.
So if your android OS can support exfat/FAT32/NTFS file system then it can support Ventoy.

**Comment by ProgrammingPlanet** [comment]
My bad, I figured it out before reading your reply.

By the way, thanks for this awesome tool 🤗

**Comment by user4302** [comment]
Hi, I'm facing this same issue, @ProgrammingPlanet how did you solve this issue?
