### ISSUE TITLE
[issue]: Debian 11 not booting.

### ISSUE THREAD

**Issue by Ohio2** [ventoy/Ventoy#1111]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.52

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64GB

### Disk Manufacturer

Kingston

### Image file checksum (if applicable)

No.

### Image file download link (if applicable)

https://www.debian.org

### What happened?

`error: invalid magic number.`
`error: you need to load a kernel.`
When selecting any option.
(netinst)

**Comment by ventoy** [comment]
Check the ISO file on Ventoy's main menu as follows to make sure that the ISO file is not corrupted:
https://www.ventoy.net/en/faq.html#faq_boot_checksum

I download `debian-11.0.0-amd64-netinst.iso` with `sha256sum: ae6d563d2444665316901fe7091059ac34b8f67ba30f9159f7cef7d2fdc5bf8a` and it boot OK.

![image](https://user-images.githubusercontent.com/59477474/134792263-34b47118-35af-44fe-aba4-701d430bb767.png)

**Comment by Ohio2** [comment]
That is not what i meant, the GRUB in the debian iso upon selecting anything displays the error.

**Comment by Ohio2** [comment]
Well, the issue shifts to that of:
Debian can not copy netinst files

**Comment by ventoy** [comment]
If the ISO file is corrupted during you copy it to the USB stick, it may display the error.
So I suggest you to checksum the ISO file in the USB stick to make sure of that.
Did you checksum the ISO file in the USB stick as above picture? Is the sha1sum value correct?

**Comment by ventoy** [comment]
Did you copy the ISO file to the USB stick in Windows or in Linux ?

**Comment by Ohio2** [comment]
Linux, yes the sha1sum is correct.

**Comment by Ohio2** [comment]
Actually
it would seem like you guys fixed it, thanks
