### ISSUE TITLE
ARM及MIPS架构机器兼容

### ISSUE THREAD

**Issue by Seryta** [ventoy/Ventoy#112]
我本身现在主要工作是测试，经常需要装系统，但是是X86、ARM、MIPS三种架构都要用。现在的Ventory看着是只支持X86的对吧？请问后续有进一步拓展，支持不同架构机器的想法吗？

**Comment by ventoy** [comment]
ARM64 有可能会支持，但是MIPS有点太小众了吧。
另外问一下，你当前 ARM 和 MIPS 是怎么装系统的， 经常安装的是哪些系统。

**Comment by Seryta** [comment]
> ARM64 有可能会支持，但是MIPS稍微小众了一点。
> 另外问一下，你当前 ARM 和 MIPS 是怎么装系统的， 经常安装的是哪些系统。
> 

目前主要装的系统是UOS统信的系统，不清楚你了不了解，deepin的新东家。它有三个平台的系统，有桌面版和服务器版，还有一些它的分支定制系统，包括今天直播发布的个人版系统。
装系统采用的是deepin一脉相承的自带启动器制作程序，系统预装，任一平台的此程序可以制作3个架构的启动盘。目前UOS所有版本的系统，都可以通过那一个程序制作启动盘。

**Comment by ventoy** [comment]
最新版本已经支持。
