### ISSUE TITLE
[issue]: Untangle install fails when used with Ventoy

### ISSUE THREAD

**Issue by asheroto** [ventoy/Ventoy#1120]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.53

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

256GB

### Disk Manufacturer

Samsung

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://mega.nz/file/jLwUGR4Y#AY-DwykMgqjAzwsgOaNJIU3ba_uWnfXayPhsC4CHgwU

### What happened?

Hello,

When trying to install Untangle while residing on a Ventoy drive, it fails with the below error message.  Using the exact same ISO with Rufus direct to a USB flash drive the install succeeds without any issues.

I have tried 3 versions of Untangle and each fail with similar messages when on a Ventoy drive.  Pressing F2 for memory mode gives a different error message when failing.

![image](https://user-images.githubusercontent.com/49938263/136198519-7d667be4-6055-47f4-a996-702dc22ff7a0.png)

Thank you

**Comment by ventoy** [comment]
Any update ? @asheroto

**Comment by asheroto** [comment]
Success! It worked!

During this process I [ended up writing an article](https://asheroto.medium.com/how-to-actually-pass-thru-a-usb-flash-drive-to-a-hyper-v-server-not-volume-pass-thru-not-3d3c3a669dd5) about USB flash drives in Hyper-V, gave a shout-out to Ventoy, in case you're interested.

Thanks for working on this.
