### ISSUE TITLE
[issue]: Update Ventoy from 1.0.27 to 1.0.53 failed

### ISSUE THREAD

**Issue by olekstomek** [ventoy/Ventoy#1126]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.53

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

Kingston DataTraveler

### What happened?

Update Ventoy from 1.0.27 to 1.0.53 failed.

![ventoy](https://user-images.githubusercontent.com/26818304/136453079-ed924358-2ab3-401e-b073-9af6d159befe.JPG)

> [2021/10/07 21:33:56.657] 
> ################################ Ventoy2Disk 1.0.0.2 ################################
> [2021/10/07 21:33:56.658] Control Flag: 0 1 1
> [2021/10/07 21:33:56.667] Windows Version : Windows 10 64-bit (Build 19042)
> [2021/10/07 21:33:56.674] 
> ===================== Enum All PhyDrives =====================
> [2021/10/07 21:33:56.682] RegOpenKeyExA <SYSTEM\CurrentControlSet\Services\disk\Enum> Ret:0
> [2021/10/07 21:33:56.687] RegQueryValueExA <Count> ret:0  Size:4 Value:2
> [2021/10/07 21:33:56.693] GetPhysicalDriveCount: 2
> [2021/10/07 21:33:56.701] Logical Drives: 0x1c
> [2021/10/07 21:33:56.707] LogicalDrive:\\.\C: PhyDrive:0 Offset:672137216 ExtentLength:252827402240
> [2021/10/07 21:33:56.713] C --> 0
> [2021/10/07 21:33:56.719] LogicalDrive:\\.\D: PhyDrive:1 Offset:1048576 ExtentLength:30909392896
> [2021/10/07 21:33:56.725] D --> 1
> [2021/10/07 21:33:56.733] LogicalDrive:\\.\E: PhyDrive:1 Offset:30910441472 ExtentLength:33554432
> [2021/10/07 21:33:56.738] E --> 1
> [2021/10/07 21:33:56.749] Create file Handle:00000178 \\.\PhysicalDrive0 status:0
> [2021/10/07 21:33:56.750] PHYSICALDRIVE0 size 256060514304 bytes
> [2021/10/07 21:33:56.765] Create file Handle:0000017C \\.\PhysicalDrive1 status:0
> [2021/10/07 21:33:56.765] PHYSICALDRIVE1 size 30943995904 bytes
> [2021/10/07 21:33:56.772] PhyDrv:0 BusType:RAID Removable:0 Size:256GB(256060514304) Name: PC611 NVMe SK hynix 256GB
> [2021/10/07 21:33:56.778] PhyDrv:1 BusType:USB  Removable:1 Size:32GB(30943995904) Name:Kingston DataTraveler 3.0
> [2021/10/07 21:33:56.783] LogicalDrive:\\.\C: PhyDrive:0 Offset:672137216 ExtentLength:252827402240
> [2021/10/07 21:33:56.788] Logical Drive:C  ===> PhyDrive:0
> [2021/10/07 21:33:56.793] LogicalDrive:\\.\D: PhyDrive:1 Offset:1048576 ExtentLength:30909392896
> [2021/10/07 21:33:56.799] Logical Drive:D  ===> PhyDrive:1
> [2021/10/07 21:33:56.804] LogicalDrive:\\.\E: PhyDrive:1 Offset:30910441472 ExtentLength:33554432
> [2021/10/07 21:33:56.809] Logical Drive:E  ===> PhyDrive:1
> [2021/10/07 21:33:56.819] Create file Handle:00000188 \\.\PhysicalDrive1 status:0
> [2021/10/07 21:33:56.824] Read MBR Ret:1 Size:512 code:183
> [2021/10/07 21:33:56.830] =========== Partition Table 1 ============
> [2021/10/07 21:33:56.835] PartTbl.Active = 0x80
> [2021/10/07 21:33:56.842] PartTbl.FsFlag = 0x7
> [2021/10/07 21:33:56.850] PartTbl.StartSectorId = 2048
> [2021/10/07 21:33:56.858] PartTbl.SectorCount = 60369908
> [2021/10/07 21:33:56.867] PartTbl.StartHead = 32
> [2021/10/07 21:33:56.874] PartTbl.StartSector = 33
> [2021/10/07 21:33:56.883] PartTbl.StartCylinder = 0
> [2021/10/07 21:33:56.890] PartTbl.EndHead = 250
> [2021/10/07 21:33:56.901] PartTbl.EndSector = 1
> [2021/10/07 21:33:56.911] PartTbl.EndCylinder = 685
> [2021/10/07 21:33:56.919] =========== Partition Table 2 ============
> [2021/10/07 21:33:56.934] PartTbl.Active = 0x0
> [2021/10/07 21:33:56.943] PartTbl.FsFlag = 0xef
> [2021/10/07 21:33:56.955] PartTbl.StartSectorId = 60371956
> [2021/10/07 21:33:56.965] PartTbl.SectorCount = 65536
> [2021/10/07 21:33:56.972] PartTbl.StartHead = 250
> [2021/10/07 21:33:56.978] PartTbl.StartSector = 2
> [2021/10/07 21:33:56.988] PartTbl.StartCylinder = 685
> [2021/10/07 21:33:56.996] PartTbl.EndHead = 15
> [2021/10/07 21:33:57.005] PartTbl.EndSector = 17
> [2021/10/07 21:33:57.014] PartTbl.EndCylinder = 690
> [2021/10/07 21:33:57.021] =========== Partition Table 3 ============
> [2021/10/07 21:33:57.028] PartTbl.Active = 0x0
> [2021/10/07 21:33:57.036] PartTbl.FsFlag = 0x0
> [2021/10/07 21:33:57.042] PartTbl.StartSectorId = 0
> [2021/10/07 21:33:57.051] PartTbl.SectorCount = 0
> [2021/10/07 21:33:57.057] PartTbl.StartHead = 0
> [2021/10/07 21:33:57.066] PartTbl.StartSector = 0
> [2021/10/07 21:33:57.073] PartTbl.StartCylinder = 0
> [2021/10/07 21:33:57.080] PartTbl.EndHead = 0
> [2021/10/07 21:33:57.086] PartTbl.EndSector = 0
> [2021/10/07 21:33:57.092] PartTbl.EndCylinder = 0
> [2021/10/07 21:33:57.100] =========== Partition Table 4 ============
> [2021/10/07 21:33:57.105] PartTbl.Active = 0x0
> [2021/10/07 21:33:57.113] PartTbl.FsFlag = 0x0
> [2021/10/07 21:33:57.119] PartTbl.StartSectorId = 0
> [2021/10/07 21:33:57.125] PartTbl.SectorCount = 0
> [2021/10/07 21:33:57.131] PartTbl.StartHead = 0
> [2021/10/07 21:33:57.137] PartTbl.StartSector = 0
> [2021/10/07 21:33:57.142] PartTbl.StartCylinder = 0
> [2021/10/07 21:33:57.148] PartTbl.EndHead = 0
> [2021/10/07 21:33:57.153] PartTbl.EndSector = 0
> [2021/10/07 21:33:57.158] PartTbl.EndCylinder = 0
> [2021/10/07 21:33:57.165] PhysicalDrive1 is ventoy disk
> [2021/10/07 21:33:57.171] QueryDosDeviceA success \Device\Harddisk1\DR1
> [2021/10/07 21:33:57.177] [0] CreateFileA \\.\PhysicalDrive1 code:0 00000190
> [2021/10/07 21:33:57.183] Parse FAT fs...
> [2021/10/07 21:33:57.188] attach media success...
> [2021/10/07 21:33:57.202] GetVentoyVerInPhyDrive rc=0...
> [2021/10/07 21:33:57.203] VentoyVerInPhyDrive 1 is <1.0.27>...
> [2021/10/07 21:33:57.211] PhyDrive 1 is Ventoy Disk ver:1.0.27 SecureBoot:0
> [2021/10/07 21:33:57.215] < PC611 NVMe SK hynix 256GB> is filtered for not USB type.
> [2021/10/07 21:33:57.293] Load languages from json file ...
> [2021/10/07 21:33:57.294] language json file len:150302 json parse:0
> [2021/10/07 21:33:57.301] Total 39 languages ...
> [2021/10/07 21:33:57.383] Combox select change, update secure boot option: 0 0
> [2021/10/07 21:34:33.650] UpdateVentoy2PhyDrive MBR PhyDrive1 <<Kingston DataTraveler 3.0 32GB>>
> [2021/10/07 21:34:33.652] Lock disk for umount ............................ 
> [2021/10/07 21:34:33.656] QueryDosDeviceA success \Device\Harddisk1\DR1
> [2021/10/07 21:34:33.671] [0] CreateFileA \\.\PhysicalDrive1 code:0 000002E8
> [2021/10/07 21:34:33.672] FSCTL_LOCK_VOLUME success
> [2021/10/07 21:34:33.678] MBR StartSector in PartTbl:60371956
> [2021/10/07 21:34:33.685] MBR Reserved Disk Space:0 MB
> [2021/10/07 21:34:33.690] LogicalDrive:\\.\C: PhyDrive:0 Offset:672137216 ExtentLength:252827402240
> [2021/10/07 21:34:33.695] LogicalDrive:\\.\D: PhyDrive:1 Offset:1048576 ExtentLength:30909392896
> [2021/10/07 21:34:33.703] D: is belong to phydrive1
> [2021/10/07 21:34:33.708] LogicalDrive:\\.\E: PhyDrive:1 Offset:30910441472 ExtentLength:33554432
> [2021/10/07 21:34:33.713] E: is belong to phydrive1
> [2021/10/07 21:34:33.721] E:\ is ventoy logical drive
> [2021/10/07 21:34:33.725] Delete mountpoint E:\ ret:1 code:0
> [2021/10/07 21:34:33.737] Lock disk for update ............................ 
> [2021/10/07 21:34:33.739] QueryDosDeviceA success \Device\Harddisk1\DR1
> [2021/10/07 21:34:33.746] [0] CreateFileA \\.\PhysicalDrive1 code:0 000002EC
> [2021/10/07 21:34:33.751] Opened \\.\PhysicalDrive1 for exclusive write access
> [2021/10/07 21:34:33.758] FSCTL_LOCK_VOLUME success
> [2021/10/07 21:34:33.764] Lock volume for update .......................... 
> [2021/10/07 21:34:33.769] GetVentoyVolumeName PhyDrive 1 SectorStart:60371956 PartOffset:30910441472
> [2021/10/07 21:34:33.775] Find volume:\\?\Volume{2089a6ff-96d1-45b7-8e48-3e65d5015131}\
> [2021/10/07 21:34:33.780] IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS bRet:1 code:0
> [2021/10/07 21:34:33.785] NumberOfDiskExtents:1 DiskNumber:0
> [2021/10/07 21:34:33.790] This volume DiskNumber:0 offset:672137216
> [2021/10/07 21:34:33.795] Find volume:\\?\Volume{61db6e26-7e16-46ba-b549-0845b3a1c1e0}\
> [2021/10/07 21:34:33.801] IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS bRet:1 code:0
> [2021/10/07 21:34:33.806] NumberOfDiskExtents:1 DiskNumber:0
> [2021/10/07 21:34:33.812] This volume DiskNumber:0 offset:253499539456
> [2021/10/07 21:34:33.818] Find volume:\\?\Volume{7393b398-2040-11eb-b088-94e70bc4f544}\
> [2021/10/07 21:34:33.823] IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS bRet:1 code:0
> [2021/10/07 21:34:33.830] NumberOfDiskExtents:1 DiskNumber:1
> [2021/10/07 21:34:33.836] This volume DiskNumber:1 offset:1048576
> [2021/10/07 21:34:33.842] Find volume:\\?\Volume{d380e4a7-bc57-11eb-b118-cc483a6282a5}\
> [2021/10/07 21:34:33.850] IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS bRet:1 code:0
> [2021/10/07 21:34:33.855] NumberOfDiskExtents:1 DiskNumber:1
> [2021/10/07 21:34:33.861] This volume DiskNumber:1 offset:30910441472
> [2021/10/07 21:34:33.867] This volume match
> [2021/10/07 21:34:33.872] GetVentoyVolumeName return 0
> [2021/10/07 21:34:33.877] Now lock and dismount volume <\\?\Volume{d380e4a7-bc57-11eb-b118-cc483a6282a5}>
> [2021/10/07 21:34:33.884] Failed to create file volume, errcode:32
> [2021/10/07 21:34:33.890] FindProcessOccupyDisk for PhyDrive 1
> [2021/10/07 21:34:33.896] QueryDosDeviceA success \Device\Harddisk1\DR1
> [2021/10/07 21:34:34.088] NOTE: Could not identify the process(es) or service(s) accessing \Device\Harddisk1\DR1
> [2021/10/07 21:34:34.089] This time update failed, now wait and retry...
> [2021/10/07 21:34:44.109] Now retry to update...
> [2021/10/07 21:34:44.109] UpdateVentoy2PhyDrive MBR PhyDrive1 <<Kingston DataTraveler 3.0 32GB>>
> [2021/10/07 21:34:44.115] Lock disk for umount ............................ 
> [2021/10/07 21:34:44.120] QueryDosDeviceA success \Device\Harddisk1\DR1
> [2021/10/07 21:34:44.128] [0] CreateFileA \\.\PhysicalDrive1 code:0 000002EC
> [2021/10/07 21:34:44.133] FSCTL_LOCK_VOLUME success
> [2021/10/07 21:34:44.137] MBR StartSector in PartTbl:60371956
> [2021/10/07 21:34:44.143] MBR Reserved Disk Space:0 MB
> [2021/10/07 21:34:44.149] LogicalDrive:\\.\C: PhyDrive:0 Offset:672137216 ExtentLength:252827402240
> [2021/10/07 21:34:44.154] LogicalDrive:\\.\D: PhyDrive:1 Offset:1048576 ExtentLength:30909392896
> [2021/10/07 21:34:44.159] D: is belong to phydrive1
> [2021/10/07 21:34:44.166] Lock disk for update ............................ 
> [2021/10/07 21:34:44.170] QueryDosDeviceA success \Device\Harddisk1\DR1
> [2021/10/07 21:34:44.177] [0] CreateFileA \\.\PhysicalDrive1 code:0 000002EC
> [2021/10/07 21:34:44.182] Opened \\.\PhysicalDrive1 for exclusive write access
> [2021/10/07 21:34:44.188] FSCTL_LOCK_VOLUME success
> [2021/10/07 21:34:44.195] Lock volume for update .......................... 
> [2021/10/07 21:34:44.200] GetVentoyVolumeName PhyDrive 1 SectorStart:60371956 PartOffset:30910441472
> [2021/10/07 21:34:44.205] Find volume:\\?\Volume{2089a6ff-96d1-45b7-8e48-3e65d5015131}\
> [2021/10/07 21:34:44.212] IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS bRet:1 code:0
> [2021/10/07 21:34:44.217] NumberOfDiskExtents:1 DiskNumber:0
> [2021/10/07 21:34:44.222] This volume DiskNumber:0 offset:672137216
> [2021/10/07 21:34:44.228] Find volume:\\?\Volume{61db6e26-7e16-46ba-b549-0845b3a1c1e0}\
> [2021/10/07 21:34:44.234] IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS bRet:1 code:0
> [2021/10/07 21:34:44.239] NumberOfDiskExtents:1 DiskNumber:0
> [2021/10/07 21:34:44.245] This volume DiskNumber:0 offset:253499539456
> [2021/10/07 21:34:44.250] Find volume:\\?\Volume{7393b398-2040-11eb-b088-94e70bc4f544}\
> [2021/10/07 21:34:44.256] IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS bRet:1 code:0
> [2021/10/07 21:34:44.262] NumberOfDiskExtents:1 DiskNumber:1
> [2021/10/07 21:34:44.267] This volume DiskNumber:1 offset:1048576
> [2021/10/07 21:34:44.273] Find volume:\\?\Volume{d380e4a7-bc57-11eb-b118-cc483a6282a5}\
> [2021/10/07 21:34:44.279] IOCTL_VOLUME_GET_VOLUME_DISK_EXTENTS bRet:1 code:0
> [2021/10/07 21:34:44.284] NumberOfDiskExtents:1 DiskNumber:1
> [2021/10/07 21:34:44.289] This volume DiskNumber:1 offset:30910441472
> [2021/10/07 21:34:44.295] This volume match
> [2021/10/07 21:34:44.301] GetVentoyVolumeName return 0
> [2021/10/07 21:34:44.306] Now lock and dismount volume <\\?\Volume{d380e4a7-bc57-11eb-b118-cc483a6282a5}>
> [2021/10/07 21:34:44.312] Failed to create file volume, errcode:32
> [2021/10/07 21:34:44.318] FindProcessOccupyDisk for PhyDrive 1
> [2021/10/07 21:34:44.324] QueryDosDeviceA success \Device\Harddisk1\DR1
> [2021/10/07 21:34:44.502] NOTE: Could not identify the process(es) or service(s) accessing \Device\Harddisk1\DR1
> [2021/10/07 21:34:47.492] Combox select change, update secure boot option: 0 0

**Comment by ventoy** [comment]
@olekstomek @khaosmaou  What about update to 1.0.55?

**Comment by olekstomek** [comment]
@ventoy it works and I updated successfully. I downgraded Ventoy to 1.0.27 and updated to 1.0.55 again, 
![image](https://user-images.githubusercontent.com/26818304/137643280-dc038b4b-5292-4cae-a06c-ef035a05de97.png)

So I'm closing this issue. Thanks.
