### ISSUE TITLE
[Feature]: Add support for custom partitions or let me config ventoy partition start&end sectors.

### ISSUE THREAD

**Issue by creky** [ventoy/Ventoy#1139]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.54

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32GB

### What happened?

Hi, I need a feature to use custom ventoy partitions,  and install ventoy to the specified partition instead of format whole disk, as the disk had many files to hard to move to another storage area. Or give a config on efi partition, even let me config each ventoy partition start sector and end sector, that's fine. Thanks!

**Comment by Creky** [comment]
I really need more partition support. As fat32 format 4GB limitation, the 1st partition can't store windows10.iso. The partition format  is not allowed to change.

**Comment by Creky** [comment]
> The first partition is exFAT by default. You can use >4GB files on exFAT or reformat to NTFS

exFAT format  is not worked on linux based system default. Like android etc, but android based system is used for many many devices. There is an only choice fat32 format.
