### ISSUE TITLE
[issue]: Unable to boot Ventoy USB?

### ISSUE THREAD

**Issue by GreenMan36** [ventoy/Ventoy#1142]
### Official FAQ

- [x] I have checked the official FAQ.

### Ventoy Version

1.0.54

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

No.

### Image file download link (if applicable)

https://ftp.nluug.nl/os/Linux/distr/ubuntu-releases/21.10/ubuntu-21.10-desktop-amd64.iso

### What happened?

So I've got 2 laptops and a desktop.
I just followed the instructions I found online.
I run the Ventoy installer + Safemode support, drop in my ISO file and try to boot into it.
One laptop has safeboot on, one does not.
Both laptops and my Desktops don't even seem to boot into the USB at all even when I put it at the top of my boot order or manually boot into it via my UEFI boot menu.

They all just boot into the main OS every time. Although when writing the Ubuntu ISO it does boot into it.
But I want to create a multi boot USB using Ventoy, hope ya'll can help me.

**Comment by GreenMan36** [comment]
Thanks that fixed it for me, could you explain my why this happened and close the issue?

**Comment by ventoy** [comment]
Although it is not common, but it does exist some kind of  motherboard that only boot USB with GPT partition style in UEFI mode and denied to boot USB with MBR partition style.
As noted in the document: https://www.ventoy.net/en/doc_mbr_vs_gpt.html

Some details about your laptop/pc? (manufacturer/brand...)

**Comment by GreenMan36** [comment]
Hi yeah there's actually 3 devices.

A Lenovo Legion Y520, crappy gtx 1050 2gb version. (Latest bios)
A Lenovo Yoga 530, 2500u I think (terrible laptop gen has a cpu battery problem, don't ever get 2000 gen) using an older bios because newer versions lock the CPU clock at 0.38gh below 20% battery, which is unusable. (below 8MCN52WW fixes it, I'm using 8MCN50WW)
And my custom built PC, 3700x, Gigabyte x570 Aorus ULTRA, wifi 6 motherboard. (Latest bios)

They all had issues until I used GPT even with or without safe boot.

In case the above details weren't enough the specific USB drive is `sdcz48-032g`.
