### ISSUE TITLE
[SOLVED]: NOT working with pyabr and refracta

### ISSUE THREAD

**Issue by pigeonskiller** [ventoy/Ventoy#1145]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.54

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

64GB

### Disk Manufacturer

SanDisk

### Image file download link (if applicable)

https://github.com/PyFarsi/pyabr/releases/download/v2.0.2/pyabr-x86_64.iso and https://get.refracta.org/files/testing/refracta_11-beta_xfce_i386-20210911_1403.iso

### What happened?

Hi developers,

sorry to inform you that Ventoy does NOT work with pyabr-x86_64.iso (based on Debian 10) and refracta_11-beta_xfce_i386-20210911_1403.iso (based on Devuan).

Seems they do not find a UEFI system.

Hope you solve soon.

Thanks and have a nice day.

**Comment by ventoy** [comment]
1.  `pyabr-x86_64.iso`
This iso file itself does not support UEFI mode. So you can not boot it in UEFI mode. It's the problem of the ISO file itself.
You can use the latest Ventoy-1.0.55 to boot it in Legacy BIOS mode.

2. `refracta_11-beta_xfce_i386-20210911_1403.iso`
This ISO file is 32bit and 32bit Linux can NOT support x86_64 UEFI. Your computer is obviously x86_64 UEFI.
You can only boot it in Legacy BIOS mode. If you want to use UEFI mode, you shoule download `refracta_11-beta_xfce_amd64-20210911_1403.iso`
Ventoy can boot it fine.

**Comment by ventoy** [comment]
@pigeonskiller  Any update?
