### ISSUE TITLE
[issue]: Fedora 34 persistence

### ISSUE THREAD

**Issue by N214** [ventoy/Ventoy#1146]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.54

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

32

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### What happened?

Hello, 

I'm trying fedora 34 with persistence but had the following error
`sh write error invalid argument `
and couldn't boot the iso. 

Tried with and without the selinux=0 argument on the start screen. And the persistence file has been downloaded from the repo.

**Comment by ventoy** [comment]
Can fedora 33 work? (e.g. Fedora-Workstation-Live-x86_64-33-1.2.iso)

**Comment by N214** [comment]
I had the selinux=0 put on the wrong line, working now.
