### ISSUE TITLE
[issue]: Time stamp is in the future

### ISSUE THREAD

**Issue by utuhiro78** [ventoy/Ventoy#1147]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.54

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

16GB

### What happened?

Time stamp is in the future.

```
mkdir -p tmp_arch
cd tmp_arch/
wget https://github.com/ventoy/Ventoy/releases/download/v1.0.54/ventoy-1.0.54-linux.tar.gz
LANG=C tar xf ventoy-1.0.54-linux.tar.gz
```

=> tar: ./ventoy-1.0.54: time stamp 2021-12-12 19:13:50 is 4879151 s in the future

Thank you for developing Ventoy. I can select ISO files in a USB stick!

**Comment by ventoy** [comment]
This is a mistake. I have a linux server and its datetime was incorrect from sometime.
I have released latest 1.0.55 which has no time problem.
