### ISSUE TITLE
[issue]: after version 12,updated versions doesn't work with winpe like (sergei,nkboot,nhvboot,..) on old laptop

### ISSUE THREAD

**Issue by amirbahalegharn** [ventoy/Ventoy#1150]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.55

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

64

### Disk Manufacturer

sandisk,unitek 3.1 reader,hp

### Image file checksum (if applicable)

Yes.

### What happened?

after the releases of 0.12 version, no other version support booting "winpe"s like sergei strelec,nhvboot,nkboot,... ; all goes to blinking line after selecting the iso on the list. i've used different memory(64-128-256) on my reader(type-c-3.1 full speed) and even hp&sandisk flashdisk but the same outcome. i'm using "dell 1501" from 2016(bios latest dec2017) which doesn't have secure boot or "eufi" option even there. i heard that some of my friends who are also technicians, told me ventoy wasn't working for them on some of their old devices that customers has brought to them so sth has changed since version 12 which is making the issue, please if possible, fix it in the next version so that me -& probably some others - could also enjoy the latest version with their features.
thanks in advance

**Comment by ventoy** [comment]
1. Only this computer has the problem? Other new computer boot ok with the same ISO file?
2. Only winpe's like ISO has the problem on the computer? Linux ISO (e.g. Ubuntu/Arch has no problem?)
3. Can standard Windows install ISO boot OK (e.g. Win10)?
3. Please do some test (test each of them one by one) and give me the result:
    a) Press `ctrl+i` firstly and then select the ISO file and boot.
    b) Press `F1` firstly and then select the ISO file and boot.
    c) For standard Windows install ISO, press `ctrl+w` firstly and then select the ISO file and boot.

**Comment by amirbahalegharn** [comment]
1-all pcs&laptops works but those time that it doesn't, I have to update it to earlier versions(12 below) to make it work & usually they are older generations.
2-linux works(zorin,solos,windowsfx)
3-windows iso also doesn't work(tested 5 different win10-11-7)
4-
a)ctrl+i (compatibility mode) works like a charm
b) f1 (iso-to-memory) in some winpe(error 0x9e) & some others just failed (nothing shows just the loading iso prompt) just the same like windows installation isos.
c)ctrl+w (wimboot mode) works for some win installations(iso of win 11,10) and didn't work for some others.
