### ISSUE TITLE
[issue]: how to boot windows VHD without use ventoy

### ISSUE THREAD

**Issue by candrapersada** [ventoy/Ventoy#1151]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.54

### What about latest release

No. I didn't try the latest release.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

40GB

### Disk Manufacturer

TOSHIBA

### Image file checksum (if applicable)

No.

### What happened?

A bug happened! how to boot windows VHD using grub without use ventoy like [vdiskchain](https://github.com/ventoy/vdiskchain)?

**Comment by ventoy** [comment]
This is not supported now.
