### ISSUE TITLE
Window10 2004 iso file can't boot

### ISSUE THREAD

**Issue by Liehu** [ventoy/Ventoy#116]
cn_windows_10_consumer_editions_version_2004_x64_dvd_0c2eefdb.iso can't boot

**Comment by ventoy** [comment]
Someone told me that he just tested this iso, and it's OK.
It does take some time in the 3rd picture.

![1](https://user-images.githubusercontent.com/59477474/82110287-b14d0400-976f-11ea-9bf2-7236329ff074.PNG)
![2](https://user-images.githubusercontent.com/59477474/82110290-b3af5e00-976f-11ea-9b5e-cadb0419acc9.PNG)
![3](https://user-images.githubusercontent.com/59477474/82110291-b447f480-976f-11ea-80a6-1e11f4a103eb.PNG)
![4](https://user-images.githubusercontent.com/59477474/82110292-b4e08b00-976f-11ea-887a-089f202ba0fa.PNG)
![5](https://user-images.githubusercontent.com/59477474/82110293-b611b800-976f-11ea-91d7-8dddde0a3974.PNG)

**Comment by Liehu** [comment]
> Someone told me that he just tested this iso, and it's OK.
> It does take some time in the 3rd picture.
> 
> ![1](https://user-images.githubusercontent.com/59477474/82110287-b14d0400-976f-11ea-9bf2-7236329ff074.PNG)
> ![2](https://user-images.githubusercontent.com/59477474/82110290-b3af5e00-976f-11ea-9b5e-cadb0419acc9.PNG)
> ![3](https://user-images.githubusercontent.com/59477474/82110291-b447f480-976f-11ea-80a6-1e11f4a103eb.PNG)
> ![4](https://user-images.githubusercontent.com/59477474/82110292-b4e08b00-976f-11ea-887a-089f202ba0fa.PNG)
> ![5](https://user-images.githubusercontent.com/59477474/82110293-b611b800-976f-11ea-91d7-8dddde0a3974.PNG)

找到问题了，ISO损坏了

**Comment by chromer030** [comment]
I tested latest Windows 10 2004 and booted and installed successfully.
> en_windows_10_business_editions_version_2004_x64_dvd_d06ef8c5
