### ISSUE TITLE
Ventoy 1.0.10 无法启动单分区U盘(FAT32)上的Linux ISO

### ISSUE THREAD

**Issue by a1ive** [ventoy/Ventoy#117]
执行 `sudo ./Ventoy2Disk.sh -i /dev/sda` 后，手动删除 exFAT 分区，调整分区如下图所示：
![深度截图_plasmashell_20200516155802](https://user-images.githubusercontent.com/10670106/82114377-1532f500-978f-11ea-8516-b6ec9fc67a4e.png)
然后 UEFI 启动，无法进入 GRUB 菜单界面。
执行如下命令，可进入 菜单界面：
```
set root=hd0,1
set prefix=(hd0,1)/grub
normal
```
![深度截图_选择区域_20200516155834](https://user-images.githubusercontent.com/10670106/82114423-43b0d000-978f-11ea-8bcb-3ba465bb25b3.png)
找不到 ISO，所以我手动指定了一个 ISO 的路径：
```
set chosen_path=/manjaro-kde-19.0.2-200311-linux54.iso
uefi_iso_menu_func (hd0,1)
```
![深度截图_选择区域_20200516155923](https://user-images.githubusercontent.com/10670106/82114437-5cb98100-978f-11ea-908f-d66a6812b99e.png)
然后启动，但是最终会进入 initramfs shell 界面，启动失败。
![深度截图_选择区域_20200516155227](https://user-images.githubusercontent.com/10670106/82114525-c89be980-978f-11ea-8619-ecc4af9f8e0f.png)
执行 `/ventoy/tool/vtoydump -f /ventoy/ventoy_os_param -v`，输出如下：
![深度截图_选择区域_20200516155411](https://user-images.githubusercontent.com/10670106/82114610-5081f380-9790-11ea-9b41-dc1141c51ccd.png)

### 如果随便在后面创建一个新分区，其他不做任何改变 (如下图)，按上面的步骤是可以正常启动 Linux 的。
![深度截图_plasmashell_20200516155748](https://user-images.githubusercontent.com/10670106/82114632-7c04de00-9790-11ea-8521-bf537a73ee40.png)

**Comment by ventoy** [comment]
这个就是我之前说过的，Ventoy设计之初是当成一个整体方案设计的，不太好独立出来。
Linux内部的hook脚本在启动时要找到哪个设备是这个U盘，找的条件中有一条就是要有 /dev/sdX2 分区

**Comment by a1ive** [comment]
以后有计划支持单分区吗？没有的话我就关闭这个issue。

-------------------

另外，如果U盘是量产过的有光驱，那就没办法 UEFI 启动 WIndows ISO。我测试了一下，屏蔽其他所有光盘就可以了，代码可以参考[这里](https://github.com/a1ive/grub/commit/ad4d5a5f115fff32c337796cbb734cca6d3e4001)。

**Comment by ventoy** [comment]
现在还没有计划，可以以后再提。

我设想在2.x版本中启动和ISO文件独立开，应该可以支持这种形式。
但是这个还是没影的事情，不知道什么时候有时间实现。

光驱的这个我之前听到这个问题的时候就想过可能这样做是可以的，还没来得及去试，看来确实如此。我参考参考。
