### ISSUE TITLE
[issue]: Boot config files are not getting replaced on Arch Linux

### ISSUE THREAD

**Issue by youk** [ventoy/Ventoy#1170]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.56

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

4

### Image file download link (if applicable)

http://mirror.rackspace.com/archlinux/iso/2021.10.01/

### What happened?

`Boot Conf Replace Plugin` does not work with Arch Linux ISO loaded to RAM. Arch Linux uses `systemd-boot` and corresponding config files on ISO are as follows:
```
├── entries
│   ├── 01-archiso-x86_64-linux.conf
│   ├── 02-archiso-x86_64-speech-linux.conf
│   └── 03-archiso-x86_64-ram-linux.conf
└── loader.conf
```
I have the following configuration:
```
"conf_replace": [
    {
        "iso": "/archlinux-2021.10.01-x86_64.iso",
        "org": "/loader/entries/03-archiso-x86_64-ram-linux.conf",
        "new": "/ventoy/archlinux/03-archiso-x86_64-ram-linux-custom.conf"
    }
]
```
It has no effect. `03-archiso-x86_64-ram-linux-custom.conf` is not getting replaced during the boot process.

**Comment by Moonbase59** [comment]
The insights here are still helpful—I just made persistence work with _EndeavourOS_ 2025.03 (Mercury Neo), for "normal mode", by replacing `/boot/syslinux/archiso_sys-linux.cfg` with added option `cow_label=vtoycow`.
