### ISSUE TITLE
Ventoy2Disk.exe升级U盘的Ventoy版本以后，再次点击升级仍然可以升级

### ISSUE THREAD

**Issue by jianyuyanyu** [ventoy/Ventoy#1183]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.57

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64GB

### Disk Manufacturer

闪迪

### Image file checksum (if applicable)

Yes.

### What happened?

Ventoy2Disk.exe升级U盘的Ventoy版本以后，再次点击升级仍然可以升级

**Comment by ventoy** [comment]
这个就是这样设计的。所谓升级其实就是用安装包内的版本覆盖U盘内的版本，而不会对这两个版本进行检查。
所以，通过升级按钮，你可以：
1. 把老版本升级为新版本
2. 把新版本降级为老版本
3. 同版本之间自己升级自己

这在有些情况下是有用的。比如说，你安装Ventoy时没有打开 `安全启动支持` 这个选项。后面又需要打开。则你只需打开软件、勾选上这个选项，然后通过一次升级就可以打开这个选项，而不需要重新安装。这个时候就是同版本之间的升级。
