### ISSUE TITLE
After install ventoy i am not able to format my pendrive

### ISSUE THREAD

**Issue by meanindra** [ventoy/Ventoy#1185]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.57

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

SanDisk

### What happened?

When I plug in my pen drive, Ubuntu file manager show that pen-drive (ventoy) is connected but after some time it disconnect automatically. 
GParted stuck here
![Screenshot from 2021-10-30 16-06-09](https://user-images.githubusercontent.com/36324543/139529468-0a995a51-03b2-4001-a696-b4b3d409402f.png)
After some time this error show
![Screenshot from 2021-10-30 16-07-08](https://user-images.githubusercontent.com/36324543/139529520-3dbd9a40-c244-42a9-bdd5-c4ce2ed4a8ee.png)
I can't delete any ISO from here
![Screenshot from 2021-10-30 16-05-43](https://user-images.githubusercontent.com/36324543/139529543-60037c6f-83f2-4ad3-80f4-585effa6a416.png)

In windows when i try to format my ventoy pen drive with rufus,  rufus stop working(I mean rufus is not respond) same with Windows file manager. I tried many ways to format my pendrive but noting is working.

**Comment by ventoy** [comment]
Ventoy just write some data to the USB stick and nothing special.
So I think there is some hardware problem with your USB drive.

**Comment by meanindra** [comment]
ok. Thanks
