### ISSUE TITLE
Testing ISOs on Surface Pro 6 with secure boot disabled

### ISSUE THREAD

**Issue by SamLukeYes** [ventoy/Ventoy#119]
Going on with #87 (ISOs that were successfully boot are no longer tested).

Tested on Ventoy 1.0.10:

- elementaryos-5.1-stable.20200501.iso
_SHA256: e57d04f0fcc1737c97be2fb22fbe16bfee9806db64c6ccefdbf98a17157fdd8b_
**No bootfile found for UEFI!**

- krd.iso
_SHA256: c9d6b70e4964e765263cc53536cc3be5ecd7cdcfd198b0381526268cf70a91aa_
Successfully boot **with check_signatures=no**.

- neon-user-20200507-1116.iso
_SHA256: 066d412e54b1142b66251505e7aecc416da9ffb4c6ad07bd72b4a69198a97f60_
**No bootfile found for UEFI!**

- Zorin-OS-15.2-Core-64-bit.iso
_SHA256: d670d51d500f9de3d6222446d52714ff13638f371a44ba3a860701020f3434ba_
**No bootfile found for UEFI!**

- ubuntudde-20.04-amd64-desktop.iso
_SHA256: 395e1ab9e7c40ab1c131b292a2ebde921baf8b3f7fa37e49ea99f4c01388b9e1_
**No bootfile found for UEFI!**

- Fedora-Workstation-Live-x86_64-32-1.6.iso
_SHA256: 4d0f6653e2e0860c99ffe0ef274a46d875fb85bd2a40cb896dce1ed013566924_
**No bootfile found for UEFI!**

- linuxmint-19.3-xfce-64bit.iso
_SHA256: 30c509d062da0f754765b5ecba861486d1f3d6138fdcec6f70f5feb88b72e4ef_
**No bootfile found for UEFI!**

- lmde-4-cinnamon-64bit.iso
_SHA256: fb6fb4f507f1de979a8922f9e503ae0ad8109e87ea1a9a163a6b30f819971256_
**No bootfile found for UEFI!**

- MX-19.1_x64.iso
_SHA256: 18e880f55d83abb19f042310f46a2738807ed8dd48c86e2ef0a5a083672e9e2d_
**No bootfile found for UEFI!**

- Solus-4.1-Budgie.iso
_SHA256: 4bf00f2f50e7024a71058c50c24a5706f9c18f618c013b8a819db33482577d17_
**No bootfile found for UEFI!**

- ubuntu-mate-20.04-desktop-amd64.iso
_SHA256: a298764d9d2615c6fc5e99c7dddd9d7687f885821e6915c57daf9747b9c33445_
Successfully boot.

- anarchy-1.2.1-x86_64.iso
_SHA256: 8075d0fc034e03e56a858f66826328f06c59d9ce884d90e920785eb7af98c9e9_
Successfully boot.

Tested on Ventoy 1.0.11:

- Win10_2004_Chinese(Simplified)_x64.iso
_SHA256: e04e4b96b2cbe7a2afe4889630958b46cd70f5dff39a8283e8ad106c3d2f75b5_
Successfully boot.

Tested on Ventoy 1.0.12:

- manjaro-gnome-20.0.2-minimal-200531-linux56.iso
_SHA256: 6b0a6923e91f80951ee566b8add56c78f90e09e2d6df9dba4e3e0de1d7fcc08b_
Successfully boot.

- manjaro-cinnamon-20.0.3-200606-linux56.iso
_SHA256: a8272c9d0d8077913378378dbebf3af76f9cd5f71e44545e52242d1dd449cfd0_
Successfully boot.

**Comment by chromer030** [comment]
for krd.iso as mentioned by dear Ventoy in mail website you should do this :

> For krd.iso, grub signature check was enabled in UEFI mode by default. Ventoy must do some > hook to avoid "kernel.dat not found" error, but the hook will be denied by the check.
> So in UEFI mode, after the kaspersky boot menu was shown, you need to run set 
> check_signatures=no in the grub shell before boot.

**Comment by SamLukeYes** [comment]
> for krd.iso as mentioned by dear Ventoy in main website you should do this :
> 
> > For krd.iso, grub signature check was enabled in UEFI mode by default. Ventoy must do some hook to avoid "kernel.dat not found" error, but the hook will be denied by the check.
> > So in UEFI mode, after the kaspersky boot menu was shown, you need to run set
> > check_signatures=no in the grub shell before boot.

OK, I'll try it again.

**Comment by SamLukeYes** [comment]
> for krd.iso as mentioned by dear Ventoy in main website you should do this :
> 
> > For krd.iso, grub signature check was enabled in UEFI mode by default. Ventoy must do some hook to avoid "kernel.dat not found" error, but the hook will be denied by the check.
> > So in UEFI mode, after the kaspersky boot menu was shown, you need to run set
> > check_signatures=no in the grub shell before boot.

Thank you, krd.iso boots now.

**Comment by chromer030** [comment]
something is wrong with this model firmware , almost all of this ISOs are booting successfully on most firmwares.

**Comment by SamLukeYes** [comment]
I'm not going to do more tests on this issue, but I'll leave it open. 

As far as tested, these distros can boot on SP6:

- Arch based distros (Manjaro and Anarchy tested)

- Ubuntu official editions (Ubuntu, Ubuntu Budgie and Ubuntu MATE tested)

- Deepin and UOS

- Kaspersky Rescue Disk

And these distros are not supposed to boot on SP6:

- Non-official Ubuntu based distros (UbuntuDDE, KDE neon, Linux Mint, etc.)

- Many other Debian based distros that are not mentioned above

- RH based distros? (Only Fedora tested)

If anyone knows any other ISOs that can or cannot boot on SP6, please comment here.

**Comment by SamLukeYes** [comment]
ubuntudde-20.04-amd64-desktop.iso successfully boot with ventoy 1.0.13. According to the release notes, this issue is likely to be fixed.

**Comment by dalianmao-nuanyangyang** [comment]
surface pro8 won't start ventoy, other PC is ok, test on HP and Thinkpad is OK, but surface pro will not appear start even UI to select iso.
