### ISSUE TITLE
[issue]: ventoy.jsonxxx file is not ignored

### ISSUE THREAD

**Issue by steve6375** [ventoy/Ventoy#1190]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.57

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

256gb

### Disk Manufacturer

any

### What happened?

\ventoy\ventoy.json was renamed to ventoy.jsonxxx  but it is still detected by Ventoy.
![image](https://user-images.githubusercontent.com/1469350/139641500-06bffa67-c1bb-4036-ace3-81ff2ac6f7ab.png)

**Comment by ventoy** [comment]
This CI release should have fixed it.
https://github.com/ventoy/Ventoy/actions/runs/1407731922
