### ISSUE TITLE
Win11 Patch - one with TPM, one Without TPM

### ISSUE THREAD

**Issue by lastsamurai26** [ventoy/Ventoy#1192]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.57

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128GB

### Disk Manufacturer

SanDisk

### What happened?

I would like to have 2 options with Win11 one for PCs that are not 
supported and one where this "workaround" is not used. 

Is this somehow possible?

**Comment by ventoy** [comment]
Ventoy can not detect the machine is PC or laptop. 
Also it can not detect whether current machine contains a Win11 compatible TPM (1.2+) or not.

So you must make the decision by yourself that whether use the workaround or not.

As for the `VTOY_WIN11_BYPASS_CHECK` option, it's just a grub variable. So you can change its value dynamically.
When you in Ventoy's main menu, press `c` to enter grub shell and run the following command.
```
set VTOY_WIN11_BYPASS_CHECK=1
```
This will enable this workaround.

```
set VTOY_WIN11_BYPASS_CHECK=0
```
This will disable this workaround.

After the command, press `ESC` to return to the main menu.

**Comment by steve6375** [comment]
You can use an XML file. Then you can choose XML or not for any iso.
https://easy2boot.xyz/ventoy/boot-windows-11-on-non-tpm-systems-using-ventoy/

**Comment by ventoy** [comment]
The workaround is actually some special registry values.

If you want to make the selection automatically, **VentoyAutoRun** feature may be helpful.
https://www.ventoy.net/en/doc_inject_autorun.html

You can include some tools alongside with the VentoyAutoRun.bat, 
In the batch script, you can check current machine with some method or some tools.
For example:  
If after check you find that the current machine is a new laptop with TPM and doesn't need the workaround, then do nothing.
If after check you find that the current machine is an old PC and need the workaround, then create these registries.

**Comment by lastsamurai26** [comment]
Thanks to both of you.

I decided to go the way of steve6375, this is better for me.

However, I will also test the variant with the Inject.

**Comment by ventoy** [comment]
OK.
This indicates the flexibility of Ventoy :)
