### ISSUE TITLE
Add VERSION.txt to created USB disk

### ISSUE THREAD

**Issue by rbeede** [ventoy/Ventoy#1193]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.57

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

USB

### What happened?

After I build a USB stick it would be handy to have an E:\VERSION.txt file with the contents of a single line (no line terminator) with the version number of VenToy deployed.

**Comment by ventoy** [comment]
After install, I prefer to give user an fully empty partition to use as they want. 
You can create such file and write the version to it manually after install and every update.
