### ISSUE TITLE
Fedora 35 Workstation x86-64: Successful UEFI/UEFI-CSM Boot

### ISSUE THREAD

**Issue by Silexium** [ventoy/Ventoy#1196]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.57

### BIOS Mode

Both

### Partition Style

GPT

### Image file name

Fedora-Workstation-Live-x86_64-35-1.2.iso

### Image file checksum type

SHA256

### Image file checksum value

85d9d0c233d560e401e2ad824aa8e6d5614e8b977dfe685396bfb2eb3ba5b253

### Image file download link (if applicable)

https://download.fedoraproject.org/pub/fedora/linux/releases/35/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-35-1.2.iso

### Test envrionment

ASUS B85M-E Motherboard

### More Details?

Successful UEFI/UEFI-CSM boot on Ventoy 1.0.57

Motherboard: ASUS B85M-E (BIOS version: 3602)
CPU: Intel Xeon E3-1231 v3
GPU: Nvidia GeForce GTX 1060 3GB

**Comment by ventoy** [comment]
Thanks.
I have added it in the official website https://www.ventoy.net/en/isolist.html

**Comment by eexpress** [comment]
F36beta fail.
