### ISSUE TITLE
[Success Image Report]: MX Linux 21 64bit

### ISSUE THREAD

**Issue by kaaax0815** [ventoy/Ventoy#1197]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.56

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

MX-21_x64.iso

### Image file checksum type

SHA256

### Image file checksum value

F9BB05075FFF26B1AF3F92D8B8F94FB0D8F53B3169207B492A30D7D0936E4D14

### Image file download link (if applicable)

https://sourceforge.net/projects/mx-linux/files/Final/Xfce/MX-21_x64.iso/download

### Test envrionment

HP Elitebook 840G1

### More Details?

This image file booted successfully in Ventoy. Persistence with the Persistence Plugin also works just fine

**Comment by ventoy** [comment]
Thanks.
I have added it in the official website https://www.ventoy.net/en/isolist.html
