### ISSUE TITLE
Some Suggestions for Github page

### ISSUE THREAD

**Issue by chromer030** [ventoy/Ventoy#12]
I think applying this suggestions may help users to get familiar to this great tool better.
1- Presenting Ventoy website address in Description section , in top of page.
2- Using Topics which place down to Descriptions section and aide to make Ventoy more discoverable , useful when users are searching for this kind of tools on Github.
3- Include released Ventoy versions on Release section of page , because most GitHub users , have eyes on Release Tab , when firstly browse a repository.
Thank You.

**Comment by ventoy** [comment]
I accept all your suggestions, thank you!  Please make a check.

**Comment by chromer030** [comment]
Great , Thanks for applying...
