### ISSUE TITLE
Alternative bootloader option

### ISSUE THREAD

**Issue by kmm2** [ventoy/Ventoy#120]
Would you be able to add a Ventoy hotkey to boot PBR of "Part1" partition?

This way we could boot from there with Grub4DOS or BOOTMGR all not yet supported ISOs or other non-ISO OS.

Thanks for your great boot tool!

**Comment by ventoy** [comment]
I tried to add this feature, but there are many special cases, so finally I remove it.
Ventoy is based on grub2, so you can press c to enter the grub2 shell, and do what you want.
for example:
set root=(hd1,1)
chainloader +1

See [https://www.gnu.org/software/grub/manual/grub/grub.html#Chain_002dloading](https://www.gnu.org/software/grub/manual/grub/grub.html#Chain_002dloading)
for detail.

**Comment by blackcrack** [comment]
i guess maintaining and updating Ventoy is enough work, there is not need a build in extra troubler *bg*
@kmm2 if you ask is answered, you could close your issue :)

**Comment by kmm2** [comment]
Thanks for your advice. It seems to work reliably everywhere. I made the following mod of grub.cfg where 'Halt' is replaced with 'Boot Part1':
```
function ventoy_power {
    echo '<1>  Reboot'
    echo '<2>  Boot Part1'
    echo '<0>  Return to menu'
    echo -e '\nPlease enter your choice:'
    
    unset vtOpt
    read vtOpt
    
    if [ "$vtOpt" = "1" ]; then
        echo -e '\n\nSystem is rebooting ... \n'
        sleep 1
        reboot
    elif [ "$vtOpt" = "2" ]; then
        set root=(hd0,1)
        chainloader +1
        boot
    fi
}
```
Now to boot grub4dos I just press F2 and then option 2. I am sure it would be useful for other users too. Please add it as eg 3rd option of the power menu.

**Comment by ventoy** [comment]
This is just the simplest case and only for legacy BIOS mode.
If you have two or three or more HDDs in the computer, the OS is not always on hd0, it may be hd2, I have seen this before. The hd0/hd1/hd2 don't match the order in BIOS sometimes.

**Comment by kmm2** [comment]
I see, but in 95% our USB boot will be hd0. Also, there is plenty of room in the F2 menu for all 4 boot options: hd0/1/2/3 - optional and only for those who understand the limitations and requirements.

Please re-consider it.

**Comment by kmm2** [comment]
I tested this code to set hd automatically:
```
        search --set=root --file /grub.exe
        linux /grub.exe
        boot
```
but the Grub2's "search" does not work. It seems that grub4dos "find" actually works as expected:
```
        linux /grub/grub.exe
        boot
```
To /grub/ copy grub.exe and menu.lst....
```
title grldr
find --set-root /grldr
configfile /menu.lst
```
To Part1 copy grldr and another menu.lst
Now it should boot g4d regardless of BIOS hd order.

**Comment by kmm2** [comment]
I note interesting changes to v1012

Please add to power.cfg the following:

```
menuentry 'Boot Part1' {
        set root=(hd0,1)
        chainloader +1
        boot
}
```

**Comment by ventoy** [comment]
Please make a try with Ventoy-1.0.13

**Comment by kmm2** [comment]
Thank you, it works! Would you be able to also add the following to localboot.cfg?
```
    menuentry 'Search and boot Grub4dos' {
        if search -n -s -f /grldr; then
            ntldr /grldr
        else
            echo "Grub4dos NOT found ..."
        fi        
    }
```
The search function is reliable and the direct grldr call does not require Part1 PBR presetting. I've already modified Ventoy-1.0.13 and confirm that the above code works fine.

Incidentally I also confirm that the latest "WinPE10_8_Sergei_Strelec_x86_x64_2020.04.27_English.iso" supports external tools in Ventoy-1.0.13.

Thank you again.

**Comment by ventoy** [comment]
1. OK, I will add it in next release.

2. Yes, Ventoy-1.0.13 make some optimization for Sergei Strelec's WinPE (external tools available), 
(see [release notes](https://www.ventoy.net/en/doc_news.html))

**Comment by kmm2** [comment]
Since v1.0.14 everything works fine.
I am closing the issue.
