### ISSUE TITLE
[issue]: Fedora 35 Live Workstation not booting.

### ISSUE THREAD

**Issue by Ollix27** [ventoy/Ventoy#1200]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.57

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

64GB

### Disk Manufacturer

Unknown

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://getfedora.org/en/workstation/download/

### What happened?

When i select Fedora 35 it shows me an blank screen wiht an _ on it. Fedora 35 Booted once and never again.

**Comment by ventoy** [comment]
1. When you in Ventoy's boot menu, select Fedora iso file and press `m` and calculate its sha256. The correct value should be:
```
Fedora-Workstation-Live-x86_64-35-1.2.iso: 85d9d0c233d560e401e2ad824aa8e6d5614e8b977dfe685396bfb2eb3ba5b253
```

2. If the sha256 is correct. please do the debug: When you in Ventoy's boot menu, press `c` to enter grub shell and run `vtdebug on` and then press `ESC` to return to the main menu, and then select the iso file to boot.

3. Try grub2 mode. When you in Ventoy's boot menu, press `ctrl+r` to enter grub2 mode and then select the iso file to boot.

**Comment by Ollix27** [comment]
Thanks much.

**Comment by ventoy** [comment]
Any update?

**Comment by dginhoux** [comment]
Hi, 

I've similar problem with Fedora 34 and 35 isos, with checked MD5 after copying on my key.
Ventoy 1.46, Ventor 1.57 and now 1.60... same problem.
already try the ctrl+r mode.

computer full UEFI : huawei matebook d15
ventoy key recreated from scratch with ext4 iso partition.

I'll edit this msg with the error msg in few minutes

**Comment by dginhoux** [comment]
I'll try tomorrow to use Ventoy 1.4x and try again... This test can appear stupid but I've installed theses computers with Fedora 33 and 34 few months ago

**Comment by dfateyev** [comment]
The issue is still actual for ventoy-1.0.62 and "Fedora-Workstation-Live-x86_64-35-1.2.iso".
At the same time, there are no issues for "Fedora-Server-dvd-x86_64-35-1.2.iso".

**Comment by Sitolam** [comment]
Does anyone know how to fix this I am using Fedora 35 workstation.

![FJIMG_20220115_153723.jpg](https://user-images.githubusercontent.com/79202140/149626108-a90c4d5d-135e-4ec5-ac38-a7ee1fab41f8.jpg)

**Comment by abradd** [comment]
I'm not certain that the issue I'm seeing is the same as everyone else, but I'll include it here for now. Let me know if you want me to create another issue.

I ran into an error when live-booting Fedora 35 (Fedora-Workstation-Live-x86_64-35-1.2.iso) after installing Ventoy 1.0.64 on an EMTEC 16GB USB. I figured the USB was bad and tried another 64GB Kingston that I had lying around also with Ventoy 1.0.64 installed on it and saw the same issue.
 
![fedora_error](https://user-images.githubusercontent.com/3516589/149705438-63766efa-8345-4bb6-b239-722874878e1f.jpg)

Ventoy was installed on both sticks using the CLI in Fedora 35 with:

Bios Mode: UEFI
Partition style: MBR

After finding this issue I ran a checksum in Ventoy on the Fedora Workstation ISO on the Kingston USB and found that the checksum didn't match. I ran:

A checksum on the Workstation ISO on the filsystem: good
Copied the the ISO onto the Kingston USB stick and ran a checksum on the ISO on the USB stick: good.
Booted into Ventoy and ran a checksum on the Workstation ISO: good
Booted into Fedora Workstation fine.

I ran a checksum in Ventoy on the Fedora Workstation ISO on the EMTEC USB stick and found that it too was wrong (I did not record the checksum on the incorrect Kingston ISO unfortunately). The checksum I got was:
    
```    
81fddfb31c041c5332177b8ef1d2f34904e8f31c0b56f7a174be6ff302e81c50  Fedora-Workstation-Live-x86_64-35-1.2.iso
```    

I repeated the process above of overwriting the Workstation ISO image and checksumming. Everything was good, but I skipped the initial checksum of the workstation ISO in Ventoy and tried to liveboot straight into Fedora. At that point it failed with the same error I received originally. Afterwards I ran the checksum of the Workstation ISO in Ventoy on the EMTEC stick and found that it was the same wrong value again:

```    
81fddfb31c041c5332177b8ef1d2f34904e8f31c0b56f7a174be6ff302e81c50  Fedora-Workstation-Live-x86_64-35-1.2.iso
```

So I seem to have a working live-boot and a non-working live-boot on two USB sticks.

I also tested the netinstall of Fedora Server on this most recent test with the EMTEC stick and found that it too failed with the same error and checksum mismatch. So it doesn't seem to be Workstation specific.

**Comment by ventoy** [comment]
@abradd 
1. I doubt your USB stick has some hardware problem. Try to do a full hardware test with some tool on your USB stick or try another USB stick. 
2. You can try other linux distro (e.g. Ubuntu/Manjaro ...) if it's something about your USB stick then other distro should also has problem when you boot.

**Comment by IPlayZed** [comment]
![20230213_224328.jpg](https://user-images.githubusercontent.com/21132316/218581503-35d70ac6-beda-44d9-9653-a6752f529557.jpg)

This issue still is present with Fedora Workstation live 37-1.7. I have the same configs as OP.

**Comment by IPlayZed** [comment]
> ![20230213_224328.jpg](https://user-images.githubusercontent.com/21132316/218581503-35d70ac6-beda-44d9-9653-a6752f529557.jpg)
> 
> This issue still is present with Fedora Workstation live 37-1.7. I have the same configs as OP.

NixOS and VanilliaOS also fails to boot with similar issues.
