### ISSUE TITLE
[issue]: VirusTotal detect Ventoy2Disk.exe as a trojan

### ISSUE THREAD

**Issue by jpangulo** [ventoy/Ventoy#1203]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.58

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32 GB

### What happened?

Windows Defender and [VirusTotal](https://www.virustotal.com/gui/file/8fe249c2d068fb2fca71eb748a51adf2681c3af5e0a528aefdc26762dd346fbd/detection) detects Ventoy2Disk.exe as a trojan

**Comment by CoodyCZ** [comment]
yes! - Microsoft Defender ... them same problem - **Trojan:Script/Phonzy.A!ml** - tested on VirtualBox - windows 10 pro (build 19044.1320) and  windows 11 pro (22000.282)

**Comment by nvt194** [comment]
> 
> 
> yes! - Microsoft Defender ... them same problem - **Trojan:Script/Phonzy.A!ml** - tested on VirtualBox - windows 10 pro (build 19044.1320) and windows 11 pro (22000.282)

Same here, my machine is on Windows 10 21H2 build 19044.1320.

**Comment by 0x78f1935** [comment]
> > yes! - Microsoft Defender ... them same problem - **Trojan:Script/Phonzy.A!ml** - tested on VirtualBox - windows 10 pro (build 19044.1320) and windows 11 pro (22000.282)
> 
> Same here, my machine is on Windows 10 21H2 build 19044.1320.

Same for build Windows 10 21H2 build 19043.1320.

Guess I'll wait until fixed..

**Comment by ventoy** [comment]
It's false positive. 
There is such false positive when I update Ventoy2Disk.exe, but after some time it will be added to the whitelist.
This happened too many times.

#1194
#660
#468
#371
#31
