### ISSUE TITLE
Virus detected in chrome, can't download; Microsoft Security also flags as virus

### ISSUE THREAD

**Issue by MultiKoopa** [ventoy/Ventoy#1204]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.58

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

256GB

### What happened?

Chrome flagged ventoy-1.0.58-windows.zip as a virus and wouldn't let me download it, so I had to switch to Firefox to actually complete the download. 

Windows / Microsoft Security also flagged it as a severe threat, so I had to tell it to ignore the threat to actually be able to use the latest release.

![ventoyfalsepositive](https://user-images.githubusercontent.com/30543543/140630161-634f3856-cf11-4df1-a515-15200ee1cdb9.png)

I'm sure it's not a real virus, but I figured I'd report it, since it can't be downloaded in Chrome right now.

**Comment by ventoy** [comment]
It's false positive.
There is such false positive when I update Ventoy2Disk.exe, but after some time it will be added to the whitelist.
This happened too many times.

#1203
#1194
#660
#468
#371
#31

**Comment by mawoka-myblock** [comment]
> It's false positive. There is such false positive when I update Ventoy2Disk.exe, but after some time it will be added to the whitelist. This happened too many times.
> 
> #1203 #1194 #660 #468 #371 #31

Don't you have an idea why these scanners think you spread malware/viruses?
