### ISSUE TITLE
建议约定一个规则，比如只扫描指定白名单文件夹下的镜像，屏蔽某些黑名单文件夹镜像

### ISSUE THREAD

**Issue by geekyouth** [ventoy/Ventoy#121]
要不然我的 u 盘存了很多镜像，会全部扫描展示，不好管理。

**Comment by ventoy** [comment]
这个官网有相关说明：
![filt](https://user-images.githubusercontent.com/59477474/82138815-e29fff80-9855-11ea-820c-9cd1184d10ea.PNG)

另外，按 F3 可以进入 TreeView 模式，按照文件夹层级显示，管理起来会方便一些。

**Comment by weakestan** [comment]
其实引导启动的iso，一般操作习惯都是集中存放的。
根目录下面定义一个搜索目录，可能更方便。（直接固定死，其实我觉得也行。）

**Comment by ventoy** [comment]
有道理，
下一个版本中，我会在 全局控制插件中增加一个 VTOY_DEFAULT_SEARCH_ROOT 项， 用来设置搜索的根目录。[https://www.ventoy.net/cn/plugin_control.html] (https://www.ventoy.net/cn/plugin_control.html)

**Comment by ventoy** [comment]
全局控制插件中 VTOY_DEFAULT_SEARCH_ROOT   已经实现。
