### ISSUE TITLE
[issue]: Theme changing not working

### ISSUE THREAD

**Issue by megaenderdragon** [ventoy/Ventoy#1212]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.58

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

64GB

### Disk Manufacturer

samsung

### What happened?

I can't set custom themes. I have a nice theme cyberRe.. I tried both ways to specify the path to theme.txt file. Ventoy/themes/CyberRe/theme.txt. doesn't work. . CyberRe/theme.txt doesn't work either. Please help
![Zrzut ekranu (6)](https://user-images.githubusercontent.com/84520871/141007036-c36c5279-531d-446f-95a9-0b009c5ac4ee.png)
![Zrzut ekranu (5)](https://user-images.githubusercontent.com/84520871/141007053-fc0c5710-239a-49d9-b01d-8ef167168576.png)

**Comment by steve6375** [comment]
Case sensitive
Forward slash /
Starts with /

**Comment by megaenderdragon** [comment]
> Case sensitive Forward slash / Starts with /

can you explain?

**Comment by steve6375** [comment]
/ventoy/themes/CyberRe/theme.txt

**Comment by steve6375** [comment]
/ventoy/ventoy.json

**Comment by megaenderdragon** [comment]
Thanks.
