### ISSUE TITLE
[issue]: It's showing it's contents virus 

### ISSUE THREAD

**Issue by sanikava** [ventoy/Ventoy#1217]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.59

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

16gb

### Disk Manufacturer

SanDisk

### What happened?

Trojan:Script/Wacatac.B!ml

This program is dangerous and executes commands from an attacker

my windows 10 security not letting me run ventoy but old is not reading usb 
it have administration

**Comment by ventoy** [comment]
It's false positive.
There is such false positive when I update Ventoy2Disk.exe, but after some time it will be added to the whitelist.
This happened too many times.

#1204
#1203
#1194
#660
#468
#371
#31
