### ISSUE TITLE
[issue]: Why is non-destructive install mode not supported by linux?

### ISSUE THREAD

**Issue by KaMyKaSii** [ventoy/Ventoy#1219]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.59

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

1TB

### What happened?

This is pretty easy to do with some shell commands, I even posted a [tutorial](https://forums.ventoy.net/showthread.php?tid=42) on the forum over a year ago on how to do this on an MBR disk. Hope this will be available in the next release. Thank you so much for your time and great work!

**Comment by ventoy** [comment]
For linux I need to consider more:
1. MBR & GPT
2. i386/x86_64/ARM64/MIPS64
3. CLI/WebUI/QT/GTK version
4. FAT/exFAT/NTFS/ext234
5. If the system does not contains some tools (e.g. ntfsresize ...)

I need more time.

**Comment by ventoy** [comment]
Ventoy 1.0.60
Add non-destructive installation support in Linux Ventoy2Disk.sh. [Notes](https://www.ventoy.net/en/doc_non_destructive.html)

**Comment by candrapersada** [comment]
is it for ventoy-livecd.iso too?
