### ISSUE TITLE
Change release checksums to SHA-256 or higher

### ISSUE THREAD

**Issue by keks24** [ventoy/Ventoy#122]
As SHA-1 is considered dead a long time ago; it would be nice, if you could provide more secure checksums like SHA-256:

> Since 2005 SHA-1 has not been considered secure against well-funded opponents,[4] as of 2010 many organizations have recommended its replacement.[5][6][7] NIST formally deprecated use of SHA-1 in 2011 and disallowed its use for digital signatures in 2013. As of 2020, attacks against SHA-1 are as practical as against MD5;[8] as such, it is recommended to remove SHA-1 from products as soon as possible and use instead SHA-256 or SHA-3. Replacing SHA-1 is urgent where it is used for signatures.

https://en.wikipedia.org/wiki/SHA-1

Thank you!

**Comment by ventoy** [comment]
Hi, what you said make sense. 
I have added the SHA-256 checksum in the release tab, and have updated the checksum in  [https://www.ventoy.net](https://www.ventoy.net)

**Comment by keks24** [comment]
Awesome!
