### ISSUE TITLE
[issue]: on Windows check for "virtual disk" service

### ISSUE THREAD

**Issue by mrx23dot** [ventoy/Ventoy#1220]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.59

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

8GB

### Disk Manufacturer

Kingston

### What happened?

If "Virtual Disk" service is disabled or cannot be started on Windows it fails with cryptic error code:
error code 5 (access denied
[log.txt](https://github.com/ventoy/Ventoy/files/7520155/log.txt)

Please add check for Virtual Disk service, or add detail into log eg Enable VD.

The goal is to have slick installation experience.

**Comment by ventoy** [comment]
VDS is not necessary.  If VDS is disabled, Ventoy will call diskpart.exe to clean the disk.
But from the log we see that even we still get error code 5 after call diskpart.exe to clean the disk.
So there must be some other reason, maybe the disk is occupied by some progress.

You can refer: https://www.ventoy.net/en/doc_ventoy2disk.html to finish the install.

We call diskpart.exe to clean the disk here:
```
[2021/11/11 11:40:07.774] This time install failed, clean disk, wait 10s and retry...
[2021/11/11 11:40:07.774] CleanDiskByDiskpart <3>
[2021/11/11 11:40:07.774] CreateProcess <C:\Windows\system32\diskpart.exe /s "C:\Users\x\Downloads\ventoy-1.0.59\ventoy\diskpart_11776.txt">
[2021/11/11 11:40:07.779] Wair process ...
```

```
[2021/11/11 11:40:17.838] Could not load VDS Service: 0x80070422
[2021/11/11 11:40:17.838] Could not query VDS Service
[2021/11/11 11:40:17.838] VDS_DeleteAllPartitions 3 ret:0 (FAIL)
[2021/11/11 11:40:17.843] Notice: Could not delete partitions: 0xb7, but we continue.   <------ Here we continue the process
```

**Comment by mrx23dot** [comment]
I tried disabling antivir, not solved it
I'm system admin,
unplug repluged it not solved it,
I set VDS from disabled-> manual, 
it worked.

Found it, diskpart depends on VDS not being disabled, At least on win10.
We could issue a warning what to do, or at least in the log.

```
λ diskpart

Microsoft DiskPart version 10.0.18362.1

Copyright (C) Microsoft Corporation.
On computer: 

DiskPart has encountered an error: The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.
See the System Event Log for more information.
```

**Comment by ventoy** [comment]
OK. I will add some log about it.

**Comment by mrx23dot** [comment]
Btw love the project, it works out of the box, unlike other usb installations which take min 1 hour of work, 
like windows, hiren bootcd.

**Comment by ventoy** [comment]
I add some log about VDS.
In latest Ventoy 1.0.60 `Optimization for Ventoy2Disk.exe. Use powershell as an alternative when VDS is unavailable.`
So it should work even VDS is disabled. You can make a test.
