### ISSUE TITLE
[feature request]: read the partition style of Device, and apply this to update by default

### ISSUE THREAD

**Issue by cloudrootab** [ventoy/Ventoy#1224]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.60

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

256

### Disk Manufacturer

Kingston

### What happened?

Not a bug, sorry. But a feature request of a QoL-thing. 
Please read the partition style in the Device. And apply this as the Package variant by default when doing updates. E.g my Kingston has GPT style installed. But I have to manually switch from the default MBR to GPT when doing updates.
Ventoy already does similar when regarding to Secure Boot-support

Thanks!

**Comment by ventoy** [comment]
The partition style in  Package variant  has no effect when update. It's only used when install.

**Comment by ventoy** [comment]
But the secure boot support option is used when update.

**Comment by ventoy** [comment]
Has been noted here: https://www.ventoy.net/en/doc_start.html

**Comment by cloudrootab** [comment]
> Has been noted here: https://www.ventoy.net/en/doc_start.html

Ah, sorry. I missed that and misunderstood the update process. Thanks again!
