### ISSUE TITLE
[issue]: ./tool/ventoy_lib.sh: line 71: vtoycli: command not found

### ISSUE THREAD

**Issue by sebma** [ventoy/Ventoy#1225]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.60

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

64GB

### What happened?

Hi,
The `vtoycli` is not found by the script `./tool/ventoy_lib.sh` : 

```bash
$ sudo ./Ventoy2Disk.sh -l /dev/sdb

**********************************************
      Ventoy: 1.0.60  x86_64
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

./tool/ventoy_lib.sh: line 71: vtoycli: command not found
Some tools can not run on current system. Please check log.txt for details.
$ cat log.txt 
############# Ventoy2Disk -l /dev/sdb [x86_64] ################
Fri Nov 12 13:50:02 CET 2021
no need to decompress tools
MODE=list FORCE= RESERVE_SPACE= RESERVE_SIZE_MB=0
hexdump test ok ...
mkexfatfs test ok ...
vtoycli fat test fail ...
$
```
However a `find` command tells us it is available in a xz compressed form : 
```
$ find . -name vtoycli* | grep $(uname -m)
./tool/x86_64/vtoycli.xz
```

**Comment by ventoy** [comment]
mkexfatfs.xz hexdump.xz vtoycli.xz  ...  are all under `./tool/x86_64/`  directory.
When you run for the first time they should be decompressed. 
I don't know why only vtoycli.xz has problem.

You can decompress the install package again and do some debug in `Ventoy2Disk.sh`, it's simple.
Following is related script in `Ventoy2Disk.sh`.
```
#decompress tool
if [ -f ./tool/$TOOLDIR/ash ]; then
    echo "no need to decompress tools" >> ./log.txt
else
    cd ./tool/$TOOLDIR
    
    [ -f ./xzcat ] && chmod +x ./xzcat
    
    for file in $(ls *.xz); do
        xzcat $file > ${file%.xz}
        [ -f ./${file%.xz} ] && chmod +x ./${file%.xz}
        [ -f ./$file ] && rm -f ./$file
    done
    cd ../../
    
    chmod +x -R ./tool/$TOOLDIR
fi
```

**Comment by sebma** [comment]
@ventoy I've just added a `set -x` before the code block you gave and here is the outcome : 
```bash
$ sudo ./Ventoy2Disk.sh -l /dev/sdb

**********************************************
      Ventoy: 1.0.60  x86_64
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

+ [ -f ./tool/x86_64/ash ]
+ echo no need to decompress tools
+ [ -f /bin/bash ]
+ /bin/bash ./tool/VentoyWorker.sh -l /dev/sdb
./tool/ventoy_lib.sh: line 72: vtoycli: command not found
Some tools can not run on current system. Please check log.txt for details.
+ [ -n /opt/ventoy ]
+ pwd
+ CURDIR=/opt/ventoy
+ [ /opt/ventoy != /opt/ventoy ]
$
```

**Comment by ventoy** [comment]
Do you have `./tool/x86_64/ash` file?
When you decompress the install package for the first time. There is only a `./tool/x86_64/ash.xz` file,
When you run for the first time, it will be decompressed to `./tool/x86_64/ash`

**Comment by ventoy** [comment]
Did you download from official website or from github?
How did you install the package?

**Comment by ventoy** [comment]
Did you use Arch ?

**Comment by sebma** [comment]
@ventoy You're too fast for me :-) There : 
```
$ \curl -Ls https://github.com/ventoy/Ventoy/releases/download/v1.0.60/ventoy-1.0.60-linux.tar.gz | tar -tz | grep /ash
./ventoy-1.0.60/tool/x86_64/ash.xz
./ventoy-1.0.60/tool/i386/ash.xz
./ventoy-1.0.60/tool/aarch64/ash.xz
./ventoy-1.0.60/tool/mips64el/ash.xz
```

**Comment by sebma** [comment]
>  When you run for the first time, it will be decompressed to `./tool/x86_64/ash`

@ventoy How can I prevent `ash.xz` to be decompressed ?

**Comment by sebma** [comment]
@ventoy I use Ubuntu.

**Comment by ventoy** [comment]
When you download `ventoy-1.0.60-linux.tar.gz`  from `https://github.com/ventoy/Ventoy/releases/download/v1.0.60/ventoy-1.0.60-linux.tar.gz`
run `tar xzf  ventoy-1.0.60-linux.tar.gz`
Then you will get ventoy-1.0.60 directory.
Then ash.xz will not be decompressed.

**Comment by ventoy** [comment]
I don't known why in your environment ash.xz is auto decompressed but vtoycli.xz is not so. They are in the same directory.

**Comment by sebma** [comment]
@ventoy Each time I update the Ventoy package, I decompress it and then rename `ventoy-1.0.60` to `ventoy`

**Comment by ventoy** [comment]
When you decompress it you get  `ventoy-1.0.60/tool/x86_64/ash.xz` or `ventoy-1.0.60/tool/x86_64/ash` ?

**Comment by sebma** [comment]
> I don't known why in your environment ash.xz is auto decompressed but vtoycli.xz is not so. They are in the same directory.

```bash
$ \ls -l ./tool/x86_64/
total 2148
-rwxr-xr-x 1 root root      219088 Oct 27 03:47 V2DServer
-rw-r--r-- 1 root sebastien  93596 Nov 12 12:21 V2DServer.xz
-rw-r--r-- 1 root sebastien 362864 Nov 12 12:21 Ventoy2Disk.gtk2
-rw-r--r-- 1 root sebastien 362896 Nov 12 12:21 Ventoy2Disk.gtk3
-rw-r--r-- 1 root sebastien 280408 Nov 12 12:21 Ventoy2Disk.qt5
-rwxr-xr-x 1 root root      185960 Oct 27 03:47 ash
-rw-r--r-- 1 root sebastien  99652 Nov 12 12:21 ash.xz
-rwxr-xr-x 1 root root       51016 Oct 27 03:47 hexdump
-rw-r--r-- 1 root sebastien  27580 Nov 12 12:21 hexdump.xz
-rwxr-xr-x 1 root root       53528 Oct 27 03:47 mkexfatfs
-rw-r--r-- 1 root sebastien  22156 Nov 12 12:21 mkexfatfs.xz
-rwxr-xr-x 1 root root      237144 Oct 27 03:47 mount.exfat-fuse
-rw-r--r-- 1 root sebastien  67732 Nov 12 12:21 mount.exfat-fuse.xz
-rw-r--r-- 1 root sebastien  34612 Nov 12 12:21 vtoycli.xz
-rwxr-xr-x 1 root root       35248 Oct 27 03:47 vtoyfat
-rw-r--r-- 1 root sebastien  15228 Nov  6 11:04 vtoyfat.xz
-rwxr-xr-x 1 root root       19304 Oct 27 03:47 vtoygpt
-rw-r--r-- 1 root sebastien   9804 Nov  6 11:04 vtoygpt.xz
-rwxr-xr-x 1 root sebastien  42576 Nov 12 12:21 xzcat
$
```

**Comment by ventoy** [comment]
This is when you decompress it or after you run Ventoy2Disk.sh?

**Comment by ventoy** [comment]
Please do exactly as follows:
```
curl https://github.com/ventoy/Ventoy/releases/download/v1.0.60/ventoy-1.0.60-linux.tar.gz  -o ventoy-1.0.60-linux.tar.gz
tar xzf ventoy-1.0.60-linux.tar.gz
cd ventoy-1.0.60
ls -l ./tool/x86_64/
```

**Comment by sebma** [comment]
> When you decompress it you get `ventoy-1.0.60/tool/x86_64/ash.xz` or `ventoy-1.0.60/tool/x86_64/ash` ?

I get  `ventoy-1.0.60/tool/x86_64/ash.xz` 

But I guess the ./tool/x86_64/ash comes from a previous installation.

**Comment by ventoy** [comment]
There is no `./tool/x86_64/ash` file after you decompress `ventoy-1.0.60-linux.tar.gz`. There is absolutely no doubt about it.

**Comment by sebma** [comment]
> Please do exactly as follows:
> 
> ```
> curl https://github.com/ventoy/Ventoy/releases/download/v1.0.60/ventoy-1.0.60-linux.tar.gz  -o ventoy-1.0.60-linux.tar.gz
> tar xzf ventoy-1.0.60-linux.tar.gz
> cd ventoy-1.0.60
> ls -l ./tool/x86_64/
> ```

@ventoy Sure : 
```
$ cd /tmp
$ curl https://github.com/ventoy/Ventoy/releases/download/v1.0.60/ventoy-1.0.60-linux.tar.gz  -o ventoy-1.0.60-linux.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   665  100   665    0     0   7150      0 --:--:-- --:--:-- --:--:--  7150
100 16.7M  100 16.7M    0     0  7837k      0  0:00:02  0:00:02 --:--:-- 18.9M
$ tar xzf ventoy-1.0.60-linux.tar.gz
$ cd ventoy-1.0.60
$ ls -l ./tool/x86_64/
total 1380
-rw-r--r-- 1 sebastien sebastien  93596 Nov 12 12:21 V2DServer.xz
-rw-r--r-- 1 sebastien sebastien 362864 Nov 12 12:21 Ventoy2Disk.gtk2
-rw-r--r-- 1 sebastien sebastien 362896 Nov 12 12:21 Ventoy2Disk.gtk3
-rw-r--r-- 1 sebastien sebastien 280408 Nov 12 12:21 Ventoy2Disk.qt5
-rw-r--r-- 1 sebastien sebastien  99652 Nov 12 12:21 ash.xz
-rw-r--r-- 1 sebastien sebastien  27580 Nov 12 12:21 hexdump.xz
-rw-r--r-- 1 sebastien sebastien  22156 Nov 12 12:21 mkexfatfs.xz
-rw-r--r-- 1 sebastien sebastien  67732 Nov 12 12:21 mount.exfat-fuse.xz
-rw-r--r-- 1 sebastien sebastien  34612 Nov 12 12:21 vtoycli.xz
-rw-r--r-- 1 sebastien sebastien  42576 Nov 12 12:21 xzcat
$
```

**Comment by sebma** [comment]
> There is no `./tool/x86_64/ash` file after you decompress `ventoy-1.0.60-linux.tar.gz`. There is absolutely no doubt about it.

My bad, it came from a previous run of a previous release of `./Ventoy2Disk.sh`.

**Comment by ventoy** [comment]
OK.

**Comment by sebma** [comment]
@ventoy I just removed `./tool/x86_64/ash` and re-run `sudo ./Ventoy2Disk.sh -u /dev/sdb` and now it works fine.

Thanks for your reactivity and help.

Congratulations for this great tool, I love it.

**Comment by cypa** [comment]
confirm the same issue on Arch - first I've killed the installation process in the middle, then install failed ...
I'll try to find script workaround to prevent such issues

**Comment by sebma** [comment]
@cypa Here's what I added at the end of my `VentoyUpdate.sh` script : 
```bash
ventoyROOT=/opt/ventoy
....
test -f $ventoyROOT/tool/x86_64/ash && sudo rm -v $ventoyROOT/tool/x86_64/ash
```
