### ISSUE TITLE
[issue]: website access

### ISSUE THREAD

**Issue by rafalohaki** [ventoy/Ventoy#1228]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

111111111111

### What about latest release

No. I didn't try the latest release.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

111111111

### What happened?

I cant access website with nordvpn.

**Comment by ventoy** [comment]
Can you `ping 47.90.13.101` ?

**Comment by rafalohaki** [comment]
> Can you `ping 47.90.13.101` ?

ip access: 
![image](https://user-images.githubusercontent.com/20607107/141649816-72172676-3880-4ddf-bf31-e08999359546.png)

domain access: 
![image](https://user-images.githubusercontent.com/20607107/141649818-9535f6bc-2e4b-47b5-a22b-6f8800d9f6e2.png)

my ip and dns using nordvpn:
![image](https://user-images.githubusercontent.com/20607107/141649827-b2be0941-7484-4260-8118-88ae103d778b.png)

**Comment by ventoy** [comment]
Maybe something about the DNS, you can add a local entry in `C:\Windows\System32\drivers\etc\hosts`  as follows and retry:
```
# localhost name resolution is handled within DNS itself.
#	127.0.0.1       localhost
#	::1             localhost

47.90.13.101 www.ventoy.net

```

**Comment by iblue** [comment]
I investigated this. ventoy.net is censored by NordVPN.

I get the following DNS records when being connected to NordVPN (from the standard DNS servers as well as from the Google DNS at 8.8.8.8 and 8.8.4.4). I tried servers in the UK, the US, Albania, Norway, Germany and Japan.
```
;; ANSWER SECTION:
ventoy.net.		300	IN	A	198.18.0.181

;; AUTHORITY SECTION:
ventoy.net.		300	IN	NS	ns1.ventoy.net.
ventoy.net.		300	IN	NS	ns2.ventoy.net.

;; ADDITIONAL SECTION:
ns1.ventoy.net.		300	IN	A	103.86.96.100
ns2.ventoy.net.		300	IN	A	103.86.99.100
```
198.18.0.181 is in a reserved range (198.18.0.0/15 as per RFC5735) and thus not reachable.

For www.ventoy.net, I get (yes, also when querying 8.8.8.8 and 8.8.4.4):
```
;; AUTHORITY SECTION:
ventoy.net.		300	IN	SOA	dns1.nordvpn.com. hostmaster.nordvpn.com. 2021092800 14400 3600 2419200 3600
```

When not connected to NordVPN I get the following records (from my ISP as well as from 8.8.8.8 and 8.8.4.4):
```
;; ANSWER SECTION:
ventoy.net.		600	IN	A	47.90.13.101
```

and
```
;; ANSWER SECTION:
www.ventoy.net.		600	IN	A	47.90.13.101
```
