### ISSUE TITLE
[Request]: 

### ISSUE THREAD

**Issue by soares23** [ventoy/Ventoy#1232]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.60

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

1000GB

### What happened?

Hi, 

Can you maybe implement on Menu Tip Plugin that not only image file can be use but also directory, it would be nice to have if not is not a problem. 

Thank's for your great work.

Best Regards
soares23

**Comment by ventoy** [comment]
Ventoy 1.0.61 released with `dir` option in `menu_tip` plugin.

**Comment by soares23** [comment]
Thanks to implement it. 
Have a nice day.
