### ISSUE TITLE
[issue]: Windows 10 auto_install not detected

### ISSUE THREAD

**Issue by ameer1234567890** [ventoy/Ventoy#1248]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.61

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### What happened?

I have setup auto_install for Windows 10 image. My `ventoy/ventoy.json` is as follows:
```
{
    "theme": {
        "file": "/ventoy/themes/Ventoy-Dark/theme.txt",
	"ventoy_color": "white"
    },
    "control": [
        { "VTOY_WIN11_BYPASS_CHECK": "1" }
    ],
    "auto_install": [
        {
            "image": "/Win11_English_x64.iso",
            "template": "/ventoy/script/windows_unattended.xml"
        }
    ]
}
```

And my `ventoy/script/windows_unattended.xml` exists at that specific location.
However, While booting Ventoy and selecting the Windows 10 ISO, Ventoy does not show the prompt for auto_install.

**Comment by steve6375** [comment]
Why do you say windows 10 image when you specify Win11 iso in JSON file?

**Comment by Remzi1993** [comment]
I have also problems using the latest version of Ventoux with Windows 10

**Comment by steve6375** [comment]
Check spelling and case sensitivity.
Give a screenshot of both iso and XML files with path and complete actual JSON file used so we can compare. It works for everyone else so must be something special about your case .

**Comment by ventoy** [comment]
Most probably  `/Win11_English_x64.iso`  or `/ventoy/script/windows_unattended.xml`  does not match the case with its real path.  

Use the following menu to check the json file.
```
F5 Tools ---> Check plugin json configuration (ventoy.json) ---> Check auto install plugin configuration
```

**Comment by Remzi1993** [comment]
> Most probably `/Win11_English_x64.iso` or `/ventoy/script/windows_unattended.xml` does not match the case with its real path.
> 
> When you in Ventoy's main menu, press `F5` to check the json file as follows:
> 
> ```
> F5 Tools ---> Check plugin json configuration (ventoy.json) ---> Check auto install plugin configuration
> ```

Strange thing is that Windows 10 international works fine, but English version doesn't work. I only needed windows 10 temporarily for updating bios.

After that I successfully installed Manjaro.

**Comment by ventoy** [comment]
What is the result of:
```
F5 Tools ---> Check plugin json configuration (ventoy.json) ---> Check auto install plugin configuration
```

**Comment by Remzi1993** [comment]
> What is the result of:
> 
> ```
> F5 Tools ---> Check plugin json configuration (ventoy.json) ---> Check auto install plugin configuration
> ```

I already remove the other .iso and used the other one. I can try it again if you want?

**Comment by ventoy** [comment]
@ameer1234567890  any update?

**Comment by ameer1234567890** [comment]
Never mind. It was my mistake specifying Windows 11 instead of Windows 10.
