### ISSUE TITLE
Macbook上无法引导

### ISSUE THREAD

**Issue by xiaozhuai** [ventoy/Ventoy#125]
试了下在我的MacBook Pro上无法启动

如图

![DC97FA4B-F8E6-4B98-8B98-A38385988C44](https://user-images.githubusercontent.com/4773701/82154740-74cdf500-98a2-11ea-9ca4-8b2dbc641c2a.jpeg)

**Comment by ljk5403** [comment]
Me too. MacBook Air 2017.

**Comment by ventoy** [comment]
Ventoy doesn't offcially support Mac
