### ISSUE TITLE
[issue]: SquashFS for the Part 1 partition

### ISSUE THREAD

**Issue by nao20010128nao** [ventoy/Ventoy#1251]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

None, but just asking

### What about latest release

No. I didn't try the latest release.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

None

### Image file checksum (if applicable)

No.

### What happened?

Hi

I'm interested in using Ventoy, but is there any plans for supporting reading SquashFS when it was used for the Part 1 partition?
That makes it easier to build a disk image without mounting.

Thanks

**Comment by ventoy** [comment]
No.
Squashfs is not supported and I have no plan to support it.
The filesystem in partition 1 must have linear layout and can not be compressed.
So squashfs/btrfs are not supported because there exist compression in these filesystems.

**Comment by nao20010128nao** [comment]
I see, thanks for response!
