### ISSUE TITLE
Ventoy is showing the window without any information

### ISSUE THREAD

**Issue by olekstomek** [ventoy/Ventoy#1252]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.61

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

Kingston DataTraveler

### Image file download link (if applicable)

https://www.microsoft.com/en-gb/software-download/windows10

### What happened?

When I try to run an ISO image of Windows 10, I get a window with a black background with no information about the problem or error. I left it like that for about 15 minutes and it didn't change.
I created a flash drive with the same image using [Rufus ](https://github.com/pbatard/rufus )- a similar problem, i.e. the image does not start and the background is black.
Finally, I managed to run the image that I created directly with the tool from Microsoft (it downloaded new ISO). It works.
There may be something wrong with the ISO I downloaded, but the question remains why is Ventoy showing the window without any information?
![1637097505888](https://user-images.githubusercontent.com/26818304/142068597-9efc0dbc-eccf-45cc-8c9a-6df17c0268c3.jpg)

**Comment by ventoy** [comment]
3 options to try.
1. Change to UEFI mode and retry.
2. Use `ctrl+w`  WIMBOOT mode.  https://ventoy.net/en/doc_wimboot.html
3. Use `ctrl+i` , please refer: https://github.com/ventoy/Ventoy/discussions/1187

**Comment by olekstomek** [comment]
Currently, I no longer have access to this computer and cannot check the steps you have written. 
I am closing this issue. 
I see that the thread you provided is a similar case.
