### ISSUE TITLE
[Success Image Report]: windows_10_ltsc_2021

### ISSUE THREAD

**Issue by erlizn** [ventoy/Ventoy#1257]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.61

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

zh-cn_windows_10_enterprise_ltsc_2021_x64_dvd_033b7312.iso

### Image file checksum type

SHA256

### Image file checksum value

C117C5DDBC51F315C739F9321D4907FA50090BA7B48E7E9A2D173D49EF2F73A3

### Image file download link (if applicable)

mag

### Test envrionment

Lenove Thinkpad T460s 

### More Details?

This image file booted successfully in Ventoy

**Comment by ventoy** [comment]
Thanks!
