### ISSUE TITLE
Here is a GUI for ventoy Linux

### ISSUE THREAD

**Issue by Philippe734** [ventoy/Ventoy#126]
It's not an issue. I share my little contrib. Here is a front end, a GUI for ventoy:
https://github.com/Philippe734/Snippets/tree/master/GUI-for-ventoy
It need yad: `sudo apt install yad`

**Comment by blackcrack** [comment]
@ventoy could maybe to be good if it is sticky for the Linuxcommunity :)

**Comment by ventoy** [comment]
Interesting, I will test it later.

**Comment by josuesoto1** [comment]
I am testing it but the following errors occcurs, did I miss something?
./Ventoy.sh: 30: [: sdb 3.7G /media/user/4GBx20USB 4GBx20USB: unexpected operator
./Ventoy.sh: 38: ./Ventoy.sh: xterm: not found
sudo: exfatlabel: orden no encontrada

**Comment by yochananmarqos** [comment]
It also requires `xterm` and `exfat-utils` (provides `exfatlabel`) at least on Arch-based distros.

**Comment by johanlosada** [comment]
I would like information to make it work in Manjaro-Linux, I do not understand why it is the year 2021 and they still continue with the thought that Linux is only for programmers I am an Electrical Engineer I understand the basics and I like the moldable, I have everything I need for work even Bricscad for editing drawings .CAD and everything is graphical, it goes well, it was easy to install and I don't understand how you make a graphical interface for windows and not for Linux 😔 ..

**Comment by arthurflor23** [comment]
> I would like information to make it work in Manjaro-Linux, I do not understand why it is the year 2021 and they still continue with the thought that Linux is only for programmers I am an Electrical Engineer I understand the basics and I like the moldable, I have everything I need for work even Bricscad for editing drawings .CAD and everything is graphical, it goes well, it was easy to install and I don't understand how you make a graphical interface for windows and not for Linux  ..

I have the same question here

**Comment by ventoy** [comment]
ventoy 1.0.36 release.
experimental Linux GUI base on web browser.
https://www.ventoy.net/en/doc_linux_webui.html

**Comment by Toadfield** [comment]
@ventoy I don't get how I can use the web based gui.
What do I need to install?
If I install the normal ventoy package with pacman and then run the command from the guide,then nothing happens.
Also,why is it web based and not just a normal gui?

**Comment by yochananmarqos** [comment]
@Toadfield Run `sudo ventoyweb`.

**Comment by johanlosada** [comment]
if you installed from pacman =
open the console or terminal
Copy and paste the following command
-------------------------------------------------------------------
sudo /opt/ventoy/VentoyWeb.sh
------------------------------------------------------------------

then copy the example url

http://127.0.0.1:24680

open and paste in the browser example firefox

Enjoy

**Comment by yochananmarqos** [comment]
@johanlosada Yes, what I said is exactly the [same thing](https://aur.archlinux.org/cgit/aur.git/tree/ventoyweb?h=ventoy-bin).

**Comment by johanlosada** [comment]
Maybe later a quick access in the menu example .desktop that automatically opens the web browser!
thank you for the work ventoy group.

**Comment by yochananmarqos** [comment]
I was thinking of doing that, but haven't gotten around to it yet.

**Comment by Toadfield** [comment]
Thanks,but I still don't get why it needs to open a web browser at all.
I mean,what's the advantage?
From what I can see it just has disadvantages,you need internet access and having to open a web browser is not as cool as just using a normal gui program.

**Comment by ventoy** [comment]
There are many different desktop environment in Linux. GNOME2/GNOME3/KDE/XFCE/LXDE......
So there is no universal GUI solution for all linux distros.
The GUI based on web browser is the simplest and relatively most universal solution.

**Comment by ventoy** [comment]
> Thanks,but I still don't get why it needs to open a web browser at all.
> I mean,what's the advantage?
> From what I can see it just has disadvantages,you need internet access and having to open a web browser is not as cool as just using a normal gui program.

There are many different desktop environment in Linux. GNOME2/GNOME3/KDE/XFCE/LXDE......
So there is no universal GUI solution for all linux distros.
The GUI based on web browser is the simplest and relatively most universal solution.

**Comment by ventoy** [comment]
@Toadfield 
Besides, we visit 127.0.0.1 from the web browser, so we don't need internet access.

**Comment by ventoy** [comment]
There are still some desktop environments that don't use QT and GTK.
Even just with GTK and QT, I need to maintain two or more different sets of code.

**Comment by Toadfield** [comment]
Then just one of those.
Nearly every distro supports those by default and it's good.
The only people who don't use it are terminal wizards,but even they need to use a browser and most browsers use qt or gtk.
So just one of them would also be good.

**Comment by trymeouteh** [comment]
A Qt GUI for Windows, Mac and Linux will be swell and user friendly for all.

**Comment by ChaosBlades** [comment]
It would be epic if someone got this added to the debian/ubuntu repo or got a 3rd party PPA up and running.

An AppImage would also be acceptable. Or even submit it to FlatHub.org

**Comment by ventoy** [comment]
Ventoy-1.0.52 release with native Linux GUI
https://www.ventoy.net/en/doc_linux_gui.html
