### ISSUE TITLE
[issue]: kali linux persistence 

### ISSUE THREAD

**Issue by ValgulNecron** [ventoy/Ventoy#1260]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.61

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128gb

### What happened?

so i'm probably just stupid but i cant make the persistence for kali linux (2021.3a) work i have the ventoy.json configure properly since no error is reported but when i'm boot on kali i dont have the persistence (i choose the boot option with persistence and not the encrypt one) and i use your prebuild file (persistence_ext4_4GB_persistence.dat)

**Comment by steve6375** [comment]
We can't tell if you have configured it properly because you have not added a zip file with the ventoy.json file and we don't know the exact full path of the persistence file.

**Comment by ValgulNecron** [comment]
[ventoyjson.zip](https://github.com/ventoy/Ventoy/files/7564188/ventoyjson.zip)
the persistence path "F:\persistence\persistence_4gb_kali.dat"
and the kali iso  "F:\Linux\kali-linux-2021.3a-live-amd64.iso"
sorry i havve forget to add them

**Comment by steve6375** [comment]
seems OK. Have you disabled Secure Boot?
Did Ventoy allow you to choose to boot without persistence or boot using the .dat file?

**Comment by steve6375** [comment]
I have tested kali-linux-2021.3-live-amd64.iso and it works OK (see my eBook 'Getting started with Ventoy').
Maybe 2021.3a has a bug?

**Comment by ValgulNecron** [comment]
> seems OK. Have you disabled Secure Boot? Did Ventoy allow you to choose between 'boot without persistence' or 'boot using the .dat file' before booting to Kali?

secure boot disable and don't have a choice when i choose kali 

> I have tested kali-linux-2021.3-live-amd64.iso and it works OK (see my eBook 'Getting started with Ventoy'). Maybe 2021.3a has a bug?

where did i can find it ?

**Comment by steve6375** [comment]
Ventoy should give you the choice to boot with or without persistence
Therefore check for bad case or path in your ventoy.json
![image](https://user-images.githubusercontent.com/1469350/142458070-d285d366-3be3-4ef0-a1d6-934e10428846.png)

**Comment by ValgulNecron** [comment]
dont know if it can help but juste tried the ventoy json test 
and it"s say 
"not array type 4 
##########dump persistence############
press enter to exit"

**Comment by steve6375** [comment]
I don't know what that message means. The syntax of the json looks OK.
So maybe something is wrong with your .dat file?
Can you check that the USB .dat file is same as the extracted .dat file. Same size/contents?

**Comment by steve6375** [comment]
Try putting [   ] around the persistence section
```
    "persistence": [
    {
            "image": "/Linux/kali-linux-2021.3a-live-amd64.iso",
            "backend": "/persistence/persistence_4gb_kali.dat"
    }
	]
}

```

**Comment by steve6375** [comment]
A better error message could output. e.g.
e.g. 'Error: Array data structure using [ ] expected in this section of json file'

**Comment by ValgulNecron** [comment]
> Try putting [ ] around the persistence section
> 
> ```
>     "persistence": [
>     {
>             "image": "/Linux/kali-linux-2021.3a-live-amd64.iso",
>             "backend": "/persistence/persistence_4gb_kali.dat"
>     }
> 	]
> }
> ```
> 
> it seems to always look for an array which is within square brackets [ xxxxxx ].

tried and nothing change (no choice when choosing kali) 

> I don't know what that message means. The syntax of the json looks OK. So maybe something is wrong with your .dat file? Can you check that the USB .dat file is same as the extracted .dat file. Same size/contents?

same hash tried to replace it anyway and change nothing

**Comment by steve6375** [comment]
Do you still get error when using F5 to check it?

**Comment by steve6375** [comment]
[ventoy.zip](https://github.com/ventoy/Ventoy/files/7564749/ventoy.zip)

**Comment by ValgulNecron** [comment]
> Do you still get error when using F5 to check it?

this time i have a file name error 
does ventoy is case sensitive ? like a g is not a G ? (used the win 11 copy as path option for geting the path)

**Comment by steve6375** [comment]
yes - I already said to check case and paths. Also Windows Explorer can lie if you change the case of the filename!
So not believe Explorer !!!
try Windows command line  DIR command instead.

**Comment by ValgulNecron** [comment]
so win explorer and dir command give me the same name 
but have a name error
tried to use the ren command for changing it for a no space no upercase character and work fine now thank you

**Comment by frankip** [comment]
Ventoy has a program VentoyPlugson.sh that can help to link your DAT files so that ventoy can recognize the persistent dat file that you will use for persistence. to run the ventoy plugins program you need to link it to your removable drive `sudo bash VentoyPlugson.sh /dev/sdX`  The X should represent you removable drive. you can find your drive by running `lsblk` it will give you a link to a web version where you can be able to customize the plugins. go to the persistent section on the side panel click add then add the absolute path to your ISO file and DAT file then save. you can also chose auto select which means it will be the default persistence file to be used. restart and after you have chosen you ISO file you will see an extra step where you can choose to use persistence or not. if you had chosen auto-select the selected file will be used instead and you can boot to your OS with persistence
