### ISSUE TITLE
[issue]: Suppport an alternate installation mode that installs ventoy into the first partition and uses the second partition for ISOs

### ISSUE THREAD

**Issue by manuelVo** [ventoy/Ventoy#1262]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.61

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

8 GB

### What happened?

The laptop I'm trying to boot refuses to boot from the ventoy USB-Stick with an error message that indicates that it determined the Stick to be a mass storage device, form which it cannot boot. I assume that this is the case because the bios is only checking if the first partition is bootable, ignoring all other partitions.

To help with such devices, I propose a setting that formats ventoy partitions in a different order: The ventoy boot partition would become the first partition and the ISO partition would become the second one.

**Comment by ventoy** [comment]
Ventoy does set partition 1 bootable and partition 2 unbootable.
You can check with some partition tool.  Ventoy partition 1 flag is 80, and partition 2 flag is 00.
So I think it is not the root cause.

**Comment by manuelVo** [comment]
You're right. I've played around in the bios of that device a little more, and it turns out that the bios settings were simply ambiguously named. Ventoy now boots just fine on the device. Thanks!
