### ISSUE TITLE
[issue]: Latest LibreELEC generic image does not work

### ISSUE THREAD

**Issue by Silejonu** [ventoy/Ventoy#1268]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.61

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

256GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://libreelec.tv/downloads/generic/

### What happened?

First of all, the template doesn't allow me to select it, but I tested both GPT and MBR (would be nice to change the template a bit!). =)

LibreELEC boots, and I get presented with 3 options: installer, live & run. None of them work and all of them show the same errors (see image below).
Note that the initial menu with _installer_, _live_ & _run_ is different from the one that shows up when booting LibreELEC on a "regular" flash drive.

Tested on two different computers, same exact result.

![IMG_20211122_170641](https://user-images.githubusercontent.com/48565914/142913320-e09c786f-d0ff-44e9-bd8f-4aa2349a2e51.jpg)

**Comment by ventoy** [comment]
@Silejonu  Please try with latest 1.0.62

**Comment by Silejonu** [comment]
> @Silejonu Please try with latest 1.0.62

I just tried with both GPT and MBR, and it now works fine. Thank you, I'm closing the issue!
