### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by mauriciolazo** [ventoy/Ventoy#1272]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.61

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

Win10_21H2_EnglishInternational_x64

### Image file checksum type

MD5

### Image file checksum value

2c112aa1c2b8ed59c804b3a2ed85b10e

### Image file download link (if applicable)

https://www.microsoft.com/en-us/software-download/windows10ISO

### Test envrionment

HP Probook 645 G1

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks. I have updated the page.

**Comment by rubanunes** [comment]
I've tried installing it and failed multiple times. Only when I switched to Rufus was I able to fully install Windows.
