### ISSUE TITLE
分区往前错位了0.02MiB

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#1275]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.61

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

123,060,879,360 B    117,360 MiB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

github

### What happened?

我的闪迪U盘容量是 2MiB 的整数倍。我想让所有的分区都至少 1MiB对齐，前面预留1MiB（分区表+引导信息+未格式化），末端也预留1MiB（未格式化+备份分区表）。
然后，我设置了，Ventoy的ESP后面预留2049MiB的空闲。结果，前面的exFAT分区比理论中的要小0.02MiB，并没有2MiB的整数倍对齐。最后面的部分，用Gparted查看，是2049.02MiB。建立了2048MiB的FAT32分区以后，后面剩下1.02MiB，比理想中的多了0.02MiB。

我估摸着，是Ventoy设置预留空间的时候，并没有把末端0.02MiB的备份分区表考虑在内。

希望，以MiB为单位，设置预留空间的时候，可以把末端的0.02MiB的分区表考虑在内。这样方便操作，并且有利于对齐到 至少 1MiB的整数倍。否则，还要扩大1024倍，以KiB为单位，再把预留空间的数值减去 20KiB，增大了计算量，操作更麻烦。

**Comment by ventoy** [comment]
在GPT模式下预留空间确实不包含备份分区表的部分。所以安装Ventoy之后，分区是以4KB对齐，但是不是以1MiB对齐。
如果希望严格1MiB对齐可以这样做。
1、U盘清除Ventoy，恢复默认状态
2、使用分区工具分出第一个分区，从1MiB开始，大小设置为你希望的值（以1MiB或2MiB对齐，都可以）。在第一个分区后面要留有一部分空闲空间
3、使用 Ventoy 的无损安装功能安装即可。

Ventoy无损安装时，如果第一个分区后面剩余空间足够，则就只会在紧贴着第一个分区的后面插入32MB的VTOYEFI分区，不会改变第一个分区位置和大小。

**Comment by 1457384613gh** [comment]
> 在GPT模式下预留空间确实不包含备份分区表的部分。所以安装Ventoy之后，分区是以4KB对齐，但是不是以1MiB对齐。
> 如果希望严格1MiB对齐可以这样做。
> 1、U盘清除Ventoy，恢复默认状态
> 2、使用分区工具分出第一个分区，从1MiB开始，大小设置为你希望的值（以1MiB或2MiB对齐，都可以）。在第一个分区后面要留有一部分空闲空间
> 3、使用 Ventoy 的无损安装功能安装即可。
> 
> Ventoy无损安装时，如果第一个分区后面剩余空间足够，则就只会在紧贴着第一个分区的后面插入32MB的VTOYEFI分区，不会改变第一个分区位置和大小。
> 
> 
> 
> 
> 

第一个分区，从2MiB处开始的，后面预留的远大于32MiB，可以进行无损安装吗？因为，我想2MiB整数倍对齐。

**Comment by ventoy** [comment]
不可以，第一个分区只能固定从1MiB的位置开始。

**Comment by 1457384613gh** [comment]
> 不可以，第一个分区只能固定从1MiB的位置开始。

可不可以开发这样一个功能？

手动输入理想中的exFAT分区大小，设为x MiB。（x<U盘容量-34MiB）
然后，Ventoy自动分区，1 MiB 前端 + x MiB exFAT +32 MiB VTOYEFI + 剩余。

这样，就不用计算剩余空间大小了，直接正向设计 exFAT大小，更方便。

**Comment by ventoy** [comment]
可以肯定是可以的。只是一般用户使用时并不是非常在意exfat分区必须固定多少MiB, 多一点少一点都不行。这种情况很少。

这个其实就是我前面说的那样，你自己先创建exfat这个分区，大小你自己定，完了之后Ventoy无损安装就可以了。
