### ISSUE TITLE
[issue]: Windows11 installation problem { "VTOY_WIN11_BYPASS_CHECK": "1" } parameter is not working in ventoy.json

### ISSUE THREAD

**Issue by crasadure** [ventoy/Ventoy#1278]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.61

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

16gb

### Disk Manufacturer

Virtual Disk (vhd)

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://www.microsoft.com/tr-tr/software-download/windows11

### What happened?

Hi @ventoy 
As you know , you had added  to Global control plugin a parameter is liked that **VTOY_WIN11_BYPASS_CHECK** for install Windows11 to BYPASS TPM control
**{ "VTOY_WIN11_BYPASS_CHECK": "1" }**
I added this line to vtoy.json and dowloaded orjinal WIN11 ISO and tried to install Win11 but TPM control can not BYPASS so installation can not completed. 
I think, Microsoft had changed control system of TPM 
İs there any solution about this subject for BYPASS this control mechanism?
![tpm error](https://user-images.githubusercontent.com/54566818/143720066-b235b68d-9d5e-497a-8bb4-8226b1753746.jpg)
I have captured a video about this issue: 
https://vimeo.com/650658487
My **ventoy.json** file :
[ventoy.zip](https://github.com/ventoy/Ventoy/files/7612363/ventoy.zip)

**Comment by steve6375** [comment]
How do you know that your ventoy.json file is correct?

**Comment by crasadure** [comment]
> How do you know that your ventoy.json file is correct?

[ventoy.zip](https://github.com/ventoy/Ventoy/files/7612354/ventoy.zip)
ı uploaded my ventoy.json file....you can control it

**Comment by ventoy** [comment]
When this message popup press `Shift+F10` to launch cmd.exe and run `regedit`  and check that whether the following registries have been created.
```
HKEY_LOCAL_MACHINE\SYSTEM\Setup\LabConfig\BypassRAMCheck
HKEY_LOCAL_MACHINE\SYSTEM\Setup\LabConfig\BypassTPMCheck
HKEY_LOCAL_MACHINE\SYSTEM\Setup\LabConfig\BypassSecureBootCheck
HKEY_LOCAL_MACHINE\SYSTEM\Setup\LabConfig\BypassCPUCheck
HKEY_LOCAL_MACHINE\SYSTEM\Setup\LabConfig\BypassStorageCheck
```

**Comment by crasadure** [comment]
> When this message popup press `Shift+F10` to launch cmd.exe and run `regedit` and check that whether the following registries have been created.
> 
> ```
> HKEY_LOCAL_MACHINE\SYSTEM\Setup\LabConfig\BypassRAMCheck
> HKEY_LOCAL_MACHINE\SYSTEM\Setup\LabConfig\BypassTPMCheck
> HKEY_LOCAL_MACHINE\SYSTEM\Setup\LabConfig\BypassSecureBootCheck
> HKEY_LOCAL_MACHINE\SYSTEM\Setup\LabConfig\BypassCPUCheck
> HKEY_LOCAL_MACHINE\SYSTEM\Setup\LabConfig\BypassStorageCheck
> ```

I controlled this registry Entry...There were these registry entries. I showed this registry entries in my captured video. I tested this happen on vhd disk. Can it be problem test it on vhd disk?

**Comment by ventoy** [comment]
I didn't test  in VHD, maybe these registries have no effect when install to VHD.
You can test in physical machine for comparision.

**Comment by crasadure** [comment]
I have tested Win11 in real machine. It was bypassed TPM control..this was my fault. thanks your help @ventoy
