### ISSUE TITLE
[Improvement]: Grub2 version

### ISSUE THREAD

**Issue by KrinalPatel889** [ventoy/Ventoy#1279]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.61

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

16gb

### What happened?

Hello @ventoy I'm curious regarding this question.

Ventoy uses grub2 version 2.04 and the latest stable version is 2.06, so, can grub2 in Ventoy be updated or not?

I mean is it easy for Ventoy to adopt grub2 2.06 or grub2 in Ventoy is highly modified that it's not possible to update it?

**Comment by ventoy** [comment]
Ventoy will update to grub2 2.06 in the future. But ventoy heavily modify grub 2.04, so it will take a long time to update.
