### ISSUE TITLE
[Success Image Report]: clonezilla-live-2.8.0-27-amd64.iso

### ISSUE THREAD

**Issue by gottalovebrando** [ventoy/Ventoy#1284]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

ventoy-1.0.61-windows

### BIOS Mode

Both

### Partition Style

GPT

### Image file name

clonezilla-live-2.8.0-27-amd64.iso

### Image file checksum type

SHA256

### Image file checksum value

96aa5a4af088d8adfcf4eba956a3b85d115bb2329b0f0eb5d36fa7bb8dc12eb1

### Image file download link (if applicable)

https://clonezilla.org/downloads/download.php?branch=stable

### Test envrionment

Multiple (see details)

### More Details?

This image file booted successfully in Ventoy.

Tested on:
Microsoft surface go model 1824	
Processor	Intel(R) Pentium(R) CPU 4415Y @ 1.60GHz   1.61 GHz
Installed RAM	4.00 GB (3.89 GB usable)
System type	64-bit operating system, x64-based processor
Installed OS (just in case)	Windows 10 Pro
	
HP Pavilion Laptop 14-ce0xxx	
Processor	Intel® Core™ i5-8250U CPU @ 1.60GHz × 8 
Installed RAM	15.5 GiB (1x16GB)
System type	64-bit operating system, x64-based processor
Installed OS (just in case)	Ubuntu 20.04.3 LTS
	
Gigabyte Tech. H61MA-DV2 Motherboard (desktop)	
Processor	i3-2100 @ 3.1 GHz
Installed RAM	4 GB (2x2GB)

**Comment by ventoy** [comment]
Thanks. I have updated the page.
