### ISSUE TITLE
[issue]: memtest86 and memtest86+ are two separate isos

### ISSUE THREAD

**Issue by gottalovebrando** [ventoy/Ventoy#1285]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

ventoy-1.0.61-windows

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

32GB

### What happened?

[This page](https://www.ventoy.net/en/distro_iso/271.html) lists two versions of memtest86 and one version of memtest86+. It is a little confusing but they are actually two separate code bases maintained by two separate orgs.

See here: https://www.memtest86.com/memtest86.html
then go to The History of MemTest86
and then 2002 - 2004

memtest86+ seems to only have support for legacy while different versions of memtest86 support legacy or UEFI.
See here:
https://www.memtest86.com/compare.html

**Comment by ventoy** [comment]
Thanks.  I have updated the page.
