### ISSUE TITLE
[Success Image Report]: tails amd64-4.24-img

### ISSUE THREAD

**Issue by gottalovebrando** [ventoy/Ventoy#1286]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

ventoy-1.0.61-windows

### BIOS Mode

Both

### Partition Style

GPT

### Image file name

tails-amd64-4.24.img

### Image file checksum type

SHA256

### Image file checksum value

c90ef3821b9b31e36b009befabac15b629e84548ee1fc3deb16847fe97889177

### Image file download link (if applicable)

https://tails.boum.org/install/download/

### Test envrionment

Multiple (see details)

### More Details?

This image file booted successfully in Ventoy (5 separate tests). Slightly newer version of tails than listed on website so submitting. Used the machines at end of message.

SIDE NOTE: On desktop (machine #3), needed to try booting twice (in UEFI mode, secure boot incapable I think). First time I got an error (excerpt below from dmesg):
kernel panic exit code:0x00007f00
Second time was a successful boot.

Machine #1: Microsoft surface go model 1824	Secure boot, UEFI
Processor	Intel(R) Pentium(R) CPU 4415Y @ 1.60GHz   1.61 GHz
Installed RAM	4.00 GB (3.89 GB usable)
System type	64-bit operating system, x64-based processor
Installed OS (just in case)	Windows 10 Pro
	
Machine #2: HP Pavilion Laptop 14-ce0xxx	Secure boot, UEFI
Processor	Intel® Core™ i5-8250U CPU @ 1.60GHz × 8 
Installed RAM	15.5 GiB (1x16GB)
System type	64-bit operating system, x64-based processor
Installed OS (just in case)	Ubuntu 20.04.3 LTS
	
Machine #3: Gigabyte Tech. H61MA-DV2 Motherboard (desktop)	secure boot disabled (incapable?), UEFI and legacy BIOS capable
Processor	i3-2100 @ 3.1 GHz
Installed RAM	4 GB (2x2GB)

**Comment by ventoy** [comment]
Thanks. I have updated the page.
