### ISSUE TITLE
提示no bootfile found for uefi

### ISSUE THREAD

**Issue by feipinxiang** [ventoy/Ventoy#129]
想用ventoy-1.0.10安装软路由系统高恪 http://docs.gocloud.cn/docs/chanpinshouce003/chanpinshouce003-1b7oth096hub8
2020年03月20日 | 4.9.0.17952 | 链接：https://gocloud.lanzous.com/iah42ng

下载了GOCLOUD-SX1200-4.9.0.17952.iso，启动后提示no bootfile found for uefi！ maybe the image does not support x64 uefi
这个是这个系统不规范的原因么？（我在pve虚拟机内是可以用此iso安装系统的）

**Comment by ventoy** [comment]
你是在UEFI模式下安装的，但是这个ISO文件只支持Legacy BIOS模式，不支持UEFI模式。
你需要切换到Legacy BIOS下。

**Comment by feipinxiang** [comment]
是不是我这软路由硬件的问题，开启Legacy Only的话就无法识别ventoy的U盘了
![微信图片_20200518213136.jpg](https://i.loli.net/2020/05/18/YLav7qekilTd9sQ.jpg)
![微信图片_20200518213145.jpg](https://i.loli.net/2020/05/18/RxgQnV4jJmcT1Io.jpg)

**Comment by ventoy** [comment]
你需要先确认下在这个机器上U盘启动有没有问题。
可以试试用其他工具，比如rufus做个可启动U盘，只看看有没有启动项就可以了。
另外，BIOS里面和USB启动相关的选项也要打开。

**Comment by feipinxiang** [comment]
感谢，改了bios里的一些Usb相关设置和硬盘排序可以启动了。
