### ISSUE TITLE
Ventoy 1.0.61 not load reactos iso

### ISSUE THREAD

**Issue by Augusto7743** [ventoy/Ventoy#1292]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.61

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

80 GB

### What happened?

Ventoy 1.0.61 not load reactos iso from link below
https://reactos.org/download

Working with others OS ISO.
Only reporting.

**Comment by ventoy** [comment]
reactos is not supported.
https://www.ventoy.net/en/distrowatch.html

**Comment by sonichy** [comment]
How to load ReactOS LiveCD ?

**Comment by ventoy** [comment]
> How to load ReactOS LiveCD ?

reactos LiveCD is not supported.

**Comment by steve6375** [comment]
Can I install ReactOS from a pendrive/stick?

There is no known way to install ReactOS from pendrive/stick. Any method relies in ReactOS installing itself, so it needs USB support to accomplish the task. ReactOS doesn't have USB support so:
- Use a CD-RW instead, or a normal CD :)
https://reactos.org/forum/viewtopic.php?f=4&t=8814

**Comment by steve6375** [comment]
If you add a bootcd ISO, that seems to work too!
![image](https://user-images.githubusercontent.com/1469350/196182741-b80061b3-f7ec-4e8d-ac54-c6c2698bd1d4.png)
