### ISSUE TITLE
[Question or Request]: 

### ISSUE THREAD

**Issue by soares23** [ventoy/Ventoy#1293]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.62

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

512GB

### What happened?

Hi,
I have a question.

Does the new "F5 Tools --> Theme Select " has also like the other Option in F5 Menu a Built-in Class?
I don't have seen it in the list in your webpage (https://www.ventoy.net/en/plugin_menuclass.html#builtin_class_notes). If a Built-in Class is defined, can you please tell me what the name is.
If no Built-in Class exist, can you maybe implement it on the next release that would be nice. 

Thanks.

**Comment by ventoy** [comment]
There exist, I have updated the page.
Built-in Class|Menu
-|-
debug_theme_select | F5 Tools --- Theme Select  
debug_theme_item | F5 Tools --- Theme Select --- Theme Item

**Comment by soares23** [comment]
Thank's for the reply.
