### ISSUE TITLE
[issue]: An error occurred during the installation, no 'Generate VTSI File'

### ISSUE THREAD

**Issue by Melonadev** [ventoy/Ventoy#1296]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.62

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

14.5 GiB

### Disk Manufacturer

Apacer

### Image file checksum (if applicable)

No.

### What happened?

**ISSUE 1:** Installing on Windows 10 SUCCESSFUL, but Linux NOT SUCCESSFUL:

Operating System: openSUSE Leap 15.3
KDE Plasma Version: 5.18.6
KDE Frameworks Version: 5.76.0
Qt Version: 5.12.7
Kernel Version: 5.3.18-59.34-default
OS Type: 64-bit

My install attempt failed (briefly after lagging at 80% for around 5 seconds), producing this error message.
1st install attempt: [log.txt](https://github.com/ventoy/Ventoy/files/7648467/log.txt)
2nd install attempt (immediately after the 1st attempt, without pulling out the USB): [log.txt](https://github.com/ventoy/Ventoy/files/7648559/log.txt)
![web_error](https://user-images.githubusercontent.com/66422959/144583035-abf88e05-1314-4794-ab4b-b3d1905db4cc.png)

After pulling out the USB and sticking it in again, this time the system doesn't even detect the USB, but Ventoy still lists it. All install attempts after that result in errors.

**ISSUE 2:** I have an issue with the Linux GUI (both WebUI and GTK/QT), regarding the option 'Generate VTSI File' detailed in [this help page (see first step under 'Methods 1')](https://www.ventoy.net/en/doc_ventoy2disk.html):
![image](https://user-images.githubusercontent.com/66422959/144581815-c1b560cd-944a-4e01-ae70-bb560b2ee5b1.png)

It appears in the Windows 10 version, but not in the Linux openSUSE Leap 15.3 version. See images below.

Windows 10:
![image](https://user-images.githubusercontent.com/66422959/144586150-75ee1b12-81a2-4abb-9e07-acc39723e90b.png)

Linux WebUI:
![web_no_ventoy](https://user-images.githubusercontent.com/66422959/144581684-74261fd4-93c1-499d-bc40-e1a67b2691d3.png)

Linux GTK/QT (VentoyGUI.x86_64):
![offline_no_ventoy](https://user-images.githubusercontent.com/66422959/144581693-e8274af8-2a37-4a03-94d0-02a7a0de347a.png)

**Comment by ventoy** [comment]
1. In my experience, most probably your USB stick is fake/fauty or at least contains some bad sectors.
You can use some tools to do a full test to see whether it has hardware problem.

2. VTSI file is an alternative install method on Windows. The vtsi file generated can only be used in Rufus, and Rufus can only be used in Windows. So there is no need for Linux Ventoy to include such option.

**Comment by ventoy** [comment]
There are two reasons why I said your USB may be fake/fauty.
1. From the log, the failure is due to data mismatch. That means, Ventoy write some data to the USB and read it back and compare  the data with what just write before, but the data doesn't match. This is abnormal.
2. Your USB only shows a name `USB FLASH DRIVE`. Normally it should shows the Vendor name for example Sandisk or Kingston..

**Comment by Melonadev** [comment]
The Windows 10 section in my post seems to be in the wrong order. I should also mention that when I later used a Windows 10 computer to format the USB into FAT32, then used the same computer to install Ventoy into that USB, it works! Probably a Linux issue or I screwed up, sorry!

**Comment by Melonadev** [comment]
I noticed that there's a folder called '[System Volume Information](https://www.howtogeek.com/282214/what-is-the-system-volume-information-folder-and-can-i-delete-it/)' in USB drives, including this one, after I format them in a Windows 10 computer. I think I deleted that folder manually (mistakenly thinking that it's useless) from the USB device, and that's probably the cause of this issue.
