### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by thewh1teagle** [ventoy/Ventoy#1298]
### Official FAQ

- [x] I have checked the official FAQ.

### Ventoy Version

1.0.62

### What about latest release

No. I didn't try the latest release.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

32

### What happened?

I would like to add support to ventoy to connect the internet over WiFi / etherent, 
Then download ISO from archive of isos and boot it. 
same as normal use of ventory but instead of has bunch of ISOs in the drive, get them from the internet

**Comment by ventoy** [comment]
Ventoy must work with drive. That's how it designed.
