### ISSUE TITLE
[issue]: 添加菜单提示居中功能

### ISSUE THREAD

**Issue by NewbieXvwu** [ventoy/Ventoy#1299]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.62

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

16GB

### Disk Manufacturer

“世纪飞扬”（似乎是个杂牌？很老的一个U盘）

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://www.ventoy.net/

### What happened?

想让Ventoy添加一个功能，谢谢！
描述：Ventoy的菜单提示插件在每一个提示长度不同的条件下，显得非常不美观，能否让菜单提示居中显示？

**Comment by ventoy** [comment]
当前只能在指定的位置开始从左到右显示。
要做到完美的自适应居中实现起来比较麻烦而且并不是功能性问题，不打算实现。
