### ISSUE TITLE
Filesystem Suggestion ( Solved on version 1.0.10)

### ISSUE THREAD

**Issue by chromer030** [ventoy/Ventoy#13]
Hi, the theory of using exfat as default format for second partition is great , but almost 80 percents of linux distros doesn't support it well, and even with manually mounting as fuse there are some problems like some distros doesn't have exfat filesystem package , fuse2 and fuse3 are not installed , included kernel are old , etc.
Most users use Ventoy for booting Live distros and mounting exfat or finding and installing package to add support exfat everytime on boot is really a pain.
According to Phoronix :

> The New Microsoft exFAT File-System Driver Has Landed In Linux 5.7.

 but this kernel version take a long time to be adapted for most distros and some distros may never use this kernel.

my suggestion :
If it is possible implement a option on Ventoy Installer , so user can select NTFS or EXFAT for second partition format.

NTFS is almost supported on every linux distro from oldest to newest even Apple macOS ( my daily driver OS) has NTFS support , ( default as read-only but you can mount it as RW or use softwares).
Thank you.

**Comment by ventoy** [comment]
I guess you mean the 1st partition.  Ventoy make the USB 2 partitions, first is exFAT, second is FAT32.
As I known, NTFS is not native supported by the linux kernel, all the distros mount ntfs with fuse.
If you can mount NTFS, that means your kernel has the fuse module,  as for the mount.exfat tool in userspace， there is a mount.exfat tool in the second partition and the Ventoy's install package. You can use it.

**Comment by chromer030** [comment]
Oh , i didn't know about presence of mount.exfat tool on second partition , Thank you very much.

**Comment by rampageX** [comment]
[FAT32 vs. exFAT vs. NTFS USB3 Performance Comparison](https://www.flexense.com/fat32_exfat_ntfs_usb3_performance_comparison.html)

> Conclusions:
> FAT32 File System - if the user needs to work with a relatively small number of medium-sized or large files, the FAT32 file system is good enough to be used with modern USB3 flash disks.
> exFAT File System - if the user needs to work with thousands of files stored on a USB3 disk and perform different types of operations, it is recommended to reformat the USB flash disk using the exFAT file system.
> NTFS File System - if the user needs to work with tens of thousands of files stored on a USB3 flash disk and perform many different types of operations, it is highly recommended to reformat the USB flash disk using the NTFS file system.

**Comment by soares23** [comment]
> I guess you mean the 1st partition. Ventoy make the USB 2 partitions, first is exFAT, second is FAT32.
> As I known, NTFS is not native supported by the linux kernel, all the distros mount ntfs with fuse.
> If you can mount NTFS, that means your kernel has the fuse module, as for the mount.exfat tool in userspace， there is a mount.exfat tool in the second partition and the Ventoy's install package. You can use it.

HI @ventoy i have found that tool on hithub "https://github.com/Sporesirius/YAMS". This Developer make a **FAT32** and **NTFS** partition an **Windows** and **Linux** ISO are compatible maybe you can analayse and make **NTFS** support for the future.

**Comment by ventoy** [comment]
Hi, 
NTFS/UDF/XFS/Ext2/3/4 are supported since Ventoy-1.0.10

**Comment by HemanthJabalpuri** [comment]
Like v1.0.28 has -L option to specify label for 1st partition, an option for type of formatting of 1st partition like ntfs/ext4/fat32/exfat will be more useful.
Eg:- `Ventoy2Disk.sh -i -L MyUSB -P fat32 /dev/sdb`
