### ISSUE TITLE
[issue]: 编译Ventoy2Disk失败

### ISSUE THREAD

**Issue by NewbieXvwu** [ventoy/Ventoy#1302]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.62

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

16GB

### Disk Manufacturer

和U盘无关

### Image file checksum (if applicable)

Yes.

### What happened?

我想自己试着编译一下Ventoy2Disk，但是它显示了错误：
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1104	无法打开文件“C:\Users\Administrator\Desktop\Ventoy-master\Ventoy2Disk\Ventoy2Disk\\Res\Ventoy2Disk64.manifest”	Ventoy2Disk	C:\Users\Administrator\Desktop\Ventoy-master\Ventoy2Disk\Ventoy2Disk\LINK	1	
我使用的是VS 2022，文件没有被占用。

**Comment by ventoy** [comment]
遗漏了几个 manifest 文件。 已经加上了，你更新一下就可以了。
