### ISSUE TITLE
Ventoy安装好了以后，可以增大VTOYEFI分区吗？

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#1303]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.62

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

128GB

### Image file download link (if applicable)

github

### What happened?

Ventoy安装好了以后，可以增大VTOYEFI分区吗？
我的U盘正好剩余 24 MiB。可以用 diskgenius 合并至VTOYEFI吗？就是让 32 MiB 的VTOYEFI变成 56 MiB。
如果不能，那末端多余的 24 MiB 可以如何利用呢？有良好的利用方案吗？难不成设置 FAT16 分区储存迷你小文件吗？

**Comment by a1ive** [comment]
https://www.ventoy.net/cn/faq.html

> Ventoy 安装以后如何调整分区？
Ventoy 安装完以后，最开始的2个分区（即存放ISO文件的分区和32MB的VTOYEFI分区）是不能动的，**包括它们的位置和大小都不能变**，变了以后 Ventoy 就无法启动了。
你可以在安装 Ventoy 的时候预留一部分合适的空间，这部分空间位于U盘后部，在安装完 Ventoy 以后，这部分保留空间是可以随便改的，Ventoy 不关心这部分空间。
因此，正常情况下，建议在安装 Ventoy 的时候就合理规划好分区布局，以避免后续的调整。

**Comment by ventoy** [comment]
```
如果真要是出现了需要调整的情况怎么办呢？ 这在以前是没办法的。不过最新版本的 Ventoy 支持无损安装，这里有一个变通的方法。
即先用分区工具把 32MB 的 VTOYEFI 分区删除。 此时就可以看成是一个普通U盘了，然后再调整分区。调整完成以后，再进行 Ventoy 的无损安装即可。
```
