### ISSUE TITLE
[Question]: Can you load OSX installer into Ventoy?

### ISSUE THREAD

**Issue by dm17** [ventoy/Ventoy#1308]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.62

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

32

### What happened?

OSX seems to require formatting the USB drive to HFS+... Is there a way to have Ventoy serve the ```InstallAssistant.pkg``` like it does other ISOs? Or is OSX meant to have dedicated flash drives to be booted/installed? I'm talking about downloading OSX using gibMacOS.

Ventoy is great - thanks!

**Comment by ventoy** [comment]
NO.
OSX is not supported.
