### ISSUE TITLE
Please add build instruction

### ISSUE THREAD

**Issue by springzfx** [ventoy/Ventoy#131]
It's very important for others to build from source.

**Comment by JohnVillalovos** [comment]
There are a few other issues that mention this: #39 and #51

**Comment by ventoy** [comment]
Hi,
I am finishing build scripts and documents, it will take about two or three days (as I can only deal it in my spare time). After that I will commit the scripts and docs.

**Comment by ventoy** [comment]
Hi,
I have committed the build scripts and documents and updated README.md.
You can refer DOC/BuildVentoyFromSource.txt.

**Comment by ventoy** [comment]
Hi, I will close the issue now.  If you have any problem during build ventoy, you can make a new issue.
