### ISSUE TITLE
[issue]: 选完ISO后就黑屏

### ISSUE THREAD

**Issue by aflyhorse** [ventoy/Ventoy#1314]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.62

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

64GB

### Disk Manufacturer

Kingston

### Image file checksum (if applicable)

Yes.

### What happened?

在UEFI下选完ISO文件就黑屏。Win10 / Fedora / RHEL 镜像都不行。
测试了手头另一台机器，Win10和Fedora镜像能成功启动到安装界面。
不能启动的机器是Thinkpad T450，另一台能启动的是Thinkpad E440

（选Legacy模式能启动，但是会花屏）

下附vtdebug信息
![image](https://user-images.githubusercontent.com/1755431/144984983-ddd2885c-9bd8-4551-9c16-1217c7c68957.png)
![image](https://user-images.githubusercontent.com/1755431/144985002-4100c827-4e09-42a7-858f-ad2bcdacc034.png)
![image](https://user-images.githubusercontent.com/1755431/144985020-179b9fe6-8bea-437c-87d0-9d54eebb2198.png)
![image](https://user-images.githubusercontent.com/1755431/144985041-a6fa9b55-5d7c-45c1-8e88-f5fa717bfb6a.png)
![image](https://user-images.githubusercontent.com/1755431/144985058-4672bdbe-e224-44bd-a53a-d435276758cf.png)

**Comment by ventoy** [comment]
应该是UEFI Firmware的兼容性问题。
对于Windows，使用WIMBOOT模式 https://www.ventoy.net/cn/doc_wimboot.html
对于Linux，使用GRUB2模式  https://www.ventoy.net/cn/doc_grub2boot.html

**Comment by aflyhorse** [comment]
好，这周末时间试一下grub2模式
建议搞个提示？这些靠快捷键开启的模式都挺隐晦的

**Comment by aflyhorse** [comment]
grub2模式可用（之前忘记反馈了
关问题单了，谢谢作者辛苦回答。

**Comment by kokutoukiritsugu** [comment]
也是t450 升级BIOS到了1.37 还是不能启动winPE
https://download.lenovo.com/pccbbs/mobiles/jbuj73ww.txt
直接回车或者memdisk或者wimboot模式都不行

![Image](https://github.com/user-attachments/assets/cace63cf-1598-4da6-bf7a-33f6940d632e)
![Image](https://github.com/user-attachments/assets/7f69de47-f238-4176-8009-3ca5e9ce50e4)
![Image](https://github.com/user-attachments/assets/51e880be-ab26-414a-842c-bf6484257209)
