### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by livioavalle** [ventoy/Ventoy#1316]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.62

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

gparted-live-1.2.0-1-amd64.iso

### Image file checksum type

SHA1

### Image file checksum value

0b5bc64c8c62affabad93a142b5ece92d5a33e11

### Image file download link (if applicable)

https://sourceforge.net/projects/gparted/files/gparted-live-stable/1.2.0-1/gparted-live-1.2.0-1-amd64.iso/download

### Test envrionment

Custom Build Desktop

### More Details?

This image file booted successfully in Ventoy.
## Build Specs:
CPU: Intel Core i5-4690
MoBo: MSI H97 GAMING 3 (MS-7918)
SSD: Samsung SSD 850 EVO 250GB
GPU: nVidia MSI GTX 960 Gaming
RAM: 4*4GB HyperX FURY DDR3
Sound Card: Sound Blaster Z

**Comment by ventoy** [comment]
Thanks.
