### ISSUE TITLE
[issue]: The resolution is not right! (2)

### ISSUE THREAD

**Issue by BajajAditya123** [ventoy/Ventoy#1318]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.62

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

16GB

### Image file checksum (if applicable)

Yes.

### What happened?

#1313 same issue but not responded

**Comment by BajajAditya123** [comment]
@ventoy

**Comment by ventoy** [comment]
Is it ok if you use Rufus to burn the ISO to the same USB drive and boot in the same computer?

**Comment by BajajAditya123** [comment]
And Grub2Win when I boot into windows same streched screen

**Comment by BajajAditya123** [comment]
@ventoy
