### ISSUE TITLE
[Success Image Report]: Windows 10 IoT Enterprise LTSC 2021 x86-64

### ISSUE THREAD

**Issue by Silexium** [ventoy/Ventoy#1322]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.62

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

en-us_windows_10_iot_enterprise_ltsc_2021_x64_dvd_257ad90f.iso

### Image file checksum type

SHA256

### Image file checksum value

a0334f31ea7a3e6932b9ad7206608248f0bd40698bfb8fc65f14fc5e4976c160

### Image file download link (if applicable)

https://dweb.link/ipfs/bafybeicfku5j343hn3h6qj3l4fjqj5xu5542xhhhcnt6ivhduxp4ldu7re?filename=en-us_windows_10_iot_enterprise_ltsc_2021_x64_dvd_257ad90f.iso

### Test envrionment

ASUS B85M-E

### More Details?

Windows 10 IoT Enterprise LTSC 2021 successfully booted on my machine (Ventoy 1.0.62, UEFI, GPT).

Specs:

Motherboard: ASUS B85M-E
CPU: Intel Xeon E3-1231 v3
GPU: GTX 1060 3GB
RAM: 4GB DDR3 1600 MHz

**Comment by ventoy** [comment]
Thanks!
