### ISSUE TITLE
[issue]: How can i enable both partition list on main page.

### ISSUE THREAD

**Issue by Se7Touch** [ventoy/Ventoy#1324]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.62

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

256

### Disk Manufacturer

Sandisk

### Image file checksum (if applicable)

No.

### What happened?

Hello, I have put some of my iso files that I do not want to appear by expanding the efi partition. but ventoy only lists ntfs partition. Is there a way to list both at the same time?

**Comment by ventoy** [comment]
Not supported.
Ventoy only list ISO files in the 1st partition.
