### ISSUE TITLE
[issue]: After updating/reinstalling Ventoy on my usb, it stopped being visible in windows

### ISSUE THREAD

**Issue by JosefLitos** [ventoy/Ventoy#1329]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.62

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

64GB (57GB)

### Disk Manufacturer

Kingston, tried Verbatim, no difference

### What happened?

The partition where I should be able to put images onto is not openable in Windows. I see it in disk manager though.

**Comment by NewbieXvwu** [comment]
Try to use the disk manager to assign a drive letter to your disk.

**Comment by JosefLitos** [comment]
Yep, that worked in deed. But will that fix the drive itself, meaning it will become visible on any other system too?
