### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by salfter** [ventoy/Ventoy#1336]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.63

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

lubuntu-21.10-desktop-amd64.iso

### Image file checksum type

SHA1

### Image file checksum value

c3a93d7d0fcbd7dea4da58861b17244db1aaa373

### Image file download link (if applicable)

https://cdimage.ubuntu.com/lubuntu/releases/21.10/release/lubuntu-21.10-desktop-amd64.iso

### Test envrionment

Framework Laptop DIY Edition

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
