### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by salfter** [ventoy/Ventoy#1337]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.63

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

clonezilla-live-20211116-impish-amd64.iso

### Image file checksum type

SHA1

### Image file checksum value

0d282d0009175e2f518368587e309014d6751314

### Image file download link (if applicable)

https://phoenixnap.dl.sourceforge.net/project/clonezilla/clonezilla_live_alternative/20211116-impish/clonezilla-live-20211116-impish-amd64.iso

### Test envrionment

Dell Latitude 5520

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
