### ISSUE TITLE
add option to continue booting from HDD

### ISSUE THREAD

**Issue by xbipin** [ventoy/Ventoy#134]
there seems to be no option to continue booting from HDD

**Comment by chromer030** [comment]
It simply can be done by defining in a FN key.

**Comment by xbipin** [comment]
how to do that?

**Comment by xbipin** [comment]
in easy2boot usually there is an entry in menu to continue to boot to HDD which ventoy doesnt

**Comment by chromer030** [comment]
it hasn't defined yet...

**Comment by ventoy** [comment]
Please make a try with F4 localboot menu in Ventoy-1.0.13
