### ISSUE TITLE
[issue]: 能不能用ventoy启动grub2或grub4dos或者添加命令行模式

### ISSUE THREAD

**Issue by Alex6357** [ventoy/Ventoy#1340]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.63

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64G

### What happened?

启动grub4dos的BOOTX64.EFI卡死，启动BOOTIA32.EFI提示需要没有内核，启动打包出来的镜像提示无法启动

**Comment by ventoy** [comment]
就是标准的grub2, 按 `c` 键就进入命令行模式。

BOOTIA32.EFI需要在32位EFI的环境下才能执行。
另外，有些EFI文件执行时需要放在FAT分区中，你可以把镜像分区重新格式化为FAT32文件系统之后，然后把EFI文件设置为 EFI\BOOT\BOOTX64.EFI 然后启动试试。

**Comment by Alex6357** [comment]
我一直在按ctrl+c[捂脸]感谢
