### ISSUE TITLE
[issue]: 1.0.63 Manjaro ISO UEFI 引导黑屏(附视频)

### ISSUE THREAD

**Issue by abcfy2** [ventoy/Ventoy#1343]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.63

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

16GB

### Disk Manufacturer

Kingston

### Image file checksum (if applicable)

- https://download.manjaro.org/kde/21.2.0/manjaro-kde-21.2.0-minimal-211220-linux515.iso

### What happened?

开机启动选择UEFI引导后，Manjaro会直接黑屏（记得以前老版本是好的），但是MBR模式引导是好的，附视频：

Manjaro失败，直接黑屏:

https://user-images.githubusercontent.com/5327677/147630150-4370ff52-bf5b-485e-ae08-957b12cd3964.mp4

请问这是什么问题？谢谢了。

**Comment by ventoy** [comment]
1. 先参考 https://www.ventoy.net/cn/doc_checksum.html 对ISO文件进行校验，确认ISO文件没有损坏
2. 是否只有这个Manjaro的ISO有问题，其他Linux ISO有没有问题？
3. 在UEFI模式下，使用grub2模式启动试试是否OK https://www.ventoy.net/cn/doc_grub2boot.html

**Comment by abcfy2** [comment]
> 1. 先参考 https://www.ventoy.net/cn/doc_checksum.html 对ISO文件进行校验，确认ISO文件没有损坏
> 2. 是否只有这个Manjaro的ISO有问题，其他Linux ISO有没有问题？
> 3. 在UEFI模式下，使用grub2模式启动试试是否OK https://www.ventoy.net/cn/doc_grub2boot.html

ISO文件已经校验过，没有问题。我在我的台式机上测试了下，BIOS+MBR模式可以引导，但是UEFI不行。换到我的笔记本上测试，UEFI又是好的，之前用某个老版本的时候好像都是好的，后来升级了Ventoy，以及更换了新的Manjaro ISO就有这个问题了。

其他ISO我的视频截图有，还有个Ubuntu，那个就是好的，似乎就这个Manjaro有问题，最后的windows ltsc都是OK的。

grub2模式还没试过，等下试试

**Comment by abcfy2** [comment]
神了个奇，莫名其妙自己解决了，猜测不知道是不是以前系统的grub影响的。

我先在开机的boot menu选择了使用BIOS+MBR模式引导了U盘，这样可以进入manjaro iso，修复以前的系统，chroot硬盘的系统之后重新`pacman -S grub`，之后重启，居然莫名其妙的好了，无论UEFI还是bios模式都正常了。
