### ISSUE TITLE
[issue]: NO ISO files found

### ISSUE THREAD

**Issue by gilbertoca** [ventoy/Ventoy#1344]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.062 and 1.0.63

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

8GB

### Disk Manufacturer

SanDisk and Sony

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://sourceforge.net/projects/mx-linux/files/Final/KDE/MX-21_KDE_x64.iso/download

### What happened?

The menu appears empty with the error "NO ISO files found" even though the iso image is in.
I've discovered the solution after watching this video https://www.youtube.com/watch?v=Pze7KfXRJKA.
After that I changed the iso file name, _replacing_ **_** by **-** and the iso now appears on menu.

Regard,

Gilberto

**Comment by ventoy** [comment]
In very old version (before 1.0.30), Ventoy doesn't support ISO files whoes file name contain space and unicode characters.
So the iso file will not appear in the menu if the file name contains space or unicode characters.
But with latest version, there is no such problem.

So I don't known why it don't appear in the menu before you change the file name.

**Comment by ventoy** [comment]
When the menu appears empty with the error "NO ISO files found".
Press `c` to enter grub shell and run the following commands and give me the result.
```
ls $vtoy_iso_part/
ls -l  $vtoy_iso_part/
```

**Comment by gilbertoca** [comment]
I'm sorry! I think the issue is with the USB stick(Sony).
Booting with no ISO and with two linux ISOs:
![image](https://user-images.githubusercontent.com/3083703/147662018-24f6b035-4a8d-4cf2-920c-aba7a7c08abb.png)


Using the SanDisk I do not see the issue:
![image](https://user-images.githubusercontent.com/3083703/147663681-4a5b0a1a-630e-4984-a2db-6a7b4f76e1f9.png)

Again, sorry to bother you!

**Comment by Vanscot** [comment]
I am having the same bug with versions .61 and .63, should I open a new ticket or hijack this one with the appropiate info?
