### ISSUE TITLE
[Success Image Report]: manjaro-gnome-21.2.0-211220-linux515.iso

### ISSUE THREAD

**Issue by Itotutona** [ventoy/Ventoy#1345]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.63

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

manjaro-gnome-21.2.0-211220-linux515.iso

### Image file checksum type

SHA1

### Image file checksum value

cb837ded77f092020d0d0eee9a438a15f91d0376

### Image file download link (if applicable)

https://manjaro.org/downloads/official/gnome/

### Test envrionment

ASUSTeK COMPUTER INC. UX430UAR

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
