### ISSUE TITLE
[Success Image Report]: Dell Platform Specific Bootable

### ISSUE THREAD

**Issue by TheOddball** [ventoy/Ventoy#1346]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.61

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

PER730XD_BOOTABLE_21.12.00.24.iso

### Image file checksum type

MD5

### Image file checksum value

 e79f2a52e3d2f3fb0cbe9b6fc3f4bf4f

### Image file download link (if applicable)

https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=8jtw5&oscode=w12r2&productcode=poweredge-r730xd

### Test envrionment

Dell R730xd

### More Details?

This image file booted successfully and updated the server successfully with Ventoy.

**Comment by ventoy** [comment]
Thanks!
