### ISSUE TITLE
[issue]: Macmini4,1 cannot boot operating system

### ISSUE THREAD

**Issue by probonopd** [ventoy/Ventoy#1348]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.62

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

111GB

### Disk Manufacturer

Multiple

### What happened?

Mac mini (Mid 2010) (`Macmini4,1` with  firmware `MM41.88Z.0047.B00.1802021546 02/02/18`) booting with Ventoy (ISOs on ExFAT partition) shows the GRUB screen and one can select an ISO, but after pressing Enter the screen only shows the `_` character and the system appears to be stalled.

**Comment by AnomSanjaya** [comment]
Ventoy doesn't support all Mac devices since @ventoy doesn't have one of Mac device for testing,

**Comment by ventoy** [comment]
Ventoy doesn't officially support mac.
