### ISSUE TITLE
[issue]: PrimeOS 2.0.1 Beta is Stuck at Detecting PrimeOS

### ISSUE THREAD

**Issue by kilickerem066** [ventoy/Ventoy#1350]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.63

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

No.

### Image file download link (if applicable)

https://sourceforge.net/projects/primeos/files/64-bit/PrimeOS-2.0.1-64-bit-20220102-BETA.iso/download

### What happened?

When I try to choose PrimeOS - Installation on the PrimeOS Bootloader (GRUB), I get stuck at Detecting PrimeOS. When I try the live install (PrimeOS - Live on the PrimeOS Bootloader aka. GRUB), it says /dev/null cannot be found and reboots the system. I cannot check using MD5 checksum because they didn't provided it. By the way, this is new PrimeOS 2.0.1 with Android 11, not old one with Android 7.

**Comment by Bowser04** [comment]
Me to

**Comment by Bowser04** [comment]
Just dont use ventoy

**Comment by kilickerem066** [comment]
but i need to use it

**Comment by Bowser04** [comment]
> but i need to use it

Why

**Comment by Bowser04** [comment]
> but i need to use it

Why ?

**Comment by ventoy** [comment]
@kilickerem066 
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/1941235100
https://www.ventoy.net/en/doc_github_ci.html

**Comment by daisy-fhb** [comment]
> 

dont work

**Comment by daisy-fhb** [comment]
> @kilickerem066 Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/1941235100 https://www.ventoy.net/en/doc_github_ci.html

dont work 4 me

**Comment by ventoy** [comment]
What about the latest Ventoy release?

**Comment by fluffyloopy** [comment]
works with the latest ventoy release

**Comment by Programmer2910** [comment]
Same
