### ISSUE TITLE
[Feature Request]: Ubuntu 20+ Auto Installation Plugin

### ISSUE THREAD

**Issue by ServerMonkey** [ventoy/Ventoy#1351]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.63

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

64GB

### What happened?

It would be awesome to have better support for Ubuntu 20.x and 21.x auto-installations.
Newer Ubuntu releases use cloud-init instead of preseeds (d-i).
Documentation:
https://ubuntu.com/server/docs/install/autoinstall
https://ubuntu.com/server/docs/install/autoinstall-quickstart
https://cloudinit.readthedocs.io/en/latest/topics/datasources/nocloud.html
Relevant discussion: https://askubuntu.com/questions/1233454/how-to-preseed-ubuntu-20-04-desktop

cloud-init requires two files, "user-data" and "meta-data" to be present.
As I understand it this is not supported by default in Ventoy. Though there is a (more elaborate) solution in the forum: https://forums.ventoy.net/showthread.php?tid=1602
But could not get this to work with Ubuntu 21.10.
Also projects like these might be an alternative?: https://github.com/covertsh/ubuntu-preseed-iso-generator

An update to the Documentation for newer Ubuntu versions would be great too.
https://www.ventoy.net/en/plugin_autoinstall.html
Or at least add which Ubuntu versions are actually supported.
Right now it is kind of confusing for inexperienced Ubuntu users because when reading "Debian/Ubuntu Server", in the Plugin docs, you expect all Ubuntu versions to just work with preseed.cfg, which is not the case anymore.

**Comment by ventoy** [comment]
It seems that only Ubuntu Server support cloud-init not the desktop version, is it?

**Comment by ventoy** [comment]
@ServerMonkey   Ventoy 1.0.65 release with ubuntu server cloud-init support. You can make a try.

**Comment by drduker** [comment]
Is there a place to find the example config file for ubuntu 21.10?  I mean i have a config, just not sure how to get it working on the new version on ventoy.  I don't know what it is looking for, so an example would be good.  You have a list of all the OS's that work, but not example files that were used.

**Comment by ventoy** [comment]
> 

There is no special thing in new ventoy version. Just use an cloud-init script as a auto install template.
There is an example for ubuntu server 20.x+ (can be used with 21.10)
https://www.ventoy.net/en/plugin_autoinstall.html
![image](https://user-images.githubusercontent.com/59477474/153105499-c614c4f6-607c-4e8f-9283-a3ebb1101278.png)
