### ISSUE TITLE
[issue]: kaspersky rescue disk does not work in UEFI, bios OK

### ISSUE THREAD

**Issue by sherpya** [ventoy/Ventoy#1353]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.63

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

128

### Disk Manufacturer

SanDisk

### Image file download link (if applicable)

https://www.kaspersky.it/downloads/thank-you/free-rescue-disk

### What happened?

I'm using QEMU + OVMF to test images

after selecting what to boot, the (internal) grub says:
```
error: bad signature.

Press any key to continue...
```
after some second it just continue by itself, but Linux fails to identify the root block device
Spawning a shell I see `sda` and `sr0` in `/proc/partitions`

I cannot mount sr0 because it says no medium found

I'll try booting on bare metal

**Comment by sherpya** [comment]
even worse on bare metal, I cannot press a key and the boot hangs there

**Comment by sherpya** [comment]
this is my script to launch qemu
```sh
#!/bin/sh
CODE=/home/sherpya/ovmf-x64/OVMF_CODE.fd
VARS=/home/sherpya/ovmf-x64/OVMF_VARS.fd
exec sudo qemu-system-x86_64 \
    -display gtk,zoom-to-fit=on \
    -enable-kvm -machine type=q35,smm=on,accel=kvm \
    -smp sockets=1,cpus=4,cores=2 -cpu host \
    -global ICH9-LPC.disable_s3=1 \
    -global driver=cfi.pflash01,property=secure,value=on \
    -m 16384 \
    -serial stdio \
    -usb -device usb-tablet \
    -netdev user,id=hostnet0 -device virtio-net-pci,romfile=,netdev=hostnet0 \
    -drive if=pflash,format=raw,unit=0,readonly=yes,file=${CODE} \
    -drive if=pflash,format=raw,unit=1,file=${VARS} \
    -drive file="/dev/sda",if=ide,cache=none,index=0,format=raw,snapshot=on \
    $*
```

**Comment by sherpya** [comment]
![Screenshot_20220108_011002](https://user-images.githubusercontent.com/120074/148622597-64e27a24-c4c4-4cb7-9674-f90dd1f84bb2.png)

**Comment by ventoy** [comment]
![image](https://user-images.githubusercontent.com/59477474/148625718-b0c6e34d-2865-4b09-b1d4-56933b452933.png)

https://www.ventoy.net/en/isolist.html

**Comment by sherpya** [comment]
@ventoy it would be possible to inject a replacement `/boot/grub/grub.cfg` before starting grub?

**Comment by ventoy** [comment]
`grub.cfg` is also signed and will be checked when boot.

**Comment by sherpya** [comment]
I used to make a sort of ventoy but only using vanilla grub, many iso are just bootable by grub with some trick,  I was loading it directly, the only problem was the version I used insisted to have the iso in /data directory.
Anyway you may overwrite the efi shim with ventoy efi grub :D

**Comment by sherpya** [comment]
if there are not cleaner solution you can just close this issue
