### ISSUE TITLE
VentoyPlugson.sh | Values entered into the interface's option fields are invisible upon a condition

### ISSUE THREAD

**Issue by Ricky-Tigg** [ventoy/Ventoy#1362]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.63

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

4 GiB

### What happened?

VentoyPlugson.sh  | Values entered into the interface's option fields are **invisible**. Nevertheless those values are dully present in the file _ventoy.json_. Illustrations:

![ventoy_plugin_option_value](https://user-images.githubusercontent.com/26058215/148743135-5c776642-1c6e-45b4-ab61-412d42afe5ab.png)

```
$ cat ventoy.json 
{
    "persistence_uefi":[
        {
            "image": "/Fedora-Server-netinst-x86_64-35-1.2.iso",
            "backend":[
                "/ventoy/fedora_persistence.dat"
            ],
            "timeout": 0,
            "autosel": 1
        (...)
```

**Comment by ventoy** [comment]
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/1677029358
https://www.ventoy.net/en/doc_github_ci.html

**Comment by ventoy** [comment]
Please make a video about how to reproduce the issue.

**Comment by Ricky-Tigg** [comment]
A further investigation made the statement depicted as title partially true. Values may be fully visible upon that condition: the web browser's windows' size according to the **width axis** is big enough.

To reproduce | 
While a window is in full size, invoking the built-in enlargement function for values **superior to one hundred percents*** shall invariably decrease furthermore the area of exhibition of the fields until the values become invisible.

(*) For example on my laptop's 15.6' screen, the value from which the issue becomes observable starts at 110.

**Comment by Ricky-Tigg** [comment]
A further investigation made the statement depicted as title partially true. Values may be fully visible upon that condition: the web browser's windows' size according to the **width axis** is big enough.

To reproduce | While a window is in full size, invoking the built-in enlargement function for values **superior to one hundred percents*** shall invariably decrease furthermore the area of exhibition of the fields until the values become invisible.

(*) For example on my laptop's 15.6' screen, the value from which the issue becomes observable starts at 110.

**Comment by Ricky-Tigg** [comment]
A further investigation made the statement that was in the title, partially true.  Values in fields may be fully or partially visible or invisible.

**Cases to reproduce in web browser**r
- While a window is in _full screen_ mode, invoke the built-in enlargement function (<kbd>ctrl</kbd> + <kbd>+</kbd>) for values* **superior to one hundred percent**. (*) On my 15.6' screen and for the resolution applied, the value from which the issue becomes observable is 110.
- Or while a window is not in _full screen_ mode, shrink it manually according to the **width axis**.
