### ISSUE TITLE
[issue]: Chinese/English blending in VentoyPlugson 

### ISSUE THREAD

**Issue by ehawman-rosenberg** [ventoy/Ventoy#1363]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.64

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

32GB

### What happened?

Selecting the `Image List Plugin` menu in the Ventoy Plugson web client confuses the translation settings.
![image](https://user-images.githubusercontent.com/81652082/148792057-1728dfec-d01d-40dd-8a83-25b651da7c4b.png)

Reproduction:
1. Launch `VentoyPlugson.exe` (either English is default or it detected my locale)
2. Go through menus in order. English appears until reaching `Image List Plugin` (see screenshot above)
3. Return to `Device Information`, English. Go to `Global Control Plugin`, weird language blend.
![image](https://user-images.githubusercontent.com/81652082/148793022-7bba117e-1ade-4935-95dc-d91ddbd1485a.png)
4. At any point, toggling the translation button in the top right will reset the issue until you go to `Image List Plugin` again.

I think it might have something to do with [plugson_image_list.html Line 103](https://github.com/ventoy/Ventoy/blob/036b58ff0c95cc294ad1ec6e5b6a715b89b34e48/Plugson/www/plugson_image_list.html#L102)? Honestly I'm not sure what's going on here but the behavior is strange.

**Comment by MrTheoW** [comment]
I've seen this to.  When I choose the "Add" button of the Auto Install Plugin the buttons in the popup will be Non-English. If I then go back to "Global Control Plugin" most of the text will be Non-English too. A simple refresh (F5) will fix it but there is something wrong with the config.

**Comment by ventoy** [comment]
@ehawman-rosenberg @MrTheoW 
Please try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/1680373260
https://www.ventoy.net/en/doc_github_ci.html

**Comment by ehawman-rosenberg** [comment]
@ventoy Tested and it's no longer blending the two on the main pages. I'm still seeing CN characters on the "Add" prompts on some (but not all) pages. Specifically, the Ok/Cancel buttons.

Clicking "Add" on Menu Alias (CN)
![image](https://user-images.githubusercontent.com/81652082/149200745-d8a362c9-26ad-4b4a-bb83-13d337382f62.png)

Boot Conf Replace (EN)
![image](https://user-images.githubusercontent.com/81652082/149200855-0093fe8a-7bc5-46e0-b465-2f30333f2f85.png)

Auto Install (CN)
![image](https://user-images.githubusercontent.com/81652082/149200883-9bab3d0f-7283-4e79-be82-8328fbdb7def.png)

DUD (EN)
![image](https://user-images.githubusercontent.com/81652082/149201105-699b786f-6f9a-48f1-8247-012a8b8842da.png)

Just to give a sampling.

That said, the main blending issue is mostly eliminated! Nice work.

**Comment by ventoy** [comment]
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/1690841147

**Comment by ehawman-rosenberg** [comment]
@ventoy 

Perfection. Thanks again!
