### ISSUE TITLE
[issue]: The Partition Configuration is not applied on Update option

### ISSUE THREAD

**Issue by sraedler** [ventoy/Ventoy#1368]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

latest

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

256

### What happened?

1. Create a bootable Device
2. Change in Option -> Partition Configuration to Preserve some space at the end of the disk
3. Press the Update Button

You will see, the changed partition configuration is not applied. This only happens if a fresh installation is conducted.

**Comment by ventoy** [comment]
Yes. 
This is how it designed from the beginning.
These configurations alongside MBR/GPT partition style only take effect when install Ventoy, not Update.
