### ISSUE TITLE
ventoy-<version>-livecd.iso | In virtual machine,  system resources not displayed when invoking the search of system resources

### ISSUE THREAD

**Issue by Ricky-Tigg** [ventoy/Ventoy#1372]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.64

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

4 GiB

### What happened?

In Linux Ventoy disk image was emulated on **Qemu/KVM** ; via virt-manager 3.2.0|. VM created by selecting _Generic OS_. In Hardware details  _OS information_ is:

![virt-manager_3 2 0_ventoy- version -livecd iso_OS_information](https://user-images.githubusercontent.com/26058215/149124387-c5fcc612-f343-482e-acec-b219ea811400.png)

Once the system was booted, Ventoy interface appeared ,

![QEMU-KVM_ventoy- version](https://user-images.githubusercontent.com/26058215/149128607-fcc4da77-57d6-4324-8f8a-6da5accbd787.png)

- While _Show all devices_  was not selected , the device field was by default empty and no virtual drive could be listed by clicking the down-arrow.
- While that _Show all devices_  was selected , at last virtual drives could be listed by clicking that arrow.
- Invoking a search in system resources by clicking the right-sided icon according to that arrow was not operational, be _Show all devices_ selected or not.
- At last, once installed to a selected drive, there did not seem to me to exist a way among the available options to add an OS's ISO file into the device.

**Comment by ventoy** [comment]
By default(Show all devices not selected) it will only show devices in **USB** interface type.
If Show all devices was selected then all devices will be shown.
After install, `/dev/sda`  for example, will be reparted into 2 partitions.  `/dev/sda1`  `/dev/sda2`, you should mount /dev/sda1 and copy ISO file to it. Before that, you must make sure that your linux system can mount exfat filesystem becasue /dev/sda1 is in exfat filesystem.
