### ISSUE TITLE
[issue]: Can't boot .vtoy from other partition

### ISSUE THREAD

**Issue by fake-programmer** [ventoy/Ventoy#1377]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.64

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

220

### What happened?

![Snipaste_2022-01-13_14-57-03](https://user-images.githubusercontent.com/63443553/149286724-d7e84045-17b2-48e8-953e-114248522ef4.png)

如图所示无法启动其他磁盘分区下的 .vtoy 虚拟磁盘，如果拷贝到Ventoy的第一分区又是可以启动的。
无法启动时的截图如下(似乎是通过启动Windows的方式去启动Linux导致的)：
![IMG_20220113_132532-tuya](https://user-images.githubusercontent.com/63443553/149287308-ecc0b8eb-123d-43e8-847b-302ebd819a5e.jpg)

**Comment by ventoy** [comment]
没好好看文档。
一个是  `vhdboot_common_func `  一个是  `vtoyboot_common_func`  不一样的。

**Comment by fake-programmer** [comment]
非常感谢，已解决。
