### ISSUE TITLE
github.com | Issue Report page | Ventoy version exhibited in field as model does not refer to the latest

### ISSUE THREAD

**Issue by Ricky-Tigg** [ventoy/Ventoy#1382]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.64

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

4 GiB

### What happened?

In the ventoy repository of that platform, in the _Issue Report_ page, the Ventoy version exhibited in field as model does refer to the release previous to the latest instead of the latest, which is now _1.0.64_.

![github com_ventoy_issue_version_field](https://user-images.githubusercontent.com/26058215/149486557-18cac5a9-c857-4352-8a63-e3389892d698.png)

**Comment by ventoy** [comment]
updated
