### ISSUE TITLE
File ventoy_backup.json | Missing implementation of backup function in Plugin web interface

### ISSUE THREAD

**Issue by Ricky-Tigg** [ventoy/Ventoy#1383]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.64

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

4 GiB

### What happened?

As noticeable along with each execution of `sh VentoyPlugson.sh /dev/sd<letter>` new login details are saved locally on the system into the file _VentoyPlugson.log_. The files _ventoy.json_ and _ventoy_backup.json_ are **automatically** created inside _ventoy_ directory respectively as soon as a modification is made during the **first session** and **following session**.

It can reasonably be concluded of the presence of _ventoy_backup.json_, that an **implementation** of a correspondent function is expected to be present within the Plugin web interface. Nevertheless this is obviously not the case. Even the current document lacks a mention referring to the methodology covering the backup of modifications made during a previous session.

**Comment by ventoy** [comment]
I update the document in https://www.ventoy.net/en/plugin_plugson.html
