### ISSUE TITLE
[issue]: 

### ISSUE THREAD

**Issue by rediffusion** [ventoy/Ventoy#1385]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.64

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

250

### Disk Manufacturer

Seegate

### Image file checksum (if applicable)

No.

### What happened?

Selamla! 🤪
I'm interested in the .json file. Is the comment working?
How do I comment on some code in the file?
`"C:\Users\halva\Desktop\ventoy\plugin\ventoy\ventoy.json"`

Tesekkurler!

**Comment by ventoy** [comment]
Comment is not supported. 
I have noticed this here: https://www.ventoy.net/en/plugin_entry.html
_......
It should be noted that, the json parser in Ventoy is very simple, please don't define too complicated structure and comment is not supported._


You can use VentoyPlugson to generate ventoy.json automatically, so I think you don't need comment.
https://www.ventoy.net/en/plugin_plugson.html
