### ISSUE TITLE
[issue]: 无法安装centos7 mini版，问题初步判断是找不到虚拟光驱label。

### ISSUE THREAD

**Issue by wuchuwei** [ventoy/Ventoy#1388]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

 1.0.64

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

128G

### Image file checksum (if applicable)

Yes.

### What happened?

iso 我就试过dell服务器用idrac的虚拟光驱安装过的。用U盘的话，需要改grub的hd:label/xxxx才能安装。
现在是我需要怎么弄才能安装？

**Comment by ventoy** [comment]
具体是哪个ISO文件？ 具体错误截个图。 CentOS 7 找不到安装介质最终会进入 dracut 的shell模式。
如果进入shell之后在里面执行以下两个命令，拍照看下结果：
```
cat /ventoy/log
blkid
```

**Comment by wuchuwei** [comment]
![P20116-174625](https://user-images.githubusercontent.com/13662108/149655062-230d2f95-a29f-45a7-81b9-2406f737a3fd.jpg)
不能进入 dracut 的shell模式。

**Comment by wuchuwei** [comment]
镜像就：CentOS-7-x86_64-Minimal-1804.iso

**Comment by ventoy** [comment]
1. 在Ventoy界面，选中ISO文件之后，按 `m` 键校验一下，确保文件没有损坏
2. 使用同一个Rufus把相同的ISO烧录到同一个U盘内，可以正常安装吗？

**Comment by wuchuwei** [comment]
找到问题了。是笔记本cpu太新了无法安装
