### ISSUE TITLE
More flexible partitioning schemes

### ISSUE THREAD

**Issue by Tank-Missile** [ventoy/Ventoy#139]
Being frusterated with previous multiboot USB solutions, I was very excited when I discovered Ventoy. However, I quickly realized that it had the same limitation every other multiboot solution had: it reformats the USB. I'm very picky about how my drives are formatted, USB or not. Currently, my USB is formatted manually as follows:

First Partition: Label = USB Storage. FsType = NTFS. Size = 30G.

Second Partition: Label = USB EFI. FsType = fat32. Size = 100M. Bootloader = rEFInd.

Third Partition: Label = Windows 10 Installer. FsType = NTFS. Size = 5G

Fourth Partition: Label = Linux Installers. FsType = Btrfs. Size = rest of USB.

The first partition I simply use for storage. This is the smallest problem with Ventoy as I could just use the ISO partition for storage, although I rather use the filesystem I want for it.

The second partition uses the rEFInd bootloader to boot the Windows 10 installer in the third partition, and any number of subvolumes in the fourth partition.

The third partition stores the Windows 10 installation files. Unfortunately, because rEFInd has no ISO boot support, I had to store them on an NTFS partition in order for the bootloader to see the boot files. I could have stored them on the first partition, but as I said, I'm very picky.

The fourth partition solves several different problems I was having, the biggest one being multiple distributions that could be manipulated through reboots. Btrfs has a nifty little feature called subvolumes, which can be booted from using the subvolume's name. For instance, you can add to the kernel command line rootflags=subvol=@arch or rootflags=subvol=@debian. I could just create a partition for each distro installer I want, but I don't want to figure out how much space each distro installer needs in order to avoid wasting space.

Now, this brings us to a very important question: if my setup works fine, why do I need Ventoy? Well, I'm not interested in manipulating every distro installer I plop into my USB. I want it mixed, where I can boot ISOs in the way Ventoy advertises, and boot manipulatable installers on a USB partition as well. While my usecase is incredibly specific, others may also want a different partitioning scheme than the one Ventoy uses. Perhaps there's a manual way to install Ventoy that doesn't require reformatting the entire USB?

**Comment by ventoy** [comment]
Hi,

Because Ventoy is designed  as a whole solution from the beginning. So it will part the usb in its way.
I think it's very difficult for any solution to match all the situations.
Ventoy also has its limitations.

**Comment by Tank-Missile** [comment]
I understand matching all situations is impossible, but I'm talking about partitioning here. Is it maybe possible for Ventoy to ask which partitions to use? For instance, use sda3 for ISOs and sda1 for the bootloader? I'm also curious how configurable the bootloader itself is. If I read the documentation right, it mainly uses GRUB2. I tried using GRUB2 before to boot ISOs, but GRUB2 canfiguration can be quite finicky.

**Comment by ventoy** [comment]
Ventoy 2.X series may match your requiments. 
In 2.X, ventoy only responsible for booting the iso files and the iso files can be in any disk, any partition. 
In 2.X, ventoy can be put anywhre as long as it can be booted by BIOS.

**Comment by Tank-Missile** [comment]
That does sound promising! If I could also specify a start folder, I could simply use one partition for both storage and ISOs. Though by looking at the releases page, it seems a 2.X release is far off?

**Comment by ventoy** [comment]
Yes, Ventoy 1.X has just been released less than two months. There are many features to be finished.
So the 2.X version indeed need more time.
