### ISSUE TITLE
Multiple-byte units expressed in SI when meant to be expressed in IEC

### ISSUE THREAD

**Issue by Ricky-Tigg** [ventoy/Ventoy#1391]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.64

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

4 GiB

### What happened?

_Tested with disk capacities (in GiB)_: 4, 8 and 16.

**Multiple-byte units** exhibited in _Document_, _README_ of Lunux version release and command line outputs are either globally or partially found invalidly expressed, for instance according to the SI standard (**power of 10^3**),  when meant to be expressed according to the IEC standard (**power of 2^10**).

Illustrations of outputs with incorrect expressions of digital storage units – missing the _i_ that characterizes the IEC standard.
- In command line:
```
# ./Ventoy2Disk.sh -I -s -r 256 -L 'monikäy' /dev/sdc
(...)
Model: (...) (scsi)
Size : 3 GB
Style: MBR

You will reserve 256 MB disk space
```
```
# sh ExtendPersistentImg.sh persistence.dat 16 | head -2
Extend dat file... (current is 16MB, append 16MB, total 32MB)
Extend xfs filesystem by xfs_growfs ...
```
- In _README_:
"_-r SIZE_MB_", , "_sh CreatePersistentImg.sh  [ -s SIZE_IN_MB ]_", all "_persistence.dat in <value>GB_" and "_sh ExtendPersistentImg.sh persistence.dat 2048  ---->  Extend persistence.dat by 2048MB
(... )persistence.dat file will grow to 3GB size (assume that it is 1GB_".

_For comparison_ | Illustrations of outputs with correct expressions of digital storage units:
```
# sh CreatePersistentImg.sh -s 16 -t xfs -l pysyvä
(...)
16777216 bytes (17 MB, 16 MiB) copied, 0,0763629 s, 220 MB/s
```
**_Note_**: _SIZE_ refers here to power of 2^10*
```
$ lsblk -o name,size /dev/sdc
NAME    SIZE
sdc     3,6G
├─sdc1  3,3G
└─sdc2   32M
$ lsblk --paths -bo name,fstype,fsver,size,mountpoints,tran /dev/sdc
NAME        FSTYPE FSVER       SIZE MOUNTPOINTS            TRAN
/dev/sdc                 3874797568                        usb
├─/dev/sdc1 exfat  1.0   3571757056 /run/media/yk/monikäy 
└─/dev/sdc2 vfat   FAT16   33554432
```

**Comment by ventoy** [comment]
Only when show the disk capacity, Ventoy use 1000 for KB, just for easy identification.
For a 64GB USB, it's actually just 59GiB.

All the other input parameters use 1024 for KB.
