### ISSUE TITLE
Missing options in graphical interfaces for Linux

### ISSUE THREAD

**Issue by Ricky-Tigg** [ventoy/Ventoy#1392]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.64

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

16 GiB

### What happened?

_Tested in Gnome on Wayland -- served by Mutter_

Options _Generate VTSI file_ and _Non-destructive install_  ,which are exhibited in [Document](https://www.ventoy.net/en/doc_non_destructive.html) covering an aspect for Windows, are not exhibited in the graphical interfaces for Linux; they may be missing.

To reproduce: either `./VentoyGUI.x86_64` or `./VentoyWeb.sh`.
```
# ./VentoyGUI.x86_64
(Ventoy2Disk.gtk3:51042): Gtk-CRITICAL **: 14:36:08.953: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed
```
![ventoy_v 1 0 64_VentoyGUI x86_64_interface_options](https://user-images.githubusercontent.com/26058215/149940950-56f0aef5-c385-4e2c-bd23-21e949b0e766.png)

_Note_: While the interfaces are not in default language, regardless the supported language, all strings are translated at the exception of _Language_. That is a **separate issue** assuming the relevant string has already be served as source for translations.

**Comment by ventoy** [comment]
1. VTSI is only for Windows user, so there is no need for linux version.
2. Non-destructive install only supported in Ventoy2Disk.sh, not supported in GUI version
3. All the language translation is in https://github.com/ventoy/Ventoy/blob/master/LANGUAGES/languages.json
   When I add new menu I will add all the english translation for all languages, wait for someone to give the native translation.

**Comment by Ricky-Tigg** [comment]
2. Good to know. 3. As I suspected, unlike _"STR_MENU_OPTION":"Option"_ the pendant for _Language_ is missing.
