### ISSUE TITLE
Partition table removed from the volume being formatted

### ISSUE THREAD

**Issue by Ricky-Tigg** [ventoy/Ventoy#1394]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.64

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

4 GiB

### What happened?

The **partition table** is accidentally removed from the  volume being formatted, which results from the invocation of _Clear Ventoy_ option. Leaving at most the volume **unallocated** should be the only purpose of that operation

_Note_:  option only supported graphically.

To reproduce in Linux: either `./VentoyGUI.x86_64` or `./VentoyWeb.sh`

_Result_:
```
# parted /dev/sdb print
Error: /dev/sdb: unrecognised disk label
Model: Kingston DataTraveler 102 (scsi)                                   
Disk /dev/sdb: 3875MB
Sector size (logical/physical): 512B/512B
Partition Table: unknown
Disk Flags:
```

**Comment by ventoy** [comment]
That's how this option designed from the beginning.
It just clean the disk and don't create any partition on it. You can use parted/fdisk/gparted to create partition in the disk.
