### ISSUE TITLE
Non-destructive installation feature | Add support in GUIs for Linux 

### ISSUE THREAD

**Issue by Ricky-Tigg** [ventoy/Ventoy#1395]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.64

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

4 GiB

### What happened?

_Suggestion_: Add support of **non-destructive installation** feature in GUIs for Linux as well.

**Comment by ventoy** [comment]
`non-destructive installation` is not used by everyone. 
All the things when do non-destructive installation are processed by other tools, so shell version is enough and fitable.

**Comment by Ricky-Tigg** [comment]
Strange logic; that very feature Is illustrated as implemented in a GUI for Windows. Anyway, ticket already closed.
