### ISSUE TITLE
Volume formatting feature | Add support in CLI for Linux

### ISSUE THREAD

**Issue by Ricky-Tigg** [ventoy/Ventoy#1396]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.64

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

4 GiB

### What happened?

_Suggestion_: Add support of **volume formatting** feature, whose pendant In GUIs for Linux is the _Clear Ventoy_ option

**Comment by ventoy** [comment]
parted/fdisk/gparted... there are many tools to format volume.
No need to reinvent the wheel.
