### ISSUE TITLE
[issue]: cannot boot KDE Neon ISO

### ISSUE THREAD

**Issue by timkgh** [ventoy/Ventoy#1398]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.64

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### Disk Manufacturer

Samsung

### Image file checksum (if applicable)

No.

### Image file download link (if applicable)

https://neon.kde.org/download

### What happened?

Tried to boot KDE Neon from https://neon.kde.org/download, both user and testing ISOs. I can get their GRUB menu but then the screen turns black and nothing happens.

I can write the 2 ISOs directly to a USB flash drive (without Ventoy) and they boot fine.

**Comment by ventoy** [comment]
1. Please checksum the ISO file as follows in Ventoy menu:
https://www.ventoy.net/en/doc_checksum.html

2. If the checksum is OK and the problem still exist. Then try GRUB2 Mode:
https://www.ventoy.net/en/doc_grub2boot.html

**Comment by timkgh** [comment]
Thank you very much! GRUB2 mode works.
