### ISSUE TITLE
[issue]: I can't clear ventoy on my usb drive, I've tried formatting using cmd but it doesn't work

### ISSUE THREAD

**Issue by JEDIPRO3471** [ventoy/Ventoy#1404]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.64

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

16GB

### Disk Manufacturer

Kingston

### What happened?

[log.txt](https://github.com/ventoy/Ventoy/files/7925841/log.txt)

**Comment by ventoy** [comment]
Use  `Option`  ---> `Clear Ventoy`  menu.

**Comment by JEDIPRO3471** [comment]
> Use `Option` ---> `Clear Ventoy` menu in Ventoy2Disk.exe

Thanks but I've tried it and it doesn't work

**Comment by ventoy** [comment]
What do you mean about `doesn't work` ?
After run the menu Ventoy still exist? The ISO files still exist? You can still boot into Ventoy menu?
Please upload the log.txt after run the menu.

**Comment by JEDIPRO3471** [comment]
> What do you mean about `doesn't work` ? After run the menu Ventoy still exist? The ISO files still exist? You can still boot into Ventoy menu? Please upload the log.txt after run the menu.
[log.txt](https://github.com/ventoy/Ventoy/files/7933649/log.txt)

**Comment by JEDIPRO3471** [comment]
1. After run the menu Ventoy still exist? yes
2.  The ISO files still exist? yes, but it's not an iso file but it's an lmg file
3. You can still boot into Ventoy menu? yes

Sorry if my English is bad 😊

**Comment by ventoy** [comment]
Since you can still boot into Ventoy.
Put the VentoyLiveCD.iso in Ventoy USB and reboot your computer.
When you boot into Ventoy menu, select the VentoyLiveCD.iso to boot.
After boot you will run into Linux version of Ventoy GUI as follows:
And then run `Option` --> `Clean Ventoy`.

![image](https://user-images.githubusercontent.com/59477474/150998595-63fc8795-4d69-487f-9adc-1cc2d1a3b07a.png)

**Comment by Cathgao** [comment]
渣士顿16G，会不会是因为写入寿命终结导致变成只读了。你试试往里面复制东西之后安全退出，再插回去看看东西写进去没有

**Comment by undod** [comment]
> 渣士顿16G，会不会是因为写入寿命终结导致变成只读了。你试试往里面复制东西之后安全退出，再插回去看看东西写进去没有

???

**Comment by arafatx** [comment]
Are you on Windows? Try `diskpart`:

diskpart
list disk
select disk X     (where X is your thumdrive)
clean

done cleaning.

**Comment by ventoy** [comment]
I  close the issue now after 20+ days without response.
If you have any update, please reopen the issue.
