### ISSUE TITLE
[issue]: /ventoy/ventoy_chain.sh: exec : line 428: /init not found

### ISSUE THREAD

**Issue by 2096779623** [ventoy/Ventoy#1405]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.64

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64GB

### Disk Manufacturer

Sandisk

### Image file checksum (if applicable)

No.

### What happened?

![](https://s4.ax1x.com/2022/01/25/77403D.jpg)
![](https://s4.ax1x.com/2022/01/25/774Bge.jpg)
![](https://s4.ax1x.com/2022/01/25/774DjH.jpg)

CPU:Intel Core i3-9100
motherboard: Lenovo 3140
Lenovo TianYi510S-07ICB

Download Image From：http://old.kali.org/kali-images/kali-2021.4/kali-linux-2021.4-installer-amd64.iso

secure boot is disabled.

**Comment by ventoy** [comment]
Please checksum the ISO file as follows:
https://www.ventoy.net/en/doc_checksum.html
and give me the photo about the result.

**Comment by 2096779623** [comment]
> Please checksum the ISO file as follows: https://www.ventoy.net/en/doc_checksum.html and give me a photo about the result.

![DSC_0008](https://user-images.githubusercontent.com/57583560/150978051-4c5e17ad-77be-4e33-adfe-bfdb7b71cf2b.JPG)
![DSC_0007](https://user-images.githubusercontent.com/57583560/150978087-aaf46ebb-3a52-4cab-a12a-88980fbf40eb.JPG)

**Comment by ventoy** [comment]
It seems the ISO file is corrupted. Please check:
http://old.kali.org/kali-images/kali-2021.4/SHA256SUMS
