### ISSUE TITLE
Ventoy boot | View listing persistence-files | Missing option "Return to previous menu [Esc]"

### ISSUE THREAD

**Issue by Ricky-Tigg** [ventoy/Ventoy#1408]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.64

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

16 MiB

### What happened?

At Ventoy boot, once the view listing **persistence-files** has been exhibited, there is no possibility to return to previous menu – for example in order to reconsider a choice. _Suggestion_: implementing the already existing function _Return to previous menu [Esc]_.

**Comment by ventoy** [comment]
When listing persistence file it can not return back to main menu and can only continue to boot, it is so designed.

**Comment by Ricky-Tigg** [comment]
What was that? I did learn a lesson. Reporting here the obvious as anomalies is as always just a waste of time. Won't happen to me again. No need thanks to encourage you keeping on doing for fun bad designs or mixing opposite concepts, you did master them all well enough by your own. After all it's your project, not mine, not ours. Good luck although. 

_Note_: Feel free to translate in Chinese; that might be helpful to you.
