### ISSUE TITLE
Source link for fat_io_lib.zip doesn't work

### ISSUE THREAD

**Issue by JohnVillalovos** [ventoy/Ventoy#141]
The source link at:
https://github.com/ventoy/Ventoy/blob/efa7a942ac87c44ae3cd78d1549f79f8d5576249/DOC/BuildVentoyFromSource.txt#L34

doesn't work. I tried to figure it out but couldn't. It redirects to the github page for the project. Maybe docs should say to git clone the project?

**Comment by ventoy** [comment]
But indeed I download the zip file here from
[http://ultra-embedded.com/releases/fat_io_lib.zip](http://ultra-embedded.com/releases/fat_io_lib.zip)

I just upload the zip directly to Ventoy/vtoyfat/fat_io_lib  directory.  
There are only txt and source file in the zip, no binary files, you can use it.

**Comment by ventoy** [comment]
Hi,
I will close the issue now, you can make a new issue if you still have some problem.
