### ISSUE TITLE
[Success Image Report]: NHV-BOOT-2022-888-EXTREME

### ISSUE THREAD

**Issue by quyentruong** [ventoy/Ventoy#1411]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.64

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

NHV-BOOT-2022-888-EXTREME.iso

### Image file checksum type

SHA256

### Image file checksum value

B6094383CA129F5051C5251CB89800952E2DA75A3A8C79941A6C78205565908E

### Image file download link (if applicable)

https://nhvboot.com/download

### Test envrionment

Desktop MSI B550i AMD 5950x 

### More Details?

There are two version: free and paid. You can find the iso here: https://nhvboot.com/download

I tested the paid version. The image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks.
