### ISSUE TITLE
如何设置，既能支持安全启动，又能在关闭安全启动时启动？

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#1414]
如何设置，既能支持安全启动，又能在关闭安全启动时启动？

**Comment by ventoy** [comment]
理论上安装Ventoy时勾选 `安全启动支持` 可以同时支持安全启动开启和关闭的情况。
但在有一些主板上有问题。

**Comment by 1457384613gh** [comment]
> 理论上安装Ventoy时勾选 `安全启动支持` 可以同时支持安全启动开启和关闭的情况。 但在有一些主板上有问题。

好的谢谢，顺便问下，可以添加这些功能吗？

①Ventoy呈现的 映像文件的列表，可以按照 映像文件所在的文件夹做成树状的吗？
②可以在映像所在的目录添加同名的图标文件，使Ventoy检索而生成的列表选项的左边呈现操作系统的LOGO吗？

**Comment by ventoy** [comment]
1. https://www.ventoy.net/cn/doc_treeview.html
2. 这个不支持。但可以通过 [菜单类型插件](https://www.ventoy.net/cn/plugin_menuclass.html)  针对每个镜像文件设置不同的logo，效果是一样的。
