### ISSUE TITLE
[Success Image Report]: OpenBSD 7.0

### ISSUE THREAD

**Issue by k4leg** [ventoy/Ventoy#1418]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.64

### BIOS Mode

Both

### Partition Style

GPT

### Image file name

install70.img  install70.iso

### Image file checksum type

SHA256

### Image file checksum value

6bc7f945c2709247d449892c33c0f1b9a31590528572c1e988fef4a7637210e6  1882f9a23c9800e5dba3dbd2cf0126f552605c915433ef4c5bb672610a4ca3a4

### Image file download link (if applicable)

https://cdn.openbsd.org/pub/OpenBSD/7.0/amd64/install70.img  https://cdn.openbsd.org/pub/OpenBSD/7.0/amd64/install70.iso

### Test envrionment

Desktop ASUS TUF GAMING B550-PLUS (WI-FI), Ryzen 7 5700G

### More Details?

This image files booted successfully in Ventoy.

`install70.img` in UEFI is successfully booted but (not fatal):
```
probing: pc0 mem[640K 156M 2M 13M 2446M 408K 508M 20M 12515M]
disk: hd0 hd1* hd2*
>> OpenBSD/amd64 BOOTX64 3.59
boot>
cannot open hd0a:/etc/random.seed: No such file or directory
```
Legacy BIOS doesn't boot:
```
 Using drive 2, partition 3.
Loading......
probing: pc0 com0 mem[614K 156M 2M 13M 2447M 19M 13027M a20=on]
disk: hd0+* hd1+*
>> OpenBSD/amd64 BOOT 3.53
open(hd2a:/etc/boot.conf): can't read disk label
boot>
cannot open hd2a:/etc/random.seed: can't read disk label
booting hd2a:/bsd: open hd2a:/bsd: can't read disk label
 failed(100). will try /bsd
```

`install70.iso` in BIOS is successfully booted but (not fatal):
```
 CD-ROM: E0
Loading /7.0/AMD64/CDBOOT
probing: pc0 com0 mem[614K 156M 2M 13M 2443M 19M 13027M a20=on]
disk: hd0+* hd1+* cd0
>> OpenBSD/amd64 CDBOOT 3.53
boot>
cannot open cd0a:/etc/random.seed: No such file or directory
```
UEFI doesn't boot at all (even through `cp $img $dev` or `dd bs=4M if=$img of=$dev conv=fsync oflag=direct status=progress`).

**Comment by ventoy** [comment]
Thanks.
