### ISSUE TITLE
Alternative download link for mirrors-libfuse-fuse-2.9.9.zip?

### ISSUE THREAD

**Issue by JohnVillalovos** [ventoy/Ventoy#142]
I attempted to download the file listed at:
https://github.com/ventoy/Ventoy/blob/efa7a942ac87c44ae3cd78d1549f79f8d5576249/DOC/BuildVentoyFromSource.txt#L33

https://gitee.com/mirrors/libfuse/repository/archive/fuse-2.9.9.zip

But it requires an account in order to proceed.  Is there a github or some other site link for the zip file?

**Comment by ventoy** [comment]
Hi,
I updated it to a github url. You should also update 2 related scripts.

`Ventoy/DOC/BuildVentoyFromSource.txt`
`Ventoy/ExFAT/buidlibfuse.sh`
`Ventoy/FUSEISO/build_libfuse.sh`

**Comment by ventoy** [comment]
I will close the issue now, If you still have problem, you can reopen it.
