### ISSUE TITLE
How to set to get that Ventoy always boots successfully whether secure boot is enabled or disabled.

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#1420]
How can I set to get that Ventoy always boots successfully whether secure boot is enabled or disabled.

If "secure boot [√]”  when setting Ventoy before installing, it cannot boot because BIOS has been set that secure boot is disabled, and Ventoy booting needs secure boot enabled.

If "secure boot [ ]”  when setting Ventoy before installing, it cannot boot because BIOS has been set that secure boot is enabled, and Ventoy booting needs secure boot disabled.

**Comment by ventoy** [comment]
Duplicate of #1414
