### ISSUE TITLE
[issue]: persistence for Batocera.Linux

### ISSUE THREAD

**Issue by candrapersada** [ventoy/Ventoy#1421]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.64

### What about latest release

No. I didn't try the latest release.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

200 GB

### Disk Manufacturer

TOSHIBA

### Image file download link (if applicable)

https://mirrors.o2switch.fr/batocera/x86_64/stable/last/batocera-x86_64-32-20210920.img.gz

### What happened?

How to use persistence for remember Batocera.Linux settings?

**Comment by ventoy** [comment]
This is an .img file so it is persistency by default and no special setting needed.
For example:
1. boot into batocera.img
2. Press F1 to browse files
3. create a new file under `Share/music` folder
4. reboot computer/boot into Ventoy/select batocera.img again
5. boot into batocera.img again, you will find the new file still exist.
