### ISSUE TITLE
[issue]: can't boot to recalbox

### ISSUE THREAD

**Issue by candrapersada** [ventoy/Ventoy#1423]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.64

### What about latest release

No. I didn't try the latest release.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

200 GB

### Image file download link (if applicable)

https://upgrade.recalbox.com/latest/download-wizard/x86_64/recalbox-x86_64.img.xz

### What happened?

A bug happened! why can't boot to recalbox from ventoy?

**Comment by ventoy** [comment]
I have fixed it, you can try with the CI release: 
https://github.com/ventoy/Ventoy/actions/runs/1801342733
https://www.ventoy.net/en/doc_github_ci.html


***Attention:***  
The latest recalbox img file will auto extend space during the first boot time.
So you **MUST** extend the original img file size (at least 2GB) before boot it from Ventoy.

For example, in linux you can extend the img file as follows (just append 2GB zero data to the end of the original img file):
```
dd if=/dev/zero bs=1M count=2048 >> recalbox-x86_64.img
```

Then copy the new `recalbox-x86_64.img` file to Ventoy USB stick and boot it.

**Comment by candrapersada** [comment]
> Attention:
> The latest recalbox img file will auto extend space during the first boot time.
> So you MUST extend the original img file size (at least 2GB) before boot it from Ventoy.

how to extend the img from Windows?

**Comment by ventoy** [comment]
On Windows
1. Find a file in Windows, it can be any file with any content, the only requirement is that its size must be at least 2GB.  Assume the file is  `xxx.bin`
2.  run the command in cmd.exe
```
copy /b recalbox-x86_64.img+xxx.bin  recalbox-x86_64_new.img
```

Finally copy the `recalbox-x86_64_new.img` to Ventoy USB stick and boot it.

**Comment by candrapersada** [comment]
how to use `xxx.bin` for add 2GB?

**Comment by ventoy** [comment]
run the command in `cmd.exe`
***copy /b recalbox-x86_64.img+xxx.bin  recalbox-x86_64_new.img***  

This command will concat `recalbox-x86_64.img` and `xxx.bin` to generate a new file `recalbox-x86_64_new.img`

**Comment by candrapersada** [comment]
what i mean is how to make `xxx.bin` with size 2GB

**Comment by ventoy** [comment]
You don't need to create a special file with exactly 2GB size.
Just find a file, for example,  abc.iso  xxx.img  xxx.rar ....   any file is OK, only that its size is at least 2GB (can be 3GB 4GB ...)

**Comment by ventoy** [comment]
Or you can make a copy of recalbox-x86_64.img and rename it as xxx.bin
```
copy  recalbox-x86_64.img   xxx.bin
```

**Comment by ventoy** [comment]
Can it work?

**Comment by candrapersada** [comment]
yes
