### ISSUE TITLE
[Success Image Report]: SeaToolsDOS223ALL.iso

### ISSUE THREAD

**Issue by 904570220** [ventoy/Ventoy#1424]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.64

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

SeaToolsDOS223ALL.ISO

### Image file checksum type

MD5

### Image file checksum value

FD695EE702255E0FBE300F0E0C0F3BD7

### Image file download link (if applicable)

http://www.seagate.com/staticfiles/support/seatools/SeaToolsDOS223ALL.ISO

### Test envrionment

GA-B75M-D3V  + E3 1230 V2

### More Details?

This image file booted successfully in Ventoy.
[SeaToolsDOS223ALL.zip](https://github.com/ventoy/Ventoy/files/8007147/SeaToolsDOS223ALL.zip)

operating system：Freedos

**Comment by ventoy** [comment]
Thanks!
