### ISSUE TITLE
[Feature Request]: Add possiblity to add ventoy to grub menu 

### ISSUE THREAD

**Issue by enigma131** [ventoy/Ventoy#1426]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.65

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

16 Go

### What happened?

The idea here is to have a new line in grub menu for opening a cascaded Ventoy menu. A option can redirect default directory for downloaded iso files. Only possible for EFI mode ?

**Comment by ventoy** [comment]
I don't quite understand.
Please give more detailed explanation about this.

**Comment by enigma131** [comment]
It would be nice to access to ventoy via an added line in grub (installed on hard disk)

**Comment by enigma131** [comment]
I've just test the browse function (via F2) from version 1.0.69 on usb stick, It's perfect ;), no more vlnk need
I'm searching now a way to install ventoy on installed hardisk (without format it) and have a grub entry for it ..

**Comment by enigma131** [comment]
I've done a try with chainloading. First i have done a menu entry at /etc/grub.d/40_custom for second partition of Ventoy's prepared stick: 
menuentry 'Ventoy' {
     insmod part_gpt
     insmod fat
     insmod ntfs
     set root='hd0,2'
     chainloader ($root)/EFI/BOOT/BOOTX64.EFI
}
Ventoy starts.
Then i have add a Fat 16 partition at end of system disk of 32 Mbytes, copied in it the content of second partition from Ventoy's prepared stick, modified the 'root' value for menu entry. After reboot and select Ventoy menu, i get grub rescue.
Any chance to solve this ?

**Comment by enigma131** [comment]
I've just seen from disk_layout that Efi part must be at number 2 and this is hard coded in lot of files. So I have destroyed my unused Windows MSR partition (2) and format it to Fat 16. I have copied necessary x64 files in it (its 16 mbytes).
Now I get an error code (7) .. I must analyse more or recompile, error seems related to partition size and position.

**Comment by steve6375** [comment]
Also ptn 1 must start at sector 2048. I think grubw boot code may also be checked in MBR.

**Comment by enigma131** [comment]
I have patch 2 tests in ventoy_check_official_device, no more error but I have an exit. Volume name is OK. Yes I have see VTOY_CMD_CHECK macro for size 33554432. Must be patched too before new try.

**Comment by enigma131** [comment]
Patch done for VTOY_CMD_CHECK. Ventoy starts now. Browsing is working, some ISOs are loading correctly and are working well.
But some bigger ISOs are hanging after starting, I don't know why.

**Comment by steve6375** [comment]
There is an article on rmprepusb.com for compiling ventoy, but full details are in ventoy ebook.

**Comment by enigma131** [comment]
Ok thanks for the link. 
I have perhaps found the problem, but can't debug it with vtdebug.
As I said above, WinPE based Isos are working, standard W10 Isos loads , but for the installation phase, it says drivers are missing. I go back to dos console, launch notepad, and after browsing 2 different results :
1) with real ventoy stick boot, there is a mounted cdrom peripheral with iso content (and required drivers)
2) with method above (boot from second partition of system hard disk) , there is no mounted cdrom !!! ??? 
So something is missing (or blacklisted) for mounting the iso to cdrom.

**Comment by steve6375** [comment]
Good work, but have you tested ALL ISOs IMG and vhds? Including all functions of XML, additional .zip files, substitute cfg, etc?

**Comment by enigma131** [comment]
Not tested all, I've done it for my own. Have tested Isos and img files. Hope feature comes next in release version. Windows ISOs didn't work except PE versions as written above, because ISOs didn't auto mount on virtual cdrom ... This feature is only for Windows Installation purpose, so I haven't work on it.

**Comment by enigma131** [comment]
I have managed to make windows ISOs working also completely, including installation phase and VTOY_WIN11_BYPASS_CHECK. In vtoyjump.c, function VentoyHook, I have removed the part for vlnk mode test.

**Comment by candrapersada** [comment]
> I've fork my complete modifications here https://github.com/enigma131/Ventoy .

is there an option to chainload Ventoy Linux vDisk use [Ventoy Boot Image Files In Local Disk](https://www.ventoy.net/en/doc_vlnk.html) and [Browse/Boot Files In Local Disk](https://www.ventoy.net/en/doc_browser.html)
without install Ventoy to a physical disk like Grub2 File Manager?

**Comment by enigma131** [comment]
I don't know. My own github contribution is based on installing Ventoy in place of MSR partition, GPT disk.

**Comment by enigma131** [comment]
Why closed? .. It's working here ...

**Comment by BWGosselin** [comment]
A couple years late but I made a script to automatically add it to the GRUB https://github.com/BWGosselin/Ventoy_GRUB_Entry

**Comment by lucasgabmoreno** [comment]
I've tried this and works:
```
menuentry "Ventoy"{
		search --file --no-floppy --set=root /EFI/BOOT/BOOTX64.EFI
		chainloader /EFI/BOOT/BOOTX64.EFI
}
```
