### ISSUE TITLE
[Success Image Report]: PearOS Monterey (linux)

### ISSUE THREAD

**Issue by Ktoto48** [ventoy/Ventoy#1428]
### Official Website List

- [x] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.65

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

pearOS_Monterey_64bit-12-beta-2021.07.01

### Image file checksum type

SHA256

### Image file checksum value

C49DB01F6719A2B196F487CEF070B86EEEDE279B0623B11955920AD9575C3430

### Image file download link (if applicable)

https://cdn.pearos.xyz/iso/monterey/

### Test envrionment

PC with Intel Pentium III, 4GB RAM, 500 HDD, GPU 1GB, Motherboard MSI 

### More Details?

This image file booted successfully in Ventoy.

**Comment by Ktoto48** [comment]
P.S It is OS looks like MacOS but it is 64bit linux

**Comment by Ktoto48** [comment]
P.S It is OS looks like MacOS but it is 64bit linux

**Comment by ventoy** [comment]
Thanks!
