### ISSUE TITLE
[issue]: Ventoy won't start

### ISSUE THREAD

**Issue by Temporary-Name-2131723** [ventoy/Ventoy#1429]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.65

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

256GB

### Disk Manufacturer

SanDisk

### What happened?

When I tried to start Ventoy, it just booted into my hard disk.

**Comment by ventoy** [comment]
Try disable the `secure boot` option in your BIOS setup.

**Comment by AidenKRP99** [comment]
> Try disable the `secure boot` option in your BIOS setup.

It didn't have an effect.

**Comment by ventoy** [comment]
1.  Disable the `secure boot` option in your BIOS setup.
2.  Don't enable `secure boot support` option when install Ventoy.

Both 1 and 2 at the same time.

**Comment by Temporary-Name-2131723** [comment]
It worked.
