### ISSUE TITLE
[issue]: Ventoy 1.0.66 Vlnk for Ntfs Partitions under linux

### ISSUE THREAD

**Issue by enigma131** [ventoy/Ventoy#1430]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.66

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

16 Go

### What happened?

I have tested the vlnk new feature under linux . A downloaded iso file under Download from local ext4 partition works. If i try create a vlnk file of a other mounted Ntfs partition, I get error fuseblk is not supported.

How must I manage this, Vlnk for ext4 under linux and Vlnk for Ntsf under Windows ? (I have 3  partitions on same disk, 1 W10, 1 Linux and 1 Ntfs for common datas)

**Comment by ventoy** [comment]
Try this updated script.
https://github.com/ventoy/Ventoy/blob/master/Vlnk/VentoyVlnk.sh

**Comment by enigma131** [comment]
Wow quick fix, well-done!  It's working from both mounted Ntfs file! Now I can play with small Usb sticks and no more need to copy to stick, and boot is very fast. Perhaps an other suggestion:  auto detect iso files from a dedicated directory + partition ?

**Comment by ventoy** [comment]
> Wow quick fix, well-done! It's working from both mounted Ntfs file! Now I can play with small Usb sticks and no more need to copy to stick, and boot is very fast. Perhaps an other suggestion: auto detect iso files from a dedicated directory + partition ?

This conflict with Ventoy's boot mechanism and plugin mechanism.

**Comment by enigma131** [comment]
Ok so, big progress this 1.0.66.
