### ISSUE TITLE
Boot Image Files In other external hard disk without install ventoy like vlnk

### ISSUE THREAD

**Issue by candrapersada** [ventoy/Ventoy#1434]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.66

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

300 GB

### What happened?

is there an option to Boot Image Files In another external hard disk without installing ventoy like `vlnk`.
eg You can create Part3 with the reserved space and use for other Boot Image Files or in another external hard disk without installing ventoy?

**Comment by ventoy** [comment]
With latest 1.0.67 release you can press `F2` to browse and boot files in local disk.

**Comment by candrapersada** [comment]
why Part 3 with the reserved space can't be accessed with vlnk or F2?
![image](https://user-images.githubusercontent.com/36833664/153920175-3487cfc3-c7e6-471a-8eef-f5934060abab.png)
