### ISSUE TITLE
[Success Image Report]: manjaro-kde-21.2.3-220205-linux515.iso

### ISSUE THREAD

**Issue by Keruskerfuerst** [ventoy/Ventoy#1436]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.66

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

manjaro-kde-21.2.3-220205-linux515.iso

### Image file checksum type

SHA1

### Image file checksum value

f79c93775b7f4fe61c9cd081c139578ec56b3700

### Image file download link (if applicable)

https://sourceforge.net/projects/manjarolinux/files/kde/21.2.3/

### Test envrionment

custom computer

### More Details?

This image file booted successfully in Ventoy.
It does boot fast.
No problems.
I have installed Manjaro with Ventoy USB stick.

**Comment by ventoy** [comment]
Thanks!

**Comment by Mannshoch** [comment]
Tested Manjaro-kde-21.2.6-220416-linux515.iso

It not work

![IMG_20220604_201020](https://user-images.githubusercontent.com/7795891/172020194-a3689d51-a673-477e-bdc4-73182c939096.jpg)
k
