### ISSUE TITLE
[Suggestion]: Browser and Power positions

### ISSUE THREAD

**Issue by KrinalPatel889** [ventoy/Ventoy#1437]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.67

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

32

### What happened?

Hello @ventoy

This is a humble suggestion and a request.

The position of Power(reboot/halt) was better where it was before. [F2: Power] (old Habit) 

And you can put (Browser) in [F4 : Localboot]. This way it will be more logical. One can choose all boot option together. Either boot from local disks or browse for isos using browser in [F4: Localboot] 

This is just a suggestion if you like. Else decision is yours. :) Thanks.

**Comment by ventoy** [comment]
I think browser is a more useful feature than localboot and worth a separate hotkey :)
