### ISSUE TITLE
Change Browser menu style

### ISSUE THREAD

**Issue by Silexium** [ventoy/Ventoy#1439]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.67

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64GB [Kingston DT100G3]

### Disk Manufacturer

Kingston

### What happened?

Is it possible to change the TreeView menu style for the Browser? Even when "VTOY_TREE_VIEW_MENU_STYLE" is set to "1" (no DIR & file size prefixes) in "ventoy.json", the Browser still shows DIR & file size prefixes.

**Comment by ventoy** [comment]
Try this CI release: 
https://github.com/ventoy/Ventoy/actions/runs/1844901325
https://www.ventoy.net/en/doc_github_ci.html

**Comment by Silexium** [comment]
1.0.69 fixes the issue.
