### ISSUE TITLE
[issue]: Lenovo x250 firmware update ISO hangs

### ISSUE THREAD

**Issue by abitrolly** [ventoy/Ventoy#1440]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.67

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

7.9GB

### Disk Manufacturer

Smartbuy 8GB

### Image file checksum (if applicable)

No.

### Image file download link (if applicable)

https://pcsupport.lenovo.com/be/en/products/laptops-and-netbooks/thinkpad-x-series-laptops/thinkpad-x250/downloads/ds102288-bios-update-utility-bootable-cd-for-windows-10817-64-bit-7-32-bit-thinkpad-x250

### What happened?

After selecting `n10ur29w.iso` from either text mode or GUI mode, the screen become garbled and notebook hangs.

**Comment by ventoy** [comment]
Try press F1 firstly and then select the ISO file to boot.

**Comment by abitrolly** [comment]
@ventoy gives this dump.

![image](https://user-images.githubusercontent.com/8781107/154951159-34f1f5be-d00f-4cb5-b974-57453b1297c5.png)

The checksum in the image is fine.

**Comment by steve6375** [comment]
For UEFI
You can use 7zip to extract the 3.fat file (right-click on .iso file in Windows Explorer and choose Open Inside # )
Then change name from 3.fat to n10ur29w.img  (or any name ending in .img)
Then UEFI boot to Ventoy and select the file.
![image](https://user-images.githubusercontent.com/1469350/154959988-d795f1bb-f4d6-44de-af3c-9d8cf06592d8.png)

**Comment by abitrolly** [comment]
Let me check.

**Comment by abitrolly** [comment]
The checksum in the image is fine.

**Comment by abitrolly** [comment]
I am going to create the checksum file to check with Ventoy itself.

**Comment by steve6375** [comment]
Press h for help, ventoy can get hash

**Comment by abitrolly** [comment]
These are official checksums.
```
    Checksum Tips

    SHA256: 8e3e2a3162e44ab084dd56a73f2d0a0e2d4f25841c4371e824e8550667fc54c8
    SHA1: 59dfcd4f5a186a062688b855b9d1b42fc150c245
    MD5: ea2b0572fed05f78e2c4a11fe273d1cf
```
This is what I get from mounted drive.
```
➜  Ventoy sha256sum n10ur29w.iso
8e3e2a3162e44ab084dd56a73f2d0a0e2d4f25841c4371e824e8550667fc54c8  n10ur29w
```

**Comment by steve6375** [comment]
I get same xsum and it works ok on  vbox uefi and ideapad 300 uefi64.
Ventoy should show UEFI at bottom of menu.
If so then there is something odd about your system.

**Comment by abitrolly** [comment]
Looks like I didn't mention my model. It is x250. I doubt it is faulty or something. In the past I already flashed the BIOS successfully without Ventoy.

**Comment by abitrolly** [comment]
I believe I tried this instruction https://www.cyberciti.biz/faq/update-lenovo-bios-from-linux-usb-stick-pen/ - going to try it again.

**Comment by abitrolly** [comment]
Extracted El Torito image from the CD. Going to try if Ventoy can load it.

```bash
$ geteltorito -o n10ur29w.{img,iso}
Booting catalog starts at sector: 20 
Manufacturer of CD: NERO BURNING ROM
Image architecture: x86
Boot media type is: harddisk
El Torito image starts at sector 27 and has 227328 sector(s) of 512 Bytes

Image has been written to file "n10ur29w.img".
```

**Comment by abitrolly** [comment]
Booting the `.img` directly failed with the message about missing operating system.

Booting into memory took significantly more time than with `.iso` (my feeling) and then failed with a trace similar to screenshot above.

Now I am going to `dd` that image to USB drive and try to boot from it without Ventoy.

**Comment by abitrolly** [comment]
The `dd` USB image failed to load. I don't think it is a problem with USB stick, as Ventoy was booted successfully. Maybe there is some hack to force people use Lenovo USB CD-ROM hardware for flashing. I remember last time I probably flashed it over the network. In any case I don't think Ventoy can help this.

**Comment by steve6375** [comment]
I used 7zip  - right-click  - 7z - Open archive - # 
then extract 3.fat as a file
then rename 3.fat to lenovo.img
then add to Ventoy and UEFI64 boot from it.

**Comment by steve6375** [comment]
You need to use the # option in the GUI
right-click on the file as I explained
![image](https://user-images.githubusercontent.com/1469350/155154565-7440467c-2742-479f-a360-f37ca53d6263.png)
![image](https://user-images.githubusercontent.com/1469350/155154737-9956ed1a-34e8-4016-ac1a-492ab5b71221.png)

**Comment by abitrolly** [comment]
I am using Linux, so there are only command line tools. What is the MD5 checksum of this `3.fat` file? It is the same as the extracted El Torito image?
```
$ md5sum n10ur29w.img
4e01d847db87c4b046dd1fe9558b4beb  n10ur29w.img
``

**Comment by steve6375** [comment]
7z x -t# n10ur29w.iso

try something like this ?

**Comment by abitrolly** [comment]
The checksum for the `7z` extracted file is different.
```
$ md5sum 3.fat
c61b14f8d36dd2c1fb28612add0c1d7b  3.fat
```
I will try to load both files once more in UEFI, but something tells me that it just not supported in X250.

**Comment by steve6375** [comment]
Using Ventoy -  m   md5sum
![image](https://user-images.githubusercontent.com/1469350/155547256-1b7edaa4-dad5-46a8-ac58-4023173459f7.png)

file must have .img extension

**Comment by abitrolly** [comment]
Booting in UEFI. Ventoy boots. Both images fail to load. Hanging with blank screen in graphic mode. Hanging with cursor on a blank screen in text mode. Memory mode doesn't help - I am not even sure it even loads any image into memory, because LED flashes only for a second or even less.

In Legacy and text mode `3.fat` image failed with an error like invalid partition. El Torito image failed with  "Missing operating system".

**Comment by steve6375** [comment]
Is md5 of **3.fat.img** file the same as in the screenshot above?

**Comment by abitrolly** [comment]
@steve6375 yes, exactly the same.

**Comment by steve6375** [comment]
You checked by pressing m in Ventoy ?
Can you try booting on other UEFI systems?

**Comment by abitrolly** [comment]
> You checked by pressing m in Ventoy ?
No. Reloaded and checked from terminal. I don't see how flash controller would return different data after it already could read Ventoy files successfully. I may try it next time I reboot, but I still doubt it is a checksum problem.

> Can you try booting on other UEFI systems?
No.

**Comment by bigo72** [comment]
Hey guys I have exactly the same problem. Something doesn't work with this iso images downloaded on Lenovo websites. I don't think it's a Ventoy issue, it's the iso. Even dd flash doesn't make a bootable pendrive. 
Same laptop.

**Comment by abitrolly** [comment]
Finally was able to write the image to USB with `dd`.

Be **careful** with `/dev/sdc` - check that it is USB drive with `lsblk`.
```
sudo dd if=x250.img of=/dev/sdc bs=64K status=progress
```
