### ISSUE TITLE
[Resolved]: Porteus Kiosk not booting starting from Ventoy v 1.0.67

### ISSUE THREAD

**Issue by jt477** [ventoy/Ventoy#1446]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.68

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

8GB

### What happened?

Starting from Ventoy v1.0.67, Porteus Kiosk 5.2 is not booting anymore.

![IMG_20220215_140423_proc](https://user-images.githubusercontent.com/92990404/154073093-e6193851-1fdd-4a93-8654-b204011ee986.jpg)

I had also reported the fact that Porteus Kiosk 5.3 was not booting, but it has been said that it must be related to the distribution itself.

**Comment by ventoy** [comment]
You can try the CI release when it finish.
https://github.com/ventoy/Ventoy/actions/runs/1847996056
https://www.ventoy.net/en/doc_github_ci.html

**Comment by jt477** [comment]
Thank you very much for your prompt answer mate.
Even with the latest CI (02151425), same error :(

**Comment by ventoy** [comment]
Have you tested the CI release here ? https://github.com/ventoy/Ventoy/actions/runs/1847996056
The CI version is : `02151619`

**Comment by jt477** [comment]
> Have you tested the CI release here ? https://github.com/ventoy/Ventoy/actions/runs/1847996056 The CI version is : `02151619`

Spot on, it works! 
Porteus Kiosk 5.2 boots fine.
Thank you very much indeed!
