### ISSUE TITLE
Windows 10 Pro x64 21H2

### ISSUE THREAD

**Issue by Keruskerfuerst** [ventoy/Ventoy#1447]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.69

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

Win10_21H2_German_x64.iso

### Image file checksum type

SHA1

### Image file checksum value

e0492d3e3f1f3f499e4fc2e62765bb03cadf4bf6

### Image file download link (if applicable)

https://www.microsoft.com/de-de/software-download/windows10ISO

### Test envrionment

custom computer

### More Details?

This image file booted successfully in Ventoy.
I have installed Win10 Pro x64 21H2 successfully.

**Comment by ventoy** [comment]
Thanks for the report.
