### ISSUE TITLE
Manjaro XFCE 21.2.3

### ISSUE THREAD

**Issue by Keruskerfuerst** [ventoy/Ventoy#1448]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.69

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

manjaro-xfce-21.2.3-220205-linux515.iso

### Image file checksum type

SHA1

### Image file checksum value

afc60695ba8c43ed51038fd93b33799ee9755f05

### Image file download link (if applicable)

https://sourceforge.net/projects/manjarolinux/files/xfce/21.2.3/

### Test envrionment

custom computer with broadwell CPU

### More Details?

This image file booted successfully in Ventoy.
I have installed this image on 3 computers.

**Comment by ventoy** [comment]
Thanks for the report.
