### ISSUE TITLE
[issue]: save location vlnk file

### ISSUE THREAD

**Issue by candrapersada** [ventoy/Ventoy#1451]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.69

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

300 GB

### What happened?

why is there no option to select save location vlnk?

**Comment by ventoy** [comment]
To be simple.

But the new exe add some cmdline option.
https://github.com/ventoy/Ventoy/tree/master/Vlnk/vs/VentoyVlnk/Release

You can start as follows:
```
VentoyVlnk.exe  -s
```
Then, it will prompt for the save as file path.

Also you can specify the input and output file path.
```
VentoyVlnk.exe  -i xxx.iso -o xxx.vlnk.iso 
```

**Comment by candrapersada** [comment]
why is there no information on how to use cmdline option at https://github.com/ventoy/Ventoy/releases/tag/v1.0.70 or https://www.ventoy.net/en/doc_vlnk.html

**Comment by ventoy** [comment]
I have just updated the page https://www.ventoy.net/en/doc_vlnk.html f
