### ISSUE TITLE
[issue]: Ventoy & Grub2FM Multiboot F2:Browser not working 

### ISSUE THREAD

**Issue by abdullah-erturk** [ventoy/Ventoy#1453]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.69

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32 (Size of directory where Ventoy is installed, Total disk size: 240 GB)

### Disk Manufacturer

Sandisk SSD

### What happened?

I am using Grub2FM and Ventoy application as multiboot.

In the build I created, Grub2FM comes by default in both mbr and uefi modes. I am able to switch to Ventoy via Grub2FM.

All shortcuts work fine if I use Ventoy alone but as I said I want to use it as multiboot with Grub2FM.

When I want to use Ventoy (v1.0.69) as multiboot with Grub2FM, for some reason the F2:Browser feature doesn't work.

Can you help with this?

I also have a suggestion:

In F2:Browser mode, don't show all files.

Let Ventoy show only bootable files (efi, iso, img, vhd, grldr, etc.)

**Comment by ventoy** [comment]
Sorry, I have no time to solve non-standard Ventoy issue.

**Comment by ventoy** [comment]
Ventoy F2 does only show Ventoy supported bootable files now.
