### ISSUE TITLE
[issue]: Win11_English_x64.iso checked in your site as uefi compatible boots only from legacy. 

### ISSUE THREAD

**Issue by DestroyerBg** [ventoy/Ventoy#1456]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.69

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

Win11_English_x64.iso

### What happened?

UEFI  in this ISO is not working. When I boot screen resolution is low and motherboard logo is not showing (Msi A320). This makes me think that the uefi boot is not working from this iso and it's checked in your website that it can boot from both- uefi and legacy, but I don't think this is true. So can you help me to solve this or uncheck uefi in this ISO.

**Comment by ventoy** [comment]
I did test this ISO in my laptop in UEFI mode and it boot OK.

In the website tested list, I have list the test environment for every ISO file.
And I have already noticed in the top of the tested list website that `the iso file listed here may not work on you machine`.

Currently, I have no idea about this issue.

**Comment by steve6375** [comment]
If it boots to ventoy in UEFI mode then you will see "UEFI" at the bottom of the menu screen.
Maybe ISO is not an official Microsoft ISO or is corrupt?

**Comment by DestroyerBg** [comment]
Can you post the link for the ISO? I tried from the official microsoft site and from 3rd party and the result was same.

**Comment by Sayor0630** [comment]
> > If it boots to ventoy in UEFI mode then you will see "UEFI" at the bottom of the menu screen. Maybe ISO is not an official Microsoft ISO or is corrupt?
> 
> I see the UEFI label at the bottom of the menu screen. Windows 10 64x works perfectly but the 11 boots from the old legacy. Currently I am trying win 10 english international from this link https://tb.rg-adguard.net/dump.php?seach=win11&str=50&lang=en-GB

Download the ISO from here. https://www.microsoft.com/en-us/software-download/windows11
this is MS's official ISO
