### ISSUE TITLE
[Success Image Report]: WePE64_V2.2

### ISSUE THREAD

**Issue by ktns01** [ventoy/Ventoy#1458]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.69

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

WePE64_V2.2.iso

### Image file checksum type

MD5

### Image file checksum value

FA0A5B8057E1C635BC49BE7BC2F79CBC

### Test envrionment

Lenovo XiaoXinPro 16ACH 2021 & 家里的一台老爷机

### More Details?

This image file booted successfully in Ventoy.
安全启动支持已打开。
不能使用Memdisk模式

**Comment by ventoy** [comment]
Thanks.
