### ISSUE TITLE
Ventoy Browser 

### ISSUE THREAD

**Issue by 55hassan** [ventoy/Ventoy#1459]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.69

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

32mb

### What happened?

The new feature of the ventoy browser is a very nice application, but I only want to see 
the wim iso vhd vhdx efi files, I don't want to search the folders on all the disks, 
is it possible to see only the bootable ventoy files? (wim iso vhd vhdx efi)

**Comment by ventoy** [comment]
Ventoy did only list supported bootable files when browsing.
If there is no supported bootable files under a directory, your will see nothing when you enter the directory.

**Comment by 55hassan** [comment]
Yes but,without seeing the directory we only want to see the bootable files if any

**Comment by ventoy** [comment]
Then Ventoy need to search all the directories and sub-directories to get the file list.
This will be very slow.

**Comment by 55hassan** [comment]
No, it has been tried on non-offical ventoys, it is not very slow, we just want to use the original ventoy thank you have a nice day

**Comment by 55hassan** [comment]
> 

https://user-images.githubusercontent.com/99954783/154672549-24623f42-8d14-4a98-85ab-9607764cc893.mp4

**Comment by 55hassan** [comment]
Doesn't take long in (C:)does a very short search I can't record video from (C:)

**Comment by ventoy** [comment]
I have a 1TB size SATA HDD which is D:\ in my system.
I downloaded huge number of ISO files in it.
I just install Ventoy on it and when I boot, it shows `Ventoy scanning files, pleas wait.` and scanning for 500+ seconds before 
boot to the main Menu.

**Comment by 55hassan** [comment]
Thanks I want one last thing if it's convenient for you
please send me your  post the change you made in ventoy_browser.c?

**Comment by KrinalPatel889** [comment]
@ventoy

What are the future plans related to browser feature?

Do you have plan to implement features from grun2fm like Image (jpg, png) viewer, hex viewer, file info viewer, Txt file viewer, pxe boot?

**Comment by ventoy** [comment]
NO.
Ventoy only focus boot and will not add these features.

**Comment by candrapersada** [comment]
does `vlnk` have an option for an image folder (just like the folder softlink)

**Comment by sebma** [comment]
B.T.W. : The `Ventoy scanning files, pleas wait.` message long wait is solved here : https://www.ventoy.net/en/doc_search_path.html
