### ISSUE TITLE
[issue]: No ISO files found..!!

### ISSUE THREAD

**Issue by zerocoolroot** [ventoy/Ventoy#1461]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.70

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

16GB and 128GB

### Image file download link (if applicable)

https://a.imagem.app/A9WAYX.png

### What happened?

No ISO files found..!!

I have tried in normal PC also..!!

**Comment by zerocoolroot** [comment]
> 1. Is that OK if previous release (1.0.69/1.0.68...) ?
> 2. Can you see these .iso files in local disk if you pree F2 to browse ?
> 3. Did you use ventoy.json configuration? If so upload the json file here
> 4. I see you tested with QEMU, did you add your F: disk to the QEMU ?

Sorry @ventoy  ,

Was my mistake..!!

Works flawlessly..!!

**Comment by steve6375** [comment]
What was the mistake? We learn nothing from you unless we know!

**Comment by zerocoolroot** [comment]
> What was the mistake? We learn nothing from you unless we know!

Sorry @steve6375 ,

I didn't add my F: disk to the QEMU..!!
