### ISSUE TITLE
[issue]: Booting windows 11 for uefi, no bootfile found for uefi

### ISSUE THREAD

**Issue by youngoliverpl** [ventoy/Ventoy#1463]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.69

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64

### Disk Manufacturer

sandisk

### What happened?

I took ventoy and set up uefi and gpt partition. I turned off the secure boot in bios and went to selecting the image. I threw windows 11 earlier. When I choose it, I get the information "no bootfile found for uefi" I don't know what to do to run this iso.

**Comment by steve6375** [comment]
Do you mean you choose the USB stick to UEFI boot, or choose the Win11 ISO after booting to Ventoy UEFI menu?
Does Ventoy menu show "UEFI" at the bottom of the screen.
Is the MD5 checksum of the WIn11 file on the USB drive correct? Can you open the WIn 11 ISO using 7zip and see an EFI folder? Does a Win10 ISO give the same issue?

**Comment by youngoliverpl** [comment]
> Do you mean you choose the USB stick to UEFI boot, or choose the Win11 ISO after booting to Ventoy UEFI menu? Does Ventoy menu show "UEFI" at the bottom of the screen. Is the MD5 checksum of the WIn11 file on the USB drive correct? Can you open the WIn 11 ISO using 7zip and see an EFI folder? Does a Win10 ISO give the same issue?

i try now win10

**Comment by youngoliverpl** [comment]
> Do you mean you choose the USB stick to UEFI boot, or choose the Win11 ISO after booting to Ventoy UEFI menu? Does Ventoy menu show "UEFI" at the bottom of the screen. Is the MD5 checksum of the WIn11 file on the USB drive correct? Can you open the WIn 11 ISO using 7zip and see an EFI folder? Does a Win10 ISO give the same issue?

When I choose windows 11 I get the message "no bootfile for uefi" with windows 10 no problem, the installer starts

**Comment by youngoliverpl** [comment]
I noticed that with the original iso it starts and I created an iso in which I deleted the dll file that allows it to be installed on an unsupported pc. I used poweriso to create the iso

**Comment by ventoy** [comment]
Test the ISO file with VM (e.g. WMWare/VirtualBox)   connect the ISO file directly to the VM and set the VM to UEFI mode 
to see that whether the ISO file can boot in UEFI mode with the VM.

**Comment by youngoliverpl** [comment]
> Test the ISO file with VM (e.g. WMWare/VirtualBox) connect the ISO file directly to the VM and set the VM to UEFI mode to see that whether the ISO file can boot in UEFI mode with the VM.

i have vm on my pc, when i choose my iso i have info from screen down, when i choose original it starts
![Screenshot_1](https://user-images.githubusercontent.com/100018189/154796425-34e26081-0cb9-454b-a14f-98108fdea367.png)

**Comment by ventoy** [comment]
Test the win 10 ISO with the same VM for comparison.

**Comment by youngoliverpl** [comment]
> Test the win 10 ISO with the same VM for comparison.

With iso win10 also no problem as with original win11 image on virtual machine. This converted iso does not work

**Comment by youngoliverpl** [comment]
I am able to do something to boot my iso without a problem?

**Comment by ventoy** [comment]
Obviously, it's not a Ventoy issue.
The ISO file itself has some problem, it can not boot from CD/DVD in UEFI mode.
I'm not good at this. 
Maybe the convert method you used is not compatiable with UEFI mode.
