### ISSUE TITLE
[issue]: Tails fails to boot

### ISSUE THREAD

**Issue by sp1cyf0x** [ventoy/Ventoy#1467]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

aur/ventoy-bin 1.0.70-1

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

29.3GiB

### Disk Manufacturer

Kingston

### Image file checksum (if applicable) [sha512sum]

71f4e83015b95f0d17d9b8f1e1d1b08f811f1555c37f9d5ed2023d8bb5a4392bbd0f648723ad5b9419ea0952673ce2de1edde384a468079d017a7e59d789adb1  tails-amd64-4.27.img

fd9dad56c0558af311efaec4f8b73c107e2a5795a0da6da14efded59dcb4a5868dee8b43a6794371e35c0d37fe71f1a68de2d0aca02fd5cf097dab4bf748b272  tails-amd64-4.27.iso

### Image file download link (if applicable)

https://tails.boum.org/install/download/index.en.html

https://tails.boum.org/install/dvd-download/index.en.html

### What happened?

My PC successfully booted to Ventoy and then Tails's boot loader but face this error:
``` 
    Booting `Tails'

Loading the Linux kernel...
error: invalid magic number.
Loading the initramfs...
error: you need to load the kernel first.
Booting...
error: you need to load the kernel first.

Press any key to continue...

    Failed to boot both the default and fallback entries.

Press any key to continue...
```
Additional information:
Secure Boot Support   : YES.
Secure Boot Disabled.
I tried both the .img and the .iso.

**Comment by JacksonChen666** [comment]
did your download corrupt? please [verify your `.img` image here](https://tails.boum.org/install/download/index.en.html) or see the below:

```
a4caa33ee96bb3294467f5216cab61cfbafc7bd2c6794f0d97b447d942f1f3cd  tails-amd64-4.27.img
e03ef93c121343b8bca001c25555a4029f1d8a8781ce4b0fac0cf560d32051ec  tails-amd64-4.27.iso
```

**Comment by sp1cyf0x** [comment]
> did your download corrupt? please [verify your `.img` image here](https://tails.boum.org/install/download/index.en.html) or verify with the hashes below:
> 
> ```
> a4caa33ee96bb3294467f5216cab61cfbafc7bd2c6794f0d97b447d942f1f3cd  tails-amd64-4.27.img
> e03ef93c121343b8bca001c25555a4029f1d8a8781ce4b0fac0cf560d32051ec  tails-amd64-4.27.iso
> ```
> 
> ([hash source](https://tails.boum.org/install/v2/Tails/amd64/stable/latest.json))

It seems the problem was that I copied the files to Ventoy using "cp", I used Ctrl+C, Ctrl+P and it works fine.
