### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by Keruskerfuerst** [ventoy/Ventoy#1470]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.70

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

systemrescue-9.01-amd64.iso

### Image file checksum type

SHA1

### Image file checksum value

ab8a231b2478700115be6bc6f269b0e79606f96f

### Image file download link (if applicable)

https://www.system-rescue.org/Download/

### Test envrionment

custom computer with broadwell CPU

### More Details?

This image file booted successfully in Ventoy.
And Systemrescuecd starts and works.

**Comment by ventoy** [comment]
Thanks!
