### ISSUE TITLE
[issue]: Default tree view did not work

### ISSUE THREAD

**Issue by enigma131** [ventoy/Ventoy#1472]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.70

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

4Gb

### What happened?

No tree view as expected, my Json:
{
    "control":[
        { "VTOY_FILE_FLT_EFI": "1" },                               works
        { "VTOY_TREE_VIEW_MENU_STYLE": "0" },        0 or 1 : did not work
        { "VTOY_LINUX_REMOUNT": "1" },                        works
        { "VTOY_DEFAULT_KBD_LAYOUT": "FRENCH" }, not tested
        { "VTOY_HELP_TXT_LANGUAGE": "fr_FR" }        works
    ]
}

**Comment by ventoy** [comment]
You use wrong option.
You should use `VTOY_DEFAULT_MENU_MODE` not `VTOY_TREE_VIEW_MENU_STYLE`

**Comment by enigma131** [comment]
I was confused, it works!
Would you in future add default browse mode as json option ?

**Comment by enigma131** [comment]
It's working fine, thanks

**Comment by ventoy** [comment]
It has an issue when booting ISO file with the default browser mode. You can try the latest CI release
https://github.com/ventoy/Ventoy/actions/runs/1886328857
