### ISSUE TITLE
[issue]: Can't Find the NVMe SSD on Installation with neither Ventoy2Disk.exe or VentoyLiveCD

### ISSUE THREAD

**Issue by nicedavid0629** [ventoy/Ventoy#1476]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.70

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128GB

### Disk Manufacturer

Netac

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://github.com/ventoy/Ventoy/releases/download/v1.0.70/ventoy-1.0.70-livecd.iso

### What happened?

Dear contributors, 

I have better experience since I met Ventoy, it is an extraordinary work. 

Recently, I have a problem when tried to install it on the only M.2 NVMe disk in my PC by these steps: 
1. There is a removable disk with Ventoy installed, I plug it in the PC, now there are actually 2 disks on this PC
2. I ran the VentoyLiveCD.iso with Ventoy(Installed on the removable disk) on the PC
3. After I toggle **Show all devices** option, there is still only 1 Disk(the removable one), I can't find the M.2 NVMe SSD
4. I tried the same thing on another PC for a SATA3 SSD, which works fine

Reason for my operations: 
I want to install Ventoy on the disk for easily repeated installation of the systems without a USB drive. 

Tries:
I delete all portions for the NVMe disk, the problem is the same
I tried to use Ventoy2Disk.exe in WePE.iso, the problem is still there

Is there something that I did wrong or there is an issue?

Any reply is much appreciated. 

Thank you.

**Comment by ventoy** [comment]
Please open Ventoy2Disk.exe  and upload  `log.txt`  here for analyse.

**Comment by nicedavid0629** [comment]
Dear longpanda, 

Thanks for your reply. 

Let me simplify the issue that I met: 

1. When I tried to install Ventoy to the NVMe disk in WePE system, I failed with Ventoy2Disk.exe 
Here is the log.txt: 
[log.txt](https://github.com/ventoy/Ventoy/files/8146001/log.txt)

2. When I tried to use VentoyLiveCD.iso, it can't find the NVMe disk
Here is the video about how I use the VentoyLiveCD.iso: 
https://user-images.githubusercontent.com/22523730/155831203-6ceb83f7-6e49-4c1e-83cb-65101c85fe39.mp4
Here is a photo showing that there are actually 2 disks on this PC: 
![disk photo](https://user-images.githubusercontent.com/22523730/155831241-eee1c2a0-9679-4c6d-a47d-04776603183a.jpg)

**Comment by ventoy** [comment]
1. Download  `ubuntu-21.10-desktop-amd64.iso`  and copy to your Ventoy USB disk.
2. Download `ventoy-1.0.73-linux.tar.gz` and copy it to your NVME disk.
3. Reboot your computer, boot into the USB Ventoy and chose the ubuntu iso file to boot.
4. After boot into the ubuntu, find and copy the `ventoy-1.0.73-linux.tar.gz` from the NVME disk to the desktop
5. Decompress the tarball and run `sudo VentoyGUI.x86_64`

**Comment by ventoy** [comment]
I  close the issue now after 10 days without response.
If you have any update, please reopen the issue.
