### ISSUE TITLE
Ventoy 1.0.11 Notes have wrong Link

### ISSUE THREAD

**Issue by wimbrts** [ventoy/Ventoy#148]
[Ventoy 1.0.11](https://github.com/ventoy/Ventoy/releases) Notes have private IP-adres as Link.
Link for Notes should be https://www.ventoy.net/en/plugin_persistence.html
Link for Notes on website is OK

**Comment by ventoy** [comment]
Yes, I have modified it.

**Comment by wimbrts** [comment]
Thanks it is OK now
