### ISSUE TITLE
[issue]: "This is NOT a standard Ventoy device and is not supported" after first run

### ISSUE THREAD

**Issue by stuartpb** [ventoy/Ventoy#1483]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.70

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

64MB

### Disk Manufacturer

Netec

### What happened?

After installing Ventoy from scratch and booting from it once, the second time I try to boot from it, I get a "This is NOT a standard Ventoy device and is NOT supported." error.

It's not clear why it would raise this error - the partition table is unchanged from what it was after initially installing:

```
[stuart@stugear ~]$ sudo fdisk -l /dev/sda
Disk /dev/sda: 58.88 GiB, 63218647040 bytes, 123473920 sectors
Disk model: Storage Device  
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x738db324

Device     Boot     Start       End   Sectors  Size Id Type
/dev/sda1  *         2048 123408383 123406336 58.8G  7 HPFS/NTFS/exFAT
/dev/sda2       123408384 123473919     65536   32M ef EFI (FAT-12/16/32)
```

**Comment by ventoy** [comment]
1. Please take a photo when it shows `This is NOT a standard Ventoy device and is NOT supported.`
2. What did you boot when you first boot into Ventoy?
3. Run `sudo Ventoy2Disk.sh -l  /dev/sda` after it shows the error message.
4. Use some tool to do a fully test with your USB stick (e.g. https://fight-flash-fraud.readthedocs.io/en/latest/)  to make sure that your USB stick has no hardware problem.
