### ISSUE TITLE
[issue]: .vlnk.dat not working

### ISSUE THREAD

**Issue by candrapersada** [ventoy/Ventoy#1485]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.70

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

300 GB

### What happened?

A bug happened! why Linux Persistence file `.vlnk.dat` not working

**Comment by ventoy** [comment]
Please give more details about the issue. The more the better.

**Comment by candrapersada** [comment]
when using Persistence on Local Disk and `iso` on ventoy I see boot with /persistence `xxx.vlnk.dat` but the data in Persistence doesn't exist after boot, is there something wrong?

**Comment by ventoy** [comment]
For persistence,  the iso file and the dat file must be in the same side.
That is to say:
If the ISO file is in the Ventoy USB disk, the dat file must be in the Ventoy USB disk too (can not in local disk).
If the ISO file is in the Local disk, the dat file must be in the Local disk too (can not in Ventoy USB disk).

I will add some notes in the official document.

**Comment by candrapersada** [comment]
> I will add some notes in the official document later.


why is there no persistence information on Linux based Debian like Linux Mint LMDE 4, Slax Linux in the document?

**Comment by ventoy** [comment]
There are many distros/branches  based on debian, I have no much time to test all of them.
I only list these distros I have tesed yet and can make sure that it can work.

**Comment by candrapersada** [comment]
Slax Linux use `persistence` or `casper-rw`?

**Comment by ventoy** [comment]
I don't known.  I currently have no time to test it.
