### ISSUE TITLE
[Meta-suggestion] donations $$$

### ISSUE THREAD

**Issue by jwmh** [ventoy/Ventoy#1487]
Q: would additional money support this project?
Maybe for bug hunting bounties?

Ventoy -- and its followers -- has grown ENORMOUSLY in a few years!
Millions of downloads.

As it grows,
Seems that more helpers would help.

If so,
Consider these two platforms?
1. Liberapay
2. OpenCollective

Both are FOSS/FLOSS, and hosted solutions.

Liberapay is free.
(It itself is supported by its own set of Liberapayers, hence it is FREE 100%.)
It uses Paypal and Stripe as backend payment processors.
It is like a free (as in beer), and FLOSS ,
 Alternative / competitor to Patreon (!)

Patrons can setup recurring donations,
As little as $1.

OpenCollective I am less familiar with,
But it is what FDroid uses.
.
Iiuc,
 it allows for "open" organizations 
where the income is split between members
 (but the founder can choose to keep the majority of donations for themselves)
.
So it woulf be very useful for offering bounties forbug hunting and issue management, making pull requesta or co tributing patches or testing ISOs and doing general overall QA work, 
incl writing,updating documentation.
.
 It also offers users/members/public a transparent budget,  
so people can see how much expenses are e.g. web hosting, etc.

So those are two good FOSS funding platforms:
1. Liberapay (recurring donations via paypal)
2. OpenCollective (crowd/group payments for bounties?)

**Comment by nguyenhathaitrong** [comment]
I welcome and support this proposal

**Comment by ventoy** [comment]
Thanks!
I will learn more about it.

**Comment by ventoy** [comment]
Just make a [liberapay](https://liberapay.com/Ventoy) acount :)
