### ISSUE TITLE
[issue]: Easy Recovery Essentional for Windows10

### ISSUE THREAD

**Issue by crasadure** [ventoy/Ventoy#1488]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

Ventoy CI #662

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

8gb

### Disk Manufacturer

Virtual Disk (vhd)

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://www.mediafire.com/file/mz43a85z4pag4be/EasyRE_W10.iso/file

### What happened?

Hi @ventoy 

You had added Easy Recovery Essential for Windows11 support to Ventoy in Ventoy [CI #662 release version](https://github.com/ventoy/Ventoy/suites/5551284768/artifacts/179012689)
[https://github.com/ventoy/Ventoy/issues/1481](url)
I tested CI Release version for EasyRE_W11.iso and everthing is OK...

But now, I recognized EasyRE_W10.iso can not booting on CI Release version...I captured a video about my problem
My captured video: https://vimeo.com/685205167

Ventoy last version (v1.0.70 ) was supporting EasyRE_W10.iso but CI Release version can't support this ISO file..
You may be delete necessary codes from Ventoy on CI Release version. Can you check it for me?

Easy Recovery Essentional for Windows10 iso: https://www.mediafire.com/file/mz43a85z4pag4be/EasyRE_W10.iso/file

**Comment by ventoy** [comment]
Are you sure this ISO file boot OK with v1.0.70?  Capture a video about it.

**Comment by crasadure** [comment]
hi @ventoy 
I captured my video about this subject.
video Link: https://vimeo.com/685500288

**Comment by ventoy** [comment]
Is it a special location to put the ISO file in the root of a FAT partition to make it find the ISO file during boot?
Can it work if you put in an exfat or NTFS partition ? or put it under some subdirectory?

![image](https://user-images.githubusercontent.com/59477474/157071248-59175bd3-0ec0-4d93-8d85-f8706b3eb587.png)

**Comment by ventoy** [comment]
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/1950871129

You don't need to put the ISO in the root of a FAT32 partition, exfat/ntfs also works (can also under any subdirectory)

**Comment by crasadure** [comment]
I tested last CI Releaese version...EasyRE_W10.iso and Easy_RE_W11.iso is running perfectly!
Thanks Master 👍

**Comment by Hayquen** [comment]
XIn link download  Easy_RE_W11.iso . Cảm ơn các bạn!
