### ISSUE TITLE
[issue]: FreeBsd 13.0 iso did not boot

### ISSUE THREAD

**Issue by enigma131** [ventoy/Ventoy#1489]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.70

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

16 Go

### Image file download link (if applicable)

https://download.freebsd.org/releases/amd64/amd64/ISO-IMAGES/13.0/FreeBSD-13.0-RELEASE-amd64-dvd1.iso

### What happened?

Get error on boot, like here but it's an ISO file : https://forums.ventoy.net/showthread.php?tid=1992

**Comment by enigma131** [comment]
Checksum is correct. I load it via browser mode, ISO is on HDD and i my USB stick is only 4 Gb.

**Comment by ventoy** [comment]
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/1950871129
https://www.ventoy.net/en/doc_github_ci.html

**Comment by enigma131** [comment]
Well-done, this version is working

**Comment by safocl** [comment]
I have like it problem -- freebsd_13.1_release -- iso and img (memstick) tested.
ERROR 19 again.
