### ISSUE TITLE
[Success Image Report]: Hiren’s BootCD PE x64 (v1.0.2) – ISO

### ISSUE THREAD

**Issue by MJK618** [ventoy/Ventoy#1491]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

ventoy-1.0.70-windows

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

HBCD_PE_x64.iso

### Image file checksum type

MD5

### Image file checksum value

BEC7304FE2EB11DE495B9EA7B73C38AA

### Image file download link (if applicable)

https://www.hirensbootcd.org/files/HBCD_PE_x64.iso

### Test envrionment

HP AMD A9-9420 Radeon R5, 5 COMPUTE CORES, 2C+3G, 3.00 GHz

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
