### ISSUE TITLE
[Success Image Report]: Zorin OS 16 Core 64-bit

### ISSUE THREAD

**Issue by MJK618** [ventoy/Ventoy#1495]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

ventoy-1.0.70-windows

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

Zorin-OS-16-Core-64-bit-r4.iso

### Image file checksum type

SHA256

### Image file checksum value

69e1be7e078c401e7991fff2e8a5f854ed04ebaba7a1b98a74d552644aa9f523

### Image file download link (if applicable)

https://zorin.com/os/download/16/core/

### Test envrionment

HP AMD A9-9420 Radeon R5, 5 COMPUTE CORES, 2C+3G, 3.00 GHz

### More Details?

This image file booted successfully in Ventoy.

I have tried all latest images of Zorin and Zorin Lite (both core and Education) and on both BIOS mode, Overall in legacy mode, booting was slower otherwise everything else worked fine.

**Comment by ventoy** [comment]
Thanks!
