### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by JamieSlome** [ventoy/Ventoy#1496]
Hey there!

I belong to an open source security research community, and a member (@scriptidiot) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by ventoy** [comment]
You can send mail to `admin@ventoy.net`

**Comment by JamieSlome** [comment]
E-mail sent!

Just for reference, you can view the report directly here too:
https://huntr.dev/bounties/04ae0f4b-77a1-42dc-978a-7bb5e6c93356

It is private and only accessible to you! 👍
