### ISSUE TITLE
Unable boot custom Windows 10 ISO

### ISSUE THREAD

**Issue by FadeMind** [ventoy/Ventoy#15]
@chromer030

Via https://uupdump.ml/

you can grab and creating standalone ISO with merged lastest updates from M$. Sadly ISO created via this tool unable boot via ventoy. 

Error:
```
No bootfile found for UEFI!
Maybe the image does not support X64 UEFI!
```
Sample FILE name:
```
19041.207.200409-1713.VB_RELEASE_SVC_PROD1_CLIENTPRO_OEMRET_X64FRE_PL-PL.ISO
```
Based on https://uupdump.ml/selectlang.php?id=1f683f23-c660-4e58-844f-3ef8eff634f9

This is realted with NAME of ISO file or more?

NOTICE ⚠️  ESD original ISO's from M$ 
```
19041.84.200218-1143.vb_release_svc_refresh_clientconsumer_ret_x64fre_pl-pl.iso
```
Boot well.

**Comment by chromer030** [comment]
Your generated ISO , Does it boot in UEFI mode in virtual machines like Virtualbox , QEMU or vmware ??

Generally modifying Microsoft Original ISO files , lead to losing Signatures that needed on UEFI booting ,
Today i tested `Windows 10 AIO 1909 Build 18363.778 April 2020` but also failed on UEFI.

**Comment by FadeMind** [comment]
Boot went fine after creating bootable USB stick via Rufus tool. I have disabled at all Secure Boot on my device.

**Comment by chromer030** [comment]
Thank you very much for reporting , so it should be a BUG in Ventoy.
I hope will be fixed in future versions.

**Comment by FadeMind** [comment]
@chromer030 I resolved this issue. 
Simply RENAME `BIG-LETTERS.ISO` to `small-letters.iso` WINDOWS SETUP
Works like a charm. 
I maded new fresh ISO `19041.208.200417-1904.vb_release_svc_im_clientpro_oemret_x64fre_pl-pl.iso` with only Pro version available. Booted to page wizard disk selecting well.
