### ISSUE TITLE
[issue]: 

### ISSUE THREAD

**Issue by nodswal** [ventoy/Ventoy#1501]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.70

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32gb

### What happened?

I generated a boot ISO from Red Hat satellite server and was hoping this would work.

**Comment by ventoy** [comment]
Can it work?
