### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by NeoakaDarkman** [ventoy/Ventoy#1502]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.70

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

rhel-baseos-9.0-beta-4-x86_64-dvd.iso

### Image file checksum type

SHA256

### Image file checksum value

c097364c1e43dafe6d7e313acd0816a0dc1771f3a82129c30b3e44ad7cf9d16d

### Test envrionment

Medion Akoya E6431 (Skylake)

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
