### ISSUE TITLE
How to make the theme menu of Grub2 display Chinese?

### ISSUE THREAD

**Issue by sjkhsl** [ventoy/Ventoy#1503]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.70

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

256GB

### What happened?

How to make the theme menu of Grub2 display Chinese?
怎么让grub2的主题菜单显示中文？

**Comment by ventoy** [comment]
用个图片说明一下你想哪部分显示中文？

**Comment by ventoy** [comment]
I  close the issue now after 10 days without response.
If you have any update, please reopen the issue.
