### ISSUE TITLE
[Success Image Report]: Hasleo Backup Suite Free WinPE (v2.8)

### ISSUE THREAD

**Issue by crasadure** [ventoy/Ventoy#1506]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.71

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

Hasleo_Backup_Suite_WinPE.iso

### Image file checksum type

MD5

### Image file checksum value

75691E409611C276390820ACEC85A374

### Image file download link (if applicable)

https://www.easyuefi.com/backup-software/backup-suite-free.html

### Test envrionment

Asus M51SN

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
