### ISSUE TITLE
[issue]: 微PE工具箱V2.2镜像无法启动

### ISSUE THREAD

**Issue by StrollStars** [ventoy/Ventoy#1507]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.71

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### What happened?

[WePE_64_V2.2](https://www.wepe.com.cn/download.html)生成iso文件，在1.0.71中无法顺利启动，卡在镜像列表界面，但会弹出一个纯色窗口覆盖在上面。
重新安装1.0.70后，能够顺利启动并使用，因此判断是1.0.71的问题。

**Comment by ventoy** [comment]
71版本这块没改动过，不应该有问题。
你试试先在Ventoy界面上按F7切换到文本模式，然后再选择ISO文件启动试试。

**Comment by StrollStars** [comment]
@StrollStars 重新安装1.0.70后，能够顺利启动并使用，但是一次以后又不行了，我又重新做了一遍，然后又可以了，不知下次还行不行。
我现在有点怀疑是不是兼容性问题，还是在使用过程中对U盘内容有写入？

下次如果不行，我试试F7。

**Comment by ktns01** [comment]
我这里一切正常，1.0.71版本，开启安全启动，无论是MBR模式还是GPT模式都可以正常启动。
或许是U盘或者设备的问题？试试换个U盘或者设备看看有没有问题。

**Comment by StrollStars** [comment]
@ktns01 谢谢回复，我先关了，再观察看看。

**Comment by StrollStars** [comment]
@ventoy F7按了以后，又跳到了图形界面。

不过问题好像解决了，先前是在Win7上制作的，现在整个U盘清空重新在Win10上制作，暂时没有出现问题。

**Comment by StrollStars** [comment]
@ventoy F7按了以后，又跳到了图形界面。

**Comment by ventoy** [comment]
> @ventoy F7按了以后，又跳到了图形界面。

原来是什么界面？ 文本的？ 
F7可以多按几次，它会在图形界面和文本界面之间来回切换。

**Comment by StrollStars** [comment]
@ventoy 一般都是通过图形菜单选择，但我这边无法引导入iso，然后按你的建议按F7，选择菜单项后没能进入iso内容，而是跳回了图形界面。

我发现菜单中的第一项能够顺利进入，但之后的iso无法顺利进入。

**Comment by bigbighill** [comment]
> @ventoy 一般都是通过图形菜单选择，但我这边无法引导入iso，然后按你的建议按F7，选择菜单项后没能进入iso内容，而是跳回了图形界面。
> 
> 我发现菜单中的第一项能够顺利进入，但之后的iso无法顺利进入。

确实有这个情况，把第一个iso删除了就可以顺利启动winpe了

ventoy 1.073

**Comment by StrollStars** [comment]
感谢 @bigbighill 告知，这是mbr方式的问题吗？不过初始安装的时候也没有选择吧？
@ventoy 还请麻烦看一下。

**Comment by mtgq** [comment]
> 感谢 @bigbighill 告知，这是mbr方式的问题吗？不过初始安装的时候也没有选择吧？ @ventoy 还请麻烦看一下。

最后咋解决的，我也是无法启动

**Comment by StrollStars** [comment]
@mtgq 问题并没有解决，尽量用新的方式吧。

**Comment by mtgq** [comment]
> @mtgq 问题并没有解决，尽量用新的方式吧。

好的，感谢
