### ISSUE TITLE
[Success Image Report]: linuxmint-20.3-cinnamon-64bit.iso

### ISSUE THREAD

**Issue by farxhan** [ventoy/Ventoy#1508]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.71

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

linuxmint-20.3-cinnamon-64bit.iso

### Image file checksum type

SHA256

### Image file checksum value

e739317677c2261ae746eee5f1f0662aa319ad0eff260d4eb7055d7c79d10952

### Image file download link (if applicable)

https://mirror.0x.sg/linuxmint-iso/stable/20.3/linuxmint-20.3-cinnamon-64bit.iso

### Test envrionment

Acer Aspire 5 A514-52G (i5 10th gen model)

### More Details?

This image file booted successfully in Ventoy, using UEFI, secure boot, and GPT partition on a 32 GB SanDisk Cruzer Glide USB Flashdisk 3.0.

**Comment by ventoy** [comment]
Thanks!
