### ISSUE TITLE
[Success Image Report]: Void Linux Base 20210930 64-bit

### ISSUE THREAD

**Issue by notjl** [ventoy/Ventoy#1511]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.71

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

void-live-x86_64-20210930.iso

### Image file checksum type

SHA256

### Image file checksum value

45b75651eb369484e1e63ba803a34e9fe8a13b24695d0bffaf4dfaac44783294

### Image file download link (if applicable)

https://alpha.de.repo.voidlinux.org/live/current/void-live-x86_64-20210930.iso

### Test envrionment

ASUS FX505DT laptop

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
