### ISSUE TITLE
[Success Image Report]: Ubuntu Unity 21.10 tested and confirms successfully boots.

### ISSUE THREAD

**Issue by Gander22H** [ventoy/Ventoy#1516]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

Ventoy 1.0.71

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

ubuntu-unity-21.10.iso

### Image file checksum type

MD5

### Image file checksum value

477103a6f6fd6d9631be0b39673d9fe3

### Image file download link (if applicable)

http://linux.darkpenguin.net/distros/ubuntu-unity/21.10/ubuntu-unity-21.10.iso

### Test envrionment

Gateway DV4860 desktop

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
