### ISSUE TITLE
[issue]: /opt/ventoy/VentoyPlugson.sh: line 3: ./tool/ventoy_lib.sh: No such file or directory

### ISSUE THREAD

**Issue by Dialga** [ventoy/Ventoy#1519]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.71

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

8GB

### What happened?

A bug happened! on Arch Linux

```
$ sudo /opt/ventoy/VentoyPlugson.sh /dev/sda
/opt/ventoy/VentoyPlugson.sh: line 3: ./tool/ventoy_lib.sh: No such file or directory
```
Perhaps the VentoyPlugson.sh script should check if ./tool/ventoy_lib.sh is in it's relative directory rather than the current directory?

**Comment by ventoy** [comment]
The package in AUR is not maintained by me.

**Comment by Dialga** [comment]
That's not the issue, ideally VentoyPlugson.sh should get the real path to ventoy_lib.sh regardless of where it's being called from:
```
#!/bin/sh

VENTOY_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
. "$VENTOY_DIR/tool/ventoy_lib.sh"
```

**Comment by ventoy** [comment]
More that one relative paths are used in the script not just this one.
This script is designed to work in the correct directory.
So before you call it, you must cd to the correct directory.

**Comment by ventoy** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/ventoyplugson?h=ventoy-bin
The AUR package of Ventoy has made some wrapper command.
You should call `ventoyplugson`  instead of directly call `VentoyPlugson.sh`.

**Comment by Dialga** [comment]
Still the wrapper would not be needed if the changed above are implemented.
