### ISSUE TITLE
[issue]: support persistent f2fs file system

### ISSUE THREAD

**Issue by Dialga** [ventoy/Ventoy#1520]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.71

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

8GB

### What happened?

```
$ sudo CreatePersistentImg.sh -s 5120 -t f2fs
unsupported file system f2fs
```
f2fs support is available on most modern linux distributions, is better for usb flash drives.

**Comment by ventoy** [comment]
I have no time to support all filesystems.  This script only support XFS and ext4 which are widly used.
The script is simple and you can modify it to support more filesystems as you want if needed.

**Comment by Dialga** [comment]
Can I submit a PR to add support? I'm testing it now.

**Comment by deathtrip** [comment]
so... how did the testing go?

**Comment by Dialga** [comment]
Didn't work, I went the direct route with dd.
