### ISSUE TITLE
[Success Image Report]: helloSystem 0.7.0 (FreeBSD)

### ISSUE THREAD

**Issue by probonopd** [ventoy/Ventoy#1521]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

11160727

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

hello-0.7.0_0G160-FreeBSD-13.0-amd64.iso

### Image file checksum type

MD5

### Image file checksum value

8bae8b7cc0ad973897b9687ee5d58058

### Image file download link (if applicable)

https://github.com/helloSystem/ISO/releases/download/r0.7.0/hello-0.7.0_0G160-FreeBSD-13.0-amd64.iso

### Test envrionment

Acer Revo One RL85

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
