### ISSUE TITLE
[issue]: disable timeout on ventoy_vhdboot

### ISSUE THREAD

**Issue by alex2844** [ventoy/Ventoy#1523]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.71

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

100

### What happened?

How to disable timeout for plugin_vhdboot?

![image](https://user-images.githubusercontent.com/18526177/159140960-807e2b56-b19a-4074-b198-a505ebfe97bf.png)

**Comment by ventoy** [comment]
Try this version:
[ventoy_vhdboot.zip](https://github.com/ventoy/Ventoy/files/8311379/ventoy_vhdboot.zip)

**Comment by alex2844** [comment]
Started getting a blue screen.
Using qemu works.

I also noticed that after the blue screen, the disk section where the images for ventoy are located is write-protected.

![image](https://user-images.githubusercontent.com/18526177/159508919-140bd342-4de3-4588-a6be-9e623798f363.png)

**Comment by ventoy** [comment]
Does it OK (no blue screen and no write protect) if  you use old release of ventoy_vhdboot plugin (not the test version I upload above) ?

**Comment by alex2844** [comment]
A couple of days ago, when the last time I loaded windows, it worked fine.
Now I tried the test version, there is no timeout, but I get a blue screen. I rolled back to the previous version - again the blue screen.
Launched using qemu - works.
I start using ventoy - does not work.

**Comment by alex2844** [comment]
Created a new vhd disk, installed windows
Copied the latest stable version of vhdiso
Doesn't work (vhd boot initialization failed). I don't understand what has changed. A couple of days the computer did not turn on, what has changed - I do not understand. It used to work, but with timeouts

**Comment by alex2844** [comment]
I copied the image to another partition - it works.
Does not work if the image is on a partition labeled Ventoy (NTFS)

**Comment by alex2844** [comment]
After formatting to exFAT it works fine.

https://github.com/ventoy/Ventoy/issues/1523#issuecomment-1073257664
There is no more timeout. Thanks.
