### ISSUE TITLE
[issue]: Ventoy can not boot venom iso

### ISSUE THREAD

**Issue by willzyx-hub** [ventoy/Ventoy#1526]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.71

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

16GB

### Disk Manufacturer

Sandisk

### What happened?

Hello Ventoy Team i experienced some issue when booting Venom Linux iso... Ventoy refused to boot the iso... It just blackscreen and nothing happened any idea what causing this issue ?

**Comment by willzyx-hub** [comment]
And what is the possible solution ? Did i need to modify the iso file to make that compatible with ventoy ?

**Comment by ventoy** [comment]
Can other ISO files boot OK in the same computer? (e.g.  Ubuntu/CentOS/Arch ...)

**Comment by willzyx-hub** [comment]
> Can other ISO files boot OK in the same computer? (e.g. Ubuntu/CentOS/Arch ...)

Yes but not Venom i wanna to make it work...

**Comment by ventoy** [comment]
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/2021545280
https://www.ventoy.net/en/doc_github_ci.html

**Comment by willzyx-hub** [comment]
> Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/2021545280 https://www.ventoy.net/en/doc_github_ci.html

Hey Thanks bro it's worked on my system...
