### ISSUE TITLE
[issue]: Execute bit missing on some tool/*/Ventoy2Disk.* GUI files

### ISSUE THREAD

**Issue by Lantizia** [ventoy/Ventoy#1530]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.71

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

Irrelevant

### What happened?

As my computer (which runs Ubuntu) is shared by multiple users... we prefer installing software globally so we can all use it... rather than keeping it to ourselves in our home directories.

So we install Ventoy to... /opt/ventoy/ 

```
wget https://github.com/ventoy/Ventoy/releases/download/v1.0.71/ventoy-1.0.71-linux.tar.gz
sudo tar -zxof ventoy-*-linux.tar.gz --xform 's/\([^-]*\)[^\/]*/\L\1/' -C /opt
```

**If you run this as a regular user for the first time...**
`/opt/ventoy/VentoyGUI.$(uname -i)`

A polkit dialogue appears to inform you Ventoy needs super user privileges... and after typing your password in... you find the GUI does not appear.  

**But if you --then-- run it --with-- sudo...**
`sudo /opt/ventoy/VentoyGUI.$(uname -i)`

The GUI now appears!

**But if you go back to running it --without-- sudo...** 
`/opt/ventoy/VentoyGUI.$(uname -i)`

The GUI now appears!  Wait, WHAT?  It now works, just fine!

What I think is happening, is that when ran with sudo... it has the power to chmod +x the correct GUI file (from /opt/ventoy/tool/[arch]/Ventoy2Disk.[ui])... so once its done that... it is done and will work fine without sudo afterwards.

**Essentially this does the same...** 
`sudo chmod +x /opt/ventoy/tool/*/Ventoy2Disk.*`

Could future downloads of the **ventoy-[ver]-linux.tar.gz** file possibly include these files being already marked as executable?

**Comment by ventoy** [comment]
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/2037524747
https://www.ventoy.net/en/doc_github_ci.html

**Comment by Lantizia** [comment]
> If you just only run /opt/ventoy/VentoyGUI.$(uname -i) two times, will the GUI appear? (with no sudo)

No if you only run it without sudo (even 2 or more times) it will never appear.

**Comment by ventoy** [comment]
I  add the execute bit in the above CI release, you can try it.

**Comment by Lantizia** [comment]
> Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/2037524747 https://www.ventoy.net/en/doc_github_ci.html

Yeah that's worked fine, thank you :)

Also if anyone is curious, this is a quick way of adding Ventoy to your desktop environments main menu/screen...
`echo -e '[Desktop Entry]\nName=Ventoy\nExec=/opt/ventoy/VentoyGUI.'$(uname -i)'\nIcon=/opt/ventoy/WebUI/favicon.ico\nType=Application\nCategories=System' | sudo tee /usr/local/share/applications/ventoy.desktop`
