### ISSUE TITLE
[issue]: Optionally store preferences in users own home/profile

### ISSUE THREAD

**Issue by Lantizia** [ventoy/Ventoy#1531]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.71

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

Irrelevant

### What happened?

Many of the computers I use are shared by multiple users... so we prefer installing software globally so we can all use it... rather than keeping it to ourselves in our home directories.

This means on Windows and Linux systems the path to the Ventoy software is usually either...

- **Linux:** /opt/ventoy/
- **Windows:** C:\Program Files\Ventoy\

I noticed that the Ventoy2Disk.ini file stores the preferences of the user.  However because it stores those preferences in the directory you installed Ventoy to... it only stores the preferences of the last person who used the software.

Ideally it'd be better for the config file to be placed in...

- **Linux:** ~/.config/ventoy/Ventoy2Disk.ini
- **Windows:** %AppData%/ventoy/Ventoy2Disk.ini

Maybe this could be an optional extra parameter you can pass to VentoyGUI?

- **Linux:** /opt/ventoy/VentoyGUI.$(uname -i)  --userconfig 
- **Windows:** C:\Program Files\Ventoy\Ventoy2Disk.exe /userconfig

That way each user of a multi-user system (either Linux or Windows) can have their own Ventoy preferences stored in their own users home/profile directory.

**Comment by ventoy** [comment]
If your Ubuntu system contains `XDG_CACHE_HOME`  and `XDG_CONFIG_HOME`  environment variables, you can try  `/opt/ventoy/VentoyGUI.$(uname -i)   --xdg`
Then the logfile will be at `$XDG_CACHE_HOME/ventoy.log`  and the ini file will be at `$XDG_CONFIG_HOME/Ventoy2Disk.ini`

**Comment by Lantizia** [comment]
It doesn't appear as though either of those variables are set on my systems.

Is --xdg documented anywhere?  I couldn't find a way of asking the program to show me the possible syntax.  Presumably --xdg isn't an answer for Windows users either?

**Comment by Lantizia** [comment]
Ah...

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

Apparently if $XDG_CACHE_HOME and $XDG_CONFIG_HOME are unset then applications should default to using $HOME/.cache and $HOME/.config respectively.

So for 99.99% of users this would mean...

~/.config/Ventoy2Disk.ini
~/.cache/ventoy.log

Which isn't terrible, but probably nicer form to put them into their own subdirectories like 90% of other things do.

~/.config/ventoy/Ventoy2Disk.ini
~/.cache/ventoy/ventoy.log

But again I'm not sure if this issue exists on Windows too and --xdg doesn't sound like it's an answer there.  Not that I care about Windows very much.

**Comment by ventoy** [comment]
--xdg if only for linux version.
You can also try  `/opt/ventoy/VentoyGUI.$(uname -i)    -i  $HOME/.config/Ventoy2Disk.ini  -l  $HOME/.cache/ventoy.log  `

**Comment by Lantizia** [comment]
Is --xdg, -l, and -i documented anywhere (anywhere but in the code)?

Curious what other options there might be.

**Comment by ventoy** [comment]
Not documented now,  can the  `-i` and `-l`  option work?

**Comment by Lantizia** [comment]
OK so I've done some tests...

**If `XDG_CACHE_HOME` and `XDG_CONFIG_HOME` are unset, then using the --xdg option...** 

`/opt/ventoy/VentoyGUI.$(uname -i) --xdg`

Then its like it just ignores the option... it just makes `Ventoy2Disk.ini` and `log.txt` (both owned by `root`) in `/opt/ventoy` as normal.

So this needs to default `XDG_CACHE_HOME` to `$HOME/.cache` and `XDG_CONFIG_HOME` to `$HOME/.config` if they are unset.

**If `XDG_CACHE_HOME` and `XDG_CONFIG_HOME` are explicitly set to [what should be the the default values](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), then using the --xdg option...** 

`XDG_CACHE_HOME=$HOME/.cache XDG_CONFIG_HOME=$HOME/.config /opt/ventoy/VentoyGUI.$(uname -i) --xdg`

Then it does make them in the correct locations, however `log.txt` is now called `ventoy.log` and `Ventoy2Disk.ini` is owned by `root` and shouldn't be.

```
user@pc:~$ ls -lah .cache/ventoy.log .config/Ventoy2Disk.ini
-rw-rw-r-- 1 user user 15K Mar 26 08:31 .cache/ventoy.log
-rw-r--r-- 1 root root 64  Mar 26 08:31 .config/Ventoy2Disk.ini
```

**If `XDG_CACHE_HOME` and `XDG_CONFIG_HOME` are set to paths that do not exist, then using the --xdg option...** 

`XDG_CACHE_HOME=$HOME/.cache/ventoy XDG_CONFIG_HOME=$HOME/.config/ventoy /opt/ventoy/VentoyGUI.$(uname -i) --xdg`

Then confusingly the program opens, but no files are created and it doesn't remember any preferences if you close it and re-open it.  It needs to be able to make missing parent directories first.

**If the file paths to the `ini` and `log` files are explicitly set to what their defaults would normally be (if --xdg was used and worked) using the -i and -l options...** 

`/opt/ventoy/VentoyGUI.$(uname -i) -i $HOME/.config/Ventoy2Disk.ini -l $HOME/.cache/ventoy.log`

Then you get the same problem as before where `Ventoy2Disk.ini` is owned by `root` and shouldn't be.

```
user@pc:~$ ls -lah .cache/ventoy.log .config/Ventoy2Disk.ini
-rw-rw-r-- 1 user user 15K Mar 26 08:55 .cache/ventoy.log
-rw-r--r-- 1 root root 64  Mar 26 08:55 .config/Ventoy2Disk.ini
```

**If the file paths to the `ini` and `log` files are explicitly set to paths that do not exist using the -i and -l options...** 

`/opt/ventoy/VentoyGUI.$(uname -i) -i $HOME/.config/ventoy/Ventoy2Disk.ini -l $HOME/.cache/ventoy/ventoy.log`

Then you get the same problem as before where the program opens, but no files are created and it doesn't remember any preferences if you close it and re-open it.  Again it needs to be able to make missing parent directories first.

Hope this helps :)

**Also**

Before I forget to say... Ventoy is an incredibly useful program and it's most appreciated by myself, [our local Linux User Group](https://staffslug.org.uk) and the company I work at.  I've already added a regular monthly donation via Liberapay.

Thank you!

**Comment by ventoy** [comment]
@Lantizia 
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/2113767268
https://www.ventoy.net/en/doc_github_ci.html

**Comment by ventoy** [comment]
@Lantizia 
Please try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/2114274326
https://www.ventoy.net/cn/doc_github_ci.html

**Comment by ventoy** [comment]
@Lantizia  any update?

**Comment by Lantizia** [comment]
Sorry, busy week :)

I've ran the same tests again (this time against CI #730).

Only the first scenario isn't working correctly now.

Test results...

**[NOT FIXED] When `XDG_CACHE_HOME` & `XDG_CONFIG_HOME` are unset (which is normal and the default for most Linux distributions),  then using the --xdg option...** 

`/opt/ventoy/VentoyGUI.$(uname -i) --xdg`

Then `Ventoy2Disk.ini` and `log.txt` are both created (owned by `root`) in `/opt/ventoy`... 

```
user@pc:~$ ls -lah /opt/ventoy/log.txt /opt/ventoy/Ventoy2Disk.ini
-rw-r--r--  1 root root 7.6K Apr 19 17:06 log.txt
-rw-r--r--  1 root root   64 Apr 19 17:06 Ventoy2Disk.ini
```

But instead it should consider...
-  an unset `XDG_CACHE_HOME` to **AT LEAST** be `$HOME/.cache` (but `$HOME/.cache/ventoy` is better and common practice to avoid namespace collisions)
-  an unset `XDG_CONFIG_HOME` to **AT LEAST** be `$HOME/.config` (but `$HOME/.config/ventoy` is better and common practice to avoid namespace collisions)

This is due to what is written [in the freedesktop XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)...

>  $XDG_CACHE_HOME defines the base directory relative to which user-specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used. 

>  $XDG_CONFIG_HOME defines the base directory relative to which user-specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used. 

**[FIXED] If `XDG_CACHE_HOME` and `XDG_CONFIG_HOME` are manually set to the values that Ventoy should be using by default, then using the --xdg option...** 

`XDG_CACHE_HOME=$HOME/.cache XDG_CONFIG_HOME=$HOME/.config /opt/ventoy/VentoyGUI.$(uname -i) --xdg`

Then it creates `ventoy.log` (which I assume is the same as `log.txt`) in ~/.cache and `Ventoy2Disk.ini` in ~/.config and now both of them have the correct ownership of the user who is running the program (not root).

```
user@pc:~$ ls -lah .cache/ventoy.log .config/Ventoy2Disk.ini
-rw-rw-r--   1 user user  30K Apr 19 17:12  ventoy.log
-rw-rw-r--   1 user user   64 Apr 19 17:12  Ventoy2Disk.ini
```

**[FIXED] If `XDG_CACHE_HOME` and `XDG_CONFIG_HOME` are set to paths that do not exist, then using the --xdg option...** 

`XDG_CACHE_HOME=$HOME/.cache/ventoy XDG_CONFIG_HOME=$HOME/.config/ventoy /opt/ventoy/VentoyGUI.$(uname -i) --xdg`

It now properly creates the missing directories and makes the files with the correct ownerships within them.

```
user@pc:~$ ls -lah .cache/ventoy/ventoy.log .config/ventoy/Ventoy2Disk.ini
-rw-rw-r-- 1 user user 15K Apr 19 17:26 .cache/ventoy/ventoy.log
-rw-rw-r-- 1 user user  64 Apr 19 17:26 .config/ventoy/Ventoy2Disk.ini
```

**[FIXED] If the file paths to the `ini` and `log` files are explicitly set to what their defaults would normally be (if --xdg was used and worked) using the -i and -l options...** 

`/opt/ventoy/VentoyGUI.$(uname -i) -i $HOME/.config/Ventoy2Disk.ini -l $HOME/.cache/ventoy.log`

Then it's now fixed and the files are made in the right place with the right permissions.

```
user@pc:~$ ls -lah .cache/ventoy.log .config/Ventoy2Disk.ini
-rw-rw-r-- 1 user user 15K Apr 19 17:30 .cache/ventoy.log
-rw-rw-r-- 1 user user  64 Apr 19 17:30 .config/Ventoy2Disk.ini
```

**[FIXED] If the file paths to the `ini` and `log` files are explicitly set to paths that do not exist using the -i and -l options...** 

`/opt/ventoy/VentoyGUI.$(uname -i) -i $HOME/.config/ventoy/Ventoy2Disk.ini -l $HOME/.cache/ventoy/ventoy.log`

Then it's now fixed, the missing directories are made and the files are made in the right place with the right permissions.

```
user@pc:~$ ls -lah .cache/ventoy/ventoy.log .config/ventoy/Ventoy2Disk.ini
-rw-rw-r-- 1 user user 15K Apr 19 17:35 .cache/ventoy/ventoy.log
-rw-rw-r-- 1 user user  64 Apr 19 17:35 .config/ventoy/Ventoy2Disk.ini
```

**Comment by Lantizia** [comment]
Also it might be an idea for Ventoy to assume the argument --xdg when the application has been started by an unprivileged (non-root) user (e.g. via pkexec, sudo, gksu, etc...).  But that's up to you.

**Comment by ventoy** [comment]
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/2215538487

**Comment by Lantizia** [comment]
Well the only thing I've re-tested (which now works) is that --xdg now properly assumes `XDG_CACHE_HOME` to be `$HOME/.cache` when unset... and `XDG_CONFIG_HOME` as `$HOME/.config` when unset.

**I still say that a subdirectory of 'ventoy' under each location is a better default.**

**Reasons...**

1. If your application (later on) wants to store more than one cache or config file... then it's easier to do this without potentially causing conflicts with the files of other applications if they are in their own subdirectory.  For example instead of saving as 'ventoy.log'... use 'log.txt' in the 'ventoy' subdirectory ('log.txt' is also the same filename used when not using `--xdg`).
2. Making that directory as an agreed namespace for the creation of files (on both Linux and Windows) is good future proofing for future releases to find all ventoy-related files easily.
3. On Linux `$XDG_CONFIG_HOME` is the equivalent of Window's `%AppData%` or `%LocalAppData%`... and although you can put files directly into those locations too... again it isn't often seen for the same reasons.
4. Applications on my system seem to prefer making their own subdirectory in these kinds of locations.  For example this is the contents of my ~/.cache and ~/.config and you can see most do seem to make a directory (likely for these reasons)...

**e.g. In my $HOME/.cache there are only 8 files, but there are 57 directories (files shown in bold)**
- 'Android Open Source Project'
-  atril
-  audacious
-  babl
-  **blueman-applet-1000**
-  chromium
-  dconf
- 'disruptive innovations sarl'
-  doc
-  epiphany
-  **event-sound-cache.tdb.7421e0gf44054492b610c639da1cf982.x86_64-pc-linux-gnu**
-  favicons
-  filezilla
-  flatpak
-  fontconfig
-  gegl-0.3
-  g-ir-scanner
-  gnome-software
-  go-build
-  Google
-  google-chrome
-  gstreamer-1.0
-  ibus
-  icedtea-web
-  **icon-cache.kcache**
-  **indicator-applet-complete.log**
-  **indicator-applet.log**
-  inkscape
-  JNA
-  keepassxc
-  kio_http
-  konqueror
- **'ksycoca5_en-GB_2AC51e3kZ80KjSPkXfJavl0iPwg='**
-  mate
-  matplotlib
-  mesa_shader_cache
-  microsoft-edge-dev
-  **motd.legal-displayed**
-  mozilla
-  obexd
-  opera
-  peek
-  pip
-  PrivateInternetAccess
-  Python-Eggs
-  **qt_compose_cache_little_endian_7401e5bb22039892b123c639ec5de982**
-  qtshadercache
-  qtshadercache-x86_64-little_endian-lp64
-  remmina
-  shutter
-  simple-scan
-  spotify
-  TeamViewer
-  thumbnails
-  thunderbird
-  transmission
-  ubuntu-mate-welcome
-  ubuntu-report
-  update-manager-core
-  vlc
-  vmware
-  wine
-  winetricks
-  yelp
-  zoom

**e.g. In my $HOME/.config there are only 11 files, but there are 73 directories (files shown in bold)**
-  abiword
- 'Android Open Source Project'
-  atril
-  audacious
-  autostart
-  blender
-  brasero
-  caja
-  chromium
- 'Code Industry'
-  dconf
-  deluge
-  discord
-  dummydroid
-  enchant
-  epiphany
-  filezilla
-  folder-color
-  freerdp
-  gandi
-  ghb
-  ghostwriter
-  goa-1.0
-  Google
-  google-chrome
-  gtk-2.0
-  gtk-3.0
-  hexchat
-  higan
-  htop
-  ibus
-  icedtea-web
-  inkscape
- 'IPFS Desktop'
-  keepassxc
-  **konq_history**
-  **konquerorrc**
-  lftp
-  libreoffice
-  lottanzb
-  mate
-  **mate_dock_applet.conf**
-  mate-menu
-  mate-session
-  matplotlib
-  menus
-  Microsoft
-  microsoft-edge-dev
-  **mimeapps.list**
-  **monitors.xml**
-  Nextcloud
-  nzb
-  obs-studio
-  opera
-  plank
-  pluma
-  **pmbootstrap.cfg**
-  PrivateInternetAccess
-  pulse
-  **QtProject.conf**
- 'Qtrac Ltd.'
-  raccoon
-  remmina
-  session
-  skypeforlinux
-  Slack
-  smplayer
-  solaar
-  spotify
-  Synology
-  teamviewer
-  tilda
-  transmission
-  **Trolltech.conf**
-  ubuntu-mate
- 'Unknown Organization'
-  update-notifier
-  **user-dirs.dirs**
-  **user-dirs.locale**
-  vlc
-  wireshark
-  xnviewmp
-  yelp
-  **zoomus.conf**

**Comment by Lantizia** [comment]
Also do Windows users need to pass some argument similar to `--xdg` to get it to use `%AppData%` ?

If **yes** then that whatever that argument is... it makes sense to merge it with the `--xdg` argument as they essentially do the same thing. 

If **no** and the Ventoy on Windows uses `%AppData%` automatically... then it seems odd that Linux is getting different treatment?

**Comment by ventoy** [comment]
I add `ventoy` directory in this CI release:  https://github.com/ventoy/Ventoy/actions/runs/2217645319

Windows version does not support --xdg option. May because most Windows users only have one account in the system and it's simpler to decompress the zip and run it.
The code for Windows and Linux version is completely different and I have no plan to add this in Windows version in the near future.

**Comment by ventoy** [comment]
@Lantizia 
You can test with the latest 1.0.74 release.

**Comment by ventoy** [comment]
You can register in the official forums https://forums.ventoy.net/

**Comment by ventoy** [comment]
The latest release should have fixed it.
