### ISSUE TITLE
[issue]: So many stale language PRs

### ISSUE THREAD

**Issue by adrian5** [ventoy/Ventoy#1532]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.71

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### Disk Manufacturer

Ventoy Corp

### What happened?

You have so many open language fixes that went stale, and some of them are probably a duplication of effort. What's the issue with accepting them?

If they can no longer be merged you should close them (and ideally inform the user why). And if you're weary of accepting such contributions in general, you should make that clear in your README.

* [#486](https://github.com/ventoy/Ventoy/pull/486)
* [#494](https://github.com/ventoy/Ventoy/pull/494)
* [#506](https://github.com/ventoy/Ventoy/pull/506)
* [#542](https://github.com/ventoy/Ventoy/pull/542)
* [#705](https://github.com/ventoy/Ventoy/pull/705)
* [#762](https://github.com/ventoy/Ventoy/pull/762)
* [#955](https://github.com/ventoy/Ventoy/pull/955)
* [#1100](https://github.com/ventoy/Ventoy/pull/1100)
* [#1425](https://github.com/ventoy/Ventoy/pull/1425)
* [#1113](https://github.com/ventoy/Ventoy/pull/1113)
* [#1124](https://github.com/ventoy/Ventoy/pull/1124)
* [#1440](https://github.com/ventoy/Ventoy/pull/1140)
* [#1442](https://github.com/ventoy/Ventoy/pull/1482)
* [#1484](https://github.com/ventoy/Ventoy/pull/1484)

**Comment by ventoy** [comment]
I have processed all.

**Comment by adrian5** [comment]
Thank you!
