### ISSUE TITLE
[issue]: Ventoy and other multiboot projects (grub2fm, aioboot, etc)

### ISSUE THREAD

**Issue by abdullah-erturk** [ventoy/Ventoy#1533]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.71

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

1024

### Disk Manufacturer

Sandisk

### Image file checksum (if applicable)

No.

### What happened?

Ventoy is a nice project but I want to use it with Grub2FM.

The Grub2FM project has support for automatic switching to Ventoy by default.

But Ventoy project is not friendly at all with other boot managers (grub2fm, aioboot, etc)

Can you work on this?

For example, if Grub2FM is installed on another part of the Ventoy installed disk, can Ventoy automatically find and boot these Grub2FM files?

This feature is available in Grub2FM's default settings.

Why not Ventoy too?

**Comment by ventoy** [comment]
For Grub2FM, you can just put the `grubfm_multiarch.iso` in Ventoy and boot it from Ventoy if needed. You don't need to install it.
For other boot-loaders, you need to write custom grub2 script  https://www.ventoy.net/en/plugin_grubmenu.html

**Comment by abdullah-erturk** [comment]
Okay, I'll use it as you say, but I need your help with something.

I need to create a hotkey for grubfm_multiarch.iso because my disk is too full and I don't want to search for it.

What code should I write in the ventoy_grub.cfg file so that I can boot the grubfm_multiarch.iso file in both efi and mbr mode?

Thanks in advance for your help...

**Comment by abdullah-erturk** [comment]
chainloader (hd1,msdos1)/grubfm_multiarch.iso
iso_common_menuentry

This code works but if you have a better suggestion that would be too :)
