### ISSUE TITLE
[issue]: Disposable VTOY_DEFAULT_IMAGE

### ISSUE THREAD

**Issue by alex2844** [ventoy/Ventoy#1537]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.72

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64GB

### What happened?

How to reboot from one OS to another OS without resetting the VTOY_DEFAULT_IMAGE value?

Previously, let's say I have Windows running, I could specify where I should boot using cmd
bcdedit.exe /set {fwbootmgr} bootsequence %guid% /addfirst
The same thing with linux, you can reboot into another OS.

Now windows is installed not on a physical disk, but in the image ... vhd
How to do the same but using ventoy ?

I'm sorry for my English, I'm translating through google translate

**Comment by ventoy** [comment]
I don't think you can achieve this except that modify the ventoy.json in one OS before reboot it.

**Comment by alex2844** [comment]
@ventoy 

Tell me where to see the list of commands that can be used in grub.cfg.
/VTOYEFI/grub/i386-pc/command.lst ?
Interested in rm, wget, curl commands

**Comment by ventoy** [comment]
`rm/wget/curl` are commands for Linux OS, so none of them can be used in grub environment.
For grub2 commands you can refer: https://www.gnu.org/software/grub/manual/grub/grub.html#Commands
But before use them you must known what you are doing.
