### ISSUE TITLE
[Success Image Report]: Win10 x86 on a IA-32 UEFI device

### ISSUE THREAD

**Issue by a5a5aa555oo** [ventoy/Ventoy#1541]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.72

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

Win10_21H2_Chinese(Traditional)_x32.iso

### Image file checksum type

SHA256

### Image file checksum value

209040E83F40629F102DF41BE0AD76136A16CB2BC0FE188A181939B427589CEC

### Image file download link (if applicable)

Downloaded from Microsoft Official website

### Test envrionment

Genuine GenPad E10T3W

### More Details?

This image file booted successfully on a IA-32 UEFI device. (No CSM)

**Comment by ventoy** [comment]
Thanks!
