### ISSUE TITLE
[Success Image Report]: Ubuntu 20.04.4 on a IA-32 UEFI device

### ISSUE THREAD

**Issue by a5a5aa555oo** [ventoy/Ventoy#1542]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.72

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

ubuntu-20.04.4-desktop-amd64.iso

### Image file checksum type

SHA256

### Image file checksum value

f92f7dca5bb6690e1af0052687ead49376281c7b64fbe4179cc44025965b7d1c

### Image file download link (if applicable)

https://ftp.udx.icscoe.jp/Linux/ubuntu-releases/20.04.4/ubuntu-20.04.4-desktop-amd64.iso

### Test envrionment

Genuine GenPad E10T3W

### More Details?

This image file booted successfully on a IA-32 UEFI device.

**Comment by ventoy** [comment]
Thanks!
