### ISSUE TITLE
[Success Image Report]: Debian 11.3.0 on a IA-32 UEFI device

### ISSUE THREAD

**Issue by a5a5aa555oo** [ventoy/Ventoy#1543]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.72

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

firmware-11.3.0-amd64-netinst.iso

### Image file checksum type

SHA256

### Image file checksum value

5c1edff910d7c104e6a5d9b7b8be65e5908c1ee76a59a9a49ca98ee73d8eda37

### Image file download link (if applicable)

https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/current/amd64/iso-cd/firmware-11.3.0-amd64-netinst.iso

### Test envrionment

Genuine GenPad E10T3W

### More Details?

This image file which is Debian 13.1.0 with none-free firmwares booted successfully on a IA-32 UEFI device.

**Comment by ventoy** [comment]
Thanks!
