### ISSUE TITLE
[Success Image Report]: Clonezilla 2.8.1-12 on a IA-32 UEFI device

### ISSUE THREAD

**Issue by a5a5aa555oo** [ventoy/Ventoy#1544]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.72

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

clonezilla-live-2.8.1-12-amd64.iso

### Image file checksum type

SHA256

### Image file checksum value

64835f5f44c76d9978b265aaaeb4ed967884593e0665a723681cf02c994cd33f

### Image file download link (if applicable)

https://sourceforge.net/projects/clonezilla/files/clonezilla_live_stable/2.8.1-12/clonezilla-live-2.8.1-12-amd64.iso/download

### Test envrionment

Genuine GenPad E10T3W

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
