### ISSUE TITLE
[Success Image Report]: Xubuntu 20.04.4 on a IA-32 UEFI device

### ISSUE THREAD

**Issue by a5a5aa555oo** [ventoy/Ventoy#1546]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.72

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

xubuntu-20.04.4-desktop-amd64.iso

### Image file checksum type

SHA256

### Image file checksum value

3265c2a2d8393c92452cff2cc0606c3d6eb326f11b0b435e47b841ffd73b37a5

### Image file download link (if applicable)

http://ubuntutym2.u-toyama.ac.jp/xubuntu/20.04/release/xubuntu-20.04.4-desktop-amd64.iso

### Test envrionment

Genuine GenPad E10T3W

### More Details?

This image file booted successfully on a IA-32 UEFI device.

**Comment by ventoy** [comment]
Thanks!
