### ISSUE TITLE
[issue]: Specify menu_tip per theme

### ISSUE THREAD

**Issue by ehawman-rosenberg** [ventoy/Ventoy#1547]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.72

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### What happened?

No bug happened!

I wanted to bring an "issue" requesting that we have per-theme position options in the menu_tip plugin (or allow setting the position in the "theme" plugin and set menu_tip position setting to "theme" with failover to our default values).

Something like this:  
![image](https://user-images.githubusercontent.com/81652082/161125623-56a05116-31af-47d0-96f8-d9edd5c0de53.png)

Then in the theme plugin, allow specifying that for file 1, the menu_tip position is `31,12,blue` or something like that. Maybe even expand "file" into a list of dicts with "path", "menu_tip_X", "menu_tip_Y", "menu_tip_color" as the keys.

Why? Because different themes have different locations that work and decidedly don't work for rendering tooltips. If we could set per-theme positions it would really help.

It would be nice if we could borrow existing-but-unused label locations (like the commonly used `progress_bar`) somehow. Not sure how that would work exactly.

**Comment by ventoy** [comment]
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/2077245369
https://www.ventoy.net/en/doc_github_ci.html

Set configuration in `theme.txt` as follows:

![image](https://user-images.githubusercontent.com/59477474/161276289-69c3d873-42b8-45b8-9662-e888d85b7ed0.png)

**Comment by ehawman-rosenberg** [comment]
This works perfectly. Thank you!

That said, given that menu_tip is a Ventoy thing, not a GRUB thing, is it possible to store these values in `ventoy.json` and inject them into the appropriate `theme.txt` just before loading?

**Comment by ventoy** [comment]
The value in `ventoy.json` is the global default value and you can overwrite it in the `theme.txt` for per-theme.
This is a more reasonable and much more easier method.
New defination in `ventoy.json` need a lot of work (the VentoyPlugson webpage/code/exe/sh also need to modify beside the Ventoy grub code) 
Most of the users don't use custom theme or only use one custom theme, so the default value in `ventoy.json` is enough for them.

**Comment by ehawman-rosenberg** [comment]
I totally forgot to reply!

Makes sense to me! Thanks again 😄
