### ISSUE TITLE
[Success Image Report]: Android-x86 on a IA-32 UEFI device

### ISSUE THREAD

**Issue by a5a5aa555oo** [ventoy/Ventoy#1548]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.72

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

android-x86-9.0-r2.iso

### Image file checksum type

SHA256

### Image file checksum value

91cedb534ba095a0c9b3eceede4147967fd27beea9bba640776f787dc3555021

### Image file download link (if applicable)

https://sourceforge.net/projects/android-x86/files/Release%209.0/android-x86-9.0-r2.iso/download

### Test envrionment

Genuine GenPad E10T3W

### More Details?

This image file booted successfully on a IA-32 UEFI device.

**Comment by ventoy** [comment]
Thanks.
