### ISSUE TITLE
[Success Image Report]: Android-86 x86_64 on a IA-32 UEFI device

### ISSUE THREAD

**Issue by a5a5aa555oo** [ventoy/Ventoy#1549]
### Official Website List

- [ ] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.72

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

android-x86_64-9.0-r2.iso

### Image file checksum type

SHA256

### Image file checksum value

f7eb8fc56f29ad5432335dc054183acf086c539f3990f0b6e9ff58bd6df4604e

### Image file download link (if applicable)

https://sourceforge.net/projects/android-x86/files/Release%209.0/android-x86_64-9.0-r2.iso/download

### Test envrionment

Genuine GenPad E10T3W (IA-32 UEFI w/o CSM)

### More Details?

This image file is in the list already but not in the "IA32 UEFI Support" list, so I report it again.

**Comment by ventoy** [comment]
Thanks.
