### ISSUE TITLE
[Success Image Report]: GParted Live 1.4.0-1-amd64

### ISSUE THREAD

**Issue by unit511** [ventoy/Ventoy#1551]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.72

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

gparted-live-1.4.0-1-amd64.iso

### Image file checksum type

SHA256

### Image file checksum value

4297227b6b47b4b9e63b2ce7c07f4b0fb934bd7de66b4dba73531b3b0307180d

### Image file download link (if applicable)

https://downloads.sourceforge.net/gparted/gparted-live-1.4.0-1-amd64.iso

### Test envrionment

QEMU/KVM

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
