### ISSUE TITLE
fedora 35 cannot be boot by Ventoy 1.0.71&1.0.72 but can be boot successfully by Ventoy 1.0.64[issue]: 

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#1553]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.72

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://download.fedoraproject.org/pub/fedora/linux/releases/35/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-35-1.2.iso

### What happened?

A bug happened!
fedora 35 cannot be boot by Ventoy 1.0.71&1.0.72 but can be boot successfully by Ventoy 1.0.64

**Comment by ventoy** [comment]
What is the exactly error?  Some photo will be better.

**Comment by 1457384613gh** [comment]
> What is the exactly error? Some photo will be better.

屏幕为黑色背景，当中显示一个白色的 `_`，并没有进入 ISO的 grub。

**Comment by ventoy** [comment]
Try grub2 mode:  https://www.ventoy.net/en/doc_grub2boot.html

**Comment by francois072** [comment]
I have the same problem. I tried GRUB2 mode, but keep getting the same error.

![Uploading 20220415_021452.jpg…]()

**Comment by francois072** [comment]
The problem is the remounting of the iso option in the plugins. Disabling it causes Fedora to boot successfully.

**Comment by ventoy** [comment]
@1457384613gh 
@francois072 
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/2177016950
https://www.ventoy.net/en/doc_github_ci.html

**Comment by francois072** [comment]
Please mark as fixed.

**Comment by ventoy** [comment]
@1457384613gh 
Have you tried grub2 mode or the above CI release?

**Comment by francois072** [comment]
Above CI release.

**Comment by francois072** [comment]
GRUB2 mode did not work on ventoy 1.0.73

**Comment by 1457384613gh** [comment]
> @1457384613gh 
> Have you tried grub2 mode or the above CI release?
> 

Yes, I have tried grub2 mode ten days ago.

It can boot ISO image of fedora and enter desktop even help to install successfully.

**Comment by francois072** [comment]
I tesed Fedora 35 with Ventoy 1.0.73 with remounting turned on and also with GRUB2, still it failed in both cases.

When remounting is turned off in Ventoy 1.0.73, Fedora boots successfully.

With the new CI release Fedora boots successfully with remounting turned on.
