### ISSUE TITLE
[features request]: to make Ventoy better

### ISSUE THREAD

**Issue by anwar-alsilwy** [ventoy/Ventoy#1554]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.72

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

128GB

### Disk Manufacturer

SanDisk

I hope to add these features to Ventoy project:

1- Add option in the Power menu to reboot PC to UEFI Firmware setup (UEFI BIOS).
2- Add option to show PC hardware specifications (CPU, RAM, Motherboard...etc).
3- Add ability to set icons for settings, power & other sub menus.

**Comment by ventoy** [comment]
3- Add ability to set icons for settings, power & other sub menus.
This already implemented.  Every settings/power & other sub menus has its menu class.
https://www.ventoy.net/en/plugin_menuclass.html    `Built-in Class`

**Comment by crasadure** [comment]
2- Add option to show PC hardware specifications (CPU, RAM, Motherboard...etc).
You can use Grub2 File manager program for learning hardware specifications. Program was developed by @a1ive
https://github.com/a1ive/grub2-filemanager/releases
ISO Download Link : https://github.com/a1ive/grub2-filemanager/releases/download/latest/grubfm_multiarch.iso

**Comment by anwar-alsilwy** [comment]
> 3- Add ability to set icons for settings, power & other sub menus. This already implemented. Every settings/power & other sub menus has its menu class. https://www.ventoy.net/en/plugin_menuclass.html `Built-in Class`

Thank you very much longPanda,
I read this article before, but it looks like updated now.
What about first option and third one ?

**Comment by anwar-alsilwy** [comment]
> 2- Add option to show PC hardware specifications (CPU, RAM, Motherboard...etc). You can use Grub2 File manager program for learning hardware specifications. Program was developed by @a1ive https://github.com/a1ive/grub2-filemanager/releases ISO Download Link : https://github.com/a1ive/grub2-filemanager/releases/download/latest/grubfm_multiarch.iso
Thanks @crasadure
I know this options in GrubFM but it will be so useful if added to Ventoy project.

**Comment by anwar-alsilwy** [comment]
> The latest 1.0.73 release. F5 Tools --> Power --> Reboot to EFI setup F5 Tools --> Hardware Information

Excellent work !!
You could also add more useful information (e.g CPU temperature, Real time clock,... etc).

![20220407_070748](https://user-images.githubusercontent.com/71539261/162118248-a79f12f6-fca5-45a5-b243-e1a77cc538ff.jpg)


![20220407_065709](https://user-images.githubusercontent.com/71539261/162118023-b1b1a8df-4590-4d35-84d8-240bbf5f285e.jpg)

You can check this file for reference:
https://www.mediafire.com/file/8r6hyee42zjmyx5/hwinfo.sh/file

Thanks.

**Comment by ventoy** [comment]
Let's talk about it later, I think the information is enough for now.
