### ISSUE TITLE
How to mount/access second partition on TVs etc?

### ISSUE THREAD

**Issue by dm17** [ventoy/Ventoy#1555]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.72

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GB

### What happened?

Since the first partition is full by default, one cannot write to it. So I store files on the second partition. Which is fine if you have a regular computer. However, I wonder if there is a way to access files in the second partition when it is not getting mounted by default (like with a modern TV, which only mounts the first partition). It isn't a crucial feature, but I'm guessing other's have worked around it before.
Thanks!

**Comment by ventoy** [comment]
https://www.ventoy.net/en/plugin_control.html
`VTOY_LINUX_REMOUNT` option.

**Comment by ventoy** [comment]
I  close the issue now after 10 days without response.
If you have any update, please reopen the issue.
