### ISSUE TITLE
Request: Please Add vhd,vhdx disk installation support for ventoy

### ISSUE THREAD

**Issue by crasadure** [ventoy/Ventoy#156]
Hi ventoy,
I am testing your system on my computer using a real usb flash drive
I captured some videos for ventoy multiboot
Video1-Introduce Ventoy
https://youtu.be/58oZyiKzIG4
Video2-İnstall and Update Ventoy
https://youtu.be/3k067c8_oIA
Video3-Using plugin(ventoy.json) with Ventoy
https://youtu.be/H9E-1ELcCtI

Can you add installing to vhd,vhdx disk support?
I reformatted my flash drive over and over for capture my videos.
So ı dont want to distrub my usb flash drive while capturing these videos.
I know that you are think safety our internal disk
I will be happy if you add vhd,vhdx installation support to your project  🙂

**Comment by ventoy** [comment]
Hi,
Thank you very much for your videos.
In fact, I always test Ventoy with Virtual Machine, and install Ventoy into the Virtual Disk in the VM.

**Comment by crasadure** [comment]
I cant see vhd disk Ventoy2disk.exe( GUI interface on Windows)
Ventoy2disk.exe can not list vhd disk on GUI interface.. can you add vhd support to GUI?

**Comment by ventoy** [comment]
Oh, I forgot it.
In windows Ventoy2Disk.exe will filt disk by USB interface type.
You can run Ventoy2Disk.exe from the cmd with -U option, that is:
`Ventoy2Disk.exe -U`

Then all the disk will be avaliable.

**Comment by crasadure** [comment]
Thanks your help,I will try  🙂
