### ISSUE TITLE
[issue]: When we install Windows without a dedicated graphics card in legacy mode, a square black BOX appears and does not move FORWARD. STOPS WORKING

### ISSUE THREAD

**Issue by captainjakey** [ventoy/Ventoy#1568]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.72

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

64GB

### Disk Manufacturer

SANDISK

### What happened?

When we install Windows without a dedicated graphics card in legacy mode, a square black BOX appears and does not move FORWARD. STOPS WORKING

**Comment by ventoy** [comment]
1. OK with a dedicated graphics card ?
2. Which ISO file did you test?  All Windows ISO files have the same problem? (Win10/Win10 ...)
3. Try WIMBOOT mode  https://www.ventoy.net/en/doc_wimboot.html

**Comment by captainjakey** [comment]
Thx for quick support, will try then I'll tell you 🤗🫂

**Comment by ventoy** [comment]
I  close the issue now after 10 days without response.
If you have any update, please reopen the issue.

**Comment by captainjakey** [comment]
Issue resolved, and also i use theme than after i don't have any issues,
thank you.

**Comment by captainjakey** [comment]
hey there
the issue persist again with lagacy without dedicated graphics card, black box appears again, when i tried as u suggested to ctrl + W, when i use this keys it'll boot nornally without black box but there after at the windows intallation parition selection i anable to create partition and also i cannot proceed further. so plz a help me with this. t

thank you

**Comment by captainjakey** [comment]
i cannot create partition on winboot mode

**Comment by captainjakey** [comment]
> 2\. indows ISO files have the same pro

i tried so many iso as well as microsoft orignal downloaded iso as well

**Comment by captainjakey** [comment]
> 1. with a dedicate

with dedicated gc ican competely install windows without any problem
bt probelm with onboard graphics with lagacy mode in some scenerios

**Comment by captainjakey** [comment]
> 3\. WIMBOOT mo

when i tried wimboot mode i cant create partion for installing windowws
