### ISSUE TITLE
[issue]: Mistake in release notes 1.0.73

### ISSUE THREAD

**Issue by ShalokShalom** [ventoy/Ventoy#1569]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.73

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

32

### What happened?

See for yourself: 

![Screenshot_272](https://user-images.githubusercontent.com/6344099/162231147-1db0ee1d-23ec-48f6-be8a-3c3bee9c0982.png)
![Screenshot_273](https://user-images.githubusercontent.com/6344099/162231155-60c477be-4c35-4160-b7cf-47a3bc2da19a.png)

**Comment by ventoy** [comment]
Thanks, I have updated the notes.
