### ISSUE TITLE
the grub menu is not displayed 

### ISSUE THREAD

**Issue by bladem2003** [ventoy/Ventoy#157]
the grub menu is not displayed.
I have several folders and subfolders with lots of small files on my USB stick.
If I only create a folder with the isos, the menu is immediately displayed.
I think it takes a long time to search for the isos.
It would be nice to have an option to set the folder with the isos or folders that are not searched.

**Comment by ventoy** [comment]
Hi,
You can put a file with name .ventoyignore in the specific directory. When ventoy detects this file, it will not search the directory and all the subdirectories for iso files.

**Comment by bladem2003** [comment]
thanks that works.
an option in ventoy.json to set the folder with the isos so that the .ventoyignore file does not have to be created every time a folder is created

**Comment by ventoy** [comment]
You are right !

I'm considering add  VTOY_DEFAULT_SEARCH_ROOT  option in  
[https://www.ventoy.net/en/plugin_control.html](https://www.ventoy.net/en/plugin_control.html)

For example:   
![捕获](https://user-images.githubusercontent.com/59477474/82793852-2d4bf800-9ea4-11ea-9194-0b131dc616a2.PNG)


So you can expect the next release  :)

**Comment by bladem2003** [comment]
Thanks that's great

**Comment by ventoy** [comment]
OK, I will close the issue now.
