### ISSUE TITLE
ventoy doesn't boot  Acer Nitro 5

### ISSUE THREAD

**Issue by maravento** [ventoy/Ventoy#1571]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.72

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

32 GB and 256 GB

### Disk Manufacturer

sandisk, PNY Elite-X

### Image file download link (if applicable)

https://www.microsoft.com/es-es/software-download/windows11

### What happened?

ventoy doesn't boot  Acer Nitro 5 AN515-54
SO Windows 11

When starting from the boot menu (f12) the usb appears as "linpus lite" and it does not start from USB
PS: Bios Parameters
- disabled secure boot
- UEFI only (acer nitro 5 has no legacy mode)

![photo1649519813](https://user-images.githubusercontent.com/14880802/162581703-81049ca6-2c73-49d4-8844-15e717a9c160.jpeg)

regards

**Comment by steve6375** [comment]
Try remaking Ventoy drive as legacy/MBR not gpt.

**Comment by maravento** [comment]
my USB drive is in MBR (not GPT)

![Captura de pantalla -2022-04-09 11-13-20](https://user-images.githubusercontent.com/14880802/162582228-38220513-578a-4a0b-85f5-785ad8ffb5d8.png)

**Comment by steve6375** [comment]
You said it was gpt!
Anyway remake the drive as gpt in that case.

**Comment by maravento** [comment]
> You said it was gpt! Anyway remake the drive as gpt in that case.

sorry. I already fixed the issue. MBR (not GPT)

**Comment by maravento** [comment]
I have tried to change the USB drive from MBR to GPT, but it does not take the changes. Do I have to format it for it to take the changes?

![Captura de pantalla -2022-04-09 11-24-42](https://user-images.githubusercontent.com/14880802/162582705-3acd5e94-ef15-416c-9e40-80b218641fd9.png)

**Comment by steve6375** [comment]
Yes

**Comment by maravento** [comment]
ok thanks
