### ISSUE TITLE
无法启动本地nvme ssd中的vhdx[issue]: 

### ISSUE THREAD

**Issue by mdmbct** [ventoy/Ventoy#1572]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.72

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

500HB

### Disk Manufacturer

WDC SN500

### Image file checksum (if applicable)

Yes.

### What happened?

不知道什么原因，同样的vhdx文件，一个在西数蓝盘SATA SSD里插在笔记本硬盘槽里，就可以启动。换成WDC SN500就不行，选择vhdx后，转几圈就停顿了下，然后笔记本重启。不知道是笔记本BIOS原因还是ventoy的原因。

**Comment by steve6375** [comment]
Are both partitions/drives NTFS?

**Comment by mdmbct** [comment]
> Are both partitions/drives NTFS?

both。I think the win10 vhdx file maybe have some problems，another win11 vhdx file can be booted。
