### ISSUE TITLE
Hide VTOYEFI partition for OSes booted from Ventoy

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#1575]
Hide VTOYEFI partition for OSes booted from Ventoy.

Some OSes booted from Ventoy will mount VTOYEFI, and maybe write it.
Example, Android x86 may mount VTOYEFI as SDcard, and make new folders such as Alarm, Android, DCIM, Pictures, Movies, Music Notifications and so on into it.
The partition before VTOYEFI named Ventoy couldn't be mount by OSes booted from itself.
So why do not ban those OSes from mounting VTOYEFI, too?
If not, Windows installed will scan and fix it, and then it will be mounted and not hidden.
……
However, hide VTOYEFI and make it disabled to be mounted by OSes booted from Ventoy.
＃I want those whoever agree and have seen and gotten it to help me to give a feedback about not mounting as SDcards and not making those folders into every partition mounted unless users allow, because I don't know where I should have given a feedback around Android maybe x86. What I can do now is just delete those folders over and over again, which wastes time and upsets me.

**Comment by ventoy** [comment]
VTOYEFI is just a normal FAT partition.
There is no way to hide it after boot int OS.

**Comment by 1457384613gh** [comment]
> VTOYEFI is just a normal FAT partition.
> There is no way to hide it after boot in OS.

But the partition before VTOYEFI named Ventoy could be hidden. VTOYEFI could have been set like it.

**Comment by ventoy** [comment]
That's because the Ventoy partition is occupied by the booting ISO file, so the OS can not mount it.

**Comment by 1457384613gh** [comment]
> That's because the Ventoy partition is occupied by the booting ISO file, so the OS can not mount it.
> 

I have an idea.

Set disk as `mbr`.
And set VTOYEFI as `EFI system partition`。
Having booted Windows images to install, it will ignore VTOYEFI as `EFI system partition` because it thinks disk with mbr has no EFI system partition

**Comment by ventoy** [comment]
VTOYEFI does is `EFI system partition` now in MBR. (with fs code `0xef`)

**Comment by 1457384613gh** [comment]
I have another idea.

Delete all partitions in USB disk and format it.
It will be RAW not mbr or gpt.

Format it as UDF.

Copy the folder named `EFI` from VTOYEFI into UDF.

Copy ISO files into UDF.

Set the disk as USB-FDD UDF.

The USB disk is like a boot-able CD or DVD.

Both VTOYEFI files and ISO files is into it.

And then OSes booted by Ventoy cannot read and write VTOYEFI.

Windows 11, Linux and Mac all can mount it as a USB disk.

Just only one partition all the disk.

**Comment by 1457384613gh** [comment]
I'm sorry but I have just known that ISO of LiveCD is like a disk, there is a ESP next to UDF.

But iso of windows without ESP next to udf.

Why could it have just only one udf to boot?

**Comment by 1457384613gh** [comment]
How about edit `startup.nsh`?
Add
`load udf_x64.efi
map -r`

**Comment by bert003** [comment]
I came across this thread and this still applies especially when using ISOs created for a Fully Automated Installation (using FAI) - https://fai-project.org/.

When you boot a FAI ISO using Ventoy, the ISO detects the Ventoy partition as the first available partition and tries to install it there. It finds it as read-only and fails. So hiding it, in this case, would solve the issue.

Any thoughts and possible solutions on this please?
