### ISSUE TITLE
Give me a LOGO.png of Ventoy resolution 512x512

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#1576]
Give me a LOGO.png of Ventoy resolution 512x512.
I am designing a theme for rEFInd Boot Manager to need png logo of Ventoy.

If the folder `VTOYEFI: /EFI/boot` is renamed ventoy and there is a png logo named `os_ventoy` , there will be logo of Ventoy with a small logo of USB flash disk beneath appearing next to logos of OSes installed .

**Comment by ventoy** [comment]
https://github.com/ventoy/Ventoy/blob/master/ICON/logo_512.png

**Comment by 1457384613gh** [comment]
> https://github.com/ventoy/Ventoy/blob/master/ICON/logo_512.png
> 

Thank you very much!
