### ISSUE TITLE
[feature]: Showing the name and icon of parent directory

### ISSUE THREAD

**Issue by htcfreek** [ventoy/Ventoy#1578]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.73

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

128GB

### What happened?

You can assign an icon to a directory entry by giving the a class id. But if you enter this directory in tree view mode there is no indicator in which directory you are. It would be great if ventoy can show the name/alias and icon of the directory on the top of the iso list.

![image](https://user-images.githubusercontent.com/61519853/163681953-a0435646-94e5-4e69-92d1-f8323ec0083c.png)

It also isn't possible to assign the class/icon to the directory AND all images in the directory. (My workaround: Manually add for each directory an parent and dir entry in the json file.)

![image](https://user-images.githubusercontent.com/61519853/163681857-1ffbd1e7-eab9-40e3-a23b-af3192f2d794.png)

**Comment by ventoy** [comment]
1. Currently there is a top `[../]` menu entry for every sub-directory.  The parent directory path can be displayed in the menu. But the class id is not equal with the parent directory, it is fixed as `vtoyret`

2. All ventoy plugins use the same logic, `dir` for directory itself, `file` for files, `parent` for all the files under a directory.  Your workaround is the right way. I will not add a `key` for directory and files.

**Comment by ventoy** [comment]
This CI release display the directory path on the top menu in treeview mode.
https://github.com/ventoy/Ventoy/actions/runs/2188190644
