### ISSUE TITLE
[Success Image Report]: slackware 15.0

### ISSUE THREAD

**Issue by Asimopostin** [ventoy/Ventoy#1579]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.71

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

slackware64-15.0-install-dvd.iso

### Image file checksum type

MD5

### Image file checksum value

f8418ef0ec2c0a205adf5dbc2f2a1971

### Image file download link (if applicable)

https://mirrors.slackware.com/

### Test envrionment

custom pc

### More Details?

This image file booted successfully in Ventoy. just successfully boot, i didn't install it but it did boot as normal
pc specs btw:
https://user-images.githubusercontent.com/82709240/163704162-dc9877cb-f5b3-4d61-b0e8-5b41220c194e.png

**Comment by ventoy** [comment]
Thanks!
