### ISSUE TITLE
3个建议。

### ISSUE THREAD

**Issue by weakestan** [ventoy/Ventoy#158]
1.增加从硬盘启动选项。
2.memdisk提醒不明显，建议提醒直接在下方改变f1颜色就行了。
3.官方论坛，帐号初期使用163邮箱，好像没收到激活邮件，更改为21cn邮箱后，没有激活邮件选项。

**Comment by weakestan** [comment]
测试启动iso
freenas安装光盘无法加载。可能freebsd也不行。
Mounting from cd9660:iso9660/FREENAS failed with error 2;retrying for 180 mor seconds

**Comment by ventoy** [comment]
1. 这个之前尝试加过，特殊情况比较多，做不太完美，后面就拿掉了。后续看看需求多的话可以考虑再加回来
2. memdisk 这个建议不错，就是实现麻烦点，或者后面看看在界面上贴个大点的图标啥的
3. 官方论坛发邮件功能有点问题，现在都是由管理员自己激活，不是邮件激活
4. FreeBSD系列现在都还没有适配

**Comment by SamLukeYes** [comment]
第一个需求可以通过自行添加可选择从硬盘启动的ISO来间接实现，例如manjaro的安装镜像在uefi模式下可以选择启动硬盘上的efi引导，一些winPE应该也有这样的功能

**Comment by ventoy** [comment]
1和2在最新版本已经实现。
