### ISSUE TITLE
[issue]: Prime OS 2.1.0; It has failed to boot.

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#1580]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.73

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

128GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://sourceforge.net/projects/primeos/files/64-bit/PrimeOS-2.1.0-64-bit-20220223-BETA.iso/download

### What happened?

It has failed to boot.
And ctrl+r (grub mode), too.
![image](https://user-images.githubusercontent.com/69227436/163708245-9e3391f7-dcf5-4552-87ce-d65680789d86.png)

**Comment by ventoy** [comment]
Try this CI release and give me the result please:

https://github.com/ventoy/Ventoy/actions/runs/2182448529
https://www.ventoy.net/en/doc_github_ci.html

**Comment by ventoy** [comment]
This CI release should have fixed it.

**Comment by 1457384613gh** [comment]
![image](https://user-images.githubusercontent.com/69227436/163816497-5baf20e6-d96c-49a4-9c1d-753b06fea9f1.png)

**Comment by ventoy** [comment]
请使用物理机测试。
