### ISSUE TITLE
some plan to support EmuELEC/CoreELEC img?

### ISSUE THREAD

**Issue by macarthor** [ventoy/Ventoy#1581]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.73

### What about latest release

No. I didn't try the latest release.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

any

### What happened?

hi community,

i wonder if ventoy supports or plan to support [EmuELEC](https://github.com/EmuELEC/EmuELEC/releases)/[CoreELEC](https://github.com/CoreELEC/CoreELEC/releases/) img?

the img format is quite simple i believe, a disk image with offset partitions, which can be seen by losetup or fdisk.

**Comment by ventoy** [comment]
Ventoy supports `LibreELEC`, maybe they are similar ?

**Comment by macarthor** [comment]
> Ventoy supports `LibreELEC`, maybe they are similar ?
aye, i saw libreelec support in ventoy.net, but it's x86 img, while emuelec/coreelec are for ARM only, more specifically AMLOGIC cpu.

**Comment by ventoy** [comment]
For arm, Ventoy only support `ARM64 UEFI` hardware environment. So they can not be supported.

**Comment by macarthor** [comment]
> For arm, Ventoy only support `ARM64 UEFI` hardware environment. So they can not be supported.

many thanks.

looking forward to support...
