### ISSUE TITLE
[issue]: It cannot work. MBR, UDF + VTOYEFI

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#1582]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.73

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

128GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

github

### What happened?

A bug happened!
My Sandisk has been formatted as MBR with only two partitions, whose size is 117,360 MiB.
1 MiB above all is for MBR and GAP;
The first partition is UDF, whose size is 117,327 MiB, named `Ventoy`;
The last partition is ESP, whose size is 32 MiB, named `VTOYEFI`

With UEFI booting USB device, it cannot enter the grub of Ventoy, only to be black and reboot.

**Comment by 1457384613gh** [comment]
![image](https://user-images.githubusercontent.com/69227436/163758180-fddf0c34-7efd-49e8-a042-35ca907cc539.png)

**Comment by ventoy** [comment]
Don't create the partitions manually.
1. Install Ventoy to the disk.
2. Reformat the Ventoy partition from exFAT to UDF.

**Comment by ventoy** [comment]
Besides, only UDF1.02-2.01 supported as grub2 only support UDF1.02-2.01, refer https://github.com/ventoy/Ventoy/issues/389

**Comment by ventoy** [comment]
@1457384613gh 
Any update?

**Comment by 1457384613gh** [comment]
> @1457384613gh 
> Any update?

I haven't tried again, yet, for occupation.
Wait for me, please.

**Comment by 1457384613gh** [comment]
第一分区为 exFAT分区，也进不去。

U盘为 MBR格式。

BIOS设置为纯UEFI引导，无法加载VTOYEFI。

**Comment by ventoy** [comment]
你意思是完全使用Ventoy默认设置安装完之后是进不去的？  没有手动创建分区？

**Comment by 1457384613gh** [comment]
但是 微PE工具箱 双分区安装。

exFAT+FAT16

却可以UEFI启动 FAT16中的PE。

**Comment by ventoy** [comment]
安全启动有没有关闭？

**Comment by 1457384613gh** [comment]
关闭了，而且我设置的是安全启动支持。

**Comment by ventoy** [comment]
关闭的同时，不要设置安全启动支持，再试试。

**Comment by 1457384613gh** [comment]
我刚刚试了。
MBR的磁盘格式，纯UEFI启动。
BIOS关闭安全启动，Ventoy取消安全启动支持，启动成功，第一次无法直接启动Fedora，只有grub模式启动fedora后重启，才能在 非 grub模式 直接启动fedora

但是，我希望 无论安全启动有没有关闭或者开启，都能够 MBR的磁盘格式并且纯UEFI启动，可以做到吗？

为什么GPT格式的U盘开启安全启动支持的安装，就可以在所有的机子上启动呢？

MBR的格式可以做到吗

**Comment by ventoy** [comment]
这个是具体机器主板UEFI固件的实现有关。
“无论安全启动有没有关闭或者开启，都能够 MBR的磁盘格式并且纯UEFI启动，可以做到吗？”  --- 这个在我自己的PC机上就可以。

**Comment by 1457384613gh** [comment]
我发现，先不添加安全启动支持，安装到U盘。然后，添加安全启动，点击升级，就可以进去了。

但是直接添加安全启动支持，安装到U盘里，会启动识别。

**Comment by ventoy** [comment]
你可以把这两种情况下的 32MB VTOYEFI 分区内的所有文件都导出来对比一下，看看有什么不一样。理论上应该是一样的。

**Comment by 1457384613gh** [comment]
有没有可能，前面1MiB有细微差别。或者，活动分区会造成影响？虽然，可能性很小。虽然纯UEFI好像不考虑活动分区和主引导记录。

**Comment by 1457384613gh** [comment]
我终于知道为什么加载失败了。


UEFI 加载的是 `VTOYEFI: /EFI/BOOT/grubx64.efi` 进不去，加载失败。

rEFInd Boot Manager 可以加载 `VTOYEFI: /EFI/BOOT/grubx64_real.efi`加载成功，进去了。

为什么 grubx64.efi 失败了呢？
既然后者是 real的，那grub.efi干什么用呢？

**Comment by 1457384613gh** [comment]
我发现，我是把VTOYEFI: /EFI/BOOT 重命名成 VTOYEFI: /EFI/ventoy 才启动成功的。

使用的主板自带的BIOS的UEFI启动，没有使用rEFInd。

之前启动失败，有可能是因为 主板没法启动 MBR或者第二个ESP分区上的BOOT文件夹。我也不知道是什么设定。重命名就可以启动成功了。我觉得 EFI的文件目录还是有必要规范的，哪怕是软链接到BOOT中都好。
