### ISSUE TITLE
[Feature Request]: 希望挂载的VHDx虚拟硬盘能够被 Ventoy for Windows 检测到，并且可以安装。

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#1583]
有的镜像需要在 Hyper-V 上测试。
所以，希望挂载的VHDx虚拟硬盘能够被 Ventoy for Windows 检测到，并且可以像给U盘安装一样地安装到虚拟硬盘文件中。

**Comment by ventoy** [comment]
现在勾选 `显示所有设备` 选项以后能显示出来吗？ 安装有错误吗？

**Comment by 1457384613gh** [comment]
可以显示，安装没错误。
但是，能不能设置一下，让虚拟硬盘和U盘一起显示，隐藏安装了操作系统的内置硬盘。
【显示所有设备】选项打开以后，容易手抖点错，好危险。

**Comment by 1457384613gh** [comment]
![image](https://user-images.githubusercontent.com/69227436/163816662-bebb4555-47c9-464c-9c63-03074bc1b440.png)

**Comment by 1457384613gh** [comment]
![image](https://user-images.githubusercontent.com/69227436/163816758-b6c1f72f-b855-4b11-9b12-60a22e31c2bf.png)

**Comment by 1457384613gh** [comment]
![image](https://user-images.githubusercontent.com/69227436/163816823-1b4bccb3-b22a-4262-86e9-80c5136c0e09.png)

**Comment by 1457384613gh** [comment]
Android x86 启动成功。
Prime OS，依然启动失败。
Prime OS，无论是使用Ventoy，还是Hyper-V 的DVD驱动器，都启动失败。
但是刻录以后，可以启动成功。
初步推测，是不支持光驱启动，只支持FAT32启动。
看下，能不能 把模拟光驱，换成 模拟FAT32 ？？？

**Comment by 1457384613gh** [comment]
🤣🤣🤣
这似乎是个不标准的 镜像文件。毕竟，无法光盘启动。

**Comment by ventoy** [comment]
1、自己注意就行了，实在担心你可以把这个虚拟硬盘挂到一个虚拟机里面，然后虚拟机里面挂载VentoyLiveCD启动以后安装。
2、ISO文件必须能光驱启动才可以。
