### ISSUE TITLE
[issue]: MacBook PRo not works

### ISSUE THREAD

**Issue by Paul75** [ventoy/Ventoy#1584]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.73

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

512GB

### What happened?

Hello, Not start on MacBook pro

**Comment by ventoy** [comment]
Ventoy doesn't officially support MacBook.
