### ISSUE TITLE
为了能够被 rEFInd 扫描到，可以在 VTOYEFI 中新增目录吗？

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#1587]
为了能够被 rEFInd 扫描到，可以在 VTOYEFI 中新增目录吗？
在 `VTOYEFI: /EFI` 的目录中，新增一个命名为 `ventoy` 的文件夹，文件夹中包含`grubx64_real.efi` 、`grubx64.efi`、 `MokManager.efi`等文件，只要能够正常引导并启动就行了，你们随意设置。严格来说，UEFI 的引导程序 要有两个文件夹放在EFI文件夹中，一个是BOOT文件夹用于旧固件默认启动，另一个是 以引导的内容 本身命名的文件夹 用于 与 其他引导程序的引导文件区分开，并且可以被 启动管理器扫描到 并列出选项，便于用户选择。
所以，在原有目录的基础上，新增 `VTOYEFI: /EFI/ventoy` 更加规范。
新增 ventoy 的文件夹可能会导致 VTOYEFI 分区的剩余空间更少，建议增大至 64 MiB，以便容纳更多，同时防止在升级的过程中，末端的那一小块被反复擦写。
下图是新增 `VTOYEFI: /EFI/ventoy` 目录以后可以达到的效果。
![image](https://user-images.githubusercontent.com/69227436/164407863-5ea8c910-25e2-4836-aa0a-c43a5a0a7282.png)

**Comment by ventoy** [comment]
/EFI/XXX 目录只是大部分安装到硬盘中的系统所用的方法，并不是UEFI标准。
Ventoy官方只支持从BIOS直接启动，所以不会增加这个目录。

**Comment by 1457384613gh** [comment]
> /EFI/XXX 目录只是大部分安装到硬盘中的系统所用的方法，并不是UEFI标准。
> Ventoy官方只支持从BIOS直接启动，所以不会增加这个目录。
> 
> 

但是，有的BIOS也会扫描这个目录。

**Comment by 1457384613gh** [comment]
> /EFI/XXX 目录只是大部分安装到硬盘中的系统所用的方法，并不是UEFI标准。
> Ventoy官方只支持从BIOS直接启动，所以不会增加这个目录。
> 
> 

但是，某些新的 BIOS 没有加载 U盘里的 /EFI/BOOT，启动失败。BOOT重命名为ventoy以后启动成功，可以加载 /EFI/ventoy。不知道是不是把 U盘当作硬盘的原因。也有可能，BOOT目录被 内置硬盘占用了，目录发生歧义。

**Comment by ventoy** [comment]
使用 Rufus 等工具直接制作的可启动U盘 （Ubuntu/CentOS 等）里面都是只有 EFI/BOOT 目录。
按照你的说法，这种在你环境上都是不能启动的，那就是你BIOS的问题了。

**Comment by steve6375** [comment]
Some uefi Lenovo bioses will add a boot entry for /efi/boot/grubx64.efi as 'Linpus Lite'. They usually offer the same model with either a windows os Installed or a Linux OS preinstalled. 
Never heard of a bios searching for .efi files. 
What system is that?
Refind can be configured to add or omit entries using plist.conf file.

**Comment by 1457384613gh** [comment]
My BIOS is from Xiaomi.
It can really search /EFI/$every/xxx.efi

Sure it can, add
```
menuentry Ventoy {
    loader /EFI/BOOT/grubx64_real.efi
    icon /EFI/refind/icons/os_ventoy.png
}
```

If pluging in the USB flash disk, it works well.
But if unpluging the USB flash disk, it will be still there.

However, it is always there even without Ventoy.

**Comment by 1457384613gh** [comment]
So I think it is better to set `VTOYEFI: /EFI/ventoy/xxx.efi` for new UEFI devices or exceptional case.

**Comment by steve6375** [comment]
Which of the four boot options did you set the Ventoy2Disk tool to before you made the USB drive?

- Secure Boot MBR
- Non-secure Boot MBR
- Secure Boot GPT
- Non-secure Boot GPT

Did you test all of these with a normal VTOYEFI:\EFI\BOOT partition ?
Often the result is different depending on your BIOS.

**Comment by 1457384613gh** [comment]
1 `BOOT` should be renamed `ventoy`
2 The first time is unknown, the second+ time works well
3 works well
4 works well

**Comment by steve6375** [comment]
So secure boot from the shim file bootx64.efi is not liked by your BIOS from a MBR partition.

What if you 

1. make  new folder \EFI\VENTOY
2. copy file \EFI\BOOT\grubx64_real.efi  to  \EFI\VENTOY
3. rename \EFI\VENTOY\grubx64_real.efi to  bootx64.efi

i.e. add one file to VTOYEFI partition
\EFI\VENTOY\BOOTX64.EFI   <<<< was grubx64_real.efi

Is there room? Will this solve the issue and still leave original \EFI\BOOT folder unchanged?

**Comment by 1457384613gh** [comment]
I have tried it, just now.
If so, it will work well.
