### ISSUE TITLE
[issue]: where is the source code for V2DServer ?

### ISSUE THREAD

**Issue by pedro-nonfree** [ventoy/Ventoy#1588]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.72

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

2GB

### What happened?

Ventoy is a nice piece of software, but I cannot find the source code of V2DServer, I would like to know what I am running as root in my computer, and the GPLv3 license enforces having a source code for each binary

**Comment by ventoy** [comment]
src:
https://github.com/ventoy/Ventoy/tree/master/LinuxGUI/Ventoy2Disk

build script:
https://github.com/ventoy/Ventoy/blob/master/LinuxGUI/build.sh
