### ISSUE TITLE
iso files with a space character are hidden in the menu

### ISSUE THREAD

**Issue by ehamon** [ventoy/Ventoy#159]
On USB stick, a file with one space character is not shown in the menu.
like: 'xxxxx YYYY.MM.DD.iso'
The same file renamed 'xxxxx-YYYY-MM-DD.iso' is shown correctly in the menu.

ventoy-1.0.11

**Comment by ventoy** [comment]
Yes, I have noted that in the document:

![11](https://user-images.githubusercontent.com/59477474/82803159-a05c6b00-9eb2-11ea-8327-12a634f0e8bf.PNG)

**Comment by ehamon** [comment]
Ok. I hadn't read this.
Many of my iso files downloaded contain space characters. I have to be picky about this.
Thank you.
