### ISSUE TITLE
[issue]: "This is NOT a standard ventoy device and is NOT supported (12)" after update to 1.0.73

### ISSUE THREAD

**Issue by rexmightlag** [ventoy/Ventoy#1590]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.72

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

16

### Disk Manufacturer

Generic

### What happened?

Hello, today I decided to update an old ventoy drive (1.0.8) to (1.073) and an error saying "This is NOT a standard ventoy device and is NOT supported (12)" showed up. I have also tried to "update" to the versions 1.0.72 & 1.0.30 after this, same error.

I have attached the screenshot of the error and the command : sudo Ventoy2Disk.sh -l /dev/sdb
![IMG_20220422_224935_1](https://user-images.githubusercontent.com/80040608/164764349-aa0c4cf4-0c75-4072-aacd-8b1bbde2eea2.jpg)
![2022-04-22_22-59](https://user-images.githubusercontent.com/80040608/164764799-de634542-4d8a-446a-9b4d-8e5ffa695e4a.png)

**Comment by ventoy** [comment]
1. please run `dd if=/dev/sdb of=1.bin bs=512 count=1`  and upload the `1.bin` file here

**Comment by rexmightlag** [comment]
Done, added .zip at the end as the .bin file extension was not allowed.
[1.bin.zip](https://github.com/ventoy/Ventoy/files/8547584/1.bin.zip)

**Comment by ventoy** [comment]
Please run the following commands and retry.
```
echo -en '\x56\x54' | dd of=/dev/sdb bs=1 count=2 seek=400
sync
```

**Comment by rexmightlag** [comment]
Hello, it worked!, thank you. Can you please explain the problem (and solution)? My friend also faced the same issue, he updated from 1.0.22 to 1.0.73. Again, thank you.

**Comment by ventoy** [comment]
How did you update from 1.0.08 to 10.0.73?

**Comment by rexmightlag** [comment]
We both used the GUI on Linux.

**Comment by ventoy** [comment]
This is a bug for Ventoy Linux GUI program.
I have fixed it, you can use this CI release for test:
https://github.com/ventoy/Ventoy/actions/runs/2224945652
https://www.ventoy.net/en/doc_github_ci.html

**Comment by rexmightlag** [comment]
It worked, Thanks.

**Comment by jovylle** [comment]
Fixed it by setting up the Ventoy again and Choosing "Update" instead of "Install"

**Comment by Reckoner911** [comment]
1.1.05 Ventoy GUI - reproduced
