### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by aaaaadrien** [ventoy/Ventoy#1591]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.72

### BIOS Mode

Both

### Partition Style

GPT

### Image file name

AlmaLinux-8.5-x86_64-minimal.iso

### Image file checksum type

MD5

### Image file checksum value

99aa2c3195a01464ddca63443bd7dcbc

### Image file download link (if applicable)

http://ftp.gwdg.de/pub/linux/almalinux/8.5/isos/x86_64/AlmaLinux-8.5-x86_64-minimal.iso

### Test envrionment

Dell Latitude 3510

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
