### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by R0undGlow** [ventoy/Ventoy#1592]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.73

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

HBCD_PE_x64.iso

### Image file checksum type

MD5

### Image file checksum value

BEC7304FE2EB11DE495B9EA7B73C38AA

### Image file download link (if applicable)

https://www.hirensbootcd.org/files/HBCD_PE_x64.iso

### Test envrionment

VMware Workstation 16

### More Details?

This image file booted successfully in Ventoy. - But after boot, you need to resize display resolution.

**Comment by ventoy** [comment]
Thanks!
