### ISSUE TITLE
[issue]:  Ventoy Plugson is not working on DUD(Driver Update Disk).

### ISSUE THREAD

**Issue by 18photos** [ventoy/Ventoy#1593]
![제목 없음](https://user-images.githubusercontent.com/31121613/165217239-e9ddbc6a-e993-469e-9897-747ca49fdf16.png)
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.72

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

512gb

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

rocky linux 8.5 official

### What happened?

Hello~Ventoy team.

Ventoy plugson is not working.

I was import RockyLinux 8.5 and some DUD image iso(dd.iso).

I was type on "TAB" and "inst.dd" after rebooting and install.

But,, There is no drivers disk.

Please check this problem.

**Comment by ventoy** [comment]
Please upload the `ventoy.json` file here for analyse.

**Comment by 18photos** [comment]
{
    "auto_memdisk":[
        "/Linux/DUD/dd-mpt3sas-37.101.00.00-1.el8_5.elrepo.iso"
    ],
    "dud":[
        {
            "image": "/Linux/RockyLinux/Rocky-8.5-x86_64-dvd1.iso",
            "dud":[
                "/Linux/DUD/dd-mpt3sas-37.101.00.00-1.el8_5.elrepo.iso",
                "/Linux/DUD/dd-mptsas-3.04.20-6.el8_5.elrepo.iso"
            ]
        },
        {
            "image": "/Linux/CentOS/CentOS-8.1.1911-x86_64-dvd1.iso",
            "dud":[
                "/Linux/DUD/dd-mpt3sas-28.100.00.00-2.el8_1.elrepo.iso"
            ]
        },
        {
            "image": "/Linux/CentOS/CentOS-Stream-8-x86_64-20220412-dvd1.iso",
            "dud":[
                "/Linux/DUD/dd-mpt3sas-37.101.00.00-1.el8_5.elrepo.iso"
            ]
        }
    ]
}

**Comment by 18photos** [comment]
H

> Please upload the `ventoy.json` file here for analyse.

Here is my json script.
Please help me :(


{
    "auto_memdisk":[
        "/Linux/DUD/dd-mpt3sas-37.101.00.00-1.el8_5.elrepo.iso"
    ],
    "dud":[
        {
            "image": "/Linux/RockyLinux/Rocky-8.5-x86_64-dvd1.iso",
            "dud":[
                "/Linux/DUD/dd-mpt3sas-37.101.00.00-1.el8_5.elrepo.iso",
                "/Linux/DUD/dd-mptsas-3.04.20-6.el8_5.elrepo.iso"
            ]
        },
        {
            "image": "/Linux/CentOS/CentOS-8.1.1911-x86_64-dvd1.iso",
            "dud":[
                "/Linux/DUD/dd-mpt3sas-28.100.00.00-2.el8_1.elrepo.iso"
            ]
        },
        {
            "image": "/Linux/CentOS/CentOS-Stream-8-x86_64-20220412-dvd1.iso",
            "dud":[
                "/Linux/DUD/dd-mpt3sas-37.101.00.00-1.el8_5.elrepo.iso"
            ]
        }
    ]
}

**Comment by ventoy** [comment]
You don't need to add `inst.dd` boot parameter manually. The configuration in ventoy.json is enough.
I just tested `Rocky-8.5-x86_64-dvd1.iso` and the two dud iso files and it worked.

You can add `rd.break=pre-mount`  boot parameter, it will pause at a debug shell when boot, then you can run `modinfo  mptsas`  to check the loaded mptsas driver.


With DUD configuration.
![image](https://user-images.githubusercontent.com/59477474/165288599-a505ae3d-3dee-4ae2-b93a-97330dda9079.png)



Without DUD configuration (only boot RockLinux ISO file in normal mode)
![image](https://user-images.githubusercontent.com/59477474/165288641-454c9615-1b3f-45c6-96fa-af1da466fd0a.png)

**Comment by 18photos** [comment]
> You don't need to add `inst.dd` boot parameter manually. The configuration in ventoy.json is enough. I just tested `Rocky-8.5-x86_64-dvd1.iso` and the two dud iso files and it worked.
> 
> You can add `rd.break=pre-mount` boot parameter, it will pause at a debug shell when boot, then you can run `modinfo mptsas` to check the loaded mptsas driver.
> 
> ![image](https://user-images.githubusercontent.com/59477474/165290108-2c15e5cd-4c30-4072-a785-00143eb13887.png)
> 
> ![image](https://user-images.githubusercontent.com/59477474/165290123-482343b8-44d4-4361-b21f-f075ee8b6f50.png)


You say.. "You don't need to add inst.dd boot parameter manually. The configuration in ventoy.json is enough.".

It means~ it works only ventoy.json?

If I use my json script, then It works?

Accourding I known,  "DUD cdrom connect" and  "Tab Key" and "inst.dd" and "Select Driver" on  Rocky Linux Installation.

But, There is no selection drivers with ventoy.json.

**Comment by ventoy** [comment]
"DUD cdrom connect" and "Tab Key" and "inst.dd" and "Select Driver"  is the official way to use DUD with RHEL/CentOS/Rocky.
But when you use Ventoy DUD plugin, it's different from that.
You just need to set `ventoy.json` and that's all.  
You don't need to do "DUD cdrom connect" and "Tab Key" and "inst.dd" and "Select Driver"  anymore.
Ventoy will automatically inject the dud iso files to the initrd and add `inst.dud=file:/xxx.iso` boot parameter and all of these work is transparent to you.  So the driver in the dud iso file will be automatically loaded without prompt.

**Comment by 18photos** [comment]
> "DUD cdrom connect" and "Tab Key" and "inst.dd" and "Select Driver" is the official way to use DUD with RHEL/CentOS/Rocky. But when you use Ventoy DUD plugin, it's different from that. You just need to set `ventoy.json` and that's all. You don't need to do "DUD cdrom connect" and "Tab Key" and "inst.dd" and "Select Driver" anymore. Ventoy will automatically inject the dud iso files to the initrd and add `inst.dud=file:/xxx.iso` boot parameter and all of these work is transparent to you. So the driver in the dud iso file will be automatically loaded without prompt.

Thank you for reply.

But there are many errors...

I don't know why...

I attached log picture.

Thank you Ventoy team.


![KakaoTalk_20220427_165357715_01](https://user-images.githubusercontent.com/31121613/165469832-c4d9549d-1d9c-47d9-9d6a-bf629d185570.jpg)

**Comment by ventoy** [comment]
Checksum the dud iso files to make sure that they are not corrupted.
When you boot into Ventoy menu, select the dud iso file and press `m` to checksum it.
This is my result:
![image](https://user-images.githubusercontent.com/59477474/165474030-14f37ee4-05ba-44ca-9c3b-acc4183e5bd9.png)

![image](https://user-images.githubusercontent.com/59477474/165474119-e27aba7d-780d-4546-a3c7-79e67d3786c0.png)

**Comment by 18photos** [comment]
> 

I

> Checksum the dud iso files to make sure that they are not corrupted. When you boot into Ventoy menu, select the dud iso file and press `m` to checksum it. This is my result: ![image](https://user-images.githubusercontent.com/59477474/165474030-14f37ee4-05ba-44ca-9c3b-acc4183e5bd9.png)
> 
> ![image](https://user-images.githubusercontent.com/59477474/165474119-e27aba7d-780d-4546-a3c7-79e67d3786c0.png)



I was saw it also..
My file's md5 checksum is same with yours.

**Comment by ventoy** [comment]
You just set 2 dud iso files for the Rock ISO, so there should be only 2 ventoy_dudx.iso but why there are 
/ventoy/ventoy_dud0.iso
/ventoy/ventoy_dud1.iso
/ventoy/ventoy_dud2.iso
/ventoy/ventoy_dud3.iso
/ventoy/ventoy_dud4.iso
/ventoy/ventoy_dud5.iso
?
I don't known.

Try just set only 1 dud iso file.

**Comment by ventoy** [comment]
![image](https://user-images.githubusercontent.com/59477474/165479819-105eb649-43b7-4fa8-8f98-4ff6f8b1845f.png)

**Comment by ventoy** [comment]
What happened?

**Comment by 18photos** [comment]
> What happened?

I can't use ventoy for my old server m/c with dud.

there are mount errs...

I will buy usb-cdrom.

thank you for your reply.

**Comment by ventoy** [comment]
It can work in VMware and it should also work in your server.
There must be something wrong in your configuration.
1. Can it work if you test in a new PC/laptop ?
2. Checksum the rocky ISO file itself just like you did for the dud iso file
