### ISSUE TITLE
[Success Image Report]: Feren OS 2022.04

### ISSUE THREAD

**Issue by noyannus** [ventoy/Ventoy#1594]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.72

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

Feren-OS-standarddt.iso

### Image file checksum type

SHA256

### Image file checksum value

570602ec06a63011cee8424d7d0e0472173530f8bd3a1b45b319635bbd776126

### Image file download link (if applicable)

https://ferenos.weebly.com

### Test envrionment

framework laptop

### More Details?

scaling of display and taskbar survived reboot

the iso has no version, it is 2022.04

the laptop's URL is https://frame.work/nl/en

**Comment by ventoy** [comment]
Thanks!
