### ISSUE TITLE
Lenovo ThinkPad X250

### ISSUE THREAD

**Issue by Sokoloft** [ventoy/Ventoy#1596]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.73

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

PNY

### Image file checksum (if applicable)

No.

### Image file download link (if applicable)

Multiple Tools/Distro images.

### What happened?

Hello,

I have a Lenovo ThinkPad X250.
Ventoy will not boot into an ISO on this machine.

It will on every other machine I've tried it on. Just not my X250.

I can get to the ventoy boot screen. Whenever I select an ISO, the activity LED on the USB flashes for a moment. Then its just a black screen. No flashing from the LED.

The drive I'm using is the following:
PNY 32GB Attaché 4 USB 2.0

I mentioned this issue on a discord. Someone asked me if I had secure boot on. It is disabled.
The laptop is set to boot only into UEFI as well.

The issue is similar to [this](https://github.com/ventoy/Ventoy/issues/635) closed issue I recently commented on.

Thanks.

**Comment by AnomSanjaya** [comment]
have u try Wimboot/GRUB mode?

**Comment by Sokoloft** [comment]
> have u try Wimboot/GRUB mode?

No, and I'm not sure what you mean. I have an installation of Manjaro on the laptop so I have grub.

**Comment by ventoy** [comment]
@Sokoloft 
Please refer:
https://www.ventoy.net/en/doc_grub2boot.html
https://www.ventoy.net/en/doc_wimboot.html

for wimboot/grub2 mode.

**Comment by Sokoloft** [comment]
Okay. Linux distros will boot with the grub2 mode. 

Thanks.
