### ISSUE TITLE
[issue]: Clear Ventoy without data loss

### ISSUE THREAD

**Issue by candrapersada** [ventoy/Ventoy#1599]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.73

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

300 GB

### What happened?

how to Clear Ventoy without data loss?
![image](https://user-images.githubusercontent.com/36833664/165834437-55a84be1-8524-4f2a-8e00-d9e8eaaf0191.png)

**Comment by ventoy** [comment]
This `Clear Ventoy` menu will clear both ventoy boot data and the the normal data.
If you just want to clear ventoy boot data and keep the normal data you can do it manually as follows:
```
1. Delete the 32MB VTOYEFI partition.
2. Clear the first 400 bytes of the 1st sector (MBR) of the USB stick.
```

**Comment by candrapersada** [comment]
> `1. Delete the 32MB VTOYEFI partition.`

how to Delete the 32MB VTOYEFI partition in Windows?

> `2. Clear the first 400 bytes of the 1st sector (MBR) of the USB stick.`

how to Clear the first 400 bytes of the 1st sector (MBR) of the USB stick in Windows?

**Comment by ventoy** [comment]
You can use some tools like diskgenius or just google to find some method.

**Comment by ventoy** [comment]
Another simple way is just put VentoyLiveCD iso file in the Ventoy USB stick and reboot your computer and boot into the LiveCD.
After you boot into it, press `Ctrl+Alt+F2` to enter shell and use linux command to do this as follows (assume the USB is /dev/sdb):
```
parted -s /dev/sdb rm 2
dd if=/dev/zero of=/dev/sdb bs=1 count=400
sync
```
