### ISSUE TITLE
[issue]: 安装凝思6.0.60系统出现探测到错误的光盘现象。

### ISSUE THREAD

**Issue by yee-lab** [ventoy/Ventoy#1600]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.74

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

aigo

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

http://www.linx-info.com/download/os/6.0.60/

### What happened?

点击Install 后，会出现探测到错误的光盘的界面，安装无法继续进行，iso镜像完整性校验过的。
![6a33af47a1337d6fd072432ce3a149d](https://user-images.githubusercontent.com/19340810/165893848-6d45907b-85e0-43cb-bb81-3d5a0c1801ed.jpg)

**Comment by ventoy** [comment]
@yee-lab 
试试这个CI版本： 
https://github.com/ventoy/Ventoy/actions/runs/2245185023
https://www.ventoy.net/cn/doc_github_ci.html

**Comment by yee-lab** [comment]
我试了这个CI版本，没有问题了。

**Comment by ventoy** [comment]
1.0.75 release
