### ISSUE TITLE
can't boot hdat2cd_lite_74.iso

### ISSUE THREAD

**Issue by Foul** [ventoy/Ventoy#1601]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.74

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

64GB

### Disk Manufacturer

Kingston

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://www.hdat2.com/files/hdat2cd_lite_74.iso

### What happened?

Not boot at all !

Tried with : 

https://www.hdat2.com/files/hdat2cd_lite_74.iso and https://www.hdat2.com/files/hdat2cd_74.iso

thx !

**Comment by ventoy** [comment]
Press `F1` (Memdisk mode) firstly and then select the ISO file to boot.  （https://www.ventoy.net/en/doc_memdisk.html）
Besides, the ISO file itself only support Legacy BIOS mode, so you must make sure that your computer is in Legacy BIOS mode.

**Comment by Foul** [comment]
now boot but stop here : https://img.super-h.fr/images/ac285a999abee697fda1cf2da73684d8.jpg

i'm on legacy bios and legacy/mbr usb key

**Comment by ventoy** [comment]
Currently I have no idea. It does work in my laptop.
![image](https://user-images.githubusercontent.com/59477474/165953687-ebdc3ec3-c10d-408f-9d99-94edf05adb76.png)
