### ISSUE TITLE
[issue]: Ventoy USB thumb drive boot error: "alloc magic is broken at 0x890aeXXX: 891349XX Aborted. Press any key to exit." after VentoyPlugson.exe configures Menu Tip plugin.

### ISSUE THREAD

**Issue by 2Torr** [ventoy/Ventoy#1602]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.74

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

32GB

### Disk Manufacturer

SanDisk

### What happened?

After using the latest VentoyPlugson.exe to configure the Menu Tip plugin (e.g. only changing the color to "white"), a previously good Ventoy USB thumb drive refuses to boot with the error: "alloc magic is broken at 0x890aeXXX: 891349XX Aborted. Press any key to exit."

in \ventoy\ventoy.json file on the USB thumb drive, the offending lines seem to "left" and "top" with "" value:
...
"menu_tip":{
        "left": "",
        "top": "",
...

I believe that in JSON format, an option with "" for its value is supposed to simply use the default value, however, Ventoy boot process can't handle these statements for some reason, and refuses to boot with the error message mentioned earlier.
When I remove those statements in ventoy.json file, the USB thumb drive boots properly again. 
I think that adding support in Ventoy boot process for blank options in ventoy.json file might be a good solution.
Alternatively, VentoyPlugson,exe could simply write the default values instead of "" values.

Also, there are some webpage quirks in configuring the Menu Tips Plugin using VentoyPlugson.exe:
When I first ran VentoyPlugson.exe to configure Menu Tips color, the Menu Tips plugin webpage shows the default values of left = 10%, top = 81%, and color = blue, but it does not show any previously-configured Menu Tips (area is completely blank).

Then I click on any other tab at the top of the page (e.g. menu_tip_legacy), then back to menu_tip tab, and now it shows the previously configured Menu Tips, however the left, top, and color options under Tip Style now show blank (no content).

Next I change the tip color to white, then click on any other tab at the top of the page (e.g. menu_tip_legacy), then back to menu_tip tab, and the tip color now becomes blank (the same with top and left options) again.

In the ventoy.json file, the following lines appear under "menu_tip":(
...
        "left": "",
        "top": "",
        "color": "white",
...
so it does record the new white value.

When I close down VentoyPlugson.exe, start it up again and then go to Menu Tip plugin again,
Menu Tips, left, and top fields are all blank, but color is white.
Again, I click on any other tab at the top of the page (e.g. menu_tip_legacy), then back to menu_tip tab, and now it shows the previously configured Menu Tips, however the left, top, and color options under Tip Style all show blank (no content).

Would someone please look into these issues? I've attached a zip file containing my sample ventoy.json file generated with VentoyPlugson.exe which does not boot: "ventoy.json", and a copy of this file which I manually edited (removing "left": "",
        "top": "", lines) which boots fine: "ventoy_works.json".
[ventoy.zip](https://github.com/ventoy/Ventoy/files/8592915/ventoy.zip)

Thanks! 
2Torr

**Comment by ventoy** [comment]
Please try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/2249241501
https://www.ventoy.net/en/doc_github_ci.html

**Comment by 2Torr** [comment]
Thank you, @ventoy, very much for the quick fix.
The new ci version fixes the problem and works great!

**Comment by mina-andajos** [comment]
Should I reinstall ventoy on disk? I tried updating it on disk and still got the same problem @2Torr

**Comment by 2Torr** [comment]
@mina-andajos so, you updated to 1.0.75 release and still have the same problem? Updating should have worked. You should not need to reinstall 1.0.75.
You can also try installing 1.0.75 to a different USB drive to make sure the issue disappears.

**Comment by mina-andajos** [comment]
> @mina-andajos so, you updated to 1.0.75 release and still have the same problem? Updating should have worked. You should not need to reinstall 1.0.75.
> You can also try installing 1.0.75 to a different USB drive to make sure the issue disappears.
> 

yeah I updated ventoy on drive and the issue persisted.

**Comment by MiceRus** [comment]
Version 1.0.99 the problem is back.
Just tried on Acer Aspire C22-963_W and got this error

**Comment by teymuur** [comment]
I had the same issue. Disabling themes worked for me. But any theme I used broke ventoy. version 1.1.0

**Comment by smpltechno** [comment]
Same issue on 1.1.05 and previous ci release that fixed this before. Using HP laptop, fails to boot with Secure Boot "Verification Failed: ((0x1A) Security Violation. Disable Secure boot and all other BIOS security features causes the alloc magic broken error. HP 1040 G9, G10, and HP 860 G8, G9... probably any HP laptop released in last ~2 years.

**Comment by mertgoksel** [comment]
Same issue on 1.1.05. Tried for both secure boot on and off. Tried with another laptop which had secure boot off and it persisted. Maybe the issue is with win11 24h2 iso?

**Comment by c00lpython** [comment]
how fix that? i tried to load my usb , but alloc magic is broken at: 0x54c5ef00 : 54ce4e77

**Comment by mertgoksel** [comment]
> how fix that? i tried to load my usb , but alloc magic is broken at: 0x54c5ef00 : 54ce4e77

what fixed it for me was to buy a new usb stick, apparently the issue wasnt ventoy but the written iso was broken because of usb degradation.

**Comment by c00lpython** [comment]
nuh uh, I has DataTraveler 16 GB .I find out like this: just delete ventoy(not Ventoy in usb, only Plugson) , make usb without custom

**Comment by Znerwicowany** [comment]
GIGABYTE H610M S2H V3 DDR4, i7-12700F, 32GB RAM, Pendrive SanDisk Ultra 2w1 3.0 32GB:
V1.1.05 -> SergeiStrelecWinPE -> alloc magic is broken at 0x172502e0: 172d6217 Aborted.
V1.1.12 -> SergeiStrelecWinPE -> Freeze entire machine (even caps/numlock dont blink)
V1.1.12 -> PartedMagic -> Run normally
Hmmm, two other pendrives work fine:
1. Sandisk Gold 128GB ULTRA LUXE USB 3.2 Gen 1
2. Noname 32GB 2.0
AD.1: Some programs dont works in this running SSWinPE on this pendrive.

Generaly - sometimes i have this issue also.
