### ISSUE TITLE
[issue]: Ventoy doesn't see Sony Memory Stick Pro DUO

### ISSUE THREAD

**Issue by GribanovIvan** [ventoy/Ventoy#1604]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.74

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

8GB

### Disk Manufacturer

Sony

### What happened?

Ventoy2Dick doesn't see Memory Stick Pro Duo on windows 7
![](https://cdn.discordapp.com/attachments/885935550463369257/970398866295889990/unknown.png)
![](https://cdn.discordapp.com/attachments/885935550463369257/970401050311950376/unknown.png)
![](https://cdn.discordapp.com/attachments/885935550463369257/970401456840659004/unknown.png)
_not mine screenshots_

**Comment by GribanovIvan** [comment]
https://cdn.discordapp.com/attachments/885935550463369257/970718496646365224/log.txt

**Comment by ventoy** [comment]
Try enable Option---->Show All Devices
![image](https://user-images.githubusercontent.com/59477474/166273656-2fb099ba-830d-4d32-87b8-8cc0b2157cff.png)

**Comment by GribanovIvan** [comment]
![](https://cdn.discordapp.com/attachments/885935550463369257/972134272980910090/unknown.png)
works!
need any other information to whitelist this device?

**Comment by ventoy** [comment]
OK, good news.
Ventoy can be installed on USB drive or local disk. To prevent misoperation, Ventoy2Disk.exe only lists USB drives by default.
You can toggle the `Show all devices` option then all the disks will be listed. But at this time, you must be very careful and don’t choose the wrong disk.

This device has a SCSI bus type (not USB type) according to the log:
```
PhyDrv:1 BusType:SCSI Removable:1 Size:8GB(8000110592) Name:Realtek PCIE Card Reader
```
So it was filted by default.

When it shows in the device list, then there is nothing special to do to whitelist it, just click install button.
