### ISSUE TITLE
U盘测试工具，可以超链接 官方网站 或者 原版出处吗？？？《关于U盘硬件问题的说明》

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#1605]
《关于U盘硬件问题的说明》这里，红框里面。
有的测试工具，特别是 chipgenius，一直都找不到原版官网。第三方网站下载的报毒。
这三款推荐的U盘测试工具，可以超链接 官方网站 或者 原版出处吗？？？
![image](https://user-images.githubusercontent.com/69227436/166191554-2f17f1c9-8b39-47eb-aa0a-dfa281d91bbb.png)

**Comment by ventoy** [comment]
这种就不需要了，我也是网上随便找一个下载用的，比较大的下载站下的一般都没问题。
至于报毒就看你自己信不信任了。Ventoy软件很多时候也报毒。
