### ISSUE TITLE
usb boots to grub cmd line

### ISSUE THREAD

**Issue by atasoyk** [ventoy/Ventoy#161]
hello, I created a Ventoy disk and copied an ISO file but only command screen comes up. Can't do anything else. See below. Tnx

GNU GRUB version 2.04
Minimal BASH-Like .....
grub>

**Comment by ventoy** [comment]
Hi,
Please give detail about:
1. UEFI or Legacy BIOS ?
2. You test enviroment
3. The USB disk type and capacity

**Comment by corentiny1** [comment]
Hello, Same problem here.
I tried with several usb keys, no name, sandisk, etc. And only one cause problem, this is an Sandisk 256GB : https://shop.westerndigital.com/en-us/products/usb-flash-drives/sandisk-ultra-dual-drive-m30-usb-3-1-type-c#SDDDC2-256G-A46

Previously I use this usb key for data storage then Windows 10 installation drive.
I'm on Windows 10 Pro version 1909 64bit, I use Ventoy 1.0.11 and 1.0.12, same problem.
My PC is an old Asus P6X58D-E (BIOS) with intel i7 930 and 12Gb RAM.

What I did : 
- enable or disable secure boot
- install, and the program confirm installed version
- format key with windows
- format key with diskpart and clean
- plug in different usb port : front, rear, usb2 or usb3

nothing work, but with other no name key 8Gb, that's works great !

After boot menu, I choose USB3 Sandisk (with ventoy installed), and this is what I have : 
![IMG_3937](https://user-images.githubusercontent.com/221623/83438147-36f3d380-a441-11ea-8009-e05560df99dc.JPG)

**Comment by corentiny1** [comment]
I did more tests :
I use my laptop to make a new installation of Ventoy (with secure boot) on Sandisk 256GB
My laptop is a Dell XPS 15" 9560 (2017) with intel core i7-7700HQ, 16GB RAM, Windows 10 Home 64bit
Everything is ok, the usb key with Ventoy works perfectly on my dell xps
I plugged this same key in my PC (Asus P6X58D-E), again the same problem : grub prompt
You can watch the boot sequence in this short video : https://www.youtube.com/watch?v=87u3vF2FXmY

Pictures of boot sequence on my dell xps 15 : 
![IMG_4018](https://user-images.githubusercontent.com/221623/83511516-0d818900-a4cf-11ea-933d-04404f1c3b59.JPG)
![IMG_4019](https://user-images.githubusercontent.com/221623/83511560-1c683b80-a4cf-11ea-9596-6771cd163dbd.JPG)

**Comment by ventoy** [comment]
Maybe something about the Legacy BIOS  access range limit. 
You can google with Legacy BIOS  137GB  and you can get some information.

**Comment by corentiny1** [comment]
Hum...
What I tried :
- Rufus 3.10.1647 (partition scheme : MBR, Target system : BIOS of UEFI, Checked : Add fixes for old NIOSes, file system FAT32, etc
- ISO : ubuntu server 18.04.LTS
And it works on my Dell XPS 15" an on the old PC Asus P6X58D-E, you can see that on this video : https://www.youtube.com/watch?v=dgjVBgGjPz0

So my Legacy BIOS work with my Sandisk 256GB, I suppose the problem come from Ventoy, what you think ?

**Comment by ventoy** [comment]
OK, so to speak.

When you use rufus or other tool to make bootable USB, the file will be write to the USB, usually from the begginning of the USB disk. So normally the range out of the limit (137GB+)  will not be used.

But ventoy's files are in the second partition which is at the end of the USB disk, that will obviously out of the limit of the legacy BIOS.

So if it's OK to use ventoy with a small USB (32GB/64GB) and failed with 256GB  USB, that is most likely the reason.

In the next release I will provide a workaround about this. But that is just a workaround, you should known that, if you put many ISO files in the 1st partition and some of them maybe out the range of the BIOS limit. And these ISO files will fail to boot. This is a BIOS limitation, no software solution.

**Comment by corentiny1** [comment]
Ok, thanks for the explain. Anyway Ventoy is a great tool, good luck for the future.

**Comment by atasoyk** [comment]
with quemu and direct boot it works fine, i used it in some places and is very easy to use. just copying iso file is enough.. i tried with virtualbox usb boot but it didn't work. thats not a problem because its was for testing. thanks for interest

**Comment by ventoy** [comment]
Ventoy-1.0.13 add a workaround for the Legacy BIOS access limitation.
[https://www.ventoy.net/en/doc_legacy_limit.html](https://www.ventoy.net/en/doc_legacy_limit.html)

**Comment by brokewindow** [comment]
I get the GNU GRUB.
MSI mb, old intel processor.
32gb USB 3.01415
latest KALI.iso
Is there a work around from inside the GNU GRUB?
My windows is too broken to open.

**Comment by rayluo** [comment]
Thanks @ventoy Long Panda for Ventoy project!

1. Ventoy has been working fine when I'm using usb flash disk. So, I believe I know the usual Ventoy installation reasonably well.

2. Today I try install Ventoy into a 500GB external USB hard disk. The Ventoy installation process went smooth, but when booting I got the same error:

![Same error](https://user-images.githubusercontent.com/221623/83438147-36f3d380-a441-11ea-8009-e05560df99dc.JPG)

3. So, I tried [workaround 1 for the legacy 137gb limit](https://www.ventoy.net/en/doc_legacy_limit.html), but then it gave me this error instead.

![non-standard](http://reboot.pro/uploads/monthly_09_2020/post-17818-0-08052000-1600075396.jpg)

4. So, I went back to redo my 500 GB external hard drive using the "workaround 2". But then, I still get the same error at step 2.

* My current laptop uses legacy BIOS, not UEFI.
* Today it is my first time using ventoy 1.0.27. Shall I downgrade to use older version of ventoy?

**Comment by tfraley** [comment]
Is there a clear fix for this. 
I've spent the day trying to figure this out. Idea was to be simple but seems it's more work than I thought. 
I have 2 different USB sticks Scandisk and Samsung. 
Initially installing using the Ventoy live on a laptop. After a few attempts of that not working.s I ran through it with a windows VM and the application with the same results. 

Why is this being such a pain and the ass?

**Comment by steve6375** [comment]
First - check that the USB device is not a fake. There are millions of USB flash drives which are fakes and do not have the correct capacity. Test the drive under Windows using FakeFlashTest.exe. Or format the drive as NTFS, fill it with at least 64GB of video files and then play the last video file from the USB drive.
Secondly - if the USB drive is larger than 128GB, you need to reserve space at the end of the drive so that the first two partitions do not exceed 128GB. See https://www.ventoy.net/en/doc_legacy_limit.html
How many different systems did you test the Ventoy USB drive on? Did you try booting the USB drive from a VM?
Since 100,000s of people can boot to Ventoy without issues, there is an issue with either your USB drive or your computer. You need to describe these. Are you Legacy or UEFI-booting? What capacity are you USB drives, Make/Model/age of computer, etc.
