### ISSUE TITLE
windows 10 moded version tested

### ISSUE THREAD

**Issue by GM779** [ventoy/Ventoy#1612]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1,0.74

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

WIN10.PRO.20H2.SUPERLITE+COMPACT.U3.X64.GHOSTSPECTRE.(N-V3) without custom boot

### Image file checksum type

MD5

### Image file checksum value

81575d6d0c9f3851ae33771d89cf777b

### Image file download link (if applicable)

http://ghostspectre.the-ninja.jp/20H2.X64.html

### Test envrionment

Hp 8770w

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
