### ISSUE TITLE
[Question]: regarding windows ISO and autounattend.xml

### ISSUE THREAD

**Issue by KrinalPatel889** [ventoy/Ventoy#1613]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.74

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

64

### What happened?

Hi  @ventoy how do you insert unattended.xml file in Windows ISO in Ventoy?

Is it possible to do the same with ei.cfg file?

I tried injection plugin but I guess it's too late when file is injected and doesn't work thay way.

That's why I want to understand if it's possible to do something like unattended.xml with ei.cfg?

**Comment by ventoy** [comment]
You can only use unattended.xml.
Please refer: [https://forums.ventoy.net/showthread.php?tid=1991](https://forums.ventoy.net/showthread.php?tid=1991)
