### ISSUE TITLE
[issue]: 

### ISSUE THREAD

**Issue by oopo0** [ventoy/Ventoy#1617]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.74

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

16GB

### Disk Manufacturer

Netac

### What happened?

![图片](https://user-images.githubusercontent.com/67009994/167247223-fe1818ad-be3e-4c04-b9cf-74da2ef40bf2.png)

在Windows 8.1中无法通过[Toucan](http://portableapps.com/toucan)的备份方式写入压缩包

**Comment by ventoy** [comment]
没明白你说的是什么问题。能不能详细描述一下。是Ventoy无法安装呢，还是安装以后无法启动某个ISO文件呢？
