### ISSUE TITLE
Request: Can you add a shortcut key(F4,F5,e.g.)for Grub2FM to your project? 

### ISSUE THREAD

**Issue by crasadure** [ventoy/Ventoy#162]
Hi Ventoy
as you know, G2FM project producer(a1live) added Ventoy support to his project.
so, can you add your project G2FM support?
You can integrate
*grubfmx64.efi
*grubfmia32.efi
*grubfm.iso
files to your FAT partition and
you can add a shortcut key(F4,F5,e.g) for g2fm and ventoy users can use g2fm and ventoy with together.. :)
what about you my idea?
ıt can be very well for users 👍

**Comment by ventoy** [comment]
Hi,
Since agFM 7.1.0, a **grubfm_multiarch.iso** is released along with other files.
And this iso file is also Ventoy Compatible.
You can just put the iso file in the USB and boot it from Ventoy as a normal iso file.

**Comment by crasadure** [comment]
Thanks guy :+1:
