### ISSUE TITLE
[Success Image Report]: windows 11 21h2 2022-04-19

### ISSUE THREAD

**Issue by waitsaber** [ventoy/Ventoy#1623]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.70

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

Windows 11 (business editions) (updated April 2022) (x64) - DVD (Chinese-Simplified)

### Image file checksum type

MD5

### Image file checksum value

DA2C5A5D22D78BF18BC3705A5F260D54

### Image file download link (if applicable)

https://next.itellyou.cn/Original/#

### Test envrionment

hasee G8-DA7NT

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
