### ISSUE TITLE
[Success Image Report]: 天意U盘维护系统全功能5.1版

### ISSUE THREAD

**Issue by waitsaber** [ventoy/Ventoy#1624]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.70

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

天意U盘维护系统全能版5.1.iso

### Image file checksum type

MD5

### Image file checksum value

5DDBDC1D3C6CB0F7A9CFFB3938CCAED2

### Image file download link (if applicable)

https://bbs.winpe.cc/thread-126407-1-1.html

### Test envrionment

GIGABYTE B85M-D2V-SI/I3-4150

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
