### ISSUE TITLE
[Success Image Report]: Kubuntu 22.04 LTS 64-bit

### ISSUE THREAD

**Issue by DuckOfTheBooBoo** [ventoy/Ventoy#1627]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.74

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

kubuntu-22.04-desktop-amd64.iso

### Image file checksum type

SHA256

### Image file checksum value

56ed1824de37c645f65a8c92545d45126a83cd93a79979b27cba553c849100d5

### Image file download link (if applicable)

https://cdimage.ubuntu.com/kubuntu/releases/22.04/release/kubuntu-22.04-desktop-amd64.iso

### Test envrionment

Lenovo B40-80

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
