### ISSUE TITLE
[Success Image Report]: 50MB Windows 7 PE by Khatmau

### ISSUE THREAD

**Issue by work-iamvinh123** [ventoy/Ventoy#1630]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.74

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

7PE50.iso

### Image file checksum type

MD5

### Image file checksum value

 4eb1ad409533a885132eb39869f835d1

### Test envrionment

Custom Core 2 Duo PC

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
