### ISSUE TITLE
[issue]: Ultramarine linux (flagship) failed to boot

### ISSUE THREAD

**Issue by rilysh** [ventoy/Ventoy#1631]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.74

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

16GB

### Disk Manufacturer

Strontium

### Image file checksum (if applicable)

No.

### Image file download link (if applicable)

https://lapis.ultramarine-linux.org/pub/ultramarine/36/Flagship/x86_64/iso/Ultramarine-Flagship-Live-x86_64-36-1.0.iso

### What happened?

Ultramarine Linux (Flagship edition) was failed to boot it up, Ventoy showed that the iso file isn't bootable, I've not yet tried other flavors of this distro only tested the flagship edition and encountered with it.

Error stack:
```
error: File (hd0, 1)/Ultramarine-Flagship-Live-x86_64-36-1.0.iso is not bootable.
chain empty failed
press Enter to continue...
```

An image:
![image](https://user-images.githubusercontent.com/71683721/169101684-c4590173-92ed-47f9-8295-b5f1abdcde2b.png)

**Comment by ventoy** [comment]
1. When you boot into Ventoy menu, select the ISO file and press `m` to calculate the checksum 
2. Connect the ISO file directly to the CD/DVD of a VM(e.g. VirtualBox/VMWare) and to see whether it can boot.

**Comment by steve6375** [comment]
Works OK for me (MBR\Legacy and UEFI64). Maybe you have a bad USB (fake) or bad ISO (corrupt) or bad BIOS?

**Comment by iyyapunna** [comment]
> 1. Saat Anda boot ke menu Ventoy, pilih file ISO dan tekan `m`untuk menghitung checksum
> 2. Hubungkan berkas ISO langsung ke CD/DVD VM (misalnya VirtualBox/VMWare) dan lihat apakah ia dapat di-boot.

![Image](https://github.com/user-attachments/assets/758b6adf-9e5a-4a72-bd07-78abf1c69b86)
