### ISSUE TITLE
[Success Image Report]: Proxmox VE - proxmox-ve_7.2-1.iso

### ISSUE THREAD

**Issue by EVOTk** [ventoy/Ventoy#1632]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.73

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

proxmox-ve_7.2-1.iso

### Image file checksum type

SHA256

### Image file checksum value

ff356eaaff865894a889ee15d29154333539fc254c4edb5736c55449ddf9675c

### Image file download link (if applicable)

https://www.proxmox.com/en/downloads/item/proxmox-ve-7-2-iso-installer

### Test envrionment

Geekom Mini IT8 – GM08i5T

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
