### ISSUE TITLE
[issue]: the newest versions of fedora (36) and redhat (9) wont boot

### ISSUE THREAD

**Issue by Windows-Guy** [ventoy/Ventoy#1636]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.74 plus ive tried the latest cli

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

64GB

### Disk Manufacturer

Mushkin

### Image file checksum (if applicable)

Yes.

### What happened?

I can secure boot and install win 10, 11, mint 20.3, tails 5, hbcd, backbox 7, recuezilla focal
But not fedora36 or rhel9
They both just lock the machine up before during and after 
choosing the install options in their command line startup

ive tried exfat ntfs defragging etc
My guess is Its something to do w their secure boot key process

EDIT: ok today i turned off secure boot and later turned it back on and now it boots. 
So maybe i just have a goofy bios.

**Comment by Windows-Guy** [comment]
The problem started again after my last post and before 1.0.75 ( not sure thats right)

but i did upgrade today and download fedora 36 and rhel 9 to test 1.0.75
And fedora boots to let me pick run live or scan media and after i pick it goes black forever
Redhat starts to display use up down keys to and locks up before it displays the selection screen

i have a 64 gb flash drive w 50 gb at the end. Im on an hp spectre x360 with linux mint installed 4 partitions boot root(ext4) swap and a big windows ntfs at the end

**Comment by Windows-Guy** [comment]
Still locks up on version 76
It boots 4 other linux distros
It seems to be an issue w the redhat line

**Comment by Windows-Guy** [comment]
Redhat 9 install still locks up at boot on version 78
Not sure about fedora. I gave up on it

**Comment by steve6375** [comment]
Both UEFI64 boot OK on my Lenovo IdeaPad 300 from Ventoy.

However, under VBox 5  VM booting from Ventoy USB drive:

![image](https://user-images.githubusercontent.com/1469350/178140008-2a0973a5-05ea-4774-8d63-b0b24fc7330b.png)
![image](https://user-images.githubusercontent.com/1469350/178140011-db59e3d9-417d-4757-8ab3-b698c4e98b5e.png)
![image](https://user-images.githubusercontent.com/1469350/178139995-d9356ee4-3806-4207-8090-b884a4b25479.png)
Lockup !

But RedHat is OK under VBox 5 too.
![image](https://user-images.githubusercontent.com/1469350/178140059-d5b88de3-b661-40d2-85d4-31c998fd6c9f.png)
![image](https://user-images.githubusercontent.com/1469350/178140068-b6ed31b5-7e81-40f2-9624-5d32d70168fc.png)
![image](https://user-images.githubusercontent.com/1469350/178140091-82988f37-439e-4127-bc63-45433941e6dd.png)
![image](https://user-images.githubusercontent.com/1469350/178140102-a966e6bf-1877-4a2e-b68d-ce5cbaa664d6.png)

**Comment by Windows-Guy** [comment]
Redhat 9, fedora 36, and now mint 21 will not secure boot now on 1.0.79 and also rescuezilla 2.4

**Comment by Windows-Guy** [comment]
Just got a new flash drive and it does the same thing

**Comment by Windows-Guy** [comment]
It all works now
