### ISSUE TITLE
[issue]: Debian installation fails when using Ventoy Auto Installation Plugin

### ISSUE THREAD

**Issue by asheroto** [ventoy/Ventoy#1638]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.74

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128GB

### Disk Manufacturer

Hyper-V

### Image file checksum (if applicable)

No.

### What happened?

I used the default Debian preseed.cfg script [here](https://www.ventoy.net/download/preseed.cfg.txt) and the installation fails with "Installation step failed" on "Select and install software". Pressing enter and attempting to continue manually fails with the same error.

I have tried this with:
- Debian 11.2.0 net install [ISO](https://cloud.debian.org/images/archive/11.2.0/amd64/iso-cd/debian-11.2.0-amd64-netinst.iso)
- Debian 10.12.0 net install [ISO](https://cloud.debian.org/images/archive/10.12.0/amd64/iso-cd/debian-10.12.0-amd64-netinst.iso)

Side note: does not work with Debian DVD ISO or net install ISO

![vmconnect_3yigsKFhsC](https://user-images.githubusercontent.com/49938263/169726846-56cfb811-fac0-41f1-abf9-7ebe73b5f847.png)

**Comment by ventoy** [comment]
When the error occurs press `Ctrl+Alt+F4` to see the error log, take a photo about it and upload here.

**Comment by ventoy** [comment]
Try this `preseed.cfg`  https://www.ventoy.net/download/preseed10.cfg.txt

**Comment by asheroto** [comment]
Just tried the pressed.cfg file and still got an error

![image](https://user-images.githubusercontent.com/49938263/171340459-6eeda008-9b55-44dd-a8c1-e2dc57019489.png)

**Comment by asheroto** [comment]
That was with the net install. With the full install ISO...

![image](https://user-images.githubusercontent.com/49938263/171341504-11e0e4df-5498-405b-9bea-605e686bdf3a.png)

**Comment by ventoy** [comment]
There is a pkgsel line in the preseed
```
d-i pkgsel/include string libcurl4 sysstat ifupdown lvm2 openssh-server ntp ethtool efibootmgr 
```

So according to the log, delete  `libcurl4 sysstat ntp ethtool` and retry.
```
d-i pkgsel/include string ifupdown lvm2 openssh-server efibootmgr 
```

**Comment by ventoy** [comment]
Good news!
I have updated the example in the official website.

**Comment by asheroto** [comment]
Awesome, thanks so much.

**Comment by asheroto** [comment]
Hey there, minor issue related to this.

- When the 

https://user-images.githubusercontent.com/49938263/175774846-89e06f9f-282e-4ccd-825f-f91c873c6b27.mp4

system boots up, the password 123456 for root does not work....

Also there is some "ubuntu" text in the cfg file.

Finally, how can you enable no-GUI install?

Thanks!

**Comment by ventoy** [comment]
When you in the login screen, press `Ctrl+Alt+F2` to switch to console and try to login with root/123456.
If you can login the console with root/123456, then that means the root password is OK, just that the root account is not permited to login from GUI.

The pressed is just an example, you need to learn more details about the preseed syntax to do more deep customization.

For the last problem, if it's OK with VirtualBox/Vmware/Qemu then it may be something with Hyper-V.

**Comment by asheroto** [comment]
Thanks for your reply.

Here's what I figured out:

With Ventoy preseed, using the same file....

[Debian 10 net install](https://cloud.debian.org/images/archive/10.12.0/amd64/iso-cd/debian-10.12.0-amd64-netinst.iso): boots to console, root login works
[Debian 10 full install](https://cloud.debian.org/images/archive/10.12.0/amd64/iso-cd/debian-10.12.0-amd64-xfce-CD-1.iso): boots to GUI, root login does **not** work in **GUI**, but root login works in console (Ctrl+Alt+F2)
[Debian 11 net install](https://cloud.debian.org/images/archive/11.2.0/amd64/iso-cd/debian-11.2.0-amd64-netinst.iso): boots to console, root login works
[Debian 11 full install](https://cloud.debian.org/images/archive/11.2.0/amd64/iso-dvd/debian-11.2.0-amd64-DVD-1.iso): boots to GUI, root login does **not** work in **GUI**, but root login works in console (Ctrl+Alt+F2)

Yes, I do need to learn more about preseed info, any recommendations where I can learn more info?

For whatever reason the black screen issue is no longer present.

**Comment by asheroto** [comment]
I also noticed another bug related to this.

If you select a Linux image and press enter, and you then have the two options to boot with the seed/cfg or without, you cannot press Escape to back out of the menu anymore.
