### ISSUE TITLE
[Success Image Report]: Kylin Desktop V10 SP1

### ISSUE THREAD

**Issue by spaceack** [ventoy/Ventoy#1641]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.74

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

Kylin-Desktop-V10-SP1-Release-hwe-2107-x86_64.iso

### Image file checksum type

MD5

### Image file checksum value

7e46c78a7a9acf84dfee6c6fcf6254ef

### Image file download link (if applicable)

https://mirrors.aliyun.com/ubuntukylin-cdimage/V10-SP1/Kylin-Desktop-V10-SP1-Release-hwe-2107-x86_64.iso

### Test envrionment

Lenovo ThinkPad T14

### More Details?

This image file booted successfully in Ventoy.
![iShot2022-05-25 10 24 34](https://user-images.githubusercontent.com/23256191/170166472-a6001cf5-f176-4a35-9dc4-58f6c19eee5f.jpg)

**Comment by ventoy** [comment]
Thanks!
