### ISSUE TITLE
[issue]: 引导其他 Linux ISO 的时候， initrd 没有加载成功

### ISSUE THREAD

**Issue by zhang-ray** [ventoy/Ventoy#1642]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.74

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

60GB

### What happened?

我这里有一个 用 `grub-mkrescue` 制作出来的 `RamOS.iso`  ISO文件，文件大概长这样：
```
menuentry "RamOS" {
    linux /bzImage 
    initrd /initramfs.cpio.gz
}
```

把 `RamOS.iso` 放到 Ventoy 后启动，发现 系统的 `initrd` 好像都还是 Ventoy 自己的。 查看 `/init` 文件里面都还是 Ventoy 的字样（而不是 RamOS 的 `init`）

这里的 `RamOS.iso` 在 qemu 模拟 是没问题的（使用 `qemu-system-x86_64 -m 4G  -cdrom RamOS.iso ` 命令）

多谢🙂

**Comment by zhang-ray** [comment]
> 

您好，我试了一下 memdisk 方式 和 包含 `ventoy.dat` 的方式，都无法解决问题（不知道是不是跟我 `grub.cfg` 文件有关系？ ）。

Ventoy 非常好用👍， 我想问一下如果我要在 ventoy 中 使用类似的 RamOS, 制作 iso 的过程中有没有推荐的 example？ 我的 RamOS 只需要包含  kernel 和 initrd 即可~

**Comment by ventoy** [comment]
使用 memdisk 和 ventoy.dat 时 具体什么问题？ 截个图或者录个视频看看。

**Comment by zhang-ray** [comment]
> 使用 memdisk 和 ventoy.dat 时 具体什么问题？ 截个图或者录个视频看看。

F1 使用 `memdisk` 之后， 闪退到原来 Ventoy 选择ISO的界面中

添加了  Ventoy.dat 并重新制作 RamOS.iso 后， 进入 RamOS 之后的文件系统还是使用 ventoy 的 initrd 文件系统（从 /init 可以看出来）

**Comment by ventoy** [comment]
你试试先按 `Ctrl+i` 然后再启动。

**Comment by zhang-ray** [comment]
> 你试试先按 `Ctrl+i` 然后再启动。

后来发现 只需要 按住 F1 （出现 `Memdisk` 字样） 然后回车即可。 本来以为按F1即可进入所以以为进不去…… 

不需要 Ctrl+i 进入兼容模式


为 ventoy 点赞 👍 Ventoy 很好用。
