### ISSUE TITLE
[issue]: HoloISO cannot boot

### ISSUE THREAD

**Issue by palxex** [ventoy/Ventoy#1644]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.74

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

128GB

### Disk Manufacturer

Sandisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://github.com/theVakhovskeIsTaken/holoiso/releases/download/snapshot20220522.1905/SteamOS_Holo-20220522_1750_amdgpu-x86_64.iso

### What happened?

The first stage works, but when archiso mounting it will report error like below.
![image](https://user-images.githubusercontent.com/58222/170299175-9d321299-8e2f-4e6c-a66d-515f4ca6ecac.png)

On same U-stick I put Windows 11 ISO/Hikari PE/SysSecCD/Knoppix, and all of them works well.
Also checked previous 20220510 version, the problem is same.
The distribution aims target UEFI, so I does not test on legacy - in fact on my system legacy ventoy often not works, even in menu stage.
PC info: MSI B450M Mortar Max + Ryzen 7 3600X + RX580.

**Comment by steve6375** [comment]
The ISO does not seem to contain UEFI  boot files for CD\DVD booting. Does the ISO boot as a DVD drive in an emulator? I suspect not...
From the github page:
**The ISO didn't boot for me, any solution?**
Currently, the ISO only boots if flashed using [BalenaEtcher](https://www.balena.io/etcher/), [RosaImageWriter](http://wiki.rosalab.ru/en/index.php/ROSA_ImageWriter), [Fedora Media Writer](https://getfedora.org/en/workstation/download/), DD with 4MB block size, or [Rufus](https://rufus.ie/) with DD mode.

**Comment by palxex** [comment]
In fact it can.
After boot into the shell, just
```
mkdir -p /run/mnt/ventoy
mount /dev/sd?1 /run/mnt/ventoy
mount /run/mnt/ventoy/ISOPATH /run/archiso/bootmnt
exit
exit
```
works. like other arch installcd.

**Comment by deftdawg** [comment]
Thanks @palxex, following your directions, I was able to boot the latest holoiso. 

![IMG_20220810_223058__01.jpg](https://user-images.githubusercontent.com/4991612/184059469-ec616842-47b8-486e-9419-4942f61c78cc.jpg)

**Comment by steve6375** [comment]
You can UEFI64-boot directly from the ISO using Easy2Boot/agFM or grubfm.
You can also add grubfm to your Ventoy USB drive if it is an MBR-partitioned drive:
1. Make sure the Holo ISO file is contiguous (e.g. use Defraggler - right-click on file in Windows - defragment)
2. Copy grubfm_multiarch.iso to your Ventoy USB drive and boot from it
https://github.com/a1ive/grub2-filemanager/releases/tag/v7.4.0
4. Find and select the ISO in the grubfm menu system, choose the partnew boot option.

Easy2Boot/grubfm/agFM can use the partnew method to boot Linux ISOs which makes a Type 0 MBR partition entry which points to the start of the ISO file on the disk. Linux will then auto-mount that Type 0 partition as an ISO 9660 volume and so it can see all the files on it.

**Comment by ventoy** [comment]
@palxex 
Try the latest 1.0.80 release.

**Comment by palxex** [comment]
> @palxex Try the latest 1.0.80 release.

Thanks mentioning, just tested works well.

**Comment by sagar9399** [comment]
After installation it was stuck at verifying installation 
![16844989501256286015281656986752](https://github.com/ventoy/Ventoy/assets/123379494/1dd0931e-dff8-41fc-812d-8193d8fcff7d)
And i got line in down
