### ISSUE TITLE
[issue]: ALT Linux doesn't boot in UEFI mode

### ISSUE THREAD

**Issue by zagagyka** [ventoy/Ventoy#1645]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.74

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32 GB

### Disk Manufacturer

Transcend JetFlash 780 32gb, USB3.0

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

http://ftp.altlinux.org/pub/distributions/ALTLinux/images/p10/workstation/x86_64/alt-workstation-10.0-x86_64.iso

### What happened?

ALT Linux doesn't boot in UEFI mode:
1. I've connected the USB flash drive to the laptop and booted from the USB flash drive with the installed Ventory
2. I've choosed the **alt-workstation-10.0-x86_64.iso** in the following menu:
![1](https://user-images.githubusercontent.com/20092621/170699437-3a40655f-0d76-4074-bb28-c426147aaff4.png)

_ALT Linux grub menu is loaded_
3. I've choosed the **LiveCD (no hard disk needed)** in the following menu:
![2](https://user-images.githubusercontent.com/20092621/170699440-4508fadd-1614-4802-a0a5-36728e84ee26.png)

**After a while, this error appears**
![3](https://user-images.githubusercontent.com/20092621/170699442-60a7a7c9-42a4-4b48-8ee4-9f932a790c9d.jpg)

- I've tried to use the other images like alt-workstation-9.1-x86_64.iso (listed as compatible -  [alt-workstation-9.1-x86_64.iso](https://forums.ventoy.net/showthread.php?tid=440&highlight=ALT))
- I've tried to use the other laptops (and QEMU KVM) and the other USB flash drives
- Also i've tried to install Ventory on USB flash drive using the old version (ventoy-1.0.18)
**The error is the same**

**In Legacy BIOS mode ALT Linux boot correctly**

**Comment by ventoy** [comment]
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/2401327676
https://www.ventoy.net/en/doc_github_ci.html

**Comment by zagagyka** [comment]
Thank you very much. This CI release fixed this bug
