### ISSUE TITLE
[Success Image Report]: Fedora Workstation 36 - Fedora-Workstation-Live-x86_64-36-1.5.iso

### ISSUE THREAD

**Issue by AlperShal** [ventoy/Ventoy#1646]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.74

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

Fedora-Workstation-Live-x86_64-36-1.5.iso

### Image file checksum type

SHA256

### Image file checksum value

80169891cb10c679cdc31dc035dab9aae3e874395adc5229f0fe5cfcc111cc8c

### Image file download link (if applicable)

https://download.fedoraproject.org/pub/fedora/linux/releases/36/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-36-1.5.iso

### Test envrionment

Monster Abra A7 v12.2, Intel i5 10300H, GTX 1650Ti Mobile, 16GB RAM, 32GB Ventoy USB

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
