### ISSUE TITLE
[issue]: DLC Boot 2022 v4.0.220520.iso Can not load Winpe Programs

### ISSUE THREAD

**Issue by crasadure** [ventoy/Ventoy#1647]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.74

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

64gb

### Disk Manufacturer

Sandisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

http://www.dlcboot.com/

### What happened?

Hi @ventoy ;
DLC Boot 2022 v4.0.220520.iso file can not load Win10 Pe x64, Win11 Pe x64 options on Legacy mode...all programs cannot load on PE system. When I try it on bootable Virtual CD on Virtualbox it can boot it and all programs are loading on interface...can you fix this problem?
Alternative ISO Download Links:
Link1: https://uploadrar.com/ys4b3jlnwejf
Link2: https://anonfiles.com/H6j0b6lcy1/DLC_Boot_2022_v4.0.220520_iso

**Comment by ventoy** [comment]
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/2413009174
https://www.ventoy.net/en/doc_github_ci.html

**Comment by crasadure** [comment]
İt's Ok...Thanks :)

**Comment by pommedefrance** [comment]
Sorry but i've still this problem..when i launch dlc boot 2022, with https://github.com/ventoy/Ventoy/suites/6722774715/artifacts/256219528, i've got a black screen and nothing happened :-(

**Comment by ventoy** [comment]
@pommedefrance 
1. Change you BIOS mode and retry (for exampe if you use Legacy BIOS mode then change to UEFI mode and retry)
2. Before you boot the ISO file press F7 to switch to TEXT mode firstly and then boot the ISO file to see whether it can work.

**Comment by pommedefrance** [comment]
still don't work :-(
i am in uefi (and i don't want to change it, a mess in my disks after..)
f7, no infos when i'm choosing dlc boot 2022, black screen, the same
crasadure it's ok for you ?

**Comment by ventoy** [comment]
@pommedefrance 
I think `DLC Boot 2022 v4.0.220520.iso` itself doesn't support boot from CD/DVD in UEFI mode.
I test it with a VM(VMWare), set the VM to UEFI mode and connect the ISO file directly to the CD/DVD of the VM and boot it.
It can not boot at all.

**Comment by pommedefrance** [comment]
i'll try...but for dlc boot 2019, it's ok...ventoy took a while for that but finally did it ;-)

**Comment by ventoy** [comment]
Maybe DLC boot 2019 can boot from CD/DVD in UEFI mode. You can test both of them in VM for comparation.

**Comment by pommedefrance** [comment]
yeah but dlc 2019 didn't change at first, ventoy did ;-)

**Comment by ventoy** [comment]
Ventoy emulate a CDROM to boot an ISO file. So the ISO file must be bootable from CD/DVD in order to boot by Ventoy.
If DLC 2019 can boot from CD/DVD bu DLC 2022 can not boot from CD/DVD, it's the problem of DLC 2022 iso file.

**Comment by steve6375** [comment]
You can work round it like this
1. Extract one of the \DLC1\WinPE  .wim files (or all three)
2. Boot to a .wim file - e.g. Win11x64.wim  (\ventoy\ventoy_wimboot.img plugin file required) - you can run DLCBoot.exe from Y: now if you wish.
3. Find the DLC Boot ISO in Explorer and right-click and 'Mount as ImDisk Virtual Disk' and use drive letter Y:
4. In Explorer, go to X:\Windows\System32 folder, drag-and-drop file **pecmd.ini** onto the file **Pecmd.exe**  (or open cmd shell at C:\Windows\System32 and type **pecmd.exe pecmd.ini**)
5. If Task bar shows 'V' - click on it to change to English 'E'
I notice that BootIce and SaveScreen in Win11 WIM do not seem to work because programs missing from X: ???

- or extract all files of ISO to USB drive (you can move .wim files to any folder) and then steps 3 and 4 may not be needed (untested).

**Comment by pommedefrance** [comment]
a bit complicated ;-) just for lauching dlc boot...but  in the forum, you say that is working for dlc, not for me !!

**Comment by pommedefrance** [comment]
another test..in virtualbox under windows, no problems...

**Comment by ventoy** [comment]
@pommedefrance 
VirtualBox does some compatibility process when booting ISO file in UEFI mode, so even the ISO file itself does not match the bootable ISO file specification, VirtualBox still can boot it in UEFI mode. I can also boot DLC 2022 OK in my computer with VirtualBox UEFI mode.
**But it fail when test with VMware in UEFI mode.**.

**Comment by maravento** [comment]
Solved with DLC Boot 2022 v4.1.220628. Tested in ventoy-1.0.79 (Boot UEFI Mode)
