### ISSUE TITLE
[issue]: cannot live boot Stratodesk NoTouch OS

### ISSUE THREAD

**Issue by ronnysteineratnetwolk** [ventoy/Ventoy#1652]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.75

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

128

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://portal.stratodesk.com/dl/QIGmYfxtNcTusuTBakbGM050i/Stratodesk-NoTouchOS-3.3.727-EEs-k514-x64-220409.zip

### What happened?

After booting Stratodesk NoTouch OS 3.3.727 with Kernel 5.14 from a Ventoy USB Stick, I received the following error:
The system can not access the 'root filesystem'. May we ask you to try these things to resolve the issue:

-Try a different boot medium. If using CD-ROM or USB, the medium may simply be defective. USB sticks sometimes can not boot properly

-If this happens on an installed machine, it could mean that the hard drive is failing, slowly. You can try to reinstall the OS from USB or PXE

-Try another Linux kernel version. use another kXXX-OS-image. This is especially true if you experience this during trial.

More detailed error messages (mountroot):
If you want to investigate, here is a Linux shell:
/bin/sh: can't access tty; job control turned off

I did try different kernel versions (5.10, 5.15, 5.16) but the error remained the same.

Do you have any idea how I can successfully boot NoTouch OS Live?

![20220602_132549128_iOS](https://user-images.githubusercontent.com/66597952/171644375-d91dc383-c59d-402b-94ee-1f0a9ba44df5.png)
![20220602_132602653_iOS](https://user-images.githubusercontent.com/66597952/171644433-bd7d4c0a-8100-441a-b3c3-9317a19ad94d.png)
![20220602_132619149_iOS](https://user-images.githubusercontent.com/66597952/171644498-f0a8622b-bd0c-4dfd-a4a8-86e8f6ac8d43.png)

**Comment by ventoy** [comment]
I can not download the zip file, please share it in some way.

**Comment by ronnysteineratnetwolk** [comment]
> I can not download the zip file, please share it in some way.

Here is a link where you can download the zip file:
https://www.swisstransfer.com/d/00c8b6c1-0a66-4466-884c-31f10d098ccf

**Comment by ventoy** [comment]
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/2438314852
https://www.ventoy.net/en/doc_github_ci.html

**Comment by ronnysteineratnetwolk** [comment]
with Stratodesk NoTouch OS 3.3.727 kernel release 5.14 it works perfectly!👌

I also tried other kernel releases.
The following kernel releases booted successfully:
5.10, 5.14, 5.15

These kernel releases still didn't boot:
5.06, 5.16

If you want to try I've uploaded all the other kernel releases as well:
https://www.swisstransfer.com/d/56a81dcd-89b6-4e42-8d89-a8e0267544f2

**Comment by ventoy** [comment]
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/2441794116

**Comment by ronnysteineratnetwolk** [comment]
now it works perfectly.👌 you are my hero! thanks a lot for your help.
I will report the ISO as successfully tested.
