### ISSUE TITLE
[Success Image Report]: Debian GNU/Linux Live image 10.6.0 i386 (LXDE) on an IA-32 UEFI device

### ISSUE THREAD

**Issue by olofolleola4** [ventoy/Ventoy#1653]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.75

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

debian-live-10.6.0-i386-lxde.iso

### Image file checksum type

SHA256

### Image file checksum value

463a9bffba0090c4295cdc0c3d67897e1983284bbeb4be26743ea431edb12bed

### Image file download link (if applicable)

https://cdimage.debian.org/cdimage/archive/10.6.0-live/i386/iso-hybrid/debian-live-10.6.0-i386-lxde.iso

### Test envrionment

Acer Iconia Tab 8 W (W1-810)

### More Details?

This image file booted successfully in Ventoy on an IA-32 UEFI device.

**Comment by ventoy** [comment]
Thanks!

**Comment by olofolleola4** [comment]
Should not be listed here: https://ventoy.net/en/distro_iso/debian.html
Should be listed here: https://ventoy.net/en/doc_ia32.html
Acer Iconia Tab 8 W (W1-810) only supports IA-32 UEFI. As far as I know, it doesn't support Legacy (x86 BIOS) or x86_64 UEFI.
