### ISSUE TITLE
[issue]: vdisk启动linux系统后，不能挂载U盘中vdisk所在分区

### ISSUE THREAD

**Issue by ruanima** [ventoy/Ventoy#1655]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.75

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128GB

### Image file checksum (if applicable)

Yes.

### What happened?

 vdisk启动linux系统后，不能挂载U盘中vdisk所在分区。请问这个是bug还是功能限制。

vdisk中的linux是deepin 20.6

**Comment by ventoy** [comment]
打开全局控制插件中的 `VTOY_LINUX_REMOUNT` 选项。
https://www.ventoy.net/cn/plugin_control.html

**Comment by ruanima** [comment]
> 

试试看，多谢

**Comment by ventoy** [comment]
@ruanima  好使吗？

**Comment by ruanima** [comment]
经过测试不好使，从本地磁盘的vdi上启动，该盘就无法挂载了，该磁盘的其他分区能正常挂载。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月6日(周一) 下午3:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ventoy/Ventoy] [issue]: vdisk启动linux系统后，不能挂载U盘中vdisk所在分区 (Issue #1655)




 
@ruanima  好使吗？

**Comment by ventoy** [comment]
VDI拷贝到Ventoy所在U盘中，启动后Ventoy盘能挂载吗？

**Comment by ventoy** [comment]
@ruanima
我自己测试 deepin-20.6 是好使的。你需要确认选项有没有配置正确。
在Ventoy界面 `F5 Tools` ---> `Check plugin json configuration (ventoy.json)` ---> `Check global control plugin configuration`
是否能正确显示   `VTOY_LINUX_REMOUNT: 1`

**Comment by ruanima** [comment]
vdi复制到U盘也不行，配置参数是OK的









---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月7日(周二) 晚上9:35
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ventoy/Ventoy] [issue]: vdisk启动linux系统后，不能挂载U盘中vdisk所在分区 (Issue #1655)




 
@ruanima
 我自己测试 deepin-20.6 是好使的。你需要确认选项有没有配置正确。
 在Ventoy界面 F5 Tools ---&gt; Check plugin json configuration (ventoy.json) ---&gt; Check global control plugin configuration
 是否能正确显示   VTOY_LINUX_REMOUNT: 1

**Comment by ventoy** [comment]
你把你的  ventoy.json 文件传上来看看。

**Comment by ruanima** [comment]
```
{
    "control":[
        { "VTOY_MAX_SEARCH_LEVEL": "2" },
        { "VTOY_LINUX_REMOUNT": "1" }
    ]
}
```

![image](https://user-images.githubusercontent.com/14031394/172629124-1a950633-a33b-4a90-8440-d44a88e3c64c.png)

**Comment by ventoy** [comment]
在终端执行  `sudo lsmod | grep dm`  看一下结果。

**Comment by ventoy** [comment]
下面是我测试环境的结果：

```
panda@panda-PC:~/Desktop$ lsblk
NAME          MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda             8:0    0 465.8G  0 disk 
├─sda1          8:1    0 465.7G  0 part /media/panda/Ventoy
│ └─ventoy    253:0    0    64G  0 dm   
│   ├─ventoy1 253:1    0   300M  0 dm   /boot/efi
│   ├─ventoy2 253:2    0   512M  0 dm   /boot
│   ├─ventoy3 253:3    0    15G  0 dm   /
│   ├─ventoy4 253:4    0    15G  0 dm   
│   ├─ventoy5 253:5    0  16.2G  0 dm   /data
│   ├─ventoy6 253:6    0    11G  0 dm   /recovery
│   └─ventoy7 253:7    0     6G  0 dm   [SWAP]
└─sda2          8:2    0    32M  0 part 
sdb             8:16   0 465.8G  0 disk 
├─sdb1          8:17   0   300G  0 part /media/panda/Main
└─sdb2          8:18   0 165.8G  0 part /media/panda/Data
sr0            11:0    1  1024M  0 rom  
panda@panda-PC:~/Desktop$ 
panda@panda-PC:~/Desktop$ 
panda@panda-PC:~/Desktop$ sudo lsmod | grep dm
dm_patch               16384  0
panda@panda-PC:~/Desktop$
```

**Comment by ruanima** [comment]
```
rlj@rlj-PC:~$ sudo lsmod |grep dm
snd_hda_codec_hdmi     61440  1
snd_pcm_dmaengine      16384  1 snd_soc_core
snd_hda_codec         147456  5 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec_realtek,snd_soc_hdac_hda
snd_hda_core           98304  8 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hda_intel,snd_hda_ext_core,snd_hda_codec,snd_hda_codec_realtek,snd_soc_hdac_hda,snd_soc_skl
snd_pcm               126976  11 snd_hda_codec_hdmi,snd_hda_intel,snd_hda_codec,soundwire_intel,snd_sof,snd_sof_intel_hda_common,snd_compress,snd_soc_core,snd_soc_skl,snd_hda_core,snd_pcm_dmaengine
snd                    94208  15 snd_hda_codec_generic,snd_hda_codec_hdmi,snd_hwdep,snd_hda_intel,snd_hda_codec,snd_hda_codec_realtek,snd_sof,snd_timer,snd_compress,snd_soc_core,snd_pcm

```

**Comment by ventoy** [comment]
再看看   `sudo dmesg` 的信息。

**Comment by ruanima** [comment]
[dmesg.log](https://github.com/ventoy/Ventoy/files/8870273/dmesg.log)

**Comment by ventoy** [comment]
你安装完执行  `vtoyboot.sh` 的时候，是使用的最新版本的 `vtoyboot-1.0.21` 吗？https://github.com/ventoy/vtoyboot/releases
老版本的 vtoyboot 是不支持这个选项的。

**Comment by ruanima** [comment]
是这个版本，但是我看版本号还是1.0.20



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月9日(周四) 晚上8:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ventoy/Ventoy] [issue]: vdisk启动linux系统后，不能挂载U盘中vdisk所在分区 (Issue #1655)




 
你安装完执行  vtoyboot.sh 的时候，是使用的最新版本的 vtoyboot-1.0.21 吗？https://github.com/ventoy/vtoyboot/releases
 老版本的 vtoyboot 是不支持这个选项的。

**Comment by ventoy** [comment]
你使用最新的版本重新执行一次再试试，版本号应该是 `1.0.21`

**Comment by ruanima** [comment]
> 你使用最新的版本重新执行一次再试试，版本号应该是 `1.0.21`

![image](https://user-images.githubusercontent.com/14031394/172854071-7bff0166-4a4b-45fc-9ea4-fe12661b9178.png)

**Comment by ventoy** [comment]
这个库里面没更新，你直接下载 release 里面的ISO文件，里面的是最新的。
https://github.com/ventoy/vtoyboot/releases/download/v1.0.21/vtoyboot-1.0.21.iso
不要使用这个仓库里的。

**Comment by ventoy** [comment]
你可以直接在物理机里面重新执行一次试试。

**Comment by ruanima** [comment]
可以了，能够正常挂载了。

我之前是下载的这个。。。。
![image](https://user-images.githubusercontent.com/14031394/172856272-790de5cb-47a0-43f4-b2a0-134e19d43cd0.png)
