### ISSUE TITLE
[issue]: Error "Unsupported Format" when enrolling .CER file.

### ISSUE THREAD

**Issue by ktns01** [ventoy/Ventoy#1657]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.75

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

64GB

### Disk Manufacturer

SanDisk

### What happened?

使用的设备是Lenovo XiaoXinPro-13ARE 2020。
之前在这台设备上可以在安全模式下使用Ventoy。
在更新 F0CN35WW BIOS后需要重新添加证书，但是在最后一步报错：
"Unsupported Format: Only DER encoded certificate (*.cer/der/crt) is supported".

**Comment by svenger87** [comment]
https://github.com/ValdikSS/Super-UEFIinSecureBoot-Disk/issues/16#issuecomment-1148589595

This workaround works for me.

**Comment by ValdikSS** [comment]
New version contains MokManager from shim 15.4-5, which should fix this issue.
https://github.com/ValdikSS/Super-UEFIinSecureBoot-Disk/releases/tag/3-3

**Comment by ventoy** [comment]
@ktns01  Try the latest 1.0.76

**Comment by icy-comet** [comment]
Just tried `v1.0.76` @ventoy. The key enrolls successfully now.

**Comment by ventoy** [comment]
OK, so the latest release should have fixed it.
