### ISSUE TITLE
[Success Image Report]: Parrot Sec 5.0.1

### ISSUE THREAD

**Issue by jruedaq** [ventoy/Ventoy#1659]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.75

### BIOS Mode

Both

### Partition Style

GPT

### Image file name

Parrot-security-5.0.1_amd64.iso

### Image file checksum type

SHA512

### Image file checksum value

a3440b12b528e6e952291af443296352815f18e205cf7ae87f4312c2715eb07ee55bc0eab11544c1dcd28878b721c5317d3062b3e38591a83e9dbb9efa31c4eb

### Image file download link (if applicable)

https://download.parrot.sh/parrot/iso/5.0.1/Parrot-security-5.0.1_amd64.iso

### Test envrionment

Asus X570ZD

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
