### ISSUE TITLE
[Success Image Report]: Parrot architect 5.0.1

### ISSUE THREAD

**Issue by jruedaq** [ventoy/Ventoy#1660]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.75

### BIOS Mode

Both

### Partition Style

GPT

### Image file name

Parrot-architect-5.0.1_arm64.iso

### Image file checksum type

SHA512

### Image file checksum value

546508e452feb2b5b989480617ef85afee7ac1fc70d6064506caf5f3035c454da8cb414f5ebfb33dd2fe53d54f28a7474cf73e2b6bccbaf88aa0635d16725d74

### Test envrionment

G41T-M7

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
