### ISSUE TITLE
[Feature request]: bypass internet connection to install Windows 11 pro/home version 

### ISSUE THREAD

**Issue by crasadure** [ventoy/Ventoy#1662]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.75

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32Gb

### Disk Manufacturer

Sandisk 32gb flash disk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://software.download.prss.microsoft.com/dbazure/Win11_English_x64v1.iso?t=f12310b1-dc98-4625-8015-d1898424b578&e=1654825586&h=09d11327a44e11834a6b28800347640985ee3539ed7bf5db4f7adb695618a80a

### What happened?

Hi @Ventoy
Please firstly can you read this articles from this links?
[https://pureinfotech.com/bypass-internet...indows-11/](https://pureinfotech.com/bypass-internet-connection-install-windows-11/)

https://www.elevenforum.com/t/what-is-oobe-bypassnro.5011/
A video:
https://youtu.be/tr-W4a4taPQ

Can we add a parameter to ventoy.json file for win11 pro and home version for Bypass internet connection 

OOBE\BYPASSNRO

**Comment by steve6375** [comment]
Just use an XML file to automatically make a local account in the name that you want.
See https://www.windowsafg.com/
This works for me :-)
You can also bypass Win11 TPM, etc, checks using an XML.

**Comment by steve6375** [comment]
If installing Win11 Pro - just enter any email address and an invalid password. It should prompt you for local account name after it fails.

**Comment by crasadure** [comment]
> If installing Win11 Pro - just enter any email address and an invalid password. It should prompt you for local account name after it fails.

Thanks your answer,great solution

**Comment by sjdrc** [comment]
> If installing Win11 Pro - just enter any email address and an invalid password. It should prompt you for local account name after it fails.

This does not seem to work any more - it first errors if the account is not a real MS account, and then any number of incorrect passwords on a real MS account will not result in prompt for local account name.

**Comment by steve6375** [comment]
I used todays Win11 UEFI64 International English ISO (direct ISO download from MS page) and using account name of steve@example.com and ddd password works for me. Maybe it depends on what version of ISO you use?

**Comment by ventoy** [comment]
@crasadure 
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/3766599075
I add `VTOY_WIN11_BYPASS_NRO`  option.
