### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Yran-Olv** [ventoy/Ventoy#1663]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.75

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

1TB

### Disk Manufacturer

HP

### Image file checksum (if applicable)

No.

### What happened?

Error Log: 
[log.txt](https://github.com/ventoy/Ventoy/files/8871359/log.txt)

Img: 
![help](https://user-images.githubusercontent.com/72234614/172874346-c45dfbd8-c167-48f5-a4c6-b5769d4095e0.PNG)

**Comment by ventoy** [comment]
I think it's a hardware issue of your USB disk.
`[2022/06/09 11:34:19.393] ### [Check Fail] The data write and read does not match`

You can refer: https://www.ventoy.net/en/doc_fake_usb.html
