### ISSUE TITLE
[issue]:Windows Defender sees v.1.0.76 Ventoy2Disk.exe as a Severe threat [Behavior:Win32/Persistence.A!ml]

### ISSUE THREAD

**Issue by QvanK** [ventoy/Ventoy#1665]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.76

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

256GB

### Disk Manufacturer

Sandisk

### Image file download link (if applicable)

n.a.

### What happened?

When unzipping the latest Ventoy version (1.0.76) Ventoy2Disk.exe is quaratined by Windows Defender as a 'Severe' threat.

Screenshot of Windows Defender report: 
![Screen Shot 2022-06-12 at 18 19 20](https://user-images.githubusercontent.com/39484227/173243089-2390be43-813e-4f16-92c2-2b005e66095b.png)

The checksum of the 'ventoy-1.0.76-windows.zip' matches the one posted here on GIT 

Checksum Comparison:
(0d7a43f2aee86a620e5a0604e19dc8b74848f1629927fe03c854390cfb537f07)
![Screen Shot 2022-06-12 at 18 23 50](https://user-images.githubusercontent.com/39484227/173243092-ac04eed1-68d6-41d1-9132-52642b47e79e.png)

**Comment by KaranKad** [comment]
I can't replicate this issue even after manually scanning ventoy folder with defender. Try updating defender security intelligence if it's outdated.

**Comment by QvanK** [comment]
I fully updated another VM (Windows 10) VM and that one did indeed not report any threats.
The VM that gave the error is a Windows 11 VM which was missing the latest defender security intelligence updat.
After the update it also did not report any threats.
Odd how just one little udate makes such a difference....
Chalking it up to a false positive.

**Comment by Ardakilic** [comment]
Hello, I'm having the same issue with 1.0.94.

This is my defender security update version.

![image](https://github.com/ventoy/Ventoy/assets/2063957/d080853a-5339-4798-9b1a-47a45e9b0a7e)

This happens on me on Win 11 , x64.

fyi: @ventoy
