### ISSUE TITLE
string "Status x%" is missing for translations

### ISSUE THREAD

**Issue by MELERIX** [ventoy/Ventoy#1667]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.76

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GB

### What happened?

string "Status x%" is missing for translations

here is a picture of the string: https://i.postimg.cc/JnHCHM99/mt.png

**Comment by ventoy** [comment]
It's indeed a missing translation.
But it doesn't affect the user's understanding of it.
I will fix it in the future, but is of low priority.
