### ISSUE TITLE
[issue]: (question) exFAT ?

### ISSUE THREAD

**Issue by eladkarako** [ventoy/Ventoy#1668]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.76

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

8GB

### Disk Manufacturer

virtual vdi

### Image file checksum (if applicable)

No.

### What happened?

not sure,  
I've tested the UI and installation,  
and found out that ventoy formats most of the storage to exFAT,  
and about 32mb to FAT32,  
could not found any reference exFAT to it in the F.A.Q. 
is this what would normally should happen?  
can I have any control of it (for example if I want the storage to be formatted as FAT32 or NTFS?)

https://gist.github.com/eladkarako/1d6e4c9c2015d50b83cae04bdcaeda45#file-creating-a-virtual-hard-disk-without-third-party-applications-then-testing-ventoy-github-com-ventoy-ventoy-just-the-first-part-installation-method-md

**Comment by Silexium** [comment]
Yes, this is normal behaviour. You can reformat the 1st partition to NTFS/FAT32/exFAT... See [here.](https://ventoy.net/en/doc_disk_layout.html)

**Comment by eladkarako** [comment]
oh thank you, that's awesome!
