### ISSUE TITLE
[Success Image Report]: WinPE10_8_Sergei_Strelec_x86_x64_2022.01.03_English.iso

### ISSUE THREAD

**Issue by eladkarako** [ventoy/Ventoy#1670]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.76

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

WinPE10_8_Sergei_Strelec_x86_x64_2022.01.03_English.iso

### Image file checksum type

SHA256

### Image file checksum value

c336cbab0d5e472ddcdf93159b15d074fb1b7bb343256dea21cb31362abaef65

### Test envrionment

VirtualBox 6.1.34 r40636 Qt5.6.2

### More Details?

(note: not related to this question https://github.com/ventoy/Ventoy/issues/1668)

a second virtual storage file created on the host machine,  
and mounted as an additional hard-drive: 8GB, fixed size, hot plugged (removable storage),  
for a vm with EFI boot and Windows 10 installed already.
ventoy installed , and an ISO was copied to the storage,  
the machine was reset and <kbd>ESC</kbd> pressed for accessing the boot menu,  
the partition with ventoy was selected and the menu was starting successfully,  
the iso was identified and run properly,  

with in the environment partition managers identified the hard-drive correctly.

`WinPE10_8_Sergei_Strelec_x86_x64_2022.01.03_English.iso` is Windows PE based,  
with a lot of utilities.  
the website and links are is offline  
there is an archive in here:  
https://web.archive.org/web/20220330113249/https://sergeistrelec.ru/winpe-10-8-sergei-strelec-english/214-winpe-10-8-sergei-strelec-x86-x64-native-x86-20220103-english-version.html

and the ISO is available through torrent.

<hr/>

<img width="960" alt="2022-06-13_144604" src="https://user-images.githubusercontent.com/415238/173349411-21f3f8b4-fcbe-48b9-bc3b-2918926ccc5f.png">
<img width="960" alt="2022-06-13_144613" src="https://user-images.githubusercontent.com/415238/173349414-f21b6b8b-4f50-40f7-9ac6-b5fee10b6455.png">
<img width="960" alt="2022-06-13_144621" src="https://user-images.githubusercontent.com/415238/173349420-8202b46a-eb7c-431c-82a4-dcfd04db608d.png">
<img width="960" alt="2022-06-13_144650" src="https://user-images.githubusercontent.com/415238/173349423-cde70698-b4c3-45a7-9a0f-a3c535dd13f8.png">
<img width="960" alt="2022-06-13_144840" src="https://user-images.githubusercontent.com/415238/173349433-bddaf66f-00da-4127-be58-6463958cc08c.png">

**Comment by youk** [comment]
That ISO is basically illegal. Kindly remove your entire report, otherwise I'll have to report it.
