### ISSUE TITLE
[issue]: Ventoy 1.0.7.5+ does not boot Sergei Strelec ISO on Alienware m15 r1

### ISSUE THREAD

**Issue by raywdude** [ventoy/Ventoy#1671]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.7.5, 1.0.7.6

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

2 TB

### Disk Manufacturer

Samsung 970 EVO Plus on a USB NVME drive

### What happened?

The drive has been working perfectly before using ventoy-1.0.74. After upgrading to 1.0.75 it does not boot Sergei Strelec ISOs. Same behavior in 1.0.76 on the Alienware m15 r1 laptop.

Both trying to boot Sergei results in some kind of "chainload error, failed to allocate 6xxxxxxxxx of memory"

I reverted it back to ventoy-1.0.74 and it is working again.

**Comment by ventoy** [comment]
Please take a photo about the error screen and upload here for analyze.

**Comment by ventoy** [comment]
1. When you boot into Ventoy menu, press `c` to enter grub shell and run  `vt_efi_dump_rsv_page`  command and give me the 
result.
2. Try grub2 mode. https://www.ventoy.net/en/doc_grub2boot.html

**Comment by raywdude** [comment]
Thanks for getting back to me. Ubuntu for some reason is working again, but Sergei Strelec continues to not work on 1.0.76.

Here's what happens when I try to boot Sergei Strelec using 1.0.76:

![20220614_181750](https://user-images.githubusercontent.com/1065479/173699157-8e7f14d7-6a3b-485b-8acf-ca99e81f7032.jpg)

Output from vt_efi_dump_rsv_page:

![20220614_181813](https://user-images.githubusercontent.com/1065479/173699158-e560e760-06d9-401c-8a9b-708948c4fd64.jpg)

It works again if I flash back to 1.0.74 using the "Upgrade" button in the Ventoy Tool.

**Comment by ventoy** [comment]
Try this CI release: 
https://github.com/ventoy/Ventoy/actions/runs/2502321818
https://www.ventoy.net/en/doc_github_ci.html

**Comment by raywdude** [comment]
> Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/2502321818 https://www.ventoy.net/en/doc_github_ci.html

Worked! I flashed the CI build on my drive, and it booted up right away.

**Comment by ventoy** [comment]
Good news.
This fix will be included in the next release.
