### ISSUE TITLE
[feature request]: Make it possible to replace multiple files on the same ISO via conf_replace

### ISSUE THREAD

**Issue by youk** [ventoy/Ventoy#1672]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.76

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64GB

### Disk Manufacturer

Samsung

### What happened?

Currently only one entry per ISO is applicable (other entries having the same `iso` are ignored). Please make it possible to replace multiple files.

**Comment by ventoy** [comment]
This plugin was designed to replace the boot configuration file (e.g.  `isolinux.cfg`   `grub.cfg`).
It was designed to work with just one file replacement from the beginning and hard to expand.

Can you explain why you need to replace more than one files at boot time?

**Comment by youk** [comment]
I need to replace two files in `systemd-boot`: `loader.conf` and boot entry under `entries`, e.g. `03-archiso-x86_64-ram-linux.conf`.
