### ISSUE TITLE
Random data at last sector of disk

### ISSUE THREAD

**Issue by Silexium** [ventoy/Ventoy#1673]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.76

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128GB

### Disk Manufacturer

Kingston

### What happened?

This isn't really an issue, but Ventoy seems to write 420 bytes of seemingly random data to the last sector of a GPT-partitioned drive. What is this data for? Ventoy & the drive itself work perfectly fine regardless if those 420 bytes are zeroed out or not. The only thing that I can think of is that this data is used to check the drive's size to make sure it has a valid capacity. In that case, wouldn't the VTOYEFI partition serve the same purpose since it's also at the end of the drive?

![](https://user-images.githubusercontent.com/87285693/173839991-20b97045-2c00-4a2c-97b5-1206938aef82.png)
What it should look like

![](https://user-images.githubusercontent.com/87285693/173840543-995a4c16-d966-4fd6-8358-fd1c08f74590.png)
What it actually is

**Comment by Silexium** [comment]
> This is GPT backup partition table. It's not Ventoy specific data, but is part of GPT partition table specification. See the following picture: https://en.wikipedia.org/wiki/GUID_Partition_Table#/media/File:GUID_Partition_Table_Scheme.svg

[According to the UEFI spec](https://uefi.org/sites/default/files/resources/UEFI_Spec_2_9_2021_03_18.pdf#G9.1002797), the GPT header should have a size of 92 bytes, with everything after the 92nd byte zeroed out. So, the first picture shows what that sector is supposed to look like according to the spec. I'm not sure what those last 420 bytes are in the second picture.

![](https://user-images.githubusercontent.com/87285693/173861377-32c767dc-5d6f-4b0e-a126-f35ca180696b.png)

**Comment by ventoy** [comment]
I just make a fresh install of Ventoy 1.0.76 on my USB drive with GPT partition style.
These bytes are all zero in my USB drive.  Which method did you use to install your Ventoy? (.exe/.sh/WebUI/LinuxGUI)?

![image](https://user-images.githubusercontent.com/59477474/173865000-21e3d2dd-e0e8-43c7-8770-4c54a64cd7d9.png)

**Comment by Silexium** [comment]
> I just make a fresh install of Ventoy 1.0.76 on my USB drive with GPT partition style. These bytes are all zero in my USB drive. Which method did you use to install your Ventoy? (.exe/.sh/WebUI/LinuxGUI)?
> 
> ![image](https://user-images.githubusercontent.com/59477474/173865000-21e3d2dd-e0e8-43c7-8770-4c54a64cd7d9.png)

I used the x64 .exe for Windows. Have you tried booting into Ventoy & then checking if the bytes are all zeros?

**Comment by Silexium** [comment]
OK, so I just made a fresh install of Ventoy on a 64GB drive & the last sector was normal (the last 420 bytes were all zeros). However, when I booted Ventoy & then rebooted back into Windows, those 420 random bytes reappeared. Strangely, those bytes seem to be identical to the bytes found on the 128GB drive. I performed a checksum on those 420 bytes on both drives & the hashes were identical. Weird.

![](https://user-images.githubusercontent.com/87285693/173881296-8285e52f-a5ee-4849-bae5-6b4505f22704.png)

**Comment by steve6375** [comment]
Is that sector the same as the EFI sector (usually LBA1)?

**Comment by Silexium** [comment]
> Is that sector the same as the EFI sector (usually LBA1)?

No, it's the last sector of the entire disk (where the backup GPT header is stored). The primary GPT header & the primary & backup partition tables all look normal, it's just the backup GPT header that has these weird random bytes.

**Comment by steve6375** [comment]
So your OS could have written it on reboot and USB detection?

**Comment by Silexium** [comment]
> So your OS could have written it on reboot and USB detection?

Hm, could be. How do I know for sure that Windows is in fact writing those bytes to disk instead of Ventoy?

**Comment by steve6375** [comment]
1. Install Ventoy
2. Check sector
3. reboot to Windows
4. Check sector

**Comment by steve6375** [comment]
P.S. Any RAID or encrypted drives/drivers in your system?

**Comment by Silexium** [comment]
> P.S. Any RAID or encrypted drives/drivers in your system?

No.

**Comment by steve6375** [comment]
??? Did you boot to Ventoy???
Why?

1. Install Ventoy under Windows
2. Check sector under Windows
3. Shutdown Windows and reboot back into Windows
4. Check sector under Windows

**Comment by Silexium** [comment]
I zeroed those bytes with a hex editor, rebooted to Windows without going to Ventoy & those bytes reappeared. So, it's in fact Windows that's writing those bytes to disk, not Ventoy.

**Comment by steve6375** [comment]
Does BIOS have any RAID enabled?

**Comment by Silexium** [comment]
> Does BIOS have any RAID enabled?

No. I skimmed through my BIOS & didn't find anything related to RAID. Should I take a look at USB settings?

**Comment by steve6375** [comment]
Maybe try same test on a different system or 3? Different Windows, different BIOSes?
See if there is a common factor.
If you have Windows VHD or WinPE ISO or WIM file on the Ventoy USB drive, you can reboot to the VHD/WinPE and see if the random bytes have been written if you have a suitable portable app to display the sector?
If so it could be writing on Windows shutdown or BIOS could be writing them.
If not then your OS is 'marking' the drive as it detects/mounts it.

Maybe try this test to eliminate BIOS:

1. Install Ventoy under Windows (or zero bytes)
2. Check sector under Windows
3. UNPLUG USB DRIVE
4. Shutdown Windows and reboot back into Windows
5. CONNECT USB DRIVE
6. Check sector under Windows

**Comment by steve6375** [comment]
Also maybe

1. Install Ventoy under Windows (or zero bytes)
2. Check sector under Windows
3. UNPLUG USB DRIVE
4.      
5. RE-CONNECT USB DRIVE
6. Check sector under Windows

**Comment by Silexium** [comment]
> Maybe try same test on a different system or 3? Different Windows, different BIOSes? See if there is a common factor. If you have Windows VHD or WinPE ISO or WIM file on the Ventoy USB drive, you can reboot to the VHD/WinPE and see if the random bytes have been written if you have a suitable portable app to display the sector? If so it could be writing on Windows shutdown or BIOS could be writing them. If not then your OS is 'marking' the drive as it detects/mounts it.
> 
> Maybe try this test to eliminate BIOS:
> 
>     1. Install Ventoy under Windows (or zero bytes)
> 
>     2. Check sector under Windows
> 
>     3. UNPLUG USB DRIVE
> 
>     4. Shutdown Windows and reboot back into Windows
> 
>     5. CONNECT USB DRIVE
> 
>     6. Check sector under Windows

Doing this doesn't write those bytes to the disk.

**Comment by Silexium** [comment]
> Also maybe dont reboot at all...
> 
>     1. Install Ventoy under Windows (or zero bytes)
> 
>     2. Check sector under Windows
> 
>     3. UNPLUG USB DRIVE
> 
>     5. RE-CONNECT USB DRIVE
> 
>     6. Check sector under Windows

This also doesn't write to disk.

**Comment by Silexium** [comment]
Booting into Ubuntu 22.04 LTS & Hiren's BootCD PE & checking the last sector while booted into those OSs shows those random bytes. I'm stumped.

**Comment by Silexium** [comment]
So, it has to be the firmware that's writing this data to disk?

**Comment by steve6375** [comment]
It seems so...
What is mainboard and bios.
Any bios update available?
Maybe go through all bios settings. It may need to store data for raid or encryption or disk password?

**Comment by Silexium** [comment]
> It seems so... What is mainboard and bios. Any bios update available? Maybe go through all bios settings. It may need to store data for raid or encryption or disk password?

Board is ASUS B85M-E
BIOS version is 3602 (the latest version)

**Comment by Silexium** [comment]
Resetting my BIOS to defaults no longer writes those bytes to disk.

**Comment by Silexium** [comment]
> Ok, well done. That's proved it! Not a Ventoy issue!

Now, the question is: what setting(s) is/are causing this issue?

**Comment by Silexium** [comment]
Disabling CSM causes this issue >:P

**Comment by steve6375** [comment]
just a thought. You say it happens if you enable secure boot. How are you testing this?
I mean how are you secure booting and what are you secure booting to (Windows system on hard disk)?

If secure booting to Ventoy - are you having to use MokManager at all?
If so, could it be caused by something that you are booting to - e.g. EFI boot stub or MokManager?

**Comment by Silexium** [comment]
> just a thought. You say it happens if you enable secure boot. How are you testing this? I mean how are you secure booting and what are you secure booting to (Windows system on hard disk)?
> 
> If secure booting to Ventoy - are you having to use MokManager at all? If so, could it be caused by something that you are booting to - e.g. EFI boot stub or MokManager?

Actually, I did some more testing & it seems that with CSM enabled, the issue no longer occurs. With CSM disabled, those bytes get written to disk. In both cases, Secure Boot was disabled. As for secure booting to Ventoy, I don't have to use MokManager. Ventoy boots fine regardless if SB is turned on or not. Windows is the only OS installed on my system.

**Comment by Silexium** [comment]
I did find this [issue](https://rog.asus.com/forum/showthread.php?114955-GPT-header-corruption) about ASUS boards corrupting the GPT header when USB storage devices were inserted into the system, maybe it's related to this issue?

**Comment by steve6375** [comment]
Yes - this post sounds like a reason
_I had the same issue when I just updated my BIOS to 1302. What I did was set the GPT recovery policy in the boot options to Auto Recovery. After that my drive booted normally again._

**Comment by steve6375** [comment]
It may be that a BIOS update causes a bit set in eerom (or battery-backed cmos) to be misinterpreted and it is then writing something to the backup GPT header to mark it as 'valid' so it knows it can use it, if the primary GPT header is damaged? Resetting to defaults put all bits as the BIOS expects and maybe stops the GPT Recovery policy from being activated.

**Comment by Silexium** [comment]
OK, so I just did some poking around in BIOS ROMs for my board & found that those 420 bytes are present in 3602 (version I'm running), whereas they aren't present in 3504 (version that I used previously).

3504
![](https://user-images.githubusercontent.com/87285693/174080739-15d61c8f-8b85-4e28-901f-1bea89398737.png)

3602
![](https://user-images.githubusercontent.com/87285693/174080871-58dbdad8-6501-467c-b695-988d7a55d9b3.png)

**Comment by Silexium** [comment]
> It may be that a BIOS update causes a bit set in eerom (or battery-backed cmos) to be misinterpreted and it is then writing something to the backup GPT header to mark it as 'valid' so it knows it can use it, if the primary GPT header is damaged? Resetting to defaults put all bits as the BIOS expects and maybe stops the GPT Recovery policy from being activated.

That could be what's happening. This board, however, doesn't have any GPT recovery settings. Searching the manual for "GPT" returns nothing & searching for "recovery" only lists results for recovering the BIOS.

**Comment by Silexium** [comment]
I probably should have mentioned this earlier, but my SSD & HDD have normal backup GPT headers regardless of BIOS settings. This only seems to affect USB drives.
