### ISSUE TITLE
[issue]: Unable to install Clear Linux

### ISSUE THREAD

**Issue by kojq** [ventoy/Ventoy#1674]
### Official FAQ

- [x] I have checked the official FAQ.

### Ventoy Version

1.0.76

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR and GPT

### Disk Capacity

32GB

### What happened?

Using either MBR or GPT, Clear Linux will not recognize the installation media when attempting installation via the **live image** with Ventoy; however, this is not the case for other live USB utilities. In addition, installing via **TTY** is not possible either. As a result, there is no way to install Clear Linux. Clear Linux is labeled as a tested OS.

**Comment by kojq** [comment]
I have noticed #708 and did not see any debug info during boot. Closing this issue may help in closing #820.

**Comment by ventoy** [comment]
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/2509822410
https://www.ventoy.net/en/doc_github_ci.html

**Comment by kojq** [comment]
The artifacts were not uploaded for the last two CI releases.

**Comment by ventoy** [comment]
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/2513313544

**Comment by kojq** [comment]
This has been resolved.👍
