### ISSUE TITLE
Ventoy2Disk_X64.exe v1.0.76 shows as v1.0.0.3 

### ISSUE THREAD

**Issue by truthsword** [ventoy/Ventoy#1675]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.76

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

512GB

### What happened?

A bug happened!

![](https://i.imgur.com/TFKE4om.png)

**Comment by ventoy** [comment]
This version number is just for `Ventoy2Disk.exe` file not for Ventoy project.
These `.exe` files may keep unmodified for many Ventoy releases.
For example, these `.exe` files are the same in Ventoy 1.0.73/1.0.74/1.0.75
