### ISSUE TITLE
vdiskchain 如何添加全局控制选项 VTOY_LINUX_REMOUNT=1，启用对 vDisk 所在卷访问支持

### ISSUE THREAD

**Issue by pdj9na** [ventoy/Ventoy#1678]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

vdiskchain

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

4GB

### Disk Manufacturer

Kingston

### Image file checksum (if applicable)

Yes.

### What happened?

vdiskchain 目前不支持Linux系统对 vDisk 所在卷的访问，VTOY_LINUX_REMOUNT 全局参数也不知如何设置

**Comment by ventoy** [comment]
你可以在 vDisk 内部的OS里面的 grub.cfg 中，增加一个  `VTOY_LINUX_REMOUNT=1` 的内核启动参数，效果一样。

**Comment by ventoy** [comment]
Duplicate with https://github.com/ventoy/vdiskchain/issues/9
