### ISSUE TITLE
CentOS 设置启动参数 VTOY_LINUX_REMOUNT=1 启动时，挂载 vtoy 所在分区失败

### ISSUE THREAD

**Issue by pdj9na** [ventoy/Ventoy#1679]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.76

### What about latest release

No. I didn't try the latest release.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

4GB

### Disk Manufacturer

Kingston

### What happened?

Fedora36、CentOS8 设置参数 VTOY_LINUX_REMOUNT=1 启动时无效

**Comment by pdj9na** [comment]
![IMG_20220617_211342](https://user-images.githubusercontent.com/39616196/174311064-060990d2-dcef-4520-bdd6-aafd3f75794d.jpg)
![IMG_20220617_211939](https://user-images.githubusercontent.com/39616196/174311138-8029c682-7c63-4935-8ec4-cdabaa338c59.jpg)
![IMG_20220617_211706](https://user-images.githubusercontent.com/39616196/174311222-58b6a755-67e1-4fce-893c-70ce9ff96dc8.jpg)
![IMG_20220617_212211](https://user-images.githubusercontent.com/39616196/174311456-6e29ced9-e4a1-4d79-917c-27fc48bb0278.jpg)

**Comment by pdj9na** [comment]
已更新到 1.0.76 测试过，问题依然存在
请问大佬，已测试过且能正常支持 VTOY_LINUX_REMOUNT=1 参数的 Linux 发行版有哪些？

**Comment by ventoy** [comment]
1. 你这个是通过 Ventoy 安装正常的方式启动的，还是通过 vdiskchain 的方式启动的？
2. 在终端执行以下几个命令看下结果
```
cat  /proc/cmdline
lsmod | grep dm
```

**Comment by pdj9na** [comment]
能不能换一种方式避开这个问题，先创建一个虚拟设备如 /dev/sda3-ventoy，然后把 vDisk 磁盘放到 /dev/sda3-ventoy 下面，lsblk 就形如：
sda
...
|---sda3-ventoy
     |---ventoy1
     |---ventoy2
...
这种方式就与现有物理设备完全独立开了,就自然没了访问问题

**Comment by ventoy** [comment]
没用的。你还没回答我上面的问题。

**Comment by pdj9na** [comment]
两种方式都试过，都不行

**Comment by ventoy** [comment]
Fedora 36 .vtoy 文件拷贝到Ventoy U盘上，全局控制插件中开启 `VTOY_LINUX_REMOUNT=1`，启动之后， .vtoy 文件所在的分区不能挂载， 是吗？
启动后在终端执行  `lsmod | grep dm`  结果传上来看一下。

**Comment by ventoy** [comment]
前几天还有人测试  deepin的系统是OK的。 https://github.com/ventoy/Ventoy/issues/1655

**Comment by pdj9na** [comment]
Fedora CentOS RHEL 这3种有没有人试过?我看了命令结果,参数没有传递进去

**Comment by pdj9na** [comment]
![IMG_20220618_163529](https://user-images.githubusercontent.com/39616196/174430129-941be20f-fa7c-44fd-859c-3cb8b92f0831.jpg)

**Comment by pdj9na** [comment]
我在 CentOS Stream8 上也试过,问题依然存在

**Comment by pdj9na** [comment]
参考 https://github.com/ventoy/vdiskchain/issues/9#issuecomment-1158878013
已成功摸索出解决办法:
编辑 /etc/default/grub,在 GRUB_CMDLINE_LINUX 里面添加内核启动参数 VTOY_LINUX_REMOUNT=1
然后执行命令:
grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
```其中的 "fedora" 由系统决定

**Comment by pdj9na** [comment]
终于可以自由玩耍 Linux 的世界了! 之前作为主机系统的 Windows 可以作为 Linux 主机下 VirtualBox 的虚拟机了

**Comment by pdj9na** [comment]
对 CentOS Stream8 也做同样的处理，却不能生效，差别就是 sda3 变成了 sda4
![IMG_20220618_223533](https://user-images.githubusercontent.com/39616196/174444752-6dbc7112-3c2c-44da-bcfe-cbc588de81c2.jpg)
4

**Comment by pdj9na** [comment]
我把 虚拟盘移动到 sda3 再测试，问题依然存在
![IMG_20220618_235435](https://user-images.githubusercontent.com/39616196/174446856-1bfe1482-04ef-456e-b4f1-6e5c4788bc8d.jpg)

**Comment by pdj9na** [comment]
http://www.xjishu.com/zhuanli/55/202011497064.html
一种物理机启动qcow2格式系统镜像的方法及系统与流程
https://jingyan.baidu.com/article/75ab0bcb9ddb16d6874db26c.html
qcow2镜像怎么启动

**Comment by ventoy** [comment]
vDisk 不支持 qcow2 格式。

**Comment by pdj9na** [comment]
dmsetup 创建的 multipath 型设备有可能支持可变大小的 vDisk 吗

**Comment by pdj9na** [comment]
CentOS Stream8 目前使用正常
![IMG_20220619_181954](https://user-images.githubusercontent.com/39616196/174476548-1b503c6d-06bf-4fdd-81b7-735858031ee5.jpg)
![IMG_20220619_182115](https://user-images.githubusercontent.com/39616196/174476555-28906f5c-1303-4a83-9b0a-ded3b70bc2a9.jpg)

**Comment by pdj9na** [comment]
# 使用 vdiskchain 时，可执行下列命令设置变量 VTOY_LINUX_REMOUNT
sed -i '/GRUB_CMDLINE_LINUX=/{ s|"$| VTOY_LINUX_REMOUNT=1&| }' /etc/default/grub
grub2-mkconfig -o `readlink -f /etc/grub2-efi.cfg`

**Comment by pdj9na** [comment]
CentOS 再生版 Rocky Linux 有新问题，执行 vtoyboot.sh 后，再通过 Ventoy 启动，会卡在开机步骤不过去，然后再用 VirtualBox 启动，问题依然存在
![IMG_20220620_142044](https://user-images.githubusercontent.com/39616196/174544182-e1984bd5-0d70-4e42-978d-6cc94318c320.jpg)
![IMG_20220620_142151](https://user-images.githubusercontent.com/39616196/174544214-84dc1725-991b-4254-9c3d-2e958f212b55.jpg)
![IMG_20220620_142919](https://user-images.githubusercontent.com/39616196/174544270-4ee0c2cd-f573-4452-9844-8b1c20d3dc33.jpg)
![IMG_20220620_143140](https://user-images.githubusercontent.com/39616196/174544292-121a4cad-f91f-4dd0-8852-769151ee52f6.jpg)

**Comment by ventoy** [comment]
执行完 vtoyboot.sh 之后，紧接着重启 VirtualBox，这次能启动吗？

**Comment by pdj9na** [comment]
我是先用 vdiskchain 启动了一次,发现过不去,然后再用 Ventoy U 盘启动,依然过不去,然后 VirtualBox 也过不去;
忘了是否在首次执行完vtoyboot.sh 之后紧接着重启 VirtualBox 了
我重新装 Rocky 之后,先用 Ventoy U 盘启动,可正常启动,然后 vdiskchain 也能启动,VirtualBox 也能启动

**Comment by ventoy** [comment]
不支持。可变大小的镜像格式就意味着内核启动后必须先挂载镜像文件所在的文件系统才可以找到这个文件进行处理。很多Linux系统在启动阶段是无法挂载exfat和ntfs系统的，能挂载的也基本上都是使用fuse的方式，性能很差，可用性不高。 另外，grub也要能识别和挂载这种可变大小的镜像格式才行。---- 回复的原邮件 ***@***.***>发送日期2022年06月19日 14:47 ***@***.***> ***@***.******@***.***>主题Re: [ventoy/Ventoy] CentOS 设置启动参数 VTOY_LINUX_REMOUNT=1 启动时，挂载 vtoy 所在分区失败 (Issue #1679)

dmsetup 创建的 multipath 型设备有可能支持可变大小的 vDisk 吗



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/ventoy/Ventoy/issues/1679#issuecomment-1159630845",

"url": "https://github.com/ventoy/Ventoy/issues/1679#issuecomment-1159630845",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
