### ISSUE TITLE
[issue]: Add a config option to disable parttion checks (error: This is NOT a standard Ventoy device and is NOT supported)

### ISSUE THREAD

**Issue by szafran81** [ventoy/Ventoy#1680]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.76

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GB, 64GB, 256GB, 720GB, 1TB

### Disk Manufacturer

SanDisk, Samsung, ADATA, Netac

### What happened?

Hi,

The USB drives created with Ventoy are created in a way that Win11 chkdsk detects some kind of errors (but not always, which is really weird - and on the other hand sometimes Windows shows a window that there are errors on the drive right after connecting it to USB) on the first partition (at least in my case). As for using the drive under windows this didn't present any anomalies (yet!). But the drive can't be mounted properly because of that under linux (ntfs-3g under Clonezilla says that there is some data left by Windows and I need to do a proper shutdown of Windows to mount it - did that, it didn't help).
I've tried fixing those error with tools under Windows and linux, and basically only thing that worked was to change the size of the first partition under GParted, but after that Ventoy presented me with an error as in the topic.

It would be nice to have an option (even hidden, to manually put it in the "ventoy.json" config file) to disable those checks and let users resize and move the partitions as they see fit. Now the only way to do that is to recreate the drive using Ventoy installer and add a third partition (this one doesn't contain any errors, and is properly mountable under linux).

I've created a few test drives with third partition and just put Clonezilla on them, and after bootup and starting Clonezilla exactly the same thing happens - when I try to mount first partition then it says to properly shutdown Windows (which never fixes the problem), and trying to mount thirt partition always works without errors.

I always use NTFS on the first and third partition.

**Comment by ventoy** [comment]
The partition layout if part of Ventoy solution design from the beginning.
So if the partition layout changed, Ventoy will not work, that's why the check added.

By default, after you boot into Linux, the 1st partition can not be mounted because of the dm limitation of linux kernel.
Did you use the `VTOY_LINUX_REMOUNT` option in ventoy.json to make the 1st partition mountable under Linux ?

**Comment by szafran81** [comment]
VTOY_LINUX_REMOUNT - will test this today, and give feedback. But that would help only with mounting under linux. What about unfixable errors under Windows?

Also I've got a Win11 vhdx image that fails to apply updates with Ventoy. Those updates apply without problems with drive created with WinToUSB software. Can this be all related?

I'm wondering what could prevent Ventoy from working when someone changes the size of the first partition without changing anything about second partition? Since only the second partition is booting.

**Comment by ventoy** [comment]
I haven't encountered this problem in Windows, so I have no idea about it.
If reduce the size of partition 1 can fix the issue in your computer, you can do as follows:
1. reduce the size of partition 1
2. delete partition 2
3. use `Non-destructive installation`

**Comment by szafran81** [comment]
VTOY_LINUX_REMOUNT works fine with Clonezilla iso.
I'lll recreate my USB stick from scratch now. Tomorrow I'll be using my Win11 vhdx image. I'll check after that what's happening with those errors, and if it still can't do the updates.

**Comment by szafran81** [comment]
Ok. Seems that almost everything works now.

Everything except the Win11 update.
Any ideas why?
What's happening now:
1. Win11 downloads the update (KB5014697)
2. I restart the OS
3. The update goes fine up to 30% before restart
4. After restart for a moment it starts to continue to install the update
5. Then it shows that something went wrong with the update and it's goint to revert changes

I've tried a couple of times to install this - didn't work.

On bare metal this update installs fine (at least on my PC and laptop).

**Comment by steve6375** [comment]
To boot from VHD on Ventoy, you may need a fully booted VHD (not one recently created by Setup).
If recently created by Setup or after applying wim, next reboot will try to update BCD on boot partition but it does not exist when running from a multiboot drive.
Solution is to boot VHD several times on VM or bare metal system and then copy the updated VHD file onto Ventoy USB drive.

**Comment by szafran81** [comment]
The VHDX is a couple of month old - booted hundreds of times, and updated a lot of times (but via WinToUSB before).

So you're saying that each time this is going to happen I'd have to run it in a VM and update it like that?

**Comment by steve6375** [comment]
AFAIK, some updates may fail if they need to change the BCD (or maybe UEFI BIOS?)  but I don't have much experience in this area.
I was suggesting that you try using a fully updated VHDx because one of the updates it is trying to apply may be the reason it is failing. It may be that whenever it runs an update that causes this issue, you will have to update the VHDx on your WinToUSB drive first and then copy it to Ventoy drive?

**Comment by szafran81** [comment]
Recreating the drive with WinToUSB just to update is a bit much work (or maybe I'd have to keep a separate drive just for updates). I'll try to update it via Hyper-V later.
Thank you for the info.

**Comment by szafran81** [comment]
I had to reinstall the OS under Hyper-V and then use it's vhdx to boot.
Vhdx created by WinToUSB was unable to boot under Hyper-V.
But now I can just connect the drive to my main PC and run the updates via Hyper-V.

Thank you for all the help guys.
