### ISSUE TITLE
[issue]: TrueNAS Core 13.0 does not boot

### ISSUE THREAD

**Issue by Silejonu** [ventoy/Ventoy#1684]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.77

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

256GB

### Disk Manufacturer

Samsung

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://download.freenas.org/13.0/STABLE/RELEASE/x64/TrueNAS-13.0-RELEASE.iso

### What happened?

I tested both MBR and GPT. The ISO partition is in exFAT. I tested with two flash drives, both with plenty of empty space left.

As I did with #628, I checked the image with blocklist (the output is `1`), and I reset my flash drive then reinstalled Ventoy. The issue is still present. I also tried memdisk to no avail.

Here is the error I get:
![IMG_20220619_200651](https://user-images.githubusercontent.com/48565914/174496652-73074d06-bec0-4812-9879-87944a3c4581.jpg)

**Comment by ventoy** [comment]
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/2527314496
https://www.ventoy.net/en/doc_github_ci.html

**Comment by Silejonu** [comment]
> Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/2527314496 https://www.ventoy.net/en/doc_github_ci.html

I just tested, and it worked correctly.
