### ISSUE TITLE
[bug]: Entering lowercase yes does not take effect

### ISSUE THREAD

**Issue by wang-qa** [ventoy/Ventoy#1685]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.77

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

64

### Image file download link (if applicable)

github

### What happened?

Entering lowercase yes does not take effect
![image](https://user-images.githubusercontent.com/58168764/174511599-d338bb90-22f0-45d1-8d0d-6b6e3e72e7d3.png)

**Comment by ventoy** [comment]
Yes, the prompt is already very clear. You must input YES (all upper case).
This is not an issue, it was designed so from the beginning.
