### ISSUE TITLE
[Success Image Report]: Linux Lite 6.0

### ISSUE THREAD

**Issue by Silexium** [ventoy/Ventoy#1687]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.77

### BIOS Mode

Both

### Partition Style

GPT

### Image file name

linux-lite-6.0-64bit.iso

### Image file checksum type

SHA256

### Image file checksum value

31bf383a283393f82d037ff5afe16e6d56182cee7518614209ff1601d27693fd

### Image file download link (if applicable)

https://quantum-mirror.hu/mirrors/pub/linuxlite/isos/6.0/linux-lite-6.0-64bit.iso

### Test envrionment

Custom PC

### More Details?

This image file booted successfully in Ventoy.

CPU: Intel Xeon E3-1231 v3 @ 3.40GHz
MB: ASUS B85M-E
RAM: 8GB 1333MHz DDR3
GPU: GTX 1060 3GB

**Comment by ventoy** [comment]
Thanks!
