### ISSUE TITLE
[Success Image Report]: Manjaro GNOME 21.3.0

### ISSUE THREAD

**Issue by Silexium** [ventoy/Ventoy#1689]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.77

### BIOS Mode

Both

### Partition Style

GPT

### Image file name

manjaro-gnome-21.3.0-220617-linux515.iso

### Image file checksum type

SHA1

### Image file checksum value

3c0267e815e0cb8a25d922059fa5cfae5ef20dad

### Image file download link (if applicable)

https://download.manjaro.org/gnome/21.3.0/manjaro-gnome-21.3.0-220617-linux515.iso

### Test envrionment

Custom PC

### More Details?

This image file booted successfully in Ventoy.

CPU: Intel Xeon E3-1231 v3 @ 3.40GHz
MB: ASUS B85M-E
RAM: 8GB 1333MHz DDR3
GPU: GTX 1060 3GB

**Comment by ventoy** [comment]
Thanks!
