### ISSUE TITLE
[Success Image Report]: Pop_OS! 22.04 LTS

### ISSUE THREAD

**Issue by Silexium** [ventoy/Ventoy#1692]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.77

### BIOS Mode

Both

### Partition Style

GPT

### Image file name

pop-os_22.04_amd64_nvidia_9.iso

### Image file checksum type

SHA256

### Image file checksum value

418ca4ea24bfa855cf8d11451cde8b5dff8ff5ab3688244018d1e4543f6ae081

### Image file download link (if applicable)

https://pop-iso.sfo2.cdn.digitaloceanspaces.com/22.04/amd64/nvidia/9/pop-os_22.04_amd64_nvidia_9.iso

### Test envrionment

Custom PC

### More Details?

This image file booted successfully in Ventoy.

CPU: Intel Xeon E3-1231 v3 @ 3.40GHz
MB: ASUS B85M-E
RAM: 8GB 1333MHz DDR3
GPU: GTX 1060 3GB

**Comment by ventoy** [comment]
Thanks!
