### ISSUE TITLE
[Enhancement]: Super-UEFIinSecurebootDisk v3.4

### ISSUE THREAD

**Issue by KrinalPatel889** [ventoy/Ventoy#1695]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.76

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

64

### Image file download link (if applicable)

https://github.com/ValdikSS/Super-UEFIinSecureBoot-Disk/releases

### What happened?

Hi @ventoy,

Super-UEFIinSecurebootDisk by @ValdikSS has been updated to v3.4.
Please update it in the next release. :)

**Comment by ventoy** [comment]
1.0.78 included
