### ISSUE TITLE
KaOS - cannot find boot volume

### ISSUE THREAD

**Issue by tejasraman** [ventoy/Ventoy#1696]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.76 (EDIT: Tried 10.7.7)

### What about latest release

EDIT: (Yes, I tried the latest release)

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

16GB

### Disk Manufacturer

Patriot Memory

### Image file checksum (if applicable)

No.

### Image file download link (if applicable)

https://kaosx.us/pages/download/

### What happened?

When I tried to boot KaOS, I got a ‘no boot volume found’ error. Upon checking the grub 3 arguments line, it specified a boot volume name. I tried changing this but it gave another error.

Changing to 10.7.7 made no difference to the issue.

why?

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/175822295-4fffcb8c-bd8e-4819-9439-2f8f2974e8b0.png)
grubfm and agFM UEFI menu in Easy2Boot work OK though using e2b\partnew boot method.

**Comment by tejasraman** [comment]
ya... that's the exact issue I have.
Tried 1.0.77, no difference.

**Comment by tejasraman** [comment]
Are you suggesting I try Easy2Boot? Or does @ventoy know why only KaOS seems to have these errors?

**Comment by steve6375** [comment]
You can try  the grubfm_multiarch.iso
Just add it to Ventoy and then boot to it
Then select the KaOS.iso from the grubfm menu
https://github.com/a1ive/grub2-filemanager/releases/download/v7.4.0/grubfm_multiarch.iso

Must be a bug in Ventoy? Did you try ctrl+r ?

**Comment by tejasraman** [comment]
I'll try right now and report back. Thanks @steve6375 !

**Comment by tejasraman** [comment]
Thanks so much @steve6375 ! The ISO actually worked (although I still think that @ventoy should fix the issue) but for now, it seems to work![image](https://user-images.githubusercontent.com/96961804/175823147-226d7f94-6543-445b-9c16-b305797e98e5.jpeg)

**Comment by ventoy** [comment]
@tejasraman 
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/2566203646
https://www.ventoy.net/en/doc_github_ci.html

**Comment by tejasraman** [comment]
The CI build still shows the same error. Ugh.

**Comment by ventoy** [comment]
When you dropped into the rootfs shell, please run `cat  /ventoy/log`  and give the result here.

**Comment by ventoy** [comment]
@tejasraman 
Try this new CI build please: https://github.com/ventoy/Ventoy/actions/runs/2569827190

**Comment by tejasraman** [comment]
@ventoy that worked amazingly well! My KaOS iso booted fine with the new CI build you gave. Thanks so much!
