### ISSUE TITLE
Garuda (KDE Dr460nized 220614] ISO

### ISSUE THREAD

**Issue by tejasraman** [ventoy/Ventoy#1697]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.76, 1.0.70, 1.0.77

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

garuda-dr460nized-linux-zen-220614.iso

### Image file checksum type

SHA256

### Image file checksum value

17f05ce5333c316b18095efc9ca8be5e604f7f05a4c18acffa3bc7ed1309495a

### Image file download link (if applicable)

https://garudalinux.org/downloads.html

### Test environments

HP Desktop M01-F0016, Samsung Chromebook 3 (Custom EFI), PC with A10-6800K COU

### More Details?

This image file booted successfully in Ventoy versions 10.7.0, 10.7.6, and 10.7.6

**Comment by ventoy** [comment]
Thanks!
