### ISSUE TITLE
[issue]: Secure boot related. error

### ISSUE THREAD

**Issue by oklokl** [ventoy/Ventoy#1699]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.77

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32G

### Disk Manufacturer

samsung sd card

### Image file checksum (if applicable)

No.

### Image file download link (if applicable)

https://github.com/ventoy/Ventoy/releases/download/v1.0.77/ventoy-1.0.77-windows.zip

### What happened?

A bug happened!
![20220628＿231632](https://user-images.githubusercontent.com/1571600/176205997-3a36b71c-bbd4-4a7f-a91e-daec3a5904fd.jpg)
I have an Intel 4th gen motherboard.
When I use Secure Boot Windows 8 on my computer, I get the same bug as the picture.
So I disable security and boot.
Windows is Windows 11. home kr
https://docs.microsoft.com/ko-kr/windows-insider/isos

**Comment by Silexium** [comment]
Look [here.](https://www.ventoy.net/en/doc_secure.html)

**Comment by oklokl** [comment]
thank you. It would be nice if the AI automatically selects it.
:)
