### ISSUE TITLE
能不能手动调整分区大小？

### ISSUE THREAD

**Issue by lowy** [ventoy/Ventoy#17]
我想扔一个refind到EFI分区 作为电脑启动项的备份 不知道可不可行？

**Comment by ventoy** [comment]
当前不支持调整分区大小。
对于你的这个需要，我建议把refind做成一个可启动的ISO文件的形式，就当成一个普通的ISO文件放在U盘的第一个分区里就OK了。 想用的时候直接Ventoy去启动这个ISO即可。
grub2-filemanager 就可以以这种形式存在。

**Comment by blackcrack** [comment]
@lowy 
使用MacriumReflect创建USB记忆棒PE Boot.iso。 将Macrium_Reflect_boot.iso移至USB。 从USB上的Macrium_Reflect_boot.iso开始，还原或备份分区，然后在USB恢复文件夹中创建恢复文件。
如果其他备份/还原程序包含USB驱动程序，则也可以这样做。 Macrum使用订购系统中当前使用的USB驱动程序创建PE。 这很重要，因此您也可以访问USB数据介质。

best Blacky
