### ISSUE TITLE
Windows 10 IoT LTSC 2021 reported as "Unknown Edition"

### ISSUE THREAD

**Issue by Silexium** [ventoy/Ventoy#1700]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.77

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

128GB

### Disk Manufacturer

Kingston

### What happened?

Windows 10 IoT LTSC 2021 is reported as "Unknown Edition" in "log.txt".

`[2022/06/28 19:27:55.658] Windows Version: <<Windows 10 (Unknown Edition), 64-bit (Build 19044.1766)>>`

![](https://user-images.githubusercontent.com/87285693/176246856-877c20b2-a0f7-4a10-b89c-7d54246fa2c0.png)

**Comment by ventoy** [comment]
This log just provides a summary of the system information, so `Windows 10` is enough, just ignore the unknown edition.
