### ISSUE TITLE
[issue]: Add support for more than 1 partion

### ISSUE THREAD

**Issue by ehab2012** [ventoy/Ventoy#1709]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.77

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Steps to reproduce:
- Install Ventoy on a usb.
- resized the main "big Ventoy" partition to a smaller size.
- create a new partition on the space gained.
- boot usb

### Expected:
Ventoy boots and lists any isos on the Ventoy labeled partition.

### Outcome:
boot fails with - Disk partition layout check failed - 
![image](https://user-images.githubusercontent.com/1481918/176995731-23ab6e28-62e0-445d-ad2c-9f1b1af825c0.png)

### Suggested solution:
update the **ventoy_check_official_device()** | **ventoy_cmd.c** 
so it does not fail if a partition with label Ventoy exists.

hopefully we can utilize the usb for other purposes along with Ventoy as the boot king :)

**Comment by milday** [comment]
Try using partition configuration when installed ventoy in Option menu. Check preserve some space bla bla...
Then put size u want for extra space beside ventoy partition.

**Comment by steve6375** [comment]
Do not resize. Use the option in  Ventoy2Disk to reserve some space at the end of the drive when you make the Ventoy drive.
If you resize then Partition 2 will be moved and may not be in the correct place for ventoy to recognise it.

https://ventoy.net/en/doc_disk_layout.html

see end of page...

When install Ventoy, you can enable and set the reserved space with "Option" ---> "Partition Configuration" (Windows) or "-r" option (Linux). The reserved space configuration is only for installation process.
The reserved space must at the bottom of the disk
**Ventoy MUST use Part1 and Part2, don't change their position and size.**
You can create Part3 and Part4 with the reserved space and use them as you want.
