### ISSUE TITLE
亲测不支持USMv6.iso如图所示

### ISSUE THREAD

**Issue by szbjb** [ventoy/Ventoy#172]
### U盘魔术师v6特别版(USMv6)
[https://www.sysceo.com/Software-softwarei-id-129.html](https://www.sysceo.com/Software-softwarei-id-129.html)

![image](https://user-images.githubusercontent.com/34825299/83247670-74085d80-a1d6-11ea-9b8c-2eda82aab297.png)
![image](https://user-images.githubusercontent.com/34825299/83248348-85059e80-a1d7-11ea-98da-1d2963be0d15.png)
![image](https://user-images.githubusercontent.com/34825299/83248379-8c2cac80-a1d7-11ea-944b-0be5eb065740.png)

![image](https://user-images.githubusercontent.com/34825299/83248394-9189f700-a1d7-11ea-9b2a-115c5d24e89e.png)

![image](https://user-images.githubusercontent.com/34825299/83248403-95b61480-a1d7-11ea-8214-291177f3c829.png)

等待修复支持  感谢

**Comment by ventoy** [comment]
从 2020/05/30 开始，USM正式版本已经原生支持Ventoy。请打开USM程序升级到最新版本。
详情请参考USM的修改日志。

**Comment by szbjb** [comment]
已解决
