### ISSUE TITLE
[issue]: Fedora CoreOS Live ISO fails to maintenance mode

### ISSUE THREAD

**Issue by skyblaster** [ventoy/Ventoy#1727]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.78

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64GB

### Disk Manufacturer

Kingston Exodia

### Image file checksum (if applicable)

No.

### Image file download link (if applicable)

https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/36.20220618.3.1/x86_64/fedora-coreos-36.20220618.3.1-live.x86_64.iso

### What happened?

I've been using Ventoy since release 1.0.71 and it's worked with virtually every ISO I've thrown at it until now.
Using the latest Fedora CoreOS Live ISO from the stable channel (linked above), I'm unable to fully boot to a live environment. I tested booting on two machines and end up at the Maintenance mode prompt.

Testing on a spare SD card and reader, I used dd to write the image and it boots successfully.

I updated my UEFI/GPT flash drive to Ventoy 1.0.78, however I still end up in maintenance mode.

**Comment by steve6375** [comment]
I get same issue with same ISO under VBox 5. 
Works OK with E2B/grubfm/agFM though.

**Comment by ventoy** [comment]
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/2654051929
https://www.ventoy.net/en/doc_github_ci.html

**Comment by skyblaster** [comment]
Works great. Thanks!
The only difference I can see visually is a lower resolution during the grub and initial loading stages.
