### ISSUE TITLE
openSUSE Leap 15.3 设置启动参数 VTOY_LINUX_REMOUNT=1 启动时，挂载 vtoy 所在分区失败

### ISSUE THREAD

**Issue by pdj9na** [ventoy/Ventoy#1729]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.76

### What about latest release

No. I didn't try the latest release.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

4GB

### What happened?

openSUSE Leap 15.3 里面执行 vtoyboot.sh，并添加内核启动参数 VTOY_LINUX_REMOUNT=1 并重启系统
然后通过 Ventoy U盘启动，在挂载 vdisk 磁盘所在分区时出错：fuse: mount failed: Device or resource busy

**Comment by ventoy** [comment]
1.  是否使用的最新的 vtoyboot-1.0.22版本？https://github.com/ventoy/vtoyboot/releases/tag/v1.0.22 （需要下载ISO文件，提取里面的压缩包使用）
2. 你同样的方式直接启动 openSUSE Leap 15.3 的ISO文件，然后通过全局控制插件设置 VTOY_LINUX_REMOUNT 为1之后，启动ISO文件之后，能不能挂载ISO文件所在的分区。

**Comment by pdj9na** [comment]
vtoyboot 是最新的
![Screenshot_20220712_204615](https://user-images.githubusercontent.com/39616196/178493093-2f88ef87-d8bb-44c0-8d6f-d0045090656e.png)

**Comment by pdj9na** [comment]
我执行脚本之前启用了 SecureBoot，后来感觉搞模块签名麻烦就禁用了
执行了 mokutil --disable-validation

**Comment by pdj9na** [comment]
执行命令：
grub2-editenv list
grub2-mkconfig -o /boot/grub2/grub.cfg
会出错

**Comment by ventoy** [comment]
1. 磁盘性能问题。你是使用 dd 直接测试的裸盘读写还是拷贝文件测试的？ 如果是通过文件测试的话，Linux下挂载NTFS/exFAT等分区使用的是fuse的方式，天生就慢。这个和ventoy没关系。如果格式化成FAT32或者是ext4/xfs等文件系统再测试的话就快乐。
2. grub2-editenv 命令在 vdisk 环境下不能执行，必须在原来虚拟机环境下执行。

**Comment by pdj9na** [comment]
拷贝文件测试

**Comment by ventoy** [comment]
拷贝文件测试就是这个原因。
抛开Ventoy/vDisk不论，你直接一个普通U盘，格式化成NTFS系统。然后插在Windows系统中拷贝文件的速度就是比插在Linux系统中拷贝文件的速度快很多。这个是受限于当前Linux系统中挂载NTFS的方式。

**Comment by pdj9na** [comment]
![Screenshot_20220713_132010](https://user-images.githubusercontent.com/39616196/178657627-9263db6c-0fdf-463c-857d-526468f237e0.png)
![Screenshot_20220713_131323](https://user-images.githubusercontent.com/39616196/178657637-80ccf1a6-b1a1-417e-96b5-e08cc6e1add6.png)

**Comment by pdj9na** [comment]
![Screenshot_20220713_135106](https://user-images.githubusercontent.com/39616196/178660457-7e602fc8-6ff2-4638-ba84-d417a76cc5ed.png)
Rocky8.6 update kernel

**Comment by ventoy** [comment]
更新使用附件中这个 vtoyboot 版本试试。不用重新制作，把后缀名改回去，使用VirtualBox 重新启动进去之后执行这个新版本的 vtoyboot 即可。
执行完之后，再把后缀名改为 .vtoy 使用 Ventoy 启动试试。
[vtoyboot-1.0.23.tar.gz](https://github.com/ventoy/Ventoy/files/9102416/vtoyboot-1.0.23.tar.gz)

**Comment by pdj9na** [comment]
我的 openSUSE 15.3 VirtualBox 无法启动了！你看我上面发的两个图片；ventoy 还是可以启动

**Comment by ventoy** [comment]
Ventoy 启动后的 vdisk环境下重新执行这个 Vtoyboot 也可以。

**Comment by ventoy** [comment]
@pdj9na 
有没有试过这个新版本？

**Comment by pdj9na** [comment]
试过新版本，挂载没有问题了，只是执行下面两个命令还有问题
grub2-editenv list
grub2-mkconfig -o /boot/grub2/grub.cfg
我在 Rocky Linux 8.6 上执行过 grub2-mkconfig 没有问题

**Comment by ventoy** [comment]
grub2-mkconfig -o /boot/grub2/grub.cfg  单独执行这个命令是什么错误？

**Comment by pdj9na** [comment]
![Screenshot_20220727_003112](https://user-images.githubusercontent.com/39616196/181061609-d7b19af7-dffa-4788-92a5-2bb27ba419db.png)
其实也是 grub2-editenv 的错误

**Comment by ventoy** [comment]
最新的 vtoyboot-1.0.24 应该解决了  grub2-editenv 的错误。

**Comment by pdj9na** [comment]
YaST 控制中心 打开 引导加载器 就会出现这个问题
![Screenshot_20220731_134548](https://user-images.githubusercontent.com/39616196/182012267-a461b5dc-5f4c-4131-8d61-9ed2547a0105.png)

**Comment by pdj9na** [comment]
![Screenshot_20220731_135807](https://user-images.githubusercontent.com/39616196/182012405-b2a364a2-90ba-4fb7-8edb-2da6b4ce68f8.png)

**Comment by pdj9na** [comment]
我的系统分区用的是 btrfs 文件系统

**Comment by pdj9na** [comment]
点 磁盘分区 也会出现相同的问题
![Screenshot_20220731_140952](https://user-images.githubusercontent.com/39616196/182012709-fa516eb5-8b39-4357-97f4-fccf2d2f2cc1.png)

**Comment by ventoy** [comment]
因为在VirtualBox的环境下，系统内只有一个 /dev/sda，在vdisk环境下所有的物理硬盘都会体现，而且 /dev/mapper/ventoy 会代替原来 /dev/sda 的位置。因此所有涉及引导、grub2 等相关配置的地方理论上都需要在原始的 VirtualBox环境下配置，不要在 vdisk环境下配置。
