### ISSUE TITLE
[issue]: Secure Boot Support

### ISSUE THREAD

**Issue by Erick790** [ventoy/Ventoy#1732]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.78

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### What happened?

I already enabled Secure Boot Support but it still doesn't work so I had to disabled secure boot in order to make it work

**Comment by ventoy** [comment]
1. Please try 1.0.76 and 1.0.77 to check that whether all these releases have the same problem.
2. Is there any error screen? Please take a photo about the error if possible.

**Comment by Erick790** [comment]
![error](https://user-images.githubusercontent.com/108352931/178958026-c5117dae-7292-421f-9ebe-c7aee1e878ca.png)

Im gonna try 1.0.76 and 1.0.77
