### ISSUE TITLE
[Success Image Report]: ZFSBootMenu v2.0.0

### ISSUE THREAD

**Issue by Adito5393** [ventoy/Ventoy#1733]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.77

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

zfsbootmenu-release-vmlinuz-x86_64-v2.0.0.EFI

### Image file checksum type

SHA256

### Image file checksum value

ce035bd5f2313b41cc7c6fcfe8f4b21293e6988bf391bbd0fd6e4b1256cb606c

### Image file download link (if applicable)

https://github.com/zbm-dev/zfsbootmenu/releases/download/v2.0.0/zfsbootmenu-release-vmlinuz-x86_64-v2.0.0.EFI

### Test envrionment

Dell OptiPlex 7040

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
