### ISSUE TITLE
[issue]: 新增功能建议：手动设置第一个分区大小

### ISSUE THREAD

**Issue by Alex6357** [ventoy/Ventoy#1737]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.78

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

512G

### What happened?

当前ventoy有在尾部保留一定空间的功能，但是如果需要第一个分区特定的大小会非常麻烦，需要知道磁盘实际空间大小再去算，如果增加直接指定第一个空间大小的功能会方便很多。非常感谢！

**Comment by ventoy** [comment]
1、绝大多数用户是不需要很精确的大小的，以GB大略算一下即可。
2、即使做这个功能，也是最小以MB为单位，如果还有更小粒度的需求也是满足不了的。
所以在Ventoy上面不做这个功能。

如果如果这种特殊需求的话可以按照如下操作：
1、使用DiskGenius删除所有分区
2、使用DiskGenius创建第1个分区，大小按照你自己的要求设置成多少都行（可以1MB对齐，也可以不对齐，都可以）。只要满足这2个条件即可：（1.  分区从1MB位置开始; 2. 分区后面留至少32MB的空间。）
3、使用 Ventoy的无损安装功能安装

**Comment by Alex6357** [comment]
现在手上没有测试U盘，但我记得之前用diskgenius创建分区尝试无损压缩ventoy提示第一个分区不是从1MB开始。还是用Windows自带磁盘管理创建分区比较靠谱。
或者用ventoy先安一遍再删ventoyefi分区调第一个分区大小再无损安装
