### ISSUE TITLE
[issue]: DiskGenius占用导致Ventoy2Disk无法找到U盘

### ISSUE THREAD

**Issue by Alex6357** [ventoy/Ventoy#1738]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.78

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

512G

### What happened?

faq中有相关描述，新发现DiskGenius也会占用磁盘导致Ventoy2Disk扫描不到（而且是一个也扫不到，包括本地硬盘）。

**Comment by ventoy** [comment]
FAQ中已经增加，谢谢！
