### ISSUE TITLE
Impossible to use on External HD

### ISSUE THREAD

**Issue by RafaelTR** [ventoy/Ventoy#174]
You cannot use your external storage. It does not create NTFS partitions for documents, it only creates exFAT. If you resize the boot it breaks.

**Comment by ventoy** [comment]
Hi, 
Ventoy's installer will create an exFAT partition by default. If you want to use NTFS, you need to reformat the 1st partition to NTFS manually.

**Comment by RafaelTR** [comment]
Hello, your tool is incredible, really! How do you do that? I will not be complaining, is that I use external HD. Your tool is in Deepin! You could put file format options and you can choose the size of the partitions, it would look perfect. I want to tell you that the secure boot feature worked very well for me.

**Comment by RafaelTR** [comment]
Reformat the larger partition? exFAT? It does not work! I tried!

**Comment by RafaelTR** [comment]
Formatting works. I thought it wouldn't work, I thought I had some hidden file. I partitioned exFAT and then created an NTFS partition. Thank you! Keep up the great work!

**Comment by RafaelTR** [comment]
Friend, just one more thing, please! As you said, formatting the entire exFAT partition works, but the program does not detect the device, so you cannot update it. That's enough for today, right? 😂 Sorry, it's because I expect a simple program that works like yours for years.

**Comment by ventoy** [comment]
Hi,
After install, Ventoy will create 2 partitions in the USB stick. The 1st partition with exfat (large) 2nd FAT (32MB).

You can reformat the 1st partition to NTFS filesystem, I always do so.
