### ISSUE TITLE
[Success Image Report]: TROMjaro

### ISSUE THREAD

**Issue by knedl1k** [ventoy/Ventoy#1742]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.78

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

TROMjaro 2022.07.07.iso

### Image file checksum type

SHA256

### Image file checksum value

ac34eca15aaf053e6694cba0eae9685dee86dc63654c7080fc2dd0ac82b6cc99

### Image file download link (if applicable)

https://www.drive.tromsite.com/s/qG8rjTNHGT8LGiE/download?path=%2F&files=TROMjaro%202022.07.07.iso&downloadStartSecret=xe9ibjmz9fb

### Test envrionment

OMEN by HP Laptop 15-ce0xx

### More Details?

Booted without any problems and blazingly fast.

**Comment by ventoy** [comment]
Thanks!
