### ISSUE TITLE
[Success Image Report]: BunsenLabs

### ISSUE THREAD

**Issue by knedl1k** [ventoy/Ventoy#1743]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.78

### BIOS Mode

Both

### Partition Style

GPT

### Image file name

lithium-3-amd64.hybrid.iso

### Image file checksum type

SHA256

### Image file checksum value

a17d0364d55352487f4d08d5dc1ad7f789931e911cb4cb2c82cb5255c1ed1d23

### Image file download link (if applicable)

https://ddl.bunsenlabs.org/ddl/lithium-3-amd64.hybrid.iso

### Test envrionment

HP desktop (P5K/EPU)

### More Details?

Booted without any problems.

**Comment by ventoy** [comment]
Thanks!
