### ISSUE TITLE
[Success Image Report]: Pentoo

### ISSUE THREAD

**Issue by knedl1k** [ventoy/Ventoy#1744]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.78

### BIOS Mode

Both

### Partition Style

GPT

### Image file name

pentoo-core-amd64-hardened-2022.0_p20220717.iso

### Image file checksum type

SHA256

### Image file checksum value

087af33fbc4b4ad09693e1f4df3cdc068821e7994c8ed334ce8a9def5d4ce174

### Image file download link (if applicable)

https://ftp.acc.umu.se/mirror/pentoo.ch/Beta/Pentoo_Core_amd64_hardened/pentoo-core-amd64-hardened-2022.0_p20220717.iso

### Test envrionment

HP desktop (P5K/EPU)

### More Details?

Booted without any problems.

**Comment by ventoy** [comment]
Thanks!
