### ISSUE TITLE
[Success Image Report]: Todo en Uno V8 By Borr@s

### ISSUE THREAD

**Issue by porquerserra** [ventoy/Ventoy#1746]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.78

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

fsc-Todo.En.Uno.V8.iso

### Image file checksum type

MD5

### Image file checksum value

887126a31b1c09195b871fdccade019a

### Test envrionment

Fujitsu-Siemens Amilo Pro V3505

### More Details?

This image file booted successfully in Ventoy. Windows XP SP2 installed without problems selecting the option -Instalacion normal con drivers- (Normal installation with SATA drivers). You have to boot the iso image each time that Win XP installer reboots the computer. If not, the Win XP installer cannot finish.

**Comment by ventoy** [comment]
Thanks!
