### ISSUE TITLE
EFI partition should use a different label than EFI

### ISSUE THREAD

**Issue by KanoTheMaster** [ventoy/Ventoy#175]
Simple patch to fix issues with broken UEFI implementations - volume label could be misinterpreted as directory name.

https://kanotix.com/files/fix/ventoy/0001-Changed-FAT-label-to-VENTOY_EFI-EFI-does-not-work-ev.patch

**Comment by ventoy** [comment]
OK, I will update it, thank you.
I always thought the label didn't matter.

**Comment by ventoy** [comment]
I have commited it in Ventoy-1.0.13

**Comment by KanoTheMaster** [comment]
Label is fine, but UEFI has different problems now.
