### ISSUE TITLE
[Success Image Report]: Guix System 1.3.0

### ISSUE THREAD

**Issue by nckx** [ventoy/Ventoy#1751]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.78

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

guix-system-install-1.3.0.x86_64-linux.iso

### Image file checksum type

SHA256

### Image file checksum value

f2b30458fa1736eeee3b82f34aab1d72f3964bef0477329bb75281d2b7bb6d4b

### Image file download link (if applicable)

https://ftp.gnu.org/gnu/guix/guix-system-install-1.3.0.x86_64-linux.iso

### Test envrionment

Lenovo Thinkpad X230 tablet

### More Details?

This image file booted successfully in Ventoy and was able to install Guix System.

**Comment by ventoy** [comment]
Thanks!
