### ISSUE TITLE
[issue]: "invalid value for reserved space" GTK

### ISSUE THREAD

**Issue by ShatteredMINT** [ventoy/Ventoy#1752]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.78 (not exclusive to this version but last tetsted)

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

0

### Disk Manufacturer

not applicable (error is in the installer)

### What happened?

When using the Linux GTK app one is unable to have any 9s in their reserved space size.

This error is exclusive to the GTK version of the app as the checking of entered values happens in the GUI specific code.

**Comment by ventoy** [comment]
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/2729563056
https://www.ventoy.net/en/doc_github_ci.html

**Comment by ventoy** [comment]
It should have been fixed in the latest 1.0.79.
