### ISSUE TITLE
[Suggestion]: M1 Mac Support 

### ISSUE THREAD

**Issue by stossy11** [ventoy/Ventoy#1754]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

Any

### Disk Manufacturer

Any

### What happened?

I Suggest to make a collab with The Asahi linux team to put ventoy on M1 Macs

**Comment by ventoy** [comment]
Currently I have no plan to support Mac machine.
