### ISSUE TITLE
[issue]: On azure GenV2 vm, no Ventoy menu but 'Secure Boot Disabled' message is displayed

### ISSUE THREAD

**Issue by dcasota** [ventoy/Ventoy#1756]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.78

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

16GB

### Image file checksum (if applicable)

No.

### What happened?

The Ventoy menu isn't displayed on an azure GenV2 vm. The only visible output is the 'Secure Boot Disabled' message.  Secure Boot and vtpm on the vm are NOT enabled. With press enter, and, if an iso is present, the iso is loading successfully. Tested with Ventoy release 1.076 and 1.078.
In GenV1 (bios mode) the Ventoy menu is displayed as expected.

This may be interesting: the GenV2 vm comes with a newer BIOS Hyper-V UEFI Release.
```
efi: EFI v2.70 by Microsoft
[    0.000000] efi: ACPI=0x3fffa000 ACPI 2.0=0x3fffa014 SMBIOS=0x3ff85000 SMBIOS 3.0=0x3ff83000 MEMATTR=0x3f5c2a98 MOKvar=0x3ff81000 
[    0.000000] SMBIOS 3.1.0 present.
[    0.000000] DMI: Microsoft Corporation Virtual Machine/Virtual Machine, BIOS Hyper-V UEFI Release v4.1 05/09/2022
[    0.000000] Hypervisor detected: Microsoft Hyper-V
[    0.000000] Hyper-V: features 0x2e7f, hints 0x64c2c, misc 0xed7b2
[    0.000000] Hyper-V Host Build:20348-10.0-1-0.1219
```

**Comment by ventoy** [comment]
Press F7 to switch to TEXT mode. May be something about the screen resolution.

**Comment by dcasota** [comment]
Hi @ventoy,
Many thanks for your quick response.
Yes, press F5, 4 rows down, then press Enter, that helped. On Azure, in vm boot diagnostics the screenshot feature helped to see the actual vga screen output of Ventoy. The vm serial console always is in textmode. 
I will do further ventoy.json conf_replace tests because that feature didn't work anymore and that was the backend reason to open this issue. In any case, I will update this issue ticket soon.

**Comment by dcasota** [comment]
With Uefi boot the text console works flawlessly. Tested with Ventoy 1.0.79. -> close ticket.

Just fyi
Navigating&setting explicitly 'Resolution Configuration' >'1024 x  768 x 32' produces an 'unaligned pointer' message similar to #1749.  
![screenshot](https://user-images.githubusercontent.com/14890243/181657718-c222cb79-6491-4ce6-a287-fa90ca23c482.png)

Here's the grub videoinfo output.
```
grub> videoinfo
List of supported video modes:
Legend: mask/position=red/green/blue/reserved
Adapter `Bochs PCI Video Driver':
  No info available
Adapter `Cirrus CLGD 5446 PCI Video Driver':
  No info available
Adapter `EFI GOP driver':
  0x000 1024 x  768 x 32 (4096)  Direct color, mask: 8/8/8/8  pos: 16/8/0/24
grub>
```
