### ISSUE TITLE
[issue]: MIPS GCC 7.3 交叉工具下载地址迁移

### ISSUE THREAD

**Issue by Alex6357** [ventoy/Ventoy#1757]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

512G

### What happened?

构建指南中MIPS GCC 7.3 交叉工具下载地址改变，不再是http://ftp.loongnix.org/toolchain/gcc/release/mips-loongson-gcc7.3-2019.06-29-linux-gnu.tar.gz，最新地址应是http://ftp.loongnix.cn/toolchain/gcc/release/mips/gcc7/mips-loongson-gcc7.3-2019.06-29-linux-gnu.tar.gz

**Comment by ventoy** [comment]
已经修改。

**Comment by borrrden** [comment]
Has this changed again?  

> http://ftp.loongnix.cn/toolchain/gcc/release/mips/gcc7/mips-loongson-gcc7.3-2019.06-29-linux-gnu.tar.gz
Resolving ftp.loongnix.cn (ftp.loongnix.cn)... 114.242.206.189
Connecting to ftp.loongnix.cn (ftp.loongnix.cn)|114.242.206.189|:80... connected.
HTTP request sent, awaiting response... No data received.

It looks like either this doesn't exist anymore, or it is somehow blocked.
