### ISSUE TITLE
[issue]: Ventoy doesn't work with Libreboot

### ISSUE THREAD

**Issue by hnhx** [ventoy/Ventoy#1759]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

16GB

### Disk Manufacturer

SanDisk

### What happened?

I couldn't get Ventoy to work with Libreboot (https://libreboot.org/), is there any way to make it work?
If there isn't any way, could someone recommend me a project similar to Ventoy that would work with Libreboot?

**Comment by a1ive** [comment]
Ventoy only supports UEFI and PC BIOS firmware.
Maybe you need to use SeaBIOS or Tianocore (EDK2) as payload.

**Comment by TechnologyClassroom** [comment]
@hnhx [Multiboot](usb.info/dotclear/) works with legacy.  [Not as simple to use](http://liveusb.info/dotclear/index.php?pages/install) as Ventoy, but it has worked in the past for me.

**Comment by davidhedlund** [comment]
> @hnhx [Multiboot](usb.info/dotclear/) works with legacy. [Not as simple to use](http://liveusb.info/dotclear/index.php?pages/install) as Ventoy, but it has worked in the past for me.

The Multiboot link (https://github.com/ventoy/Ventoy/issues/usb.info/dotclear/) above is broken. However, the domain you refered to http://usb.info/dotclear, is for sale.

Can you please give me another link to it (preferably to a repository)?

**Comment by TechnologyClassroom** [comment]
@davidhedlund I formatted it incorrectly.  It should have been liveusb.info, but I fixed the link to their sourceforge.

**Comment by davidhedlund** [comment]
> @davidhedlund I formatted it incorrectly. It should have been liveusb.info, but I fixed the link to their sourceforge.

Thanks.

**Comment by ventoy** [comment]
Ventoy only supports UEFI and PC BIOS firmware.

**Comment by FrostKnight** [comment]
> Ventoy only supports UEFI and PC BIOS firmware.

Than it has no use for me.  It is utterly worthless. Pity... 

I hope multiboot or something works  At least I know multiboot exists now.

**Comment by davidhedlund** [comment]
> > Ventoy only supports UEFI and PC BIOS firmware.
> 
> Than it has no use for me. It is utterly worthless. Pity...
> 
> I hope multiboot or something works At least I know multiboot exists now.

Hello! I just filed:
* https://github.com/ventoy/Ventoy/issues/3403
