### ISSUE TITLE
[issue]: CLI模式 帮助界面语言选择中文没起作用

### ISSUE THREAD

**Issue by MYJN** [ventoy/Ventoy#1762]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

64GB 

### Disk Manufacturer

SanDisk

### What happened?

VentoyPlugson生成的配置文件信息,菜单语言是这个决定的? { "VTOY_HELP_TXT_LANGUAGE": "zh_CN" }
---------------------------------------
{
    "control":[
        { "VTOY_DEFAULT_MENU_MODE": "1" },
        { "VTOY_FILT_DOT_UNDERSCORE_FILE": "0" },
        { "VTOY_WIN11_BYPASS_CHECK": "1" },
        { "VTOY_HELP_TXT_LANGUAGE": "zh_CN" }
    ],
    "control_legacy":[
        { "VTOY_DEFAULT_MENU_MODE": "1" },
        { "VTOY_FILT_DOT_UNDERSCORE_FILE": "0" },
        { "VTOY_WIN11_BYPASS_CHECK": "1" },
        { "VTOY_HELP_TXT_LANGUAGE": "zh_CN" }
    ],
    "control_uefi":[
        { "VTOY_DEFAULT_MENU_MODE": "1" },
        { "VTOY_FILT_DOT_UNDERSCORE_FILE": "0" },
        { "VTOY_WIN11_BYPASS_CHECK": "1" },
        { "VTOY_HELP_TXT_LANGUAGE": "zh_CN" }
    ],
    "control_ia32":[
        { "VTOY_DEFAULT_MENU_MODE": "1" },
        { "VTOY_FILT_DOT_UNDERSCORE_FILE": "0" },
        { "VTOY_WIN11_BYPASS_CHECK": "1" },
        { "VTOY_HELP_TXT_LANGUAGE": "zh_CN" }
    ],
    "control_aa64":[
        { "VTOY_DEFAULT_MENU_MODE": "1" },
        { "VTOY_FILT_DOT_UNDERSCORE_FILE": "0" },
        { "VTOY_WIN11_BYPASS_CHECK": "1" },
        { "VTOY_HELP_TXT_LANGUAGE": "zh_CN" }
    ],
    "control_mips":[
        { "VTOY_DEFAULT_MENU_MODE": "1" },
        { "VTOY_FILT_DOT_UNDERSCORE_FILE": "0" },
        { "VTOY_WIN11_BYPASS_CHECK": "1" },
        { "VTOY_HELP_TXT_LANGUAGE": "zh_CN" }
    ],
    "theme":{
        "display_mode": "CLI"
    },
    "theme_legacy":{
        "display_mode": "CLI"
    },
    "theme_uefi":{
        "display_mode": "CLI"
    },
    "theme_ia32":{
        "display_mode": "CLI"
    },
    "theme_aa64":{
        "display_mode": "CLI"
    },
    "theme_mips":{
        "display_mode": "CLI"
    }
}
---------------------------------------

**Comment by ventoy** [comment]
CLI模式不支持显示中文以及其他unicode字符。
