### ISSUE TITLE
[issue]: ESXi-customized.iso, uefi boot and boot conf replace

### ISSUE THREAD

**Issue by dcasota** [ventoy/Ventoy#1763]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

16 GB

### What happened?

Hi @ventoy,
Since version 1.0.78 Ventoy supports 2 replacement of configuration files in an ISO file. Nifty feature *****
I've used the following ventoy.json in an Uefi boot scenario, but it didn't succeed. Adding ```"img" :  1``` in config_replace_uefi didn't help. The boot config checks finished with OK though. Can you clarify the bootconf_replace feature if it is available for VMware ESXi 7 iso as well?
```
{
    "conf_replace_legacy": [
        {
            "iso": "/ESXi-customized.iso",
            "org": "/boot.cfg",
            "new": "/ventoy/boot.cfg"
        },
        {
            "iso": "/ESXi-customized.iso",
            "org": "/isolinux.cfg",
            "new": "/ventoy/isolinux.cfg"
        }
    ],
    "conf_replace_uefi": [
        {
            "iso": "/ESXi-customized.iso",
            "org": "/EFI/BOOT/boot.cfg",
            "new": "/ventoy/boot.cfg"
        },
        {
            "iso": "/ESXi-customized.iso",
            "org": "/isolinux.cfg",
            "new": "/ventoy/isolinux.cfg"
        }
    ]	
}
```

**Comment by ventoy** [comment]
Please share me the ISO file for test.

**Comment by dcasota** [comment]
Beside the e-Mail, here a screenshot with ```"img" : 1``` check.
![ESXi01 e6ed481b-35d3-46b9-bf43-f815e96d9f28 screenshot](https://user-images.githubusercontent.com/14890243/182621338-893fc2b9-1a17-4020-9917-83fa347825e8.png)

**Comment by ventoy** [comment]
What about don't use F1 memdisk mode.  Boot conf replace plugin does not support memdisk mode.

**Comment by ventoy** [comment]
memdisk mode just load the original iso file to memory and use [syslinux memdisk](https://wiki.syslinux.org/wiki/index.php?title=MEMDISK) to boot it.
So some plugins(e.g.  boot conf replace/injection/auto install ...) for the ISO file will not take affect. 
Some other plugins (e.g.  menu class/menu tip/menu alias ...) can take  affect.

**Comment by dcasota** [comment]
"original iso" -> thanks for the hint. I missed https://www.ventoy.net/en/doc_name_identifier.html ! Let me check that first. I'll update this thread these next days.

**Comment by dcasota** [comment]
Hi @Ventoy,

Still no clue why the loading does not work.
I've copied the iso and renamed it to ESXi7_VTGRUB2.iso. The original ESXi-customized.iso appears on the menu, too.  

![image](https://user-images.githubusercontent.com/14890243/184109761-f73e5107-231e-4288-a271-e67334c03745.png)

After a cold boot, attempting immidiately to start the ESXi7_VTGRUB2.iso, the following issue appears.
![image](https://user-images.githubusercontent.com/14890243/184110284-96a6ccb5-4cfd-4aae-ab69-7261215b15ef.png)

Here's the config.  

![image](https://user-images.githubusercontent.com/14890243/184110109-a7f0314b-310b-4293-8eb2-c32c0c8c661e.png)

![image](https://user-images.githubusercontent.com/14890243/184111864-c116cb07-556d-4d72-a940-48a14ddb2d7a.png)

When traversing through the F5 menus back to the main menu, then the ESXi7_VTGRUB2.iso starts, but with memdisk (!) As discussed, boot conf replace plugin isn't supported with memdisk.

![image](https://user-images.githubusercontent.com/14890243/184110507-3d7e6f32-a400-4c24-9862-5bd23c1f0d62.png)

The second image ESXi-customized.iso always starts with memdisk as expected.

**Comment by ventoy** [comment]
`ESXi7_VTGRUB2.iso`  has `_VTGRUB2` suffix which means the ISO file will boot in `grub2 mode`.
Boot conf replace plugin only take affect in normal mode and 
So both memdisk mode and grub2 mode are not supported by boot conf replace plugin.

That is to say if you want to use boot conf replace plugin, you can not use memdisk mode and grub2 mode to boot the ISO file.

**Comment by dcasota** [comment]
Okay, this wasn't clear until yet, thanks for the clarification. So both memdisk mode and grub2 mode are not supported by boot conf replace plugin.
In reference to https://www.ventoy.net/en/doc_name_identifier.html, how to automatically enforce "normal mode"?

  _ESXi7_VTGRUB2.iso_ _has_ _VTGRUB2 suffix which means the ISO file will boot in grub2 mode._ No, not. That's the weired issue.

**Comment by ventoy** [comment]
If the ISO file name doesn't contains these special suffix, for example, ESXi7.iso file, and you don't press F1 or ctrl+g, just selec the ISO file and press enter to boot it. Then it will boot in normal mode.

You use a TEXT menu so if you press F1 by mistake, you will not see the red memdisk word in the screen.
https://www.ventoy.net/en/doc_memdisk.html

**Comment by ventoy** [comment]
Also there is a `Auto Memdisk Plugin` https://www.ventoy.net/en/plugin_automemdisk.html  can be used to specify an ISO file to boot in memdisk mode.

**Comment by ventoy** [comment]
Besides, as descripted in the doc: https://www.ventoy.net/en/doc_grub2boot.html
grub2 mode only  support ISO file which contains `grub.cfg/grub2.cfg....`
EXSi iso file doesn't contain them so grub2 mode doesn't support EXSi ISO file.

**Comment by dcasota** [comment]
I didn't press F1 or ctrl+g, neither for ESXi-customized.iso nor for ESXi_VTGRUB2.iso.

**Comment by ventoy** [comment]
As in the doc: https://www.ventoy.net/en/doc_grub2boot.html
Only the ISO file contains  one of
```
/boot/grub/grub.cfg
/EFI/BOOT/grub.cfg
/EFI/boot/grub.cfg
/efi/boot/grub.cfg
/grub/grub.cfg
/EFI/BOOT/BOOTX64.conf
/EFI/debian/grub.cfg
```
then Ventoy will try to boot in grub2 mode if you press `ctrl+g` or rename the iso file with `_VTGRUB2` suffix.
Your ISO file doesn't contains these files (`/efi/boot/boot.conf` is not in the above list) so even you rename it with `_VTGRUB2` 
suffix Ventoy still use normal mode to boot it.
Besides, as I known grub2 can not boot EXSi in UEFI mode, so forget grub2 mode, it can not work.
After cold reboot, you get `No boot file found for UEFI!`, I think your custom ESXi iso file doesn't match the UEFI bootable ISO file format specification.
You can test with VMWare first. Create a VM by VMWare and set it to UEFI mode, connect your ISO file to the CD/DVD of the VM and then boot the VM. If the VM can  not boot your ISO file normally, then it means your ISO file has problem.


`When traversing through the F5 menus back to the main menu, then the ESXi7_VTGRUB2.iso starts, but with memdisk (!) `
I don't know why.


`The second image ESXi-customized.iso always starts with memdisk as expected.`
Why you said ESXi-customized.iso boot in memdisk mode as expected?
It should boot in normal mode by default if you didn't specify it to boot in memdisk mode.

**Comment by dcasota** [comment]
There are more than one culprits and better separate them.

1) This issue case isn't for a baremetal installation. It is a home lab with provisioned VMware ESXi in an Azure hypervisor Generation V2 virtual machine - Uefi yes, but without Secure Boot.
So, it is unsupported even if it completely would work with Ventoy boot. So, no worries.
To put it clear, Ventoy usually works like a charm in a VMware virtual machine vHW release version 13++.
Azure GenV2 virtual machines is supported for a few Linux distros. There is no limit for a Ventoy offer on Azure.

2) Is Ventoy grub2 mode eligible for a VMware ESXi uefi iso setup?
_Besides, as I known grub2 can not boot EXSi in UEFI mode, so forget grub2 mode, it can not work._
In my own words, Ventoy actually does NOT provide a VMware ESXi boot.cfg and isolinux.cfg injection option in an uefi boot scenario, at least not in the Azure GenV2 lab.

3) _When traversing through the F5 menus back to the main menu, then the ESXi7_VTGRUB2.iso starts, but with memdisk (!)_
_I don't know why._ No clue either, just a user feedback.

4) _The second image ESXi-customized.iso always starts with memdisk as expected._
_Why you said ESXi-customized.iso boot in memdisk mode as expected?_ No clue either, as said, didn't configure anything else than the configuration published. First, I didn't even noticed that it runned in mem disk mode. I thought it would be expected behavior.

5) _After cold reboot, you get No boot file found for UEFI!. This may because your custom ESXi iso file doesn't match the UEFI bootable ISO file format specification._
In theory it could be possible. See separate email (admin@ventoy.net) with download url of the iso.

**Comment by dcasota** [comment]
close ticket
