### ISSUE TITLE
[issue]: .IMG file of a Ventoy USB drive does not legacy boot payloads

### ISSUE THREAD

**Issue by steve6375** [ventoy/Ventoy#1765]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

Sandisk + others

### Image file download link (if applicable)

https://1drv.ms/u/s!AqlrQcdsFA-K8RXOduRr0QVcwwSI?e=MOXC64

### What happened?

Medicat is a multiboot solution with many payload files that is based on Ventoy.

The original idea was that a 32GB VHD of Medicat could be made. Then rename it as a .img file and add it to a standard Ventoy USB boot disk.
This was done as follows:
1. Create blank 32GB Fixed disk VHD using Windows Disk Manager
2. Use Ventoy2Disk.exe to create a Ventoy disk on the VHD - MBR exFAT (also tried NTFS).
3. Extract the Medicat .zip payload files onto Partition 1 of the VHD
4. Detach the VHD and rename file extension to .img
5. Copy the VHD to a Ventoy USB drive

The Ventoy USB drive can then boot, load the .img file which loads Ventoy inside the Medicat VHD and then run any payload inside the VHD.
This worked for UEFI. The Medicat menu was loaded and any UEFI payload could be booted.
The problem comes when Legacy booting to Ventoy.
1. Legacy Boot to Ventoy USB drive
2. Select Medicat.img file -> Medicat menu system is loaded
3. Browse Medicat menu system (which is actually Ventoy) and select an MBR payload ISO or WIM file
4. -> black screen - no boot

However, Easy2Boot can boot the .img file and it loads the Medicat menu system and it can then boot to any payload.

So the Legacy Ventoy menu system seems to have a problem when loading an .img containing a second Ventoy menu system!

The download URL contains a test 1GB  VHD with a .img file extension.
It has two payloads (chosen for small size - most Linux iso or .wim, etc, seems to fail)

- Norton Ghost 2003.iso  (requires F1 to boot successfully in Ventoy)
- Acronis_Cyber_Backup.iso

If you legacy boot the VHD it works as expected.
If you add the file to an Easy2Boot USB drive and legacy boot and select it - it works correctly.
However, if you add the file to a Ventoy USB drive - the inner Ventoy menu will not boot to the iso files.

![image](https://user-images.githubusercontent.com/1469350/182655248-9a6f05db-140b-47eb-8326-a97506bda1c9.png)
![image](https://user-images.githubusercontent.com/1469350/182655331-d193b8d6-e55e-49ff-a26c-f214b508e46d.png)
![image](https://user-images.githubusercontent.com/1469350/182655574-9aadebff-faba-48c4-8569-22298492ada2.png)

I have tried updating the Ventoy used in the VHD to 1.0.79 but get the same issue.

I know this is a curious thing to do (run a Ventoy image using Ventoy) but I am curious as to why it does not work when grub4dos (Easy2Boot) does work.

**Comment by ventoy** [comment]
Put simply, because Ventoy and grub4dos use different mechanisms to map the .img file to boot in Legacy BIOS mode.

grub4dos use `map` to emulate the .img file to boot while Ventoy use a different mechanisms (derived from ipxe).

grub4dos `map` has a limitation that the .img file can not contains too many fragments in the physical disk or it will not work.
But grub4dos `map` can be nested. (grub4dos map --->grub4dos map ---> grub4dos map)
Ventoy's mechanisms does not have the fragments limitation but does not support nested map (for code simplicity).

**Comment by steve6375** [comment]
But the .img file is loaded by Ventoy and the (second) Ventoy menu system in the .img file works OK. It can see the payload files. If F1 is used it will load the payload file into memory. The issue seems to be when the payload file (ISO or WIM) is run - then it hangs.

**Comment by ventoy** [comment]
When Ventoy load the .img file it need a `Ventoy map`  then when boot the payload file inside the .img file it need another `Ventoy map`. 
As I said above, for code simplicity Ventoy's map mechanisms doesn't support nested map. The latter `Ventoy map` will conflict with the first `Ventoy map`.

**Comment by steve6375** [comment]
So to boot an ISO in legacy mode Ventoy uses the map command?

**Comment by ventoy** [comment]
Not map command (Ventoy has no map command) but some mechanisms similar with grub4dos map command. 
memdisk mode can work, in memdisk mode Ventoy doesn't need to use the map mechanisms.
