### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by mattlcbesc** [ventoy/Ventoy#1768]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.79

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

UNTANGLE-NGFW-16.5.1.iso

### Image file checksum type

MD5

### Image file checksum value

566c75c01bea1161217b40de295028b4

### Image file download link (if applicable)

https://downloads.untangle.com/public/current-release/NGFW/UNTANGLE-NGFW-16.5.1.iso

### Test envrionment

Lenovo Thinkcentre 93p

### More Details?

This image file booted successfully in Ventoy.  SecureBoot disabled.

**Comment by ventoy** [comment]
Thanks!
