### ISSUE TITLE
[issue]: 爱快软路由ISO镜像无法启动，进入爱快启动菜单后会自动重起

### ISSUE THREAD

**Issue by left3721** [ventoy/Ventoy#1769]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.78

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32

### Disk Manufacturer

SanDesk

### What happened?

[issue]: 爱快软路由ISO镜像无法启动，进入爱快启动菜单后会自动重起

**Comment by ventoy** [comment]
你的ISO文件是哪个？ 我测试是可以的。
![image](https://user-images.githubusercontent.com/59477474/184123198-49234be4-5725-4a74-94d9-aa61dafbbac1.png)

**Comment by left3721** [comment]
iKuai8_x32_3.6.5_Build202206011520.iso
iKuai8_x64_3.6.5_Build202206011520.iso
这两个版本，我都试了，在实体机上启动，到不了图片的这个位置，直接重起。
虚拟机上我没有试过。

**Comment by ventoy** [comment]
不使用Ventoy，使用Rufus或者其他工具，把ISO文件写到同一个U盘上，插电脑上能正常启动吗？

**Comment by left3721** [comment]
之前一直是用UltralSO 把ISO写入U盘安装。
这个小路由硬件配置较低。
硬件配置
CPU
Intel(R) Atom(TM) CPU D525 @ 1.80GHz | 512 KB | 1796 MHz | ×4
硬盘
ATA SSD08G 1021 (7.48GB)
内存
2037MB
主板芯片：
Intel Corporation Atom Processor D4xx/D5xx/N4xx/N5xx DMI Bridge (rev 02)
网卡：
Intel Corporation 82583V Gigabit Network Connection (eth0 e4:3a:6e:12:b5:89)
网卡：
Intel Corporation 82583V Gigabit Network Connection (eth1 e4:3a:6e:12:b5:8a)
网卡：
Intel Corporation 82583V Gigabit Network Connection (eth2 e4:3a:6e:12:b5:8b)
网卡：
Intel Corporation 82583V Gigabit Network Connection (eth3 e4:3a:6e:12:b5:8c)
网卡：
Intel Corporation 82583V Gigabit Network Connection (eth4 e4:3a:6e:12:b5:8d)
网卡：
Intel Corporation 82583V Gigabit Network Connection (eth5 e4:3a:6e:12:b5:8e)

**Comment by ventoy** [comment]
你这次再用同样的方法， 用UltralSO 把同一个ISO写入同一个U盘安装。可以正常启动到图中的位置吗？

**Comment by ventoy** [comment]
我在我的笔记本上测试也是启动OK的。

![image](https://user-images.githubusercontent.com/59477474/184468974-2f69e43b-e4ae-4ab6-a594-7f7d223edc28.png)

**Comment by left3721** [comment]
现在手头没有这个设备了。
用自己PC测试，
用UltralSO写入U盘正常到图片位置，
用Ventoy启动ISO可以到现在图片位置。

**Comment by ventoy** [comment]
那等以后再遇到这种设备再看吧。其实就是需要确认是Ventoy的问题还是本身这个ISO文件在这个设备上就不兼容的问题。

**Comment by left3721** [comment]
我最后的解决是用Ventoy引导WEPE2.1.ISO，从WEPE里安装的爱快
