### ISSUE TITLE
[issue]: Unable to boot latest Gentoo live environment

### ISSUE THREAD

**Issue by Jow1e** [ventoy/Ventoy#1770]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### Disk Manufacturer

Transcend

### Image file checksum (if applicable)

No.

### Image file download link (if applicable)

https://bouncer.gentoo.org/fetch/root/all/releases/amd64/autobuilds/20220731T170548Z/install-amd64-minimal-20220731T170548Z.iso

### What happened?

Can't boot into latest Gentoo live environments (both GUI and non-GUI). On previous Gentoo environment version everything worked just fine.
Using raw disk (without Ventoy) also works

**Comment by ventoy** [comment]
@Jow1e 
Try this CI release.
https://github.com/ventoy/Ventoy/actions/runs/2838870522
https://www.ventoy.net/en/doc_github_ci.html

**Comment by Jow1e** [comment]
@ventoy 
Under that release everything works.
Somehow booting to live gui version only works with Ventoy (I couldn't boot into it using raw disk)

**Comment by ventoy** [comment]
Fixed in 1.0.80

**Comment by steve6375** [comment]
works OK for me in VirtualBox 5 - Ventoy 1.0.81  UEFI64
livegui-amd64-20221023T170534Z.iso

**Comment by NightSpirit2099** [comment]
In VirtualBox it works for me too

Em ter., 25 de out. de 2022 às 14:17, Steve Si ***@***.***>
escreveu:

**Comment by steve6375** [comment]
yes, it fails for me on real system too (E2B\agFM\grubfm works though using partnew option and contiguous file).

**Comment by ventoy** [comment]
> yes, it fails for me on real system too (E2B\agFM\grubfm works though using partnew option and contiguous file).

1. take a photo about the error
2. If it drop into a shell, run `cat /ventoy/log`
3. Try press `c` and run `vtbreak 0 1` and then select and boot the ISO file.

**Comment by cosoc** [comment]
错误依然存在

**Comment by ventoy** [comment]
> 错误依然存在
> 
> livegui-amd64-20221106T170545Z.iso

1、拍个照或者录个视频。
2、如果最后进入一个命令行，执行   cat   /ventoy/log  看看。

**Comment by tyn1998** [comment]
> still cant boot the latest gentoo livegui-amd64-20221023T170534Z.iso. Send me to a grub menu, and even after figuring my way out stil throws a media not found error on boot.

After I updated the Ventoy version to 1.0.88, it worked!
