### ISSUE TITLE
[Success Image Report]: Windows Vista Ultimate x64 Service Pack 2 (Russian)

### ISSUE THREAD

**Issue by SigmaTel71** [ventoy/Ventoy#1771]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.73

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

ru_windows_vista_with_sp2_x64_dvd_x15-36364.iso

### Image file checksum type

SHA1

### Image file checksum value

8B7EC16E567F3F2C113E8A229BBCD1215B97B4B8

### Test envrionment

Custom build LGA775 bench (GA-P35-S3G motherboard)

### More Details?

Successfully booted and installed Windows Vista from this ISO image. Any other Vista SP2 image can be booted as well.

**Comment by ventoy** [comment]
Thanks!
