### ISSUE TITLE
[issue]: 

### ISSUE THREAD

**Issue by Lunarequest** [ventoy/Ventoy#1772]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

32gb

### What happened?

Ventoy is being imporsonated by adware on the playstore 
https://play.google.com/store/apps/details?id=com.mixapplications.ventoy_app&gl=US

**Comment by ventoy** [comment]
Ventoy is open source and it has made a statement that ` this is unofficial app.`

**Comment by Lunarequest** [comment]
I believe ventoy should request they change the name and report it to the playstore. Reading the reviews there are many people who believe it is official and ventoy is adware

**Comment by sdshan8** [comment]
I think it's also violating the GPL-3.0 license, as there is no disclosure of the source code as far as I can see
