### ISSUE TITLE
[issue]: 如何填写 rdinit=

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#1775]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128GB

### Disk Manufacturer

Sandisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://sourceforge.net/projects/android-x86/files/Release%209.0/

### What happened?

A bug happened!
我用 Ventoy 引导 原生的 Android-86_64-9.0-r2.iso ，选择 installation ，安装到内置硬盘里。
安装以后，无法开机，发现 grub里面, `rdinit=/vtoy/vtoy`
删除了`rdinit=/vtoy/vtoy`以后，可以进入桌面，但几秒钟以后黑屏自动重启。
`rdinit=`正确的路径该怎么填写？

**Comment by ventoy** [comment]
把现在的grub配置文件导出来保存一份。
然后不使用Ventoy，使用其他工具（比如Rufus）把ISO文件写入U盘，启动重新安装一次。
然后看一下grub文件里面是怎样写的，和Ventoy安装之后有哪些区别。
同时确认使用新的方式安装之后，没有几秒钟之后黑屏重启的问题。

**Comment by 1457384613gh** [comment]
> 然后看一下grub文件里面是怎样写的，和Ventoy安装之后有哪些区别。

试过了，删除`rdinit=/vtoy/vtoy`这一条，就能够正常启动。
刻录后安装，便没有这条。
