### ISSUE TITLE
EFI partition appeared in file explorer with the letter F

### ISSUE THREAD

**Issue by juandi46XD** [ventoy/Ventoy#1776]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

64GB

### Disk Manufacturer

EAGET

### Image file checksum (if applicable)

Yes.

### What happened?

I was using the option to conserve space on the USB and when I installed ventoy on that usb, the EFI partition with the letter F called System appeared in the file explorer. I hid the drive with diskpart but I would like to know if I create any file there and how to delete it.
![image](https://user-images.githubusercontent.com/71406541/183452729-b01193fb-fb04-4c55-acfc-b8e604d9390a.png)
![image](https://user-images.githubusercontent.com/71406541/183454234-8744e262-fe03-4f65-b904-666876e157e7.png)
![image](https://user-images.githubusercontent.com/71406541/183454877-807e5908-ec78-4b5a-9165-44adab2de2fc.png)

Edit: When I restart the computer the disk appears again

**Comment by ventoy** [comment]
Is this disk your USB stick or your local disk?
Have you ever installed Ventoy on this disk?(There is no Ventoy or VTOYEFI partition in the picture.)

**Comment by juandi46XD** [comment]
That is my local drive and I have never downloaded VENTOY to it.
I installed it to a usb and that partition of the local disk appeared in the file explorer.
