### ISSUE TITLE
Arch linux not booting

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [ventoy/Ventoy#1783]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

16GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

No.

### Image file download link (if applicable)

https://archlinux.org/download/

### What happened?

No arch based distribution is booting
I tried manjaro and arch both
secure boot is off

**Comment by ventoy** [comment]
Can you take a video or photo about the problem?

**Comment by Etaash-mathamsetty** [comment]
> Can you take a video or photo about the problem?

on arch you can't see anything, it fails so quickly 
on manjaro I could probably send a picture

**Comment by ventoy** [comment]
When you boot into Ventoy menu, please checksum the ISO files as follows:
https://www.ventoy.net/en/doc_checksum.html

**Comment by Etaash-mathamsetty** [comment]
I recopied the files and it seems to work now (I did this before and it wasn't working :/)
