### ISSUE TITLE
[issue]: Add support multiple initrd

### ISSUE THREAD

**Issue by antohami** [ventoy/Ventoy#1784]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

32 GB

### Image file download link (if applicable)

http://ftp.altlinux.org/pub/distributions/ALTLinux/p10/images/simply/x86_64/slinux-10.1-x86_64.iso

### What happened?

iso images ALT Linux may include two or more kernels. Accordingly, in addition to /boot/initrd.img, there is also /boot/initrd-<version>.img
Examples of such images:
http://ftp.altlinux.org/pub/distributions/ALTLinux/p10/images/simply/x86_64/slinux-10.1-x86_64.iso
http://nightly.altlinux.org/sisyphus/tested/regular-xfce-latest-x86_64.iso

Needed:
1. Instead of vt_linux_specify_initrd_file, vt_linux_specify_initrd_files should be processed, who include the found known initrd variants.
2.  Find /boot/initrd*.img, /boot/full*.cz etc.

Is this possible to implement?

**Comment by ventoy** [comment]
Actually, Ventoy does supports multiple initrd files. 
Normally, Ventoy will parse the isolinux.cfg/grub.cfg and try to find all the initrd files appearing in isolinux.cfg/grub.cfg.
But some special distro like here the ALT Linux, use variable suffix to expand the initrd files (`/boot/initrd$KFLAVOUR.img`) which Ventoy doesn't support.  So it need special process for it.

**Comment by ventoy** [comment]
@antohami 
Try this CI release: 
https://github.com/ventoy/Ventoy/actions/runs/2856211690
https://www.ventoy.net/en/doc_github_ci.html

**Comment by antohami** [comment]
It works! Thanks!
I will try not to do more "innovations" in bootloading ALT Linux, so as not to break :-)

**Comment by ventoy** [comment]
Fixed in 1.0.80
