### ISSUE TITLE
[Success Image Report]: odysseyn1x

### ISSUE THREAD

**Issue by olivertzeng** [ventoy/Ventoy#1789]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.57

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

odysseyn1x-v2.15-amd64.iso, odysseyn1x-v2.14-amd64.iso 

### Image file checksum type

SHA512

### Image file checksum value

IDK

### Image file download link (if applicable)

https://github.com/raspberryenvoie/odysseyn1x/releases/download/v2.15/odysseyn1x-v2.15-amd64.iso

### Test envrionment

HP Pavilion

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
