### ISSUE TITLE
可否与WTG等兼容？

### ISSUE THREAD

**Issue by huangsijun17** [ventoy/Ventoy#179]
例如直接引导其他Grub2或者Windows Boot Manager？亦或者通过Grub2来引导Ventoy。
Legacy BIOS和UEFI的兼容情况分别如何？

**Comment by ventoy** [comment]
ventoy本身是基于grub2的，这些理论上都是可行的。你在ventoy菜单界面按 c 进入grub2命令行之后就是标准的grub2环境，grub2支持的理论上都可以。你可以自己尝试下。

**Comment by huangsijun17** [comment]
引导不了哦，包括我试过引导了EFI SHELL再去手动引导也不行。

UEFI模式下，Ventoy加载非Metro的Windows Boot Manager，文字是一个一个得显示出来的，显卡驱动问题？
