### ISSUE TITLE
[issue]: Ventoy doesn't see any drives

### ISSUE THREAD

**Issue by jSydorowicz21** [ventoy/Ventoy#1795]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

128GB

### Disk Manufacturer

Samsung

### What happened?

When trying to install ventoy, ventoy2disk does not see any drives. Toggling show all devices doesn't change outcome. 

![image](https://user-images.githubusercontent.com/90705257/185333924-b72b4119-dd65-4475-b20e-4bd93e9b50d1.png)

![image](https://user-images.githubusercontent.com/90705257/185333968-bacdb9b5-8c02-4af8-8a9a-d0cd88c797e9.png)

[Log from venoy2disk](https://drive.google.com/file/d/1Vcg8kjGNMEqVkZnJ9_n-rs3_w5Muh-XA/view?usp=sharing)

**Comment by ventoy** [comment]
Did you check this:
https://www.ventoy.net/en/faq.html
![image](https://user-images.githubusercontent.com/59477474/185387848-2c2d4c68-8fae-4139-b62e-2ceae35be915.png)

**Comment by jSydorowicz21** [comment]
After doing more investigation its a conflict with OpenHardwareMonitor. After closing, ventoy enumerates as expected.
