### ISSUE TITLE
[issue]: Theme settings have no effect

### ISSUE THREAD

**Issue by maxelblack** [ventoy/Ventoy#1796]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.65

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64 GiB

### Disk Manufacturer

Kingston DTX

### What happened?

As the title, I set 3 themes by `VentoyPlugson.exe` but they didn't work. F5 menu didn't contain any items about themes, either.

When I tried check ventoy.json, Ventoy told me that 'fonts NOT found'. But I added all fonts used by the themes in Plugson and there is no error message.

**Comment by ventoy** [comment]
Please upload your ventoy.json/theme files/font files.... here for analyze.

**Comment by maxelblack** [comment]
> Please upload your ventoy.json/theme files/font files.... here for analyze.

OK, I uploaded the entire directory: [ventoy.zip](https://github.com/ventoy/Ventoy/files/9386188/ventoy.zip)

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/185731263-3577c270-21c7-4c5c-9f39-fa801794d8db.png)
Theme has a few problems, but is seems to be displayed.
I deleted the VTOY_DEFAULT_SEARCH_ROOT on mine.

**Comment by steve6375** [comment]
[theme.txt](https://github.com/ventoy/Ventoy/files/9386375/theme.txt)
Here is better theme.txt file which has Ventoy hotkeys added (ctrl+r, ctrl+u, ctrl+w, ctrl+i, F1) added and adjusted sizes\positions.
![image](https://user-images.githubusercontent.com/1469350/185732551-b81d4185-9753-4ea4-91f4-cf9e1a27c0ba.png)

**Comment by steve6375** [comment]
or this
![image](https://user-images.githubusercontent.com/1469350/185732865-5561284d-ed5f-4a78-9b04-88e6394d4452.png)
[theme.txt](https://github.com/ventoy/Ventoy/files/9386385/theme.txt)

**Comment by maxelblack** [comment]
Thanks, but my ventoy still shows the default theme... It's like I didn't set the theme at all...

**Comment by steve6375** [comment]
json file is on Partition 1 of your USB drive?
at \ventoy\ventoy.json
???
Maybe you have a corrupt USB drive or a fake one?

**Comment by maxelblack** [comment]
I deleted a useless folder named `ventoy` in `themes` and it worked fine.
Very magical... but at least it worked.
And thanks for your `theme.txt`

**Comment by steve6375** [comment]
what was in the \ventoy\themes\ventoy folder?
If there is a bug in ventoy we should try to find out.

**Comment by maxelblack** [comment]
It contains a theme.txt and some theme files, but I didn't add the theme to `ventoy.json`

**Comment by steve6375** [comment]
Can you reproduce the problem?
I added a \ventoy\themes\ventoy\theme.txt and it does not seem to affect anything...

**Comment by maxelblack** [comment]
It seems that I ignored something in `ventoy.json`

I set `theme_uefi` - `gfxmode` to `1440x900` and the bug occurred, default theme appeared at 1440x900 resolution. When I changed `gfxmode` back to `1024x768`, my theme settings worked.

But the same theme works fine on GRUB2 at 1680x1050 resolution.
