### ISSUE TITLE
[Feature Request] Abillity to boot Darwin based OSs (MacOS)

### ISSUE THREAD

**Issue by Sporesirius** [ventoy/Ventoy#18]
It might be useful to be able to boot Darwin based operating systems (MacOS DMGs). There is a project that could be useful.
Maybe you want to integrate this?
https://github.com/acidanthera/OpenCorePkg

**Comment by notslang** [comment]
See: https://github.com/ventoy/Ventoy/issues/3

**Comment by dm17** [comment]
Would be sweet to be able to boot OSX as well as Windows & Linux... Would be pretty complete! I recommend downloading OSX with gibMacOS, if needed.

**Comment by SalahAdDin** [comment]
How is this going on?

**Comment by ventoy** [comment]
Ventoy doesn't offcially support MacOS

**Comment by SalahAdDin** [comment]
Is it on plans?

**Comment by rzr** [comment]
This feature wish is desirable, any blocker ?
