### ISSUE TITLE
[Success Image Report]: UnionTech OS Desktop 20 Professional 1050 update2 arm64

### ISSUE THREAD

**Issue by opsiff** [ventoy/Ventoy#1814]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.77

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

uniontechos-desktop-20-professional-1050-update2-arm64.iso

### Image file checksum type

SHA256

### Image file checksum value

0b2a0fb96f9ba275ce7f07dc22a62989dbded2b05b77f232f784258cde154226

### Image file download link (if applicable)

https://cdimage-download.chinauos.com/uniontechos-desktop-20-professional-1050-update2-arm64.iso

### Test envrionment

HUAWEI QingYun W510 PGU-WBY0

### More Details?

This image file booted successfully in Ventoy UEFI Mode.

**Comment by ventoy** [comment]
Thanks!
