### ISSUE TITLE
[issue]: dd command not found 

### ISSUE THREAD

**Issue by anwar-alsilwy** [ventoy/Ventoy#1817]

**Comment by a1ive** [comment]
Offical GRUB2 does not have 'dd' command.

**Comment by anwar-alsilwy** [comment]
> Offical GRUB2 does not have 'dd' command.

Actually I checked official grab2.04, and yes there is no dd, I'm sorry it's my bad.
Anyway, I decided to copy 'dd.mod' from 'A1ive grubfm' to the Ventoy (grubfm/i386_pc/ to VTOYEFI/grub/i386_pc/) and type:
insmod dd
But it showed message: 'lua.mod not found on /grub/i386_pc'

So again, I copied 'lua.mod' to the same directory and type:
insmod dd
or
insmod lua
but this time it showed message:
symbol 'grub_strpbrk' not found

Any suggestions @A1ive ?? Could you help me how to add dd module to ventoy, I really need this.

**Comment by a1ive** [comment]
No. You can not add `dd` module to Ventoy.
