### ISSUE TITLE
[Success Image Report]: Nobara Project

### ISSUE THREAD

**Issue by GeoBoi254** [ventoy/Ventoy#1819]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.79

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

Nobara-36-KDE-2022-08-28.iso

### Image file checksum type

SHA256

### Image file checksum value

2152b927fe79ef038f59933d48d9e7fc80ec7fe90a50e8e5a037e2ac9d73267b

### Image file download link (if applicable)

https://nobaraproject.org/download-nobara/

### Test envrionment

Acer Aspire E5-473G

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
