### ISSUE TITLE
[issue]: 能不能搞一个ISO版的启动镜像文件

### ISSUE THREAD

**Issue by lsq** [ventoy/Ventoy#1820]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

32GB

### What happened?

建议搞一个可以用grub2(-filemanager )启动的ISO文件，这样大家完全没有必须非要无损安装，或者格式化U盘，这样看起来也灵活了不少，还有32M分区感觉也很别扭，或者大佬讲一个实现方案给我们参考修改下。
![图片](https://user-images.githubusercontent.com/1617256/187682109-3e82d3f9-350e-4b56-8a06-a639cf40bced.png)

**Comment by ventoy** [comment]
Ventoy 从最初就是按照安装到U盘的使用方式设计和实现的。无法改造成ISO的形式。
