### ISSUE TITLE
[issue]: Implement Check privilege in execution CreatePersistentImg.sh 

### ISSUE THREAD

**Issue by rick0x00** [ventoy/Ventoy#1825]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

0GB

### Disk Manufacturer

All

### What happened?

A bug happened!
The script CreatePersistentImg.sh does not require execution with SUDO or ROOT user, but if it is executed without special permissions, errors occur during the creation of the .DAT file.

A privilege check should be implemented as in the VentoyWeb.sh script.

**Comment by ventoy** [comment]
OK
