### ISSUE TITLE
[issue]: Failed to boot the Linux system HoloISO installation disk.

### ISSUE THREAD

**Issue by huangsijun17** [ventoy/Ventoy#1828]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

512GB

### Disk Manufacturer

笑着无奈

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://github.com/theVakhovskeIsTaken/holoiso/releases

### What happened?

https://github.com/theVakhovskeIsTaken/holoiso

SteamOS 3 (Holo) is an Arch Linux derivative distribution. HoloISO is a derivative of this distro, compatible with other hardware.

**Comment by ventoy** [comment]
@huangsijun17 
Try the latest 1.0.80 release.

**Comment by huangsijun17** [comment]
> @huangsijun17 Try the latest 1.0.80 release.

Booting successfully in UEFI mode.
