### ISSUE TITLE
[Success Image Report]: ChallengerOS

### ISSUE THREAD

**Issue by Daniel2193** [ventoy/Ventoy#1830]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.33

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

challengeros-2.1.9-dre-x86_64.iso

### Image file checksum type

SHA256

### Image file checksum value

E31027601C27FE1FDCEB1459BDA522E68EFC82EC10F2FF74CCAA882AF9E49351

### Image file download link (if applicable)

https://www.challengeros.com/download/64/4.9.197/challengeros-2.1.9-dre-x86_64.iso

### Test envrionment

Custom Build PC with: [CPU] AMD Ryzen 7 3800X, [MB] ASUS rog strix b450 f gaming 2, [GPU] AMD Radeon rx 590

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
