### ISSUE TITLE
[issue]: ctrl+w does not enable WIMBOOT mode in some PCs

### ISSUE THREAD

**Issue by devdevadev** [ventoy/Ventoy#1837]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

Samsung

### What happened?

Hi..

RecentlIy I was trying to install WIN10 in a PC using ventoy but it stuck to blinking cursor screen for infinite time. So I pressed ctrl+w to enable WIMBOOT mode but PC does not seems to recognize ctrl+w key press. I have also tried to enable ctrl+r but it also does not seems to work. But F1 successfully enabled MEMDISK mode.

I think Ctrl key press does not seems to work in UEFI Firmware in boot mode !!! but Fn keys works fine...

It will be useful if we can using Fn keys to enable WIMBOOT mode and GRUB2 mode so it will work for all PC firmware.
F8-F12 keys are free to use as alternative. How I can use Fn keys to enable WIMBOOT mode. Is there any provision in Ventoy to customize Fn keys as per our requirement ?

Finally I have to rename ISO name and added _VTWIMBOOT suffix to enable WIMBOOT mode but it will not be better idea to rename all our WIN ISO all the time.  How we can use F8 to enable WIMBOOT mode similiar to F1 for MEMDISK mode ?

Please help...

Thanks & Regards...

**Comment by ventoy** [comment]
I add `w` and `r` hotkey for WIMBOOT and grub2 mode.  
So you can press `ctrl` + `w` or  `w` to use WIMBOOT mode with this CI release:
https://github.com/ventoy/Ventoy/actions/runs/3034462229
https://www.ventoy.net/en/doc_github_ci.html

**Comment by devdevadev** [comment]
Thanks you so much....Now it works perfectly.....

**Comment by devdevadev** [comment]
If you like you can allow user to enable WIMBOOT mode using Global Control Plugin so user can keep WIMBOT mode as default for all Windows/WinPE ISOs if required....

     { "VTOY_WIMBOOT_MODE": "0" }   - Normal Mode
     { "VTOY_WIMBOOT_MODE": "1" }   - WIMBOOT mode

Thanks & Regards...

**Comment by devdevadev** [comment]
you can also provide u and i hotkey as alternative of ctrl+u and ctrl+i if prefer....

**Comment by ventoy** [comment]
Fixed in 1.0.80
