### ISSUE TITLE
[issue]: VentoyVlnk.sh on Debian Linux fails with error message

### ISSUE THREAD

**Issue by Yanestra** [ventoy/Ventoy#1838]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

64GB

### Disk Manufacturer

n/a

### What happened?

Starting VentoyVlnk.sh under Debian x86_64 I get the error message:
LVM/DM is not supported!
/sys/class/block/dm-2/start not exist!

Kernel is 5.19.0-8.2-liquorix-amd64

**Comment by ventoy** [comment]
With VentoyVlnk you can boot ISO files in your local disk.
But the ISO file must be in the plain disk, LVM is not supported.
LVM is a logical drive not normal physical disk as /dev/sda /dev/sdb ...

**Comment by Yanestra** [comment]
But I do not use LVM on my system. I guess I misunderstood the task of the
tool anyway, thank you for the information.

**Comment by ventoy** [comment]
If you just want to boot an ISO file in your local disk, you can just press F2 in Ventoy menu and don't need to use VentoyVlnk.
