### ISSUE TITLE
Limine support? 

### ISSUE THREAD

**Issue by TymianekPL** [ventoy/Ventoy#1839]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

64GB

### What happened?

Ventoy doesn't support limine

**Comment by ventoy** [comment]
limine and grub2(Ventoy based on grub2) are both bootloaders.
Ventoy only supports booted directly from BIOS and booted from another bootloader is not supported.

**Comment by mintsuki** [comment]
This project is garbage and it's sad to see that so many people have come to rely on this piece of garbage.
