### ISSUE TITLE
[issue]: Bob.Ombs.Modified.Win10PEx64.v4.8.ISO not booting in Ventoy neither in NORMAL mode nor in WIMBOOT mode

### ISSUE THREAD

**Issue by devdevadev** [ventoy/Ventoy#1842]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

Samsung

### What happened?

Hi..LongPanda

**Bob.Ombs.Modified.Win10PEx64.v4.8.ISO** not seems to boot in Ventoy neither in NORMAL mode nor in WIMBOOT mode. It just stuck at blinking cursor screen for infinite time......

I have also tried the same ISO with grubfm and it boot fine. 

Why Ventoy don't like it ?

Thanks & Regards...

**Comment by ventoy** [comment]
Try `Ctrl+i `

**Comment by devdevadev** [comment]
ctrl+I hotkey not working in my PC. Please add i hotkey so I can test....

**Comment by ventoy** [comment]
I will add `i` hotkey later, now you can do as follows:
press `c` to enter grub shell, run `set vtcompat=1`  press Enter, and then press ESC to return.
After that select the ISO file and boot.

The above is equivalent to `ctrl+i`

**Comment by devdevadev** [comment]
I have tried
set vtcompat=1

But still showing blinking cursor in the screen as before.
Should I try WIMBOOT mode ?

**Comment by ventoy** [comment]
For reconfirm, use this CI release https://github.com/ventoy/Ventoy/actions/runs/3049532139 and use `i` hotkey.

**Comment by ventoy** [comment]
Both Legacy BIOS mode and UEFI mode has this problem?

**Comment by ventoy** [comment]
If the new CI release also has this problem, press `c` to enter grub shell and run `vtdebug on` and then select the ISO file to boot.
Will pause many times for debug, press ctrl+c to continue as the prompt.

**Comment by devdevadev** [comment]
Currently I am testing in UEFI mode. But it also does not boot in MBR mode last time when I tested...
Still same problem with latest CI release....

When I used debug on, then it displayed following codes I have to press ENTER to continue

![20220914_075905](https://user-images.githubusercontent.com/20319541/190045834-a2bddd15-64ba-4a4e-b18b-b2fd6aad52f4.jpg)

But after pressing many ENTER keys it reach to the same cursor blinking screen...and never booted !!!

**Comment by VanFlusen** [comment]
Put the ISO file in the root of the USB drive (no parent directory) and it will work.

**Comment by steve6375** [comment]
Doesnt work in root either.
1.0.79 - MBR ptns - NTFS ptn1

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/190207431-78539c0b-3fc3-48a1-9252-a16b09f22b6c.png)

**Comment by VanFlusen** [comment]
1.0.79 - MBR ptns - NTFS ptn1
Hmm, I'm using Bob.Ombs.Modified.Win10PEx64.v4.98.iso
and it works well on real DELL Optiplex and AMD X570 machine in UEFI mode.

![Capture](https://user-images.githubusercontent.com/82698833/190216524-5e914909-f431-4621-b364-0735b36d7f78.PNG)


![1Capture](https://user-images.githubusercontent.com/82698833/190216581-1db23c30-f459-4d21-96c6-f4657182a94d.PNG)

**Comment by steve6375** [comment]
hmmm - this is very strange!
v4.8 ISO was not booting on my Lenovo IdeaPad 300 - either UEFI or Legacy - from either root of USB drive or a folder \_ISO\WINPE.
Then I copied the v4.98 to the USB drive and that works fine in both UEFI and Legacy and both folders.
Then I retested the v4.8 ISO again and it now works legacy and UEFI from both folders!
I have no idea why it now works! Same file, same USB drive...
The ISO does not need to be in the root for me.

**Comment by VanFlusen** [comment]
It's been a long time since Ventoy 1.0.2?
Bob.Omb.ISO in a folder booted fine but drive Y: did not present.
If Bob.Omb.ISO was in the root, drive Y: was present.
But you are right, the ISO no longer needs to be in the root.
Thanks for the info.

**Comment by ventoy** [comment]
@devdevadev 
Try this CI release : https://github.com/ventoy/Ventoy/actions/runs/3062312167  when it finish build.
Use WIMBOOT mode to boot the ISO file.

**Comment by devdevadev** [comment]
Thanks for adding wimboot mode support Bob.Ombs.Modified.Win10PEx64.ISO . Have you added WIMBOOT support for all WinPE type ISO or only for this Bob.Omb ISO ?

Now it boot perfectly in WIMBOOT mode in my Macbook Air. It also boot fine in normal mode in old Dell Laptop and in my Office Dell PC also....

But when I try to boot in normal mode in my Macbook Air then it still stuck to blinking cursor.....
![20220916_192032](https://user-images.githubusercontent.com/20319541/190659258-d26f0cf4-7e47-4abb-86c4-650a06b2d4b4.jpg)

Why Ventoy don't like to boot Windows ISO, WinPE ISO and any other ISOs in normal mode ? While all ISOs works fine in Macbook Air if I boot them using Grub2fm. It's looking Ventoy uses a unique and different machanism to boot ISOs.
Is there any clue in above screenshot why Ventoy fail to boot Bob.Omb ISO in normal mode ?

Thanks & Regards...

**Comment by ventoy** [comment]
For WinPE, WIMBOOT now only supports Bob.Ombs.Modified.Win10PEx64.ISO.

As you said, normal mode only fail in some computer, not all the computers. 
So it may because come computer's  BIOS is not standard.

Ventoy uses different machanism to boot ISOs.
When you boot Bob.Ombs. ISO by grubfm, the ISO file is not mounted as a CDROM and some tools can not be used.

All programs:
![image](https://user-images.githubusercontent.com/59477474/190665414-d6abd0b0-43f1-40c5-9cce-a3f50b05c177.png)
