### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by HikariCalyx** [ventoy/Ventoy#1847]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.79

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

Hikari_PE_X64_V8.51_HardwareTestSuite_Plus_EN.iso

### Image file checksum type

SHA256

### Image file checksum value

fb2df2a360723981ab88493ed83cbcc43c296c530654b173a0209ef2449a6b17

### Image file download link (if applicable)

https://tpedutw-my.sharepoint.com/:u:/g/personal/hikaricalyx_tp_edu_tw/EaCN9CrYmoNKn-hQJgsEg5IBwk4mlocwjPSkeQfDARA3ng?e=YeJqcA

### Test envrionment

Dell Latitude 3490

### More Details?

This image file booted successfully in Ventoy. 
Ventoy environment can be detected by Hikari PE Project.
<img width="960" alt="ventoy_detect" src="https://user-images.githubusercontent.com/29157608/190859511-961a22f4-2b55-492f-ac40-e11f82134ad8.png">

**Comment by ventoy** [comment]
Thanks!
