### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by Fenghaojun0628** [ventoy/Ventoy#1849]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.79

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

deepin-desktop-community-20.7-amd64.iso

### Image file checksum type

MD5

### Image file checksum value

b922f0924fe92e1b0988c9a3fcd98285

### Image file download link (if applicable)

deepin.org/zh/download

### Test envrionment

ASUS A53S Laptop

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
