### ISSUE TITLE
引导不了Windows10镜像?

### ISSUE THREAD

**Issue by syaofox** [ventoy/Ventoy#185]
我的电脑是NUC8i7HVK2,安全引导已经关闭
进入ventoy界面后选择ios镜像
cn_windows_10_business_editions_version_2004_updated_may_2020_x64_dvd_c2acd212.iso无法启动,黑屏一会儿就回到ventoy界面了
测试了一下其他iso.比如win7,omv5,正常进入安装界面,什么问题呢?

**Comment by ventoy** [comment]
会不会是提示  **Press any key to boot from CD  (按任意键从光驱启动)**  的时候你没有按键？

**Comment by syaofox** [comment]
> 会不会是提示 **Press any key to boot from CD (按任意键从光驱启动)** 的时候你没有按键？

不是的,没有任何提示文字

**Comment by ventoy** [comment]
试试 ventoy-1.0.13 看看是什么情况。

**Comment by syaofox** [comment]
```
Windows 10 (business edition), Version 2004 (Updated May 2020) (x64) - DVD (Chinese-Simplified)
文件：cn_windows_10_business_editions_version_2004_updated_may_2020_x64_dvd_c2acd212.iso
大小：4.8GB
MD5：78F1D702D223081D46366CCE61FD7C30
SHA1：B598612123340EC6BEFCBB537C17557DAF9BF160
SHA256：D5CF2CA6517ED3518429024DB8FDE0500718513A13CAFC1FF18C0F40F7F981AC
```
这个镜像还是不行,一样的情况
我直接用其他方法制作启动u盘是可以正常安装的

我还测试了手头上几个windows镜像,ventoy可以正常引导

**Comment by ventoy** [comment]
会不会提示信息没显示出来， 你选择ISO之后马上按几次 Enter 键试试。

**Comment by ventoy** [comment]
另外，我QQ群里问了下，这个ISO镜像至少有两个人是测试OK的。

**Comment by syaofox** [comment]
更新了ventoy-1.0.14特地测试了一下，已经没有问题了，感谢
