### ISSUE TITLE
[issue]: Fedora Silverblue isn't booting

### ISSUE THREAD

**Issue by kbdharun** [ventoy/Ventoy#1851]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

16 GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://download.fedoraproject.org/pub/fedora/linux/releases/36/Silverblue/x86_64/iso/Fedora-Silverblue-ostree-x86_64-36-1.5.iso

### What happened?

I logged into Ventoy and when I selected Fedora Silverblue from the list there was a blank screen with just `-` at the top left corner. I checked if the file was corrupted and verified that the file worked when I tried it on VM.

Unfortunately, I wasn't able to take a clear screenshot but I will add a rough representation of the blank screen in the codeblock below.

```text
-






```

**Comment by ventoy** [comment]
Try grub2 mode : https://www.ventoy.net/en/doc_grub2boot.html

**Comment by kbdharun** [comment]
Sure, I will give it a try.

**Comment by kbdharun** [comment]
> Try grub2 mode : https://www.ventoy.net/en/doc_grub2boot.html

Update: It successfully boots in grub2 mode, Should I create a new issue with `Success image report` with grub2 mode mentioned in it?

**Comment by ventoy** [comment]
That's OK.
