### ISSUE TITLE
[issue]: Bad substitution in ExtendPersistentImg.sh script

### ISSUE THREAD

**Issue by remogatto** [ventoy/Ventoy#1855]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

256 GB

### What happened?

A 'bad substitution' error was raised by bash when running ExtendPersistentImg.sh. I solved the issue running the script using the 'bash' command. A similar issue was closed days ago (#1809). Thank you.

**Comment by ventoy** [comment]
OK. I will add the same modifdy as #1809
