### ISSUE TITLE
[issue]: Systax error detected in ventoy.json after adding Secondary Boot Menu in Control Plugin

### ISSUE THREAD

**Issue by devdevadev** [ventoy/Ventoy#1860]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.80

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

Samsung

### What happened?

Hi LongPanda...

First Thanks for providing Secorndary Boot Menu feature....

`{
    "control": [
        { "VTOY_SECONDARY_BOOT_MENU": "1" },
        { "VTOY_SECONDARY_TIMEOUT": "20" }
    ]
}`

Once I add above Secondary Boot Menu Control Plugin in my ventoy.json file, then Ventoy give following Syntax error message in Ventoy startup screen !!!

![20220922_021134](https://user-images.githubusercontent.com/20319541/191643590-98a0cfe1-e1c5-44eb-9a72-0236e2a07ed4.jpg)

and does not load ventoy.json settings after pressing ENTER....

When I remove these Secondary Boot Menu in Control Plugin from ventoy.json file, then it works fine as expected.....

Thanks & Regards...

**Comment by ventoy** [comment]
Upload you original `ventoy.json` file here for analyze.

**Comment by devdevadev** [comment]
> Upload you original `ventoy.json` file here for analyze.

Ah...sorry. It's may fault...

I was using 

`    "control": [
        { "VTOY_DEFAULT_MENU_MODE": "1" },
        { "VTOY_TREE_VIEW_MENU_STYLE": "1" },
        { "VTOY_FILT_DOT_UNDERSCORE_FILE": "1" },
        { "VTOY_SORT_CASE_SENSITIVE": "0" },
        { "VTOY_MAX_SEARCH_LEVEL": "max" },
        { "VTOY_FILE_FLT_ISO": "0" },
        { "VTOY_FILE_FLT_WIM": "0" },
        { "VTOY_FILE_FLT_EFI": "0" },
        { "VTOY_FILE_FLT_IMG": "0" },
        { "VTOY_FILE_FLT_VHD": "0" },
        { "VTOY_FILE_FLT_VTOY": "0" },
        { "VTOY_DEFAULT_KBD_LAYOUT": "QWERTY_UK" },
        { "VTOY_DEFAULT_SEARCH_ROOT": "/_ISO/" },
        { "VTOY_MENU_TIMEOUT": "10" },
        { "VTOY_DEFAULT_IMAGE": "/_ISO/WINDOWS/WIN10/VTOY_DEFAULT_ISO" }
    ],
`

and I have just added following two lines at the end

        { "VTOY_SECONDARY_BOOT_MENU": "1" },
        { "VTOY_SECONDARY_TIMEOUT": "20" }

I forget to add Comma ( , ) in previous last line. So it giving system error...


`    "control": [
        { "VTOY_DEFAULT_MENU_MODE": "1" },
        { "VTOY_TREE_VIEW_MENU_STYLE": "1" },
        { "VTOY_FILT_DOT_UNDERSCORE_FILE": "1" },
        { "VTOY_SORT_CASE_SENSITIVE": "0" },
        { "VTOY_MAX_SEARCH_LEVEL": "max" },
        { "VTOY_FILE_FLT_ISO": "0" },
        { "VTOY_FILE_FLT_WIM": "0" },
        { "VTOY_FILE_FLT_EFI": "0" },
        { "VTOY_FILE_FLT_IMG": "0" },
        { "VTOY_FILE_FLT_VHD": "0" },
        { "VTOY_FILE_FLT_VTOY": "0" },
        { "VTOY_DEFAULT_KBD_LAYOUT": "QWERTY_UK" },
        { "VTOY_DEFAULT_SEARCH_ROOT": "/_ISO/" },
        { "VTOY_MENU_TIMEOUT": "10" },
        { "VTOY_DEFAULT_IMAGE": "/_ISO/WINDOWS/WIN10/VTOY_DEFAULT_ISO" },
        { "VTOY_SECONDARY_BOOT_MENU": "1" },
        { "VTOY_SECONDARY_TIMEOUT": "20" }
    ],
`

Now it works fine perfectly. Thanks you so much....

Regarsa...

**Comment by ventoy** [comment]
So you'd better to use VentoyPlugson instead of edit the json file manually.
https://www.ventoy.net/en/plugin_plugson.html
