### ISSUE TITLE
UEFI issues with KANOTIX ISO images on older systems

### ISSUE THREAD

**Issue by KanoTheMaster** [ventoy/Ventoy#187]
After enabling "vtdebug on" in grub.cfg I found an error with my boards for Sandy Bridge, Ivy Bridge and Haswell CPUs. My boards for Skylake and newer can boot fine.

**FSBindingSupported
FSBindingStart
Could not read block at address 00000040: [2]
error: not a ISO9660 filesystem.**

**Comment by ventoy** [comment]
Can you try ventoy-1.0.13?

**Comment by KanoTheMaster** [comment]
The error is now different. Currently it is not possible to boot KANOTIX at all - even with a newer system using EFI.

**ASSERT_EFI_ERROR (Status = Invalid Parameter)
ASSERT [Ventoy] ...MemoryAllocationLib.c(813): !EFI_ERROR (Status)
No bootfile found for UEFI!
Maybe the image does not support X64 UEFI!**

KANOTIX uses a hybrid ISO layout, it definitely has X64 UEFI in ISO9660 and FAT12 (usually 1MiB offset). (The 32 bit images have got the 32 bit UEFI). The "live" folder is similar to Debian live.

Ventoy up to 1.0.12 used the /dev/mapper/ventoy approach to boot.

Btw. compared to other images KANOTIX has even an Apple Partition Map with appended HFS+ partition (with USB-Stick ImageWriter for Mac). Unpatched parted tools usually crash. Created by

https://github.com/acritox/kanotix/blob/master/isohybrid-acritox

Verify:

**ISO=kanotix64-silverfire-nightly-KDE-extra.iso
blkid --probe --offset=$(($(stat -c %s $ISO)-1048576)) $ISO**

Maybe the hack in line 148 of isohybrid-acritox is problematic for Ventoy.

**Comment by retabell** [comment]
no uefi boot with 1.0.13 and 1.0.14
Pictures with debug output
http://kanotix.com/files/fix/ventoy/ventoy1.014-debug1/
http://kanotix.com/files/fix/ventoy/ventoy1.013-debug2/

output of blkid
http://kanotix.com/files/fix/ventoy/isohybrid/offset.txt

isohybrid log
http://kanotix.com/files/fix/ventoy/isohybrid/isohybryd.log
