### ISSUE TITLE
[issue]: /ventoy/ventoy.json not found - issue with recursive folder structure?

### ISSUE THREAD

**Issue by Thyself17** [ventoy/Ventoy#1871]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.80

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

PNY

### What happened?

First time setting up a Ventoy drive.  I have used VentoyPlugson.exe to create a new plugin configuration file.  I have run a few different tests, and it seems that whenever the ventoy folder is present, the file structure messes up on boot.  Pressing F5 for tools and checking the plugin config shows a message that /ventoy/ventoy.json does not exist.  

Using the file browser (F2) in the boot menu, I can see a /ventoy folder in root.  As soon as I navigate to that folder, the browser still shows the contents of the root folder as if I had never navigated to it, however, my path shows /ventoy/.  I can recursively go into this "ventoy" folder multiple times (EG "/ventoy/ventoy/ventoy/ventoy") without ever actually navigating inside that folder.

As an experiment, I tried deleting the ventoy.json configuration file, however, the issue persists.  Another oddity is that all my iso names are duplicated multiple times.  It certainly seems like the /ventoy folder will recursively redirect the OS to root.

I have a folder structure on the exFAT VENTOY drive that is structured as follows:

-E:/
--isos (my iso files live here)
--ventoy
---ventoy.json (IT DOES NOT MATTER IF THIS FILE IS HERE- duplication of isos will persist)

**Comment by Thyself17** [comment]
Here's a couple screenshots on windows of the directory structure

![Screenshot 2022-09-25 214637](https://user-images.githubusercontent.com/49064696/192190483-e388e91b-9cd8-486f-bb5c-6b51265744ca.jpg)
![Screenshot 2022-09-25 214720](https://user-images.githubusercontent.com/49064696/192190481-33e6783e-2f08-4132-acfc-25810e50b2b9.jpg)

**Comment by Thyself17** [comment]
Showing the duplication of .iso files 
![IMG_20220925_214920~2](https://user-images.githubusercontent.com/49064696/192190695-67d314f7-121d-4513-91a5-4f53cb1c6ecc.jpg)

Showing the missing /ventoy/ventoy.json.  This appears regardless of whether a ventoy.json file exists in the /ventoy folder
![IMG_20220925_215017~2](https://user-images.githubusercontent.com/49064696/192190690-418c4ff9-7efa-46d1-891b-b56cb5646ecc.jpg)

Navigating through the browser to show the "recursive" behavior
![IMG_20220925_214930](https://user-images.githubusercontent.com/49064696/192190696-90fa8c27-cc72-444e-9a97-f9aec8912ae1.jpg)
![IMG_20220925_214939](https://user-images.githubusercontent.com/49064696/192190702-eb29ffe1-dff3-4d6f-a0c6-0fab334c8578.jpg)
![IMG_20220925_214945](https://user-images.githubusercontent.com/49064696/192190710-b05a1384-1cbe-4df8-abdc-234e2c83b0a6.jpg)

**Comment by steve6375** [comment]
Probably a bad or fake USB drive. Try a different USB drive.

**Comment by Thyself17** [comment]
> Probably a bad or fake USB drive. Try a different USB drive.

Perhaps, though I'll note that removing the ventoy folder allowed the system to boot and run isos properly with no errors.  I don't have another USB drive on me right now to verify, but may be able to restart and try again in a week.

**Comment by Thyself17** [comment]
I have reformatted and recreated my drive which seems to have resolved the issue.

**Comment by Ant0ni022** [comment]
Just read the post and did a few testing and figured out why this happened. (Its very silly honestly). Its because the folder that has the theme.txt in it is also case sensetive. for example: Vimix needs to be "vimix" and inside the ventoy.json file also need to be lower-case.
