### ISSUE TITLE
"BypassStorageCheck" is useless

### ISSUE THREAD

**Issue by Silexium** [ventoy/Ventoy#1873]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

No. I didn't try the latest release.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

128GB

### Disk Manufacturer

Kingston

### What happened?

The `BypassStorageCheck` value in `HKEY_LOCAL_MACHINE\SYSTEM\Setup\LabConfig` doesn't actually do anything. ([#1990](https://github.com/pbatard/rufus/issues/1990))

**Comment by ventoy** [comment]
Removed https://github.com/ventoy/Ventoy/commit/911d5dcab9ef701c42dc0f275c7102c9669e076d
