### ISSUE TITLE
[issue]: no disk is found when windows 11 setup via an iso file.

### ISSUE THREAD

**Issue by cfbsks** [ventoy/Ventoy#1874]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.80

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64GB

### Disk Manufacturer

OV

### What happened?

A bug happened!
When I try to reinstall my Windows 11 Laptop, I got a problem. I download the Windows 11 iso image from Microsoft websites and move it in my ventoy Udisk. Then, start the setup program normally.
However, when the procedure moved to **check my disk capacity and select disk to install**, no any disk was found. I tried many times in variety methods, but nothing worked.
Please help!

**Comment by steve6375** [comment]
What make and model is the laptop, what hard disk is inside the laptop and what type is it, SATA, m.2, ?

**Comment by cfbsks** [comment]
Acer swift 3
M.2 NVME 1.4

**Comment by cfbsks** [comment]
> What make and model is the laptop, what hard disk is inside the laptop and what type is it, SATA, m.2, ?

Acer swift 3
M.2 NVME 1.4

**Comment by cfbsks** [comment]
I found some related explanation: after 11th gen Intel CPU, there is a VMD tech. I think it might cause this problem. Would anyone know more about it can help?

**Comment by steve6375** [comment]
Did setup give you any warnings at all? E.g. CPU or tpm or not large enough disk?

**Comment by cfbsks** [comment]
> Did setup give you any warnings at all? E.g. CPU or tpm or not large enough disk?

No, just no any disk in the list.

**Comment by steve6375** [comment]
Might be worth configuring the Win11 skipTPM,size.CPU Winn1 Bypass check using  VentoyPlugson ?
https://ventoy.net/en/plugin_control.html

**Comment by cfbsks** [comment]
diskpart->list disk->no media😥

> Might be worth configuring the Win11 skipTPM,size.CPU Winn1 Bypass check using VentoyPlugson ? https://ventoy.net/en/plugin_control.html Use SHIFT+F10 and run DISKPART to see if internal disk is listed

**Comment by cfbsks** [comment]
Finally!
I solved the problem. After 11th Intel CPU. IRST is enable by default . As so, before we operate the drives, we have to load the driver for specific environment. 
[Dell's explanation](https://www.dell.com/support/kbdoc/zh-cn/000188116/intel-11th-generation-processors-no-drives-can-be-found-during-windows-10-installation)
And I recommend to find drivers via your device maker's website

**Comment by liblaf** [comment]
I ran into the same problem. Loading the IRST driver when using Ventoy does not solve the problem, but loading the IRST driver when using Rufus works.
