### ISSUE TITLE
[issue]: VTOY_LINUX_REMOUNT=1 does not work with Batocera 35

### ISSUE THREAD

**Issue by gingerbeardman** [ventoy/Ventoy#1878]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.80

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

16GB

### Disk Manufacturer

SanDisk (model: Cruzer Blade)

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://updates.batocera.org/x86_64/stable/last/batocera-x86_64-35-20220917.img.gz

### What happened?

VTOY_LINUX_REMOUNT=1 does not work with Batocera 35.

I used VentoyPlugson to write the json file:

```
{
    "control":[
        { "VTOY_DEFAULT_SEARCH_ROOT": "/ventoy/ISO" },
        { "VTOY_LINUX_REMOUNT": "1" },
        { "VTOY_MENU_TIMEOUT": "3" }
    ]
}
```

**Comment by ventoy** [comment]
@gingerbeardman 
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/3202004006
https://www.ventoy.net/en/doc_github_ci.html

**Comment by gingerbeardman** [comment]
@ventoy that CI version works. Thanks!
