### ISSUE TITLE
安全启动映像未验证

### ISSUE THREAD

**Issue by wzwtt** [ventoy/Ventoy#1888]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.80

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### What happened?

制作ventoy时已经勾选安全启动支持。之前在惠普商用笔记本安全启动模式下能够成功出现 https://ventoy.net/cn/doc_secure.html 所示的界面并且已经按照文档所示进行操作，可以成功引导ventoy，但在更新bios后出现如图所示的报错，固件提示映像未验证，在关闭安全启动后才能正常引导。尝试使用[ventoy-delete-key-1.0.iso]，将其直接用Rufus写入u盘，但发现根本无法在安全启动模式下引导这个文件，仍然为如图报错。已尝试重新制作ventoy，但问题依旧。请问还能否在不关闭安全启动时使用ventoy呢？谢谢！
![11A47728-08C9-40E8-AF72-0BBAFC38291B](https://user-images.githubusercontent.com/21050445/193731181-c5faafaa-59db-44b7-a959-7bd5c51b9e28.jpeg)

**Comment by BonexP** [comment]
在三代战66笔记本上面也有这个问题.之后我在BIOS里"先进"-"安全引导配置"-"配置传统支持和安全引导"都禁用之后可以使用ventoy了.供参考.

**Comment by wzwtt** [comment]
> 在三代战66笔记本上面也有这个问题.之后我在BIOS里"先进"-"安全引导配置"-"配置传统支持和安全引导"都禁用之后可以使用ventoy了.供参考.

谢谢，本机电脑是四代战66，在bios先进里已经没有安全引导配置这个选项了，但在安全选项卡里有这个选项。不过这个选项里没有配置传统支持和安全引导这一项。😭😭![image](https://user-images.githubusercontent.com/21050445/201519533-23818319-ec9f-494b-b254-d6511a2634e5.jpeg)![image](https://user-images.githubusercontent.com/21050445/201519543-8db2fcbd-731f-4336-8bb2-c1bef8546081.jpeg)

**Comment by ventoy** [comment]
试试最新的版本

**Comment by wzwtt** [comment]
> 试试最新的版本

谢谢。我在更新最新的版本后已经可以重新正常引导了。
