### ISSUE TITLE
[Request]: EFI partition limit to 32 MiB prevents installing other efi loaders

### ISSUE THREAD

**Issue by vortigont** [ventoy/Ventoy#1890]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.80

### What about latest release

No. I didn't try the latest release.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GiB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### What happened?

I was hoping that it is possible to have more that one EFI loaders on Ventoy flash (i.e. refind or other), so it is enough to drop files under EFI/ subfolder and be it. Let UEFI "bios" decide which one to boot or chain-load one with another.
But looks like `Ventoy` is very picky regarding EFI partition size and refuses to boot if EFI partition's size is more than 32 MiB. Why is that limit enforced? It is OK to compare partition label even drop some "magic" file to check. But `why` strictly limiting partition size I do not understand.
Would appreciate any advise how to workaround it.
Thanks!

**Comment by steve6375** [comment]
The 32MB partition must not be moved or changed in size.
You can add the rEFInd ISO file to the first partition and use Ventoy to run it
You can add a /refind folder to the first partition from 'refind.bin' download file and use Ventoy to run it (or use F6 and add a /ventoy/ventoy_grub.cfg file)
You can add a third FAT partition and add the refind files to that partition (copy \EFI folder from the refind .iso  cd download). Then you can boot directly to refind from partition 3.

**Comment by steve6375** [comment]
It has been requested many times but allowing people to add to or change the files on the 2nd partition would mean that Ventoy is no longer a 'standard' drive and so it would be very difficult to support.
Also, if you do change the contents of the VTOYEFI partition, it will be destroyed when you do a Ventoy version update as the partition is removed and re-written on Updating.

You must change the code and recompile if you want to remove the checks (it is open source) but doing so may break something!

Most people just add a folder to the first partition for any UEFI files or add a 3rd partition (as I have said). Then your Ventoy drive will be 100% compatible still and updating will not destroy your new files/changes on Ptn2.

**Comment by vortigont** [comment]
> if you do change the contents of the VTOYEFI partition, it will be destroyed when you do a Ventoy version update as the partition is removed and re-written on Updating.

that makes sense. I was not aware of update procedure rewriting the whole partition.
Looks like there are to many thing depends on this restriction to consider relaxing it any time soon.
Thanks for your fastest and detailed replies on this, that was really useful information.
Cheers!

**Comment by wsy** [comment]
> if you do change the contents of the VTOYEFI partition, it will be destroyed when you do a Ventoy version update as the partition is removed and re-written on Updating.

Instead of writing image to overwrite the whole partition, maybe we can consider updating VTOYEFI partition by copying new files?
