### ISSUE TITLE
[Success Image Report]: Linux Mint 21 "Vanessa" x86-64

### ISSUE THREAD

**Issue by Silexium** [ventoy/Ventoy#1896]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.80

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

linuxmint-21-cinnamon-64bit.iso

### Image file checksum type

SHA256

### Image file checksum value

f524114e4a10fb04ec428af5e8faf7998b18271ea72fbb4b63efe0338957c0f3

### Image file download link (if applicable)

https://mirrors.layeronline.com/linuxmint/stable/21/linuxmint-21-cinnamon-64bit.iso

### Test environment

Custom PC

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
