### ISSUE TITLE
[Feature Request] Create separate Legacy and Uefi Boot Menu

### ISSUE THREAD

**Issue by soares23** [ventoy/Ventoy#19]
HI, it would be nice if it is possible i don't know but if in the name of the iso are legacy that this iso was only appear in legacy boot for uefi in uefi Menu and if there a nothing from both (uefi or legacy) that it will appaer on both in uefi and legacy boot. With that we can Have a more organisate Boot Menu, it would be nice if is possible. Thanks an sorry for my bad english.

**Comment by chromer030** [comment]
Or by pressing a function key in related boot mode ( UEFI or Legacy) ,  for example F2 , unsupported  ISO files disengage and disappear from Menu.
I don't know if this implementation could be possible.

**Comment by soares23** [comment]
> Or by pressing a function key in related boot mode ( UEFI or Legacy) , for example F2 , unsupported ISO files disengage and disappear from Menu.
> I don't know if this implementation could be possible but maybe this workarounds can be usable :
> 
> 1- By adding a discoverable specific filename flag (UEFI/Legacy) to each ISO file name , and Ventoy separate and disappear unrelated ones based of that.
> 2- Maintaining a reliable , always in updating phase database ( with help of users contributions ) for Ventoy , so that Ventoy will know which ISO has Full/Semi support of UEFI or Legacy or both.
> 3- Before showing the list Ventoy try to test and separate UEFI/BIOS capable ISOs (this make boot time longer ) , or after pressing a FN key try to do that.
> 4- User make two folder on USB , one with name of UEFI . one with name of Legacy and put related ISOs in related folder , then in the list , by pressing a FN key Ventoy separate ISO based on this folders and if press again show all ISOs.

I thing from the 4 options the best if is possible to make is the First an Last one because the Second if a iso is not in the database but is compatible for example Uefi not Legacy what Menu is showing.

The third option i thing how do you want test it. Maybe you can verify is a efi bootloader is in the iso but that will not guarantee that if one iso have a efi file to boot that is booting efi.

**Comment by chromer030** [comment]
@soares23 , thank you very much for your opinions and any effort that make this great and lovely tool better than before.
I will update my suggestions for this feature request if i find any idea.
And thank you millions for paying attention to my ISO tests.

**Comment by ventoy** [comment]
In most cases, I think the user should known  whether this ISO supports UEFI mode or not.
If this filtering is done by Ventoy, it will be very easy to misjudge.

**Comment by soares23** [comment]
Yes is true but if expample: i make the stick i know what is uefi or legacy but if other people use the stick also because working in a repair shop they don't know if all the iso that i but is uefi or not because they maybe not use all of that stuff. For an other reseon is also if you but an amount of iso thats bigger you must scroll very to reach the right iso if is more at the bottom if you has a splitt of uefi and legacy all these iso's isn't showing and you must not scroll so much and i thing also is a estetic point in my opinion to. If is possible maybe to programm that you create 2 folders how chromer030 has say maybe uefi and legacy and that ventoy was only search ISO in that Folder and separate the iso in there Menu was nice because if you would have exapmle Office iso oder other Programm Iso's also on the usb  drive oder harddrive he's showing also that was also e nice feature that they don't see them if possible.

**Comment by ventoy** [comment]
@soares23 @chromer030 

A new feature is under testing now. 
I will provide two styles of boot menu: normal list mode and directory tree mode. 
By default it's list mode, and you can switch freely between the two modes by a hotkey (e.g. F3)

So, we can expect the next release!

**Comment by ventoy** [comment]
You can try 1.0.08 with TreeView Mode.

**Comment by soares23** [comment]
HI tanks have try it is definitely better with that.  For me is ok, i can ignore the folders that i want and also create the folder tree thanks ventoy for that. 

I have another questions for version 1.0.08 in the previous version a have put the **parameter** in **grub.cfg** for **menuentry** the **--class $img_name**  after that i have change the icon name to the name of the iso that the icon is appear on the Menu. How can i do that with version 1.0.08 that you can tell me where i can but that and if it's no more possible that you can maybe put that option on new version that would be nice. Thanks for you great work.

**Comment by ventoy** [comment]
Yes, in 1.0.08 the menu and submenu was created in the backend.
I will add the file name or directory name as there class in the next release.

**Comment by soares23** [comment]
ok thanks it would be nice if maybe for both name and directory if possible if not than if possible ass option to specify if we would have Name or directory. THanks for the great work.

**Comment by soares23** [comment]
Hi Ventoy, i have a question have you implement in 1.0.09 the --class parameter don't see it on changelog and isn't working for now or i don't know how to activate?
