### ISSUE TITLE
[issue]: rockcluster, part of config missing during install

### ISSUE THREAD

**Issue by svennd** [ventoy/Ventoy#1900]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.80

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

64Gb

### Disk Manufacturer

samsung

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

http://central-7-0-x86-64.rocksclusters.org/isos/kernel-7.0-0.x86_64.disk1.iso

### What happened?

I was using Ventoy to install rocks cluster, but the part on "configure cluster" did not show, installation also failed complaining a missing package. I tried to upgrade to the latest version of Ventoy but the issue remained. After trying it on a VM I noticed the same behavior. When using Rufus, it does work as expected and shows the configure cluster.

You can see on this image : http://central-7-0-x86-64.rocksclusters.org/roll-documentation/base/7.0/images/install7/no-network-scrolled-640.png what it is suppose to look like.

Perhaps this can be resolved, or not, i'm unsure.

**Comment by ventoy** [comment]
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/3208753666
https://www.ventoy.net/en/doc_github_ci.html

**Comment by ventoy** [comment]
Fixed in the latest release.
