### ISSUE TITLE
[issue]: VentoyPlugson cannot read/write ventoy.json if exFAT ISO partition has a drive label with a space (e.g. "Ventoy 8GB")

### ISSUE THREAD

**Issue by NintendoManiac64** [ventoy/Ventoy#1901]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.80

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

1GB

### Disk Manufacturer

Verbatim

### Image file download link (if applicable)

N/A

### What happened?

Simply put, if Ventoy's exFAT ISO partition is renamed to something that has a space in the drive label, e.g. `Ventoy 1GB`, then VentoyPlugson will not be able to properly read or write the ventoy.json file to the drive.

...at least on a live ISO of Linux Mint 21.0 Xfce using its default mounting options, no idea about any other configuration.

　

**Off-topic question**: On the subject of Linux Mint 21's live ISO, on your Thinkpad T420 while it's booted into the OS, does it behave the same way as my T420 whereby one has to actually hold the power button for a second for the usual suspend/restart/shutdown dialog window to appear, i.e. just tapping the power button does nothing?

**Off-topic question 2**: With the battery *not* at 100%, when the T420 is powered off and the battery is removed, if you plug in the charger first and then subsequently insert the battery while the charger is connected (all while the T420 is powered off), does the T420 remain not charging until you re-plug the charger or power it on?

(I just recently came into possession of a T420 and I'm trying to figure out if these two "quirks" are design issues/"features" or just the fault of my specific unit)

**Comment by ventoy** [comment]
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/3212448500
https://www.ventoy.net/en/doc_github_ci.html

As for the two off-topic questions, I will test later.

**Comment by NintendoManiac64** [comment]
Sure enough, that works!

...btw, I discovered another T420 "quirk" - if "boot lock order" is enabled in the BIOS ("Startup" tab), then the Linux distro may create something like 100 EFI entries as shown by running the `efibootmgr' command in the terminal.

**Comment by ventoy** [comment]
**Off-topic question1**:   Yes, just tapping the power button does nothing. I press and hold for a few seconds still nothing, when I hold a little longer, it power off.
**Off-topic question2**:  The same.

**Comment by NintendoManiac64** [comment]
>. I press and hold for a few seconds still nothing,

It's worth mentioning that, depending on how your OS is configured, you may have it set that pressing the power button "does nothing" - this is why I mentioned the Linux Mint live ISO because, by default, it's configured to show the suspend/restart/shutdown dialog.
