### ISSUE TITLE
[issue]: 安装win11找不到硬盘驱动

### ISSUE THREAD

**Issue by gland2015** [ventoy/Ventoy#1903]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.80

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

550GB

### What happened?

最好能类似小兵启动盘, 可以注入驱动. 参考: http://www.dnxtc.net/zixun/zhuangjijiaocheng/2022-06-20/10057.html

**Comment by gland2015** [comment]
作为一个合格的启动盘。。。

**Comment by ventoy** [comment]
Ventoy 有文件注入插件可以注入驱动。具体参考说明文档。
https://www.ventoy.net/cn/plugin_injection.html

**Comment by gland2015** [comment]
> Ventoy 有文件注入插件可以注入驱动。具体参考说明文档。 https://www.ventoy.net/cn/plugin_injection.html

注入一个驱动后可以识别usb硬盘，但是识别本地硬盘还要另外一个驱动，这个驱动注入没效果，要手动加载，而且加载时还要二选一驱动，是不是这个二选一导致注入失败了

**Comment by ventoy** [comment]
你可以注入驱动文件的同时，注入一个 `VentoyAutoRun.bat`  把需要做的动作都写到这个脚本里面。参考： https://www.ventoy.net/cn/doc_inject_autorun.html

**Comment by gland2015** [comment]
> 你可以注入驱动文件的同时，注入一个 `VentoyAutoRun.bat` 把需要做的动作都写到这个脚本里面。参考： https://www.ventoy.net/cn/doc_inject_autorun.html

有没有示例参考下, 运行时bat文件能获取到驱动文件吗

**Comment by ventoy** [comment]
你不是驱动文件注入到某一个目录下了吗， 在 bat里面直接找到这个目录下的文件就可以了。

**Comment by gland2015** [comment]
可以了,用这个内容就行
pnputil -i -a %~dp0\dir\*.inf
