### ISSUE TITLE
[issue]: Hiren’s BootCD PE x64 (v1.0.2) does not show all programs if loaded in memdisk mode from exFAT or loaded in any mode from ext4

### ISSUE THREAD

**Issue by NintendoManiac64** [ventoy/Ventoy#1904]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.80

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GB, 128GB

### Disk Manufacturer

Microcenter (32GB), Samsung 830 (128GB 2.5" SSD connected via SATA)

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

http://hirensbootcd.org/

### What happened?

This is basically identical to the issue described here:
- https://github.com/ventoy/Ventoy/issues/992

...except in this case, it occurs if you load it in memdisk mode from exFAT or if you load it in any mode from ext4.

For reference, the only modes that seem to load all of the programs is normal mode from exFAT or wimboot mode from exFAT (and/or maybe NTFS as well - I haven't tested that).

Also, compared to what #992 described, I find that the easiest and quickest way to see if all programs are loaded is to just see if the Firefox icon is present on the desktop or not.

**Comment by ventoy** [comment]
Not all ISO files can use memdisk mode.  Hiren’s BootCD PE can not use memdisk mode. See https://github.com/ventoy/Ventoy/issues/1897

Windows doesn't support ext filesystem by default. So if you want to boot Windows/WinPE ISO files, you can not use ext4 file system for the ISO partition.
