### ISSUE TITLE
[Success Image Report]: Lakka 4.2

### ISSUE THREAD

**Issue by gingerbeardman** [ventoy/Ventoy#1908]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.80

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

Lakka-Generic.x86_64-4.2.img

### Image file checksum type

MD5

### Image file checksum value

e208cea6a236327d84af841c28e7c4b3

### Image file download link (if applicable)

https://le-builds.lakka.tv/Generic.x86_64/Lakka-Generic.x86_64-4.2.img.gz

### Test environment

Dell Wyse 5060

### More Details?

This image file booted successfully in Ventoy.

I successfully used both of Lakka's boot options: Live & Installer.

**Comment by ventoy** [comment]
Thanks!
