### ISSUE TITLE
[issue]: easyOS easy-4.4.2-amd64.img error: cannot find easy.sfs

### ISSUE THREAD

**Issue by leyleyla** [ventoy/Ventoy#1926]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.80

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32G

### Disk Manufacturer

teamgroup

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://distro.ibiblio.org/easyos/amd64/releases/dunfell/2022/4.4.2/easy-4.4.2-amd64.img

### What happened?

A bug happened!
error: cannot find easy.sfs
![easyos_312267754_481075277382530_6705029304314884289_n](https://user-images.githubusercontent.com/116318854/197077999-c8b022dd-693f-47ad-8375-72121b3cd6f5.jpg)

**Comment by ventoy** [comment]
@leyleyla 
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/3302426044
https://www.ventoy.net/en/doc_github_ci.html

**Comment by leyleyla** [comment]
dear longpanda, thank you for your quick reply!
unfortunately both 10220751 and the latest 10221221 builds (sha256 sums are correct) gave the following error:
![ventoy_309714883_404083771776769_2355133008086958465_n](https://user-images.githubusercontent.com/116318854/197367428-36ea83c9-9d77-4c11-ae83-9811750241ca.jpg)
keen to try your next build

**Comment by ventoy** [comment]
`10220751 and the latest 10221221 builds`
Where to download the image files?

**Comment by ventoy** [comment]
I test https://distro.ibiblio.org/easyos/amd64/releases/dunfell/2022/4.4.3/easy-4.4.3-amd64.img and it boo OK.
![image](https://user-images.githubusercontent.com/59477474/197382350-b72085a0-8f1c-4c85-8fa7-d4a4a1f289ee.png)

**Comment by leyleyla** [comment]
easy-4.4.3 works great (with 10221221 build)!
thank You for the heads up and effort!

longpanda ***@***.***> ezt írta (időpont: 2022. okt. 23., V,
10:30):

**Comment by ventoy** [comment]
So which image file did you test fail with the CI release?
Which image file is `10220751 and the latest 10221221 builds` 
I want to download and test it to see why it boot fail in your environment.

**Comment by ventoy** [comment]
Fixed in Ventoy 1.0.81

**Comment by leyleyla** [comment]
Sorry for replying so late, feeling bit confused, I might have a hardware
issue, right now vt 1.0.81 works with easy 4.4.3

longpanda ***@***.***> ezt írta (időpont: 2022. okt. 30., Vas
6:45):
