### ISSUE TITLE
[Feature request]: Be able to show or hide `password asterisk characters` via `VentoyPlugson`

### ISSUE THREAD

**Issue by keks24** [ventoy/Ventoy#1931]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.81

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

Not needed.

### Disk Manufacturer

Not needed.

### What happened?

Refers to #1868.

Hello!

It would be nice to have a switch for the `password visibility (asterisk characters)`.

Even, if every character is obfuscated; not showing any character at all is the safest way.

Thank you for your efforts!
-Ramon

**Comment by ventoy** [comment]
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/3327016927
https://www.ventoy.net/en/doc_github_ci.html

**Comment by keks24** [comment]
Awesome, works nicely!

**Comment by ventoy** [comment]
Feature added in Ventoy 1.0.81.
