### ISSUE TITLE
[issue]: Secure Boot - Ventoy update process doesn't update EFI files

### ISSUE THREAD

**Issue by tomgar** [ventoy/Ventoy#1933]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.81

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128GB

### What happened?

I was updating Ventoy since long time ago in my pendrive, but at some moment due to DBX updates, my computer started to refuse loading the EFI files from the Ventoy pendrive in Secure Boot mode.

I started to compare SHA256 hashes from the EFI files and the CSV list in https://uefi.org/revocationlistfile and I noticed that BOOTX64.EFI was in the revocation list.

I actually fixed my Ventoy pendrive with Secure Boot, by downloading Ventoy's source code and overwriting the EFI files from the source code (INSTALL > EFI > BOOT) in the VTOYEFI partition of the pendrive > EFI > BOOT directory, since the source code has more recent EFI files (I saw that for the other non-X64 architectures there are still EFI files in the revocation list, so for some other archs it won't be possible to use secure boot if their DBX database is updated).

I've been using the Ventoy2Disk.sh -u for updating in Linux.

**Comment by ValdikSS** [comment]
Try to use `Ventoy2Disk.sh -u -s`.

**Comment by tomgar** [comment]
Thank you @ValdikSS I will try in next update, but I find it odd that I need to explicitly indicate that since the Ventoy2Disk.sh says that's actually the default option:

```
**********************************************
      Ventoy: 1.0.86  x86_64
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

Usage:  Ventoy2Disk.sh CMD [ OPTION ] /dev/sdX
  CMD:
   -i  install Ventoy to sdX (fails if disk already installed with Ventoy)
   -I  force install Ventoy to sdX (no matter if installed or not)
   -u  update Ventoy in sdX
   -l  list Ventoy information in sdX

  OPTION: (optional)
   -r SIZE_MB  preserve some space at the bottom of the disk (only for install)
   -s/-S       enable/disable secure boot support (default is enabled)   <---- here
   -g          use GPT partition style, default is MBR (only for install)
   -L          Label of the 1st exfat partition (default is Ventoy)
   -n          try non-destructive installation (only for install)

```

**Comment by tomgar** [comment]
I've tested with 1.0.91 and it's doing the right thing now it seems. No need to add "-s" and I saw the efi files being updated (and even re-instated after a test I did where I deleted the efi files from the destination before doing an upgrade), therefore closing this issue.
