### ISSUE TITLE
[issue]: WEB/GUI does not restore MBR when updating

### ISSUE THREAD

**Issue by Ratio2** [ventoy/Ventoy#1935]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.81

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

20GB

### Disk Manufacturer

VirtualBox

### What happened?

If for some reason we overwritten the MBR (for example, we installed Debian to an empty place), then the CLI restores the MBR, but the WEB/GUI does not.

According to the source codes, it can be seen that the CLI overwrites the entire MBR, and the WEB/GUI patches the existing one.

Alien MBR fails integrity check and boot fails.

**Comment by ventoy** [comment]
@Ratio2  Please try this CI release: https://github.com/ventoy/Ventoy/actions/runs/3354264255
https://www.ventoy.net/en/doc_github_ci.html

**Comment by Ratio2** [comment]
I checked the GUI in ISO, the problem is fixed.
