### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by MIKAILREI** [ventoy/Ventoy#1936]
### Official Website List: Mini tool partition Bootable media

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

 1.1.80

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

mtboot.iso

### Image file checksum type

MD5

### Image file checksum value

AC87925029785AC6576F8EEAE5104C1D

### Test environment

Dell Inspiron 5000 Series (5410) 2 in 1

### More Details?

This image file booted successfully in Ventoy without problems!.

**Comment by ventoy** [comment]
Thanks!
