### ISSUE TITLE
[issue]: Can't back to Image List after Image File selected

### ISSUE THREAD

**Issue by RyuujiX** [ventoy/Ventoy#1937]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.81

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

V-Gen

### What happened?

Hello, i can't go back after selecting Image File....

After ISO selected, then secondary boot option appeared.... and i want to change other iso files, i can't back to iso menu.... also, can't access option like F5 ( Tools ), F4 (Localboot) need to force reboot.... 

Hope you fix this, thanks

**Comment by ventoy** [comment]
This is exactly how the secondary boot menu designed.
In old release, there is no secondary boot menu, so when you select an ISO file it immediately start to boot the ISO file.

In latest release, when the secondary boot menu display,  most of the work for booting this ISO file has been done and can not return back.
It's similar with the menu for select auto install script.

**Comment by ventoy** [comment]
The secondary boot menu is not a static menu but a dynanmic menu.
For example:
`Boot in wimboot mode`  will only display when the ISO file is Windows. 
`Boot in grub2 mode` will only display when the ISO file is Linux.

So we can not display the secondary boot menu at the very begginning after you select an ISO file.
So when you see the secondary boot menu, we have finished most of  the work for booting this ISO file.
