### ISSUE TITLE
[issue]: ISO default language is Chinese

### ISSUE THREAD

**Issue by Ratio2** [ventoy/Ventoy#1938]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.81

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

20GB

### Disk Manufacturer

VirtualBox

### What happened?

Perhaps it is worth changing the default to English, as the most popular in the IT world.

**Comment by ventoy** [comment]
This CI release fix it: https://github.com/ventoy/Ventoy/actions/runs/3357976806

**Comment by ventoy** [comment]
Fixed in 1.0.82
