### ISSUE TITLE
[issue]: Help line disappears when auto-going to a submenu

### ISSUE THREAD

**Issue by Ratio2** [ventoy/Ventoy#1939]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.81

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

20GB

### Disk Manufacturer

VirtualBox

### What happened?

/ventoy/ventoy.json
```
{
    "control":[
        { "VTOY_MENU_TIMEOUT": "5" },
        { "VTOY_DEFAULT_IMAGE": "F6>0" }
    ]
}
```
/ventoy/ventoy_grub.cfg
```
menuentry "Debian configfile" {
	search --no-floppy --fs-uuid --set=root faf7353a-bceb-41b2-bc9c-a46d9d194fd1
	configfile /boot/grub/grub.cfg
}

menuentry "Debian multiboot" {
	search --no-floppy --fs-uuid --set=root faf7353a-bceb-41b2-bc9c-a46d9d194fd1
	multiboot /boot/grub/i386-pc/core.img
}

menuentry "Debian chainloader" {
	search --no-floppy --fs-uuid --set=root 55F7-B2F8
	chainloader /EFI/debian/shimx64.efi
}
```
![Screenshot from 2022-10-30 20-10-45](https://user-images.githubusercontent.com/2958497/198892018-c63432f4-7f59-4dcf-9795-746eb90b9adb.png)
![Screenshot from 2022-10-30 20-10-59](https://user-images.githubusercontent.com/2958497/198892023-34634dc6-4bc4-46b9-b1c1-4860974b8171.png)

**Comment by ventoy** [comment]
Fixed in 1.0.82
