### ISSUE TITLE
[issue]: Are you sure you want to copy this file without its properties? exfat??

### ISSUE THREAD

**Issue by oklokl** [ventoy/Ventoy#1940]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

ventoy-1.0.81

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32G

### Disk Manufacturer

Samsung SD card

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewiso

### What happened?

A bug happened!

![1](https://user-images.githubusercontent.com/1571600/198897200-a6ed0a5b-4084-41c6-98c5-536287f205de.png)
https://files.rg-adguard.net/file/091409ce-a67b-5159-e164-f21626724b85
SHA-256: 286A0444E1A69B6ADED4251319C5D240A128A5551B31F1C6FD32A75C22E4D5D0
No file hash issues.

https://youtu.be/0p8gyyHCg0Y
Recorded on video.

The partition is `exfat`. Why is this message? are you coming out?

For reference, this message does not appear for Korean Windows iso files.
![2022-10-31 (2)](https://user-images.githubusercontent.com/1571600/198897401-64cfc956-a6f1-43f7-804d-950a63631244.png)
![2022-10-31 (3)](https://user-images.githubusercontent.com/1571600/198897402-cec4aafb-ab98-40cf-b14b-9ecc98830342.png)
There is no bad sector.

.

.

https://answers.microsoft.com/en-us/windows/forum/all/are-you-sure-you-want-to-copy-this-file-without/fa810b7e-f228-4661-9789-2090175dd7de
Are you sure you want to copy this file without its properties?
NTFS to fat32 
I know this.

My question is now the partition is
This is `exfat`.

I didn't set up or modify any partitions.
I use it as set in the program.

.

additional message
473.81-desktop-win10-win11-64bit-international-dch-whql.exe
ipfilter.zip

When this program is also transferred to `usb`, it asks the above.
If you click 'Yes', it will be copied without any problem.

Could it be a virus?

**Comment by ventoy** [comment]
I think `exfat` is just an extend of classical `fat32` and behaves the same for file properties.

Create a txt file in NTFS filesystem as follows:
```
echo  123 > abc.txt:ads.txt
```

Then when you copy the `abc.txt` file to `exfat` file system it will show this message.

**Comment by oklokl** [comment]
thank you.
I was worried.
I suspected it was a virus.
I'm glad it's been resolved.

I have recently been experiencing an unknown Windows login type 11 cache.
Although I fixed it to `ForceUnlockLogon 0`.
I haven't found the cause yet.
:(
