### ISSUE TITLE
[issue]: 问题

### ISSUE THREAD

**Issue by llxiaoyuan** [ventoy/Ventoy#1942]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.80

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### Disk Manufacturer

金士顿

### What happened?

我在启动 WindowsPE.iso 的时候发现有三种启动选项，分别是

1. Boot in normal mode
2. Boot in wimboot mode
3. Boot in memdisk mode

经过一些测试，发现 1. 的速度比较快，我猜测是虚拟光驱实现的，可以描述一下 1. 的实现原理吗，先行感谢。

**Comment by ventoy** [comment]
这个一两句话说不清楚。在无忧论坛有说明过，可以到下面爬楼。
http://bbs.wuyou.net/forum.php?mod=viewthread&tid=419840&extra=page%3D1
