### ISSUE TITLE
[question] open-folder 📂 installation for Windows - possible?

### ISSUE THREAD

**Issue by ghost** [ventoy/Ventoy#1943]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.80

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

16GB

### What happened?

(I need FAT32 (not NTFS/ExtFS) and ISOs are ~4GB..)

is it possible for me to extract the iso to a folder and add it to the menu,  
(which includes unattend xml) or tell ventoy to boot from there?

`install.esd` is about 3.5GB, `boot.wim` and the rest of the files so it is fine,

**Comment by ventoy** [comment]
You can try:
1. Extract the iso to a folder
2. Use some tool (e.g. UltralSO) to edit the ISO file, delete the big install.esd and get a small ISO file.
3. Use Ventoy injection plugin to inject a `VentoyAutoRun.bat` for the new small ISO file.  
In the bat file, find the folder and use `subst` command to map the folder to a logic drive.
https://www.ventoy.net/en/doc_inject_autorun.html
