### ISSUE TITLE
[issue]: 无法在win10或win11，以及livecd的模式下安装联想TU202固态硬盘

### ISSUE THREAD

**Issue by sungamma** [ventoy/Ventoy#1945]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.81

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

128GB

### Disk Manufacturer

闪存显示为Soar Tech  U盘型号联想TU202

### What happened?

联想双接口TU202固态移动U盘，win11下面安装ventoy，在16%和22%来回跳动，过一会出现错误。错误见附件log。

随后采用创建vtsi文件的方式，利用rufus进行安装，也没有成功。

我在磁盘管理器里面看到的是953gb的硬盘。

<img width="1120" alt="屏幕截图 2022-11-03 235959" src="https://user-images.githubusercontent.com/33790/200119452-91a215e1-23c9-49a0-aad9-f4486d6b88a2.png">

附件log.txt
[log.txt](https://github.com/ventoy/Ventoy/files/9943746/log.txt)

随后利用另外一个u盘，进入到livecd，没有办法用ctrl+alt+f2打开shell，只能gui模式下安装ventoy。提示成功。见下面两张图
<img width="672" alt="image" src="https://user-images.githubusercontent.com/33790/200119603-b6d870e3-0dd7-4e28-b903-a7465db30842.png">
<img width="704" alt="image" src="https://user-images.githubusercontent.com/33790/200119610-92c7042a-484c-4d66-a720-00b826d85be6.png">
但是重启还是不能引导，重新进入win下，磁盘管理器看到的是这样的。
<img width="856" alt="image" src="https://user-images.githubusercontent.com/33790/200119700-37d4242d-3291-4c5c-a662-f5120eb94f50.png">

简单来说，对于这个硬盘，win下直接安装，rufus安装vtsi，livecd安装均失败。
另外，livecd下ctrl+alt+f2打不开shell，选的是debug模式

**Comment by sungamma** [comment]
Use manjaro live cd, try use ventoy2disk.sh install. But failed again, it told me "Error: The location 249905151 is outside of the device /dev/sdd."
```
sudo sh Ventoy2Disk.sh -I /dev/sdd                             ✔  40s  

**********************************************
      Ventoy: 1.0.81  x86_64
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

Disk : /dev/sdd
Model: Soar Tech (scsi)
Size : 119 GB
Style: MBR


Attention:
You will install Ventoy to /dev/sdd.
All the data on the disk /dev/sdd will be lost!!!

Continue? (y/n) y

All the data on the disk /dev/sdd will be lost!!!
Double-check. Continue? (y/n) y

Create partitions on /dev/sdd by parted in MBR style ...
Error: The location 249905151 is outside of the device /dev/sdd.
Done
Wait for partitions ...
Wait for /dev/sdd1//dev/sdd2 ...
Wait for /dev/sdd1//dev/sdd2 ...
Wait for /dev/sdd1//dev/sdd2 ...
Wait for /dev/sdd1//dev/sdd2 ...
Wait for /dev/sdd1//dev/sdd2 ...
Wait for /dev/sdd1//dev/sdd2 ...
Wait for /dev/sdd1//dev/sdd2 ...
Wait for /dev/sdd1//dev/sdd2 ...
Wait for /dev/sdd1//dev/sdd2 ...
Wait for /dev/sdd1//dev/sdd2 ...
sed: can't read /sys/class/block/sdd1/dev: No such file or directory
mknod -m 0660 /dev/sdd1 b  ...
mknod: missing operand after ‘b’
Special files require major and minor device numbers.
Try 'mknod --help' for more information.
sed: can't read /sys/class/block/sdd2/dev: No such file or directory
mknod -m 0660 /dev/sdd2 b  ...
mknod: missing operand after ‘b’
Special files require major and minor device numbers.
Try 'mknod --help' for more information.
[FAIL] /dev/sdd1//dev/sdd2 does not exist

```

**Comment by sungamma** [comment]
换u盘了

**Comment by yjqg6666** [comment]
遇到了相同的问题。linux下面安装也会失败， 同样遇到的报错是 

> Create partitions on /dev/sda by parted in GPT style ...
> Error: The location 499826647 is outside of the device /dev/sda.
> Done
> Wait for partitions ...
> Wait for /dev/sda1//dev/sda2 ...
> Wait for /dev/sda1//dev/sda2 ...
> Wait for /dev/sda1//dev/sda2 ...
> Wait for /dev/sda1//dev/sda2 ...
> Wait for /dev/sda1//dev/sda2 ...
> Wait for /dev/sda1//dev/sda2 ...
> Wait for /dev/sda1//dev/sda2 ...
> Wait for /dev/sda1//dev/sda2 ...
> Wait for /dev/sda1//dev/sda2 ...
> Wait for /dev/sda1//dev/sda2 ...
> sed: can't read /sys/class/block/sda1/dev: No such file or directory

联想的固态u盘：
Disk /dev/sda: 238.37 GiB, 255944818688 bytes, 62486528 sectors
Disk model: Tech            
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 268431360 bytes
Disklabel type: gpt
Disk identifier: 5707F7F9-D620-4E48-B6BC-521B937846AB

**Comment by sungamma** [comment]
建议换u盘解决，买了闪迪的cz880。

**Comment by ventoy** [comment]
这个应该是因为固态盘是纯4K扇区，不支持512扇区。Ventoy不支持纯4K的扇区模式。

**Comment by yjqg6666** [comment]
> 这个应该是因为固态盘是纯4K扇区，不支持512扇区。Ventoy不支持纯4K的扇区模式。

所以是固态U盘都会遇到这个问题。有没有啥配置项或修改源码的方式绕过这个。

**Comment by ventoy** [comment]
没有选项。 
也不是所有的固态U盘都有问题，应该是很多固态U盘都支持 512 扇区模式，都没问题。有问题的是少数。

**Comment by yjqg6666** [comment]
> 建议换u盘解决，买了闪迪的cz880。

已经退货 重新换了个不是固态的u盘。

**Comment by sungamma** [comment]
> > 建议换u盘解决，买了闪迪的cz880。
> 
> 已经退货 重新换了个不是固态的u盘。

那个闪迪的固态可以的。无限质保

**Comment by sungamma** [comment]
> > 建议换u盘解决，买了闪迪的cz880。
> 
> 已经退货 重新换了个不是固态的u盘。

那个闪迪的固态可以的。无限质保
