### ISSUE TITLE
[issue]: v1.81在B85M-Gamer无法启动，提示Invalid image

### ISSUE THREAD

**Issue by Phil-Libra** [ventoy/Ventoy#1948]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.81

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### Disk Manufacturer

Sandisk

### What happened?

v1.81在B85M-Gamer上无法启动，提示Invalid image。测试GPT和MBR都无法解决。
回退v1.80正常。

v1.81在其他主板（Z170/X570S/B450）上测试可启动。

**Comment by ventoy** [comment]
1.0.82 版本怎么样？

**Comment by Phil-Libra** [comment]
> 

已测试，1.0.82可以引导了

**Comment by ctz556** [comment]
1.0.82在h81主板（dell品牌机）上UEFI启动出现同样问题，在技嘉B85M-D3H上正常。

**Comment by ventoy** [comment]
> 1.0.82在h81主板（dell品牌机）上UEFI启动出现同样问题，在技嘉B85M-D3H上正常。

@ctz556  1.0.84 呢？
