### ISSUE TITLE
[issue]: UQi_USBsys_12th.iso 这个PE系统用U盘启动不了

### ISSUE THREAD

**Issue by jay763190097** [ventoy/Ventoy#1949]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.80

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

16G

### Disk Manufacturer

Kingston

### Image file download link (if applicable)

https://www.uqiba.com/post/2021.html

### What happened?

A bug happened!
![微信图片_20221110000633](https://user-images.githubusercontent.com/16317178/200880749-75329fe3-6f11-427a-aadf-240ea13ea0bd.jpg)

**Comment by ventoy** [comment]
先按照如下方式校验一下ISO文件，确保ISO文件在拷贝到U盘过程中没有损坏。
https://www.ventoy.net/static/img/filechecksum.gif

**Comment by jay763190097** [comment]
@ventoy 
校验了
![微信图片_20221112005921](https://user-images.githubusercontent.com/16317178/201391747-ce1a1f79-dad5-4af8-8848-86df8707577d.jpg)

**Comment by ventoy** [comment]
从这里下载的：
http://www.jinhu.me/article.asp?id=252
```
文件: UQi_USBsys_12th[ISO].7z
大小: 812663170 字节（775MB）
MD5: 3758D0F5170F5F83FC3329C6F829427B
SHA1: 4E57AC819D572B881559D3D401E67109D3E4A9AF
CRC32: BAFC8BCE
```

这里面解压出来的 `UQi_USBsys_12th.iso` 的文件的校验值和你图片中的对不上。
正确的 sha256 值应该是 `68242F5924936AE44DCF3318B6118C8A48EB558C98E954633689D50509AC7A19`

我自己在电脑是测试的这个  `UQi_USBsys_12th.iso`  启动是正常的。

**Comment by jay763190097** [comment]
![image](https://user-images.githubusercontent.com/16317178/201917222-c358429b-be58-404a-a8c3-6097661fd578.png)
这个指的是这个7z压缩包的校验值

**Comment by ventoy** [comment]
之前不能启动是不是文件损坏了？
