### ISSUE TITLE
no way to force the booting of ISOs into uefi

### ISSUE THREAD

**Issue by distilledliquor** [ventoy/Ventoy#195]
I couldn't make a boot into uefi with the iso image file which supports legacy bios and uefi both even if I choose Ventoy with uefi on motherboard's bios booting interface.

Is there a way to force it?

**Comment by ventoy** [comment]
It depends on your bios, ventoy is the passive side.
You can disable the **CSM** support in your BIOS setup and then your BIOS will only support UEFI mode.

**Comment by distilledliquor** [comment]
> It depends on your bios, ventoy is the passive side.
> You can disable the **CSM** support in your BIOS setup and then your BIOS will only support UEFI mode.

I disabled it and I finally could make it. Thanks :)
