### ISSUE TITLE
[issue]: ventoy-1.0.81-windows.zip  flagged as Trojan.Malware.300983.susgen

### ISSUE THREAD

**Issue by petrus9** [ventoy/Ventoy#1950]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.81

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

64

### Disk Manufacturer

teamgroup

### Image file checksum (if applicable)

Yes.

### What happened?

Tested ventoy-1.0.81-windows.zip  in virustotal.com  and got a positive flag for Trojan.Malware.300983.susgen

![image](https://user-images.githubusercontent.com/63444532/200931172-affdd368-32f9-4896-bfd1-a1f62b592373.png)

![image](https://user-images.githubusercontent.com/63444532/200931270-b9119467-8343-48da-b52d-39708eb52b0c.png)

**Comment by ventoy** [comment]
Every release since 1.0.00 will get false positive report, I can't do anything.
Ventoy is 100% open source.
