### ISSUE TITLE
Request for Guest Plugin/mode in Ventoy Menu

### ISSUE THREAD

**Issue by devdevadev** [ventoy/Ventoy#1953]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.81

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

Samsung

### What happened?

Hi LongPanda...

I am currently enjoying Password Plugin of Ventoy in my USB Drive. But sometimes we have to give our USB Drive to third person for some specific rescure/installation purpose. But we don't want to tell boot password of our Ventoy USB Drive to them. It will be very useful in these situations if we can have Guest Plugin/mode in our Ventoy USB Drive so we can tell guestpwd to Guest and only predefind images/file/iso will be accessible to Guest. 

Guest Plugin/mode will work along with Password Plugin. When user will enter password then first match it with bootpwd if entered password is same as bootpwd then load full Ventoy menu as usual. If entered password is not matched with bootpwd then look for Guest Plugin (if present) and match entered password with guestpwd, If password is matched then load Guest Menu with predefind images/file/iso . 

{
    "password": {
        "bootpwd": "txt#123456",
        "isopwd": "txt#111",
        "wimpwd": "txt#222",
        "imgpwd": "txt#333",
        "vhdpwd": "txt#444",
        "efipwd": "txt#555",
        "vtoypwd": "txt#666",
        "menupwd": [
            {
                "parent":"/MyVhdDir/WindowsVHD",
                "pwd":"md5#def#14fa11b4ab450b0204182266140e284d"
            },
            {
                "file":"/ISO/MX-19.1_x64.iso",
                "pwd":"md5#e10adc3949ba59abbe56e057f20f883e"
            },
            {
                "file":"/ISO/ubuntu-20.04-desktop-amd64.iso",
                "pwd":"md5#abc#0659c7992e268962384eb17fafe88364"
            }
        ]
    }

    "guest": {
        "guestpwd": "txt#123",
        "file_list": [
            "/ISO/Linux/archlinux-2020.10.01-x86_64.iso",
            "/ISO/MAINMENU/Win10PE.iso"
        ],
        "parent_list": [
            "/ISO/Linux",
            "/ISO/WINDOWS/WIN10",
            "/ISO/WinPE"
        ]
    }
}

Do you think it will be possible to implement Guest Plugin/mode in Ventoy menu system ? If it would be possible then we can also have multi set of Guest Profiles with different subset of images/file/iso for different Guest to access same Ventoy USB Drive for different purposes without disclosing our Master bootpwd to anyone. 

Thanks & Regards....

**Comment by ventoy** [comment]
I think you can prepare another `ventoy.json` file for guest.
For example, you put 
```
ventoy/ventoy.json
ventoy/ventoy_guest.json
```
`ventoy.json` is for you and `ventoy_guest.json` is for guest.
Rename the two json files when you need to give your USB to the guest
```
ventoy/ventoy_main.json
ventoy/ventoy.json
```

You can set  `ISO file list/password/theme/....`  all the supported customized options for your guest.
