### ISSUE TITLE
Fedora 37 Cannot Boot with Ventoy 1.0.81

### ISSUE THREAD

**Issue by linuxtopia** [ventoy/Ventoy#1955]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.81

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

16GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://download.fedoraproject.org/pub/fedora/linux/releases/37/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-37-1.7.iso

### What happened?

Ventoy's latest release is not compatible with new released Fedora 37 isos. I have downloaded KDE, LXQT etc. all those working with virtualbox but cannot boot with Ventoy even with GRUB2 mode.

I cannot get bug log bur roughly message is kinda that:
`dracut fatal failed to find a root filesystem`
`dracut-initqueue wrong fs type`

I hope you'll find a solution and update Ventoy.

Thanks

**Comment by ventoy** [comment]
Checksum the ISO file as follows: 
https://www.ventoy.net/static/img/filechecksum.gif

![image](https://user-images.githubusercontent.com/59477474/202165645-d5b3d682-cee7-4866-ba79-c2a2135b4c6e.png)

**Comment by linuxtopia** [comment]
very weird, original file on my sdd matches checksum but copied version on usb does not. how to solve this?

**Comment by ventoy** [comment]
If you use Linux, you can run `sync` command in the terminal after you copy the ISO file to the USB.

![image](https://user-images.githubusercontent.com/59477474/202204587-f6d4bbf7-7977-44e8-a697-0bd0f89494be.png)
