### ISSUE TITLE
[Success Image Report]: MHDD (Magic Boot Disk v2.0)

### ISSUE THREAD

**Issue by GitArUs** [ventoy/Ventoy#1964]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.81

### BIOS Mode

Legacy BIOS Mode

### Partition Style

GPT

### Image file name

Magic_Boot_Disk_ISO_v2.0.iso

### Image file checksum type

SHA256

### Image file checksum value

ae19dd138695f3d565ab65c3c25c38b472768dd6d623d245b27d31484dc7e193

### Image file download link (if applicable)

https://hddguru.com/software/2006.02.10-Magic-Boot-Disk/

### Test environment

Desktop PC, custom build on Asus P5B Deluxe motherboard (yes, old hardware).

### More Details?

This image file booted successfully in Ventoy **in memdisk mode**.
OS: Based on Windows 98 Second Edition boot disk (DOS mode).
It contains MHDD - HDD diagnostic tool. Works fine booted in Ventoy.

**Comment by ventoy** [comment]
Thanks!

**Comment by guitarbug** [comment]
the MHDD ISO image file also can boot successfully in Ventoy in **memdisk mode**
http://hddguru.com/download/software/mhdd/mhdd32ver4.6iso.zip
