### ISSUE TITLE
[Feature Request]: on top of the iso list, when you go up you would go to the bottom of the list

### ISSUE THREAD

**Issue by eskiiom** [ventoy/Ventoy#1966]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.82

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

128

### Disk Manufacturer

sandisk

### Image file checksum (if applicable)

No.

### What happened?

Hello and thank you for one of the best tool of the century :)
I didn't find where to submit feature requests so if an issue is not the right place please tell me.

I think everything is on the title.
Why I'm requesting for that is because I have ordered my iso with LIN and WIN prefixes
And it would be nice to be able in 2 keystrokes to go from LIN-archalbs to WIN-xx

Thanks

**Comment by ventoy** [comment]
You can press `Home` / `End` key to go to the top / bottom entry.
Also you can use `PgUp` / `PgDn` key for page up / down.

**Comment by eskiiom** [comment]
I'm sorry I feel so dumb ...
Thanks for the answer, I confirm it obviously works.
