### ISSUE TITLE
[issue]: Installation broken after attempted update

### ISSUE THREAD

**Issue by jwgn** [ventoy/Ventoy#1967]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.82

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

128GB

### What happened?

I tried to use the installer to update my Ventoy from 1.0.79 to 1.0.82. It told me the update is safe. It failed. When I try to install it now, it tells me:

The device will be formatted and all the data will be lost.
Continue?

Instead of my ISO files, there are now the following files on the stick:

EFI
grub
tool
ventoy
ENROLL_THIS_KEY_IN_MOKMANAGER.cer

What now? How to make it working again? Where are the ISO files?

[log.txt](https://github.com/ventoy/Ventoy/files/10046704/log.txt)

**Comment by ventoy** [comment]
Press `Win` + `R` and enter `diskpart` to launch diskpart.exe

Then run `list volume` command in diskpart.exe, it will list all the volumes in your computer as follows:
![image](https://user-images.githubusercontent.com/59477474/202847799-691b2392-ed4a-46d2-be08-b2d4c2d7cc21.png)

Find the volume with label `Ventoy`.  I assume that `Volume 5` is the Ventoy volume, then run 
```
select volume 5
assign
```
Then you should see your ISO files again in your computer.

**Comment by jwgn** [comment]
Thanks, but I have now re-created and re-downloaded all ISO files and created the stick from scratch. I will not try to update Ventoy again.
