### ISSUE TITLE
[issue]: error: '/dev/disk/by-label/COS_2211' did not show up after 30 seconds

### ISSUE THREAD

**Issue by ksz00** [ventoy/Ventoy#1970]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.82

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### What happened?

When booting from the latest Cachyos gui iso, I receive the following error.

Waiting 30 seconds for device /dev/disk/by-label/COS_2211...
ERROR: '/dev/disk/by-label/COS_2211' device did not show up after 30 seconds...
Falling back to interactive prompt
You can try to fix the problem manually, log out when you are finished
sh: can't access tty: job control off

With the older iso versions the erros was similar

**Comment by ventoy** [comment]
I test  `cachyos-kde-linux-221119.iso`   and it boot fine.
Please checksum the iso file as follows to make sure that the ISO file was not corrupted during copy to the USB:
https://www.ventoy.net/static/img/filechecksum.gif

refer: #1955

`cachyos-kde-linux-221119.iso`  SHA256 should be `b545db32ce45fb307aa1189f69fddc874503ee1b8b68c47cf0cd6d2e3066b899`

![image](https://user-images.githubusercontent.com/59477474/202907683-db8d9e12-877a-4b33-b72f-bda7820aee8a.png)

**Comment by ventoy** [comment]
@ksz00  Any update?
