### ISSUE TITLE
[issue]: Fedora Silverblue 37 not boot w/ Ventoy 1.0.82

### ISSUE THREAD

**Issue by Thv1337** [ventoy/Ventoy#1971]
![error_silverblue](https://user-images.githubusercontent.com/113289112/202914874-aeaa0457-c9e4-4ec8-a303-35a0684d7fd6.png)
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.82

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

120GB

### What happened?

If I proceed to boot Fedora Silverblue 37 with GPT and UEFI Mode, it fails to boot. Secure boot disabled.

**Comment by ventoy** [comment]
Please checksum the ISO file firstly. refer: #1955

**Comment by Thv1337** [comment]
> Please checksum the ISO file firstly. refer: #1955
Yes, that was it. I'm sorry.
