### ISSUE TITLE
[issue]:  Could not identify the process(es) or service(s) accessing \Device\Harddisk1\DR6

### ISSUE THREAD

**Issue by mirzayaky** [ventoy/Ventoy#1972]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.82

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

64

### Disk Manufacturer

KingstonDTSE9

### Image file checksum (if applicable)

Yes.

### What happened?

[log.txt](https://github.com/ventoy/Ventoy/files/10050436/log.txt)

**Comment by ventoy** [comment]
Your USB stick has a name `USB2.0 DISK 64GB`
In the log it said `### [Check Fail] The data write and read does not match`

These all indicate that your USB is fake or faulty.
Please refer:
https://www.ventoy.net/en/doc_fake_usb.html#

#1750 
#1730 
#1663 
#1486 
#1479 
#1191

**Comment by ksz00** [comment]
Update: My usb stick is Sandisk usb 3.2Gen1 32GB

**Comment by ksz00** [comment]
Update iso now working
