### ISSUE TITLE
[issue]: 

### ISSUE THREAD

**Issue by yeshivish** [ventoy/Ventoy#1979]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.82

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

128

### Disk Manufacturer

SP silicon power

### What happened?

I cannot copy files to the USB, but aside from It work fine I can to use the iso, and start programs all as usual.

I tried to format using windows, rufus, ultra iso, and also aomei-partition-assistant and it's failed

I checked in disk management and the USB is online.

when I try to install I get an error 
![image](https://user-images.githubusercontent.com/96909062/204108345-d81945b2-d58e-4a62-920f-e70fe8be8e1c.png)

[log_2.txt](https://github.com/ventoy/Ventoy/files/10096980/log_2.txt)

my USB is OFFICIAL https://www.silicon-power.com/web/us/product-Jewel_J80

**Comment by ventoy** [comment]
From the log it said you have an old Ventoy installed in the USB  (1.0.81), right ?
Can you still boot into the Ventoy 1.0.81 now?

**Comment by yeshivish** [comment]
no, I check after that on the new version...

**Comment by ventoy** [comment]
What happen when you try to copy file to the USB stick?

**Comment by ventoy** [comment]
Since you can still boot into the USB, you can put the Ventoy-LiveCD iso file to the USB and reboot your computer and select the ISO file to boot.
Then re-intall Ventoy when you boot into the Ventoy Live CD.
https://www.ventoy.net/en/doc_livecd.html

**Comment by yeshivish** [comment]
There is 3 way that showed up in this manual, the first is rufus but I already sad that It's failed, second way is to format and copy but I can't format, Install or copy anything.
but maybe I didn't understand you?

**Comment by yeshivish** [comment]
O.K. I will try and update...

**Comment by yeshivish** [comment]
I am getting tired of this and I simply send my USB to my warranty..
thanks for the great help and fast respond...
