### ISSUE TITLE
vantoy.json not working

### ISSUE THREAD

**Issue by ronen1n** [ventoy/Ventoy#198]
I tried several places and the theme and unattended files don't work for me
What am I doing wrong?

https://i.imgur.com/DE8NhvY.png

**Comment by Atari800XL** [comment]
You didn't forget to update the Ventoy version on the USB, did you?

**Comment by ronen1n** [comment]
I have the 1.0.12 version (the latest)

**Comment by mrash44** [comment]
your missing the opening bracket. Your ventoy.json file should start like this:
{
    "theme" : [

**Comment by ronen1n** [comment]
@mrash44 It didn't help
This site fixed the code for me https://jsonformatter.curiousconcept.com/ 
Thank you all

`{
   "theme":{
      "file":"/ventoy/theme/Stylish/theme.txt"
   },
   "auto_install":[
      {
         "image":"/ISO/Win2004H.iso",
         "template":[
            "/ventoy/script/NoWipeDriveMBRautounWin10Pro.xml",
            "/ventoy/script/NoWipeDriveUEFIautounWin10Pro.xml",
            "/ventoy/script/WipeDriveMBRautounWin10pro.xml",
            "/ventoy/script/WipeDriveUEFIautounWin10pro.xml"
         ]
      }
   ]
}`
