### ISSUE TITLE
Windows BSOD while trying to install Ventoy

### ISSUE THREAD

**Issue by ManuaL46** [ventoy/Ventoy#1980]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.82

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

16

### Disk Manufacturer

SanDisk

### What happened?

Hi, I am very new to ventoy and I wanted to create a multiboot USB with my San Disk 16GB Cruzer Blade. I installed the application from the ventoy site and when I try to install it, it causes a BSOD error. The drive did have a OS flashed on it before, but I even formatted and tried again and it still crashes with the same reason.

I am using Windows 11 22H2 and Ventoy-1.0.82-windows version. I also tried it with Yumi which was using a 1.0.78 but still got the same issue

The BSOD error I get is related to CLASSPNP.SYS.

I checked the minidump and I think it's saying it had issues with the partition manager.

**Comment by ventoy** [comment]
Try other install methods here ==> https://www.ventoy.net/en/doc_ventoy2disk.html

**Comment by ManuaL46** [comment]
> Try other install methods here ==> https://www.ventoy.net/en/doc_ventoy2disk.html

Hi,
Thanks for the suggestion. This helped a lot and was able to fix the issue I was having.
