### ISSUE TITLE
[issue]: USB not being detected at all after Ventoy

### ISSUE THREAD

**Issue by MagicznyJestem** [ventoy/Ventoy#1981]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.82

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

8GB

### Disk Manufacturer

IDK

### Image file checksum (if applicable)

No.

### Image file download link (if applicable)

revi.cc

### What happened?

[log.txt](https://github.com/ventoy/Ventoy/files/10098760/log.txt)
After using Ventoy my usb isn't being detected at all even by windows.

**Comment by ventoy** [comment]
1. Your USB stick has a name `General UDisk 8GB`
2. In the log it said `### [Check Fail] The data write and read does not match`
These indicate that your USB stick maybe fake/faulty.

https://www.ventoy.net/en/doc_fake_usb.html

There are many similar reports before, please refer:
#1750
#1730
#1663
#1486
#1479
#1191

**Comment by wiz64** [comment]
it happens a few times. A few years ago similar stuff happened with me on a 16gb flash drive, with Rufus, tried countless formatting tools, its dead forever. Just get another one, they are cheaper these days. Hardware issue, Ventoy not responsible.
or try low level formatting tools...

**Comment by HuySky009** [comment]
> ### Official FAQ
> * [x]  I have checked the official FAQ.
> 
> ### Ventoy Version
> 1.0.82
> 
> ### What about latest release
> Yes. I have tried the latest release, but the bug still exist.
> 
> ### Try alternative boot mode
> Yes. I have tried them, but the bug still exist.
> 
> ### BIOS Mode
> Both
> 
> ### Partition Style
> GPT
> 
> ### Disk Capacity
> 8GB
> 
> ### Disk Manufacturer
> IDK
> 
> ### Image file checksum (if applicable)
> No.
> 
> ### Image file download link (if applicable)
> revi.cc
> 
> ### What happened?
> [log.txt](https://github.com/ventoy/Ventoy/files/10098760/log.txt) After using Ventoy my usb isn't being detected at all even by windows.

https://github.com/ventoy/Ventoy/issues/1981#issue-1465508123

**Comment by userosos** [comment]
> it happens a few times. A few years ago similar stuff happened with me on a 16gb flash drive, with Rufus, tried countless formatting tools, its dead forever. Just get another one, they are cheaper these days. Hardware issue, Ventoy not responsible.

It an new devices. I can see it in other software wo problems.

**Comment by userosos** [comment]
> or try low level formatting tools...

Ok, I will test it.

**Comment by userosos** [comment]
> > or try low level formatting tools...
> 
> Ok, I will test it.

It not work.
I can see that SD Memory Card Formatter for Windows not see the usb flash too. But windows and UltraISO can see the flash OK, I think that it not classics USB flash. May be inside it has SSD?
