### ISSUE TITLE
[issue]: Failed to load image: Unsupported with Secure Boot support enabled

### ISSUE THREAD

**Issue by nyf9b** [ventoy/Ventoy#1982]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.82

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

16GB

### Disk Manufacturer

SanDisk

### What happened?

I have the same error as #1735 and #1707. I have tried Ventoy 1.0.79, 1.0.80... and every version gives the same error. 

My PC have a "generic" firmware (BIOS), but I don't think that it's incompatible with MOK, because I use it with Linux distros like Ubuntu and it flavours.

**Comment by ventoy** [comment]
The shim and mok used by Ventoy are from Fedora 37.
So maybe the mok is incompatible in your computer.

**Comment by qualk** [comment]
Could you post your mobo model and current BIOS version?

**Comment by nyf9b** [comment]
> The shim and mok used by Ventoy are from Fedora 37. So maybe the mok is incompatible in your computer.

The MOK (key) or the mokutil?
On the second case: unlikely, because I can "invoke" MOK on the terminal (mokutil --import) in Fedora 37, but I don't know if there's any diff.

![IMG_20221128_004455_829](https://user-images.githubusercontent.com/117118559/204190471-8b543fdd-f5b6-4487-8153-512b2c382192.jpg)


> Could you post your mobo model and current BIOS version?

Generic MOBO. GoLine GL-H61-MA (socket 1155)

**Comment by ventoy** [comment]
You can refer: https://bugzilla.redhat.com/show_bug.cgi?id=2113005

**Comment by nyf9b** [comment]
Fixed. https://ask.fedoraproject.org/t/f37-install-media-dont-boot-in-uefi-mode-on-certain-motherboards/28364

Thank you!

**Comment by autodeck** [comment]
> Fixed. https://ask.fedoraproject.org/t/f37-install-media-dont-boot-in-uefi-mode-on-certain-motherboards/28364
> 
> Thank you!

That worked for me too - copying the BOOTX64.EFI as per the forum post. 

This is an issue on 1.0.81 & 2 - will it be fixed in a later version?

**Comment by Silexium** [comment]
> > Fixed. https://ask.fedoraproject.org/t/f37-install-media-dont-boot-in-uefi-mode-on-certain-motherboards/28364
> > Thank you!
> 
> That worked for me too - copying the BOOTX64.EFI as per the forum post.
> 
> This is an issue on 1.0.81 & 2 - will it be fixed in a later version?

Shim was recently updated to 15.7, which fixed the issue. Maybe it can be included in 1.0.83+?
