### ISSUE TITLE
有几率花屏

### ISSUE THREAD

**Issue by ltgentoo** [ventoy/Ventoy#2]
win10 1903和asus winpe这两个iso都出现过，但不是100%出现
机器是乞丐版thinkpad t460，最大分辨率是1366x768

**Comment by ventoy** [comment]
你说的花屏是指Ventoy的启动菜单画面还是启动ISO之后的画面，下次出现的话劳烦截个图看下，多谢！

**Comment by ltgentoo** [comment]
> 你说的花屏是指Ventoy的启动菜单画面还是启动ISO之后的画面，下次出现的话劳烦截个图看下，多谢！

是在启动iso之后花屏，这个好像和bios设置有关，我重置bios设置之后，不再花屏了
![Uploading IMG_20200409_164002.jpg…]()
