### ISSUE TITLE
[issue]: 丢失全部的 UEFI 引导项

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#2004]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.82

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128GB

### Disk Manufacturer

Sandisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://fydeos.com/download/

### What happened?

A bug happened!
我用 Ventoy 成功启动 fydeOS的 .img，并未进行安装操作，只是 Live 一下就关机。
关机，拔掉 U盘，重启以后，发现 先前的 UEFI 引导项 （Windows Boot Manager 和 UEFI grub）全部丢失，就好像 重置了 NVRAM 一样。

无法进入系统。

又得 F2，进入 BIOS Setup，手动选择 EFI分区中的 .efi 文件 添加引导项并命名。

有办法 live 体验 .img 但不丢失全部的 UEFI 引导项吗？

**Comment by ventoy** [comment]
这个和Ventoy没有关系，我也不了解，建议你去FydeOS社区咨询。
