### ISSUE TITLE
[issue]: fydeOS安装程序提示：“该磁盘没有EFI分区”。

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#2005]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.82

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128GB

### Disk Manufacturer

Sandisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://fydeos.com/download/

### What happened?

A bug happened!
Ventoy 按 F2——browser，选择 内置硬盘 sda2 分区上的 fydeos的 .img镜像包。

进入系统后，用引导程序安装到 sda3分区，但选择EFI分区sda1时，提示：“该磁盘没有EFI分区”。

似乎，Ventoy启动 fydeos时，屏蔽了 .img文件所在的磁盘上的EFI分区，导致无法下一步安装。

但是 启动 manjaro的 iso时，并未 屏蔽 .iso 文件所在的磁盘上的 EFI分区，可以安装成功。

**Comment by ventoy** [comment]
Ventoy最多影响的是img文件所在的那个分区，同一个磁盘上的其他分区不会影响，建议你去FydeOS社区咨询。
