### ISSUE TITLE
[Success Image Report]: Ubuntu 22.10

### ISSUE THREAD

**Issue by dmitrygribenchuk** [ventoy/Ventoy#2012]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.82

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

ubuntu-22.10-desktop-amd64.iso

### Image file checksum type

SHA1

### Image file checksum value

db151e49fd2a8f92dded9a66d808c272568f919d

### Image file download link (if applicable)

https://releases.ubuntu.com/22.10/ubuntu-22.10-desktop-amd64.iso

### Test environment

Lenovo E14 Gen2 (AMD)

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
