### ISSUE TITLE
[Success Image Report]: Clonezilla 3.0.2-21

### ISSUE THREAD

**Issue by dmitrygribenchuk** [ventoy/Ventoy#2013]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.82

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

clonezilla-live-3.0.2-21-amd64.iso

### Image file checksum type

SHA1

### Image file checksum value

7c2b4e458bb833a1057249290fdd723f774f97ab

### Test environment

Lenovo E14 Gen2 (AMD)

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
