### ISSUE TITLE
[issue]: F6:ExMenu doesn't work

### ISSUE THREAD

**Issue by kbdharun** [ventoy/Ventoy#2026]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.84

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

16GB

### Disk Manufacturer

Sandisk

### Image file checksum (if applicable)

None

### What happened?

When I press the F6 key anywhere it doesn't work when I am inside the menu for choosing modes and Esc don't bring me back to the main grub menu. When I try to press F6 in the main menu it gives this error.

```bash
ventoy_grub.cfg NOT exist.

press ENTER to exit ...
```

**Comment by ventoy** [comment]
You need to prepare `ventoy_grub.cfg` by your self.
https://www.ventoy.net/en/plugin_grubmenu.html
