### ISSUE TITLE
[issue]: 二级启动菜单无法返回上级

### ISSUE THREAD

**Issue by danielesk** [ventoy/Ventoy#2027]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.84

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Image file checksum (if applicable)

None

### What happened?

二级菜单无法返回上级菜单；

![secondary_menu1](https://user-images.githubusercontent.com/10652829/205483167-c246d77f-f80b-4ff7-8f19-6f10556b8baf.png)

**Comment by ventoy** [comment]
二级启动菜单不是普通的菜单，进入二级启动菜单的时候，启动工作已经完成了一大半了，这个时候不能返回了。

**Comment by ventoy** [comment]
最新的 1.0.87版本增加了此功能。
