### ISSUE TITLE
Ventoy-8cde5a4 is not among your listed versions?

### ISSUE THREAD

**Issue by alice-quixote-dent** [ventoy/Ventoy#203]
I got it from SourceForge,who I trust, but now I am worried something was spoofed.  TBH, I worry a lot,though.  I have a folder named /ventoy/ventoy--Ventoy.  I deleted the. tar automatically. must untick that option
. 
/ventoy-Ventoy-8cde5a4  Also, it has a LOT more folders than the install vid I watched showed.  It is already in Grub, and I only unpacked it.

I will not be rebooting any time soon.

Ventoy-8cde5a4  Thanks in advance.  I got nothing from a bing search thou

![ventoy-phony-maybe](https://user-images.githubusercontent.com/61720040/83933277-edb2c500-a75b-11ea-80f7-0171edbaf5e0.png)

![is this-right](https://user-images.githubusercontent.com/61720040/83933284-fefbd180-a75b-11ea-8b62-d637a36ebc34.png)

**Comment by ventoy** [comment]
It should be ventoy-1.0.12 
![image](https://user-images.githubusercontent.com/59477474/83933463-42e1eb80-a7db-11ea-947c-c3d6a2074774.png)

**Comment by alice-quixote-dent** [comment]
Thank you so much!  I will get rid of it and run the install package.  I wish I had opened it with Synaptic, somehow.
