### ISSUE TITLE
[issue]: Disk Partition Structure (for v1.84) 

### ISSUE THREAD

**Issue by abdullah-erturk** [ventoy/Ventoy#2031]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.84

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

16GB

### Disk Manufacturer

Kingston

### Image file checksum (if applicable)

None

### What happened?

For v1.84 correctly working partition structure preferences are only exFAT and UDF, the result of other preferences is exFAT every time.

**Comment by ventoy** [comment]
The format operation is at the end of the install process.
That is to say, the partition is formated in exFAT by default, and then if you select NTFS/FAT32/UDF then it will call Windows API to format it again at the end.
So there may be some failure when format it at the end.
Upload your `log.txt` file here for analyze.

**Comment by abdullah-erturk** [comment]
[log.txt](https://github.com/ventoy/Ventoy/files/10148516/log.txt)

![Ventoy](https://user-images.githubusercontent.com/54866587/205491390-0a86aed5-25fa-4912-8ba4-fa0cb2bbf54c.gif)

**Comment by ventoy** [comment]
As I guessed, it format failed at the end of  the installation process.
Last it open diskpart and format it
```
select volume G
format FS=NTFS LABEL=Ventoy QUICK OVERRIDE
```

You can run these commands manually to see whether you can format it successfully.

**Comment by Vexz00** [comment]
> As I guessed, it format failed at the end of the installation process. Last it open diskpart and format it
> 
> ```
> select volume G
> format FS=NTFS LABEL=Ventoy QUICK OVERRIDE
> ```
> 
> You can run these commands manually to see whether you can format it successfully.

That worked fine.
Also for everyone interested in this solution: Yes, booting from ISOs after formatting to NTFS this way works also fine. Tried it with two indipendent USB drives.

**Comment by ventoy** [comment]
Please try 1.0.82 to see whether it can format to NTFS.

**Comment by ventoy** [comment]
@abdullah-erturk 
Please try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/3720691355
https://www.ventoy.net/en/doc_github_ci.html

**Comment by ventoy** [comment]
Try latest 1.0.85
