### ISSUE TITLE
[issue]: Partition table corruption due to upgrade error

### ISSUE THREAD

**Issue by ovrase** [ventoy/Ventoy#2036]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.84

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128G

### Disk Manufacturer

ORICO

### Image file checksum (if applicable)

None

### What happened?

Download the latest version, directly upgrade the version in the USB flash drive, try to upgrade again after reporting an error, and find that the partition table is lost and damaged.

![20221204234322](https://user-images.githubusercontent.com/22218428/205501060-f69e91b1-9834-44d7-b609-264efb935da2.png)

I had the same problem in 1.0.83, after repartitioning the disk all functions are normal.

[log.txt](https://github.com/ventoy/Ventoy/files/10148939/log.txt)

**Comment by ventoy** [comment]
Some process on your computer occupys the USB and prevent it to write.
So I suggest you use the following method to update your Ventoy USB stick and this way should always success.
https://www.ventoy.net/en/doc_fail_update.html

**Comment by ovrase** [comment]
Thanks, I'll try it out
