### ISSUE TITLE
[issue]: NTFS not installing, going back to exFAT

### ISSUE THREAD

**Issue by dziugas1959** [ventoy/Ventoy#2037]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.84

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

None

### What happened?

Using „Ventoy2Disk“ NTFS GPT, on an empty drive, clicking install. Shows that 
„Ventoy In Package“ – 1.0.84 NTFS, GPT
„Ventoy In Device“ – 1.0.84 NTFS, GPT
But if you close it, and reopen it, now it says 
„Ventoy In Package“ – 1.0.84 NTFS, GPT
„Ventoy In Device“ – 1.0.84 exFAT, GPT
and the main partition is for some reason in a cluster size of 128KB, even when it wasn't set like that in the configuration.

**Comment by ventoy** [comment]
Duplicate with #2031

**Comment by ventoy** [comment]
Please try 1.0.82 to see whether it can format to NTFS.

**Comment by ventoy** [comment]
@dziugas1959 
Please try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/3720691355
https://www.ventoy.net/en/doc_github_ci.html

**Comment by ventoy** [comment]
@dziugas1959 
Try latest 1.0.85

**Comment by dziugas1959** [comment]
Yes it did work, just forgot to update.
