### ISSUE TITLE
[issue]: 二级启动菜单 没有【返回主菜单】选项

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#2042]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.84

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

128GB

### Disk Manufacturer

Sandisk

### Image file checksum (if applicable)

None

### Image file download link (if applicable)

github

### What happened?

A bug happened!
二级启动菜单有【WIMBOOT】【GRUB2】【MEMDISK】【校验】，但是并没有【返回主菜单】。

😭😭😭不小心手抖，按了回车，选错了，就无法返回，非要关机重启。

希望，二级启动菜单可以添加【返回主菜单】选项。

**Comment by ventoy** [comment]
二级启动菜单不是普通的菜单（二级启动菜单是根据ISO文件不同会显示不同选项的），
进入二级启动菜单的时候，启动工作已经完成了一大半了，这个时候不能返回了。

**Comment by 1457384613gh** [comment]
那就增加一个提示。

“你确定要启动文件名为‘……’的镜像文件吗？”

【确认】【返回列表】

**Comment by ventoy** [comment]
最新版本已经新开发此功能。

**Comment by 1457384613gh** [comment]
Ahhhaaaaaaaa!
