### ISSUE TITLE
[Success Image Report]: antiX-22 x64 (Full) on an IA-32 UEFI device

### ISSUE THREAD

**Issue by olofolleola4** [ventoy/Ventoy#2048]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.84

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

antiX-22_x64-full.iso

### Image file checksum type

SHA256

### Image file checksum value

579b29b0d9047d1a2ca914a0c4b09ef93c04035f620fdaeb4356f5b5fef1a60a

### Image file download link (if applicable)

https://sourceforge.net/projects/antix-linux/files/Final/antiX-22/antiX-22_x64-full.iso/download

### Test environment

Acer Iconia Tab 8 W (W1-810)

### More Details?

This image file booted successfully in Ventoy on an IA-32 UEFI device.
Should be added here: https://ventoy.net/en/doc_ia32.html

**Comment by ventoy** [comment]
Thanks!
