### ISSUE TITLE
[Success Image Report]: Parted Magic 2022_11_20

### ISSUE THREAD

**Issue by rmolina** [ventoy/Ventoy#2051]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.84

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

pmagic_2022_11_20.iso

### Image file checksum type

SHA256

### Image file checksum value

d555a5b3c8399b4eb46cd5f9e6ad4c5f25f8085ead0d90f983754215c45062ff

### Test environment

OptiPlex 3040 SFF

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
