### ISSUE TITLE
[Success Image Report]: Redo Rescue (aka Redo Backup) v4.0.0

### ISSUE THREAD

**Issue by rmolina** [ventoy/Ventoy#2052]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.84

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

redorescue-4.0.0.iso

### Image file checksum type

SHA256

### Image file checksum value

38190c56b2cc458f949b6c66a3f86e46f102fe27fa726d4f1cf3321a7cbce1c3

### Image file download link (if applicable)

https://sourceforge.net/projects/redobackup/files/redorescue-4.0.0.iso

### Test environment

OptiPlex 3040 SFF

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!

**Comment by drw2005** [comment]
启动不了arm64架构的
