### ISSUE TITLE
[Success Image Report]: Rescuezilla v2.4.1

### ISSUE THREAD

**Issue by rmolina** [ventoy/Ventoy#2053]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.84

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

rescuezilla-2.4.1-64bit.jammy.iso

### Image file checksum type

SHA256

### Image file checksum value

c8a3b3877eb46c256fe70efc1dfba75b35780687a3e5a172ef201ba660b5b867

### Image file download link (if applicable)

https://github.com/rescuezilla/rescuezilla/releases/download/2.4.1/rescuezilla-2.4.1-64bit.jammy.iso

### Test environment

OptiPlex 3040 SFF

### More Details?

This image file booted successfully in Ventoy (using the Graphical fallback mode).

**Comment by ventoy** [comment]
Thanks!
