### ISSUE TITLE
[Success Image Report]: Windows 10 22H2 (Spanish, x64)

### ISSUE THREAD

**Issue by rmolina** [ventoy/Ventoy#2054]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.84

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

Win10_22H2_Spanish_x64.iso

### Image file checksum type

SHA256

### Image file checksum value

254eb069827e48e76168e30676928bd6c68105101dc8db4ae6149f9a8b4ef17d

### Test environment

OptiPlex 3040 SFF

### More Details?

This image file booted successfully in Ventoy (using WIMBOOT mode for Legacy BIOS mode).

**Comment by ventoy** [comment]
Thanks!
