### ISSUE TITLE
[Success Image Report]: Windows 11 22H2 (Spanish, x64)

### ISSUE THREAD

**Issue by rmolina** [ventoy/Ventoy#2055]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.84

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

Win11_22H2_Spanish_x64v1.iso

### Image file checksum type

SHA256

### Image file checksum value

2ac6a7b2da30937fb435c71945be2dbb0cd1b6768850ce9fec61aff8e727e15a

### Test environment

OptiPlex 3040 SFF

### More Details?

This image file booted successfully in Ventoy (using WIMBOOT mode for Legacy BIOS mode).

**Comment by ventoy** [comment]
Thanks!
