### ISSUE TITLE
[Feature Request]: Show `Return to previous menu` on the Secondary Boot Menu

### ISSUE THREAD

**Issue by wh201906** [ventoy/Ventoy#2057]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.84

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### Image file checksum (if applicable)

None

### What happened?

Hi there. This is just a feature request. Could you please add `Return to previous menu` in the Secondary Boot Menu?
I think the secondary boot menu should look like this:
![图片](https://user-images.githubusercontent.com/62299611/206766510-2e37cc81-069c-4d89-b5c3-177d68a8bcc0.png)

请问可以在二级启动菜单当中添加返回到上级菜单的选项吗？

**Comment by wh201906** [comment]
I tried to add it but it doesn't work. I have few knowledge of grub and I think my code is buggy.
https://github.com/wh201906/Ventoy/commit/76074a3d5aae267db8fff47216ab97bb7ce0a8a4
Plus, all function keys don't work in the secondary boot menu.
![图片](https://user-images.githubusercontent.com/62299611/206767306-e2ec0636-6d1b-42f7-bcf7-7a4b03e28dc3.png)

**Comment by ventoy** [comment]
That's designed so.
The secondary boot menu is part of the boot process and we can not return from secondary boot menu.
Once the secondary boot menu is shown, we can do nothing but continue to boot the ISO file.

**Comment by steve6375** [comment]
That is not true - you could, for instance, reload Ventoy (grub2) again?

**Comment by wh201906** [comment]
> we can do nothing but continue to boot the ISO file.

How about these function keys?
![图片](https://user-images.githubusercontent.com/62299611/206767306-e2ec0636-6d1b-42f7-bcf7-7a4b03e28dc3.png)

**Comment by wh201906** [comment]
> That is not true - you could, for instance, reload Ventoy (grub2) again?

I wonder how to reload Ventoy again

**Comment by steve6375** [comment]
Menu entry in secondary menu could just reload grub2

**Comment by wh201906** [comment]
> Menu entry in secondary menu could just reload grub2

I'm not familiar with grub2. Could you please tell me what should I do to reload it?

**Comment by steve6375** [comment]
Ventoy code will need to be changed

**Comment by wh201906** [comment]
> Ventoy code will need to be changed

I got it.

**Comment by wh201906** [comment]
@ventoy 
Could you please add a function key to reload Ventoy(grub2)?
请问可以添加一个快捷键或者是菜单项重新加载Ventoy(grub2)吗？这样也相当于返回上级菜单重选ISO镜像

**Comment by ventoy** [comment]
It's not so simple to reload Ventoy(grub2) as we thought.
There are a lot of details to deal with.
For example, grub2 reserve amount of some memory in UEFI mode for boot usage.
If we don't free these reserved memory we will get memory leak.

That's the same when chainloading Ventoy(grub2) from another grub2.

So, officially Ventoy doesn't support to be chainloaded from another grub2 (including itself).

**Comment by wh201906** [comment]
I got it. Thanks!

**Comment by steve6375** [comment]
what about just reload  /grub/grub.cfg  using configfile?

**Comment by ventoy** [comment]
Ventoy has some global settings that can not run more than once. So can not configfile again.
Reboot option is no need I think, we can press `ctrl+alt+delete`

**Comment by ventoy** [comment]
Added in the latest release 1.0.87

**Comment by wh201906** [comment]
Thanks!
