### ISSUE TITLE
[issue]: lIVECD VENTOY

### ISSUE THREAD

**Issue by Loogosh** [ventoy/Ventoy#2058]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.84

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

16GB

### Image file checksum (if applicable)

None

### What happened?

Good afternoon I want to make a livecd iso image for vento so that I can run vento through my floppy disk emulator 
 but I can't find or make such an image in any way, I can't find the boot file, could you help me with advice?

**Comment by ventoy** [comment]
Ventoy does not support booted through floppy or cdrom.
Ventoy can only be installed on a hdd.
