### ISSUE TITLE
引导usm.iso后 加载不了外置工具

### ISSUE THREAD

**Issue by LittleDeng1** [ventoy/Ventoy#206]
见视频
https://littledeng.cowtransfer.com/s/c40a026cdf8e45

![15915146984528797012887895357827](https://user-images.githubusercontent.com/62782358/83962809-13aea580-a8d3-11ea-954b-57c973c0fb3b.jpg)
不是U盘 一个nvme一个sata 都转接USB

USM版本是 v6.0.2020.0518S

**Comment by ventoy** [comment]
USM从5月30日的版本开始正式支持Ventoy，请更新到最新的USM版本使用。
（注：支持Ventoy的USM版本生成的ISO文件根目录下有一个 ventoy.dat文件）
