### ISSUE TITLE
【全局控制插件】添加【硬盘过滤】

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#2060]
【全局控制插件】添加【硬盘过滤】功能。

- 0，不过滤任何硬盘
- 1，过滤内置硬盘，不安装操作系统，仅 live体验镜像
- 2，过滤Ventoy所在硬盘，防止安装系统时对外置硬盘进行读写，破坏VTOYEFI等数据。

**Comment by ventoy** [comment]
这个想法太理想化了，这个实现不了。
Ventoy属于引导工具，而系统启动之后，磁盘驱动是系统自己的，不会再受引导工具的影响，Ventoy无法对其进行过滤。

**Comment by 1457384613gh** [comment]
传递参数的时候，
不传递那块硬盘的参数不行吗？

**Comment by 1457384613gh** [comment]
既然可以屏蔽 iso文件所在的分区，那为什么不能屏蔽 iso文件所在的磁盘呢？

**Comment by ventoy** [comment]
Ventoy并没有屏蔽ISO文件所在的分区，在系统下还是能看到这个分区的，只是默认情况下不能挂载这个分区。
但是系统下还是可以对整个磁盘重新分区格式化的，这个阻止不了。

**Comment by ventoy** [comment]
这个和传递参数没关系，没有参数会影响系统下识别或不识别某个硬盘。

**Comment by 1457384613gh** [comment]
那，能不能设置，不能挂载 iso文件所在的磁盘的所有分区呢？

**Comment by 1457384613gh** [comment]
- 0，禁止挂载 .iso文件所在的分区
- 1，禁止挂载 内置硬盘所有分区，仅live体验镜像，防止内置硬盘被改动。
- 2，禁止挂载 VTOYEFI所在的存储介质的所有分区，安装系统是用，防止 VTOYEFI等数据被改动。

**Comment by ventoy** [comment]
这个没必要，而且这个阻止挂载只对Linux系统有效，Windows和Unix都无效。
同时某些情况下Ventoy自己也需要挂载VTOYEFI分区。
另外，Live环境下很多时候也需要访问本地硬盘的分区。

**Comment by 1457384613gh** [comment]
主要是针对 Android x86的 iso。
总是把 USB设备挂载成 SD卡。

移动硬盘的每个分区都创建了 <Android> <Alarms> <Audiobooks> <DCIM> <Documents> <Downloads> <Movies> <Music> <Notifications> <Pictures> <Podcast> <Recordings> <Ringtones> 这些文件夹。

我 VTOYEFI后面有5个分区，5个分区都有，唯独前方的 Ventoy分区禁止挂载很成功，没有这些文件夹。又要手动删，而且 VTOYEFI分区里也有这些文件夹。

Android x86是基于 Linux内核的，禁用挂载是有效的。

想在 live Android x86 的同时 禁止挂载 VTOYEFI所在的磁盘的所有分区，的确有必要。

**Comment by 1457384613gh** [comment]
而且，外置硬盘 会有 和 内置硬盘 相同卷标 的 分区，万一 自己手抖，弄错了呢？？？
添加一个【选择性禁止挂载 VTOYEFI 所在存储介质 的所有分区的功能】是有必要的。

Linux好像有只读挂载的功能。

改成只读挂载都可以。

既然是放在 USB设备里的文件，就是需要慎重处理的。

或者添加【只读挂载 VTOYEFI 所在存储介质 的所有分区的功能】Read-Only的那种，没有权限 删除或者修改的那种。

**Comment by ventoy** [comment]
Ventoy启动时只会关注ISO文件所在的那个磁盘，其他盘不会关注，包括他们什么时候初始化OK，什么时候能在系统内看到这些盘等，这些都不关心。因此Ventoy没法对其他盘做这个动作。如果只对ISO文件所在盘做的话并不彻底，其他盘还是会有这些问题。

这种最好的方法应该是从 `如何禁用XXX Linux系统启动后自动挂载本地硬盘分区` 这个角度入手。
一般通过设置某个选项，或者通过什么特殊配置等，是可以禁用这个自动挂载功能的。当然这个因系统而异。
这样就可以通过`文件注入插件`在合适的位置插入脚本，使得这个脚本能在启动开始时被调用，然后在脚本内设置就可以了。
