### ISSUE TITLE
给chromiumOS的 .img的镜像添加【二级启动菜单】

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#2061]
给chromiumOS的 .img的镜像添加【二级启动菜单】。（chromeOS Flex/FydeOS）
U盘刻录镜像后启动，在登录账户之前，有【安装】选项。（可能与syslinux中的引导文件有关）
直接从硬盘中启动的，被当作安装好了，没有安装选项。（可能与boot中的引导文件有关）

【二级启动菜单】
- 硬盘模式
- U盘模式
- 校验

**Comment by ventoy** [comment]
`U盘刻录镜像后启动，在登录账户之前，有【安装】选项`  
这个截个图看看。

**Comment by 1457384613gh** [comment]
![image](https://user-images.githubusercontent.com/69227436/207015884-a0d6e0d9-2c13-4ab4-9508-f1777732da8f.png)

FydeOS 也有类似的界面，暂时没在互联网上找到这张图片。

**Comment by ventoy** [comment]
目前来看，这个Ventoy实现不了。
这个不是启动参数决定的，而是系统启动之后根据当前启动的设备文件来判断决定的。
Chrome OS启动之后会判断当前是从什么设备启动的，是U盘、可移动设备还是本地硬盘等等。
由于Ventoy启动的机制和直接烧录到U盘启动是不一样的，对应的启动设备也不一样，一个是普通的  /dev/sda  /dev/sdb 这种，一种是 /dev/dm-X 这种。因此系统内不把从Ventoy启动当成普通的从U盘启动，就不会有这里的选项。

**Comment by 1457384613gh** [comment]
Ventoy可以传递参数啊，更改传递参数呢？

**Comment by 1457384613gh** [comment]
不能模拟一个假的 /dev/dm-X 吗？

**Comment by ventoy** [comment]
烧录到U盘启动，是 /dev/sda  /dev/sdb 这种，使用Ventoy启动时， /dev/sda  /dev/sdb 仍然存在，但是Ventoy会新增一个 /dev/dm-X设备，系统实际上是从/dev/dm-X上启动的。你没办法造假让系统检查时仍然能认为系统是从 /dev/sda  /dev/sdb 这种设备上启动的。根文件系统的挂载关系是早不了假的。当然理论上你可以改系统里面的检查软件，但这样就太麻烦了。
而且我也不知道需要改哪些地方。

**Comment by 1457384613gh** [comment]
Got it！
