### ISSUE TITLE
[issue]: Holo ISO

### ISSUE THREAD

**Issue by AceSardonyx** [ventoy/Ventoy#2066]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.84

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

256

### Disk Manufacturer

Samsung

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

http://holoiso.itsvixano.me/HoloISO_4.0_OfflineInstaller-20221211_1636-x86_64.iso

### What happened?

My USB is fine, there is just an issue when I try to use Holo ISO, a fork on SteamOS
It just doesn't boot in grub2 mode which I need it to for the device I want to install it on.

```
error: Unsupported chunk list
.
error: image chunk is null
.
ventoy not ready
chain empty failed
press Enter to continue ......
_
```
I will boot it nornally for now which does work but man I sure do love using ventoy 😻

**Comment by ventoy** [comment]
Please checksum the ISO file as follows and upload your screenshot here:
![filechecksum](https://user-images.githubusercontent.com/59477474/208033509-17c516ff-0ea7-4768-9051-55561b8f55a7.gif)

**Comment by ventoy** [comment]
ISO file: HoloISO_4.0_OfflineInstaller-20221211_1636-x86_64.iso 
Ventoy: 1.0.84

I have tested the above ISO file on my laptop and it boot OK in both Legacy BIOS mode and UEFI mode.
