### ISSUE TITLE
[Success Image Report]: Nobara 36 Official

### ISSUE THREAD

**Issue by notjl** [ventoy/Ventoy#2072]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.84

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

 Nobara-36-Official-2022-12-05.iso

### Image file checksum type

SHA256

### Image file checksum value

0d8abe36d2f7c463107bb8a63c4f7851eed81bf080d21f6b2528c7830b20b3fa

### Image file download link (if applicable)

https://nobaraproject.org/download-nobara/#

### Test environment

ASUS FX505DT Laptop

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
