### ISSUE TITLE
[issue]: VentoyPlugson.exe does not accept lowercase drive letter

### ISSUE THREAD

**Issue by steve6375** [ventoy/Ventoy#2078]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.85

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

128gb

### Disk Manufacturer

sandisk

### Image file checksum (if applicable)

None

### What happened?

Two issues:

font file is "\ventoy\themes\ascii.pf2"
USB drive is formatted as **NTFS**.

1. When specifying path for font, **k:**\ventoy\themes\ascii.pf2 is not accepted - i.e. lowercase drive letter is not accepted as valid path.

2. However,  K:\ventoy\themes\ascii.**PF2**  and **.pF2** is accepted - i.e. case of extension is wrong but this is accepted.

![image](https://user-images.githubusercontent.com/1469350/208632686-9d7712a9-7d36-434d-9d58-0834882b1ced.png)

GUI does not mention drive letter is case sensitive and does not warn user that they should check path and filename for case sensitivity.

**Comment by ventoy** [comment]
Q1: I will fix it soon.

Q2: In Windows, by default file path is case insensitive, so you can input file path in lower/upper case. But for NTFS Ventoy will automatically use the right case in ventoy.json. So you can preview the json content or see the ventoy.json file, the path in the json is right.

**Comment by steve6375** [comment]
Q2 - yes you are right - but I can add multiple entries all with different cases - which is a bit confusing
            "/ventoy/themes/ascii.pf2",
            "/ventoy/themes/ascii.pf2",
            "/ventoy/themes/ascii.pf2"

**Comment by ventoy** [comment]
Q1 has been fixed.
And also I add check for the duplicate path in different case.

Reload will make the implement a little complex and most of the users only use VentoyPlugson and don't manually edit json file at the same time.
So I will not add reload feature now. Just close the exe before you manually edit the json file.

For `ventoy_left/ventoy_top/ventoy_color` , I hope users leave this information, so I don't add it in the Web page :)
If you want, just edit the json file manually. If these options are already in the json file before you run the exe, then Plugson will load them and will not change them.

**Comment by ventoy** [comment]
Fixed in 1.0.86
