### ISSUE TITLE
[issue]: Black screen in boot manager, but can boot from inside bios

### ISSUE THREAD

**Issue by kindofabuzz** [ventoy/Ventoy#2082]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.84

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

128GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

None

### What happened?

I've tried installing it several times. GPT and MBR, secure and non secure. Tried with iso's on it and tired it with no iso's on it. Tried command line and gui, all have no luck. Install Ventoy, reboot, start hitting F12 to go into boot manager and I get a black screen with a flashing cursor. I can rebbot and actually go into bios and select it there and it works. Just doesn't work in boot manager. gigabyte aorus master z390 motherboard. Most current BIOS.

**Comment by ventoy** [comment]
You'd better take a video about the process.

**Comment by kindofabuzz** [comment]
[https://photos.app.goo.gl/TU5uTjjG2LgpHbtYA](url)

**Comment by ventoy** [comment]
As I know, press F12 will list a boot menu, and you can select to boot the USB.
So when you just press F12, it has not started to boot the Ventoy USB yet, I don't know why it black screen.

If you don't insert the USB, the F12 is OK? How it looks?

**Comment by kindofabuzz** [comment]
Just tested with another USB without Ventoy and it does the same thing. Sorry about that. Case closed. Now to figure out why it does that on my end.
