### ISSUE TITLE
[issue]: egrep: warning: egrep is obsolescent; using grep -E

### ISSUE THREAD

**Issue by kojq** [ventoy/Ventoy#2083]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.85

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

0 GB

### Image file checksum (if applicable)

None

### What happened?

Type `ventoy` into Linux CLI and the first output is:
`egrep: warning: egrep is obsolescent; using grep -E`
`egrep: warning: egrep is obsolescent; using grep -E`

This begins from GNU Grep 3.8 with part of documentation stating: egrep and fgrep were not standardized by POSIX and are no longer needed. In the current GNU implementation, egrep and fgrep issue a warning and then act like their modern counterparts; eventually, they are planned to be removed entirely.

**Comment by kojq** [comment]
The fix for the warnings look good, however, some other parts of the code use this.

```
SQUASHFS/squashfs-tools-4.4/squashfs-tools/build.sh
GRUB2/MOD_SRC/grub-2.04/install.sh
IMG/cpio/sbin/init
FUSEISO/build.sh
IMG/cpio/ventoy/hook/debian/porteus-path.sh
Ventoy/IMG/cpio/ventoy/loop/cloudready/ventoy-hook.sh
IMG/cpio/ventoy/loop/fydeos/ventoy-hook.sh
ExFAT/buidexfat.sh
IMG/cpio/ventoy/hook/tinycore/ventoy-disk.sh
IMG/cpio/ventoy/loop/openwrt/ventoy-disk.sh
LiveCD/VTOY/ventoy/ventoy.sh
```
There are also references with BusyBox. I suppose none of this matters due to your build environment?

**Comment by ventoy** [comment]
These scripts are not for users and will not run in your system. So it doesn't matter.

**Comment by kojq** [comment]
We can close this :+1: .
