### ISSUE TITLE
pfSense-CE-2.4.5-RELEASE-amd64.iso do not start

### ISSUE THREAD

**Issue by ZeroDot1** [ventoy/Ventoy#209]
First of all, this is a very useful tool, thanks to all developers involved.

pfsense /BSD Iso images unfortunately do not start.
Here is a screenshot.
![my_photo-1](https://user-images.githubusercontent.com/28985171/83978194-5a14fc00-a8f5-11ea-99f9-bf1327d23437.jpg)

**Comment by crasadure** [comment]
I think this problem solved ventoy v1.0.18 ...
You can try last version of ventoy..and you can close this issue

**Comment by ZeroDot1** [comment]
It works, thanks.
