### ISSUE TITLE
[Suggestion]: When displaying the "warning! not a standard ventoy device" error, do not continue booting and instead halt the boot (in a manner similar to if you try to boot a PC with no drives connected)

### ISSUE THREAD

**Issue by NintendoManiac64** [ventoy/Ventoy#2094]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.85

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

256GB

### Disk Manufacturer

Crucial (M4 2.5" SATA SSD)

### Image file checksum (if applicable)

None

### What happened?

Simply put, if/when ventoy displays the "warning! not a standard ventoy device" error, do not continue booting and instead halt the boot - this would then make the behavior similar to if you were to try to boot a PC with no storage drives connected or the like.

In particular, if you're trying to boot ventoy in order to do maintenance on a hard drive or the like, the last thing you want is for the PC to actually then boot into that hard drive which is exactly what happened to me with the current v1.0.85.

(basically, for whatever reason, ventoy didn't seem to get properly updated or something, resulting in that error being displayed and it then subsequently booted into the normal OS, causing 2 hours of maintenance progress needing to be redone)

**Comment by ventoy** [comment]
I have changed as follows: (https://github.com/ventoy/Ventoy/commit/4707022ef9664feff6ddb4a910e5c305429cb08d)
![image](https://user-images.githubusercontent.com/59477474/209266730-6eaf4132-047c-48f7-9d21-9ea02020e3a0.png)

**Comment by NintendoManiac64** [comment]
It seems silly to specifically include a "halt" option since it displaying that menu essentially works as a "halt"

I would instead suggest replacing it with a "shut down" option, though it could be argued that the order in that case should be:

1. exit grub
2. reboot
3. shut down

**Comment by ventoy** [comment]
Sounds reasonable.
I have changed it follows (https://github.com/ventoy/Ventoy/commit/12b51bcf090e80803e2bab681bb91ea52e327df3)
![image](https://user-images.githubusercontent.com/59477474/209417039-63964f57-aea5-4ba6-9a3d-566843e273fe.png)

**Comment by NintendoManiac64** [comment]
Looks good to me!

**Comment by ventoy** [comment]
Fixed in 1.0.86
