### ISSUE TITLE
[Feature request]: add option to choose default ISO to boot with delay (like GRUB menu)

### ISSUE THREAD

**Issue by alex-ie** [ventoy/Ventoy#2097]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.62

### What about latest release

No. I didn't try the latest release.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

64Gb

### Image file checksum (if applicable)

None

### What happened?

Great tool, thanks for developing it! I have an idea for improvement. 

Even when only one ISO file was left to choose from it did not boot w/out me selecting ISO file. I'd like to have (similar to GRUB /isolinux boot menu) to have option to select default ISO file and after delay let it boot. I understand implementing this in the interface might not be easy. Can you hint me how to modify grub/isolinux.cfg on VTOYEFI to add some path to ISO as default? Might simple modification of *.cfg achieve what I need? TIA 

Added: 
In grub.cfg I saw default_image process, I naively (I don't know well how GRUB works) set the variable from `if` line to name of one of ISO files on the disk; noted no changes during boot (to LEGACY).

**Comment by ventoy** [comment]
Ventoy already has  such options, please refer `VTOY_MENU_TIMEOUT` and `VTOY_DEFAULT_IMAGE` option in
https://www.ventoy.net/en/plugin_control.html

BTW, you use Ventoy 1.0.62 which is a fairly old release, you'd better update to latest release (1.0.85).

**Comment by ventoy** [comment]
If you are not familar with Ventoy's plugins.
Just run `VentoyPlugson.exe`, select the USB and click `start` then it will open a web page.
On the page, just click `Global Control Plugin` and find `VTOY_DEFAULT_IMAGE` option and set a file path, find `VTOY_MENU_TIMEOUT ` option and set an integer value.

https://www.ventoy.net/en/plugin_plugson.html

**Comment by alex-ie** [comment]
@ventoy Hi, thanks for prompt reply, Ventoy is really a great tool! I made it work as I wanted, I have some suggestions to improve even further for others: see below.

Solved ! :
On version 1.0.62 somehow it booted automatically but first image as sorted, not  image as wrote as default in json. So I followed you advice, upgraded to 1.0.86 [it was in downloads, so latest, but not 85]  by `-u` option, used `plugin_plugson` and after Ventoy loaded selected image was indeed one I wanted, but I saw additional screen waiting to select normal/grub2/checksum which negated my goal of unattended boot. That was quickly solved by noting `{ "VTOY_SECONDARY_BOOT_MENU": "1" }`.

Suggestions:
Add default image option to FAQ, explaining to add ventory.json to vetroy folder on partition where images are with image path and secondary menu timeout `VTOY_SECONDARY_TIMEOUT`. 

In README it was written to start `sudo sh VentoyPlugson.sh`, w/out `/dev/sdX` - add it as it saves newbie from reading notification that it needs to be added.

On that new `SECONDARY_BOOT_MENU` keys F1-help etc did not work. Worked in 1st menu, I booted my laptop in LEGACY mode. Now that is a bug IMO. Maybe you will be interested to tackle it.

Cheers again. Feel free to close the issue or leave open to track my suggestions.

**Comment by alex-ie** [comment]
https://www.ventoy.net/en/plugin_entry.html
> All the plugins and their related files must be in ventoy directory in the first partition of the disk (along with the iso files and created by yourself). Directory and file names are case sensitive. 

Seems confusing to me default image is done via "control" plugin when I've added no files of that plugin in the above described location. Maybe add info to the site which plugins are now no longer plugins and their functionality is directly supported by the core? That will be number 5 suggestion.

**Comment by ventoy** [comment]
1. I will add it in the FAQ soon.
2. Fn hotkeys are not avaiable when you in the secondary boot menu, it's designed so.
3. If json file is incorrect it will show the following message, press `Enter` it will continue to boot and ignore the json file.
![image](https://user-images.githubusercontent.com/59477474/209462922-5bb2030e-e7a7-4a23-8830-1808bf03078d.png)

4. I have update the README.

**Comment by ventoy** [comment]
You used the VentoyPlugson tool, it will automatically generate the json file.
As you said, it is not very convenient to create and edit the ventoy.json file manually, so I provide the VentoyPlugson tool.
With this tool, you just need to set in the webpage and don't need to create and edit the json file, the tool will do it automatically.

**Comment by alex-ie** [comment]
@ventoy , thanks! 3 seems I had not paid enough attention, as for 2: the screen has line displayed with F keys, maybe hide it if keys are not supposed to work? That is nit  picking though. You closed the issue already, so cheers and thanks again.
