### ISSUE TITLE
Install fails on dd: failed to open './boot/boot.img': no such file or directory

### ISSUE THREAD

**Issue by dyslexicjedi** [ventoy/Ventoy#21]
rob@pop-os:~/tools/Ventoy/INSTALL$ sudo ./Ventoy2Disk.sh -i /dev/sdb

***********************************************************
*                Ventoy2Disk Script                       *
*             longpanda  admin@ventoy.net                 *
***********************************************************

Disk : /dev/sdb
Model: SanDisk Ultra Fit (scsi)
Size : 28 GB

Attention:
You will install Ventoy to /dev/sdb.
All the data on the disk /dev/sdb will be lost!!!

Continue? (y/n)y

All the data on the disk /dev/sdb will be lost!!!
Double-check. Continue? (y/n)y

Create partitions on /dev/sdb ...
Done
mkfs on disk partitions ...
create efi fat fs ...
mkfs.fat 4.1 (2017-01-24)
success
dd: failed to open './boot/boot.img': No such file or directory
xzcat: ./boot/core.img.xz: No such file or directory
xzcat: ./ventoy/ventoy.disk.img.xz: No such file or directory

Install Ventoy to /dev/sdb successfully finished.

**Comment by dyslexicjedi** [comment]
The drive is not mountable, and the installation did fail.

**Comment by ventoy** [comment]
Oh, you can't run this script in the source tree (INSTALL directory).
You should download the install package from the release tab, decompress it and run script there.

**Comment by dyslexicjedi** [comment]
Yup, that works. Thanks!

**Comment by a1ex-V** [comment]
Could someone please explain what 'download the install package from the release tab, decompress it and run script there' means literally step by step, what to click and where I will find that on screen? I've managed to convert a dmg file to iso in the terminal for a dual boot setup I'd like to try, but have been having the same issue as @dyslexicjedi getting Ventoy installed with the files I downloaded for it. Thanks
