### ISSUE TITLE
[issue]: VT2Disk v1.0.86 reported by Windows Defender

### ISSUE THREAD

**Issue by htcfreek** [ventoy/Ventoy#2102]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.86

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

-

### Image file checksum (if applicable)

None

### What happened?

![image](https://user-images.githubusercontent.com/61519853/209442596-b3b88f95-0974-4b80-88ed-316774106709.png)

https://www.virustotal.com/gui/file/a4f1e92e0949dcc508f78651f7e2d76de406f97b4feb369bf1303384d5928f7c/detection

**Comment by tht1kd** [comment]
Also had this issue. Same computer does not detect any trojans within ventoy-1.0.81.

**Comment by ventoy** [comment]
https://www.microsoft.com/en-us/wdsi/submission/c07ed524-95a2-42d9-b645-ac9566412d3a

![image](https://user-images.githubusercontent.com/59477474/209455243-d6d0f7e8-2101-4a00-b5b6-2ae6a22b2b61.png)

**Comment by htcfreek** [comment]
It is fixed. No false-positive anymore.
