### ISSUE TITLE
[issue]: Ventoy 1.0.86 help

### ISSUE THREAD

**Issue by steve6375** [ventoy/Ventoy#2103]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.86

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

128gb

### Disk Manufacturer

Sandisk Extreme Pro

### Image file checksum (if applicable)

None

### What happened?

F1 help text:
**L - Language**

should be same as other text in list below?
**l/Ctrl+l - Language select**

![image](https://user-images.githubusercontent.com/1469350/209462405-8a8e8cb1-7866-4448-99ce-f63cfc96b240.png)

**Comment by ventoy** [comment]
`L` is visible and is just in front of `F1` in the screen, so I put it the first.
I think it's not a big problem.

**Comment by steve6375** [comment]
no, not a big problem but Ctrl+L key is not documented anywhere and it is the same a L key in function.

**Comment by ventoy** [comment]
Or we can add a line `L/Ctrl+L - Language Select` in the list below too.
