### ISSUE TITLE
[issue]: missing files

### ISSUE THREAD

**Issue by termuxtest101** [ventoy/Ventoy#2107]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.85

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

2TB

### Disk Manufacturer

HP

### What happened?

issue booting ventoy

error: file '/grub/i336-pc/setkey.mod' not found.
error: file '/grub/i386-pc/regexp.mod' not found.
error: xz file corrupted or unsupported block option.
!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!
!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!
!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!

This is NOT a standard Ventoy device and is NOT supported (4098)
Error message: <File ventoy/ventoy.cpio missing in VTOYEFI partition>

You should follow the instructions in https://ventoy.net to use Ventoy.

I have try reinstalling Ventoy, reformat the pendrive and install Ventoy I use gtkhash and it match SHA256 checksum (I use my phone to take a screenshot)
![Screenshot_20221226-213753](https://user-images.githubusercontent.com/99701913/209562394-306b4b77-9573-43c4-b7d7-dc5a114e0698.png)

**Comment by ventoy** [comment]
Try a small disk (2TB is a large disk and your BIOS may not access all its range).

**Comment by ventoy** [comment]
Or try UEFI mode.

**Comment by termuxtest101** [comment]
> Try a small disk (2TB is a large disk and your BIOS may not access all its range).

It did work yesterday but when I try to boot to my usb today I get that error

**Comment by termuxtest101** [comment]
> Or try UEFI mode.

UEFI doesn't work properly on my pc

**Comment by ventoy** [comment]
Ventoy will create 2 partitions after install. The 2nd partition (VTOYEFI) is at the end of the disk and contains Ventoy boot files.
The error message means that some files are missing in the 2nd partition (VTOYEFI).
So you can update Ventoy to recover these files. (Just run Ventoy2Disk.exe and click update button).
But I don't know why these files are missing.

**Comment by termuxtest101** [comment]
> Ventoy will create 2 partitions after install. The 2nd partition (VTOYEFI) is at the end of the disk and contains Ventoy boot files. The error message means that some files are missing in the 2nd partition (VTOYEFI). So you can update Ventoy to recover these files. (Just run Ventoy2Disk.exe and click update button). But I don't know why these files are missing.

I forgot to mention Im using Linux but I have to just run sudo bash Ventoy2Disk.sh -u /dev/sdb right?

**Comment by termuxtest101** [comment]
> Ventoy will create 2 partitions after install. The 2nd partition (VTOYEFI) is at the end of the disk and contains Ventoy boot files. The error message means that some files are missing in the 2nd partition (VTOYEFI). So you can update Ventoy to recover these files. (Just run Ventoy2Disk.exe and click update button). But I don't know why these files are missing.

I have try updating it but it still have a file missing 


https://user-images.githubusercontent.com/99701913/209600331-adf8b805-faf3-4b6b-8721-29baa96d52a0.mp4

**Comment by ventoy** [comment]
After update, just mount `/dev/sdb2`  manually to see whether these files exist.

**Comment by ventoy** [comment]
Can it boot OK in your real PC? (not with QEMU)

**Comment by termuxtest101** [comment]
> Can it boot OK in your real PC? (not with QEMU)

It also have the same error on qemu

**Comment by ventoy** [comment]
OK, just mount `/dev/sdb2` manually to see whether these files exist.

**Comment by termuxtest101** [comment]
> After update, just mount `/dev/sdb2` manually to see whether these files exist.

![Uploading 16721214538556780008663694848141.jpg…]()

**Comment by ventoy** [comment]
The picture was corrupted, I can't see it.

**Comment by termuxtest101** [comment]
> The picture was corrupted, I can't see it.

I can't access partition because it fail to read the information of the /dev/sdb2

**Comment by ventoy** [comment]
If you can't access the /dev/sdb2 (32MB VTOYEFI) partition after update, then there may be some hardware issue with the USB stick.
After install/update Ventoy, you should be able to mount the /dev/sdb2 partition and see the files in it.
