### ISSUE TITLE
[Issue]: NHV BOOT 2023 v1400 EXTREME is not booting on Legacy Boot in real machine

### ISSUE THREAD

**Issue by crasadure** [ventoy/Ventoy#2108]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.88

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

64GB

### Disk Manufacturer

Sandisk Extreme

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://drive.google.com/drive/folders/1LFXbIPoa7IzSGlHWgaDl1HAMuF7J60UY?usp=sharing

### What happened?

Hi @ventoy ;
I know I have opened this ISSUE before,but every new version of this ISO can not working as ISO in Ventoy by NORMAL BOOT method.
I tested NHV BOOT 2023 v1400 EXTREME.iso file on Virtual machine and it is working on virtual machine...
but when I test on REAL MACHINE(wimboot mode , Normal mode and Grub2 Mode ) it is not booting this ISO file...
İt is working on UEFI Mode at real machine

Can you solve this ISO file boot problem?
Google Drive Link1-->https://drive.google.com/drive/folders/1LFXbIPoa7IzSGlHWgaDl1HAMuF7J60UY?usp=sharing
Google Drive Link2-->https://drive.google.com/drive/folders/1KB6nuX89OGS-6BsznB2zc30Exv3mpRpb?usp=sharing

**Comment by steve6375** [comment]
In what way is it 'not booting'?
Ventoy error message? BSOD? What message? Windows error?

**Comment by crasadure** [comment]
> In what way is it 'not booting'? Ventoy error message? BSOD? What message? Windows error?
> 
> When you say 'I tested NHV BOOT 2023 v1300 EXTREME.iso file on Virtual machine and it is working on virtual machine' do you mean you tested by booting to the Ventoy USB drive on a VM and running the ISO from the Ventoy menu system or do you mean you attached the ISO to a virtual DVD and booted the VM from the virtual DVD?

I copied the ISO file to the Sandisk USB flash drive, selected the ISO file on the flash memory and tried to boot in Normal Mode and Wimboot Mode. I tried all these operations on real machine. Unfortunately the ISO file did not boot.

When I test the flash drive in the Virtual machine, it runs the ISO file correctly in Normal Mode.

**Comment by steve6375** [comment]
Wimboot mode is only for standard Microsoft ISOs - press F1 in Ventoy for help. It is not suitable for special WinPE ISOs.


You can boot to the ISO if you name it NHV_BOOT_2023_.isogrub.iso and boot it using Easy2Boot. You can add the Easy2Boot menu system to your Ventoy drive
https://easy2boot.xyz/ventoy/add-easy2boot-to-a-ventoy-usb-drive/
Does that work for you?

**Comment by crasadure** [comment]
I captured a video on Virtual machine..as you seen it is working on Virtual system with Ventoy
Captured Video : https://streamable.com/803qc0

but i try it on real machine it is not working...I wonder why is not working on real machine?

**Comment by steve6375** [comment]
If the system has a formatted internal hard drive then Ventoy does not boot to the ISO but seems to attempt to boot from the internal hard disk. If the internal hard disk contains a valid legacy-bootable copy if Windows then after selecting the ISO file in Ventoy it boots to the Windows on the internal hard disk.
Same for a VM. If the VM also contains a virtual hard disk containing Windows, then it boots to that, but if the VM does not contain an internal hard disk then it boots to WinPE from the ISO OK.

**Comment by crasadure** [comment]
![iso_content](https://user-images.githubusercontent.com/54566818/209656767-c71673af-797f-4f93-b61d-a3f32c1b155c.jpg)
I think, it is reading **Grldr** file and take control Windows operating system.

**Comment by ventoy** [comment]
This ISO file boot OK in my laptop in legacy BIOS mode (normal boot mode). (There is a Windows 10 in my laptop for UEFI mode, not for legacy BIOS mode).

If I select wimboot mode, it indeed report this c000000f error code.

**Comment by crasadure** [comment]
> This ISO file boot OK in my laptop in legacy BIOS mode (normal boot mode). (There is a Windows 10 in my laptop for UEFI mode, not for legacy BIOS mode).
> 
> If I select wimboot mode, it indeed report this c000000f error code.

Master @ventoy ;
İf I Select Normal Boot method, Win11 operating system is starting to boot from internal harddisk.
if i select Wimboot method, I am taking c000000f error code.

Computer disk file system MBR and Bios mode is Legacy

**Comment by ventoy** [comment]
`İf I Select Normal Boot method, Win11 operating system is starting to boot from internal harddisk.`
Write the ISO file to the USB with Rufus, to see whether it boot Win11 from internal harddisk.

**Comment by nhtt2023** [comment]
Does your computer install grub2 as bootloader? If so, it boots into grub2 on your computer's hdd/sdd first. If you want to use wimboot without error, you must copy the iso file to the first partition of the ventoy usb

**Comment by nhtt2023** [comment]
Since Longpanda added wimboot to winpe, I have been able to fix loading and booting winpe.iso from hdd/ssd by editing the wimboot code as follows:
function vtoy_winpe_wimboot {
     unset vtoy_boot_sdi_legacy
     unset vtoy_boot_sdi_efi
    
     set vtoy_wimboot_prefix=(loop)
     set vtoy_wim_path="$1"
    
     if [ -n "${vtdebug_flag}" ]; then
         echo "winpe_wimboot $1 $2 $3"
     fi
    
     if [ "$2" != "0" ]; then
         set vtoy_boot_sdi_legacy="newc:boot.sdi:$vtoy_wimboot_prefix/$2"
         set vtoy_boot_sdi_efi="vf=boot.sdi:$vtoy_wimboot_prefix/$2"
     fi

     vt_windows_wimboot_data $vtoy_wimboot_prefix/$vtoy_wim_path vtoy_init_exe vtoy_wim_bit
    
     if [ "$grub_platform" = "pc" ]; then
         linux16 "$vtoy_path/$vt_wimkernel" quiet
         ventoy_debug_pause

         vt_set_wim_load_prompt 1 "Loading files......"
         initrd16 newc:$vtoy_init_exe:mem:${vtoy_wimboot_mem_addr}:size:${vtoy_wimboot_mem_size} \
              newc:vtoy_wimboot:$vtoy_path/$vt_wimkernel \
              newc:bootmgr.exe:mem:${vtoy_pe_bootmgr_mem_addr}:size:${vtoy_pe_bootmgr_mem_size} \
              newc:bcd:($vtoy_dev,1)/bcd \
              newc:boot.sdi:($vtoy_dev,1)/boot.sdi \
              newc:boot.wim:$vtoy_wimboot_prefix/$vtoy_wim_path
         vt_set_wim_load_prompt 0
         boot
     else
         if [ "$VTOY_EFI_ARCH" = "x64" -a "$vtoy_wim_bit" = "32" ]; then
             echo -e "\nThis is 32bit Windows and does NOT support x86_64 UEFI firmware.\n"
             echo -e "这是32位的 Windows 系统，不支持当前的64位 UEFI \n"
         fi

         vt_set_wim_load_prompt 1 "Loading files......"
         vt_load_file_to_mem "nodecompress" $vtoy_wimboot_prefix/$vtoy_wim_path vtoy_wimfile_mem
         vt_set_wim_load_prompt 0

         if [ $? -eq 0 ]; then
             set vtoy_wimfile_path=mem:${vtoy_wimfile_mem_addr}:size:${vtoy_wimfile_mem_size}
         else
             set vtoy_wimfile_path=$vtoy_wimboot_prefix/$vtoy_wim_path
         fi
        
         unset vtoy_boot_efi_path
         if [ -F (loop)/efi/boot/boot${VTOY_EFI_ARCH}.efi ]; then
             set vtoy_boot_efi_path="vf=bootx64.efi:(loop)/efi/boot/boot${VTOY_EFI_ARCH}.efi"
         fi

         ventoy_cli_console
         chainloader "$vtoy_path/$vt_wimkernel" quiet \
             "vf=$vtoy_init_exe:mem:${vtoy_wimboot_mem_addr}:size:${vtoy_wimboot_mem_size}" \
             "vf=vtoy_wimboot:$vtoy_path/$vt_wimkernel" \
             "vf=bcd:($vtoy_dev,1)/efibcd" \
             "vf=boot.sdi:($vtoy_dev,1)/boot.sdi" \
             "$vtoy_boot_efi_path" \
             "vf=boot.wim:$vtoy_wimfile_path" \
             pfsize=$vtoy_chain_file_size \
             pfread=$vtoy_chain_file_read
         boot
         ventoy_gui_console
     fi
}
The files bcd, efibcd, boot.sdi I attached below
https://drive.google.com/file/d/1zWeaDghVrrD-B-YbSia41mrCtK8BQXdF/view?usp=share_link
[https://drive.google.com/file/d/1zWeaDghVrrD-B-YbSia41mrCtK8BQXdF/view?usp=share_link](url)

**Comment by crasadure** [comment]
> Does your computer install grub2 as bootloader? If so, it boots into grub2 on your computer's hdd/sdd first. If you want to use wimboot without error, you must copy the iso file to the first partition of the ventoy usb

This computers are our classroom computer. There is no grub2 bootloader our computer. Computers have 120gb ssd and have Windows 11 operating system on our computers. I will try  suggestion of @ventoy . Because ventoy said it like that.

I will write your ISO to USB drive only with Rufus program and will boot it from usb.
I will write result of this option.

**Comment by crasadure** [comment]
> Does your computer install grub2 as bootloader? If so, it boots into grub2 on your computer's hdd/sdd first. If you want to use wimboot without error, you must copy the iso file to the first partition of the ventoy usb

I dont want to use wimboot mode, I want to boot your system with Normal Boot with Ventoy. Our forum users have same problems..they were reported same problem on Tnctr forum
These are reported problems links:
https://www.tnctr.com/topic/1097668-nhv-boot-2023-v1300-extreme/page/3/?tab=comments#comment-2657610

**Comment by nhtt2023** [comment]
If you want to use ventoy to load and boot NHV-BOOT-2023-V1300-EXTREME.iso in normal mode, use Ultriso to edit NHV-BOOT-2023-V1300-EXTREME.iso, select grldr in the root directory and press the key Right click and select set boot file, save the file.

**Comment by crasadure** [comment]
> If you want to use ventoy to load and boot NHV-BOOT-2023-V1300-EXTREME.iso in normal mode, use Ultriso to edit NHV-BOOT-2023-V1300-EXTREME.iso, select grldr in the root directory and press the key Right click and select set boot file, save the file.
@nhtt2023 
I tried your suggestion and Ventoy Normal Boot option started your system from Ventoy... My problem was solved..I will share your solution at our forum.. pls, on other versions of NHV-BOOT , can you test your system on Ventoy Multiboot system.. Thanks for your help :) 

Master @ventoy 
I wrote NHV-BOOT with Rufus program..İt booted from USB succesfully. This is not your system problem.. The owner of NHBOOT solved this ISSUE.. I am closing this ISSUE.. Thanks your help

**Comment by crasadure** [comment]
Hi Ventoy

**Comment by nhtt2023** [comment]
There are 2 ways to fix this error, both use ultraiso
Method 1: delete grldr in the root directory of the iso file and replace it with grldr in the boot\nhv\grub directory of the iso file and setboot for grldr and save
Method 2: copy bootmgr, bootmgr.efi (in the standard windows iso file) to the root directory of the iso file and then save

**Comment by crasadure** [comment]
Thanks answer 🙂
________________________________
Gönderen: nhtt2023 ***@***.***>
Gönderildi: 19 Ocak 2023 Perşembe 21:50
Kime: ventoy/Ventoy ***@***.***>
Bilgi: Tayfun Akkoyun ***@***.***>; State change ***@***.***>
Konu: Re: [ventoy/Ventoy] [Issue]: NHV BOOT 2023 v1400 EXTREME is not booting on Legacy Boot in real machine (Issue #2108)


There are 2 ways to fix this error, both use ultraiso
Method 1: delete grldr in the root directory of the iso file and replace it with grldr in the boot\nhv\grub directory of the iso file and setboot for grldr and save
Method 2: copy bootmgr, bootmgr.efi (in the standard windows iso file) to the root directory of the iso file and then save
