### ISSUE TITLE
Windows Vista Error

### ISSUE THREAD

**Issue by 44cK3r** [ventoy/Ventoy#2109]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.86

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

None

### Image file download link (if applicable)

https://archive.org/details/windows-vista-ultimate-32-bit-sp-2-pre-activated

### What happened?

A bug happened!
![IMG20221228133212](https://user-images.githubusercontent.com/86052117/209753498-f89b14ed-fd42-429a-b56a-d6062f43178a.jpg)
I tried to boot the (.iso) with (WimBoot) everything goes perfectly fine but when it gets to the point where I can control the mouse it shows the mouse and then goes away then shows it again with this error I can provide some more pictures if needed or a video if there's no upload file size limit also sorry if I don't respond my notifications never work properly and I have a terrible memory sorry I really badly need this I have spent so much to try and bring back this Laptop and I want it to be installed to my (external SSD) - (SATA Adapter to USB) and then (Dual Boot) (Windows 98 SE) alongside Vista thank you Love You All Keep It Up And Stay Positive

**Comment by ventoy** [comment]
Ventoy only supports Windows 7 and later release.  Windows Vista is not supported.

**Comment by 44cK3r** [comment]
> Ventoy only supports Windows 7 and later release.  Windows Vista is not supported.
> 

Will it ever be added

**Comment by ventoy** [comment]
No.
If you want to install Windows XP/Vista you can firstly boot into some WinPE and then install inside the WinPE.

**Comment by 44cK3r** [comment]
> No.
> If you want to install Windows XP/Vista you can firstly boot into some WinPE and then install inside the WinPE.
> 

Sadly I don't even think that would work on my laptop it's extremely fussy but I'll try windows 7 and see how far I get sorry thank you though this software or whatever you want to call idk sorry is the best I'll be using whenever I can sorry I'm not very good at wording things so I hope you know what I meant sorry nothing bad
