### ISSUE TITLE
[issue]: 无法启动ventoy，直接报错

### ISSUE THREAD

**Issue by zznx12345** [ventoy/Ventoy#2110]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.86

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

128GB(119GB)

### Disk Manufacturer

Sandisk Extreme Pro CZ880

### Image file checksum (if applicable)

Yes.

### What happened?

在BIOS选择磁盘后出现：alloc magic is broken at 0x88193860:88219877 Aborted.Press any key to exit.
然后加载vtloading之后再次报错并按任意键重启

**Comment by steve6375** [comment]
have you modified the Ventoy in any way - e.g. theme? add a \ventoy\ventoy.json file ? Same error if not using a json file?

**Comment by zznx12345** [comment]
Maybe I have changed the part of the theme configuration.But I think the problem may not about theme.

**Comment by ventoy** [comment]
默认安装，不要做任何修改的情况下能正常启动吗？（不设置、修改主题，不使用 ventoy.josn）

**Comment by zznx12345** [comment]
默认安装没有问题

**Comment by zznx12345** [comment]
默认安装没有问题

**Comment by ventoy** [comment]
那就简单了。可能是哪里的设置有问题。你一点点加，就能找到问题了。
很可能是主题的问题，比如主题中的图片格式问题之类的。
