### ISSUE TITLE
[feature request]: BSD style CHECKSUM

### ISSUE THREAD

**Issue by skatcat743** [ventoy/Ventoy#2112]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.86

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

128GB

### Disk Manufacturer

Sandisk

### Image file checksum (if applicable)

Yes.

### What happened?

In the documentation on ventoy.net about checksums describe the format of the checksum file. 

 

> The following two format of .md5/.sha1/.sha256/.sha512 file are supported. (Take sha256 for example)
> 
> `f8d3ab0faeaecb5d26628ae1aa21c9a13e0a242c381aa08157db8624d574b830`
> 
> `f8d3ab0faeaecb5d26628ae1aa21c9a13e0a242c381aa08157db8624d574b830  ubuntu-21.10-desktop-amd64.iso`
> 

But in my opinion there is a more convenient type that I wish I could use instead. Which would be the BSD format.
`SHA256 (ventoy-1.0.86-livecd.iso) = adcda85d6152331b492793f62adb9e486718f1ad8dbaddc9c9e318f347630dc0`

The BSD format of checksums can be created by using --tag if you are using gnu sha256sum / md5sum etc
There are two nice features of BSD format one of them is that it can be just one file rather than creating "duplicates" like Mac ._files. The other feature is showing the algorithm in the contents rather than relying on the filename extension.
current checksum way.
```
ISO/antiX-22_x64-base.iso
ISO/antiX-22_x64-base.iso.sha256
ISO/easy-4.5.3-amd64.img
ISO/easy-4.5.3-amd64.img.sha256
ISO/ventoy-1.0.86-livecd.iso
ISO/ventoy-1.0.86-livecd.iso.sha256
ISO/Win10_22H2_English_x64.iso
ISO/Win10_22H2_English_x64.iso.sha256
ISO/Win11_22H2_English_x64v1.iso
ISO/Win11_22H2_English_x64v1.iso.sha256
```
vs
```
ISO/antiX-22_x64-base.iso
ISO/CHECKSUM
ISO/easy-4.5.3-amd64.img
ISO/ventoy-1.0.86-livecd.iso
ISO/Win10_22H2_English_x64.iso
ISO/Win11_22H2_English_x64v1.iso
```
the contents of the CHECKSUM file would be
```
SHA256 (antiX-22_x64-base.iso) = 1d69537d3b93a97ceb8eaef9909eb15d6129412b26df23f69dc668dfa7f7c993
SHA256 (easy-4.5.3-amd64.img) = cfbad935964241e8024e1322e2f59c784618c617685da08ece98e297ecdafe53
SHA256 (ventoy-1.0.86-livecd.iso) = adcda85d6152331b492793f62adb9e486718f1ad8dbaddc9c9e318f347630dc0
SHA256 (Win10_22H2_English_x64.iso) = f41ba37aa02dcb552dc61cef5c644e55b5d35a8ebdfac346e70f80321343b506
SHA256 (Win11_22H2_English_x64v1.iso) = 0df2f173d84d00743dc08ed824fbd174d972929bd84b87fe384ed950f5bdab22
```
When I would download a new iso on a Linux system I would use this is to hash the file from my Downloads folder then while it's copying to the flash drive append the hash.
`sha256sum --tag MX-21.2.1_ahs_x64.iso >> /mnt/Ventoy/ISO/CHECKSUM`
which would add this line to the bottom of the CHECKSUM file
`SHA256 (MX-21.2.1_ahs_x64.iso) = 05efaae3ec3ce7f845538c226a145534c4836dd7a8435e6f85dd0d4eb17a90a5`

A nice part of this would maybe be in the tools menu being able to hash all images if they have the checksum on disk.
If you could direct me to the appropriate areas of source code I would like to try to implement it myself.

**Comment by ventoy** [comment]
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/3812902366
https://www.ventoy.net/en/doc_github_ci.html

The help page also updated: https://www.ventoy.net/en/doc_checksum.html#checksum_compare

**Comment by skatcat743** [comment]
Thanks a lot for the feature.

There is one consideration
I understand the current (CI release 12311655) behavior of the menu where it says "calculate and check" for all hashing algorithms when using this style of formatting. since it would be harder to tell which hash this is with out it being labeled like .sha256

> f8d3ab0faeaecb5d26628ae1aa21c9a13e0a242c381aa08157db8624d574b830  ubuntu-21.10-desktop-amd64.iso

but if the VENTOY_CHECKSUM file is using the BSD style the "and check" appears on all of the options not just the one listed in the file. 

> **_SHA256_** (ubuntu-21.10-desktop-amd64.iso) = f8d3ab0faeaecb5d26628ae1aa21c9a13e0a242c381aa08157db8624d574b830

If the function could open the global/local file and print instead calculate, calculate, calculate and check, and calculate based on the first contents of the line. or perhaps a simple bypass like "VENTOY_CHECKSUM.sha256" which would inform the function which hash system is in the file without having to read the contents

**Comment by ventoy** [comment]
We still don't know whether the checksum value for an ISO file is included in the `VENTOY_CHECKSUM` or not if we don't read all the lines of the file.
With `VENTOY_CHECKSUM.sha256` we can just know that MD5/SHA1/SHA512 is not included, but we still don't know whether SHA256 is really included.

It's not a good idea to read the whole checksum file when generating the menu. So current is OK I think.

Well, any way, Ventoy checksum feature was designed only to calculate the current checksum value for referrence and normally is only used when you failed to boot an ISO file. I don't want to make it too complex. 

Besides, checksum under bootloader is very slow, so if you really want to checksum for some of the ISO files. You can put a small WinPE or Linux LiveCD iso to Ventoy, boot into the WinPE/Linux Live and do the checksum there. There are many professional tools available.
