### ISSUE TITLE
[issue]: unable to boot PER620_BOOTABLE_21.09.00.206.iso

### ISSUE THREAD

**Issue by mischapeters** [ventoy/Ventoy#2113]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.85

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

Sandisk

### Image file checksum (if applicable)

Yes.

### What happened?

Booting from the Dell PER ISO for the PowerEdge R620 refuses to continue after it's unable to mount the block device.
See attached image from the console.

5.522384] dracut-initqueue(725]: mount: (DEUNAME) is write-protected, mounting read-only
5.5342741 dracut: FATAL: Failed to mount block device of live image
5.5343211 dracut: Refusing to continue
5.5229511 dracut-initqueuel725]: mount: special device (DEVNAME] does not exist

![rpviewer](https://user-images.githubusercontent.com/7456624/209847072-affa7283-86cd-4473-8941-6d42cfeb7e59.png)

**Comment by ventoy** [comment]
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/3828039757
https://www.ventoy.net/en/doc_github_ci.html

**Comment by mischapeters** [comment]
That works like a charm! Great stuff.

![rpviewer](https://user-images.githubusercontent.com/7456624/210560749-77208c1d-7143-4e1a-9ba3-b529dbaa56d0.png)

**Comment by ventoy** [comment]
Fixed in 1.0.87
