### ISSUE TITLE
[issue]: Linux VentoyPlugson GUI?

### ISSUE THREAD

**Issue by rgl** [ventoy/Ventoy#2115]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.86

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

-1

### Image file checksum (if applicable)

None

### What happened?

What is the Linux equivalent of the VentoyPlugson GUI?

For example, in Windows, its:

![image](https://user-images.githubusercontent.com/43356/209864766-0c6493ed-c0e3-483e-9962-4b2d4045bde8.png)

But in Linux, we only seem to have a `VentoyPlugson.sh`, which is a CLI application.

**Comment by ventoy** [comment]
VentoyPlugson is a web-based app.

In Windows:
When you run `VentoyPlugson.exe` , select your USB device and click `Start` button, it will automatically open your browser and visit URL `http://127.0.0.1:24681`

In Linux:
Run `sudo bash VentoyPlugson.sh /dev/sdX` in the terminal, then it will print the tip message, then you need to manually open your browser and visit URL `http://127.0.0.1:24681`

See: https://www.ventoy.net/en/plugin_plugson.html  for details.

![image](https://user-images.githubusercontent.com/59477474/209893326-6a2cfbd1-efe5-463e-a5de-4516880a40ac.png)

**Comment by rgl** [comment]
Will there be a Linux GUI version too? So it is the same as in windows.

**Comment by ventoy** [comment]
No.
It's just used to start the web server, so there is no need to do a GUI version for linux.
It's more complex for linux GUI version than Windows (you should consider GTK/QT ...)

**Comment by rgl** [comment]
Going on a limb, but as there's a reason for a GUI in windows, there's a reason for it in any platform. Maybe it would be interesting to use a cross platform ui like electron or wails rather than directly use a native toolkit.
