### ISSUE TITLE
[Success Image Report]:  Vanilla OS 22.10

### ISSUE THREAD

**Issue by kbdharun** [ventoy/Ventoy#2121]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.86

### BIOS Mode

Both

### Partition Style

GPT

### Image file name

VanillaOS-22.10-all.20221229.iso

### Image file checksum type

MD5

### Image file checksum value

dd884b54e5635d021d4a06221eade619

### Image file download link (if applicable)

https://github.com/Vanilla-OS/os/releases/download/22.10/VanillaOS-22.10-all.20221229.iso

### Test environment

ASUS H110M-D Motherboard

### More Details?

This image file booted successfully in Ventoy. And the installation was successful.

**Comment by kbdharun** [comment]
Vanilla OS Unstable is already present on the website. It was a weekly build from a few weeks ago, now stable is out and I tested it with Ventoy.

**Comment by ventoy** [comment]
Thanks!
