### ISSUE TITLE
[Success Image Report]: ShredOS

### ISSUE THREAD

**Issue by comp2x** [ventoy/Ventoy#2122]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.86

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

shredos-2021.08.2_21_x86-64_0.32.023_20220126.iso

### Image file checksum type

SHA1

### Image file checksum value

5f464534a40456584d2d28607750791f364e28ec

### Image file download link (if applicable)

https://github.com/PartialVolume/shredos.x86_64/releases/download/v2021.08.2_21_x86-64_0.32.023/shredos-2021.08.2_21_x86-64_0.32.023_20220126.iso

### Test environment

Custom-built i7-2600k desktop

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
