### ISSUE TITLE
[issue]: AtlasOS

### ISSUE THREAD

**Issue by visious25** [ventoy/Ventoy#2124]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.84

### What about latest release

No. I didn't try the latest release.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

4GB

### Image file checksum (if applicable)

None

### What happened?

Hi, does ventoy support [AtlasOS](https://atlasos.net/)? Is alternative of Windows 10 operating system, but opensource. It would be good to know.

PS: I didn't run it yet of any version of ventoy.

**Comment by FabioLolix** [comment]
> does ventoy support [AtlasOS](https://atlasos.net/)?

Why don't you try it?

> Is alternative of Windows 10 operating system, but opensource.

Atlas is a pre-tweaked Windows 10, and their tools are open source

**Comment by visious25** [comment]
1) I have an old laptop dual boot and I'm running Windows 7 and Arch Linux.
2) I don't have enough space in my Hard Drive.

**Comment by FabioLolix** [comment]
fair enough

**Comment by visious25** [comment]
You are wellcome. I just found out today on the web that AtlasOS exists as open source operating system.

**Comment by ventoy** [comment]
I only test `Atlas_v0.5.2.iso` in VM and it works fine.

**Comment by visious25** [comment]
Which means ventoy supports Atlas_v0.5.2.iso, right?

**Comment by ventoy** [comment]
Yes, at least in VM.

**Comment by visious25** [comment]
You're used the iso directly to VM, not thou ventoy. I see.

**Comment by ventoy** [comment]
I tested by Ventoy on VM, not directly connect the ISO file to the CDROM of the VM.

**Comment by visious25** [comment]
Which means ventoy supports Atlas_v0.5.2.iso, right?

**Comment by rkr87** [comment]
I just tried installing it on one of my spare drives via ventoy, works fine.

**Comment by visious25** [comment]
If it works fine is good to know and a happy new year.
