### ISSUE TITLE
[issue]: 文本模式中文会显示为 ？？ 问号。 这个问题是无解的么？

### ISSUE THREAD

**Issue by kkjoy** [ventoy/Ventoy#2126]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.84

### What happened?

文本模式和图形模式在功能上是一样的，只是图形模式更漂亮一点，再有就是文本模式中文会显示为 ？？ 问号。
在cli界面下显示中文有没有办法呀？一堆问号还是有点恼火的

**Comment by a1ive** [comment]
无解。除非你的 UEFI BIOS 有中文字库。
