### ISSUE TITLE
[issue]: `ei.cfg` does not trigger edition selection with Windows 11

### ISSUE THREAD

**Issue by hoang-himself** [ventoy/Ventoy#2127]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.86

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://www.microsoft.com/en-us/software-download/windows11/

### What happened?

I followed [this thread](https://forums.ventoy.net/showthread.php?tid=1991&pid=5222#pid5222) to inject `ei.cfg` into my Windows installation boot with a few changes. I tried installing Windows 11 on a new machine with OEM Windows pre-installed, but the edition selection window is not displayed.

I can confirm that `ei.cfg` exists in `X:\sources` during installation.

<details><summary>Directory structure</summary>

```text
├───injection
│       windows.zip
│
├───iso
│   │   Fedora-Workstation-Live-x86_64-37-1.7.iso
│   │   kali-linux-2022.3-live-amd64.iso
│   │   ubuntu-22.04-desktop-amd64.iso
│   │
│   └───WinNT10
│           Win11_22H2_English_x64v1.iso
│           Win10_22H2_English_x64.iso
│
└───ventoy
    │   ventoy.json
    │
    └───theme
            ...
```

</details>

<details><summary>ventoy.json</summary>

```json
{
  "theme": {
    "file": "/ventoy/theme/tela/theme.txt"
  },
  "injection": [
    {
      "parent": "/iso/WinNT10",
      "archive": "/injection/windows.zip"
    }
  ]
}
```

</details>

[windows.zip](https://github.com/ventoy/Ventoy/files/10328979/windows.zip)

**Comment by ventoy** [comment]
inject `ei.cfg` to the WinPE X drive does not help. The `ei.cfg` must be inside of the ISO file.
So use a special XML file as noted in the same thread.

**Comment by TheForgottened** [comment]
Hey, sorry to revive an old thread. I am currently facing this and the XML given in the thread makes the edition screen show up, but only Home Edition is available. Not sure if this has always been the case of recent changes to WIndows images caused this.

**Comment by steve6375** [comment]
Setup will use the OEM product key which the manufacturer has embedded into the bios during factory production. Sounds like your pc has Home licence.
You can make an XML file which has a generic product key set, e.g. for win10 professional. This will force setup to install pro.
See the wafg website to make an XML file or use one of the XML files which you can find in the Easy2boot download files.
https://www.windowsafg.com/

**Comment by fgGitH2001** [comment]
I tried using EI.cfg with Build 26080, but I did not trigger the prompt for selecting the edition.
Did Microsoft change the logic on the latest insider Bulds?
How can we get the edition selection back?

**Comment by steve6375** [comment]
answer files take precedence over ei.cfg
If you have problems then check the .log file on X: drive
The log file will tell you if the embedded OEM Product Key is overriding and ei.cfg or xml file.
https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/deployment-troubleshooting-and-log-files?view=windows-11
https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-setup-log-files-and-event-logs?view=windows-11
https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-setup-edition-configuration-and-product-id-files--eicfg-and-pidtxt?view=windows-11

**Comment by fgGitH2001** [comment]
There are no answer files.
The same ei.cfg works fine with 23H2 Build 22631.2861 and triggers the edition selection menu.
The same exact ei.cfg does not work with Build 26080.
 ei.cfg 

[Channel]
_Default
[VL]
0

With 26080 I had to use 2 files to install the edition I wanted. (In this case I wanted Home edition.
Still did not show the menu for edition selection. The edition was selected by the 2 files.
1) EI.cfg

[EditionID]
Home
[Channel]
_Default
[VL]
0

2) PID.txt

[PID]
Value=YTMG3-N6DKC-DKB77-7M9GH-8HVX7

**Comment by steve6375** [comment]
Are you saying that 23H2 Build 22631.2861  worked Ok - ON THE SAME PC?

**Comment by fgGitH2001** [comment]
@steve6375,
Yes, works perfectly on the same PC using 22631.2861, but not with 26080.1.

**Comment by steve6375** [comment]
ah OK. well then you need to check log files to see what is going on!

**Comment by fgGitH2001** [comment]
@steve6375,

That is something for MS, they are the ones that screwed it up in 26080. I submitted an FBH report.
I can work around the problem as I explained earlier; Microsoft needs to get the answer about what they changed on latest insider builds. 😎🤷‍♂️

https://aka.ms/AAqfho0

The edition selection menu was pretty handy for testing different edition installations without messing with the EI.cfg and PID.txt for every edition.

**Comment by terryhobart** [comment]
OK It's Oct. 3 2024. I created a brand new install disk.  To make it work I had to add ei.cfg & PID.txt to sources.
ei.cfg:
[Edition]
Professional
[Channel]
Retail
[VL]
0

I really think the latest version is ignoring this file.

PID.txt
[PID]
value=VK7JG-NPHTM-C97JM-9MPGT-3V66T

This is the generic windows Pro key. You can get the list online.

For me (your luck may vary) it went ahead & intsalled Windows 11 Pro fine (no menu).

**Comment by fgGitH2001** [comment]
@terryhobart,
ei.cfg alone does not work anymore. It was reported several months ago with build 26080.
With latest Builds for 24H2, to trigger the installation of the correct edition you need both the ei.cfg and the PID.txt.
Without those two files in the Sources directory, it will pick the same edition that is defined in the BIOS of the machine.  
The machine BIOS may have the information for the edition that was originally installed in the box.
That could be different from the edition installed later in the machine after acquiring a new license for the desired edition.
IE: The machine originally could have the Windows Home edition, while you may have later acquired a license for the Pro edition. If that is the case, you need to add both the files ei.cfg and PID.txt to the Sources folder of the installation media to select the correct edition.

**Comment by Marmotte69** [comment]
Hello,
Do you know how to clean the edition that is defined in the BIOS of the machine ?

**Comment by huuthanh21** [comment]
> OK It's Oct. 3 2024. I created a brand new install disk. To make it work I had to add ei.cfg & PID.txt to sources. ei.cfg: [Edition] Professional [Channel] Retail [VL] 0
> 
> I really think the latest version is ignoring this file.
> 
> PID.txt [PID] value=VK7JG-NPHTM-C97JM-9MPGT-3V66T
> 
> This is the generic windows Pro key. You can get the list online.
> 
> For me (your luck may vary) it went ahead & intsalled Windows 11 Pro fine (no menu).

This worked for me too. Ty

**Comment by fgGitH2001** [comment]
> Hello, Do you know how to clean the edition that is defined in the BIOS of the machine ?

@Marmotte69, 
No, I have no idea on how to clean the edition define in the BIOS.  I don't think the users can change that.
It is the edition key that was purchased originally with the PC.
Maybe you should direct the question to the PC manufacturer forums.  🤷‍♂️

**Comment by steve6375** [comment]
You can use an XML file and specify a generic product key of the edition you want to install.
If you download Easy2boot you will find examples of XML files for home retail and pro retail. Just use the desired one with Ventoy and your ISO as described on Ventoy document page for autounnatend.xml

**Comment by fgGitH2001** [comment]
> You can use an XML file and specify a generic product key of the edition you want to install. If you download Easy2boot you will find examples of XML files for home retail and pro retail. Just use the desired one with Ventoy and your ISO as described on Ventoy document page for autounnatend.xml

@steve6375,
Adding ei.cfg and PID.txt to the Sources folder is pretty easy. No need for anything else. 😉🤷‍♂️

**Comment by steve6375** [comment]
Adding an XML file to the usb drive is easier than editing the iso to add two files. Using an XML, the original iso can be used.

**Comment by fgGitH2001** [comment]
> Adding an XML file to the usb drive is easier than editing the iso to add two files. Using an XML, the original iso can be used.

You can add the ei.cfg and PID.txt to the USB, no need to modify the ISO. 😂🤷‍♂️

**Comment by codejq** [comment]
I can confirm that adding ei.cfg and PID.txt to the Sources folder works for me

**Comment by H0RU52** [comment]
Unfortunately, this still doesn't work for me.
I injected the two files (ei.cfg, pid.txt -> zip) into the sources folder using ventoyplugson.
I even put my legit pro key into pid.txt.

Still cannot choose windows 11 edition, home installs.

**Comment by fgGitH2001** [comment]
@H0RU52,
What Build number is your installation media?
Also, please show the exact content for the ei.cfg and pid.txt files that you added.
Thanks.

**Comment by H0RU52** [comment]
I downloaded the latest iso from microsoft (from here: https://www.microsoft.com/en-us/software-download/windows11)

ei.cfg
---
[Edition]
Professional
[Channel]
Retail
[VL]
0

PID.txt
---
[PID]
value=MYFRE-AKINL-EGITW-INKEY

**Comment by H0RU52** [comment]
Build number 26200.6584

**Comment by fgGitH2001** [comment]
@H0RU52,
I don't know if I still have that build number to try out.
If that is not working anymore, you could download an ISO from UUP-dump with just the Professional edition without the Home edition and use that instead of the multi-edition that you have. 
B.T.W. you show [Edition] it should be [EditionID],  
Try correcting your file.   I just tried with the 2 files below on my machine and it worked as expected.
  
**ei.cfg**

[EditionID]
Professional
[Channel]
Retail
[VL]
0

**PID.txt**

[PID]
Value=VK7JG-NPHTM-C97JM-9MPGT-3V66T
