### ISSUE TITLE
[issue]: VTOY_WIN11_BYPASS_NRO

### ISSUE THREAD

**Issue by kerrigans07** [ventoy/Ventoy#2128]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.86

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

16GB

### Image file checksum (if applicable)

None

### What happened?

I install Windows 11 but can't not bypasses the online account requirement of Windows 11
in spite of opening VTOY_WIN11_BYPASS_NRO but not working

**Comment by ventoy** [comment]
NB: Network MUST be temporarily disabled or unplugged for the local account creation to be proposed

**Comment by SakuraMay** [comment]
> 注意：必须暂时禁用或拔出网络才能建议创建本地帐户

我今天试着用新版本重装一次，拔掉网线还是没有出现跳过按钮，然后用命令窗口输入命令之后出现了跳过按钮

**Comment by SakuraMay** [comment]
> NB: Network MUST be temporarily disabled or unplugged for the local account creation to be proposed

Today I unplugged the network cable and tried it again, but the skip button still didn't appear

**Comment by ventoy** [comment]
What cmd did  you enter?  Did the cmd just create the following registry?
```
KEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE\BypassNRO
```
open regedit and check whether the above registry exist before you enter cmd.
open regedit and check whether the above registry exist after you enter cmd.

**Comment by SakuraMay** [comment]
> What cmd did you enter? Did the cmd just create the following registry?
> 
> ```
> KEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE\BypassNRO
> ```
> 
> open regedit and check whether the above registry exist before you enter cmd. open regedit and check whether the above registry exist after you enter cmd.

Just a few minutes ago, I used Ventoy again to install windows11 (PS:Unplug the network cable before installation). When entering the configuration prompt network connection interface, there is no "I don't have Internet connection options" in the lower right corner of the interface, only a gray next button that cannot be clicked. I use command window input regedit, check HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE no BYPASSNRO registration entry, After I enter OOBE\ bypassro.CMD in the command window and press enter, the computer restarts immediately and enters the configuration prompt interface of network connection again. "I don't have Internet connection option" appears at the lower right corner of the interface. Check for BYPASSNRO registration entry under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE

> What cmd did you enter? Did the cmd just create the following registry?
> 
> ```
> KEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE\BypassNRO
> ```
> 
> open regedit and check whether the above registry exist before you enter cmd. open regedit and check whether the above registry exist after you enter cmd.

Just a few minutes ago, I used Ventoy again to install windows11 (PS:Unplug the network cable before installation). When entering the configuration prompt network connection interface, there is no "I don't have Internet connection options" in the lower right corner of the interface, only a gray next button that cannot be clicked. I use command window input regedit, check HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE no BYPASSNRO registration entry, After I enter OOBE\ bypassro.CMD in the command window and press enter, the computer restarts immediately and enters the configuration prompt interface of network connection again. "I don't have Internet connection option" appears at the lower right corner of the interface. Check for BYPASSNRO registration entry under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE

**Comment by SakuraMay** [comment]
> What cmd did you enter? Did the cmd just create the following registry?
> 
> ```
> KEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE\BypassNRO
> ```
> 
> open regedit and check whether the above registry exist before you enter cmd. open regedit and check whether the above registry exist after you enter cmd.

Just a few minutes ago, I used Ventoy again to install windows11 (PS:Unplug the network cable before installation). When entering the configuration prompt network connection interface, there is no "I don't have Internet connection options" in the lower right corner of the interface, only a gray next button that cannot be clicked. I use command window input regedit, check HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE no BYPASSNRO registration entry, After I enter OOBE\ bypassro.CMD in the command window and press enter, the computer restarts immediately and enters the configuration prompt interface of network connection again. "I don't have Internet connection option" appears at the lower right corner of the interface. Check for BYPASSNRO registration entry under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE

**Comment by SakuraMay** [comment]
> What cmd did you enter? Did the cmd just create the following registry?
> 
> ```
> KEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE\BypassNRO
> ```
> 
> open regedit and check whether the above registry exist before you enter cmd. open regedit and check whether the above registry exist after you enter cmd.

Just a few minutes ago, I used Ventoy again to install windows11 (PS:Unplug the network cable before installation). When entering the configuration prompt network connection interface, there is no "I don't have Internet connection options" in the lower right corner of the interface, only a gray next button that cannot be clicked. I use command window input regedit, check HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE no BYPASSNRO registration entry, After I enter OOBE\ BYPASSNRO.CMD in the command window and press enter, the computer restarts immediately and enters the configuration prompt interface of network connection again. "I don't have Internet connection option" appears at the lower right corner of the interface. Check for BYPASSNRO registration entry under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE

**Comment by ventoy** [comment]
In the cmd, copy out  `X:\Windows\system32\ventoy.log`  and upload here.

**Comment by ventoy** [comment]
When you install Windows by Ventoy:
step1: The ISO boots, and the setup launch, format disk and begin to copy files.  And finally, it reboot.
step2: You computer reboot into the new installed Windows.

The `I don't have Internet connection options` appears in step1 or step2?

**Comment by SakuraMay** [comment]
> In the cmd, copy out `X:\Windows\system32\ventoy.log` and upload here.

Sorry, I didn't find ventoy.log

**Comment by ventoy** [comment]
@SakuraMay 
Please try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/3855580994
https://www.ventoy.net/en/doc_github_ci.html

**Comment by SakuraMay** [comment]
> @SakuraMay Please try this CI release: https://github.com/ventoy/Ventoy/actions/runs/3855580994 https://www.ventoy.net/en/doc_github_ci.html

Problem solved

**Comment by ventoy** [comment]
Fixed in 1.0.87

**Comment by liblaf** [comment]
How can I disable network on a laptop?

**Comment by SeryiBaran** [comment]
@liblaf did you know what to do in your situation?

**Comment by davidhedlund** [comment]
@ventoy 

# Setup 1
* Win11_22H2_EnglishInternational_x64v2.iso
* USB flash stick without Ventoy
* No internet cable plugged
* The "I don't have internet" button appear during the installation

# Setup 2
* Win11_22H2_EnglishInternational_x64v2.iso
* USB flash stick **with** Ventoy
* Internet cable plugged
* The "I don't have internet" button **don't** appear during the installation

**Comment by davidhedlund** [comment]
> NB: Network MUST be temporarily disabled or unplugged for the local account creation to be proposed

With Win11_22H2_EnglishInternational_x64v2.iso extracted to a USB flash drive (Shift + F10 and type OOBE\BYPASSNRO - https://answers.microsoft.com/en-us/insider/forum/all/set-up-windows-11-without-internet-oobebypassnro/4fc44554-b416-4ecb-8961-6f79fd55ae0f), or used from Ventoy (with the default option "Bypass online account requirement when install Windows 11" enabled): When the "Let's connect you to a network" shows up, the "I don't have internet" button, and the "Next" button, shows up. But the "I don't have internet" button disapears after 0.5-1 second. I've never heard of this before. Without the OOBE\BYPASSNRO method, the "I don't have internet" button didn't show up even for a second just to confirm that the OOBE\BYPASSNRO actually caused the "I don't have internet" to display for a second earlier.

The only workaround for me was to unplug the network cable during the installation.

**Comment by davidhedlund** [comment]
> ### Official FAQ
> 
>     * [x]  I have checked the official FAQ.
> 
> 
> ### Ventoy Version
> 
> 1.0.86
> ### What about latest release
> 
> Yes. I have tried the latest release, but the bug still exist.
> ### Try alternative boot mode
> 
> Yes. I have tried them, but the bug still exist.
> ### BIOS Mode
> 
> UEFI Mode
> ### Partition Style
> 
> GPT
> ### Disk Capacity
> 
> 16GB
> ### Disk Manufacturer
> 
> _No response_
> ### Image file checksum (if applicable)
> 
> None
> ### Image file download link (if applicable)
> 
> _No response_
> ### What happened?
> 
> I install Windows 11 but can't not bypasses the online account requirement of Windows 11 in spite of opening VTOY_WIN11_BYPASS_NRO but not working

* https://github.com/ventoy/Ventoy/issues/2630

**Comment by davidhedlund** [comment]
> ### Official FAQ
> 
>     * [x]  I have checked the official FAQ.
> 
> 
> ### Ventoy Version
> 
> 1.0.86
> ### What about latest release
> 
> Yes. I have tried the latest release, but the bug still exist.
> ### Try alternative boot mode
> 
> Yes. I have tried them, but the bug still exist.
> ### BIOS Mode
> 
> UEFI Mode
> ### Partition Style
> 
> GPT
> ### Disk Capacity
> 
> 16GB
> ### Disk Manufacturer
> 
> _No response_
> ### Image file checksum (if applicable)
> 
> None
> ### Image file download link (if applicable)
> 
> _No response_
> ### What happened?
> 
> I install Windows 11 but can't not bypasses the online account requirement of Windows 11 in spite of opening VTOY_WIN11_BYPASS_NRO but not working

I didn't even succeed with this without Ventoy. When I installed Win11_22H2_EnglishInternational_x64v2.iso on a USB flash drive, booted it and selected Windows Home during the installation, and then pressed Shift + F10 and typed OOBE\BYPASSNRO (https://answers.microsoft.com/en-us/insider/forum/all/set-up-windows-11-without-internet-oobebypassnro/4fc44554-b416-4ecb-8961-6f79fd55ae0f)

When the "Let's connect you to a network" shows up, the "I don't have internet" button, and the "Next" button, shows up. But the "I don't have internet" button disapears after 0.5-1 second. I've never heard of this before. Without the OOBE\BYPASSNRO method, the "I don't have internet" button didn't show up even for a second just to confirm that the OOBE\BYPASSNRO actually caused the "I don't have internet" to display for a second earlier. The only workaround for me was to unplug the network cable during the installation.

**Comment by davidhedlund** [comment]
> NB: Network MUST be temporarily disabled or unplugged for the local account creation to be proposed

* https://github.com/ventoy/Ventoy/issues/2630
