### ISSUE TITLE
添加【更正分区表】功能

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#2129]
添加【更正分区表】功能

如果安装介质的分区表有细微错误，那么 Ventoy将无法启动。
需要使用 DiskGenius 或者 Gparted 等软件 更正分区表 以后，才能启动 Ventoy。

希望可以给 Ventoy 添加【更正分区表】的功能，在挂载 整个安装介质之前，发现分区表有错误以后，更正分区表以后再启动 Ventoy。

**Comment by ventoy** [comment]
一般更新一下Ventoy可以修复。

**Comment by 1457384613gh** [comment]
Grub启动微内核，用内核命令更正分区表，可以吗？

**Comment by ventoy** [comment]
在bootloader层面修复分区表有几方面的限制：
1. Legacy BIOS模式下可能BIOS有访问限制，访问不了GPT的backup表
2. 某些BIOS可能在boot阶段会设置磁盘只读。

所以修复分区表最好是启动系统之后在系统下修复。不一定是启动一个真正的系统，启动一个精简的PE，在PE内修复更简单。

**Comment by 1457384613gh** [comment]
> 那你们可以给Ventoy添加一个Linux内核。

**Comment by ventoy** [comment]
这不是Ventoy的工作。你在U盘里放一个就行了。

**Comment by 1457384613gh** [comment]
> 这不是Ventoy的工作。 
> 

又不是不可以。

Super Grub 2 还不是有个 Linux 内核， 便于开发更多功能。

**Comment by ventoy** [comment]
那你可以把 super grub2 ISO文件放Ventoy U盘里面就行了。
或则你自己拿 ubuntu或则redhat的内核+initrd定制一个ISO文件放Ventoy U盘里面就行了。
或则你找个WinPE的ISO文件或WIM文件放在Ventoy U盘里面就行了。

你也说了，分区表有问题的时候，Ventoy是无法启动的，这个地方Ventoy做再多也没用啊。
你只能启动一个本机硬盘里面的grub，这个时候Ventoy U盘里的任何东西都是普通文件了。剩下的问题就是你去研究如何在标准grub下启动 Linux的系统/WinPE的系统等。
研究好了，这些命令写到一个配置文件里，也放到Ventoy U盘，下次在grub下直接 configfile xxxxx 就行了。

**Comment by 1457384613gh** [comment]
弄个 BIOS boot partition，或者 Kernel写进一个分区里，先加载 BIOS boot partition 检查分区表错误，再加载 VTOYEFI。

**Comment by ventoy** [comment]
这样做问题太多，而且也解决不了所有问题。分区表搞坏有很多种情况，要是MBR里面的启动代码搞坏了，Legacy BIOS模式下不管怎么弄都起不来。
