### ISSUE TITLE
[issue]: Indian Languages text aren't rendered properly in boot ISO

### ISSUE THREAD

**Issue by kbdharun** [ventoy/Ventoy#2131]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.86

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

16GB

### Disk Manufacturer

Sandisk

### Image file checksum (if applicable)

No.

## Steps to Reproduce

- Boot into Ventoy ISO.
- Press `L` 
- Select Any Indian language such as Tamil or Bengali or Hindi. There is irregular cell spacing between the characters.

My suggestion would be to bundle and use a compatible font along with ventoy. If you need suggestions feel free to ask me.

For the context of this issue: I translate components to Tamil here, I had seen the translated version of the program before in Tamil but not the boot side just checked it today and found this issue.

@ventoy Can you look into this. Thanks in advance.

**Comment by kbdharun** [comment]
Also, there is an empty field below `Chinese Traditional`

**Comment by ventoy** [comment]
The empty line has been fixed.
Ventoy uses a unicode font which match most of the cases.
If it doesn't fit some language, then uses can use customize theme and add fonts through theme plugin.
