### ISSUE TITLE
[issue]: Impersonation, violation of license and more.

### ISSUE THREAD

**Issue by KortaPo** [ventoy/Ventoy#2136]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.84

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

8GB

### Disk Manufacturer

Sandisk

### Image file checksum (if applicable)

None

### What happened?

An app in google play store has been impersonating and trying to profit from this project, and according to the users they believe that this app is the official ventoy application for android, which it is not.

https://play.google.com/store/apps/details?id=com.mixapplications.ventoy_app

There was an issue regarding this application before, **however**, the case is worse, as they are blatantly trying to profit from their pay to use coin scheme.

If you download the app and use, you will be immediately met with, 'you need to use coins', which only can be obtained by either watching ads or buying it with real money, plus the app is horribly slow and buggy, previously they were blasting ads in your screen whenever you did an operation in this app and now its even worse, they are trying to profit and because the app is poorly made, it also is damaging the reputation of the official ventoy software.

I hope something can be done for this, asap.

![20230105_134610](https://user-images.githubusercontent.com/70193867/210733195-f313c347-1c0f-4be0-944e-742b1b7aae16.jpg)

![20230105_134620](https://user-images.githubusercontent.com/70193867/210733234-1b332503-d8e9-4844-b7fc-f650a8fc8e10.jpg)

This is absolutely disgusting.

**Comment by wiz64** [comment]
@ventoy 
You can try mailing the dev to remove this :
![image](https://user-images.githubusercontent.com/67432394/211046169-0487339d-cf39-40f9-afa6-dfaf8c379814.png)
(i don't believe he's gonna remove that)

**Comment by KortaPo** [comment]
Any updates regarding this? The app is still available in playstore.

**Comment by Galacticai** [comment]
I see now Ultimate USB, Rufus, and Ventoy which are all by MixApplications on play store

They ask for coins which are gained by $$$ or really long advertisements 

I reported them but I have no idea if anything will happen.

**Comment by Islam-Darwish** [comment]
Hi all , this is mixapplications owner 
First of all thank Ventoy developers for this great project…
I would like to clarify some points:
1- My source code (Android application) is not related to original Ventoy project, I just using binary files that included in windows release That who does not fall under  GPL license, so that my project is not open source.

2- As for naming and user thinking it’s official app I changed it’s title to “Ventoy (Unofficial)”.

3- As for coins system this app was totally free with some popup ads but users reported it many times to google for (Disruptive Ads) and google suspended it more than one time so I created this annoying system i am sorry for that but it was the only way for me. (Users forced me to do that)

4- Finally if you don’t like it just uninstall it there is no use for reporting me

**Comment by Islam-Darwish** [comment]
> @Islam-Darwish
> 
> > Hi all , this is mixapplications owner First of all thank Ventoy developers for this great project… I would like to clarify some points: 1- My source code (Android application) is not related to original Ventoy project, I just using binary files that included in windows release That who does not fall under GPL license, so that my project is not open source.
> > 2- As for naming and user thinking it’s official app I changed it’s title to “Ventoy (Unofficial)”.
> > 3- As for coins system this app was totally free with some popup ads but users reported it many times to google for (Disruptive Ads) and google suspended it more than one time so I created this annoying system i am sorry for that but it was the only way for me. (Users forced me to do that)
> > 4- Finally if you don’t like it just uninstall it there is no use for reporting me
> 
> 1. GPL license also applies to compiled binaries, if the source code of those components are under GPL. Since you're using the binary files included in windows release, they also fall under GPL.
> 2. I appreciate the renaming thing.
> 3. Why do you need to force people to watch ads to use it ? can't a simple banner on bottom be enough ?
>    You're trying to take advantage of Ventoy developers' hard work and make money off of it. Honestly dude it's not gonna bag you enough money to survive from shady apps like this. Its you forcing users to watch ads to try out your app.
>    I understand that you've done some work on it as well but its not ethical to do this.
> 4. If something is fishy about your app, people have every right to report stuff if anything is fishy. The report button exists for a reason.
>    Focus on user satisfaction rather than just saying "if you don't like it just uninstall it". It's hilarious.
>    If you really want to be a successful, quality and professional app developer, follow the ethics.
> 
> If you support Ventoy development, make a donation instead please.

(1)The binary that I'm using is precompiled without modifications, so the source code is already available. Also, it is not a dependency for my codes to work. I only write it as is to the drive.

(3)Thank you for your suggestions. I'll reconsider the business model of the application and how I can improve the user experience.

**Comment by wiz64** [comment]
@Islam-Darwish 
If it's a perfect implimentation of ventoy on android, maybe you should open source it, it will be beneficial for the entire open source community and might help you land up a better job as you will have a good project.
