### ISSUE TITLE
Uhhhh...

### ISSUE THREAD

**Issue by TF21045** [ventoy/Ventoy#2138]
### Official FAQ

- [x] I have checked the official FAQ.

### Ventoy Version

1.0.86

Uhh, I just want to ask, not really an issue but I accidentally installed Ventoy on my secondary SSD, and I have no idea how to remove it without completely formatting the entire thing
![image](https://user-images.githubusercontent.com/53613828/210935676-526e0e7a-8c53-46b9-be80-57c436f59153.png)

**Comment by ventoy** [comment]
You can just delete the second partition (32MB VTOYEFI partition) by diskpart or other third part software.
