### ISSUE TITLE
after take off error (0x1A)

### ISSUE THREAD

**Issue by mhmad240** [ventoy/Ventoy#2142]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.87

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

32

### Image file checksum (if applicable)

None

### What happened?

A bug happened!
![WhatsApp Image 2023-01-08 at 8 50 27 AM](https://user-images.githubusercontent.com/67698326/211182895-34a79755-eb8f-4c91-8eed-2dc10203548f.jpeg)

**Comment by ventoy** [comment]
Please refer:
https://www.ventoy.net/en/doc_secure.html
