### ISSUE TITLE
菜单界面无法通过方向键选择系统

### ISSUE THREAD

**Issue by bigStuart** [ventoy/Ventoy#215]
在windows中制作的，版本是 ventoy-1.0.12-windows      
在电脑中设置u盘启动可以看到菜单、但点击回车、上下方向键没反应是什么情况呢？电脑是比较旧的电脑

**Comment by ventoy** [comment]
你用个外接的USB键盘试试

**Comment by bigStuart** [comment]
嗯、可以了、多谢啦
