### ISSUE TITLE
VentoyPlugson.exe: Error, ventoy\plugson.tar.xz does not exist

### ISSUE THREAD

**Issue by izakc-spc** [ventoy/Ventoy#2150]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.87

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

None

### What happened?

I wanted to install Plugson on my Ventoy drive, but as soon as the UAC window closed it brings an error saying: ventoy\plugson.tar.xz does not exist. I have downloaded the newest release and i ve also tried the x64 version, there didn't even opened a window.
![image](https://user-images.githubusercontent.com/95540550/211463256-1e3a03cb-6938-419f-94ee-007bb0103bd0.png)

**Comment by ventoy** [comment]
Did you have `ventoy\plugson.tar.xz` file after you decompress the package?

1. Download the latest release from https://github.com/ventoy/Ventoy/releases/download/v1.0.87/ventoy-1.0.87-windows.zip
2. After download, decompress it, then you should see the `ventoy\plugson.tar.xz`  file.
