### ISSUE TITLE
[issue]: Disk structure selection and in Command Line installation

### ISSUE THREAD

**Issue by abdullah-erturk** [ventoy/Ventoy#2151]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.87

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

64

### Disk Manufacturer

Kingston

### Image file checksum (if applicable)

None

### What happened?

Can you provide disk structure selection feature (NTFS, FAT32 or exFAT) in command line installation?

Example:
Ventoy2Disk.exe VTOYCLI /I /Drive:D: /NTFS

Also, can you share the latest version of /grub/i386pc/core.img here?

By default this file is not in the /grub/i386pc/ folder.

**Comment by ventoy** [comment]
Ventoy2Disk.exe CLI only provides basic option. Just reformat the drive after install, it's very simple.
Use core.img to chainload Ventoy is not officially supported, so I don't provide it anymore. If you want to use it, you can download the source code and rebuild it and get it.

**Comment by crasadure** [comment]
Hi @ventoy 
Our friend Abdullah wants to have Ventoy installed on the flash memory using the CMD command system using the original files of grub2fm and ventoy. During the installation, it plans to have automatic installation by giving the "Disk Number" or "Disk drive" as a parameter, without the need for a GUI screen. The link to his project is below. 

Project Link : https://www.tnctr.com/topic/1174848-ventoy-grub2fm-multiboot-revizyon-6-orijinal-dosyalarla/
Project Download Link: https://disk.yandex.com.tr/d/PY0dDz5ikKvywg

You can understand what I mean by looking at the source code of the project. I would be glad if you can help with this. Have a nice day :)

**Comment by steve6375** [comment]
https://github.com/ventoy/Ventoy/blob/master/INSTALL/grub/i386-pc/core.img
any good?

**Comment by crasadure** [comment]
> https://github.com/ventoy/Ventoy/blob/master/INSTALL/grub/i386-pc/core.img any good?

İt is not very important @steve6375 ... We can create core.img file building Ventoy project..
but /NTFS or /FAT32 or /EXFAT parameter is very important for installation from cmd interface
he wants to add /NTFS and /FAT32 options  Optional Parameters to CMD command system
https://www.ventoy.net/en/doc_windows_cli.html
![optional parameters](https://user-images.githubusercontent.com/54566818/211514352-d50b1fba-cf1e-4bef-807b-7d52d800422d.jpg)

**Comment by steve6375** [comment]
Just run the FORMAT command afterwards - what the problem?

**Comment by crasadure** [comment]
> Just run the FORMAT command afterwards - what is the problem?

1.Install Ventoy
2.Then reformat the ventoy partition of the disk

Instead of doing this, I think it would be more logical to give the format of the Ventoy score as a parameter during Ventoy setup.

**Comment by abdullah-erturk** [comment]
Added Command Line interface support for Ventoy in Grub2FM & Ventoy MultiBoot project 👍😊

[https://github.com/abdullah-erturk/Ventoy-Grub2FM-Multiboot-With-Original-Files
](url)
Is it possible to add command line support for the Ventoy update process?

In my project, the formatted installation is completely done through the command interface, but the update process is done through the Ventoy2Disk.exe interface.
