### ISSUE TITLE
[issue]: Can't format Drive (MediaRange MR1902)

### ISSUE THREAD

**Issue by psflachglas** [ventoy/Ventoy#2155]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.87

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

128GB

### Disk Manufacturer

MediaRange (MR1902) 
13-1902-20200927

### Image file checksum (if applicable)

No.

### What happened?

When I try to format my USB stick I get an error message:

![image](https://user-images.githubusercontent.com/94624822/211775076-9b5bcb90-76a0-4601-820b-68e6697c87bc.png)

### Troubleshooting

I have already tried the following:
- Ventoy versions, 1.0.87, 1.0.85, 1.0.75
- In Windows 11 and Windows 10 64x
- With Rufus and *.vtsi -> Displayed as RAW
- With the VentoyLiveCD -> Displayed as RAW

With the VentoyLiveCD the disk can be formatted.
In Windows computer management, the volume is then displayed as "RAW".

See Log File

[log.txt](https://github.com/ventoy/Ventoy/files/10391027/log.txt)

### Rufus Message

***This drive has a non-standard sector size.***

![image](https://user-images.githubusercontent.com/94624822/211778333-33b9a2ea-82cd-4ab4-9d4e-1066e008648c.png)

**Comment by ventoy** [comment]
Your USB stick is 4K native (logical sector size and physical sector size are both 4096)
Currently Ventoy doesn't support 4K native disk.

**Comment by psflachglas** [comment]
Thank you for the fast Response.
