### ISSUE TITLE
[issue]: 显示不了全部磁盘 

### ISSUE THREAD

**Issue by tonycody** [ventoy/Ventoy#2156]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.87

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

1024GB

### Image file checksum (if applicable)

None

### What happened?

![image](https://user-images.githubusercontent.com/6773121/211946712-1ec341d8-4b55-45b0-b406-b8d16b699955.png)

不能显示所有磁盘，明明在磁盘0安装的Ventoy，但设备列表中没有该磁盘。
 
![image](https://user-images.githubusercontent.com/6773121/211946827-cf505206-66e7-4f0a-b5af-01fabab69a26.png)

**Comment by ventoy** [comment]
应该是被哪个进程占住了，Ventoy获取不到读写控制权，就不会列出来。
下面这些进程都会引起这种问题，可以看看有没有。
```
1. Paragon ExtFS for Windows
2. ParagonMounter
3. DokanMounter
4. ext2fsd
5. extservice
6. DiskGenius
7. DSAService.exe (Intel® Driver & Support Assistant).
```

**Comment by tonycody** [comment]
> 应该是被哪个进程占住了，Ventoy获取不到读写控制权，就不会列出来。 下面这些进程都会引起这种问题，可以看看有没有。
> 
> ```
> 1. Paragon ExtFS for Windows
> 2. ParagonMounter
> 3. DokanMounter
> 4. ext2fsd
> 5. extservice
> 6. DiskGenius
> 7. DSAService.exe (Intel® Driver & Support Assistant).
> ```

DSAService 导致的，这个应该做个提示才对，否则大多数用户一脸蒙啊。应该在打开时给个提示，让结束相关进程！

**Comment by ventoy** [comment]
后面会考虑增加
