### ISSUE TITLE
[issue]: 1.0.87 won't boot .vhdx files, previous version does

### ISSUE THREAD

**Issue by aarondpriest** [ventoy/Ventoy#2157]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.87

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

512GB

### Disk Manufacturer

SanDisk Extreme Pro

### Image file checksum (if applicable)

Yes.

### What happened?

I have a Win11.vhdx file that boots fine with Ventoy 1.0.84 through 1.0.86 (and many versions before, but I just tested these three specifically today), however it does not boot with 1.0.87. I'm getting "0xc000000e There is an invalid object in the Boot Configuration Data store" for an error. Booting via Grub2FM also works fine, even on 1.0.87, but not via ventoy_vhdboot.img. I would guess that 1.0.87 introduced some conflict with ventoy_vhdboot.img?

**Comment by ventoy** [comment]
This is a bug in 1.0.87 and has been fixed, you can test this CI release:
https://github.com/ventoy/Ventoy/actions/runs/3879364570
https://www.ventoy.net/en/doc_github_ci.html

**Comment by aarondpriest** [comment]
Thank you!!!

**Comment by ventoy** [comment]
Fixed in 1.0.88
