### ISSUE TITLE
[issue]: fix (MBR check failed) via vtoy2disk.exe

### ISSUE THREAD

**Issue by anwar-alsilwy** [ventoy/Ventoy#2158]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.87

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

1 TB

### Disk Manufacturer

Samsung SSD

### Image file checksum (if applicable)

None

### What happened?

Sometimes Ventoy bootloader or MBR corrupt suddenly
And this message appears without any reason:

![209266730-6eaf4132-047c-48f7-9d21-9ea02020e3a0](https://user-images.githubusercontent.com/71539261/212345591-88c334a0-fbe8-4155-96b8-3fe0b915bb82.png)

We need feature to repair  corrupted MBR or  Ventoy bootloader via vtoy2disk.exe without needing to reinstall or update usb drive.

**Comment by ventoy** [comment]
update can fix both corrupted MBR and corrupted 32MB VTOYEFI partition and update is safe operation.
So you can do a self update (for example update from 1.0.88 to 1.0.88) to fix it.
