### ISSUE TITLE
FATAL: Failed to mount block device of live image

### ISSUE THREAD

**Issue by ivanristic** [ventoy/Ventoy#216]
Machine: HP Probook 6570b
Bios : F70
ISO: Fedora-Workstation-Live-x86_64-32-1.6.iso
Ventoy version: 1.0.12

dracut: FATAL: Failed to mount block device of live image
dracut: Refusing to continue
dracut-initqueue[1024]: mount: /run/initramfs/live: unknown filesystem type 'swap'.
reboot: System halted

**Comment by ivanristic** [comment]
I think it's related to issue #72

**Comment by ventoy** [comment]
Can you try ventoy-1.0.13?

**Comment by ivanristic** [comment]
I have tested ventoy-1.0.13.

Fedora-Workstation-Live-x86_64-32-1.6.iso - I have same problem on HP. I got my hands on ThinkPat T460s and same image boots OK.

ClearOS - clear-33320-live-desktop.iso - Boots OK on HP

ubuntu-20.04-desktop-amd64.iso - Fails to boot on HP. 
![20200617_080847](https://user-images.githubusercontent.com/14258935/84879725-de9d1280-b08b-11ea-9244-5c3517b92611.jpg)
![20200617_110559](https://user-images.githubusercontent.com/14258935/84879739-e361c680-b08b-11ea-81fd-db1cd58b6597.jpg)

**Comment by drescherjm** [comment]
I had similar with a modified system rescue cd 6.1.3 that adds zfs support. The boot could not find the filesystem because /dev/disk/by-label did not have a link for the disk label SYSRCDV613 which was mounted on /dev/mapper/ I believe the problem is udev is not searching for devices in /dev/mapper

I was able to get around this and continue the boot after manually making the symbolic link.

**Comment by ivanristic** [comment]
I have tested ventoy-1.0.14. and have same problem

**Comment by fjen** [comment]
Try UEFI mode. see https://github.com/ventoy/Ventoy/issues/72#issuecomment-655476284

**Comment by ivanristic** [comment]
It works in UEFI mode. I'm closing this issue

**Comment by lynndixon** [comment]
Still seeing this on my Fedora and RHEL iso's even on an older machine that does not have secureboot / UEFI.  Howver, I only see them on a 256gb stick, not a 64 gb stick.
