### ISSUE TITLE
[issue]: /FS: Parameter

### ISSUE THREAD

**Issue by abdullah-erturk** [ventoy/Ventoy#2162]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.87

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

16

### Disk Manufacturer

Kingston

### Image file checksum (if applicable)

None

### What happened?

I'm writing a script for the latest version of Ventoy, but I ran into a problem.

Does the /FS: parameter not support UDF?

![Ekran görüntüsü_20230113_202209](https://user-images.githubusercontent.com/54866587/212381653-bd6b36b4-f61c-4858-b008-29f77b7ef417.png)

**Comment by ventoy** [comment]
Fixed.
Try this CI release:  https://github.com/ventoy/Ventoy/actions/runs/3918820790
https://www.ventoy.net/en/doc_github_ci.html
