### ISSUE TITLE
[issue]: doesnt support 4k?

### ISSUE THREAD

**Issue by jinfagang** [ventoy/Ventoy#2173]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.87

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

128G

### Disk Manufacturer

vgreg

### Image file checksum (if applicable)

No.

### Image file download link (if applicable)

https://user-images.githubusercontent.com/21303438/212795605-fd450abd-452b-4e7e-961e-1d3b29ed3248.png

### What happened?

A bug happened!

![image](https://user-images.githubusercontent.com/21303438/212795605-fd450abd-452b-4e7e-961e-1d3b29ed3248.png)

i want to know why? and how to fix it?

**Comment by ventoy** [comment]
In Ventoy's code, there are many places presuppose that the disk sector size is 512.
It's a lot of work to modify all the code to support 4K native disk.
So currently Ventoy does not support 4k native disk.
It will be supported someday, but not in the near future.

**Comment by jinfagang** [comment]
@ventoy  thanks for reply.
so it means only old disk with 512 sector size can be supported? These new disk hard to support/?

**Comment by easycodesnipper** [comment]
> In Ventoy's code, there are many places presuppose that the disk sector size is 512. It's a lot of work to modify all the code to support 4K native disk. So currently Ventoy does not support 4k native disk. It will be supported someday, but not in the near future.

@ventoy
Since you mentioned a lot of work to modify... 
Can you please identify where those codes have to be modified? 
Don't ignore contribution from  community, perhaps we can help to fix this bug, since you know that currently most of U disk sector size is 4K.

**Comment by ledlamp** [comment]
I just tried to use a usb hard drive and got this message. Disappointing. It's the only thing I have right now. I think this issue should be left open as long as it remains an issue with ventoy.

**Comment by ledlamp** [comment]
Well, it turns out device can't boot 4k anyway. So this does not matter.

**Comment by ledlamp** [comment]
Wait, my newer laptop can.

**Comment by juanpide** [comment]
I can use Ventoy with 4K with an external SSD disk but not with a USB drive ZX.
I have tried ntfs, fat32, exFAT, UDF and modifying cluster size.
I have also tried with an unpartitioned disk and with a manually partitioned one.

**Comment by Armi1P** [comment]
> In Ventoy's code, there are many places presuppose that the disk sector size is 512. It's a lot of work to modify all the code to support 4K native disk. So currently Ventoy does not support 4k native disk. It will be supported someday, but not in the near future.

It must be like trillions of lines where this is the case, it's been 3 and a half years and it still isn't fixed.

**Comment by XaTTa6bl4** [comment]
And why is this issue closed? Similar issues are regularly reported here, marked as duplicates, and then closed. If a problem is reported by users, then it should be open and awaiting resolution. Or is there no plan to ever resolve this issue?
