### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by Lamuier** [ventoy/Ventoy#2175]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

openEuler-22.09-everything-x86_64-dvd.iso

### Image file checksum type

SHA256

### Image file checksum value

ea6116a645580cae87ecc061c0a821941fc1cb70edce86257e8da0e2925a91ce

### Image file download link (if applicable)

https://repo.openeuler.org/openEuler-22.09/ISO/x86_64/openEuler-22.09-everything-x86_64-dvd.iso

### Test environment

Lenovo Thinkpad E460

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
