### ISSUE TITLE
[Success Image Report]: Drauger OS 7.6

### ISSUE THREAD

**Issue by Batcastle** [ventoy/Ventoy#2178]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

Drauger_OS-7.6-AMD64.iso

### Image file checksum type

SHA256

### Image file checksum value

d1d6db424cd561adcb567be23835472fd7c1fd0e86032ae0246c58427528feb

### Image file download link (if applicable)

https://draugeros.org/thank_you

### Test environment

Lenovo ThinkBook 15 G4 ABA

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
