### ISSUE TITLE
[issue]: update documentation

### ISSUE THREAD

**Issue by InfoLibre** [ventoy/Ventoy#2183]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

latest

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32

### Image file checksum (if applicable)

None

### What happened?

On https://github.com/ventoy/Ventoy/blob/master/DOC/BuildVentoyFromSource.txt, https://www.uclibc.org/downloads/binaries/0.9.30.1/mini-native-x86_64.tar.bz2 is used. But there is a virus in it : https://www.virustotal.com/gui/file/b3768ddc9d82c9ca9d313b1de1d16902b1d8fd58f886253aff961a8ade4fc6e9?nocache=1

Do you still use this version of mini-native? If not, could you update DOC/BuildVentoyFromSource.txt?

**Comment by ventoy** [comment]
Yes. This version of mini-native is still used.
This mini-native is only used to build the file `64h` https://github.com/ventoy/Ventoy/blob/master/IMG/cpio_x86/ventoy/busybox/64h
The files detected as virus are not included in Ventoy release package.

The file `64h` which was built by mini-native is not detected as virus. 
https://www.virustotal.com/gui/file/306abe0a74bc2ae110334e29151ef306de4e71d5f8ab3ec5321c02d9bb3363ed
