### ISSUE TITLE
Error booting  ventoy-1.0.88-livecd.iso 

### ISSUE THREAD

**Issue by nixfreak** [ventoy/Ventoy#2193]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.88

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

0GB (Live ISO)

### Image file checksum (if applicable)

None

### What happened?

Trying to run ISO in VBox (VirtualBox) 
Version: 7.0 w/ Extensions

![image](https://user-images.githubusercontent.com/3707258/214642343-15aca86d-c529-41cf-97ac-7fb5362317ce.png)

**Comment by ventoy** [comment]
1. Did you checksum the ISO file after download?
```
SHA256
ventoy-1.0.88-livecd.iso:      00e6bca25c17a97b92b22aa876ea56e92f8a9216fa92ab2e1c93373498509f1e
```

2. Can the ISO file boot OK in QEMU/VMWARE ?
3. Can the ISO file boot OK in physical machine. (boot by Ventoy).
