### ISSUE TITLE
[issue]: Tuxedo WebFAI Stick not booting

### ISSUE THREAD

**Issue by powerriegel** [ventoy/Ventoy#2194]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.88

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

16

### Disk Manufacturer

Kingston

### Image file checksum (if applicable)

No.

### Image file download link (if applicable)

https://www.tuxedocomputers.com/webfai/webfai-nb/ipxe-stick-webfai-nb_current.iso

### What happened?

No bootfile found for UEFI
Maybe the image does not support  x64_UEFI

It does. When booting a stick without Ventoy, the image boots on the same laptop.

**Comment by ventoy** [comment]
Alough the file has `.iso` suffix, but it is not an ISO file at all.
Change the file suffix from `.iso` to `.img` and retry. (`ipxe-stick-webfai-nb_current.img`)

**Comment by powerriegel** [comment]
Worked like a charm! Perfect!
