### ISSUE TITLE
[Success Image Report]: Windows Vista x64

### ISSUE THREAD

**Issue by CloudyShane** [ventoy/Ventoy#2205]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.84

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

en_windows_vista_sp2_x64_dvd_342267.iso

### Image file checksum type

SHA256

### Image file checksum value

EDF9F947C5791469FD7D2D40A5DCCE663EFA754F91847AA1D28ED7F585675B78

### Image file download link (if applicable)

http://rutracker.org/forum/viewtopic.php?t=3543471

### Test environment

HP Pavilion G7

### More Details?

This image file booted successfully in Ventoy. No problems whatsoever.

**Comment by ventoy** [comment]
Thanks!
