### ISSUE TITLE
[issue]: Menu bar issue

### ISSUE THREAD

**Issue by YALdysse** [ventoy/Ventoy#2209]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.88

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

42 GiB

### Disk Manufacturer

Seagate

### Image file checksum (if applicable)

No.

### What happened?

The Menu bar with hotkeys goes beyond the visible area in Russian language.
Sorry for bad photo. 
![screenshot_001](https://i.ibb.co/dLSTTgb/20230202-153749.jpg)

**Comment by ventoy** [comment]
Some language is too long for the  screen width.
There are two method:
1. Use some short abbreviations
2. Use higher resolution.   `F5 ---> Resolution Configuration`

**Comment by crasadure** [comment]
Hotkey Tips[Hotkey Tips](https://www.ventoy.net/en/plugin_theme.html) 

Add these following hbox definitions to your new theme.txt to show the hotkey tips. You can also change the position and color.
![Screenshot_20230202-173152_Samsung Internet](https://user-images.githubusercontent.com/54566818/216353093-aedcab0b-9666-4967-97c0-71d40b19ed38.jpg)
