### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by lzb-libra** [ventoy/Ventoy#2210]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

Legacy BIOS Mode

### Partition Style

GPT

### Image file name

deepin-desktop-community-20.8-amd64.iso

### Image file checksum type

SHA256

### Image file checksum value

9e6c940d9aa2750220eb011287502fb059dcfc3a8b68c750ff2808ccbc003bc7

### Image file download link (if applicable)

https://www.mediafire.com/folder/zx44yz8yigy9m/deepin_20.8

### Test environment

惠普246笔记本电脑

### More Details?

The first use after starting is not smooth

**Comment by ventoy** [comment]
Thanks!
