### ISSUE TITLE
[Success Image Report]: Linux Mint Cinnamon 21.1 64-bit

### ISSUE THREAD

**Issue by queengooborg** [ventoy/Ventoy#2214]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

linuxmint-21.1-cinnamon-64bit.iso

### Image file checksum type

SHA256

### Image file checksum value

2df322f030d8ff4633360930a92d78829d10e515d2f6975b9bdfd1c0de769aca

### Image file download link (if applicable)

https://linuxmint.com/edition.php?id=302

### Test environment

Framework Laptop Intel 11th Gen

### More Details?

This image file booted successfully in Ventoy.  There were no tweaks required to boot the ISO.

**Comment by ventoy** [comment]
Thanks!
