### ISSUE TITLE
[issue]: Cannot boot file in UEFI mode

### ISSUE THREAD

**Issue by bindoet** [ventoy/Ventoy#2217]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.88

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

8gb

### Disk Manufacturer

Generic Flash

### Image file checksum (if applicable)

Yes.

### What happened?

Whenever I boot into UEFI mode, my ISO fails to boot; no boot file is found. Maybe the image doesn't support x64 UEFI.

I've tried Windows 7, 8.1, 10, and 11, and it doesn't work in UEFI mode, but it works perfectly in legacy mode (mbr). 

I've chosen NTFS for the partition and GPT in the Ventoy app, and just tried to boot in normal mode.

**Comment by steve6375** [comment]
Which iso exactly, e.g. which win 10 iso?

**Comment by bindoet** [comment]
> Which iso exactly, e.g. which win 10 iso?

Win 10 22H2 official from microsoft website

**Comment by steve6375** [comment]
32-bit or 64-bit?

**Comment by bindoet** [comment]
> 32-bit or 64-bit?

all of my file is 64 bit

**Comment by ventoy** [comment]
1. Can any linux ISO boot OK? For example,  `ubuntu-22.04.1-desktop-amd64.iso`
2. Try `Wimboot mode` for Windows ISO.

**Comment by bindoet** [comment]
Perhaps my flash drive is failing; it works intermittently.
