### ISSUE TITLE
[Success Image Report]: MAXDOS

### ISSUE THREAD

**Issue by OkayJim** [ventoy/Ventoy#2219]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

MAXDOS.IMG

### Image file checksum type

SHA256

### Image file checksum value

4F6499AFD186A3BF67207B1484320898DFD06B54939CFBF154F1B7ACB2285274

### Test environment

Gigabyte B85

### More Details?

1. Must set as Mendisk mode.
2. Must use BIOS Mode to boot this image, UEFI didn't support DOS.

**Comment by ventoy** [comment]
Thanks!

**Comment by Cathgao** [comment]
Where to get it?

**Comment by ruthan** [comment]
Is there some english version of Maxdos? It seems chinese only..
