### ISSUE TITLE
[Success Image Report]: ESET SysRescue Live

### ISSUE THREAD

**Issue by queengooborg** [ventoy/Ventoy#2220]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

eset_sysrescue_live_enu.iso

### Image file checksum type

SHA256

### Image file checksum value

5d4215a240c875e53457269f1971459423f9094150e855e9186af0e0a6177934

### Image file download link (if applicable)

https://www.eset.com/int/support/sysrescue/#c66026

### Test environment

Dell Latitude E5530 non-vPro

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
