### ISSUE TITLE
[issue]: Unable to install openSUSE MicroOS

### ISSUE THREAD

**Issue by kojq** [ventoy/Ventoy#2223]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.88

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://download.opensuse.org/tumbleweed/iso/openSUSE-MicroOS-DVD-x86_64-Current.iso

### What happened?

Selecting the image from the Ventoy menu results in directly entering GRUB CLI rather than the install screen. This may affect other openSUSE distributions such as Leap, Tumbleweed, and Leap Micro.

**Comment by ventoy** [comment]
Please checksum the ISO file in Ventoy menu as in the following gif to make sure that the ISO file was not corrupted during copy to the USB.
Take a screenshot of the result and upload here.

https://www.ventoy.net/static/img/filechecksum.gif

**Comment by kojq** [comment]
It seems to be that the iso was corrupted.
