### ISSUE TITLE
[issue]: Unable to install Fedora Silverblue Rawhide Build

### ISSUE THREAD

**Issue by kojq** [ventoy/Ventoy#2225]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.88

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Silverblue/x86_64/iso/

### What happened?

Booting the image from the Ventoy menu results in a stuck process and may apply to other Fedora distributions.

**Comment by ventoy** [comment]
Please checksum the ISO file in Ventoy menu as in the following gif to make sure that the ISO file was not corrupted during copy to the USB.
Take a screenshot of the result and upload here.

https://www.ventoy.net/static/img/filechecksum.gif

**Comment by kojq** [comment]
The issue is:

`Job systemd-udev-settle.service/start running` and the iso does not boot.

I'm not sure if this is related to Ventoy, as I have not yet tried another USB solution.

**Comment by ventoy** [comment]
With the latest CI release:
https://github.com/ventoy/Ventoy/actions/runs/4211423289
https://www.ventoy.net/en/doc_github_ci.html

I can boot it OK in my laptop in both Legacy BIOS mode and UEFI mode.
![image](https://user-images.githubusercontent.com/59477474/219869795-8560238c-46a6-4382-b9a5-318b86863daf.png)

![image](https://user-images.githubusercontent.com/59477474/219869840-0ddfff62-b68d-4dea-ad77-3ae6ab1a8d5f.png)

**Comment by kojq** [comment]
Okay. I am unable to test at the moment, so you can close the issue. I will reopen or open an issue if I notice anything.

**Comment by kojq** [comment]
As it seems resolved, I have closed this issue, @ventoy.
