### ISSUE TITLE
[issue]: ventoy menu/browser not listing some images

### ISSUE THREAD

**Issue by hgkamath** [ventoy/Ventoy#2228]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.88

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

2Tb

### Disk Manufacturer

Seagate

### Image file checksum (if applicable)

None

### What happened?

A bug happened!

A raw.img.vtoy file (```m02_lnx.raw.img.vtoy```) is not listed in ventoy boot-menu/browser. 
ventoy may be skipping other non-iso image files in the directory. I can't see a pattern/reason.

For example: 
vtoy menu lists ```seaboot_20191118.raw.img.vtoy``` but not ```m02_lnx.raw.img.vtoy``` .
```seaboot_20191118.raw.img.vtoy```  is also bootable

This used to work before and I have in the past booted into this image via ventoy using vtoyboot and all.

### misc info
- 1st partition is ntfs, 1.2 Tb, the filesystem has been fs-checked ```chkdsk /F /V /X E:```
- image is 40GiB raw image with fedora-37 linux installed to it, raw img with gpt, 4 partitions (efisys, biosboot, boot-ext4, root-ext4)
- It is possible to boot into it from qemu from both windows/Linux

### log
```
PS C:\vol\scoop_01\scoopg\apps\ventoy\current> dir E:\transcend\*vtoy


    Directory: E:\transcend


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         1/25/2023   1:53 PM    49861885952 m02_lnx.raw.img.vtoy
-a----         12/3/2022   7:50 PM      352321536 seaboot_20191118.raw.img.vtoy
```

**Comment by ventoy** [comment]
Can it list if you copy it to the Ventoy USB?

**Comment by hgkamath** [comment]
my USB stick is only 8Gb, but I copied the file to first drive (SSD) to two partitions (1) ```hd0, 16, ExFAT``` (2) ```hd0, 17, NTFS```  
Ventoy F2 browser was able to see them in respective partitions but still not in the original location HDD2: ```hd2, 1, NTFS```  
Ventoy was also able to boot them as before. 
However, I still want to place it and have it work where it is in ```E:\transcend``` 

Below is what the directory contains after some filtering
```
PS E:\transcend> dir E:\transcend\ | findstr /v /i checksum | findstr /v /i sha256 | findstr /v /i .txt | findstr /v /i .sh | findstr /v /i changelog


    Directory: E:\transcend


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
da----          1/7/2023   5:42 PM                EFI
da----         9/17/2021   7:09 PM                groot_07
d-----         3/30/2022   9:47 PM                nirsoft
da----         9/17/2021   7:14 PM                System Volume Information
da----         9/17/2021   6:58 PM                ventoy
d-----         3/30/2022   9:45 PM                win11
-a----        12/15/2022   9:02 PM      159383552 alpine-standard-3.17.0-x86_64.iso
-a----          1/4/2022   9:02 PM      906309632 archlinux-2022.01.01-x86_64.iso
-a----         1/15/2022   1:38 AM     1481637888 Bliss-v15.0-Alpha-android_x86_64-OFFICIAL-foss-202112151838-nb-sd-ksu
                                                  -gearlock-ex_vt-console_all-mesa-drivers-crocus.iso
-a----         1/28/2023   8:57 AM     2619355136 cachyos-gnome-linux-230121.iso
-a----        12/15/2022   9:01 PM      380633088 clonezilla-live-3.0.2-21-amd64.iso
-a----        12/12/2022   5:18 PM     2037372928 Fedora-Workstation-Live-x86_64-37-1.7.iso
-a----         11/3/2022   6:04 PM      507510784 gparted-live-1.4.0-6-amd64.iso
-a----         9/17/2021   7:29 PM     3099203584 HBCD_PE_x64_v1.0.2_20210701.iso
-a----          2/9/2023   9:15 PM     6446645248 HBCD_PE_x64_v1.0.2_20210701.vhdx
-a----          1/4/2022   9:19 PM        1339392 hdt-0.5.2.iso
-a----         11/6/2019   7:33 PM      134596608 HP_sp100048_UEFI_Diagnostics-2017.iso
-a----         8/11/2022   7:01 PM          32768 m01_lnx.raw.vlnk.img
-a----         2/10/2023  10:07 AM    49861885952 m02_lnx.raw.img.vtoy
-a----          2/3/2023   4:38 AM        6193152 mt86plus_6.10_64.iso
-a----         8/11/2022   5:58 PM            512 qq1
-a----         8/11/2022   6:01 PM            512 qq2
-a----         8/11/2022   6:13 PM            512 qq3
-a----         8/11/2022   6:01 PM           2407 qw1
-a----         8/11/2022   6:01 PM           2407 qw2
-a----         8/11/2022   6:13 PM           2407 qw3
-a----         8/11/2022   6:08 PM           2407 qw3a
-a----        12/15/2022   9:12 PM      267386880 ReactOS-0.4.14-release-36-g90505bc-Live.iso
-a----        12/15/2022   9:20 PM     1149517824 rescuezilla-2.4.1-64bit.jammy.iso
-a----         8/11/2022   5:57 PM        1048576 sda_2048.bin
-a----         8/11/2022   5:58 PM        1048576 sdb_2048.bin
-a----         8/11/2022   5:58 PM        1048576 sdc_2048.bin
-a----         12/3/2022   7:50 PM      352321536 seaboot_20191118.raw.img.vtoy
-a----         8/11/2022  11:07 AM          32768 test_lnx.raw.vlnk.img
-a----          1/9/2022  10:43 AM      556431360 virtio-win-0.1.208.iso
-a----         8/29/2021   3:24 PM     4556128256 Windows_10_21H1.iso
-a----        11/22/2021  11:34 PM     4600823808 Windows_10_21H2.iso
-a----         12/4/2021   5:39 PM     4537712640 Windows_11_21H2.iso
-a----         9/20/2021   1:56 PM     1145044992 WinXP_WA.vhdx
```

I memorized mnemonic of 1st chars to try remember what of this list ventoy listed in it F2-browser. 
``` a a b c c f g h h h m r r s t v 4w```
So if my memory serves me right   
The F2 browser is missing   
- ```HBCD_PE_x64_v1.0.2_20210701.vhdx```
- ```m01_lnx.raw.vlnk.img```
- ```m02_lnx.raw.img.vtoy```

nb: a couple of months ago, I had resized my first partition form 1Tb to 1.2Tb , also moving my ventoy partition . But I don't think its because of that, because I see cachy linux which I downloaded a week ago.

**Comment by ventoy** [comment]
Can it be listed if you  copy a new file from `m02_lnx.raw.img.vtoy` and rename it to `m02_lnx.raw.img_new.vtoy`.

**Comment by hgkamath** [comment]
I think I found out what the bug might be. 

Notice that the two files
```
08/11/2022  07:01 PM            32,768 m01_lnx.raw.vlnk.img
02/10/2023  10:07 AM    49,861,885,952 m02_lnx.raw.img.vtoy
```
appear one after the other in dirent inode structure linked list order. 

I decided to check if the first file, the vtoy-vlnk file ```m01_lnx.raw.vlnk.img``` is valid.   
The GUI tool ```PS C:\vol\scoop_01\scoopg\apps\ventoy\current> .\VentoyVlnk.exe``` , parse button told me that it is invalid. 
Apparently I had renamed the file.   
So I recreated the vtoy-vlnk as follows
```PS C:\vol\scoop_01\scoopg\apps\ventoy\current> .\VentoyVlnk.exe -i H:\m01_lnx.raw.img.vtoy -o E:\transcend\m01_lnx.raw.vlnk.img```
This fixed the vtoy-vlnk file, and it started to appear in the ventoy menu/browser. 

Surprisingly, it also fixed the the non-appearance of ```m02_lnx.raw.img.vtoy``` in the ventoy menu/browser.   
Both vtoy-vlnk ```m01_lnx.raw.vlnk.img``` and the raw-vtoy-image ```m02_lnx.raw.img.vtoy``` are ventoy-bootable.   

So the bug might be that 
(A) During the population of menu-listing/F2-browser, an invalid vtoy-vlnk is swallowing (omitting) a successor file from the file-linked-list. 
(B) Somewhat less importantly, an invalid vlnk should perhaps be reported?

**Comment by ventoy** [comment]
Can you reproduce the problem if you make the vlnk file invalid again? (rename the original img file will make the vlnk file invalid)

**Comment by hgkamath** [comment]
Confirming: yes

1. First I rename the file to break vtoy-vlnk
```
PS H:\> Rename-Item .\m01_lnx.raw.img.vtoy m01_Zlnx.raw.img.vtoy
PS H:\> dir H:\m01_Zlnx.raw.img.vtoy
    Directory: H:\
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         2/10/2023  12:51 PM    49861885952 m01_Zlnx.raw.img.vtoy
```
2. reboot to ventoy
3. I confirm that both files are missing in menu and F2-browser
4. reboot to win10
5. I rename the file to restore the vtoy-vlnk
```
PS H:\> Rename-Item .\m01_Zlnx.raw.img.vtoy m01_lnx.raw.img.vtoy
PS H:\> dir H:\m01_lnx.raw.img.vtoy
    Directory: H:\
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         2/10/2023  12:51 PM    49861885952 m01_lnx.raw.img.vtoy
```
6. reboot to ventoy
7. I confirm that both files reappear in menu and F2-browser

**Comment by ventoy** [comment]
Can you reproduce the problem if the img file and vlnk file are in Ventoy USB ?
You don't need to really copy the img file to Ventoy USB, you can just copy any file (bigger than 32KB) to Ventoy USB and rename it to xxxx.img and then create a vlnk file for it.

**Comment by hgkamath** [comment]
Confirming: yes on USB flash-drive as well

- I created the same vtoy-vlnk in the UBB folder to the image in ```H:\``` , named it ```m01_lnx.raw.vlnk.img```
- I also copied a small 1MiB dummy file to the USB folder m02_lnx.raw.img.vtoy 
- Did the exact same tests as before, but this time in the UEFI-bios, choosing to boot from a detected USB efi loader (the ventoy efi loader)
- In the ventoy menu/F2-browser, when vlnk is broken, both files do not list. When vlnk is repaired both files show.

### misc
- The USB flash drive is a Kingston 8GB, it had a windows installer iso flashed onto it. 
- Ventoy was installed to second partition using non-destructive install some time ago
- I copied ```.ventoyignore``` in every other directory except ```L:\transcend```
- In the ventoy menu, there was total of 4 files, gparted, the 2 created files, and ```bootmgr.efi``` from the root folder

### log
```
PS C:\WINDOWS\system32> C:\vol\prog_01\prog\gdisk\gdisk-windows-1.0.9\gdisk64.exe \\.\PhysicalDrive10
GPT fdisk (gdisk) version 1.0.9

Partition table scan:
  MBR: protective
  BSD: not present
  APM: not present
  GPT: present

Found valid GPT with protective MBR; using GPT.

Command (? for help): p
Disk \\.\PhysicalDrive10: 15240576 sectors, 7.3 GiB
Sector size (logical): 512 bytes
Disk identifier (GUID): 5BD95AB7-69B1-4100-A5C9-E1BC6C5C55BD
Partition table holds up to 128 entries
Main partition table begins at sector 2 and ends at sector 33
First usable sector is 34, last usable sector is 15240542
Partitions will be aligned on 128-sector boundaries
Total free space is 5565 sectors (2.7 MiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048        14651263   7.0 GiB     0700  Main Data Partition
   2        14651264        14716799   32.0 MiB    0700  VTOYEFI
   3        14716928        15237119   254.0 MiB   0700  Basic data partition

Command (? for help): q

PS L:\transcend> C:\vol\scoop_01\scoopg\apps\ventoy\current\VentoyVlnk.exe -i H:\m01_lnx.raw.img.vtoy -o L:\transcend\m01_lnx.raw.vlnk.img
PS L:\transcend> dir Y:\test_lnx.raw.img
    Directory: Y:\
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         8/11/2022  11:07 AM        1048576 test_lnx.raw.img
PS L:\transcend> copy-item Y:\test_lnx.raw.img L:\transcend\m02_lnx.raw.img.vtoy
PS L:\transcend> dir L:\transcend\
    Directory: L:\transcend
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         11/3/2022   6:04 PM      507510784 gparted-live-1.4.0-6-amd64.iso
-a----         2/10/2023   6:12 PM          32768 m01_lnx.raw.vlnk.img
-a----         8/11/2022  11:07 AM        1048576 m02_lnx.raw.img.vtoy
-a----         2/10/2023   6:12 PM            710 VentoyVlnk.log

PS C:\vol\scoop_01\scoopg\apps\ventoy\current> .\Ventoy2Disk.exe
version shown was 1.0.84

PS C:\vol\scoop_01\scoopg\apps\ventoy\current> .\Ventoy2Disk.exe VTOYCLI /U /PhyDrive:10 /GPT
upgraded to 1.0.88
```
