### ISSUE TITLE
通过主引导记录启动的Ventoy能不能选择并引导ESP分区的.efi文件

### ISSUE THREAD

**Issue by 1457384613gh** [ventoy/Ventoy#2235]
通过主引导记录启动的Ventoy能不能选择并引导ESP分区的.efi文件。

发现，Legacy+MBR 启动的Ventoy 比 UEFI+ESP 启动的 Ventoy 支持更多的分辨率。支持 1366x768，可以设置成显示器的分辨率。

想知道，能不能用 Legacy+MBR 启动的 Ventoy 去浏览 ESP分区，并选择启动 .efi文件。倘若能，想知道，EFI图形界面 是 沿用 Legacy加载的显卡驱动，还是 重新加载 EFI的显卡驱动？

**Comment by steve6375** [comment]
You cannot run .EFI files from a legacy boot.

**Comment by ventoy** [comment]
不能。
