### ISSUE TITLE
[Success Image Report]: MX Linux 21.3 AHS 64Bit

### ISSUE THREAD

**Issue by sdamn** [ventoy/Ventoy#2236]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

MX-21.3_ahs_x64.iso

### Image file checksum type

MD5

### Image file checksum value

52e0b7bf9416f532b0e704661b64553b

### Image file download link (if applicable)

https://sourceforge.net/projects/mx-linux/files/Final/Xfce/MX-21.3_ahs_x64.iso/download

### Test environment

Lenovo ThinkPad X230 Laptop

### More Details?

This image file booted successfully in Ventoy and no errors were seen.

Laptop Specs: - Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz, 2601 Mhz, 2 Core(s), 4 Logical Processor(s)
                          x64-based PC
                          8.00 GB RAM
                          500 GB SSD

**Comment by ventoy** [comment]
Thanks!
