### ISSUE TITLE
[Success Image Report]: Pop_OS! 22.04 LTS 64Bit Intel

### ISSUE THREAD

**Issue by sdamn** [ventoy/Ventoy#2237]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

pop-os_22.04_amd64_intel_17.iso

### Image file checksum type

MD5

### Image file checksum value

7d5697f5282aa0384791c7a9335fa38078dec676ed994fdae42821eb4119b8b9

### Image file download link (if applicable)

https://iso.pop-os.org/22.04/amd64/intel/22/pop-os_22.04_amd64_intel_22.iso

### Test environment

Lenovo ThinkPad X230 Laptop

### More Details?

This image file booted successfully in Ventoy and no errors were seen.

PS: The download link and a filename given are different as the link has now been updated.

Laptop Specs: - Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz, 2601 Mhz, 2 Core(s), 4 Logical Processor(s)
                          x64-based PC
                          8.00 GB RAM
                          500 GB SSD

**Comment by ventoy** [comment]
Thanks!
