### ISSUE TITLE
[Success Image Report]: TrueNAS CORE 13.0 - U3.1 RELEASE

### ISSUE THREAD

**Issue by sdamn** [ventoy/Ventoy#2238]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

TrueNAS-13.0-U3.1.iso

### Image file checksum type

SHA256

### Image file checksum value

05e12c9599f5bd11d565efdb3ed5aa776fadc4ae54013495ca7f04f78909eee0

### Image file download link (if applicable)

https://download.freenas.org/13.0/STABLE/U3.1/x64/TrueNAS-13.0-U3.1.iso/

### Test environment

Lenovo ThinkPad X230 Laptop

### More Details?

This image file booted successfully in Ventoy and no errors were seen.

Laptop Specs: - Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz, 2601 Mhz, 2 Core(s), 4 Logical Processor(s)
x64-based PC
8.00 GB RAM
500 GB SSD

**Comment by ventoy** [comment]
Thanks!
