### ISSUE TITLE
[Success Image Report]: GRML Full x64 Bit 2022.11 RELEASE

### ISSUE THREAD

**Issue by sdamn** [ventoy/Ventoy#2239]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

grml64-full_2022.11.iso

### Image file checksum type

MD5

### Image file checksum value

8b8e4a548a7dcdcd8f3e93098e740c012b5427cf5f4bc5730ef428a6feddd877

### Image file download link (if applicable)

https://download.grml.org/grml64-full_2022.11.iso

### Test environment

Lenovo ThinkPad X230 Laptop

### More Details?

This image file booted successfully in Ventoy and no errors were seen.

Laptop Specs: - Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz, 2601 Mhz, 2 Core(s), 4 Logical Processor(s)
x64-based PC
8.00 GB RAM
500 GB SSD

**Comment by ventoy** [comment]
Thanks!
