### ISSUE TITLE
windows UEFI cant boot

### ISSUE THREAD

**Issue by Sosha1996** [ventoy/Ventoy#224]
i use prime H270-plus motherboard
my USB flash: SP Jewel J07

File: /EFI/Microsoft/Boot/BCD

Status: 0x000014c

Info: The Boot Configuration Data for your PC is missing or contains errors.

![image](https://user-images.githubusercontent.com/16008585/84533379-4276b280-acfd-11ea-8149-9738427173c8.png)

**Comment by ventoy** [comment]
Can you try ventoy-1.0.13?
Besides, which iso file do you test?

**Comment by Sosha1996** [comment]
ok i use vento 1.0.14 and use this windows https://software-download.microsoft.com/db/Win10_2004_EnglishInternational_x64.iso?t=f57e1ad2-b50a-4514-b1f8-09d3ec2ca0b6&e=1593471823&h=bd43dd8effebc51071992a05577d373b (https://tb.rg-adguard.net/public.php) and my problem is solved.

**Comment by jelabarre59** [comment]
Not fixed here.  I have Ventoy 1.0.99, ISO image Win10_22H2_English_x64v1.iso, and it fails there as well.  The SSD has been wiped so there's no OS on it.

**Comment by LavaLaugh** [comment]
I have also found the same problem, both with the Win10_22H2_Dutch_x64v1.iso and Hiren's BootCD.

**Comment by rexendevar** [comment]
I solved this by selecting "boot in wimboot mode" instead of "boot in normal mode."
