### ISSUE TITLE
[Success Image Report]: Ubuntu Kylin 22.04 Enhanced / Pro Version x64 Bit

### ISSUE THREAD

**Issue by sdamn** [ventoy/Ventoy#2241]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

ubuntukylin-22.04-pro-amd64.iso

### Image file checksum type

MD5

### Image file checksum value

0145d61dcea77cd7e7ced4020e09c840

### Image file download link (if applicable)

https://mirrors.aliyun.com/ubuntukylin-cdimage/22.04/ubuntukylin-22.04-pro-amd64.iso/

### Test environment

Lenovo ThinkPad X230 Laptop

### More Details?

This image file booted successfully in Ventoy and no errors were seen.

Laptop Specs: - Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz, 2601 Mhz, 2 Core(s), 4 Logical Processor(s)
x64-based PC
8.00 GB RAM
500 GB SSD

**Comment by ventoy** [comment]
Thanks!
