### ISSUE TITLE
[Success Image Report]: Ubuntu Kylin 22.04.1 LTS (Jammy Jellyfish) Basic x64 Bit

### ISSUE THREAD

**Issue by sdamn** [ventoy/Ventoy#2242]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

ubuntukylin-22.04.1-desktop-amd64.iso

### Image file checksum type

MD5

### Image file checksum value

56e4acdda4dd0c03841e3ba75d359917

### Image file download link (if applicable)

http://cdimage.ubuntu.com/ubuntukylin/releases/22.04.1/release/ubuntukylin-22.04.1-desktop-amd64.iso

### Test environment

Lenovo ThinkPad X230 Laptop

### More Details?

This image file booted successfully in Ventoy and no errors were seen.

Laptop Specs: - Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz, 2601 Mhz, 2 Core(s), 4 Logical Processor(s)
x64-based PC
8.00 GB RAM
500 GB SSD

**Comment by ventoy** [comment]
Thanks!
