### ISSUE TITLE
[Success Image Report]: NixOS Graphical 22.11GNOME x64( Intel / AMD )

### ISSUE THREAD

**Issue by sdamn** [ventoy/Ventoy#2243]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

nixos-gnome-22.11.2523.1b82144edfc-x86_64-linux.iso

### Image file checksum type

SHA256

### Image file checksum value

32e0b68cad48c8027ac0dae189a5e9e03769887bdad9b1c53fa0c42b27f6d0f9

### Image file download link (if applicable)

https://releases.nixos.org/nixos/22.11/nixos-22.11.2523.1b82144edfc/nixos-gnome-22.11.2523.1b82144edfc-x86_64-linux.iso/

### Test environment

Lenovo ThinkPad X230 Laptop

### More Details?

This image file booted successfully in Ventoy and no errors were seen.

Laptop Specs: - Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz, 2601 Mhz, 2 Core(s), 4 Logical Processor(s)
x64-based PC
8.00 GB RAM
500 GB SSD

**Comment by ventoy** [comment]
Thanks!
