### ISSUE TITLE
[Success Image Report]: NixOS Console Version ( Minimal ) x64 ( Intel / AMD )

### ISSUE THREAD

**Issue by sdamn** [ventoy/Ventoy#2244]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

nixos-minimal-22.11.2523.1b82144edfc-x86_64-linux.iso

### Image file checksum type

SHA256

### Image file checksum value

d013d5cd42436dfea6485d825c6ece23dbb2bb6bd8a68376e0f72a0ca9fee74e

### Image file download link (if applicable)

https://releases.nixos.org/nixos/22.11/nixos-22.11.2523.1b82144edfc/nixos-minimal-22.11.2523.1b82144edfc-x86_64-linux.iso

### Test environment

Lenovo ThinkPad X230 Laptop

### More Details?

This image file booted successfully in Ventoy and no errors were seen.

Laptop Specs: - Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz, 2601 Mhz, 2 Core(s), 4 Logical Processor(s)
x64-based PC
8.00 GB RAM
500 GB SSD

**Comment by ventoy** [comment]
Thanks!
