### ISSUE TITLE
[Success Image Report]: Tiny 11 ( by NTDEV ) based on Windows 11 Pro 22H2

### ISSUE THREAD

**Issue by sdamn** [ventoy/Ventoy#2246]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

tiny11 b1.iso

### Image file checksum type

MD5

### Image file checksum value

efd53d1bd51854ee57391ea3a4700cbf

### Image file download link (if applicable)

https://archive.org/download/tiny-11-NTDEV/tiny11%20b1.iso

### Test environment

Lenovo ThinkPad X230 Laptop

### More Details?

This image file booted successfully in Ventoy and no errors were seen.

Laptop Specs: - Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz, 2601 Mhz, 2 Core(s), 4 Logical Processor(s)
x64-based PC
8.00 GB RAM
500 GB SSD

**Comment by ventoy** [comment]
Thanks!
