### ISSUE TITLE
[issue]: Ventoy does not update if you set the read-only attribute in diskpart

### ISSUE THREAD

**Issue by Alex-S1** [ventoy/Ventoy#2248]
### Official FAQ

- [x] I have checked the official FAQ.

### Ventoy Version

1.0.88

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

8 GB

### Disk Manufacturer

UFD 2.0 Silicon-Power8G

### Image file checksum (if applicable)

None

### What happened?

If you set the read-only attribute in diskpart for the disk, there is an error.

![problem](https://user-images.githubusercontent.com/61148267/218717218-6e250843-b705-49c7-ac9a-9449eca93102.png)

[log.txt](https://github.com/ventoy/Ventoy/files/10731656/log.txt)

---

Run in command line:
`diskpart`
`list disk`
`select disk 1`

Sets read-only attribute: `attributes disk set readonly`
Remove the read-only attribute: `attributes disk clear readonly`

OS: Windows  10.0.19044.1288  Pro  64-bit

**Comment by hgkamath** [comment]
So why would that be a bug? sounds like either WinOS/ventoy is heeding the meaning of the attribute. 
 
```
[root@fedora dev]# gdisk /dev/sdc
GPT fdisk (gdisk) version 1.0.9

Partition table scan:
  MBR: protective
  BSD: not present
  APM: not present
  GPT: present

Found valid GPT with protective MBR; using GPT.

Command (? for help): p
Disk /dev/sdc: 3907029168 sectors, 1.8 TiB
Model: ST2000LM007-1R81
: 
Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048      2566852607   1.2 TiB     0700  15KJ_Ventoy
   2      2566852608      2566918143   32.0 MiB    0700  15KJ_VTOYEFI
:
Command (? for help): x

Expert command (? for help): i
Partition number (1-11): 2
Partition GUID code: EBD0A0A2-B9E5-4433-87C0-68B6B72699C7 (Microsoft basic data)
Partition unique GUID: 17D8F0D9-0ADF-46B2-8B9A-F3915DCA1B49
First sector: 2566852608 (at 1.2 TiB)
Last sector: 2566918143 (at 1.2 TiB)
Partition size: 65536 sectors (32.0 MiB)
Attribute flags: 0000000000000001
Partition name: '15KJ_VTOYEFI'

Expert command (? for help): a
Partition number (1-11): 2
Known attributes are:
0: system partition
1: hide from EFI
2: legacy BIOS bootable
60: read-only
62: hidden
63: do not automount

Attribute value is 0000000000000001. Set fields are:
0 (system partition)

Toggle which attribute field (0-63, 64 or <Enter> to exit): 

```
