### ISSUE TITLE
[issue]: gentoo minimal image copying to tmpfs fails

### ISSUE THREAD

**Issue by mortezadadgar** [ventoy/Ventoy#2250]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

10.88

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

16G

### Image file checksum (if applicable)

None

### What happened?

Hey,
This is the first time I'm using this program I chose GPT and FAT32 from menu and installed it and copied the latest minimal gentoo iso(install-amd64-minimal-20230129T164658Z.iso) right after booting into and selecting normal mode I got many errors in "copying read/write contents to tmps" section of init like this "cp: error reading: input/output error" and then drop to rescue mode of gentoo(not grub)

**Comment by mortezadadgar** [comment]
![IMG_20230215_172636_1](https://user-images.githubusercontent.com/27911493/219048754-51bb83d1-9525-490c-b54a-accaaee209fd.jpg)

**Comment by ventoy** [comment]
So the ISO file was corrupted.
The correct SHA256 value is `b245245d49995ff1866de0136af6e19c47ae2649fb82d326dace4e36c60eb825`
https://gentoo.osuosl.org/releases/amd64/autobuilds/current-install-amd64-minimal/install-amd64-minimal-20230129T164658Z.iso.sha256

**Comment by mortezadadgar** [comment]
so I tested with another boot image that i installed gentoo with that successfully calculated sha256 still don't match

**Comment by ventoy** [comment]
It's OK in my computer.

![image](https://user-images.githubusercontent.com/59477474/219287456-c4c054bf-b58b-48f4-a4bd-3c26b819acd1.png)

**Comment by mortezadadgar** [comment]
yeah it was corrupted
