### ISSUE TITLE
[Success Image Report]: Paladin Forensics Suite

### ISSUE THREAD

**Issue by JReming85** [ventoy/Ventoy#2251]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

carbon-paladin.iso

### Image file checksum type

MD5

### Image file checksum value

AE4F6D675DAF2297B3DA5E9EE36B0215

### Test environment

Dell Latitude 3420, Macbook Pro, Dell Latitude 5420, Thinkpad E15

### More Details?

This image file booted successfully in Ventoy on multiple systems to perform forensic imaging.

Software is donationware for business use, otherwise freeware for home use

https://sumuri.com/software/paladin/

**Comment by ventoy** [comment]
Thanks!
