### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by JoaquinPro64** [ventoy/Ventoy#2253]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

Hiren's.BootCD.15.2.iso

### Image file checksum type

MD5

### Image file checksum value

7EFC81ADBBD551D56F6021C439C6837C

### Image file download link (if applicable)

https://www.hirensbootcd.org/old-versions/

### Test environment

Samsung NP300E4C AB1AR

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
