### ISSUE TITLE
[Success Image Report]:  Darick's Boot and Nuke

### ISSUE THREAD

**Issue by JoaquinPro64** [ventoy/Ventoy#2254]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

dban-2.3.0_i586.iso

### Image file checksum type

MD5

### Image file checksum value

33a1df4171e649462ef9679ac207aa77

### Image file download link (if applicable)

https://sourceforge.net/projects/dban/files/dban/dban-2.3.0/dban-2.3.0_i586.iso/download

### Test environment

Gigabyte GA-B75M-D3H

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
