### ISSUE TITLE
[Success Image Report]: Hirens Boot PE

### ISSUE THREAD

**Issue by JoaquinPro64** [ventoy/Ventoy#2255]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

HBCD_PE_x64.iso

### Image file checksum type

MD5

### Image file checksum value

BEC7304FE2EB11DE495B9EA7B73C38AA

### Image file download link (if applicable)

https://www.hirensbootcd.org/files/HBCD_PE_x64.iso

### Test environment

Samsung NP300E4C AB1AR

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
