### ISSUE TITLE
[issue]: Install pfSense 2.5.2, 2.6.0, 2.7.0: Error 19

### ISSUE THREAD

**Issue by pompfe** [ventoy/Ventoy#2259]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.88

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

512GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

None

### What happened?

A bug happened!

Installing pfSense 2.5.2, 2.6.0 & 2.7.0:
Trying to mount root from ufs:ufs/dev/ufs/FreeBSD_Install [ro,noatime]...
mountroot: waiting for device /dev/ufs/FreeBSD_Install ...
Mounting from ufs:/dev/ufs/FreeBSD_Install failed with error 19.
---  STOP

Some have reported strange behaviour with SanDisk USB sticks.  Are they really that problematic?  Should I get another brand and try again?

EDIT:  pfSense installs fine from SanDisk sticks if not using ventoy.  Tried ventoy with pfSense images on another brand USB stick (Lexar) - does not work, get the same error.  So problem seems to be with ventoy.

**Comment by pompfe** [comment]
One addition:
It's all about the memstick image versions.

**Comment by ventoy** [comment]
For pfsense, only ISO file is supported, memstick image is NOT supported.

**Comment by pompfe** [comment]
ok, thanks.
