### ISSUE TITLE
[Success Image Report]: el_windows_7_enterprise_with_sp1_x64_dvd_u_677650.iso

### ISSUE THREAD

**Issue by EAZYBLACK** [ventoy/Ventoy#2260]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

el_windows_7_enterprise_with_sp1_x64_dvd_u_677650.iso

### Image file checksum type

SHA256

### Image file checksum value

d879895c279276c8dd21c3a647bbacc7e2aaa8b9abac0a72ecca50356a4ace97

### Test environment

Gigabyte GA-G31M-ES2C with a core 2 quad q9450 and 4gb ram

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!

**Comment by Huaweidev** [comment]
I can boot cn_windows_7_ultimate_with_sp1_x64_dvd_u_677408.iso on VirtualBox like this, how to test run it successfully?
frozen...
![05-09_20-39-02](https://github.com/ventoy/Ventoy/assets/10258421/33b4d9de-ed37-47da-b594-ef9e33a59128)

**Comment by abdulmosen** [comment]
How to download Windows system

**Comment by gokhangur25** [comment]
yessssssssssssssss!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
