### ISSUE TITLE
[issue]: Persistence option is not shown but checks out OK with F5 tool

### ISSUE THREAD

**Issue by ccheath** [ventoy/Ventoy#2263]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.88

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

16GB

### Disk Manufacturer

EDGE

### Image file checksum (if applicable)

Yes.

### What happened?

I have one .iso file for my image (`linuxmint-21.1-mate-64bit.iso`) and used VentoyPlugson.exe to create the `ventoy.json` file.
When booting and selecting the image the next screen lets me choose normal mode, grub2 mode, or checksum but there is no persistence option.
I have run the F5 tools menu option to check the persistence plugin in the ventoy.json file and it says OK/Success.

**Comment by ventoy** [comment]
The persistence option will show after this screen.
Just choose normal mode or grub2 mode, press Enter and then the persistence option will show.

**Comment by ccheath** [comment]
> 

The persistence option does not show up after that screen, it just boots to the iso...
