### ISSUE TITLE
[issue]: 

### ISSUE THREAD

**Issue by sekaom** [ventoy/Ventoy#2265]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.88

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

64Gb

### Disk Manufacturer

kingstone

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

archlinux-2023.02.01-x86_64.iso

### What happened?

I can't boot archlinux-2023.02.01-x86_64.iso on ventoy,ventoy  version is 1.0.88  
I tried normal , grub2 and mem mode ,but it still can't boot  
After I select boot it ,nothing will display,all the black

**Comment by ozky84** [comment]
Sounds like hardware problem as i can boot it fine with Ventoy.....
I have: ASUS VIVOPC K20CD-K-NR009T
tinyurl.com/45yueu5k
Does it shows only black screen without any text????

**Comment by sekaom** [comment]
Sorry,after I verified sha256,I found it not same,my iso file has broken.I redownloaded archlinux iso file,it could boot normally.
