### ISSUE TITLE
[issue]: Ventoy2Disk.sh whether support excute in 32 bits system?

### ISSUE THREAD

**Issue by InnerPeaceSwordsMan** [ventoy/Ventoy#2268]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.08b2

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32G

### Disk Manufacturer

USB msd

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://github.com/ventoy/Ventoy/releases/tag/v1.0.08

### What happened?

A bug happened!

when i excute Ventoy2disk.sh in armv7 of 32 bits system, An error occurred of xzcat " ./xzcat: Exec format error",  Is this meaning not support 32 bits system ?

**Comment by ventoy** [comment]
Ventoy2Disk.sh only supports x86 32bit system.  It does not support armv7 32bit system and has no plan to support it.
