### ISSUE TITLE
[Success Image Report]: Palera1n Linux (Palen1x)

### ISSUE THREAD

**Issue by TheFunnyMan16** [ventoy/Ventoy#2271]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

c-palen1x-v1.0.7-amd64.iso

### Image file checksum type

SHA1

### Image file checksum value

cb2a47bba41080c1a0efafef885531af773a79dc

### Image file download link (if applicable)

https://cdn.nickchan.lol/palera1n/artifacts/palen1x/

### Test environment

Gateway 14.1" Ultra Slim Running Windows 10

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
