### ISSUE TITLE
[Success Image Report]: TrueNAS-Scale

### ISSUE THREAD

**Issue by Hellhium** [ventoy/Ventoy#2275]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

TrueNAS-SCALE-22.12.1.iso

### Image file checksum type

MD5

### Image file checksum value

08cff536d026940a003b9a05f2152472

### Image file download link (if applicable)

https://download.truenas.com/TrueNAS-SCALE-Bluefin/22.12.1/TrueNAS-SCALE-22.12.1.iso

### Test environment

AMD X399 (Threadripper 1950x)

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
