### ISSUE TITLE
[issue]: VTOY_LINUX_REMOUNT=1 does not work on Nobara 37 (fedora fork)

### ISSUE THREAD

**Issue by SzczurekYT** [ventoy/Ventoy#2276]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.88

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32 GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

No.

### Image file download link (if applicable)

https://nobaraproject.org/download-nobara/#

### What happened?

Hello
I'm trying to access the bigger ventoy partition on my Nobara 37 image.
I've enabled the `VTOY_LINUX_REMOUNT` setting using the plugman. No difference, with the setting enabled or disabled the result is this same. When I try to mount the bigger partition I get an error like this:
`Error mounting /dev/sda1 at /run/media/liveuser/Ventoy: /dev/sda1 already mounted or mount point busy`

![image](https://user-images.githubusercontent.com/67533827/222916270-c3180ecb-fd3d-4978-8134-b3d5c04518bf.png)

Nobara is Fedora based distro with some fixes for gaming and hardware support. I've seen another issue where you added a fix for fedora so I thought it will work on Nobara too, but apparently it doesn't.

Side note: I also have persistence enabled. Nobara isn't using Selinux, so I didn't added the selinux=0 in the boot options, and it works perfectly fine, you can add this to wiki.

The full iso name is: `Nobara-37-KDE-2023-02-25.iso` (I'm using the kde spin).

Thanks

**Comment by ventoy** [comment]
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/4219907971
https://www.ventoy.net/en/doc_github_ci.html

**Comment by SzczurekYT** [comment]
Now it works properly. Thanks for a quick fix. You are doing a great work.
