### ISSUE TITLE
[issue]: Ventoy可以实现类似PXE/iPXE引导各类ISO镜像系统这个功能不？这样方便局域网批量安装其他主机

### ISSUE THREAD

**Issue by maojianyou** [ventoy/Ventoy#2278]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.88

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

111

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

Ventoy可以实现类似PXE/iPXE引导各类ISO镜像系统这个功能不？这样方便局域网批量安装其他主机

### What happened?

A bug happened!Ventoy可以实现类似PXE/iPXE引导各类ISO镜像系统这个功能不？这样方便局域网批量安装其他主机

**Comment by ventoy** [comment]
不支持。Ventoy功能是基于U盘/磁盘 安装系统，不支持网络安装。
