### ISSUE TITLE
[issue]: cannot boot libreelec latest

### ISSUE THREAD

**Issue by temperta** [ventoy/Ventoy#2281]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.89

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128GB

### Disk Manufacturer

sandisk

### Image file checksum (if applicable)

None

### What happened?

A bug happened!
libreelec generic 11.0 cannot boot,with errors

![IMG_20230308_225801](https://user-images.githubusercontent.com/6389198/223748047-d9fd5307-e8ae-40df-bad9-7f288ded734a.jpg)

**Comment by ventoy** [comment]
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/4376333909
https://www.ventoy.net/en/doc_github_ci.html

**Comment by temperta** [comment]
it can boot now
