### ISSUE TITLE
[Success Image Report]: ReviOS 11 23.02

### ISSUE THREAD

**Issue by xemulat** [ventoy/Ventoy#2282]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.87

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

ReviOS-11-23.02.iso

### Image file checksum type

MD5

### Image file checksum value

D1BFB9DDC9558FA286D822E22515547E

### Image file download link (if applicable)

https://www.revi.cc/revios/download

### Test environment

Custom PC

### More Details?

This image file booted successfully in Ventoy, System installed successfully.

**Comment by ventoy** [comment]
Thanks!
