### ISSUE TITLE
[issue]: Cannot install in mint live boot

### ISSUE THREAD

**Issue by ibrahimashraf** [ventoy/Ventoy#2284]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.89

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

64

### Disk Manufacturer

Hikvision

### Image file checksum (if applicable)

Yes.

### What happened?

Cannot install or use webui server link not opening in browser

***this is ventoy CL***

`mint@mint:~/Downloads/ventoy$ sudo bash Ventoy2Disk.sh -I /dev/sdd

**********************************************
      Ventoy: 1.0.89  x86_64
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

./tool/ventoy_lib.sh: line 53: 27459 Segmentation fault      vtoycli fat -T
Some tools can not run on current system. Please check log.txt for details.`

**this is log** 

> ############# Ventoy2Disk -I /dev/sdd [x86_64] ################
Thu Mar  9 09:20:54 UTC 2023
decompress tools
MODE=install FORCE=Y RESERVE_SPACE= RESERVE_SIZE_MB=0
hexdump test ok ...
mkexfatfs test ok ...
vtoycli fat test fail ...

**this is webui command** 
`mint@mint:~/Downloads/ventoy$ sudo sh VentoyWeb.sh

===============================================================
  Ventoy Server 1.0.89 is running ...
  Please open your browser and visit http://127.0.0.1:24680
===============================================================

**Comment by ventoy** [comment]
Is it OK if you run in other OS environment instead of mint live?

**Comment by ventoy** [comment]
Which mint live ISO file did you test?

**Comment by ibrahimashraf** [comment]
It was my first time on linux so I just tried some people recommendation, i managed to use balenaetcher and mount another environment mx linux and ventoy works like a charm 
![99133591_3282772198423274_1356173839683289088_o](https://user-images.githubusercontent.com/16999985/224495948-8fab86fb-0f00-4094-82e9-7e15be032d9d.jpg)
