### ISSUE TITLE
[Success Image Report]: HelenOS

### ISSUE THREAD

**Issue by TCFFan123** [ventoy/Ventoy#2289]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.89

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

helenos.iso

### Image file checksum type

SHA256

### Image file checksum value

83256c0f9da4ed405ecde33a7653aca4cb3beed4d4a3b0061c75d916f85cc812

### Test environment

Lenovo IdeaPad 3 LNVNB161216 (0x000002B1 - 0x9FAA9BE0)

### More Details?

Use legacy mode in BIOS to boot. **EFI doesn't work.**

**Comment by ventoy** [comment]
Thanks!
