### ISSUE TITLE
[issue]: 

### ISSUE THREAD

**Issue by karthikvijay5227** [ventoy/Ventoy#2291]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.89

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Image file checksum (if applicable)

None

### What happened?

After installing Windows 11 from Ventoy USB,the pen drive has now one more VYOEFI like partition of 4.3MB something which is not usable.It is little irritating.I have to reinstall Ventoy now.Please resolve or explain why it is creating?

**Comment by ventoy** [comment]
When you install Ventoy to USB, the USB will be devided into 2 partitions, part1 is a bigger Ventoy partition, part2 is a 32MB VTOYEFI partition.
For Windows 10/11, if the USB contains more that one partitions, then all the partitions will be shown.
You can delete the drive letter for one partition, then it will not be shown agagin, but when you plug the USB to a new computer with Windows 10/11, it will be shown again. You can not completely hide it, that's the Windows limitation.

When you install Ventoy, Ventoy2Disk program delete the drive letter for the 32MB VTOYEFI partition, so you can not see it.
But when you plug the USB to a new Windows 10/11 system (a new computer or you install a new Windows 11) then it will be shown agagin.

However, you don't need to reinstall Ventoy, you can just click update button to do a self update (e.g. update from 1.0.89 to 1.0.89)  then the drive letter for VTOYEFI partition will be deleted and it will not be shown agagin in this Windows system.
