### ISSUE TITLE
[Small Question]: about Persistence Plugin

### ISSUE THREAD

**Issue by anwar-alsilwy** [ventoy/Ventoy#2297]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.89

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

SSD 1TB

### Disk Manufacturer

Samsung 

### Image file checksum (if applicable)

None

### What happened?

I have 1TB SSD with 4 partitions:
PTN1= ISO files /NTFS
PTN2= VTOYEFI /FAT32
PTN3= My other files /NTFS
PTN4= Extra Partition for testing /FAT32

There are two methods to use Persistence function, Could you please tell me Which one is working or even better ??

1- I will put (Kali_Live.iso & Kali_Persistence.dat ) at the same folder on partition 3, then creat vlnk for both two files, then copy them to 1st partition, then add (Kali_Live.vlnk.iso &  Kali_Persistence.vlnk.dat ) to ventoy.json.

2- I will put (Kali_Live.iso &  Kali_Persistence.dat ) at the same folder directly on 1st partition, then add (Kali_Live.iso &  Kali_Persistence.dat ) to ventoy.json.

**Comment by ventoy** [comment]
Both can work.
In your case, there is no much difference between the two methods.

If you install Ventoy on a small/slow USB stick then method 1 will be better. 
Because you can put your iso and dat files on your other high speed disk (e.g. SSD).

**Comment by anwar-alsilwy** [comment]
Thank you for letting me know, Master @longpanda

one more thing please:

On regular USB drives, if I want to re-format Persistence partition, I load Kali iso live without Persistence option, and I mount Persistence partition using (e.g Gparted tool) then re-create Persistence.cfg with "/ union" command, after that I reload Kali iso live withe Persistence option to start fresh Kali.
Ok, how can I do this on ventoy Persistence.dat file, I don't want to re-create Persistence.dat over and over again, since my Persistence.dat file size about 10GB and consuming SSD writing lifespan.
Thanks.

**Comment by ventoy** [comment]
In a linux system, you can connect the persistence.dat file to a loop device and format it as common /dev/sda,/dev/sdb ...
```

#find a free loop device (e.g. /dev/loop1)
freeloop=$(losetup -f)

#connect the dat file to the loop device
losetup $freeloop  persistence.dat

#format  the loop device (e.g. /dev/loop1) with command line or gparted .....

#disconnect the loop device
losetup -d $freeloop
```

**Comment by anwar-alsilwy** [comment]
Testing...
