### ISSUE TITLE
[Feature request] folders visible in boot menu

### ISSUE THREAD

**Issue by aretsmarvin** [ventoy/Ventoy#23]
Should be nice if the folders (how they are on the usb) showed in the boot menu.
For example:
- A Windows folder
- A Linux folder
- A Tools folder (hirens boot, etc.)

I've placed my ISO's in folders, but now it grabs them out of the folders and shows them just in an row (without structure).

**Comment by ventoy** [comment]
You can try 1.0.08 with TreeView Mode.

**Comment by aretsmarvin** [comment]
Yes. That looks nice.
One question: is it possible to "auto-boot" in TreeView mode, instead of using F3 every time?
Thanks!

**Comment by ventoy** [comment]
You can modify the grub.cfg or maybe I can add an option in the installer.

**Comment by aretsmarvin** [comment]
In Windows I can't see grub.cfg? An option in the installer would be nice!

**Comment by aretsmarvin** [comment]
> You can modify the grub.cfg or maybe I can add an option in the installer.

Do I need to recompile or something when I update grub.cfg?

I've added the option to auto switch to treeview, but nothing happend. To verify if changes were applied I edited de text, but that also doesn't change?

**Comment by aretsmarvin** [comment]
Feature is added in plugin json config. Problem solved.
