### ISSUE TITLE
[Feature Request] availability to define Class parameter on ventoy.json

### ISSUE THREAD

**Issue by soares23** [ventoy/Ventoy#230]
Hi,
Can you please put the option on ventoy.json to define the --Class parameter (that we also can define icon's for the ISO's) to customize the theme of the Menu if possible.
Thanks for your great work.

**Comment by ventoy** [comment]
It's in my plan. Maybe next release or after next release.

**Comment by ahmaddxb** [comment]
That would be a nice addition.

**Comment by ventoy** [comment]
Ventoy-1.0.14
https://www.ventoy.net/en/plugin_menuclass.html

**Comment by ventoy** [comment]
I will close the issue now. If you have some problem of the menu class plugin, you can create a new issue.
