### ISSUE TITLE
[issue]: No Boot on Asus Transformer Book T100TAF

### ISSUE THREAD

**Issue by Foul** [ventoy/Ventoy#2300]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.89

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

?

### Image file checksum (if applicable)

None

### What happened?

Impossible to boot on Asus Transformer Book T100TAF.

I'm computer Technician and use Ventoy every day on multiples computers, but this one... no boot...  pic attached.

![Asus](https://user-images.githubusercontent.com/829842/225866140-a48b567d-7fe1-4fa5-ba9b-f532ec5322ff.jpg)

Try Both UEFI/Legacy.. same message...

HELP !

**Comment by ventoy** [comment]
For this computer you need to disable `secure boot supported` option in Ventoy  and at the same time disable `secure boot` option in the BIOS of the computer.

PS: you don't need to reinstall Ventoy to disable `secure boot support` option in Ventoy, just uncheck the option in Ventoy menu and update Ventoy.

**Comment by Foul** [comment]
You're right.. booted on non UEFI USB Key 👍🏻
Thx !

**Comment by juliolambert020-prog** [comment]
Pero porque no me deja instalar windows
