### ISSUE TITLE
[Success Image Report]: Tiny 11 Beta 2 ( by NTDEV )

### ISSUE THREAD

**Issue by notjl** [ventoy/Ventoy#2306]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.85

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

tiny11 b2.iso

### Image file checksum type

SHA1

### Image file checksum value

cd75ce88b35b3ebd69ca4c135a21582deea48816

### Image file download link (if applicable)

https://archive.org/download/tiny-11-NTDEV/tiny11%20b2.iso

### Test environment

QEMU/KVM

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!

**Comment by Sovenok-Hacker** [comment]
Hello! Why is the Tiny 11 listed as Linux on ventoy.net ?

**Comment by phpac** [comment]
> Hello! Why is the Tiny 11 listed as Linux on ventoy.net ?
There are Windows and PE in the list.
And Tiny11 is like a "distribution" of Windows

**Comment by Sovenok-Hacker** [comment]
> > Hello! Why is the Tiny 11 listed as Linux on ventoy.net ?
> > There are Windows and PE in the list.
> > And Tiny11 is like a "distribution" of Windows

But it isn`t Linux

**Comment by phpac** [comment]
> > > Hello! Why is the Tiny 11 listed as Linux on ventoy.net ?
> > > There are Windows and PE in the list.
> > > And Tiny11 is like a "distribution" of Windows
> 
> But it isn`t Linux

who said it is?

**Comment by ventoy** [comment]
I have moved it to the Windows section.
