### ISSUE TITLE
[issue]: chimera linux is not supported 

### ISSUE THREAD

**Issue by ahmed12345678910111213141516** [ventoy/Ventoy#2309]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.89

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Image file checksum (if applicable)

None

### Image file download link (if applicable)

https://chimera-linux.org/downloads/

### What happened?

Chimera faills to boot ,as the devloper said ventoy dose not support chimera
chimera is non-gnu Linux distribution which uses dinit as init system insted of systemd

**Comment by ventoy** [comment]
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/4511296980
https://www.ventoy.net/en/doc_github_ci.html

**Comment by ventoy** [comment]
supported in latest 1.0.90
