### ISSUE TITLE
[issue]: Debian 11.6.0 bullseye live - boot conf replace not working

### ISSUE THREAD

**Issue by TK1987** [ventoy/Ventoy#2321]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.90

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

64GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://cdimage.debian.org/debian-cd/current-live/i386/iso-hybrid/debian-live-11.6.0-i386-mate.iso

### What happened?

I have tried replacing the "/boot/grub/grub.cfg", but no matter what I do, it keeps calling the original grub.cfg.

I did the exact same thing with an Ubuntu iso and it works fine with that.

I have also tried replacing a few other confs, but none work. When I select "check boot conf replace plugin configuration" on the tools page with F5, I get the following output:
```
iso:</ISO/Linux/ubuntu-mate-22.10-desktop-amd64.iso>  [OK]
org:</boot/grub/grub.cfg>  [OK]
new1:</.config/mate.cfg>  [OK]

iso:</ISO/Linux/debian-live-11.6.0-i386-mate.iso>  [OK]
org:</boot/grub/grub.cfg>  [OK]
new1:</.config/debian.cfg>  [OK]

iso:</ISO/Linux/debian-live-11.6.0-i386-mate.iso>  [OK]
org:</boot/grub/loopback.cfg>  [OK]
new1:</.config/debian.cfg>  [OK]

iso:</ISO/Linux/debian-live-11.6.0-i386-mate.iso>  [OK]
org:</EFI/debian/grub.cfg>  [OK]
new1:</.config/debian.cfg>  [OK]
```

Is there anything else I can try?

**Comment by ventoy** [comment]
`ubuntu-mate-22.10-desktop-amd64.iso`  use grub2 as the bootloader in both Legacy BIOS mode and UEFI mode.
`debian-live-11.6.0-i386-mate.iso` use isolinux as the bootloader in Legacy BIOS mode and use grub2 as the bootloader  in UEFI mode.

Your BIOS is legacy BIOS mode, so for `debian-live-11.6.0-i386-mate.iso`  you need to replace `/isolinux/isolinux.cfg` or `/isolinux/menu.cfg`  not `grub.cfg`.

**Comment by TK1987** [comment]
That's weird, now it works via legacy boot even though I didn't do anything other than remove the other replaced config.
Anyway, thanks. However, it still does not work for EFI boot.

**Comment by TK1987** [comment]
> `debian-live-11.6.0-i386-mate.iso` is 32bit so you should test it in a IA32 UEFI machine, normally people's PC/laptop is UEFI 64, not IA32 UEFI.

That's the problem, I tried it with a 64bit UEFI. Background is that I wanted to have tools in a persistent Debian live system that work under all systems, no matter if it is a 64bit UEFI or a 32bit legacy system.

I have now created separate persistent systems for 64bit and 32bit respectively. Not really nice, but it works.
