### ISSUE TITLE
[issue]: OPNsense-23.1-OpenSSL-vga-amd64.img fails to boot

### ISSUE THREAD

**Issue by Silejonu** [ventoy/Ventoy#2326]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.90

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

256 GB

### Disk Manufacturer

Samsung

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://mirror.ams1.nl.leaseweb.net/opnsense/releases/23.1/OPNsense-23.1-OpenSSL-serial-amd64.img.bz2

### What happened?

The image boots, but during the initial loading of the live system, the following error happens:

![IMG_20230401_112323](https://user-images.githubusercontent.com/48565914/229278191-7245114e-d7cf-4e0c-9282-1900d36678a3.jpg)

The issue is the same whether the Ventoy disk is in MBR or GPT. I also tried to use MemDisk, with the same result.

Note that *OPNsense-23.1-OpenSSL-dvd-amd64.iso* boots correctly.

**Comment by ventoy** [comment]
For OPNsense, only  `.iso` file is supported, `.img` file is NOT supported.

**Comment by Silejonu** [comment]
Alright, no worries.

**Comment by EinsKatze** [comment]
OPNsense-24.1-dvd-amd64.iso does not boot correctly. Similar error to the one in the picture.

**Comment by valdezpa09** [comment]
> OPNsense-24.1-dvd-amd64.iso does not boot correctly. Similar error to the one in the picture.

I can confirm this. I have tried as well.

**Comment by catt0** [comment]
FYI I tried to boot OPNsense-24.7-dvd-amd64.iso with Ventoy 1.0.88 and got the above error. I updated Ventoy to 1.0.99 and the boot worked correctly.

**Comment by unclesam87** [comment]
still has the same error - with gpt and mbr ventoy 1.0.99 and iso

**Comment by mkaatman** [comment]
Update to 1.0.99 with the iso worked for me.
