### ISSUE TITLE
Fedora Rawhide Server DVD ISO cannot Boot Through Ventoy

### ISSUE THREAD

**Issue by jdb130496** [ventoy/Ventoy#2327]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.90

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128 GB

### Disk Manufacturer

Sandisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Server/x86_64/iso/Fedora-Server-dvd-x86_64-Rawhide-20230331.n.0.iso

### What happened?

when launching through Ventoy error message (attached Screenshot) Tried different USB ports - Issue persists.
![IMG_20230401_155736133](https://user-images.githubusercontent.com/57437119/229281517-6316e954-2159-4f41-8a92-f4370b8d9ec6.jpg)

**Comment by ventoy** [comment]
Checksum the ISO as in the following gif and upload your result here:
https://github.com/ventoy/Ventoy/blob/master/ICON/filechecksum.gif

**Comment by jdb130496** [comment]
Just noticed that after I posted the above bug, the repository has changed and new iso has been posted. I will download that, edit the issue above, will checksum the iso as per method you have mentioned above. Request to wait. Keeping this issue opened.

**Comment by jdb130496** [comment]
New ISO worked. I think, you were right. I may have missed checksum part in old ISO. There may have been corruption during download. Incredibly sorry.
