### ISSUE TITLE
[issue]: winget安装ventoy失败，0x80070032

### ISSUE THREAD

**Issue by ChongChengAC** [ventoy/Ventoy#2328]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.88

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

500GB

### Image file checksum (if applicable)

None

### What happened?

在win11家庭中文版通过winget安装ventoy出现意外错误：
![image](https://user-images.githubusercontent.com/63496547/229339939-97e19d86-2a03-4ef4-a456-59a3f3e30f61.png)

**Comment by ventoy** [comment]
Ventoy 官方不支持 winget 安装，这个应该是其他人弄的。
请从Ventoy 官网下载安装包安装。
