### ISSUE TITLE
[issue]: emulate iso (cd-file) into usb-hdd (sandisk). Bliss OS 15.x

### ISSUE THREAD

**Issue by Mas4hmad** [ventoy/Ventoy#2329]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.90

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

None

### What happened?

i wanna install bliss OS iso file into USB.
when i boot with ventoy (1.0.90 + GPT), the kernel was found nothing to media file, maybe because ISO file only emulate cd-rom drive.

is Sandisk USB drive can only boot with USB Image (*.img file like openindiana*.img or freebsd*.img)?

though i was able boot up artix*.iso or ubuntu*.iso and that derivative.

so i tought it was can emulate iso file to usb drive

**Comment by ventoy** [comment]
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/4591883988
https://www.ventoy.net/en/doc_github_ci.html

**Comment by Mas4hmad** [comment]
> <https://github.com/ventoy/Ventoy/actions/runs/4591883988>

yes. this link now fix the issue, and the boot have worked succesfully.
