### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by TheTrueColonel** [ventoy/Ventoy#2332]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.88

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

OPNsense-23.1-OpenSSL-dvd-amd64.iso

### Image file checksum type

SHA256

### Image file checksum value

95962AD9C64EC9BD19D3B91CAAC0AB1E458D93F2003185A5AE56903A00A6669B

### Image file download link (if applicable)

https://opnsense.org/download/

### Test environment

Dell Optiplex 3020

### More Details?

Tested with the VGA image (.img) and the DVD image (.iso), and the VGA version failed no matter what BIOS mode I had set, but the DVD version worked perfectly fine first try.

**Comment by ventoy** [comment]
Thanks!

For OPNsense, only .iso file is supported, .img file is NOT supported.

#2326

**Comment by ventoy** [comment]
Thanks!

**Comment by github-tomster** [comment]
i can **not** confirm

`OPNsense-23.1-OpenSSL-dvd-amd64.iso`
on
`VENTOY 1.0.94` 
- MBR or GPT style
- secure boot disabled
- uefi boot 

no progress after 'boot' with error:
`mounting from cd9660:/dev/iso9660/opnsense_install failed with error 19`

**Comment by pierrehenrymuller** [comment]
I confirm that not work with 23.1 and with 23.7 with vga or iso file.

**Comment by CrazyWolf13** [comment]
@ventoy I can also confirm it is NOT working, getting `error 19` Seems the bootloader of opnsense is unable to detect the right partition.

**Comment by l8gravely** [comment]
Not working for me either on a Protectli 4 port system, I can boot using ventoy using the 23.7 DVD ISO image, but then it hangs:

da0: Serial Number 070119BE90DA6124
da0: 40.000MB/s transfers
da0: 118236MB (242147328 512 byte sectors)
da0: quirks=0x2<NO_6_BYTE>
mountroot: waiting for device /dev/iso9660/OPNSENSE_INSTALL...
Mounting from cd9660:/dev/iso9660/OPNSENSE_INSTALL failed with error 19.

Loader variables:
  vfs.root.mountfrom=cd9660:/dev/iso9660/OPNSENSE_INSTALL
  vfs.root.mountfrom.options=ro

Manual root filesystem specification:
  <fstype>:<device> [options]
      Mount <device> using filesystem <fstype>
      and with the specified (optional) option list.

    eg. ufs:/dev/da0s1a
        zfs:zroot/ROOT/default
        cd9660:/dev/cd0 ro
          (which is equivalent to: mount -t cd9660 -o ro /dev/cd0 /)

  ?               List valid disk boot devices
  .               Yield 1 second (for background tasks)
  <empty line>    Abort manual input
