### ISSUE TITLE
[issue]: Fedora does not boot

### ISSUE THREAD

**Issue by nuqleo** [ventoy/Ventoy#2333]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.90

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Image file checksum (if applicable)

None

### Image file download link (if applicable)

https://download.fedoraproject.org/pub/fedora/linux/releases/37/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-37-1.7.iso

### What happened?

Fedora 37 live image does not boot with Ventoy 1.0.90.

dracut-initqueue error: unknown filesystem type 'ntfs'
https://imgur.com/a/LUKCTHW

Image boots fine with Ventoy 1.0.89 and earlier versions.

**Comment by ventoy** [comment]
1. Did you format Ventoy partition in NTFS file system?
2. Did you use any ventoy.json ?
3. Did you enable `VTOY_LINUX_REMOUNT` option?

**Comment by nuqleo** [comment]
No problem with the same partition and Ventoy 1.0.89.

**Comment by ventoy** [comment]
It's a bug introduced in 1.0.90.
I have fixed it, you can try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/4597478516
https://www.ventoy.net/en/doc_github_ci.html

**Comment by nuqleo** [comment]
I confirm Fedora boot fixed with ventoy-04031409.
Thanks.

**Comment by ventoy** [comment]
Fixed in the latest 1.0.91

**Comment by wolf-yuan-6115** [comment]
> Fixed in the latest 1.0.91

I'm facing same issue here with ventoy 1.0.91, on USB stick is Fedora 38 workstation iso file.

![20230607_191253_HDR.jpg](https://github.com/ventoy/Ventoy/assets/58245644/ecaee990-cefe-4ced-aeff-ef67f4533006)

**Comment by wolf-yuan-6115** [comment]
Ventoy GUI:

![image](https://github.com/ventoy/Ventoy/assets/58245644/b89917b0-883b-44a2-b558-97a9cb6fdfd2)

**Comment by navaneeth-dev** [comment]
Fedora Sway and Fedora Everything ISOs not booting but Fedora Workstation works with Ventoy.

Using Fedora Media Writer I was able to boot into Sway and Everything.

Link to Fedora Matrix details: https://matrix.to/#/!vhfPzfVuWUpUJacVPM:matrix.org/$PG8BX5ibP2BF-MUBvr9bb4uH7ynb0PPTxUnv82TEDa8?via=fedora.im&via=matrix.org&via=tchncs.de

![image](https://github.com/ventoy/Ventoy/assets/32010211/aebeeee5-2eaf-417c-afe3-b81a40b55ff8)

**Comment by harusharu** [comment]
> Fixed in the latest 1.0.91

That same issue getting now, with fedora [ref](https://github.com/ventoy/Ventoy/issues/2333#issuecomment-2158567578)
