### ISSUE TITLE
[issue]: 不支持原生4K扇区

### ISSUE THREAD

**Issue by akio1321** [ventoy/Ventoy#2337]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.91

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

256

### Disk Manufacturer

Lenovo

### Image file checksum (if applicable)

None

### What happened?

A bug happened! 不支持原生4K的磁盘。请帮帮我。谢谢
盘的型号是Lenovo Thinkplus TU202

**Comment by ventoy** [comment]
没办法，当前不支持原生4K的盘。

**Comment by xinxinenjoy** [comment]
> 没办法，当前不支持原生4K的盘。

请问现在的版本支持原生4k的盘了么？

**Comment by cygbs** [comment]
> > 没办法，当前不支持原生4K的盘。
> 
> 请问现在的版本支持原生4k的盘了么？

<img width="1404" height="554" alt="Image" src="https://github.com/user-attachments/assets/7382d53d-2e25-46d5-9530-b943bfcdf8b1" />

来自25年的版本仍然没有支持。
