### ISSUE TITLE
[issue]: Arch Linux ISO is not booting and outputs syntax errors

### ISSUE THREAD

**Issue by TheBACKTRACK** [ventoy/Ventoy#2338]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.91

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64GB

### Disk Manufacturer

Samsung

### Image file checksum (if applicable)

None

### Image file download link (if applicable)

https://archlinux.org/download

### What happened?

I can't boot Arch Linux ISO image using Ventoy from my 64GB Samsung USB
It gives me 8-9 syntax error and not booting

**Comment by ventoy** [comment]
Some photos?

**Comment by TheBACKTRACK** [comment]
Somehow, this error have disappeared after 1 day, and Arch Linux successfully started

**Comment by ezkha** [comment]
Yeah, that probably was a file corruption error.
Also happened to me. I should've checksummed myself.
