### ISSUE TITLE
[issue]: no ventoy partition in AOMEI Backuper

### ISSUE THREAD

**Issue by iopia** [ventoy/Ventoy#2339]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.91

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

512GB

### Disk Manufacturer

Transcend 910 

### Image file checksum (if applicable)

None

### What happened?

when working through usb 3 in the winpe version of aomei backup there are no flash drive partitions
the flash drive is formatted as an external hdd (factory condition). in usb 2.0 mode are visible
when the flash drive is flashed into the usb flash drive state, then the partitions are visible in usb 3.0, but this mode cuts the speed

**Comment by steve6375** [comment]
?? don't understand ?? what is 'usb flash drive state' ?  How can you format it as an external hdd?

**Comment by iopia** [comment]
![usb-flash Sandisk](https://user-images.githubusercontent.com/8014237/230593107-dae8381c-2c3d-4dda-a426-bb64915683ab.JPG)
![usb-hdd Transcend 910](https://user-images.githubusercontent.com/8014237/230593111-2bdeaeb3-9c9d-4a8e-a8d8-796657296d3f.JPG)

transcend appears as an external hard drive now

**Comment by steve6375** [comment]
under what OS?

**Comment by iopia** [comment]
aomei backuper (winPE) building on Windows 10 (build 19045.2728 and older)

**Comment by steve6375** [comment]
Windows Explorer under WinPE ?

**Comment by iopia** [comment]
No, it's on full Windows.
on winPE only backuper

**Comment by steve6375** [comment]
I did not understand that?
I have a JetFlash 920 flash drive and that cannot be detected by Strelec WinPE.
This is due to missing drivers in WinPE.
A full Windows OS should be able to detect the drive.

**Comment by iopia** [comment]
my 910 is recognized in Strelec WinPE (this time I'm running the backuper)
I assumed it was a driver problem.
I'll try to add 3 drivers to usb in the backup and write

**Comment by iopia** [comment]
the problem is solved by building on winPE 11 22r2
"usb iscsi transcend 910" flash drive is visible
