### ISSUE TITLE
Autorun option

### ISSUE THREAD

**Issue by kmm2** [ventoy/Ventoy#234]
On a small flash drive where only one ISO fits in, it would be optimal to auto-boot such ISO directly. Can you add this option to the global configuration?

**Comment by ventoy** [comment]
In the next release, I will add a timeout option in global control plugin. 
You can set it to 1 for example, then after 1 second, the first iso will be selected and boot.

**Comment by kmm2** [comment]
Perfect, thank you.

**Comment by neradp** [comment]
It would be better to determine which iso autoboot.

**Comment by ventoy** [comment]
It's in the development plan of Ventoy-1.0.14 #243

**Comment by kmm2** [comment]
I've tried 1.0.14 and see a problem. In ventoy.json I have only
```
{
    "control": [
        { "VTOY_MENU_TIMEOUT": "1" },
    ]
}
```
but the first ISO does not boot after 1s.

I have to set VTOY_DEFAULT_IMAGE for it to autoboot and update it whenever file/iso version changes. Can you please fix it?

**Comment by ventoy** [comment]
You have a syntax error in the json (remove the `,`   after  `{ "VTOY_MENU_TIMEOUT": "1" }`)
I tested it and it works fine.

**Comment by kmm2** [comment]
My bad, you are right, v1.0.14 is flawless.
Thank you again!

**Comment by neradp** [comment]
It would be great if you extend "auto_install" with autoboot  feature too.

**Comment by ventoy** [comment]
> It would be great if you extend "auto_install" with autoboot feature too.

You can use VTOY_DEFAULT_IMAGE to set a default image, why we need to set in auto_install configuration?

**Comment by neradp** [comment]
Yes, im using VTOY_DEFAULT_IMAGE. I wanna use unattend the windows setup as default use case for my usb. I have multiple windows isos, multiple unattend.xml files in that usb, and wanna use one as default action without my interaction.

**Comment by ventoy** [comment]
The menu always auto select the 1st template script. So I think a `noprompt` option can be added to the `auto_install` as follows:

```
{
    "auto_install" : [
        {
            "image": "/ISO/cn_windows_server_2012_r2_vl_x64_dvd_2979220.iso",
            "template": "/ventoy/script/windows_unattended1.xml",
            "noprompt": true
        }
    ]
}
```

**Comment by ventoy** [comment]
`autosel` option is added in new release.
