### ISSUE TITLE
[Success Image Report]: LMDE 5 Elsie x64

### ISSUE THREAD

**Issue by a-oakman** [ventoy/Ventoy#2343]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.91

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

lmde-5-cinnamon-64bit.iso

### Image file checksum type

SHA256

### Image file checksum value

8f351d30e97f3a9c3f3848fde781c7f3758abd0f8ddf120827d98a5832cfa027

### Image file download link (if applicable)

https://www.linuxmint.com/download_lmde.php

### Test environment

LibVirt standard OS

CPU: copy the host's configuration: AMD Ryzen 7 4700U with Radeon Graphics

2/8 virtual kernels 

RAM 3096 MB

### More Details?

This image file booted successfully in Ventoy.

Also I was able to set up a persistence. 

```sh
./CreatePersistentImg.sh -t ext4 -s 2048 -c persistence.conf -l persistence
```

`-l` option must be set to `persistence`, it is mandatory (see [Debian wiki](https://wiki.debian.org/DebianLive/LiveUsbPersistence)).

`-c` option must be set to `persistence.conf`, Debian requires it.

To achieve a persistence `persistent` option must be specified in Grub boot options (see [Stackoverflow](https://askubuntu.com/a/1249846)).

It should looks like:

```
/live/vmlinuz boot=live persistent initrd=...
```

**Comment by ventoy** [comment]
Thanks!
