### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by DidierSpaier** [ventoy/Ventoy#2355]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.91

### BIOS Mode

Both

### Partition Style

GPT

### Image file name

slint64-15.0-2.iso

### Image file checksum type

SHA256

### Image file checksum value

cc0421fdd9630d3bb3ea8ef338c7cfb7a29fd8df98ccbae3debed60847a976a3

### Image file download link (if applicable)

https://slackware.uk/slint/x86_64/slint-15.0/iso/slint64-15.0-2.iso

### Test environment

Custom made desktop.

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
