### ISSUE TITLE
[Success Image Report]: ubuntu-23.04-desktop-amd64.iso

### ISSUE THREAD

**Issue by mavericane** [ventoy/Ventoy#2359]
### Official Website List

- [x] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.91

### BIOS Mode

Both

### Partition Style

GPT

### Image file name

ubuntu-23.04-desktop-amd64.iso

### Image file checksum type

SHA256

### Image file checksum value

A8CD6CCFF865E17DD136658F6388480C9A5BC57274B29F7D5BD0ED855A9281A5

### Image file download link (if applicable)

https://releases.ubuntu.com/23.04/ubuntu-23.04-desktop-amd64.iso

### Test environment

Acer Aspire E1-530G

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
