### ISSUE TITLE
[issue]: Fedora 38 dosen`t boot

### ISSUE THREAD

**Issue by VolodymyrPanasyuk** [ventoy/Ventoy#2360]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.91

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128GB

### Disk Manufacturer

Kingston

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://download.fedoraproject.org/pub/fedora/linux/releases/38/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-38-1.6.iso

### What happened?

Boot stops there

![IMG_20230421_121642224](https://user-images.githubusercontent.com/117359181/233602800-d90b01b4-6888-4572-b3de-ce24d91b17ed.jpg)

**Comment by ventoy** [comment]
It's a bug, I have fixed it.  You can try the following CI release:  
https://github.com/ventoy/Ventoy/actions/runs/4764673300
https://www.ventoy.net/en/doc_github_ci.html

PS:
The bug only occurs when the ISO file name contains special characters(e.g.  `(` ), so if you rename your ISO file 
from `Fedora(Gnome)-38.iso` to for example `Fedora_Gnome-38.iso` then it should boot fine.
