### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by Roopee** [ventoy/Ventoy#2365]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.91

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

proxmox-ve_7.4-1.iso

### Image file checksum type

SHA256

### Image file checksum value

55b672c4b0d2bdcbff9910eea43df3b269aaab3f23e7a1df18b82d92eb995916

### Image file download link (if applicable)

https://www.proxmox.com/en/downloads?task=callelement&format=raw&item_id=681&element=f85c494b-2b32-4109-b8c1-083cca2b7db6&method=download&args[0]=7cbd6b95e91bcb90905180ec0bc4532d

### Test environment

HP EliteBook 8560p
BIOS: F.65 (UEFI Disabled)
CPU: i5-2520M (has VT-x and VT-d)
RAM: 8GB 1x 8GB PC3L-12k8
Graphics: CPU: Intel HD 3000 + Radeon HD 6470M

Target drive for Proxmox installation: SanDisk SDSSDP-064G in USB3 caddy

### More Details?

Ventoy installed on 32GB uSD card (Kingston Canvas Select Plus) in MicroSDXC USB3 card reader.
This image file booted successfully in Ventoy. 
Proxmox VE installed and runs correctly.

**Comment by ventoy** [comment]
Thanks!
