### ISSUE TITLE
[issue]: I'm trying to update to the latest release but ./tool/ventoy_lib.sh: line 63: ./tool/x86_64/mkexfatfs: No such file or directory

### ISSUE THREAD

**Issue by levdopa** [ventoy/Ventoy#2366]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.88

### What about latest release

No. I didn't try the latest release.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64GB

### Disk Manufacturer

Samsung

### Image file checksum (if applicable)

No.

### What happened?

trying to run
doas sh Ventoy2Disk.sh -u /dev/sdb
I get 
./tool/ventoy_lib.sh: line 63: ./tool/x86_64/mkexfatfs: No such file or directory

trying to run  doas bash VentoyWeb.sh
VentoyWeb.sh: line 104: ./tool/x86_64/V2DServer: No such file or directory

I'm on 64bit

**Comment by levdopa** [comment]
I updated it from another operating system. I'll leave issue for now incase someone has a fix.

**Comment by wiz64** [comment]
Not enough information available for debugging, if possible add more info or consider close this issue

**Comment by ventoy** [comment]
What linux distro did you use?
Run 
```
ldd  ./tool/x86_64/V2DServer
```
