### ISSUE TITLE
[issue]: add support inject file to freedos live image

### ISSUE THREAD

**Issue by efirshik** [ventoy/Ventoy#2370]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.91

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

64gb

### Image file checksum (if applicable)

None

### Image file download link (if applicable)

https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.3/official/FD13-LiteUSB.zip

### What happened?

a try add zip file with bios in freedos live image:
```
{
    "injection_legacy":[
        {
            "image": "/FD13LITE.img",
            "archive": "/bios.zip"
        }
    ]
}

```
but after boot freedos file bios missing. i try check X: disk in freedos but they write "no disk". boot to freedos with memdisk mode.
This good option for inject file bios to freedos live image!

**Comment by ventoy** [comment]
injection plugin only support ISO file.
