### ISSUE TITLE
[issue]: System partition capped at 2GB?

### ISSUE THREAD

**Issue by twojapiez** [ventoy/Ventoy#2371]
### Official FAQ

- [x] I have checked the official FAQ.

### Ventoy Version

1.0.91

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

128

### Disk Manufacturer

goodram

### Image file checksum (if applicable)

None

### Image file download link (if applicable)

https://zorin.com/

### What happened?

Im trying to run zorinos and i get a problem with the size of the partiton that its on ive tried changing some stuff and still no help how do i change/fix it?

**Comment by wiz64** [comment]
what is the partition type you've formatted ventoy to ? is it fat32 ?

**Comment by twojapiez** [comment]
> what is the partition type you've formatted ventoy to ? is it fat32 ?

I believe it's in exfat i didn't change anything

**Comment by wiz64** [comment]
Try playing with options > Partition Configuration. also check if iso is not corrupted (verify hash)

**Comment by twojapiez** [comment]
> Try playing with options > Partition Configuration. also check if iso is not corrupted (verify hash) 

I will try changing thanks
