### ISSUE TITLE
[Success Image Report]: Fedora 38

### ISSUE THREAD

**Issue by ManorSailor** [ventoy/Ventoy#2373]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.91

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

Fedora-Workstation-Live-x86_64-38-1.6.iso

### Image file checksum type

SHA256

### Image file checksum value

https://ftp.riken.jp/Linux/fedora/releases/38/Workstation/x86_64/iso/Fedora-Workstation-38-1.6-x86_64-CHECKSUM

### Image file download link (if applicable)

https://download.fedoraproject.org/pub/fedora/linux/releases/38/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-38-1.6.iso

### Test environment

Asus TUF A15 (FA506IC)
CPU: Ryzen 7 4800H
mGPU: AMD Radeon Vega 
dGPU: RTX 3050
BIOS: FA506IC.302

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
