### ISSUE TITLE
[issue]: Ventory进入镜像选择界面不能操控，不能用键盘控制上下左右，重新安装无效

### ISSUE THREAD

**Issue by 2496414612** [ventoy/Ventoy#2374]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.91

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

128GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

远景论坛

### What happened?

我在启动 Ventory 之后不能操控我的电脑，不能用键盘，不能选择进入哪个镜像文件，重新安装之后依旧出现这种情况，和这个问题一样：https://github.com/ventoy/Ventoy/issues/552   ，但是他关闭了 issue，并且也没说解决办法

补充一下：我的朋友可以正常启动，正常操控，都是联想笔记本，我的却不能🙁

搞好啦！！！

解决办法：进入选择界面之后重新插拔键盘或者鼠标，我在百度贴吧上看到的，这十几年来一直都存在这个问题

**Comment by usernamedd** [comment]
台式机，主板是华硕的，也是键盘不行。最开始是可以的，F2后找iso文件，我使用上下键选择文件夹，突然就不能用了，并且有时，我按下的向右剪头的按键，看界面的反应像是我按下了enter键。
重新插拔也没用。

**Comment by usernamedd** [comment]
看起来不是ventoy的问题，我使用multi-usb安装操作系统时，也遇到同样的问题
