### ISSUE TITLE
[Success Image Report]: Bodhi Linux 6.0.0

### ISSUE THREAD

**Issue by amaciotta** [ventoy/Ventoy#2375]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.91

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

bodhi-6.0.0-64-apppack.iso

### Image file checksum type

MD5

### Image file checksum value

88f674abeb1ddf662077508399e3de44

### Image file download link (if applicable)

https://sourceforge.net/projects/bodhilinux/files/6.0.0/bodhi-6.0.0-64-apppack.iso/download

### Test environment

Asus EeeBox 1007 

### More Details?

This image file booted successfully in Ventoy.
EeeBox page:
https://www.asus.com/commercial-desktop/eeebox_pc_eb1007
EeeBox spec:
https://www.asus.com/commercial-desktop/eeebox_pc_eb1007/specifications/

Intel Atom D410 is a 64bit CPU

**Comment by ventoy** [comment]
Thanks!
