### ISSUE TITLE
[Success Image Report]: manjaro-gnome-22.0.5-230316-linux61.iso

### ISSUE THREAD

**Issue by dobb13** [ventoy/Ventoy#2376]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.90

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

manjaro-gnome-22.0.5-230316-linux61.iso

### Image file checksum type

SHA512

### Image file checksum value

fce727ad9274aa74fb1cf82aa78f7704e2dc4de508bd7c8ca738b9156f0a630176cdd2a19a3d593bbad9c11479e71a17405507fb17ac84b6164bb57388537e51

### Image file download link (if applicable)

https://download.manjaro.org/gnome/22.0.5/manjaro-gnome-22.0.5-230316-linux61.iso

### Test environment

AMD Ryzen 2600X with 32 GiB DDR4, Radeon 6900 XT

### More Details?

This image file booted successfully in Ventoy.

SHA256 checksum:
2fc482f8a652f1905bbfafc5aa9fe4e0f1a68d82985a69614105cc5c63e0ecd5

SHA1 checksum:
54763e50055ad173a94088f38865aba496dfa9dd

MD5 checksum:
21887b187375f39a6643381c78cc4cde

**Comment by ventoy** [comment]
Thanks!

**Comment by fxlmangutana** [comment]
can we run this manjaro-gnome-22.0.5-230316-linux61.iso with persistence ? how to do it? thank you
