### ISSUE TITLE
[issue]: Plugson writes empty ventoy.json file

### ISSUE THREAD

**Issue by tonyrulez** [ventoy/Ventoy#2377]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.91

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

64GB

### Image file checksum (if applicable)

None

### What happened?

Using `VentoyPlugson.exe`, I want to create the necessary `ventoy.json` file to enable Windows 11 hardware check and online account requirement bypasses. Doing so, the program creates the following file: `\ventoy\ventoy.json`
However, the file is empty, it only contains the following:

```
{
}

```

Every time I change a setting in the WebUI, it says "Configuration successfully saved!". `ventoy.json` does get updated (there is even a `ventoy_backup.json` created), but it's still empty. Happens even when `VentoyPlugson.exe` is started with admin privileges. The flash drive is not write protected, and clearly the WebUI **can** create a new file there, only for some reason it leaves it empty.

**Comment by steve6375** [comment]
Default is to bypass checks, so nothing is needed

**Comment by tonyrulez** [comment]
Interesting, so instead of writing
`{ "VTOY_WIN11_BYPASS_CHECK": "1" }`
it just deletes the line. Ok, thanks!
