### ISSUE TITLE
Impossible to install Ventoy

### ISSUE THREAD

**Issue by noussibeau** [ventoy/Ventoy#238]
[log.txt](https://github.com/ventoy/Ventoy/files/4797887/log.txt)

I've a W10 PC,a 128GO SANDISK USB Key
impossible to install Ventoy : each time I've a message sayoing "a error occured during install" and that's all.It's true for Ventoy 12 & 13
Thank for an idea
![image](https://user-images.githubusercontent.com/67099669/85006877-00b19600-b15b-11ea-86c0-77d81fe9f49b.png)

**Comment by PeterCodar** [comment]
I found a workaround for my Sandisk 64GB USB 3.0 Stick:
I have deleted the existing partition(s) completeley without any reformat attempts.
With such a "raw" unformated stick, the installation worked.

**Comment by noussibeau** [comment]
Thanks for help.
I did it without success...

**Comment by noussibeau** [comment]
closed by error!

**Comment by ventoy** [comment]
@noussibeau 
This is an old issue. I will close it now.
If you still have problem with latest Ventoy release, you can reopen the issue.
