### ISSUE TITLE
[feature request]: add option to set default boot mode for each iso

### ISSUE THREAD

**Issue by 2468-13579** [ventoy/Ventoy#2382]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.91

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

any

### Image file checksum (if applicable)

None

### What happened?

Some isos only work using a specific boot mode (normal, grub2, memdisk...). Currently you have to remember which one works if the normal one doesn't.
Would it be possible to add an option to ventoy.json where you can set the default boot mode for each iso when pressing enter once (or the one that is selected by default). I imagine this could be done similarly to alias, like specifying the image and the boot mode like 0,1,2,...

Thanks in advance.

**Comment by ventoy** [comment]
You can use special identifier in the ISO name.
Please refer: https://www.ventoy.net/en/doc_name_identifier.html

**Comment by 2468-13579** [comment]
Thanks! Don't know how I didn't find that.
