### ISSUE TITLE
[issue]: Can't boot Fedora 38 iso

### ISSUE THREAD

**Issue by OPRESEK** [ventoy/Ventoy#2384]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.91

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

Goodram

### Image file checksum (if applicable)

None

### Image file download link (if applicable)

https://download.fedoraproject.org/pub/fedora/linux/releases/38/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-38-1.6.iso    https://download.fedoraproject.org/pub/fedora/linux/releases/38/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-38-1.6.iso

### What happened?

Both Fedora Workstation 38 Gnome and Fedora 38 KDE images are not booting

https://imgur.com/1m94N98
mount: /run/initramfs/isoscan: unknown filesystem type 'ntfs'

The flash drive is formatted in exFAT with the MBR partition style

![344309152_3204270423196756_1199452495042343232_n](https://user-images.githubusercontent.com/30323604/236690775-7e1a405f-90f5-4a5a-8667-dccc5f0f96f6.jpg)

**Comment by Silejonu** [comment]
Please check if your bug is the same as #2385.

**Comment by OPRESEK** [comment]
It worked, thanks.
