### ISSUE TITLE
[issue]: Fedora 38 does not boot when a directory in its path contains a space on Ventoy 1.0.90+

### ISSUE THREAD

**Issue by Silejonu** [ventoy/Ventoy#2385]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.91

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

256GB

### Disk Manufacturer

SanDisk / Samsung

### Image file checksum (if applicable)

None

### Image file download link (if applicable)

https://download.fedoraproject.org/pub/fedora/linux/releases/38/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-38-1.6.iso

### What happened?

When booting Fedora 38, it reaches GRUB, but hangs for a while, then after a couple minutes, the screen gets spammed by error messages and ends up on this:
![IMG_20230508_093259](https://user-images.githubusercontent.com/48565914/236763997-aededb95-11f3-4ae6-bf82-225e4677b693.jpg)

The problem only occurs when a directory in the ISO path contains a space:
- `/Ventoy/Fedora Workstation/Fedora-Workstation-Live-x86_64-38-1.6.iso` will not boot
- `/Ventoy/Fedora/Fedora-Workstation-Live-x86_64-38-1.6.iso` will boot correctly

I could reproduce the bug in the following conditions:
- MBR **and** GPT style partitions
- exFAT filesystem (I did not try with NTFS or anything else)
- Ventoy 1.0.90 and 1.0.91
- 3 different computers, with various configurations
- 3 different flash drives

The problem is not present on Ventoy 1.0.89. Other operating systems seem to not be affected.

**Comment by ventoy** [comment]
Please refer #2360

**Comment by Silejonu** [comment]
> Please refer #2360

This does indeed fix the issue, thank you.

I checked for existing bug reports, but did not think of checking already closed ones, sorry.
