### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by TheBunnyMan123** [ventoy/Ventoy#2389]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.91

### BIOS Mode

Legacy

### Partition Style

MBR

### Image file name

EndeavourOS_Cassini_Nova-03-2023_R1.iso

### Image file checksum type

SHA512

### Image file checksum value

d60fd83ef24b0d62208f48d6de37ea62e056b01dedfe86cbd0bd464f6eb7130c141cf931144d3426270d8e8b53db2d2dd4777b3a49b150b70fac8bec10c91d4c

### Image file download link (if applicable)

https://github.com/endeavouros-team/ISO/releases/download/1-EndeavourOS-ISO-releases-archive/EndeavourOS_Cassini_Nova-03-2023_R1.iso

### Test environment

Lenovo IdeaPad z50-75

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
