### ISSUE TITLE
[Success Image Report]: Ubuntu 23.04

### ISSUE THREAD

**Issue by dmitrygribenchuk** [ventoy/Ventoy#2393]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.93

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

ubuntu-23.04-desktop-amd64.iso

### Image file checksum type

SHA1

### Image file checksum value

3c5df0e65db679c12134e044ad4440df6f7d22f9

### Image file download link (if applicable)

https://releases.ubuntu.com/23.04/ubuntu-23.04-desktop-amd64.iso

### Test environment

Lenovo L390

### More Details?

This image file booted successfully in Ventoy.

**Comment by dmitrygribenchuk** [comment]
Hey. Is it possible to accept it and close?

**Comment by ventoy** [comment]
Thanks!
