### ISSUE TITLE
MX Linux 19.2 blurred screen in GRUB

### ISSUE THREAD

**Issue by EldersJavas** [ventoy/Ventoy#242]
感谢您的ventoy:

MX19.2大概两个周前发布了,我通过Ventoy启动发现进MX自己的GRUB的时候出现花屏,盲按键盘可以操作.
在Dell笔记本主板/技嘉ATX主板均出现这种情况(其他主板不知)
经测试,在VM/VBOX/QEMU均正常,原版ISO用DD和DVD模式考入U盘启动均未出现问题.
大概是主板集显兼容问题吧...(虽然没什么大碍)
还要反馈一个暗性问题:
大概是ventoy在格式化U盘时有些bug,每次做完U盘时,分区表终止位置参数都会溢出(基于DG报错)
基本上DG和其他硬盘软件很多功能都无法操作.例如修改或重建分区表.本以为是U盘问题,结果换了一个还是有问题(换了个闪迪),重新格式化解决一切,之前还有一次出现无法拷贝文件的问题,每次拷贝win都报错无法考入CDIR驱动器,要求重新格式化,最后低格解决...

希望ventoy能够越做越好.

**Comment by ventoy** [comment]
MX  19.2 是什么模式 Legacy 还是 UEFI？

第二个问题我再确认一下。

**Comment by EldersJavas** [comment]
Legacy模式花屏.UEFI没问题.
本来今天想去试试19.1,结果...昨天立的Flag成立了...
U盘又不能考文件了>_<
看图片:
<a href="https://sm.ms/image/YNIp9dVT3MUaybl" target="_blank"><img src="https://i.loli.net/2020/06/21/YNIp9dVT3MUaybl.png" ></a>
![捕获.PNG](https://i.loli.net/2020/06/21/YNIp9dVT3MUaybl.png)

额...还望大佬能够解决问题,我低格后再测试19.1.

**Comment by EldersJavas** [comment]
刚刚测试了MX19.1和19.1April两个版本,Legacy模式均花屏,UEFI没问题.

**Comment by EldersJavas** [comment]
刚刚又在ThinkPad上试了试,没出现花屏现象(不支持UEFI的2011年的笔记本)
