### ISSUE TITLE
[issue]: D盘没了 损失巨大

### ISSUE THREAD

**Issue by tyza66** [ventoy/Ventoy#2421]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.91

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Image file checksum (if applicable)

None

### What happened?

触发D盘消失条件：就是我使用window版工具制作U盘的时候，第一次制作成功之后发现选错了格式，就换了个格式重新制作，这时候我觉得进度条卡住了，就拔掉了一下U盘，之后再插上，进度条有回退，一直插着进度条不动，点了几下刷新U盘列表，之后关闭制作U盘工具，之后重新打开，选择格式，制作U盘成功。事后发现D盘没了，变成了未分区，里面东西没能找回来，重做系统了。

**Comment by woshishabii** [comment]
做一半拔uu盘你怎么敢的（雾）

**Comment by tyza66** [comment]
🤦
