### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by Liad-n** [ventoy/Ventoy#2423]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.87

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

ubuntu-22.04.2-desktop-amd64.iso

### Image file checksum type

SHA256

### Image file checksum value

b510dd1250af171bdf6289ff927fffb4c077f32450f5abebc11e06b235cb6fcb

### Test environment

Lenovo Thinkpad E15 2023

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
