### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by dreamer2908** [ventoy/Ventoy#2425]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.91

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

tiny10 2303 x86.iso

### Image file checksum type

SHA256

### Image file checksum value

c4ac50930ed9ab24e7950421700865046aba01f110537b6cf3cd475c0486c8ab

### Image file download link (if applicable)

https://archive.org/details/tiny-10-NTDEV

### Test environment

Centerm C92 (IA32 UEFI on 64-bit CPU Intel J1800)

### More Details?

This image file booted successfully in Ventoy. Windows installation also completed sucessfully.

**Comment by ventoy** [comment]
Thanks!
