### ISSUE TITLE
[Success Image Report]: VMware ESXi

### ISSUE THREAD

**Issue by leoppro** [ventoy/Ventoy#2431]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.57

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

VMware-VMvisor-Installer-8.0U1a-21813344.x86_64.iso

### Image file checksum type

MD5

### Image file checksum value

--

### Test environment

VM

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
