### ISSUE TITLE
传统启动微PE花屏

### ISSUE THREAD

**Issue by LittleDeng1** [ventoy/Ventoy#244]
选择镜像后如下图
![bd64ed61e11fb75e4d4ad42adfce322](https://user-images.githubusercontent.com/62782358/85190048-0b009b00-b2e7-11ea-8f46-879d43c03b61.jpg)
因为选的是微pe 随后倒计时结束后 花屏结束 加载文件完成后 如下图
![521663c5a3e3572e8f1843b54c7cf49](https://user-images.githubusercontent.com/62782358/85190056-1c49a780-b2e7-11ea-9796-68d72a8946eb.jpg)
这块盘是512G nvme转usb 多数机子用这个盘复现问题 只有传统引导会 uefi不会
另一块240G SATA转usb的盘 没有这个问题

**Comment by yuko12300** [comment]
我也出现了这个问题，同样的iso文件，在uefi引导系统下制作的ventoy启动盘，在传统引导下花屏。正在尝试重新在传统引导系统上制作启动盘，希望可以解决。

**Comment by yuko12300** [comment]
已解决，请尝试使用ventoy.json定义需要扫描的iso文件路径，不要让ventoy扫描全盘，参见 [https://www.ventoy.net/cn/plugin_control.html](url) 
及创建方法
[https://www.ventoy.net/cn/plugin_entry.html](url)

**Comment by LittleDeng1** [comment]
@yuko12300 还是花了
![$F`YFA CU_5U}BF{JR97MR1](https://user-images.githubusercontent.com/62782358/85378603-5af09380-b56d-11ea-8492-cb0e02eb4fcf.png)

**Comment by yuko12300** [comment]
是否在u盘内存储了其他的文件？目前看来是由于文件数量较多读取缓慢导致的问题。

**Comment by yuko12300** [comment]
添加指令，将默认视图改为树状图模式，经过多次尝试，在树状图模式下启动正常 @LittleDeng1

**Comment by LittleDeng1** [comment]
300+G/476G
树状我等上班再试试
@yuko12300

**Comment by LittleDeng1** [comment]
@yuko12300 树状还是花了

**Comment by LittleDeng1** [comment]
疑似线材/接口问题 多次测试偶尔正常

**Comment by nekoprpr** [comment]
按F5 降低分辨率就好了....

**Comment by LittleDeng1** [comment]
@nekoprpr 改用cli也行 当时提issue还没cli
