### ISSUE TITLE
this is not a standard ventoy device and is not supported (12)

### ISSUE THREAD

**Issue by wpc1825** [ventoy/Ventoy#2445]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

ventoy-1.0.92-windows

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

128

### Disk Manufacturer

Lexar

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://www.microsoft.com/software-download/windows11

### What happened?

When trying to install windows, or even linux, the following message appears at boot. "this is not a standard ventoy device and is not supported (12)"

**Comment by 508loopdetect** [comment]
Same here, same version installed today. came from 1.0.88

**Comment by ventoy** [comment]
Ventoy-1.0.92 was was deprecated, please use 1.0.93

**Comment by wpc1825** [comment]
> Ventoy-1.0.92 was was deprecated, please use 1.0.93

Thank you.
