### ISSUE TITLE
[Success Image Report]: blendOS.iso (blendOS GNOME Edition)

### ISSUE THREAD

**Issue by cindrmon** [ventoy/Ventoy#2455]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.93

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

blendOS.iso

### Image file checksum type

SHA512

### Image file checksum value

9f06ce936eb2ad3d44a2b42743c5699d812d74aed894e7996a9cf3272c132a91360beec88ae7e5f4e778e758ee6725dc32f46054e9b8d544a8514836c5c9ac4b

### Image file download link (if applicable)

https://images.blendos.co/track/gnome/download

### Test environment

Lenovo ThinkPad T470s Laptop

### More Details?

This image file booted successfully in Ventoy. It took a little long to load in normal mode (~2-4 mins), but it loaded up the GNOME DE flawlessly.

![Screenshot from 2023-06-26 15-14-27](https://github.com/ventoy/Ventoy/assets/37018771/2335a43c-6f33-46a8-ba35-e6874cf7003d)

**Comment by ventoy** [comment]
Thanks!
