### ISSUE TITLE
[issue]: Synchronous Exception at 0x0000000075DD52A8

### ISSUE THREAD

**Issue by conanlm** [ventoy/Ventoy#2458]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.93

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

128

### Image file checksum (if applicable)

None

### What happened?

华为擎云L420
CPU:麒麟9006C 
OS:麒麟银河

Synchronous Exception at 0x0000000075DD52A8

**Comment by ventoy** [comment]
@conanlm 
You can try the latest 1.0.94  release.

**Comment by conanlm** [comment]
> @conanlm You can try the latest 1.0.94 release.

谢谢，更新1.0.95后已经可以用了
