### ISSUE TITLE
[Success Image Report]: BlendOS 3

### ISSUE THREAD

**Issue by turtaf** [ventoy/Ventoy#2471]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.93

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

blendOS.iso

### Image file checksum type

MD5

### Image file checksum value

93a50be465b63fce5475e74d2d9d48b5

### Image file download link (if applicable)

https://images.blendos.co/track/gnome/download

### Test environment

Lenovo ideapad C340 

### More Details?

This image file booted successfully in Ventoy. The one reported here is the Gnome version, also KDE version worked

**Comment by ventoy** [comment]
Thanks!
