### ISSUE TITLE
[issue]: VTOY_LINUX_REMOUNT=1 does not work on Pop!_OS 22.04 LTS

### ISSUE THREAD

**Issue by Misabthepro** [ventoy/Ventoy#2475]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.93

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

32

### Disk Manufacturer

Sandisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://iso.pop-os.org/22.04/amd64/intel/31/pop-os_22.04_amd64_intel_31.iso

### What happened?

Hello,
I'm trying to access the bigger ventoy partition from nautilus but it show an error that it couldn't mount it.
Pop!_OS is based on ubuntu. Help would really be appreciated.
Thanks

**Comment by railgauge** [comment]
Remount used to work for me on an Arch VHD but I have the same issue after a recent system upgrade. 

| Ventoy          | 1.0.93       |
|-----------------|--------------|
| Mode            | UEFI         |
| Partition Table | GPT          |
| Filesystem      | NTFS         |
| Disk            | WD 512GB SSD |

| OS                                      | Kernel                 | Works? |
|-----------------------------------------|------------------------|--------|
| Arch (VHD)                              | 6.4.2-arch1-1          | No     |
| Arch (VHD)                              | 6.4.2-zen1-1-zen       | No     |
| EndeavourOS_Cassini_Nova-03-2023_R1.iso | 6.2.8-arch1-1          | Yes    |
| EndeavourOS_Cassini_Nova-03-2023_R2.iso | 6.3.4-arch1-1          | Yes    |
| pop-os_22.04_amd64_intel_31.iso         | 6.2.6-76060206-generic | No     |


When remount is not working, `sudo dmesg` says `Can't open blockdev`

**Comment by Daniel100022** [comment]
Try reinstalling Ventoy cause the way ventoy makes I.S.O be able to be bootable is it mounts the I.S.O and then boots to it but it cannot mount it on ur side due to a software issue .

**Comment by Daniel100022** [comment]
> Try reinstalling Ventoy cause the way ventoy makes I.S.O be able to be bootable is it mounts the I.S.O and then boots to it but it cannot mount it on ur side due to a software issue. If this issue keeps on happening DONT boot it in normal mode, boot it in GRUB2 mode

**Comment by Misabthepro** [comment]
> > Try reinstalling Ventoy cause the way ventoy makes I.S.O be able to be bootable is it mounts the I.S.O and then boots to it but it cannot mount it on ur side due to a software issue. If this issue keeps on happening DONT boot it in normal mode, boot it in GRUB2 mode
> 
> 

Already tried grub2 mode, doesn't work. Also tried reinstalling, still not working.

**Comment by Daniel100022** [comment]
> > > Try reinstalling Ventoy cause the way ventoy makes I.S.O be able to be bootable is it mounts the I.S.O and then boots to it but it cannot mount it on ur side due to a software issue. If this issue keeps on happening DONT boot it in normal mode, boot it in GRUB2 mode
> > 
> > 
> 
> Already tried grub2 mode, doesn't work. Also tried reinstalling, still not working.

Then u might have a incompatibility issue with ur usb or computer

**Comment by babaric-dev** [comment]
This also happens on Ubuntu 23.04. I can't get it to work. Help?

**Comment by dhbaird** [comment]
A possibly related message appears in dmesg when booting with VTOY_LINUX_REMOUNT=1 and Ubuntu 23.04: `dm_patch: disagrees about version of symbol module_layout`. Might be related to discussion ongoing here: https://github.com/ventoy/Ventoy/issues/2234

**Comment by Atrate** [comment]
I can confirm that `VTOY_LINUX_REMOUNT=1` does not work with BlackArch linux on a VDI file as well.

**Comment by Atrate** [comment]
Updated `ventoy` to `1.0.96` and downloaded `vtoyboot 1.0.30`, re-ran the script inside the iso/tgz (inside the `.vdi` system), did not help. I set `VTOY_LINUX_REMOUNT=1` using `ventoyplugson`.
