### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by TwinCitiesTransplant** [ventoy/Ventoy#2479]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.91 (Ventoy Portable Version 1.0.91 for Windows)

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

neon-user-20230706-0717.iso

### Image file checksum type

SHA256

### Image file checksum value

ad3c9934b535c7ba64da184078c33a617ad50fbf5e8fe021373e5fa5edc8f2d9

### Image file download link (if applicable)

https://files.kde.org/neon/images/user/20230706-0717/neon-user-20230706-0717.iso

### Test environment

Lenovo ThinkPad T530

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
