### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by TwinCitiesTransplant** [ventoy/Ventoy#2487]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.91 (Ventoy Portable Version 1.0.91 for Windows)

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

KaOS-2023.04-x86_64.iso

### Image file checksum type

SHA256

### Image file checksum value

1126895cb8fa11c7acf37d10e82993c52363e1939ed1c53f1fb05a872b454556

### Test environment

Lenovo ThinkPad T530

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
