### ISSUE TITLE
Folder support in UI?

### ISSUE THREAD

**Issue by beltet** [ventoy/Ventoy#25]
It would be a really nice feature if you had support for folders in the UI.
In my use case it would be a nice feature as I have a SSD with my ISO's.
I would like to sort them in folder like "live" & "install". You can have them in folders on the drive, but the UI puts them all in the same list.
Hopefully it isn't to much work to get that feature.
Sincerely!

**Comment by dudefoxlive** [comment]
This would be great for keeping your ISOs organized.

**Comment by chromer030** [comment]
I think it can be done via scanning only for folders that contain ISO file/s on Ventoy's Startup scanning.

**Comment by ventoy** [comment]
You can try 1.0.08 with TreeView Mode.

**Comment by beltet** [comment]
> You can try 1.0.08 with TreeView Mode.

I will! Looks like what I wanted! Thanks!
