### ISSUE TITLE
[issue]: 华为擎云W515启动ventoy黑屏

### ISSUE THREAD

**Issue by SakuraMay** [ventoy/Ventoy#2501]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.94

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

32GB

### Image file checksum (if applicable)

None

### What happened?

我看到 #2488 中有关于华为擎云L410和L420的成功启动记录，看到他是关闭安全启动的。然后我在W515上也关闭了安全启动，在启动时进入ventoy后就黑屏了（屏幕是有背光的）

**Comment by opsiff** [comment]
试过黑屏的时候按 键盘的 F7 切换到文本模式么？

**Comment by SakuraMay** [comment]
> 试过黑屏的时候按 键盘的 F7 切换到文本模式么？

刚试了一下，F7按了之后还是黑屏（按的时候屏幕背光没了一下，然后又有背光亮起来）

**Comment by ventoy** [comment]
里面只放1个ISO文件，然后盲按回车键，看看能不能启动进去。
之前遇到过 ARM机器启动之后显示白屏，但实际上菜单是有的，只是显示不出来。

**Comment by SakuraMay** [comment]
> 里面只放1个ISO文件，然后盲按回车键，看看能不能启动进去。 之前遇到过 ARM机器启动之后显示白屏，但实际上菜单是有的，只是显示不出来。

这样做试了一下，进去之后还是黑屏（有背光）

**Comment by opsiff** [comment]
> > 里面只放1个ISO文件，然后盲按回车键，看看能不能启动进去。 之前遇到过 ARM机器启动之后显示白屏，但实际上菜单是有的，只是显示不出来。
> 
> 这样做试了一下，回车2下进去之后还是黑屏（有背光）

能提供一下BIOS固件版本么 可以尝试在显示黑屏的时候多按几次enter试试看，以及可以试试在ventoy黑屏界面按ctrl+u切换到uefi mode是否有帮助。

**Comment by SakuraMay** [comment]
> > > 里面只放1个ISO文件，然后盲按回车键，看看能不能启动进去。 之前遇到过 ARM机器启动之后显示白屏，但实际上菜单是有的，只是显示不出来。
> > 
> > 
> > 这样做试了一下，回车2下进去之后还是黑屏（有背光）
> 
> 能提供一下BIOS固件版本么 可以尝试在显示黑屏的时候多按几次enter试试看，以及可以试试在ventoy黑屏界面按ctrl+u切换到uefi mode是否有帮助。

BIOS版本是百敖1.00，然后试了下你说的盲进镜像后再多按几次ENTER，发现成功进去了装机界面正常显示，我猜想刚进入镜像时候的黑屏界面应该是选择升级还是体验之类的那个选择菜单。另外在ventoy黑屏界面的时候按 CTRL+U并无反应。

**Comment by ventoy** [comment]
通过 VentoyPlugson 工具把它配置为默认文本模式（而不是先启动后再按F7切换） 试试。

**Comment by SakuraMay** [comment]
> 

可以，切换到文本模式之后能正常看到。

**Comment by SakuraMay** [comment]
> 通过 VentoyPlugson 工具把它配置为默认文本模式（而不是先启动后再按F7切换） 试试。

可以，切换到文本模式能正常显示

**Comment by ventoy** [comment]
那就再通过 VentoyPlugson 改成图形模式，然后改分辨率，尝试各种分辨率，看看哪种能正常显示。

**Comment by SakuraMay** [comment]
> 那就再通过 VentoyPlugson 改成图形模式，然后改分辨率，尝试各种分辨率，看看哪种能正常显示。

1920*1080的分辨率测试成功，正常显示（华为售卖配置里搭配的显示器分辨率是1920*1080）。

**Comment by ventoy** [comment]
你把分辨率选项设置为 max 试试。

**Comment by SakuraMay** [comment]
> 你把分辨率选项设置为 max 试试。

MAX不行，无法显示
