### ISSUE TITLE
[Success Image Report]:  Archboot

### ISSUE THREAD

**Issue by tpowa** [ventoy/Ventoy#2502]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.94

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

archboot-2023.07.27-09.50-6.4.6-arch1-1-x86_64.iso

### Image file checksum type

SHA256

### Image file checksum value

521ca67958afaf0c4c852686ba715d2dadc16231034d24cb8ef2c1a2daa1f65b

### Image file download link (if applicable)

https://archboot.com/iso/x86_64/2023.07/archboot-2023.07.27-09.50-6.4.6-arch1-1-x86_64.iso

### Test environment

Acer Chromebook R11

### More Details?

This image file booted successfully in Ventoy.
I release quite often new files and monitor the ventoy support.

**Comment by ventoy** [comment]
Thanks!
