### ISSUE TITLE
[Success Image Report]: windows insider build 23511

### ISSUE THREAD

**Issue by Mackie219** [ventoy/Ventoy#2505]
### Official Website List

- [x] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.94

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

23511.1000.230722-2325.NI_PRERELEASE_CLIENTMULTI_X64FRE_EN-GB.iso

### Image file checksum type

SHA256

### Image file checksum value

832b67b194c6b0e3e3f50f22dc5249199217804defaa7cc4c98eeab65999305b

### Test environment

Dell Latitude E6510 Laptop

### More Details?

This image file booted successfully in Ventoy.
This image installed from Ventoy in normal mode successfully.

**Comment by ventoy** [comment]
THanks!
