### ISSUE TITLE
[Success Image Report]: DragonOS

### ISSUE THREAD

**Issue by FrankMeyvis** [ventoy/Ventoy#2507]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.94

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

DragonOs_FocalX_R30.2.iso

### Image file checksum type

MD5

### Image file checksum value

16ef364d9f518fcda233a4e3b3a855e0

### Image file download link (if applicable)

https://sourceforge.net/projects/dragonos-focal/files/DragonOS_FocalX_R30.2.iso/download?use_mirror=deac-fra&download=&failedmirror=deac-riga.dl.sourceforge.net

### Test environment

Laptop Samsung R519

### More Details?

This image file booted successfully in Ventoy on this 12 y. old laptop.

**Comment by ventoy** [comment]
Thanks!
