### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by JPWhiteHome** [ventoy/Ventoy#2514]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.94

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

gnoppix-23.2-amd64.iso

### Image file checksum type

MD5

### Image file checksum value

734f8faffd029b32fa977c0ea8229e71

### Image file download link (if applicable)

https://www.gnoppix.com/download

### Test environment

Acer Aspire E1-731-4699

### More Details?

This image file booted successfully in Ventoy.

Interesting mix of MacOS and Windows.

Has advanced network intrusion testing and sniffing tools.

**Comment by ventoy** [comment]
Thanks!
