### ISSUE TITLE
[Success Image Report]: Windows Vista 64-bit

### ISSUE THREAD

**Issue by MaxWorlds** [ventoy/Ventoy#2525]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.94

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

ru_windows_vista_with_sp2_x64_dvd_x15-36364.iso

### Image file checksum type

MD5

### Image file checksum value

AAFA79902DA7275E580369DA4E0C433B

### Image file download link (if applicable)

https://archive.org/details/Windows_Vista_with_Service_Pack_2_-_DVD_Russian

### Test environment

ASUS K750JB

### More Details?

I'm started a russian 64-bit Windows Vista with Ventoy in BIOS and UEFI modes on my ASUS K750JB laptop.

**Comment by ventoy** [comment]
Thanks!

**Comment by MaxWorlds** [comment]
please
