### ISSUE TITLE
[Success Image Report]: Rhino Linux 2023.1

### ISSUE THREAD

**Issue by Flan-Fan** [ventoy/Ventoy#2531]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.94

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

Rhino-Linux-2023.1-amd64.iso

### Image file checksum type

SHA256

### Image file checksum value

ae024c90aaa803e7bde38f339ce9681b0b4a54888120cae7e5cb544ae68ded0b

### Image file download link (if applicable)

https://dl.rhinolinux.org/releases/2023.1/Rhino-Linux-2023.1-amd64.iso

### Test environment

Fujitsu Esprimo E400 E85+ (4GB RAM, i3-2120 @ 3.30GHZ, Integrated Graphics)

### More Details?

This image file booted successfully in Ventoy.
I manually typed out the SHA256 checksum because I calculated it in Ventoy itself so there's a small chance there might be a character or two wrong (I did double check and it all seems ok though)

**Comment by ventoy** [comment]
Thanks!
