### ISSUE TITLE
[issue]: Partition Style switch with update

### ISSUE THREAD

**Issue by mralemao** [ventoy/Ventoy#2534]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.94

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

32GB

### Image file checksum (if applicable)

None

### What happened?

Allow to change partition style without losing saved ISOs, using Update command.

**Comment by ventoy** [comment]
The Ventoy partition style can not be updated with data losing.
