### ISSUE TITLE
[Success Image Report]: PikaOS

### ISSUE THREAD

**Issue by ToasterUwU** [ventoy/Ventoy#2537]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.95

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

PikaOS-KDE-2304-amd64-23.07.16.iso

### Image file checksum type

MD5

### Image file checksum value

cb9e7f25b076c7ecb8b4f80e5a41c8f9

### Image file download link (if applicable)

https://cdn.pika-os.com/PikaOS-KDE-2304-amd64-23.07.16.iso

### Test environment

All kinds of Laptops and PCs

### More Details?

Official Member of the PikaOS Admins here, we have been recommending people to use Ventoy for all versions of PikaOS from the very beginning. It has been tested by dozens of people, on dozens of different PCs and Laptops. Meaning Gnome, KDE, Hyprland, new and old, with Nvidia drivers or without. All the same, it worked perfectly.

Im a big fan of Ventoy, and I just noticed PikaOS isn't yet in the list, so I thought I might as well.

Official Website: https://pika-os.com/

**Comment by ventoy** [comment]
Thanks!

**Comment by Khaos1221** [comment]
Hey @ventoy  not working anymore with them shifiting to debian SID

**Comment by ToasterUwU** [comment]
> Hey its not working anymore with them shifiting to debian SID
> Maybe i should make a new issue?
> 

Try to report this to the Pika team first, maybe it's a simple fix

**Comment by allaze-eroler** [comment]
We also need to verify if pikaos can be used as persistent usb drive instead of immutable usb drive. And honestly, i had no idea which persistence configuration i should use...
