### ISSUE TITLE
[issue]: Version 1.0.95 not showing in releases (appears to be GitHub bug)

### ISSUE THREAD

**Issue by asheroto** [ventoy/Ventoy#2539]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.95

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

0

### Image file checksum (if applicable)

None

### What happened?

Version 1.0.95 is on the Releases page under "Tags", but not under "Releases". Generally that means the author removed/retracted/unpublished the release. But since it's still available for download on tags, and still on ventoy.net as version 1.0.95, I just wanted to check and see if maybe this was a mistake or if there was a bug with 1.0.95 and it had to be removed on purpose?

v1.0.95 Available:
https://github.com/ventoy/Ventoy/releases/tag/v1.0.95

v1.0.95 Not available:
https://github.com/ventoy/Ventoy/releases/

**Comment by ventoy** [comment]
![image](https://github.com/ventoy/Ventoy/assets/59477474/84103797-0231-4c05-89e6-cecce65b4fd7)

**Comment by asheroto** [comment]
I will contact GitHub support as it appears there may be a glitch.

Mobile version...

![Screenshot_2023-08-23-09-37-36-18_e4424258c8b8649f6e67d283a50a2cbc (Custom)](https://github.com/ventoy/Ventoy/assets/49938263/2ac60194-0feb-48b3-bfe2-83e204648d3c)

**Comment by Aerospherology** [comment]
There are a few trojan detections for the Windows ZIP, maybe that's what's causing it. 3 detections right now including Microsoft.
[https://www.virustotal.com/gui/file/73eb20d1c17b068f0d6315304affc5cbf7102de8699fc4e0b620abb3ebbc0d4c](url)

**Comment by asheroto** [comment]
I submitted a ticket to GitHub support reporting the bug. Even with caching turned off through devtools it doesn't show 1.0.95. Mobile browser shows the same. Different web browser shows the same. I also remoted-in to a computer I have in Dallas and it shows the same. But since the developer sees 1.0.95 there must be a site bug with GitHub.

**Comment by Perkolator** [comment]
Same problem here. Never seen this in github before.

**Comment by asheroto** [comment]
I heard back from GitHub support and they said this...

```
I've reindexed ventoy/Ventoy/releases and the latest version is now displaying on the releases page. Thanks for flagging this, sometimes the pages can get a little out of sync :)
```

Closing ticket.
