### ISSUE TITLE
[issue]: Trojan detected by Windows Defender in 1.0.95

### ISSUE THREAD

**Issue by dcanl** [ventoy/Ventoy#2540]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.95

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

64GB

### Disk Manufacturer

LEXAR

### Image file checksum (if applicable)

Yes.

### What happened?

Windows Defender detects Trojan:Win32/Wacatac.B!ml when running Ventoy2Disk.exe in v.1.0.95

![image](https://github.com/ventoy/Ventoy/assets/7107676/8401363f-654b-444c-9ff9-edb3d9448c17)

**Comment by asheroto** [comment]
It's a false positive. Two other vendors are flagging it as well, out of 71.

https://www.virustotal.com/gui/file/d0fbb98b3de71b571276016743d1a2b56fc71b8708455a533a7489fdb64e63de

**Comment by ventoy** [comment]
Yes, it's false positive.
Once I update Ventoy2Disk.exe it will get false positive.
Ventoy2Disk.exe has kept with no update for a few releases before 1.0.95.

**Comment by asheroto** [comment]
| File                                                                 | Detected By                     | VirusTotal URL                                                                                                                                  |
|----------------------------------------------------------------------|---------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------|
| [ventoy-1.0.95-windows.zip](https://www.virustotal.com/gui/file/73eb20d1c17b068f0d6315304affc5cbf7102de8699fc4e0b620abb3ebbc0d4c)    | Antiy-AVL, MaxSecure            | [URL](https://www.virustotal.com/gui/file/73eb20d1c17b068f0d6315304affc5cbf7102de8699fc4e0b620abb3ebbc0d4c) |
| [Ventoy2Disk.exe](https://www.virustotal.com/gui/file/d0fbb98b3de71b571276016743d1a2b56fc71b8708455a533a7489fdb64e63de)              | Bkav Pro, Secure Age            | [URL](https://www.virustotal.com/gui/file/d0fbb98b3de71b571276016743d1a2b56fc71b8708455a533a7489fdb64e63de) |
| [VentoyPlugson.exe](https://www.virustotal.com/gui/file/a27bef270abb8e0649358d89a004573b45156c7a2bb520fb62cfe1f50300145b)            | Antiy-AVL, Bkav Pro, SecureAge, MaxSecure | [URL](https://www.virustotal.com/gui/file-analysis/MzhmMThlYmI1YjgxYjQ0ODFiNzMyZjY4ZDJiOWZlOTA6MTY5MjgwMzUyNA==) |
| [VentoyVlnk.exe](https://www.virustotal.com/gui/file/fcfaa10af53eebef4a986b002006a7acf7af9c2465caed7e37edab9626bcfc4d)               | Bkav Pro, MaxSecure, SecureAge  | [URL](https://www.virustotal.com/gui/file/fcfaa10af53eebef4a986b002006a7acf7af9c2465caed7e37edab9626bcfc4d) |

I have submitted a false positive reports to all of the above anti-virus vendors.

**Comment by asheroto** [comment]
@dcanl Microsoft replied and said they have removed the detection from their database.

From Microsoft...
---
At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed. Please follow the steps below to clear cached detections and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"
---

**Comment by asheroto** [comment]
Only 3 detections remain. @dcanl you can close this when ready. 😊

**Comment by dcanl** [comment]
Thank you, I will update my ventoy usb key soon! 😊
