### ISSUE TITLE
[Success Image Report]: Rhino Linux 2023.2

### ISSUE THREAD

**Issue by Flan-Fan** [ventoy/Ventoy#2546]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.94

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

Rhino-Linux-2023.2-amd64.iso

### Image file checksum type

SHA256

### Image file checksum value

07e0c3618685ef60ad3f915ce2dfc37da965a7fe65399459c6625c1a71ef7e04

### Image file download link (if applicable)

https://dl.rhinolinux.org/releases/2023.2/Rhino-Linux-2023.2-amd64.iso

### Test environment

Fujitsu Esprimo E400 E85+ (4GB RAM, i3-2120 @ 3.30GHZ, Integrated Graphics)

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
