### ISSUE TITLE
[Success Image Report]: crystal-live-2023-07-13-x86_64

### ISSUE THREAD

**Issue by misjah** [ventoy/Ventoy#2548]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.91

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

crystal-live-2023-07-13-x86_64.iso

### Image file checksum type

SHA256

### Image file checksum value

d2b53b682b2571df6b4fb5833a7663eb4c592f573a7eba00feed16189d6d7280

### Image file download link (if applicable)

https://git.getcryst.al/crystal/misc/iso/-/jobs/286/artifacts/raw/iso/crystal-live-2023-07-13-x86_64.iso

### Test environment

Desktop: Asus a320-mk, 16GB ram, GTX1650, USB 2.0 port, 4GB transcend flash drive. 

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
