### ISSUE TITLE
[issue]: VTOY_LINUX_REMOUNT=1 does not work on openSUSE 15.4/15.5/Tumbleweed

### ISSUE THREAD

**Issue by efati** [ventoy/Ventoy#2551]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.95

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://download.opensuse.org/distribution/leap/15.5/iso/openSUSE-Leap-15.5-DVD-x86_64-Build491.1-Media.iso

### What happened?

While mounting the first partition on the pendrive, I got:
`# mount /dev/sdb1 /mnt`
`mount.bin: /mnt: /dev/sdb1 already mounted or mount point busy`
Global option `VTOY_LINUX_REMOUNT` has been activated, because I managed to boot from the same pendrive Ubuntu 22.04 and mount the same partition.
The same errors appears in openSuSE 15.5, 15.4, 15.3, and Tumbleweed.

**Comment by ventoy** [comment]
Try 1.0.96

**Comment by efati** [comment]
I am happy to report that it works! Both on BIOS systems and on UEFI systems.
Many thanks!

**Comment by minamorcose** [comment]
hello 
it's not working on ventoy  1.0.98 for leap
i tried both on UEFI and MBR|CSM
| Name | Hash (sha256) |state|
|--------|--------|--------|
| openSUSE-Leap-15.5-XFCE-Live-x86_64-Build13.195-Media.iso  | d303b2f6368d8674e07f62cc6c49312958839415b8c706d9500d8e4d9d36351b | NO |
| debian-live-12.1.0-amd64-cinnamon.iso | 9e1daaf6fc3fb237815e3cde436a99fc41c96a17e6d0bb88cd7f4210f98a7abb | Yes|

may be there is a regression 
if  you can confirm it @efati

**Comment by ventoy** [comment]
@minamorcose 
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/9234717389
https://www.ventoy.net/en/doc_github_ci.html

**Comment by minamorcose** [comment]
@ventoy 
it worked on MBR and UEFI 
thank you for your great program i would love to donate to you if i didn't have some economical issues i appreciate   your work
