### ISSUE TITLE
1.0.14 installer doesn't update

### ISSUE THREAD

**Issue by CRCinAU** [ventoy/Ventoy#256]
Trying to upgrade from 1.0.13 -> 1.0.14 - as root:
```
./Ventoy2Disk.sh -u /dev/sdb

***********************************************************
*                Ventoy2Disk Script                       *
*             longpanda  admin@ventoy.net                 *
***********************************************************

Upgrade operation is safe, all the data in the 1st partition (iso files and other) will be unchanged!

Update Ventoy  1.0.13 ===> 1.0.14   Continue? (y/n)y
cat: /sys/class/block/sdb2/start: No such file or directory
dd: invalid number: ‘’
mv: cannot stat './tmp_mnt/EFI/BOOT/grubx64_real.efi': No such file or directory

Update Ventoy to /dev/sdb successfully finished.

```

Running the update again still shows 1.0.13 installed.

**Comment by CRCinAU** [comment]
Ah - silly me - Gnome auto-mounted the USB drive which caused problems... 

Ran a umount manually, then the upgrade worked...

**Comment by ouuan** [comment]
It happens to me even the USB drive is not mounted.

**Comment by ouuan** [comment]
I wanted to echo some debug information, so I added `cat /sys/class/block/sdc2/start` before this line:

https://github.com/ventoy/Ventoy/blob/1cbe4c81b4978311696ab4e9e8dffb7d98b82570/INSTALL/tool/VentoyWorker.sh#L311

And to my surprise, after adding this line, the error message contains only a single "cat: /sys/class/block/sdc2/start: No such file or directory", and the update succeeded.

**Comment by ventoy** [comment]
I have updated  INSTALL/tool/VentoyWorker.sh 
You can get it and override the script in tool directory after you decompress the install package.

**Comment by ouuan** [comment]
> I have updated INSTALL/tool/VentoyWorker.sh
> You can get it and override the script in tool directory after you decompress the install package.

e91b315 does fix the problem, but I'm curious about why it fixes the problem, because I can run this script without any problem:

```sh
#!/bin/sh
  
PART2=/dev/sdc2
part2_start=$(cat /sys/class/block/${PART2#/dev/}/start)
echo $part2_start
```

**Comment by CRCinAU** [comment]
Ah - yeah - a reinstall works after the patch:
```
./Ventoy2Disk.sh -u /dev/sdb

***********************************************************
*                Ventoy2Disk Script                       *
*             longpanda  admin@ventoy.net                 *
***********************************************************

Upgrade operation is safe, all the data in the 1st partition (iso files and other) will be unchanged!

Update Ventoy  1.0.14 ===> 1.0.14   Continue? (y/n)y

Update Ventoy to /dev/sdb successfully finished.
```

**Comment by ouuan** [comment]
BTW, I don't think it's a good idea to change the content of a version. You should release 1.0.15 even if it's a small fix. The patch version (the third number in the version number) is exactly for small changes.

**Comment by ouuan** [comment]
The checksum check failed when I was updating the AUR package because of the cached `ventoy-1.0.14-linux.tar.gz`. I have to clean the cache and install again.

**Comment by ventoy** [comment]
Yes, you are right. I will be careful in the future release.  Ventoy-1.0.15 is coming soon.

**Comment by blackcrack** [comment]
curios, i have no troubles, here works it nice.. as WinNT Binary..
maybe be it different Distributions, different older or newer library's what's need..
so can it be to be the library's be over aged in Linux ..  
so could it maybe helpful if you day you're version's of Distributions
Manny Distributions could it to be the one r the other not really supported because the decencies of versions ..
best regards
Blacky
