### ISSUE TITLE
[Success Image Report]: Tails

### ISSUE THREAD

**Issue by HPOA909** [ventoy/Ventoy#2564]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.95

### BIOS Mode

Both

### Partition Style

GPT

### Image file name

Tails-amd64-5.17.iso

### Image file checksum type

SHA512

### Image file checksum value

125a5f9f87dffc13ee0a6b977292b9ece436eef76d5eb7be03eba0e5e2e55958bbbdc98c748c1ce219270b253ada0dee8de3edf1df0a2743bbdfc65e489270ec

### Image file download link (if applicable)

https://download.tails.net/tails/stable/tails-amd64-5.17/tails-amd64-5.17.iso

### Test environment

Lenovo ThinkPad T480s

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!

**Comment by Omio-Kun-69** [comment]
What was the persistent file that u used?
