### ISSUE TITLE
[Success Image Report]: Kali Linux

### ISSUE THREAD

**Issue by HPOA909** [ventoy/Ventoy#2565]
### Official Website List

- [x] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.95

### BIOS Mode

Both

### Partition Style

GPT

### Image file name

kali-linux-2023.3.live-amd64.iso

### Image file checksum type

SHA256

### Image file checksum value

7755f44318e6183d8411128b8a56c2982dbf0dd4c62870f4e5ca28c6df73fd9a

### Image file download link (if applicable)

https://cdimage.kali.org/kali-2023.3/kali-linux-2023.3-live-amd64.iso

### Test environment

Lenovo ThinkPad T480s

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
