### ISSUE TITLE
[Success Image Report]: Fedora 39 Prerelease

### ISSUE THREAD

**Issue by mark94849** [ventoy/Ventoy#2568]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.57

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

Fedora-Workstation-Live-x86_64-Rawhide-20230916.n.0.iso 

### Image file checksum type

SHA256

### Image file checksum value

78266467f504f850431d2ea8e5dbef812b75d621ba44e9749b61481b225a4301

### Image file download link (if applicable)

https://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-Rawhide-20230916.n.0.iso

### Test environment

Acer Swift 1 SF114-32

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
