### ISSUE TITLE
[Success Image Report]: Tiny 11 23H2

### ISSUE THREAD

**Issue by NickMihal** [ventoy/Ventoy#2569]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.95

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

tiny11 23H2 x64.iso

### Image file checksum type

SHA256

### Image file checksum value

F260E50BF9AFAFD8F972A729402A557AADCD3A227918FC566CF42D48AA723A85

### Image file download link (if applicable)

https://archive.org/details/tiny11-23h2

### Test environment

HP EliteDesk 800 G2 SFF

### More Details?

This image file booted successfully in Ventoy.

**Comment by NickMihal** [comment]
Yes, the Tiny 11 23H2 Image file has been taken down, i'm closing the report.

**Comment by grandpa1946** [comment]
> item is no longer available

magnet:?xt=urn:btih:83c0db1959fd4413622595188d2f7a315ca2a762&dn=tiny11-23h2&tr=http%3A%2F%2Fbt1.archive.org%3A6969%2Fannounce&tr=http%3A%2F%2Fbt2.archive.org%3A6969%2Fannounce&ws=http://ia600509.us.archive.org/27/items/&ws=http://ia800509.us.archive.org/27/items/&ws=https://archive.org/download/
