### ISSUE TITLE
[Success Image Report]: ubuntu-20.04.6-desktop-amd64.iso

### ISSUE THREAD

**Issue by aalpguzel** [ventoy/Ventoy#2570]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.95

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

ubuntu-20.04.6-desktop-amd64.iso

### Image file checksum type

SHA256

### Image file checksum value

510ce77afcb9537f198bc7daa0e5b503b6e67aaed68146943c231baeaab94df1

### Test environment

Lenovo Legion Y530

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
