### ISSUE TITLE
[Success Image Report]: Windows11_InsiderPreview_Client_x64_en-us_22621.iso

### ISSUE THREAD

**Issue by aalpguzel** [ventoy/Ventoy#2571]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.95

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

Windows11_InsiderPreview_Client_x64_en-us_22621.iso

### Image file checksum type

SHA256

### Image file checksum value

c0e6e8d4d5a8a37d3fa85d719da8773432b73a4f92ba1779e74a5f984d709058

### Test environment

Lenovo Legion Y530

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
