### ISSUE TITLE
[Success Image Report]: archlinux-2023.09.01-x86_64.iso

### ISSUE THREAD

**Issue by auryark** [ventoy/Ventoy#2573]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.95

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

archlinux-2023.09.01-x86_64.iso

### Image file checksum type

SHA256

### Image file checksum value

0d71c9bc56af75c07e89cd41eaa5570ac914677ad6bc8e84935dc720ce58f960

### Image file download link (if applicable)

magnet:?xt=urn:btih:ab6ad7ff24b5ed3a61352a1f1a7811a8c3cc6dde&dn=archlinux-2023.09.01-x86_64.iso

### Test environment

ASUS All Series

### More Details?

This image file booted successfully in Ventoy.

**Comment by Fexonchik5120** [comment]
I want to add, UEFI mode also working on non UEFI computer (lenovo IdeaPad y570)

**Comment by ventoy** [comment]
Thanks!
