### ISSUE TITLE
[Success Image Report]: ru-ru_windows_10_consumer_editions_version_22h2_x64_dvd_86fd5014.iso

### ISSUE THREAD

**Issue by Fexonchik5120** [ventoy/Ventoy#2577]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.95

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

ru-ru_windows_10_consumer_editions_version_22h2_x64_dvd_86fd5014.iso

### Image file checksum type

SHA256

### Image file checksum value

	da678e01bd85c561c45a0c2a92c0b6730b610c2d6fc6683345355f9f21e0eb72

### Test environment

Lenovo IdeaPad Y570

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
