### ISSUE TITLE
[Success Image Report]: archlinux-2023.09.01-x86_64.iso

### ISSUE THREAD

**Issue by Fexonchik5120** [ventoy/Ventoy#2578]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.95

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

archlinux-2023.09.01-x86_64.iso

### Image file checksum type

SHA256

### Image file checksum value

0d71c9bc56af75c07e89cd41eaa5570ac914677ad6bc8e84935dc720ce58f960

### Image file download link (if applicable)

https://geo.mirror.pkgbuild.com/iso/2023.09.01/archlinux-2023.09.01-x86_64.iso

### Test environment

Lenovo IdeaPad Y570

### More Details?

This image file booted successfully in Ventoy. Also booted in UEFI mode, but computer doesn't support UEFI.

**Comment by ventoy** [comment]
Thanks!
