### ISSUE TITLE
[Success Image Report]: Ubuntu Budgie 23.04

### ISSUE THREAD

**Issue by eThaffu** [ventoy/Ventoy#2579]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.95

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

ubuntu-budgie-23.04-desktop-amd64.iso

### Image file checksum type

SHA256

### Image file checksum value

 d587c8eaf961ccdff7b90adac965a26a12f1f0a9abe7f51401b277ffe5f76db7

### Image file download link (if applicable)

https://cdimage.ubuntu.com/ubuntu-budgie/releases/23.04/release/ubuntu-budgie-23.04-desktop-amd64.iso

### Test environment

Acer Nitro AN515-45 [AMD 5 5600H/RTX 3070Laptop]

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
