### ISSUE TITLE
GUI flash drive refresh

### ISSUE THREAD

**Issue by kmm2** [ventoy/Ventoy#258]
I have a bunch of flash drives formatted with Ventoy and need to update them all after new Ventoy release.
To do so I need to run/close/re-run the Ventoy app in order to see a newly inserted USB device.
Can you add a GUI USB 'refresh' option to simplify the process?

**Comment by ventoy** [comment]
Emm, it's indeed a little inconvenience. I will add a refresh button in the future release.

**Comment by kmm2** [comment]
I love this project.
Thank you in advance!

**Comment by kmm2** [comment]
Perfect!
Closing the issue.
