### ISSUE TITLE
[Success Image Report]: chromeos_15393.58.0_reven_recovery_stable-channel_mp-v2.img

### ISSUE THREAD

**Issue by noigamegun** [ventoy/Ventoy#2583]
### Official Website List

- [x] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.95

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

chromeos_15393.58.0_reven_recovery_stable-channel_mp-v2.img

### Image file checksum type

SHA256

### Image file checksum value

83D2063E03905AA7078A1CCD7E0BF6E2492B9A51AD6A0D608579C64322E7FCFB

### Image file download link (if applicable)

https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_15393.58.0_reven_recovery_stable-channel_mp-v2.bin.zip?sjid=1259366640281510207-AP

### Test environment

MSI GF65 Thin 10UE

### More Details?

This image file booted successfully in Ventoy.

(Replaced *.bin with *.img)

**Comment by noigamegun** [comment]
@ventoy Any Updates?

**Comment by ventoy** [comment]
Thanks!
