### ISSUE TITLE
[issue]: Ventoy 1.0.95 Windows release not working

### ISSUE THREAD

**Issue by BlackfishStudios** [ventoy/Ventoy#2587]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.95

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

64G

### Image file checksum (if applicable)

Yes.

### What happened?

The 1.0.95 release for windows is not formatted properly. It's simply a zip of the current repo, as opposed to the actual release version. The installers in the install directory won't let you install as they aren't in the right location. The 1.0.94 release works no problems, and they have a vastly different structure. 

![image](https://github.com/ventoy/Ventoy/assets/65311324/a8d54cd3-d161-4410-b1b4-7655cbf8eca0)

**Comment by ventoy** [comment]
You downloaded the source code tarball, not the release package.
So please download Ventoy 1.0.95 from  https://sourceforge.net/projects/ventoy/files/v1.0.95/
(I have deleted the source code tarball which may cause misunderstanding)
