### ISSUE TITLE
[issue]: Ventoy doesn't load any images [5/5]

### ISSUE THREAD

**Issue by Brensom** [ventoy/Ventoy#2592]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.95

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

16

### Disk Manufacturer

090c:1000 Silicon Motion, Inc. - Taiwan (formerly Feiya Technology Corp.) Flash Drive

### Image file checksum (if applicable)

Yes.

### What happened?

Ventoy does not load any of the five randomly selected images.
I don't even know what to say here. The program simply doesn't work. Maybe I'm doing something wrong? But I didn't find any settings that could change this.

<a href="https://ibb.co/SVrrQL0"><img src="https://i.ibb.co/SVrrQL0/P-20231002-101014.jpg" alt="P-20231002-101014" border="0"></a> <a href="https://ibb.co/cczWk2k"><img src="https://i.ibb.co/cczWk2k/P-20231002-101253.jpg" alt="P-20231002-101253" border="0"></a> <a href="https://ibb.co/GMJ0ky2"><img src="https://i.ibb.co/GMJ0ky2/P-20231002-101624.jpg" alt="P-20231002-101624" border="0"></a> <a href="https://ibb.co/x5PLBQH"><img src="https://i.ibb.co/x5PLBQH/P-20231002-101809.jpg" alt="P-20231002-101809" border="0"></a> <a href="https://ibb.co/M9SvV9Y"><img src="https://i.ibb.co/M9SvV9Y/P-20231002-105101.jpg" alt="P-20231002-105101" border="0"></a>

**Comment by steve6375** [comment]
What do you mean by 'image' exactly?
What actual files are you trying to boot to and what was the source and how were they made?

**Comment by Brensom** [comment]
> What do you mean by 'image' exactly? What actual files are you trying to boot to and what was the source and how were they made?
Look, I tested over 30 images and none of them worked.
I didn't remember their names and I'm not going to look for them. I’m just surprised why it says on your website that 1000+ images are supported, but I haven’t downloaded any of the more than 30 images.
I saved 5 screenshots just to prove my words. I have already deleted Ventoy and all the images that I tested. Now I use another tool for recording images. I just want other people to know that there are no 1000+ working images here.

**Comment by steve6375** [comment]
Ventoy is used by millions of people and you can see it works by simply looking at all the YouTube video made by hundreds of other people. If you cannot give one single example of a bootable file then we can't help you.
P.S. I am not the author of Ventoy, I am just asking you for details because Ventoy works well for most bootable files, e.g. .ISO files but of course not all. Also there are some workarounds for some specific ISOs.

**Comment by Brensom** [comment]
I don't know why you deceive people. All the videos I saw on YouTube about Ventoy were tested in VirtualBox, and not on real hardware.

**Comment by steve6375** [comment]
VBox is used just because it is easier to record to a video than using a real system. It still works on a real system.
Thousands of techs, schools, universities, repair shops, businesses, etc, use Ventoy on real systems everyday.
Typically to install WIndows or Linux onto a real system.

**Comment by Brensom** [comment]
Let's argue with you. I will download the image that is marked as “working” on your website and if it does not work on my PC, will you transfer me $1000? Is it coming?

**Comment by steve6375** [comment]
I am not asking you to make videos. I am simply asking you the exact name of ONE FILE that you would expect to work.
Tails ISOs are rather odd and may not work, try a simple one like Ubuntu or Microsoft Windows 10 ISOs first (although most others should work).

**Comment by Brensom** [comment]
Ok. It was:
alpine-standard-3.18.0-x86_64.iso
archlinux-2023.09.01-x86_64.iso
Endeavouros_Cassini_Nova-03-2023_R3.iso
kali-linux-2023.1-live-amd64.iso
tails-amd64-5.12.img

**Comment by steve6375** [comment]
OK, I just downloaded archlinux-2023.09.01-x86_64.iso
and booted it OK using UEFI boot on my Asus Z97 Intel i5 PC.
Also works on VBox.
As I expected, of course.
So there is no problem at my end.
Now you may have a fake/faulty USB drive or you may be booting on a different x86 computer of course.
You indicated you are UEFI booting in your original post, so you should have seen UEFI displayed on the menu.

![CaptureARchV](https://github.com/ventoy/Ventoy/assets/1469350/a6cdf83f-0334-406e-aa3b-4966aa3e37af)

I then chose the Normal boot option and it booted.


![CapturerARCHCV2](https://github.com/ventoy/Ventoy/assets/1469350/dafebeab-16c0-4716-b347-5a58f99478d7)

![CaptureARCHV3](https://github.com/ventoy/Ventoy/assets/1469350/ab1d3484-c397-4b61-a00e-a11508fa49da)

**Comment by steve6375** [comment]
You can check for file corruption simply be highlighting the ISO file in the Ventoy menu system and pressing the m key
![image](https://github.com/ventoy/Ventoy/assets/1469350/3826179e-76aa-4e69-9c66-313b96b5c57a)
It should look like this
