### ISSUE TITLE
Request: Ability for Persistant storage for Linux ISOs

### ISSUE THREAD

**Issue by carverhaines** [ventoy/Ventoy#26]
Would be great if we could have persistant storage for linux ISOs... Maybe creating an empty folder the same name as the ISO for it to see/use would be easiest?

**Comment by vickyorlo** [comment]
Seconding this, it would make Ventoy the prime multiboot solution right now. I think it'd be fine even if this feature had a far more limited ISO whitelist than the current supported ISOs list, like just Ubuntu flavors or something.

**Comment by ventoy** [comment]
I'm testing a new feature about persistence, and It's almost done.

You can specify a simple img file as the persistence backend for one iso file. The img file is put in the 1st partition along with the iso files.

You can specify different img files to different iso files at a time or share one img file between some iso files.

**Comment by ventoy** [comment]
Please take a look at Ventoy-1.0.11 with persistence support.

**Comment by dennisvanderpool** [comment]
Hey,

Is it possible the create the image file under windows or is there a way to run it inside the live distro?
I've tried to mount the host usb to be able to copy the image file over to it, but that didn't work as it seemed /dev/sdb2/ventoy was already mounted as type "dm".

I will now try it under another linux desktop PC i have, but would be great to be able to do it from inside a live running linux distro :)

Thanks a lot!

Dennis

**Comment by ventoy** [comment]
Hi,
Once you get an image file, it can be saved as a template in your computer, so you don't need to create it all the time.
So I think it should not be a very big problem. Although it indeed has a little inconvenience.

**Comment by carverhaines** [comment]
Any documentation? How does one create the image file?

**Comment by dennisvanderpool** [comment]
Hi,

I tried a lot but i couldn't get it to work. Any hints? :-)
![image](https://user-images.githubusercontent.com/24899089/82814838-38992680-9e98-11ea-92ba-321bcb31786c.png)
![image](https://user-images.githubusercontent.com/24899089/82814857-3fc03480-9e98-11ea-8699-5ae20f116834.png)

Dennis

**Comment by ventoy** [comment]
@dennisvanderpool 
Hi,

You must create a **ventoy** directory and put ventoy.json in the ventoy directory.

**Comment by dennisvanderpool** [comment]
Hey,

Thanks! That seems to work. As i've got a 256GB stick, is it possible to have a dual boot between ventoy and another OS?

I would like to have Ubuntu booting & running directly on the stick (no livecd with persistance) and also the possibility to boot ventoy?

Maybe also update the documentation so it's more clear how the folder structure works?
A screenshot or directory listing besides the sample ventoy.json might be helpful.
![image](https://user-images.githubusercontent.com/24899089/82829570-dc440000-9eb3-11ea-9cc7-117daa077fc5.png)

Thanks,

Dennis

**Comment by dennisvanderpool** [comment]
Hey,

You did a great job, it works. Imo you can close this one! :)

Dennis

**Comment by ventoy** [comment]
Persistence is supported since Vntoy-1.0.11, so I close this issue.

**Comment by PranavBhattarai** [comment]
The ability to have persistent storage is not straightforward for noob users. I love how Ventoy has matured over time, but it would be really cool to have a GUI option for persistent storage similar to how [Rufus](https://rufus.ie/en/) offers. It's really straightforward option in Rufus. And very easy to use. I think we should have something like that in VentoyGUI script.

![Screenshot from 2022-02-08 10-42-29](https://user-images.githubusercontent.com/32763112/152921012-56495cd6-beb9-4b00-8c79-378a11e7d6e5.png)

What do you think? @ventoy

**Comment by ventoy** [comment]
> The ability to have persistent storage is not straightforward for noob users. I love how Ventoy has matured over time, but it would be really cool to have a GUI option for persistent storage similar to how [Rufus](https://rufus.ie/en/) offers. It's really straightforward option in Rufus. And very easy to use. I think we should have something like that in VentoyGUI script. We already have nice options for other things, why not another named "Persistent Storage"?
> 
> ![Screenshot from 2022-02-08 11-02-42](https://user-images.githubusercontent.com/32763112/152923050-f4e27aa4-ac87-4fc9-a407-e196c0b93c08.png)
> 
> What do you think? @ventoy

Ventoy use a different and more flexible mechanism to support persistence.
The Rufus GUI option is used to create a new partition of the USB for persistence.
Ventoy only need to put a file in the USB for persistence.

Persistence is distro specific, different linux distros use different persistence implement. There is no common method.
Rufus is only for one ISO file, so when you select an ISO file, it can known which type of distro is in the ISO file and does it 
support persistence or not, which method it used to implement persistence ...... 
So if you select an ISO file with persistence support, then Rufus will provide an option for you to set persistence partition size, if you select an for example Windows ISO file, then the option will not shown.
But Ventoy GUI is only used to install/update Ventoy and all the options in the GUI are common options. They don't depend on the ISO files in the USB.

**Comment by steve6375** [comment]
Feature could be added to Plugson maybe? Select ISO file on USb drive to add - look at name to recognise distro and thus know required type of persistence type (or allow user to choose type) - set persistence file size 0-4gb, download persistent image zip file - extract and name the new persistence file and write entry in ventoy.json file.
