### ISSUE TITLE
关于1.0.14版本保留分区如何在windows上使用？

### ISSUE THREAD

**Issue by yinch3ng** [ventoy/Ventoy#260]
作者您好，

感谢您开发出这么NB好用的软件，给大家带来了便利！ :thumbsup:

特此请教个问题，windows系统上如何使用生成的保留分区？windows自带的diskpart无法创建分区，总是有这个报错信息（The operation is not supported on a non-empty removable disk） 我尝试过用diskgenius，可以分区，但是在系统上也无法访问，也会报错。

linux下分区格式化均成功，感谢回复！

**Comment by ventoy** [comment]
我没注意到Windows上有此限制。你Linux下新建好分区，插回Windows能正常使用识别使用吗？

**Comment by ventoy** [comment]
我的系统是Windows 10 1903。我自己测试保留的空间是能正常分区和格式化的。

**Comment by yinch3ng** [comment]
> 
> 
> 我没注意到Windows上有此限制。你Linux下新建好分区，插回Windows能正常使用识别使用吗？

windows磁盘管理器里能看到分区，但是无法分配盘符或者打开，右击该分区点格式化或者分配盘符均会报错。。我暂时不能翻墙 原谅我无法截图。。
我系统是windows8.1  台式机和笔记本win8.1都是报错。。。不知道有没有网友可以顺带测试下。。

**Comment by yinch3ng** [comment]
https://ftp.bmp.ovh/imgs/2020/06/d596eb55a99dc419.jpg

这是在我win8.1系统上默认制作完毕后无法操作的截图。如果强行用diskpart命令行操作 会出现

> DISKPART> create part primary
> Virtual Disk Service error:
> The operation is not supported on a non-empty removable disk.

因为暂时无法翻墙，所以无法搜索更多关于这个报错的有效的信息

**Comment by ventoy** [comment]
这个我猜应该是Windows版本的限制。
直到最新的Windows10版本，U盘上所有的分区才都可以显示并分配盘符使用。
在此之前的Windows版本，对于U盘，只有第一个分区是可以分配盘符的。

**Comment by yinch3ng** [comment]
> 
> 
> 这个我猜应该是Windows版本的限制。
> 直到最新的Windows10版本，U盘上所有的分区才都可以显示并分配盘符使用。
> 在此之前的Windows版本，对于U盘，只有第一个分区是可以分配盘符的。

有可能。。主要我想实现一种场景需求。比如在linux live cd下拷贝了对应的资料放置在保留分区中，然后windows老版本下也能跨平台读取，这个对于我来说就很方便了。。我再想想有啥其他不依赖第三方软件的曲线救国的方法

感谢您的回复！

**Comment by yinch3ng** [comment]
> 这个我猜应该是Windows版本的限制。
> 直到最新的Windows10版本，U盘上所有的分区才都可以显示并分配盘符使用。
> 在此之前的Windows版本，对于U盘，只有第一个分区是可以分配盘符的。

https://ftp.bmp.ovh/imgs/2020/06/23f0e38c50059c89.jpg

我刚才尝试了一下只用windows磁盘管理功能去分区，好像是可以了。。。分区完之后也能分配盘符。。。很奇怪。。。

**Comment by yinch3ng** [comment]
> 这个我猜应该是Windows版本的限制。
> 直到最新的Windows10版本，U盘上所有的分区才都可以显示并分配盘符使用。
> 在此之前的Windows版本，对于U盘，只有第一个分区是可以分配盘符的。

正如作者所说 在网上搜索了发现确实可能是老版本windows usb设备类型的分区限制。。。
目前找到的方法就是要么搞一个usb移动硬盘装ventoy，要么就继续用usb，但是用其他软件比如DG来访问这个保留分区。。。
我目前用的移动硬盘。。

感谢作者 祝ventoy越来越好！:+1:
