### ISSUE TITLE
[issue]: I/O error for Ventoy with a disk drive connected with a USB 3.1 to 2.5" SATA hard drive adapter

### ISSUE THREAD

**Issue by davidhedlund** [ventoy/Ventoy#2609]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.95

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

120GB

### Disk Manufacturer

Kingston

### Image file checksum (if applicable)

None

### What happened?
Connected a USB-A 3.1 (gen 2(x1)) to 2.5" SATA hard drive adapter to a USB-A 3.1 (gen 2x2) port on the backside of the computer and the SSD hard drive.

* In the Ventoy making program: Select the Kingston 120 GB SSD SATA hard disk.[1] Install Ventoy (interestingly, the installation failed once when I used the adapter, but I didn't save the log).
* Add a bunch of different ISOs (GNU/Linux distros, Windows 11) to the new Ventoy filesystem.
* Shut down the computer
* Configure the UEFI to boot from the newly installed hard drive.
* When I'm trying to boot the OS ISOs, they either halt, or I get error messages during the OS installations.

Example from Trisquel 11:

![image](https://github.com/ventoy/Ventoy/assets/6416073/ce0d7e6f-ed11-4eba-9274-345b073a9c83)

Windows 11:

![image](https://github.com/ventoy/Ventoy/assets/6416073/9b67a625-1342-48d5-92c1-c214f7f0229b)

# References
1: Same issue if I'm connecting the Kingston drive to a SATA port on the mainboard, and select "Option -> Show All Devices" in the Ventoy making program, and install it. Then shut down the computer and connect the USB to SATA hard drive adapter. Then add ISOs to the Ventoy filesystem, etc...

**Comment by steve6375** [comment]
You say you get this error when you boot to an ISO?
Is that true?
Or is it that you are trying to install an OS after booting to an ISO?
Are you trying to install it to the same drive?

**Comment by davidhedlund** [comment]
> You say you get this error when you boot to an ISO? Is that true? Or is it that you are trying to install an OS after booting to an ISO?

When I'm trying to boot the ISO installer (I never got the chance to click actually begin the installation). For example Ubuntu in live mode fails to boot up, which is needed to install it.

> Are you trying to install it to the same drive?

No.

**Comment by davidhedlund** [comment]
This adapter came today, and I just tried to restore a disk image of a GNU/Linux distro installation. It crashed one minute after I logged in to the desktop enviroment. So this is not a Ventoy issue after all.
