### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by Janssen-e55** [ventoy/Ventoy#2616]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.96

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

FreeBSD-13.2-RELEASE-amd64-dvd1.iso

### Image file checksum type

MD5

### Image file checksum value

6b1159a204fd614410d32b15993416c745917e6de1781aa608e53d8c6b3d24a4

### Image file download link (if applicable)

https://download.freebsd.org/releases/amd64/amd64/ISO-IMAGES/13.2/FreeBSD-13.2-RELEASE-amd64-dvd1.iso

### Test environment

Intel Celeron G1610

### More Details?

This image file booted successfully in Ventoy. I successfully installed FreeBSD 13.2 on pc.

**Comment by ventoy** [comment]
Thanks!
