### ISSUE TITLE
Macrium Reflect Free Works

### ISSUE THREAD

**Issue by shellster** [ventoy/Ventoy#263]
Hi,

I recently found Ventoy, and I just wanted to say that Macrium Reflect Free (https://www.macrium.com/reflectfree) seems to be compatible in my testing, and it isn't listed in your list. 

Thanks for this great tool.

**Comment by ventoy** [comment]
OK, thanks for your report.
Please give some detail about your test envrioment? Legacy BIOS or UEFI? the ISO file name and size ?

**Comment by shellster** [comment]
It was UEFI as well as Legacy BIOS, the iso is called "MacriumRescue.iso" and is 764MB.  Tested on a Lenovo Ideapad.

**Comment by chromer030** [comment]
Macrium Reflect is already tested and listed in Github test page : 

> Macrium Reflect Workstation , supports UEFI , booting successfully.
>Macrium_Reflect_Workstation_PE_v7.2.4797.iso - 280 MB

**Comment by shellster** [comment]
@chromer030 You are right.  I missed that somehow.  Might make sense to add the "Free" addition as well to the list.

**Comment by chromer030** [comment]
Will be added , Thanks very much .
