### ISSUE TITLE
[Success Image Report]: Batocera 38

### ISSUE THREAD

**Issue by dementeb** [ventoy/Ventoy#2647]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.96

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

batocera-x86_64-x86_64-38-20231014.img

### Image file checksum type

MD5

### Image file checksum value

581e1fb0f324da1ded45e614a8429cf4

### Image file download link (if applicable)

https://updates.batocera.org/x86_64/stable/last/batocera-x86_64-x86_64-38-20231014.img.gz

### Test environment

Dell Latitude 7490 Laptop

### More Details?

This image file booted successfully in Ventoy.

I also try to use "VTOY_LINUX_REMOUNT=1" but no luck, it's doesn't work.
Latest version of vtoyboot script (1.0.30) does not work here - "Current OS is not supported!" (this release of batocera used 6.4.16 kernel).

**Comment by ventoy** [comment]
Thanks!
