### ISSUE TITLE
[Success Image Report]: Win10_22H2_English_x64v1.iso

### ISSUE THREAD

**Issue by karczex** [ventoy/Ventoy#2648]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.96

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

Win10_22H2_English_x64v1.iso

### Image file checksum type

MD5

### Image file checksum value

c2b19762870226ca467d6cbd87cd8fab

### Image file download link (if applicable)

https://www.microsoft.com/en-us/software-download/windows10ISO

### Test environment

Dell latitude 3340

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
