### ISSUE TITLE
[issue]: cannot run in linux 

### ISSUE THREAD

**Issue by newyorkthink** [ventoy/Ventoy#2650]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

latest

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32G

### Image file checksum (if applicable)

None

### What happened?

hi
my linux run ventoy cannot open GUI
![image](https://github.com/ventoy/Ventoy/assets/87791643/de536067-ce1c-4282-b373-acf9475ae241)
its not have happen some , 
please support APPimage

**Comment by catherinedoyel** [comment]
Do not run from your home directory.
```
cd Downloads/ventoy-1.0.96
sudo chmod +x VentoyGUI.x86_64
sudo VentoyGUI.x86_64
```

**Comment by newyorkthink** [comment]
> Do not run from your home directory.
> 
> ```
> cd Downloads/ventoy-1.0.96
> sudo chmod +x VentoyGUI.x86_64
> sudo VentoyGUI.x86_64
> ```

![image](https://github.com/ventoy/Ventoy/assets/87791643/e9387324-5307-47be-a609-02471f890df6)

**Comment by newyorkthink** [comment]
> Do not run from your home directory.
> 
> ```
> cd Downloads/ventoy-1.0.96
> sudo chmod +x VentoyGUI.x86_64
> sudo VentoyGUI.x86_64
> ```

not work

**Comment by newyorkthink** [comment]
it ok
