### ISSUE TITLE
Lazesoft Recover My Password Success Image Report]: 

### ISSUE THREAD

**Issue by higginsneil** [ventoy/Ventoy#2653]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.57

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

lssoft.iso

### Image file checksum type

MD5

### Image file checksum value

Unknown 

### Image file download link (if applicable)

https://www.lazesoft.com/lazesoft-recover-my-password.html

### Test environment

Lenovo laptop

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
