### ISSUE TITLE
[issue]: WIM file not recognized

### ISSUE THREAD

**Issue by Staubgeborener** [ventoy/Ventoy#2664]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.96

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

64GB and 32 GB

### Disk Manufacturer

SanDisk and Toshiba

### Image file checksum (if applicable)

Yes.

### What happened?

I got an original .wim file from lenovo. As the readme file in this repository tells me, .wim files should be supported. So i created two different ventoy usb sticks (32 GB and 64 GB) successfully. After that, i put this .wim file into the data partition and booted from it. I can access the graphical ventoy grub menu, but the .wim file is not listed.

**Comment by steve6375** [comment]
Did you add the plugin?
https://ventoy.net/en/plugin_wimboot.html

**Comment by Staubgeborener** [comment]
No, but i tried it right now. The `ventoy_wimboot.img` file is in the same partition which hols the .wim files. Didn't solve the issue.

**Comment by steve6375** [comment]
![image](https://github.com/ventoy/Ventoy/assets/1469350/19076946-34ef-4773-8917-86a19fe7232c)
Did you put the file in the /ventoy directory?

**Comment by Staubgeborener** [comment]
Oh damn, you're totally right. That's it.

**Comment by steve6375** [comment]
The documentation could be improved. Fort instance main page https://ventoy.net/en/index.html  says it will boot wim files and VHD files but there is no indication that anything special like plugins, etc. are required.
There should be a link or asterisk or something, if a plugin or special action or limitation (like NTFS for ptn1) is required.
Also info about booting .wim, .VHDs, .VHDx, files etc. it should be in  FAQ page
