### ISSUE TITLE
[Success Image Report]: LMDE 6 Faye

### ISSUE THREAD

**Issue by maciejkrol18** [ventoy/Ventoy#2665]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.96

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

lmde-6-cinnamon-64bit.iso

### Image file checksum type

SHA256

### Image file checksum value

96963cac1ac2ad4ba38414e618adbcdf64a6faadc33ddf53889fa3dc74d59df4

### Image file download link (if applicable)

https://ftp.icm.edu.pl/pub/Linux/dist/linuxmint/isos/debian/lmde-6-cinnamon-64bit.iso

### Test environment

Dell Latitude E7240

### More Details?

This image file booted successfully in Ventoy. The system was successfully installed

**Comment by ventoy** [comment]
Thanks!
