### ISSUE TITLE
[Success Image Report]: MiniOS

### ISSUE THREAD

**Issue by Wh1t3st4r** [ventoy/Ventoy#2676]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.96

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

minios-bookworm-xfce-standard-pt-lkm-aufs-amd64-zstd-20231107_0742

### Image file checksum type

SHA256

### Image file checksum value

bf8e635c980d873fc3bf748e471027c8e2915d1bfe144953843459193e941932

### Image file download link (if applicable)

https://minios.dev/en/download-xfce-standard-amd64.html

### Test environment

Compaq Presario CQ43

### More Details?

This image file booted and executed successfully in Ventoy. Only the Standard Edition image was tested.

**Comment by ventoy** [comment]
Thanks!
