### ISSUE TITLE
[Feature Request] Define different Icon's for Folder in Tree View.

### ISSUE THREAD

**Issue by soares23** [ventoy/Ventoy#268]
Hi, 
Thanks for your great work and does you have implemented the feature of class in the new version of ventoy.

I would ask you if is possible do define different icon's for Folders.

For now, what I have tested only can use the vtoydir.png icon but that is for all the Folders.

Can you say me if it's possible to specify in Tree View of Ventoy different classes for the Folder if not can you please implement it in your next release if possible if not is no problem but would be nice. Thanks for your Great work.

**Comment by ventoy** [comment]
Yes, currently all the folders use the same `vtoydir` class, it's also simple to support customized directory class.
Maybe something as follows in the next release (specify the full path of the folder and the corresponding class):
```
{
    "menu_class" : [
        {
            "key": "MX-",
            "class": "mx"
        },         
        {
            "folder": "/ISO/Windows",
            "class": "windows"
        }
    ]
}
```

**Comment by soares23** [comment]
That would be nice if you can implement it in your next release.

**Comment by ventoy** [comment]
For consistency, maybe `key` is more appropriate.

If `key` is start with `/`  it means a full path of a directory or it means a substring of image file name.

```
{
    "menu_class" : [
        {
            "key": "MX-",
            "class": "mx"
        },         
        {
            "key": "/ISO/Windows",
            "class": "windows"
        }
    ]
}
```

**Comment by soares23** [comment]
Yes, for the consistency is better to use **key**. But if your Using **Folder** as parameter is easier to see the different if it is a folder or and iso file. 
It is on your choice to make it like you thing is the best things for the project, for me is no matter how it is done. The only thing that is important that the option is possible.

**Comment by ventoy** [comment]
I will add this option in the next release.

**Comment by ventoy** [comment]
Supported in new release
