### ISSUE TITLE
Deepin latest did not sart at all

### ISSUE THREAD

**Issue by enigma131** [ventoy/Ventoy#269]
deepin-live-system-2.0-amd64.iso and install iso did start on menu, then a splash screen then a kernel error.
Same isos works with Rufus.  I'm with MBR partitions

**Comment by ventoy** [comment]
deepin live system is not supported now.

**Comment by enigma131** [comment]
Ok thanks, I's more clear now

**Comment by ventoy** [comment]
Deepin-live is supported now, please try with latest release.
