### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by TanaroSch** [ventoy/Ventoy#2690]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.96

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

Win10_22H2_German_x64v1.iso

### Image file checksum type

MD5

### Image file checksum value

D1A41A09E9AE09631A087EDF95D7F4EECAB622F88B3C824D856CFEA47FCC0B4C

### Image file download link (if applicable)

https://www.microsoft.com/de-de/software-download/windows10ISO

### Test environment

Dell Latitude E6420

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
