### ISSUE TITLE
[Success Image Report]:  Debian live 12.4.0

### ISSUE THREAD

**Issue by NovoAnachronistic** [ventoy/Ventoy#2698]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.96

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

debian-live-12.4.0-amd64-cinnamon.iso

### Image file checksum type

SHA256

### Image file checksum value

4d780b003fdfdddc6218a3abf4243dfe96fd53520ce9aa710bb7708dde120472

### Image file download link (if applicable)

http://debian.mirror.digitalpacific.com.au/debian-cd/12.4.0-live/amd64/iso-hybrid/debian-live-12.4.0-amd64-cinnamon.iso

### Test environment

HP ProBook 650 G1

### More Details?

This image file booted successfully in Ventoy.
Ventoy installed to : ID 03f0:2d40 HP, Inc v150w USB drive

So far, persistence only achieved through creating a disk partition on the v150w device labeled 'persistence', and following instructions [here](https://github.com/bestia-dev/boot_usb_with_ventoy_debian_live_persistence) and [here](https://unix.stackexchange.com/questions/118965/how-to-create-a-debian-live-usb-with-persistence).

lmde-6-cinnamon-64bit.iso (**Linux Mint LMDE booted via Ventoy on different device**) is happy to use the persistence partition, even though it is booted from a different USB device to that which the persistence partition is installed on.

I'm still trying to get persistence working with the .dat files.  Can I update progress here?

**Comment by ventoy** [comment]
Thanks!
