### ISSUE TITLE
[Success Image Report]: Kylin Desktop V10 SP1 Release 2203

### ISSUE THREAD

**Issue by phanxlee** [ventoy/Ventoy#2701]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.96

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

Kylin-Desktop-V10-SP1-HWE-Release-2203-X86_64.iso

### Image file checksum type

MD5

### Image file checksum value

0D1EF564BBCB5A93EC20E0844A259172

### Test environment

HIKVISION XC-P923P

### More Details?

Test environment Detail:
HIKVISION XC-P923P
CPU: ZHAOXIN KaiXian KX-U6780A
MEM: SinoChip 3200 DDR4 SCC08GU03H3F1C-32AA
Video: ZX-E C-960 GPU
SSD: HIKVISION HS-SSD-V100
----------------------------------------------------------------------------------------
uniontechos-desktop-20-professional-1050-update2-amd64.iso
MD5: F5D2687C3F5FD32C3897FE2210DCF00B
SHA-1: 22C5A11DCA1843F4A9E8B26C96D8643876706AC7
SHA-256: 21C64BBCDDA5BA674D0A89AF7A1FF14D2DBC68650153E6B75804D48A066AE06F

**Comment by ventoy** [comment]
Thanks!
