### ISSUE TITLE
[issue]: Ventoy GUI makes a GPT USB that boots to Grub prompt

### ISSUE THREAD

**Issue by juls0730** [ventoy/Ventoy#2704]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.96

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64GB

### Disk Manufacturer

Memorex

### Image file checksum (if applicable)

None

### What happened?

When creating a GPT disk using the ventoy GUI, my Memorex 64GB flash drive always boots to the Grub prompt on both my acer aspire VX 15 laptop and my PC. The USB is correctly created via the cli using the same formatting scheme and same everything. I tried using secure boot, and without secure boot, but I have not tried MBR.

**Comment by Gravy59** [comment]
I have this issue as well, same Memorex 64 GB flash drive formatted with GPT and secure boot, tried it in Vbox + various laptops, boots to grub cmd line

**Comment by steve6375** [comment]
Ventoy requires the use of the last 32mb of a usb drive.
So the usb drive must not be a fake drive 
As an experiment, use the make gui to create a new Ventoy drive but reserve 32gb of space . The gui will then put the 2nd Ventoy boot partition in the middle of the usb drive.
Then see if it boots 
You can also test the usb drive using validrive.exe or fakeflashtest.exe.

**Comment by juls0730** [comment]
The USB is not a fake drive, I have tested all my drives before, and all my Memorex drives (including the one I used in this instance) are real drives and the capacity they report is correct. I don't recall how I got the drive working, but I eventually did

**Comment by steve6375** [comment]
Of course the capacity they report is correct, it's just that they actually contain less memory than they report!
Your reply makes no sense, what do you mean you 'eventually got the drive working ' ? You mean it now boots to Ventoy ok? If so please close the issue.

**Comment by juls0730** [comment]
sorry if I wasnt clear, but when I said the capacity they report is correct, I meant that the USB drives report the same amount of memory that they contain

**Comment by steve6375** [comment]
But how do you know what size memory they contain?  What utility did you use to test them?

**Comment by juls0730** [comment]
I used F3probe from the F3 project

**Comment by Gravy59** [comment]
My Memorex passes validation:
![image](https://github.com/ventoy/Ventoy/assets/58180094/c82700b0-a6fd-40bc-a19b-d0fa8948a288)
![image](https://github.com/ventoy/Ventoy/assets/58180094/899f751d-8353-44d2-bab7-0dba042facc8)

**Comment by Gravy59** [comment]
> As an experiment, use the make gui to create a new Ventoy drive but reserve 32gb of space .
Doing now, will update with results
![image](https://github.com/ventoy/Ventoy/assets/58180094/c8e055c8-8eec-4e84-891d-92282f8505da)
![image](https://github.com/ventoy/Ventoy/assets/58180094/6891cffa-81fe-46dd-aac8-1c1b19f2a9d5)

**Comment by Gravy59** [comment]
Doing what @steve6375 recommended worked

**Comment by juls0730** [comment]
I’m going to take a shot in the dark, can you try using fat32 on the drive as opposed to exfat. I’ll see if Exfat was the problem for me when I get home.
