### ISSUE TITLE
[Success Image Report]: memtest86plus-grub-nightly-64.iso (v7.00)

### ISSUE THREAD

**Issue by goldshadow0731** [ventoy/Ventoy#2707]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.89

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

memtest86plus-grub-nightly-64.iso

### Image file checksum type

SHA1

### Image file checksum value

B39D7BC743C4B2AF85A7B51A7003927493D6BD20

### Image file download link (if applicable)

https://www.memtest.org/dev

### Test environment

HP TPN-I130 laptop

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
