### ISSUE TITLE
[Success Image Report]: IGEL OS 12

### ISSUE THREAD

**Issue by monkeydude7230** [ventoy/Ventoy#2709]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.96

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

osc12.02.000.iso

### Image file checksum type

SHA256

### Image file checksum value

8a1eabe630b2dba0ad045931a42a1dfdfa778ea03e9b133cd2665f15f52409b0

### Test environment

13th Gen Intel NUC

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!

**Comment by SpikeTurbo** [comment]
I am having trouble getting this to work. What steps were taken to get IGEL to work with Ventoy? It appears to be getting stuck each time I try to boot to it in Ventoy.

**Comment by ChrisKibble** [comment]
I don't have access to 12.02 (it's quite outdated at this point), but neither 12.7.1 nor 12.7.2 work.

**Comment by Moshikot3** [comment]
12.7.3 Doesn't work either. Stuck on boot screen.
