### ISSUE TITLE
[Success Image Report]: clonezilla

### ISSUE THREAD

**Issue by ljtetris** [ventoy/Ventoy#2710]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.96

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

clonezilla-live-20231102-mantic-amd64.iso

### Image file checksum type

MD5

### Image file checksum value

9dfe9c248c26bb2a1f8dd50087839d00

### Image file download link (if applicable)

https://sourceforge.net/projects/clonezilla/files/clonezilla_live_alternative/20231102-mantic/clonezilla-live-20231102-mantic-amd64.iso

### Test environment

Asus U5F laptop

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
