### ISSUE TITLE
[Success Image Report]: crystal-live-2023-10-27-x86_64.iso Successful boot

### ISSUE THREAD

**Issue by Dark-Matter1** [ventoy/Ventoy#2712]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.96

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

crystal-live-2023-10-27-x86_64.iso

### Image file checksum type

MD5

### Image file checksum value

796ddf0a041c9fb74bc4f7f524c7c803

### Image file download link (if applicable)

https://git.getcryst.al/crystal/misc/iso/-/jobs/296/artifacts/raw/iso/crystal-live-2023-10-27-x86_64.iso

### Test environment

Dell Latitude 5480

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
