### ISSUE TITLE
[Success Image Report]: Windows 10 LTSC 2021 Works On Chuwi Hi8 Pro IA32

### ISSUE THREAD

**Issue by GelzarZakcrakious** [ventoy/Ventoy#2718]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.96

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

en-us_windows_10_enterprise_ltsc_2021_x86_dvd_9f4aa95f.iso

### Image file checksum type

MD5

### Image file checksum value

-

### Image file download link (if applicable)

https://massgrave.dev/windows_ltsc_links.html

### Test environment

Chuwi Hi8 Pro (Hi8 PQ32G22170xxxxx)

### More Details?

This image file booted successfully in Ventoy IA32.

**Comment by ventoy** [comment]
Thanks!
