### ISSUE TITLE
建议默认文件系统为 ntfs，无日志文件系统 exfat 有丢失数据的风险。

### ISSUE THREAD

**Issue by xiaorong61** [ventoy/Ventoy#272]
[为什么有人说exfat会丢数据呢？](https://www.zhihu.com/question/21034296)
节选：作者：木头龙
链接：https://www.zhihu.com/question/20448164/answer/976789624
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

因为exFAT是一个没有日志的文件系统，是会出现文件“丢失”的风险的。具体来说，假设我们往移动硬盘上复制一个文件，复制到一半的时候把移动硬盘拔下，那么这个文件肯定没拷贝完，用什么文件系统都一样并没有区别。但是拷贝一个文件，不单单是拷贝这个文件本身，文件系统需要修改这个文件所在的目录的数据，这样操作系统才能知道这个目录下有这么一个文件，这个文件在硬盘上的哪个扇区，这样的数据，一般称之为Metadata（元数据）。但在修改Metadata的过程中，如果移动硬盘被拔下，Metadata被破坏的话，那么这个目录下的文件、子目录数据都会被破坏，结果就是文件、子目录的数据其实都还在硬盘上，但是在操作系统看来，有部分文件/子目录消失了——这是前面说丢失要用双引号的原因。对于有日志的文件系统，如NTFS、HFS+，在修改Metadata之前会先写日志记录要修改哪些Metadata，如何修改。硬盘拔下后修改失败，只要重新插上，操作系统挂载的时候会发现这个修改未完成，重新修改一遍，保证文件系统数据结构的完整性。对于没有日志的文件系统，如FAT/FAT32/exFAT、HFS，只能在进行文件系统检查的时候发现错误，然后把丢失的文件找出来——但文件信息已经丢失，文件系统只能知道这里曾经有一个文件，但不知道文件名，也不知道在哪个目录下。

**Comment by ventoy** [comment]
后续版本在安装时会增加一个文件系统的选项。
当前exfat主要考虑跨平台兼容性较好以及比较适合U盘（NTFS比较伤小容量U盘）。当然需要用户注意安全操作。
如果有这方面考虑的，可以选择NTFS文件系统，但默认应该还是会保持exFAT

**Comment by sky5454** [comment]
日志式文件系统并不适合 U盘 使用。另外 exFAT 易丢文件应该是单文件分配表造成的。和 exFAT 相比， FAT32 就没那么容易丢文件。

**Comment by xiaorong61** [comment]
> 日志式文件系统并不适合 U盘 使用。另外 exFAT 易丢文件应该是单文件分配表造成的。和 exFAT 相比， FAT32 就没那么容易丢文件。

> 后续版本在安装时会增加一个文件系统的选项。
> 当前exfat主要考虑跨平台兼容性较好以及比较适合U盘（NTFS比较伤小容量U盘）。当然需要用户注意安全操作。
> 如果有这方面考虑的，可以选择NTFS文件系统，但默认应该还是会保持exFAT

可以通过容量或者别的方式检查一下，U盘 exfat，移动机械或固态盘 ntfs。

**Comment by GoGoogle** [comment]
被你这么一提醒，我突然感觉我是不是有必要换成NTFS？
因为我之前用的exFAT，别说文件，连U盘都废了，我也不知道是因为质量问题还是exFAT造成的。

（话说，如果换NTFS，我这40GB的文件又要重新整理一次，好累的说。
