### ISSUE TITLE
[Success Image Report]: Parted Magic 2023_11_22

### ISSUE THREAD

**Issue by rmolina** [ventoy/Ventoy#2721]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.96

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

pmagic_2023_11_22.iso

### Image file checksum type

SHA256

### Image file checksum value

29f58200cae4cccc867fab0907672fb58a476e3dbf62833f979adcf6a5f9df1a

### Test environment

OptiPlex 3070 SFF

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
