### ISSUE TITLE
[issue]: 启动iso后，linux挂载U盘的问题。

### ISSUE THREAD

**Issue by happymy** [ventoy/Ventoy#2724]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

last

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

32GB

### Image file checksum (if applicable)

None

### What happened?

ISO File：Debian 12 livecd
成功启动后，发现启动的USB DISK 无法挂载数据分区。
USB DISK 分区数量2 
类型：可移动磁盘。
SDB1=数据分区，FAT32或者EXFAT ，SDB2=Ventoy 建立的分区。
SDB2 已被挂载。可以被访问。
手动mount SDB1 无法被挂载，错误：设备忙或已被挂载。
mount -l 未发现SDB1挂载点。

**Comment by ventoy** [comment]
可以使用 全局控制插件中的 `VTOY_LINUX_REMOUNT` 选项。 
https://www.ventoy.net/cn/plugin_control.html

**Comment by ventoy** [comment]
或者在 F5 里面设置。
https://www.ventoy.net/cn/doc_ctrl_settings.html

**Comment by happymy** [comment]
谢谢，有效。
