### ISSUE TITLE
关于“大容量（128GB以上）”优盘的处理

### ISSUE THREAD

**Issue by joomlagate** [ventoy/Ventoy#273]
我无意中在网上发现 Ventoy 的介绍时，非常激动，一下子就认定这是个不错的工具。但是我没有仔细阅读相关文档就立即从网上购买了一款 512GB 容量的大优盘，因为考虑着要在里面多放几个系统安装盘的 ISO 文件。

拿到大容量优盘之后，我立即用 Ventoy 进行了安装，并复制了多个 ISO 文件进去。

然后我在 PC 上面测试该优盘的时候，发现只能引导进入 Grub 命令行，并未出现引导选择菜单。百思不得其解。

随后我在 Ventoy 官方网站看到了“不支持 128GB 以上优盘”的相关文档，才意识到优盘买大了。

现在我有个建议：

从携带文件数量越多越好这个角度来说，大容量优盘显然是最好用的。

但是考虑到很多PC主板的 BIOS 不支持大容量优盘，那么，是否可以这么做： 给 Ventoy 增加一个“将大容量优盘切割多个分区” 的新功能？

具体工作模式是：

1、Ventoy 运行后，如果探测到目标优盘容量大于 128GB，发出警告，提醒用户：该优盘容量过大，很多 PC 主板不能识别。无法直接制作启动盘。

2、Ventoy 向用户提出建议：要么更换小容量优盘，要么将当前大容量优盘分区，使得第一个分区大小约 128GB，剩余容量作为第二个分区。

当然了，这就需要给 Ventoy 在增加一个“能够给大容量优盘（闪存芯片）分区”的功能。貌似给 Flash Drive 分区还有点难度。希望你们能考虑一下这个功能建议。

谢谢！

**Comment by ventoy** [comment]
首先，这个问题只存在于一些较老的主板上面，而且只针对Legacy BIOS模式，UEFI模式没有这个问题，UEFI是今后的主流。
对于确实有这种问题的，而且必须要用Legacy BIOS模式的，Ventoy从1.0.14版本开始支持安装时保留空间，参考 [https://www.ventoy.net/cn/doc_disk_layout.html#reserve_space](https://www.ventoy.net/cn/doc_disk_layout.html#reserve_space)

可以在安装Ventoy时在U盘最后保留一大部分空间，这样让存放ISO的第一个分区不超过BIOS限制就可以了。

**Comment by joomlagate** [comment]
我用的 Ventoy 版本就是 1.0.14，是不是已经自动预留空间了？那我再试试把主板的 BIOS 改成 UEFI 模式试试。

**Comment by ventoy** [comment]
默认不会自动预留空间，需要你手动去指定。参考上面的链接。

**Comment by joomlagate** [comment]
今晚上测试了上面的操作过程，手工设置预留空间，简单计算了一下，512 - 128 = 384 ，因此我设置 “-384” 预留空间。但是，完成 ventoy “安装” 之后，win10 系统竟然只识别了 ventoy “自留”的那个 32MB 的盘符（K），而没有识别本应该用来存放 ISO 文件的另一个分区（J 盘）！

我万万没想到，买了一个 512GB 的大容量优盘，反而被它给害惨了！

我还尝试了一个办法：用 Bootice 工具，把优盘先分成两个分区，一个 128GB，一个 384GB。然后，我希望 ventoy 只针对第一个 128GB 的分区来进行“安装”，但是 ventoy 不是针对“分区”来工作，而是针对整个“磁盘”来工作。因此，ventoy 没有理会我对优盘所做的“分区”操作，直接重新格式化了整个优盘。

怎么办呢？难道我需要联系销售商，把这个大容量优盘给退了？

**Comment by GoGoogle** [comment]
@joomlagate 我建议你只留下100G试试。

**Comment by ventoy** [comment]
“而没有识别本应该用来存放 ISO 文件的另一个分区（J 盘）！”
--------- 这个是什么情况？ 截图看看？

另外，你可以找个Linux环境（也可以用虚拟机）用Linux版本的安装包制作一次试试。

**Comment by joomlagate** [comment]
算了，不折腾了，考虑到某些主板（包括我自己笔记本电脑的主板）都不支持 128GB 以上的优盘，我还是从根本上解决吧。我打算把这个大优盘给退了，换成 128GB 的再试。

或许是我买的杂牌的优盘其芯片等等硬件存在问题？谁知道呢，不管了，先换容量再说。

**Comment by yinch3ng** [comment]
我用的是移动硬盘。。。好像没受128G限制。。

我之前是遇到老版本windows无法识别usb设备第二分区的问题，无奈选择移动硬盘，建议你试试

**Comment by LuoshuiTianyi** [comment]
我的移动硬盘以前用grub引导镜像的方法没什么问题，刷ventoy来管理应该也不会有问题吧，害怕
