### ISSUE TITLE
[issue]: `VTOY_LINUX_REMOUNT` doesn't work on Arch Linux 2024.02.01

### ISSUE THREAD

**Issue by youk** [ventoy/Ventoy#2730]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.97

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64GB

### Image file checksum (if applicable)

None

### Image file download link (if applicable)

https://archlinux.org/releng/releases/2024.02.01/

### What happened?

It's broken again: the usual "device busy" blah-blah. `dmesg` shows the following error message:

> dm_patch: module verification failed: signature and/or required key missing - tainting kernel

**Comment by ventoy** [comment]
If the secure boot option is enabled in the BIOS try to disable it and reboot.

**Comment by ventoy** [comment]
Try the latest CI release.
