### ISSUE TITLE
[issue]: Windows 10 / 11, HP ProBook 450 G8: No install source detected during the installation.

### ISSUE THREAD

**Issue by philippetev** [ventoy/Ventoy#2733]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.97

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64GB

### Disk Manufacturer

Transcend

### Image file checksum (if applicable)

Yes.

### What happened?

The flash drive is GPT formatted. I have Windows 10 and Windows 11 ISOs on the Ventoy partition. I can boot any of those ISOs, but when I click the "Install now" button, instead of the product key dialog, I get the famous "A media driver your computer needs is missing" message and can't continue any further. At this point I've noticed there is no install media, only the Ventoy drive and the X drive (the installer session).

This happens on my HP ProBook 450 G8 (11 Gen Intel, 16 GB RAM, m.2 nvme ssd).

My old rig (Gigabyte H77N-WIFI, i7-3770, 16GB RAM, SATA SSD) has no such problem. The install media appears during the install and I go to the product key dialog, then to the edition selection and then to the partition editor with no issues.

All tests have been made with UEFI boot (the ProBook has no Legacy support). I suspect there is something wrong with the HP's UEFI implementation, but can't be sure.

**Comment by steve6375** [comment]
A driver is needed for the target drive to be detected. 
Usually the main board manufacturer will cover this situation on their website.

**Comment by philippetev** [comment]
The target drive is not the issue here. I have no install media, not target drive. The target drive appears right after I install the Intel RST driver.

**Comment by steve6375** [comment]
So it is standard Microsoft iso?
How do you load rst driver if no usb can be seen?

**Comment by philippetev** [comment]
Haven't said the usb doesn't work. They do. All the USB drives I attach during the installation are visible in the browse dialog. There is no only the installation media, you know, the ISO file, mounted as a drive, so the installation can't find the install.wim/install.esd file.

**Comment by steve6375** [comment]
Are you using a standard, unmodified Microsoft ISO - made and downloaded from Microsoft?
Ventoy injects its own winpeshl.exe file into the X: ram disk and that shell has additional code to install the ISO as a virtual drive before calling the real winpeshl.exe. So it only works with standard Windows  PE  boot.wim files. It may not work with 3rd-party non-standard Windows Install ISOs.
So maybe you could answer my question?

**Comment by philippetev** [comment]
I think I've solved it. Kind of. It was some setting/s in my BIOS. Restored the default settings, then set them again and now it injects those files correctly and the ISO is mounted. Thanks for the hints anyway!

**Comment by steve6375** [comment]
Interesting. Can you remember what settings you changed in the BIOS?

**Comment by philippetev** [comment]
Unfortunately, no.
More importantly, I don't know which setting I turned on, and obviously I shouldn't have...
