### ISSUE TITLE
[Success Image Report]: AlmaLinux-9.3-x86_64-boot.iso

### ISSUE THREAD

**Issue by iocc-git** [ventoy/Ventoy#2734]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.97

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

AlmaLinux-9.3-x86_64-boot.iso

### Image file checksum type

MD5

### Image file checksum value

6df36134d4bdf363f3f216049fd3c8ad

### Image file download link (if applicable)

https://repo.almalinux.org/almalinux/9.3/isos/x86_64/AlmaLinux-9.3-x86_64-boot.iso

### Test environment

Razer Blade 15 (2022 Advanced) Laptop

### More Details?

This image file booted successfully in Ventoy and it was possible to install AlmaLinux and boot from the SSD.
Ventoy is a great tool that I didnt know about!

It was absolutely impossible to boot the image without Ventoy. Most likely due nasty UEFI.

**Comment by iocc-git** [comment]
When will it be added to the isolist? Long time since it was updated now. All success reports could be merged at least.

**Comment by ventoy** [comment]
Thanks!
