### ISSUE TITLE
[Success Image Report]: Parrot-security-6.0_amd64.iso

### ISSUE THREAD

**Issue by Gonpachiro-Kun** [ventoy/Ventoy#2738]
### Official Website List

- [x] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.97

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

Parrot-security-6.0_amd64.iso

### Image file checksum type

MD5

### Image file checksum value

176c2a3d94b6cb2a568769c25b0dB122

### Image file download link (if applicable)

https://bunny.deb.parrot.sh//parrot/iso/6.0/Parrot-security-6.0_amd64.iso

### Test environment

Gigabyte B75MS Computer Using Windows 10 (8GB RAM, i5-2400S @ 2.50GHz, GT 710)

### More Details?

This image file booted successfully in Ventoy and also calculated the MD5 checksum using Ventoy.
I tried booting the image with Legacy boot system but did not have any luck with it and it crashed.
I also used persistence using ext4 by creating a parrot_persistence.dat file of 12GB which is working fine.

**Comment by qqzwc** [comment]
This iso can use Ventoy Persistence Plugin with label "persistence"

**Comment by DavidFlisar** [comment]
The download link doesn't work anymore. 404
