### ISSUE TITLE
[Success Image Report]: ubuntu-23.10-live-server-amd64.iso

### ISSUE THREAD

**Issue by tofupup** [ventoy/Ventoy#2739]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.97

### BIOS Mode

Both

### Partition Style

MBR

### Image file name

ubuntu-23.10-live-server-amd64.iso

### Image file checksum type

SHA256

### Image file checksum value

d2fb80d9ce77511ed500bcc1f813e6f676d4a3577009dfebce24269ca23346a5

### Image file download link (if applicable)

[ubuntu 23.10 server download from releases.ubuntu.com](https://releases.ubuntu.com/23.10/ubuntu-23.10-live-server-amd64.iso)

### Test environment

AMD Ryzen 5600x with X570 chipset, 5900x with B550 chipset

### More Details?

This image file booted successfully in Ventoy.  I used it to upgrade a couple of bare metal instances to 23.10, worked beautifully.

**Comment by ventoy** [comment]
Thanks!
