### ISSUE TITLE
theme.txt syntax description

### ISSUE THREAD

**Issue by GHNewbiee** [ventoy/Ventoy#275]
Please, include in documentation a detailed syntax description of the `theme.txt` file.

I am trying to use **menu class** *plugin*  and set `item_spacing`, `item_padding`, `item_icon_space` and other variables (**<-- ?**).

Tia

**Comment by ventoy** [comment]
Ventoy use standard grub2 theme. So you can search grub2 theme manual in the internet.
These may be helpful:

[https://www.gnu.org/software/grub/manual/grub/html_node/Theme-file-format.html](https://www.gnu.org/software/grub/manual/grub/html_node/Theme-file-format.html)

[http://wiki.rosalab.ru/en/index.php/Grub2_theme_tutorial](http://wiki.rosalab.ru/en/index.php/Grub2_theme_tutorial)

**Comment by blackcrack** [comment]
https://store.kde.org/browse/cat/109/order/latest
