### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by NullDott** [ventoy/Ventoy#2754]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1,0,97

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

Fedora-Workstation-Live-x86_64-39-1.5.iso

### Image file checksum type

SHA256

### Image file checksum value

https://mirror.cpsc.ucalgary.ca/mirror/fedora/linux/releases/39/Workstation/x86_64/iso/Fedora-Workstation-39-1.5-x86_64-CHECKSUM

### Image file download link (if applicable)

https://download.fedoraproject.org/pub/fedora/linux/releases/39/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-39-1.5.iso

### Test environment

Dell Latitude E7470
CPU: Intel Core i7-6600U 
GPU:Intel Corporation Skylake GT2 [HD Graphics 520]

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
