### ISSUE TITLE
Hkboot and Pardus-19.0-XFCE-amd64.iso boot error

### ISSUE THREAD

**Issue by crasadure** [ventoy/Ventoy#276]
Hi ventoy;
@[serhat100](https://www.tnctr.com/profile/220094-serhat100/)  from TNCTR forum reported that There are some errors at Hkboot WinPE  tests on Ventoy Legacy and uefi. 
These are error pictures:

HKBootx64 Legacy Bios error
![Hkboot legacy](https://user-images.githubusercontent.com/54566818/86250912-e1365680-bbb9-11ea-8ea2-3bf79e914d20.jpg)

HKBootx64 UEFİ error
![Hkboot uefi](https://user-images.githubusercontent.com/54566818/86251005-fdd28e80-bbb9-11ea-80a0-db586e52257c.jpg)

Pardus-19.0-XFCE-amd64.iso UEFI is normally booted, only there is an error notification in the picture.
![Pardus Uefi](https://user-images.githubusercontent.com/54566818/86251036-062ac980-bbba-11ea-8c78-80a06d5df797.jpg)

Can you fix these problems?

**Comment by ventoy** [comment]
For Hkboot I will download and test it.
For Pardus I only test  Pardus-19.1-XFCE-amd64.iso in VMware and there is no such message. 
You can use other tools to make a bootable USB and make a comparative test

**Comment by crasadure** [comment]
Hi ventoy
@serhat100 from TNCTR  said that;
I made an edit in hkboot.iso, I took the edited bootmgr file in the main directory and changed it in the original windows.iso, I put it in the boot folder hkboot.iso, I put the bcd file in the boot folder content, but this time I choose win10x64.wim starts the installation windows opening icon then he makes the following mistake. 

image of the error
![IMG_20200706_120759](https://user-images.githubusercontent.com/54566818/86588127-c5ed9180-bf93-11ea-8f91-1bd879ba3603.jpg)

How can fix this problem?

**Comment by ulgens** [comment]
@crasadure Why did you close the issue? Is it completely resolved?
