### ISSUE TITLE
[Success Image Report]: Trusted End Node Security (TENS-Public Deluxe)

### ISSUE THREAD

**Issue by TwinCitiesTransplant** [ventoy/Ventoy#2761]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.97

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Image file name

TENS-3.0.4.1_public_deluxe.iso

### Image file checksum type

SHA256

### Image file checksum value

91a4a9c605c85092fef9e6142e371e4c72c7256378cf38d26977fbc7c35ebe1a

### Test environment

Hewlett-Packard HP Compaq dx2400 Microtower

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!

**Comment by new985211** [comment]
TENS-3.0.4.1_public_deluxe.iso，where can download it?it's a very Security Linux System Releases，I want to study use it，can you give a url or an Network disk download link？thank you very much!

**Comment by TwinCitiesTransplant** [comment]
@new985211, why don't you try the Internet Archive Wayback Machine?

**Comment by new985211** [comment]
I don't know how to download it. Can you give me a URL link?
