### ISSUE TITLE
[issue]: Can't install the world smallest Windows 10 / Windows 11 builds (only 1 GB) on MBR drive

### ISSUE THREAD

**Issue by oleedd** [ventoy/Ventoy#2771]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

The last version

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

4 GB

### Image file checksum (if applicable)

None

### What happened?

I installed Ventoy with "MBR" in the settings. But on formating, Windows installers say that UFI systems require GPT. Installations also don't work.
ISO files:
https://drive.google.com/file/d/19S16cXrJsFFZSM5H1-D0h4n_UnEwdvT9/view
https://drive.google.com/file/d/1E_kfOmJqnv44E_OzCl-Qn-h_wNUVIkJ6/view
They have Russian interface.
What is wrong? I need to install to MBR. Please help.

**Comment by steve6375** [comment]
Look at the Ventoy menu. Does it say UEFI Ventoy 1.0.97 or BIOS Ventoy 1.0.97?
If it says uefi then you have booted in uefi mode and so you can only install to a GPT disk.
A UEFI bios can boot from both MBR and got partitions.
Just because the usb drive contains MBR partitions does not mean it will boot only in BIOS mode!

**Comment by oleedd** [comment]
It says "UEFI", and I don't know why and how to fix it.
But I have Bios, it looks old and msinfo32 says so.
So how to boot in Bios?

**Comment by steve6375** [comment]
You need to disable secure boot and enable CSM mode in the bios options
Then press the bios boot selection key after power on, this could be F8 or F11 or something else depending on your bios
There may be two boot options , e.g. usb and UEFI usb. For legacy boot you need the plain usb option.

**Comment by oleedd** [comment]
I don't have a setting for Secure Boot, but on start, Ventoy writes that Secure Boot is disabled.
I don't have a setting for CSM. I knew that it can solve this.
I don't have options UEFI/BIOS. If I had, I wouldn't even install Ventoy. I have "PXE opRom policy" (it is about Uefi/Legacy), but enabling it doesn't help.

**Comment by steve6375** [comment]
Well, modern computers are uefi only, so you will have to delete the disk contents and create GPT partitions if legacy is not supported.
Check the manual for your system

**Comment by oleedd** [comment]
It is not modern. It is from 2014. It has American Bios. And "Legacy" is mentioned there. I don't have space to copy it. I can't delete.

**Comment by steve6375** [comment]
Well you need to boot in legacy mode.

**Comment by oleedd** [comment]
Yes. I checked related models, and there should be "CSM", but there isn't. Like I should do something to make it appear.

**Comment by steve6375** [comment]
Sometimes you need to set an admin bios password before the csm options will appear. Read the manual for your system!

**Comment by oleedd** [comment]
Setting a password didn't help. Bios reset too. In one Youtube video, I found that if to press "Esc" on startup, Boot Menu appears. And there are 2 options. So it is solved. But something wrong with my Bios...
Also, I found that Ventoy doesn't show memory cards (in a cardreader). In Windows, they work without installing a driver like flash drives.
