### ISSUE TITLE
[issue]: Not recognizing .WIM files

### ISSUE THREAD

**Issue by trumpeta** [ventoy/Ventoy#2773]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.97

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

8GB

### Disk Manufacturer

Silicon Power

### Image file checksum (if applicable)

None

### What happened?

Unlike .ISO and .EFI files, the boot manager does not recognize any .WIM files (they're put into /WIM/ directory on 1st partition). There is no filtering for WIM files and does not find in WIMBOOT mode. Also browse mode does not show the files (neither the WIM root folder is shown).

**Comment by steve6375** [comment]
Did you add the wimboot plugin file, as described in the documentation?

**Comment by trumpeta** [comment]
No, I did not notice the requirement at first. By putting the ISO on the drive WIMs already are visible. I would suggest to include all format plugin files into the installation package.
