### ISSUE TITLE
[issue]:  Endeavour Os not booting

### ISSUE THREAD

**Issue by pirsonxyz** [ventoy/Ventoy#2777]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.96

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

64GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://endeavouros.com/#Download

### What happened?

When booting with ventoy in a Endeavour Os iso i get this error: /dev/disk/by-label/EndeavourOS_XXXXXX. However, when i make the usb bootable with Balena Etcher i can install normaly without modifying anything in my BIOS.

**Comment by steve6375** [comment]
Did you try the grub2 boot option?
https://discovery.endeavouros.com/installation/create-install-media-usb-key/2021/03/

**Comment by steve6375** [comment]
![image](https://github.com/ventoy/Ventoy/assets/1469350/e9367cfa-cf58-42d7-a756-54726fcbd51c)

Booted using 'Normal' mode on Ventoy 1.0.97 using Virtual Box v5. Seems OK?

**Comment by pirsonxyz** [comment]
thanks! that fixed it

**Comment by keinou** [comment]
How you fixed this?
