### ISSUE TITLE
我测试了 ventoy-1.0.14 (U盘保留空间支持) ，发现多出来的分区根本无法正常使用。

### ISSUE THREAD

**Issue by GoGoogle** [ventoy/Ventoy#278]
RT
我把最后一个分区保留了4GB，但我新建分区，格式化分配盘符后，也无法正常读取，这是Bug还是我使用方法不对？

**Comment by a1ive** [comment]
低版本 Windows 只能给u盘的一个分区分配盘符。

**Comment by GoGoogle** [comment]
> 低版本 Windows 只能给u盘的一个分区分配盘符。

我还真是只在 Win7 上面测试的…
谢谢提点
