### ISSUE TITLE
[Success Image Report]: Proxmox v8.1-2

### ISSUE THREAD

**Issue by pjotrek-b** [ventoy/Ventoy#2783]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.97

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

proxmox-ve_8.1-2.iso

### Image file checksum type

MD5

### Image file checksum value

398cab55b4228720ae053db149fa80d1 

### Image file download link (if applicable)

https://enterprise.proxmox.com/iso/proxmox-ve_8.1-2.iso

### Test environment

MSI Mortar B450M Max, nVidia RTX 3060, 16 GB RAM

### More Details?

This image file booted successfully in Ventoy, after doing the following:

1) You need Ventoy v1.0.97
Otherwise the Proxmox install won't boot - claiming it does not find its ISO image (see #2657)

2) Remove the `initrd=/vtoy/vtoy` kernel parameter on the installed target system to [avoid getting stuck at "Loading initial ramdisk"](https://forum.proxmox.com/threads/ventoy-install-of-proxmox-8-1-halts-at-loading-initial-ramdisk.143196/) - see issue #2782.

**Comment by ventoy** [comment]
Thanks!

**Comment by pjotrek-b** [comment]
Thank you very much!
(And generally for Ventoy :kissing_heart: )
