### ISSUE TITLE
[issue]: `No ISO or supported IMG files found` on Kingston DataTraveler 256GB when formatted with EXT4

### ISSUE THREAD

**Issue by rempas** [ventoy/Ventoy#2791]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.97

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried GRUB2 as well, but the bug remains.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

256GB

### Disk Manufacturer

Kingston DataTraveler 256GB

### Image file checksum (if applicable)

None

### Image file download link (if applicable)

http://ftp.gr.freebsd.org/pub/FreeBSD/ISO-IMAGES-amd64/14.0/FreeBSD-14.0-RELEASE-amd64-disc1.iso

### What happened?

Hello and thank you for your amazing work on saving our USBs from unnecessary writings! About my problem:

I installed Ventoy (1.0.97) on my `Kingston DataTraveler 256GB` and formatted the first partition to **ext4** using [Gparted](https://gparted.org/). Then, I added FreeBSD14 (the iso in the download link above) and when I boot, I get the following line: `No ISO or supported IMG files found (Press enter to reboot ...)`.

This is a problem when formatting the USB to **ext4** as **fat32** works without problems.

**Comment by steve6375** [comment]
Did you check the file is there now? Did you Sync and Eject the USB drive before removing it or rebooting?

**Comment by rempas** [comment]
> Did you check the file is there now? Did you Sync and Eject the USB drive before removing it or rebooting?

Yeah. The file is there and I have "ejected" the disk. After that, I tried to boot, using normal and grub2 modes. Also, using both USB3 and USB2. Nothing works...

**Comment by steve6375** [comment]
So the file is there now? Visible in Linux on the USB drive?

**Comment by rempas** [comment]
> So the file is there now? Visible in Linux on the USB drive?

Yeah! Visible and accessible!

**Comment by steve6375** [comment]
Ok. So have you made a ventoy.json file ?
Is the ext4 partition 'special' in any way?
For test purposes, what if you reformatted it as exfat or NTFS or fat32?

**Comment by rempas** [comment]
> Ok. So have you made a ventoy.json file ? Is the ext4 partition 'special' in any way? For test purposes, what if you reformatted it as exfat or NTFS or fat32? Is the crc32 or md5 xsum of the iso correct?

Ok, I have good new and bad news!

Good news is, that it works when formatted on **fat32**

Bad news is, I have to use that terrible and ancient filesystem for my whole USB (unless I can break a third partition and use that for files, which is a little bit better).

Thanks a lot for the help! I will change the title and I hope it can be fixed soon!

**Comment by Pixel6test** [comment]
What distro did you use to format ? 
I had the same issue when I wanted to format in EXT4 within Fedora Rawhide (with gnome-disks). 

But it worked using Gparted livecd. So try to use another distro. Maybe it is related to the version of gparted used.

**Comment by rempas** [comment]
> What distro did you use to format ? I had the same issue when I wanted to format in EXT4 within Fedora Rawhide (with gnome-disks).
> 
> But it worked using Gparted livecd. So try to use another distro. Maybe it is related to the version of gparted used.

Thanks for the information! I used "Gparted" on Arch Linux. At that point, I cannot try something else. Also, FreeBSD used to boot (using **Fat32**) but now doesn't, so I'll probably avoid Ventoy all together so I can do my work.

**Comment by ventoy** [comment]
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/9144969402
https://www.ventoy.net/en/doc_github_ci.html

**Comment by rempas** [comment]
> Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/9144969402 https://www.ventoy.net/en/doc_github_ci.html

Thanks! It now works! However, FreeBSD doesn't work (error with USB from my understanding) and, can I make a feature request to be able to configure other file systems when we flash Ventoy so, we don't have to re-format the big partition again?
