### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by smoke007** [ventoy/Ventoy#2809]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.97

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

linuxmint-21.3-cinnamon-64bit.iso

### Image file checksum type

SHA256

### Image file checksum value

5aa24abbc616807ab754a6a3b586f24460b0c213b6cacb0bf8b9a80b65013ecc

### Image file download link (if applicable)

https://linuxmint.com/edition.php?id=311

### Test environment

Dell Precision 5530

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
