### ISSUE TITLE
[Success Image Report]: 

### ISSUE THREAD

**Issue by smoke007** [ventoy/Ventoy#2810]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.97

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Image file name

chromeos_15393.58.0_reven_recovery_stable-channel_mp-v2.bin.zip

### Image file checksum type

SHA256

### Image file checksum value

37745c82cf436126e5891589e8369f3c6b66b37b3b69d67697b27c9830c3bc65

### Image file download link (if applicable)

https://dl.google.com/chromeos-flex/images/latest.bin.zip

### Test environment

Dell Precision 5530

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!

**Comment by EnzoRedstone** [comment]
Okay, but the ChromeOS with Play Store is compatible ?
