### ISSUE TITLE
[Success Image Report]: ChromeOS Flex 123

### ISSUE THREAD

**Issue by Fede2782** [ventoy/Ventoy#2812]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.97

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

chromeos_15786.58.0_reven_recovery_stable-channel_mp-v3.bin

### Image file checksum type

SHA1

### Image file checksum value

5f364689463f095cda7602f496d545bbd39c91f2

### Image file download link (if applicable)

https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_15786.58.0_reven_recovery_stable-channel_mp-v3.bin.zip

### Test environment

Lenovo Ideapad 3 15IIL05

### More Details?

This image file booted successfully in Ventoy. Extract and .BIN file extension must be changed to .IMG

**Comment by ventoy** [comment]
Thanks!
