### ISSUE TITLE
[Success Image Report]: Ubuntu 22.04.4 Desktop, Kali 2024.1, Windows 10 English US

### ISSUE THREAD

**Issue by prusswan** [ventoy/Ventoy#2813]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.97

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

ubuntu-22.04.4-desktop-amd64.iso
Win10_22H2_English_x64v1.iso
kali-linux-2024.1-live-amd64.iso

### Image file checksum type

SHA256

### Image file checksum value

071d5a534c1a2d61d64c6599c47c992c778e08b054daecc2540d57929e4ab1fd
a6f470ca6d331eb353b815c043e327a347f594f37ff525f17764738fe812852e
48c9f9c24a7dbe68277e591e5f3af588714190cde8263af2f9b35e7ad252750c

### Image file download link (if applicable)

https://ubuntu.com/download/desktop/thank-you?version=22.04.4&architecture=amd64
https://www.microsoft.com/en-au/software-download/windows10ISO
https://www.kali.org/get-kali/#kali-installer-images

_No response_

### Test environment

Intel x86/64 (custom build)

### More Details?

These image file(s) booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
