### ISSUE TITLE
[Success Image Report]: ubuntu-24.04-desktop-amd64.iso 

### ISSUE THREAD

**Issue by AllenKu0** [ventoy/Ventoy#2820]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.79

### BIOS Mode

Legacy BIOS Mode

### Partition Style

GPT

### Image file name

ubuntu-24.04-desktop-amd64.iso 

### Image file checksum type

SHA256

### Image file checksum value

81fae9cc21e2b1e3a9a4526c7dad3131b668e346c580702235ad4d02645d9455

### Image file download link (if applicable)

https://releases.ubuntu.com/noble/ubuntu-24.04-desktop-amd64.iso

### Test environment

HP Z230

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!

**Comment by lanmmn** [comment]
This link shows 'The requested URL was not found on this server.' what's going on? and how can I continue downloading 24.04.iso
