### ISSUE TITLE
[Success Image Report]: ubuntu-24.04-live-server-amd64.iso

### ISSUE THREAD

**Issue by AllenKu0** [ventoy/Ventoy#2821]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.79

### BIOS Mode

Legacy BIOS Mode

### Partition Style

GPT

### Image file name

ubuntu-24.04-live-server-amd64.iso

### Image file checksum type

SHA256

### Image file checksum value

8762f7e74e4d64d72fceb5f70682e6b069932deedb4949c6975d0f0fe0a91be3

### Image file download link (if applicable)

https://releases.ubuntu.com/noble/ubuntu-24.04-live-server-amd64.iso

### Test environment

HP Z230

### More Details?

This image file booted successfully in Ventoy.

**Comment by ventoy** [comment]
Thanks!
