### ISSUE TITLE
[issue]: Arch Linux 2024.05.01 Won't boot

### ISSUE THREAD

**Issue by knoppmyth** [ventoy/Ventoy#2825]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.97

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

16GB

### Disk Manufacturer

MicroCenter

### Image file checksum (if applicable)

No.

### Image file download link (if applicable)

https://mirror.arizona.edu/archlinux/iso/2024.05.01/

### What happened?

Arch Linux 2024.05.01 won't boot with Ventoy. Errors with /ventoy/busybox/sh: can't access tty; job control turned off. See included screenshot. To create:
Install Ventoy on thumb drive.
Copy the Arch Linux 2024.05.01 to the Ventoy partition.
Boot off the USB.
Select the ISO.
Select normal mode.
Note the failure to boot.

I had no issue booting the ISO with QEMU or Virtualbox.

![Screenshot_20240502_224659](https://github.com/ventoy/Ventoy/assets/107227128/f3cc79d2-8b94-4e4d-a1c0-880e2e59197a)

**Comment by Ithde** [comment]
I also encountered the same problem，Then I tried using Rufus.
When using Rufus, I was prompted: 
~~~
“This mirror uses Syslinux 6.04/pre2-11-gbf6db5b4, and this program only contains the installation files for Syslinux 6.04/pre1. 
Since the new version of Syslinux is not compatible with other versions, and Rufus can't possibly include all of them, you need to download two additional files (ldlinux.sys and ldlinux.bss) from the Internet. The two extra files (ldlinux.sys and ldlinux.bss) need to be downloaded from the Internet.”
~~~
Then I can boot archiso normally. 
Of course I'm not sure if that's the reason, Since I've always used ventoy, I ran into this problem this time, so I tried other tools.

**Comment by steve6375** [comment]
Select grub2 mode

**Comment by slyfox1186** [comment]
I just wanted to chime in and say that this is _also_ a problem for me!

![Screenshot](https://github.com/ventoy/Ventoy/assets/37704019/22d1d2cc-e311-48f5-9700-d3945132bab4)

@Ithde You mentioned that there were two files you needed to source on the internet. If you know where they are found would you share that with the group? Also, if you know where the files should be located please share that too. Thanks for the great information!

**Comment by Ithde** [comment]
@slyfox1186 I'm sorry, I don't know how to download it either, I just switched to Rufus and reinstalled ventoy after installing Arch again.

**Comment by slyfox1186** [comment]
> @slyfox1186 I'm sorry, I don't know how to download it either, I just switched to Rufus and reinstalled ventoy after installing Arch again.

If you want to use Ventoy then when the main menu loads with all of your iso files listed, press control+r to enable grub 2. This allowed me to use the latest arch iso with no issues.

**Comment by duffydack** [comment]
I've checked the docs, is there any way to have specific ISO's use grub2 mode?  I already a ventoy.json to auto select an iso and disable secondary, be nice if there was another variable to tell it to use grub2 before booting.

**Comment by steve6375** [comment]
Yes, you can add a suffix to the filenames. Read the documents pages.

**Comment by ventoy** [comment]
@knoppmyth @ptr1337 @slyfox1186 @duffydack 
This CI release should have fixed this issue.
https://github.com/ventoy/Ventoy/actions/runs/9048876467
https://www.ventoy.net/en/doc_github_ci.html

**Comment by knoppmyth** [comment]
Functionality verified. Thanks for the quick response.

**Comment by knoppmyth** [comment]
Functionality verified. Thanks for the quick response.

**Comment by Dreuzz** [comment]
This error appeared on my laptop, and I can't turn off my laptop anymore? The power button doesn't work or anything else

**Comment by HanabishiRecca** [comment]
I want to point out that despite the original issue is fixed, the normal mode is still kinda broken.
Microcode is not being loaded in the normal mode. Which could lead to problems on certain CPUs.

**Comment by street-grease-coder** [comment]
If you boot system rescue something is an issue already. It's pretty bad that normal mode fails in that moment with default options. It made me just not want to use ventoy in the first place
