### ISSUE TITLE
[Success Image Report]: MemTest86 v10.0 Free

### ISSUE THREAD

**Issue by mausfra** [ventoy/Ventoy#2826]
### Official Website List

- [X] I have checked the list in official website and the image file is not listed there.

### Ventoy Version

1.0.97

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Image file name

memtest86-iso.iso

### Image file checksum type

SHA256

### Image file checksum value

719d26f95f9978e2d8b25258f5c0dc7e36f4a4b112e223683ec779ef06e6bd8e

### Image file download link (if applicable)

https://www.memtest86.com/tech_booting-cd-dvd.html

### Test environment

ASRock J4105-ITX

### More Details?

This image file booted successfully in Ventoy.
This image is current 10.0 Free version.
[Download MemTest86 v10.0 Free ISO image] https://www.memtest86.com/downloads/memtest86-iso.zip

**Comment by ventoy** [comment]
Thanks!
