### ISSUE TITLE
[issue]: Arch Linux 2024.05.01

### ISSUE THREAD

**Issue by f1qns** [ventoy/Ventoy#2837]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

Latest

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

931GB

### Image file checksum (if applicable)

Yes.

### What happened?

INIT NOT FOUND

**Comment by f1qns** [comment]
Those who use ventoy have this problem.

**Comment by ventoy** [comment]
Same as #2825

It has been fixed, just that the new version has not been released.
You can use the latest CI release.

**Comment by ventoy** [comment]
Fixed in latest 1.0.98
