### ISSUE TITLE
[issue]: Typo in Changelogs Ventoy v1.0.98: "Upadte EFI boot files." should be "Update EFI boot files."

### ISSUE THREAD

**Issue by wiensha** [ventoy/Ventoy#2842]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.98

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Image file checksum (if applicable)

None

### What happened?

Typo in Changelogs Ventoy v1.0.98: "Upadte EFI boot files." should be "Update EFI boot files."

**Comment by SteavenGamerYT** [comment]
Update ❌ 
Upadte ✅

**Comment by SteavenGamerYT** [comment]
Update :x: 
Upadte :white_check_mark:

**Comment by ventoy** [comment]
Fixed, thanks!
