### ISSUE TITLE
[issue]: Ventoy 1.0.98 problem with image boot on Honor MagickBook 

### ISSUE THREAD

**Issue by valpywall** [ventoy/Ventoy#2845]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.98

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

64GB

### Disk Manufacturer

Kingston DataTraveler, ADATA UC310

### Image file checksum (if applicable)

None

### What happened?

After update ventoy to latest version images on boot has bootloop and wan't loading. I'm use Honor MagickBook (NBLL-WXX9).

**Comment by ventoy** [comment]
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/9193630577
https://www.ventoy.net/en/doc_github_ci.html

**Comment by valpywall** [comment]
> Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/9193630577 https://www.ventoy.net/en/doc_github_ci.html

Yes, it works fine on this build. Is it safe to use until 1.0.99 is released, or should I go back to 1.0.97 instead?

**Comment by ventoy** [comment]
You can use this CI release, it's safe.
