### ISSUE TITLE
[BUG] Ventoy boot screen crashes sometimes !

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [ventoy/Ventoy#285]
### I also seen that windows somehow unhides 33MB ventoy partition which is bad

**Comment by candrapersada** [comment]
(showing like multiple screen teared) for Legacy BIOS

**Comment by BL4CKH47H4CK3R** [comment]
### Cluster Size >= 2048

This problem happens if you reformatted your device not following following cluster size (Solved)
