### ISSUE TITLE
U盘制作了启动盘之后无法被电视识别

### ISSUE THREAD

**Issue by yimouren** [ventoy/Ventoy#2853]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.97

### What about latest release

No. I didn't try the latest release.

### Try alternative boot mode

No. I didn't try these alternative boot modes.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

None

### What happened?

使用ventoy制作U盘之后,除了往U盘里拉几个镜像之外,还拉了几个APK文件打算到电视上安装,但是插上电视后只能识别到ufi分区,真正存放内容的盘识别不到,请问会有可能修复这种问题吗

**Comment by ventoy** [comment]
这个问题的原因是Ventoy安装之后，默认会把 U盘会被格式化为 exFAT 文件系统。
而电视里面的系统不支持 exFAT 文件系统，只支持 FAT 文件系统导致的。

你可以手动右键格式化，把U盘重新格式化FAT文件系统，这样电视就能识别了。
但是 FAT 文件系统有个限制，就是不能存放大于4GB的文件，而很多 ISO 文件都是超过 4GB的，这也是为什么 Ventoy 默认把 U盘格式化为 exFAT 文件系统的原因（exFAT文件系统没有这个限制）。

**Comment by yimouren** [comment]
好的明白
