### ISSUE TITLE
会考虑加入指定iso路径的功能么？

### ISSUE THREAD

**Issue by ashi876** [ventoy/Ventoy#286]
如果可以指定iso路径，或者扫描各硬盘分驱的第一层目录。可以大大加快pe或安装镜像的加载速度,
在u盘上安装几个g的系统或加载大一些的pe，那速度真的是非常慢的，很多人应该有习惯把镜像拷入硬盘安装或加载

**Comment by ventoy** [comment]
现在版本就可以指定 ISO 搜索路径，不过只能指定本U盘内的路径。参考 [https://www.ventoy.net/cn/plugin_control.html](https://www.ventoy.net/cn/plugin_control.html)

![image](https://user-images.githubusercontent.com/59477474/86531812-0ba84c80-bef7-11ea-8f9c-f7116a9132c7.png)

**Comment by ashi876** [comment]
> 
> 
> 现在版本就可以指定 ISO 搜索路径，不过只能指定本U盘内的路径。参考 https://www.ventoy.net/cn/plugin_control.html
> 
> ![image](https://user-images.githubusercontent.com/59477474/86531812-0ba84c80-bef7-11ea-8f9c-f7116a9132c7.png)

嗯，看来我表述问题有问题~
其实就是想指定硬盘路径，指定u盘路径的那个我有看readme. 毕竟指定u盘路径意义不大，并不能提速~
但愿以后会有:-)

**Comment by a1ive** [comment]
> > 现在版本就可以指定 ISO 搜索路径，不过只能指定本U盘内的路径。参考 https://www.ventoy.net/cn/plugin_control.html
> > ![image](https://user-images.githubusercontent.com/59477474/86531812-0ba84c80-bef7-11ea-8f9c-f7116a9132c7.png)
> 
> 嗯，看来我表述问题有问题~
> 其实就是想指定硬盘路径，指定u盘路径的那个我有看readme. 毕竟指定u盘路径意义不大，并不能提速~
> 但愿以后会有:-)

目前 Ventoy 不能启动硬盘上的 ISO。

**Comment by ventoy** [comment]
@ashi876  那我理解有误。 Ventoy从一开始就是作为一个整体方案设计的，所以目前不能启动非本盘上的ISO文件。
在远期的2.X版本有规划，但是估计要比较长时间以后。

**Comment by ashi876** [comment]
期待中。。。 感谢答复
