### ISSUE TITLE
[issue]: 直接安装1.0.98后无法启动

### ISSUE THREAD

**Issue by lsxuan12138** [ventoy/Ventoy#2865]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.98

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

128GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

None

### What happened?

首先，大致介绍以下测试的环境，机器是华为的matebook14 2020版，具体信息如下，
<img width="424" alt="image" src="https://github.com/ventoy/Ventoy/assets/74349318/3f47bd0a-7580-4a3b-813e-3af1b70d605e">
**直接安装有问题**
使用闪迪u盘，当直接在u盘上安装1.0.98（将u盘上所有分区删除后安装或直接安装）后，进入boot manger后显示如图：
![IMG_20240604_235638](https://github.com/ventoy/Ventoy/assets/74349318/9e8b7a81-e79c-4526-a647-6034d00919df)
其中Windows Boot Manager(...)为硬盘上windows的引导，而Linpus lite (...)为u盘上的引导（大概是ventoy？），直接启动失败：
![IMG_20240605_000830_edit_80077319337259](https://github.com/ventoy/Ventoy/assets/74349318/5d6b2acf-c39d-41a1-916a-c8b3f6699189)
但是经过测试在vmware（17.5.x典型，win10 x64，加一个物理u盘虚拟的硬盘）中却可以正常启动。
![image](https://github.com/ventoy/Ventoy/assets/74349318/d5b543e5-5e71-40b4-8037-1bbedf8d0014)
**从低版本升级也有问题**
然后尝试使用1.0.96及1.0.97版本，直接安装后均无问题，显示EFI USB Device(...)且都可以正常启动，
![IMG_20240604_233921](https://github.com/ventoy/Ventoy/assets/74349318/5842ca35-c90c-433a-8178-44e502ed6b66)
但是在从1.0.97升级到1.0.98后，启动界面显示EFI USB Device和Linpus lite，同样的，前者可以正常启动而后者会启动失败，感觉这个问题比较神奇，且之前没有遇到过，故此反馈
![IMG_20240604_235358](https://github.com/ventoy/Ventoy/assets/74349318/e70795f3-d161-468f-b4d9-1b76637bf60d)

**Comment by steve6375** [comment]
Is there any difference between 

1. Power Off - Power On - boot menu
2. Power off - remove power and battery - press power button to discharge device - connect AC or battery - power on - boot menu
3. Reset/Restart - boot menu

also any difference between MBR Ventoy USB and GPT Ventoy ISB ?

**Comment by lsxuan12138** [comment]
> Is there any difference between
> 
> 1. Power Off - Power On - boot menu
> 2. Power off - remove power and battery - press power button to discharge device - connect AC or battery - power on - boot menu
> 3. Reset/Restart - boot menu
> 
> also any difference between MBR Ventoy USB and GPT Ventoy ISB ?

Thanks for your reply, and I will test the difference tomorrow.

**Comment by lsxuan12138** [comment]
> Is there any difference between
> 
> 1. Power Off - Power On - boot menu
> 2. Power off - remove power and battery - press power button to discharge device - connect AC or battery - power on - boot menu
> 3. Reset/Restart - boot menu
> 
> also any difference between MBR Ventoy USB and GPT Ventoy ISB ?
**I only tested the situation of direct installation**
In fact, my computer is a laptop and removing the battery is quite difficult, so I didn't try it.
And,  I tested the difference between 1 and 3, and the result was that neither could boot normally.
In addition, I tested the difference between GPT and MBR, and the results of MBR have already been mentioned above. Surprisingly, when using GPT, although the boot manager still displays **Linux lite (...)**, it can boot successfully.

**Comment by ventoy** [comment]
试试这个CI版本：
https://github.com/ventoy/Ventoy/actions/runs/9193630577
https://ventoy.net/cn/doc_github_ci.html

**Comment by lsxuan12138** [comment]
> 试试这个CI版本： https://github.com/ventoy/Ventoy/actions/runs/9193630577 https://ventoy.net/cn/doc_github_ci.html

这个版本可以了，GPT和MBR测试都正常了

**Comment by ventoy** [comment]
Fixed in 1.0.99
