### ISSUE TITLE
[issue]: 找不到initrd.img

### ISSUE THREAD

**Issue by wibin86** [ventoy/Ventoy#2879]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.99

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Image file checksum (if applicable)

None

### What happened?

在申威服务器（国产芯片sw3231）上使用u盘ventoy
提示错误如下：
Boot From USB
Loading the file ‘initrd.img ’ ......ERROR !!!
Can not find Kernel File: \boot\initrd.img
Press C/c to try  next boot
请问这种情况怎么解决

**Comment by ventoy** [comment]
Ventoy 不支持申威构架的机器，后续也没有计划支持。
