### ISSUE TITLE
WIM made with LZX max compression (inside ISO) will not boot

### ISSUE THREAD

**Issue by 44vince44** [ventoy/Ventoy#288]
Hello everyone ! Hello Ventoy!

This is a problem with the compression used when packing WIM.
Usually, compression used in a WIM file is XPRESS. 

- If I compress a project to Wim with XPRESS standard compression, create the iso, put the iso in usb key formatted with Ventoy, it works.

- If I compress the SAME PROJECT to wim, using now LZX max compression, create the iso and boot with Ventoy key, the process of "Loading Files..." will begin, and in the middle of it it stops with the error that the USB key may have been removed.
That same ISO boots perfectly on a virtual machine.

So maybe a bug in Ventoy? Tried only UEFI.

**Comment by ventoy** [comment]
In theory, lzx compression with boot.wim will not affect the boot progress. 
Only that Ventoy can't inject utility into the wim file and the source media may not found after boot.
But it should boot into the WinPE enviroment. 
Can you give a such ISO file for test?

**Comment by 44vince44** [comment]
it's a very big iso i made with winbuilder2 (customized project using as base Win10XPE), The ISO is 2GB, or 1.7GB when using LZX max compression. I'm afraid I have no upload speed that allow sharing this (I live in a country where we're still using metered connections with upload speed of 512kbps).
Now the error happens at about 60% of the "Loading Files..."  progress. Which could mean that with a smaller project, the error might not happen. I'd like to help. Is there anything I can do (else than sending "big" amounts of data) ?

**Comment by ventoy** [comment]
Please try this:
when in Ventoy's boot menu, press  Ctrl+i  then continue to select the iso file and boot.

**Comment by 44vince44** [comment]
I tried: press Ctrl+i, it displayed "Compatibility Mode", I loaded the lzx-max compressed ISO: **IT WORKED**!

I restarted without Ctrl+i just to take a photo of the message error, here it is (it happens near 75% of the loading)
![IMG_20200707_173312](https://user-images.githubusercontent.com/17828567/86797359-3ec61980-c078-11ea-8f29-2ee89cfe782c.jpg)

**Comment by ventoy** [comment]
I checked the code again. For standard Windows ISO from MSDN, boot.wim is in LZX compression format. 
Ventoy only support LZX,   XPRESS and LZMS are not supported now.

Please give the hex dump of the wim file head.  like bellows:  

```
00000000  4d 53 57 49 4d 00 00 00  d0 00 00 00 00 0d 01 00  |MSWIM...........|
00000010  82 00 04 00 00 80 00 00  30 c5 87 4e 9a e6 7f 4c  |........0..N...L|
00000020  91 c1 36 c8 49 0b e4 26  01 00 01 00 02 00 00 00  |..6.I..&........|
```

**Comment by 44vince44** [comment]
Hi Ventoy, thank you for taking care of the issue.

Here is the command that created the high compression wim file, that will work only in Compatible Mode:
wimlib-imagex.exe capture #$q%GTarget%#$q #$q%GISO%\sources\boot.wim#$q #$q%ImageName%#$q #$q%ImageName%#$q --boot --flags=9 --compress=LZX --verbose

here is the header of the resulting wim:


```
00000000  4D 53 57 49 4D 00 00 00 D0 00 00 00 00 0D 01 00  MSWIM...Ð.......
00000010  82 00 04 00 00 80 00 00 01 48 E2 68 D1 AB 0E 19  ‚....€...HâhÑ«..
00000020  36 E6 FC FA 05 85 2D 5B 01 00 01 00 01 00 00 00  6æüú.…-[........
00000030  3E AA 0D 00 00 00 00 02 3E 01 2F 70 00 00 00 00  >ª......>./p....
00000040  3E AA 0D 00 00 00 00 00 1E 08 00 00 00 00 00 02  >ª..............
00000050  7C AB 3C 70 00 00 00 00 1E 08 00 00 00 00 00 00  |«<p............
00000060  20 18 0E 00 00 00 00 06 1E E9 20 70 00 00 00 00   ........é p....
00000070  00 8C 3E 00 00 00 00 00 01 00 00 00 00 00 00 00  .Œ>.............
00000080  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
00000090  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
000000A0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
000000B0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
000000C0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
000000D0  0E 20 00 A2 00 00 03 00 40 23 34 00 C8 0C 92 3B  . .¢....@#4.È.’;
000000E0  4A E5 C7 04 C0 30 31 21 30 4D 70 82 AB DE BD 41  JåÇ.À01!0Mp‚«Þ½A
000000F0  B7 D4 61 85 FF 09 FA FF 00 04 00 00 09 00 00 54  ·Ôa…ÿ.úÿ.......T
00000100  0C 01 96 0B B4 EB 12 62 F1 43 FB 72 DF 82 D1 DF  ..–.´ë.bñCûrß‚Ñß
00000110  00 00 00 00 00 00 00 00 10 22 C2 DE F7 7D 23 DF  ........."ÂÞ÷}#ß
00000120  34 9D 52 55 1E 88 D7 2A AD 52 AF 37 C9 17 63 6D  4.RU.ˆ×*.R¯7É.cm
00000130  5F D5 C1 B8 B1 95 11 74 5F C6 76 4F FF DD 01 1C  _ÕÁ¸±•.t_ÆvOÿÝ..
00000140  F1 2F B6 27 23 10 1B B1 48 CE CC B1 1A 7F 80 72  ñ/¶'#..±HÎÌ±..€r
00000150  92 F5 C7 31 06 E7 1E 18 CB 42 34 07 93 12 A5 8C  ’õÇ1.ç..ËB4.“.¥Œ
```

**Comment by 44vince44** [comment]
> Ventoy only support LZX, XPRESS and LZMS are not supported now.
That's strange because when using EXPRESS it works:

wimlib-imagex.exe capture #$q%GTarget%#$q #$q%GISO%\sources\boot.wim#$q #$q%ImageName%#$q #$q%ImageName%#$q --boot --flags=9 --compress=XPRESS --verbose

here is the verbose:
Setting the FLAGS property of image 1 to "9".
Setting the DESCRIPTION property of image 1 to "Win10XPE_x64".
Using XPRESS compression with 8 threads
Archiving file data: 3219 MiB of 4571 MiB (70%) done
