### ISSUE TITLE
winiso在Dell studio15-1558上无法启动

### ISSUE THREAD

**Issue by llllllllqq** [ventoy/Ventoy#29]
古董笔记本工作站，i7 q720，4gram，usb2.0，仅bios，可以启动debian、wepe但无法进入win7/win10的原版iso，左上角光标一直闪，u盘无读写。
同时，partedmagic0223版用bios启动，在此笔记本和华硕p8z77v上均出现kernelpanic，日志图片已通过邮箱联系您。

**Comment by ventoy** [comment]
最新版本什么情况？ @llllllllqq
