### ISSUE TITLE
128GB优盘，ventoy 引导后到了 Grub 命令行，该怎么办？

### ISSUE THREAD

**Issue by joomlagate** [ventoy/Ventoy#291]
我用了一个杂牌的 128GB 优盘，使用 ventoy v1.0.14 版本安装好，给优盘上复制了多个 ISO 启动盘文件。

然后我在另一台台式机电脑上测试，优盘引导后没有出现 ISO 选择菜单，而是出现了 Grub 命令行，如下图所示：

![gr](https://user-images.githubusercontent.com/1249063/86992117-57971200-c1d3-11ea-8c14-8bf6d3f94b16.jpg)

屏幕上最终显示的是：

`grub>_`

请问为何没有引导进入 ISO 选择菜单呢？

屏幕上显示这个 grub 命令行之后，该怎么操作呢？

谢谢！

**Comment by a1ive** [comment]
https://www.ventoy.net/cn/doc_legacy_limit.html

**Comment by ventoy** [comment]
在这里执行个  ls  -l  命令看看。
如果是Legacy BIOS模式的话，可以参考上面 @a1ive  发的那个链接中的说明。

**Comment by joomlagate** [comment]
可是我这个优盘是 128GB 容量，还没达到 137GB 呢，按理不应该出现那种问题。

我执行 ls -l 命令后结果如下：

![gr](https://user-images.githubusercontent.com/1249063/87021431-cc843f00-c207-11ea-81ba-5ff4b4c36da1.jpg)

请教：是不是我必须将 ventoy 这个分区重新手工格式化，然后再复制各种 ISO 进去？

顺便说说这个电脑，看看有没有什么提示：我在 BIOS 里面如果选择 UEFI 方式引导，根本不理会优盘，直接进入台式机自带的 Windows 10 了；必须在 BIOS 里面选择 Legacy 模式引导，才能从优盘引导，但是引导之后显示的就是 grub 命令行。

回头我试试手工格式化的方法。谢谢帮助！

**Comment by ventoy** [comment]
我这网络有问题，看不到图片。

不需要重新格式化。直接拷贝ISO进去即可。
如果你有另外的小点的U盘，可以对比测试下。如果小的U盘，比如32G 64G的没问题，128的有问题，那十有八九就是这个问题导致的，137GB只是个参考值，不同的BIOS可能具体的限制值不一样。
另外，最新的1.0.14版本在安装Ventoy时可以设置在U盘最后保留一段空间，你也可以利用这个功能测试一下，比如你设置保留64GB，这样Ventoy就只会使用前面64GB的空间，这样应该就不会触发BIOS的访问限制问题了，然后看看是不是OK。

UEFI的话你要确认下BIOS里面安全启动有没有关闭。

**Comment by maiconjs** [comment]
I just went through that problem now. I installed Ventoy on an external 1TB disk and came across this message. When I partied in 127gib, it worked. It is interesting for the developer to implement a message and a script that detects devices larger than 128gib and provide a suggestion to partition the disk before proceeding with the creation.
