### ISSUE TITLE
使用最新版Ventoy创建引导盘时总是失败，U盘无法删除分区

### ISSUE THREAD

**Issue by pengpenggeng** [ventoy/Ventoy#292]
连续尝试使用两块usb2.0的 u盘进行尝试，均失败
![image](https://user-images.githubusercontent.com/51321470/87005902-59240280-c1f2-11ea-8cf4-8a8a1cff67e7.png)
log如下：
[log.txt](https://github.com/ventoy/Ventoy/files/4894969/log.txt)

**Comment by ventoy** [comment]
Ventoy2Disk.exe在Windows下需要直接操作硬件，往U盘中写入数据，这个过程很容易受到其他程序的影响从而导致安装失败。 比如杀毒软件、系统主动防御等等，不同的系统情况各异。
这里给出一些常用的建议（有些人按照这样操作之后就OK了）
1. 临时关闭杀毒软件
2. 临时关闭系统主动防御功能
3. 试先使用DiskGenius之类的工具把U盘分区全部删掉、把启动模式修改为HDD。

**Comment by Disk2019** [comment]
@ventoy now its a complete usb boot tool . thanks a lot for creating such a great tool.
GPT disk structure support is one of the fabulous option added to your tool .

**Comment by ventoy** [comment]
Ventoy2Disk.exe在Windows下需要直接操作硬件，往U盘中写入数据，这个过程很容易受到其他程序的影响从而导致安装失败。 比如杀毒软件、系统主动防御等等，不同的系统情况各异。
这里给出一些常用的建议（有些人按照这样操作之后就OK了）
1. 临时关闭杀毒软件
2. 临时关闭系统主动防御功能
3. 试先使用DiskGenius之类的工具把U盘分区全部删掉、把启动模式修改为HDD。

如果各种尝试之后还是一直失败，建议使用 Ventoy LiveCD的方式安装，成功率有保证，具体参考 [说明](https://www.ventoy.net/cn/doc_livecd.html)
