### ISSUE TITLE
[issue]: Cannot boot latest Windows 10 ISO

### ISSUE THREAD

**Issue by umnikos** [ventoy/Ventoy#2944]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.99

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

32GB

### Disk Manufacturer

Verbatim

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://www.microsoft.com/en-us/software-download/windows10ISO

### What happened?

In normal boot mode the windows logo shows up for about 1/10th of a second then the screen goes black and only a blinking cursor remains.

In wimboot mode the error `FATAL: No bootmgr.exe` appears shortly after selecting the option.

I have tested this with two separate USBs on two separate laptops, both UEFI without secure boot.

The specific windows ISO I have been attempting to boot is `Win10_22H2_EnglishInternational_x64v1.iso` (latest one from microsoft's website) with a sha256 hash of `edc53c5c5fe6926dea23fc3e884fbcf78cc2b9e76364be968f806fc6d42b59d2`

**Comment by steve6375** [comment]
P.S. Is it possible that a different monitor/display output is being used? Can you connect another display?
Try using text mode F7 in Ventoy?

**Comment by umnikos** [comment]
Turns out I had made two mistakes while testing this:

1. The laptop is actually BIOS (ventoy version says 1.0.99 BIOS)
2.  I had not been patient enough. After roughly 45 seconds of staring at the blinking cursor it suddenly boots into the installer just fine
