### ISSUE TITLE
[issue]: I can't get it to boot from Ventoy USB stick

### ISSUE THREAD

**Issue by katastrophe92** [ventoy/Ventoy#2957]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.99

### What about latest release

No. I didn't try the latest release.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64Gb

### Disk Manufacturer

Philips

### Image file checksum (if applicable)

None

### What happened?

Hello Ventoy community!

After installing Ventoy I copied over some ISO's and give it a try. It looked weird already in the BIOS how it was named the USB stick after I changed the BOOT order it restarten and got that error message from image 2. I don't know what's wrong.
Partition style GPT
File system exFAT
![2520240829_193959](https://github.com/user-attachments/assets/75c93e51-3e39-43e3-8332-fa39c40b8ded)
![20240829k_194104](https://github.com/user-attachments/assets/68588b48-f9a9-4601-ae8d-70cb79cd7627)

**Comment by TeamLinux01** [comment]
There was a Windows update that applied an updated SecureBoot Advanced Targeting policy, which will blocked the version of GRUB that Ventoy ships with. For the time being, either disable SecureBoot or roll back the SBAT policy for the machine.

Hopefully Ventoy updates and uses a newer version of GRUB and the rest of the stack that isn't considered vulnerable.

**Comment by katastrophe92** [comment]
> roll back the SBAT policy for the machine.

Hey, thanks for the reply. How to do that SBAT policy thingy? Thanks again
