### ISSUE TITLE
Win PE create with mdt not working since ventoy 1.0.13

### ISSUE THREAD

**Issue by admmozilla78** [ventoy/Ventoy#298]
I Have a problem to boot with  win Pe create from MDT since ventoy 1.0.13 ( I Have tested with the 1.0.15 same issue; 1.0.12 is OK)  , the blue screen is IO1_initalisation_failed . I cannot find specific explanation( about bootable usb key)  for this blue screen on the net.
About the win pe i've tested with dell driver pack and whitheout but it didn't change anything.

**Comment by ventoy** [comment]
Can you give such an ISO file for test?

**Comment by admmozilla78** [comment]
Yes, a juste need an e mail adress to share a one drive link

**Comment by ventoy** [comment]
admin@ventoy.net

**Comment by FingerlessGlov3s** [comment]
@admmozilla78 

Is you MDT winpe created from SCCM?

I've been trying to get SCCM task sequence working, I can boot in the WINPE but it can't then find any of the SMS media. To get this far I had to the WIM plugin.

I tried reformatting the first partition as FAT32, copied over the content from the ISO to the root of the partition but no luck.

This same thing your trying to do?

I'm kinda guessing Ventoy can't support this boot thingy...

**Comment by admmozilla78** [comment]
HI ,

we dont use SCCM but just MDT installed on a computer. The iso is boooting but I have blue screen( IO error ) so it's a bit different.



________________________________
De : FingerlessGloves <notifications@github.com>
Envoyé : mardi 27 octobre 2020 21:24
À : ventoy/Ventoy <Ventoy@noreply.github.com>
Cc : admmozilla78 <gobelkie@hotmail.com>; Mention <mention@noreply.github.com>
Objet : Re: [ventoy/Ventoy] Win PE create with mdt not working since ventoy 1.0.13 (#298)


@admmozilla78<https://github.com/admmozilla78>

Is you MDT winpe created from SCCM?

I've been trying to get SCCM task sequence working, I can boot in the WINPE but it can't then find any of the SMS media. To get this far I had to the WIM plugin.

I tried reformatting the first partition as FAT32, copied over the content from the ISO to the root of the partition but no luck.

This same thing your trying to do?

I'm kinda guessing Ventoy can't support this boot thingy...
