### ISSUE TITLE
Secure Boot Support setting is not remembered per-device when updating

### ISSUE THREAD

**Issue by ltGuillaume** [ventoy/Ventoy#299]
Currently, the "Secure Boot Support" setting is saved locally in the .ini-file.

- I don't have Ventoy permanently on disk, I only download it temporarily when a new version is available. As such, the setting "Secure Boot Support" will not be remembered.
- One might want to update multiple devices, e.g. one where this setting was enabled, and others where it wasn't. The setting should then be toggled manually each time.

1. Is the "Secure Boot Support" enabled/disabled according to the setting upon updating?
2. If so, wouldn't it be best for VentoyDisk to read the current state of this setting from the inserted device with Ventoy installed and enable/disable the setting accordingly before updating? If any other settings like this will be added, it would be nice to have this mechanism in place anyway.

**Comment by ventoy** [comment]
What you said make sense. But we should also consider this case:
"Currently it is disabled in the USB but I want to enable it and don't want to reinstall ventoy. "

**Comment by renatofrota** [comment]
> What you said make sense. But we should also consider this case:
> "Currently it is disabled in the USB but I want to enable it and don't want to reinstall ventoy. "

How this is done currently in Ventoy2Disk.exe? Just by selecting the device and clicking menu `Option > Secure Boot support` is the Secure Boot support supposed to be enabled (with no need to update/reinstall Ventoy in device)?

(note: I am now the issue OP, just got curious, because I have only tried Ventoy in Linux so far)

**Comment by ltGuillaume** [comment]
If updating Ventoy with Secure Boot enabled on a device that was installed without Secure Boot enabled change the status from disabled to enabled, then I don't see the problem: user selects device to update > Secure Boot setting changes to device's current state > user changes the setting and updates Ventoy > Ventoy is updated and the device's Secure Boot setting is saved on the device.

**Comment by ltGuillaume** [comment]
According to #630, this is fixed for Linux. Is it also fixed for Windows?
