### ISSUE TITLE
Fedora OK in 7, but FAIL in 8b2

### ISSUE THREAD

**Issue by wimbrts** [ventoy/Ventoy#30]
[Fedora](https://getfedora.org/nl/workstation/download/) is booting OK in v1.0.07 but FAILS to boot for Ventoy v1.0.08 Beta2 (as tested in BIOS and UEFI Secure mode

**Comment by ventoy** [comment]
I fixed it in 1.0.08, you can make a try.

**Comment by wimbrts** [comment]
Fix is OK, Fedora 1.6 is booting now in BIOS and in UEFI Secure mode 👍
