### ISSUE TITLE
[issue]: ventoy.net certificate expired

### ISSUE THREAD

**Issue by es20490446e** [ventoy/Ventoy#3007]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

None

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

None

### Image file checksum (if applicable)

None

### What happened?

![1](https://github.com/user-attachments/assets/dc6db68c-3d0c-4d26-8914-39bc80611a0f)

**Comment by DX37** [comment]
Seems like HTTPS certificate is expired yesterday, on 20 October.

**Comment by Korkman** [comment]
Yup. @es20490446e maybe change the ticket title to "ventoy.net https certificate expired" for better visibility

**Comment by MestreLion** [comment]
Fixed, new certificate was issued on 2024-10-22

**Comment by cirrusflyer** [comment]
Expired again today.

**Comment by DX37** [comment]
> Expired again today.

Prolonged to one year, I presume.
