### ISSUE TITLE
[issue]: Updating from 1.0.99-2 -> 1.0.99-3 fails on aur/ventoy on Arch

### ISSUE THREAD

**Issue by chrisfederico1** [ventoy/Ventoy#3023]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.99-2

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32

### Image file checksum (if applicable)

None

### What happened?

Not sure if this is a AUR issue or what but I'm getting this error when updating ventoy on arch .ERROR: One or more files did not pass the validity check! 

The file that is failing the test is 
ventoy-grub-fix-build-with-binutils-2.36.patch ... FAILED

Not sure if anyone else is having this issue .

**Comment by FabioLolix** [comment]
Hello, you nees to report on AUR since it is AUR specific

**Comment by FabioLolix** [comment]
This was already reported yesterday https://aur.archlinux.org/packages/ventoy#comment-996958

Run `updpkgsums` to get the correct hash check

**Comment by chrisfederico1** [comment]
Thanks sorry if this was the wrong spot . I will check the aur ventoy package ...
