### ISSUE TITLE
Please add support for the Vietnamese language (I have translated it)

### ISSUE THREAD

**Issue by hoangdiemtinh** [ventoy/Ventoy#303]
[Language-Vietnamese (Tiếng Việt)]
FontFamily='Tahoma'
FontSize=14
Author=Nguyen Quoc Hoang - cuumay.com

STR_ERROR='Lỗi'
STR_WARNING='Cảnh báo'
STR_INFO='Thông tin'
STR_INCORRECT_DIR='Vui lòng chạy Ventoy2Disk tại đúng thư mục của nó !'
STR_INCORRECT_TREE_DIR='Không được chạy Ventoy2Disk ở đây, vui lòng tải gói cài đặt đã phát hành và chạy ở đó.'
STR_DEVICE='Thiết bị'
STR_LOCAL_VER='Phiên bản Ventoy'
STR_DISK_VER='Phiên bản Ventoy ở thiết bị'
STR_STATUS='Trạng thái - SẴN SÀNG'
STR_INSTALL='Cài đặt'
STR_UPDATE='Cập nhật'
STR_UPDATE_TIP='Việc cập nhật Ventoy là an toàn, các tập tin ISO của bạn sẽ được giữ nguyên trạng.#@ Bạn thật sự muốn tiếp tục ?.'
STR_INSTALL_TIP='Thiết bị sẽ được định dạng và do đó TẤT CẢ DỮ LIỆU trên thiết bị sẽ bị mất.#@ Bạn thật sự muốn tiếp tục ?.'
STR_INSTALL_TIP2='Thiết bị sẽ được định dạng và do đó TẤT CẢ DỮ LIỆU trên thiết bị sẽ bị mất.#@ Bạn thật sự muốn tiếp tục ?. (Xác nhận lần hai)'
STR_INSTALL_SUCCESS='Chúc mừng bạn !.#@ Thiết bị đã được cài Ventoy thành công.'
STR_INSTALL_FAILED='Đã xảy ra lỗi trong quá trình cài đặt Ventoy. Bạn có thể rút thiết bị ra và thử lại. Xem chi tiết ở tệp log.txt.'
STR_UPDATE_SUCCESS='Chúc mừng bạn !.#@ Thiết bị đã được cập nhật Ventoy thành công.'
STR_UPDATE_FAILED='Đã xảy ra lỗi trong quá trình cập nhật Ventoy. Bạn có thể rút thiết bị ra và thử lại. Xem chi tiết ở tệp log.txt.'
STR_WAIT_PROCESS='Một luồng xử lý đang chạy, vui lòng chờ...'
STR_MENU_OPTION='Tùy chọn'
STR_MENU_SECURE_BOOT='Bật hỗ trợ Secure Boot'
STR_MENU_PART_CFG='Cấu hình phân vùng'
STR_BTN_OK='OK'
STR_BTN_CANCEL='Hủy'
STR_PRESERVE_SPACE='Giữ lại phần dung lượng ở dưới cùng của thiết bị'
STR_SPACE_VAL_INVALID='Giá trị dung lượng giữ lại không hợp lệ.'
STR_MENU_CLEAR='Gỡ bỏ Ventoy'
STR_CLEAR_SUCCESS='Chúc mừng bạn !.#@ Thiết bị đã được gỡ bỏ Ventoy thành công.'
STR_CLEAR_FAILED='Đã xảy ra lỗi trong quá trình gỡ bỏ Ventoy. Bạn có thể rút thiết bị ra và thử lại. Xem chi tiết ở tệp log.txt.'
STR_MENU_PART_STYLE='Kiểu phân vùng'
STR_DISK_2TB_MBR_ERROR='Thiết bị có dung lượng lớn hơn 2TB. Vui lòng chọn Kiểu phân vùng là GPT.'

**Comment by hoangdiemtinh** [comment]
@ventoy How to submit a translated language to you ?.

**Comment by ventoy** [comment]
I have just commited it.
