### ISSUE TITLE
[issue]: GParted live 1.6.0-10 - Ventoy 1.0.99 - Problem loading X.509 certificate

### ISSUE THREAD

**Issue by Hanatarou** [ventoy/Ventoy#3034]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.99

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

16GB

### Disk Manufacturer

Kingston

### Image file checksum (if applicable)

Yes.

### Image file download link (if applicable)

https://sinalbr.dl.sourceforge.net/project/gparted/gparted-live-stable/1.6.0-10/gparted-live-1.6.0-10-amd64.iso?viasf=1

### What happened?

My computer has a Gigabyte AERO G Z790 motherboard with BIOS version F12 (latest). My operating system is Windows 11 24H2 fully updated. My boot configuration is CSM disabled, UEFI x64 with secure boot enabled.

I used Ventoy version 1.0.99 to create a bootable USB drive with the GParted ISO version 1.6.0-10. The USB drive has an MBR partition style and NTFS file system. When I attempt to boot in normal mode, the following error message is displayed.

![20241120_213717](https://github.com/user-attachments/assets/12bf1458-9791-46f6-9943-2f0f85b06286)

After this, I am forced to reboot the computer, and the following error message is displayed.

![20241120_141940](https://github.com/user-attachments/assets/d4abe552-c52f-4847-b882-595d62157199)

Afterwards, I can no longer boot from the USB drive, regardless of what option I change in the motherboard's secure boot settings. I tried everything, including "Reset to setup mode," which clears the NVRAM security keys.

I had to clear the CMOS, which I could only do by updating the BIOS to the same version, which, as far as I know, clears the CMOS.

Here are some screenshots of my BIOS options related to secure boot.

![20241120_142541](https://github.com/user-attachments/assets/d6f7e801-37ff-4c03-b437-8f9b19e06c19)

![20241120_142548](https://github.com/user-attachments/assets/2652b973-9804-42f9-ac55-4b5bd7d9d577)

In the end, I gave up and disabled the secure boot option. Can anyone help me diagnose the problem and get secure boot working again?

**Comment by Hanatarou** [comment]
Hello everyone,

After additional research and testing, I downloaded and updated my Ventoy version to the Ventoy-CI version from the following link:

https://github.com/ventoy/Ventoy/actions/runs/11868854580

This version fixed the bug "Update to latest Shim (Fix verifying shim SBAT data failed) #2947."

After this update, the loop error "...shim SBAT data failed..." stopped, and I can now boot normally from the USB drive. However, the error "...Problem loading X.509..." from the GParted image persists. I even tested a more recent version of the GParted image, "gparted-live-1.6.0-12-amd64.iso", but the error remains.

The problem seems to lie with the GParted image; perhaps the developer needs to update its shim as well.

Can anyone advise if my conclusion is correct?

Is there a way to manually update the shim for the GParted image? If so, could someone guide me on how to test it myself?

Best regards,

Hanatoru

**Comment by axelgomez** [comment]
Hello @Hanatarou,
I had the same issue "...shim SBAT data failed..."  but after I installed VentoyCI the problem dissapeared (also I had to add Key to my whitelist keys for secure booting) but I can boot Gparted 1.6.0-10-amd64.iso without any problem.
So, I wasn't able to replicate the problem you mention because it works fine for me.

I am using Lenovo Thinkpad L15 Gen1 with BIOS version R17ET41W 1.24 (it is not the latest version available but I don't think if that could be a problem).

Best regards,
Axel

**Comment by Hanatarou** [comment]
Thank you for the feedback, @axelgomez . I contacted Steven Shiau regarding GParted. After some tests and conversations with him, we understood that the problem lies in the Linux kernel used as the base for GParted.

Apparently, this Linux kernel does not support my hardware. Therefore, I will have to wait for a kernel update to support my hardware.

I will change the status of this post to closed since the issue is not with Ventoy, but with the base Linux kernel of GParted.

Best regards,

Hanatoru
