### ISSUE TITLE
[A very niche issue]: 使用音量键切换启动项时出现错误

### ISSUE THREAD

**Issue by XZH2024** [ventoy/Ventoy#3036]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.99

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### Try alternative boot mode

Yes. I have tried them, but the bug still exist.

### BIOS Mode

Both

### Partition Style

MBR

### Disk Capacity

128GB

### Disk Manufacturer

SanDisk

### Image file checksum (if applicable)

None

### What happened?

事情是这样的：
我尝试在我的手机上启动Ventoy，虽然成功启动了，但是当我使用音量键切换启动项的时候却出现了错误，如图
更奇怪的是经过我的多次尝试（比如拔下U盘换成键盘/鼠标，或者使用USB HUB来同时连接键盘和鼠标）后，有一次启动突然又可以使用音量键来选择，用电源键来确认了，但是后来都没成功复现过

图片和视频如下：
![QQ图片20241123200259](https://github.com/user-attachments/assets/b6282b59-955c-40d2-90ca-67039f65e15f)
[Video.zip](https://github.com/user-attachments/files/17879691/Video.zip)

视频0：10处出现的界面的项目地址：github.com/BigfootACA/simple-init

**Comment by XZH2024** [comment]
在simple init内置的程序中也遇到了这个报错，可能不是ventoy的问题

**Comment by a1ive** [comment]
https://github.com/ventoy/Ventoy/pull/2488

应该是你用的 UEFI 固件 USB 驱动的某些代码访问了0地址导致的。
