### ISSUE TITLE
The Window title of Partition Configuration form is not translate to my language

### ISSUE THREAD

**Issue by hoangdiemtinh** [ventoy/Ventoy#305]
The Window title of Partition Configuration form is not translate to my language.

And, Font of the Partition Configuration form is not show correct. I set to Tahoma (for Vietnamese), but not work.

See image:

<img src="https://i.postimg.cc/y6nXL62P/ventoy.png">

https://i.postimg.cc/y6nXL62P/ventoy.png

Please fix.

**Comment by ventoy** [comment]
Configuration title was not multilingual and it's not a big problem as the main title `Ventoy2Disk`
I will check and fix the font issue.
