### ISSUE TITLE
Pls update language.ini for turkish user

### ISSUE THREAD

**Issue by crasadure** [ventoy/Ventoy#307]
Language-Turkish (Türkçe)]
FontFamily='Courier New'
FontSize=16
Author=Erhan Kültür/crasadure

STR_ERROR='Hata'
STR_WARNING='Uyarı'
STR_INFO='Bilgi'
STR_INCORRECT_DIR='Lütfen doğru dizin altında çalıştırın!'
STR_INCORRECT_TREE_DIR='Dosyayı burada çalıştırma, lütfen yayınlanan en son kurulum paketini indirin ve oradan çalıştırın.'
STR_DEVICE='Aygıt'
STR_LOCAL_VER='Ventoy GÜNCEL Sürüm'
STR_DISK_VER='Cihazdaki Ventoy Sürümü'
STR_STATUS='Durum - HAZIR'
STR_INSTALL='Kur'
STR_UPDATE='Güncelle'
STR_UPDATE_TIP='Ventoyun versiyon bilgisi güncellenecek, ISO dosyalarınız bundan etkilenmiyecek.#@Devam edilsinmi?'
STR_INSTALL_TIP='Disk biçimlendirilecek ve tüm veriler kaybolacak.#@Devam edilsinmi?'
STR_INSTALL_TIP2='Disk biçimlendirilecek ve tüm veriler kaybolacak.#@Devam edilsinmi? (Son UYARI!)'
STR_INSTALL_SUCCESS='Tebrikler!#@ventoy cihaza başarıyla kuruldu.'
STR_INSTALL_FAILED='Yükleme sırasında bir hata oluştu. USB'yi yeniden takıp tekrar deneyebilirsiniz. Ayrıntılar için log.txt dosyasına bakın.'
STR_UPDATE_SUCCESS='Tebrikler!#@ventoy cihazda başarıyla güncellendi.'
STR_UPDATE_FAILED='Güncelleme sırasında bir hata oluştu. USB'yi yeniden takıp tekrar deneyebilirsiniz. Ayrıntılar için log.txt dosyasına bakın.'
STR_WAIT_PROCESS='Mevcut işlem çalışıyor, lütfen bekleyiniz ...'
STR_MENU_OPTION='Seçenek'
STR_MENU_SECURE_BOOT='Güvenli Önyükleme'
STR_MENU_PART_CFG='Partisyon Yapılandırması'
STR_BTN_OK='Tamam'
STR_BTN_CANCEL='İptal et'
STR_PRESERVE_SPACE='Diskin sonunda ayrılmış disk partisyonu oluştur'
STR_SPACE_VAL_INVALID='Ayrılmış alan için geçersiz değer girdiniz'
STR_MENU_CLEAR='Ventoyu USB Diskten Sil'
STR_CLEAR_SUCCESS='Ventoy başarılı bir şekilde diskten silindi'
STR_CLEAR_FAILED='Ventoy USB diskten temizlenirken bir hata oluştu.Lütfen USB Diski tekrar takın ve tekrar deneyin.Hatanın detayları için Log.txt dosyasını okuyun'
STR_MENU_PART_STYLE='Partisyon Yapısı'
STR_DISK_2TB_MBR_ERROR='2TB üstündeki diskler için lütfen GPT disk yapısını seçiniz.'

**Comment by ventoy** [comment]
I have updated it.

**Comment by crasadure** [comment]
Thanks
