### ISSUE TITLE
Trojan detected for Ventoy2Disk.exe

### ISSUE THREAD

**Issue by luketanti** [ventoy/Ventoy#31]
![DeepinScreenshot_select-area_20200430123122](https://user-images.githubusercontent.com/23320513/80700755-895a7100-8ade-11ea-8835-5368d3c7596b.png)

When extracting on windows, the Ventoy2Disk.exe is getting flagged and deleted by McAfee

Is this false positive?

I have also checked on VirusTotal and attached a screenshot

**Comment by HarmVeenstra** [comment]
Same goes for Sophos Endpoint Protection

**Comment by boomschtick** [comment]
The detections on VirusTotal is up to 19.  I ran the app in Windows Sandbox and didn't see anything wrong, but the detection rate is concerning for people who care to look.

![image](https://user-images.githubusercontent.com/1853797/81125432-586ea780-8ef5-11ea-8675-858da5fa9e24.png)

**Comment by fboyd** [comment]
Same for Bitdefender.  Says it found Trojan.GenericKD.33781261 in the zip file.

**Comment by luketanti** [comment]
@ventoy can you please have a look about this please?

**Comment by ventoy** [comment]
@luketanti 

Currently I have no idea about this. 
Ventoy2Disk.exe is open source. You can compile it from the source by VisualStudio. 
So I don't known why it is denied by these antivirus software.

Any suggestions?

**Comment by boomschtick** [comment]
There has to be some kind of behavior in the code that the AV's don't like to see.  Either that or you have used source code that was used previously in some kind of malware.

That's my best guess.

**Comment by RudiKlein** [comment]
Hi,
Maybe the message I got from Acronis Active Protection (module of Acronis True Image 2020) could shine some light on this. It blocks the Ventoy2Disk.exe with the message: Possibe ransomware detected. Acronis Active Protection paused the program that tried to modify your Master Boot Record". That might be a hint.

**Comment by jsamr** [comment]
@ventoy I dig into support channels. Here is a list, you could submit reports to be whitelisted! I know it's a lot of work, but that would be great for community trust.

- AhnLab-V3: https://global.ahnlab.com/en/site/support/virusreport/virusReport.do
- SecureAge APEX: https://www.secureaplus.com/features/antivirus/report-false-positive
- Cylance: *no official channel unfortunately*
- Cyren: https://www.cyren.com/support/reporting-av-misclassifications
- eGambit: https://tehtris.com/egambit_fp.php
- Fortinet: [report by mail](submitvirus@fortinet.com)
- MaxSecure: https://www.maxsecureantivirus.com/submit_aFalse_Positive.htm
- McAfeee: https://secure.mcafee.com/apps/mcafee-labs/dispute-form.aspx
- Qihoo-360: https://www.360totalsecurity.com/help/360-total-security/#collapse-faq-3-2
- Rising: http://mailcenter.rising.com.cn/filecheck_en/
- Sangfor Engine Zero: *couldn't find a channel*
- Sophos AV: https://www.techsupportalert.com/content/how-report-malware-or-false-positives-multiple-antivirus-vendors.htm#Sophos
- TrendMicro-HouseCall: https://success.trendmicro.com/solution/1115860-reporting-a-false-positive-issue-in-worry-free-business-security-wfbs
- Webroot: https://www.webrootanywhere.com/servicewelcome.asp

**Comment by Riz-waan** [comment]
Hi, what about for windows defender?

**Comment by tonyd85** [comment]
Acronis claims it modifies the Master Boor Record. Of which disk, Acronis is yet to say. However, Acronis is kind enough to bug out for 30 minutes before finally blocking it.

**Comment by jimmihenry** [comment]
Windows Defender found and kicked the Ventoy.exe, pointing out **Trojan:Win32/Phonzy.C!ml.** Ver.1.0.58
Cheers

**Comment by petrus9** [comment]
Just tested ventoy-1.0.81-windows.zip on virus total and got one flag:  Trojan.Malware.300983.susgen  by MaxSecure
![image](https://user-images.githubusercontent.com/63444532/200929913-d852e1f0-e48b-49e2-b836-f476c16be397.png)

![image](https://user-images.githubusercontent.com/63444532/200930171-88239bd6-c362-45dd-b6b0-ef6d8a76cf92.png)
