### ISSUE TITLE
能否支持把ESP分区放前面，后面的分区放ISO ？

### ISSUE THREAD

**Issue by galaxy001** [ventoy/Ventoy#311]
想问下为啥需要把ESP放在第二分区。

如果ESP放前面，调整iso分区的大小也方便些。也可以随时划分第三分区干别的。

**Comment by ventoy** [comment]
这个在官网上有说明，参考 [https://www.ventoy.net/cn/doc_disk_layout.html](https://www.ventoy.net/cn/doc_disk_layout.html)

放第二个分区是因为Win7/Win8等早期Windows版本对于U盘，只有第一个分区可以分配盘符使用，后面的分区都不可见除非使用第三方的工具。 如果ESP放第一个分区在这些系统上就不能用了，第二个分区不可见，无法拷贝ISO文件。

**Comment by galaxy001** [comment]
我想把Ventoy装到第二块硬盘上，做备用的启动盘。

看到 #249 涉及设备名不能带p所以nvme不行，你打算添加装到nvme上的支持。

而 #279 也是希望自己分区然后装的。

我希望能改成规定首分区最小开始扇区，然后允许用户自己分区，指定ESP分区与ISO分区的设备名，自动或手动探测ESP分区是第几个分区。

手动分区的好处是可以保证不破坏后面的分区，只调整开头几十G的部分。

另外，如果可以把现在ESP分区内的 grub 目录改名成例如 ventoy，还可以实现与Linux或其他系统共用 ESP 分区。chainload grub目录内的grub就行。
即时重装系统，`copy /boot/efi/EFI/BOOT/BOOTX64.BAK /boot/efi/EFI/BOOT/BOOTX64.EFI`就可以了。

**Comment by ventoy** [comment]
nvme后面会支持。

自定义分区的功能理论上都是可以做的，但暂时应该不会做，当前还是会优先在当前的方案下把ISO支持完全，兼容性做好。
