### ISSUE TITLE
Fix font of Ventoy2Disk

### ISSUE THREAD

**Issue by hoangdiemtinh** [ventoy/Ventoy#314]
@ventoy 

I tried to fix the wrong font display error. It works well with 18 current languages. I would like to propose to you. :)

## 2. WinDialog.c, see image:
![font1](https://user-images.githubusercontent.com/67616643/87738033-af9ecb80-c806-11ea-9b51-06c29f250ea4.png)

## 3. Ventoy2Disk.rc, see image:
![font2](https://user-images.githubusercontent.com/67616643/87738040-b3cae900-c806-11ea-9ab4-30b5e521997d.png)

## 4. Result:
![font3](https://user-images.githubusercontent.com/67616643/87738302-42d80100-c807-11ea-97ee-ecdc3a5d4414.png)

Thanks.

**Comment by ventoy** [comment]
Hi,
Some language looks not so smooth and beautiful in Arial font. So I prefer that different languages can have different fonts.
I have updated the Ventoy2Disk.exe now the font in partition configuration dialog will follow that defined in the language.ini.
