### ISSUE TITLE
Please add more detail disk / disk list for information

### ISSUE THREAD

**Issue by hoangdiemtinh** [ventoy/Ventoy#316]
@ventoy 

Because I want to not choose the wrong device when creating boot.

You add to Ventoy2Disk that the drive for more information like the image below, okay ?.
.
![a1](https://user-images.githubusercontent.com/67616643/87749218-4a58d380-c822-11ea-85ef-fe2e0e3db9ee.png)
.
![a2](https://user-images.githubusercontent.com/67616643/87749222-4d53c400-c822-11ea-8dfa-f962828fb868.png)
.
As in the picture, my SSD external hard drive is mounted via HDD-box Enclosure. And it has 2 partitions, these partitions are drive G: and H:

On Ventoy2Disk, it is show only one partition (specifically, Ventoy2Disk combobox control of disks).

And, detailed information about the drive will be useful in some cases.

Thank you for understanding me.

**Comment by BL4CKH47H4CK3R** [comment]
For better understanding you should read our documentations. Hope you will understand how Ventoy works !

https://ventoy.net/en/doc_disk_layout.html

**Comment by ventoy** [comment]
@hoangdiemtinh  
In Ventoy-1.0.16, all the drive letters belong to the disk will be displayed in the combox, just as you hoped.
