### ISSUE TITLE
Only boots to grub prompt. Sandisk 64GB, partition <32GB doesn't help. Ventroy 1.0.15

### ISSUE THREAD

**Issue by Artyrm** [ventoy/Ventoy#323]
As additional symptom, under Win10, after install utility shows success message, if refresh drive - information that it has ventroy installed, disappears.

Workaround here doesn't help either:
https://www.ventoy.net/en/doc_legacy_limit.html

**Comment by ventoy** [comment]
What about the latest release?

This is an old issue. I will close it now.
If you still have problem with latest Ventoy release, you can reopen the issue.
