### ISSUE TITLE
Will we be able to use dd CLI in ventoy copy operation?

### ISSUE THREAD

**Issue by abdulbadii** [ventoy/Ventoy#324]
Will we be able to correctly use `dd` CLI in copy operation (as I took deep look into the dd's result, it always extract ISO it copies)?
Has anyone known it'll be succesful to copy ISO needed, using `dd`?

**Comment by ventoy** [comment]
dd will extract ISO files? Perhaps NOT.

For example
`dd if=/ubuntu-20.04-desktop-amd64.iso of=/mnt/ventoy/ubuntu-20.04-desktop-amd64.iso`

dd should only copy the iso file ubuntu-20.04-desktop-amd64.iso  to the destnation.

**Comment by abdulbadii** [comment]
So I deduce it from ours, dd conditionally:
- Will decide to extract an ISO if the destination is the path name of a mounted point
- Will copy a file into another location outright intact if the destination is a file name under a path

I'm exercising this hypothesis..
