### ISSUE TITLE
[Feature Request] PXE Boot to Ventoy

### ISSUE THREAD

**Issue by ajpri** [ventoy/Ventoy#325]
Be able to boot ventoy from a PXE server. As well as selecting ISO images that are on network resources.

**Comment by ventoy** [comment]
This project will not support PXE. 
I will start a new project after Ventoy, maybe with name VtoyPXE. 
I'm also a fan of PXE :)

**Comment by mconger** [comment]
> Be able to boot ventoy from a PXE server. As well as selecting ISO images that are on network resources.

Have you looked at iPXE.org? It is a free PXE firmware replacement and comes in a bootable ISO too so you can choose what works best for you. I have not used it (yet) but it looks very promising for booting from just about any network type or location you can think of, even over the internet.

**Comment by ventoy** [comment]
I known iPXE. iPXE is part of Ventoy.

**Comment by ventoy** [comment]
I know iPXE. Ventoy also uses iPXE.

**Comment by mh166** [comment]
@ventoy Once you start this project, could you maybe drop a short note, here? So we'll be informed about the great news! 😉 

Also: is there a (very rough) estimate about a possible "birth date"? Not even talking about months, but maybe just as in "first/second half of 2021" or "once I'll get to it..." 😄 Just a bit curious... :)
