### ISSUE TITLE
Install in linux

### ISSUE THREAD

**Issue by rajib-raiyat** [ventoy/Ventoy#330]
How to install in linux and make a ventoy launching application on linux?

**Comment by ventoy** [comment]
Refer to  [https://www.ventoy.net/en/doc_start.html](https://www.ventoy.net/en/doc_start.html)

**Comment by rajib-raiyat** [comment]
Don't have graphical software like Windows?

**Comment by ventoy** [comment]
Yes, only shell script now.

**Comment by rajib-raiyat** [comment]
After run this command.
`sh Ventoy2Disk.sh -i /media/rajib/USB/`

Its says that
`/media/rajib/USB/ is NOT a valid device`

**Comment by ventoy** [comment]
/media/rajib/USB is a mountpoint not a block device.
You should run like this:
`sh Ventoy2Disk.sh -i /dev/sdb`
`sh Ventoy2Disk.sh -i /dev/sdc`
`sh Ventoy2Disk.sh -i /dev/sdd`

/dev/sdb(c)(d) is your USB drive.  Use fdisk to find exact name.

**Comment by rajib-raiyat** [comment]
Thanks it's works.
`Install Ventoy to /dev/sdb successfully finished.`

However I have a suggestion please write a proper documentation `README.md` for linux installation and the whole process or I can do this.

**Comment by ventoy** [comment]
Just run sh Ventoy2Disk.sh  without any parameter, it will print the usage info as follows:
```
Ventoy2Disk.sh CMD [ OPTION ] /dev/sdX
  CMD:
    -i   install ventoy to sdX (fail if disk already installed with ventoy)
    -I   force install ventoy to sdX (no matter installed or not)
    -u   update ventoy in sdX
    
  OPTION: (optional)
   -r SIZE_MB  preserve some space at the bottom of the disk (only for install)
   -s          enable secure boot support (default is disabled)
   -g          use GPT partition style, default is MBR style (only for install)
```

**Comment by rajib-raiyat** [comment]
Thanks
