### ISSUE TITLE
[Features - Menu Alias Plugin] Fixed order list

### ISSUE THREAD

**Issue by TimerWolf** [ventoy/Ventoy#331]
First of all, thanks for an amazing software!

It would be nice if it could be possible to have the possible to have the list in order.

As it is today i don't know for sure how it is order as it's  not by name but in some way the list is mixed up.

One way could be to order it automatic as it is in the json file, or add another key to set it in the order you like...

**Comment by ventoy** [comment]
The order is as it is in the json file.

**Comment by TimerWolf** [comment]
I can tell you for sure that that's not the case, as my order is actually different from the one in the json file...

**Comment by ventoy** [comment]
What do you mean about the order. Normally in Menu Alias plugin, we set an array in the json file, each item in the array is an iso file  path and its alias. The order should doesn't matter.

**Comment by TimerWolf** [comment]
You say its order as it is in the json file but it's not.

The json file is like this

```
{
  "menu_alias": [
    {
      "image": "xxx.iso",
      "alias": "xxx"
    },
    {
      "image": "xxx.iso",
      "alias": "xxx"  
    },
    {
      "image": "xxx.iso",
      "alias": "xxx"
    },
    {
      "image": "/ISO/Linux/ubuntu-mate-20.04-desktop-amd64.iso",
      "alias": "Ubuntu Mate Desktop (20.04) [x64]"
    },
    {
      "image": "/ISO/Linux/tails-amd64-4.8.iso",
      "alias": "Tails (4.8) [x64]"
    },
    {
      "image": "/ISO/Tools/boot-repair-disk-64bit.iso",
      "alias": "Boot Repair Disk [x64]"
    },
    {
      "image": "xxx.iso",
      "alias": "xxx"
    }
  ]
}
```
![Proof](https://i.imgur.com/88oL1HU.jpg)

It's no way to really order the iso:s and that's is what i try to say....

**Comment by ventoy** [comment]
I just misunderstood what you said.

Without considering the Menu Alias plugin.
The ISO file list in the boot menu is ordered by the ISO file name alphabetically (case sensitive)

Menu Alias just display the alias instead of the original ISO file name, but the order will not change.
In other words, the list in the boot menu is ordered by the original ISO file name (only name, without directory prefix)

**Comment by ventoy** [comment]
You can use image_list plugin if you want to list the iso files in your order.
https://www.ventoy.net/en/plugin_imagelist.html
