### ISSUE TITLE
[Features - Menu Alias Plugin] SubDirectories

### ISSUE THREAD

**Issue by TimerWolf** [ventoy/Ventoy#332]
Another nice feature would be if the added ISOs could be in "virtual" dirs..

> 
> First way
>
> ```json
> {
>   "menu_alias": [
>     {
>       "image": "/ISO/Linux/ubuntu-mate-20.04-desktop-amd64.iso",
>       "alias": "Linux/Ubuntu/Ubuntu Mate Desktop (20.04) [x64]"
>     },
>     {
>       "image": "/ISO/Linux/tails-amd64-4.8.iso",
>       "alias": "Linux/Talis/Tails (4.8) [x64]"
>     }
>   ]
> }
> ```

> 
> Second way
> 
> ```json
> {
>   "menu_alias": [
>     {
>       "image": "/ISO/Linux/ubuntu-mate-20.04-desktop-amd64.iso",
>       "alias": "Ubuntu Mate Desktop (20.04) [x64]"
>       "subdir": "Linux/Ubuntu"
>     },
>     {
>       "image": "/ISO/Linux/tails-amd64-4.8.iso",
>       "alias": "Tails (4.8) [x64]"
>       "subdir": "Linux/Tails"
>     }
>   ]
> }
> ```

**Comment by ventoy** [comment]
Menu Alias is a simple alias feature, just for menu display.
I don't want to make it too complex.

**Comment by TimerWolf** [comment]
That was very sad to hear, but maybe you can combine the tree-view and the menu alias?

The only problem there is that i actually have some directorys that I would like to hide from the view...

But build in an ignore function for directorys is maybe not out of the question?

As what i understand it the ventoy don't show files that not is images, and that's really smart to just ignore them as them don't have any purpose in the view. 

And if it not possible to combine those two maybe that's a way around it...

**Comment by ventoy** [comment]
`The only problem there is that i actually have some directorys that I would like to hide from the view...`

There are two method for you.
1. You put a file with name `.ventoyignore` in the directory, then Ventoy will skip the directory and its subdirectories.
2. You can use global control plugin to set `VTOY_DEFAULT_SEARCH_ROOT`  then Ventoy will only search the directory and its subdirectories.

**Comment by TimerWolf** [comment]
I don't understand, is the new plugin "menu extension" related to this feature request?

**Comment by ventoy** [comment]
supported in latest release.
