### ISSUE TITLE
Preserve space at the bottom of disk

### ISSUE THREAD

**Issue by hoangdiemtinh** [ventoy/Ventoy#340]
## Environment:
- Windows 7 SP1 64bit
- Ventoy 1.0.16 - 23/7/2020
- USB Flash (1 GB)
## Process:
I tried to enter a number (6GB) larger than the device's capacity (1GB) and clicked OK, strangely, the GUI still accepted, without any warning.

![Preserve-Space](https://user-images.githubusercontent.com/67616643/88298630-99739c80-cd2b-11ea-81cc-15b0a36fcec0.png)

**Comment by ventoy** [comment]
Yes, the number will only be checked when you click  install  button.
You can insert, refresh and select another 8GB USB after you set the number. 
So it will NOT be checked immediately.
