### ISSUE TITLE
Kaspersky Rescue Disk with LEGACY and UEFI booting

### ISSUE THREAD

**Issue by hoangdiemtinh** [ventoy/Ventoy#342]
## Environment:
- mainboard use chiset Intel H61, CPU Intel Celeron G530/630
- Ventoy 1.0.16 - 23/7/2020
- USB Flash (1 GB)
## Process:
- Install Ventoy for USB
- Ventoy GUI Options:
++ Enable Secure Boot
++ Menu GPT checked/enable

## Result:
- LEGACY: KRD OK
- UEFI mode: KRD FAILED
KRD message: bad signature

Is someone like my case ?.

**Comment by chromer030** [comment]
https://www.ventoy.net/en/isolist.html

![Screen Shot 2020-07-23 at 20 50 05](https://user-images.githubusercontent.com/13361552/88311591-53680a00-cd26-11ea-815c-d4dc7fe18e03.png)

**Comment by IvanAclu** [comment]
To clarify, this is what you have to do to UEFI boot Kaspersky Rescue Disk (KRD).

Boot to KRD first menu
Press c to go to the KRD GRUB2 prompt
Type set check_signatures=no
Press ENTER
Press ESC

Select language and carry on
KRD should now boot

**Comment by ventoy** [comment]
Yes, KRD need the special process.
