### ISSUE TITLE
Problems on some ISO's 

### ISSUE THREAD

**Issue by lonnietc** [ventoy/Ventoy#344]
Hello,

Let me first say that I really like Ventoy and it seems to work very well for a number of ISO's that I have tried.

With that in mind, I did find that I am having trouble using it to boot up

1. FuryBSD (https://www.furybsd.org/) 

     ISO: https://sourceforge.net/projects/furybsd/files/

2. OpenIndiana (https://www.openindiana.org/)

     ISO: http://dlc.openindiana.org/isos/hipster/20200504/OI-hipster-gui-20200504.iso

Is there any way that you can look into these as for the current project that I am working on, I may really need to get the OpenIndiana, SmartOS, and OmniOS (Illumos-Based) ISO's to work as they all have the same installer and format on their ISO's.

Cheers

**Comment by ventoy** [comment]
Hi，
FreeBSD series are not supported now but in my plan.

**Comment by lonnietc** [comment]
Hello,

Thanks for the update and Ventoy is really amazing an I absolutely plan to use it for the project. Will contact you when the project is in Beta to explain more about how Ventoy has been integrated as I think that you will really like what I am planning to do with it and how it works as part of the project.

Cheers
