### ISSUE TITLE
Can't update from ventoy-1.0.16 to ventoy-1.0.17

### ISSUE THREAD

**Issue by diablothebest** [ventoy/Ventoy#347]
[log.txt](https://github.com/ventoy/Ventoy/files/4975864/log.txt)
Can't upgrade from 1.0.16 to 17 release. Use GTP style + Secure Boot.
Do clean install only.

**Comment by DX37** [comment]
Strange. I upgraded perfectly. Even that bug about injection gone.

**Comment by asheroto** [comment]
Don't forget to update the Chocolatey repo,, thanks!!!!!! :-)

**Comment by ventoy** [comment]
If you can reproduce the problem. Try follows:
Assume that the USB is disk 2 in your system.
```
1. run diskpart
2. select disk 2
3. select part 2
4. GPT ATTRIBUTES=0x8000000000000001
```

After that, retry the update operation.

**Comment by iPyGuy** [comment]
Yep, same issue here (though I'm not using Secure Boot).
When I open up the Ventoy app, it doesn't even properly display what version of Ventoy is already installed on my device (which is 1.0.16) and the update button is grayed out.

![alt text](https://i.imgur.com/vGFn2cL.png "Just an empty field...")

Anyway, guess I'll just have to copy all the iso files from my USB stick to my system and then install Ventoy 1.0.17 from scratch and copy all the iso files back to my USB stick.

**Comment by ventoy** [comment]
@iPyGuy 
If you still have the log.txt when you open Ventoy2Disk.exe and can't see the version, please put it here for debug.

**Comment by iPyGuy** [comment]
> @iPyGuy
> If you still have the log.txt when you open Ventoy2Disk.exe and can't see the version, please put it here for debug.

Yeah, this is the log file that is produced when I run the Ventoy program.
[log.txt](https://github.com/ventoy/Ventoy/files/4977162/log.txt)

I notice that at the very end of the log file is the error `Invalid ventoy efi part name` which is probably why the program doesn't detect/display the Ventoy version installed on my USB stick.

**Comment by yoksi** [comment]
hi, update .17 always stuck on 12% with differed flash disk brands... solution was remove flash disk, run Ventoy .17,  put flashdisk back, refresh button and then it works

![Capture-1](https://user-images.githubusercontent.com/41486154/88473456-ea4ae700-cf1d-11ea-9818-eddfd9437af4.jpg)

**Comment by diablothebest** [comment]
> If you can reproduce the problem. Try follows:
> Assume that the USB is disk 2 in your system.
> 
> ```
> 1. run diskpart
> 2. select disk 2
> 3. select part 2
> 4. GPT ATTRIBUTES=0x8000000000000001
> ```
> 
> After that, retry the update operation.

Can't do this. I'm install fresh 1.0.17 on my USBFLASH Drive. May be some one else check it....

**Comment by ammar-morad** [comment]
I have an external Hard 1 terabyte installed version 1.0.13 can  not updated to any version or even see the installed version
I use MBR cannot format all my data 150 GB to reinstall it 
![Ven](https://user-images.githubusercontent.com/69061487/89088542-5b185600-d399-11ea-80d2-da81b022abe5.png)

**Comment by ventoy** [comment]
version related problem.
