### ISSUE TITLE
Request: Could we please have an option to hide the .iso or .wim extension on the menus, please? Perhaps on by default?

### ISSUE THREAD

**Issue by CyberTacoX** [ventoy/Ventoy#348]
I know the json can be rigged to show nice menu names, and I do use that all the time. But, for the people who can't handle or don't have time right now to figure out that part, at least not showing the extensions by default would make the menu look a lot nicer. :-)

**Comment by ventoy** [comment]
I prefer the full name with extension.

**Comment by hoangdiemtinh** [comment]
Right, I am so. Full filename with extension !!!.

**Comment by CyberTacoX** [comment]
{shrug} Ok then, how about an option to hide the extension, with the default being off instead? :-)

**Comment by mconger** [comment]
Maybe it would be possible to modify the source code to your preference.

**Comment by CyberTacoX** [comment]
Well of course, that's always an option - for programmers. For the rest of us, that's a bit out of reach. :-)
