### ISSUE TITLE
Keyboard and touch pad issue on Surface Laptop 3

### ISSUE THREAD

**Issue by abc1236762** [ventoy/Ventoy#349]
I cannot use the keyboard and touch pad that integrated in Surface Laptop 3 after Surface Laptop 3 booted into the system of `.iso` with Ventoy, I have tested the following `.iso` file with or without secure boot support Ventoy:
- ct_windows_10_business_editions_version_2004_x64_dvd_5be1f8d6.iso
- ct_windows_10_consumer_editions_version_2004_x64_dvd_524ec676.iso
- ubuntu-20.04-desktop-amd64.iso
- ubuntu-18.04.4-desktop-amd64.iso
- manjaro-gnome-20.0.3-minimal-200606-linux56.iso

But if I use external input device, it's worked.

**Comment by ventoy** [comment]
Does the keyboard work if you make a bootable USB by other tool (e.g. rufus)?

**Comment by abc1236762** [comment]
Close it due to not the problem on Ventoy, I tried use rufus to make Windows 10 installation USB (use ct_windows_10_consumer_editions_version_2004_x64_dvd_524ec676.iso) on both GPT and MBR, and whether secure boot is opened or not, the input devices that integrated in Surface Laptop 3 cannot be worked, I also tried the offical way (use [Windows 10 installation media tool](https://www.microsoft.com/en-us/software-download/windows10)) and had the same results, I think is the problem on Microsoft.
