### ISSUE TITLE
Windows Iso does not boot (legacy boot)

### ISSUE THREAD

**Issue by Traumlewis** [ventoy/Ventoy#350]
Windows does not boot on Ventoy 1.0.17 
UEFI works fine but for some time now I can't boot Windows Iso in legacy boot mode😕

**Comment by ventoy** [comment]
Which ISO file did you test?
Does it OK with previous ventoy release (1.0.16) ?
What happen when you boot in legacy BIOS mode?

**Comment by Traumlewis** [comment]
• All Win 10 , 8, 8.1, 7 and PE Version Original from Microsoft.
• The answer is no, the same with version 1.0.16. I will make myself a Ventoy Stick with an older version and test the time when the bug exists
•In the legacy BIOS I only get a dash blinking when starting a Windows Iso.  And nothing happens

**Comment by DX37** [comment]
I encountered this issue on some old hardware, like Dell Latitude 3460 in BIOS mode, but in UEFI mode it works fine. On the other hardware legacy boot works good.

**Comment by ventoy** [comment]
This is an old issue. I will close it now.
If you still have problem with latest Ventoy release, you can reopen the issue.
