### ISSUE TITLE
有个小建议，把别名和文件注入合并是不是比较舒服？

### ISSUE THREAD

**Issue by GoGoogle** [ventoy/Ventoy#351]
不知道在实现上会不会有所难度，因为我觉得这俩放在一起很舒服，然后加个自动判断。
这样也可以缩小json文件的大小以及去重。

类似如下代码：
```json
"menu_alias_injection" : [
			{
				"image": "/ISO/WIN10.iso",
				"alias": "0.测试",
				"archive": "/driver/win10-driver.zip"
			}
		]
}
```

**Comment by ventoy** [comment]
这两个功能并不相关，放一起并不合适。

**Comment by GoGoogle** [comment]
好吧，只是个人建议。

**Comment by redchenjs** [comment]
对于用户来说这样确实比较直观，因为都是对同一个image的操作嘛，只是这个菜单项命名有点生硬，用个类似menu_image_config之类的通用命名，archive项名可以直接改用injection，以后如果有其他对单个image的配置也可以从这里面读取。

**Comment by GoGoogle** [comment]
> 对于用户来说这样确实比较直观，因为都是对同一个image的操作嘛，只是这个菜单项命名有点生硬，用个类似menu_image_config之类的通用命名，archive项名可以直接改用injection，以后如果有其他对单个image的配置也可以从这里面读取。

我也是这样想的，所以提了个issues.
