### ISSUE TITLE
Ventoy is not flexible at all when it comes to the order of the EFI boot partition 

### ISSUE THREAD

**Issue by cpuuntery** [ventoy/Ventoy#352]
you you can install ventoy manually without the script if you are using Linux. you just need to take the files from "ventoy.disk.img" file. and create an EFI partition using GParted. but ventoy force you to make the EFI the 2nd partition. and the developer based his partitioning decisions on an almost 11 years old OS that is out of support (windows7). and **this is totally fine**. but at least he should give us the option if we want to **make the EFI partition the 1st**. the problem that the parting order is hardcoded into ventoy if you change the partitioning order you will get `minimal bash like line editing is supported`. and I should mention that **projects like grub2-filemanager and rEFInd don't force you to any partitioning order** you can choose whatever order you like it will boot just fine but these two projects have weak iso support. I am not asking the developer to change the partitioning order **I am asking him to give the people who install ventoy manually a choice** if the developer did that **ventoy will be perfect for me. and I will have the best of both worlds**

**Comment by ventoy** [comment]
Windows 7/8/8.1 and Windows 10 before 1703 (I remember), they are all the same, only the 1st partition of USB drive can be mounted and used by default. 
So I put the EFI partition the 2nd partition, it was designed from the beginning just like the 32MB size and will keep status quo during Ventoy 1.X.

ps: Why not fork it and enjoy the open source :)

**Comment by cpuuntery** [comment]
@ventoy 
the number of people running windows 8 and 8.1 is minuscule. and it is near impossible to disable windows update you can only slow it down. anyone who installed windows 10 1511 and connected to the internet will be running 20.04 by now.
**Can you at least tell me which line of code I should change**. and after that, I believe I can build from source using docker

**Comment by cpuuntery** [comment]
from what you said if Ventoy reached version 2.0 maybe I can set the EFI partition to be the 1st and it will work

**Comment by ventoy** [comment]
In my plan 2.X will change the way that ventoy exist. For example, only one partition or only a bootable ISO of Ventoy.

Now it's almost impossiable to make it work with EFI partition to be part 1. Too many modifications needed.
