### ISSUE TITLE
Please update third-part source for Ventoy

### ISSUE THREAD

**Issue by hoangdiemtinh** [ventoy/Ventoy#355]
I am check third-part source code for Ventoy, I see new versions at current date 27/7/2020:

## 1. tianocore EDK2
- In Ventoy use version: edk2-stable201911 (release on 11/2019)
- tianocore EDK2 lastest version: release on date 3/6/2020 - https://github.com/tianocore/edk2/releases/tag/edk2-stable202005

## 2. libfuse
- In Ventoy use version: libfuse 2.9.9 (release on 4/1/2019)
- libfuse lastest version: 3.9.2 (release on 12/6/2020) - https://github.com/libfuse/libfuse/releases/tag/fuse-3.9.2

@ventoy  Please update third-part source code for Ventoy.

And update content for BuildVentoyFromSource.txt :)

**Comment by ventoy** [comment]
There is no need to always follow the latest version of the third-part code unless there is a serious bug or necessary new feature.

Ventoy did't use the latest release of libfuse even when Ventoy was first released.
