### ISSUE TITLE
Can't choose a specific partition of external USB HDD

### ISSUE THREAD

**Issue by NAbdulla1** [ventoy/Ventoy#356]
My external HDD has multiple partitions. I want to choose a particular partition to install Ventoy. But it shows the whole HDD as a single entry. and no option to select a particular partition. I can select a particular partition of that HDD with Universal USB Installer though.

**Comment by ventoy** [comment]
Yes, Ventoy can't be installed in a partition.  Ventoy must occupy the whole USB disk and create partitions in its rule. That's how it was designed from the beginning.
