### ISSUE TITLE
联想的biso升级镜像引导不了

### ISSUE THREAD

**Issue by skyfly0** [ventoy/Ventoy#357]
下载链接http://newdriverdl.lenovo.com.cn/newlenovo/alldriversupload/73178/BIOSCD-r12uj55wd.iso
挂载这个镜像会发面里面的内容是空的，但直接用dd把镜像写入到u盘后可以启动，把这个镜像放到u盘里ventoy也能找到，但引导不了。

**Comment by ventoy** [comment]
用F1 MemDisk 模式试试呢

**Comment by skyfly0** [comment]
> 用F1 MemDisk 模式试试呢

试了下，确实可以了，感谢！
