### ISSUE TITLE
debian 10.4 buster netinst / IBM Thinkpad X31 / i386 

### ISSUE THREAD

**Issue by flohoff** [ventoy/Ventoy#358]
Hi,
the boot of the i386 image works fine but the Debian Buster i386 installer does abort after trying to detect a CD Rom Drive. I tried looking whats going on and i couldnt mount /dev/sdb1 the ventoy drive from the installer so i guess exfat support is missing.

File used is this:

debian-10.4.0-i386-netinst.iso

Flo

**Comment by ventoy** [comment]
It's indeed a bug, I will fix it in 1.0.20 release.

**Comment by ventoy** [comment]
Have fixed.
