### ISSUE TITLE
Ventoy2Disk was wrong detect Partition Style

### ISSUE THREAD

**Issue by hoangdiemtinh** [ventoy/Ventoy#359]
## Environment:
- Windows 7 SP1 64bit
- Ventoy2Disk 1.0.17
- Windows Command Prompt
## Process:
[ If you want to test with HDD/SSD --> ]
change
static int g_FilterUSB = 1;
to
static int g_FilterUSB = 0;
[ <-- If you want to test with HDD/SSD ]

**PLEASE BACKUP YOUR DATA BEFORE TESTING !!!**

### 1. Open Command Prompt of Windows
1. Type **diskpart** and enter
2. At the DiskPart:
- Type **list disk** and Enter
- Type **select disk _index_of_disk_** and Enter. Example, in my case:
select disk 1

![mbr-gpt-1](https://user-images.githubusercontent.com/67616643/88619253-5287fd00-d0c5-11ea-970d-83187826ff72.png)
- Type **clean** and Enter
### 2. Open Computer Management (right click on My Computer --> Manage), select Disk Management
NOW, my Disk/Drive (with Disk Index = 1), it's show **Not Initialized Disk** (sure, = UnAllocated Disk). Meaning it does not have a Partition Style/Scheme (either MBR or GPT).
### 3. Open Ventoy2Disk
It's show MBR of Partition Style :)

![mbr-gpt-2](https://user-images.githubusercontent.com/67616643/88619952-f8883700-d0c6-11ea-9324-d137c0cbfb5f.png)
## Result:
Ventoy was wrong detect Partition Style.

@ventoy Please fix.

**Comment by ventoy** [comment]
I will fix it in the next release.

**Comment by ventoy** [comment]
Please give a screenshot of Ventoy2Disk.exe

**Comment by hoangdiemtinh** [comment]
Sorry, I am confused.
I have modified some code in Ventoy2Disk.
I checked, Ventoy2Disk showed nothing about Partition Style.
I will close this topic.

**Comment by ventoy** [comment]
Yes, I just test it and it show nothing.  
GPT/MBR will only be shown if the version of Ventoy in the disk can be correctly detected.
