### ISSUE TITLE
Linpus Lite Boot Failed

### ISSUE THREAD

**Issue by amouses** [ventoy/Ventoy#36]
I can create the USB key in eather Ubutnu Linux or Windows 10 without issue.

I take it to my test laptop to boot from key and get the Linpus Boot failure.

In the laptop BIOS I can see the 64GB Sandisk drive is visible and bootable.

**Comment by ventoy** [comment]
I hava reveived this report.
Can you try to close the Secure Boot option in BIOS and see what will happen?

**Comment by amouses** [comment]
Okay,  I make the following report.
Hardware is Sandisk 64GB, and Ventoy version is  1.0.08
I tested the key on a VMWARE virtual machine.  In that environment this key works fine and I selected the Ubuntu 20.04 .iso and booted Ubuntu fine.

---

So then I insert this same key into my noname laptop

Case 1
Goto into BIOS
Select UEFI trusted file for execution
I select Sandisk, then \EFI\boot\BOOTX64.EFI
Set Secure Boot to Enabled
Reboot
Machine tries to boot
Blue Dialog box, message
**Linpus lite boot failed.**


Case 2
Enter BIOS
Secure Boot is disabled
Reboot
Machine tries to boot
Blue Dialog box, message
**Linpus lite boot failed.**

**Comment by ventoy** [comment]
Ok,
It's due to Ventoy's secure boot solution. Since 1.0.07 Ventoy add support to secure boot, but the solution is not perfect enough, it will not work on some mathine no matter secure boot is enabled/disabled.
**Linpus lite boot failed** is the most common cases of them.
So in the next release, I will add an option during installation for secure boot, for these machines user can uncheck secure boot support. Then disabled secure boot in BIOS and use Ventoy.

For 1.0.08, if you want to try, you can do as follows:
Find a way to mount the second partition of Ventoy (EFI FAT partition), there will be 4 files, in \EFI\BOOT directory:  BOOTX64.EFI  grubx64.efi  grubx64_real.efi  MokManager.efi 
Just rename BOOTX64.EFI to another name like abc.efi and rename grubx64_real.efi to BOOTX64.EFI

Then Ventoy may work with UEFI when you disable secure boot in BIOS.

**Comment by amouses** [comment]
Thanks for the reply ... it still fails with Linpus lite boot failed.  To be clear I 

a) mounted the EFI partition which shows up as /dev/sdb2 on my ubuntu system onto /efi

b) I then found the BOOT64.EFI file and renamed it to fred.efi

c) Then I renamed grub64_real.efi to BOOTX64.EFI

d) then went into bios and disabled secure boot

On reboot I still get the Linpus lite boot failure message, so then it gives up on the USB key and goes to the hard disk and I get my standard GRUB (version 2.04) menu

**Comment by ventoy** [comment]
Can you try this way ?
Just delete BOOTX64.EFI grubx64.efi MokManager.efi 
and rename grubx64_real.efi  to BOOTX64.EFI

**Comment by ventoy** [comment]
Or try this way:
1. delete  BOOTX64.EFI
2. rename grubx64.efi to BOOTX64.EFI (leave grubx64_real.efi unchanged)

**Comment by amouses** [comment]
Trying this first:

delete BOOTX64.EFI
rename grubx64.efi to BOOTX64.EFI (leave grubx64_real.efi unchanged)

**Still no joy**

![Linpus lite boot failed](https://user-images.githubusercontent.com/19480319/80910303-52769c00-8d26-11ea-8ed1-60ef8938a554.jpg)

![bios screen](https://user-images.githubusercontent.com/19480319/80910309-67532f80-8d26-11ea-8bca-8bf25c808bf9.jpg)

![secure boot status disabled](https://user-images.githubusercontent.com/19480319/80910310-70440100-8d26-11ea-858b-e2824747b06f.jpg)

**Comment by amouses** [comment]
Trying this second
Can you try this way ?
Just delete BOOTX64.EFI grubx64.efi MokManager.efi
and rename grubx64_real.efi to BOOTX64.EFI

**Wahoo,  that worked !! **

![1 fix](https://user-images.githubusercontent.com/19480319/80910847-48ef3300-8d2a-11ea-9dd6-a5baec67ccd9.jpg)

![2 fix](https://user-images.githubusercontent.com/19480319/80910848-4987c980-8d2a-11ea-9c26-3d47c87dbb8a.jpg)

![3 fix](https://user-images.githubusercontent.com/19480319/80910849-4987c980-8d2a-11ea-96d4-d6a70bd79fd2.jpg)

![4 fix](https://user-images.githubusercontent.com/19480319/80910850-4987c980-8d2a-11ea-8d47-7b7d7cd120a9.jpg)

**Comment by pblgomez** [comment]
> Trying this second
> Can you try this way ?
> Just delete BOOTX64.EFI grubx64.efi MokManager.efi
> and rename grubx64_real.efi to BOOTX64.EFI
> 



I can confirm this works on Xiaomi laptop too !

**Comment by ventoy** [comment]
I change the default option for secure boot, so ventoy-1.0.09 beta1 will work well.

**Comment by ventoy** [comment]
@amouses 
Is it OK in 1.0.09 ?

**Comment by amouses** [comment]
I can confirm that I tried 1.0.09 and just a plain install onto a 32GB Sandisk Extreme key, followed by populating with some .ISO works fine now.

Fantastic!

I can honestly say this is the best small utility product I have come across in years.  Thanks so much for developing it.

regards mb.
