### ISSUE TITLE
自动挂载导致的失败

### ISSUE THREAD

**Issue by yichangshengwu** [ventoy/Ventoy#360]
系统：arch linux
桌面：kde
版本：1.0.17

以 mbr 方式安装，未发现问题，
以 gpt 方式安装，则报错：mv: 无法获取'./tmp_mnt/EFI/BOOT/grubx64_real.efi' 的文件状态(stat): 没有那个文件或目录

因为过程中反复提示 sdb2 存在已挂载分区，
遂停止了 kde 的自动挂载移动存储的服务，
发现可以正常完成安装了，

特此反馈一下

**Comment by ventoy** [comment]
是这样的， Ventoy在安装时会自己尝试 umount 这个挂载， 可能umount失败了。

**Comment by yichangshengwu** [comment]
> 是这样的， Ventoy在安装时会自己尝试 umount 这个挂载， 可能umount失败了。

也不排除是 解除挂载 之后又被其他程序给 自动挂载 回去了吧？
也许可以在 常见问题 里提一下？
