### ISSUE TITLE
Ventoy2Disk always does the removal although Ventoy is not installed yet

### ISSUE THREAD

**Issue by hoangdiemtinh** [ventoy/Ventoy#361]
## Environment:
- Windows 7 SP1 64bit
- Ventoy2Disk 1.0.17
- A Hard Disk
## Process:
[ If you want to test with HDD/SSD --> ]
change
static int g_FilterUSB = 1;
to
static int g_FilterUSB = 0;
[ <-- If you want to test with HDD/SSD ]

**PLEASE BACKUP YOUR DATA BEFORE TESTING !!!**

I format my hard disk to GPT Partition Style (and only one partition).
I have not done the Ventoy installation yet. Then I open Ventoy2Disk, click on menu "Remove Ventoy".
Ventoy2Disk always does the removal even though devices is not installed yet.
And my hard drive became **RAW DISK** with MBR Partition Style !. :)

![RAW-DISK](https://user-images.githubusercontent.com/67616643/88655137-89c3d180-d0f8-11ea-849d-beedbdb531c2.png)

Then Windows alert: **Do you want to format it ?**

![RAW-DISK2](https://user-images.githubusercontent.com/67616643/88656527-ab25bd00-d0fa-11ea-988d-6bb216c7ee13.png)

@ventoy Please fix this problem.

**Comment by ventoy** [comment]
I think there is no need to fix the "issue".
User should use "Clean Ventoy" with the right disk just like when they install Ventoy.

**Comment by hoangdiemtinh** [comment]
If you say, assume that Ventoy always does the removal, then you revise the RAW Disk issue.
Put everyone's hard drive in the normal format, which is the correct format for reading in Windows Explorer / File Explorer.

**Comment by ventoy** [comment]
That's just designed so. 
I remove Ventoy from the disk and user can format the partition with FAT or exFAT or NTFS as they want.

**Comment by hoangdiemtinh** [comment]
If so, we change the "Remove Ventoy" menu to a PushButton and add an optional hard disk format combobox with the value FAT32/NTFS/Ext4 :)

**Comment by ventoy** [comment]
I think an explain about this in FAQ is enough.

**Comment by Sebastian666** [comment]
i had the exact same problem
Installing .Net Framework 3.5 seems to solve the problem.
