### ISSUE TITLE
Device did not show up.

### ISSUE THREAD

**Issue by sgse** [ventoy/Ventoy#362]
Hope I'm right here :-)
I test with Garuda Linux but failed with
![rect837](https://user-images.githubusercontent.com/17575778/88669406-620e4280-d0d3-11ea-970b-68c34bdd1715.png)
https://garudalinux.in
Edit:
I have ISO grub on the monitor, then do the boot settings, then the splash screen of garuda appears with spinner, but then ...

**Comment by ventoy** [comment]
It's indeed a bug, I will fix it in the next release (1.0.20)

**Comment by sgse** [comment]
Sorry, but 1.0.20 show the same error.
Maybe it need some fix like for Manjaro and EndeavourOS?


Inspired by longpanda ;-)
![usb-01-sgs](https://user-images.githubusercontent.com/17575778/91664788-eee85980-eae0-11ea-8347-340e6ab66c4c.png)

**Comment by SecretAgentAgentX** [comment]
1.0.20 and Garuda just sits and spins. I gave it over 5 minutes once iot reached it's splash screen with the spinner. Both EnveavourOS and Manjaro booted without issue.

**Comment by sgse** [comment]
@SecretAgentAgentX 
Just press Esc on startup and you will see why it does not boot. Or look at post one.

**Comment by SecretAgentAgentX** [comment]
Thanks good to know.

**Comment by Surendrajat** [comment]
Getting the same on the Gnome version here...
![image](https://user-images.githubusercontent.com/11215000/92254215-2fcfdc00-eeee-11ea-9a32-cbf65d3e5691.png)

**Comment by sgse** [comment]
Thank you for the fix.
