### ISSUE TITLE
Preserve Some Space at the Bottom of the Disk

### ISSUE THREAD

**Issue by RafaelTR** [ventoy/Ventoy#363]
The feature of leaving extra space is bad and confusing. Never accept the values ​​I want. It could have a slider button. Has the developer tried to use 35 GB and leave the rest? Why is this so complicated?

**Comment by RafaelTR** [comment]
"GB" values ​​are not accepted. You have to convert first to see how many "MB" you have.

**Comment by ventoy** [comment]
I think it's OK, if you  want to be very precise you need to do some calculations.

Take **rufus** for example, it provide a slider button, but the slider is just to select the size of the persistence partition (similar with reserver partition)  not the size of the main partition.

**Comment by ventoy** [comment]
You can't use GB ?  The default unit is GB.
