### ISSUE TITLE
[Feature Request] An Option in Menu for Boot from installed system (example: Windows)

### ISSUE THREAD

**Issue by soares23** [ventoy/Ventoy#37]
It would be nice if a installed system boot from usb that we have a entry on Menu for Boot directly to OS and must restart a Machine . Would be nice but not Priority for me. Can also make a restart an finish but for the future would be nice.

**Comment by ventoy** [comment]
I used to try the feature, but it's not as simple as it seems to be. Too many speical cases needed to be considered, so finally i remove it.

**Comment by soares23** [comment]
yes is not so important for now is more important that the stability for yout tool and compatiblity . Is a future that not must be for now can be an a very later state of the project is only a nice to have option not a must have.

**Comment by ventoy** [comment]
implemented in Ventoy-1.0.13
