### ISSUE TITLE
Ventoy-1.0.18-windows Release triggers Windows 10 Trojan

### ISSUE THREAD

**Issue by binarylandscapes** [ventoy/Ventoy#371]
![image](https://user-images.githubusercontent.com/32802505/89112704-a8d5a280-d41b-11ea-9933-1e147c89dbbe.png)

**Comment by kmm2** [comment]
False positive.
1018 makes no reg/fs mods on my OS.

**Comment by kosi2801** [comment]
I just submitted the 1.0.18 Ventoy2Disk.exe to Microsoft for review. Reported it as suspected false positive.

**Comment by kosi2801** [comment]
I got response from Microsoft, they confirmed the false positive and updated the signatures.
`We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions`

@binarylandscapes Does this also fix the issue for you?

**Comment by binarylandscapes** [comment]
@kosi2801 Yep just redownloaded with no issues.
