### ISSUE TITLE
可否加入EFI文件搜索引导的功能？

### ISSUE THREAD

**Issue by huangsijun17** [ventoy/Ventoy#372]
类似于搜索引导ISO文件那样，搜索EFI文件并列出以供引导。
方便直接运行“memtest64”、“EFI SHELL”等。

**Comment by ventoy** [comment]
当前版本就支持吧，你把 .efi 文件放U盘试试。不过没怎么测试过。

**Comment by huangsijun17** [comment]
VM测试成功。
