### ISSUE TITLE
Request: Azure serial console for a Ventoy VM

### ISSUE THREAD

**Issue by dcasota** [ventoy/Ventoy#373]
Hi folks,

Ventoy might become quite useful for Azure VMs, too. Actually I couldn't find out how to configure the serial console output for an Azure Ventoy VM.

Using syslinux I would have added "serial 0 115200", "serial 1 115200" and "tty1Port=com1 tty2Port=com1 logPort=none gdbPort=none" in syslinux.cfg.

Could you provide some help on this?

I've created an Azure CentOS-like VM with os disk and a managed data disk.
```
# download required packages
tdnf distro-sync -y
tdnf install -y tar wget curl sed parted dosfstools

# find last attached device
export DEVICE=$(echo /dev/`ls --indicator-style=none /sys/block/ |grep -Ev '(ram|loop|dm-|sr0)' | tail -1`)

cd /root
curl -O -J -L https://github.com/ventoy/Ventoy/releases/download/v1.0.18/ventoy-1.0.18-linux.tar.gz
tar -xzvf ./ventoy-1.0.18-linux.tar.gz
cd ./ventoy-1.0.18-linux.tar.gz
echo y > ./y
echo y >> ./y
cat ./y | ./Ventoy2Disk.sh -I -s -g $DEVICE

mkdir ./exfat
./tool/mount.exfat-fuse_64 {$DEVICE}1 ./exfat
cd ./exfat

# download the ISO here

cd ..
umount ./exfat

```
After the swap of the managed data disk with the os disk, Ventoy boots but without Azure serial console output. It would be very nice specifying the serial console port at install time.

**Comment by ventoy** [comment]
Do you mean that you want Ventoy display the menu through console?

**Comment by dcasota** [comment]
Yes. A built-in use boot option from uploaded ISOs for VMs is missing on Azure. Hence, there is no Azure built-in serial console support for scenarios like prompt before boot for an uploaded bootable ISO.
The injection plugin model of Ventoy looks promising. It would become easier implementing Microsoft Linux Integration Services components.

**Comment by ventoy** [comment]
You can try 1.0.19 and set the serial config. Refer https://www.ventoy.net/en/plugin_theme.html

**Comment by dcasota** [comment]
Yes, saw the progress for this request and already started some tests. The ventoy.json file (on the root of /dev/sdc1 where the .iso resides) filled with serial_console + 9600 setting for both ports did not work yet yesterday on my lab setup. However I have to read the manual and hints for the installation again - for sure I missed a step. I will share the next findings in these days.

**Comment by dcasota** [comment]
@ventoy Here are the findings so far.

1) I use an Azure VM with os disk and data disk. Os is VMware Photon OS 3. Ventoy is installed on the data disk before switching data disk and os disk. Afaik VMware Photon OS 3 is not on the Ventoy compatibility list yet.

2) This is the modified code

```
# download required packages
tdnf distro-sync -y
tdnf install -y tar wget curl sed parted dosfstools

# find last attached device (use carefully)
export DEVICE=$(echo /dev/`ls --indicator-style=none /sys/block/ |grep -Ev '(ram|loop|dm-|sr0)' | tail -1`)

# download and install Ventoy
curl -O -J -L https://github.com/ventoy/Ventoy/releases/download/v1.0.19/ventoy-1.0.19-linux.tar.gz
tar -xzvf ./ventoy-1.0.19-linux.tar.gz
cd ./ventoy-1.0.19
echo y > ./y
echo y >> ./y
cat ./y | ./Ventoy2Disk.sh -I -s -g $DEVICE

# mount first partition on $DEVICE
mkdir ./exfat
./tool/mount.exfat-fuse_64 ${DEVICE}1 ./exfat
cd ./exfat

# download&save an ISO
curl -O -J -L https://packages.vmware.com/photon/3.0/Rev2/iso/Update2/photon-3.0-a0f216d.iso

# set Ventoy parameters for Azure console interoperability
mkdir ./ventoy
cat << EOF1 >> ./ventoy/ventoy.json
{
    "theme": {
        "display_mode": "serial_console",
        "serial_param": "--unit=0 --unit=1 --speed=115200"
    }
}
EOF1

# cleanup
cd ..
umount ./exfat
```

3) This is the Azure serial console directory structure output before switching /dev/sdc with the os disk.
![picVentoy](https://user-images.githubusercontent.com/14890243/90311568-5c4e9480-defc-11ea-9b02-b5f2d08136c0.png)

4) Booting Ventoy, the Azure serial console still remains black.
![picVentoy2](https://user-images.githubusercontent.com/14890243/90311624-1e05a500-defd-11ea-9401-0aeb1fae22b7.png)

Remark: In serial_param the unit0 and unit1 do not have a separate speed configuration. Tests failed: a) with 9600 b) with 115200 c) using unit0 only

Setup details:
Azure VM size: Standard E4s v3 (4 vCPU, 32 GB RAM), Hyper-V generation V1, os disk = 16 GB, data disk = 16 GB, accelerated networking

The next step I've planned will be to check the output on a physical usb device and better self-help defecting from that point.
