### ISSUE TITLE
[Feature] device label for DEFAULT_SEARCH_ROOT

### ISSUE THREAD

**Issue by rotflol** [ventoy/Ventoy#376]
make the partition label for DEFAULT_SEARCH_ROOT configurable in global control plugin, defaults to ventoy

**Comment by rotflol** [comment]
device label = partition label

**Comment by ventoy** [comment]
Ventoy only support ISO file in the 1st partition and only search ISO files in the 1st partition.
So DEFAULT_SEARCH_ROOT is set to the path under the 1st partition and there is no need to set the partition label.

**Comment by rotflol** [comment]
Only 1st partition on the booted USB device? So no support for isos on other devices / partitions?
How hard would it be to implement? Is the partition label "ventoy" used?

**Comment by TimerWolf** [comment]
That would actually be very useful to have support to find every drives on the computer and select the file from any available path...

Anyways i don't think that was the way ventoy what created for..  

A side note is when the "vhd" support come as i have read in the forums will come leator to boot up virtual machines make it a lot more useful, as some of those can take a lot of space that maybe not fit the storage ventoy is used from.

**Comment by rotflol** [comment]
chainloading using grub2fm? 
my use case has a lot of isos that need to be kept up-to-date, so I tried putting those in the reserved space, but that is the wrong partition

**Comment by TimerWolf** [comment]
Not sure what you mean by that but back to the first question about "DEFAULT_SEARCH_ROOT" instead of have that it would be neat to have an "F" key to get a list of your available units outside the ventoy and possibly to select any supported file from the drive of your choice..

But again, i don't think this will happen as its not what ventoy built for.
