### ISSUE TITLE
[Feature] ing file support

### ISSUE THREAD

**Issue by TimerWolf** [ventoy/Ventoy#377]
I did try to find any information about this but i could not find this anywhere..

Anyways the possibility to boot from img files would be neat as well...

**Comment by jendalinda** [comment]
I see that some IMG files are now supported.

Is it possible to add support for the Memtest86 Free 8.4 image? That would be quite useful.
https://www.memtest86.com/download.htm

**Comment by ventoy** [comment]
This is an old issue. I will close it now.
If you still have problem with latest Ventoy release, you can reopen the issue.
