### ISSUE TITLE
Debian 10.5.0 iso's

### ISSUE THREAD

**Issue by Gyppie** [ventoy/Ventoy#385]
With the netinstall in graphical mode and testmode ends up in a "Incorrect CD-ROM detected error". The old 10.4.0 iso's still work.

**Comment by ventoy** [comment]
I have fixed it, please wait for the next release.

**Comment by ventoy** [comment]
Please try Ventoy-1.0.19

**Comment by QiangF** [comment]
I have the same error with 1.0.22

**Comment by ventoy** [comment]
Please try 1.0.24
