### ISSUE TITLE
I have an external Hard 1 terabyte installed version 1.0.13 can  not updated to any version or even see the installed version

### ISSUE THREAD

**Issue by ammar-morad** [ventoy/Ventoy#386]
I Fix IT (the ID of fat16 changed to 07 I think by it self > Changed it back to EF and it work and upgraded) thank you for no help

I have an external Hard 1 terabyte installed version 1.0.13 can  not updated to any version or even see the installed version
I use MBR cannot format all my data 150 GB to reinstall it 
![Ven](https://user-images.githubusercontent.com/69061487/89088542-5b185600-d399-11ea-80d2-da81b022abe5.png)

_Originally posted by @ammar-morad in https://github.com/ventoy/Ventoy/issues/347#issuecomment-667430019_

**Comment by ventoy** [comment]
OK
