### ISSUE TITLE
vyos 1.3 rolling release iso cant boot

### ISSUE THREAD

**Issue by 9l** [ventoy/Ventoy#388]
vyos 1.3 rolling release iso cant boot

vyos-1.3-rolling-202008110118-amd64.iso
Window 10
Virtualbox 6.1.12 BIOS and UEFI

![ventoy_vyos_1 3_rolling-202008110118-amd64 iso](https://user-images.githubusercontent.com/2160960/89916176-e7dcd280-dc29-11ea-8e2c-f335ef9af7ab.png)

**Comment by ventoy** [comment]
I have supported it, please wait for the next release.

**Comment by ventoy** [comment]
Please try Ventoy-1.0.19

**Comment by 9l** [comment]
It works!
Thank you!

**Comment by ventoy** [comment]
Good news!
