### ISSUE TITLE
Some bugs and suggestions for Ventoy (对Ventoy的一些错误和建议)

### ISSUE THREAD

**Issue by ZhuMa12345678** [ventoy/Ventoy#389]
English (英语)
Let me talk about a few more questions:
1. The Windows version of Ventoy authoring tool is very unstable and often fails during installation.
![image](https://user-images.githubusercontent.com/61312109/90106813-85471c00-dd7a-11ea-8761-eab42553b565.png)
![image](https://user-images.githubusercontent.com/61312109/90106831-8d9f5700-dd7a-11ea-90fb-87bf1260da4f.png)
And there is a bug that has not been fixed since the initial version, that is, under certain systems, if the first production fails, the program will crash the next time it is produced.
![image](https://user-images.githubusercontent.com/61312109/90106866-97c15580-dd7a-11ea-8d6e-c36e4d181dfb.png)
In addition, it is recommended to add a check box to display all devices in the program to facilitate testing. At present, every time you test in a virtual machine, you have to run the program with the command line Ventoy2Disk.exe -U parameter to install it in the virtual hard disk.
![image](https://user-images.githubusercontent.com/61312109/90106907-a445ae00-dd7a-11ea-88db-59ec55de7261.png)

2. As shown in the figure, Ventoy cannot recognize the UDF 2.50 version.
![image](https://user-images.githubusercontent.com/61312109/90106923-a9a2f880-dd7a-11ea-98b7-2f6dc720a5a1.png)
![image](https://user-images.githubusercontent.com/61312109/90107015-cf300200-dd7a-11ea-8f91-f44f8661df2a.png)
OSTA's UDF file system, and like Microsoft's NTFS and ReFS file systems, has many different versions. Although the Ventoy official website documents support the use of UDF file systems for data partitions, after actual testing, only UDF1.02-2.01 versions are supported. I hope the author has time to adapt to the UDF 2.50 specification.
In addition, a detailed tutorial on how to view the version numbers of all file systems supported in Windows can be found here: http://bbs.wuyou.net/forum.php?mod=viewthread&tid=412267&mobile=no

3. Ventoy has compatibility issues with motherboards that support booting from NTFS or exFAT UEFI.
![image](https://user-images.githubusercontent.com/61312109/90107033-d5be7980-dd7a-11ea-8dab-23ea0be4abfd.png)
At present, the boot disk produced by Ventoy adopts the first partition exFAT data area + the second partition FAT16 UEFI boot area by default, but there is a problem that some motherboard manufacturers have built-in NTFS and exFAT file system DXE drivers in the UEFI BIOS. , Because the data partition will directly boot from the exFAT partition by default before, it is impossible to boot to the Ventoy interface in the UEFI environment.
I provide two solutions to this problem:
The first is to add a setting option in the program, and change the positions of the two partitions during production, that is, the first partition is the EFI boot area, and the second partition is the data area.
The second is to keep the existing partition order unchanged and change the default exFAT file system of the data partition to the UDF file system. Since there is currently no UEFI firmware of any motherboard that can support UDF UEFI booting, this type of problem can be effectively avoided.
A universal UDF file system formatting tool for all platforms can be referred to: http://github.com/JElchison/format-udf

汉语 (Chinese)
我再说几个问题吧：
1、Windows版的Ventoy制作工具极不稳定，在安装时经常失败。
![image](https://user-images.githubusercontent.com/61312109/90107077-e40c9580-dd7a-11ea-9263-dc449e132f30.png)
![image](https://user-images.githubusercontent.com/61312109/90107087-e7a01c80-dd7a-11ea-8491-97c09562b0dc.png)
而且还有一个Bug从初版到现在一直都没修，就是在某些系统下如果第一次制作失败后下一次再制作时程序必崩溃。
![image](https://user-images.githubusercontent.com/61312109/90107098-ec64d080-dd7a-11ea-8f9e-97a62bfec303.png)
另外建议在程序里加一个显示所有设备的勾选框方便测试用，目前每次在虚拟机里测试都得要用命令行Ventoy2Disk.exe -U参数运行程序才能对虚拟硬盘制作。
![image](https://user-images.githubusercontent.com/61312109/90107109-f090ee00-dd7a-11ea-8539-943bf7b66069.png)

2、如图所示，Ventoy不能识别UDF2.50版本。
![image](https://user-images.githubusercontent.com/61312109/90107123-f555a200-dd7a-11ea-9155-7d2cdc64e005.png)
![image](https://user-images.githubusercontent.com/61312109/90107133-f8e92900-dd7a-11ea-8461-bb8295461b4d.png)
光学存储技术协会的UDF文件系统与微软的NTFS和ReFS文件系统一样都是有很多不同的版本，尽管在Ventoy官网文档中宣称支持数据分区使用UDF文件系统，但经实测只支持UDF1.02-2.01版本，希望作者抽空适配一下UDF2.50规范。
对于详解如何查看在Windows中受支持的所有文件系统的版本号教程可参考：http://bbs.wuyou.net/forum.php?mod=viewthread&tid=412267&mobile=no

3、Ventoy对于支持从NTFS或exFAT UEFI引导的主板存在兼容性问题。
![image](https://user-images.githubusercontent.com/61312109/90107156-01416400-dd7b-11ea-9499-2721ddb0a15b.png)
目前Ventoy制作出来的启动盘默认采用第一分区exFAT数据区+第二分区FAT16 UEFI启动区方案，但这样有一个问题就是某些主板厂商的UEFI BIOS中已经内置了NTFS和exFAT文件系统的DXE驱动，由于数据分区在前就会直接默认从exFAT分区上启动了导致无法在UEFI环境下引导到Ventoy界面。
对于这个问题我提供两种解决方案：
第一种是在程序里加一个设置选项，在制作时将两个分区调换一下位置，即第一分区为EFI启动区，第二分区为数据区。
第二种是保持现有的分区顺序不变，将数据分区默认的exFAT文件系统变更为UDF文件系统，由于目前没有任何主板的UEFI固件能支持UDF UEFI启动，因此可以有效地规避此类问题。
全平台通用的UDF文件系统格式化工具可参考：http://github.com/JElchison/format-udf

**Comment by ZhuMa12345678** [comment]
For Chinese users who are slow to open GitHub, click this link to view:
对于中国用户打开GitHub很慢的可点击此链接查看：
http://bbs.wuyou.net/forum.php?mod=redirect&goto=findpost&ptid=419840&pid=4119498&fromuid=566366&mobile=no

**Comment by ventoy** [comment]
1. 制作会失败这个问题确实存在，也没办法短时间内解决。每个人的环境都不太一样，只能慢慢优化。像rufus开发了十几年也是特殊情况下制作会失败，还有就是Win7/8/10系统的表现也不一样，这些都需要慢慢来了。
   崩溃的问题看你是在虚拟机下PE里面测试的，你这个PE可以共享我下，包括虚拟机的配置，我自己试试能不能出现。
  显示所有设备的选项可以增加一个。

2. UDF2.50的问题之前有网友反馈过，确实比较小众，而且grub2官方也不支持，这个得等到grub2先支持了，再适配过来。

3. 对于集成了exFAT/NTFS驱动的UEFI固件，只要第一个分区里面没有EFI目录以及.efi文件，一般也是无法启动的。可能有个别比较特殊的主板，就不再特殊适配了，可以想其他办法，比如通过EFI shell启动之类的。
