### ISSUE TITLE
Compile from source

### ISSUE THREAD

**Issue by ldnpub** [ventoy/Ventoy#39]
It would be interesting to be able to compile from the source files.
The "How To" could be added to the README.md

**Comment by filalex77** [comment]
+1 for this. Would be great for packaging as well.

**Comment by ventoy** [comment]
Sure, I will add it after I sort it out.

**Comment by ventoy** [comment]
Hi,
I have committed the build scripts and documents and updated README.md.
You can refer DOC/BuildVentoyFromSource.txt.

**Comment by ventoy** [comment]
Hi, I will close the issue now.  If you have any problem during build ventoy, you can make a new issue.
