### ISSUE TITLE
Unsuported ISo

### ISSUE THREAD

**Issue by Hasanbd756** [ventoy/Ventoy#391]
Ventoy is not working with latest windows 10 iso Version 2004 (Build 19041.264). please fix this problem.

**Comment by ChooTingFeng** [comment]
The file must not have any spaces

**Comment by Hasanbd756** [comment]
there is no space but unfortunately not working.

**Comment by Disk2019** [comment]
its working great on my side to boot Win10 build 19041.264 iso
as well
Downloaded ESD 19041.388 via http://dl.delivery.mp.microsoft.com/filestreamingservice/files/0885dbb2-d000-4b7d-a77c-ca1daddf41b3/19041.388.200710-1729.vb_release_svc_refresh_CLIENTCONSUMER_RET_x64FRE_en-us.esd & decrypting it to ISO via Abbodi1406 ESD to ISO Script Tool.

**Comment by jendalinda** [comment]
For me, the Windows 10 2004 ISO is working as expected. Both 32bit and 64bit.

**Comment by blackcrack** [comment]
19042.423 works .. installed in the last couple day's
@ventoy , i guess we can close this issue in good conscience ...

**Comment by mehargags** [comment]
I guess Ventoy cannot boot ESD files directly ?

**Comment by Testato** [comment]
I can confir that it do not work.
The .iso that i mean is the one that all can download from here:
https://www.microsoft.com/en-gb/software-download/windows10ISO

**Comment by ventoy** [comment]
This is an old issue. I will close it now.
If you still have problem with latest Ventoy release, you can reopen the issue.
