### ISSUE TITLE
Issue getting persistence with a Debian based distro

### ISSUE THREAD

**Issue by Bodanor** [ventoy/Ventoy#395]
Basically I can't get for example Kali Linux working with a persistence "dat" file. The issue is that I need to create a persistence.conf file in the partition that will contain all the data but every-time I fire up Kali-linux, the Persistence partition is missing.

**Comment by kmm2** [comment]
Kali works with persistence partition not with persistence file. Follow their guide precisely. Works for me in Ventoy...
```
root@kali:/home/kali# df -h
Filesystem          Size  Used Avail Use% Mounted on
udev                444M     0  444M   0% /dev
tmpfs                97M  1.3M   96M   2% /run
/dev/mapper/ventoy  2.9G  2.9G     0 100% /run/live/medium
/dev/loop0          2.6G  2.6G     0 100% /run/live/rootfs/filesystem.squashfs
tmpfs               483M     0  483M   0% /run/live/overlay
/dev/sdb5           4.7G   27M  4.4G   1% /run/live/persistence/sdb5
overlay             4.7G   27M  4.4G   1% /
tmpfs               483M     0  483M   0% /dev/shm
tmpfs               5.0M     0  5.0M   0% /run/lock
tmpfs               483M     0  483M   0% /sys/fs/cgroup
tmpfs               483M  8.0K  483M   1% /tmp
tmpfs                97M  8.0K   97M   1% /run/user/1000

kali@kali:~$ uname -a
Linux kali 5.5.0-kali2-amd64 #1 SMP Debian 5.5.17-1kali1 (2020-04-21) x86_64 GNU/Linux
```

**Comment by Bodanor** [comment]
That's what I thought at first but then I saw this post right here : https://github.com/ventoy/Ventoy/issues/138#issuecomment-633539332

This user got it work with the persistence.dat file. Problem is that I don't know where to put this persistence.conf file as I don't see any partition loading with ventoy.

Otherwise I managed to get it work with a physical partition too, but I wanna use that persistence plugin that Ventoy has to offer me.

**Comment by kmm2** [comment]
I tried the persistence.dat file and it also works for me...
```
kali@kali:~$ df -h
Filesystem          Size  Used Avail Use% Mounted on
udev                444M     0  444M   0% /dev
tmpfs                97M  1.3M   96M   2% /run
/dev/mapper/ventoy  2.9G  2.9G     0 100% /run/live/medium
/dev/loop0          2.6G  2.6G     0 100% /run/live/rootfs/filesystem.squashfs
tmpfs               483M     0  483M   0% /run/live/overlay
/dev/dm-1           976M   30M  880M   4% /run/live/persistence/dm-1
overlay             976M   30M  880M   4% /
tmpfs               483M     0  483M   0% /dev/shm
tmpfs               5.0M     0  5.0M   0% /run/lock
tmpfs               483M     0  483M   0% /sys/fs/cgroup
tmpfs               483M  8.0K  483M   1% /tmp
tmpfs                97M   20K   97M   1% /run/user/1000
kali@kali:~$ uname -a
Linux kali 5.5.0-kali2-amd64 #1 SMP Debian 5.5.17-1kali1 (2020-04-21) x86_64 GNU/Linux
```
Simply prep persistence.dat (fs must be labelled **persistence**) with persistence.conf in any Linux first. Then copy it to Ventoy.

**Comment by Bodanor** [comment]
I understand that fs must be labelled "persistence" as it is explained in the official documentation of Kali. But I don't get with persistence.conf. Should I first create this file before booting Kali ? Because I don't know how to mount that persistence.dat file and copy persistence.conf in it. Can you please show the steps you did to reproduce this in my own ?

**Comment by kmm2** [comment]
OK, first get one of Ventoy persistence.dat casper-rw files, boot a Linux and in the terminal type:
```
mount persistence.dat /mnt
echo "/ union" > /mnt/persistence.conf
```
Next run Disks or Gparted and re-label it to **persistence**
Unmount and copy it to Ventoy disk.

**Comment by ventoy** [comment]
Please refer to  https://www.ventoy.net/en/plugin_persistence.html

You can use `CreatePersistentImg.sh` to create a persistence.dat file with label `persistence` label with the follow command in a linux shell envrioment.
`sh CreatePersistentImg.sh -s 2048 -l persistence -t ext4` 
This will create a persistence.dat file with 2GB size in ext4 filesystem and with a persistence label.

Then as @kmm2  mentioned above 
```
mount persistence.dat /mnt
echo "/ union" > /mnt/persistence.conf
umount /mnt
```

And finally, copy the persistence.dat file to Ventoy USB drive and boot the ISO with it.

**Comment by Bodanor** [comment]
> OK, first get one of Ventoy persistence.dat casper-rw files, boot a Linux and in the terminal type:
> 
> ```
> mount persistence.dat /mnt
> echo "/ union" > /mnt/persistence.conf
> ```
> 
> Next run Disks or Gparted and re-label it to **persistence**
> Unmount and copy it to Ventoy disk.



> Please refer to https://www.ventoy.net/en/plugin_persistence.html
> 
> You can use `CreatePersistentImg.sh` to create a persistence.dat file with label `persistence` with the follow command in a linux shell envrioment.
> `sh CreatePersistentImg.sh -s 2048 -l persistence -t ext4`
> This will create a persistence.dat file with 2GB size in ext4 filesystem and with a `persistence` label.
> 
> Then as @kmm2 mentioned above
> 
> ```
> mount persistence.dat /mnt
> echo "/ union" > /mnt/persistence.conf
> umount /mnt
> ```
> 
> And finally, copy the persistence.dat file to Ventoy USB drive and boot the ISO with it.

Thank you I managed to get it worked. My problem was that I didn't know that you could mount an ".dat" file so I didn't thought about this one when I had to create a persistence.conf file. Again linux basics, you learned me something new !

**Comment by ventoy** [comment]
Good news!
