### ISSUE TITLE
Save data in Ventoy USB

### ISSUE THREAD

**Issue by and0705** [ventoy/Ventoy#397]
I have a large capacity flash device. And I installed Ventoy to boot multiple OSs, it was fine at all.
But I wonder if I could use the empty space of the USB to save my data. I mean
____
Ventoy USB
   --window...iso
   --kde...iso
   --linuxmint...iso
    ...
   --MyDATAFolder (img, music, video...)
____
Is there any problem? I appreciate your answers!

**Comment by kmm2** [comment]
No problem, save your data.

**Comment by ventoy** [comment]
Sure! You can also use it as a plain USB drive to store files and this will not affact Ventoy's function.

**Comment by and0705** [comment]
Thank you so much!
