### ISSUE TITLE
1.0.19 can not update

### ISSUE THREAD

**Issue by farsking** [ventoy/Ventoy#399]
[log.txt](https://github.com/ventoy/Ventoy/files/5094913/log.txt)
![image](https://user-images.githubusercontent.com/30152155/90609878-419b5900-e237-11ea-90df-b1233bc19bc7.png)

I have successfully installed, but after reinserting the U disk , ventoy can't recognize the upgrade

**Comment by ventoy** [comment]
Can you make a comparison test with another USB drive?

**Comment by ventoy** [comment]
This is an old issue. I will close it now.
If you still have problem with latest Ventoy release, you can reopen the issue.

**Comment by farsking** [comment]
It's works when i test with another U-drive, thanks so mach ~
