### ISSUE TITLE
Linux Distros Support issues

### ISSUE THREAD

**Issue by chromer030** [ventoy/Ventoy#4]
I tried to boot following distros , but no success :

1- ALT Linux Live :
After a lot of errors reached here :

![78903741-d5daff80-7a90-11ea-926d-62acb0e0b7eb](https://user-images.githubusercontent.com/13361552/78912863-5e5f9d00-7a9d-11ea-83b1-80d9f70366f7.jpg)

2- Austrumi 4.1.8 

can't find it's image

3- Porteus 5 KDE

can't find it's data

**Comment by ventoy** [comment]
For linux distros, Ventoy has  to adapt them one by one. These distros you test happened to be untested, sorry.  Here is the  tested distro list:  [http://www.ventoy.net/isolist.html](url)

**Comment by chromer030** [comment]
In my opinion , the priority of Linux supports can be DistroWatch Page Hit Ranking , which measures the popularity of Linux distributions : http://distrowatch.org/dwres.php?resource=popularity
According to the Tables the most hit Distros in last 12 months are these ones :

MX Linux
Manjaro 
Mint 
Debian 
Ubuntu 
elementary 
Solus 
Fedora 
Zorin 
deepin 
antiX 
KDE neon 
openSUSE 
CentOS 
Pop!_OS 
ArcoLinux 
PCLinuxOS 
Arch 
Kali 
ReactOS 
Puppy 
FreeBSD 
Lite 
Peppermint 
Mageia 
SparkyLinux 
Lubuntu 
Parrot 
Tails 
Slackware 
Ubuntu Kylin 
Xubuntu 
Q4OS 
EasyOS 
Trident 
Alpine 
Archman 
Kubuntu 
SmartOS 
Android-x86 
Void 
Ubuntu MATE 
EndeavourOS 
Red Hat 
Endless 
Bluestar 
Gentoo 
Devuan 
Feren 
OpenMandriva 
Voyager 
ClearOS 
GhostBSD 
KNOPPIX 
4MLinux 
ArchBang 
LXLE 
Netrunner 
KaOS 
Bodhi 
Nitrux 
DragonFly 
Emmabuntüs 
Ultimate 
PureOS 
BlackArch 
Clear 
NixOS 
Ubuntu Budgie 
Tiny Core 
Qubes 
Obarun 
Elive 
Kodachi 
ExTiX 
OpenBSD 
NomadBSD 
Septor 
Ubuntu Studio 
Oracle 
Robolinux 
Volumio 
Artix 
Clonezilla 
Raspbian 
Slax 
BunsenLabs 
SteamOS 
LibreELEC 
Sabayon 
ALT 
Trisquel 
ROSA 
AV Linux 
ArchLabs 
Haiku 
AUSTRUMI 
Whonix 
BackBox 
Lakka 
Simplicity 
Enso 
NuTyX 
MakuluLinux 
NetBSD 
Absolute 
Porteus 
Arya 
Calculate 
Fatdog64 
Rescatux 
Container 
GParted 
OpenMediaVault 
IPFire 
GuixSD 
SolydXK 
OpenIndiana 
Hyperbola 
SUSE 
HardenedBSD 
Pardus 
CRUX 
Runtu 
Proxmox 
Parabola 
Bedrock 
Redcore 
Exe 
LFS 
MidnightBSD 
Neptune 
SliTaz 
Zenwalk 
AcademiX 
OSMC 
Funtoo 
Univention
Debian Edu 
LinuxConsole
SuperX 
FreeNAS 
OPNsense 
Bicom 
Solaris 
Dragora 
EasyNAS 
SuperGamer 
UBports 
FuryBSD 
XigmaNAS 
BEE free 
KolibriOS 
SystemRescue 
RancherOS 
Slackel 
siduction 
FuguIta
Live Raizo
Parted Magic 
Peach OSI 
PrimTux 
RSS 
Star 
Berry 
BigLinux 
MiniNo 
CAINE
pfSense 
DuZeru 
Gecko 
MLL 
RebeccaBlackOS 
Untangle 
ClonOS 
Linuxfx 
Porteus Kiosk 
Super Grub2 
Ubuntu DP 
TENS 
batocera 
3CX 
OSGeoLive 
Pinguy 
Zevenet 
Namib 
OLPC 
Pisi 
RDS 
Zentyal 
BSDRP 
Plop 
VyOS 
Wifislax 
Freespire 
Pearl 
Zeroshell 
blackPanther 
KANOTIX 
Lunar 
Exherbo 
Kwort 
NethServer 
Omarine 
OviOS 
Elastix 
NST 
Plamo 
CAELinux 
Refracta 
ArchStrike 
GoboLinux 
Karoshi 
Linspire 
MorpheusArch 
Daphile 
Hanthana 
RISC 
Vine 
Pentoo 
CloudReady 
Secure-K 
Asianux 
BOSS 
DietPi 
LinHES 
Sophos 
Stella 
UBOS 
Cucumber 
DRBL 
EuroLinux 
Source Mage 
T2 
BlankOn 
LliureX 
Nova 
Photon 
Shark 
Thinstation 
BlueOnyx 
Grml 
Rocks Cluster 
Springdale 
Endian 
paldo 
Clu |
NexentaStor 
PLD 
TurnKey 
VenenuX 
Baruwa 
Greenie 
Hamara 
Openwall 
Securepoint 
Smoothwall 
ToOpPy 
YunoHost 
FreePBX 
FreedomBox 
SELKS 
SME Server 
Omoikane 
Pardus Topluluk 
Webconverger 
tuxtrans 
BitKey 
OB2D 
openmamba 
Anarchy 
APODIO 
Mangaka 
ForLEx 
Recalbox

Ventoy supports most of them and support for others should be added in future releases if it will be possible.

**Comment by ventoy** [comment]
Yes, although there will be many difficulties, I will do my best to support all releases in DistroWatch, which is also my goal. As for the priorities, what I am doing now is exactly in line with your thoughts.

**Comment by chromer030** [comment]
Great , i will help with testing most of latest versions of this 250 Distros in UEFI64 mode under my Kabylake , Skylake  and Haswell PCs and report here success and failure attempts one.

**Comment by ventoy** [comment]
Thank you very much! Limited to my test environment, I can only test them in Virtual Machine or My old laptop, so this is really a great help for me!  Thanks again!

BTW, Ventoy 1.0.04 was released now, and I added a simple implement of the feature --- Load ISO to ram and run. 
The feature now is only for test, it may be unstable or may have some bugs. You can make a try.

When the boot menu was shown, press F1 and there will show a red word "MEMDISK" on the right top. 
After that, select the iso and boot it. Take care about the iso and ram size. Good luck!

**Comment by chromer030** [comment]
Hi , I tested MEMDISK and worked well , in a new issues i share my tests results.
Thank you very much.

**Comment by LuboGD** [comment]
Thanks. In reference to this comment, https://github.com/ventoy/Ventoy/issues/4#issuecomment-611916410 and making Ventoy.

Glad to see antiX works, including using ISOs made by their iso-snapshot tool for system backup. Awesome.

Can I request you take a look at Adelie Linux please? It is a soft fork of Alpine, so some things should be quite similar to that. But it does not boot fully with Ventoy. I seem to recall it boots to grub OK, but fails to load the files it needs from the ISO, so the boot stops.

They do provide a live ISO, which can be burned to USB, but in some cases it is more useful to have Ventoy load the original ISO, so you don't format the USB flash over and over.
