### ISSUE TITLE
Boot WinPE needs to read from drive

### ISSUE THREAD

**Issue by ronen1n** [ventoy/Ventoy#40]
When I boot WinPE (like "Sergei Strelec's WinPE") that have software that he reads from drive it says that the file is missing because the iso is not mounted after the OS loaded
And I checked Acronis iso and it's not working too I think it's the same issue

**Comment by ventoy** [comment]
For windows, Ventoy works well with MSDN standard iso files.
As for PE, because there are many many types of WinPE, so it's very dificult for Ventoy to support all of them.
So I introduced "**Ventoy Compatible**" concept. 
I hope the PE can contain some special process for Ventoy, I have provided some tool to get the iso file information under PE, so the PE can mount the right iso file as the source media.

**Comment by ronen1n** [comment]
> For windows, Ventoy works well with MSDN standard iso files.
> As for PE, because there are many many types of WinPE, so it's very dificult for Ventoy to support all of them.
> So I introduced "**Ventoy Compatible**" concept.
> I hope the PE can contain some special process for Ventoy, I have provided some tool to get the iso file information under PE, so the PE can mount the right iso file as the source media.

Thanks for the quick answer 
I asked the WinPE owner to add it to the ISO I hope he will
Its very good software and go in goo direction (simple and professional) it reminds me of xboot but simpler
Thank you again for the software

**Comment by soares23** [comment]
@ronen1n  for WinPE10_8_Sergei_Strele iso  you must copy the SSTR to the root of yout USB drive than all apps are avalaible and working. Is a workaround for now but if the developer integrate it to iso is better but for now you can do that with copy the SSTR to root of your usb device.

**Comment by ronen1n** [comment]
I copied only this folders 78SETUP,DriverPacks,Fonts,MInst and USER inside of SSTR to the root (with the SSTR folder) and delete it from the iso (except from the Fonts folder and other folder that i didn't copy) and it works great
Thank you
