### ISSUE TITLE
CLI不起作用

### ISSUE THREAD

**Issue by LittleDeng1** [ventoy/Ventoy#400]
![image](https://user-images.githubusercontent.com/62782358/90726302-1296ed00-e2f4-11ea-949b-b79138fb1372.png)
![image](https://user-images.githubusercontent.com/62782358/90726574-889b5400-e2f4-11ea-8379-8de364f2a5b5.png)
愣是没看出哪有问题 这两个打法都还是GUI启动

**Comment by ventoy** [comment]
语法错误太多，应该是这样：
```
{
    "control": [
        { "VTOY_DEFAULT_MENU_MODE": "0" },
        { "VTOY_MENU_TIMEOUT": "10" },
        { "VTOY_DEFAULT_IMAGE": "/WePE_64_v2.0.iso" }        
    ],

    "theme": {
        "display_mode": "CLI"
    }
}

```

**Comment by LittleDeng1** [comment]
@ventoy 我还是太蔡了 然后我发现你这文件名大小写打错(区分大小写) 导致默认镜像不起效 这算是个新issue马
谢谢 btw

**Comment by ventoy** [comment]
正常的，Ventoy就是区分大小写的。
