### ISSUE TITLE
Support Internal SSD Too

### ISSUE THREAD

**Issue by Disk2019** [ventoy/Ventoy#401]
it will be good if Ventoy a super USB boot tool will support internal SSD , NVME as i have found that till date only usb device is supported.
AIOBOOT , Multiboot Toolkit etc etc all supports Internal HDD, SSD , NVME but Ventoy isnt .
I Hope Dev of this tool will take my suggestion under consideration & will update it in next release too.

**Comment by ventoy** [comment]
Run  `Ventoy2Disk.exe  -U`  in cmd.exe and this will list all the disk.

**Comment by Disk2019** [comment]
Query Solved . Thanks a lot.
