### ISSUE TITLE
磁盘无法显示

### ISSUE THREAD

**Issue by ieew** [ventoy/Ventoy#402]
我先是使用ventoy-windows正常安装了ventoy,并且没有异常提示，然后在 “此电脑” 中右键u盘之后对它格式化，这时候系统卡住了，等了一段时间后，u盘就无法正常显示出来了，具体表现为：
系统的磁盘管理中可以发现这个磁盘，但是一个分区都不显示(有分配盘符号)
DiskGenius中不显示u盘
设备管理器中驱动正常，ventoy中也无法显示该u盘
以下是实际情况的图片
![image](https://user-images.githubusercontent.com/44091335/90756352-d624ba80-e30e-11ea-9c5a-a720e790b340.png)
![image](https://user-images.githubusercontent.com/44091335/90756401-e9378a80-e30e-11ea-8c8f-9a946e283cc4.png)
我不知道这种情况应该如何处理，因为我能使用的磁盘管理软件都无法对它进行任何操作。

**Comment by ventoy** [comment]
重启电脑之后试试呢？

**Comment by ventoy** [comment]
This is an old issue. I will close it now.
If you still have problem with latest Ventoy release, you can reopen the issue.
