### ISSUE TITLE
1.0.19 broke booting .efi files

### ISSUE THREAD

**Issue by gigaplex** [ventoy/Ventoy#403]
Version 1.0.14 was able to successfully boot the UEFI shell (https://github.com/tianocore/edk2/blob/UDK2018/ShellBinPkg/UefiShell/X64/Shell.efi), however this does not work on 1.0.19. I get the error:

No bootfile found for UEFI!
Maybe the image does not support X64 UEFI!

(which is ironic because it is the X64 UEFI shell)

**Comment by gigaplex** [comment]
Note: it works fine in 1.0.18 too.

**Comment by gigaplex** [comment]
I tried rolling back the efi_common_menuentry function in grub.cfg back so it chainloads the .efi file directly rather than using ventoy_x64.efi, and it worked fine.

**Comment by ventoy** [comment]
What about the latest release?

**Comment by gigaplex** [comment]
The latest version (1.0.27) doesn't even attempt to add the EFI shell to the boot menu list.

**Comment by ventoy** [comment]
OK
