### ISSUE TITLE
Fedora 32 boot failure

### ISSUE THREAD

**Issue by mia0x75** [ventoy/Ventoy#41]
LXDE version:

https://download.fedoraproject.org/pub/fedora/linux/releases/32/Spins/x86_64/iso/Fedora-LXDE-Live-x86_64-32-1.6.iso

**Comment by ventoy** [comment]
Which version do you tested?
There is an issue in 1.0.07 with Fedora.
I tested this iso file with Ventoy 1.0.08 in my laptop, and it worked well.

**Comment by danielbgto** [comment]
Hi!
I have tested with Ventoy 1.0.08 Fedora 32 Workstation and F32 Cinnamon Spin too and it's not booting on my Thinkpad 470p.
I have tested two Windows 10 ISOs of Windows 2019 LTSC which also didn't boot.
I have succeeded only with Ubuntu and Ubuntu based OS/ ISOs.

**Comment by ventoy** [comment]
Can you give more detail about the failure.  Maybe some photos?

**Comment by danielbgto** [comment]
Unfortunately there is no real error messages - just a black screen. The computer itself is not frozen but nothing more than black monitor. If I press Ctrl+ALt+Del - it restarts. I was waiting 10 minutes every.  

Fedora is finishing with this:

![IMG_20200503_181524](https://user-images.githubusercontent.com/5525957/80918081-bf605500-8d6b-11ea-8193-048b4cc6e120.jpg)

![IMG_20200503_181623](https://user-images.githubusercontent.com/5525957/80918084-c0918200-8d6b-11ea-90f1-1dacb6f9341b.jpg)

![IMG_20200503_181633](https://user-images.githubusercontent.com/5525957/80918087-c12a1880-8d6b-11ea-90fe-b9ef647f6418.jpg)

Windows 10 is finishing with this:

![IMG_20200503_181719](https://user-images.githubusercontent.com/5525957/80918089-c1c2af00-8d6b-11ea-8995-3eed3bfc6d40.jpg)

**Comment by mia0x75** [comment]
LXDE error message

![IMG_20200504_210632](https://user-images.githubusercontent.com/5111356/80968903-56500e80-8e4b-11ea-9205-039bfcfb4cdc.jpg)

**Comment by danielbgto** [comment]
I have a good news. I have upgraded from 1.0.8b2 to 1.0.8 and the problems from my tests are gone. Original Windows 10 ISOs are booting but custom ones no.

**Comment by theraw** [comment]
i'm having same problem as @danielbgto black screen and it doesn't boot to ventoy exactly this https://user-images.githubusercontent.com/5525957/80918087-c12a1880-8d6b-11ea-90fe-b9ef647f6418.jpg

**Comment by chromer030** [comment]
I tested Fedora XFCE Rawhide via Ventoy 1.0.09 BETA1 and everything was fine under both Skylake/Haswell.

**Comment by mia0x75** [comment]
Fixed on 1.0.9.

**Comment by theraw** [comment]
@mia0x75 i just tested the latest version install + uploaded 2 iso on usb alpine linux + ubuntu and i got the same black screen as last time.

and i have no idea how to debug this!
