### ISSUE TITLE
Grub2 throws error when specifying a VTOY_DEFAULT_IMAGE while one or more ISOs exist in subdirectories

### ISSUE THREAD

**Issue by Jefferderp** [ventoy/Ventoy#426]
Hello!

This bug is a bit convoluted, but I've managed to reproduce it consistently.

My full `/ventoy/ventoy.json`:
```json
{
	"control": [
		{ "VTOY_DEFAULT_MENU_MODE": "1" },
		{ "VTOY_FILT_DOT_UNDERSCORE_FILE": "1" },
		{ "VTOY_DEFAULT_SEARCH_ROOT": "/ISO" },
		{ "VTOY_MENU_TIMEOUT": "15" },
		{ "VTOY_DEFAULT_IMAGE": "/ISO/foo.iso" }
	]
}
```
The issue specifically is that when specifying `VTOY_MENU_TIMEOUT` and `VTOY_DEFAULT_IMAGE` as seen above, in combination with the following directory structure:
```
/ISO/
├── Linux/
│   └── bar.iso
└── foo.iso
```

upon booting Ventoy and waiting 15 seconds for the default image to be selected, `grub2` throws the following error (seen on-screen and transcribed exactly):

```
Booting `DIR        [Linux]'

  Failed to boot both default and fallback entries.
Press any key to continue...
```

The error consistently occurs when one or more ISO files (in my case, `bar.iso`) exist in `/ISO/Linux/`, or in any directory that exists below the root directory `/ISO/`. In other words, the error will not occur if there are no sub-directories containing ISOs.

It's not relevant whether my default image (`foo.iso`) exists in `/ISO/Linux/`, or in the root `/ISO/`. Simply the presence of *any* ISO in `/ISO/Linux/` results in failure to auto-boot, followed by the above error.

*Tested and reproducible on Ventoy versions 1.18 and 1.19.*

I've had no problems with Ventoy until this point, enjoying it multiple times a week. My ultimate goal is to specify a default image that can be headlessly booted for purposes of hosting an SSH server/etc.

Thanks for this excellent software!

**Comment by ventoy** [comment]
It was described in the document.
![image](https://user-images.githubusercontent.com/59477474/91525067-3df08c00-e933-11ea-80cc-7422315abb89.png)

**Comment by Jefferderp** [comment]
My apologies. I remember seeing that, but must have mis-read.

In the future, would it be possible to implement VTOY_DEFAULT_IMAGE with TreeView? Perhaps by not traversing directories, and only considering images located in the root?

Thanks very much.
