### ISSUE TITLE
Memdisk Failed To Boot ArchLinux UEFI

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [ventoy/Ventoy#432]
Memdisk can boot ArchLinux on BIOS mode. But failed to boot on UEFI mode

**Comment by ventoy** [comment]
Memdisk mode is very suitable for WinPE (without external programs), various Live CD, Vmware ESXi and all other small distros. The characteristics of this type of system are: the image is small (hundreds of MB), and there is no need to mount the image after startup.

So Memdisk doesn't support ArchLinux. Memdisk is only for LiveCD.

**Comment by BL4CKH47H4CK3R** [comment]
I mean ArchLinux memdisk liveboot works on bios mode but not on uefi mode
