### ISSUE TITLE
Set the keyboard layout, language and timezone in the booted operating system

### ISSUE THREAD

**Issue by probonopd** [ventoy/Ventoy#437]
It would be very useful if one could configure Ventoy to pass the keyboard layout, language and timezone in the booted operating system. This way, all operating systems booted by Ventoy would use the same keyboard layout, language and timezone.

Since Ventoy already has a mechanism to pass information from Ventoy to the booted operating systems, I hope this is possible, at least for "Ventoy Compatible" operating systems.

**Comment by ventoy** [comment]
That's not Ventoy's work.
Ventoy only pass the ISO file's location information to the OS.  The information is necessary for the OS to continue boot.

**Comment by probonopd** [comment]
I understand, so I guess it would need to be done as part of a customization script that runs during the boot process.
