### ISSUE TITLE
where do binary files come from?

### ISSUE THREAD

**Issue by soloturn** [ventoy/Ventoy#438]
can you please explain a little bit where the binary files in the repository come from, or how to create and verify them?

**Comment by DX37** [comment]
> can you please explain a little bit where the binary files in the repository come from, or how to create and verify them?

Dude, your answer is literally under your nose. In README.
https://github.com/ventoy/Ventoy/blob/master/DOC/BuildVentoyFromSource.txt

**Comment by DX37** [comment]
These binaries comes from another open source projects. You can check them out by links in txt file above.
