### ISSUE TITLE
Selected boot image did not authenticate.

### ISSUE THREAD

**Issue by ghost** [ventoy/Ventoy#439]
Hello,

I am trying to install Windows with GPT partition style. After selecting the USB on boot, system gives the following error:

**Error:**
"Selected boot image did not authenticate. Press Enter to continue."

After pressing Enter, system boot directly into installed OS.

Ventoy version: 1.0.19
Copied ISO partition style: GPT
USB: contains only one iso
Secure boot: enabled

What could be the possible reasons? How does Ventoy manage Secure boot on devices. Do I need to disable secure boot first?

**Comment by ventoy** [comment]
Disable Secure Boot option in BIOS is the simplest way or you can refer to https://www.ventoy.net/en/doc_secure.html

**Comment by ValdikSS** [comment]
https://github.com/ventoy/Ventoy/issues/676#issuecomment-790186902

**Comment by Kareshi0** [comment]
I am facing the same problem with secure boot disabled

Boot Image: Ubuntu 20.04 LTS
Partition Style: GPT
USB: contains only one iso

**Comment by ventoy** [comment]
This is an old issue. I will close it now.
If you still have problem with latest Ventoy release, you can reopen the issue.

**Comment by keesse** [comment]
Ventoy 1.0.95, had the same issue with a HP Laptop, installing the key like described here https://www.ventoy.net/en/doc_secure.html worked for me!

**Comment by huoyan1231** [comment]
I encountered the same problem, but due to time constraints, I was unable to conduct further testing.
