### ISSUE TITLE
F2 -> Halt attempts to halt, then freezes

### ISSUE THREAD

**Issue by milochadam** [ventoy/Ventoy#442]
It gets stuck with text
```
System is halting ...

_
```

I tried to halt with GRUB installed on my laptop by pressing `c` in GRUB menu and it works fine.

Ventoy version: 1.0.19
USB stick flashed with GPT option

**Comment by ventoy** [comment]
F2 Halt is just run halt command

```
menuentry Halt --class=power_halt {
    echo -e '\n\nSystem is halting ... \n'
    sleep 1
    halt
}
```

**Comment by milochadam** [comment]
It seems to halt correctly now (3 recent tries in a row).
This might be a bug in GRUB:
https://bugs.launchpad.net/ubuntu/+source/grub2/+bug/720364
https://bugs.launchpad.net/ubuntu/+source/grub/+bug/220543
or something with my BIOS settings, though the only thing I changed in the meantime was boot order to select the USB and `Legacy first -> UEFI first` option. Other than that I've been changing `menu_class` in ventoy.json but I suppose that can't have possibly fixed that.
