### ISSUE TITLE
Unattended Windows ISO's not boot !

### ISSUE THREAD

**Issue by last0tt0man** [ventoy/Ventoy#449]
Hi ;

I'm tested and used Ventoy project long time.  

Thanks your efforts and making this project.

Some windows unattended ISO's boot error. 

"Silent Windows ISOS"Windows could not apply the Windows PE bootstrap setting specified in the unattended answer file. "

![image](https://user-images.githubusercontent.com/30460524/91683850-6dcfa780-eb5e-11ea-85ba-30fc931010c6.png)

**Comment by blackcrack** [comment]
maybe a to hugh USB-Stick ? check it with 8Gig, 16 Gig and 32 Gig.. different Mobo's 
supporting different Sticksize, depending on the manufacturer and age of the Bios..

**Comment by ventoy** [comment]
In this point, press `shift+F10` to lunch cmd.exe, and use `diskpart` to see whether you USB disk can be seen inside the PE envrioment. Maybe your Win7 ISO miss some driver (e.g. USB3.0).
