### ISSUE TITLE
ventoy gui for linux

### ISSUE THREAD

**Issue by realsifocopypaste** [ventoy/Ventoy#450]
please provide us with gui for ventoy linux

thanks

**Comment by blackcrack** [comment]
why do you it not programming in QT ?

i want, i want , i want.. you do you not by self ?

**Comment by duck7000** [comment]
Not everyone has programming skills..

**Comment by BeatLink** [comment]
I am currently working on such a thing, but I require the ventoy linux script to be able to be noninteractive I am waiting on the developer response from #504

**Comment by BeatLink** [comment]
I can also use this issue to track my progress and development

**Comment by BeatLink** [comment]
The repository will be hosted here, until the gui is complete and can be integrated in the project https://github.com/BeatLink/Ventoy-GTK

**Comment by BeatLink** [comment]
I will be using Python and GTK with Glade GUI Builder to design the interface

**Comment by BeatLink** [comment]
This is a screenshot from the current UI window:

![image](https://user-images.githubusercontent.com/47278150/95007440-ac310a00-05d5-11eb-8c79-1fe3c2bd5ec4.png)

I already have code to display a menu of removable devices from a previous project, so that is already sorted. The dropdown list will present removable usb devices with their manufactuer name, model name and size

**Comment by BeatLink** [comment]
This is what the menu looks like:

![image](https://user-images.githubusercontent.com/47278150/95007463-f619f000-05d5-11eb-9448-6c6e19e9a33a.png)

**Comment by BeatLink** [comment]
One thing not shown in the screenshots would be the behavior if ventoy was already installed. The GUI would then present two buttons instead: one to update the existing ventoy installation and another to remove the ventoy installation and format the drive

**Comment by BeatLink** [comment]
Another thing i could add was a dropdown to set the units for the space to preseve, whether GB or MB

**Comment by blackcrack** [comment]
maybe could you create a self decompress/executed File together with the ventoy f.L. (/tmp of the user)
just as idea...

**Comment by BeatLink** [comment]
Hmm, sounds good. I was thinking of just including the linux tarball and script inside the app, or download it at runtime. I do want #504 to be solved first though

**Comment by ventoy** [comment]
Ventoy 1.0.36 release with Linux GUI based on web browser.
https://www.ventoy.net/en/doc_linux_webui.html

**Comment by BeatLink** [comment]
Oh cool! So this issue can be closed then?

**Comment by ventoy** [comment]
Ventoy-1.0.52 release with native Linux GUI
https://www.ventoy.net/en/doc_linux_gui.html
