### ISSUE TITLE
麻烦大佬有时间支持一下x86架构OpenWrt的IMG文件

### ISSUE THREAD

**Issue by huanghuangge** [ventoy/Ventoy#453]
发现这两次更新的版本开始支持img文件了，所以希望大佬支持一下openwrt，软路由用得人很多，估计很多人都希望用上，感谢！

**Comment by ventoy** [comment]
我理解，这种应该会长时间运行的，U盘插上就不会再拔出来了，应该找个专门的U盘来制作成启动盘使用，并不适合Ventoy这种方式。

**Comment by ventoy** [comment]
OpenWrt 的img文件内的kernel不支持加载 dm.ko, 无法支持。

**Comment by 1715173329** [comment]
> OpenWrt 的img文件内的kernel不支持加载 dm.ko, 无法支持。

选上 kmod-dm 这个软件包即可

**Comment by ventoy** [comment]
@huanghuangge @1715173329 
最新的 1.0.41 版本支持 OpenWrt IMG文件。参考 https://www.ventoy.net/cn/doc_openwrt.html

**Comment by 1715173329** [comment]
给大佬点赞👍
