### ISSUE TITLE
deepin中安装提示/dev/sdb1 is a partition, please use the whole disk

### ISSUE THREAD

**Issue by libsgh** [ventoy/Ventoy#454]
deepin v20中安装Ventoy 1.0.20提示/dev/sdb1 is a partition, please use the whole disk

**Comment by ventoy** [comment]
`sudo  sh Ventoy2Disk.sh  /dev/sdb`

Ventoy 不能安装在某个磁盘的分区上，Ventoy必须独占整个磁盘，重新分区格式化。 
所以参数要传  `/dev/sdb`  不能是  `/dev/sdb1`

**Comment by libsgh** [comment]
> `sudo sh Ventoy2Disk.sh /dev/sdb`
> 
> Ventoy 不能安装在某个磁盘的分区上，Ventoy必须独占整个磁盘，重新分区格式化。
> 所以参数要传 `/dev/sdb` 不能是 `/dev/sdb1`

多谢问题解决啦～
