### ISSUE TITLE
PheonixOS can't be installed.

### ISSUE THREAD

**Issue by kuppo** [ventoy/Ventoy#455]
Ventoy version: Ventoy 1.0.20 release
Ventor installation settings: GPT partition table, no secure boot, default partition settings.
USB drive: SanDisk Cruzer Blade (16GB)
PheonixOs iso: PhoenixOSInstaller_v3.6.1.564_x64.iso

It is said that PheonixOS v3.6.1.564 iso is supported since Ventoy 1.0.19. But I failed on the installation. I could boot into ventoy and see the iso file, then loaded it and enter into the PheonixOS grub interface, I chose PhoenixOS but the terminal alwsy show "Detecting PheonixOS installation....." and lots of ellipses dots, the kernel and the image disk could be loaded but seems failed to find the root device, so it always showed dots.

I entered the Grub configuration for PheonixOS, it showed that the root device is /dev/rom, but I don't think this is right for ventoy.

Any ideas?

**Comment by ventoy** [comment]
Please do a test:
In ventoy's boot meun, press c to enter shell and run this cmd:
`vtbreak 0 1`
press enter to run and press ESC to return, then select the iso and boot it.

**Comment by ventoy** [comment]
It's not a workaround, I just want to see the debug info printed in the screen after open the debug flag.

**Comment by vqsld** [comment]
I can install it，maybe your graphics card doesnt fit？

**Comment by kuppo** [comment]
@ventoy I didn't get any debug info on the screen, everything happened was just like before.

@vqsld I don't think it is related to the graphic card, but anyhow I will try to remove the AMD car I have and try it again.

Also I will try it on another machine.

**Comment by kuppo** [comment]
I now know what was the problem.

My PC was a pure UEFI loader. So when I loaded Ventoy, it was default UEFI, so as to boot into the PhoenixOS iso. That way the PhoenixOS would directly boot into a live CD mode, there was no way to install it.

From PhoenixOS's instruction, it clearly says it supports UEFI installation, but I can. Maybe there is something wrong with the instructions.

When I chose the legacy mode, I can install it.

Please consider close this. I really appreciate your help.

**Comment by vqsld** [comment]
> I now know what was the problem.
> My PC was a pure UEFI loader. So when I loaded Ventoy, it was default UEFI, so as to boot into the PhoenixOS iso. That way the PhoenixOS would directly boot into a live CD mode, there was no way to install it.
> From PhoenixOS's instruction, it clearly says it supports UEFI installation, but I can. Maybe there is something wrong with the instructions.
> When I chose the legacy mode, I can install it.
> Please consider close this. I really appreciate your help.

But I can install PhoenixOS on my TIMI laptop and mac……
