### ISSUE TITLE
Feature Request: support DebianInstaller/Preseed

### ISSUE THREAD

**Issue by zend** [ventoy/Ventoy#456]
Preseeding is a way to automate the Debian installer procedure, it is useful for distros based on Debian. https://wiki.debian.org/DebianInstaller/Preseed

Atzlinux (https://www.atzlinux.com/) is heavily rely on this Preseed feature. Without this feature, a atzlinux ISO in ventoy will act like a original Debian ISO, ignoring all the features atzlinux offers.

The preseed file of atzlinux: https://gitee.com/atzlinux/debian-cn/blob/apt-install/isodvd/profiles/atzlinux-amd64-xall.preseed

Thank you.

**Comment by DX37** [comment]
Did you read [documentation](https://www.ventoy.net/en/plugin_autoinstall.html)?
It literally says, that Ventoy support Debian/Ubuntu preseed installation through Auto Installation Plugin.
`/ventoy/ventoy.json`:
```
{
    "auto_install": [
        {
            "image": "/ubuntu-16.04-server-amd64.iso",
            "template": "/ventoy/script/ubuntu_server.seed",
            "autosel": 1
        }
    ]
}
```

**Comment by zend** [comment]
Thanks @DX37 for the information.

But the `auto_install` section in the `/ventoy/ventory.json` is a way to do auto-installation with the original ISO file. For the already recreated ISOs, the best way is recognize the preseed files in the ISO, not requiring a new config for it.

As a normal user, I can burn the ISO to a USB disk and enjoy the automated installation, why I can't just throw it to ventoy and enjoy the same thing?

**Comment by dylanmtaylor** [comment]
> If you want to test now, you can update this file

If the fix is in master, you can also grab the latest CI test build and run that from https://github.com/ventoy/Ventoy/actions

**Comment by zend** [comment]
Thanks
