### ISSUE TITLE
"losetup" and "mksf" not present in OpenSUSE

### ISSUE THREAD

**Issue by RafaelLinux** [ventoy/Ventoy#457]
I tried "sh CreatePersistentImg.sh -s 2048 -t ext4" but after near one minute, script stop, showing:

`
2048+0 registros leídos
2048+0 registros escritos
2147483648 bytes (2,1 GB, 2,0 GiB) copied, 27,0385 s, 79,4 MB/s
CreatePersistentImg.sh: línea 68: losetup: no se encontró la orden
CreatePersistentImg.sh: línea 70: losetup: no se encontró la orden
CreatePersistentImg.sh: línea 72: mkfs: no se encontró la orden
CreatePersistentImg.sh: línea 76: losetup: no se encontró la orden
`
I tried to find "losetup" and "mkfs" in OpenSUSE repositories, but they are not available.

How could I fix this withoout compiling?

Thank you

**Comment by azisnaufal** [comment]
Hi!
I just wanted to tell you.
losetup is available, but as root. Not as average user.

**Comment by RafaelLinux** [comment]
I see. Doing a "sudo" it worked.

Thanks azisnaufal!

**Comment by ventoy** [comment]
Good news!
