### ISSUE TITLE
Boot Manager skips to default windows partition

### ISSUE THREAD

**Issue by omangbaheti** [ventoy/Ventoy#458]
Hardware: Acer Nitro 5 AN515-52
BIOS: UEFI, secure disabled
Ventoy flash drive doesnt boot even though it was installed with 0 errors. Instead the boot manager skips to my default windows partition.

**Comment by ventoy** [comment]
1. Please run Ventoy2Disk.exe again and see whether the version inside the disk will be shown
2. Please make sure that secure boot is closed 
3. You can try GPT partition style

**Comment by omangbaheti** [comment]
![image](https://user-images.githubusercontent.com/60500898/92319779-7ed65800-f039-11ea-8d85-7f767f8873c6.png)
2. I tried booting ith secure boot disabled and enabled.
3. Tried formatting my flashdrive to GPT but it still did not work
