### ISSUE TITLE
Parabola fails to boot with systemd-boot and refind

### ISSUE THREAD

**Issue by Megver83** [ventoy/Ventoy#459]
Hi, I'm the developer behind the Parabola OpenRC LXDE ISO (the one in the Ventoy tested ISOs list page), which uses refind for EFI booting. I discovered that the ISOs which use systemd-boot simply failed with the same error as #124, and sometimes with refind too, although this issue is a bit more complex.

**TL;DR:** systemd-boot always fails, refind works when the `.efi` binary is located in `/EFI/boot` in the ISO but fails when on `/EFI/BOOT`, and grub always works. Note that these problems only happen with Ventoy in EFI mode, the ISOs don't have this issues with BIOS or  with EFI when booting them without Ventoy.

Long story: Parabola is based in Arch, and the tools we use for building our ISOs are based on Arch's scripts too. Until recently, Arch/Parabola used `/EFI/boot/bootx64.efi` as the EFI bootloader (Arch always used systemd-boot, Parabola uses it too but for its OpenRC ISOs it uses refind, which has the same location and name for its `.efi` file).

The issue here is really mind-blowing to me. Arch Linux boots fine with systemd-boot but Parabola fails, which doesn't make sense to me as they are basically the same. Then I started to create various Parabola and Arch ISOs to try different things. At first I thought it could be a problem with the kernel, as Arch with the Linux-libre kernel (the one used in Parabola) failed, but Parabola with the Arch kernel didn't work so that really made my brain explode. This, plus other things I tried (like using Arch's systemd in a Parabola ISO instead of Parabola's, as we have our own systemd build), simply didn't work.

The second crazy thing is the issue with refind. It worked fine until Arch started to use `/EFI/BOOT` as the bootloader directory insted of `/EFI/boot` like before. This made refind fail with the same error as with systemd-boot. However, using lowercase instead of uppercase made it work again. I can't understand why.

Then, just to be sure, I tried with grub. This one went flawlessly, absolutely no problems. It works always, and doesn't have the same issue as refind.

If you wish to try these ISOs, tell me, right now I'm uploading them to my Nextcloud cloud.

**Comment by ventoy** [comment]
Ventoy do many special treatment for specific distros.
https://github.com/ventoy/Ventoy/blob/master/INSTALL/grub/grub.cfg
You can find something about parabola in the cfg file above.

You can share me some ISO files with problem for test.

**Comment by Megver83** [comment]
@ventoy thanks for the fast answer. I don't see anything strange in Parabola's specific configurations. It should be basically the same as Arch's, but with the refind things, which are there. Maybe I would change "boot" in [this line](https://github.com/ventoy/Ventoy/blob/48a1b80be0258bedbb558bd009f4f143d87af47d/INSTALL/grub/grub.cfg#L502) with "BOOT", but idk if that will solve the refind issue (adding another conditional that uses the uppercase boot dir aside from the lowercase one is preferred, to maintain compatibility between new and old Parabola ISOs). Anyways, the systemd-boot problem is a total mystery to me.

Here's my public folder with the ISOs, categorized by their EFI bootloaders:
* grub: all these ISOs work
* refind: the 2020.09.03 ISOs work (they use `/EFI/boot`), the 2020.09.04 one doesn't (uses `/EFI/BOOT`)
* systemd-boot: none of these work

I'm open to build new ISOs with tweaks that you request to me, if necessary.

https://nc.nl.tab.digital/s/GmHiXZQbGTT58ka

**Comment by Megver83** [comment]
I think that the problem could be this:

```
        if [ -d (loop)/loader/entries ]; then
            vt_linux_get_main_initrd_index vtindex
            
            if [ -d (loop)/arch ]; then
                if [ -f (loop)/arch/boot/x86_64/archiso.img ]; then
                    vt_add_replace_file $vtindex "EFI\\archiso\\archiso.img"
                elif [ -f (loop)/boot/initramfs_x86_64.img ]; then
                    vt_add_replace_file $vtindex "boot\\initramfs_x86_64.img"
                fi
            elif [ -f (loop)/EFI/BOOT/initrd.gz ]; then
                vt_add_replace_file $vtindex "EFI\\BOOT\\initrd.gz"
            elif [ -f (loop)/loader/entries/thinstation.conf ]; then
                vt_add_replace_file $vtindex "boot\\initrd"
            elif [ -f (loop)/loader/entries/pisi-efi-x86_64.conf ]; then
                vt_add_replace_file $vtindex "EFI\\pisi\\initrd.img"
            fi
        elif [ -d (loop)/EFI/boot/entries ]; then
            if [ -f (loop)/parabola/boot/x86_64/parabolaiso.img ]; then
                vt_add_replace_file 0 "EFI\\parabolaiso\\parabolaiso.img"
            elif [ -f (loop)/hyperbola/boot/x86_64/hyperiso.img ]; then
                vt_add_replace_file 0 "EFI\\hyperiso\\hyperiso.img"
            fi
        elif [ -e (loop)/syslinux/alt0/full.cz ]; then
            vt_add_replace_file 0 "EFI\\BOOT\\full.cz"            
            set FirstTryBootFile='@EFI@BOOT@grubx64.efi'
        fi
```

There should be a piece like this, but for Parabola:

```
            if [ -d (loop)/arch ]; then
                if [ -f (loop)/arch/boot/x86_64/archiso.img ]; then
                    vt_add_replace_file $vtindex "EFI\\archiso\\archiso.img"
                elif [ -f (loop)/boot/initramfs_x86_64.img ]; then
                    vt_add_replace_file $vtindex "boot\\initramfs_x86_64.img"
                fi
            elif [ -f (loop)/EFI/BOOT/initrd.gz ]; then
                vt_add_replace_file $vtindex "EFI\\BOOT\\initrd.gz"
            elif [ -f (loop)/loader/entries/thinstation.conf ]; then
                vt_add_replace_file $vtindex "boot\\initrd"
            elif [ -f (loop)/loader/entries/pisi-efi-x86_64.conf ]; then
                vt_add_replace_file $vtindex "EFI\\pisi\\initrd.img"
            fi
```

**Comment by ventoy** [comment]
Yes, this cfg file is just make according to the latest version of parabola ISO file.
So if you modify the structure of the ISO Ventoy need to be updated to fit.
This is a little ugly workaround for systemd boot in UEFI mode. Because there are two copy of initramfs in the ISO file.
One is in the normal directory another is in the efi.img.

**Comment by Megver83** [comment]
OK, so I managed to solve this with the following: (starting from [line 486](https://github.com/ventoy/Ventoy/blob/48a1b80be0258bedbb558bd009f4f143d87af47d/INSTALL/grub/grub.cfg#L486))

```
        if [ -d (loop)/loader/entries ]; then
            vt_linux_get_main_initrd_index vtindex
            
            if [ -d (loop)/arch ]; then
                if [ -f (loop)/arch/boot/x86_64/archiso.img ]; then
                    vt_add_replace_file $vtindex "EFI\\archiso\\archiso.img"
                elif [ -f (loop)/boot/initramfs_x86_64.img ]; then
                    vt_add_replace_file $vtindex "boot\\initramfs_x86_64.img"
                fi
            elif [ -d (loop)/parabola ]; then
                if [ -f (loop)/parabola/boot/x86_64/parabolaiso.img ]; then
                    vt_add_replace_file $vtindex "EFI\\parabolaiso\\parabolaiso.img"
                elif [ -f (loop)/boot/initramfs_x86_64.img ]; then
                    vt_add_replace_file $vtindex "boot\\initramfs_x86_64.img"
                fi
            elif [ -f (loop)/EFI/BOOT/initrd.gz ]; then
                vt_add_replace_file $vtindex "EFI\\BOOT\\initrd.gz"
            elif [ -f (loop)/loader/entries/thinstation.conf ]; then
                vt_add_replace_file $vtindex "boot\\initrd"
            elif [ -f (loop)/loader/entries/pisi-efi-x86_64.conf ]; then
                vt_add_replace_file $vtindex "EFI\\pisi\\initrd.img"
            fi
        elif [ -d (loop)/EFI/boot/entries ]; then
            if [ -f (loop)/parabola/boot/x86_64/parabolaiso.img ]; then
                vt_add_replace_file 0 "EFI\\parabolaiso\\parabolaiso.img"
            elif [ -f (loop)/hyperbola/boot/x86_64/hyperiso.img ]; then
                vt_add_replace_file 0 "EFI\\hyperiso\\hyperiso.img"
            fi
        elif [ -d (loop)/EFI/BOOT/entries ]; then
            if [ -f (loop)/parabola/boot/x86_64/parabolaiso.img ]; then
                vt_add_replace_file 0 "EFI\\parabolaiso\\parabolaiso.img"
            fi
        elif [ -e (loop)/syslinux/alt0/full.cz ]; then
            vt_add_replace_file 0 "EFI\\BOOT\\full.cz"            
            set FirstTryBootFile='@EFI@BOOT@grubx64.efi'


        fi
```
Basically it does the same treatment as with Arch's systemd-boot and added the same conditional as with `/EFI/boot/entries` but for the uppercase version.

**Comment by ventoy** [comment]
OK. I will add this in the next release.
