### ISSUE TITLE
期待支持Legacy引导的 Memtest86 和 Memtest86+

### ISSUE THREAD

**Issue by le45tx1m** [ventoy/Ventoy#461]
看日志，Ventoy 1.0.20 支持了 UEFI 引导的memtest86，这方便不少，终于临时测一下内存不用格U盘了。
但目前工作中还是经常接触到只有Legacy引导的主机，期盼早日能实现支持。

**Comment by ventoy** [comment]
Ventoy 支持   Memtest86+ V5.31b (12/04/2020)，注意使用Memdisk模式（启动前按F1）

**Comment by Rambin** [comment]
> Ventoy 支持 Memtest86+ V5.31b (12/04/2020)，注意使用Memdisk模式（启动前按F1）

能不能在配置里加上指定某些ISO用Memdisk模式启动的选项

**Comment by ventoy** [comment]
> > Ventoy 支持 Memtest86+ V5.31b (12/04/2020)，注意使用Memdisk模式（启动前按F1）
> 
> 1.0.20版本的那个ventoy-1.0.20-livecd.iso，是可以用etchdroid直接烧写U盘了吗？

`ventoy-1.0.20-livecd.iso` 不是Ventoy的ISO启动版，只是用来辅助安装Ventoy用的。详见 https://www.ventoy.net/cn/doc_livecd.html

**Comment by vqsld** [comment]
> 
> 
> > > Ventoy 支持 Memtest86+ V5.31b (12/04/2020)，注意使用Memdisk模式（启动前按F1）
> > 
> > 
> > 1.0.20版本的那个ventoy-1.0.20-livecd.iso，是可以用etchdroid直接烧写U盘了吗？
> 
> `ventoy-1.0.20-livecd.iso` 不是Ventoy的ISO启动版，只是用来辅助安装Ventoy用的。详见 https://www.ventoy.net/cn/doc_livecd.html

嘿嘿，我不死心，我要试试

**Comment by ventoy** [comment]
> 定某些ISO用Memdisk模式启动的选项

1.0.21版本增加了相关配置。
