### ISSUE TITLE
reserved space partition creation disabled.

### ISSUE THREAD

**Issue by faisalkamalia** [ventoy/Ventoy#465]
hy sir i tried your product its a rich featuring index. but i have faced a problem with reserved space partition making . because in windows disk management all the options are disabled. please suggest a new way to success in this.
![image](https://user-images.githubusercontent.com/22927462/92481867-606e8900-f200-11ea-8c25-ca5cf6b275f2.png)

**Comment by ventoy** [comment]
Only new Windows 10 can mount these reserved partitions that's Windows's limitation
If you use Windows7/8/8.1  you can mount it and you need some third-part tool to access the partition.
