### ISSUE TITLE
ventoy-1.0.20自动安装centos报错

### ISSUE THREAD

**Issue by denwork** [ventoy/Ventoy#466]
目录结构：
ls -R /media/office/ventoy/

/media/office/ventoy/ISO:
CentOS-7-x86_64-Minimal-2003.iso  cn_windows_7_ultimate_with_sp1_x64_dvd_u_677408.iso

/media/office/ventoy/ventoy:
script	ventoy.json

/media/office/ventoy/ventoy/script:
'centos7ks(副本).cfg'   centos7ks.cfg

配置内容ventoy.json
{
    "control": [
        { "VTOY_DEFAULT_MENU_MODE": "1" },
        { "VTOY_FILT_DOT_UNDERSCORE_FILE": "1" },
        { "VTOY_DEFAULT_SEARCH_ROOT": "/ISO" },
        { "VTOY_MENU_TIMEOUT": "60" }
    ],
    "auto_install": [
        {
            "image": "/ISO/CentOS-7-x86_64-Minimal-2003.iso",
            "template": "/ventoy/script/centos7ks.cfg"
        }
    ]
}

centos7ks.cfg文件

`#version=DEVEL`
`# System authorization information`
`auth --enableshadow --passalgo=sha512`
`# Install OS instead of upgrade`
`install`
`# Use graphical install`
`text`
`# Use hard drive installation media`
`cdrom`
`# Run the Setup Agent on first boot`
`# Keyboard layouts`
`keyboard --vckeymap=us --xlayouts='us'`
`# System language`
`lang en_US.UTF-8`
`# Firewall configuration`
`firewall --disabled`
`# Network information`
`network  --bootproto=dhcp --device=None --onboot=on`
`network  --hostname=zjqzjserver`
`# SELinux configuration`
`selinux --disabled`
`# Root password`
`rootpw --iscrypted $6$ktI5DJ9/HknFdtr3$laPPJmYa02iKDYiVwJ12upBEEWHiYUnj3fVKiEmuQ8wuRL5VnlzYZuopLYe9xTkYmOvNr3CbAyepyZEOsUzZL1`
`# System timezone`
`timezone Asia/Shanghai --isUtc --nontp`
`# System bootloader configuration`
`bootloader --location=mbr`
`autopart --type=lvm`
`# Clear the Master Boot Record`
`zerombr`
`# Partition clearing information`
`clearpart --all --initlabel`
`# Reboot after installation`
`reboot`

`%packages`
`@^minimal`
`@core`
`kexec-tools`

`%end`

`%addon com_redhat_kdump --enable --reserve-mb='auto'`

`%end `

安装过程

![image](https://user-images.githubusercontent.com/21987200/92570942-05757a00-f272-11ea-80d7-d57baefd9f0a.png)

![image](https://user-images.githubusercontent.com/21987200/92571000-1a520d80-f272-11ea-8a87-aedc34c27447.png)

![image](https://user-images.githubusercontent.com/21987200/92571047-276efc80-f272-11ea-8bca-3d5f039c9d46.png)

![image](https://user-images.githubusercontent.com/21987200/92571399-9c423680-f272-11ea-8c39-55fe210b1d5d.png)

![image](https://user-images.githubusercontent.com/21987200/92571498-c09e1300-f272-11ea-894f-ea5ab6374008.png)

希望知道原因的大佬们，能帮我解答一下。在此先谢过了。。。

**Comment by ventoy** [comment]
把 ks里面的这两句去掉就可以了。
···
network --bootproto=dhcp --device=None --onboot=on
network --hostname=zjqzjserver
···

详细原理需要去网上查询kickstart的文档，我个人感觉第一行的配置有错误，尤其是 --device=None 这个参数。
