### ISSUE TITLE
The primary disk partition is unavailable

### ISSUE THREAD

**Issue by MerdanK** [ventoy/Ventoy#467]
Hey there! After several boots from ventoy disk, the primary flash disk partition is unavailable, but sudenly ventoy installed partition have got availabled. First times after ventoy install, I cound't get access to ventoy installed partition, but could get primary partition.  I can't anymore access that partition, Windows asks to format the disk. However, despite all this I can boot ISO files well. 

![2020-09-10_165015](https://user-images.githubusercontent.com/13086690/92727487-a35b6880-f388-11ea-9af3-13f18917c57a.png)

**Comment by jendalinda** [comment]
The partition is corrupted. I would try to fix it using dosfsck in Linux.

**Comment by MerdanK** [comment]
I formatted flash disk in low level mode. Even scanned with several software for bad blocks, errors did not found.

**Comment by steve6375** [comment]
Download RMPrepUSB.exe
Look at LBA 0 and  PBR sectors and add files to report please
RMPrepUSB - Drive Info - 0
RMPrepUSB - Drive Info - P1
https://www.fosshub.com/RMPrepUSB.html

**Comment by MerdanK** [comment]
> Download RMPrepUSB.exe
> Look at LBA 0 and PBR sectors and add files to report please
> RMPrepUSB - Drive Info - 0
> RMPrepUSB - Drive Info - P1
> https://www.fosshub.com/RMPrepUSB.html


[P1.txt](https://github.com/ventoy/Ventoy/files/5219536/P1.txt)
[0.txt](https://github.com/ventoy/Ventoy/files/5219537/0.txt)

**Comment by steve6375** [comment]
Looks OK. 
Are you using Windows 10? It can get confused. I have seen this with recent versions. It can be proved by connecting the flash drive to a different system. Sometimes rebooting Windows and using a different USB port can help.
If it works in a different system then WIndows 10 registry may be bad. Often this can be cleared using USBDeview
https://www.wikihow.com/Clear-the-Record-of-USB-Plug-in-Equipment
List USB devices by 'Connected' column - find 'bad' USB drive,  Uninstall. Then unplug and reconnect USB drive.

**Comment by MerdanK** [comment]
> Looks OK. 
> 
> Are you using Windows 10? It can get confused. I have seen this with recent versions. It can be proved by connecting the flash drive to a different system. Sometimes rebooting Windows and using a different USB port can help.
> 
> If it works in a different system then WIndows 10 registry may be bad. Often this can be cleared using USBDeview
> 
> https://www.wikihow.com/Clear-the-Record-of-USB-Plug-in-Equipment
> 
> List USB devices by 'Connected' column - find 'bad' USB drive,  Uninstall. Then unplug and reconnect USB drive.

Yes, I do. I've used Windows 10 LTSB and couple of days ago I replaced it with 10 pro. Now seems everything is ok. However, I will test some more days. After that I'll close this issue.
