### ISSUE TITLE
Qt GUI for Linux

### ISSUE THREAD

**Issue by panickingkernel** [ventoy/Ventoy#469]
I made GUI for Linux with python and QT. I am in hurry, sorry. there is bit more detailed explanation in readme.txt
[QtVentoyFiles.tar.gz](https://github.com/ventoy/Ventoy/files/5213173/QtVentoyFiles.tar.gz)

**Comment by ventoy** [comment]
Ventoy 1.0.36 release with Linux GUI based on web browser.
https://www.ventoy.net/en/doc_linux_webui.html
![webui_en](https://user-images.githubusercontent.com/59477474/109389864-5a549c00-7949-11eb-8262-c304e467fef1.png)

**Comment by trymeouteh** [comment]
A Qt GUI for Windows, Mac and Linux will be swell and user friendly for all.
