### ISSUE TITLE
Problem Creating Ventoy Bootable USB-Drive

### ISSUE THREAD

**Issue by soares23** [ventoy/Ventoy#47]
I have test to create a ventoy boot-stick on a Samsung 256GB USB-Stick and is not working.
Before a have test it on another stick that is working but i don't now why with the smasung isn't working. The log is as attachmend.

He cleans all the partitions on usb stick but after that he's not creating the 2 partitions.

[log.txt](https://github.com/ventoy/Ventoy/files/4569405/log.txt)

**Comment by ventoy** [comment]
Maybe you can try to delete all the partitions and change the boot mode to USB-HDD with some tool.
Then try Ventoy2Disk.exe again.

Or if you have some linux enviroment, you can try Ventoy2Disk.sh to create.

**Comment by soares23** [comment]
HI, ventoy i have now tested to update to **1.0.09b1** but problem is that on the 2 drives i have created before, the update has failing the ventoy have format the fat32 partition but not recreate it. I have also on the same drives tested to create a new installation wirt first delete all partitions problem also to create a new one.  Here you have the log to see if you maybe found a problem after the update. I don't have now a linux to test it with the linux version .

[log.txt](https://github.com/ventoy/Ventoy/files/4576446/log.txt)

**Comment by soares23** [comment]
I have success create the Ventoy drive with 1.0.09b1 on an other device with windows 10 it was the same device that i have tested with Ubuntu as Live Boot but with Windows is workling. Is bizzare that with the pc that i normaly have do the ventoy stick is no more working.

**Comment by ventoy** [comment]
This is an old issue. I will close it now.
If you still have problem with latest Ventoy release, you can reopen the issue.
