### ISSUE TITLE
I can't boot Arch Linux

### ISSUE THREAD

**Issue by Zorin-Dev** [ventoy/Ventoy#471]
Like in issue #181 i can't boot to arch linux iso (archlinux-2020.09.01-x86_64.iso) on BIOS. The old iso (archlinux-2020.08.01-x86_64.iso) and before works well.

Thanks ventoy team

**Comment by ventoy** [comment]
I just test `archlinux-2020.09.01-x86_64.iso  md5: ebcdb2223a77f098af3923fe1fa180aa` in my laptop with Ventoy-1.0.21
Both legacy BIOS and UEFI mode worked fine.

**Comment by Zorin-Dev** [comment]
Thank you for reply.

I noticed strange thing, i have to recopy arch iso file to work. the same happened with latest manjaro 20.1.
