### ISSUE TITLE
[Feature request] Add an option for case insensitive sorting of ISOs

### ISSUE THREAD

**Issue by Silejonu** [ventoy/Ventoy#476]
ISOs are named following different conventions, and some of them include capital letters while others don't. This causes them to be sorted in a pretty annoying way in Ventoy (in my opinion at least), with the ones using a capital letter first being sorted at the top. It would be nice to have the option to sort them in a case insensitive way (in the ventoy.json file, for instance?).

**Comment by Posi81** [comment]
i agree with Silenjonu.
Would be really nice :-)

**Comment by ventoy** [comment]
It is case insensitive now.
If you put  `abc.iso DEF.iso ghi.iso ` then the final list will be:
```
abc.iso
DEF.iso
ghi.iso
```

**Comment by ventoy** [comment]
I mean it was sorted case insensitive from ventoy-1.0.0 util the latest release.

**Comment by Silejonu** [comment]
> I mean it was sorted case insensitive from ventoy-1.0.0 util the latest release.

It's indeed sorted case insensitive in list view, but not in tree view. As I'm only using tree view recently, I didn't realise it was the case for list view. It would be nice to still have the option for case insensitive sorting in tree view.

**Comment by Silejonu** [comment]
Thanks for making case-insensitive sorting default in TreeView mode, and adding an option in the latest release, much appreciated!
