### ISSUE TITLE
How to enable persistence for Kali linux using ventoy?

### ISSUE THREAD

**Issue by geronimo23** [ventoy/Ventoy#479]
I was trying to configure persistence so I can use it with Kali linux. I followed the instructions from issue #395 without success.

### My folder structure:

./ventoy
./ventoy/ventoy.json
./ventoy/ISO
./ventoy/ISO/kali-linux-2020.2-live-amd64.iso
./ventoy/persistence
./ventoy/persistence/CreatePersistentImg.sh
./ventoy/persistence/persistence.dat

### The procedure:

1. Boot from another linux system (ubuntu) and go to persistence directory
    `cd ./ventoy/persistence/` 
2. Create the persistence file
    `sudo sh CreatePersistentImg.sh -s 8192 -l persistence -t ext4`
3. The path of the persistence file is now `./ventoy/persistence/persistence.dat`
4. Create persistence.conf
   `sudo mount persistence/persistence.dat /mnt`
   `sudo echo "/ union" > /mnt/persistence.conf`
   `sudo umount /mnt`
5. Reboot and select Kali from Grub menu. Select the persistence mode without encryption.

### Problem:
The persistence does not work. I save some files to the desktop or to the documents folder but these changes are not permanent. They are not saved.

### Contents of my ventoy.json

    {
    "persistence": [
            {
                "image": "/ventoy/ISO/kali-linux-2020.2-live-amd64.iso",
                "backend": "/ventoy/persistence/persistence.dat"
            }
        ]
    }

### Ventoy version:
1.0.21

**Comment by geronimo23** [comment]
it works now. Ventoy didn't find the ventoy.json because of the name of my ventoy folder. It was ".ventoy" instead of "ventoy". I changed my post. My procedure as described above, works 😄

**Comment by hessedelohim** [comment]
Hi.. wher u put the persistencie.conf file? in the same folder that *.dat ? or with the *.json file? Regards

**Comment by paulo-roger** [comment]
> Hi.. wher u put the persistencie.conf file? in the same folder that *.dat ? or with the *.json file? Regards

It is inside the `.dat`
