### ISSUE TITLE
[Feature Request] Hotkeys a-z for automatic jumping in List

### ISSUE THREAD

**Issue by jsuelwald** [ventoy/Ventoy#484]
Hi,

I suggest keys a-z should trigger a jump within the image-list to the first entry starting with that letter. If no image with that letter exists, either display a short warning or jump to the image-entry starting with the next availible letter.

This should make ventoy easier to use, esp. if you have many (>20 or so) images on the disk.

Reason: Scrolling in that list takes some time and is somewhat slow on some PCs here

**Comment by ventoy** [comment]
Maybe you can put the images into different directories/subdirectories  and use TreeView mode.

**Comment by Silejonu** [comment]
Not exactly that, but you can use Page Up / Page Down.
I have a few dozens ISOs. What I ended up doing is use TreeView mode and make some directories by OS/purpose.
