### ISSUE TITLE
EndeavourOS doesnt boot

### ISSUE THREAD

**Issue by dag7dev** [ventoy/Ventoy#487]
It says "random seed file write protected".
Unable to boot.

**Comment by SecretAgentAgentX** [comment]
Odd since I know this has been corrected. I tested with the last ISO and the new one that just came out, both work without issue here.

**Comment by dag7dev** [comment]
Nope. Official website suggest to don't use unetbootin and so on because it alters the label of the partition. It could be the same issue.

**Comment by AtifChy** [comment]
for ventoy doesn't even work on linux. When the iSOs are copied from windows, they work and when they are copied from linux, they don't work.

**Comment by dag7dev** [comment]
@AtifChy yeah, I forgot to mention that I am from Linux, so this could be the issue.
