### ISSUE TITLE
/dev/sdd1 is a partition, please use the whole disk

### ISSUE THREAD

**Issue by achuanya** [ventoy/Ventoy#488]
I want to write ventoy to my U disk, but an error says that my U disk is a partition, but it is not
```shell
/dev/sdd1 is a partition, please use the whole disk
```

**Comment by ventoy** [comment]
You should use `/dev/sdd`  not `/dev/sdd1`   Ventoy must install  to a whole USB disk, not a partition.
```
sudo  sh Ventoy2Disk.sh  /dev/sdd
```
