### ISSUE TITLE
Dell Diagnostics Utility iso problem

### ISSUE THREAD

**Issue by git70** [ventoy/Ventoy#489]
I was looking for a good multiboot utility for Linux for a long time until I found Ventoy.
Basically all my iso's work fine, but unfortunately I have a problem with one :(
![screen_ventoy](https://user-images.githubusercontent.com/49098178/94285006-af2b5b00-ff42-11ea-9778-3c5e2dfc4bd5.png)

It works fine under YUMI, but I wanted to finally be able to give it up because I have to run Windows specifically for it.
Can someone check at home and help me?
Here is the file: [https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=gtw03](https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=gtw03)
After executing .exe, iso is extracted.

**Comment by ventoy** [comment]
Can you boot the iso directly by a VirtualMachine (e.g. VMware) ?

**Comment by git70** [comment]
> Can you boot the iso directly by a VirtualMachine (e.g. VMware) ?

I'm not using VMware, but it boots fine under Virtualbox.
Additionally, I found that under Linux MultiBootUSB (http://multibootusb.org) also works fine.
YUMI works fine under Windows

**Comment by ventoy** [comment]
You can use F1 memdisk mode to boot this ISO, i tested it in a VirtualMachine.

When you in Ventoy's boot menu, Press F1 first and then select the ISO to boot.

**Comment by git70** [comment]
I don't know how it happened, but I was sure I checked the memdisk option before reporting the error :(
Now it actually works fine;)
