### ISSUE TITLE
Compatible with Unraid?

### ISSUE THREAD

**Issue by BSalita** [ventoy/Ventoy#49]
Looks like Unraid is not compatible? Although I do see the similar Proxmox is supported.

**Comment by ventoy** [comment]
Where can I download the iso file? I only find the zip file to download.

**Comment by Traumlewis** [comment]
Unraid does not exist as iso. it is created via an exe and is bound to hardware id, therefore not possible to.

**Comment by BSalita** [comment]
@Traumlewis Thanks for clarifying. At least this question is now searchable by others. I'm closing the issue.

**Comment by ylluminate** [comment]
Unraid support would be very, very useful @ventoy. I'm not sure what method you may use to make it work, but a lot of people have trouble with Unraid and various servers such as the Dell R710 with UEFI mode. Even BIOS boot is problematic sometimes for them.

If you can manage to figure out how to get it to work I would be happy to test. We definitely need a superior method for booting this system that lives on a USB flash drive.

**Comment by trivarialthea** [comment]
Any progress in this? @ventoy

**Comment by yaamas** [comment]
@trivarialthea This will probably help: https://www.reddit.com/r/unRAID/comments/prhbl6/can_i_virtualize_unraid/
