### ISSUE TITLE
Working ISOs report

### ISSUE THREAD

**Issue by andrew867** [ventoy/Ventoy#490]
Hi!

Thanks for all your work on this, it's an amazing project and will save so much time for many people!

Here are some ISOs that worked for me:
clonezilla-live-2.6.7-28-amd64.iso - UEFI boot Dell 9010 SFF
clonezilla-live-2.6.7-28-i686.iso - UEFI boot Dell 9010 SFF
debian-live-10.5.0-amd64-kde+nonfree.iso - UEFI boot Dell 9010 SFF
HBCD_PE_x64.iso (already reported working) - UEFI boot Dell 9010 SFF
kali-linux-2020.3-live-amd64.iso - UEFI boot Dell 9010 SFF

Do you have a different preferred way of reporting working ISOs?

**Comment by ventoy** [comment]
Thanks, you can email me to report.
