### ISSUE TITLE
LiveCD will not boot

### ISSUE THREAD

**Issue by bitching** [ventoy/Ventoy#493]
![IMG_0855](https://user-images.githubusercontent.com/12702029/94367913-fa489800-0113-11eb-8671-da57a3cd56b0.JPG)
can not even show the ISOs, this is all.

**Comment by ventoy** [comment]
Do you mean  Ventoy LiveCD iso?

**Comment by bitching** [comment]
both 1.0.21 and 1.0.22

**Comment by ventoy** [comment]
I hava no idea about it. 
You can try to use Ventoy  LiveCD with VirtualMachine.

**Comment by bitching** [comment]
found [Super-UEFIinSecureBoot-Disk](https://github.com/ValdikSS/Super-UEFIinSecureBoot-Disk) instead, works for me.
