### ISSUE TITLE
lenovo tianyi 310-14ISK EFI boot not support

### ISSUE THREAD

**Issue by MelanPrince** [ventoy/Ventoy#497]
linpus lite boot failed  是否开启安全启动 都是  CPU 是I5-6200u

MBR 可以进入ventoy 界面 但是 启动镜像 花屏。

**Comment by ventoy** [comment]
linpus lite这种必须要在BIOS里面吧安全启动关闭，同时再安装Ventoy也不能勾选安全启动支持，这两条都要满足。

花屏问题可以F5调整下分辨率试试，参考官网常见问题说明。

**Comment by MelanPrince** [comment]
BIOS 里 关闭了 安全启动  需要重新制作 ventoy 不勾选 安全启动  EFI 模式 可以启动。
