### ISSUE TITLE
Asking about plugins

### ISSUE THREAD

**Issue by git70** [ventoy/Ventoy#498]
The /Ventoy directory and the ventoy.json file do not exist.
Do I understand correctly that they do not form themselves during installation, but I have to create them myself?

**Comment by DX37** [comment]
> Do I understand correctly that they do not form themselves during installation, but I have to create them myself?

[Documentation](https://ventoy.net/en/plugin_entry.html) about plugins clearly says, that these configuration files (or plugins) _must be placed under `ventoy` directory_. So yes, you have to **create** them yourself.

**Comment by crasadure** [comment]
Ventoy Training Set
https://www.youtube.com/playlist?list=PLbRmvlGlFFnSr2ziMJwl5JyA3YRKsRA7x

Ventoy.rar
https://drive.google.com/file/d/1nZwI0amADPFmwJmWVlkqFLcrJApx_kz1/view?usp=drivesdk
