### ISSUE TITLE
[Feature Request] Run iso from RAM

### ISSUE THREAD

**Issue by chromer030** [ventoy/Ventoy#5]
Is it possible to add a option to copy ISO to ram and run it from there ( like YUMI and Easy2boot)  ??
Nowadays the PCs and Laptops have a lot of ram , For the Linux distros this method lead to get a huge speed increase.
And also help to use tools like Kon-Boot and Super-Grub2-Disk very well
Thank you again.

**Comment by ventoy** [comment]
It's a good idea! 
But in my opinion maybe we don't need to copy the whole ISO file into RAM.  For those LiveCD linux distros, the kernel, initrd, squashfs image will be copy to ram, that's it. In addition, copying ISO files also takes time, doesn’t it? 
Looking forward to your reply! 
Thanks!

**Comment by a1ive** [comment]
> Nowadays the PCs and Laptops have a lot of ram , For the Linux distros this method lead to get a huge speed increase.

Linux won't recognize the virtual iso created by bootloader.

**Comment by chromer030** [comment]
I think Booting ISO from RAM is very useful in these situations :
1- You want to boot a ISO for someone else but you need your USB !
2- Using some ISO that take long time to finish operations , and in whatever reason you don't like your USB be attached , ISO like : HDShredder, Dban, HDClone, PartitionWizard , Norton Ghotst and a lot of other tools , generally this tools have lightweight ISO files.
3- Based of situation you must keep your privacy and no trace and footprint so RAM is best place for files and operation , because RAM storage is non-persistent , after reboot everything will be wiped.
4- RAM has a large speed benefit over using a USB , it may take some times to copy ISO or contents to RAM but in compare to speed that we gain it's worthy , also we should note that generally we boot ISO under 1 or 2 GB from RAM.
5- Based on SK Hynix news , upcoming DDR5 RAMs all have ECC and minimum speed of 3200 mhz , so it give magical operating speed to our ISOs

![nQZjXpVpNDzxCiDt](https://user-images.githubusercontent.com/13361552/78966676-b89c4480-7b15-11ea-989a-028c2c19c7e5.jpg)
![BNgAU7D74LgDfS1Z](https://user-images.githubusercontent.com/13361552/78966686-c0f47f80-7b15-11ea-8eea-ab69e133e5bd.jpg)

According to Distrowatch there is 17 distro with native Run From RAM feature :
http://distrowatch.org/search.php?category=From+RAM

**Comment by ventoy** [comment]
What you said makes sense, and it is not so difficult for Ventoy to implement it.
I will consider adding this feature in a future version. 
Thank you for your suggestion!

**Comment by chromer030** [comment]
Your-welcome man , Thank you for this perfect project and for your warmth.
I wish bests for you and this project.
