### ISSUE TITLE
"dir" in menu_class plugin not working

### ISSUE THREAD

**Issue by ZeroOne010101** [ventoy/Ventoy#503]
In the process of setting up my stick i have noticed that, while "key" keywords still cause the correct icon to show up, "dir" keywords dont.
I hope someone here can tell me what i am doing wrong.
I have attached my ventoy directory for diagnostics.
[ventoy.zip](https://github.com/ventoy/Ventoy/files/5320793/ventoy.zip)

**Comment by ventoy** [comment]
```
{
            "dir": "/_ISO/Windows",
            "class": "windows"
        },
        {
            "dir": "/_ISO/Linux",
            "class": "gnu-linux"
        }
```
dir must be the full path of the directory and is **case sensitive**, please check.

**Comment by ZeroOne010101** [comment]
I cant find anything wrong with it.
Or do you mean F:\_ISO\Windows when you say full path?
Screenshot attached.
<img width="676" alt="Unbenannt" src="https://user-images.githubusercontent.com/43586679/95457112-b144df00-0970-11eb-8917-2c86ab832769.png">

**Comment by ventoy** [comment]
Please do some debug in Ventoy's boot menu:
1. Press F5 Debug---> Check Plugin Json Configuration --->Check menu class plugin configuration
2. Press `c` to enter grub shell and run 
```
set  pager=1
vt_dump_menu  1
```

**Comment by ZeroOne010101** [comment]
These are the outputs. Sorry for the bad quality.
![IMG_20201008_153245](https://user-images.githubusercontent.com/43586679/95466372-92e4e080-097c-11eb-934c-eeeb911a8db0.jpg)
![IMG_20201008_153538](https://user-images.githubusercontent.com/43586679/95466384-94160d80-097c-11eb-974e-09e02427c477.jpg)

**Comment by ventoy** [comment]
In the photo I see that 
```
submenu "DIR       [Windows]"  --class="windows"
```
So it should take affect.   Do you put a windows.png file under the theme directory (like kali.png) ?
Is the windows.png file a valid png file? (you can copy kali.png and rename it to windows.png to test)

**Comment by ZeroOne010101** [comment]
Here. All of my isos are either in the windows or linux folder. The icons can be found under ventoy/themes/poly-dark/icons in the zip i sent and should all be valid.
![IMG_20201008_154800](https://user-images.githubusercontent.com/43586679/95467683-0b986c80-097e-11eb-89c1-57f3ac7ba7ca.jpg)
![IMG_20201008_154809](https://user-images.githubusercontent.com/43586679/95467744-194df200-097e-11eb-9f34-fdef5a439792.jpg)

**Comment by ventoy** [comment]
Please change VTOY_DEFAULT_MENU_MODE to 1 in your ventoy.json
```
{ "VTOY_DEFAULT_MENU_MODE": "1" },
```

and give the menu photo again.

**Comment by ZeroOne010101** [comment]
Ooh, im so sorry, i thought that image would be applied to all isos in the directory but its for the directory itself! Im so very sorry for wasting your time!

I think it would be great if something like this, or a default image was possible down the line, but you are probably busy as-is.
![IMG_20201008_160211](https://user-images.githubusercontent.com/43586679/95470225-d4778a80-0980-11eb-8461-6accf7741911.jpg)
![IMG_20201008_160148](https://user-images.githubusercontent.com/43586679/95470228-d5a8b780-0980-11eb-8a34-76b3ba10643f.jpg)
![IMG_20201008_160200](https://user-images.githubusercontent.com/43586679/95470231-d6414e00-0980-11eb-876d-059e64b7a8d3.jpg)

**Comment by ventoy** [comment]
OK. In fact, if you put a  `vtoyiso.png` file and doesn't set any menu class, then all the iso files will use this png file as icon.
