### ISSUE TITLE
Add script mode/noninteractive option for linux installation script

### ISSUE THREAD

**Issue by BeatLink** [ventoy/Ventoy#504]
Hello, I am working on a GUI wrapper for the ventoy linux script, however, its interactive nature makes it difficult to include in the application. Is it possible to add an option such as '-s' or '--script' so that all commands will proceed without confirmation?

**Comment by BeatLink** [comment]
Also would it be possible to add an option to display whether ventoy is already installed and if so, what version? eg '-d' or '--display'

**Comment by ventoy** [comment]
Ventoy-1.0.29 add  `-l` option to show the ventoy information in the disk.

For noninteractive, please refer:

```
echo -e 'y\ny' | sh Ventoy2Disk.sh -i /dev/sdb

echo y | sh Ventoy2Disk.sh -u /dev/sdb
```

**Comment by ventoy** [comment]
Ventoy-1.0.52 release with native Linux GUI
https://www.ventoy.net/en/doc_linux_gui.html
