### ISSUE TITLE
Windows 10 unattended problem

### ISSUE THREAD

**Issue by houd-chahid** [ventoy/Ventoy#507]
Hi, please I have this issue with ventoy: when i boot into windows 10 iso (the iso have the autounattend.xml file in it) and setup goes normal until it needs to reboot and ventoy pops up again and it blocks windows 10 from continuing its setup. Can you please add option or show me a trick to make ventoy boot only when i press a key as example.
Like the one windows use: "press any key to boot from thid media.."

Thank you so very much.

**Comment by DX37** [comment]
What prevents you from disconnecting a USB flash drive, so Ventoy will not prevent Windows boot?

**Comment by houd-chahid** [comment]
Having to deal with multiple machines. I think it is the essence of
unattended windows setup, to be able to leave the machine work and be sure
that it will be autonomous.
Other than that i have files in the reserved usb partition that windows use
automatically to obtain drivers.

**Comment by houd-chahid** [comment]
I think it would be awesome if we could have something like windows have, the bootfix.bin, that prompts user to boot into ventoy or not.

**Comment by DX37** [comment]
I guess @ventoy can add an option for `ventoy.json` to enable or disable mode you suggested, if it's possible.

**Comment by houd-chahid** [comment]
I really hope he does.  I like ventoy so much and i started to get habituated to it. Thank you so very much for your suggestions Maxim.

**Comment by ventoy** [comment]
I suggest that, you should set the HDD as the 1st default BIOS boot option.
If you want to boot into Ventoy, you must press some hotkey (e.g. F12) to select USB boot option.
So after the 1st reboot, you don't press any key, it will auto boot into hdd.

**Comment by ventoy** [comment]
This is an old issue. I will close it now.
If you still have problem with latest Ventoy release, you can reopen the issue.
