### ISSUE TITLE
Documentation: No documentation on how to build Ventoy

### ISSUE THREAD

**Issue by JohnVillalovos** [ventoy/Ventoy#51]
I cloned Ventoy but then failed to find documentation on how to build Ventoy. I would assume in the top level directory there would be some documentation that explains how to build Ventoy.

**Comment by Atari800XL** [comment]
Coming soon, I guess:
https://github.com/ventoy/Ventoy/issues/39

**Comment by ventoy** [comment]
Hi,
I have committed the build scripts and documents and updated README.md.
You can refer DOC/BuildVentoyFromSource.txt.

**Comment by ventoy** [comment]
Hi,
I will close the issue now, you can make a new issue if you still have problem.
