### ISSUE TITLE
Some ISOs don't boot for me in my UEFI only BIOS

### ISSUE THREAD

**Issue by gopal-kaul** [ventoy/Ventoy#510]
I installed Ventoy on my 16GB USB 2.0 pendrive through linux. I copied DSL, Kali, Manjaro, Parrot into it. On my asus tuf fx505DD, it shows the device to boot only in UEFI mode. Only Manjaro ISO works, after removing and re-adding it 3-4 times. Others give me issues of kernel not loaded and go into minimal GRUB. 
Whereas it works fine on my old Dell Optiplex PC with an older BIOS.
Any fix? I really need to use Ventoy and only recently discovered it.

**Comment by ventoy** [comment]
Please make a checksum of these ISO files to make sure that they are not corrupted

**Comment by gopal-kaul** [comment]
I did. I said it boots on an older PC with legacy only, whereas it doesn't boot for me with my UEFI-only BIOS with Legacy support. My boot menu doesn't even show the USB as a legacy boot option, it shows as UEFI only boot option
