### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ZhuMa12345678** [ventoy/Ventoy#512]
如图，Ventoy显示不出没有文件名的文件。
![截图20201008130546](https://user-images.githubusercontent.com/61312109/95418694-a4bd8800-096a-11eb-85ba-214ed53c4417.jpg)
![截图20201008130634](https://user-images.githubusercontent.com/61312109/95418703-a9823c00-096a-11eb-96a4-4e392221d40a.jpg)
alive的grubfm就没这问题
![截图20201008130935](https://user-images.githubusercontent.com/61312109/95418714-af781d00-096a-11eb-86a8-e3cd59ee54fc.jpg)

**Comment by ventoy** [comment]
已经修复，下个版本就可以了。
