### ISSUE TITLE
exclude files from being read

### ISSUE THREAD

**Issue by Relected** [ventoy/Ventoy#513]

**Comment by ventoy** [comment]
?

**Comment by blackcrack** [comment]
file-blacklisting.. not unintelligent, a file where is files blacklisted, like ".*" "*exe", "*ini" or "name.exe" and folders
with name "files", "tools", "old isos" and "the rest of files"

and by the way... @Relected, Longpanda is not a dog where you can kick a bone in front.. shame over you.. you have lost you face... and you have no decency and respect...
