### ISSUE TITLE
可否增加功能：检测到U盘中存在版本，点击安装时自动升级，而不是格式化重装。

### ISSUE THREAD

**Issue by znning** [ventoy/Ventoy#514]
可否增加功能：检测到U盘中存在版本，点击安装时自动升级，而不是格式化重装。

**Comment by ventoy** [comment]
安装功能保留下来是为了防止 升级功能出现BUG，或者出现了升级无法解决的问题。
而且Ventoy功能稳定之后，版本就不会经常更新了。所以不会经常出现升级的情况。
