### ISSUE TITLE
WePE_64_V2.1.iso 启动后无法获取到U盘的内容

### ISSUE THREAD

**Issue by houkunlin** [ventoy/Ventoy#515]
# 启动 WePE_64_V2.1.iso 后，在WePE里面无法获取到U盘的内容，C盘（Ventoy）无法读取。  版本：ventoy-1.0.22

**Comment by ghostry** [comment]
ventoy-1.0.24 下测试 WePE_64_V2.0.iso 无此问题

**Comment by houkunlin** [comment]
> ventoy-1.0.24 下测试 WePE_64_V2.0.iso 无此问题

我测试的时候发现启动PE后，进入我的电脑，C盘的容量条无显示，双击打开C盘鼠标转圈页面无反应，后来无意间发现，启动PE后需要等很久（不要动C盘，不要尝试打开C盘）然后C盘才加载出来

**Comment by houkunlin** [comment]
> ventoy-1.0.24 下测试 WePE_64_V2.0.iso 无此问题

@ghostry 
我测试的时候发现启动PE后，进入我的电脑，C盘的容量条无显示，双击打开C盘鼠标转圈页面无反应，后来无意间发现，启动PE后需要等很久（不要动C盘，不要尝试打开C盘）然后C盘才加载出来

**Comment by RenChunhui** [comment]
哪有 WePE_64_V2.1.iso 的下载？一直没找到

**Comment by houkunlin** [comment]
> 哪有 WePE_64_V2.1.iso 的下载？一直没找到

@RenChunhui 
下载官方的 exe 运行后可以弄出一个iso

**Comment by linch0318** [comment]
这个问题和电脑有关，怀疑是驱动问题，我遇到过几台电脑是这样的，启动PE后识别不到U盘，PE工具显示不完整。更换PE后解决。我准备了8个PE，多怪的电脑试一圈下来总有可以使用的
