### ISSUE TITLE
ARCH2020.10 not booting

### ISSUE THREAD

**Issue by X9VoiD** [ventoy/Ventoy#516]
ArchLinux install iso boots fine but can't continue to installation. It fallbacks to rootfs interactive prompt after waiting for device for 30 seconds

**Comment by ventoy** [comment]
I have fixed it and it will be ok in the next release.

**Comment by skulldealer** [comment]
Is it going to be supporting blackarch linux also same case 30 seconds cooldown and then takes to initramfs?

**Comment by ventoy** [comment]
Please try Ventoy-1.0.23

**Comment by ventoy** [comment]
I receive a report that it's ok in new release. So I will close this issue now.
