### ISSUE TITLE
using all_in_one.sh error message in the DEPS portion

### ISSUE THREAD

**Issue by SteveEbey73742** [ventoy/Ventoy#518]
error: missing binary operator before token "("
   60 | #if ! ( defined ( CONSOLE_EFIFB ) && CONSOLE_EXPLICIT ( CONSOLE_EFIFB ) )

is presented at the end of each DEPS and seems to throw the script into an endless loop, that I let run for 30 minutes, and then gave up.

**Comment by ventoy** [comment]
Now ventoy support github CI docker build.
