### ISSUE TITLE
在HP　DL３８０G７服务器直接进入ｇｒｕｂ引导

### ISSUE THREAD

**Issue by darth-j** [ventoy/Ventoy#520]
在一台HE　DL３８０服务器直接进入ｇｒｕｂ引导，不显示镜像选择菜单，在其他普通PC启动可以正常显示镜像选择菜单

**Comment by ventoy** [comment]
是Legacy BIOS模式还是UEFI模式？ U盘多大容量？

**Comment by darth-j** [comment]
应该是legacy bios，g7老的BIOS貌似还不支持uefi，使用的120g移动硬盘，使用的斐讯硬盘盒

**Comment by ventoy** [comment]
参考下  https://www.ventoy.net/cn/doc_legacy_limit.html
看看是不是这个问题。
