### ISSUE TITLE
BLACKARCH LINUX SUPPORT REQUIRED

### ISSUE THREAD

**Issue by skulldealer** [ventoy/Ventoy#521]
Pls update the ventoy to support BLACKARCH linux Live CD. It doesn't boot
Maybe because of the huge size. I really don't know. Only distribution missing in my ventoy toolkit. Please add support of BLACKARCH LINUX.
Thank you.

**Comment by skulldealer** [comment]
Uay even indirectly add a plugin to ventoy. json to add support if possible

**Comment by skulldealer** [comment]
It boots into initramfs instead of the login screen

**Comment by ventoy** [comment]
Which iso did you test?
When you drop into the initramfs shell, please run some commands and send me the result:
```
cat /ventoy/log
blkid
```

**Comment by skulldealer** [comment]
Ok
I used the 14.3 gb live iso from official website of BLACKARCH LINUX and it worked with virtualbox vm

Will share results for commands in a while

**Comment by skulldealer** [comment]
On running the iso it says waiting 30 seconds for device /dev/disk/by-label l/BLACKARCH_202005 

THEN AFTER 30 SECONDS
device did not show up after 30 seconds...
Falling back to interactive prompt 
You can fix the problem manually, log out when you are finished

sh: can't access tty: job control turned off
------------------------------------
Attaching the pic of the same
![IMG_20201015_082245.jpg](https://user-images.githubusercontent.com/65908813/96071393-ab468500-0ebf-11eb-95e6-3f29f11b6578.jpg)

------------------------------------

NOW ONTO YOUR COMMANDS

OOPS SORRY I RAN INTO ROOTFS NOT IN INITRAMFS. TYPO EEROR.

Pic of command

![IMG_20201015_082654.jpg](https://user-images.githubusercontent.com/65908813/96071663-3d4e8d80-0ec0-11eb-8e47-d27d7dd84959.jpg)



But still unable to boot into login screen.
Thank you.

**Comment by skulldealer** [comment]
By when will this be fixed so as I could resume my work.
Thank you.

**Comment by ventoy** [comment]
Which BIOS mode did you test? Legacy BIOS or UEFI ? Can you change the bios mode and test again?

**Comment by skulldealer** [comment]
Able to see only one boot option uefi.
Sharing pic 
![IMG_20201015_084149.jpg](https://user-images.githubusercontent.com/65908813/96072653-5d7f4c00-0ec2-11eb-9a9d-df4fec9c01ab.jpg)


My bios info here
Sharing pic
![IMG_20201015_084217.jpg](https://user-images.githubusercontent.com/65908813/96072684-6e2fc200-0ec2-11eb-9208-18f26e6cb812.jpg)

**Comment by skulldealer** [comment]
All other debain based iso work completely fine

**Comment by skulldealer** [comment]
Worked asap on old laptop probably in lagacy mode.
Looks like the same result
![IMG_20201015_084735.jpg](https://user-images.githubusercontent.com/65908813/96072981-19d91200-0ec3-11eb-936a-ef5e259a779f.jpg)

Sharing pic
![IMG_20201015_084853.jpg](https://user-images.githubusercontent.com/65908813/96073075-4bea7400-0ec3-11eb-868d-38f6383531be.jpg)

**Comment by ventoy** [comment]
I'm downloading `blackarch-linux-live-2020.06.01-x86_64.iso` then I will test it in my PC.

**Comment by skulldealer** [comment]
Would recommend u guys to try yourselves to boot blackarch live iso

**Comment by skulldealer** [comment]
We still have an option to boot from vdi

The official site provides 35 gb ova download.

Mavbe vdi plugins could be used

**Comment by skulldealer** [comment]
Let me know if I need to share my vtoy.json TXT file

**Comment by skulldealer** [comment]
> I'm downloading `blackarch-linux-live-2020.06.01-x86_64.iso` then I will test it in my PC.

Ok

**Comment by skulldealer** [comment]
> I'm downloading `blackarch-linux-live-2020.06.01-x86_64.iso` then I will test it in my PC.

Note I have not used any plugins with the iso in . json file

**Comment by skulldealer** [comment]
> I'm downloading `blackarch-linux-live-2020.06.01-x86_64.iso` then I will test it in my PC.

Looks you have successfully tested -

blackarch-linux-live-2020.01.01-x86_64.iso
This one is the first release of the year

The one you are downloading is the 2nd release of the year

The changelog and release notes of the current latest iso from blackarch official website might help

**Comment by skulldealer** [comment]
Rechecked on another usb
Same result

**Comment by skulldealer** [comment]
The boot menu looks like this
![IMG_20201015_092900.jpg](https://user-images.githubusercontent.com/65908813/96075552-e8634500-0ec8-11eb-8cab-d1d32b15fdbb.jpg)

The results sent by me are from first option (option 1)

With second and third option things get even worse

Pic after choosing option 2
![IMG_20201015_093246.jpg](https://user-images.githubusercontent.com/65908813/96075802-78a18a00-0ec9-11eb-91d8-15a14e94d56c.jpg)

Pic after choosing option 3
![IMG_20201015_093432.jpg](https://user-images.githubusercontent.com/65908813/96075873-a686ce80-0ec9-11eb-95a8-cd69768c32cc.jpg)

**Comment by skulldealer** [comment]
Just verified with balena etcher.
Works with it.

**Comment by skulldealer** [comment]
Is it a bug, definately something weird happening during boot processing....
Can't it be fixed?

**Comment by ventoy** [comment]
I have fixed it. You can update the `grub/grub.cfg` in the second partition (VTOYEFI) and retry.
https://github.com/ventoy/Ventoy/blob/master/INSTALL/grub/grub.cfg

**Comment by skulldealer** [comment]
> I have fixed it. You can update the `grub/grub.cfg` in the second partition (VTOYEFI) and retry.
> https://github.com/ventoy/Ventoy/blob/master/INSTALL/grub/grub.cfg
> 

So it will work even with the future versions of ventoy directly out of the box right?


Thank you,
Great response 👍

**Comment by skulldealer** [comment]
> I have fixed it. You can update the `grub/grub.cfg` in the second partition (VTOYEFI) and retry.
> https://github.com/ventoy/Ventoy/blob/master/INSTALL/grub/grub.cfg
> 

Asking because I do not know how to do that. Never messed with grub much. You could either tell me how to do that or I could wait for next update for ventoy which would fix it.

**Comment by skulldealer** [comment]
Will updating to next version of ventoy solve the issue?

**Comment by ventoy** [comment]
You can wait the next release.
If you want to test it now, you can do it manually.
There is a `grub\grub.cfg` file in the 2nd partition (with name VTOYEFI ) of the USB drive after install Ventoy.
Just replace it with the latest and retry.
The latest file is at https://github.com/ventoy/Ventoy/blob/master/INSTALL/grub/grub.cfg

**Comment by skulldealer** [comment]
Thanks I will check it out.

**Comment by ventoy** [comment]
Please try Ventoy-1.0.23
