### ISSUE TITLE
Can't boot up Samsung SSD Firmware image

### ISSUE THREAD

**Issue by alven-a** [ventoy/Ventoy#523]
On the
https://www.samsung.com/semiconductor/minisite/ssd/download/tools/ page
there is `Samsung SSD Firmware` section
and inside of it the `NVMe SSD-970 EVO Plus Firmware` line with `ISO 2B2QEXM7 | 28MB DOWNLOAD`

That ISO do not want to start: `/bin/sh: can't access tty: job control turned off`:
![PHOTO_20201015_202922](https://user-images.githubusercontent.com/68462094/96166928-2c2c6d80-0f0e-11eb-94be-6a69dfbdcdf8.jpg)
but ISO written via `dd` works well.

How to start the ISO via ventoy?

This is old PC:
```
$ inxi -CMy1
Machine:
  Type: Desktop
  System: Hewlett-Packard
    product: HP Elite 7100 Microtower PC
    v: xxx0204GRxxxxxxxx0
    serial: <superuser/root required>
  Mobo: MSI
    model: 2A9Ch
    v: 1.0
    serial: <superuser/root required>
  BIOS: American Megatrends
    v: 5.15
    date: 06/25/2010

CPU:
  Topology: Dual Core
    model: Intel Core i3 550
    bits: 64
    type: MCP
    L2 cache: 4096 KiB
  Speed: 3145 MHz
    min/max: 1200/3200 MHz
    Core speeds (MHz): 
      1: 1699
      2: 1933

```

So can't execute bootable media via ventoy to refresh Samsung ssd firmware.

**Comment by ventoy** [comment]
Please use Memdisk mode and retry. (Press F1 before select the ISO file)

**Comment by alven-a** [comment]
Did not note circumstances in the initial post:
```
$ pacman -Qi ventoy
Name            : ventoy
Version         : 1.0.22-1
...
```
used on Manjaro Linux

**Comment by alven-a** [comment]
> Please use Memdisk mode and retry. (Press F1 before select the ISO file)

Yeah, at least can load welcome screen:
![image](https://user-images.githubusercontent.com/68462094/96258576-bd055680-0fab-11eb-8e78-8ee1ee1a6d0f.png)

From one point of view it works, from another need additional but simple actions.
Could this be automated somehow? Please choose what to do with this ticket by yourself: to close now or may be to add more "automation" (for example, detection of such images, flags in ISO list, execution mode recommendations notes in ISO list, etc.).

Thank you for your software!

**Comment by ventoy** [comment]
You can use auto_memdisk plugin to tell Ventoy that always use Memdisk mode to boot this ISO file.
https://www.ventoy.net/en/plugin_automemdisk.html

**Comment by alven-a** [comment]
Additional info:

Tried on different machine (https://ark.intel.com/content/www/us/en/ark/products/126147/intel-nuc-kit-nuc8i5bek.html)

```
$ sudo inxi -Mazy1
Machine:
  Type: Mini-pc
  System: Intel Client Systems
    product: NUC8i5BEK
    v: J72742-308
    serial: <filter>
  Chassis: Intel Corporation
    type: 35
    v: 2.0
    serial: N/A
  Mobo: Intel
    model: NUC8BEB
    v: J72692-309
    serial: <filter>
  UEFI: Intel
    v: BECFL357.86A.0083.2020.0730.1436
    date: 07/30/2020
```

All tries was in UEFI mode only (legacy boot turned off in BIOS).

W/o `Memdisk` technique:

![PHOTO_20201016_173640](https://user-images.githubusercontent.com/68462094/96281286-a7525a00-0fc8-11eb-8d38-5ad62081fe35.jpg)

![PHOTO_20201016_173718](https://user-images.githubusercontent.com/68462094/96281288-a8838700-0fc8-11eb-8647-113def8e8ae8.jpg)

![PHOTO_20201016_173756](https://user-images.githubusercontent.com/68462094/96281291-a8838700-0fc8-11eb-99b4-a587ad7ecd66.jpg)

No success.

W/ `Memdisk` technique:

![PHOTO_20201016_173909](https://user-images.githubusercontent.com/68462094/96281321-b46f4900-0fc8-11eb-95e6-5c8fcb4a1e55.jpg)

![PHOTO_20201016_173919](https://user-images.githubusercontent.com/68462094/96281325-b507df80-0fc8-11eb-97fb-30992d11688c.jpg)

![PHOTO_20201016_173934](https://user-images.githubusercontent.com/68462094/96281327-b507df80-0fc8-11eb-9ba9-13f99d7323e8.jpg)

![PHOTO_20201016_174002](https://user-images.githubusercontent.com/68462094/96281329-b5a07600-0fc8-11eb-91df-4f11317b2275.jpg)

Success at least up to the first user payload screen.

**Comment by alven-a** [comment]
> You can use auto_memdisk plugin to tell Ventoy that always use Memdisk mode to boot this ISO file.
> https://www.ventoy.net/en/plugin_automemdisk.html

Got it. Thank you!
