### ISSUE TITLE
Can't boot up current Manjaro Linux using Memdisk mode

### ISSUE THREAD

**Issue by alven-a** [ventoy/Ventoy#526]
**Image**
file name
manjaro-kde-20.2-pre1-testing-minimal-201014-linux59.iso
sha256 sum
531af2352fb1ae90aaa92781bd005a6188dfe607127d32f86477b72042bd79be
origin
https://osdn.net/projects/manjaro/storage/kde/20.2-pre1/

**Problem desc**
UEFI: Image fully loads w/ success.
UEFI + Memdisk mode: Image won't to load.

![PHOTO_20201016_195446](https://user-images.githubusercontent.com/68462094/96289623-ebe3f280-0fd4-11eb-8e76-811eaf10d233.jpg)

![PHOTO_20201016_195511](https://user-images.githubusercontent.com/68462094/96289627-ed151f80-0fd4-11eb-9c07-d500c37ca508.jpg)

![PHOTO_20201016_195921](https://user-images.githubusercontent.com/68462094/96289630-ed151f80-0fd4-11eb-8c7b-9e940e0b6805.jpg)

![PHOTO_20201016_200046](https://user-images.githubusercontent.com/68462094/96289631-edadb600-0fd4-11eb-8c3a-04a02dd51f7b.jpg)

```
error: device did not show up after 30 seconds...
Falling back to interactive prompt
You can try to fix the problem manually, log out when you are finished
sh: can't access tty; job control turned off
```

**Machine**
```
$ sudo inxi -Mmazy1 
Machine:
  Type: Mini-pc
  System: Intel Client Systems
    product: NUC8i5BEK
    v: J72742-308
    serial: <filter>
  Chassis: Intel Corporation
    type: 35
    v: 2.0
    serial: N/A
  Mobo: Intel
    model: NUC8BEB
    v: J72692-309
    serial: <filter>
  UEFI: Intel
    v: BECFL357.86A.0083.2020.0730.1436
    date: 07/30/2020

Memory:
  RAM: 
    total: 31.25 GiB
    used: 1.64 GiB (5.3%)
  Array-1: 
    capacity: 32 GiB
    slots: 2
    EC: None
    max module size: 16 GiB
      note: est.
    Device-1: SODIMM1
      size: 16 GiB
      speed: 2400 MT/s
      type: DDR4
      detail: synchronous
      bus width: 64 bits
      total: 64 bits
      manufacturer: Kingston
      part-no: KHX2400C14S4/16G
      serial: <filter>
    Device-2: SODIMM2
      size: 16 GiB
      speed: 2400 MT/s
      type: DDR4
      detail: synchronous
      bus width: 64 bits
      total: 64 bits
      manufacturer: Kingston
      part-no: KHX2400C14S4/16G
      serial: <filter>
```
(specs: https://ark.intel.com/content/www/us/en/ark/products/126147/intel-nuc-kit-nuc8i5bek.html)

```
$ pacman -Qi ventoy
Name            : ventoy
Version         : 1.0.22-1
Description     : A new multiboot USB solution
Architecture    : x86_64
URL             : http://www.ventoy.net
Licenses        : GPL3
Groups          : None
Provides        : None
Depends On      : bash  util-linux  xz  exfat-utils  dosfstools  lib32-glibc
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 7.18 MiB
Packager        : Mark Wagie <user edit: hidden>
Build Date      : Mon 28 Sep 2020 01:28:58 UTC
Install Date    : Fri 16 Oct 2020 02:30:20 UTC
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Possibly related to** (Manjaro "origins" from Arch)
https://github.com/ventoy/Ventoy/issues/516

**Gratitude**

Tried the `ventoy` app and it loads several ISOs.

Thank you for the great and comfortable app, at least:
-) UEFI and legacy boot features-independent: loads in both cases;
-) many ISOs on one drive;
-) easy and fastest ISOs update/delete/add;
-) easy and fastest `ventoy` app update, as I understood, w/o ISO files loss;
-) `Memdisk` technique, where you can use it in compatibility cases and also to load your 5 GB ISO into PC RAM, and later proceed with fastest possible speed of PC: no any permanent storage media access in further load/install: all as fast as your manual actions and CPU+RAM bunch speed. Just amazing idea! Very old (15-20 years) `RAM disk` technique (where file folders can be loaded and managed in RAM), and that `Memdisk` came from alien's worlds also :)

I even still do not opened docs page of it (except `Memdisk` feature) to learn more abilities, including permanent configs.

Remember `Dendy` tv-box, remember cartridges for it?
`Ventoy` is like that: `150 in 1`: `150 ISOs - 1 ventoy-driven media`

Glad to interact with it!
Thank you so much for ideas and realisations! <3 <3 <3 <3 <3

**Comment by alven-a** [comment]
```
$ pacman -Qi ventoy
Name            : ventoy
Version         : 1.0.23-1
...
```
Got update of PC package version, updated it on USB stick via `sudo ventoy -u /dev/sda`): saw the `ventoy` shows msg sort of "1.0.22 ---> 1.0.23", even did it twice: update 1.0.23 to the same 1.0.23.

Also switched to slightly another ISO:
filename
`manjaro-kde-20.1.1-201001-linux58.iso`
sha1sum
`4ff5f61dbcd211c352c6bc6d50c6aad78a2cac56`
origin
`https://osdn.net/projects/manjaro/storage/kde/20.1.1/`

Just the same error as was before:
```
error: device did not show up after 30 seconds...
Falling back to interactive prompt
You can try to fix the problem manually, log out when you are finished
sh: can't access tty; job control turned off
```

So "direct load" works fine until the desktop of OS,
`Memdisk` mode outputs the error text.

**Comment by ventoy** [comment]
Memdisk mode is only for the ISO files which load everything into memory when boot and which do not need to mount the ISO after startup.

So not every ISO file can be booted in Memdisk mode.

Manjaro Linux ISO can't be booted in Memdisk mode, because it need to mount the ISO file after boot.

**Comment by alven-a** [comment]
Got it.
Thank you!
