### ISSUE TITLE
file version number in Ventoy2Disk.exe does not match with current release version number

### ISSUE THREAD

**Issue by MELERIX** [ventoy/Ventoy#527]
it shows 1.0.0.2 instead of  1.0.23 which is the current version at this moment.

**Comment by ventoy** [comment]
Ventoy2Disk.exe is just an installer program of Ventoy in Windows.
Ventoy2Disk.exe has not been modified for a few releases.

**Comment by MELERIX** [comment]
well, it could be good is the exe file have the same version number of the current release, so then it can be identified by SUMo (Software Update Monitor) detecting there is a new version of Ventoy based on version number in the exe file.

**Comment by ventoy** [comment]
Another reason is that,  once I update Ventoy2Disk.exe, it will be alerted by various antivirus software.
If I keep Ventoy2Disk.exe unmodified for some releases, then it seems that it has been in the whitelist of these antivirus software.
