### ISSUE TITLE
U盘活动分区的问题

### ISSUE THREAD

**Issue by beldzhang** [ventoy/Ventoy#528]
1.0.22，其他都通过，但是碰到活动分区不对的问题

32G的U盘全新安装，第二个分区是启动分区，但是bootable标记在第一个分区，以BIOS方式启动时，会提示找不到启动设备。

在Linux下手工调整过来后，就没有问题了。

**Comment by ventoy** [comment]
BIOS启动时其实没有哪个分区是启动分区的说法。应该只看bootable标记。
我遇到很多是必须要求bootable标记在第一个分区的，或者在第一第二都可以的。还没遇到过必须要求bootable标记在第二个分区，在第一个分区就启动不了的。

**Comment by beldzhang** [comment]
启动分区这个是DOS时代的说法，现在确实可以忽略了

用 1.0.24 全新测试了一下，问题没有重现出来，再碰到的话我留心吧。

测试的机器是 DELL XPS 15z，10年前的机器了。
