### ISSUE TITLE
2 ISO FILES DONT BOOT , PULL REQUEST

### ISSUE THREAD

**Issue by skulldealer** [ventoy/Ventoy#529]
1. raspbian os for desktop doesnt boot,
file name - 2020-02-12-rpd-x86-buster.iso
download link- [https://downloads.raspberrypi.org/rpd_x86/images/rpd_x86-2020-02-14/2020-02-12-rpd-x86-buster.iso
](url)
2. knoppix
file name - KNOPPIX_V8.6.1-2019-10-14-EN.iso
download link - [http://mirrors.sonic.net/knoppix/knoppix-dvd/KNOPPIX_V8.6.1-2019-10-14-EN.iso](url)

please download and test it yourself, unable to figure out anything.

pull request-

please add option to return to uefi bios firmware settings from ventoy grub menu. 
this option is seen in linux distributions such as ubuntu-dde.
pretty helpful to change settings in bios otherwise need to restart computer to get into bios.

Thank You.

**Comment by ventoy** [comment]
1. I will test later.
2. press `c` to enter grub shell and run `exit`

**Comment by skulldealer** [comment]
> 1. I will test later.
> 2. press `c` to enter grub shell and run `exit`

please test it. requested a week ago.

**Comment by skulldealer** [comment]
> 1. I will test later.
> 2. press `c` to enter grub shell and run `exit`
> 
> 
> 


Please let me know when it has been fixed so I can close this issue.

Thank you.
