### ISSUE TITLE
Boot vDisk at Local disk by Ventoy

### ISSUE THREAD

**Issue by yizg20** [ventoy/Ventoy#530]
Can you produce a detailed configuration file how to write the local hard disk number + path? I Many ways have failed

**Comment by ventoy** [comment]
官网中的模板应该只需要改一个文件路径就可以了。你遇到什么问题了？

**Comment by yizg20** [comment]
> 官网中的模板应该只需要改一个文件路径就可以了。你遇到什么问题了？

**Comment by yizg20** [comment]
> 官网中的模板应该只需要改一个文件路径就可以了。你遇到什么问题了？

已经解决，我在qq群里向你咨询过，谢谢
