### ISSUE TITLE
[建议] 菜单类型 允许不区分大小写搜索

### ISSUE THREAD

**Issue by ghostry** [ventoy/Ventoy#531]
比如
```
{
    "menu_class": [
        {
            "key": "ubuntu",
            "class": "ubuntu"
        }
    ]
}
```

很多文件用的是 Ubuntu ,目前区分大小写需要写两条,只有两三个的时候 X 2 没什么,如果有十几个,再 X 2 ,那就很慢了.

**Comment by ventoy** [comment]
可以使用一部分匹配，比如   `buntu`

**Comment by ghostry** [comment]
> 可以使用一部分匹配，比如 `buntu`

这倒是一个办法,不过不是那么完美, buntu 范围更大了,kubuntu,lubuntu等等的一堆.

**Comment by ventoy** [comment]
https://www.ventoy.net/cn/plugin_path_match.html
