### ISSUE TITLE
报错内存不足以启动

### ISSUE THREAD

**Issue by mengxifl** [ventoy/Ventoy#536]
由于PE太大进去之后会报错，内存不足。所以没办法进入PE系统

**Comment by ventoy** [comment]
你用的F1 Memdisk模式吗？ 只有Memdisk模式才会在启动时把整个ISO文件加载到内存，默认是不会的。

**Comment by mengxifl** [comment]
用的wim插件直接启动的wim文件

**Comment by ventoy** [comment]
你的WIM文件多大？ 你不会加载的是 install.wim吧。
