### ISSUE TITLE
传统启动模式太卡

### ISSUE THREAD

**Issue by mengxifl** [ventoy/Ventoy#537]
使用传统启动时候，如果按键按的过快的话，就会导致界面卡主，而且死机

**Comment by ventoy** [comment]
这种情况有人反馈过。和硬件有关，这种情况你只能使用文本模式，不能使用图形模式。
通过配置文件设置默认使用文本模式即可。https://www.ventoy.net/cn/plugin_control.html

**Comment by mengxifl** [comment]
close
