### ISSUE TITLE
提供静态链接的二进制文件

### ISSUE THREAD

**Issue by My9xVm** [ventoy/Ventoy#541]
可能相关的问题：https://github.com/ventoy/Ventoy/issues/310

有些 Linux 发行版允许用户使用 [musl](https://musl.libc.org/) 而不是 glibc 作为 C 库，alpine 和 Void 是在此方面较知名的。

动态链接的二进制无法兼顾不同的 C 库，是否可以提供静态链接的版本？

```
$ file ./tool/mkexfatfs_64
./tool/mkexfatfs_64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=de003a5ae097b4004e6b77e6cd71d2410df7b310, stripped
```

**Comment by ventoy** [comment]
我觉得你可以在这个系统内重新编译一遍 exfat 就可以了。
https://github.com/ventoy/Ventoy/tree/master/ExFAT 里面有编译脚本。

**Comment by ventoy** [comment]
https://github.com/ventoy/statictool/tree/main/ventoy
