### ISSUE TITLE
Kali Linux 2020.3 live iso boot failed from memdisk mode took to initramfs & encrypted persistence

### ISSUE THREAD

**Issue by skulldealer** [ventoy/Ventoy#545]
As per my knowledge memdisk mode loads the iso into system memory.

I have important files which run only on kali linux which I have stored on my ventoy bootable usb.

So when I open ventoy grub and select kali Linux live 2020.3 iso it takes me to blue colour kali linux grub menu where I selected the 1st option to run live system

It then takes me to initramfs busybox

![IMG_20201024_101059.jpg](https://user-images.githubusercontent.com/65908813/97068009-3e2ea000-15e1-11eb-8aa3-dd84eab7237a.jpg)

My goal is to load iso of kali to memory by memdisk mode and then run the file in the same usb.

Please test kali-linux-2020.3-live.iso with memdisk mode and provide fix for the same.

Thank you.

**Comment by skulldealer** [comment]
No output on cat /boot.log

**Comment by skulldealer** [comment]
Output of blkid

![IMG_20201024_101907.jpg](https://user-images.githubusercontent.com/65908813/97068126-5eab2a00-15e2-11eb-8ede-a75c8b020ef3.jpg)

**Comment by a1ive** [comment]
Memdisk mode is only for the ISO files which load everything into memory when boot and which do not need to mount the ISO after startup.

**Comment by skulldealer** [comment]
So kali-linux won't work

I have seen such a feature in grub boot menu of parrot os which is called ram mode which loads iso in ram and allows us to use files in ventoy bootable usb

**Comment by skulldealer** [comment]
> Memdisk mode is only for the ISO files which load everything into memory when boot and which do not need to mount the ISO after startup.

Yeah I know that I want to boot kali live iso from ventoy usb such that I could get access to a folder in the same usb.

Is this possible from memdisk mode or could a new plugin help which could mount that desired folder after booting in iso just like how shared folder works in virtualbox

**Comment by a1ive** [comment]
> So kali-linux won't work?

Yes.
> I have seen such a feature in grub boot menu of parrot os which is called ram mode which loads iso in ram and allows us to use files in ventoy bootable usb

You need to edit grub boot menu in kali iso, and add `toram` to kernel cmdline.

**Comment by skulldealer** [comment]
Or a new feature like creating another partition for storing such files on ventoy bootable USB could help?

**Comment by skulldealer** [comment]
> > So kali-linux won't work?
> 
> Yes.
> > I have seen such a feature in grub boot menu of parrot os which is called ram mode which loads iso in ram and allows us to use files in ventoy bootable usb
> 
> You need to edit grub boot menu in kali iso, and add `toram` to kernel cmdline.


What's the difference between memdisk mode and this one? Sorry but I am little confused

**Comment by skulldealer** [comment]
Feels like a new plugin would really help It could take help of the injection plugin already present. Such a feature would come really handy to do work and store files on the same ventoy bootable USB pendrive.

**Comment by skulldealer** [comment]
> > So kali-linux won't work?
> 
> Yes.
> > I have seen such a feature in grub boot menu of parrot os which is called ram mode which loads iso in ram and allows us to use files in ventoy bootable usb
> 
> You need to edit grub boot menu in kali iso, and add `toram` to kernel cmdline.

I am not familiar with any of these stuff like the kernel command line or toram

**Comment by a1ive** [comment]
> Or a new feature like creating another partition for storing such files on ventoy bootable USB could help?

You can preserve some space when installing Ventoy, and then create a new partition.
See https://www.ventoy.net/en/doc_disk_layout.html

**Comment by skulldealer** [comment]
The preserved space is unformatted so which type of format should I give to it  NTFS of exfat.

After which will it automatically mount on booting iso?

**Comment by skulldealer** [comment]
> > Or a new feature like creating another partition for storing such files on ventoy bootable USB could help?
> 
> You can preserve some space when installing Ventoy, and then create a new partition.
> See https://www.ventoy.net/en/doc_disk_layout.html

Do I need to reinstall ventoy or could I just update it ?

**Comment by ventoy** [comment]
Yes, just like @a1ive  said, a new partition with preserved space should meet your requirement.

You need to format the new preserved partition manually after install Ventoy.
You'd better format it in FAT32, because every Linux distro can mount FAT32 filesystem (some Linux distros can't mount ntfs/exfat).

You need to reinstall Ventoy with preserve space.

**Comment by skulldealer** [comment]
Thank you


Little off topic but I would love to see some kind of encryption method with ventoy for persistence.dat backend as I am facing difficulty in setting up user account password for some distros.


Also will the backends for ubuntu work with kali linux which is directly debian based? Because it has a direct option in grub to use persistence or encrypted persistence

**Comment by ventoy** [comment]
1. encryption  for persistence is not supported.
2. Different distros have different requirement for the format of the persistence partition. So it depends on kali/ubuntu/debian ...
   I have no experience either.

**Comment by skulldealer** [comment]
Ok thanks
