### ISSUE TITLE
THESE 2 ISO'S DONT BOOT, BLANK SCREEN AND STUCK AT SPLASH SCREEN

### ISSUE THREAD

**Issue by skulldealer** [ventoy/Ventoy#546]
1. raspbian os for desktop-
file name - 2020-02-12-rpd-x86-buster.iso
download link- [https://downloads.raspberrypi.org/rpd_x86/images/rpd_x86-2020-02-14/2020-02-12-rpd-x86-buster.iso
](url)
2. knoppix-
file name - KNOPPIX_V8.6.1-2019-10-14-EN.iso
download link - [http://mirrors.sonic.net/knoppix/knoppix-dvd/KNOPPIX_V8.6.1-2019-10-14-EN.iso](url)

Observations-
knoppix shows black blank screen
raspbian gets stuck at splash screen 

please download and test it yourself, unable to figure out anything.

**Comment by skulldealer** [comment]
Please let me know when the issue is fixed

Thank you.

**Comment by skulldealer** [comment]
Please tell me if it will ever be possible to run off these 2 iso files from ventoy or not
Is there a fix to it?
I have not got a reply from a week.

**Comment by sky-wa1ker** [comment]
@skulldealer You can try first booting into [Plop boot manager](https://www.plop.at/en/bootmanager/download.html) and then using it to boot into your Ventoy USB drive. I don't really know how but it did fix ventoy for me.
