### ISSUE TITLE
What is USB drive write-protected support in ventoy

### ISSUE THREAD

**Issue by skulldealer** [ventoy/Ventoy#547]
What is USB drive write-protected support in ventoy???
It is listed as one of the features on ventoy home page (to be specific 4th last point) there is no such mention on official website. Please explain how to do this?

**Comment by ventoy** [comment]
Some USB drive has a hardware write-protect switch.
If you turn it on, then you can only read data from the USB drive and can't write anything to it.

If Ventoy was installed in such USB drive. You can turn the switch on after you copy all your ISO files to the drive.
Ventoy works well no matter the write-protect switch is on/off.
Some other tools may have problem to boot if you turn the write-protect switch on.

**Comment by skulldealer** [comment]
Ok got it
