### ISSUE TITLE
Unable to select Windows 10 Pro edition or insert product key

### ISSUE THREAD

**Issue by santamario** [ventoy/Ventoy#549]
Hi, hope you are ok

Would you be kind to help me, please.
Don't know if it was posted before.

I have Ventoy latest version 1.0.26 and today I updated my usb drive with Windows 10 October update x86 & x64 in 1 iso file.

I tried to do a clean install on my HP laptop but something has changed. It didn't ask me for the product key and didn't let me choose which version I want to install.
It skipped them and started to install.

Is there a ways to change it to fix it like it was before ?

I saw on Youtube that I need to do a txt file inside the Windows image

Is there any other way ?

Please help me.
Looking forward to hearing from you.
Thank you so much in advance

Regards,

Mario

**Comment by soares23** [comment]
Hi, 

That has nothing to do with Ventoy. Is the ISO that you use. The default ISO from Microsoft check if in BIOS a Product key exist if so, he automatically chosen the Version to install that match the Product key. If you want change that you must create a ei.cfg on Windows ISO on Folder Sources and recreate the ISO and then you can choose the Edition to Install.

Regards

**Comment by santamario** [comment]
Hi,

Thank you so much for your reply.

I think you are right, Windows running on my HP laptop is now activated with a Home license key.

Didn't know about is, was running Windows 8.1 before.

Much appreaciated, take care.

Regards,

Mario
