### ISSUE TITLE
persistence.sh modification

### ISSUE THREAD

**Issue by skulldealer** [ventoy/Ventoy#554]
Please add option in persistence.sh to expand or shrink a backend persistence.dat

I have a 3 gb backend and I have run out of space. I know antoher backend could be added to increase space and that's what I have done. But will be great to see option to resize backend using same script. Both shrink and expand.

Also please include this script persistence. sh in ventoy.iso

Thank you.

**Comment by ventoy** [comment]
To expand or shrink a backend image is not so simple as you think.
The image contains a whole file system in it. 
So it's not enough for you only expand the image file.
You must use some utility to expand the filesystem to use the expanded space.
This process depends on filesystem and is not 100% safe in theory. 

So Ventoy will not provide such option, instead a document is better.

**Comment by skulldealer** [comment]
Ok thank you
