### ISSUE TITLE
Default image plugin bug

### ISSUE THREAD

**Issue by skulldealer** [ventoy/Ventoy#555]
Default image in my ventoy.json is pop os iso file but boots me into kali linux by default. On checking in tools and global ventoy configuration everything seems fine and ok.

**Comment by ventoy** [comment]
Please give your `ventoy.json` file and your boot menu screenshot.

**Comment by skulldealer** [comment]
> Please give your `ventoy.json` file and your boot menu screenshot.

{
    "control": [
        { "VTOY_DEFAULT_MENU_MODE": "1" },
        { "VTOY_DEFAULT_SEARCH_ROOT": "/ISO" },
        { "VTOY_FILT_DOT_UNDERSCORE_FILE": "1" },
        { "VTOY_MENU_TIMEOUT": "10" },
        { "VTOY_DEFAULT_IMAGE": "/ISO/pop-os_20.10_amd64_nvidia_1.iso" }       
    ],
    
    "theme": {
        "file": "/ventoy/theme/theme.txt",        
        "display_mode": "GUI",
        "ventoy_left": "5%",
        "ventoy_top": "95%",
        "ventoy_color": "#ffffff"
    },
    
    
    "menu_class": [        
        {
            "key": "ubuntu",
            "class": "ubuntu"
        },        
        {
            "key": "deepin",
            "class": "deepin"
        },
        {
            "dir": "rhel",
            "class": "red-hat"
        }
    ],
    
    "menu_alias": [
        {
            "image": "/ISO/MX-19.1_x64.iso",
            "alias": "MX 19.1 ISO file For me"
        },
        {
            "image": "/cn_windows_10_enterprise_ltsc_2019_x64_dvd_9c09ff24.iso",
            "alias": "我的 Windows 10 系统"
        }
    ],
    
    "auto_install": [
        {
            "image": "/ISO/cn_windows_10.iso",
            "template": "/ventoy/script/windows_unattended.cfg"
        },
        {
            "image": "/ISO/cn_windows_server_2012_r2_vl_x64_dvd_2979220.iso",
            "template": [
                "/ventoy/script/windows_unattended1.xml",
                "/ventoy/script/windows_unattended2.xml",
                "/ventoy/script/windows_unattended3.xml",
                "/ventoy/script/windows_unattended4.xml",
                "/ventoy/script/windows_unattended5.xml",
                "/ventoy/script/windows_unattended6.xml"
            ]
        }
    ]
    
}

**Comment by skulldealer** [comment]
list of iso i use (they are too many. Sorry but your software is addictive.)

![Screenshot (18)](https://user-images.githubusercontent.com/65908813/97183383-b94fac00-17c3-11eb-929e-aa86d08cb3ff.png)

**Comment by skulldealer** [comment]
some more info-

[bug.zip](https://github.com/ventoy/Ventoy/files/5439347/bug.zip)

**Comment by skulldealer** [comment]
my opinion,
there is a limit of 13 or 14 in default image plugin.
it scanned till letter k , which is kali could not reach p which is pop os. something is wrong with sorting. i suppose if pop started with a then it would work properly like apop.iso

looks like there is a limit to scanning iso for ventoy default pluging. the last one is  13 or 14.

try keeping atleast 15 isos in a drive you shall notice this after fifteenth iso fil definately.

**Comment by skulldealer** [comment]
After changing name of pop.iso to apop.iso still boots kali linux.

Looks like something went wrong during last update when kali linux 2020.3 was supported

**Comment by skulldealer** [comment]
Sorry I just got it what exactly is happening.




Understand this carefully,
Ventoy is misbehaving

What I did was took a 128 gb usb and reserved 25 gb space. So now ventoy partition has 100 gb for iso files.

Then I partitioned that 25 gb into 2 .

One 5 gb partition and one 20 gb partition.

Then I used 20 gb fat32 as shared partition which you earlier suggested to keep my files and store and modify them in live session of ventoy.


Listen from here extra carefully.

Now I used a GitHub project called unetbootin. It allows us to boot into a partition so I formatted the 5 gb fat32 and installed kali linux on it so that I get macbook support. You should be knowing that ventoy doesn't work well on macos so this partition could be used to boot kali linux on macbook if needed.

Your default image plugin is booting me into that unetbootin kali linux partion. That's crazy.


Please don't get mad at me I am really sorry for bothering

Here is screenshot of the partition table of the unlucky usb

![Screenshot (20).png](https://user-images.githubusercontent.com/65908813/97187093-1cdbd880-17c8-11eb-94a4-e19fd72becfa.png)




I want to share my research also on enabling macbook support. Should I start it as a new issue or continue in this thread.

What I have found is a way to enable macbook support in ventoy and improving iso support in general for ventoy

**Comment by ventoy** [comment]
Please test with 1.0.27

**Comment by skulldealer** [comment]
> Please test with 1.0.27

You are a LEGEND.

**Comment by ventoy** [comment]
Anything else?

**Comment by skulldealer** [comment]
Yeah I am closing this thread for now. Will be creating a new one soon a week or two later and will share everything I know that you can do to add macbook support to ventoy. It will be kind of experimental bet release.
