### ISSUE TITLE
.img support

### ISSUE THREAD

**Issue by rajib-raiyat** [ventoy/Ventoy#556]
A few days ago I took the Tails OS image file to the pen drive which had ventoy installed. When I turn on the boot option on the PC, I see that the other .iso files in my pen drive are showing up but the file of tails os .img is not showing up.

I want to know ventoy does not support .img?

**Comment by skulldealer** [comment]
Check this out

[https://www.ventoy.net/en/plugin_vtoyboot.html]()


Please download official iso file from tails website will work similarly

**Comment by ventoy** [comment]
Tails.img is supported in latest release.

This is an old issue. I will close it now.
If you still have problem with latest Ventoy release, you can reopen the issue.
