### ISSUE TITLE
有没有可能注入文件到ISO安装镜像中

### ISSUE THREAD

**Issue by chenrizhi** [ventoy/Ventoy#557]
在给服务器安装Linux系统时，不同的服务器可能需要给GRUB传递不同的启动参数，现在要么自定义ISO镜像，要么在启动界面手工修改启动参数再进行启动，操作比较繁琐。

如果ventoy能提供注入文件到ISO安装镜像的能力，那么就能大大简化此类操作。

**Comment by ventoy** [comment]
可以看下 最新  1.0.27版本的新功能
https://www.ventoy.net/cn/plugin_bootconf_replace.html
