### ISSUE TITLE
cannot run eeupdate.efi

### ISSUE THREAD

**Issue by ystartgo** [ventoy/Ventoy#558]
cannot run eeupdate.efi show InitShellApp: Application not started from Shell

**Comment by ystartgo** [comment]
In ventoy-1.0.26

**Comment by ventoy** [comment]
From the output information, Maybe you can put a shell.efi along with eeupdate.efi and firstly boot shell.efi  and then boot eeupdate.efi from efi shell.

**Comment by ystartgo** [comment]
I try shell.efi is work, but need put eeupdate.efi  in first disk ,  defualt shell.efi is not support htfs or exfat at ventoy label disk

**Comment by ventoy** [comment]
Yes, only fat is supported by UEFI spec.
So you need to put the eeupdate.efi file int the VTOYEFI  label disk.
Or you can preserver some space at the end of the USB drive and format it with FAT32 and put eeupdate.efi in it.
https://www.ventoy.net/en/doc_disk_layout.html#reserve_space

**Comment by ventoy** [comment]
Another little more complicated way:

Run the follows script in a Linux shell envrioment.

```
dd if=/dev/zero of=eeupdate.img.vtoy bs=1M count=8
mkfs.vfat eeupdate.img.vtoy
mkdir efimnt
mount eeupdate.img.vtoy efimnt
mkdir -p efimnt/EFI/BOOT
cp shell.efi efimnt/EFI/BOOT/bootx64.efi
cp eeupdate.efi efimnt/EFI/BOOT/
umount efimnt
rm -rf efimnt
```

Copy the eeupdate.img.vtoy file to the USB drive and boot by Ventoy.

**Comment by ventoy** [comment]
You can download 
https://github.com/ventoy/statictool/blob/main/ventoy/eeupdate.img.xz

decompress it and copy eeupdate.img to the USB drive and boot from Ventoy.

**Comment by ystartgo** [comment]
Thanks , https://github.com/ventoy/statictool/blob/main/ventoy/eeupdate.img.xz is work shell and run eeupdate
