### ISSUE TITLE
Ventoy 1.0.26 can't be used to install Fedora Server 32 or Fedora Server 33

### ISSUE THREAD

**Issue by patbarron** [ventoy/Ventoy#560]
Neither Fedora Server 32 nor Fedora Server 33 can be successfully installed when booted from Ventoy 1.0.22.  The Server ISOs do boot successfully, and the installer does start up - but the installer doesn't see the virtual optical drive to install packages from - it does see the USB device that was booted, and the individual partitions on it, but the installer just sees these as local filesystems.

Whatever this issue is, it does not affect Fedora Workstation 32 or Fedora Workstation 33, both of which can be successfully booted, run, and installed when booted from Ventoy.

I first noticed this issue with Ventoy 1.0.22, but have confirmed it still exists as of Ventoy 1.0.26.

**Comment by ventoy** [comment]
I test Fedora Server 32 in Virtual Machine UEFI mode. It workd fine util installed finish, and reboot.
I will test in a real machine later.

**Comment by patbarron** [comment]
Thanks for the feedback!  My attempt was done on a real machine, with legacy BIOS (not UEFI - this motherboard does not support UEFI).

**Comment by ventoy** [comment]
OK, good news.
