### ISSUE TITLE
[Feature Request] Image mapping mode?

### ISSUE THREAD

**Issue by DX37** [ventoy/Ventoy#561]
Hi there. Is there any chance that Ventoy can be coded to map ISO image to become whole USB drive? Just temporarily.

There's one case, where it could be useful: SCCM offline Windows installation, where unpacked install image boots from USB and applies system to drive, and then after reboot it continues to use unpacked install image to install programs and run scripts.

Is it possible? :)

**Comment by ventoy** [comment]
The map is only available during boot process and is gone after kernel boot.
So it's impossible to do this.

**Comment by DX37** [comment]
Ok, I understand. Thanks for answer!
