### ISSUE TITLE
legacy 无法引导多个Linux发行版

### ISSUE THREAD

**Issue by Cathgao** [ventoy/Ventoy#562]
测试电脑为HP elitebook 8570w，ventoy版本为1.0.26，引导方式为legacy（BIOS）
测试镜像有：
boot-repair-disk-64bit.iso
cn_windows_10_business_editions_version_1909_updated_jan_2020_x64_dvd_b3e1f3a6.iso
ubuntu-20.04.1-desktop-amd64.iso
ubuntu-20.04.1-live-server-amd64.iso

只有win10光盘镜像能成功引导，其余Linux发行版均在splash后报没有可用的引导设备
![IMG_20201028_141439](https://user-images.githubusercontent.com/21031564/97400505-309f5000-192a-11eb-8adf-1458d327796c.jpg)

**Comment by Cathgao** [comment]
exsi7.0镜像可以成功引导

**Comment by ventoy** [comment]
Linux 停下来的时候看看能不能进入一个命令行界面，如果可以的话支持两个命令看看结果。
```
blkid
cat /ventoy/log
```

**Comment by Cathgao** [comment]
> Linux 停下来的时候看看能不能进入一个命令行界面，如果可以的话支持两个命令看看结果。
> 
> ```
> blkid
> cat /ventoy/log
> ```
测试镜像为ubuntu-20.04.1-desktop-amd64.iso
![IMG_20201028_155936](https://user-images.githubusercontent.com/21031564/97408666-626ae380-1937-11eb-921c-50cf930f417f.jpg)

**Comment by ventoy** [comment]
This is an old issue. I will close it now.
If you still have problem with latest Ventoy release, you can reopen the issue.
