### ISSUE TITLE
Win10 is not booting from Ventoy, without any error message

### ISSUE THREAD

**Issue by SaryZainoun** [ventoy/Ventoy#563]
When trying to boot from win10.iso on Ventoy usb, a black window appears for seconds and then it returns to Ventoy's main screen.

I can boot from kaspersky rescue disc .iso on the same usb after applying (set check_signatures=no).

The same usb works fine on other laptops and win10 boot normally.

I have tried to disable secure boot, it didn't work.

**Comment by ionelmc** [comment]
I had the same problem when booting in UEFI mode from the usb stick. Booting in legacy mode worked as expected.

**Comment by SaryZainoun** [comment]
> I had the same problem when booting in UEFI mode from the usb stick. Booting in legacy mode worked as expected.

Will give a try

**Comment by ventoy** [comment]
Currently I have no idea about it.
Better with some photo with latest ventoy release.

**Comment by olos00** [comment]
I came across this issue as well, had to disable CSM support from uefi settings then windows 10 started booting up.
This was in Gigabyte AB350-Gaming3 motherboard, and Windows Win10_20H2 iso

**Comment by Bananaman** [comment]
> I came across this issue as well, had to disable CSM support from uefi settings then windows 10 started booting up.
> This was in Gigabyte AB350-Gaming3 motherboard, and Win10_20H2 iso

Thanks a lot for posting the solution! CSM is "Compatibility Support Module" and emulates BIOS on UEFI machines.

Having CSM/BIOS enabled probably confuses either Ventoy or Windows.

It is always best to be in pure UEFI mode with CSM disabled.

**Comment by ventoy** [comment]
This is an old issue. I will close it now.
If you still have problem with latest Ventoy release, you can reopen the issue.
