### ISSUE TITLE
通过查找windows boot 引导进入win7 会丢失系统激活

### ISSUE THREAD

**Issue by jgx91** [ventoy/Ventoy#564]
开机启动进入iso列表界面后，按F4，通过查找windows boot 引导进入win7 会丢失系统激活，进入系统后提示未激活

**Comment by a1ive** [comment]
这说明你可能是盗版软件的受害者。
你用了盗版的win7系统，激活软件会把bootmgr替换为一个可以修改slic的bootloader。

**Comment by ventoy** [comment]
F4里面启动Windows使用的是grub2的 ntldr 命令。
如果是 @a1ive  说的原因的话，你可能需要自己写一个菜单，使用 chainload的方式启动Win7所在硬盘上的bootloader。
