### ISSUE TITLE
Feature request: Recovery Linux partition.

### ISSUE THREAD

**Issue by pthfdr-42** [ventoy/Ventoy#567]
Instead of 2 partitions, you can add an option in the installer to create an additional UDF partition (supports UNIX attributes) so you can copy a Linux rootfs to it and add a menu entry in GRUB to boot `/vmlinuz` with parameters specified in `/params` (rootfs and initrd support).
Maybe you should also make the ISO partition UDF as well.
It has 2 advantages:
1. Since the kernel is directly loaded, you only need a rootfs instead of the whole LiveCD+persistance and you do not need to deal with a bootloader inside the bootloader.
2. It would be compatible with both BIOS and UEFI since the rootfs does not need to be bootable.

**Comment by ventoy** [comment]
All these are supported by Ventoy. 
But this is not necessary for everybody, so ventoy will not add this option in the installer, you need to do this by yourself.
https://www.ventoy.net/en/doc_disk_layout.html#reserve_space
