### ISSUE TITLE
usb drive boots to grub cmd line (with workaround)

### ISSUE THREAD

**Issue by rayluo** [ventoy/Ventoy#569]
Thanks @ventoy Long Panda for Ventoy project!

1. Today I try install Ventoy into a 500GB external USB hard disk. The Ventoy installation process went smooth (or so I thought; more on this later).

2. When booting I got the same error:

![Same error](https://user-images.githubusercontent.com/221623/83438147-36f3d380-a441-11ea-8009-e05560df99dc.JPG)

  I then tried [workaround 1 & 2 for the legacy 137gb limit](https://www.ventoy.net/en/doc_legacy_limit.html), tried using UEFI instead of Legacy, tried different computer. None worked.

3. Until, I attempted `sudo ./Ventoy2Disk.sh -u /dev/sdd` trying to update it, it gave this error.

> /dev/sdd does not contain ventoy or data corupted
>
> Please use -i option if you want to install ventoy to /dev/sdd

This error inspires me to use `dd` to dump the second partition from a working Ventoy flash drive, and write it into my usb hard drive. This fixes the issue.

4. Now looking back, there were many error message during my step 1 installation.

```
...
mkfs.fat 4.1 (2017-01-24)
mkfs.vfat: /dev/sdd2 contains a mounted filesystem.
1 retry ...
mkfs.fat 4.1 (2017-01-24)
mkfs.vfat: /dev/sdd2 contains a mounted filesystem.
1 retry ...
mkfs.fat 4.1 (2017-01-24)
mkfs.vfat: /dev/sdd2 contains a mounted filesystem.
1 retry ...
mkexfatfs 1.3.0
Creating... done.
Flushing... done.
File system created successfully.
...
```

That was presumably caused by my Linux system auto-mount the 2nd partition, and then Ventoy installation script was not able to write data into it, and ended up the 2nd partition remaining empty. So, a better workaround would be, to manually unmount that partition quickly so that Ventoy's retry would succeed.

It would still be nice to change/fix Ventoy so that in the situation above, do NOT proceed, but should error out at the spot.

**Comment by skulldealer** [comment]
Yeah that is happening with me also when I specifically boot into some distros from ventoy menu.

**Comment by ventoy** [comment]
There is  a shell script    `tool\VentoyWorker.sh`   

```
#check mountpoint
grep "^$DISK" /proc/mounts | while read mtline; do
    mtpnt=$(echo $mtline | awk '{print $2}')
    vtdebug "Trying to umount $mtpnt ..."
    umount $mtpnt >/dev/null 2>&1
done

if grep "$DISK" /proc/mounts; then
    vterr "$DISK is already mounted, please umount it first!"
    exit 1
fi
```

Ventoy will check whether /dev/sddX is mounted and try to umount it and will exit if still mounted.
I wonder why the check did't take effect.
You can do some debug about this.

**Comment by devrob20** [comment]
i have seen the same thing happening, bottomline best way to setup a ventoy disk is in ubuntu (gnome) livecd or install, make sure u have exfat-utils and fuse (sudo apt install exfat-utils fuse qemu virt-manager boxes) otherwise the partition for sdc2 is formatted in fat16 and no bootflag is set.

https://linuxconfig.org/how-to-create-a-multiboot-usb-with-ventoy#h3-step-2-prepare-the-usb-device
