### ISSUE TITLE
Make text mode default mode in ventoy grub

### ISSUE THREAD

**Issue by skulldealer** [ventoy/Ventoy#570]
I really want to have only text mode as default on ventoy usb and don't want that background.png as wallpaper.

Any plugins suggestions?

**Comment by ventoy** [comment]
https://www.ventoy.net/en/plugin_theme.html
```
{
    "theme": {
        "display_mode": "CLI"
    }
}
```

**Comment by skulldealer** [comment]
Ok thanks
