### ISSUE TITLE
What is your preferable language? 

### ISSUE THREAD

**Issue by skulldealer** [ventoy/Ventoy#572]
I am about to post my research on how to make ventoy better by enabling support for macbooks.

It is pretty long post which I am preparing.

So please let me know your preferable language English or Chinese. I am confused. I could post translation of the research for you in Chinese if you want. Sorry for the dumb question.

As per my knowledge Google translate is not available in China. So you local English to Chinese translation could be buggy and may give wrong results while translating from English to Chinese. May create misunderstanding.

If you understand English well then let me know. I will post in English else i could post a very well translated English post in simplified Chinese.

**Comment by a1ive** [comment]
作者是国人。

**Comment by skulldealer** [comment]
好吧，我将用中文发表我的研究成果，以便作者更好地理解

**Comment by skulldealer** [comment]
I will post it in both Chinese and English.

我将用中文和英文发布

**Comment by blackcrack** [comment]
@skulldealer , would be nice if you speak/write in english for the rest of the world, because the head/motherlanguage is not german or an other language to any understand what is is write,
would very nice if the rest of the western world also understand what it is wrote.
best

**Comment by skulldealer** [comment]
I will post everything in both the languages   English as well as simplified Chinese. So don't worry.
