### ISSUE TITLE
Legacy mode blind monitor in serial console

### ISSUE THREAD

**Issue by ystartgo** [ventoy/Ventoy#573]
Hi, In ventoy-1.0.27, uefi mode can be displayed in the serial console, in the legacy mode, the blind monitor of ventoy cannot be used, only show text GRloading...
您好,在ventoy-1.0.27中，uefi 模式中可以在 serial console 顯示畫面，在 legacy 模式中，不能使用 ventoy 無畫面，僅顯示 GRloading ...

**Comment by ventoy** [comment]
Please refer https://www.ventoy.net/en/plugin_theme.html
```
display_mode: serial  or  serial_console
serial_param
```

**Comment by ystartgo** [comment]
ok, thanks 
I use /ventoy/ventoy.json

{
    "control_legacy": [
        { "VTOY_DEFAULT_MENU_MODE": "1" },
        { "VTOY_FILT_DOT_UNDERSCORE_FILE": "1" }
    ],
    
    "control_uefi": [
        { "VTOY_DEFAULT_MENU_MODE": "1" },
        { "VTOY_FILT_DOT_UNDERSCORE_FILE": "1" }
    ],
    
    "theme_legacy": {
        "display_mode": "CLI"        
    },
    
    "theme_uefi": {
        "display_mode": "CLI" 
    }
}
