### ISSUE TITLE
[Feature Request] Default ISO persist mounted on System 

### ISSUE THREAD

**Issue by soares23** [ventoy/Ventoy#574]
Hi,

If it's possible that if we can have an option to persist mounted the Windows Iso after install process.
I have scripts that install Software on Setupcomplete phase but i don't want that all the Software are copy to drive install and that remove it because of that i have create a script that search the files on usb drive (Mounted ISO) to install from that.
My problem actually is that i have the ISO with all that Stuff and i have to copy the Software part also to root of my drive because the Iso install drive isn't mounted on boot after installation.

If we can have an option that can mount one specific ISO on initialisation of ventoy maybe in combination with default ISO and persist that would be nice if it's possible. If not is ok is not a must have but would be nice if possible, to realise.

**Comment by ventoy** [comment]
The ISO must be mounted by yourself.
When you install Windows, Ventoy insert a program into the PE enviroment to help you mount the ISO before start the installer.
So you didn't perceive this process.

But after install process, nobody will mount the iso as you think. So you must mount it yourself.

**Comment by soares23** [comment]
ok no Problem thanks i would be only an option i will see to mount it manually per script but thanks in adanced for you reply an for your great work.
