### ISSUE TITLE
Problems when commiting to languages.ini

### ISSUE THREAD

**Issue by luzeagithub** [ventoy/Ventoy#58]
There is some problem when editing the languages.ini file.
It must be UTF-16LE. (because of the chinese characters?)
![image](https://user-images.githubusercontent.com/62355456/81102946-a218bb80-8f10-11ea-8e8a-d4dbec127b22.png)
You can't edit those files via web editor, so you (@ventoy) has to re-format the file every time someone's pulling changes.
I suggest having one file for every language, would be much easier for you, @ventoy, or not?

EDIT: You **can** edit them, but it will save them in UTF-8.

**Comment by ventoy** [comment]
Yes, it's UTF-16 now.
UTF-16 is needed for some languages like chinese, japanese ....
GetPrivateProfileString/GetPrivateProfileInt Windows APIs only support UTF-16.

One file for every language is an option, but it may end up with too many ini files.

Besides, it's not too trublesome to deal with the ini file encoding. So let it be now.
