### ISSUE TITLE
UEFI ISSUE WITH VENTOY

### ISSUE THREAD

**Issue by skulldealer** [ventoy/Ventoy#581]
there is a small problem with uefi in ventoy.

In my boot menu it says boot option set to uefi ventoy but boots into bios. I doubted that it is a problem with my bios so I checked other usb by booting it with Rufus, Balena etcher and unetbootin. They perfectly booted into UEFI while only ventoy boots in bios.

Then I created a new boot option and tested all .efi files in ventoy partition but no success in booting in uefi. Is there a plugin ventoy.json to boot me into UEFI? 

I did not notice this for a month. But suddenly I realised.

**Comment by ventoy** [comment]
It's the firmare in the motherboard to decide to boot Ventoy in Legacy BIOS mode or UEFI mode. 
You can disable CSM option in your BIOS setup and retry.

**Comment by skulldealer** [comment]
Thanks done.
