### ISSUE TITLE
Ventoy not showing up in boot menu

### ISSUE THREAD

**Issue by coreytl-github** [ventoy/Ventoy#586]
When i go into my boot menu, theres nothing for ventoy. Put some system information in the file below if that helps, reply if i need to add anything else, thanks!
[sysInfo.txt](https://github.com/ventoy/Ventoy/files/5539608/sysInfo.txt)

**Comment by ventoy** [comment]
Maybe something about UEFI Secure Boot. Please disable the Secure Boot option in BIOS setup.

**Comment by coreytl-github** [comment]
I already had it disabled.

**Comment by ventoy** [comment]
1. Please make sure that if you make a bootable USB drive by other tool(e.g. rufus) there is a boot option in the BIOS boot menu.
2. Please try with GPT partition style.

**Comment by candrapersada** [comment]
> I already had it disabled.

how to repair the boot loader Ventoy without losing data? for Ventoy BIOS MBR.

**Comment by coreytl-github** [comment]
Sorry for keeping this open, completely forgot.

**Comment by UniFanNumOne** [comment]
having the exact same issue, been stuck here for hours. USB boot is enabled, secure boot is disabled, etc. no luck.

**Comment by zellybean5** [comment]
same here, im pretty sure ventoy worked on my pc a long time ago, but now it wont work (using a fresh install of course)
