### ISSUE TITLE
Usb key emptied

### ISSUE THREAD

**Issue by kasylozy** [ventoy/Ventoy#589]
When we recreate the windows boot from the command line installation iso

bootrec / fixmbr
bootrec / fixboot
bcdboot E: \ Windows / l en-en / s E: / f UEFI

The key ventoy this vacuum completely and this format

![Capture](https://user-images.githubusercontent.com/4899491/99160792-ea334a80-26b8-11eb-96db-19be0b13a6b6.PNG)

![ABEBE233-8CB2-4CB0-B94B-9BF751848F49](https://user-images.githubusercontent.com/4899491/99155781-1b942200-2689-11eb-82cf-1f457bc496e8.jpeg)

![AAB39EE2-B685-47C7-9F21-7C48C533EBDB](https://user-images.githubusercontent.com/4899491/99155791-35356980-2689-11eb-9b47-c22e878b6145.jpeg)

![23D3151F-1614-4C8A-8735-D849B8396197](https://user-images.githubusercontent.com/4899491/99155799-4b432a00-2689-11eb-8c5b-de32eb8fe98a.jpeg)

**Comment by Master-Bob45** [comment]
Hello I also have this problem when I do the same thing as you @ventoy possible to correct this thank you

**Comment by TechCare-Aus** [comment]
I also had this issue. How to recover?

**Comment by hurzl** [comment]
It is still happening
