### ISSUE TITLE
Problems with Debian ISO's

### ISSUE THREAD

**Issue by Gyppie** [ventoy/Ventoy#59]
Hi!
I have problems with installing debian in graphics mode, and installing from debian-firmware-netinst iso's. It work up until the point where the install are going to install and start Tasksel. Are debian-firmware iso's compatible with Ventoy? Normal install (not graphics) work from debian-10.3.0-amd64-DVD-1.iso.

**Comment by ventoy** [comment]
Maybe it's not Ventoy's problem if normal install OK but graphics install fail for the same ISO.
Can you confirm that graphics install is ok with your machine? Maybe you can use another similar tool to create a bootable USB with the iso file and make a comparison test.

**Comment by Gyppie** [comment]
Graphics install works on my computers. Tested it on multiple computers. debian-10.3.0-amd64-DVD-1.iso works wit the normal install. But not graphics. firmware-10.3.0-amd64-netinst.iso doesnt install and have the same problem both in graphics and normal install. It stops at Tasksel. The same happens to debian-10.3.0-amd64-netinst.iso. Everything works fine up to the point of tasksel. I used aioboot in the past. It worked there, but I had to modify the debian ISO's and use the vmlinuz and initrd.gz from debian hd-install to map the iso correctly. I tried those ISO's in Ventoy also, but that failed.

**Comment by mangoscn** [comment]
debian-10.4.0-amd64-DVD-1.iso 安装不了，可以启动，但是不能完成安装（Graphics install 和 Install都试了），选择软件那里只有 standard system utilities 一个包可以选，最后以 GRUB installation failed 结束，和 Gyppie 一样的情况，在 Tasksel 这里出问题了

**Comment by mangoscn** [comment]
对 debian iso 文件所在文件夹做了磁盘 contiguous 后，安装时可以正常过 Tasksel 了，但是结果还是一样不成功（上面安装不成功的情况与做了 contiguous 不成功的情况都是可以复现的，使用 Ventoy 在 Linux 系统与 Win 系统下制作了多次启动 U 盘实验过）
不知道如果对整个 U 盘都做一次 contiguous 会不会就可以正常安装了，得空再试试

**Comment by ventoy** [comment]
最新版本应该修复了。
