### ISSUE TITLE
安装到移动硬盘时Localboot无法正确找到BOOTX64.EFI

### ISSUE THREAD

**Issue by HiFiPhile** [ventoy/Ventoy#592]
- 版本：1.0.28
- 本地硬盘：960 Evo NVME
- 本地分区：GPT, EFI fat32, Windows ntfs, Debian ext4
- 本地引导：`/efi/boot/bootx64.efi`: systemd-boot, `/EFI/Microsoft/Boot/bootmgfw.efi` Windows boot manager

Ventoy安装在移动硬盘上，执行'Search and boot Windows'可以启动Windows，执行'Search and boot BOOTX64.EFI'屏幕一闪回到主界面，没有"BOOTX64.EFI NOT found ..."错误，应该是Ventoy又启动了一遍自身。

查看`localboot.cfg`发现并没有排除Ventoy自身的EFI分区。

由Ventoy启动到EFI Shell后，执行`FS0:` `\efi\boot\bootx64.efi`可以成功手动启动。

**Comment by ventoy** [comment]
1.0.29版本已修改。
