### ISSUE TITLE
单纯的吐槽而已

### ISSUE THREAD

**Issue by t3225210** [ventoy/Ventoy#599]
这个启动工具与我理想中的有很大不同
首先第一点
分区结构固定, 第一分区起始位置必须在第2048扇区, efi分区只能是第二分区
如果我需要将它移植到一块已经存在系统的移动硬盘上,就会很难,需要重新格盘
第二点
我下载了作者的源码进行修改,强制将efi分区设置到第一分区, ISO分区设置到第六分区
但是这样做了之后能启动Windows系列系统,包括PE,Linux系统全部NG

**Comment by ventoy** [comment]
1. Ventoy从最开始就是这样设计的，它完全符合我自己的设计思路。因为不符合你心中的想法而吐槽我觉得没什么道理。
2. 这个更没道理了，你使用了一个开源软件，修改了部分代码，不符合自己的预期肯定是因为没有整体理解这个软件、没有修改完全，这有什么好说的呢？

**Comment by a1ive** [comment]
> 第二点
我下载了作者的源码进行修改,强制将efi分区设置到第一分区, ISO分区设置到第六分区
但是这样做了之后能启动Windows系列系统,包括PE,Linux系统全部NG

说明你改错了。
