### ISSUE TITLE
同时插2个U盘的问题

### ISSUE THREAD

**Issue by heham** [ventoy/Ventoy#6]
两个不同品牌不同容量的U盘，能正常安装，但是安装完只显示一个，查看磁盘管理器显示脱机，签名冲突。

**Comment by ventoy** [comment]
这种情况我确实没测试过。我会测试一下。 另外，你方便的话可以帮忙测试下，先插1个U盘，安装，再插另一个U盘，安装。 这种顺序有没有问题。
多谢！

**Comment by heham** [comment]
> 
> 
> 这种情况我确实没测试过。我会测试一下。 另外，你方便的话可以帮忙测试下，先插1个U盘，安装，再插另一个U盘，安装。 这种顺序有没有问题。
> 多谢！

测试的就是先插一个安装再插一个安装，安装前盘符里面的文件都能够正常，安装也能完成，但是安装完成后只有之前插的那个能显示盘符访问，后面那个不行，到磁盘管理里面查看显示脱机，签名冲突，度娘了一个这样的https://zhidao.baidu.com/question/182520280.html，还没操作

**Comment by heham** [comment]
用diskgenius查看了一下，因该就是下面这个参数的问题，两个盘这个参数是一样的
MBR Signature:	11D7AE9B

**Comment by ventoy** [comment]
Ventoy 1.0.04版本已发布，我修改了这个地方。我手头只有1个U盘。你方便的话可以测试一下。

**Comment by heham** [comment]
谢谢，已经解决了

**Comment by ventoy** [comment]
好的，多谢！
