### ISSUE TITLE
update to v1.0.29 input/output error

### ISSUE THREAD

**Issue by fdisp** [ventoy/Ventoy#600]
partitioning tools like gnome-disk-utility stop responding.

terminal output below:

user@0:~/Downloads/ventoy-1.0.29$ sudo sh Ventoy2Disk.sh -u /dev/sde
[sudo] password for user: 

**********************************************
      Ventoy: 1.0.29
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

Upgrade operation is safe, all the data in the 1st partition (iso files and other) will be unchanged!

Update Ventoy  1.0.27 ===> 1.0.29   Continue? (y/n)y

rm: cannot remove './tmp_mnt/EFI/BOOT/BOOTX64.EFI': Input/output error
rm: cannot remove './tmp_mnt/EFI/BOOT/grubx64.efi': Input/output error
rm: cannot remove './tmp_mnt/EFI/BOOT/MokManager.efi': Input/output error

**Comment by ventoy** [comment]
And then? The Ventoy version still 1.0.27? or your USB corrupted?

**Comment by fdisp** [comment]
> And then? The Ventoy version still 1.0.27? or your USB corrupted?

no damage to the usb filesystem, and no changes, though i had to remove it physically for the system to start responding.
after rebooting, i tried to update again.
there were some errors but booting from the updated usb showed that the usb was updated successfully

**Comment by fdisp** [comment]
@ventoy i'm thinking about closing this issue because i can not reproduce. i believe that there could have been some interference from gnome-disk-utility or something accessing the usb, what do you think?

**Comment by ventoy** [comment]
I think so.
