### ISSUE TITLE
primeos cannot start

### ISSUE THREAD

**Issue by undefined-moe** [ventoy/Ventoy#601]
using primeos mainline 0.4.5.iso, installation stuck at "Detecting primeos"

**Comment by ventoy** [comment]
Primeos is not in the support list.
I will try to support is if possible.

**Comment by ventoy** [comment]
It will be supported in the next release.

**Comment by ventoy** [comment]
Please try with 1.0.30

**Comment by ventoy** [comment]
Should be supported in latest release . I will close this issue.
