### ISSUE TITLE
win10最新系统中无法识别优盘

### ISSUE THREAD

**Issue by sofs2005** [ventoy/Ventoy#602]
好像在win10最新版本上（20H2）上ventoy完全无法识别插上的优盘，之前都是正常的，现在我手上3个优盘都无法识别。之前都是装过老版本的，现在识别不到也更新不了。

**Comment by ventoy** [comment]
请参考 https://www.ventoy.net/cn/faq.html#faq_install_cannot_list_usb

**Comment by sofs2005** [comment]
知道了，应该是那个分区软件的冲突
