### ISSUE TITLE
Disk Encryption

### ISSUE THREAD

**Issue by svh1985** [ventoy/Ventoy#604]
Maybe a weird request;
As most of us are using USB-Sticks, which we all know, have a tendency to get lost, would it be possible to add disk encryption?

Thanks!

**Comment by ventoy** [comment]
Disk encryption is not supported.

**Comment by MaximilianKohler** [comment]
For anyone else wondering, the solution is https://forums.ventoy.net/showthread.php?tid=56

When creating/formatting the USB drive initially with Ventoy, first go to "option" -> partition configuration, and select "preserve space at end of disk". The amount of space you preserve will be your 2nd+ partition which you can use to store your files and encrypt that whole partition. 

It may be useful to add this to the FAQ https://www.ventoy.net/en/faq.html
