### ISSUE TITLE
Nobis tablet UEFI 32 bits

### ISSUE THREAD

**Issue by mkultimate** [ventoy/Ventoy#605]
One question, there is the possibility that it works with 32-bit uefi because I have a Nobis intel tablet, it would be good if it has support for 32-bit uefi since when I use the ventoy it does not work only on computers with 64-bit uefi

**Comment by ventoy** [comment]
Ventoy only support x86_64 efi now.

**Comment by mkultimate** [comment]
checking the efi folder only the BOOTX64.EFI file appears, I have tried on several windows tablets but it works when placing the usb the tablet starts normally without problem, the different thing that the tablets have is that they use 32 bit uefi

**Comment by ventoy** [comment]
Ventoy only support 64-bit UEFI from the beginning.

**Comment by ventoy** [comment]
Ventoy-1.0.30 supports IA32 UEFI, you can make a try.
