### ISSUE TITLE
Preserve some space at the bottom of the disk

### ISSUE THREAD

**Issue by RafaelTR** [ventoy/Ventoy#607]
This space-saving scheme is very complicated. I've used online converters and I can't find the value of an external 2 Tb hard drive (the program doesn't accept any value). I want to use 35 Gb for Ventoy and everything else for files. Any suggestion? Ventoy could detect the size of the device and have a sliding needle

**Comment by ventoy** [comment]
Indeed, a aliding needle is better,  however,  mostly maybe we don't need a very precise value.
If your drive is 2TB,  you can set preserve space  2048GB - 35GB = 2013GB, so you input 2013 GB in the program.
Mostly, the space for a 2TB drive is about 2000GB, so you can input 2000GB - 35GB=1965GB

Before I add this option, the most asked question is  "I want to preserve  4GB space for a new partition and everything else for Ventoy."

**Comment by RafaelTR** [comment]
Those values ​​you mentioned don't work!

https://drive.google.com/file/d/1KaQYB7-PC3K8xNTyR26CTcE3tc1v0HaG/view?usp=sharing

**Comment by ventoy** [comment]
OK, please show the `log.txt`

**Comment by RafaelTR** [comment]
I'm just putting 35 Gb and leaving it at the end of the record, it's easier. I was wanting to put the Ventoy partition first because the ISO files are not shown in the list, it looks like this has been fixed.
