### ISSUE TITLE
Question: Is manual installation on an external USB HDD possible?

### ISSUE THREAD

**Issue by leinardi** [ventoy/Ventoy#608]
I have a 500GB disk that I would like to use with Ventoy but, on this disk, I have already several partitions.

I was wondering how complex would be to do a manual installation of Ventoy.

I have already a working copy of Ventoy on a USB pen drive with, with the following partitions:
```
/dev/sdd1   *         2048 15728639 15726592  7,5G  7 HPFS/NTFS/exFAT
/dev/sdd2         15728640 15794175    65536   32M ef EFI (FAT-12/16/32)
```
If I recreate the same partitions on the HDD, mark the first partition as bootable and copy over the content of the EFI partition, do I have to do anything else for Ventoy to work from the HDD?

**Comment by ventoy** [comment]
It should works in UEFI mode.
But in Legacy BIOS mode you need to do something else. 
You can refer  `Ventoy2Disk.sh`   which contains all the steps to install Ventoy.

**Comment by leinardi** [comment]
Thanks!

**Comment by candrapersada** [comment]
> But in Legacy BIOS mode you need to do something else.
> You can refer Ventoy2Disk.sh which contains all the steps to install Ventoy.

how to manual installation without losting data on at the bottom of the disk?

> Reserved Disk Space
