### ISSUE TITLE
最新版ventoy无法正常进入deepin20（1003）的安装界面

### ISSUE THREAD

**Issue by vqsld** [ventoy/Ventoy#609]
正常显示ventoy界面，但再grub界面选了“deepin-desktop-community-1003-amd64.iso”后再进入正常的安装模式，就一直停留在deepin logo了，电脑没有死机，deepin logo也在闪，就是进不去安装界面

**Comment by ventoy** [comment]
我下载测试了 
···
deepin-desktop-community-1003-amd64.iso
MD5: b073db6142dc233036a713201e55846f
···

在我的笔记本上测试，Legacy BIOS 模式和UEFI模式都是可以正常启动到安装界面的。

**Comment by a1ive** [comment]
在闪 deepin logo 的时候按 Ctrl+Alt+F1 看看输出？

**Comment by vqsld** [comment]
> 
> 
> 在闪 deepin logo 的时候按 Ctrl+Alt+F1 看看输出？

Ctrl+Alt+f1和Ctrl+Alt+F2都没有反应哎……Ctrl+Alt+delete能重启

**Comment by ventoy** [comment]
只有这个iso有问题吗？其他的都没问题？

**Comment by vqsld** [comment]
> 
> 
> 只有这个iso有问题吗？其他的都没问题？

破案了，是deepin不兼容绿联的USB 3.2 Gen 2的集线器，拔了直接插USB 3.2 Gen 1口上就能进安装界面了。

**Comment by vqsld** [comment]
> 
> 
> 只有这个iso有问题吗？其他的都没问题？

以前都是用USB 2.0优盘装的，就昨天第一次用3.2 Gen 1的来装
