### ISSUE TITLE
main partition by default is in exFAT, but it should be configurable in the UI when you install Ventoy, in order to have more compatibility with older mainboards that are non compatible with exFAT.

### ISSUE THREAD

**Issue by MELERIX** [ventoy/Ventoy#611]
also to avoid having to reformat the main partition after you install Ventoy.

**Comment by ventoy** [comment]
Ventoy use an open source library to format exfat, not with windows's native interface. So it's a little trublesome to provide this option.
So I think now is OK. Just need to reformat it with right click.
