### ISSUE TITLE
Avira-Rescue-System doesn't start

### ISSUE THREAD

**Issue by hansnolte** [ventoy/Ventoy#613]
Secure Boot Off.
Tested with UEFI and legacy Mode.

/init: line 7: can't open /dev/sr0: No medium found

Download for the Avira Iso:
https://download.avira.com/download/rescue-system/avira-rescue-system.iso

Ventoy 1.0.29
Win 10 - 2002

**Comment by Traumlewis** [comment]
windows 10 with unattend.xml to. It doesn't start in legacy Mode.

**Comment by hansnolte** [comment]
The new Ventoy 1.0.30 release doesn't work with me either, neither in Legacy nor in UEFI mode.
My DELL monitor says shortly after I start AVIRA that it has no more signal and goes into Power Safe Mode.

**Comment by ventoy** [comment]
You mean with 1.0.29 you can boot to /init fail and with 1.0.30 even worse?
Please give some photo or video.

**Comment by hansnolte** [comment]
Hi ventoy-Team,

thanks for your feedback.

_"You mean with 1.0.29 you can boot to /init fail and with 1.0.30 even worse?"_
Yes.

Uefi-Boot-Video:
[avira-uefi.zip](https://github.com/ventoy/Ventoy/files/5684436/avira-uefi.zip)
The last Requester is the "no more Signal" message.
The Monitor goes into Power safe Mode and I have to do a hard reset.

Something else caught my eye.
Ventoy always sets my system clock back one hour. (Germany - UTC+01:00)

**Comment by ventoy** [comment]
Will it work fine if you make a bootable USB with the same ISO file by other tool(e.g. rufus) ?

**Comment by hansnolte** [comment]
Install with Rufus and it doesn't work.
Forget it, maby the ISO is to old for my System (Ryzen 3600).

Many thanks for your Help!
