### ISSUE TITLE
Resolution configuration does not save with 1.0.29

### ISSUE THREAD

**Issue by Adora16** [ventoy/Ventoy#615]
If I remember correctly, Ventoy 1.0.28 saved my resolution configuration, but 1.0.29 does not. It would be nice to have a persistent configuration, especially since the default resolution results in large text that makes it harder to navigate the menus.

**Comment by ventoy** [comment]
You can change resolution in 2 ways:
1. Press F5 to change it.   `<--- This is a temporary, and will not save in the next boot`
2. Use ventoy.json to set in theme plugin.   `<--- This is a persistence way.`
https://www.ventoy.net/en/plugin_theme.html
