### ISSUE TITLE
[Suggestion] 建议包含EFI Shell

### ISSUE THREAD

**Issue by HiFiPhile** [ventoy/Ventoy#616]
在执行一些简单操作,比如维护启动项的时候，EFI Shell很方便.。

现在很多的BIOS都没有内置EFI Shell，比如我手上的两张X570主板，一台MSI Intel Gen8的笔记本。

**Comment by ventoy** [comment]
Ventoy支持直接启动efi文件，就像启动ISO文件一样。
建议自己下载个EFI Shell的efi文件，比如 https://github.com/tianocore/edk2/blob/UDK2018/ShellBinPkg/UefiShell/X64/Shell.efi
就像普通ISO文件一样放在U盘里，想用时启动即可。而且这样也可以自己选择合适的shell版本，或者多放一些不同版本等，比集成到Ventoy里面更加灵活。

**Comment by woshishabii** [comment]
Ventoy是只能启动Shell.efi还是其他EFI也能启动？
我把我自己编写的EFI文件放到U盘之后文件并不会展示在菜单里（文件浏览菜单里也没有）
