### ISSUE TITLE
Ventoy Global Control Plugin Issue

### ISSUE THREAD

**Issue by duckimann** [ventoy/Ventoy#617]
As the example from [the page](https://www.ventoy.net/en/plugin_control.html)
`{
    "control": [
        { "VTOY_MENU_TIMEOUT": "10" },
        { "VTOY_DEFAULT_IMAGE": "F4>Boot the 1st local disk" }
    ]
}`

i managed to change it to

`{
    "control": [
        { "VTOY_MENU_TIMEOUT": "10" },
        { "VTOY_DEFAULT_IMAGE": "F5>Resolution Configuration>800x600x32>Esc>W10PE_x64.ISO" }
    ]
}`

but it didn't work and here is the screenshot ![](https://i.imgur.com/Fc7kQ1G.png)

**Comment by ventoy** [comment]
VTOY_DEFAULT_IMAGE can only be set to a menu. Can not return to parent level and run another menu again.
So `ESC` is not supported.

```
F2>Reboot <---- This is OK
F4>Boot the 1st local disk   <---- This is OK
F5>Resolution Configuration>800x600x32   <---- This is OK
F5>Check plugin json configuration (ventoy.json)>Return to previous menu [Esc]>Ubuntu.iso   <--- This is NOT ok.
```
