### ISSUE TITLE
Can existing ventoy partition be resized?

### ISSUE THREAD

**Issue by rayluo** [ventoy/Ventoy#618]
Thanks Long Panda for Ventoy!

Several questions here.

* I installed ventoy into my external 500GB hard drive, with the 2 default partitions only: one big `ventoy` partition in exFAT and a small `VTOYEFI` partition. And then I immediately reformatted the first partition to NTFS, and loaded some ISOs. One of the ISO is a 6 GB Windows 10 installation image. Then I use this to boot one of my computer and successfully install Windows 10, so all the fundamentals must be right. However, when I tried to repeat this process on my another older & BIOS-only computer, I can choose the Windows 10 ISO from Ventoy menu, but then the boot process just displayed an underscore `_` at upper left screen and then stuck there. Such symptom is different than the "Typical Behavior No.2" on [this page](https://ventoy.net/en/doc_legacy_limit.html), how do I know whether I hit the 137 GB issue? Does the fact that Ventoy can boot and I can boot some OTHER iso for this machine mean it is NOT the 137 GB issue?

* Assuming I do want to go ahead to resize my external hard drive into THREE partitions: a 130 GB `ventoy` partition to hold ISOs, the 32 MB `VTOYEFI` partition, and the rest for my other data. Can I simply resize the hard drive using normal tools? I'm currently using Linux, which already comes with GParted. Will it work? Why some more [complicated steps](https://forums.ventoy.net/showthread.php?tid=42) were needed?

**Comment by ventoy** [comment]
1. It's not the 137GB issue. Because you have boot into Ventoy's menu. Maybe a compatibility issues about Ventoy and your computer. You can try other ISO (e.g. Window8/8.1/7  or ubuntu/centos ...) to check whether this problem only with this windows 10 iso.

2. NO. You must reinstall Ventoy.

**Comment by rayluo** [comment]
Thanks for the quick response and your confirmation! I learned from it.

I tried 3 different Linux ISOs on the same external hard drive and they all work. I do not currently have, nor do I intend to install Windows 7/8.

So, at this point, it is safe to say it is some unknown compatibility issue among that computer, Windows 10 installation ISO, and perhaps Ventoy. Do you want me to grab any more info for you to debug? I'm fine to close this issue as-is.

**Comment by ventoy** [comment]
Maybe a compatibility issues.
