### ISSUE TITLE
安装完ventory后重启系统u盘无法自动挂载

### ISSUE THREAD

**Issue by Bluesands** [ventoy/Ventoy#619]
使用1.0.29版本在ubuntu18上安装完成后重启系统，无法找到U盘，无法拷贝iso镜像文件，使用cp命令复制iso文件到/dev/sdb1后，重启系统F12进入U盘安装提示无法找到iso文件，在官方文档没有找到解决办法，不清楚是什么原因导致的

**Comment by ventoy** [comment]
你后面说拷贝到 /dev/sdb1,  那不就是说U盘就是 /dev/sdb 吗。找不到U盘是什么意思？ 
你是指U盘没有自动挂载吗？在图形界面里面找不到U盘的图标啥的？

`使用cp命令复制iso文件到/dev/sdb1后`
这句具体是怎么拷贝的，把命令说一下，或者截个图。

U盘插入系统之后，系统是否会自动挂载取决于：
1. 自动挂载的配置有没有打开
2. 系统支不支持分区里的文件系统，即你这个ubuntu18支不支持exfat文件系统。

如果是没有挂载，你可以手动挂载。比如你确定 /dev/sdb1 就是U盘的第一个分区。你可以执行 
```
sudo mkdir -p /tmp/mntusb
sudo mount /dev/sdb1  /tmp/mntusb
cp xxxxx.iso   /tmp/mntusb/
```

**Comment by Bluesands** [comment]
ubuntu 我安装了 exfat-utils，重启系统后，重新安装ventory，系统依旧没挂载U盘
我安装你提供的命令手动挂载，会报错如下错误
mount: /tmp/mntusb: more filesystems detected on /dev/sdb1; use -t <type> or wipefs(8)

在这之前已经安装了exfat-utils

**Comment by ventoy** [comment]
你执行几个命令看看：
```
blkid
lsblk
fdisk -l /dev/sdb
```

**Comment by Bluesands** [comment]
执行 sudo mount -t exfat /dev/sdb /mnt/mntusb 就可以手动挂载了，ubuntu和其他发行版linux有点区别

**Comment by ventoy** [comment]
好吧。
