### ISSUE TITLE
自制镜像如何保证兼容性？

### ISSUE THREAD

**Issue by YiuTerran** [ventoy/Ventoy#62]
hello，如果使用kickstart自定义centos安装镜像，生成的iso如何保证兼容性呢？

grub里面的menu默认按hd:label来搜索U盘，如果使用ventoy，这个label怎么对应上去呢。

**Comment by ventoy** [comment]
单独针对Centos来说的话，ventoy会在后台做处理，grub.cfg里面的 hd:label  实际上已经不生效了。 你写不写都行。

**Comment by YiuTerran** [comment]
也就是说我直接写cdrom也可以是吧？

**Comment by ventoy** [comment]
可以的

**Comment by YiuTerran** [comment]
测了一下，恐怕不行呢。

我用hd:label，感觉没法找到kickstart文件，卡在`starting dracut initqueue hook`这里了。

isolinux.cfg增加如下入口：

```
label linux
  menu label ^Auto Install CentOS 7
  menu default
  kernel vmlinuz
  append initrd=initrd.img inst.stage2=hd:LABEL=CENTOS7 inst.ks=hd:LABEL=CENTOS7:/kickstart/ks.cfg quiet
```

grub.cfg增加如下入口

```
menuentry 'Auto Install CentOS 7' --class fedora --class gnu-linux --class gnu --class os {
       linuxefi /images/pxeboot/vmlinuz inst.stage2=hd:LABEL=CENTOS7 inst.ks=hd:LABEL=CENTOS7:/kickstart/ks.cfg quiet
       initrdefi /images/pxeboot/initrd.img
}
```

生成镜像的代码：

```bash
cd /root/iso && mkisofs -v -cache-inodes -joliet-long -R -J -T -V CENTOS7 -o /root/centos7.iso -c isolinux/boot.cat -b isolinux/isolinux.bin -no-emul-boot -boot-load-size 4 -boot-info-table -eltorito-alt-boot -e images/efiboot.img -no-emul-boot .
isohybrid /root/centos7.iso
implantisomd5 /root/centos7.iso
```

我试着用dd写入u盘直接安装是没问题的，用ventoy的话bios/efi都不行，感觉是找不到卷标。

**Comment by ventoy** [comment]
你试试用    `inst.ks=hd:/dev/dm-0:/kickstart/ks.cfg`

**Comment by ventoy** [comment]
另外，Ventoy后续计划通过插件支持各种系统的自动安装功能。
比如，对于Centos, 就可以直接用原版ISO镜像，只需要在U盘里制定个ks.cfg就可以了，就不用重新制作了，而且还可以随意更换ks模板。

**Comment by YiuTerran** [comment]
> 你试试用 `inst.ks=hd:/dev/dm-0:/kickstart/ks.cfg`
> ventoy会在系统下把 iso文件映射到 /dev/dm-0

这种方案是可行的，感谢～
