### ISSUE TITLE
Unable to run updates to .iso images in ventoy ERROR : "not enough space"

### ISSUE THREAD

**Issue by warloxian** [ventoy/Ventoy#620]
Forgive me, I am a 54 year old NEWBIE!! I am coming along well with installng Kali, but I wanted other OS as well. I came across Ventoy. Love the concept and have just started using it.  Installed on an Apricorn 120gb ssd. Have Mint and Parrot .iso , I also installed BlackArch but it isn't showing up? Thats not my urgent issue though. 
Since I am new at all of this (although I am very computer literate, if you consider windows as literate?) anyway. lets spare the long dissertation here and get to the point. As I am new . When I started my Kali traiing the first thing I the frst thing that stood out was that it was important to update regularly to stay secure. So, when i installed the iso I started Mint first and went immidiatly to the update. Evereyting seemed to be going along just fine until I looked up and see "ERROR, not enough space to install updates. Now I have to small ISO images on this 120gb ssd . What am I doing wrong? If I cant add other apps to the OS images I have on Ventoy and can't update my operating systems what is the advantage. I have Googled, Duck duck go'd, etc...etc.. and the answe is evading meThe only thing even close that I found was to just install the latest version over the top of the old one, but thats a pain if I have to do it every few days and that still doesnt solve the issue if I want to install additional software to the system. PLEASE give me a hard time and give me shit because I cant find the answer all you want,  I can handle it, I am a big boy, plus you cant see me crying cause I have a piece of duct tape over my cam. But after you harass me I'd appreciate the answer. Like I said I am pretty literate and when my friends , family, tech support agents are the ones that usually call me when they can't figure out the answer. Plus you may harass me about my spelling and writing skills cause I suck at that and everyone gives me shit about that and watches me cry. THX for your help in advance

**Comment by ventoy** [comment]
The 1st way of understand:
```
1. You install Ventoy to a 120GB SSD and put a Mint.iso in it.
2. You boot into Ventoy and select Mint.iso to boot
3. After you boot into Mint, you start installation and install the Whole Mint system to another disk (e.g. another 256GB SSD)
4. After install, you reboot, and directly boot into the whole mint system in the (e.g. 256GB SSD)
5. You want to update something in the system and get the error 
```

The 2nd way of understand:
```
1. You install Ventoy to a 120GB SSD and put a Mint.iso in it.
2. You boot into Ventoy and select Mint.iso to boot
3. After you boot into Mint, you want to update something in the system and get the error 
```

Which one is right?

**Comment by warloxian** [comment]
2nd way. I installed Ventoy on 120ssd. I have 2 ISO images on it. I try to update those ISO images so I dont have security issues and it says I dont have room

**Comment by warloxian** [comment]
I actually installed 3 ISO images on it but one doesn't even how up when i boot the ssd. It is Backbox.iso

**Comment by ventoy** [comment]
In the 2nd way, you actually run the system in a LiveCD mode, not a normal mode.
In LiveCD mode, all the system(with all the runtime data) is in memory. and your change will lost after reboot.

LiveCD mode is normally used to experience a distro temporarily.
LiveCD mode is not for normal use.

So you need to install the system on a physical disk and reboot into the real system to do you update.

**Comment by warloxian** [comment]
Maybe I'm misunderstanding. But I have the complete .iso fill is of Parrot, Backbox and Mint. I'm not running in live mode. I have the 120gb ssd and I have those three complete operating systems on this disc. I want to install several Windows is and other tools as well. Or are the iso images all just automatically running as live? When I boot my kali system I use F12 and boot to the ssd. It comes up with a screen that has the three operating systems on it. I just click the one I want and it loads . Never gives me any other options?

**Comment by warloxian** [comment]
Also just more info. I am running Backbox tonight and it is updating just fine. No problems with out of space errors

**Comment by ventoy** [comment]
You have installed three OS in the same SSD with Ventoy or another SSD?

**Comment by warloxian** [comment]
I apologise. I was updating Backbox and it looked fine but I get same error![20201201_232748.jpg](https://user-images.githubusercontent.com/71565043/100836682-f21b1a80-342c-11eb-9825-65dca76d6848.jpg)

**Comment by ventoy** [comment]
Please run  `blkid` here.

**Comment by warloxian** [comment]
![20201202_140258.jpg](https://user-images.githubusercontent.com/71565043/100931014-2a5f3f00-34a7-11eb-833a-5b5ca83c8b26.jpg)

And this is the result. I did notice when I booted to parrot that it asked if I wanted live and had an entire menu
 I attempted to install on the 120gd ssd but I guess I need to learn partitioning better?

**Comment by ventoy** [comment]
You just put an ISO file in the SSD. You did't install the system into the SSD. These are two completely different concepts.
The disk(normally USB drive) that installed Ventoy is normally used to install a system (from an ISO file) to another physical disk.

**Comment by warloxian** [comment]
So I could use this USB to install Mint on my Hard drive of thsi laptop? If I chose to do that would I loose my kali dist thats on this machi?

**Comment by warloxian** [comment]
I am also curious if youve ever seen anyone try your program the way i did? Was I a firts or do all idiots like me do this?

**Comment by warloxian** [comment]
I apologise if I'm a pest. We're all busy in this crazy world. I am over my head with Kali linux. I am cloning my hard drive right now. Then I'll wipe this drive and install mint. Once I learn the basics I'll be fine. I'd like to just get your advise if I can use Ventoy to write mint onto my hard drive as my ony os? While I wait for an answer I'll re read the Ventoy instructions. I have apparently misunderstood how It works

**Comment by warloxian** [comment]
Ok you have me enough info and I read the install guide and I did it. In fact I just took an old chromebook 11 3180 and made Linux Mint the sole operating system on the devise and it looks and runs beautiful. Thanks for giving me just enough info to help me along but to make me work a little to get it to work. That's how this old man kearns best

**Comment by warloxian** [comment]
I am sorry I didn't close earlier. I wasn't sure of the process, but I was interpreting how Ventoy works incorrectly. It's perfect as usual. Thanks
