### ISSUE TITLE
Persistence Not working in Ventoy

### ISSUE THREAD

**Issue by on-error** [ventoy/Ventoy#624]
As soon as I boot my manjaro OS it boots up fine .. and I booted this with persistence from the Ventoy menu
But as soon as make any changes and restart the OS ... 
The changes don't get saved
I don't know why this issue is occurring.. 
Thanks in Advance

**Comment by ventoy** [comment]
When you boot manjaro, is there a menu for you to select boot with or boot without persisitence as follows?
[https://www.ventoy.net/static/img/persistence1.png](url)

**Comment by on-error** [comment]
Yes , there is a menu option to select boot with persistence exactly like the image you shared. And I boot up with that option but changes I make don't reflect
 when I restart

**Comment by ventoy** [comment]
Persistence is not supported for all the distros.
Only the distros in the list are supported now.
https://www.ventoy.net/en/plugin_persistence.html

Currently, manjaro is not supported yet.

**Comment by on-error** [comment]
THANKS !  for sharing this information . will it support in future and like when we can expect to see manjaro to supports persistence ?

**Comment by ventoy** [comment]
As I known, manjaro ISO doen't support persistence.
I suggest you use vhd/vdi for manjaro https://www.ventoy.net/en/plugin_vtoyboot.html
It's a real manjaro enviroment like installed in a physical disk.
