### ISSUE TITLE
The latest version of Tails (tails-amd64-4.13) does not work

### ISSUE THREAD

**Issue by shpaginkirill** [ventoy/Ventoy#625]
When you start Tails at the time of loading, a message appears:
```
BusyBox v1.30.1 (Debian 1:1.30.1-4) built-in shell (ash)
Enter 'help' for a list of built-in commands.

(initramfs) cannot find a medium containing a live file system
```

**Comment by ventoy** [comment]
Please run 2 cmds in the initramfs shell:
```
blkid
cat /ventoy/log
```

**Comment by shpaginkirill** [comment]
https://telegra.ph/result-12-02

**Comment by ventoy** [comment]
I can't reproduce the problem.
I test it and it works fine in my laptop (both Legacy BIOS and UEFI mode).
```
tails-4.13-amd64.iso
md5sum: 1121970d5891d89b4a1b05bccc3ac9d4
```

**Comment by shpaginkirill** [comment]
devil... I downloaded not an "iso" image, but an "img". I did not pay attention to the file extension. Thank you so much for your time and for testing it personally!!!

I have 2 questions: 
1) Linux Slax does not run on UEFI (it is listed in the Tested ISO table and I checked it). Please tell me, is it possible for Slax to run in UEFI mode in the future with an update of Ventoy? Or is the problem with Slax itself and nothing depends on you here?
2) Is it possible in the future to start the system not from an ISO file, as is done now, but from a folder where the ISO is unpacked? For example, the Slax saves all the changes in a separate file, and the ISO, as we know, is write protected. 

Thank you again!!!

**Comment by ventoy** [comment]
1. When I note `This iso only support Legacy BIOS`  it means that it's the ISO file itself that doesn't support UEFI mode. 
    It's not Ventoy's limitation, it's the ISO file's problem.
2. Folder is not bootable, so it's impossible to boot from a folder. If you want to save data after boot a ISO, I think you need something called persistence. You can refer to : https://www.ventoy.net/en/plugin_persistence.html

**Comment by shpaginkirill** [comment]
Slax itself (unpacked on a flash drive) works in uefi, but I wanted his job at Ventoy.
You said that " it means that it's the ISO file itself that doesn't support UEFI mode."
Based on this, we can assume that by changing some file and then remaking the ISO, I can get a working Slax. But I don't know what I have to change...

**Comment by ventoy** [comment]
Many distro's ISO file(e.g. Ubuntu/CentOS) support both legacy BIOS mode ans UEFI mode.
But slax's ISO file can only boot in Legacy BIOS mode, so the developer need to add some option to make it support UEFI mode when generating ISO file.

If you test with a VirtualMachine(e.g. Vmare/Virtualbox), in UEFI mode and directly boot the ISO file (don't extract it, just directly use the ISO file) you will find that it will not  boot.

**Comment by narinaresh** [comment]
i wanna use tails os in USB stick . to do this i wanna download the .ISO
