### ISSUE TITLE
在固态硬盘（nvme协议）上，无法安装系统

### ISSUE THREAD

**Issue by Sherry520** [ventoy/Ventoy#627]
提示EFI的文件引导找不到，在普通机械硬盘试了试，是可以正常使用的
![image](https://user-images.githubusercontent.com/22561797/100979793-3c141580-357f-11eb-9def-0fa489d8451d.png)

**Comment by ventoy** [comment]
是说把Ventoy安装到机械硬盘上，然后安装这个Windows的ISO就没问题。
把Ventoy安装到NVMe的盘上，然后安装这个Windows的ISO就有这个问题。
这个意思吗？

有没有试过其他的ISO文件对比过，看只有这一个ISO有问题，还是所有都有问题？
可以试试 Windows 10/Ubuntu 之类的对比下。

**Comment by Sherry520** [comment]
不是，Ventoy安装到了U盘(闪迪USB3.0)，然后用U盘装系统。在nvme硬盘上，安装就出了这个问题。换了另一个电脑，它只有机械硬盘，安装就没有问题。系统都是win10 1909 X64

**Comment by Sherry520** [comment]
另外我想知道 krd.iso 在哪里打开 grub shell 来输入set check_signatures=no

**Comment by ventoy** [comment]
这个图应该还没有开始安装。理论上你插的是NVMe盘还是普通盘都没关系，至少这个地方不应该出错。
你的NVMe盘里面之前装过系统吗？ 会不会里面数据对启动有影响，可以的话先把NVMe盘格式化情况，再试试。

**Comment by ventoy** [comment]
在 Ventoy界面选择了 krd.iso 回车之后，会显示出krd的启动菜单，一般首先是让你选择语言。就在这个位置，按 e 进入 grub shell 输入。
只对UEFI模式需要。

**Comment by Sherry520** [comment]
nvme盘里有系统，我就是试试看新U盘怎么样。那就等我有装系统的需求时再看看

**Comment by Sherry520** [comment]
好的，谢谢
