### ISSUE TITLE
TrueNAS-12.0-RELEASE.iso can't install

### ISSUE THREAD

**Issue by Silejonu** [ventoy/Ventoy#628]
TrueNAS-12.0-RELEASE.iso boots fine initially, but when selecting the default installation, it hangs at detecting peripherals. The iso boots and installs fine on the same machine when burned with dd.
Tested in UEFI only.

**Comment by ventoy** [comment]
It will be supported in the next release.

**Comment by ventoy** [comment]
Please try with 1.0.30

**Comment by Silejonu** [comment]
> Please try with 1.0.30

I tried and it worked fine. I could finish the installation without any trouble.

However, in the meantime, another release hit: TrueNAS-12.0-U1.iso
I tested it, and it worked fine the first time. But every other time I tried to get to the install menu, it failed (I could only get it to boot, just like with TrueNAS-12.0-RELEASE.iso). I tried memdisk and it didn't work either.

Attached are the pictures of the output I get.
![IMG_20201215_213437](https://user-images.githubusercontent.com/48565914/102273696-09750000-3f23-11eb-8f03-7255a77ddb21.jpg)
![IMG_20201215_214036](https://user-images.githubusercontent.com/48565914/102274104-9fa92600-3f23-11eb-830f-6e9a961d6549.jpg)
![IMG_20201215_214838](https://user-images.githubusercontent.com/48565914/102274359-0c242500-3f24-11eb-8625-ee82513b011c.jpg)
![IMG_20201215_213410](https://user-images.githubusercontent.com/48565914/102273138-25c46d00-3f22-11eb-9486-781273e8248e.jpg)

**Comment by ventoy** [comment]
When you boot into ventoy's menu, press `c` to enter  grub shell and run this command:
```
blocklist  $vtoy_iso_part/TrueNAS-12.0-U1.iso
```
(This command may run a long time)

**Comment by Silejonu** [comment]
I ran the command you asked, and here is the output I received:
![IMG_20201216_112903](https://user-images.githubusercontent.com/48565914/102340641-12071e00-3f97-11eb-9e31-dbf5f795c204.jpg)

I copied a new iso with a new name, and tried to boot it. I got the same results as last time.

**Comment by ventoy** [comment]
`blocklist` cmd prints the file fragments in the physical disk.
The result means the ISO file you copied to the USB drive has 4997 fragments, it's very rare.
Normally the file in the disk only occupy one or some fragments.
Is your USB stick nearly full? What filesystem do you use? exfat or ntfs?

run `blocklist` cmd to check the new ISO file to see whether it also has so many fragments.

Finally if possiable, reformat your USB stick and recopy the file and test.

PS:
Ventoy doesn't need the file to be contigous and has no limitation on the fragments number of the file in disk,
but from the log it seems that we run into a limitation by the TrueNas kernel.

**Comment by Silejonu** [comment]
I have more than 90 GB free, and it's an exFAT partition.
For good measure, I re-downloaded the ISO and checked its checksum.
I put the iso in 3 files on my flash drive under different names and ran `blocklist` against each of them. I got 4997, 6508 and 4322.

I remade my key from scratch, with the same settings (GPT, exFAT partition, Secure Boot support, and a custom ventoy.json), and it seems to be working fine now, even after I put back everything else (more than 154 GB of ISOs and programs).
It's weird that it's the only ISO I noticed an issue with, but as long as it's resolved, it's good in my book. =)

**Comment by crazy-logic** [comment]
I had a similar if not the same problem - reformatted, reinstalled the 1.0.31 version and then copied the ISO over once again and this time it works :)

**Comment by jedie** [comment]
TrueNAS-12.0-U1.iso doesn't work:

![signal-2021-01-04-130227](https://user-images.githubusercontent.com/71315/103533574-a0cbd400-4e8d-11eb-86c0-a0636cda66d6.jpeg)

**Comment by ventoy** [comment]
@jedie 
Please do these test above in the thread and give me the result.

**Comment by ShalokShalom** [comment]
This seems to be a trouble-maker. 

I tested a good dozen of Linux distros and some Windows respins, but this is the first who wont work:

![DSC_0013](https://user-images.githubusercontent.com/6344099/156632934-04b29c76-a091-4ca0-83f5-8a2772a8e754.JPG)

![DSC_0014](https://user-images.githubusercontent.com/6344099/156633747-b0f5e4e8-d4b4-494e-9673-ff3525e61cbb.JPG)


I am using a 32 GB stick, who is half full, FAT32.

**Comment by steve6375** [comment]
Select iso and press m
Does the checksum hash match the expected value?

**Comment by ShalokShalom** [comment]
Nice feature, could be shown more popular. 

And yes, its the correct checksum.

It works on the same device with Etcher.

**Comment by steve6375** [comment]
UEFI64 and MBR boot under VBox 5 using Ventoy 1.0.57 and 1.0.70 seems OK
e.g.
![image](https://user-images.githubusercontent.com/1469350/156743124-ebc1fc1c-e5f1-419e-834c-f72612912486.png)
So maybe hardware issue with your PC?

**Comment by steve6375** [comment]
P.S. I used an NTFS partition 1 (not default exFAT)

**Comment by steve6375** [comment]
Same for U8 ISO - works OK too in VBox 5. Legacy.
![image](https://user-images.githubusercontent.com/1469350/156756643-c629a9b4-cf42-410c-9e5d-1165ecd38402.png)

**Comment by ShalokShalom** [comment]
Well, Etcher works with this USB stick on this hardware, and also Ventoy works with other distros on this stick.

**Comment by steve6375** [comment]
Works for me on Lenovo IdeaPad 300 too (USB 3 port - USB 3 Sandisk Extreme 128GB flash drive)
If your sha256 is same as mine above (using Ventoy - m) then file must be OK.
Maybe you can try on a different system?
Maybe you can give more details - e.g. Legacy or UEFI booting, on what PC, what is your flash drive, USB 3 port or USB 2 port, if using usb 3 flash drive and usb 3 port then try connecting with a USB 2 cable.

**Comment by ShalokShalom** [comment]
Yes, its that sha number. Its UEFI booting, USB 2 Rainbow Intenso 32 GB. I already installed it with Etcher, but can try some combinations afterwards. I will try it on another hardware later. Thanks

**Comment by oscar13sd** [comment]
TrueNAS-12.0-U8.1.iso didn't work for me using ventoy-1.0.76-windows.

I ran the blocklist command and got entry number: 1
I confirmed the sha256 using the ventoy UI
I reformatted my USB and tried the settings used by Silejonu (minus his custom json)
I ended up using Rufus and creating a bootable USB to install Truenas successfully

**Comment by ventoy** [comment]
@oscar13sd 
I can't reproduce the issue on my laptop (Thinpad T420).
`TrueNAS-12.0-U8.1.iso` boot fine in my laptop both Legacy BIOS mode and UEFI mode.

**Comment by oscar13sd** [comment]
> @oscar13sd I can't reproduce the issue on my laptop (Thinpad T420). `TrueNAS-12.0-U8.1.iso` boot fine in my laptop both Legacy BIOS mode and UEFI mode.

Maybe it is just my USB drive (PNY 32 GB USB 2.0)?  I still love your software, just wanted to provide another data point.
