### ISSUE TITLE
updating ventoy from 1st partition

### ISSUE THREAD

**Issue by candrapersada** [ventoy/Ventoy#629]
> Update will only update the data in the MBR/1MB GAP/2nd partition.

can or not, use ventoy-livecd.iso from the first partition only to update the version?

**Comment by ventoy** [comment]
Yes.
https://www.ventoy.net/en/doc_livecd.html

LiveCD Composition
Ventoy LiveCD is TinyCore Linux + Ventoy Linux install package.
```
If you already have an USB drive with Ventoy in it and you just want to update it or you want to install Ventoy to another USB drive, you just need to put the LiveCD iso to the Ventoy USB drive and boot it as a normal ISO image by Ventoy.
```
......
