### ISSUE TITLE
Remember secure boot setting when updating

### ISSUE THREAD

**Issue by jwillikers** [ventoy/Ventoy#630]
*Ventoy Version*: 1.0.29
*OS*: Ubuntu 20.10

When updating a Ventoy disk created with Secure Boot enabled, the Secure Boot option appears to be forgotten unless explicitly enabled when updating with the `-s` flag.

Steps to reproduce:

1. Install Ventoy to a flash drive with Secure Boot and GPT enabled.

```sh
$ sudo ventoy-1.0.29/Ventoy2Disk.sh -i -s -g /dev/sdb
```

2. Update the Ventoy flash drive.

```sh
$ sudo ventoy-1.0.29/Ventoy2Disk.sh -u /dev/sdb
```

It appears that the previous setting for secure boot is forgotten. Is this the intended behavior? I assumed it would *remember* the secure boot setting when updating.

**Comment by ventoy** [comment]
I will fix it in the next release.

**Comment by jwillikers** [comment]
@ventoy  I just confirmed this is fixed in the latest release, thank you!

**Comment by ltGuillaume** [comment]
Thanks for fixing this! (see #299)
