### ISSUE TITLE
arm环境下编译源码

### ISSUE THREAD

**Issue by Rayuu** [ventoy/Ventoy#631]
您好，我想在aarch64环境下编译源码，目前我安装了centos7.9 arm版。按照编译说明https://github.com/ventoy/Ventoy/blob/master/DOC/BuildVentoyFromSource.txt
我发现在第五步“5. Binaries”中的一些二进制文件没有arm版的，请问这个影响编译吗？
目前我们经常安装的系统有"yinhe kylin"和Ubuntu。

**Comment by ventoy** [comment]
下一个版本会支持 ARM64 UEFI 平台。

**Comment by ventoy** [comment]
1.0.30版本已支持ARM64平台

**Comment by Rayuu** [comment]
收到谢谢，目前正在在机器上测试kylin server V10安装测试。
![image](https://user-images.githubusercontent.com/11494597/102434309-7a193b00-404f-11eb-8dd7-69b861e9dc24.png)

![image](https://user-images.githubusercontent.com/11494597/102434321-7f768580-404f-11eb-99d8-0d9b036e89b3.png)
![image](https://user-images.githubusercontent.com/11494597/102434347-8a311a80-404f-11eb-824d-282446071381.png)
