### ISSUE TITLE
不支持含中文文件名的ISO

### ISSUE THREAD

**Issue by sonichy** [ventoy/Ventoy#632]
含中文文件名的ISO不在列表中。

**Comment by ventoy** [comment]
从 1.0.29 版本开始支持中文文件名。你用的是哪个版本？

**Comment by sonichy** [comment]
怎么查看版本？

**Comment by ventoy** [comment]
启动界面左下角会显示

**Comment by ventoy** [comment]
制作软件 Ventoy2Disk.exe 打开之后也会显示 U盘内安装的Ventoy版本号。
Ventoy2Disk.exe 这个程序本身的版本号没有意义， 已经很长时间没改过了。

你下载的安装包名字里就带着版本号，比如  Ventoy-1.0.29-Windows.zip  版本号就是1.0.29

**Comment by sonichy** [comment]
sh Ventoy2Disk.sh 有版本和说明。
