### ISSUE TITLE
Windows 10 iso not booting in legacy boot

### ISSUE THREAD

**Issue by alk-alyss** [ventoy/Ventoy#633]
when I try to boot windows 10 20h2 in legacy boot it quickly flashes the windows logo and then shows a blinking underscore

ventoy version: 1.0.29
iso filename: Win10_20H2_v2_English_x64.iso

**Comment by Alitai12** [comment]
Same Problem here with 1.0.30.

**Comment by namePlayer** [comment]
Is it hte exact same error, I described in #636?

**Comment by alk-alyss** [comment]
> Is it hte exact same error, I described in #636?

Yes we are having the same issue although my pc only supports legacy and not uefi (if it even makes any difference)

**Comment by namePlayer** [comment]
> Yes we are having the same issue although my pc only supports legacy and not uefi (if it even makes any difference)

**Comment by namePlayer** [comment]
Okay, good to know that someone else experiences the same problem.

**Comment by ventoy** [comment]
@alk-alyss 
Please do a test:
When you boot into Ventoy's menu, press ctrl+i firstly and then select the ISO and boot.

**Comment by alk-alyss** [comment]
I already use ventoy.json to enforce cli display mode, so it's still the same

**Comment by alk-alyss** [comment]
Update: it turns out that the iso does boot eventually, it just gets "stuck" at the flashing underscore before it continues booting

**Comment by sxd1140** [comment]
> @alk-alyss
> Please do a test:
> When you boot into Ventoy's menu, press `ctrl+i` firstly and then select the ISO and boot.

选win10 黑屏左上角跳光标

按了`ctrl+I`进入`Compatible Mode`后再选win10 会先出现一下windows logo 然后再黑屏左上角跳光标

电脑 legacy  
ventoy mbr
