### ISSUE TITLE
Lenovo ThinkPad X250

### ISSUE THREAD

**Issue by fleamour** [ventoy/Ventoy#635]
Boots to menu which is better than Mint's right click > burn to USB which are not even seen. But will not load any images in MBR or GPT from RAM or no. Other methods fail, only way I find is Mkusb self extracting Windows installer but this is a huge time sink & only boots one image.

**Comment by Sokoloft** [comment]
Hello,

I have this issue with my X250 as well.
I'm on the very latest version. 1.0.73. 

I can get to the ventoy boot screen. Whenever I select an ISO, the activity LED on the USB flashes for a moment. Then its just a black screen. No flashing from the LED.
