### ISSUE TITLE
NOT working with Austrumi

### ISSUE THREAD

**Issue by pigeonskiller** [ventoy/Ventoy#637]
Thanks for your great application.

Working very good in general but found a bug with Austrumi distros here ftp://austrumi.ru.lv/

After initial sequence enumerating till number 5 (!) can't find starting CD.

Hope you solve soon.

In the meanwhile thanks again and have a nice day.

**Comment by ventoy** [comment]
I have supported it and will be avaliable in the next release.

**Comment by ventoy** [comment]
Please test with latest release.

**Comment by ventoy** [comment]
Should be supported in latest release . I will close this issue.

**Comment by pigeonskiller** [comment]
Hi longpanda,

thanks for support.

Sorry to inform you that new ventoy-1.0.32 still doesn't work with new Austrumi 4.3.5

**Comment by ventoy** [comment]
I just test in VM before, indeed have some problem when tested in my laptop.
I will fixed it in the next release.

**Comment by pigeonskiller** [comment]
Solved as in post #1121 using grub 2 mode: pressing ctrl+r, after Ventoy shows menu, let me boot the iso.
