### ISSUE TITLE
Virus warning on latest Ventoy Build

### ISSUE THREAD

**Issue by Scoty43** [ventoy/Ventoy#638]
I am on latest Windows 10 and i use the Defender. I can not download the latest Ventoy. I get a Virus warning.

![Screenshot 2020-12-13 062616](https://user-images.githubusercontent.com/25227541/102003939-2388c580-3d0c-11eb-9c46-1de490500da5.png)

**Comment by ventoy** [comment]
I have noted it here https://github.com/ventoy/Ventoy/releases/tag/v1.0.30

```
https://github.com/ventoy/Ventoy/releases/tag/v1.0.30
```

**Comment by robotshateme** [comment]
Same but installed via Chocolatey. Will whiteist.

**Comment by Karl-WE** [comment]
Hi there 
ventoy-1.0.36-windows.zip is also flagged by Defender, this time with a different name.

![image](https://user-images.githubusercontent.com/45657752/109390220-9586a900-7910-11eb-885b-85e877f75479.png)
