### ISSUE TITLE
BunsenLabs Lithium / Debian 10 on Raw Image can't boot

### ISSUE THREAD

**Issue by hysrx** [ventoy/Ventoy#639]
## Issue

When trying to boot a BunsenLabs Lithium / Debian 10 from a raw image file, I get

```
No bootfile found for UEFI!
Maybe the image does not support X64 UEFI!
```

## Recreation

File Structure
```
qemu/
ovmf/
lithium-1-amd64.hybrid.iso
```

- qemu folder contains qemu,

- ovmf folder contains decompressed ovmf edk2 from https://www.kraxel.org/repos/jenkins/edk2/, containing efi bios for qemu

- lithium-1-amd64.hybrid.iso is from bunsenlabs.org website

### Create Raw Image
`qemu\qemu-img.exe create -f raw ..\lithium-vdisk.img 24G`

### Install Operating System
Linux
```
qemu\qemu-system-x86_64 -bios "ovmf\usr\share\edk2.git\ovmf-x64\OVMF-pure-efi.fd" \
                        -drive file=lithium-vdisk.img,format=raw,if=virtio \
                        -cdrom ..\lithium-1-amd64.hybrid.iso \
                        -boot d \
                        -smp 2 \
                        -m 2G
```

Windows
```
qemu\qemu-system-x86_64 ^
-bios "ovmf\usr\share\edk2.git\ovmf-x64\OVMF-pure-efi.fd" ^
-drive file=lithium-vdisk.img,format=raw,if=virtio ^
-cdrom lithium-1-amd64.hybrid.iso ^
-boot d ^
-smp 2 ^
-m 2G
-display sdl
```

### Get vtoyboot
```
wget -c https://github.com/ventoy/vtoyboot/releases/download/v1.0.5/vtoyboot-1.0.5.tar.gz
tar -xvf vtoyboot-1.0.5.tar.gz
cd vtoyboot-1.0.5
sudo sh vtoyboot.sh
```

### Shutdown
`shutdown now`

### Add `.vtoy` to raw image file

Current File Structure
```
qemu/
ovmf/
lithium-1-amd64.hybrid.iso
lithium-vdisk.img.vtoy
```

### Boot via Ventoy
Recieve error
```
No bootfile found for UEFI!
Maybe the image does not support X64 UEFI!
```

**Comment by ventoy** [comment]
Start qemu and boot into the system again, and run some cmds:
```
blkid
parted /dev/sda p
ls -l /boot
```

**Comment by hysrx** [comment]
> 
> 
> Start qemu and boot into the system again, and run some cmds:
> 
> ```
> blkid
> parted /dev/sda p
> ls -l /boot
> ls -l /boot/efi
> ls -l /boot/efi/boot
> ```

![commands](https://user-images.githubusercontent.com/59181111/102018208-ba34a100-3d63-11eb-82bf-16020ccb9d86.jpg)

**Comment by hysrx** [comment]
Even after changing vda to sda by using a different controller, I don't see any notable changes to any of the results from the commands you gave me

![sda_commands](https://user-images.githubusercontent.com/59181111/102020123-03d6b900-3d6f-11eb-9dc3-827fb6ba12ad.jpg)

**Comment by ventoy** [comment]
Sorry, some more cmds please:
```
ls -l /boot/efi/EFI
ls -l /boot/efi/EFI/BOOT         <------ or /boot/efi/EFI/boot 
mount
```

**Comment by hysrx** [comment]
> 
> 
> Some more cmds please:
> 
> ```
> ls -l /boot/efi/EFI
> ls -l /boot/efi/EFI/BOOT         <------ or /boot/efi/EFI/boot 
> mount
> ```

![cont_commands](https://user-images.githubusercontent.com/59181111/102039640-62795280-3dc2-11eb-83b7-e3003823adc6.jpg)

**Comment by ventoy** [comment]
What about the 1st and 3rd cmd?
```
ls -l /boot/efi/EFI
mount
```

**Comment by hysrx** [comment]
> 
> 
> What about the 1st and 3rd cmd?
> 
> ```
> ls -l /boot/efi/EFI
> mount
> efibootmgr
> ```

![cont2_commands](https://user-images.githubusercontent.com/59181111/102088742-3afea600-3e13-11eb-9bf0-12f9706746e3.jpg)

**Comment by ventoy** [comment]
I have update vtoyboot-1.0.6 https://github.com/ventoy/vtoyboot/releases/tag/v1.0.6
1. start qemu and boot into the system
2. download vtoyboot-1.0.6.tar.gz. decompress it and run vtoybooy.sh again
3. powoff the system
4. copy the new image to Ventoy disk and boot it

**Comment by hysrx** [comment]
> 
> 
> I have update vtoyboot-1.0.6 https://github.com/ventoy/vtoyboot/releases/tag/v1.0.6 you can make a try.
> 
>     1. start qemu and boot into the system
> 
>     2. download vtoyboot-1.0.6.tar.gz. decompress it and run vtoybooy.sh again
> 
>     3. powoff the system
> 
>     4. copy the new image to Ventoy disk and boot it

Thank you! It works perfectly!
