### ISSUE TITLE
1.0.09 Beta1 Not booting with secure boot on

### ISSUE THREAD

**Issue by IvanAclu** [ventoy/Ventoy#64]
Motherboard Asus Prime Z270-A.
I was able to successfully boot with UEFI secure boot enabled using Ventoy 1.0.07 and 1.0.08.
When I try with Ventoy 1.0.09 Beta1 the following error appears.

![UEFI Boot Error 800](https://user-images.githubusercontent.com/64646805/81146088-82fd4680-8f6f-11ea-9475-a07c0daa00a8.jpg)

**Comment by ventoy** [comment]
Hi, the secure boot solution in Ventoy is not perfect enough.  I have received many reports about this.  If ventoy 1.0.07/1.0.08 worked well with secure boot in you machine, that's a good news for you.
So from 1.0.09 beta1 i add an option for secure boot in Ventoy2Disk.exe and default is not enabled.
So if the secure boot solution works well in your machine, you can turn on the option when updateing Ventoy.

In the menu:  `Option---->Secure Boot`   check it and click Update button. (You can just update from 1.0.09b1 to 1.0.09b1 again)

**Comment by IvanAclu** [comment]
That works thank you.
