### ISSUE TITLE
macOS Catalina and Ubuntu 20.04 LTS not working

### ISSUE THREAD

**Issue by ibrahemesam** [ventoy/Ventoy#640]
macOS Catalina 10.15.5 (19F101).iso : Error: iso is not bootable
ubuntu-20.04.1-desktop-amd64.iso : ubuntu logo appear but some error happen and no boot

**Comment by ventoy** [comment]
Please give some photo or video.

**Comment by ibrahemesam** [comment]
sorry, I forgot about this issue.
now they work after updating Ventoy
