### ISSUE TITLE
macos etcher 烧写，开机选中liveos之后花屏卡死

### ISSUE THREAD

**Issue by jcleng** [ventoy/Ventoy#641]
是macos下etcher烧录的，不知道如何排查问题和提供日志

**Comment by ventoy** [comment]
你是用etcher 把VentoyLiveCD.iso 烧录到U盘然后把U盘插到机器上启动时花屏吗？
启动的机器也是这个MACOS的机器吗？

**Comment by jcleng** [comment]
> 你是用etcher 把VentoyLiveCD.iso 烧录到U盘然后把U盘插到机器上启动时花屏吗？
> 启动的机器也是这个MACOS的机器吗？

是这样的, 用etcher 把VentoyLiveCD.iso 烧录到U盘,然后把U盘插到thinkpad启动,显示了grub2,然后有两个选项,进入Liveos和Liveos(debug),回车之后就花屏卡住了.

**Comment by ventoy** [comment]
看看thinkpad当前是什么BIOS模式，如果是Legacy  模式的话，切换成UEFI模式试试。

**Comment by jcleng** [comment]
> 看看thinkpad当前是什么BIOS模式，如果是Legacy 模式的话，切换成UEFI模式试试。

是UEFI，错误日志或者代码有需要吗，没看到日志

**Comment by ventoy** [comment]
暂时不知道什么问题了。可能是LiveCD里面这个小系统和机器有兼容性问题。
LiveCD其实就是打包了一个 TinyLinux 同时加上Linux版本的Ventoy安装包。
可能这个TinyLinux小系统和机器有兼容性问题吧。

LiveCD只是用来安装Ventoy的，你也可以找个真正的Linux系统或者是找个别的Windows系统来安装Ventoy

**Comment by ventoy** [comment]
This is an old issue. I will close it now.
If you still have problem with latest Ventoy release, you can reopen the issue.
