### ISSUE TITLE
Anarchy Linux 1.3.1 doesn't boot

### ISSUE THREAD

**Issue by arthurflor23** [ventoy/Ventoy#642]
Hi,

I used Anarchy Linux 1.2.1 and it worked fine. However, in the latest version (1.3.1), this issue is shown after 30 seconds of waiting:
```
ERROR: '/dev/disk/by-label/ANARCHY131' device did not show up after 30 seconds...
  Falling back to interactive prompt
  You can try to fix the problem manually, log out when you are finished
sh: can't access tty: job control turned off
```

Thanks!

**Comment by ventoy** [comment]
I have fixed it.
If you want you can test it manually.
1. Update to latest release 1.0.30
2. Replace the file   `/grub/grub.cfg` in the 2nd partition (VTOYEFI partition)  with https://github.com/ventoy/Ventoy/blob/master/INSTALL/grub/grub.cfg

**Comment by arthurflor23** [comment]
It worked!

Thanks for the quick fix.

**Comment by laichiaheng** [comment]
Do I still need to manually do it? It still doesn't boot.
