### ISSUE TITLE
[Feature Request] Btrfs support

### ISSUE THREAD

**Issue by damian101** [ventoy/Ventoy#645]
Btrfs support would be nice, with support for all three compression algorithms, `zlib`, `lzo` and `zstd`.
I'm mostly interested in it because of the file system compression, so I can fit more ISO's on my Ventoy drives. NTFS also supports file system compression, but it's nowhere near as good.

**Comment by ventoy** [comment]
Ventoy depends on the file's location on the disk and map these blocks to a virtualdevice.
So the file in the filesystem can NOT be compressed.
So brtfs and other filesystems with compression enabled can NOT be supported.

**Comment by damian101** [comment]
Yes, just noticed that NTFS compressed ISOs don't load...
Makes sense though.

**Comment by HaleTom** [comment]
What about NTFS and btrfs with compression disabled?

Or is the real blocker to btrfs its extent-based mapping?

**Comment by ventoy** [comment]
Normal NTFS without compression is supported.
But btrfs is not supported now (even without compression).
