### ISSUE TITLE
Windows SetupComplete

### ISSUE THREAD

**Issue by sraedler** [ventoy/Ventoy#647]
Is it possible to use the Windows SetupComplete.bat functionality without recreating the ISO?

Thanks!

**Comment by ventoy** [comment]
Ventoy supports unattend.xml for Windows ISO. You don't need to recreate the ISO file, just create an unattended.xml file and tell Ventoy to use it with an Windows ISO file when boot.
https://www.ventoy.net/en/plugin_autoinstall.html

Can SetupComplete.bat implemented by Unattended.xml?

**Comment by sraedler** [comment]
I don't think that you can implement it using the unattended.xml. 
There is rather a copying of files in a specific windows direction after the installation.

Check here: https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/add-a-custom-script-to-windows-setup

**Comment by ventoy** [comment]
I'm not familiar with SetupComplete.bat.
Maybe you can put all the needed files and script in the USB drive (under some directory) and make a call to this script after installation.
All the copying or other thing can be done in the script.

**Comment by sraedler** [comment]
Ok, so could you than please extend the functionality of the Injection Plugin so to specify the destination path?

I need to copy a folder calls "scripts" including the SetupComplete.bat and a "files" folder containing the software to %WINDIR%\Setup. 

That is basically everything.

Advances plus would be if I could select whether I want to copy a folder or not same like in the prompt before boot option of the auto install plugin

I think this could also be additional benefit for other OS as well.

**Comment by sraedler** [comment]
Ok, so I probably can life with the Injection Plugin.

Could you just tell me, how can I specify that I want to put two folder with files in the following folder: %WINDIR%\Setup\

thanks!

**Comment by ventoy** [comment]
Injection Plugin Only inject files to the Window PE envrioment(e.g.  X:\Windows\) not the finaly system (C:\Windows)
Is it ok?

**Comment by sraedler** [comment]
I will try it and inform you as soon as I'm finished with this test.

If I need help for the path, I will inform you, thanks!

**Comment by DX37** [comment]
@sraedler Maybe you can add commands to unattended steps, like I do?
```

    <settings pass="specialize">
        <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <TimeZone>North Asia Standard Time</TimeZone>
        </component>
        <component name="Microsoft-Windows-Deployment" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <RunSynchronous>
                <RunSynchronousCommand wcm:action="add">
                    <Order>1</Order>
                    <Path>net accounts /maxpwage:unlimited</Path>
                </RunSynchronousCommand>
            </RunSynchronous>
        </component>
    </settings>
```
This code runs `net accounts /maxpwage:unlimited`, because after skipping OOBE, password of created user expires in month or so. This command sets password age to be unlimited.

**Comment by sraedler** [comment]
Unfortunately, this is not working for me.
I want to automatically install some applications like office.

anyways thanks!

**Comment by steve6375** [comment]
Easy2Boot uses an XML to kick off a build, complete with online or offline application installs, automatic h/w driver installation, etc. 
ISO+XML. Other files are on the USB drive and are copied across to C: drive during setup phase.
You could use the same method with Ventoy.

**Comment by sraedler** [comment]
@steve6375 thanks for your suggestion. I would really like to solve the issue with ventoy.

After hours of testing I found following behaviour.

1) It is not possible to use the injection plugin to inject multiple files 
`
"injection": [
        {
            "image": "/ISO/Windows.iso",
            "archive": [
                "/zips/script.zip",
                "/zips/files.zip"
             ]
        }
    ]
`

2) It is not possible to extract a folder calls scripts to the OEM folder.
My zip structure: $OEM$ -> $$ -> Setup -> Scripts and Files Folder with both .bat and exe files

On execution, the Files folder is available at the correct location and the scripts folder is missing. If I create a zip with only the scripts folder, no output can be seen. Additionally, the bat files does not seem to be the problem. I think the problem comes with the scripts folder.


@ventoy could you please check whether the copy of scripts folder is really not possible?

**Comment by sraedler** [comment]
Has someone an idea?

**Comment by steve6375** [comment]
Use one zip file.

**Comment by sraedler** [comment]
Even with one zip file, it does not work. The scripts folder cannot be copied.

**Comment by steve6375** [comment]
Is it because of the $ symbols in the path? Did you try changing the path to OEM\s\Setup\Scripts for instance?

**Comment by steve6375** [comment]
Can you upload a small .zip file here for testing that shows the issue?

**Comment by sraedler** [comment]
You can check this out: https://dellwindowsreinstallationguide.com/the-oem-folder/
It is what I want to do.

I attached an example zip. However, I cannot make it work.
[sources.zip](https://github.com/ventoy/Ventoy/files/5835484/sources.zip)

**Comment by steve6375** [comment]
zip file has a /sources folder

So wont the files be in X:\Sources ?

**Comment by sraedler** [comment]
Yes, I would expect the folder structure in X. So X:\Sources\$OEM$\$$\...

The reason is that in a single iso file, I need to add the $OEM$ folder to the Sources folder.

**Comment by steve6375** [comment]
So when you boot to Windows Setup - are the files in X:\Sources folder ?  Yes or No?

X: is the WinPE RAM drive (i.e. boot.wim). It is not the source media (not a DVD). The instructions are for a DVD, I dont think it can be expected to work if you inject the $OEM$ files into the X: drive.

**Comment by sraedler** [comment]
>So when you boot to Windows Setup - are the files in X:\Sources folder ? Yes or No?

No, this was a try to make it work. Even the working version is not copied there.

>X: is the WinPE RAM drive (i.e. boot.wim). It is not the source media (not a DVD). The instructions are for a DVD, I dont think it can be expected to work if you inject the $OEM$ files into the X: drive.

So you guess that there is no way to inject it using the injection tool? 
If so, do you think it might be possible with the unattended.xml of the auto setup? I mean that I automatically copy the files after installation on the Win drive?

**Comment by steve6375** [comment]
This process does not add a \sources folder into the **ISO** file.
What the ZIP file should do is unpack the contents of the zip file to X:\ (the WinPE RAM drive).
i.e.
Run Ventoy, select /ISO/Windows.iso - boot to Windows Setup - press SHIFT+F10 - do 'dir X:\Sources' command - files should be there...

**Comment by sraedler** [comment]
yeah, the files are there except the scripts folder.
No matter what folder structure I use. If any contains a folder "scripts", then it is not copied.

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/105044479-b11fa980-5a5e-11eb-8630-573865e93ad8.png)
I tested your zip file
It seems OK to me

**Comment by CRiS-SVRS** [comment]
> So I finally could manage the issue. It is now a mix of easy2boot and ventoy.
> 
> The basis is Ventoy and the scripts that are used to install and copy the stuff for the unattended setup are borrowed from easy2boot.
> 
> Thank you all for the help!
hi. i'm in the same situation. i try to mix ventoy and e2b script but i can't get out with something that works. maybe i'm missing something or i messed up the batch... 
could you explain how you managed it? 
thanks

**Comment by sraedler** [comment]
@CRiS-SVRS, can you be more specific about where you are having problems?

**Comment by CRiS-SVRS** [comment]
i edited my autounattended adding this code:
```
        <settings pass="specialize">
        <component name="Microsoft-Windows-Deployment" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <RunSynchronous>
                <RunSynchronousCommand wcm:action="add">
                    <Order>1</Order>
                    <Path>cmd /q /c "FOR %i IN (C D E F G H I J K L N M O P Q R S T U V W X Y Z) DO IF EXIST %i:\WIN10\copy_scripts.bat cmd /k %i:\WIN10\copy_scripts.bat %i"</Path>
                </RunSynchronousCommand>
            </RunSynchronous>
        </component>
    </settings>
```

in the "copy_scripts.bat" i put a couples of line to xcopy the "Script" folder from x:\WIN10\ in %systemdrive%\Windows\Setup. 
the bat works manually tested but during setup it won't. i tried almost everything... it looks like setup just skip my "specialize" pass or something like this...

**Comment by sraedler** [comment]
Try the following code in your copy_scripts.bat:

    @echo off
    :: don't run this twice!
    if exist %systemroot%\DONE_SDI.tag exit
    
    :: set USB and location Dir
    set USB=%~d0
    set FILEDIR=%USB%\WIN10\
    set SETUPDIR=%WINDIR%\SETUP\
    
    :: create Temp folder and set log path
    md %systemdrive%\Temp > nul
    set log=%systemdrive%\Temp\%~n0.log
    
    echo "Copy started\r\n" >> %log%
    
    xcopy /herky %FILEDIR%\*.* %SETUPDIR%\ >> %log%
    
    :: push tag to stop
    echo stop > %systemroot%\DONE_SDI.tag
    
    echo "Successful executed" >> %log%
    
    exit


After that you will find the files from your USB in the SETUP folder of your system drive.

**Comment by steve6375** [comment]
The code needs to be in the WIndowsPE pass

e.g.
```

<?xml version="1.0" encoding="utf-8" ?> 
<unattend xmlns="urn:schemas-microsoft-com:unattend">

<settings pass="windowsPE">


<component name="Microsoft-Windows-Setup" processorArchitecture="x86" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<RunSynchronous>
<RunSynchronousCommand wcm:action="add">
<Order>1</Order>
<Path>cmd /q /c "FOR %i IN (C D E F G H I J K L N M O P Q R S T U V W X Y Z) DO IF EXIST %i:\_ISO\E2B\FIRADISK\LOADISONP.CMD cmd /k %i:\_ISO\E2B\FIRADISK\LOADISONP.CMD"</Path>
<Description>Detecting usb drive</Description>
</RunSynchronousCommand>
</RunSynchronous>
<UserData>
<AcceptEula>true</AcceptEula>
<ProductKey>
<Key>W269N-WFGWX-YVC9B-4J6C9-T83GX</Key>
</ProductKey>
</UserData>
</component>

<component name="Microsoft-Windows-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<RunSynchronous>
<RunSynchronousCommand wcm:action="add">
<Order>1</Order>
<Path>cmd /q /c "FOR %i IN (C D E F G H I J K L N M O P Q R S T U V W X Y Z) DO IF EXIST %i:\_ISO\E2B\FIRADISK\LOADISONP.CMD cmd /k %i:\_ISO\E2B\FIRADISK\LOADISONP.CMD"</Path>
<Description>Detecting usb drive</Description>
</RunSynchronousCommand>
</RunSynchronous>
<UserData>
<AcceptEula>true</AcceptEula>
<ProductKey>
<Key>W269N-WFGWX-YVC9B-4J6C9-T83GX</Key>
</ProductKey>
</UserData>
</component>

</settings>
</unattend>

```

https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/how-configuration-passes-work?view=windows-11

**Comment by 999dante** [comment]
> So I finally could manage the issue. It is now a mix of easy2boot and ventoy.
> 
> The basis is Ventoy and the scripts that are used to install and copy the stuff for the unattended setup are borrowed from easy2boot.
> 
> Thank you all for the help!

detail explanation please

**Comment by CRiS-SVRS** [comment]
already explained. 
you have to add this to autounattend.xml: 
````
        <settings pass="specialize">
        <component name="Microsoft-Windows-Deployment" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <RunSynchronous>
                <RunSynchronousCommand wcm:action="add">
                    <Order>1</Order>
                    <Path>cmd /q /c "FOR %i IN (C D E F G H I J K L N M O P Q R S T U V W X Y Z) DO IF EXIST %i:\WIN10\copy_scripts.bat cmd /k %i:\WIN10\copy_scripts.bat"</Path>
                </RunSynchronousCommand>
            </RunSynchronous>
        </component>
    </settings>
````
and create a batch that contains something like this:
````
@echo off
:: don't run this twice!
if exist %systemroot%\DONE_SDI.tag exit

:: set USB and location Dir
set USB=%~d0
set FILEDIR=%USB%\WIN10\
set SETUPDIR=%WINDIR%\SETUP\

:: create Temp folder and set log path
md %systemdrive%\Temp > nul
set log=%systemdrive%\Temp\%~n0.log

echo "Copy started\r\n" >> %log%

xcopy /herky %FILEDIR%\*.* %SETUPDIR%\ >> %log%

:: push tag to stop
echo stop > %systemroot%\DONE_SDI.tag

echo "Successful executed" >> %log%

exit
````
obviously check the right path all over the code.

**Comment by dmuiX** [comment]
@sraedler 
I'm trying the same right now. Would it be possible for you to share your working configuration? Would help a lot to figure it out how to make it work by myself.

**Comment by steve6375** [comment]
If you specify an XML file when using an ISO with Ventoy, then the XML file must have a
`<settings pass="windowsPE">`
section or else the XML file will not be used by Windows at all.
This is because Ventoy creates a **X:\AutoUnattend.xml** file and not a X:\Unattend.xml file. Windows will only cache a X:\AutoUnattend.xml file if it has a windowsPE pass section inside.
If the XML does not contain a windowsPE pass section then Setup will ignore the file. On reboot Setup will look for a <bootdisk>\Unattend.xml or a cached XML file - neither will exist (unless you place a \Unattend.xml file there by some other method) and so your XML file will not be on the hard disk at all.

**Comment by dmuiX** [comment]
@steve6375 If you answered because of my post thanks a lot. My AutoUnattend.xml has this section already. Might be because I come from Easy2Boot and there the dev is/was using it as well. I think e2b is way tooo complicated for my task and I want an easier to maintain solution and also one that is not crashing every time I update it...
Well so far my files are copied to X: so the injection is working. But My SetupComplete.cmd is not working. But I found somet typo. Maybe its working after I fixed it. Either way I will post a link to my github repo with my solution. Maybe it will help some other people to get it working for themselves or somebody can help me figure it out.

**Comment by sraedler** [comment]
I will create a repo as soon as and upload my script with a sample installation using choco and another exe.

The repo will consist of the folder structure so that you can copy it on your USB and just add your windows iso.

**Comment by dmuiX** [comment]
Thats so amazing. Thanks a lot :).

**Comment by sraedler** [comment]
@dmuiX It took a bit to create the reposity due to some changes. But finally, the first version: https://github.com/sraedler/AutoVentoyWin

**Comment by dmuiX** [comment]
Thanks a lot. Well my experience was so far its not working. The Windows Installation runs through. But my user is not being logged in. I have to manually log in and then nothing happens. No apps are installed nothing. Had the same problems before with own scripts. I have used my own autounattend.xml with your scripts and put some more choco install commands and some registry entries and my decrapifier.ps1 script. Maybe it has sth. to do with that...I don't know yet.

**Comment by steve6375** [comment]
If you do not provide the actual XML file you are using, or the \Windows\Panther log files, it is difficult to help.

**Comment by sraedler** [comment]
> I have used my own autounattend.xml with your scripts

I believe that your script might be the problem. The XML file is incorrect if you don't see any dialog during the setup.
Please try once with my script. If it then works, adjust it so that it fits your script.

**Comment by dmuiX** [comment]
Thanks a lot for your help. I will do it when I find time. I do not install any windows 10 system right now. So its not that urgent right now.
