### ISSUE TITLE
Kaspersky Rescue Disk not loading

### ISSUE THREAD

**Issue by IvanAclu** [ventoy/Ventoy#65]
KRD is listed as as compatible.  https://www.ventoy.net/en/isolist.html

I have tried Ventoy 1.0.06, 1.0.07 and 1.0.08 and while it is possible to boot the ISO it fails to load.
After selecting the language, an error occurs when the display mode is selected in both MBR and UEFI modes.

To use under UEFI there is a note to set check_signatures=no in the grub shell before boot.
   Boot Ventoy
   Press C to get to Grub command line
   Enter  set check_signatures=no
   Press return
   Press Escape
   Select KRD
This has no effect and the same error occurs.

**Comment by ventoy** [comment]
Can you give the krd.iso size or checksum? I want to see whether we tested the same iso file.
Or you can give a download link for your iso.

Besides,  can you give more detail about error? maybe some photos ?

**Comment by IvanAclu** [comment]
KRD changes daily as the virus definitions are updated.
I use the latest version from here
https://support.kaspersky.com/viruses/krd18

**Comment by ventoy** [comment]
I download the iso and test it. It worked well in VirtualMachine with both legacy bios and UEFI.
I will test it in a real machine later.

**Comment by IvanAclu** [comment]
Tested with 1.0.09 Beta1
UEFI - I get this message
   No bootfile found for UEFI!
   Maybe the image does not support X64 UEFI!
  _
MBR
Get message in photo below

**Comment by IvanAclu** [comment]
Tested with Ventoy 1.0.09 Beta1
UEFI - I get his message
   No bootfile found for UEFI!
   Maybe the image does not support X64 UEFI!
   _
MBR
See photo
![Ventoy MBR error99_cr](https://user-images.githubusercontent.com/64646805/81166907-3b38e800-8f8c-11ea-817a-6be2b68baaff.jpg)

**Comment by ventoy** [comment]
I test it on my laptop, still OK in both legacy and UEFI.
**krd.iso SHA1:  ff36e88b5425e2c56a85b9870deded045fa01073**
Is it right?  You can check the sha1 of the iso file in the usb drive.

**Comment by IvanAclu** [comment]
The ISO I tested with has the same SHA1: FF36E88B5425E2C56A85B9870DEDED045FA01073 as the one that you used.

**Comment by IvanAclu** [comment]
Tested on a Dell laptop with Ventoy 1.0.0.09 beta1

MBR
error:bad signature.
	Press any key to continue..._

Pressing any key has no effect.
After approximately 20 seconds it continues 
and ends with this
![Dell UEFI 1 pers_cr2](https://us.er-images.githubusercontent.com/64646805/81229282-71f01c00-8fe7-11ea-94b4-5cab0d37c39d.jpg)

**Comment by IvanAclu** [comment]
Tested on a Dell laptop with Ventoy 1.0.0.09 beta1

UEFI - Secure boot off
	error:bad signature.
	Press any key to continue..._

UEFI - Secure boot on
entered set check_signstures=off
	error:bad signature.
	Press any key to continue..._

Pressing any key has no effect.
After approximately 20 seconds it continues 
![IMG_20200506_204823746_cr_cr_cr](https://user-images.githubusercontent.com/64646805/81229738-39047700-8fe8-11ea-9d8a-c5c40b8104e5.jpg)

**Comment by IvanAclu** [comment]
Tested on a Dell laptop with Ventoy 1.0.0.09 beta1

MBR
	error:bad signature.
	Press any key to continue..._

Pressing any key has no effect.
After approximately 20 seconds it continues 
![Dell UEFI 1 pers_cr2](https://user-images.githubusercontent.com/64646805/81229941-8e408880-8fe8-11ea-8dcf-31a8595924ee.jpg)

**Comment by IvanAclu** [comment]
I have retested with Ventoy 1.0.09 on 4 different PCs. 
KRD boots successfully but then fails to load on all 4 PCs.
Ventoy fails to load KRD after the mode selection screen.

When you tested have you been able to go past the mode selection screen?

I have also tested the same ISO with Easy2Boot. KRD loads successfully on all 4 PCs.
This indicates to me that it is not a problem with a corrupted ISO or the hardware.

I attach a picture showing the sequence of successfully loading KRD.
![KRD menus](https://user-images.githubusercontent.com/64646805/81540434-90e50a00-9369-11ea-9e97-e74ab875e626.jpg)

**Comment by ventoy** [comment]
Yes, I indeed boot into the desktop, not only boot menu.
So it's a little strange.
Is the error in 1.0.09  the same with old version?

**Comment by IvanAclu** [comment]
Tested again with Ventoy 1.0.13
Legacy/BIOS boot works on all 5 PC's tested.
UEFI Boot failed on the 2 PC's tested

**Comment by IvanAclu** [comment]
Forgot to say.
Installed Ventoy 1.0.13 on USB with Secure Boot Option off.
UEFI Secure Boot on PC's turned off.

**Comment by IvanAclu** [comment]
Have tested KRD UEFI boot on Asus X441SA this also fails with, error: bad signature

**Comment by IvanAclu** [comment]
On my Asus Prime Z270A why do I get two UEFI Boot options for the Ventoy USB drive?
UEFI: Sandisk Extreme 0001, Partition 1 (61057MB) - This boots straight to Windows.
UEFI: Sandisk Extreme 0001, Partition 2 (61057MB) - This boots to Ventoy.
![1 UEFI settings pers](https://user-images.githubusercontent.com/64646805/85200482-c1687e00-b2ef-11ea-90c9-797c026cf8ae.png)
![2 UEFI Boot selection pers](https://user-images.githubusercontent.com/64646805/85200484-c2011480-b2ef-11ea-8ce5-fd29b0970d0f.png)
![3 KRD setting pers](https://user-images.githubusercontent.com/64646805/85200485-c299ab00-b2ef-11ea-8157-09bffa8343cf.png)
![4 KRD display selection pers](https://user-images.githubusercontent.com/64646805/85200486-c3324180-b2ef-11ea-9765-3c7aebf1c2d1.png)
![5 after KRD display setting pers](https://user-images.githubusercontent.com/64646805/85200487-c3324180-b2ef-11ea-9ae7-c76036d9e86f.png)

**Comment by JazzTech** [comment]
I am also seeing the **error: bad signature** message when booting KRD through Ventoy in UEFI mode.

**Comment by IvanAclu** [comment]
Tested again with Ventoy 1.0.15.

UEFI Boot failed on the 2 PC's tested.
Both failed after selecting Kaspersky Rescue Disk. Graphic mode.
I entered "set check_signatures=no" first.

Asus Prime Z270-A & Dell Inspiron 7720 secure boot turned off

error: bad signature.
Press any key to continue...

**Comment by IvanAclu** [comment]
Here is video of Ventoy 1.0.015 UEFI boot failing.
Motherboard Asus Prime Z270-A
Secure boot turned off
With these GRUB2 settings
> set pager=1
> set check_signatures=no
> vtdebug on

[Ventoy_1015_KRD_X264.zip](https://github.com/ventoy/Ventoy/files/4906562/Ventoy_1015_KRD_X264.zip)

**Comment by ventoy** [comment]
`set check_signatures=no`  should be run in KRD's grub enviroment NOT Ventoy's envrioment.

![image](https://user-images.githubusercontent.com/59477474/87223432-794cf080-c3af-11ea-90a7-dc6d8b8da872.png)

**Comment by IvanAclu** [comment]
Thanks, with this clarification I can now UEFI boot to KRD

For other users the steps are:

Boot to KRD first menu
Press c to go to the KRD GRUB2 prompt
Type  set check_signautures=no
Press ENTER
Press ESC

Select language and carry on
KRD will now boot

**Comment by IvanAclu** [comment]
@ventoy Longpanda why do I see two UEFI entries for my 64GB stick?
I have used the standard Ventoy formatting.

UEFI: Sandisk Extreme 0001, Partition 1 (61057MB) - This boots straight to Windows.
UEFI: Sandisk Extreme 0001, Partition 2 (61057MB) - This boots to Ventoy.

**Comment by ventoy** [comment]
The boot option is generated by UEFI firmware.  May be the UEFI firmware in your computer already integrated exfat/ntfs efi driver.
Only FAT is standard supported by UEFI specification, but some UEFI firmware integrates other efi driver, for example exfat/ntfs.

**Comment by IvanAclu** [comment]
OK Thanks

**Comment by nierewa** [comment]
Sorry that I reactivate this tread.

The solution is:
Boot to KRD first menu
Press c to go to the KRD GRUB2 prompt
Type set check_signatures=no
Press ENTER
Press ESC

Is there a way tho change a file in KRD.iso so that I have to do this manually?

I add the "set check_signatures=no" parameter in boot/cfg/menu_lang.cfg
but I get this error message:

Something goes wrong with config (cd0)/boot/grub/grub.cfg

Legacy Boot ends uo with bash.

**Comment by IvanAclu** [comment]
I do not think that you can do this.
When booting, KRD checks that its configuration files have not been modified by using a signature file.
If any changes are found KRD will not boot.

**Comment by nierewa** [comment]
Hmm, that's what I hought.
Can you change the signature file or is there any way to circumvent this?

**Comment by IvanAclu** [comment]
I don't know. 
Look here for more info.
https://www.gnu.org/software/grub/manual/grub/html_node/Using-digital-signatures.html

**Comment by almodovaris** [comment]
Just press Ctrl-R (for GRUB) and it boots.
