### ISSUE TITLE
Secure boot feedback and question

### ISSUE THREAD

**Issue by MFlisar** [ventoy/Ventoy#653]
**Feedback**

I just tried ventoy again with a new usb stick and did following:

- created a MBR stick without secure
- enabled secure boot in ventoy
- tried to switch to GPT

Here my feedback is that switching from MBR to GPT is silently failing (it just does not work)

**Problem**

Additionally I have a problem that is not mentioned in the documentation:

If I enable secure boot, the ventoy stick is not recognized at all, this means the bios is skipping to my installed windows without recognizing ventoy on my usb stick - this happens in MBR + secure mode as well as in GPT + secure mode. I see informations about errors in the documentation but nothing about that ventoy is not recognized at all on boot.

Is this a known and not solvable issue? Or is there something else I can try?

**Comment by ventoy** [comment]
1. MBR or GPT option is ony for install, when you update Ventoy, this option is not used. That is to say, when you finish install, the MBR/GPT part style is fixed and can NOT be changed unless you reinstall Ventoy.
2. You mean, you enable secure boot the stick is not recognized, if you disable secure boot, it is recognized? Did you enable secure boot option in your BIOS setting?

**Comment by MFlisar** [comment]
>     1. MBR or GPT option is ony for install, when you update Ventoy, this option is not used. That is to say, when you finish install, the MBR/GPT part style is fixed and can NOT be changed unless you reinstall Ventoy.

This was not obvious for me - the GUI shows it somehow if you pay attention. Maybe a simple dialog telling the user that this option can not be changed without reinstalling ventoy would improve usability...

>     2. You mean, you enable secure boot the stick is not recognized, if you disable secure boot, it is recognized? Did you enable secure boot option in your BIOS setting?

Correct. As a side note I must say, that my bios does not allow UEFI without save mode, this means I must disable UEFI and switch to legacy mode. In legacy mode (I made sure that the usb stick is the first boot device) the stick is just jumped over (no matter if I try MBR or GPT with secure boot).

**Comment by ventoy** [comment]
1. I have noted in the manual, MBR/GPT option is only for install. MBR and GPT are compeletly different partition layout, so we can't swith from one to another without reformat. 

2. I have noted here https://www.ventoy.net/en/doc_secure.html   
   The secure boot solution in Ventoy has some compatibility problem in some machine.  If so, you must disable secure boot in BIOS and at the same time disable the secure boot option in Ventoy.
If you can't disable secure boot in your BIOS. That means you can't use Ventoy in UEFI mode. You can only use Ventoy in Legacy BIOS mode(Remember to disable the secure boot option in Ventoy at the same time).

**Comment by MFlisar** [comment]
Thanks for clarification. I made a mistake in my previous reply in point 2. It should be following:

2. In **UEFI mode (with enabled secure boot)** the stick is just jumped over (no matter if I try MBR or GPT with secure boot).

So my question here is, if this behavior is an expected "problem" and just means I must switch to legacy mode on my machine.

**Comment by ventoy** [comment]
Yes.
The secure boot solution in Ventoy has some compatibility problem in some machine.
It's possible that  the Ventoy disk can not boot at all when you enable secure boot in your BIOS setting.

**Comment by MFlisar** [comment]
Ok, thanks for taking the time to explain.
