### ISSUE TITLE
latest Blackarch won't start "ERROR: '/dev/disk/by-label/"

### ISSUE THREAD

**Issue by lucki1000** [ventoy/Ventoy#654]
Hi,

I have tried to boot the latest Blackarch ISO "blackarch-linux-full-2020.12.01-x86_64.iso" but stucks at:

Waiting 30 seconds for device /dev/disk/by-label/BLACKARCH_202011
ERROR: '/dev/disk/by-label/BLACKARCH_202011' device did not show up after 30 seconds.

I use ventoy 1.30(also installed on usb)  x86_64 on Arch Linux
usb is GPT formatted secureboot disabled on usb and PC, the ISO file is stored on ext4 partition.

regards
Lucki1000

**Comment by ventoy** [comment]
I have fixed it.
If you want you can test it manually.

Update to latest release 1.0.30
Replace the file /grub/grub.cfg in the 2nd partition (VTOYEFI partition) with https://github.com/ventoy/Ventoy/blob/master/INSTALL/grub/grub.cfg

**Comment by lucki1000** [comment]
Now it works thanks for the fast response 👍
