### ISSUE TITLE
ventoy在某些平板windows电脑无法被识别引导

### ISSUE THREAD

**Issue by seawiththewind** [ventoy/Ventoy#657]
我用的是影雅w8100平板电脑。该电脑配置为atom z8350，主板的UEFI据说是32位的阉割版，无法通过ventoy进行引导。
现在只有32位版本的WEPE可以对其进行成功引导。
不知道能否加入对32位的UEFI的支持呢？据说有很大一部分的平板电脑都是这样的阉割版UEFI。

**Comment by ventoy** [comment]
最新的 1.0.30 版本支持 32位 UEFI

**Comment by seawiththewind** [comment]
谢谢
