### ISSUE TITLE
皮肤怎么安装啊？

### ISSUE THREAD

**Issue by sjkhsl** [ventoy/Ventoy#661]
皮肤下载下来后，安装后直接就修改系统的grub了，ventoy的没反映。求解决办法！

**Comment by sjkhsl** [comment]
然后把皮肤复制到根目录，修改名称也没有反应！这个教程写的实在是让人头大！

**Comment by ventoy** [comment]
Ventoy的安装包里有一个主题示例，直接把 plugin目录下的  ventoy 这个目录拷贝到U盘根目录下即可（不包含plugin目录，只拷贝里面的 ventoy目录， 拷贝到存放ISO文件的那个分区根目录下）

之后你可以直接替换里面对应的图片即可。

**Comment by sjkhsl** [comment]
> Ventoy的安装包里有一个主题示例，直接把 plugin目录下的 ventoy 这个目录拷贝到U盘根目录下即可（不包含plugin目录，只拷贝里面的 ventoy目录， 拷贝到存放ISO文件的那个分区根目录下）
> 
> 之后你可以直接替换里面对应的图片即可。

好吧，我在安装目录里修改，重新安装好几回😭
感谢，弄好了！
