### ISSUE TITLE
安全启动选项状态不保存

### ISSUE THREAD

**Issue by jianyuyanyu** [ventoy/Ventoy#662]
Ventoy2Disk.exe 1.0.30版本 安全启动选项状态勾选上以后关闭软件，再次打开软件安全启动选项失效

**Comment by ventoy** [comment]
这个确实是修改了。现在安全启动这个选项不会保存和恢复。
30版本 在升级Ventoy时会保留U盘中的安全启动设置。所以这个选择会随着你“设备”下拉框中选择的变化而跟着变化。

**Comment by jianyuyanyu** [comment]
是我没有注意release公告，麻烦了
