### ISSUE TITLE
[Question] Where is the /dev/sdc1 (ventoy partition) mounted

### ISSUE THREAD

**Issue by sebma** [ventoy/Ventoy#667]
Hi,
I had stored along with the ISOs, some of my scripts on the ventoy partition and I'd like to run them.
After booting ventoy and load the ubuntu ISO, I cannot find where the ventoy partition is mounted : 
```
$ sudo fdisk -l /dev/sdc
Disk /dev/sdc: 28.89 GiB, 30992891904 bytes, 60532992 sectors
Disk model: Silicon-Power32G
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x7412da37

Device     Boot    Start      End  Sectors  Size Id Type
/dev/sdc1  *        2048 60467455 60465408 28.9G  7 HPFS/NTFS/exFAT
/dev/sdc2       60467456 60532991    65536   32M ef EFI (FAT-12/16/32)
$ findmnt /dev/sdc1
$
```
Can you tell me where it is mounted ?

**Comment by ventoy** [comment]
/dev/sdc1 can **NOT** be mounted due to Ventoy's internal mechanism.

**Comment by ventoy** [comment]
The latest Ventoy 1.0.64  provides an experimental option  `VTOY_LINUX_REMOUNT` which can help to access the ISO partition after boot.

**Comment by sebma** [comment]
@ventoy By "the ISO partition", you mean the partition containing the ISO files, the partition that is labelled `Ventoy` by default right ?
