### ISSUE TITLE
Terminal wizard for GNU/Linux

### ISSUE THREAD

**Issue by igatjens** [ventoy/Ventoy#668]
Ventoy does not have a graphical interface for GNU/Linux, I think a quick and very useful alternative is a terminal wizard.

I have created a script that helps to select the options and select between the USB storage devices connected to the computer.

Then run Ventoy2Disk.sh.

I attach the script and some screenshots.

[ventoy-wizard.zip](https://github.com/ventoy/Ventoy/files/5743967/ventoy-wizard.zip)

I hope it helps.

![Captura de pantalla_área-de-selección_20201226190203](https://user-images.githubusercontent.com/66392244/103161863-00e7b980-47ae-11eb-9688-3a850e7f69b9.png)

![Captura de pantalla_área-de-selección_20201226190219](https://user-images.githubusercontent.com/66392244/103161868-0cd37b80-47ae-11eb-8558-7e5867138fa9.png)

![Captura de pantalla_área-de-selección_20201226190233](https://user-images.githubusercontent.com/66392244/103161871-1230c600-47ae-11eb-9ef8-7f2ecb5646b2.png)

![Captura de pantalla_área-de-selección_20201226190258](https://user-images.githubusercontent.com/66392244/103161872-178e1080-47ae-11eb-8aca-9b70a85368ec.png)

![Captura de pantalla_área-de-selección_20201226190317](https://user-images.githubusercontent.com/66392244/103161874-1b219780-47ae-11eb-8625-5753e808a19f.png)

**Comment by ventoy** [comment]
Thanks.
GUI for linux is in my plan.

**Comment by igatjens** [comment]
Thanks for the prompt response.

If you want, you can use this script while finishing the GUI development.

A few hours ago I made a few small changes to make it more pleasant to use and display for 1 second (literally) the selected option.

[ventoy-wizard.zip](https://github.com/ventoy/Ventoy/files/5745082/ventoy-wizard.zip)

Ventoy seems like a very good project. I made a .deb package to put in a launcher and created an icon for the launcher, maybe you like it or maybe not, but I offer it if it helps you in something.

[ventoy.svg.zip](https://github.com/ventoy/Ventoy/files/5745084/ventoy.svg.zip)

Greetings and thanks, very good job.

**Comment by ventoy** [comment]
Ventoy 1.0.36 release with Linux GUI based on web browser.
https://www.ventoy.net/en/doc_linux_webui.html
![Uploading webui_en.png…]()

**Comment by ventoy** [comment]
Ventoy-1.0.52 release with native Linux GUI
https://www.ventoy.net/en/doc_linux_gui.html
