### ISSUE TITLE
请求支持运行 macos 镜像文件安装

### ISSUE THREAD

**Issue by carlchina** [ventoy/Ventoy#67]
一直在找一款可以同时支持 windows iso 和 mac iso 运行的 usb 启动器

**Comment by blackcrack** [comment]
OSX是苹果的linux，因此请尝试linux二进制文件
此外，其他人也应该在世界范围内听到他们的意思，这就是为什么英语通常是互联网上的标准语言的原因
不然我会说德语 .. 
请关闭此任务，因为您在此处编写的内容只是声明而非程序问题
