### ISSUE TITLE
More options to install Ventoy

### ISSUE THREAD

**Issue by RaXorX** [ventoy/Ventoy#670]
Currently, the only way to install ventoy offered right now is to install it via the installer and formatting the device as per the limited options that are available. Even for hard disks that seem to be the case.
What I propose is to remove this limitation and allow installation via a simple extraction too on devices prepared manually aka ventoy doesn't force the partitioning itself. 

I didn't think there would be any limitations if one extracted those files manually, but when I put all the ventoy related files within my EFI partition, I have this error on my side, telling me that "This is not a standard Ventoy device and is NOT supported."

Why are there such restrictions? Not everyone would be happy formatting their HDDs to use it.

**Comment by a1ive** [comment]
https://github.com/ventoy/Ventoy/commit/8bbd5a14a3ca4820266bed6afc1314c3f41e76c3

**Comment by ventoy** [comment]
The partition layout is part of the whole Ventoy solution.  That's how Ventoy designed from the beginning.
