### ISSUE TITLE
wifislax64 2.1 cannot start

### ISSUE THREAD

**Issue by diablosoy** [ventoy/Ventoy#671]
Hi. I have seen that the iso of wifislax64 2.1 is compatible with ventoy. However when starting the iso it does not work for me. Attached image of the error that gives me. I don't know if I have to do some kind of thing. Can you help me? Thank you

![error wifislax](https://user-images.githubusercontent.com/76746078/103302774-b9a73600-4a04-11eb-9310-36aa62680b00.png)

**Comment by ventoy** [comment]
It's a bug, I have fixed it. It will be OK in the next Ventoy release.

**Comment by ventoy** [comment]
Please try with 1.0.32

**Comment by ventoy** [comment]
It should work in the latest release. I will close this issue now.
