### ISSUE TITLE
Tails OS 4.14 iso image not working

### ISSUE THREAD

**Issue by kajzersoze** [ventoy/Ventoy#672]
It gets to the Tails OS boot menu where you choose between Tails OS and Tails OS (Troubleshooting) , no matter what you choose it gives error a couple of seconds later

**Comment by ventoy** [comment]
I test `tails-amd64-4.14.iso md5:25b301c9c7ec6a377e93d849a1e4ca2b` in my laptop and it boot fine in  both Legacy BIOS and UEFI mode.
Please give some details about the error, better with some photos.

**Comment by ventoy** [comment]
Maybe similar with #626

**Comment by ventoy** [comment]
What about this release: https://github.com/ventoy/Ventoy/actions/runs/613266157

**Comment by VanillaBase1lb** [comment]
Does not work. Tails 4.16 and the latest Ventoy version. Tails gets stuck on loading page and then stuck on (initfram) shell

**Comment by VanillaBase1lb** [comment]
Sorry my bad, I was using .img instead of .iso. It works with .iso, you may close the issue

**Comment by kajzersoze** [comment]
Sorry for the late reply, I'm using Legacy BIOS mode, didn't try UEFI
I made Ventoy stick once and then just adding and removing ISO's
How do I update Ventoy?

**Comment by quaitzel** [comment]
Tails 4.16 and also 4.15.1 are not working (ventoy 1.0.37).
If Tails ISO is selected in list the screen goes black and after some seconds it jumps back to ISO-list.

**Comment by kajzersoze** [comment]
Exactly, I don't know how and why it works for some, but I've tried maybe 20 different ISO's and they all worked fine, except Tails

**Comment by steve6375** [comment]
What is your USB drive? Make\Model\Size\Type
What filesystem is on partition 1?
What system re you booting from?

**Comment by kajzersoze** [comment]
Jesus... just forget about it ...

**Comment by steve6375** [comment]
I ask because Tails is very fussy!
First, it will only boot successfully from USB Flash drives (Removable type) not USB Hard Disks.
Also the kernel parameters must be correct for each distro as they change from versions to version.
Also, Ventoy may not find any EFI files in the ISO if you boot on some systems (e.g. Asus Z87) and report an error immediately but boots fine on others (e.g. IdeaPad 300).
Also, you may get a graphics error and need to add in extra kernel parameters to avoid this (e.g. for VESA graphics).
https://rmprepusb.blogspot.com/2020/01/direct-uefi64-boot-from-tails-24-using.html

**Comment by quaitzel** [comment]
The solution on my side was to actually really use the .iso not the .img.
Sorry, was my fault. 
Maybe kajzersoze had the same issue? :D

**Comment by kajzersoze** [comment]
Like the title says, it's ISO image.
Look, this is really the only one ISo with the problem that I faced, and I tried 20+ images.
I made Ventoy only once, I delete and add ISO images as needed, always checking the checksums
Ventoy is in Legacy mode, not UEFI, because I use Legacy BIOS even though I have modern MB, ASUS Prime
I described what's going on in the first post
It doesn't work for some reason, fine, I reported the issue and it's probably just me, for some odd reason.
Same image on other USB flash drive, but not on Ventoy, just the Tails OS, and it works fine.
I guess Tails doesn't like Ventoy, there's no other explanation, in my case at least.
I've closed this and if someone else encounter this problem, well ...

**Comment by kajzersoze** [comment]
Okay, so I've deleted old Ventoy (don't know what version was that) and installed 1.0.37
Now Tails is working
I also updated BIOS, so maybe that was the problem before, hard to tell now, I guess I could've tried the old Ventoy where Tails wasn't working before I made new one, but I forgot
But like I said, only Tails wasn't working while 20+ other ISO's were.
Whatever it was it's ok now :D
