### ISSUE TITLE
能否提供超时自动进入默认的镜像

### ISSUE THREAD

**Issue by mzky** [ventoy/Ventoy#674]
经验证群晖启动img文件可以使用，但是需要手动敲回车，因官方手册没查到相关功能，希望作者能够提供此功能，谢谢！

**Comment by ventoy** [comment]
请参考 https://www.ventoy.net/cn/plugin_control.html
VTOY_MENU_TIMEOUT 和 VTOY_DEFAULT_IMAGE    参数

**Comment by mzky** [comment]
非常感谢！
