### ISSUE TITLE
关于自动安装镜像使用的kickstart 文件

### ISSUE THREAD

**Issue by RyanDx** [ventoy/Ventoy#675]
我安装的是CentOS7.6
设置了自动安装脚本cfg文件，里边有一个参数需要指定镜像源路径，我设置的cdrom，没有安装成功，
这个应该怎么设置，是要预先解压镜像到一个路径吗？然后指定本地路径吗？

**Comment by mzky** [comment]
官方文档有，路径是写U盘下的路径 比如ISO/centos.iso

**Comment by ventoy** [comment]
不需要设置，比如
```

install

lang en_US.UTF-8
keyboard us
rootpw  123456
firewall --service=ssh
authconfig --enableshadow --passalgo=sha512
selinux --disable
timezone --utc Asia/Shanghai

eula --agreed
firstboot --disable

# bootloader
bootloader --location=mbr --driveorder=sda

# partition
ignoredisk --only-use=sda
clearpart --all --initlabel --drives=sda
zerombr
autopart --type=plain

#packages configuration
%packages
@core
net-tools
%end

reboot
```

**Comment by RyanDx** [comment]
> 不需要设置，比如
> 
> ```
> 
> 
> 
> install
> 
> 
> 
> lang en_US.UTF-8
> 
> keyboard us
> 
> rootpw  123456
> 
> firewall --service=ssh
> 
> authconfig --enableshadow --passalgo=sha512
> 
> selinux --disable
> 
> timezone --utc Asia/Shanghai
> 
> 
> 
> eula --agreed
> 
> firstboot --disable
> 
> 
> 
> # bootloader
> 
> bootloader --location=mbr --driveorder=sda
> 
> 
> 
> # partition
> 
> ignoredisk --only-use=sda
> 
> clearpart --all --initlabel --drives=sda
> 
> zerombr
> 
> autopart --type=plain
> 
> 
> 
> #packages configuration
> 
> %packages
> 
> @core
> 
> %end
> 
> 
> 
> reboot
> 
> ```

提示mounting /dev/dm-0 on run/install/repo failed

**Comment by RyanDx** [comment]
问题已解决
1:可能用的笔记本老旧，论装什么系统都会提示mounting /dev/dm-0 on run/install/repo failed，解决方法：bios改为uefi 

2:kickstart文件确实不需要指定安装源
但是一定要设置指向的盘，我就是没设置把优盘给格了
3:centos7.6 安装成功了，我又试了8.3，出了新问题，kickstart文件设置的安装源、安装盘指定、软件选择、到了最后begin install 显示全部无效，需要手动重新定义，我看了最新的ventoy支持列表是8.0，可能是ventoy固件还没适配吧

**Comment by ventoy** [comment]
也可能 8.3 kickstart的写法要求变了。
要找一个确保在8.3上能正常使用的kickstart 文件，然后再在Ventoy里面用，如果出问题，才说明是Ventoy的问题。

**Comment by RyanDx** [comment]
> 也可能 8.3 kickstart的写法变了。
> 
> 要找一个确保在8.3上能正常使用的kickstart 文件，然后再在Ventoy里面用，如果出问题，才说明是Ventoy的问题。
> 
> 

我最近用pxe装系统时centos8.3使用这个kickstart能安装成功，centos7.6也是直接从我的pxe迁移过来去掉安装源参数然后指定安装盘就成功了，8.3一样的操作会卡在Error setting up base repository![Uploading 103395293...]()

**Comment by ventoy** [comment]
把你的kickstart贴一下我自己测试一下。

**Comment by RyanDx** [comment]
> 把你的kickstart贴一下我自己测试一下。

我的其实和你贴的ks文件差不多，麻烦帮忙试试，辛苦啦


#platform=x86, AMD64, or Intel EM64T
#version=DEVEL
# Install OS instead of upgrade
install
# Keyboard layouts
keyboard us
# Root password
rootpw 111111
# System language
lang en_US.UTF-8
# Firewall configuration
firewall --disabled
# System authorization information
auth  --useshadow  --passalgo=sha512
# Use text mode install
text
# Run the Setup Agent on first boot
eula --agreed
firstboot --disable
# SELinux configuration
selinux --disabled
# Do not configure the X Window System
skipx
# System timezone
timezone --utc Asia/Shanghai

# bootloader
bootloader --location=mbr --driveorder=sda

# partition
ignoredisk --only-use=sda
clearpart --all --initlabel --drives=sda
zerombr
autopart --type=lvm

#packages configuration
%packages
@base-x
@core
%end

**Comment by ventoy** [comment]
我前面那个 kickstart 文件实测在 CentOS 7系列一直到 CentOS 8.2 都是可用的。
CentOS 8.3上确实有问题。必须加上下面这句才可以。
```
url --url=file:///run/install/repo
```

**Comment by RyanDx** [comment]
> 我前面那个 kickstart 文件实测在 CentOS 7系列一直到 CentOS 8.2 都是可用的。
> 
> CentOS 8.3上确实有问题。必须加上下面这句才可以。
> 
> ```
> 
> url --url=file:///run/install/repo
> 
> ```
> 
> 
> 
> 

这一条参数是默认的值嘛，如果cenos7的ks加这句也能成功吗

**Comment by ventoy** [comment]
值是默认的， centos7我没试过，不过我觉得加上这句应该也没影响，你可以试试。8.2的我试过，加不加这句都行。

**Comment by RyanDx** [comment]
> 值是默认的， centos7我没试过，不过我觉得加上这句应该也没影响，你可以试试。8.2的我试过，加不加这句都行。
> 
> 

对了，我还遇到一个问题，有些电脑会把优盘识别为sda，这种情况使用ks文件自动安装会导致把优盘格掉，我只能把指定盘参数变为sdb来进行自动安装，venty有参数可以保护优盘不被改写吗

**Comment by ventoy** [comment]
这个做不到，除非硬件上有写保护功能。
这种情况，你disk不能写死。需要加一段 %pre 脚本，来动态监测当前要安装的盘到底是 sda还是 sdb
可以给你一个例子
```
install

lang en_US.UTF-8
keyboard us
rootpw  123456
firewall --service=ssh
authconfig --enableshadow --passalgo=sha512
selinux --disable
timezone --utc Asia/Shanghai

eula --agreed
firstboot --disable

%include /tmp/partation.ks
zerombr
autopart --type=plain

#packages configuration
%packages
@core
%end

reboot

%pre

disk_short_name=sda

echo bootloader --location=mbr --driveorder=$disk_short_name >> /tmp/partation.ks
echo ignoredisk --only-use=$disk_short_name  >> /tmp/partation.ks
echo clearpart --all --initlabel --drives=$disk_short_name  >> /tmp/partation.ks

%end

```

`disk_short_name=sda` 这个地方你需要根据不同的情况，做一些判断，来确定，比如
```
if xxxx; then
    disk_short_name=sda
elif xxxx; then
    disk_short_name=sdb
elif xxxx; then
    disk_short_name=nvme0n1
fi
```

**Comment by RyanDx** [comment]
> 这个做不到，除非硬件上有写保护功能。
> 
> 这种情况，你disk不能写死。需要加一段 %pre 脚本，来动态检测当前要安装的盘到底是 sda还是 sdb
> 
> 可以给你一个例子
> 
> ```
> 
> install
> 
> 
> 
> lang en_US.UTF-8
> 
> keyboard us
> 
> rootpw  123456
> 
> firewall --service=ssh
> 
> authconfig --enableshadow --passalgo=sha512
> 
> selinux --disable
> 
> timezone --utc Asia/Shanghai
> 
> 
> 
> eula --agreed
> 
> firstboot --disable
> 
> 
> 
> %include /tmp/partation.ks
> 
> zerombr
> 
> autopart --type=plain
> 
> 
> 
> #packages configuration
> 
> %packages
> 
> @core
> 
> %end
> 
> 
> 
> reboot
> 
> 
> 
> %pre
> 
> 
> 
> disk_short_name=sda
> 
> 
> 
> echo bootloader --location=mbr --driveorder=$disk_short_name >> /tmp/partation.ks
> 
> echo ignoredisk --only-use=$disk_short_name  >> /tmp/partation.ks
> 
> echo clearpart --all --initlabel --drives=$disk_short_name  >> /tmp/partation.ks
> 
> 
> 
> %end
> 
> 
> 
> ```
> 
> 
> 
> `disk_short_name=sda` 这个地方你需要根据不同的情况，做一些判断，来确定，比如
> 
> ```
> 
> if xxxx; then
> 
>     disk_short_name=sda
> 
> elif xxxx; then
> 
>     disk_short_name=sdb
> 
> elif xxxx; then
> 
>     disk_short_name=nvme0n1
> 
> fi
> 
> ```
> 
> 
> 
> 

之前我有试过，官方文档里讲的ignoredisk可以通过设备的wwid去忽略设备，但到最后没忽略成功
例如：ignoredisk --drives=disk/by-id/dm-uuid-mpath-2416CD96995134CA5D787F00A5AA11017

**Comment by ventoy** [comment]
指定名称是肯定可以的。
我们PXE安装都是这样用。我们的情况更复杂，有 SSD 还有NVME，有要求装在第一个盘，有要求装在第二个盘，还有的要求装在容量最小的盘（不管哪个），我们都是通过 %pre 脚本来做判断，扫描出来 是 sda就是sda 是nvme0n1就是 nvme0n1 
绝对不会出错。

**Comment by ventoy** [comment]
这个问题应该已经解决了。我先关闭此issue。

**Comment by RyanDx** [comment]
os_disk=`lsblk |egrep -o '(sd[a-z]|nvme[0-9]n[0-9]).*VTOYEFI$'|awk '{print $1}' |egrep -o '(sd[a-z]|nvme[0-9]n[0-9])'`

我计划用这条命令，抓取到优盘，可行吗
