### ISSUE TITLE
古董笔记本认不到iso

### ISSUE THREAD

**Issue by LittleDeng1** [ventoy/Ventoy#678]
![IMG_20210101_125942](https://user-images.githubusercontent.com/62782358/103433812-babdaa80-4c32-11eb-93a1-0922dc494ce8.jpg)
![16094782862785143707735773569926](https://user-images.githubusercontent.com/62782358/103433866-d2e1f980-4c33-11eb-863a-9197d1034c68.jpg)

引导没问题 盘和default search root参数在其他机子一直用着正常 就这老古董认不到任何iso

**Comment by a1ive** [comment]
应该是 BIOS 访问范围限制导致的：https://www.ventoy.net/cn/doc_legacy_limit.html

**Comment by ventoy** [comment]
先升级一下吧，你这个 1.0.13版本太老了。最新的是 1.0.31

**Comment by LittleDeng1** [comment]
![wtf](https://user-images.githubusercontent.com/62782358/103448822-eb0c5400-4cd9-11eb-9bf0-60daffb85f50.png)
有点意思 其实这盘不是1.0.13

**Comment by ventoy** [comment]
这个Ventoy安装之后应该被魔改过。
首先它会显示一个  Unofficial Ventoy字样，就表示不是原版的。
其次就是这个版本号显示根本对不起来。

**Comment by LittleDeng1** [comment]
一直都是在releases下的 搞不懂哪里出的问题都
