### ISSUE TITLE
Current Ventoy (1.0.31) is not working @ Raspberry Pi 4B 8 GB

### ISSUE THREAD

**Issue by DragonSerW** [ventoy/Ventoy#679]
`Linux raspberrypi 5.4.79-v7l+ #1373 SMP Mon Nov 23 13:27:40 GMT 2020 armv7l GNU/Linux
`
log.txt:
############# Ventoy2Disk -I -s /dev/sda [i386] ################
Fri 01 Jan 2021 12:00:05 PM MSK
no need to decompress tools
root permission check ok ...
MODE=install FORCE=Y RESERVE_SPACE= RESERVE_SIZE_MB=0
hexdump test fail ...

**Comment by ventoy** [comment]
Ventoy only support `x86(i386&x86_64)` and `arm64(aarch64)`.
`armv7l` is not supported.

**Comment by kelvinnkat** [comment]
Doesn't the Raspberry Pi 4 (and 3, for that matter) support aarch64? My apologies if I am asking this question as a result of my lack of knowledge on the issue.
