### ISSUE TITLE
将exfat分区格式化为ntfs后无法启动

### ISSUE THREAD

**Issue by wang0810** [ventoy/Ventoy#68]
仅可以选择exfat分区格式吗，请求加入ntfs格式支持

**Comment by ventoy** [comment]
当前仅支持exfat格式， NTFS格式后续版本有规划支持。

**Comment by blackcrack** [comment]
wäre schön, wenn auch Fat32 unterstützt werden würde, vielleicht eine Auswahl bei dem Formatieren ?

**Comment by ventoy** [comment]
最新1.0.10版本已经支持NTFS
