### ISSUE TITLE
All page titles in the doc are the same

### ISSUE THREAD

**Issue by noyannus** [ventoy/Ventoy#682]
Small issue to make learning about Ventoy and setting it up easier:

Change the title of the pages at www.ventoy.net to something specific. Currently all browser tabs of the site are labelled "Ventoy" -- that is annoying when the user has more than a small number of Ventoy pages open.

**Comment by ventoy** [comment]
I have updated the pages, now they have different titles.

**Comment by noyannus** [comment]
That's really helpful. Thank you!
