### ISSUE TITLE
Timeout with autoselect hangs a

### ISSUE THREAD

**Issue by noyannus** [ventoy/Ventoy#684]
A boot after timeout with a set persistence autoselect does not auto-boot. It stops and displays the selection menu for "without persistence" or a persistence file. These are the settings:
```
		{ "VTOY_MENU_TIMEOUT": "10" },
		{ "VTOY_DEFAULT_IMAGE": "/images/linuxmint-20-cinnamon-64bit.iso" }
```
```
		{
			"image": "/images/linuxmint-20-cinnamon-64bit.iso",
			"backend": "/persistence-files/linuxmint-20-cinnamon-64bit.dat",
			"autosel": "1"
		}
```
Boot starts OK after manually hitting enter with persistence file selected, so I guess it is a Ventoy issue.

**Comment by ventoy** [comment]
I test with this ventoy.json
```
{	
	"control": [
		{ "VTOY_MENU_TIMEOUT": "3" },
        { "VTOY_DEFAULT_IMAGE": "/Linux/ubuntu-20.04-desktop-amd64.iso" }
	],
	
	"persistence" :
	[
		{
			"image": "/Linux/ubuntu-20.04-desktop-amd64.iso",
            "backend": "/persistence_ext4_1GB_casper-rw.dat"
			"autosel": 1
		}
	]
}
```
It's OK, it directly boot to ubuntu after 3 seconds. If I delete `autosel` line, it will stop at the select menu.

Please give your full ventoy.json file.

**Comment by ventoy** [comment]
`autosel` is an integer, NOT a string.
So you should set  `"autosel": 1`

**Comment by noyannus** [comment]
> So it is "autosel": 1 not "autosel": "1"

THAT was the problem. Fixed. Thank you!

**Comment by kalligator** [comment]
Is it possible to inherit the timeout behavior?
As it stands now if we use timeout & autoselect set to "backend" we don't get a (timeout) choice to select the plain "image", it goes straight to "backend".
