### ISSUE TITLE
显示俩iso

### ISSUE THREAD

**Issue by SHEN-MI** [ventoy/Ventoy#685]
放了一个iso，显示两个iso，上面正常使用，下面显示
![Uploading IMG_20210104_210351.jpg…]()
![Uploading IMG_20210104_210349.jpg…]()
![Uploading IMG_20210104_210346.jpg…]()

**Comment by a1ive** [comment]
图裂了

**Comment by SHEN-MI** [comment]
> 图裂了

![IMG_20210104_210351](https://user-images.githubusercontent.com/76948746/103542263-a948fc80-4ed7-11eb-9f7e-1af38db7aa7e.jpg)
![IMG_20210104_210349](https://user-images.githubusercontent.com/76948746/103542268-ab12c000-4ed7-11eb-9d42-a07a4c531217.jpg)
![Uploading IMG_20210104_210346.jpg…]()

**Comment by ventoy** [comment]
还是看不到图片，你可以多截几张图发我邮箱。 admin@ventoy.net

**Comment by SHEN-MI** [comment]
> 还是看不到图片，你可以多截几张图发我邮箱。 [admin@ventoy.net](mailto:admin@ventoy.net)

发了老哥

**Comment by ventoy** [comment]
没收到呢? 附件太大了？

**Comment by SHEN-MI** [comment]
> 没收到呢? 附件太大了？

又用qq邮箱发了个，老哥你看看

**Comment by ventoy** [comment]
你显示2个ISO的图截一个看看。包括U盘根目录的截图。
另外，在Ventoy启动界面，按 `c` 进入命令行，执行  
```
ls -l $vtoy_iso_part/
```
看看

**Comment by SHEN-MI** [comment]
> 你显示2个ISO的图截一个看看。包括U盘根目录的截图。
> 另外，在Ventoy启动界面，按 `c` 进入命令行，执行
> 
> ```
> ls -l $vtoy_iso_part/
> ```
> 
> 看看


> 你显示2个ISO的图截一个看看。包括U盘根目录的截图。
> 另外，在Ventoy启动界面，按 `c` 进入命令行，执行
> 
> ```
> ls -l $vtoy_iso_part/
> ```
> 
> 看看

暂时没法截老哥，明天截给你

**Comment by SHEN-MI** [comment]
> 你显示2个ISO的图截一个看看。包括U盘根目录的截图。
> 另外，在Ventoy启动界面，按 `c` 进入命令行，执行
> 
> ```
> ls -l $vtoy_iso_part/
> ```
> 
> 看看
![IMG_20210106_172758](https://user-images.githubusercontent.com/76948746/103753897-90128e00-5046-11eb-86a0-e581fe2392d8.jpg)
老哥那个第一个iso也用不了，显示这个
![IMG_20210106_173922](https://user-images.githubusercontent.com/76948746/103753881-8ab54380-5046-11eb-87ff-dade115010cc.jpg)
然后我做了俩u盘，另一个只显示一个iso，但是也显示了第一个u盘的第二个iso的那个
![IMG_20210104_210349](https://user-images.githubusercontent.com/76948746/103753928-9d2f7d00-5046-11eb-967e-d8fb7f04141d.jpg)

**Comment by ventoy** [comment]
1. 使用最新的 1.0.32 版本重做U盘。
2. ISO文件拷贝到U盘上之后，校验一下U盘中的文件，防止拷贝过程中出错

**Comment by SHEN-MI** [comment]
> 1. 使用最新的 1.0.32 版本重做U盘。
> 2. ISO文件拷贝到U盘上之后，校验一下U盘中的文件，防止拷贝过程中出错

明天试试，谢谢～

**Comment by SHEN-MI** [comment]
> 1. 使用最新的 1.0.32 版本重做U盘。
> 2. ISO文件拷贝到U盘上之后，校验一下U盘中的文件，防止拷贝过程中出错

iso文件是Ubuntu.com官网下的检测sha256正常，ventoy是蓝奏云下的检验sha256正常。安装ventoy把iso复制进去检测sha256正常，但是拔了之后啥也没干重插再检测一遍就不正常了
![IMG_20210107_204240](https://user-images.githubusercontent.com/76948746/103894112-6716f980-5129-11eb-8772-60698222c5f9.jpg)
是我的问题吗，两个u盘都这样，用的系统是也是Ubuntu，刚安装的什么也没下。u盘目录是一个iso文件夹一个test文件夹，iso文件放在iso文件夹里的。然后test文件夹下是另一个test文件夹，然后这个test文件夹下是一个空的server文件夹，一个空的client文件夹，我之前出问题的目录就是这样的所以想还原下试试，里面啥也没放就是几个空文件夹。有事所以没来得及试u盘只放iso文件会怎么样。


> 1. 使用最新的 1.0.32 版本重做U盘。
> 2. ISO文件拷贝到U盘上之后，校验一下U盘中的文件，防止拷贝过程中出错

> 1. 使用最新的 1.0.32 版本重做U盘。
> 2. ISO文件拷贝到U盘上之后，校验一下U盘中的文件，防止拷贝过程中出错

iso文件是Ubuntu.com官网下的检测sha256正常，ventoy是蓝奏云下的检验sha256正常。安装ventoy把iso复制进去检测sha256正常，但是拔了之后啥也没干重插再检测一遍就不正常了
![IMG_20210107_204240](https://user-images.githubusercontent.com/76948746/103895247-0dafca00-512b-11eb-8654-16d714a0dcec.jpg)
两个u盘都这样，用的系统是也是Ubuntu，刚安装的什么也没下。u盘目录是一个iso文件夹一个test文件夹，iso文件放在iso文件夹里的。然后test文件夹下是另一个test文件夹，然后这个test文件夹下是一个空的server文件夹，一个空的client文件夹，我之前出问题的目录就是这样的所以想还原下试试，里面啥也没放就是几个空文件夹。有事所以没来得及试u盘只放iso文件会怎么样。实在想不出哪里有问题所以又只能来请教下了。。。

**Comment by ventoy** [comment]
你拷贝ISO文件到U盘之后，再校验U盘的ISO文件，这时候是对的。
但是这个时候不代表文件就真正写到U盘里面去了。只是你看着是写完了，但是可能还是有部分数据还是在系统的缓存里面。
你拷贝完之后，在终端执行如下两个命令：
```
sync
poweroff
```
这样等关机之后再拔出U盘来应该就没问题了。(正常只要执行了 sync 命令一般就没问题了，poweroff 关机只是更保险一些）

**Comment by SHEN-MI** [comment]
> 你拷贝ISO文件到U盘之后，再校验U盘的ISO文件，这时候是对的。
> 但是这个时候不代表文件就真正写到U盘里面去了。只是你看着是写完了，但是可能还是有部分数据还是在系统的缓存里面。
> 你拷贝完之后，在终端执行如下两个命令：
> 
> ```
> sync
> poweroff
> ```
> 
> 这样等关机之后再拔出U盘来应该就没问题了。(正常只要执行了 sync 命令一般就没问题了，poweroff 关机只是更保险一些）
> 
> 另外，Ubuntu上应该也有类似Windows上面右键弹出U盘的操作。使用这个操作之后再拔盘应该也不会有问题。
> 总之，使用U盘都要避免直接拔盘，要使用安全的操作。

弄好了谢谢～
