### ISSUE TITLE
Ventoy + DriveDroid

### ISSUE THREAD

**Issue by namazso** [ventoy/Ventoy#688]
Hi!

There is an app called DriveDroid for rooted Android devices that lets you mount arbitrary files as mass storage (or as DVD drive, however support for that in kernels is rare).
As you probably know, mounting a Windows installer iso as mass storage does not work. It would be great if there was a way to use Ventoy to start up a Windows installer from DriveDroid, preferably going something like this:

1. Mount a Ventoy image
2. Boot it on the machine
3. Mount the Windows installer iso (this removes the Ventoy image)
4. Boot it up with Ventoy

I understand this isn't really the original goal of the project, but it could be useful for many.

**Comment by ventoy** [comment]
As you said, this isn't really the original goal of Ventoy. I have no more time to do this, sorry!

**Comment by ufgf** [comment]
I recently checked the possibility of installing on the mounted DriveDroid image on the Ventoy 1.0.64, it works 👍

**Comment by rust2** [comment]
What??? You can create 3,95gib (FAT32) img on your android, then burn windows ISO via rufus. No need for Ventoy here

**Comment by ufgf** [comment]
> What??? You can create 3,95gib (FAT32) img on your android, then burn windows ISO via rufus. No need for Ventoy here

In fact, it's true - you can just copy the image and mount it in DriveDroid, but someone likes to work with (physically) one image using, for example, Ventoy.
In other words, everyone decides for himself how to use DriveDroid 🙃

**Comment by bighamx** [comment]
> I recently checked the possibility of installing on the mounted DriveDroid image on the Ventoy 1.0.64, it's possible and it works 👍

May i know how to install ventoy into a drivedroid virtual USB image? thanks

**Comment by namazso** [comment]
You make an appropriately sized null filled file, mount it with DriveDroid, then use the Ventoy installer on the computer

This issue was for making this whole process less cumbersome, but apparently only I mind this

**Comment by rust2** [comment]
> You make an appropriately sized null filled file
Not less than 64mb, if you wanna store only Ventoy there
