### ISSUE TITLE
build is not building  ia32 efi files

### ISSUE THREAD

**Issue by steve6375** [ventoy/Ventoy#690]
Does GRUB2\buildgrub.sh need up dating?
maybe other build files too for new architectures?

**Comment by ventoy** [comment]
I have update this script for ia32.
Other files are in checking.

**Comment by steve6375** [comment]
That builds  the  EFI\boot file but
/ventoy/ventoy_ia32.efi  is not updating.

**Comment by steve6375** [comment]
Great! Thanks.
