### ISSUE TITLE
usb pen drive not accessible, cant be mounted

### ISSUE THREAD

**Issue by z3huti** [ventoy/Ventoy#691]
When booting any linux distro from ventoy pen drive. That pen drive is not accessible, cant be mounted, in booted linux distro. Please fix that.

**Comment by ventoy** [comment]
Please refer #667

**Comment by ventoy** [comment]
The latest Ventoy 1.0.64  provides an experimental option  `VTOY_LINUX_REMOUNT` which can help to access the ISO partition after boot.
