### ISSUE TITLE
Ventoy makes my system unbootable

### ISSUE THREAD

**Issue by nkuttler** [ventoy/Ventoy#692]
I have only tested this on a Dell laptop so far, but every time I boot the Ventoy USB stick my internal drive becomes unbootable, it looks like the MBR might get overwritten. I need to use supergrub loaded from ventoy to boot the OS on the internal disk and install grub again by hand. I'm using version 1.0.31. I can try more things to debug this but am unsure what.

**Comment by nkuttler** [comment]
I tried on a different laptop and there the problem does not exist. Could be BIOS vs EFI, unsure, will update when I know more.

**Comment by ventoy** [comment]
OK. I will close the issue first. You can reopen it if needed.
