### ISSUE TITLE
issue with clear-34000-live-desktop.iso

### ISSUE THREAD

**Issue by skulldealer** [ventoy/Ventoy#694]
unable to figure out issue with clear-34000-live-desktop.iso

other linux distributions are working fine with ventoy.

error
fatal failed to find installer media, retries exhausted, failed to boot clear linux.

note-
not using any themes. ventoy.json is very standard.
please add support for clear linux

**Comment by ventoy** [comment]
I can't reproduce the problem. I test clear-34000-live-desktop.iso and it boot fine.
Maybe you can test with another computer or another USB stick for comparison

**Comment by steve6375** [comment]
Uefi64?

**Comment by skulldealer** [comment]
able to boot with balena etcher on same machine. try preserving space and do not format that space. secure boot enabled
[my json.zip](https://github.com/ventoy/Ventoy/files/5802991/my.json.zip)

**Comment by ventoy** [comment]
If you finally dropped into a shell, please run 2 commands and send me the output.
```
cat /ventoy/log
blkid
```
