### ISSUE TITLE
Found an iso that don't boot in Ventoy

### ISSUE THREAD

**Issue by mooms06** [ventoy/Ventoy#697]
https://www.touslesdrivers.com/index.php?v_page=23&v_code=65175

It's a bootable iso to update Micron SSD. Probably based on Linux. It boot fine with Rufus

**Comment by ventoy** [comment]
I download it  1300_revM5MU30_bootable_media_update.iso with  `md5sum 1390f11a981d41c5c1190c9911c0c36a`
This iso file has some problem itself. If you test it with a VirtualMachine(e.g. VMWare/VirtualBox) you will find that it boot fail.

Ventoy create a VirtualCD device based on the ISO file and it just like you burn it to a CD/DVD and boot it from a CDROM.
Rufus just extract the ISO file to the USB and it just like you boot from USB.
So they have different internal mechanisms.

**Comment by mooms06** [comment]
I see, thanks.
So the image will not work if burned, but only with an utility like Rufus, ironic !

**Comment by ventoy** [comment]
NO.
That not means you can't boot it from Ventoy. But you need some more work.
Let me tell you how to do that:

1. copy the iso file 1300_revM5MU30_bootable_media_update.iso  to the root of the Ventoy USB stick (no parent directory)
2. get the attachment `ventoy.zip`  and decompress it to the root of Ventoy USB stick (There will be a `\ventoy\ventoy_grub.cfg` file)
3. When you boot into Ventoy's menu, press F6 and select `Boot Micron Firmware Updater`

[ventoy.zip](https://github.com/ventoy/Ventoy/files/5809922/ventoy.zip)

**Comment by mooms06** [comment]
Thanks for the answer and for offering a solution, but as I've said, I've used Rufus so there is no need to use it anymore.
Have a nice day.
