### ISSUE TITLE
Kickstart instructions

### ISSUE THREAD

**Issue by rderooy** [ventoy/Ventoy#699]
Unfortunately, the RedHat Anaconda installer does not support autodetecting the installation source when using a kickstart file.

As such, since there is no mention of this in the Ventoy documentation, and after trying for 30min to get it to work, I just thought I would share my experience.

To get a kickstart automated installation to work, you need to have something like the following installation source in your kickstart file:

```
harddrive --partition=sdb2 --dir=/
```

Obviously, the exact source partition can change. This is on a system which had a local SATA disk (sda), so the USB stick was designated sdb. If you have multiple SATA or SAS disks, it could end up being sdc, sde, sdf, etc. If you have only NVME devices, the usb stick will be sda instead.
The best way to find out which device you need to use, is to boot the installer without kickstart file, and see what the installation source is set for.

This was tested with CentOS 8.3, and the Ventoy partition was formatted exFAT (which CentOS8 does not natively support).

**Comment by ventoy** [comment]
This is a kickstart template which is tested with CentOS 8.3
```
install

lang en_US.UTF-8
keyboard us
rootpw  123456
firewall --service=ssh
authconfig --enableshadow --passalgo=sha512
selinux --disable
timezone --utc Asia/Shanghai

eula --agreed
firstboot --disable

url --url=file:///run/install/repo

%include /tmp/partation.ks
zerombr
autopart --type=plain


#packages configuration
%packages
@core
%end

reboot

%pre

#You can set to sdb/sdc depends on some conditions...
disk_short_name=sda

echo bootloader --location=mbr --driveorder=$disk_short_name >> /tmp/partation.ks
echo ignoredisk --only-use=$disk_short_name  >> /tmp/partation.ks
echo clearpart --all --initlabel --drives=$disk_short_name  >> /tmp/partation.ks

%end
```

**Comment by rderooy** [comment]
Interesting... perhaps something to add to the documentation.

**Comment by ventoy** [comment]
I have put some sample script in the website.
Does this sample kickstart work OK? Can I close the issue now?

**Comment by rderooy** [comment]
I did not try your, I have my own kickstart script specific to the system. But your ``url`` trick worked and took out at least one variable.
