### ISSUE TITLE
Ventoy boots to grub prompt (Asus Eee PC 900)

### ISSUE THREAD

**Issue by Massedil** [ventoy/Ventoy#706]
Hello,

I have well read [doc_legacy_limit.html](https://www.ventoy.net/en/doc_legacy_limit.html), but my USB key is 8Go.

1. Can I still boot one of my ISO in grub prompt ? If yes, how ?

I have also seen #323, #318 and #161.

- [Asus Eee PC 900](https://en.wikipedia.org/wiki/Asus_Eee_PC#Eee_900_series). 
- I imagine it is Legacy BIOS.
- 8Go USB key :

```
Périphérique Amorçage    Début      Fin Secteurs Taille Id Type
/dev/sdd1    *            2048 15581183 15579136   7,4G  7 HPFS/NTFS/exFAT
/dev/sdd2             15581184 15646719    65536    32M ef EFI (FAT-12/16/32)
```
- Ventoy 1.0.32 :

```
$ sudo ./Ventoy2Disk.sh -l /dev/sdd

**********************************************
      Ventoy: 1.0.32  x86_64
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

Ventoy Version: NA
```

2. Do you have a workaround or something I can do boot Ventoy on this device ? I'm available to help, but I will have this computer only this week.

**Comment by steve6375** [comment]
Do you mean that you cannot boot to the Ventoy menu system?
I have an Asus eePC 904HA  and a 32Gb USB Flash drive
It boots to the Ventoy menu OK.
Does it boot on other systems?
Did you switch off first?
Did you try both USB ports (switch off first - then on - then press ESC - then select USB drive).

**Comment by Massedil** [comment]
> Do you mean that you cannot boot to the Ventoy menu system?

No, I can't, I have this screen :

![](https://user-images.githubusercontent.com/28628331/87788487-cb46b800-c880-11ea-9f66-5820bd4e3af1.png)

> Does it boot on other systems?

Yes, more than 10 different computers until now (thanks !) ! With no problem. (Except one time I had this grub prompt boot problem but, not sure to well remember the solution, I think I solved it by moving the USB key from an USB3 port to an USB2 port.

> Did you switch off first?

Switch off what ? The computer ? Yes !

> Did you try both USB ports (switch off first - then on - then press ESC - then select USB drive).

I have 3 USB ports, I tried 2, I will try the third one.

Before I : 
- Change the bios to boot on usb first
- Let as it is the strange option saying "OS Installation [Finished]" 

Then, I : 
- switch off the computer
- plug in the USB key
- switch on the computer
- See the grub prompt

**Comment by ventoy** [comment]
Please refer:  #695  and  #689  and to check whether your USB has some hardware problem.

**Comment by steve6375** [comment]
Do you have any options in bios to boot as USB: HDD . 
If you have grub prompt, type
ls
What do you see?

**Comment by Massedil** [comment]
I managed to screenshot this error in the boot process that disappears quickly (sorry for the poor quality, but it is extracted from a movie) : 

![1](https://user-images.githubusercontent.com/20357783/105059788-ef759280-5a77-11eb-8703-4f91ed704a0e.png)

Looks like : `error : file : '/ventoy/ventoy.disk.img.img' not found.`.

I also remember that it is the first time I use the version 1.0.32 of Ventoy and the first time I have updated the Ventoy binary from Linux (all time before I updated it from Windows). Can it be linked ?

I will try if the problem occurs from another computer.

**Comment by ventoy** [comment]
```
$ sudo ./Ventoy2Disk.sh -l /dev/sdd

**********************************************
      Ventoy: 1.0.32  x86_64
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

Ventoy Version: NA
```
This means the data in `/dev/sdd2` was corrupted.
You can run `xzcat ./ventoy/ventoy.disk.img.xz | dd of=/dev/sdd2 conv=fsync` to repair it.

**Comment by Massedil** [comment]
Hum, same problem now with this key on another PC.
I seems that the last upgrade from Linux instead of Windows changed something...

> You can run xzcat ./ventoy/ventoy.disk.img.xz | dd of=/dev/sdd2 conv=fsync to repair it.

I'll try it. Thanks.

> If you have grub prompt, type
> ls
> What do you see?

```
(proc) (hd0)(hd0,msdos2)(hd0,msdos1)(hd1)(hd1,msdos2)(hd1,msdos1)
```

**Comment by Massedil** [comment]
Ok. So... Strange !

Before :

```
$ sudo ./Ventoy2Disk.sh -l /dev/sdd

**********************************************
      Ventoy: 1.0.32  x86_64
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

Ventoy Version: NA
```
Then :

```
$ xzcat ./ventoy/ventoy.disk.img.xz | sudo dd of=/dev/sdd2 conv=fsync
65536+0 enregistrements lus
65536+0 enregistrements écrits
33554432 octets (34 MB, 32 MiB) copiés, 11,4573 s, 2,9 MB/s
$ sudo ./Ventoy2Disk.sh -l /dev/sdd

**********************************************
      Ventoy: 1.0.32  x86_64
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

Ventoy Version in Disk: 1.0.32
Disk Partition Style  : MBR
Secure Boot Support   : YES
$ sudo ./Ventoy2Disk.sh -l /dev/sdd

**********************************************
      Ventoy: 1.0.32  x86_64
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

Ventoy Version in Disk: 1.0.32
Disk Partition Style  : MBR
Secure Boot Support   : YES
```

Then I put off the USB key and put on again on my computer : 

```
$ sudo ./Ventoy2Disk.sh -l /dev/sdd

**********************************************
      Ventoy: 1.0.32  x86_64
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

Ventoy Version in Disk: 1.0.32
Disk Partition Style  : MBR
Secure Boot Support   : YES
```

Then I put the USB key into the Asus EEE PC 900, and the grub problem occurs again.

Then, I put the USB key on my computer : 

```
$ sudo ./Ventoy2Disk.sh -l /dev/sdd

**********************************************
      Ventoy: 1.0.32  x86_64
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

Ventoy Version: NA
```

TODO : 
- I will test on another computer (one I'm sure I works before)
- I will test your md5sum test to see if it is a hardware problem

**Comment by Massedil** [comment]
USB hardware test seems fine :

```
$ xzcat ./ventoy/ventoy.disk.img.xz > write.img
$ dd if=./write.img  of=/dev/sdd2 conv=fsync
dd: impossible d'ouvrir '/dev/sdd2': Permission non accordée
$ sudo dd if=./write.img  of=/dev/sdd2 conv=fsync
65536+0 enregistrements lus
65536+0 enregistrements écrits
33554432 octets (34 MB, 32 MiB) copiés, 6,47479 s, 5,2 MB/s
$ dd if=/dev/sdd2 of=read.img
dd: impossible d'ouvrir '/dev/sdd2': Permission non accordée
$ sudo dd if=/dev/sdd2 of=read.img
65536+0 enregistrements lus
65536+0 enregistrements écrits
33554432 octets (34 MB, 32 MiB) copiés, 1,24353 s, 27,0 MB/s
$ md5sum write.img
6ec2819546cc738228e1696916f3f92c  write.img
$ md5sum read.img
6ec2819546cc738228e1696916f3f92c  read.img
```

But I catch a strange thing that occured when I wanted to check the version `rm: impossible de supprimer './tmpmntp2': Périphérique ou ressource occupé` :

```
$ sudo ./Ventoy2Disk.sh -l /dev/sdd

**********************************************
      Ventoy: 1.0.32  x86_64
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

Ventoy Version in Disk: 1.0.32
Disk Partition Style  : MBR
Secure Boot Support   : YES
rm: impossible de supprimer './tmpmntp2': Périphérique ou ressource occupé
```

Immediately after the error message :

```
$ sudo ./Ventoy2Disk.sh -l /dev/sdd

**********************************************
      Ventoy: 1.0.32  x86_64
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

Ventoy Version: NA
```

Do you understand what happens ?

**Comment by Massedil** [comment]
So. Here I am.

I reinstalled Ventoy to the USB key with : 

```
$ sudo ./Ventoy2Disk.sh -u /dev/sdd

**********************************************
      Ventoy: 1.0.32  x86_64
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

Upgrade operation is safe, all the data in the 1st partition (iso files and other) will be unchanged!

Update Ventoy  1.0.32 ===> 1.0.32   Continue? (y/n)y

Update Ventoy to /dev/sdd successfully finished.
```

No tmp mount problem after that.

After that, I tested the USB key with my MSI PC (Legacy mode) and Ventoy boots normally : I saw the ISO choice screen.

After that I tested the USB key with the Asus EEE 900 PC and Ventoy failed to boot : I saw the grub screen.

After that I checked the Ventoy version on my main xUbuntu computer with : 

```
$ sudo ./Ventoy2Disk.sh -l /dev/sdd

**********************************************
      Ventoy: 1.0.32  x86_64
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

Ventoy Version: NA
```

What do you think ?

**Comment by Massedil** [comment]
New test. 

I used the same USB key, just putted it on my Windows computer, clicked on the update button to downgrade from 1.0.32 to 1.0.24.

I works on the EEE PC 900 : I see the Ventoy ISO screen and I successfully booted xUbuntu 20.04 ISO.

I don't know if it is solved by Windows or by 1.0.24.

Let me know what do you want I test to better understand what happens.

**Comment by ventoy** [comment]
Maybe the same with #703   you can update the shell script and retry.

**Comment by Massedil** [comment]
> Maybe the same with #703 you can update the shell script and retry.

Test just done : 

1. Updated to Ventoy `1.0.32` from **Windows** and it still works on the Asus EEE PC 900 : I can see the Ventoy interface with the ISO list.
2. Updated to Ventoy `1.0.33` from **Linux** (it contains your fix) and it still works on the Asus EEE PC 900 : I can see the Ventoy interface with the ISO list.

**Comment by webberian** [comment]
For others coming to this thread with similar problems and the Grub command line, I was able to work around this problem by disabling secure boot (`-S`) and using GPT instead of MBR (`-g`).
