### ISSUE TITLE
期望支持 OpenWrt 的 img 格式镜像

### ISSUE THREAD

**Issue by L-sizhong** [ventoy/Ventoy#71]
当前不支持 OpenWrt 的 img 格式镜像，期望能够支持。

OpenWrt 下载地址：https://downloads.openwrt.org/releases/19.07.2/targets/x86/64/

**Comment by ventoy** [comment]
当前ventoy只支持iso格式， 你可以看看有没有办法可以转换为ISO文件

**Comment by blackcrack** [comment]
please try to hold the internet language, i am a german, i could write in German..
and Ventoy should work in both languages to hold it equal..
oder sollten wir kein Standard einhalten ?
Ich kann gern nur in Deutsch schreiben .. 

Danke, Thank you..

best regards
Blacky

**Comment by luzeagithub** [comment]
@blackcrack German is definitely not a standard language. Also bitte auf Englisch hier.

**Comment by adaaaaaa** [comment]
@ventoy 
期望支持 OpenWrt 的 img 格式
什么时候能支持这种格式啊？？

**Comment by ventoy** [comment]
@L-sizhong @adaaaaaa 
最新的 1.0.41 版本支持 OpenWrt IMG文件。参考 https://www.ventoy.net/cn/doc_openwrt.html
