### ISSUE TITLE
请问如何修改MENU界面左下角版本信息字体颜色和位置？

### ISSUE THREAD

**Issue by freenaser** [ventoy/Ventoy#716]
您好！我更换了主题，需要调整一下版本信息字体颜色和位置，是否可以通过theme.txt来进行修改？如果可以参数该如何配置呢？

**Comment by ventoy** [comment]
需要在 ventoy.json 文件里设置，如下(#ff0000 代表红色）：
```
{
    "theme": {
        "file": "/ventoy/theme/blur/theme.txt",       
        "ventoy_color": "#ff0000"
    }
}
```

**Comment by freenaser** [comment]
> 
> 
> 不能通过 theme.txt修改，需要在 ventoy.json 文件里设置，如下(#ff0000 代表红色）：
> 
> ```
> {
>     "theme": {
>         "file": "/ventoy/theme/xxxxxxx/theme.txt",       
>         "ventoy_color": "#ff0000",
>         "ventoy_left": "5%",
>         "ventoy_top": "95%"
>     }
> }
> ```
> 
> 官网文档由说明： https://www.ventoy.net/cn/plugin_theme.html

感谢您的指点！
此前我曾尝试1.运行主题包内自带安装脚本来进行主题加载，显示“done”运行成功，但重启后依旧是原主题；2.用Diskgenius尝试替换“VTOYEFI”下“themes”中的“background”图片。均未实现主题更换。请问是针对“VTOYEFI”的写保护机制作用原因么？是否可以通过工具直接修改该启动盘内的文件内容呢？

**Comment by ventoy** [comment]
1. 主题内的安装脚本安装后更新的是你本地硬盘上主系统里的grub主题，对ventoy一点用都没有。
2. 替换图片理论上是可以的。我不知道你有没有真正替换掉。

最简单的，Ventoy的安装包解压后里面有一个 plugin\ventoy 目录，你把这个 ventoy 目录直接拷贝到U盘里（拷贝到那个放ISO文件的大分区里，不是32MB的VTOYEFI分区里。只拷这个 ventoy目录，不要带着外面的plugin目录）。 然后重启就会看到主题改掉。 这是一个简单的示例，你可以再换里面的图片。

**Comment by freenaser** [comment]
> 
> 
>     1. 主题内的安装脚本安装后更新的是你本地硬盘上主系统里的grub主题，对ventoy一点用都没有。
> 
>     2. 替换图片理论上是可以的。我不知道你有没有真正替换掉。
> 
> 
> 最简单的，Ventoy的安装包解压后里面有一个 plugin\ventoy 目录，你把这个 ventoy 目录直接拷贝到U盘里（拷贝到那个放ISO文件的大分区里，不是32MB的VTOYEFI分区里。只拷这个 ventoy目录，不要带着外面的plugin目录）。 然后重启就会看到主题改掉。 这是一个简单的示例，你可以再换里面的图片。

感谢释疑！此问题已解决。
