### ISSUE TITLE
WINPE启动镜像加载失败

### ISSUE THREAD

**Issue by freenaser** [ventoy/Ventoy#718]
RT.国外软件公司开发的一款基于WINPE启动的64bit维护工具盘，Ventoy可以识别并启动该镜像，直到屏幕左上角出现“Press any key to boot from CD or DVD”。但此时按键无法进入WINPE操作界面（无反应），左上角文字闪烁2-3次以后自动返回Ventoy Menu界面。可再次选择该镜像，但现象依旧。
该WINPE镜像用任意版本VMWARE虚拟机均可成功加载，故判断引导不成功的原因应是基于Ventoy，如有需要可提供镜像文件供分析。

**Comment by ventoy** [comment]
你同一个环境下，测试个标准的 windows 10 镜像，看看是不是这个地方也是有同样按键无效的问题。

**Comment by freenaser** [comment]
> 
> 
> 你同一个环境下，测试个标准的 windows 10 镜像，看看是不是这个地方也是有同样按键无效的问题。

我常用引导镜像有20个左右，涵盖WIN，LINUX，使用Ventoy引导均无问题。上述WINPE遇到的问题是头一次碰到，曾怀疑过是文件名或镜像本身的问题，但后期通过测试都一一排除了，最终指向Ventoy。

**Comment by ventoy** [comment]
你同样的环境下，启动标准Windows 10镜像也会显示 `Press any key to boot from CD or DVD`    这时就没问题？

**Comment by freenaser** [comment]
> 
> 
> 你同样的环境下，启动标准Windows 10镜像也会显示 `Press any key to boot from CD or DVD` 这时就没问题？

对，WIN10直接按任意键正常进入镜像安装界面。

**Comment by ventoy** [comment]
你是UEFI模式吧。 Windows 10 镜像正常应该是你不按键它也会自动进去。

**Comment by freenaser** [comment]
> 
> 
> 你是UEFI模式吧。 Windows 10 镜像正常应该是你不按键它也会自动进去。

对，UEFI。屏幕出现提示我才按，所以只能用legacy？此镜像的上一版用Ventoy引导还正常。

**Comment by ventoy** [comment]
那你对比看看这个镜像前后两个版本有什么区别。
Ventoy启动镜像是模拟一个光驱来启动。
所以Ventoy启动相当于你把这个ISO文件刻录到一个空白的DVD光盘上，然后电脑上插一个USB光驱，启动这个光盘，这种情况下可能也会有这个问题。

你直接虚拟机上测试或者刻录到U盘上测试，都和Ventoy启动的环境是不一样的。所以不出问题很正常。

另外解释下，什么时候才会打印这句提示？  只有启动时它检测到你本地硬盘里面还有其他系统时他才会显示。如果你本地硬盘没有系统，就不会显示。所以你创建一个新的虚拟机，它本地没有系统，启动时它不会打印这句提示。

**Comment by freenaser** [comment]
> 
> 
> 那你对比看看这个镜像前后两个版本有什么区别。
> Ventoy启动镜像是模拟一个光驱来启动。
> 所以Ventoy启动相当于你把这个ISO文件刻录到一个空白的DVD光盘上，然后电脑上插一个USB光驱，启动这个光盘，这种情况下可能也会有这个问题。
> 
> 你直接虚拟机上测试或者刻录到U盘上测试，都和Ventoy启动的环境是不一样的。所以不出问题很正常。
> 
> 另外解释下，什么时候才会打印这句提示？ 只有启动时它检测到你本地硬盘里面还有其他系统时他才会显示。如果你本地硬盘没有系统，就不会显示。所以你创建一个新的虚拟机，它本地没有系统，启动时它不会打印这句提示。

可以理解为不同的引导镜像需要不同的引导环境么？有些启动镜像无法通过ventoy启动的原因是因为不支持虚拟光驱启动？

**Comment by ventoy** [comment]
也可以这么说吧。 我只是想说，如果你把这个ISO文件刻录到一个空白的DVD光盘上，然后电脑上插一个USB光驱，然后启动这个光盘。如果这种情况有问题，Ventoy也有问题。那就不是Ventoy的问题。 如果前者没问题，Ventoy有问题，那就是Ventoy的问题。

**Comment by freenaser** [comment]
> 
> 
> 也可以这么说吧。 我只是想说，如果你把这个ISO文件刻录到一个空白的DVD光盘上，然后电脑上插一个USB光驱，然后启动这个光盘。如果这种情况有问题，Ventoy也有问题。那就不是Ventoy的问题。 如果前者没问题，Ventoy有问题，那就是Ventoy的问题。

好的，明天盘到我测试后给您反馈。

**Comment by ventoy** [comment]
另外，你有没有在其他电脑上测试过这个ISO文件？ 或者你可以把这个ISO共享给我测试一下。

**Comment by freenaser** [comment]
> 
> 
> 另外，你有没有在其他电脑上测试过这个ISO文件？ 或者你可以把这个ISO共享给我测试一下。

我手上有台新款工控机，跑了一下，情况和我笔记本上一样。卡在boot...返回主界面。如何发送给你，邮箱或者其他方式我发网盘链接过去。

**Comment by ventoy** [comment]
网盘共享吧 在2021年01月23日 21:17，freenaser 写道： 

另外，你有没有在其他电脑上测试过这个ISO文件？ 或者你可以把这个ISO共享给我测试一下。

我手上有台新款工控机，跑了一下，情况和我笔记本上一样。卡在boot...返回主界面。如何发送给你，邮箱或者其他方式我发网盘链接过去。

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ventoy/Ventoy/issues/718#issuecomment-766020459",
"url": "https://github.com/ventoy/Ventoy/issues/718#issuecomment-766020459",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by freenaser** [comment]
> 
> 网盘共享吧 在2021年01月23日 21:17，freenaser 写道： 另外，你有没有在其他电脑上测试过这个ISO文件？ 或者你可以把这个ISO共享给我测试一下。 我手上有台新款工控机，跑了一下，情况和我笔记本上一样。卡在boot...返回主界面。如何发送给你，邮箱或者其他方式我发网盘链接过去。 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[#718 (comment)](https://github.com/ventoy/Ventoy/issues/718#issuecomment-766020459)", "url": "[#718 (comment)](https://github.com/ventoy/Ventoy/issues/718#issuecomment-766020459)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

下载链接，取件码已发送至邮箱。

**Comment by ventoy** [comment]
```
Active.Boot.Disk.17.0.WINPE.ISO:   md5:  b2e92e2fc62d8b40722c3761885b7989
```

这个ISO文件我使用VMware/VirtualBox直接挂载上都是无法启动，打印出这句提示之后按键也无效，最后返回了。

**Comment by freenaser** [comment]
[cid:f62b51b4-61f1-4a44-b4a2-3fa19352ab98]
________________________________
发件人: longpanda <notifications@github.com>
发送时间: 2021年1月24日 8:50
收件人: ventoy/Ventoy <Ventoy@noreply.github.com>
抄送: freenaser <pengye2008@live.com>; Author <author@noreply.github.com>
主题: Re: [ventoy/Ventoy] WINPE启动镜像加载失败 (#718)


Active.Boot.Disk.17.0.WINPE.ISO:   md5:  b2e92e2fc62d8b40722c3761885b7989



这个ISO文件我使用VMware/VirtualBox直接挂载上都是无法启动，打印出这句提示之后按键也无效，最后返回了。

―

**Comment by freenaser** [comment]
> 
> 
> ```
> Active.Boot.Disk.17.0.WINPE.ISO:   md5:  b2e92e2fc62d8b40722c3761885b7989
> ```
> 
> 这个ISO文件我使用VMware/VirtualBox直接挂载上都是无法启动，打印出这句提示之后按键也无效，最后返回了。

VMWARE加载镜像的视频已录制发送至邮箱，另反馈一下光盘刻录后的运行情况，和V下加载情况一致。

**Comment by ventoy** [comment]
你视频里Vmware是在 Legacy BIOS模式下启动的。你需要切换到 UEFI 模式下测试。这个问题是出在 UEFI 模式下，你电脑是在UEFI模式下。 你光盘刻录在电脑上也是一样的问题。所以我觉得是你这个ISO文件的问题，它在UEFI模式下启动本身就有问题。因为不管是在VMware/VirtualBox还是通过Ventoy在你电脑上、还是刻录到光盘在你电脑上，只要是UEFI模式下，就无法启动。

**Comment by ventoy** [comment]
你也可以把你的电脑在BIOS里面切换成Legacy模式，然后再用Ventoy测试看看。

VMWare怎么切换模式，电脑怎么切换模式，这些网上都能查到。

**Comment by freenaser** [comment]
> 
> 
> 你也可以把你的电脑在BIOS里面切换成Legacy模式，然后再用Ventoy测试看看。
> 
> VMWare怎么切换模式，电脑怎么切换模式，这些网上都能查到。

VMWARE切换到UEFI模式后会出现和最初问题描述中一样的情况。工控机会直接跳出Grub命令符界面。

**Comment by freenaser** [comment]
> 
> 
> 你视频里Vmware是在 Legacy BIOS模式下启动的。你需要切换到 UEFI 模式下测试。这个问题是出在 UEFI 模式下，你电脑是在UEFI模式下。 你光盘刻录在电脑上也是一样的问题。所以我觉得是你这个ISO文件的问题，它在UEFI模式下启动本身就有问题。因为不管是在VMware/VirtualBox还是通过Ventoy在你电脑上、还是刻录到光盘在你电脑上，只要是UEFI模式下，就无法启动。

是的，实践可以印证你的推论，所以这个case可以关了。
