### ISSUE TITLE
vDisk versus ISO + persistence performance

### ISSUE THREAD

**Issue by matfeb** [ventoy/Ventoy#719]
Hi,

can you tell me if it's better to have a fixed size vdisk or a live iso with persistency in terms of performance ?

You explained that VDI was like having the system booting on the whole platfom, accessing the hardware as if the system was installed on the peripheral where the vdi is. 
About the ISO file, if I'm right, the ISO file is loaded inside the RAM only if memdisk is used and so the OS is running on the peripheral as well ?

Last question, is there any limitation to use the persistency such as a volume limit or a consistency problem ?

Please enlighten me :)

**Comment by ventoy** [comment]
When you use ISO + persistence mode (no matter memdisk mode or not). All the system is running in the RAM. So it has a better performance.  vdisk is just like you run a system from the physical disk.

There is no limitation in volume limit for persistence. 
There is no special consistency problem for persistence. Of course you need to reboot/poweroff in normal way and to avoid abnormal poweroff.

ISO+Persistence has some other limatitions, for example:
1. You can't update kernel and some drivers
2. You can't update grub configfile/theme...
3. You even can't install softwares in some distros.
......

In my opinion, ISO+Persistence is for lightweight and temporary use or just for experience.

**Comment by matfeb** [comment]
Thank you for your crystal clear answer.
