### ISSUE TITLE
Ubuntu gives error in Ventoy?

### ISSUE THREAD

**Issue by aretsmarvin** [ventoy/Ventoy#72]
Ubuntu 20 and 19 give the same error.

It shows up in the Ventoy menu. Then you see the Ubuntu logo loading. And then it gives the following error:

`
BusyBox v1.30.1 (Ubuntu 1:1.30.1-4ubuntu4) built-in shell (ash)
Enter 'help' for a list of built-in commands.

(initramfs) Unable to find a medium containing a live file system.
`

Then I can enter some basic Linux commands, but installer is not showing up.

Edit: Ventoy 1.0.08
Ubuntu: ubuntu-19.10-desktop-amd64.iso & ubuntu-20.04-desktop-amd64.iso

**Comment by ventoy** [comment]
Hi, 
Please help to run two commands in the basic linux shell and give a photo of the output, thanks:
`blkid`
`cat /ventoy/log`

**Comment by wahibre** [comment]
same message with elementaryOS:  

```
(initramfs) blkid
/dev/sda1: LABEL="ventoy" UUID="C704-558F" TYPE="exfat" PTTYPE="dos" PARTUUID="9edd9cf8-01"
/dev/sda2: SEC_TYPE="msdos" LABEL="EFI" UUID="2723-4627" TYPE="vfat" PARTUUID="9edd9cf8-02"
/dev/sdb1: UUID="0870b44e-0c4b-40ac-97a8-cdfa56888485" TYPE="ext4" PARTUUID="c8d38348-01"
/dev/sdb2: UUID="479de71f-d0fa-45c0-ac24-8a5194c11fbb" TYPE="swap" PARTUUID="c8d38348-02"
/dev/sdb3: LABEL="fedora" UUID="d55e6453-1997-4cab-be7e-fc1d50191486" UUID_SUB="ce20b8aa-5208-4914-b52f-b476092de0a5" TYPE="btrfs" PARTUUID="c8d38348-03"
```

```
(initramfs) cat /ventoy/log
============== VENTOY =================
274 blocks
5724 blocks
kenel version=Linux version 5.3.0-51-generic (buildd@lgw01-amd64-018) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020
kenel cmdline=BOOT_IMAGE=/casper/vmlinuz boot=casper maybe-ubiquity quiet splash initrd=/casper/initrd.lz
=====ventoy_unpack_initramfs: #/initrd001 0 3037 /initrd001_tmp#
vtx=3037 cat
62 blocks
=====ventoy_unpack_initramfs: #/initrd001 436 3037 /initrd001_tmp#
vtx=3037 cat
5784 blocks
=====ventoy_unpack_initramfs: #/initrd001 212 1F8B /initrd001_tmp#
vtx=1F8B zcat
364560 blocks
Now hand over to ventoy.sh
#### install vtoytool #####
try /ventoy/tool/vtoytool/00/ ...
vtoytool_64 OK
use vtoy_fuse_iso_64
use unsquashfs_64
use unsquashfs_64
kernel version
Linux version 5.3.0-51-generic (buildd@lgw01-amd64-018) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020
OS=###debian###
##### distribution = default ######
Here before mountroot ...
####### /ventoy/hook/debian/disk_mount_hook.sh  ########
wait_for_usb_disk_ready /dev/sda ...
wait_for_usb_disk_ready /dev/sda finish
```

I tried other distros (fedora, zorinos, slax, ubuntu, ...) and same issue - starts booting and then breaks into TTY with initramfs in prompt and message like "could not find / load data...".

**Comment by aretsmarvin** [comment]
> Hi,
> Please help to run two commands in the basic linux shell and give a photo of the output, thanks:
> `blkid`
> `cat /ventoy/log`

Sorry for the late response. The issue is still ongoing. (even created a clean ventoy usb with newest version .11). See photo below. 

![IMG_20200527_111340](https://user-images.githubusercontent.com/45003967/83000970-605ccb80-a00b-11ea-9905-f9a7f31cb0b4.jpg)

**Comment by markspo** [comment]
I am receiving the same messages on a HP Folio 9470m

**Comment by TDGalea** [comment]
Also receiving this issue. Tested with KDE Neon, Lubuntu, all three variants of Mint.

**Comment by wahibre** [comment]
I found only one iso working on my HP ProBook - MX Linux.  
I have no idea what is different in MX Linux.  
Is there anything I can help with? Maybe enable debug messages?




|		ISO file   						| 	Works on HP ProBook 6440b? | 
|------------------------------------|:-----------:|
|elementaryos-5.1-stable.20200501.iso <br> Fedora-Xfce-Live-x86_64-32-1.6.iso <br> **focal-desktop-20.04-amd64.iso**<br> linuxmint-20-mate-64bit.iso <br> slax-64bit-9.11.0.iso	 <br> Solus-4.0-Budgie.iso <br> Zorin-OS-15.1-Lite-64-bit-r1.iso <br> manjaro-xfce-20.0.1-200511-linux56.iso |	No		|
|MX-19.1_x64.iso						| Yes	|

**Comment by fjen** [comment]
Please try booting in UEFI mode. After switching to UEFI mode on an HP Probook 6570, the following images were booting successfully:

- debian-10.4.0-amd64-netinst.iso
- ubuntu-18.04.4-desktop-amd64.iso
- ubuntu-20.04-desktop-amd64.iso
- pmagic_2020_05_20.iso
- gparted-live-1.1.0-1-amd64.iso
- linuxmint-19.3-cinnamon-64bit.iso
- systemrescuecd-amd64-6.1.4.iso

**Comment by wahibre** [comment]
Ubuntu (and many others) works In UEFI mode.

**Comment by ivanristic** [comment]
This issue should be closed, and another opened. "Ventoy doesn't work in legacy mode on HP"?
