### ISSUE TITLE
Crucial SSD Firmware ISO does not start

### ISSUE THREAD

**Issue by git70** [ventoy/Ventoy#723]
Can I ask you to check why this iso is not working?
1. https://www.crucial.com/content/dam/crucial/support/firmware/MX500_M3CR033.zip
2. https://content.crucial.com/content/dam/crucial/support/firmware/MX300_M0CR070_Firmware_Update.zip

ISO booting up but getting "Could not find kernel image: / boot / vmlinuz64"

However, it works fine:
https://content.crucial.com/content/dam/crucial/support/firmware/MX200_MU05_Update.zip

**Comment by ventoy** [comment]
Maybe the two ISO files have some problem themselves. I boot them directly in a VM and get the same error.
This is the test result:

ISO File | VMware | Ventoy
-|-|-
MX500_M3CR033.iso|Legacy Fail<br>UEFI Fail|Legacy Fail<br>UEFI Fail
MX300_M0CR070_Firmware_Update.iso|Legacy Fail<br>UEFI OK|Legacy Fail<br>UEFI OK

**Comment by git70** [comment]
Can I ask you to look inside this ISO?
I am too weak :(

**Comment by ventoy** [comment]
1. Update Ventoy to the latest 1.0.34
2. Download the file `a.txt` in the attachment and rename it to `MX500_M3CR033.iso.vcfg` and put it in the same place as the ISO file. 
3. Download the file `a.txt` in the attachment and rename it to `MX300_M0CR070_Firmware_Update.iso.vcfg` and put it in the same place as the ISO file. 
4. Retry

**Comment by ventoy** [comment]
Does that works?

**Comment by git70** [comment]
It works!
Thank you very much!!!
I am shocked why a large and respected manufacturer cannot properly make software for their products :(

PS: Sorry for the long response time (I was sick).
Best Regards!
