### ISSUE TITLE
Ubuntu 20.10 tries to install assuming you are sing UEFI even if you are using Legacy boot

### ISSUE THREAD

**Issue by SViN24** [ventoy/Ventoy#724]
Hardware tested on: Thinkpad T440s

**Comment by ventoy** [comment]
Ventoy does support both Legacy BIOS mode and UEFI mode.
But it's the BIOS firmware not Ventoy that decide to boot in Legacy BIOS mode or UEFI mode.

When you boot into Ventoy's boot menu. There is a version messages shown in the bottom left.
If it shows `1.0.33 BIOS www.ventoy.net` that means this time Ventoy was booted in Legacy BIOS mode by the BIOS firmware.
If it shows `1.0.33 UEFI www.ventoy.net` that means this time Ventoy was booted in UEFI mode by the BIOS firmware.

**Comment by SViN24** [comment]
it does say bios
However after testing the same images on a virtualmachine i may have found out the issue.
I think this issue has more to do with ubuntu making changes to the installer. 

loading the ubuntu 20.10 iso on virtualbox i found it behaved the same way. So i think this is a case of Ventoy working correctly and this being an ubuntu bug.

**Comment by ventoy** [comment]
This is an old issue. I will close it now.
If you still have problem with latest Ventoy release, you can reopen the issue.
