### ISSUE TITLE
Slax linux distribution not work

### ISSUE THREAD

**Issue by Ayad0net** [ventoy/Ventoy#725]
Sadly I test the Slax linux operating system x64 & x86 but it not works.

**Comment by ventoy** [comment]
Please give the ISO file name and download link.

**Comment by Ayad0net** [comment]
Linux ISO Website: https://www.slax.org/


Slax 64bit | 9.11.0 | [slax-64bit-9.11.0.iso](http://ftp.sh.cvut.cz/slax/Slax-9.x/slax-64bit-9.11.0.iso) | 
Slax 32bit | 9.11.0 | [slax-32bit-9.11.0.iso](http://ftp.sh.cvut.cz/slax/Slax-9.x/slax-32bit-9.11.0.iso) | 

Thanks ventoy ^_^

**Comment by ventoy** [comment]
You can try this CI build release after it completed: https://github.com/ventoy/Ventoy/actions/runs/531346694

**Comment by Ayad0net** [comment]
Awesome, worked perfectly on both version x86 & x64 without any issues. Thanks 👍

**Comment by Samuel88** [comment]
Same with new slax iso

Slax 32bit | 12.2.0 | [slax-32bit-debian-12.2.0.iso](http://ftp.sh.cvut.cz/slax/Slax-12.x/slax-32bit-debian-12.2.0.iso) |
Slax 64bit | 12.2.0 | [slax-64bit-debian-12.2.0.iso](http://ftp.sh.cvut.cz/slax/Slax-12.x/slax-64bit-debian-12.2.0.iso) |

**Comment by eltrevii** [comment]
@ventoy please
