### ISSUE TITLE
Update ComputerName in Unattend.xml

### ISSUE THREAD

**Issue by AdamKearn** [ventoy/Ventoy#727]
Hi,

Just wondering if you could make a small plugin that would ask for user input before booting a windows image.
And Ventoy will update the answer file with the values.

Then we can provide things dynamic values such as the ComputerName etc into our answer files.

**Comment by steve6375** [comment]
You can already add a grub cfg file as plugin to ventoy.
Easy2boot agFM contains a sample cfg file which does exactly what you want, but I don't know if the same code would work under ventoy grub2.

**Comment by ventoy** [comment]
There is a principle always complied in Ventoy: will never write anything to the disk. 
So Ventoy works even if the USB stick is write protected.

You can use `injection plugin` to inject a bat script. So your work will become: `how to modify a string in a xml file by bat script`.
You can refer: #696

**Comment by AdamKearn** [comment]
@ventoy  that's understandable I can see why you wouldn't want ventoy to make modifications.
@steve6375  I had a look at that config file but I wasn't able to modify it for my needs.

I found a solution to my problem by using the inject plugin to add some extra config files into the WinPE image.
For anyone else that is trying to achieve the same thing as me, I'll attach my files below to save you some time.

**ventoy.json**
```
{
  "auto_install": [
    {
       "image": "/images/microsoft/Win10_20H2_English_x64.iso",
       "template": [
         "/images/microsoft/unattended/autounattend.xml"
       ]
     }
  ],
   "injection": [
     {
       "image": "/images/microsoft/Win10_20H2_English_x64.iso",
       "archive": "/scripts/wim_mod.zip"
     }
   ]
}
```
Inside the `win_mod.zip` archive I added these files.  Note that the `.ini` file is in `Windows/System32/` and not on the root of the zip file.
Download for SED (which is used to make the modifications to the .XML file):  http://gnuwin32.sourceforge.net/packages/sed.htm

**win_mod.zip/Windows/System32/winpeshl.ini**
```
[LaunchApps]
%SYSTEMDRIVE%\prompt.bat
%SYSTEMDRIVE%\Windows\system32\startnet.cmd
%SYSTEMDRIVE%\Windows\system32\setlw.exe
%SYSTEMDRIVE%\Sources\setup.exe
```
**win_mod.zip/prompt.bat**
```
@echo off

if not exist "X:\Autounattend.xml" (GOTO EOF)

:START
cls
mode con:cols=60 lines=15

echo ============================================================
echo               Pre-Windows Install Questions
echo ============================================================
echo.
echo The computer name must be less than 15 characters
set /p PCNAME= Set a computer name:

echo.
set /p enable_account=Remove Aspentech Account? (Y/[N]):
IF /I "%enable_account%"=="Y" (GOTO REMOVEACCOUNT) else (GOTO EDIT)

:REMOVEACCOUNT
echo.
echo Removing Aspentech account from Answer File...

:EDIT
X:\sed.exe -i "s/<ComputerName><\/ComputerName>/<ComputerName>%PCNAME%<\/ComputerName>/" X:\Autounattend.xml

:EOF
```

The end result looks something like this:
![image](https://user-images.githubusercontent.com/30593259/106944924-19d57a00-671f-11eb-98eb-6fd5d0c5e2ae.png)

**Comment by ventoy** [comment]
@AdamKearn 
Ventoy 1.0.77 release with support for variables expansion in auto installation script.
https://www.ventoy.net/en/plugin_autoinstall.html#auto_install_var_expand

**Comment by AdamKearn** [comment]
> @AdamKearn
> Ventoy 1.0.77 release with support for variables expansion in auto installation script.
> https://www.ventoy.net/en/plugin_autoinstall.html#auto_install_var_expand

Hi @ventoy 

Thanks for adding this feature… I’m going to add this into my config right away.

Thanks again for continuing to update your amazing project.

**Comment by publicarray** [comment]
> if not exist "X:\Autounattend.xml" (GOTO EOF)

FYI The file is now called "X:\_ventoy_auto_install" but I will migrate to the variables expansion soon.
