### ISSUE TITLE
Support Lenovo BIOS Update CD

### ISSUE THREAD

**Issue by alucard856** [ventoy/Ventoy#729]
Hi,

is it possible to supporting the BIOS Update ISO?
It would be great for non Windows User.

https://pcsupport.lenovo.com/de/de/products/laptops-and-netbooks/thinkpad-x-series-laptops/thinkpad-x260/downloads/ds105890

**Comment by ventoy** [comment]
Please try this CI build release:
https://github.com/ventoy/Ventoy/actions/runs/531227108

**Comment by alucard856** [comment]
It works perfeklty :+1: 

A huge thank you.

**Comment by LANopop** [comment]
trying to update lenovo e14 gen 2 ([r1auj47wd.iso](https://download.lenovo.com/pccbbs/mobiles/r1euj56wd.iso)) , booting the bios ios via ventoy works, but i see this error when i try to start the bios update
![signal-2023-11-08-134234](https://github.com/ventoy/Ventoy/assets/2630216/e187de3f-e3f7-42d4-8f57-ed1a417bb4bf)
