### ISSUE TITLE
Ventoy2Disk.exe -U后选择本地硬盘分区X，会把整个硬盘都格式化？

### ISSUE THREAD

**Issue by GoGoogle** [ventoy/Ventoy#735]
Rt，我看了看常见问题，没看懂。
通过命令行 Ventoy2Disk.exe -U 来启动
我选择分区X，它会把这个分区所在的整个磁盘都重新分区并格式化？

`需要特别注意的是，不管安装在U盘还是硬盘，都会重新分区、格式化，整个盘的数据都会被清除，请慎重操作。`

**Comment by a1ive** [comment]
会的。

**Comment by GoGoogle** [comment]
> 会的。

那么我的疑问就来了。
一，如果安装在当前系统所在磁盘的话，它能安装成功？
二，根据这个逻辑，如果要安装在本地磁盘系统里面的话是否需要准备两个磁盘硬件才行？

**Comment by ventoy** [comment]
1. 不会成功，操作系统会阻止你格式化当前系统所在的磁盘。
2. Ventoy需要单独占用一个物理磁盘。如果你想装在本地磁盘系统里。有两种情况，如果你当前的这个系统还想留着，则只能再插一块物理磁盘。如果你当前的系统不想要了，那么你直接在这个系统下安装不行。但是可以用过其他方式安装，比如你先启动一个PE，在PE里面运行安装程序来安装，或者使用VentoyLiveCD来安装。这时候相当于在一个运行在内存里的系统中安装，此时本地硬盘就相当于一个普通磁盘了，操作就没问题了。

**Comment by GoGoogle** [comment]
> 1. 不会成功，操作系统会阻止你格式化当前系统所在的磁盘。
> 2. Ventoy需要单独占用一个物理磁盘。如果你想装在本地磁盘系统里。有两种情况，如果你当前的这个系统还想留着，则只能再插一块物理磁盘。如果你当前的系统不想要了，那么你直接在这个系统下安装不行。但是可以用过其他方式安装，比如你先启动一个PE，在PE里面运行安装程序来安装，或者使用VentoyLiveCD来安装。这时候相当于在一个运行在内存里的系统中安装，此时本地硬盘就相当于一个普通磁盘了，操作就没问题了。

大概明白了，谢谢。
那么这样一来，仍旧还不能一键脱离优盘启动的束缚，独立磁盘安装并想保留当前系统是做不到了。

**Comment by ventoy** [comment]
是的，这一代Ventoy的设计已经定型了，就是和物理磁盘、分区结构强绑定在一个整体方案里的。

**Comment by blackcrack** [comment]
@ventoy Longpanda,
hmmm... i have take a translator and have read it... 

it is possible ?, if take there a include like in php and css
to include a post-configuraton grub.cfg on the normal space where is the iso's 
for add extra boot commands for extra bootentry's to boot with UID from the partitions or ID from the harddisk
to the possible for extra commands in the grub.cfg .. this could maybe make possible
for boot a 2nd partition on the usb(part3)(swap4thpart) for boot a Technical Linux partition from the usb with special tools
or a install WinNT on the usbstick/harddisk and move the whole with Minitool Partitions Manager backward,
and in the place on the first free place it is then space for ventoy with 2 partitions.. on the extfad with the images, could then 
create a grub.cfg where included in the grub-menu and ready for selecting.. this 2nd "addon"/included - grub.cfg could generated from hand and able to by read in .. before the extfsread in via array is readed out from the extfs 2 partition..

the including could be really easy.. if exist the file grub.cfg at the 2nd partiton , include it/then read or is exit not, go to the next step.
i guess need only 2-3 lines to realisation this "grub.cfg addon" file at/for the 2nd partition
this give more possibility's at hand to more technical geek's ;) if there a possibility to add a manual boot option with a manual create grub.cfg ... who be included in the Ventoy-boot Menu automagically, therewith could it also possible for create a usb3 special External USB Harddisk ..
In Ventoy must only able to set up the space who it is take by creating Ventoy-space with 2 partitons,
the update of the Ventoy is like it was before .. usb3-harddisk plug in, ventoy checks the usb, find Ventoy Software and update it..

this is only a suggestion/idea how it could work.. but if you whant hold Ventoy like it is.. also okey.. 
i love it in any case ;) ...  I definitely love them and see how many work and support is in it :+1: :kissing_heart:

best
Blacky

**Comment by ventoy** [comment]
> @ventoy Longpanda,
> hmmm... i have take a translator and have read it...
> 
> it is possible ?, if take there a include like in php and css
> to include a post-configuraton grub.cfg on the normal space where is the iso's
> for add extra boot commands for extra bootentry's to boot with UID from the partitions or ID from the harddisk
> to the possible for extra commands in the grub.cfg .. this could maybe make possible
> for boot a 2nd partition on the usb(part3)(swap4thpart) for boot a Technical Linux partition from the usb with special tools
> or a install WinNT on the usbstick/harddisk and move the whole with Minitool Partitions Manager backward,
> and in the place on the first free place it is then space for ventoy with 2 partitions.. on the extfad with the images, could then
> create a grub.cfg where included in the grub-menu and ready for selecting.. this 2nd "addon"/included - grub.cfg could generated from hand and able to by read in .. before the extfsread in via array is readed out from the extfs 2 partition..
> 
> the including could be really easy.. if exist the file grub.cfg at the 2nd partiton , include it/then read or is exit not, go to the next step.
> i guess need only 2-3 lines to realisation this "grub.cfg addon" file at/for the 2nd partition
> this give more possibility's at hand to more technical geek's ;) if there a possibility to add a manual boot option with a manual create grub.cfg ... who be included in the Ventoy-boot Menu automagically, therewith could it also possible for create a usb3 special External USB Harddisk ..
> In Ventoy must only able to set up the free space who it is take by creating Ventoy-space with 2 partitons, by Creating the Ventoyspace .. USB-Drive+FreeSpace / USB-Drive+... ? pulldown
> the update of the Ventoy is like it was before .. usb3-harddisk plug in, ventoy checks the usb, find Ventoy Software and update it..
> 
> this is only a suggestion/idea how it could work.. but if you whant hold Ventoy like it is.. also okey..
> i love it in any case ;) ... I definitely love them and see how many work and support is in it  
> 
> best
> Blacky

Do you mean something like this: https://www.ventoy.net/en/plugin_grubmenu.html
