### ISSUE TITLE
ventoy no funciona con una memoria usb kingston dtse9  32gb ajo ayuda por favor 

### ISSUE THREAD

**Issue by edwincaleropardo** [ventoy/Ventoy#737]
ventoy no funciona con una memoria usb kingston dtse9  32gb ajo
sale este error si se corre desde maquina virtual MobaLiveCD_v2.1 
![error de ventoy](https://user-images.githubusercontent.com/71736997/107003250-73a76580-675a-11eb-9e2e-c78a2f20eda1.jpg)

gmu grub version 2.04
Minimal bash - like line editing is supported. For the first word, tab lists possible command completions. Anywhere else tab lists possible device or file completions.
grub>

ayuda por favor para que funcione desde mi usb kingston dtse9  32gb ajo
y desde menu de boot la usb no carga memoria usb kingston dtse9  32gb ajo con ventoy

**Comment by ventoy** [comment]
Do you have the same problem when you test in real machine? (not QEMU)

**Comment by motorhead4** [comment]
Hola, a mi me sucede lo mismo, formatie la unidad usb kingnston de 32gb, borré las particiones, lo formatie en fat3, ntfs, exfat, y me aparece el mismo error.
Tendrá algo que ver con la marca y modelo.
Hay que hacerlo con algna marca y modelo específico?
Espero puedan resolverlo ya que sería de mucha utilidad.
Saludos desde Argentina!

**Comment by 8tm** [comment]
I have the same error using Ventoy 1.0.46 (ventoy-1.0.46-linux.tar.gz)

Installed from Linux Debian 11.0 (bullseye) on SanDisk Extreme PRO 256 GB

https://i.ibb.co/jW0spNQ/IMG-20210708-231813.jpg

**Comment by steve6375** [comment]
Some BIOSes have a 128GiB limit - for these Ptn1+Ptn2 < 128GiB
Some BIOSes have an 8GiB limit - for these Ptn1+Ptn2 < 8GiB
Ventoy could test by reading last sector at the end of Ptn2 and if error warn user that BIOS has bug (if it manages to boot to the files on Ptn2 first!).

**Comment by motorhead4** [comment]
Thanks!
