### ISSUE TITLE
Not running in Windows 10.

### ISSUE THREAD

**Issue by elitearmedforce** [ventoy/Ventoy#74]
I am a new user of Ventoy. Learned about it from a youtube video. 
I just downloaded it in Windows 10. Ran it for the first time, and it failed with no warning dialog box. Later, I will test it in Ubuntu 18.04.

![image](https://user-images.githubusercontent.com/61043834/81457961-4583fd80-91a9-11ea-8a69-4793f621f169.png)

**Comment by ventoy** [comment]
Hi,
You can't run Ventoy2Disk.exe in the source tree(INSTALL directory), you should download the released install package, decompress it, and run there.

There is a small error in this video. That's why I put a `DO_NOT_RUN_Ventoy2Disk_HERE.txt` file in the directory :)

**Comment by elitearmedforce** [comment]
Sorry, I didn't get it in beginning. Figured it out. Thank you
