### ISSUE TITLE
Problem booting manjaro iso with USB flash drive using gpt scheme created in linux version of Ventoy

### ISSUE THREAD

**Issue by Majo111** [ventoy/Ventoy#740]
Hi,
I have a problem booting manjaro iso with USB flash drive that was created in linux version of Ventoy with gpt scheme. An error message pops up: No bootfile found for UEFI. But there is no problem in Windows version of Ventoy. Manjaro iso will boot without problem.

**Comment by AlienProber** [comment]
Really shouldn't be using anything but the default.

```
Download latest Ventoy
 
 Extract it to it's own folder
 
 Open it's folder
 
 Open Konsole or whichever terminal you're using in Ventoy's folder
 
 Enter the below command replacing x in sdcx with the actual letter of your drive
 
 sudo sh Ventoy2Disk.sh -I /dev/sdx
 
 follow the onscreen instrustions and install Ventoy to your flashdrive

May need to do a reboot before you can copy ISOs to it.
```

**Comment by ventoy** [comment]
> Hi,
> I have a problem booting manjaro iso with USB flash drive that was created in linux version of Ventoy with gpt scheme. An error message pops up: No bootfile found for UEFI. But there is no problem in Windows version of Ventoy. Manjaro iso will boot without problem.

1. Does other iso file boot ok in the same linux gpt USB key? (e.g.  Ubutu/Arch/CentOS...)
2. Check the manjaro iso file in the USB key again to make sure that the file is not corrupted.
3. Do you mean the same USB key in Windows version of GPT style work OK with the same manjaro iso file?

**Comment by Majo111** [comment]
1. I tried Ubuntu instead for Manjaro. The same problem. It shows only terminal line. 
2. I have the same manjaro iso on another USB flash drive, which is created in ventoys windows version. And there is no problem with gpt table. Manjaro is booting without problem.
3. Yes. Exactly. I tried it.

**Comment by ventoy** [comment]
1. Which version of Ventoy did you use to install the linux gpt USB key
2. Please retry with a fresh install with latest 1.0.35
3. Is the same iso file boot ok if you use default MBR style  in linux?
4. Better with some photos

**Comment by Majo111** [comment]
1. First time it was 1.0.34 version from AUR repositories and than I updated USB flash drive to 1.0.35 version.
2. I tried it. Unfortunately, it doesn't help me. I have another problem with version 1.0.35 in linux. I don't have permission to write on USB with gpt table created in Ventoy. There is information, that I am not owner of disc.
3. Yes, with MBR table boot all iso files without problem.
4. I took some photos. Excuse me quality of some shots. But this photos are still readable. 
![Ventoy boot menu](https://user-images.githubusercontent.com/31368840/107362111-9e861680-6ad8-11eb-994c-a64fc0530dbd.jpg)
![Successful boot of Ubuntu from Ventoy USB drive with MBR table](https://user-images.githubusercontent.com/31368840/107362115-9fb74380-6ad8-11eb-9429-c46d4b53b250.jpg)
![Successful boot of Manjaro from Ventoy USB drive with MBR table](https://user-images.githubusercontent.com/31368840/107362119-a0e87080-6ad8-11eb-96af-2665b6bf2343.jpg)
![After booting Ubuntu from Ventoy USB drive with gpt table](https://user-images.githubusercontent.com/31368840/107362121-a1810700-6ad8-11eb-8c56-a5fe27667b98.jpg)
![Error after booting Manjaro from Ventoy USB drive with gpt table](https://user-images.githubusercontent.com/31368840/107362122-a2199d80-6ad8-11eb-9c64-2dccb77bd02b.jpg)

**Comment by Majo111** [comment]
1. First time it was 1.0.34 version from AUR repositories and than I updated USB flash drive to 1.0.35 version.
2. I tried it. Unfortunately, it doesn't help me. I have another problem with version 1.0.35 in linux. I don't have permission to write on USB with gpt table created in Ventoy. There is information, that I am not owner of disc.
3. Yes, with MBR table boot all iso files without problem.
4. I took some photos. Excuse me quality of some shots. But this photos are still readable. 
![Ventoy boot menu](https://user-images.githubusercontent.com/31368840/107362111-9e861680-6ad8-11eb-994c-a64fc0530dbd.jpg)
![Successful boot of Ubuntu from Ventoy USB drive with MBR table](https://user-images.githubusercontent.com/31368840/107362115-9fb74380-6ad8-11eb-9429-c46d4b53b250.jpg)
![Successful boot of Manjaro from Ventoy USB drive with MBR table](https://user-images.githubusercontent.com/31368840/107362119-a0e87080-6ad8-11eb-96af-2665b6bf2343.jpg)
![After booting Ubuntu from Ventoy USB drive with gpt table](https://user-images.githubusercontent.com/31368840/107362121-a1810700-6ad8-11eb-8c56-a5fe27667b98.jpg)
![Error after booting Manjaro from Ventoy USB drive with gpt table](https://user-images.githubusercontent.com/31368840/107362122-a2199d80-6ad8-11eb-9c64-2dccb77bd02b.jpg)

**Comment by Majo111** [comment]
Update:
Everything works as It should. Problem is probably in copying files (corrupted iso). After copy files, Nautilus still do something with flash drive. I have to wait until this process end and than I can remove USB drive. But thanks a lot for your help.
