### ISSUE TITLE
Is it possible to disable the file system detection prompt for VHD(X) boot? （能不能禁用VHD(X)启动的文件系统的检测弹窗？）

### ISSUE THREAD

**Issue by ZhuMa12345678** [ventoy/Ventoy#745]
English (英语) 
The problem of exFAT+VHD(X) booting Windows has long been resolved: 
http://bbs.wuyou.net/forum.php?mod=viewthread&tid=414354&mobile=no
Every time you use Ventoy to select a boot virtual hard disk file, you have to press the Enter key one more time, which is too troublesome. 
![截图20210210233327](https://user-images.githubusercontent.com/61312109/107538705-38e07a00-6bff-11eb-8447-7b972de44582.jpg)
![截图20210210233337](https://user-images.githubusercontent.com/61312109/107538741-4138b500-6bff-11eb-897f-f868f0cc30e1.jpg)
![截图20200819030248](https://user-images.githubusercontent.com/61312109/107538790-4b5ab380-6bff-11eb-9d98-210f574b0311.jpg)
It is recommended to add a system version detection mechanism, and it will be passed directly if the boot conditions are met. 

汉语 (Chinese) 
exFAT+VHD(X)启动Windows都是早就已经解决的问题： 
http://bbs.wuyou.net/forum.php?mod=viewthread&tid=414354&mobile=no
每次用Ventoy选择引导虚拟硬盘文件，都得要多按一次回车键也太麻烦了。 
![截图20210210233327](https://user-images.githubusercontent.com/61312109/107538816-50b7fe00-6bff-11eb-85c3-ce7a17189376.jpg)
![截图20210210233337](https://user-images.githubusercontent.com/61312109/107538824-531a5800-6bff-11eb-9afd-816f3098cfaa.jpg)
![截图20190505123743](https://user-images.githubusercontent.com/61312109/107538826-54e41b80-6bff-11eb-88ce-9eca04e7d63a.jpg)
建议加一个系统版本检测机制，符合启动条件的直接判定通过。

**Comment by ZhuMa12345678** [comment]
For Chinese users who are slow to open GitHub, click this link to view:
对于中国用户打开GitHub很慢的可点击此链接查看：
http://bbs.wuyou.net/forum.php?mod=redirect&goto=findpost&ptid=419840&pid=4237953&fromuid=566366&mobile=no

**Comment by ventoy** [comment]
自动检测功能还没有。不过在全局控制插件中有一个开关 `VTOY_VHD_NO_WARNING`，可以把这个告警关掉。请参考
https://www.ventoy.net/cn/plugin_control.html
