### ISSUE TITLE
文件系统错误

### ISSUE THREAD

**Issue by IanGoo** [ventoy/Ventoy#75]
我制作了一个启动盘，然后用它启动了一次，再进Windows插上这个U盘的时候会提示文件系统有错误。100%复现。但是扫一下又没有发现什么文件损坏。

环境：

Chipfancier SLC 32GB U盘，一个Windows 10 1909专业版，一个Manjaro 20，U盘里装了一个Windows 10 1909和Manjaro 20和wepe 64的ISO。

**Comment by IanGoo** [comment]
Ventoy版本是07更新到的08

**Comment by ventoy** [comment]
我暂时没有遇到这类错误，你可以对比测试下，比如更新和重新制作有无差别， 另外在Windows系统上制作和Linux系统下制作有无差别。 另外，启动的这次是Windows系统还是Linux系统有无差别。

**Comment by ventoy** [comment]
新版本已经支持 NTFS 文件系统，你可以手动把第一个分区格式化为NTFS格式试试。
此ISSUE先关闭，如果还有问题可以新提issue.
