### ISSUE TITLE
Menu Class Plugin - Add Undocumented Built-in Classes

### ISSUE THREAD

**Issue by thewarden** [ventoy/Ventoy#750]
Hello, I've discovered that the documentation for Menu Class Plugin located at https://ventoy.net/en/plugin_menuclass.html has a few undocumented built-in classes.

Please add the following built-in classes to the documentation.

- debug_krdlayout
- debug_kbd
- custom
- custom_sub
- custom2

**Comment by ventoy** [comment]
I update the page for debug_krdlayout and debug_kbd.
custom/custom_sub/custom2  are just examples for ventoy_grub.cfg. 
The whole ventoy_grub.cfg is not built-in part of Ventoy. It's provided by the user if they want to use this feature.
So there is no need for documentation fot them.

**Comment by thewarden** [comment]
Thanks for documenting. Ahh I thought that maybe the case but I wasn't certain.
