### ISSUE TITLE
Black Screen after choosing any ISO on MacBookPro a1278 (late 2011)

### ISSUE THREAD

**Issue by JOduMonT** [ventoy/Ventoy#752]
Hi;

Ventoy work well with my Asus Zenbook u305ua but not with my MacBookPro a1278 (late 2011).

- On the Asus it boot and I'm able to choose and run any of those ISO
- On the MacBookPro, Ventoy boot but after choosing the machine stuck on a black screen, [like described in this post](https://forums.ventoy.net/showthread.php?tid=1291&highlight=black+screen)

Ventoy as been installed with EFI from **Ubuntu 20.04LTS** (which is installed on both machine the MacBookPro and the Asus as **single and unique OS** and both with EFI)

And the ISO I put at the root of the second partition of my USB are:

- clonezilla-live-20210127-groovy-amd64.iso
- gparted-live-1.2.0-1-amd64.iso
- grml64-full_2020.06.iso
- kali-linux-2020.4-installer-netinst-amd64.iso
- kubuntu-20.04.2.0-desktop-amd64.iso
- proxmox-ve_6.3-1.iso

which all boot individually on both machine if I dd them on the same USB.

The USB key is a Kingston_DataTraveler_3.0 16GB.

_PS: I would replied in the forum but I never received the email to confirm my account._

**Comment by ventoy** [comment]
Do you test with **vtdebug on**  as descripted in the post?
PS: The forum account is actived manully. So now your account should be OK.

**Comment by mdl052020** [comment]
Friend you can use Opencore Bootloader with Ventoy & then test with your mac . it worked flawlessly on my side.
Just Go Through Dortania Guide for macOS Opencore Bootloader [Non Hacknitosh]

**Comment by JOduMonT** [comment]
@mdl052020 thanks but this mac don't use MacOS since 2012, anyway, it was more by curiosity, at the end using 2 USB Key is cheaper and faster than passing more hours on that :)
