### ISSUE TITLE
Grub load ISO from HDD(NTFS) fail

### ISSUE THREAD

**Issue by sonichy** [ventoy/Ventoy#756]
I am trying to use grub to load ISO from HDD(NTFS).
sudo gedit /etc/grub.d/40_custom, add:
```
menuentry "ubuntu 16" {
    set isofile="/ISO/ubuntu-16.04.7-desktop-amd64.iso" 
    loopback loop (hd0,5)$isofile
    linux (loop)/casper/vmlinuz boot=casper
    initrd (loop)/casper/initrd
}
```
sudo update-grub
Reboot, choose ubuntu 16:
```
......
stdin: Not a typewriter
stdin: Not a typewriter
stdin: Not a typewriter
stdin: Not a typewriter
stdin: Not a typewriter
stdin: Not a typewriter
......
Unable to find a medium container a live file system
```

**Comment by ventoy** [comment]
It's just as expected. Boot from an iso file is not so simple as you thought.
The loopback device is only exist in grub period and will not exist after the kernel boot.
So the system will not find the install medium.

Actually, this is what Ventoy solved.

**Comment by sonichy** [comment]
So, if Ventoy can remember path can boot from iso from HDD ?

**Comment by ventoy** [comment]
Not so simple. It's a lot of work.
Even we can tell the system that "hey, the install medium is an iso file, it's path is `/ISO/xxx.iso`  in /dev/sdb1."
The system will find that /dev/sdb1 is in NTFS filesystem, and the system currently doesn't support to mount NTFS filesystem at all.

Many linux distros don't support NTFS/exFAT filesystem by default (unless you install third-part driver/package).

**Comment by steve6375** [comment]
Such issues can be overcome if you use the partnew command as used by grub4dos and a1ive grub2.
Since the ISO appears as a ISO 9660 filesystem, no NTFS or FAT driver is needed by the kernel.
The partnew method requires the ISO to be contiguous and the drive must be write-enabled, however it is a generic method of booting Linux ISOs - see Easy2Boot+agFM. The grub2 agFM can boot many ISOs from any disk and any partition.

**Comment by ventoy** [comment]
Yes. 
partnew is a simple way to boot ISO file sometimes. 
But it has many restrictions, for example:

1. The USB drive must be writable (can't be writeprotected)
2. The BIOS firmware must support the write operation to disk
3. The ISO file must be contiguous in the physical disk (can't have more than one fragments)
4. You must preserve a MBR partition table for partnew, you can't use all the 4 MBR partition tables.
5. Doesn't support GPT partition style
6. Some system doesn't support such partition(e.g. FreeBSD series)
7. Some Linux distros don't support USB iso9660 partition (e.g. rhel6/CentOS6/Vine/mageia...)
8. Side effects. You will see an extra partition when you use the USB drive in a Linux system.
9. Can't implement some advanced functions(e.g. auto install/file injection/dud...)

Actually, it's just these restrictions of partnew that drove me to design Ventoy.

**Comment by sonichy** [comment]
After try again and again, I found the problem: iso-scan/filename is necessary !
Success, but lose select menu:
```
menuentry "Ubuntu Kylin" {
    set root=(hd0,msdos5)
    set isofile="/ISO/ubuntukylin-20.04.1-enhanced-amd64.iso"
    loopback loop $isofile
    linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=$isofile locale=zh_CN.UTF-8
    initrd (loop)/casper/initrd
}
```
```
menuentry "ubuntu 16" {
    set isofile="/ISO/ubuntu-16.04.7-desktop-amd64.iso"
    loopback loop (hd0,msdos5)$isofile
    linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=$isofile
    initrd (loop)/casper/initrd
}
```
```
menuentry "KDE neon" {
    set root=(hd0,msdos5)
    set isofile="/ISO/KDE-neon-user-20210217-1639.iso"
    loopback loop $isofile
    linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=$isofile
    initrd (loop)/casper/initrd
}
```
```
menuentry "fossapup" {
    set root=(hd0,msdos5)
    set isofile="/ISO/fossapup64-9.5.iso"
    loopback loop $isofile
    linux (loop)/vmlinuz iso-scan/filename=$isofile
    initrd (loop)/initrd.gz
}
```
```
menuentry "slitaz" {
    echo "Loading memdisk..."
    linux16 /usr/lib/syslinux/memdisk iso raw
    echo "Loading ISO..."
    initrd16 /usr/slitaz-rolling.iso
}
```
```
menuentry "WIN7PE" {
    echo "Loading memdisk..."
    linux /usr/lib/syslinux/memdisk iso raw
    echo "Loading ISO..."
    initrd (hd0,msdos5)/ISO/WIN7PE.iso
}
```
Fail:
```
menuentry "elementaryos" {
    set root=(hd0,msdos5)
    set isofile="/ISO/elementaryos-5.1-stable.20200814.iso"
    loopback loop $isofile
    linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=$isofiler
    initrd (loop)/casper/initrd.lz
}
```
```
menuentry "Deepin Live" {
    set root=(hd0,msdos5)
    set isofile="/ISO/deepin-live-system-2.0-amd64.iso"
    loopback loop $isofile
    linux (loop)/live/vmlinuz boot=live iso-scan/filename=$isofile
    initrd (loop)/live/initrd.img
}
```

**Comment by steve6375** [comment]
Many Ubuntu-based ISOs have a loopback.cfg file. They are intended to be used when you boot from an ISO.
Different distros have different parameters - they don't all use iso-scan/filename=
You have to do research on each one to see what you need to add to the kernel parameters (e.g. these are valid for different distors: fromiso=, isofrom_system=, isoboot=, findiso=, from=, isofrom=).
Some distros don't even support an iso parameter.

Note that they all rely on the kernel containing filesystem drivers for whatever filesystem the ISO is stored on, e.g. NTFS, exFAT, etc.
HTH

**Comment by sonichy** [comment]
How to load grub.cfg in the ISO ?

**Comment by vitaly-zdanevich** [comment]
Still no way to boot Ventoy from GRUB/SSD as ISO?
