### ISSUE TITLE
Ventoy Turkish language translation updated

### ISSUE THREAD

**Issue by crasadure** [ventoy/Ventoy#76]
Hi ventoy...

I know your project have Turkish language support but some translations are wrong...can you change turkish tranlations with my tranlation file
I fixed wrong translating sentences...
Turkish language.ini : [languages.zip](https://github.com/ventoy/Ventoy/files/4602431/languages.zip)

**Turkish Language Translations:**

`[Language2]
Name=Türkçe
FontFamily='Courier New'
FontSize=16
Author=longpanda admin@ventoy.net

STR_ERROR='Hata'
STR_WARNING='Uyarı'
STR_INFO='Bilgi'
STR_INCORRECT_DIR='Lütfen doğru dizin altında çalıştırın!'
STR_INCORRECT_TREE_DIR='Dosyayı burada çalıştırma, lütfen yayınlanan en son kurulum paketini indirin ve oradan çalıştırın.'
STR_DEVICE='Aygıt'
STR_LOCAL_VER='Ventoy GÜNCEL Sürüm'
STR_DISK_VER='Cihazdaki Ventoy Sürümü'
STR_STATUS='Durum - HAZIR'
STR_INSTALL='Kur'
STR_UPDATE='Güncelle'
STR_UPDATE_TIP='Ventoy Güncelleme işlemi tamamlandı, ISO dosyaları değişmeyecek.#@Devam edilsinmi?'
STR_INSTALL_TIP='Disk biçimlendirilecek ve tüm veriler kaybolacak.#@Devam edilsinmi?'
STR_INSTALL_TIP2='Disk biçimlendirilecek ve tüm veriler kaybolacak.#@Devam edilsinmi? (Son UYARI!)'
STR_INSTALL_SUCCESS='Tebrikler!#@Ventoy cihaza başarıyla kuruldu.'
STR_INSTALL_FAILED='Yükleme sırasında bir hata oluştu. USB'yi yeniden takıp tekrar deneyebilirsiniz. Ayrıntılar için log.txt dosyasına bakın.'
STR_UPDATE_SUCCESS='Tebrikler!#@Ventoy cihazda başarıyla güncellendi.'
STR_UPDATE_FAILED='Güncelleme sırasında bir hata oluştu. USB'yi yeniden takıp tekrar deneyebilirsiniz. Ayrıntılar için log.txt dosyasına bakın.'
STR_WAIT_PROCESS='Mevcut işlem çalışıyor, lütfen bekleyiniz ...'
STR_MENU_OPTION='Seçenek'
STR_MENU_SECURE_BOOT='Güvenli Önyükleme'`

**Comment by ventoy** [comment]
OK , thanks. I will update it later.

**Comment by ventoy** [comment]
I have commited the update.

**Comment by crasadure** [comment]
hi ventoy;

I updated Ventoy v1.0.09 and I think, "update message" will be good liket that at STR_UPDATE_TIP parameter : 

**STR_UPDATE_TIP='Ventoyun versiyon bilgisi güncellenecek, ISO dosyalarınız bundan etkilenmiyecek.#@Devam edilsinmi?'**

sorry..this is my fault..ı am using it new,guys :)

**Comment by chromer030** [comment]
@crasadure , Thank You for correcting translation , it's fully OK.
(Çeviriyi düzelttiğiniz için teşekkür ederiz, Tamamen iyi.)
