### ISSUE TITLE
Arch Linux Failed To Open Random Seed File Write Protected

### ISSUE THREAD

**Issue by thewarden** [ventoy/Ventoy#764]
When booting Arch Linux 2020.09.01 x86_64 ISO I receive a message of "Failed to open random seed file: write protected" just before the Arch Linux boot menu appears. If I boot the same ISO by itself (without using Ventoy) I don't see this error message.

**Comment by ventoy** [comment]
Can you reproduce the problem in another computer or VirtualMachine?

**Comment by thewarden** [comment]
Hello, yes I've experienced this on two systems thus far. I tried testing this on a virtual machine using libvirt v1:7.0.0-3 along with Virtual Machine Manager v3.2.0-1 on Arch Linux x86 64.

**Comment by moralrebuild** [comment]
Same issue for arch 20210601 iso after used it installing on desktop.

**Comment by Parn23** [comment]
I also have have the same issue with the latest ISO

**Comment by thewarden** [comment]
I'm still experiencing this issue with Arch Linux 2021.07.01-x86_64 ISO. I've not confirmed with August's build as of yet. I have been able to fix an existing Arch Linux install using Ventoy to boot Arch Linux  without issues.

I'm not certain the entire meaning of this error message. Just odd that it only occurs when using Ventoy.

**Comment by ventoy** [comment]
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/1097404201

**Comment by escape0707** [comment]
I can confirm that this also happens to August build. But it still runs and I can finish my purpose.

**Comment by ventoy** [comment]
@thewarden @escape0707 
Does this CI release work?
https://github.com/ventoy/Ventoy/actions/runs/1097404201

**Comment by escape0707** [comment]
@ventoy This patch seems to solve the issue. I'm not seeing the error message OP mentioned anymore.

> I tested with the downloaded the CI release and `sudo sh Ventoy2Disk.sh -u /dev/sda` then reboot into it.

**Comment by ventoy** [comment]
I think it's an issue of systemd and I also make a PR for this:
https://github.com/systemd/systemd/pull/20383

**Comment by ventoy** [comment]
The systemd project has accepted this patch.
https://github.com/systemd/systemd/pull/20383
