### ISSUE TITLE
[Feature Request] Custom Wallpaper

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [ventoy/Ventoy#77]
`[*]` Add user a option to flash `Ventoy` with their `custom choosen wallpaper` so that they can change the default `\grub\themes\ventoy\background.png`
`[*]` A warning do you wan't to use `previous wallpaper` if no is selected then `Ventoy Updater` will use its `own default wallpaper`

Greetings, `BL4CKH47H4CK3R`

**Comment by ventoy** [comment]
Ventoy has provided a simple way to change the theme, not only the wallpaper.
See  [https://www.ventoy.net/en/plugin_theme.html](url)
