### ISSUE TITLE
[Feature Request] Support for armv7l

### ISSUE THREAD

**Issue by joe733** [ventoy/Ventoy#775]
Hi, since raspberry Pi now [officially supports booting from USB](https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/msd.md). I'd love to see Ventoy support that architecture, please.

**Comment by ventoy** [comment]
For arm, only aarch64 is supported.
I have no such time to support too many architectures.

**Comment by joe733** [comment]
I understand, but I'm positive that it will be a good adventure. Is there any documentation on how to support more architecture(s) in future?

**Comment by ventoy** [comment]
Maybe when I have enough spare time.
