### ISSUE TITLE
[Critical] Kernel Panic When Booting Linux ISO Via BIOS (Legacy Mode)

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [ventoy/Ventoy#784]
I always get kernel panic when I try to boot any Linux ISO from Legacy Mode. UEFI Mode works fine. Sometimes RAMDISK Mode works well with BIOS Mode. Compatible Mode also not working on BIOS Mode for Linux ISO. Facing the problems since ventoy 1.0.33 or 34 maybe. Hope this problem will get fixed soon !

Cheers, BL4CKH47H4CK3R !

**Comment by ventoy** [comment]
Which ISO file did you test?
Is Ventoy 1.0.32 has no such problem?
Does this problem happen sometimes or everytime?
DId you test it in another computer when you have this problem?

**Comment by BL4CKH47H4CK3R** [comment]
Almost all linux distro. Just booting from BIOS (Legacy Mode) is causing this error. Also tried booting using (Compatible Mode) on (Legacy Menu) that also failed.  And yes, I am getting this error every time I try to boot an linux ISO. I think it was from version 1.0.32 also. Can't remember exactly because of gradual updates. But I am always up-to-date and every time I test it to make sure everything is working properly.
Another computer also causing the same issue I have tested. Also checked the checksum of the ISO to make sure that its downloaded correctly or not :smile:

**Comment by steve6375** [comment]
Why not test using a virtual machine?
E.g. QEMU or Virtual Box.
