### ISSUE TITLE
Fedora persistence file ?

### ISSUE THREAD

**Issue by imakiro** [ventoy/Ventoy#791]
Is there any way to make Fedora workstation work with persistence ?
The official documentation doesn't list any RedHat style OS https://www.ventoy.net/en/plugin_persistence.html
Simply setting a dat file in the ventoy.json file doesn't work as it's working with ubuntu style OSes

**Comment by ventoy** [comment]
Ventoy persistence feature depends on that the distro supports persistence itself.
If the distro doesn't support persistence, then the persistence feature will not take effect.

I didn't find any doc about how to make  fedora iso support persistence.

**Comment by imakiro** [comment]
Fedora mentions the following in the official doc : 
https://docs.fedoraproject.org/en-US/quick-docs/creating-and-using-a-live-installation-image/
```
Using the livecd-iso-to-disk tool
To enable 'data persistence' support - so changes you make to the entire live environment will persist across boots - add the --overlay-size-mb parameter to add a persistent data storage area to the target stick. For example:
```

No mention of labels, but it seems to be an overlayfs.

**Comment by tsoernes** [comment]
@ventoy 

Fedora does have support for persistence. See
[](https://docs.fedoraproject.org/en-US/Fedora/10/html/Release_Notes/sn-Live_USB_persistence.html)
[](https://github.com/livecd-tools/livecd-tools/blob/main/tools/livecd-iso-to-disk.sh)

It would be tremendously useful with support for Fedora/RHEL, you know how common these distros are in server/business/commercial environments

**Comment by ventoy** [comment]
@imakiro @tsoernes 
Please try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/721555777

**Comment by imakiro** [comment]
My usb key might have an issue, but I seem to get stuck at starting the session.
Just to make sure, how should I create the .dat file for the overlayfs and is there a specific instruction I should use in the ventoy.json ? I am using an EXT4 file like ubuntu right now.

**Comment by ventoy** [comment]
Please use the latest 1.0.40 for test and show me your ventoy.json.
You can use `F5 Tools-->Check plugin json configuration (ventoy.json) -->Check persistence pugin configuration` to check.

**Comment by imakiro** [comment]
Flashed the latest 1.0.40 and it doesn't boot with persistence in the file, even though the config is valid
![ventoy-final-boot-crash](https://user-images.githubusercontent.com/2473976/114374625-285b6a00-9b84-11eb-91c4-1c21d63b26c6.jpg)
![ventoy-valid-peristence-conf](https://user-images.githubusercontent.com/2473976/114375082-9acc4a00-9b84-11eb-9223-b1df2d7aa031.jpg)
![ventoy-dracut-issue](https://user-images.githubusercontent.com/2473976/114375479-f7c80000-9b84-11eb-8ccc-a8b3342e7c26.jpg)

**Comment by ventoy** [comment]
`Press Enter for maintaince`
Press enter to enter a shell and run 2 commands:
```
cat /ventoy/log
blkid
```

**Comment by imakiro** [comment]
vi /ventoy/log (the /bin/dracut-initqueue continues to infinity)

![ventoy-log](https://user-images.githubusercontent.com/2473976/114426569-7e4b0480-9bba-11eb-9754-4affd46e2b0c.jpg)

followed by blkid

![blkid](https://user-images.githubusercontent.com/2473976/114426556-7c814100-9bba-11eb-8afc-7d52d00e418d.jpg)

**Comment by ventoy** [comment]
Some more commands pls:
```
/ventoy/tool/vtoydump -f /ventoy/ventoy_os_param -v
fdisk -l  /dev/sda
fdisk -l  /dev/sdb
```

Is /dev/sda your hard drive?

**Comment by imakiro** [comment]
Vtoydump :
![ventoydump](https://user-images.githubusercontent.com/2473976/114535643-8e152800-9c50-11eb-9427-e8debd4b2b63.jpg)

/dev/sda is the internal ssd
/dev/sdb is the external ssd, usb plugged, on which ventoy is installed

Fdisk being not available from the ventoy emergency shell, here's the output from the ubuntu live environment
![FDisk-l](https://user-images.githubusercontent.com/2473976/114567252-57043e00-9c73-11eb-8e3b-dce5cfba5099.jpg)

**Comment by ventoy** [comment]
Please use this CI release for test:
https://github.com/ventoy/Ventoy/actions/runs/746796746

**Comment by imakiro** [comment]
Happy to report that with this build it works really well ! still can't choose to persistence file when booting the ISO, but the file indicated by the "autoselect" in the config is taken into account.
Brilliant work !

**Comment by ventoy** [comment]
When you set `autosel` in the config file the prompt menu will not be shown anymore.

**Comment by bagong** [comment]
[](url)Hi, I tried with Fedora Workstation 41 today and ran into similar trouble... I did all the commands suggested for analyzing the failure? Maybe something can be said? Did I make a mistake or does the old system not work with latest Fedora any more? Would be a lovely "nice to have" ;-)

[https://photos.app.goo.gl/znMiVGKogVenrjeb7](url)
