### ISSUE TITLE
能否实现Windows端安装器的热更新？

### ISSUE THREAD

**Issue by MasterOfStar** [ventoy/Ventoy#792]
每次有更新的时候都需要重新下载，有些麻烦。
也许可以参考隔壁https://github.com/netchx/Netch 的那种热更新方式来更新？
他们的方式好像是从github下载release然后自动解压替换（覆盖？）当前文件
![image](https://user-images.githubusercontent.com/21274896/110784339-89053780-82a4-11eb-82b3-240261674b26.png)

**Comment by ventoy** [comment]
随着功能的稳定，Ventoy后续也会稳定下来，不会像前期更新这么频繁。
另外，不联网对用户来说感觉上也更安全一些。

因此，不打算实现热更新的功能。
