### ISSUE TITLE
Ventoy 能支持 Virtual Box 的虚拟机启动吗？

### ISSUE THREAD

**Issue by taotieren** [ventoy/Ventoy#794]
Ventoy 能支持 Virtual Box 的虚拟机启动吗？

**Comment by taotieren** [comment]
Ventoy 支持 ova 格式启动吗？

**Comment by ventoy** [comment]
支持 Linux的 vdi/vhd 启动，ova不支持。
https://www.ventoy.net/cn/plugin_vtoyboot.html

**Comment by taotieren** [comment]
有计划支持 OVA 吗2021年3月18日 10:20，longpanda ***@***.***>写道：

支持 Linux的 vdi/vhd 启动，ova不支持。

https://www.ventoy.net/cn/plugin_vtoyboot.html

**Comment by ventoy** [comment]
肯定不会支持。
OVA并不是一个磁盘镜像格式，是一个虚拟机的格式。
Ventoy并不是一个虚拟机软件，它只能启动镜像文件或者磁盘镜像。
