### ISSUE TITLE
Can you add support this WinPE systems

### ISSUE THREAD

**Issue by crasadure** [ventoy/Ventoy#80]
Hi vento;
Can you support these WinPE systems with Ventoy multiboot programs...

WinPE Systems Names and Download Links 

Sergei Strelec WinPE:
https://sergeistrelec.ru/winpe-10-8-sergei-strelec-english/
Download Link:
https://drive.google.com/file/d/1G5-JDKsEkvHOOawog1FyDbNhScgwoq92/view?usp=sharing

Anhdv Boot WinPE
https://anhdvboot.com/en/download/
Download Link:
Google Drive Link : https://bit.ly/3dbXTmE
Onedrive Link1: https://bit.ly/3fdsfag
Onedrive Link2 : https://bit.ly/3ferhur

DLC Boot 2019 3.6 Build 190411:
http://dlcboot.com/download.html?i=1
Download Link 
https://drive.google.com/file/d/1WoVImkrZhvEGVVwDROkMZs_1VXWOjK0-/view?usp=sharing
http://www.mediafire.com/file/id2rg1926cw7mfd/DLC.Boot.2019.V3.6.rar/file

HKBoot 2017 WinPE
https://hoangkhien.com/hkboot.html
Download Link :
https://yadi.sk/d/8rNHpHdp3HYrqx

Kmpe Xp-8-10 (x86/x64/ Native.x86) 2020_05_05
https://www.tnctr.com/topic/658892-kmpe-xp-8-10-x86x64-nativex86-2020_05_05/
Download Link:
https://drive.google.com/file/d/1Aq7QswVjXRjcq9xmXRvQHbVMghN7Vglt/view?usp=sharing

Bob.Omb’s Modified Win10PEx64 v4.8 RS5
https://www.warezturkey.org/46511-bob-ombs-modified-win10pe.html
Download Link 
https://uptobox.com/ob3l4txchyjh/Bob.4.8RS5.WT.rar

Hiren’s BootCD PE x64 (v1.0.1)
https://www.hirensbootcd.org/download/
Download Link : 
https://www.hirensbootcd.org/files/HBCD_PE_x64.iso

**Comment by danielcshn** [comment]
I am using "**DLC Boot 2019 3.6 Build 190411**" with Ventoy 1.0.47 without problems.
