### ISSUE TITLE
No bootfile found for UEFI with Ventoy, But OK witth rufus. Help !!!!!!!

### ISSUE THREAD

**Issue by andycuong** [ventoy/Ventoy#800]
Hi !
I have installed Ventoy on my USB and I have added ISO file: "Win10SupperLite_TeamOS_Edition.iso"
all give ERROR on my PC
No bootfile found for UEFI!
Maybe the image does not support X64 UEFI!
But i have added ISO file by Rufus. Its ok

**Comment by ventoy** [comment]
Please test this ISO file with VirtualMachine(e.g. VMware or VirtualBox)
Set the VM to UEFI mode and connect the ISO file directly to the VM and boot.
Will it boot fine?

**Comment by andycuong** [comment]
> Please test this ISO file with VirtualMachine(e.g. VMware or VirtualBox)
> Set the VM to UEFI mode and connect the ISO file directly to the VM and boot.
> Will it boot fine?

its okay. only ventoy give error "No bootfile found for UEFI!"

**Comment by ventoy** [comment]
Can you share the ISO file for test?

**Comment by andycuong** [comment]
> Can you share the ISO file for test?

https://drive.google.com/file/d/1_mYChRFanLEdyttDvT-cn6zH0o6KX7Th/view 
can u test ? i was test in VMWare 16 for rufus, winsetupusb, yumi...its okay

**Comment by ventoy** [comment]
I can't download this file.

**Comment by andycuong** [comment]
> I can't download this file.

https://drive.google.com/file/d/1_mYChRFanLEdyttDvT-cn6zH0o6KX7Th/view?usp=sharing

can u try again ?

**Comment by ventoy** [comment]
I always get
![image](https://user-images.githubusercontent.com/59477474/111790601-550dc000-88fd-11eb-831d-1f252c90c0b6.png)

**Comment by benathan** [comment]
@ventoy I can confirm this, using the exact same iso.
Link:
Error message:
No bootfile found for UEFI!
Maybe the image does not suport IA32 UEFI!

**Comment by andycuong** [comment]
> I always get
> ![image](https://user-images.githubusercontent.com/59477474/111790601-550dc000-88fd-11eb-831d-1f252c90c0b6.png)

can u try

**Comment by andycuong** [comment]
> > I always get
> > ![image](https://user-images.githubusercontent.com/59477474/111790601-550dc000-88fd-11eb-831d-1f252c90c0b6.png)
> 
> can u try

yes, but i try with rufus, yumi, winsetuptousb,... its okay. can u fix now ?
