### ISSUE TITLE
Latest release still not working for FreeBSD 13.0-RC2

### ISSUE THREAD

**Issue by ykla** [ventoy/Ventoy#801]
Latest release still not working for FreeBSD 13.0-RC2
![QQ图片20210318131253](https://user-images.githubusercontent.com/10327999/111576561-b47bab00-87eb-11eb-8053-c65a8ff6c42f.jpg)

**Comment by ventoy** [comment]
https://download.freebsd.org/ftp/releases/ISO-IMAGES/13.0/FreeBSD-13.0-RC2-amd64-disc1.iso
SHA256 (FreeBSD-13.0-RC2-amd64-disc1.iso) = ab244a85e7acbadd5ea609934809f549302e911a68d6abfb784e4b83a6905cef

I test this ISO file and it boot fine.

**Comment by ykla** [comment]
I try it once it works.
