### ISSUE TITLE
F key shortcut to enter text-only mode

### ISSUE THREAD

**Issue by chrome68issues** [ventoy/Ventoy#804]
It would be really nice to have an option of just pressing any function key to enter text-only mode. I had several times laptops which don't play nice with ventoy and the menu gets cut off. You can still navigate and change resolution or enter text only mode if you memorized the path you're supposed to take, since you can't see the menus you're navigating in.

It would be much easier if there was a dedicated hotkey to enter text-only mode (for example F7, F8, whatever).

**Comment by ventoy** [comment]
In the latest 1.0.39 release, I add a F7 hotkey for text mode.
