### ISSUE TITLE
[Feature Request] Keep Existing Data in Preserved Storage

### ISSUE THREAD

**Issue by hxr404** [ventoy/Ventoy#808]
It would be useful if one could specifiy in the installer wich partitions to keep. At the moment I have to
1. copy my entire Data to an external disk
2. install ventoy and create the preserved storage
3. create the partitions again 
4. copy the data back. 

It would be much easier if I could simply set preserve Storage and then just select "Keep Partition F:"
Just make a disclaimer that you're not responsible for any data losses so nobody can complaint

**Comment by ventoy** [comment]
Ventoy must create a new partition table and split the whole disk into some partitions as designed.
To preserve data after create new partitions is a complex work and is what professional disk management software should do.
Ventoy is just for boot and should not do such work.
What you did is just the most simple and reliable way.

**Comment by hxr404** [comment]
Oh ok thanks for the answer.
This copying back and fourth can be a really tedious task especially when having hundreds of gigs on that drive.
So is this planned in a far future release or is it a wontfix?
Maybe you could add a manual install mode, where the user creates the partitions and then manually flashes Ventoy to the FAT32 Partition

**Comment by howdev** [comment]
I don't see why Ventoy cannot preserve data. Multibootusb can install without wiping existing data

**Comment by ventoy** [comment]
@hxr404  @howdev 
Latest Ventoy release supports non-destructive installation if your USB disk match some requirements.
https://www.ventoy.net/en/doc_non_destructive.html

**Comment by howdev** [comment]
@hxr404 Ventoy non-destructive is a lot more complicated. Multibootusb doesn't touch partitions or files. Always installs without damaging data.

**Comment by ventoy** [comment]
Yes, different softwares have different mechanisms. That's very common.
The disk layout is part of Ventoy solution from the begging.
The non-destructive installation is what I can do for the best.

ps: 
If your USB disk doesn't have a FAT EFI partition, how does it boot in UEFI mode?

**Comment by howdev** [comment]
my disk is not new. It has data on it. My USB flash is also has data on it. 
There is legacy boot mode

**Comment by hxr404** [comment]
Non-destructive installation works great for me. Thanks a lot for implementing this feature.

(Sorry, I forgot closing this issue after release v1.0.60 b0568922d20d7c19025f371fa9066044777d7b5b)
