### ISSUE TITLE
not enough space for plugins

### ISSUE THREAD

**Issue by sharicov** [ventoy/Ventoy#810]
In latest versions there is not enough free space on vtoyEFI partition for plugin files (ventoy_vhdboot.img; ventoy_wimboot.img)
Please either make partition bigger, or optimize the ventoy files to fit in.

**Comment by ventoy** [comment]
ventoy_vhdboot.img and ventoy_wimboot.img should be in the 1st partition(ventoy partition) not VTOYEFI partition.
Although in current release it will also take effect if you put them in VTOYEFI partition.

**Comment by sharicov** [comment]
Thank you very much for clarifying, good to know! It wasn't so clear from the guide: https://www.ventoy.net/en/plugin_vhdboot.html

**Comment by ventoy** [comment]
I have updated the page.
