### ISSUE TITLE
Windows 7 OEM

### ISSUE THREAD

**Issue by Rikitik** [ventoy/Ventoy#813]
I have an old Windows 7 OEM install disc from my IT Shop days
It complains about No EFi X64
I got It working with WinPE long time ago(modified it with USB3 supprt
Like help getting it working willing to pay

**Comment by steve6375** [comment]
Get a \efi\boot\bootx64.efi file from a win 8 or win10 iso and add it to your iso file

**Comment by Rikitik** [comment]
It's an AIO OEM disc tried your suggestion new error is
 chain empty failed

**Comment by Rikitik** [comment]
It seems to be a Image related, ssue. I rebuild the image and got it to work for the most part(winload.efi) issue left
