### ISSUE TITLE
有没可能支持Redhat6/Centos6的自动化安装

### ISSUE THREAD

**Issue by Cyclonekid** [ventoy/Ventoy#821]
有没可能支持Redhat6/Centos6的自动化安装？虽然6现在已经淘汰了·   但是好多地方还在使用，没有计划支持他们的自动化你装。

**Comment by ventoy** [comment]
后续会考虑支持。

**Comment by ventoy** [comment]
@Cyclonekid 

请使用这个CI版本测试一下。

 === VentoyCI Download Link ===

ventoy-04021025-windows.zip :
md5: 76e78125c05fe6f8bc4e3443dbf8f0dd
link: https://ws28.cn/f/530984kmmpa 

ventoy-04021025-linux.tar.gz :
md5: faa933f387cc9ac86a96be2e08b9b6b3
link: https://ws28.cn/f/5309mmhevla

**Comment by Cyclonekid** [comment]
收到，下午测试一下

**Comment by Cyclonekid** [comment]
测试了下，单独写在auto_install、auto_install_legacy、auto_install_uefi下，redhat6的自动化安装已经可以使用自定义配置文件进行自动安装部署。但如果同时存在auto_install和多模式auto_install_legacy、auto_install_uefi的时候，auto_install里面的东西就不生效了。不生效的时候的写法如如下：
                
![image](https://user-images.githubusercontent.com/17697818/113385112-0c084200-93ba-11eb-9af4-b79b2bfc9628.png)

**Comment by ventoy** [comment]
这个在官网手册里面有说明，这两种模式是不能同时配置的。
https://www.ventoy.net/cn/plugin_dual_option.html

![捕获](https://user-images.githubusercontent.com/59477474/113389385-863cc480-93c2-11eb-846b-cbf8f6426fed.PNG)

**Comment by Cyclonekid** [comment]
收到，大意了，直接忽略了这句话，已经完成测试了，测试版可以支持rhel6的自动化安装配置，本comment关闭了，希望可以尽快合并至主线。

**Comment by ventoy** [comment]
OK.
修改会包含在下一个正式版本中。
