### ISSUE TITLE
Ventoy booting fist iso/img/efi automaticlly

### ISSUE THREAD

**Issue by Admin-A-LLC** [ventoy/Ventoy#824]
I've noticed that on some of my computers, ventoy boots but then immediately boots the first file on the menu. Not sure how to collect debug files for this. As an attempt to circumvent it, I've created a rEFInd bootable ISO file and named it 1.iso so that it's at the top of the list. This gets me to a menu and even lets me fall back to the Ventoy boot menu, but none of the boot options work and it just reboot back into a cycle. Any way around this?

**Comment by ventoy** [comment]
Maybe something about the keyboard? You can do the following test:
1. Change USB to the 1st boot option in the BIOS setup
2. Reboot your computer
3. Don't press any key, just wait your computer to boot into Ventoy automatically and to see whether it auto boot the 1st iso file

Also I can give you a workaround for test.
Create a `ventoy` directory in the 1st partition(which hold the iso files) of the USB drive and put the `ventoy.txt` file in the attachment to the directory and rename it to `ventoy.json`
[ventoy.txt](https://github.com/ventoy/Ventoy/files/6237363/ventoy.txt)

**Comment by damianlavalle** [comment]
Ok That's weird. Your workaround worked, but only once! It stopped and gave me a menu, after witch I chose a random iso and It was ready to boot. I didn't need to completely boot so I just did the 3 flag salute and rebooted again, only this time It just booted my first iso automatically again. Was that supposed to happen?

**Comment by damianlavalle** [comment]
> 
> 
> Maybe something about the keyboard? You can do the following test:
> 
>     1. Change USB to the 1st boot option in the BIOS setup
> 
>     2. Reboot your computer
> 
>     3. Don't press any key, just wait your computer to boot into Ventoy automatically and to see whether it auto boot the 1st iso file
> 
> 
> Also I can give you a workaround for test.
> Create a `ventoy` directory in the 1st partition(which hold the iso files) of the USB drive and put the `ventoy.txt` file in the attachment to the directory and rename it to `ventoy.json`
> [ventoy.txt](https://github.com/ventoy/Ventoy/files/6237363/ventoy.txt)

I see what you did with the jason file. What happens if I specify a non-existent default image?

**Comment by ventoy** [comment]
Please use this CI release for test.
https://github.com/ventoy/Ventoy/actions/runs/710396388

**Comment by ventoy** [comment]
@Admin-A-LLC 
Any update?
