### ISSUE TITLE
Multiple antimalware engines flag the Windows Ventoy 1.0.09 installer

### ISSUE THREAD

**Issue by jdrch** [ventoy/Ventoy#83]
Just a heads up that the Windows Ventoy 1.0.09 installer is flagged by both Avira Antivirus Pro (on my machine) and [BitDefender Theta (on VirusTotal)](https://www.virustotal.com/gui/file/5506cec07f4cd9f6f049de5aa7cbfb33dd7c61e5bb92f8b6d355f0fe9c038bbd/detection).

Any ideas?

**Comment by ventoy** [comment]
Maybe I will send a false positive report to these Vendors.

**Comment by jdrch** [comment]
FWIW, no false positive from Avira for 1.0.10, so I'd say this is solved. Still 2 false positives on 2 lesser known antimalware engines, but I'm willing to ignore those.
