### ISSUE TITLE
Do i need to defrag usb flash drive after deleting or copying iso files?

### ISSUE THREAD

**Issue by peter099** [ventoy/Ventoy#830]
I have used Easy2boot before to create multi boot usb drives and after i delete or copy new iso file to the drive i had to run a script that makes the drive contiguous. Do i need to do that with usb drivers created with Ventoy? I am using Ventoy on MX Linux.

**Comment by ventoy** [comment]
NO.
You don't need to defrag the USB drive.
Ventoy works in a different mechanism so there is no need for the file to be continuous in the disk.

**Comment by peter099** [comment]
Good to know, thanks.
