### ISSUE TITLE
Suggestion: rename "bottom of the disk" to "end of the disk"

### ISSUE THREAD

**Issue by asheroto** [ventoy/Ventoy#834]
![image](https://user-images.githubusercontent.com/49938263/113802356-35a9cc00-9720-11eb-95bd-9b9300cf6103.png)

Not a bug.

Big Ventoy fan here.

Most folks think of the "end" or "beginning" of the disk, not the bottom/top of the disk.  I'm assuming you mean end of the disk, but I'm not sure.  😎 I think "end" or "beginning" would make more sense.

Thanks!

**Comment by ventoy** [comment]
Fixed in the latest release.
