### ISSUE TITLE
无法使用DiskCryptor创建的引导ISO文件

### ISSUE THREAD

**Issue by hs180-cn** [ventoy/Ventoy#838]
DiskCryptor是一款磁盘加密工具，通过它可以对硬盘进行加密，在对系统盘进行加密后可以创建一个解密的iso光盘。当我使用ventoy对该dcload.iso进行引导启动时无法正常工作。
DiskCryptor项目主程序，https://github.com/DavidXanatos/DiskCryptor
用于引导的ISO文件，https://github.com/hs180-cn/dcload/blob/main/loader.iso
希望作者能解决这个问题。

**Comment by ventoy** [comment]
试试先按 F1 再选择ISO文件启动。

**Comment by hs180-cn** [comment]
> 试试先按 F1 再选择ISO文件启动。

感谢您的回复，问题已解决
