### ISSUE TITLE
Setup without installation feature request

### ISSUE THREAD

**Issue by sharicov** [ventoy/Ventoy#839]
could you please add an option to set the Ventoy up without the installation? 
Would be extremely useful to use to boot from the hard drive!
What I am normally doing to set up AIO Boot is:
Creating FAT32 partition of the hard disk (shrinking windows partition on the fly)
Extracting AIO Boot file structure from the installation executable to the FAT32 
Result: can boot from it choosing it from the boot menu (UEFI only but still covers 90% of my daily needs).
Thanks in advance!

**Comment by ValdikSS** [comment]
The files are in `ventoy/ventoy.disk.img.xz` disk image. MBR bootloader is in `boot/boot.img`, second stage bootloader is in `boot/core.img.xz`.

**Comment by sharicov** [comment]
Thanks for response!
If I only need EFI boot can I just extract contents of ventoy.disk.img.xz into it, or do I need adidtional manipulations?

**Comment by ventoy** [comment]
Ventoy must be installed to a disk to use. All other install methods are unofficial and unsupported.
