### ISSUE TITLE
已找到无法引导Bitlocker加密的vhd系统的问题，劳烦作者能够更新

### ISSUE THREAD

**Issue by hs180-cn** [ventoy/Ventoy#840]
我有一个U盘有2个分区，第一个分区（H:\）是引导分区Fat，第二个分区（i:\）是数据存放区NTFS。我的vhd系统是Windows to Go版win10，采用bitlocker加密，加载后盘符为（k:\）。我使用引导创建命令bcdboot  k:\windows /s h: /f BIOS创建了引导数据后，可以正常通过U盘启动vhd系统。如今数据安全越来越被人们重视，我想使用ventoy系统来引导加密的vhd，但视乎ventoy_vhdboot.img插件并不支持，未加密的vhd可以正常引导。请问有什么办法可以支持加密的vhd系统启动，比如把原生的引导文件修改导入到ventoy_vhdboot.img插件中。但视乎缺乏这方面的资料，不知如何修改。

**Comment by hs180-cn** [comment]
找到问题了。第一是插件ventoy_vhdboot.img中的BOOTMGR版本过旧，同时缺少boot/bootvhd.dll 文件所致。第二在替换新版本的BOOTMGR后BCD文件需要大写。BOOTMGR来源最新版Win10提取。劳烦作者对其更新。
这是我修改后的插件https://github.com/hs180-cn/vhdiso/blob/main/ventoy_vhdboot.img，供您参考。

**Comment by ventoy** [comment]
已更新。
不过不同Windows版本下的BOOTMGR的兼容性不一样，也不是越新越好。
我把你这个也添加进去了，使用的时候根据自己情况选一个能用的即可。

**Comment by hs180-cn** [comment]
感谢作者的回复，我修改的测试插件中的BCD文件是我测试环境的，其他人可能不通用，发布出来的话需要编辑下BCD文件中的VHD加载路径和名称。测试环境是Legacy引导，UEFI暂时没测试可能会存在问题。我看您发布的好像还是我测试环境的路径文件。

**Comment by ventoy** [comment]
已经更新

**Comment by fjsuetgf5s** [comment]
我使用了[vhdimg v3.0 release]，但问题依然存在，无法成功引导。我最近在win10_21H1、win10_21H2、server2022、win10_1607上测试，只要使用了bitlocker加密均无法正常引导。不知vhdimg插件如何自己制作呢？或者烦请作者增加通用的vhdimg插件吧！
