### ISSUE TITLE
About Ventoy GPT

### ISSUE THREAD

**Issue by Sayor0630** [ventoy/Ventoy#842]
My SSD or Windows is in GPT UEFI. Then why Ventoy is showing MBR?
![image](https://user-images.githubusercontent.com/77576588/114293536-c5e96780-9ab8-11eb-8f75-e96305fbe1e0.png)

**Comment by ventoy** [comment]
You misunderstand.
The `MBR` in the left means that you will install Ventoy to this device in MBR partition style.
This can be changed by `Option---->Partition Style` menu.

**Comment by Sayor0630** [comment]
ooh. thank u

**Comment by Sayor0630** [comment]
What is Secure Boot support?

**Comment by Luk164** [comment]
> What is Secure Boot support?

Support for UEFI Secure boot feature, it is usually used to prevent unauthorized bootable mediums being used in the system. Pretty much useless for an average user as they do not have passwords in their BIOS set anyway
