### ISSUE TITLE
Qubes 4.0.4

### ISSUE THREAD

**Issue by hardcod3dd** [ventoy/Ventoy#845]
![IMG_20210412_180537](https://user-images.githubusercontent.com/23269636/114418441-2d87db80-9bbb-11eb-8e83-2a1ab43db7ab.jpg)

Getting this when i try to boot qubes 4.0.4 is it caused by ventoy ?

**Comment by ventoy** [comment]
I suggest to check the ISO file in the USB stick (md5/sha1/sha256) to make sure  that it is NOT corrupted during copy.

**Comment by hardcod3dd** [comment]
Thanks.i never thought of that i will check it as soon as possible

**Comment by hardcod3dd** [comment]
Checked.hashes are same but still getting the same error

**Comment by ventoy** [comment]
Run the following commaond when you drroped to the shell.
```
cat /ventoy/log
blkid
```

**Comment by hardcod3dd** [comment]
`❯ cat a.txt
/dev/sda1: UUID="D89D-E4BC" TYPE="vfat" PARTUUID="8b56c34b-99c3-9e46-991b-fbefc9e99289"
/dev/sda2: UUID="a895ce51-5fc6-4e13-8a04-c834e1eacdec" TYPE="crypto_LUKS" PARTUUID="9490911e-24e3-ae44-bdbb-6c3c138c8770"
/dev/sdb2: UUID="DCF6DF8EF6DF6774" TYPE="ntfs" PARTLABEL="Basic data partition" PARTUUID="d64cd17f-5c13-417b-bce1-d7fefcf4b310"
/dev/mapper/ventoy: UUID="2021-03-04-14-07-15-00" LABEL="Qubes-R4.0.4-x86_64" TYPE="iso9660" PTUUID="501be065" PTTYPE="dos"
/dev/sdd1: LABEL="Ventoy" UUID="2E0A-527F" TYPE="exfat" PTTYPE="dos" PARTUUID="9c50276c-01"
/dev/sdd2: SEC_TYPE="msdos" LABEL="VTOYEFI" UUID="A8D7-18F1" TYPE="vfat" PARTUUID="9c50276c-02"
/dev/sdb1: PARTLABEL="Microsoft reserved partition" PARTUUID="3bfd82db-1a1e-4711-a7a8-40a0df130a10"
❯ cat log
============== VENTOY =================
608 blocks
5242 blocks
77 blocks
Use i386 busybox toolkit ...
kenel version=Linux version 5.4.98-1.fc25.qubes.x86_64 (user@build-fedora4) (gcc version 6.4.1 20170727 (Red Hat 6.4.1-1) (GCC)) #1 SMP Wed Feb 17 01:49:26 UTC 2021
kenel cmdline=inst.stage2=hd:LABEL=Qubes-R4.0.4-x86_64 i915.alpha_support=1
handover to init_chain
remove whole sbin directory
=====ventoy_unpack_initramfs: #/initrd001 0 FD37 /initrd001_tmp#
vtx=FD37 xzcat
143089 blocks
Now hand over to ventoy.sh
#### install vtoytool #####
try /ventoy/tool/vtoytool/00/ ...
vtoytool_64 OK
use vtoy_fuse_iso_64
use unsquashfs_64
kernel version
Linux version 5.4.98-1.fc25.qubes.x86_64 (user@build-fedora4) (gcc version 6.4.1 20170727 (Red Hat 6.4.1-1) (GCC)) #1 SMP Wed Feb 17 01:49:26 UTC 2021
OS=###rhel7###
VTKS=  VTOVERLAY=
vtInstDD=
patch /sbin/dmsquash-live-root ...
... start inotifyd listen /ventoy/hook/rhel7/ventoy-inotifyd-hook.sh ...
##### INOTIFYD: /dev/char is created (NO) ...
##### INOTIFYD: /dev/usbmon1 is created (NO) ...
##### INOTIFYD: /dev/rtc is created (NO) ...
##### INOTIFYD: /dev/bus is created (NO) ...
##### INOTIFYD: /dev/usbmon2 is created (NO) ...
##### INOTIFYD: /dev/block is created (NO) ...
##### INOTIFYD: /dev/disk is created (NO) ...
##### INOTIFYD: /dev/hidraw0 is created (NO) ...
##### INOTIFYD: /dev/sg2 is created (NO) ...
##### INOTIFYD: /dev/sdc is created (NO) ...
##### INOTIFYD: /dev/sdc1 is created (NO) ...
##### INOTIFYD: /dev/sdc2 is created (YES) ...
/etc/udev/rules.d/99-live-squash.rules not exist...
find ventoy partition ...
create_ventoy_device_mapper /dev/sdc --readonly
dmsetup avaliable in system /ventoy/tool/dmsetup
device-mapper module check success
==== create ventoy device mapper success ====
no need to replace block device
This is dm-0, OK ...
set anaconda-diskroot ...
VTLABEL=Qubes-R4.0.4-x86_64
link to /dev/disk/by-label/Qubes-R4.0.4-x86_64`

**Comment by ventoy** [comment]
/dev/dm-0 is mapped to the ISO file.
So you can run   md5sum  /dev/dm-0  to check.

**Comment by hardcod3dd** [comment]
shasum md5sum commands are non existent.cannot check

**Comment by ventoy** [comment]
Try this:
```
/ventoy/busybox/md5sum   /dev/dm-0
```

**Comment by hardcod3dd** [comment]
both sha256 and md5 checksums does not match the qubes iso.the file on usb does match but not dm-0

**Comment by ventoy** [comment]
It's weird. 
I test `Qubes-R4.0.4-x86_64.iso` in my laptop and the md5sum of /dev/dm-0 is `5e37ed0f81e4babc0df322ec19f9d5b4` which matches the value in the website.

1. I want another command here:
```
cat /ventoy/ventoy_dm_table
```

2. When you boot into Ventoy's menu, press `c` to enter grub shell and run two commands (will take long time):
```
vt_test_block_list $vtoy_iso_part/Qubes-R4.0.4-x86_64.iso
blocklist $vtoy_iso_part/Qubes-R4.0.4-x86_64.iso
```

3. Does other ISO files boot fine?

**Comment by hardcod3dd** [comment]
Yep.windows,linux,windows pe,debian and some other distros are just fine.im gonna try to re download and put qubes just in case.

**Comment by hardcod3dd** [comment]
for some reason moving iso from windows to usb drive works.but not works if i move the iso from manjaro xfce.something must have wrong with my setup you can close the issue.

**Comment by ventoy** [comment]
When you in manjaro, after move the iso to USB stick, run `sync` command in the terminal.
You need to wait  the `sync` command to finish before you plug-out the USB stick or reboot the computer.

**Comment by ventoy** [comment]
When you see that the iso file has been moved to the USB stick, actually part of the data is in the memory cache and has not been written to the USB stick. If you plug-out USB or reboot the computer the ISO file will be corrupted.
`sync` command force to flush all the cache to the USB stick.
