### ISSUE TITLE
boot jailm8.iso failed

### ISSUE THREAD

**Issue by Arthur2012** [ventoy/Ventoy#847]
开源项目jailm8，是用GRUB引导的iso镜像，基于squashfs文件系统的linux liveCD。iso下载和源码见github：
https://github.com/SarKaa/jailm8/releases

用ventoy引导此iso失败，屏幕左上角闪烁一个文本光标，无响应。
请大佬看看是否能解决，谢谢！

**Comment by ventoy** [comment]
这个ISO文件我使用虚拟机直接挂上启动也是一直闪光标。可能ISO文件有问题。

**Comment by Arthur2012** [comment]
> 这个ISO文件我使用虚拟机直接挂上启动也是一直闪光标。可能ISO文件有问题。

咦，真的是。用rufus把iso刷到U盘是能启动的，用虚拟机加载iso却无法启动。难道这个iso没有引导能力，GRUB是rufus额外写上去的？我去问问作者。
由此冒出2个问题：
1. 可引导的U盘能否成备份成可引导的镜像文件
2. ventoy加载带GRUB的镜像，形成套娃，是不是会有问题？（部分PE工具和微型linux镜像，有立刻花屏和死机现象。FAQ调整分辨率的建议还有待试验）

**Comment by ventoy** [comment]
1. 可以，但是一般启动之后会报找不到安装介质的错误。所以基本上不可用。
2. 没问题，绝大多数的Linux系统的ISO在UEFI模式下都是通过grub2引导的。花屏死机现象和这个无关。

Ventoy里面有一种grub2启动模式，就是使用grub2直接启动ISO文件，你可以使用下面这个版本进行测试，应该可以启动。
https://github.com/ventoy/Ventoy/actions/runs/744590696
**注意启动到Ventoy界面之后先按 Ctrl+r 然后再选择ISO文件启动。**
