### ISSUE TITLE
Translated Ventoy in Slovenian language

### ISSUE THREAD

**Issue by Urajmal** [ventoy/Ventoy#848]
Please add a Slovenian language bellow:

[Language-Slovenian (Slovenski)]
FontFamily='Courier New'
FontSize=16
Author=Urajmal

STR_ERROR='Napaka'
STR_WARNING='Opozorilo'
STR_INFO='Info'
STR_INCORRECT_DIR='Prosim izberite pravilno pot!'
STR_INCORRECT_TREE_DIR='Ne zaganjajte tukaj. Prosim prenesite posodobljeno verzijo in jo zaženite.'
STR_DEVICE='Naprava'
STR_LOCAL_VER='Ventoy verzija'
STR_DISK_VER='Ventoy na napravi'
STR_STATUS='Status - PRIPRAVLJEN'
STR_INSTALL='Namesti'
STR_UPDATE='Nadgradi'
STR_UPDATE_TIP='Varna nadgradnja. ISO datoteke ne bodo spremenjene.#@Nadaljujem?'
STR_INSTALL_TIP='Ta disk bo formatiran in vsi podatki bodo izbrisani.#@Nadaljujem?'
STR_INSTALL_TIP2='Ta disk bo formatiran in vsi podatki bodo izbrisani.#@Nadaljujem? (Druga potrditev)'
STR_INSTALL_SUCCESS='Čestitamo!#@Ventoy je bil uspešno nameščen na napravo.'
STR_INSTALL_FAILED='Med namestitvijo je prišlo do napake. Iztaknite in ponovno priklopite USB. Preverite log.txt za podrobnosti.'
STR_UPDATE_SUCCESS='Čestitamo!#@Ventoy na napravi je bil uspešno posodobljen.'
STR_UPDATE_FAILED='Prišlo je do napake med nadgradnjo. Iztaknite in ponovno priklopite USB. Preverite log.txt za podrobnosti.'
STR_WAIT_PROCESS='Proces teče, prosimo počakajte, ...'
STR_MENU_OPTION='Nastavitve'
STR_MENU_SECURE_BOOT='Podpora Secure Boot'
STR_MENU_PART_CFG='Konfiguracija particij'
STR_BTN_OK='V redu'
STR_BTN_CANCEL='Prekliči'
STR_PRESERVE_SPACE='Ohrani nekaj prostora na koncu particije'
STR_SPACE_VAL_INVALID='Nepravilna vrednost za rezerviran prostor'
STR_MENU_CLEAR='Odstrani Ventoy'
STR_CLEAR_SUCCESS='Ventoy je bil uspešno odstranjen.'
STR_CLEAR_FAILED='Prišlo je do napake pri odstranjevanju Ventoy-a iz diska. Iztaknite in ponovno priklopite USB. Preverite log.txt za podrobnosti.'
STR_MENU_PART_STYLE='Vrsta particije'
STR_DISK_2TB_MBR_ERROR='Prosim izberite GPT za particije nad 2TB'
STR_SHOW_ALL_DEV='Pokaži vse naprave'
STR_PART_ALIGN_4KB='Poravnaj particije na 4KB'
STR_WEB_COMMUNICATION_ERR='Napaka v komunikaciji: '
STR_WEB_REMOTE_ABNORMAL='Napaka v komunikaciji: oddaljena težava'
STR_WEB_REQUEST_TIMEOUT='Napaka v komunikaciji: čas je potekel'
STR_WEB_SERVICE_UNAVAILABLE='Napaka v komunikaciji: storitev ni na voljo'
STR_WEB_TOKEN_MISMATCH='Zahteva storitve je potekla, prosim poskusite kasneje.'
STR_WEB_SERVICE_BUSY='Storitev je zasedena, prosim poskusite kasneje.'

**Comment by ventoy** [comment]
Commited, thanks.
