### ISSUE TITLE
启动盘换到其他电脑又会被显示出来，有没有办法让他其他电脑也完全隐藏

### ISSUE THREAD

**Issue by jeromeli002** [ventoy/Ventoy#849]
启动盘换到其他电脑又会被显示出来，容易误删里面的文件。
有没有办法让他其他电脑也完全隐藏
或者类似成量产U盘成cd一样，不会被如删除文件

**Comment by ventoy** [comment]
没有办法。
最新的Windows10系统就是会显示出来，想隐藏也不行。
这个是EFI分区，必须老老实实的是一个正常的FAT分区，不能量产成CD，否则UEFI模式下就不能启动了。

误删也不要紧，更新一下就回来了。

**Comment by Sucareto** [comment]
分区格式改成GPT就不会显示出来了。
https://ventoy.net/cn/faq.html
第6条。

**Comment by ventoy** [comment]
MBR格式就是这样，在Windows 10以后的系统中想隐藏也没办法隐藏。 GPT是隐藏的。
