### ISSUE TITLE
Ventoy doesn't start on Legacy HP Laptop

### ISSUE THREAD

**Issue by jameslevalaisan** [ventoy/Ventoy#85]
Hi, I test with success your great tool on my Secure Boot PC but on my HP it doesn't start. With the last version, there is a black windows and with the 1.06 and 1.07 the screan show GRloading...... and nothing appends. I try two usb stick. A Windows10 make with rufus work also on this laptop.

I also try the usb key with venty on an very old HP laptop (2009) and it works.

I need to try on my actual PC but I'm pretty shure it will work.

I'm very happy to discovers this tool, I hope, we will find the issue (not only for my usage)

Regards
Daniel

**Comment by manosv** [comment]
Same ploblem here but in an Asus notebook.

**Comment by ventoy** [comment]
This is an old issue. I will close it now.
If you still have problem with latest Ventoy release, you can reopen the issue.
@jameslevalaisan
