### ISSUE TITLE
black screen on UEFI boot with serial_param unit=0

### ISSUE THREAD

**Issue by dcasota** [ventoy/Ventoy#851]
Hi,

This is the ventoy.json for an Azure UEFI booted linux virtual machine gen v2.
```
{
    "theme": {
        "display_mode": "serial_console",
        "serial_param": "--unit=0 --speed=115200 --word=8 --parity=no --stop=1"
    },
    "theme_legacy": {
        "display_mode": "serial_console",
        "serial_param": "--unit=0 --speed=115200 --word=8 --parity=no --stop=1"
    },
    "theme_uefi": {
        "display_mode": "serial_console",
        "serial_param": "--unit=0 --speed=115200 --word=8 --parity=no --stop=1"
    }
}
```

The ventoy serial console menu appears. I can see "UEFI" in the text mode ui, so the theme_uefi has been applied.
However, after selecting the Linux iso the screen drives black. In Azure boot diagnostics I can see the console output from the iso installer, but not on the serial console itself.

Before selecting the iso, F5>..>theme.. shows
```
display_mode: serial_console
serial_param --unit=0 --speed=115200 --word=8 --parity=no --stop=1
fonts NOT found

press ENTER to exit ...
```

In text mode ui > F5>..>'force text mode' looses the com setting, too.

**Comment by ventoy** [comment]
When you select the ISO file and press enter to boot, Ventoy will handover control to the bootloader (e.g. grub2) inside the ISO file.
So if the grub2 inside the ISO file use an graphical interface, you will not see the output from the console.
So you need to change the config file inside the ISO file (e.g. grub.cfg) to set console as its output device.
After that you need to add some boot options to the config file for the linux kernel, like `console=ttyS0,115200` to make sure that the log can also come to the console when the kernel is booting.

**Comment by dcasota** [comment]
Hi,
thank you for the prompt answer.

True <- The uploaded Linux distro vhd is precompiled with ```console=tty1 console=ttyS0,115200n8 earlyprintk=ttyS0,115200``` in grub.cfg. This is not the case using the distro' iso. Stupid me.

grub2 release 2.04 does not use ACPI Serial Port Console Redirection table yet. That's what might bring more flexibility. The discussion at https://lists.gnu.org/archive/html/grub-devel/2021-03/msg00255.html is ongoing.

Might be worth to study the change list of latest grub 2.06rc1 (https://github.com/rhboot/grub2). It contains much code changes since 2019. This sample [here](https://github.com/rhboot/grub2/commit/2d7c3abd871f6e45da35a72ac4609236141e2199) as example makes scenarios with a non-mandatory text-mode setting more relaxed.
