### ISSUE TITLE
能否将一块U盘作为Ventoy启动盘的同时，安装一个Linux系统？

### ISSUE THREAD

**Issue by forliuyifei** [ventoy/Ventoy#852]
昨天尝试了一下，第一步制作 ventoy 启动 U盘 A，此时有两个分区1和2。

然后用另一块 U盘 B 启动 Ubuntu 打算安装到 A，将 A 的大分区1删掉，重建 EFI 分区6，ext4 分区1，留 4G 空间作为 FAT32 分区5，指望把 ISO 文件放这里也能用。（别问我为什么分区号这么怪，4还不见了，3和5之间有1kb🤣）

成功将 Ubuntu 装在U盘A，但这时候我发现Ventoy引导损坏了，难道ISO文件必须放在编号第一的分区吗？

如果标题是可行的，请指导我一下，感觉挺有意思。

**Comment by forliuyifei** [comment]
这需求可能有点怪，但要是真能实现的话，美滋滋啊。

**Comment by ventoy** [comment]
Ventoy安装之后分区1和分区2的位置、大小都不能动。
你只能在安装Ventoy的时候选择在U盘最后保留一部分空间。然后在这段空间上再分区安装Linux系统。
是可行的，不过要注意不能安装启动文件，也就是安装之后的系统只有系统分区文件、没有启动相关的东西。
启动时先进入Ventoy，然后通过Ventoy引导进入Linux系统。

这种其实使用Linux vDisk插件更方便 https://www.ventoy.net/cn/plugin_vtoyboot.html

**Comment by forliuyifei** [comment]
> 启动时先进入Ventoy，然后通过Ventoy引导进入Linux系统。

请问这个要怎么实现呢？有可以编写类似grub的配置文件，让ventoy进行引导并进入Linux系统吗？
不想用vdisk，感觉不够灵活。

**Comment by ventoy** [comment]
Ventoy 支持自定义grub配置文件，通过F6加载。至于怎么写这个配置文件就看自己的需求了。
https://www.ventoy.net/cn/plugin_grubmenu.html

**Comment by forliuyifei** [comment]
有空再折腾

**Comment by lpwm** [comment]
> 有空再折腾

我折腾成功了~ 记录了一下过程: https://lpwmm.blog.csdn.net/article/details/119056455
