### ISSUE TITLE
[HELP] Need help on how should be installed GRUB2FM into Ventoy for booting WinXP_SP3 ISO? 

### ISSUE THREAD

**Issue by cinnamonmatexfce** [ventoy/Ventoy#853]
As in title.
I wasn't able to find instructions on how to install and where to put files.
How should I do? Please explain, thanks.

How should be installed this?: https://github.com/a1ive/grub2-filemanager/releases/tag/v7.4.0
Where should I put Windows XP SP3 ISO?

What configuration files should I create / modify?

I'm on Linux.

Best Regards

**Comment by ventoy** [comment]
Download `grubfm_multiarch.iso` and put it in the USB stick as an normal ISO file.
When you boot into Ventoy's menu, select and boot  `grubfm_multiarch.iso` as an normal ISO file.

**Comment by cinnamonmatexfce** [comment]
Solved. Thanks!
