### ISSUE TITLE
Ventoy doesn't recognize my keyboard

### ISSUE THREAD

**Issue by Keviny9** [ventoy/Ventoy#854]
I have a error with my Wireless Keyboard, my normal USB keyboard and my old P2 keyboard work on Ventoy, but my current wireless keyboard does not work on ventoy, but when the windy screen (OS boot) passes, the keyboard is recognized and works perfectly

Edit 1: I tested it in qemu and the keyboard work.
![Peek 18-04-2021 09-53](https://user-images.githubusercontent.com/38106355/115146261-19fdca00-a02c-11eb-923e-c3dc3be6cfcb.gif)

**Comment by ventoy** [comment]
Ventoy is based on grub2.
When at Venoy's boot menu, grub2's usb driver will be used to recognize usb devices(include your kerboard).
When you boot into OS, the linux's/Windows's driver will be used to recognize usb devices(include your kerboard).
When you use qemu, the keyboard inside the VM is virtualized and is not correspond to your usb keyboard.

So the problem may be that your usb keyboard is not supported in grub2. You can do the following test:
1. Write an ubuntu ISO file to a USB stick with Rufus.
2. Reboot your computer and boot into the USB stick
3. Check that whether your keyboard work well in the Ubuntu's grub2 boot menu.

**Comment by Keviny9** [comment]
Thanks, I will test

**Comment by a1ive** [comment]
> Ventoy is based on grub2.
> When at Venoy's boot menu, grub2's usb driver will be used to recognize usb devices(include your kerboard).
> When you boot into OS, the linux's/Windows's driver will be used to recognize usb devices(include your kerboard).
> When you use qemu, the keyboard inside the VM is virtualized and is not correspond to your usb keyboard.
> 
> So the problem may be that your usb keyboard is not supported in grub2. You can do the following test:
> 
> 1. Write an ubuntu ISO file to an USB stick with Rufus.
> 2. Reboot your computer and boot into the USB stick
> 3. Check that whether your keyboard work well in the Ubuntu's grub2 boot menu.

> When at Venoy's boot menu, grub2's usb driver will be used to recognize usb devices(include your kerboard).

I don't think so. GRUB2 only calls UEFI gST->ConIn->ReadKeyStroke or BIOS int16h to get the keys.
If suitable HCI drivers (ohci/ehci/uhci) are not loaded, `usb_keyboard` will not work.
But on the other hand, if these drivers (ohci/ehci/uhci) are loaded, there is no way to access the disks via UEFI/BIOS.

**Comment by Keviny9** [comment]
> I don't think so. GRUB2 only calls UEFI gST->ConIn->ReadKeyStroke or BIOS int16h to get the keys.
> If suitable HCI drivers (ohci/ehci/uhci) are not loaded, `usb_keyboard` will not work.
> But on the other hand, if these drivers (ohci/ehci/uhci) are loaded, there is no way to access the disks via UEFI/BIOS.
I did the test by formatting the Mint on my Pen Drive and ended up discovering the cause of the error, I was starting the pendrive in legacy mode, I switched to UEFI mode in Bios and my keyboard now works normally both in Mint's Grub, when currently Ventoy,

**Comment by Keviny9** [comment]
I did the test by formatting the Mint on my USB stick and ended up discovering the cause of the error, I was starting the USB stick in legacy mode, I switched to UEFI mode and my keyboard now works normally in both Mint and currently Ventoy,

**Comment by Keviny9** [comment]
I did the test by formatting the Mint on my USB stick and ended up discovering the cause of the error, I was starting the USB stick in legacy mode, I switched to UEFI mode and my keyboard now works normally in both Mint and currently Ventoy,

**Comment by NXzzz** [comment]
How did you switch to UEFI? I have my MacBook Air 2011 with the keyboard not working and my USB keyboard is not recognized by Ventoy, and my keyboard is recognized in other interfaces Linux.

**Comment by Keviny9** [comment]
Try in Bios idk about key is used in MacBook
