### ISSUE TITLE
无法安装deepin 20.2

### ISSUE THREAD

**Issue by meilihao** [ventoy/Ventoy#856]
原先deepin 20.1还是能用ventoy安装的, 但20.2不行. 选中20.2的iso后无法进入deepin安装器界面反而是小米笔记本重启了.

**Comment by ventoy** [comment]
https://www.ventoy.net/cn/faq.html#faq_boot_checksum

请先按照这里的说明，校验一下ISO文件，确保ISO文件没有损坏。

**Comment by meilihao** [comment]
确实是iso拷贝时损坏了，重新处理并检验哈希后已能正常安装。
