### ISSUE TITLE
如何在kickstart文件的%post执行优盘内的脚本

### ISSUE THREAD

**Issue by RyanDx** [ventoy/Ventoy#857]
我的后处理脚本和需要的第三方包都在优盘内，希望自动安装过系统之后调用优盘路径内的这些东西，优盘默认挂在在什么路经啊，还有自动安装的os镜像缓存在哪个目录啊，感谢🙏！

**Comment by RyanDx** [comment]
> U盘存放ISO文件的分区在启动之后是不能访问的。
> 
> 如果需要有2种方案：
> 
> 1. 把这些文件打包放到ISO文件里面
> 
> 2. 安装 Ventoy 的时候，在U盘最后保留一部分空间，创建第3或第4个分区，然后把文件放到这里面。
> 
> 
> 
> 
> 
> 

如果用第二个方法的话，这个分区会自动挂载嘛？这个分区必须是fat32嘛？挂载规则也是/dev/sd+字母+数字嘛？或者是不是需要自己用命令获取这个盘的具体的盘符，类似于disk=lsblk |egrep -o '(sd[a-z]|nvme[0-9]n[0-9]).*VTOYEFI$'|awk '{print $1}' |egrep -o '(sd[a-z]|nvme[0-9]n[0-9])'

**Comment by ventoy** [comment]
这个都需要自己去做。不会自动挂载，需要自己找到设备、分区、自己挂载。

**Comment by RyanDx** [comment]
> 这个都需要自己去做。不会自动挂载，需要自己找到设备、分区、自己挂载。

那优盘设备的VTOYEF分区，用lsblk列出来的话，输出的设备信息一定是sd开头和VTOYEF结尾吧，能否提供一条获取优盘设备sd号的命令，我想参考一下，谢谢🙏

**Comment by ventoy** [comment]
sd开头不一定， VTOYEFI肯定有。
另外，你可以这样来精确找出Ventoy对应的U盘到底是哪个？ 是 /dev/sda 还是 /dev/sdb 还是 /dev/hda 还是谁。

执行  `dmsetup table ventoy`  命令，输出结果类似如下格式：
`0 12345 linear 8:1 56789`

其中中间的 `8:1` 表示设备号，其中8表示主设备号。然后你就去找哪个盘的主设备号是8就可以了。
找到是 sda 就是 sda 是 sdb 就是sdb，然后你对应的第三个分区自然就是  sda3/sdb3
磁盘的主设备号从下面这个文件里面可以读到：（以 sda 为例）
`cat  /sys/block/sda/dev`  里面的内容格式类似：  `8:0`   前面这个就是主设备号。

**Comment by ventoy** [comment]
```
VentoyMajor=$(dmsetup table ventoy | grep -m1 line | sed "s/.* \([0-9]*\):.*/\1/")
VentoyDisk=$(ls /dev | grep "$Major, *0" | awk "{print $NF}")
```

上面的命令应该能获取到， VentoyDisk 最后的值即为Ventoy所在U盘的名称，比如  sda/sdb/hda...
如果使用的是Nvme/SD卡等，分区名是磁盘名称后面加 p1/p2/p3 如果就是普通的U盘的话，直接加 1/2/3 即可

**Comment by RyanDx** [comment]
> ```
> 
> VentoyMajor=$(dmsetup table ventoy | grep -m1 line | sed "s/.* \([0-9]*\):.*/\1/")
> 
> VentoyDisk=$(ls /dev | grep "$Major, *0" | awk "{print $NF}")
> 
> ```
> 
> 
> 
> 上面的命令应该能获取到， VentoyDisk 最后的值即为Ventoy所在U盘的名称，比如  sda/sdb/hda...
> 
> 如果使用的是Nvme/SD卡等，分区名是磁盘名称后面加 p1/p2/p3 如果就是普通的U盘的话，直接加 1/2/3 即可
> 
> 

感谢，对了，第二条命令用到的$Major 指的是上一个变量VentoyMajor吗

**Comment by ventoy** [comment]
是 VentoyMajor， 写错了，已经更新。
