### ISSUE TITLE
Support of glob patterns

### ISSUE THREAD

**Issue by GHNewbiee** [ventoy/Ventoy#859]
*Glob patterns* would be helpful to avoid making **unnecessary** changes to the names.

**Example**
A new version (*neon-user-20210422.iso*) comes out and I want to check/test it. I have to **change** the old name (*neon-user-20210415.iso*) into the new one in `ventoy.json` as below. That does happen **every** single week! With *glob patterns* that change would be **avoided**. Escaping special characters has also to be considered.

```json
{
   ...,
    "menu_class" : [
        ...,
        {
              "key": "neon",
            "class": "kdeneon"
        },
        ...
    ],
    "menu_alias" : [
        ...,
        {
-           "image": "/Ubuntu_based/KDEneon/neon-user-20210415.iso",
+           "image": "/Ubuntu_based/KDEneon/neon-user-20210422.iso",
!           "image": "/Ubuntu_based/KDEneon/neon-user-*.iso",
            "alias": "KDEneon - Stable"
        },
        ...
    ],
    ...
}
```
*Tia*

**Comment by ventoy** [comment]
You can test with this CI release:
https://github.com/ventoy/Ventoy/actions/runs/780095502

I add a simple * match feature.
But for simplicity, the * fuzzy matching is much different with our common usage.
```
A * is fixed to match only 1 character, if you want to match multiple characters, you need to write multiple *
```
So you can set :
```
{
    "menu_alias" : [
        {
            "image": "/Ubuntu_based/KDEneon/neon-user-********.iso",
            "alias": "KDEneon - Stable"
        }
    ]
}
```

**Comment by GHNewbiee** [comment]
That's cool! It does work fine!

But unfortunately, it only works for distros which follow a **fixed** number of characters file name pattern. For those which follow a "**simplified**" semver pattern (e.g linuxmint-20, linuxmint-20.1 instead of linuxmint-20.0), it doesn't work.

Does it also apply for "**persistence**" file names? *Tia*

**Comment by ventoy** [comment]
For these distros 2 or 3 entries should be enough.
```
{
    "menu_alias" : [
        {
            "image": "/linuxmint-20.iso",
            "alias": "linuxmint20"
        },
        {
            "image": "/linuxmint-20**.iso",
            "alias": "linuxmint20"
        },
        {
            "image": "/linuxmint-20***.iso",
            "alias": "linuxmint20"
        }
    ]
}
```

1.0.42 released with this feature for `menu_alias/image_list/auto_install/persistence` plugins.

**Comment by GHNewbiee** [comment]
This workaround does help to "solve the problem" but it is a bit "crude". If you are happy with that and you do not have a second thought for improvement than you may close the issue. It's up to you. Thanks.

**Comment by ventoy** [comment]
OK.
Most important that it's very very simple to implement.
