### ISSUE TITLE
[Feature Request] Make menu_class keys case insensitive

### ISSUE THREAD

**Issue by DanGM96** [ventoy/Ventoy#862]
Checked #476, #579 and #859 but they aren't exactly solutions.

My propose: support for _keys_ to match files with same characters (windows/Windows/WINDOWS) to easily get icons.

Why: Only reason is to keep aesthetically pleasing filenames without having to create an entry for each file (either for _keys_ or for _aliases_) if you want to use the same icon. Example [here](https://github.com/Teraskull/bigsur-grub2-theme/blob/master/screenshots/bigsur.png).

Current alternatives:

- Create a new _menu_class_ entry for each filename, like: `{"key": "ubuntu",  "class": "ubuntu"}, {"key": "Ubuntu",  "class": "ubuntu"}`.
- Use _*_ for the first letter, but it would not help with distros that have the same first letter (windows/lindows, kubuntu/lubuntu/xubuntu).

**Comment by ventoy** [comment]
Maybe this CI release can help:
https://github.com/ventoy/Ventoy/actions/runs/781797811

A `parent` optioin  added to the menu_class plugin.
```
{
    "menu_class": [
        {
            "parent": "/ISO/Windows",
            "class": "windows"
        }
    ]
}
```

In the sample above, all the ISO files under `/ISO/Windows`  directory (include subdirectories) will use the same class.

**Comment by DanGM96** [comment]
A very good solution, thank you for this!
