### ISSUE TITLE
Common persistence backend file

### ISSUE THREAD

**Issue by GHNewbiee** [ventoy/Ventoy#866]
Since a **persistence "backend"** file can be used by more than one **"image"** files, it would be more elegant to make **"image"** to be either of a **string** or of an **array of strings** type. So, we would be able to write:

*ventoy.json*
```json
{
  ...
  "persistence" : [
    ...,
    {
      "image" : [
        "/path/to/1st-distro.iso",
        "/path/to/2nd-distro.iso",
        ...
      ],
      "backend": "/vtoycow.img"
    },
    ...
  ]
  ...
}
```
*Tia*

**Comment by ventoy** [comment]
I think the current format is enough. No time and plan for this enhanced format, sorry.
