### ISSUE TITLE
USB drive shows up twice in the boot menu.

### ISSUE THREAD

**Issue by Battler624** [ventoy/Ventoy#872]
I am guessing this isn't supposed to happen? anyway, whenever I install ventoy then I go to the bios I see the same usb drive twice, one of the 2 options wont work and the other shows up the ventoy menu.

Is this somehow fixable?

**Comment by AndRo-Marian** [comment]
If you have the Legacy and UEFI activated should be show 2 with the same USB Drive.
One of them is the USB name and other other has the prefix with UEFI: USB Name.

Not sure why the other not working but is that with UEFI prefix?

**Comment by Battler624** [comment]
Both options show up as uefi, I have legacy disabled.

As you can see here. ![20210501_232906.jpg](https://user-images.githubusercontent.com/9511158/116794352-0dba4800-aad5-11eb-9bc7-88966c598c6b.jpg)

**Comment by steve6375** [comment]
Is there a BIOS update available for your PC?

**Comment by Battler624** [comment]
There is something weird ill test in a bit

When installing a Linux distribution I saw my ventoy with 3 partitions, ventoy1,ventoy2,ventoy3.

Ventoy3 is 0mb, is that Normal?

**Comment by Battler624** [comment]
> Is there a BIOS update available for your PC?
> How was the drive formatted and partitioned? Is there really two 61GB partitions on it?

No, its a total 64gb drive, I partitioned it used ventoy, I am on the latest bios and this only happens with ventoy.

I'm going to test other usb devices to isolate the issue in a bit.

**Comment by Battler624** [comment]
Did some testing, all in all I am certain ventoy is causing it somehow.

![20210502_040016.jpg](https://user-images.githubusercontent.com/9511158/116798877-99939a80-aafc-11eb-8bf6-8131e796394e.jpg)


![20210502_040030.jpg](https://user-images.githubusercontent.com/9511158/116798879-9bf5f480-aafc-11eb-924c-19bde18153eb.jpg)


As you can see, the first image is my ventoy install and the second is simply flashing the iso using rufus in which I don't get the double partition issue.

**Comment by steve6375** [comment]
You still haven't answered my question - **how** was the drive partitioned and formatted.
Is partition 1 and 2 exFAT, NTFS, FAT32, ext4, ?  MBR or GPT?
Can you see a \EFI folder on partition 1 **and** partition 2 - or only on partition 2.
Do you get the same issue if you wipe and make a fresh Ventoy drive using default settings?

**Comment by Battler624** [comment]
> You still haven't answered my question - **how** was the drive partitioned and formatted.
> Is partition 1 and 2 exFAT, NTFS, FAT32, ext4, ?  MBR or GPT?
> Can you see a \EFI folder on partition 1 **and** partition 2 - or only on partition 2.
> Do you get the same issue if you wipe and make a fresh Ventoy drive using default settings?

The drives were formatted and partitioned using ventoy, iirc I saw them on gparted as fat16 and ext4.

No idea if they are mbr or gpt ill check them in a bit.

I can't see any efi folder at all, probably because I can only see 1 partition while in Windows 

Again the drives were fresh wiped,partitioned and formatted using ventoy.

**Comment by steve6375** [comment]
Thanks
When you say 'using Ventoy' do you mean the VentoyToDisk.exe Windows executable or the  Linux Ventoy script?
Maybe you could try creating a Ventoy disk with an NTFS partition instead of ext4?

**Comment by Battler624** [comment]
> Thanks
> When you say 'using Ventoy' do you mean the VentoyToDisk.exe Windows executable or the  Linux Ventoy script?
> Maybe you could try creating a Ventoy disk with an NTFS partition instead of ext4?

Ventoy2disk on Windows.

I'll try changing it to ntfs, gimme 10 minutes and I'll report back

**Comment by Battler624** [comment]
So now Partition 1 is set to Fat16 and Partition 2 is set to NTFS, they both still show up on the bios.

So no luck.

**Comment by steve6375** [comment]
Maybe your bios is just showing a uefi boot option for each partition on the usb drive, regardless of what is on it? So if you just created three empty formatted partitions do you get three bios entries?

**Comment by Battler624** [comment]
I'll test and report back in a couple of hours.

**Comment by Battler624** [comment]
It is exactly like you said, each partition shows up as its own thing in the bios.

**Comment by steve6375** [comment]
I would consider that a BIOS bug. Maybe you could report it and ask for BIOS update?

**Comment by Battler624** [comment]
^ i tried reporting it but no luck.

I am wondering if you guys can somehow fix this by making the partition that you boot from also the one where you save the isos? maybe inside a folder?

**Comment by Battler624** [comment]
I know that its a bios bug, I am trying to find a workaround to this bug other that manually pressing the second partition.

**Comment by Battler624** [comment]
Are exfat and ntfs not bookable? (I guessing the latter no but the former yes?
