### ISSUE TITLE
mx-linux persistence not working

### ISSUE THREAD

**Issue by jlslinux** [ventoy/Ventoy#875]
Hi
Mx-linux cannot use persistence.
I've created the persistence file but it doesn't get loaded by mx

**Comment by ventoy** [comment]
Some details about the problem? Better with soime photos.
Does your json configuration take affect?
Do you see the prompt menu?
Which ISO file do you test?
Which persistence file did you use? (MX-Persist label must be used)

**Comment by ventoy** [comment]
This is an old issue. I will close it now.
If you still have problem with latest Ventoy release, you can reopen the issue.
