### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by zjacai** [ventoy/Ventoy#880]
dell vostro 3400

![微信图片_20210506155723](https://user-images.githubusercontent.com/20898457/117262517-ecb27800-ae83-11eb-8ca7-5378ff307c73.jpg)
![微信图片_20210506155728](https://user-images.githubusercontent.com/20898457/117262519-ee7c3b80-ae83-11eb-8760-62713ac8d896.jpg)

**Comment by ventoy** [comment]
这个不是错误，是安全启动相关的设置，首次启动你需要参考下面的说明设置一次。
https://www.ventoy.net/cn/doc_secure.html
