### ISSUE TITLE
WinPE Optional Components

### ISSUE THREAD

**Issue by AdamKearn** [ventoy/Ventoy#881]
Hey,

**Background:**
My current setup/config is amazing.    I use Ventoy to inject a ZIP file that makes some modifications to my WIM image that prompts for PC name and runs an unattended setup.     This works really well for me and the other guys where I work.

(I work in IT support so we are often reinstalling or setting up new computers with windows)
The process has been speedup soo quickly using Ventoy now it takes about 7mins to wipe and reinstall windows which makes things a lot easier for us.

**Issue:**
My current setup runs a batch script before the `setup.exe` and allows me to enter a custom computer name.
Which then updates the `unattended.xml` file to use the name provided in the script.
This works really well at the moment.   But I would like to upgrade this and instead use a GUI.
I was thinking of using an HTA application as they are very simple to create.
But it looks like for HTA applications to run inside the WinPE environment you need to import the `WinPE-HTA` package.   (See [https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpe-add-packages--optional-components-reference](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpe-add-packages--optional-components-reference))

To import this I have to use DISM to modify the `boot.wim` file to include this package.
But this means modifying the ISO file for every windows update.
At the moment as long as the ISO is called the same my setup works on any windows version without any modifications to the ISO as it gets injected using the ZIP file.

Do you think you could add support for Importing `WinPE Optional Components` at Run-Time instead of Build-Time?

Thanks.    I Love this project!!!!

What my Config Currently Looks like:
![image](https://user-images.githubusercontent.com/30593259/117267238-fa4d0b00-ae4d-11eb-9849-d806ff5d12e8.png)
![image](https://user-images.githubusercontent.com/30593259/117267435-2a94a980-ae4e-11eb-9a82-f2aef45439fc.png)

**Comment by ventoy** [comment]
Ventoy is just a bootloader and I don't know much about `WinPE Optional Components`.
So injection plugin is what I can only provide.

Maybe you can copy all the needed files to the WinPE environment and launch the GUI exe in your current bat script?

**Comment by AdamKearn** [comment]
Hey,  Thanks for the response.

I am just looking for a way to import the option components without having to modify the `boot.wim` manually every update.
Looks like I am going to have to go down the Win32 App instead.

I was hoping to use something simple like the .HTA applications like what I did in the above screen shot to show the computer name after installing windows.

Thanks anyway.
