### ISSUE TITLE
If no payloads found on partition 1 - cannot use F4 or F6 to select alternate menu

### ISSUE THREAD

**Issue by steve6375** [ventoy/Ventoy#883]
If no payload files are found, it reboots. This means we cannot use F6 or F4 or view options, etc.
F6 could load an alternate menu which could include a menu for other partitions (for instance) or user can use F4 to boot to other partitions, etc..

**Comment by ventoy** [comment]
If no payload files, it just show a menu `NO ISO files found (Press enter to reboot ...)`
But you can still press F4 F6 in the screen.

**Comment by ventoy** [comment]
F2 is OK too.
If no payload files,  only F3 is unavaliable, all other Fn key can work.

**Comment by steve6375** [comment]
Yes, but asking user to press ENTER to reboot is not helpful.
Its your choice.
