### ISSUE TITLE
ventoy cannot renew or remove the key used for secure boot.

### ISSUE THREAD

**Issue by QingKongBaiYu** [ventoy/Ventoy#884]
so it's not available to add new iso with secure boot enabled.
I have tried re-upgrade ventoy with secure boot support off and on, and reset BIOS setting, but no help.
is there any way to do that?

**Comment by ventoy** [comment]
Ventoy use https://github.com/ValdikSS/Super-UEFIinSecureBoot-Disk for secure boot.
You can consult the author for help.

**Comment by QingKongBaiYu** [comment]
> Ventoy use https://github.com/ValdikSS/Super-UEFIinSecureBoot-Disk for secure boot.
> You can consult the author for help.

thanks, problem solved.
