### ISSUE TITLE
安装好系统后，启动页面不好看，能自定义美化吗？

### ISSUE THREAD

**Issue by imic07** [ventoy/Ventoy#887]
如题，启动时候，显示GNU GRUB那个页面。如果能美化下就更好了
![image](https://user-images.githubusercontent.com/16321067/117564310-14048180-b0de-11eb-96b3-170a29b940d3.png)

**Comment by ventoy** [comment]
可以美化，https://www.gnome-look.org/browse/cat/109/order/latest/  这里有很多主题。
不过这个和Ventoy无关。你网上搜索 **grub2主题美化**，有很多相关说明。
