### ISSUE TITLE
Arch linux fail UEFI boot

### ISSUE THREAD

**Issue by og900aero** [ventoy/Ventoy#889]
There is a problem with the Arch linux UEFI boot again. When I try boot archlinux-2021.05.01-x86_64.iso in UEFI mode, get the error message:
"No bootfile found for UEFI!
Maybe the image does not support x64 UEFI"

**Comment by ventoy** [comment]
With the same Ventoy USB and computer:
Can you boot other distro OK ?(e.g. Ubuntu)
Can you boot old Arch linux release OK ?

**Comment by og900aero** [comment]
1. I can boot other distro: Debian 10.9 working fine.
2. I can boot older Arch linux. archlinux-2021.03.01-x86_64.iso working fine.

**Comment by ventoy** [comment]
I test `archlinux-2021.05.01-x86_64.iso` in VM and it boot fine in UEFI mode.
Please checksum the ISO file as follows:
https://www.ventoy.net/en/faq.html#faq_boot_checksum

**Comment by og900aero** [comment]
Checksum doesnt get error, but I downloaded again the file, and now booting fine. Thank u!
