### ISSUE TITLE
Where to download the Tested ISO Files

### ISSUE THREAD

**Issue by gshmu** [ventoy/Ventoy#89]
`213 Tested ISO Files (Updating)` but I searched the WinPE by google, I can't find the tested file.

can you add the tested iso link, or website url?

best wish for you and thank you.  I think you find the best solution for multi bootable.

**Comment by chromer030** [comment]
If you google exact ISO name , simply it can be found.

**Comment by gshmu** [comment]
<img width="844" alt="image" src="https://user-images.githubusercontent.com/1797676/81504784-cbc15080-931d-11ea-98a6-97047a5cc1f1.png">

**Comment by ventoy** [comment]
HBCD_PE_x64.iso should be found by google.

**Comment by ventoy** [comment]
Hi,
I will close the issue now, you can make a new issue if you still have some problem.
