### ISSUE TITLE
Proposal: Network center for ISOs and WIMs

### ISSUE THREAD

**Issue by jul-fls** [ventoy/Ventoy#890]
Hello, I have an idea to improve Ventoy, it would be to have the possibility to have files (iso, wim, vhd, etc... ) on a server and just like for a plugin or a theme, we could configure this plugin to list the bootable files on this server via FTP or samba share and it would load directly the image from this server without having to write it on the usb key with Ventoy, this would allow to have a centralized management of the bootable files on Ventoy in order to have for example several Ventoy usb keys which would have all the same bootable images, I think it would be very practical, because for example in my job (computer maintenance) I often have several PCs to repair at the same time so I use several ventoy usb sticks but when there is an update of a wim file of a software I have to deploy it on each stick whereas there I would put the new file on the server and the update is made on all the sticks, it would be very practical !
Do you think my idea is feasible?

**Comment by ventoy** [comment]
It's a good idea. But  all Ventoy's design and implementation are based on disk.  It can't work with network.

**Comment by jul-fls** [comment]
Ok, if it is not possible to have that, is there some alternatives that have these type of features ?

**Comment by ventoy** [comment]
I have no idea. 
PXE is network deployment solution. But it is fully based on network, no USB needed.

**Comment by jul-fls** [comment]
Ok thank you for your suggestion, i will search for that, thanks !
