### ISSUE TITLE
vtoyfat not found on linux (install error)

### ISSUE THREAD

**Issue by biggs** [ventoy/Ventoy#893]
After running the following commands:

``` bash
tar -xvpf Downloads/ventoy-1.0.43-linux.tar.gz && cd ventoy-1.0.43
sudo sh Ventoy2Disk.sh -i /dev/sda
```

I get the following error:
```

**********************************************
      Ventoy: 1.0.43  x86_64
      longpanda admin@ventoy.net
      https://www.ventoy.net
**********************************************

./tool/VentoyWorker.sh: line 71: vtoyfat: not found
Some tools can not run on current system. Please check log.txt for details.

```

And the log.txt gives:
```
############# Ventoy2Disk -i /dev/sda [x86_64] ################
Mon 10 May 13:53:27 BST 2021
MODE=install FORCE= RESERVE_SPACE= RESERVE_SIZE_MB=0
hexdump test ok ...
mkexfatfs test ok ...
vtoyfat test fail ...

```

This seems like it might be related to https://github.com/ventoy/Ventoy/issues/673 but I'm not sure.

**Comment by ventoy** [comment]
Which Linux distro do you use? (give the `uname -a` output)
Please try run  `./tool/x86_64/vtoyfat -T` manually.

Also you can use VentoyWeb.sh  https://www.ventoy.net/en/doc_linux_webui.html

**Comment by ventoy** [comment]
run `file  ./tool/x86_64/vtoyfat`

**Comment by biggs** [comment]
Oops, sorry that got cut off, the error was:
``` ./VentoyWeb.sh: line 103: ./tool/x86_64/V2DServer: No such file or directory ```

and the output of file is:
```
./tool/x86_64/vtoyfat: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=0616ab6ecebc2db89a411d53a068eb536d009106, stripped

```

**Comment by biggs** [comment]
`ls -l` gives
```
-rwxr-xr-x 1 root  root   35248 May 10 13:53 vtoyfat
```

**Comment by ventoy** [comment]
1.  replace `./tool/x86_64/vtoyfat` with https://github.com/ventoy/statictool/tree/main/ventoy/tool/x86_64/vtoyfat
2.  replace `./tool/x86_64/mkexfatfs` with https://github.com/ventoy/statictool/tree/main/ventoy/tool/x86_64/mkexfatfs
3. chmod +x `./tool/x86_64/vtoyfat` 
4. chmod +x `./tool/x86_64/mkexfatfs` 
5. retry Ventoy2Disk.sh

**Comment by biggs** [comment]
That worked! Amazing, thank you. Did you figure out what the issue was?

**Comment by biggs** [comment]
Ah, I imagine the compile has a hard link to some shared library, which will be in a different place on NixOS. Thanks, I'll mark this as closed.

**Comment by marcelarie** [comment]
> 1. replace `./tool/x86_64/vtoyfat` with [https://github.com/ventoy/statictool/tree/main/ventoy/tool/x86_64/vtoyfat](https://github.com/ventoy/statictool/tree/main/ventoy/tool/x86_64/vtoyfat?rgh-link-date=2021-05-11T16%3A21%3A14Z)
> 
>     2. replace `./tool/x86_64/mkexfatfs` with [https://github.com/ventoy/statictool/tree/main/ventoy/tool/x86_64/mkexfatfs](https://github.com/ventoy/statictool/tree/main/ventoy/tool/x86_64/mkexfatfs?rgh-link-date=2021-05-11T16%3A21%3A14Z)
> 
>     3. chmod +x `./tool/x86_64/vtoyfat`
> 
>     4. chmod +x `./tool/x86_64/mkexfatfs`
> 
>     5. retry Ventoy2Disk.sh

This fix it for me. I use NixOS. thanks!

**Comment by jsw08** [comment]
> 1. replace `./tool/x86_64/vtoyfat` with https://github.com/ventoy/statictool/tree/main/ventoy/tool/x86_64/vtoyfat
> 2. replace `./tool/x86_64/mkexfatfs` with https://github.com/ventoy/statictool/tree/main/ventoy/tool/x86_64/mkexfatfs
> 3. chmod +x `./tool/x86_64/vtoyfat`
> 4. chmod +x `./tool/x86_64/mkexfatfs`
> 5. retry Ventoy2Disk.sh

This fixed it for me 2 lmao, i use NixOS as well. Thank you and I love your project.

**Comment by mkellyxp** [comment]
Quick Note for anyone using NixOS.  I just found a great work around that is quite a bit faster than copying files.

Run ventoy from inside a nix-shell with extfat.  So:

nix-shell -p exfat
sudo ./Ventoy2Disk.sh -i /dev/sda

Worked perfectly for me

**Comment by iloveyumyumshrimpnoodles** [comment]
> 1. replace `./tool/x86_64/vtoyfat` with https://github.com/ventoy/statictool/tree/main/ventoy/tool/x86_64/vtoyfat
> 
>     2. replace `./tool/x86_64/mkexfatfs` with https://github.com/ventoy/statictool/tree/main/ventoy/tool/x86_64/mkexfatfs
> 
>     3. chmod +x `./tool/x86_64/vtoyfat`
> 
>     4. chmod +x `./tool/x86_64/mkexfatfs`
> 
>     5. retry Ventoy2Disk.sh

Fixed it for me too.
Running Void Linux with `musl` instead of `glibc`.
