### ISSUE TITLE
Issue with Parted Magic

### ISSUE THREAD

**Issue by peter099** [ventoy/Ventoy#897]
Ventoy doesn't seem to work with the latest Parted Magic version 2021.02.28. I am starting it with the default setting (from ram). It copies the files to ram, then starts the services and before showing the graphical interface the screen goes black and stays that way. 
With the previous version 2020.08.23 i don't have issues, but the latest doesn't seem to work.

**Comment by ventoy** [comment]
1. Can it boot fine if you use Rufus to write the ISO file to the USB?
2. Can Parted Magic version 2021.05.12 works?

**Comment by peter099** [comment]
Interesting, i tested the usb on my other laptop - Thinkpad T420, and version 2021.02.28 booted fine. The laptop with which i have issue is HP Elitebook 8560w with nvidia card, and i think the nvidia drivers that parted magic is trying to use by default are the issue. I saw that there is a option 'No official nvidia driver' on boot, which is using the open source nouveau driver, and when i select it Parted Magic is starting fine, no black screen.

Version 2021.05.12 is also working fine.

**Comment by ventoy** [comment]
OK, seems not Ventoy's issue.
I will close this issue now.
