### ISSUE TITLE
Apply password multiple files

### ISSUE THREAD

**Issue by rehannali** [ventoy/Ventoy#898]
Hi, i want to set password password for all files and yes, i read all documentation.
I have multiple iso and img files and it is pain to add each and every file in config file. I try to use `*` with standard behaviour i.e. `/*.iso` password1 and `/*.img` password2, password apply automatically on each iso and img file. 
It won't work. I also find out `*` is only used for single character. Which is annoying.

Is there anyway to achieve the above mentioned behaviour so i don't have to mentioned all files in `ventoy.json`.

**Comment by ventoy** [comment]
You can test this CI release. https://github.com/ventoy/Ventoy/actions/runs/842452885
I add `isopwd` `wimpwd` `efipwd` `imgpwd` `vhdpwd` `vtoypwd` options in password plugin to set default password for `.iso` `.wim` ... files.


```
{	
	"password": {
        "isopwd": "txt#123",
        "imgpwd": "txt#abc"
    }
}
``` 
In this case all the .iso files will have a same password `123` by default.
  
  
  

```
{	
	"password": {
        "isopwd": "txt#123",
        "imgpwd": "txt#abc",
        "menupwd": [
            {
                "file":"/archlinux.iso",
                "pwd":"txt#456"
            }
        ]
    }
}
``` 
In this case, `/archlinux.iso` will have a password `456`, all other ISO files will have the default password `123`.

**Comment by rehannali** [comment]
@ventoy hi, thanks for reply. Does i have to provide path for iso or other formats? What if we need to give folder1 > all ios pass 123 and folder2 > all iso 456. How can we achieve this?

**Comment by ventoy** [comment]
You can test this CI release https://github.com/ventoy/Ventoy/actions/runs/843858209. 
I add `parent`option in password plugin.

```
{	
	"password": {
        "isopwd": "txt#123",
        "imgpwd": "txt#abc",
        "menupwd": [
            {
                "parent":"/iso1",
                "pwd":"txt#123"
            },
            {
                "parent":"/iso2",
                "pwd":"txt#456"
            }
        ]
    }
}
``` 
In this case, all files under `iso1` directory will have a password `123`, so as `iso2` with `456`.
All files mean all `.iso/.wim/.img ...` files. If you want to set different passwords for `.iso` and `.wim` you must put them in different directories.

**Comment by ventoy** [comment]
You can test with the latest 1.0.44

**Comment by rehannali** [comment]
@ventoy I've tested this with latest version and it is working perfectly fine. Although, i have a question. 
`parent` key required path to a folder. I tried with `/` i.e. main folder and it won't work. Maybe this key doesn't work with this design, don't know. I encounter this issue and i thought it is worth discussing this.

**Comment by ventoy** [comment]
Try this CI release: https://github.com/ventoy/Ventoy/actions/runs/868861368

**Comment by ventoy** [comment]
This is an old issue. I will close it now.
If you still have problem with latest Ventoy release, you can reopen the issue.
