### ISSUE TITLE
Some Issues

### ISSUE THREAD

**Issue by chromer030** [ventoy/Ventoy#9]
Hi.
During testing various Distros , i faced in some issues , i dont know it's about my hardwares faults or it's universal.

1- In Legacy BIOS mode , UI is a little laggy , means that there is a little lag about timeout in pressing up and down keys.
2- screen flickering  on booting some ISOS on BIOS mode like Septor linux.

**Comment by a1ive** [comment]
> 1- In Legacy BIOS mode , UI is a little laggy , means that there is a little lag about timeout in pressing up and down keys.

run `terminal_output console` in terminal?

**Comment by chromer030** [comment]
how to access Ventoy Terminal to enter _terminal_output console_ ?

**Comment by a1ive** [comment]
> how to access Ventoy Terminal to enter `terminal_output console` ?

Press 'C' (It's based on grub2).

**Comment by chromer030** [comment]
after entering `terminal_output console` , screen will move to another console :
**Grub> __**
even there entered `terminal_output console` but nothing happened.

**Comment by ventoy** [comment]
After entering terminal_output console   press ESC to come back to the boot menu with no backgroud picture

**Comment by chromer030** [comment]
@a1ive @ventoy  Thanks very much for help , for first issue , i can boot ISOs without problem even with lag etc. i just wanted to report.
For second issues , i think it's about firmwares because the same ISO run great on UEFI.
Thanks again.
