### ISSUE TITLE
Win安装程序无法检测到已安装版本

### ISSUE THREAD

**Issue by llllllllqq** [ventoy/Ventoy#90]
安装ventoy到u盘后，对分区表后面添加一些东西（比如用ventoy启动grub2再partnew一个iso会添加一个虚拟的分区），但不破坏原有分区，ventoy安装程序不能识别已安装到u盘的版本。
但可以正常点升级进行升级而不破坏任何数据/分区表。

**Comment by ventoy** [comment]
ventoy对分区表的检查比较严格， 你动过了，它就认为被改过了，ventoy可能被破坏了，所以会这样。当然也仅仅是检查这一步，你还是可以进行update, partnew的那个虚拟分区表又会被清零。

**Comment by llllllllqq** [comment]
> ventoy对分区表的检查比较严格， 你动过了，它就认为被改过了，ventoy可能被破坏了，所以会这样。当然也仅仅是检查这一步，你还是可以进行update, partnew的那个虚拟分区表又会被清零。

感谢回复。但升级操作后，那个partnew的分区还在，不过不影响使用。希望日后可以支持多分区的结构（手动选择efi分区），移动硬盘上比较方便。

**Comment by ventoy** [comment]
哦， 是没清楚，我记错了。 只是无法识别版本号，实际上功能正常。
把那个partnew的分区表清零了就可以识别了。
