### ISSUE TITLE
Be able to put ventoy on a partition without erasing entire drive

### ISSUE THREAD

**Issue by nutterthanos** [ventoy/Ventoy#904]

**Comment by ventoy** [comment]
Ventoy can not be installed into a partition.
Ventoy must occupy the whole disk and reformat it. That's how it designed from the beginning.

**Comment by nutterthanos** [comment]
> Ventoy can not be installed into a partition.
> Ventoy must occupy the whole disk and reformat it. That's how it designed from the beginning.

why?
