### ISSUE TITLE
Request for fuzzy matching in injection plugin and parent support in both auto-installation and injection plugin

### ISSUE THREAD

**Issue by devdevadev** [ventoy/Ventoy#907]
It will be very useful if * fuzzy matching also available in injection plugin. This way I don't have to edit ventoy.json again and again when update same type of ISOs.

I use 
SMART_XML_WIN10.xml for all ISOs of /ISO/WINDOWS/WIN10 folder
SMART_XML_WIN81.xml for all ISOs of /ISO/WINDOWS/WIN81 folder
SMART_XML_WIN7.xml for all ISOs of /ISO/WINDOWS/WIN7 folder

I inject start_vtoy.7z for all ISOs of /ISO/WINDOWS folder

It will be very useful in I can use 'parent' feature in both Auto-Installation and Injection plugin...

Thanks in Advance....
Regards....

**Comment by ventoy** [comment]
The  * fuzzy matching can be used in injection plugin and auto-install plugin.
https://www.ventoy.net/en/plugin_injection.html
https://www.ventoy.net/en/plugin_autoinstall.html

**Comment by devdevadev** [comment]
What about parent option in in both auto installation and injection plugin ?

**Comment by ventoy** [comment]
You can test with this CI release: https://github.com/ventoy/Ventoy/actions/runs/847002828
I add `parent` option in auto_install and injection plugin.

**Comment by devdevadev** [comment]
Thank you so much.....Lord Longpanda

**Comment by ventoy** [comment]
> Thank you so much.....Lord Longpanda
> 
> I want to know how exactly Ventoy mount and boot windows ISOs ? Few months ago I had seen topic related to this topic in your site but currently I am unable to find that article which describes how exactly windows isos works ?
> 
> Please provide me link of that article....


http://reboot.pro/index.php?showtopic=22277&p=214750

**Comment by ventoy** [comment]
The official website always there.  https://www.ventoy.net/
Can you visit it?
