### ISSUE TITLE
Two WinPE ISO doesn't work

### ISSUE THREAD

**Issue by theoricher** [ventoy/Ventoy#91]
Hello,

Hello I have tested the two isos below and it seems that it doesn't work : 

- Hirens Boot CD : https://www.hirensbootcd.org/download/
- Live CD Malekal : https://mega.nz/#!Y8YR0CKI!q1nqME2hs6lDFZhYCydoIawdHX0lP_ztQbg9wTVbZsE
(The live cd maleak is a winpe very used in the french community.)

Thanks in advance for the addition to Ventoy.

**Comment by ventoy** [comment]
Hi,
Please give detail about the ventoy version and BIOS mode.

A HBCD_PE_x64.iso has been tested before, but maybe not in the same version with the one you tested.

BTW, you can try memdisk mode for WinPE.

**Comment by theoricher** [comment]
Hi, 

I have tested HBCD_PE_x64.iso v1.0.1 on legacy BIOS (HP Laptop) with Ventoy 1.0.08 :)

**Comment by ventoy** [comment]
When i test HBCD_PE_x64.iso, in legacy bios mode, can only boot with memdisk mode.
You can try memdisk mode in legacy bios. (Press F1 before you select the iso in the boot menu)

**Comment by theoricher** [comment]
I will repeat the test with Malekal and HBCD_PE_x64.
I'll let you know if it worked.

**Comment by ero35** [comment]
WinPE 10-8 Sergei Strelec (x86/x64/Native x86)
support please!!!
https://sergeistrelec.ru/
https://sergeistrelec.ru/winpe-10-8-sergei-strelec-english/

**Comment by theoricher** [comment]
> I will repeat the test with Malekal and HBCD_PE_x64.
> I'll let you know if it worked.

This issue can be closed.

**Comment by Ahmed-E-86** [comment]
> When i test HBCD_PE_x64.iso, in legacy bios mode, can only boot with memdisk mode.
> You can try memdisk mode in legacy bios. (Press F1 before you select the iso in the boot menu)

I was not able to boot in legacy bios, but I was able to boot on UEFI after pressing f1 to enter memdisk mode, and the latest ISO booted without any issues. I just had to press any key when asked for that afterwards.
