### ISSUE TITLE
Ventoy won't boot Legacy/BIOS after recompile

### ISSUE THREAD

**Issue by anwar-alsilwy** [ventoy/Ventoy#912]
Today I tried to build Ventoy 1.0.44 from the source using CentOS 7.
I downloaded all necessary packages and all third-part sources, as mentioned in the instructions.
I didn't modify any thing on the original source, just to try if it's working.
I did all steps mentioned in the instructions carefully, and I run [ sh all_in_one.sh ] script as root user, it's showed me ====SUCCESS====  at the end.
but when I install Ventoy to empty usb, it boot from UEFI successfully , BUT it won't boot in Legacy/BIOS mode, it show me black screen with fatal error.

Q: Is this because I'm using CentOS 7 booted from VHD file and using Vdisk plugin to boot from it ???

![vvv](https://user-images.githubusercontent.com/71539261/118820559-0c539280-b8bf-11eb-909f-744caa7534cb.jpg)

**Comment by ventoy** [comment]
test the USB in a real machine?

**Comment by anwar-alsilwy** [comment]
Of course I tested it in a real machine !!! , I just run it in Virtualbox to capture screen shot.
In Uefi mode it boot normal to Ventoy menu, But in Legacy mode it stuck in black screen forever.
 Do you think this issue happened because I boot CentOS from ( vhd.vtoy) file using vdisk plugin??

**Comment by anwar-alsilwy** [comment]
By the way, I faced this issue before, maybe when I tried to build ventoy 1.0.33.
It show error message in terminal,
But It also generate ventoy-for-windows.zip file.
I installed that zip file to usb and it boot normally to Uefi, But won't boot to Legacy mode.
See picture:
![1-1](https://user-images.githubusercontent.com/71539261/118873759-cc0e0780-b8f2-11eb-8ecd-a5496b752e05.jpg)

**Comment by anwar-alsilwy** [comment]
Mr.Longpanda
I think you should attempt to install CentOS 7 to VHD file then boot using (ventoy Vdisk plugin), then try to build Ventoy source, maybe you will face this issue too

**Comment by anwar-alsilwy** [comment]
Testing the fix ...

**Comment by ventoy** [comment]
test result?

**Comment by anwar-alsilwy** [comment]
Now, after rebuilding on CentOS 7 vdisk, it booted successfully on UEFI/BIOS mode.
Thanks a lot Mr.longpanda for your hard work, you're the best.
