### ISSUE TITLE
Ability to booting (Win/linux) Vhd/vdisk files from 3rd partition.

### ISSUE THREAD

**Issue by anwar-alsilwy** [ventoy/Ventoy#915]
I have 500GB HDD:
- 1st NTFS partition is less than 137GB (for Bios limitations) used for ISO payloads.
- 2nd FAT 32MB partition for VTOYEFI files.
- 3rd NTFS partition، the rest of space.

I have a lot of very big vhd/vdisk files, and I want to place them in 3rd larg partition, So is there any possible way to boot them? or could be supported on future release?

**Comment by ventoy** [comment]
Windows VHD(x) and Linux vDisk files can be placed in other partition or other disk (e.g. local disk).
Ventoy can boot them well, please refer the official document:
https://www.ventoy.net/en/plugin_vhdboot.html
https://www.ventoy.net/en/plugin_vtoyboot.html

**Comment by anwar-alsilwy** [comment]
Ok thanks for let me know, I didn't test this method before, but it looks like interesting.

By the way, what if we can browse & navigate partitions and folders from any disk, and boot iso/vhd/img ...etc, from anywhere via Ventoy (just like Grub file manager).

this feature will make Ventoy become more and more powerful.

**Comment by ventoy** [comment]
That's not suported. Ventoy only boot iso files in the 1st partition of Ventoy USB.
