### ISSUE TITLE
同一centos7.9镜像不同分区安装系统,有的分区模式可以引导，有的不行

### ISSUE THREAD

**Issue by yusenyi123** [ventoy/Ventoy#916]
同一镜像的不同分区模式，为什么有的分区模式是可以使用ventoy进行引导，有的分区模式不能进行引导
图片地址
https://mail.qq.com/cgi-bin/viewfile?f=8DBBC9C07F856985DEF230580C9B79E218F86D6BEBC57668EBE2BEC2AFB18CB3F0A36C012571743E3F6CE1F361E003B0066BDEC766FECD0F2391DA8822373A583A2A11A30382097C39E5835C1C5BD16094C571B4D8288BE91755CB43B897FE6D&mailid=ZL0522-WYV%7Ekb9BzRy07nQUU3RXOb5&sid=L-O7mLZNDdx0hx19&net=2675783946

**Comment by ventoy** [comment]
是个BUG，已经修复，请使用最新版本的 vtoyboot 重新制作vhd文件。
https://github.com/ventoy/vtoyboot/releases
