### ISSUE TITLE
Not able to boot Ultimate Boot CD

### ISSUE THREAD

**Issue by darkvpier** [ventoy/Ventoy#919]
When I try to boot to Ultimate Boot CD using ventoy, it says file not found

**Comment by ventoy** [comment]
You may boot it in UEFI mode.
The iso file of Ultimate Boot CD only supports Legacy BIOS mode.
So you can NOT boot it in UEFI mode. It's the problem of the ISO file itself.

**Comment by darkvpier** [comment]
> You may boot it in UEFI mode.
> The iso file of Ultimate Boot CD only supports Legacy BIOS mode.
> So you can NOT boot it in UEFI mode. It's the problem of the ISO file itself.

When i boot it in legacy BIOS mode it works perfectly

**Comment by imthenachoman** [comment]
@ventoy I am confused. You said you may boot it in UEFI mode but then you say you cannot boot it in UEFI mode?
