### ISSUE TITLE
更新后U盘启动直接进入系统而不是进入ventoy

### ISSUE THREAD

**Issue by Jacobax** [ventoy/Ventoy#92]
之前1.0.08升级1.0.09 BETA1是这样，后来重装会1.0.08，现在看到发行版1.0.09除了，更新，还是这问题，U盘启动直接进入win10系统

**Comment by ventoy** [comment]
如果是UEFI模式的话，需要在BIOS下关闭安全启动

**Comment by Jacobax** [comment]
谢谢！关闭安全启动后可以了，好奇为什么08可以，而升级09后要做这项操作才行

**Comment by ventoy** [comment]
因为ventoy的安全启动的方案在某些机器上不能工作，所以从09版本开始默认支持安全启动的选项是关闭的， 如果你08版本OK，说明这个安全启动的方案在你的机器上可以工作，你可以在升级09版本时在菜单里把 安全启动 勾上  就可以了。
