### ISSUE TITLE
Config File Wildcards

### ISSUE THREAD

**Issue by AdamKearn** [ventoy/Ventoy#929]
Hi All,

See my below config file used for ventoy.
I was wondering if anyone knows how to get wildcards working for referencing images?

Instead of providing the full path the the ISO file can we use something like `Win10*.iso` so anything that starts with "Win10" will get the answer files added and also injected custom files.

Love this project by the way...  Saves soo much time instead of rebuilding USBs every time there is a new update released.

```
{
    "theme":{
        "file":"/ventoy/theme/<redacted>/theme.txt"
    },
    "auto_install":[
        {
            "image":"/images/microsoft/Win10_20H2_R2_English_x64.iso",
            "template":[
                "/images/microsoft/unattended/<redacted>_unattended_setup_UEFI.xml",
                "/images/microsoft/unattended/<redacted>_unattended_setup_BIOS.xml",
                "/images/microsoft/unattended/autounattend.xml"
            ]
        }
    ],
    "injection":[
        {
            "image":"/images/microsoft/Win10_20H2_R2_English_x64.iso",
            "archive":"/scripts/wim_mod.zip"
        }
    ],
    "control": [
        { "VTOY_DEFAULT_IMAGE": "/images/microsoft/Win10_20H2_R2_English_x64.iso" },
        { "VTOY_MENU_TIMEOUT": "5" }
    ]
}
```

**Comment by ventoy** [comment]
`parent` option in auto_install and injection plugin can be helpful. Refer :
https://www.ventoy.net/en/plugin_autoinstall.html
https://www.ventoy.net/en/plugin_injection.html

**Comment by AdamKearn** [comment]
Hi @ventoy,

I tried using the `parent` option but after modifying the JSON file to use those options it would no longer detect the answer files or inject the ZIP file...

I am currently only using Windows ISOs  (20H2 and 21H1)

As a test I pressed the `F5` key and ran the `Check the auto install plugin configuration` and that reported that there was no images detected.  (See image below)

It looks like the injection didn't work with this method as well as I couldn't see the files inside the WinPE environment.

Not sure if I am using it incorrectly.   Please see config below:


![image](https://user-images.githubusercontent.com/30593259/120300952-50ce2d80-c2c4-11eb-8c73-38b03880f90e.png)

```json

{
    "theme":{
        "file":"/ventoy/theme/aspentech/theme.txt"
    },
    "auto_install":[
        {
            "parent":"/images/microsoft/",
            "template":[
                "/images/microsoft/unattended/apsentech_unattended_setup_UEFI.xml",
                "/images/microsoft/unattended/apsentech_unattended_setup_BIOS.xml",
                "/images/microsoft/unattended/autounattend.xml"
            ]
        }
    ],
    "injection":[
        {
            "parent":"/images/microsoft/",
            "archive":"/scripts/wim_mod.zip"
        }
    ],
    "control": [
        { "VTOY_DEFAULT_IMAGE": "/images/microsoft/Win10_20H2_R2_English_x64.iso" },
        { "VTOY_MENU_TIMEOUT": "5" }
    ]
}
```

**Comment by steve6375** [comment]
Update to latest version of Ventoy?

**Comment by AdamKearn** [comment]
Hi @steve6375,

I was originally using `ventoy-1.0.32`   But I have just used the Windows Utility to update my VHD to use the latest build (`ventoy-1.0.45`)   but I am still having this issue.

**Comment by steve6375** [comment]
are all files on first partition and in correct folder?

**Comment by AdamKearn** [comment]
That was the first thing I checked.   I copied and pasted the names of the folders to check to make sure I hadn't made a typo or anything.

It looks like the First Partition is formatted using `exFAT`.    The only thing I did was enable `Secure Boot` and told it to format using `MBR` instead of `GPT`

(See images below)

![image](https://user-images.githubusercontent.com/30593259/120306322-a6f19f80-c2c9-11eb-916e-3aa1c8dab1e8.png)


![image](https://user-images.githubusercontent.com/30593259/120305944-406c8180-c2c9-11eb-88b1-273fd94e36c2.png)
![image](https://user-images.githubusercontent.com/30593259/120306089-68f47b80-c2c9-11eb-8bc3-7fa15321b689.png)

**Comment by steve6375** [comment]
Be careful about ventoy.json format

"auto_install":[

no space between : and [   ???

Use a format checker
A json file ventoy.json must be placed under the ventoy directory (no subdirectory) as the configuration file. The file must match the syntax of json and the outermost layer must be an object( { } ). For json syntax you can check it with the 2 online tools as follows:
https://www.json.cn
http://json.parser.online.fr

**Comment by ventoy** [comment]
Remove the trailing `/` of parent option and retry.

```
{
    "theme":{
        "file":"/ventoy/theme/aspentech/theme.txt"
    },
    "auto_install":[
        {
            "parent":"/images/microsoft",
            "template":[
                "/images/microsoft/unattended/apsentech_unattended_setup_UEFI.xml",
                "/images/microsoft/unattended/apsentech_unattended_setup_BIOS.xml",
                "/images/microsoft/unattended/autounattend.xml"
            ]
        }
    ],
    "injection":[
        {
            "parent":"/images/microsoft",
            "archive":"/scripts/wim_mod.zip"
        }
    ],
    "control": [
        { "VTOY_DEFAULT_IMAGE": "/images/microsoft/Win10_20H2_R2_English_x64.iso" },
        { "VTOY_MENU_TIMEOUT": "5" }
    ]
}
```

**Comment by AdamKearn** [comment]
@steve6375  @ventoy 
That's it   !!!!!!    It was the trailing slash at the end of the path.

Thank you very much everyone for your help.       Everything works completely fine now.
Lovely weather here in the UK....  too bad I am stuck inside at work today.   ;)

Thanks again for your help.     I would love to help contribute to this project but I don't know much stuff about the low-level booting stuff.     That's all magic to me.   LOL
