### ISSUE TITLE
[Feature Request] Auto-Memdisk-Mode

### ISSUE THREAD

**Issue by jsuelwald** [ventoy/Ventoy#93]
It would be nice if ventoy can use memdisk-mode automatically, if needed.

Could be triggered on name, for example "acronis_rescue_[memdisk].iso" or something like this.

**Comment by ventoy** [comment]
Hi, 
I think it's not very troublesome to press F1 to enter memdisk mode. 
Besides, in most cases, ventoy works well in normal mode. There are indeed some iso files that can only boot in memdisk mode, but this is not common.

**Comment by ventoy** [comment]
supported in the latest release.
https://www.ventoy.net/en/plugin_automemdisk.html
