### ISSUE TITLE
Release 1.0.45 error load fedora

### ISSUE THREAD

**Issue by mozgbrasil** [ventoy/Ventoy#936]
![16226525730431025791904784607521](https://user-images.githubusercontent.com/17202780/120519773-66695300-c3a9-11eb-888c-1d95201cc3f5.jpg)

![16226526003285042584107274659565](https://user-images.githubusercontent.com/17202780/120519830-784af600-c3a9-11eb-88f3-8e68cec039a6.jpg)

**Comment by ventoy** [comment]
Try press `F7` to switch to TEXT mode and then select the ISO file to boot.
