### ISSUE TITLE
Clarify the project license

### ISSUE THREAD

**Issue by Calinou** [ventoy/Ventoy#94]
The website says Ventoy is licensed under the GPLv3 or later: https://www.ventoy.net/en/doc_license.html

However, this repository contains a file called `GPLv3` at its root, with the text of the **L**GPLv3: https://github.com/ventoy/Ventoy/blob/master/GPLv3

Is Ventoy licensed under the GPLv3+ or LGPLv3+? It would be good to clarify this :slightly_smiling_face: 

Also, it would be better to rename the license file to `LICENSE` so GitHub can recognize it.

**Comment by ventoy** [comment]
Hi, Thank you for your reminder.
I have modified the file info. 
Ventoy is GPLv3+

**Comment by Calinou** [comment]
Thanks :slightly_smiling_face:
