### ISSUE TITLE
Error when booting

### ISSUE THREAD

**Issue by AnUnkownSkeleton** [ventoy/Ventoy#941]
![IMG_20210605_123031_993](https://user-images.githubusercontent.com/75160111/120901768-01586c00-c5fa-11eb-990b-8ac1c2e57d66.jpg)

**Comment by ventoy** [comment]
It's about secure boot.
So the simplest way is to disable the `secure boot` option in the BIOS and retry.
Or you can refer:  https://www.ventoy.net/en/doc_secure.html
