### ISSUE TITLE
使用Ventoy制作GPT分区类型的启动盘 在Windows10系统环境下 VTOYEFI分区仍然无法自动被隐藏

### ISSUE THREAD

**Issue by Leeray-Lau** [ventoy/Ventoy#943]
作者是不是忘记了捏？(｡•﹃•｡)
刚才制作完启动盘后看了下，VTOYEFI的分区类型GUID，仍然为“基本数据分区”的值：EBD0A0A2-B9E5-4433-87C0-68B6B72699C7
正常情况下，此分区类型GUID应该是“EFI系统分区”的值：C12A7328-F81F-11D2-BA4B-00A0C93EC93B
才能被Windows10系统自动隐藏。
我自己手动改了下，把VTOYEFI的分区类型GUID的值：“基本数据分区”改为“EFI系统分区”，然后在虚拟机快照模式里测试了一遍，恢复正常~
![Snipaste_2021-06-06_10-11-10](https://user-images.githubusercontent.com/59900651/120910212-8c476e00-c6af-11eb-95c1-8b5cae297806.png)

**Comment by ventoy** [comment]
这个是有意这样做的。
原因是如果设置成EFI的类型，安装Windows会出错，Windows不允许系统中有多个EFI分区，U盘上有了，安装系统时硬盘上就不能创建EFI分区了。

**Comment by DAVPanda** [comment]
作者说的没错，如果在安装系统的时候系统检测到其他磁盘已经存在一个EFI分区，会自动把引导放到那里去，在安装Windows系统的磁盘就不会建立EFI分区了。

**Comment by ventoy** [comment]
@Leeray-Lau
最新版本创建GPT分区时给这个分区增加了一个隐藏属性， 你可以试试最新版本重新安装之后看看会不会隐藏。

**Comment by Leeray-Lau** [comment]
@ventoy 嗯，使用最新版本的Ventoy，重新创建GPT分区类型的启动盘之后，确实可以成功的将这个VTOYEFI分区给隐藏掉，即使将U盘插入到一台新的Win10系统的电脑上，也不会自动分配盘符了。最新版本的Ventoy，在创建GPT类型的分区时，会给这个分区添加一个隐藏属性。请问作者，这个隐藏属性是否指的是GPT分区属性：0xC000000000000001（OEM + 不自动分配盘符 + 隐藏），从而实现的分区盘符自动隐藏？另外目前对于MBR类型的分区而言，是否仍然没有通用的隐藏方案？

**Comment by ventoy** [comment]
GPT是的。 MBR没有通用方案。
