### ISSUE TITLE
Blue Screen white installing Ventoy

### ISSUE THREAD

**Issue by BajajAditya123** [ventoy/Ventoy#947]
There is a error
When I clicked the install button in ventoy it shows me a blue screen then I restart my computer then I put a iso file then try reboot for testing it my computer then my computer was bootable but after boot it shows me a blue screen. I then fix the issue of blue screen from windows.com/stopcode. So can you help me run ventoy

**Comment by TheAlienDrew** [comment]
Not sure what's happening with your machine, but ventoy shouldn't be causing any bluescreen issues

**Comment by BajajAditya123** [comment]
CRITICAL_PROCESS_DIED

**Comment by BajajAditya123** [comment]
This error of blue screen coming

**Comment by ventoy** [comment]
I have no idea about the BlueScreen.
Maybe you can try VentoyLiveCD to install Ventoy.
https://www.ventoy.net/en/doc_livecd.html

**Comment by TheAlienDrew** [comment]
@BajajAditya123 https://helpdeskgeek.com/help-desk/how-to-fix-a-stop-code-critical-process-died-bsod/

> Driver issues, corrupted system files, a bad system update—you name it, because they can all have an impact on your Windows system performance to cause a BSOD error like this. It may only take one corrupted file to cause a system process to fail. 

Try fixes your system with the two following commands:

```ps1
DISM /Online /Cleanup-Image /RestoreHealth
SFC /scannow
```

**Comment by BajajAditya123** [comment]
Ok

**Comment by TheAlienDrew** [comment]
After those are done, I suggest rebooting. And then trying to use Ventoy

**Comment by BajajAditya123** [comment]
I am afraid of command prompt and powershell

**Comment by BajajAditya123** [comment]
There is another way??

**Comment by BajajAditya123** [comment]
I think Ventoy is doing something with my system reserved partition

**Comment by TheAlienDrew** [comment]
@BajajAditya123 I can ensure you running those commands is safe, you can search on microsoft.com to understand what DISM and SFC do to your machine.

There really isn't another way, unless you want to go into settings and do a reset reinstallation of Windows (which I assume you don't)

**Comment by BajajAditya123** [comment]
@TheAlienDrew I have already reset and run these commans. I will fix this issue soon
