### ISSUE TITLE
修改主题后,下方的F1 F2菜单消失

### ISSUE THREAD

**Issue by xiaozhuai** [ventoy/Ventoy#95]
如题, 修改了主题, 主题可以正确显示, 但是下面的F1 F2菜单没了.
主题链接 [https://github.com/gustawho/grub2-theme-breeze](https://github.com/gustawho/grub2-theme-breeze)

**Comment by ventoy** [comment]
修改主题需要在 theme.txt最后添加几个 hbox定义， 参考 INSTALL/grub/themes/ventoy/theme.txt
文件中最后面的几个 hbox定义，把它们拷贝到新的主题的theme.txt中
这部分我还没得及更新到说明文档中。

**Comment by xiaozhuai** [comment]
试了, 可以! 但是除了菜单, 前面的版本可以显示出来是为什么

**Comment by ventoy** [comment]
这个算是个标记吧，当前是在代码里写死的。

**Comment by xiaozhuai** [comment]
soga 很完美 一直想要这么个U盘引导 另外提个小建议 F2的关机重启菜单建议直接展开 用两个按钮控制关机重启 比收进去更方便一点 感谢作者 有捐助渠道吗 或者加个微信什么的

**Comment by ventoy** [comment]
等后面快捷键有富裕的，可以分出来一个。
可以到官网扫二维码哈 :)

**Comment by xiaozhuai** [comment]
已捐助200 非常好的东西 希望能坚持维护下去!

**Comment by ventoy** [comment]
非常感谢！
Ventoy刚发布不久，我会努力做好。

**Comment by xiaozhuai** [comment]
加油! 那我关issue了

**Comment by xiaozhuai** [comment]
对了 微信的捐助二维码貌似有点问题 支付宝可以

**Comment by ventoy** [comment]
多谢提醒， 刚看了下微信说交易异常限制了。 操作了之后已经可以了。

**Comment by xiaozhuai** [comment]
有个小问题, 另外提issue了
