### ISSUE TITLE
Nitrux fails to boot

### ISSUE THREAD

**Issue by GHNewbiee** [ventoy/Ventoy#953]
*Ventoy*: ***1.0.45***
*Nitrux*: ***nitrux-release-amd64_2021.05.28.iso*** a.k.a. ***1.4.1 build.270521***

Any similar experience? *Tia*

**Comment by GHNewbiee** [comment]
Only the legacy booting was tested.

**Comment by steve6375** [comment]
Legacy boot is OK on Easy2Boot and agFM. On Ventoy I get an INT 18h error and doesn't boot - is that what you see?

**Comment by GHNewbiee** [comment]
On Ventoy, I do not get anything on the screen. It just takes me directly to the grub menu.

**Comment by ventoy** [comment]
Try this CI release:
https://github.com/ventoy/Ventoy/actions/runs/928548230

**Comment by GHNewbiee** [comment]
Fixed!

You may close it if you wish that or I will do it after v. 1.0.46 is published and issue is rechecked.

**Comment by AtomicHawkYT** [comment]
Thanks I was also facing the same problem!
