### ISSUE TITLE
TreeView模式下, 没有上级目录的选项

### ISSUE THREAD

**Issue by xiaozhuai** [ventoy/Ventoy#96]
如题, TreeView模式下, 进入一个目录后没有上一级的选项, 按Esc可以返回上一级, 建议增加返回上级目录的选项

**Comment by ventoy** [comment]
可以增加，只不过ESC返回是grub自带的功能，所以这一块没有多做改动。
习惯了可能ESC更方便吧。

**Comment by xiaozhuai** [comment]
嗯嗯 不是紧迫的功能 之后可以完善

**Comment by ventoy** [comment]
此功能在 1.0.12 版本已经实现。
