### ISSUE TITLE
error: not a regular file when booting from ventoy USB

### ISSUE THREAD

**Issue by mufinlive** [ventoy/Ventoy#962]
When booting from the USB, i get a black screen with small white text in the corner saying `error: not a regular file`. What could be the problem here?

**Comment by Diacius** [comment]
We need more info here:

- UEFI or MBR?
- How did you create the USB? on Windows, Mac or Linux?
- What ISO are you using?

Also, just try reinstalling Ventoy

**Comment by mufinlive** [comment]
> 
> 
> We need more info here:
> 
>     * UEFI or MBR?
> 
>     * How did you create the USB? on Windows, Mac or Linux?
> 
>     * What ISO are you using?
> 
> 
> Also, just try reinstalling Ventoy

I setup the USB using the windows .exe, i selected MBR in that menu and UEFI in my bios. I have an ubuntu and arch iso in there, but after some troubleshooting i figured out its my ventoy folder thats actually causing the problem. I attached it here, maybe im doing something completely wrong?


[ventoy.zip](https://github.com/ventoy/Ventoy/files/6657493/ventoy.zip)

**Comment by Diacius** [comment]
Hi again, I've found the problem!
You have configured your ventoy.json incorrectly, **sadly AFAIK ventoy doesn't let you define themes per ISO or multiple themes**.

Here you have tried to define more than one theme file. Which i don't think is supported 🤷🏻 
[Here are the docs for correct theming :\)](https://www.ventoy.net/en/plugin_theme.html)
You can only define one theme, so you would have to pick 1 theme.
I suspect the person who made the grub theme intends you to use **1** theme for the OS you boot, not multiple as grub doesn't support multiple active themes :)

Other than that, your second reply was really helpful, so please include that info in a issue description (It's a win-win for everyone).
Enjoy using Ventoy and have a nice day!

**Comment by mufinlive** [comment]
Hi there!

From my understanding, in those docs it says you can put a string array of directories, and it will choose one at random at boot time. Is this just not true or am i doing it wrong?

**Comment by Diacius** [comment]
Oops sorry! I am **so** sorry 😮!
![image](https://user-images.githubusercontent.com/77890144/122108809-90446000-ce14-11eb-844d-0f51892f1e93.png)
I just read the docs page, and saw it, it may be a new feature or I didnt notice before.
You may need to check the themes in that case. I don't know about the internals of GRUB or Ventoy so I can't comment on what could be causing the issue. Possibly a malformed(bad) theme or something. IDK 🤷🏻.
Sorry I couldn't help
P.S just out of interest, whats the theme called?

**Comment by mufinlive** [comment]
No worries, ill try another theme to see if that works instead, and if it does ill close this issue. 
PS The theme can be found [here](https://www.gnome-look.org/p/1482847/)

**Comment by Diacius** [comment]
Ok thanks for being so helpful.

**Comment by mufinlive** [comment]
It was the themes that made it not work, closing this issue.

**Comment by Diacius** [comment]
Great! Maybe somebody can work out what was wrong with the themes...

**Comment by Diacius** [comment]
Personally, the default is fine for me. @steve6375 which specifically?, I'd love to know as many themes don't show the ventoy shortcuts.

**Comment by mufinlive** [comment]
@steve6375 that's what I did :) currently using bigsur
