### ISSUE TITLE
Feat.req. Make option to scan isos in root only or is it so now?

### ISSUE THREAD

**Issue by necros2k7** [ventoy/Ventoy#964]
Cause there are cases when Ventoy USB drive used to transfer files, and if there are many possibly it will scan isos too long.

**Comment by steve6375** [comment]
Just place a file in each root folder.
.ventoyignore
https://www.ventoy.net/en/faq.html

**Comment by necros2k7** [comment]
it`s ok as a workaround, but when there`re thounds of folders..

**Comment by steve6375** [comment]
Just make one folder (MYFOLDER) and put all your other folders inside that folder.

\MYFOLDER\.ventoyignore
\MYFOLDER\F1\
\MYFOLDER\F2\
etc.

**Comment by necros2k7** [comment]
Got it thanx

**Comment by ventoy** [comment]
Also, you can use `VTOY_MAX_SEARCH_LEVEL` option in `global control` plugin.
https://www.ventoy.net/en/plugin_control.html

![image](https://user-images.githubusercontent.com/59477474/122236065-c820d580-cef0-11eb-817d-3602221076ca.png)
