### ISSUE TITLE
Latest ISO for LM Mint 20.2 beta not working in UEFI mode

### ISSUE THREAD

**Issue by enigma131** [ventoy/Ventoy#965]
Hi,
I have an USB prepared stick , and latest ISO from : 
http://mirror.csclub.uwaterloo.ca/linuxmint/testing/linuxmint-20.2-cinnamon-64bit-beta.iso
is not working in UEFI mode, but it works in CSM legacy mode.
C. Lefebvre says it is same method was used to compile the ISO as previous:
https://github.com/linuxmint/mint20.2-beta/issues/6.
Ventoy stick is up to date to latest release.

**Comment by steve6375** [comment]
http://mirror.csclub.uwaterloo.ca/linuxmint/testing/linuxmint-20.2-cinnamon-64bit-beta.iso
seems OK on VBox with older version of Ventoy.
DId you check the SHA of the file that is on the USB drive after copying it?

**Comment by enigma131** [comment]
Yes Sha256 is vérified. Did you mean i must try an older Ventoy release ?

**Comment by ventoy** [comment]
1. Can old release of LinuxMint boot fine with Ventoy?
2. What is the problem when you boot in UEFI mode? a photo?
3. Pleas checksum the ISO file as follows in Ventoy's menu. Refer: https://www.ventoy.net/en/faq.html#faq_boot_checksum
![md5](https://user-images.githubusercontent.com/59477474/122556742-73a36480-d06e-11eb-9956-b519601c8021.PNG)

**Comment by enigma131** [comment]
I have a cheksum application integrated in previous LM 20.1 thanks for your suggestion, checksum is OK I repeat.
When I boot on this UEFI computer, After Ventoy menu and Iso selection, I have only cursor at top left corner.
I will try older LM next, other iso on Ventoy where booting (Magea, Arch linux, Bodhi ec)

**Comment by enigma131** [comment]
I've just try with LM 20.1 Cinnamon release same problem

**Comment by ventoy** [comment]
Try:
When you in Ventoy's main menuy, press `ctrl+r` to enter GRUB2 mode and then select the ISO and boot.

**Comment by enigma131** [comment]
Well, this trick is working!
So now, why only LM 20.x need this trick ?

**Comment by ventoy** [comment]
I have no idea.
Actually, I have tested this ISO file with both VirtualBox and my laptop and both boot fine.

If possible I need some debug info.
When boot into Ventoy's menu, press `c` to enter grub shell and run `vtdebug on`  press `Enter` to run the command, and 
then press `ESC` to return to the menu and then select the ISO file to boot.
This time it may print some debug message and pause many times, just follow the prompt to continu.
And give me a video or some photos about them.

**Comment by enigma131** [comment]
Hum in debug mode, after multiples "hit enter" , it is booting too...

**Comment by ventoy** [comment]
It's weird.
Maybe your UEFI firmware is a little special.

**Comment by enigma131** [comment]
It's a laptop Acer E5 571

**Comment by enigma131** [comment]
I have take pictures, I can send you via e-mail if you want.
