### ISSUE TITLE
Suggestion -- install Ventoy to hard disk

### ISSUE THREAD

**Issue by rekeeszeng** [ventoy/Ventoy#967]
It's gonna be wonderful if Ventoy can be installed to the hard disk. It can create two partitions, just like it does on a USB drive.

**Comment by ventoy** [comment]
Ventoy can be installed to hard disk. By default only USB devices are listed, but you can enable `Option`--->`Show All Devies`
Then hard disk will be listed for select.


![image](https://user-images.githubusercontent.com/59477474/122673332-7a62e080-d202-11eb-9e38-9afb42a562ae.png)

**Comment by rekeeszeng** [comment]
> Ventoy can be installed to hard disk. By default only USB devices are listed, but you can enable `Option`--->`Show All Devies`
> Then hard disk will be listed for select.
> 
> ![image](https://user-images.githubusercontent.com/59477474/122673332-7a62e080-d202-11eb-9e38-9afb42a562ae.png)

Cool. I'll give that a shot. Thanks. Good job!
