### ISSUE TITLE
Does xp iso work now

### ISSUE THREAD

**Issue by Algamerthetruealbanian** [ventoy/Ventoy#969]
Just a question wich technically is a issue for a long time 
dev or users of ventoy can you tell me if winxp works now or its still dosnt work

**Comment by ventoy** [comment]
Windows XP is not suppored now and will not be supported in the future.
You can find some WinPE that supported install WinXP. So you can boot the WinPE by Ventoy firstly and install WinXP inside the WinPE.

**Comment by Oreeeee** [comment]
@Algamerthetruealbanian For Windows XP and any other NT based Windows under Windows Vista you need to use Easy2Boot. Windows XP installer doesnt have USB and during graphical portion of the setup you need Windows XP installation media inserted. Easy2Boot actually emulates CD and unmount USB to prevent text mode part from blue screening and graphical part from showing "insert Windows XP CD". Ventoy works differently from Easy2Boot and it makes no sense to rewrite Ventoy just for XP support.

**Comment by ibilux** [comment]
Is it a problem with xp drivers ? Cause as I understood ventoy maps the iso file as a CD (correct me if I'm wrong).
And it seems that the windows xp setup can't load the correct mapped iso drivers.
