### ISSUE TITLE
Error compiling mips64 for latest build 1.0.46

### ISSUE THREAD

**Issue by steve6375** [ventoy/Ventoy#972]
![image](https://user-images.githubusercontent.com/1469350/122979436-744e3a80-d38f-11eb-831b-9d8e6e9aa35a.png)

The configure command fails. Could you give me a hint as to what the issue could be please?
All others build OK. I think I have PATH and correct zip files as in the BuildVentoyfromSource.txt file.

**Comment by steve6375** [comment]
![image](https://user-images.githubusercontent.com/1469350/122981386-99dc4380-d391-11eb-80fd-e14009d2feae.png)

**Comment by ventoy** [comment]
In your log:
`mips-linux-gnu-gcc : command not found.` 

So you need to include  `/opt/mips-loongson-gcc7.3-linux-gnu/2019.06-29/bin/`  in your `PATH`.
This is done in `all_in_one.sh`
```
export PATH=$PATH:/opt/gcc-linaro-7.4.1-2019.02-x86_64_aarch64-linux-gnu/bin:/opt/aarch64--uclibc--stable-2020.08-1/bin:/opt/mips-loongson-gcc7.3-linux-gnu/2019.06-29/bin/:/opt/mips64el-linux-musl-gcc730/bin/
```

So, did you run `all_in_one.sh` ? or you manually run `configure` in grub source directory?

**Comment by steve6375** [comment]
There is no /opt/mips-loongson-gcc7.3-linux-gnu/2019.06-29/bin/ folder.
maybe because I Ctrl+c'd out of the all-in-one.sh script and it left an incomplete extraction which no passes the prepare_env test.
I ran the tar command manually and now all is OK
thanks!
P.S. maybe a  all-in-one.sh **clean**   parameter to force pre_env to always extract tar files?
