### ISSUE TITLE
SystemRescueCD 8.03 won't boot

### ISSUE THREAD

**Issue by UntouchedWagons** [ventoy/Ventoy#973]
![systemrescuecd](https://user-images.githubusercontent.com/160996/122995584-c8e5bb80-d377-11eb-9ea7-39cc19d22bd0.jpg)

I have tried multiple machines, SystemRescueCD 8.03 won't boot it just produces this garbled display when the ISO is chosen from the main menu.

**Comment by ajgringo619** [comment]
Have you tried another ISO? I just downloaded this today and it worked; tested in a VMware VM, so not exactly the same test, but it did boot without a hitch.

**Comment by UntouchedWagons** [comment]
Yes I used the Truenas Core ISO this morning

**Comment by ventoy** [comment]
Try this:
When you get this garbled display, press `F7` to switch to TEXT mode and continue.

**Comment by ajgringo619** [comment]
> Yes I used the Truenas Core ISO this morning

Sorry, I meant another SystemRescueCD ISO.

**Comment by UntouchedWagons** [comment]
I tried SystemRescueCD versions 6.1.8 and 7.01 and they both created the same garbled display. I also tried booting 8.03 in text mode and the same thing occurred.

**Comment by ventoy** [comment]
Make TEXT mode as the default mode and retry.
https://www.ventoy.net/en/doc_fuzzy_screen.html

**Comment by UntouchedWagons** [comment]
I was able to boot SystemRescueCD using text mode on my laptop although it was booting in UEFI mode, the other machines booted in legacy BIOS mode. I'll try one of them tomorrow.

**Comment by UntouchedWagons** [comment]
Making text mode the default works as a workaround when booting via legacy mode.
