### ISSUE TITLE
Custom EFI FILE

### ISSUE THREAD

**Issue by rafalohaki** [ventoy/Ventoy#974]
is it possible to load custom efi from ventoy folder?
  
Below structure without ventoy
custom.efi is custom efi file to load
bootx64.efi is  EDK2 efi shell 
Normally I do:
load custom.efi from  FS0(USB)
then run \EFI\Boot\bootx64.efi on FS1 (windows boot media )

![image](https://user-images.githubusercontent.com/20607107/123005970-48df4600-d3b7-11eb-88f9-d43375d6feca.png)

**Comment by ventoy** [comment]
Ventoy does support boot efi files, you can make a try.
Just put the .efi file (custom.efi or bootx64.efi) in the Ventoy USB stick as the ISO files.
And boot the efi file the same as you boot an ISO file.
