### ISSUE TITLE
USB not bootable on HP elitebook 8570w (UEFI)

### ISSUE THREAD

**Issue by mSubhani** [ventoy/Ventoy#98]
Hi Dev, thanks for such an amazing tool i am searching this type of tool since long and finally found this, but i have an issue i created usb as per instruction (tried on both windows and linux) then copy two iso windows 10 and manjaro 20.0.1 and reboot my pc (UEFI native mode) but usb did not shown in boot devices list. It will be very nice if you fix my issue thanks in advance.

ventoy-1.0.09
HP Elitebook 8570w (UEFI native mode)
OS = Windows 10 and Manjaro 20.0.1 lysia xfce

**Comment by ventoy** [comment]
Please confirm the Secure Boot status in BIOS. You can retry after disable Secure Boot.

**Comment by mSubhani** [comment]
> Please confirm the Secure Boot status in BIOS. You can retry after disable Secure Boot.

Already disabled sir

**Comment by ventoy** [comment]
When you use rufus, what the partition format do you chose? MBR or GPT ?
Ventoy use MBR format, is it possiable that your machine only accept GPT?

**Comment by mSubhani** [comment]
> When you use rufus, what the partition format do you chose? MBR or GPT ?
> Ventoy use MBR format, is it possiable that your machine only accept GPT?

You are right on Native UEFI mode my pc only detect GPT. The last thing i checked was partition table then i also reached the point that you are asking. If it can be solveable i will be thankful

**Comment by ventoy** [comment]
In order to support both legacy and uefi, ventoy use MBR format, and most type of machine accept MBR in UEFI mode. Of course this is not the case with you.
If so, it's not solveable in current release.  Maybe in  ventoy 2.X  :)

**Comment by mSubhani** [comment]
> In order to support both legacy and uefi, ventoy use MBR format, and most type of machine accept MBR in UEFI mode. Of course this is not the case with you.
> If so, it's not solveable in current release. Maybe in ventoy 2.X :)

Nice to hear this looking forward for upcoming release. Thanks

**Comment by iki789** [comment]
I have the same issue on legacy bios

**Comment by tao1** [comment]
Of course it makes sense to use MBR as it is widely accepted.
But notice MBR limits disk size to 2TB, so I cannot use ventoy with my brand new 5TB USB disk bought 100$.
I guess I am not alone in this case. Please add support to GPT.

KR

**Comment by DrissiReda** [comment]
@mSubhani I have a similar issue and if you want you can try to make it manually, check the issue I opened #279 . My solution isn't perfect which is why I had to open an issue. I have a problem with the boot part, it doesn't automatically find the partition to boot. But it gives you a grub shell from which you can tell the grub where to boot. If you're willing to do things manually and need further explanation, just let me know.

**Comment by ventoy** [comment]
You can use the latest release and install Ventoy in GPT partition style.

**Comment by ventoy** [comment]
This is an old issue. I will close it now.
If you still have problem with latest Ventoy release, you can reopen the issue.
@mSubhani
