### ISSUE TITLE
Unable to mount Ventoy Ubuntu 16.04.7

### ISSUE THREAD

**Issue by vinsent2002** [ventoy/Ventoy#981]
![Screenshot from 2021-06-29 23-40-22](https://user-images.githubusercontent.com/46157952/123864602-9f0e3500-d933-11eb-9f66-1d7112114781.png)

**Comment by ajgringo619** [comment]
Try using `vfat` instead of `exfat`. I just checked my Mint 20 system (based on Ubuntu 20) and I don't have `exfat` listed in /proc/filesystems.

**Comment by ajgringo619** [comment]
I think I misspoke earlier. Do you have `exfat-fuse` and `exfat-utils` installed? I still don't show a `exfat` entry in /proc/filesystems, but I can mount exfat.

**Comment by ventoy** [comment]
After install Ventoy, the /dev/sdc1 is formated in `exfat` format.
So you need to install `exfat-utils` package to support exfat filesystem and mount it.

**Comment by vinsent2002** [comment]
> After install Ventoy, the /dev/sdc1 is formated in `exfat` format.
> So you need to install `exfat-utils` package to support exfat filesystem and mount it.
Thanks for the advice. After installing exfat-utils (sudo apt install exfat-utils) in Ubuntu 16.04 it works properly.

**Comment by vinsent2002** [comment]
> After install Ventoy, the /dev/sdc1 is formated in `exfat` format.
> So you need to install `exfat-utils` package to support exfat filesystem and mount it.

Thanks for the advice. After installing exfat-utils (sudo apt install exfat-utils) in Ubuntu 16.04 it works properly.
