### ISSUE TITLE
bootable iso not authorized

### ISSUE THREAD

**Issue by 13laddi** [ventoy/Ventoy#984]
I am using Ubuntu. I make my USB bootable with ISO file of windows 10 .
when restart is system and go with booting process the USB device is show but it shows that (BOOTABLE ISO NOT AUTHORIZED)...

**Comment by ventoy** [comment]
Disable the `secure boot` option in your BIOS and retry.

**Comment by 13laddi** [comment]
now It's working 
thanks for the help
