### ISSUE TITLE
Ventoy Boots GNU GRUB Command Line

### ISSUE THREAD

**Issue by kaanabdullah** [ventoy/Ventoy#987]
I have 32gb usb with Lenevo G572. When I boot from usb ventoy opens command line. I tried all the solutions on the internet. 

I tried this usb on an other computer. It runs very well.

Sorry for my bad English. I'm not native.

![Uploading 16253804017741735975285307189352.jpg…]()

**Comment by steve6375** [comment]
can't see screenshot! Please add.
Are you UEFI booting or Legacy/BIOS booting?

**Comment by kaanabdullah** [comment]
> can't see screenshot! Please add.
> Are you UEFI booting or Legacy/BIOS booting?

Legacy/bios booting. I can't send photo but it looks like this. 
![image](https://user-images.githubusercontent.com/86880189/124376803-64005e80-dcb1-11eb-9196-5d49d2066abc.png)

**Comment by steve6375** [comment]
please type
ls
at grub command line
and then type
set
and upload screenshot

**Comment by kaanabdullah** [comment]
too many things appeared on the screen.

![16253835605307141885378213927230](https://user-images.githubusercontent.com/86880189/124376997-48e21e80-dcb2-11eb-93d5-ec0b2e4440ae.jpg)

**Comment by steve6375** [comment]
ls
???

**Comment by kaanabdullah** [comment]
I wrote it first but I'll post it again

![16253837114335614463629277798245](https://user-images.githubusercontent.com/86880189/124377052-ac6c4c00-dcb2-11eb-877c-d79704390e9f.jpg)

**Comment by steve6375** [comment]
Try preparing the Ventoy USB drive as MBR  not GPT?

**Comment by kaanabdullah** [comment]
When I try mbr partition it never seem on boot screen or bios.

**Comment by steve6375** [comment]
OK 
First make a MBR/Legacy Ventoy drive
Then - on the 2nd partition there is a \EFI folder -please rename it to \EFIXX
and try Legacy boot

**Comment by steve6375** [comment]
P.S. What is total capacity of USB drive?

**Comment by kaanabdullah** [comment]
32gb

**Comment by RobotMerkezi** [comment]
kaan secure boot açsana biostan öyle bir dene

**Comment by steve6375** [comment]
P.S. Do not boot using USB-ZIP option in BIOS menu
Must use USB-HDD
If it does not appear then change BIOS option to USB HDD.

**Comment by kaanabdullah** [comment]
![16253861614543397339405340012369](https://user-images.githubusercontent.com/86880189/124378104-500c2b00-dcb8-11eb-85e9-6196865e55a6.jpg)

**Comment by steve6375** [comment]
It is best to always set the First Boot Device to the  Internal HDD  NOT the USb drive.
Then use F12 key to boot to the USB drive.
This is because when installed some early OS's, it can install boot code to the 'boot drive' and so will install boot code to the USB drive instead of to the internal hard disk.

**Comment by kaanabdullah** [comment]
This still same

**Comment by steve6375** [comment]
So you made an MBR USB drive and renamed \EFI to \EFIXX ???

**Comment by kaanabdullah** [comment]
I don't have an other computer

**Comment by kaanabdullah** [comment]
Can I boot iso files with some codes ?

**Comment by steve6375** [comment]
How did you make the Ventoy USB drive then?

**Comment by kaanabdullah** [comment]
I make it two weeks ago and my pc broken rn

**Comment by steve6375** [comment]
OK
can you type
ls (hd0,2)/
and show result please

**Comment by kaanabdullah** [comment]
![16253868661783251025154828292703](https://user-images.githubusercontent.com/86880189/124378439-f7d62880-dcb9-11eb-8fdb-5138e892278d.jpg)

**Comment by steve6375** [comment]
that is the issue.  Borrow a friends PC/notebook and make a new USB drive and follow my instructions.
Also make sure your 32GB USB drive is not a fake (it has 32GB of memory).
Use FakeFlashTest.exe to test it.

**Comment by kaanabdullah** [comment]
Ok so I will borrow a pc today. When I borrow pc I will write it here.

**Comment by kaanabdullah** [comment]
I realized that I don't have a friend.    
But I'll still find a PC.
@steve6375

**Comment by ventoy** [comment]
You can try an USB with small capacity (e.g.  8GB)  for comparison test.

**Comment by ventoy** [comment]
Or you can reinstall Ventoy and reserve some space at the end of the USB stick (e.g.  reserve 16GB) as follows:
https://www.ventoy.net/en/doc_disk_layout.html#reserve_space

**Comment by ivandscds** [comment]
I have the same problem too

**Comment by yashkadudkin** [comment]
v1.0.06 - Good) https://sourceforge.net/projects/ventoy/files/
