### ISSUE TITLE
[Issue]:  HP DL360 G7 - Drops straight into Grub Shell (Possible BIOS issue?)

### ISSUE THREAD

**Issue by Armageus** [ventoy/Ventoy#990]
### Official FAQ

- [X] I have checked the official FAQ.

### Details about the issue

Upon booting HP DL360 G7 Servers, Ventoy drops straight to the Grub Shell.
(My "main" ventoy 128GB stick works fine on newer HP servers, and all kinds of PCs and laptops using either BIOS or UEFI)

I assume this is likely a BIOS issue, (but no updates are available - last is from 2015) however I have tried the workarounds listed (a 32Gb USB, or reserving a partition at the end), however neither made any difference.

With a 32GB Kingston DTSE9 G2, with 16GB reserved ls (hd0,1) and ls(hd0,2) shows:

```
Partition hd0,1: Filesystem type exfat - label 'Ventoy'
Partition start at 1024KiB - Total Size 125008896KiB

Partition hd0,2: No known filesystem detected -
Partition start at 125009920KiB - Total Size 32768KiB
```

Using ventoy-1.0.46-windows

**Comment by steve6375** [comment]
Partition hd0,2: No known filesystem detected

Can you see any files on partition 2???

**Comment by Armageus** [comment]
> Partition hd0,2: No known filesystem detected
> 
> Can you see any files on partition 2???

How would I check?

**Comment by ventoy** [comment]
What about reserve more space? (For example, you reserve 28GB and only give Ventoy 4GB to use)

**Comment by steve6375** [comment]
You may have a fake usb drive 
Simply look at the files on partition 2 using Linux or windows 10 system.

**Comment by Armageus** [comment]
> You may have a fake usb drive
> Simply look at the files on partition 2 using Linux or windows 10 system.

Nope definitely not fake as works fine on other systems when booted


> What about reserve more space? (For example, you reserve 28GB and only give Ventoy 4GB to use)

Just tried reserving 28GB and that boots fine (although obviously is limiting as to what payloads I can use, as <1gb usable space for isos).

I will have a bit more of a play about with it and see where the limit lies

**Comment by steve6375** [comment]
Fake 32 GB usb drives contain only 16gb, 8gb or 4gb of memory. So how do you know it's not fake? Did you test it with h2testw or fakeflashtest?

**Comment by Armageus** [comment]
> Fake 32 GB usb drives contain only 16gb, 8gb or 4gb of memory. So how do you know it's not fake? Did you test it with h2testw or fakeflashtest?

Because my 128GB usb drive does exactly the same thing. Both the 128GB and 32GB with Ventoy boot fine on other machines (UEFI or BIOS), with multiple ISO images using a significant amount of space

**Comment by steve6375** [comment]
Ok, so bios has 8gb limit. Very old?

**Comment by Armageus** [comment]
Technically the servers were end of Sale in 2013, but they are running a 2015 BIOS and were supposed to be supported until 2018.

**Comment by steve6375** [comment]
Wow, 2015 bios with 8gb usb limit! That's a new one on me!

**Comment by ventoy** [comment]
https://forums.ventoy.net/showthread.php?tid=1476
Here is a DL369 Gen9 also with 8GB limit in legacy BIOS mode.

**Comment by steve6375** [comment]
Bios does not have uefi?

**Comment by ventoy** [comment]
So this is most probably a BIOS issue. May I close this issue?

**Comment by Armageus** [comment]
> So this is most probably a BIOS issue. May I close this issue?

Yes no problem
