### ISSUE TITLE
Hiren’s BootCD PE x64 (v1.0.2) does not show all programs

### ISSUE THREAD

**Issue by hansnolte** [ventoy/Ventoy#992]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.46

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Both

### Partition Style

GPT

### Disk Capacity

64GB

### What happened?

When I run the ISO with Ventoy only a fraction of the programs are displayed.
E.G.. under the heading "Hard Disk Tools - Imaging"... only Lazesoft Disk Image & Clone v4.0.0.1 is displayed.
(Tested with LEGACY and UEFI)

When I install the ISO with RUFUS, all programs are displayed.
"Hard Disk Tools - Imaging" 
Acronis TrueImage 2021 build 39216
AOMEI Backupper v6.5.1
Lazesoft Disk Image & Clone v4.0.0.1
Macrium Reflect PE v7.3.5925
Runtime DriveImage XML v2.60

https://www.hirensbootcd.org/download/
Hiren’s BootCD PE x64 (v1.0.2)
Ventoy 1.0.46 release
WIN 10

Many greetings
Hans

**Comment by Conan179** [comment]
I have this issue too.

**Comment by steve6375** [comment]
How did you format Partition 1?  exFAT or NTFS?

**Comment by Conan179** [comment]
![vintoy_070721](https://user-images.githubusercontent.com/1906242/124751585-155bfa00-df27-11eb-9782-7c308b932a4f.JPG)
ventoy standart

**Comment by steve6375** [comment]
Try NTFS - much more compatible!

**Comment by hansnolte** [comment]
> 
> 
> Try NTFS - much more compatible!
> When booted to Hirens WinPE - can you see any files on the USB drive Partition 1?

Hi, Steve,
thank you for your answer.

I see some programs, maybe 25%.
Here is a thread (in German), apparently many feel the same way.
https://www.deskmodder.de/blog/2021/07/02/hirens-bootcd-pe-1-0-2-jetzt-mit-windows-10-21h1-als-basis-und-vielen-neuen-treibern-und-updates/#comment-183960

**Comment by steve6375** [comment]
ah, it's v1.0.2 is a new version. Ventoy should load the ISO as drive Y:, but that does not happen. :-(

**Comment by hansnolte** [comment]
> ah, it's v1.0.2 is a new version.

Sorry, I should have mentioned that.



> Ventoy should load the ISO as drive Y:,

You've gotten more out in an hour than I've gotten out in a day.

**Comment by steve6375** [comment]
Works if use E2B (Legacy) if give ISO a .isoPE01 file extension.
Also agFM v1.72g works if use .isomap or .isoPE01 file extension.
Not sure why Ventoy is not loading the ISO as drive Y: - probably not recognising the ISO as a WinPE ISO?

**Comment by hansnolte** [comment]
Hi, Steve,

thank you very much for your effort.

Unfortunately, I have no idea at all about Easy2Boot.
I'll have to read up on that.

**Comment by ventoy** [comment]
Please test with this CI release:
https://github.com/ventoy/Ventoy/actions/runs/1019159825

**Comment by hansnolte** [comment]
> Please test with this CI release:
> https://github.com/ventoy/Ventoy/actions/runs/1019159825

Fantastic!
It works perfectly.

Thanks a lot
Hans

**Comment by steve6375** [comment]
I used 1.0.46 but changed grub.cfg as shown here
https://github.com/ventoy/Ventoy/commit/fc3a5fae36f2d9f6529213196e309fcd0125f8c1
but it did not load the ISO as Y: or give full desktop???
Was there some other change?

**Comment by ventoy** [comment]
The previous commit also needed.
https://github.com/ventoy/Ventoy/commit/b3982d49300143ebc944d8ffdeb1a13292e1409a

**Comment by nguyenhathaitrong** [comment]
[https://github.com/ventoy/Ventoy/commit/b3982d49300143ebc944d8ffdeb1a13292e1409a](url)

**Comment by ventoy** [comment]
Please test with 1.0.47 and close this issue if it has been fixed, thanks.

**Comment by hansnolte** [comment]
> Please test with 1.0.47 and close this issue if it has been fixed, thanks.

Great work!
Works perfectly with 1.0.47.

Many thanks and greetings
Hans

**Comment by nguyenhathaitrong** [comment]
very good, very ok

**Comment by nguyenhathaitrong** [comment]
it worked very well

**Comment by Conan179** [comment]
I was only able to test it now, it works with me now without problems (even with exfat)
