### ISSUE TITLE
Ventoy Menu Bug in Legacy Boot

### ISSUE THREAD

**Issue by biladina** [ventoy/Ventoy#993]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.46

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

Sandisk Cruzer Blade 128GB

### Image file checksum (if applicable)

Yes.

### What happened?

I try to boot ventoy with Legacy boot, but the menu is buggy, I can't choose the ISO and when I try to choose an ISO, the menu rolling like in the video I attach..

already try to enable legacy support, enable/disable xHCI USB mode, disable secure boot..

this issue just appear in Legacy boot, when I try to UEFI, the menu is good..

the laptop that I try to boot ventoy is ASUS X200M..

https://user-images.githubusercontent.com/10651085/124910151-76fa9200-e015-11eb-893e-288358073c97.mp4

**Comment by ventoy** [comment]
Press `F7` to switch to text mode.

**Comment by ventoy** [comment]
Or press `F5--->Resolution Configuration`  to select a small resolution (e.g. 800x600)

**Comment by biladina** [comment]
> Or press `F5--->Resolution Configuration` to select a small resolution (e.g. 800x600)

with this, i just got empty list, there is no resolution list on this menu..

![IMG_Dise_20210708_192631](https://user-images.githubusercontent.com/10651085/125133318-e95f9500-e12f-11eb-9804-a2a492fe6ca7.jpg)

**Comment by biladina** [comment]
> Press `F7` to switch to text mode.

thank you, it works with this way, but I can't directly swithc to text mode because the menu still buggy and repeat itself, so I need to press another function key (F2 or F5) to switch to text mode..

**Comment by ventoy** [comment]
You can use theme plugin to set text mode as the default mode for Legacy BIOS mode.
https://www.ventoy.net/en/plugin_theme.html

```
{
    "theme_legacy": {      
        "display_mode": "CLI"
    }      
}
```

**Comment by biladina** [comment]
> You can use theme plugin to set text mode as the default mode for Legacy BIOS mode.
> https://www.ventoy.net/en/plugin_theme.html
> 
> ```
> {
>     "theme_legacy": {      
>         "display_mode": "CLI"
>     }      
> }
> ```

OK, this is good, it works with CLI, as long as I can see and choose the menu, its good..
thank you..
