### ISSUE TITLE
fedyos img launch fail

### ISSUE THREAD

**Issue by sonichy** [ventoy/Ventoy#994]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.46

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

32GB

### What happened?

A bug happened!

**Comment by ventoy** [comment]
fedyos is based on chromeos which is not supported now.

**Comment by ventoy** [comment]
Duplicate of #760
