### ISSUE TITLE
Duplicate boot entries when main data partition is reformatted.

### ISSUE THREAD

**Issue by Silexium** [ventoy/Ventoy#997]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.46

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

64GB [Kingston DT100G3]

### What happened?

Duplicate UEFI boot entries get created on each boot after the main data partition gets reformatted to NTFS. Have had this happen on 2 USB drives. I also tried deleting the duplicates using "bcdedit" & "efibootmgr" with no luck. The entries keep duplicating seemingly forever & they point to the main data partition (which is not bootable).

![20210712_021024](https://user-images.githubusercontent.com/87285693/125214397-3de14c80-e2b7-11eb-8b8d-c836302eb588.jpg)

![Screenshot 2021-07-12 021238](https://user-images.githubusercontent.com/87285693/125214408-4afe3b80-e2b7-11eb-9942-b32bd905202f.png)

**Comment by steve6375** [comment]
Do you  have an Asus z87 mainboard? Mine does the same.
It seems to be a bios bug. I get same issue with other types of uefi-bootable usb drives too, not just Ventoy.

**Comment by steve6375** [comment]
https://www.programmersought.com/article/7094577532/

**Comment by Silexium** [comment]
> Do you have an Asus z87 mainboard? Mine does the same.
> It seems to be a bios bug. I get same issue with other types of uefi-bootable usb drives too, not just Ventoy.

Nope (ASUS B85M-E with the latest BIOS version - 3602). I've also had this happen when I created a MemTest86 bootable USB. Tried different tools to create the drive with no luck (Rufus & the tool that comes with MemTest86, don't remember what it's called). The drive had like 10 duplicate entries. It was ridiculous.

**Comment by Silexium** [comment]
Is there some sort of script that can delete the duplicates by reading the "partition=F:" value & deleting all identifiers that contain it? I don't know Batch or Powershell, so help on this would be greatly appreciated. Are there other workarounds that don't involve modifying the UEFI boot entries? Ventoy should give us the option on what filesystem to choose when initially creating the drive (something like Rufus), since the default exFAT 128k configuration is ridiculous for small files (which is why I decided to reformat in the first place).

**Comment by steve6375** [comment]
There are scripts which can remove the firmware entries, however they will just come back again whenever you connect the USB drive again. The UEFI BIOS adds the entries to the **mainboard** **NVRAM** - then when you boot to Windows\WinPE it reads the UEFI NVRAM and adds the firmware entries into its BCD file.
https://www.vacuumbreather.com/index.php/blog/item/45-the-case-of-duplicate-firmware-objects-in-bcd
