### ISSUE TITLE
[issue]: Ubuntu 21.04 error : can't allocate initrd

### ISSUE THREAD

**Issue by florentlagoda** [ventoy/Ventoy#998]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.46

### What about latest release

No. I didn't try the latest release.

### BIOS Mode

UEFI Mode

### Partition Style

GPT

### Disk Capacity

128

### Image file checksum (if applicable)

Yes.

### What happened?

Hi,
With Ubuntu 21.04 have this : `error : can't allocate initrd`
My BIOS only support UEFI mode.
It's work with Ubuntu 20.04

**Comment by ventoy** [comment]
Which iso file did you test? The download link?
Also you can test it in another computer for comparison.

**Comment by florentlagoda** [comment]
Computer is Dell Latitude 3410
I download here : https://releases.ubuntu.com/21.04/
But i think provide of the new computer not supported, because i test too Ubuntu Budgie, Xubuntu and same error.
I try too other usb key with mbr and other with gui option, same problem.
It's work with Linux Mint.
If nobody have same problem i think is due to Dell Latitude 3410

**Comment by ventoy** [comment]
Did you get the same result with the same command?
![image](https://user-images.githubusercontent.com/59477474/125832906-4e0a6969-e769-4a15-b170-334f7cbcb0d7.png)

**Comment by florentlagoda** [comment]
Yes:
```
$ md5sum ubuntu-21.04-desktop-amd64.iso
736a9acaf195063600a6e1876d48a263  ubuntu-21.04-desktop-amd64.iso
```

**Comment by ventoy** [comment]
Please try as follows:
When you boot into Ventoy's main menu press `ctrl+r` and then select the ISO file to boot.

**Comment by florentlagoda** [comment]
Thanks ! It's okay on GRUB2 mode. Sorry I did not know this option switch.
I close the issue
