### ISSUE TITLE
[Bug] Ventoy can't boot some WinPE.iso files directly （【Bug】Ventoy无法直接启动某些WinPE.ISO文件）

### ISSUE THREAD

**Issue by ZhuMa12345678** [ventoy/Ventoy#999]
English (英语)
This bug has existed since version 1.0.40 and was caused by the update log "3.Fixup a bug when booting special Windows/WinPE ISO file.", and it has not been fixed until now.
The specific manifestation is that when booting some PE systems, it will always be stuck on the boot logo interface,
![20210714002735](https://user-images.githubusercontent.com/61312109/125637583-55b3ba0b-8625-4fd8-8d08-eec53d11adae.jpg)
![20210714002809](https://user-images.githubusercontent.com/61312109/125637597-6ed80ad0-dce2-4d37-9a06-02193c403c40.jpg)
and you can only boot normally by pressing F1: Memdisk mode.
![20210714005744](https://user-images.githubusercontent.com/61312109/125637619-b0c3cd58-13b4-4118-b640-e97237a8d20d.jpg)
![20210714015555](https://user-images.githubusercontent.com/61312109/125637645-e0a3d3c9-787c-4b86-81f5-67f86e8c1fd1.jpg)
After testing, this bug is a problem between .ISO and .WIM files, and has nothing to do with the operating system version and file system type. Please fix this bug.

汉语 (Chinese)
这个Bug从1.0.40版本开始就有了，是由更新日志“3.修复了一个启动特殊 WinPE 时的BUG”所产生的，到现在一直都没修复。
具体表现为启动某些PE系统时会一直卡死在开机Logo界面，
![20210714002735](https://user-images.githubusercontent.com/61312109/125637661-012a27bc-f1ee-4b72-b178-2eb08e0aa793.jpg)
![20210714002809](https://user-images.githubusercontent.com/61312109/125637672-194cfba3-a72a-4a34-8304-c41d74006cad.jpg)
只能按F1:Memdisk模式才能正常启动。
![20210714005744](https://user-images.githubusercontent.com/61312109/125637689-143c3a0d-e7b0-4285-a64c-244e08e7b11b.jpg)
![20210714021816](https://user-images.githubusercontent.com/61312109/125637697-f4939a33-e450-4d5e-bd7e-305b50649320.jpg)
经测试该Bug是.ISO和.WIM文件之间出现的问题，与操作系统版本和文件系统类型都无关，请修复这个Bug。

**Comment by ZhuMa12345678** [comment]
For Chinese users who are slow to open GitHub, click this link to view:
对于中国用户打开GitHub很慢的可点击此链接查看：
http://bbs.wuyou.net/forum.php?mod=redirect&goto=findpost&ptid=419840&pid=4334043&fromuid=566366&mobile=no

**Comment by ventoy** [comment]
这个BUG在前两天已经顺带解决了。https://github.com/ventoy/Ventoy/commit/b3982d49300143ebc944d8ffdeb1a13292e1409a

可以使用下面这个CI版本验证。
https://github.com/ventoy/Ventoy/actions/runs/1018352017

**Comment by ventoy** [comment]
请使用最新版本 1.0.47 测试。

**Comment by ventoy** [comment]
已确认问题已解决。
